### ISSUE TITLE
Key Manager's host-name and port are incorrect in the token endpoint during the token generation scenario.

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/product-apim#10036]
### Description:
When logging the Key Manager's hostname and the port of the Token endpoint during the Token API call we got the outcome as below. we are logging the host-name and the port in the Token API itself.

`INFO - LogMediator {api:_WSO2AMTokenAPI_} uri.var.portnum = 9443, uri.var.hostname = localhost`

But actual Key manager configurations: 
- **hostname:** wso2.km.server
- **port:** 9445

### Steps to reproduce:
- Configure an APIM server with a separate Key Manager.
- Add a log mediator in the **_Token_API.xml** in order to log the Key Manager hostname and port.
- Perform the Token API call.
- Observe the logged hostname and port number.

### Affected Product Version:
APIM 3.2.0

**Comment by dushansilva** [comment]
closing issue since this can be solved with a config
