### ISSUE TITLE
Search functionality in the Subscriptions tab of the Applications section in Dev portal is not working as expected

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#10035]
### Description:
When trying to search APIs to subscribe via devportal in the Subscriptions tab of the Applications section, we need to put the actual complete name of the API in order to get the search result.  If we provide the part of the API name, the searching process is not working as expected which means the result set is not visible for the partial string.

### Steps to reproduce:
1. Add some APIs via publisher portal
2. Visit the Subscriptions tab of the Applications section in devportal
3. Click on **SUBSCRIBE APIS** plus signed button
4. Try to search an API with a partial string of the API. You will get no APIs available.

### Affected Product Version:
APIM 3.2.0

**Comment by npamudika** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/10000
