### ISSUE TITLE
TryIt Console breaks in devportal if the API revision has not been deployed.

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-apim#10040]
### Describe your problem(s)
With the introduction of vhost concept, if the a revision has not been deployed with a proper vhosts, the tryIt console breaks in the devportal. 
This happens because the endpoint URLs for the API are not defined in the getAPIbyID backend response.

<img width="1649" alt="Screen Shot 2021-03-01 at 3 41 13 PM" src="https://user-images.githubusercontent.com/22365810/109493264-3bbde480-7ab2-11eb-9081-781f69d13d6f.png">

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/10002 
hence closing the issue
