### ISSUE TITLE
UI Error shows when creating sample Pizzashack API in Publisher UI

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10043]
### Description:
The following UI Error shows when creating sample Pizzashack API in Publisher UI by a user with only **_creator_** permissions

![Pizzashack-error](https://user-images.githubusercontent.com/6614042/109494715-411c2e80-7ab4-11eb-8a3c-77e3797f642f.png)

This seems to be caused by the fact that only publisher users are able to deploy revisions. This causes the deployment of the Pizzashack API to fail.

It would be better if we could check the user permission before attempting to create/deploy a revision of the sample API.

### Steps to reproduce:
1. Login to the publisher UI with a user who only has **creator** permissions
2. Click on the deploy sample API link in the home page.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Seems this is fixed in the master branch.
![create_api_by_creator](https://user-images.githubusercontent.com/1591316/111207015-24711200-85ef-11eb-9605-700e28b097d2.gif)
