### ISSUE TITLE
Application name is not visible under the "Manage Subscriptions" section in the Publisher Portal

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#10049]
### Description:
The application name cannot be seen in the **Manage Subscriptions** section of an API in the Publisher Portal.

### Steps to reproduce:
1. Create an API from the Publisher Portal.
2. Subscribe to it using an Application.
3. Go to the **Subscriptions** tab in the Publisher Portal that belongs to the particular API.
4. The application name will not be displayed under the **Manage Subscriptions** section.
    ![image](https://user-images.githubusercontent.com/25246848/109591484-99464580-7b33-11eb-8550-8b73e8113e49.png)

### Affected Product Version:
APIM 4.0.0-alpha

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS
- Web browser: Chrome

**Comment by Krishanx92** [comment]
Fix https://github.com/wso2/carbon-apimgt/pull/9936

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/10130
