### ISSUE TITLE
Devportal API overview page Endpoint field obscures data

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10055]
### Description:
When looking at an APIs overview page in the Dev portal there are several alignment and styling issues as shown in the screenshot below

![image](https://user-images.githubusercontent.com/6614042/109599201-cfd68d00-7b40-11eb-9301-0a7fdbf6b684.png)

### Critical issue:

- The value of the endpoint field is overlapping the Business Owners name and email. 
![image](https://user-images.githubusercontent.com/6614042/109599523-5ab78780-7b41-11eb-9065-468f661096e6.png)

### Minor issue:

- Icons for Context, Version, Key Managers, Tags are displayed between these labels and the respective value label as shown below
![image](https://user-images.githubusercontent.com/6614042/109600551-4d030180-7b43-11eb-9e1e-1a5f820a4b89.png)
This seems a bit strange to look at and it maybe better if we could align the icon with the top labels

**Comment by tmkasun** [comment]
These issues will be addressed/resolved after implementing the new developer portal overview design 
![image](https://user-images.githubusercontent.com/3313885/111431405-c1cc6300-8721-11eb-9836-9458d1358d4a.png)
Design [XD](https://xd.adobe.com/view/67c2ddac-11d7-4ebc-8f34-2544f4d01770-3291/screen/ddcb358d-fbb3-4fd3-9b5c-2729eb6345b9)

hence closing this issue
