### ISSUE TITLE
Error Occurring when Executing 3.2.0 to 4.0.0 MSSQL Database Migration Script

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10052]
### Description:
When executing the 3.2.0 to 4.0.0 MSSQL database migration script [1] from the terminal, the following error is encountered.
```
Msg 1779, Level 16, State 1, Server dca5a503261b, Line 28
Table 'AM_API_CLIENT_CERTIFICATE' already has a primary key defined on it.
Msg 1750, Level 16, State 1, Server dca5a503261b, Line 28
Could not create constraint or index. See previous errors.
``` 
[1] https://github.com/wso2-extensions/apim-migration-resources/blob/master/migration-scripts/migration-3.2.0_to_4.0.0/mssql.sql

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS
- Client: Ubuntu Terminal
- Database docker image: microsoft/mssql-server-linux 2017-latest

**Comment by CrowleyRajapakse** [comment]
Need to add following steps in the migration docs, after running the mssql scripts.

1.) Get the indexes of the AM_API_CLIENT_CERTIFICATE table;

EXEC sp_helpindex 'AM_API_CLIENT_CERTIFICATE'

2. ) Use the index name and remove the primary key contraint

ALTER TABLE AM_API_CLIENT_CERTIFICATE
DROP CONSTRAINT [index name]

3.) Add new primary key

ALTER TABLE AM_API_CLIENT_CERTIFICATE ADD PRIMARY KEY(ALIAS,TENANT_ID, REMOVED, REVISION_UUID);

**Comment by isharac** [comment]
Fixed. Need to update the doc accordingly.

**Comment by isharac** [comment]
Fixed in the mssql.sql script in the migration client with https://github.com/wso2-extensions/apim-migration-resources/pull/81
Hence doc update is not required.
