### ISSUE TITLE
Monetization page  throws an error

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#10059]
### Steps to reproduce:
Select Monetization

<img width="872" alt="Screenshot 2021-03-02 at 1 21 59 PM" src="https://user-images.githubusercontent.com/4861150/109615931-88f59100-7b5a-11eb-9a10-6eb995e6472b.png">

pack : 4.0.0-alpha

**Comment by malinthaprasan** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10107
