### ISSUE TITLE
Language files are not consistent in dev portal

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-apim#10058]
### Description:
Default language json files (es, si, ar) are inconsistent on the devportal and publisher. Need to add correct translations for each file.

**Comment by tmkasun** [comment]
We can't do the translation, Those additional, si, es, etc are only for reference, and we will remove those additional empty locale files. Those are not very useful IMO

**Comment by malinthaprasan** [comment]
Reduced the priority as per above comment.
