### ISSUE TITLE
[API-M 4.0.0][Priority/HIGH]Error When trying to Add Scope Mappings in Admin Portal

### ISSUE THREAD

**Issue by Dulangi-anuththara** [wso2/product-apim#10063]
#### Steps to reproduce:
1. Log in to Admin Portal and Go to Scope assignments in settings to add new scope mapping
![Screenshot from 2021-03-02 11-42-43](https://user-images.githubusercontent.com/40545407/109606387-9d329180-7b4c-11eb-9207-8200b5baec60.png)

2.  Click next to select permissions
![Screenshot from 2021-03-02 13-07-06](https://user-images.githubusercontent.com/40545407/109614135-3a46f780-7b58-11eb-8042-4606b5b3da05.png)

### Affected Product Version:

APIM 4.0.0-alpha

### Environment details (with versions):
- OS: Ubuntu 20.04
API-M 4.0.0

**Comment by malinthaprasan** [comment]
![image](https://user-images.githubusercontent.com/1591316/111205730-8fb9e480-85ed-11eb-804a-137435d49ba8.png)

App scope mappings is now changed from store -> devportal.

![image](https://user-images.githubusercontent.com/1591316/111205829-ac561c80-85ed-11eb-9023-2ed5857b361b.png)
