### ISSUE TITLE
APIM scopes does not authenticate users

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-apim#10064]
### Description:
Scopes get authorized for all the request even with a token that has not belong to the given scope.

### Steps to reproduce:
Create a new Role from the carbon console.
Create new shared scope with the role created.
Create a REST API with a mock backend that responds with some JSON. Add created scope to the API for any method.
Create another role and user.
Generate a token from the new user and invoke the API. API gets authenticated and receives the response.

### Affected Product Version:
APIM 4 alpha

**Comment by malinthaprasan** [comment]
This is not reproducible in the latest pack.
After adding the scope make sure you created a revision and deploy before invoking.
