### ISSUE TITLE
Account lock doesn't send the email notification

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10066]
### Description:
APIM does not send the account lock email notification when the account is locked after number of failed attempts is reached the maximum number. But when the admin user manually unlock the account that notification is received.

### Steps to reproduce:

Follow https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking

### Affected Product Version:

APIM 4.0.0  Alpha

**Comment by rmsamitha** [comment]
This is not reproducible in the latest pack on carbon component version 9.0.133. Account locking notification is received after exceeding the count of failed attempts.
