### ISSUE TITLE
Enable social sharing for apis make the UI cluttered

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10069]
### Description:
After enabling the social feature the devportal api view gets cluttered.
<img width="1149" alt="Screen Shot 2021-03-02 at 1 53 06 PM" src="https://user-images.githubusercontent.com/3424539/109633060-b3047e80-7b6d-11eb-8124-d53a8b1d50ad.png">

### Steps to reproduce:
Enable social sharing by enabling it via the following config.

```
 custom: {
        social: {
            showSharing: {
                active: true,
            }
       }
}
```
The spacing and alignments need fixing to go with the new design.

**Comment by tmkasun** [comment]
@erangatl 
I think we need to update the design to show social buttons and developer engagement links (Github & Slack URLs) when they are available or enabled
![image](https://user-images.githubusercontent.com/3313885/111752887-3cc98100-88bc-11eb-9d73-b083bb3a46ec.png)
https://xd.adobe.com/view/67c2ddac-11d7-4ebc-8f34-2544f4d01770-3291/screen/fae73d72-916c-4beb-bef0-390baea59f4c/

**Comment by tmkasun** [comment]
Fixed in master hence closing the issue

**Comment by erangatl** [comment]
https://xd.adobe.com/view/67c2ddac-11d7-4ebc-8f34-2544f4d01770-3291/screen/fae73d72-916c-4beb-bef0-390baea59f4c
![image](https://user-images.githubusercontent.com/20179540/114251783-f4374c00-99bf-11eb-993a-5168ebe43cc8.png)
