### ISSUE TITLE
Remove support for labelName query param in /apis/{apiId}/swagger devportal endpoint

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#10076]
### Description:
Need to remove support for [1].

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/resources/devportal-api.yaml#L244

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by renuka-fernando** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/10010
related issue: https://github.com/wso2/product-apim/issues/10253
