### ISSUE TITLE
GraphQL Schema Definition is not displayed as expected

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10078]
### Description:
GraphQL Schema Definition is not displayed as expected. Schema definition panel is not aligned correctly and there are black lines in the top and bottom.

![chrome-capture (1)](https://user-images.githubusercontent.com/32265029/109641425-8a956980-7b06-11eb-8f49-c67b39386bbf.gif)

### Steps to reproduce:

1. Import a GraphQL SDL
2. Click Schema Definition under API configuration

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by TheRasanjana** [comment]
The same behavior is observed in API Definition page as well.
<img width="1643" alt="Screen Shot 2021-03-03 at 6 26 43 PM" src="https://user-images.githubusercontent.com/32265029/109809190-0948ee80-7c4e-11eb-9c8b-8bc3d20fefc6.png">

**Comment by msm1992** [comment]
API Definition > Edit view is also not displayed as expected.
<img width="1788" alt="Screenshot 2021-03-04 at 17 26 27" src="https://user-images.githubusercontent.com/28379317/109961029-76708880-7d0f-11eb-8322-028cc440455c.png">

**Comment by malinthaprasan** [comment]
This can be most probably fixed by https://github.com/wso2/product-apim/issues/10156#issuecomment-799209452

**Comment by kavishkafernando** [comment]
This issue has been fixed with https://github.com/wso2/product-apim/issues/10156#issuecomment-799209452 hence closing the issue
