### ISSUE TITLE
Publisher basic theming configuration unused parameters

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10072]
### Description:
Changing the following is not making any difference. We need to either remove this or fix it.
```
title: { 
          prefix: '[Publisher]',
          sufix: '- WSO2 APIM',
},
```

Following configs are never used. We can remove it.

```
showApiHelp: false,
starColor: '#f2c73a'
```

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/10005 hence closing the issue
