### ISSUE TITLE
Application ownership change is not working

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10081]
### Description:
Followed the following doc to change the ownership of an application.

https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/#changing-the-owner-of-an-application

### Steps to reproduce.

Create two users and assign them subscriber role ( cat, dog).
Add both of them to the same organization.
Login to devportal with cat's credentials.
Create an application.
Logout and login again with dog's credentials.
Now login to the admin console and try to change the ownership from cat to the dog. "Something went wrong while updating owner" message comes.

**Comment by malinthaprasan** [comment]
@YasasRangika is checking this
