### ISSUE TITLE
UX issues in API Publisher Landing Page

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#10089]
Following UX issues have been identified in the Publisher Landing page.

- Many fonts have been used and it does not look nice
- Usage of font sizes are inconsistent
- There should be a gap between the API type icon and the type name
- The description is too lengthy and not eye-catching
- The options under each API type are not highlighted
- Sample should be highlighted

**Comment by tmkasun** [comment]
Thanks for the comment,
We have updated the design of the landing page incorporating the feedback we received,

![image](https://user-images.githubusercontent.com/3313885/109941555-4a4a0d00-7cf9-11eb-9e62-ebe7b6b42405.png)

XD: [Link](https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/)

please review, we will do the changes according to this design

**Comment by tmkasun** [comment]
We have fixed the issues raised here in this PR https://github.com/wso2/carbon-apimgt/pull/10009

![image](https://user-images.githubusercontent.com/3313885/111192901-97728c80-85df-11eb-8a54-62f56eee3491.png)

hence closing this issue
