### ISSUE TITLE
[Devportal] Custom URL feature is broken

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10093]
### Description:
After setting up custom URL and load the custom URL, the Devportal UI keeps loading with the following errors.

<img width="1437" alt="Screen Shot 2021-03-03 at 11 52 05 AM" src="https://user-images.githubusercontent.com/3424539/109762758-244c3c00-7c17-11eb-8164-96bd39237faa.png">

### Steps to reproduce:
Add the following config to usr/local/etc/ngix/nginx.conf and restart nginx

```
#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
       listen 443;
       ssl on;
       server_name "developer.abc.com";
       ssl_certificate /etc/nginx/ssl/nginx.crt;
       ssl_certificate_key /etc/nginx/ssl/nginx.key;
       location /{
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;
               proxy_pass https://localhost:9443/devportal/;
               proxy_redirect https://localhost:9443/devportal/ /;
               proxy_set_header X-WSO2-Tenant "abc.com";

       }
       location /api/am/store/v1{
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;
               proxy_pass https://localhost:9443;
               proxy_set_header X-WSO2-Tenant "abc.com";
       }
      
    }


    upstream sslapi.am.wso2.com {
    server localhost:9443;
}


 
server {
    listen 443;
    server_name api.am.wso2.com;
    proxy_set_header X-Forwarded-Port 443;
    ssl on;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/apim.key;
    location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;
               proxy_pass https://sslapi.am.wso2.com;
        }
 
        # access_log /usr/local/etc/nginx/log/am/https/access.log;
        # error_log /usr/local/etc/nginx/log/am/https/error.log;
}


    include servers/*;
}

```

2. Copy the attached SSL certs to /etc/nginx/ssl/ folder. [certs.zip](https://github.com/wso2/product-apim/files/6074038/certs.zip)

3. etc/hosts entries

127.0.0.1 developer.abc.com
127.0.0.1 api.am.wso2.com

4. Add the following entries to deployment.toml

[server]
hostname = "api.am.wso2.com"

and

[transport.https.properties]
proxyPort = 443

5. Create a tenant domain
abc.com

6. log in to the carbon console from "admin@abc.com" and add the following to the 
/_system/config/apimgt/applicationdata/tenant-conf.json

```
"EnablePerTenantServiceProviderCreation" : true,
```

7. Login to the carbon console from super admin and add the following file.

`/_system/governance/customurl/api-cloud/abc.com/urlMapping/abc.com`

```
{
        "tenantDomain": "abc.com",
        "store" : {
            "customUrl" : "developer.abc.com"
        },
        "gateway" : {
            "customUrl" : "<custom domain for gateway>"
        }
}
```

Now try to access https://developer.abc.com

**Comment by malinthaprasan** [comment]
change this `location /api/am/store/v1{`  to  `location /api/am/devportal/v2{`

**Comment by malinthaprasan** [comment]
If above suggestion works please transfer to doc issue.

**Comment by chanaka3d** [comment]
@malinthaprasan suggestion fixed the issue.

The following doc needs to be updated with the change.
https://apim.docs.wso2.com/en/latest/develop/customizations/customize-the-api-store-and-gateway-urls-for-tenants/#configure-per-tenant-custom-domain-mappings
