### ISSUE TITLE
Try out page in DevPortal goes black and empty for Graphql APIs

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10096]
### Description:
This behaviour is observed in Windows.
![chrome-capture (2)](https://user-images.githubusercontent.com/32265029/109767785-eca8aa00-7bac-11eb-82d9-3378d52a9530.gif)

### Steps to reproduce:

1. Create a Graphql API 
2. Publish API
3. Go to Dev Portal
4. Select the API
5. Click **Try Out**

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows 2019 server
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by malinthaprasan** [comment]
Related https://github.com/wso2/product-apim/issues/10274.
Is it possible to check if the issue happens because the API doesn't have any deployments like the above issue?

**Comment by malinthaprasan** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10339
