### ISSUE TITLE
Error when creating a new API from scratch by a user with Creator only permission

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10098]
### Description:
Below error popup is displayed in Publisher UI when a user with Creator only permissions creates an API from scratch at the point of clicking on the CREATE button.
![image](https://user-images.githubusercontent.com/6614042/109771222-91190380-7c22-11eb-88cd-17d00519a78e.png)

The browser console shows the following two calls being made to the revision rest API
![image](https://user-images.githubusercontent.com/6614042/109769568-675edd00-7c20-11eb-9cf6-7c430c408831.png)

![image](https://user-images.githubusercontent.com/6614042/109769678-8a898c80-7c20-11eb-83fe-03f6a360dc13.png)

Since the revision REST API resources require Publisher permissions these calls fail with 401 being returned.

### Steps to reproduce:
1. Login to the Publisher UI with a user who only has Creator permissions.
2. Fill in the fields required for a new REST API from scratch and click on the "CREATE" button

**Comment by CrowleyRajapakse** [comment]
https://github.com/wso2/carbon-apimgt/pull/9942

**Comment by CrowleyRajapakse** [comment]
Fixed in the latest, please reopen if recurring
