### ISSUE TITLE
Monetization page displaying error

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10107]
### Description:
When the user navigates to the Monetization page in the Publisher portal, an error is displayed.

<img width="1215" alt="Screen Shot 2021-03-03 at 9 27 26 PM" src="https://user-images.githubusercontent.com/32265029/109833790-90ef2700-7c67-11eb-9b1a-84b9d3c431e3.png">

### Steps to reproduce:

1. Create an API and publish
2. Go to the API created
3. Click Monetization

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by malinthaprasan** [comment]
Not reproduced in latest pack
