### ISSUE TITLE
[3.2.0] OAuth2 Endpoint Security Configurations are Missing When SecureVault Enabled

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#10104]
### Description:

The OAuth2 Protected BE endpoint configurations are missing in the API Synapse artifacts when the Secure Vault configurations are enabled. 

From the Publisher portal, it is possible to add OAuth2 (Client Credentials/Password) Endpoint security to the Production and Sandbox endpoints [[Doc]](https://apim.docs.wso2.com/en/latest/learn/design-api/endpoints/endpoint-security/oauth-2.0/). But, when having the APIM configured with Secure Vault, the respective XML configurations and properties (including the OAuth Mediator) are missing in the API Synapse. Please find the steps to reproduce below.

### Steps to reproduce:

- Configure the API Manager v3.2.0 with Secure Vault. Add the following configuration in the deployment.toml to enable the Secure Vault
  
  ```toml
  [apim]
  enable_secure_vault = true
  ```  
- Execute the `Ciphertool` script to prepare the API Manager. Run the following command from the `<apim>/bin` directory
  
  ```sh
  ./ciphertool.sh -Dconfigure
  ```
- Once executed, start the API Manager and login to the Publisher portal
- Publish an API and navigate to Endpoints and add a Digest or OAuth2 configurations for Production Endpoints
- Save and Publish the API
- Open the respective API Synapse from `<apim>/repository/deployment/server/synapse-configs/default/api` directory and view the artifact (will be missing the OAuth Mediator or Digest authentication related configurations there)

### Affected Product Version:

- APIM 3.2.0

**Comment by RakhithaRR** [comment]
This is already fixed in master
