### ISSUE TITLE
"Revision 1" is displayed as already "Deployed" when the Default API is created only

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#10102]
### Description:

"Revision 1" is displayed as already "Deployed" when the Default Pizzashack API is created only.

### Steps to reproduce:
1. Go to Publisher
2. Deploy sample API
When checked the LC state of the API in Lifecycles tab, it is displayed as "Created". But Lifecycle history list has an event as "LC has changed from CREATED to PUBLISHED" 
![image](https://user-images.githubusercontent.com/2484781/109799041-85890500-7c41-11eb-8c9f-fd80473e11f9.png)

This is critical as the default API is used by many and it should behave correctly.

### Affected Product Version:
APIM-4.0.0-Alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by CrowleyRajapakse** [comment]
As per the feature implementation we are supporting deploying revisions in API created state. For lifecycle issue, that seems to be fixed in the latest pack, should be able to verify and close the issue.

**Comment by rmsamitha** [comment]
Doesn't reproduced in the latest pack. Hence closing.
