### ISSUE TITLE
[Publisher] test console does not render properly

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10103]
### Description:
<img width="639" alt="Screen Shot 2021-03-03 at 6 58 18 PM" src="https://user-images.githubusercontent.com/3424539/109813216-0c92a900-7c53-11eb-972c-daedd3cabb3c.png">

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/10009
