### ISSUE TITLE
An Error message displayed when logged with user with creator role.

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10109]
### Description:
When a user with a creator role is logged in and goes to an API created by the admin in Publisher, an error response message is displayed.
<img width="1680" alt="Screen Shot 2021-03-03 at 10 14 51 PM" src="https://user-images.githubusercontent.com/32265029/109843243-debc5d00-7c70-11eb-9af6-1d6b1a6ec6a8.png">

### Steps to reproduce:

- Login with super admin and create an API
- Create a user with a creator role
- Login with new user
- Click on the API created by Super admin

### Affected Product Version:
- v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by CrowleyRajapakse** [comment]
https://github.com/wso2/carbon-apimgt/pull/9942

**Comment by CrowleyRajapakse** [comment]
Fixed in the latest, please reopen if recurring
