### ISSUE TITLE
Load the Existing Roles to a dropdown list

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10108]
### Describe your problem(s)
The user needs to type the roles here, under Design Configurations, these are case-sensitive as well.

<img width="1012" alt="Screen Shot 2021-03-03 at 10 18 31 PM" src="https://user-images.githubusercontent.com/32265029/109841183-cf3c1480-7c6e-11eb-8296-62c1585334ae.png">

### Describe your solution
Load the existing roles in to a dropdown list so user can easily select the desired roles.

**Comment by vithu30** [comment]
IIRC we discussed the same earlier as well. But we can't list all available roles as it can lead to security issues.

@malinthaprasan , @tmkasun WDYT?

**Comment by malinthaprasan** [comment]
Yes we should not show all roles in the system to users other than admins.
This also gets complicated when there are multiple userstores too.
