### ISSUE TITLE
Can not see Test Console button unless API is in Created stage

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10116]
### Description:
Test Console button is only visible if the API is in the CREATED stage. The user will not be aware if there is such an option if he is straight away publishing the API when creating.  
<img width="1456" alt="Screen Shot 2021-03-04 at 12 50 36 PM" src="https://user-images.githubusercontent.com/32265029/109925845-42ce3800-7ce8-11eb-8669-57c2e0ee8fa3.png">

However, the documentation contains a screenshot of the published API and its Test Console. We will need to emphasize the fact Test console is only available for CREATED apis.
<img width="1176" alt="Screen Shot 2021-03-04 at 12 52 07 PM" src="https://user-images.githubusercontent.com/32265029/109926228-bc662600-7ce8-11eb-8d1c-ee9428ca6c43.png">

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10049
