### ISSUE TITLE
Cannot block all subscriptions for the API with the application name contain hyphen (-)

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#10117]
### Description:
Cannot block all subscriptions for the API from the application that contains hyphen in the application name.

### Steps to reproduce:

1. Create an application with hyphen.
2. Subscribe to an API
3. Go to the publisher and click on BLOCK ALL.

### Affected Product Version:
3.1.0

**Comment by prasa7** [comment]
Master branch do not need this change due to this change https://github.com/wso2/carbon-apimgt/pull/10585
