### ISSUE TITLE
Issue in invoking migrated APIs using old access token

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#10119]
### Description:

we can't use old token to invoke migrated APIs, in both super and tenants, if we resubscribe can invoke relevant APIs in both super and tenants.
Following error comes when we try to invoke API

`{
  "fault": {
    "code": 900908,
    "message": "Resource forbidden ",
    "description": "User is NOT authorized to access the Resource. API Subscription validation failed."
  }
}`

Might need to perform Cross tenant API subscription fix to migration client

### Steps to reproduce:

Tested during migration from APIM 3.2 to APIM 4.0(Oracle)

**Comment by isharac** [comment]
Fixed in the latest version.
