### ISSUE TITLE
Custom Properties are not displayed

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10111]
### Description:
Custom Properties added in the publisher can not be seen.
I added two properties one ticked to be visible in dev portal. I was unable to see the property in dev portal. 
<img width="1456" alt="Screen Shot 2021-03-03 at 11 11 26 PM" src="https://user-images.githubusercontent.com/32265029/109848919-ce0ee580-7c76-11eb-8711-73f36015f720.png">
<img width="1456" alt="Screen Shot 2021-03-03 at 11 12 47 PM" src="https://user-images.githubusercontent.com/32265029/109848943-d2d39980-7c76-11eb-8cf3-7f3fc5e55a45.png">

### Steps to reproduce:

1. Create an API
2. Add a custom property
3. Go to Dev portal
4. Go to API's overview page.

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by malinthaprasan** [comment]
Also additional properties coming from the devportal API is 
additionalProperties: {<name>__display: "<value>"}.
We should remove these additional __display parts.
