### ISSUE TITLE
UI Issue when viewing resources of SOAP to REST API

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#10114]
### Description:
Following UI issue occurred when viewing the resources of REST API created from a SOAP service.

![image](https://user-images.githubusercontent.com/19728269/109916987-92a60280-7cda-11eb-9952-a9479a567879.png)

### Steps to reproduce:

- Create a REST API using a WSDL file
- Navigate to Resources tab.

**Comment by vithu30** [comment]
Scrolling the generated sequence is also not working properly

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/10009


![Publisher-WSO2-APIM](https://user-images.githubusercontent.com/3313885/111428958-43ba8d00-871e-11eb-85da-6b572b846f19.gif)
