### ISSUE TITLE
Applications are not displayed in Manage Subscriptions section of API

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10130]
### Description:
Application names are empty in the Manage Subscriptions section of the API
<img width="1418" alt="Screen Shot 2021-03-04 at 7 58 44 PM" src="https://user-images.githubusercontent.com/32265029/109978926-5eefca80-7d24-11eb-914a-448026adc557.png">

### Steps to reproduce:
1. Create an API in Publisher and publish
2. Go to Dev portal and create an application and subscribe the API
3. Go to Publisher and click on the API created
4. Go to the Subscription page.

Why have we put these info icons under subscriber? Can we put the subscriber name instead?
<img width="1418" alt="Screen Shot 2021-03-04 at 7 58 44 PM" src="https://user-images.githubusercontent.com/32265029/109980046-85623580-7d25-11eb-88c2-e31c10321327.png">

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by malinthaprasan** [comment]
First issue is not reproducible for me.

![image](https://user-images.githubusercontent.com/1591316/111193616-58910680-85e0-11eb-8c76-7ec81aad0a64.png)

For the latter one, +1 add the name of the subscriber along with the Info icon. Info Icon shows additional details of the user profile.

**Comment by sahan29** [comment]
@malinthaprasan FYI I have executed this test in Windows. Maybe that's why this wasn’t reproducible

**Comment by Krishanx92** [comment]
> First issue is not reproducible for me.
It's already fixed :) 

https://github.com/wso2/product-apim/issues/10049

> 
> ![image](https://user-images.githubusercontent.com/1591316/111193616-58910680-85e0-11eb-8c76-7ec81aad0a64.png)
> 
> For the latter one, +1 add the name of the subscriber along with the Info icon. Info Icon shows additional details of the user profile.

**Comment by Krishanx92** [comment]
The first issue already fixed :) . Let's keep this open until fixing the latter part.
