### ISSUE TITLE
JSON Schema validation for API calls not working as expected

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-apim#10149]
Tried sending a request to an API with a request body containing an extra key-value pair and an invalid datatype for a key. The tryout menu returns '500: undocumented error' and the cURL command returns nothing.

**Comment by pubudu538** [comment]
It looks like schema validation does not happen as we don't build the message. Basically, it skips the schema validation.

**Comment by RakhithaRR** [comment]
This seems to be working in the latest pack.
