### ISSUE TITLE
Improvement in Add Gateway Environment page

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10148]
### Describe your problem(s)

The Admin Portal UI in the "Add Gateway Environment page" states "HTTP Context" as the caption of the textbox and the info text. However, this context is applicable to HTTP and HTTPS as confirmed by @pubudu538  and @renuka-fernando. Therefore, the UI text caption should change to "**HTTP(S) Context**". Otherwise, it will mislead the user. @uvindra , too confirmed this requirement. 

<img width="603" alt="Screenshot 2021-03-05 at 11 49 49" src="https://user-images.githubusercontent.com/5195851/110075655-23e3aa80-7da9-11eb-9550-e7d9a0e3d9cf.png">

**Comment by uvindra** [comment]
Currently with the way the UI is laid out it is not obvious that the http context will not be applied WS/WSS connections. Its would be better from a UX perspective to have a separation between the http context and the WS/WSS port fields, to show that it does not apply to them.

Also as @pubudu538 suggested, it would be good if we could have a preview of what each connection URL would look like once the relevant fields have been filled. This to help the publisher to get an idea of what the invocation URL will look like
