### ISSUE TITLE
Devportal API to get all subscriptions response does not contains pagination parameters

### ISSUE THREAD

**Issue by WickramBug** [wso2/product-apim#10140]
### Description:
When we use DevPortal REST API in order to list the subscribed application for the given API, the pagination value always returns null in the response body.
![pagination_null](https://user-images.githubusercontent.com/19631078/110066789-4a4d1a00-7d98-11eb-97fc-dee630f9d12d.png)

### Steps to reproduce:
1. Create a REST API via Publisher Portal.
2. Create multiple applications and subscribe to the created API in step 1 via Dev Portal.
3. Send a GET request to retrieve subscription details in PostMan or any REST API invoking clients.
`https://127.0.0.1:9443/api/am/store/v1/subscriptions?apiId=<created_apiId>&limit=5`
4. Observe that the pagination parameters are returned with null.

### Affected Product Version:
APIM 3.1.0

**Comment by lathlk** [comment]
The same issue can be observed when querying using the applicationId.

Steps to reproduce: 
1. Create a REST API via Publisher Portal.
2. Create multiple applications and subscribe to the created API in step 1 via Dev Portal.
3. Send a GET request to retrieve subscription details in PostMan or any REST API invoking clients.
`https://127.0.0.1:9443/api/am/store/v1/subscriptions?applicationId=<created_application_id>&limit=5`
4. Observe that the pagination parameters are returned with null.
<img width="942" alt="Screenshot 2021-04-07 at 10 12 27" src="https://user-images.githubusercontent.com/20392682/113815581-07180980-9791-11eb-8876-8254b08eb33e.png">
