### ISSUE TITLE
Multiple versions of API is shown in devPortal

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10145]
### Description:
By default, DevPortal is supposed to show only the latest version of the API.
<img width="1111" alt="Screen Shot 2021-03-05 at 10 48 29 AM" src="https://user-images.githubusercontent.com/32265029/110070678-7f5d6a80-7da0-11eb-8fa5-48599ae58fc4.png">
and by default the deployment.toml file contains following value,
#display_multiple_versions = false

### Steps to reproduce:

1. Create and publish an API
2. Go to the API and click Create new Version
3. Give the new version and click create
4. Publish the new version of API
5. Go to Dev Portal

### Affected Product Version:
v4.0.0-alpha

### Environment details (with versions):
- OS: Windows server 2019
- Browser : Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by malinthaprasan** [comment]
This is fixed in the latest.
