### ISSUE TITLE
When we enable the JWTTokenIssuer, we cannot  generate the JWT token with the given validity period(exp value is static one)

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#10159]
### Description:
When we are having the following configurations in deployment.toml file, to use the org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer to generate JWT tokens with the specific validity period(larger than the default value in the service provider configs) via the APIM dev portal, the exp value in the generated token is showing a value of the default value configured in the service provider configurations. It is not showing the inputted validity period.
```
[oauth.extensions]
token_generator = "org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer"
```
For example, when we have the Application Access Token Expiry Time as 3600 in service provider configurations in the management console, if we generate the token with the validity period 14400s, then in the database we can see the correct jti entry with 14400s validity period.
But, when we decoded the JWT token and checked the exp value of the JWT that is showing 3600s.

Further, when we have validated the above-generated token against introspect endpoint, the result shows the correct exp value with 14400s.

### Steps to reproduce:
1. Add the following configs in the deployment.toml file
2. Generate the token via devportal with the 7200s
3. Decode the token and check the exp value that will show as 3600s.

### Affected Product Version:
APIM 3.0.0 and APIM 3.1.0

**Comment by npamudika** [comment]
This is fixed in the APIM 3.1.0 version with a WUM update. Not adding the fixes to the public branch as the fixes are N/A (feature is removed from APIM 3.2.0 version onwards).
