### ISSUE TITLE
API Definition (Swagger) page is not aligned

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10156]
### Description:
The API definition page is not aligned.

<img width="1653" alt="Screen Shot 2021-03-05 at 4 12 38 PM" src="https://user-images.githubusercontent.com/6702569/110104845-ad0cd880-7dcd-11eb-9fa1-8575c0e5c391.png">

### Steps to reproduce:
1. create an API.
2. Go to API Definition tab

### Affected Product Version:
APIM 4 - Alpha 

### Environment details (with versions):
- OS: MacOS
- Client:
- Env (Docker/K8s):

---

**Comment by arunans23** [comment]
Same issue is observed for Async API definition as well.

<img width="1678" alt="Screenshot 2021-03-05 at 23 09 52" src="https://user-images.githubusercontent.com/17047910/110152823-3a6d1e80-7e08-11eb-9e4f-ea95a3cbc938.png">

**Comment by tmkasun** [comment]
This will be fixed with this PR
https://github.com/wso2/carbon-apimgt/pull/10009
