### ISSUE TITLE
Unable to view publisher API deployment page after migration

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#10151]
### Description:
Tested during APIM 2.2 to 4.0 mssql migration. Migration client(latest including Vhost fix) executed without any issues and API also seems to be deployed successfully. Able to invoke the API. but when try to view deployments page of the API following error comes.

<img width="1654" alt="Screenshot 2021-03-05 at 13 34 37" src="https://user-images.githubusercontent.com/23296184/110086486-6e205800-7db8-11eb-9e81-e6ec7d840e44.png">

No issues in viewing/invoking API in devportal

<img width="1651" alt="Screenshot 2021-03-05 at 13 36 12" src="https://user-images.githubusercontent.com/23296184/110086679-acb61280-7db8-11eb-8cd9-2acc1cff3def.png">

Migration logs: https://notepad.pw/216sf2uh

### Steps to reproduce:
APIM 2.2 to 4.0 mssql migration

### Affected Product Version:
Tested with carbon-apimgt : 9.0.26-SNAPSHOT

**Comment by CrowleyRajapakse** [comment]
This might be due to migrateFrom320.migrateLabelsToVhosts(); method is only added to the 3.2 to 4.0 section, this method is not getting executed when running 2.2 to 4.0 migration, hence newly added logic to the common deploying dynamic environments path might be missing above method impl in 2.2 to 4.0 run. 
Also will need to add above method to all relevant sections where label feature is present
ex; 3.1 to 4.0, 3.0 to 4.0 up until this label feature introduced and will need to check the behaviour of the old ones as well

**Comment by renuka-fernando** [comment]
In the migration we are setting vhost as NULL, and in the Rest API we should get the default vhost of the environment and returns with the response
