### ISSUE TITLE
Unable to publish to external stores.

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#10150]
### Description:
Followed the following doc to publish to an external store.
https://apim.docs.wso2.com/en/latest/learn/design-api/publish-api/publish-to-multiple-external-api-stores/#publish-to-multiple-external-developer-portals

### Steps to reproduce:
Get two instances of APIM ( instance1, instance2 )
Make instance 2 port offset to 1.
Change instance 1  `/_system/governance/apimgt/externalstores/external-api-stores.xml` to the following.
```
<ExternalAPIStores>
    <StoreURL>http://localhost:9443/devportal</StoreURL>
        <ExternalAPIStore id="DeveloperPortal2" type="wso2" className="org.wso2.carbon.apimgt.impl.publishers.WSO2APIPublisher">
            <DisplayName>DeveloperPortal2</DisplayName>
            <Endpoint>http://localhost:9444/devportal</Endpoint>
            <Username>admin</Username>
            <Password>admin</Password>
        </ExternalAPIStore>
</ExternalAPIStores>
```

Go to instance 1 publisher portal and try to publish to the DeveloperPOrtal2. 

<img width="1439" alt="Screen Shot 2021-03-05 at 12 08 16 PM" src="https://user-images.githubusercontent.com/3424539/110077384-082dd380-7dac-11eb-8392-bc2b33c921c6.png">

<img width="1076" alt="Screen Shot 2021-03-05 at 12 10 51 PM" src="https://user-images.githubusercontent.com/3424539/110077410-12e86880-7dac-11eb-9405-412412523d32.png">

**Comment by malinthaprasan** [comment]
<Endpoint>http://localhost:9444/devportal</Endpoint> needs to be pointed to **https**

**Comment by chanaka3d** [comment]
Did the change in the registry config.

The configuration change is visible in the publisher.

<img width="849" alt="Screen Shot 2021-03-23 at 5 09 33 PM" src="https://user-images.githubusercontent.com/3424539/112140885-9acad100-8bfa-11eb-98b3-501949db00eb.png">


Following error printed in the terminal.

```bash
[2021-03-23 17:07:04,441] ERROR - WSO2APIPublisher Import API service call received unsuccessful response:  status: 404
[2021-03-23 17:07:04,442] ERROR - APIProviderImpl org.wso2.carbon.apimgt.api.APIManagementException: Import API service call received unsuccessful response:  status: 404
[2021-03-23 17:07:04,443] ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Failed to publish API to external Store. 
```
