### ISSUE TITLE
Message mediation does not working in APIM 4

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-apim#10152]
### Description:
APIM mediation flows do not work in APIM 4 alpha.

### Steps to reproduce:
- Create a new API with a sample backend service.
- In runtime configurations, add "log_in_message" common policies to the "Message Mediation" request flow.
- Invoke the API but no log message printed on the terminal.

**Comment by CrowleyRajapakse** [comment]
If you are doing any change to the API(related to resource/runtime) changes, after doing the changes need to create a new revision and deploy that revision in order for that change to be applied to gateway. Use deployments section

**Comment by malinthaprasan** [comment]
Tested in the latest pack. Works after deploying a deploying a revision after adding a mediation.
