### ISSUE TITLE
Prototype Implementation inline script UI corrupted and cannot update the inline scripts 

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#10181]
### Description:
The inline script editor in API Prototype implementation has been corrupted. The editor view is overflowed. And also even we update the inline script of a resource, it doesn't get reflected in the response when invocation.

### Steps to reproduce:
1. Create an API with "Prototype implementation"
2. Go to Endpoints section.
3. Select a resource. You will see the corrupted editor view with overlapping sections as below.

![image](https://user-images.githubusercontent.com/2484781/110281636-1d506f80-8003-11eb-9dae-7a7e69286ff7.png)

4. Anyhow we can manage to edit the inline script content and save.
5. Then deploy a revision of the API
6. Then "Deploy API as prototype"
7. Go to devportal and invoke the API.
Response is {} eventough a json payload is expected as defined in the inline script. 

### Affected Product Version:
carbon-apimgt 9.0.22.SNAPSHOT based APIM (after 4.0.0-alpha)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Alignment issue is fix in the master branch.

Once we do a change to the script we need to do a redeployment.
Tested in the latest pack and changes to the script reflected in the responses after redeploy the API.
