### ISSUE TITLE
[UI] Listing issue for comments in dev portal

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#10197]
### Description:
- When there are many comments, the overview page comment tile keeps expanding. Better if we can add a scroll bar or some mechanism 
<img width="1338" alt="Screenshot 2021-03-09 at 11 45 56 AM" src="https://user-images.githubusercontent.com/4861150/110427534-e85d1f00-80cd-11eb-8aa2-ed93bff9a981.png">

- 'Reply' button is shown for a reply comment. this needs to be hidden since we do not allow to reply to a reply.

<img width="255" alt="Screenshot 2021-03-09 at 11 52 32 AM" src="https://user-images.githubusercontent.com/4861150/110427626-0dea2880-80ce-11eb-95a8-14d8c594483a.png">

**Comment by erangatl** [comment]
Will be fixed with 
https://github.com/wso2/carbon-apimgt/pull/10162
