### ISSUE TITLE
WARN logs appearing during APIM 4.0.0 alpha pack startup

### ISSUE THREAD

**Issue by amilam** [wso2/product-apim#10198]
I could observe the following WARN logs when starting the APIM 4.0.0 alpha pack. Below output is a grep from the carbon.log after server startup.

`TID: [2021-03-09 12:12:35,527]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /Users/amila/Releases/wso2am-4.0.0-alpha {org.wso2.config.mapper.ConfigParser}
`
`
TID: [-1234] [] [2021-03-09 12:12:54,170]  WARN {org.wso2.carbon.mediation.security.vault.external.ExternalVaultConfigLoader} - No such file: external-vaults.xml in location /Users/amila/Releases/wso2am-4.0.0-alpha/repository/conf/security/external-vaults.xml
`

`
TID: [-1234] [] [2021-03-09 12:13:04,015]  WARN {org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator} - We don't support method overloading. Ignoring [generateUpdatedAPIFromSwagger]
TID: [-1234] [] [2021-03-09 12:13:04,017]  WARN {org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator} - We don't support method overloading. Ignoring [generateUpdatedAPIFromSwagger]
TID: [-1234] [] [2021-03-09 12:13:04,092]  WARN {org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator} - We don't support method overloading. Ignoring [generateSwaggerFromSynapseAPI]
TID: [-1234] [] [2021-03-09 12:13:04,093]  WARN {org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator} - We don't support method overloading. Ignoring [generateAPIFromSwagger]
`

**Looks like a newly introduced admin service has some overloaded methods.**

`
TID: [-1234] [] [2021-03-09 12:13:05,816]  WARN {org.wso2.carbon.identity.application.mgt.internal.ApplicationManagementServiceComponent} - Templates directory not found at /Users/amila/Releases/wso2am-4.0.0-alpha/repository/resources/identity/authntemplates
`
**Above shouldn't be a WARN, IMO.**

`
TID: [-1234] [] [2021-03-09 12:13:59,107]  WARN {org.wso2.carbon.andes.internal.QpidServiceComponent} - MQTT Transport is disabled as per configuration.
`
**If MQTT transport is disabled as per config, why should it be a WARN?**

`
TID: [-1234] [] [2021-03-09 12:13:59,619]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-03-09 12:13:59,620]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-03-09 12:13:59,621]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-03-09 12:13:59,621]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-03-09 12:13:59,622]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
TID: [-1234] [] [2021-03-09 12:13:59,622]  WARN {org.apache.tomcat.util.net.SSLUtilBase} - jsseUtil.trustedCertNotValid
`

`
TID: [-1] [] [2021-03-09 12:14:00,692]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : keyManager
TID: [-1] [] [2021-03-09 12:14:00,704]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : notification
TID: [-1] [] [2021-03-09 12:14:01,177]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : tokenRevocation
TID: [-1] [] [2021-03-09 12:14:01,181]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : throttleData
TID: [-1] [] [2021-03-09 12:14:01,193]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : notification
TID: [-1] [] [2021-03-09 12:14:01,194]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : cacheInvalidation
TID: [-1] [] [2021-03-09 12:14:01,195]  WARN {org.wso2.carbon.apimgt.jms.listener.utils.JMSUtils} - Cannot locate destination : asyncWebhooksData
`

Please see whether there is a good reason to print a WARN log. If not either get rid of the log or change the log level.

**Comment by chanikag** [comment]
Warn messages in org.wso2.config.mapper.ConfigParser a PR is sent [1] and merged. But a kernel upgrade is needed .

Warn messages in org.apache.tomcat.util.net.SSLUtilBase is due to the expired certs in the shipped truststore. This needs kernel upgrade and already having a discussion in [2]

[1] https://github.com/wso2/config-mapper/pull/20
[2] https://github.com/wso2/product-is/issues/8479

**Comment by chanikag** [comment]
org.wso2.carbon.identity.application.mgt.internal.ApplicationManagementServiceComponent warn message is due to missing adaptive authentication templates. As we do not recommend to use APIM on that, we are not going to do so. The other option is to set a flag to disable Script Based Adaptive Authentication in the carbon console. But that requires a version upgrade of org.wso2.carbon.identity.application.mgt which we do not going to do in this release. Therefore created [1] to do this in a wum update.

[1] https://github.com/wso2/product-apim/issues/10717
