### ISSUE TITLE
Configure Okta as a Key Manager - cannot change fields once set initially

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#10191]
### Description:
Cannot change "Certificates" , "Token Handling Options",  fields once set initially in the UI.

### Steps to reproduce:
1. Follow below guide to setup Okta KM as a KM in admin portal
https://apim.docs.wso2.com/en/next/administer/key-managers/configure-okta-connector/#configure-okta-as-a-key-manager
Issue 1: When selected the "Certificates" type "PEM/"JWKS" we can't unselect the selected option. This field is mentioned as optional in the docs.

First:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/2484781/110323317-74be0200-803a-11eb-96e3-3a1d3b974f68.png">
Then:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/2484781/110323971-5c9ab280-803b-11eb-96e7-40ad9b734353.png">

Issue 2:  (Similar to above mentioned issue) When "Token Validation Method" is set as "Self validate JWT" when selected any item from "Token Handling Options",  we cannot unselect the selected option. This property too is optional.

NOTE: normal radio button input-type is not suitable for an "Optional" input field.

**Solution suggested:**
Better to have above fields as tick box i

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This issue fixed in latest version.
