### ISSUE TITLE
Username and consumerKey values are null in the RequestContextDTO in preProcessRequest of ExtensionListener interface

### ISSUE THREAD

**Issue by RivinduM** [wso2/product-apim#10203]
### Description:
Username and ConsumerKey values are passed as null in the preProcessRequest method of the ExtensionListener interface.

### Steps to reproduce:
1. Implement the ExtensionListener interface (org.wso2.carbon.apimgt.common.gateway.extensionlistener.ExtensionListener)
2. Do an API call
2. Inspect the APIRequestInfoDTO of RequestContextDTO passed to the preProcessRequest method.

### Affected Product Version:
wso2am-4.0.0-alpha

**Comment by tharindu1st** [comment]
@RivinduM  Did you check the user was there in  following method in Authentication 

    ExtensionResponseDTO postProcessRequest(RequestContextDTO requestContextDTO);

**Comment by RivinduM** [comment]
@tharindu1st Yes, the user is there in the postProcessRequest method. As per the offline discussion since this is a pre Authentication method, I'm closing the issue.
