### ISSUE TITLE
[UI] Delete button is half visible in Publisher portal when multiple tags are present.

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10223]
### Description:

Delete button is half visible in Publisher portal when multiple tags are present.

![Screenshot 2021-03-10 at 14 56 45](https://user-images.githubusercontent.com/17047910/110607658-6ba37100-81b1-11eb-80b7-4425d0db90b5.png)

### Steps to reproduce:

1. Create websocket API and publish it

### Affected Product Version:

wso2am-4.0.0-alpha

### Environment details (with versions):
- OS: MacOs
- Client:
- Env (Docker/K8s):

**Comment by erangatl** [comment]
Fixed in latest
![image](https://user-images.githubusercontent.com/20179540/114196084-a9d9af00-996e-11eb-9c7a-e574043d78af.png)
