### ISSUE TITLE
Updating the AsyncAPI definition deletes all the Topics in Websocket API

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10229]
### Description:

Updating the AsyncAPI definition deletes all the Topics in Websocket API.

<img width="743" alt="Screenshot 2021-03-10 at 20 52 55" src="https://user-images.githubusercontent.com/17047910/110652798-b5f11600-81e2-11eb-9857-3b32b0e746c6.png">
<img width="1184" alt="Screenshot 2021-03-10 at 20 53 20" src="https://user-images.githubusercontent.com/17047910/110652808-b7bad980-81e2-11eb-9f8e-f30e72125df4.png">
<img width="791" alt="Screenshot 2021-03-10 at 20 53 34" src="https://user-images.githubusercontent.com/17047910/110652813-b9849d00-81e2-11eb-997a-79bfc081452b.png">

### Steps to reproduce:

1. Create a websocket API
2. Add a new topic (channel) by editing the AsyncAPI Definition (yaml/json)
3. When you save and visit the topics tab, all the topics would have been deleted now

### Affected Product Version:

wso2am-4.0.0-alpha

### Environment details (with versions):
- OS: MacOS
- Client:
- Env (Docker/K8s):

**Comment by arunans23** [comment]
The same issue exists for WebSub APIs

**Comment by lasanthaS** [comment]
This issue is fixed from https://github.com/wso2/carbon-apimgt/pull/10078. Hence closing
