### ISSUE TITLE
[UI] alignment issue in API list view items for websocket api

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#10246]
### Description:
See image below
<img width="303" alt="Screenshot 2021-03-12 at 12 47 39 PM" src="https://user-images.githubusercontent.com/4861150/110905903-3c1b7280-8331-11eb-8bc6-27642158ba3f.png">

**Comment by tmkasun** [comment]
Duplicate issue https://github.com/wso2/product-apim/issues/10246 , Will track the issue in the previous GitHub issue. Hence closing this
