### ISSUE TITLE
WebSocket Topic Schema tab takes to an error page

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10267]
### Description:
WebSocket Topic Schema tab takes the user to an error page
![chrome-capture (3)](https://user-images.githubusercontent.com/32265029/111131893-f5e33080-8535-11eb-821b-d60da6f7464a.gif)

### Steps to reproduce:

- Follow the doc and create a new webSocket https://apim.docs.wso2.com/en/next/design/create-api/create-streaming-api/create-a-websocket-streaming-api/
- Click show more under topics
- Add a new Topic.
- Click and expand the created Topic.
- Click on **SCHEMA** tab

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL server 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by Krishanx92** [comment]
This is not reproduce in latest pack.
