### ISSUE TITLE
WebSocket Topic with empty name

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10262]
### Description:

- User is allowed to add a webSocket with an empty name.
![chrome-capture (1)](https://user-images.githubusercontent.com/32265029/111122744-af88d400-852b-11eb-99a8-acf24f5e119e.gif)
 
- User can add a new Topic with existing Topic name. No errors will be displayed when add button is clicked. But when the save button is clicked Topic name disappears and "_webSocket API updated successfully_" message is displayed.
![chrome-capture (2)](https://user-images.githubusercontent.com/32265029/111122809-c92a1b80-852b-11eb-851e-c20c28b27c5f.gif)

### Steps to reproduce:

-  Follow the doc and create a new webSocket https://apim.docs.wso2.com/en/next/design/create-api/create-streaming-api/create-a-websocket-streaming-api/
- Click show more under topics
- Add a new Topic, leave name blank. 
- Click save
- Add two new topics with same name.

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL server 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by dushansilva** [comment]
Fixed in latest pack, hence closing
