### ISSUE TITLE
Scopes not getting reflected in API product

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10284]
### Description:
If a user add an scope to a resource of the API of an API Product that was based on, the scope will not get reflected in the resource of the API Product.

### Steps to reproduce:

- Create 2 APIs ( https://apim.docs.wso2.com/en/latest/learn/design-api/create-api-product/create-api-product/ )
- Create an API Product with the 2 APIs
- Publish the product.
- Go to one of the APIs
- Go to resources.
- Expand a resource and add a new scope
- Save
- Go to the API Product
- Go to resources

### Expected result :
Added new scope should be displayed under the resource

### Expected result :
Scope field is empty

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10

#### Suggested Labels:
API-M 4.0.0

**Comment by CrowleyRajapakse** [comment]
User will need to re add the resource to the API Product, by going to resources tab and clicking Edit resources.
