### ISSUE TITLE
I cannot login to carbon admin UI

### ISSUE THREAD

**Issue by kaiyuan01** [wso2/product-apim#1028]
I installed WSO2 AM(API Manager) 1.10.0 and used the user-mgt.xml from working AM 1.9.0 with LDAP enabled, but now I cannot login to carbon admin UI.

Please refer to this question:
http://stackoverflow.com/questions/38167243/i-installed-wso2-amapi-manager-1-10-0-and-used-the-user-mgt-xml-from-working-a

Any help is appreciated.

**Comment by harsha89** [comment]
Please check the configuration. It was working fine.
