### ISSUE TITLE
Error while adding a scope for an API Product resource

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10286]
### Description:
User is unable to add an scope for an API Product resource if the underline API is not published.

![chrome-capture (5)](https://user-images.githubusercontent.com/32265029/111270870-a52f0e80-85ed-11eb-8629-9addd29df132.gif)

### Steps to reproduce:

- Create 2 APIs ( https://apim.docs.wso2.com/en/latest/learn/design-api/create-api-product/create-api-product/ )
- Publish one API
- Create an API Product with the 2 APIs
- Go to overview page of the API product.
- Click "Show more" under resources
- Expand an resource of the unpublished API
- Click **Create new scope**
- Fill valid data and Click Save

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL server 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by CrowleyRajapakse** [comment]
It seems this is also related to https://github.com/wso2/product-apim/issues/10280, fixing the redirect at show more will resolve this as well
