### ISSUE TITLE
Revoked API Key usable after restarting the server

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10283]
### Description:
Revoked API keys are considered to be valid after a server restart.

### Steps to reproduce:
- Publish an API with API Key enabled
- Navigate to Devportal and subscribe to the API
- Generate an API Key
- Invoke the API using the API Key
- Revoke the API Key using the Devportal REST APIs
- Restart the server
- Invoke the API using the previously revoked API Key

#### Related Issues:
https://github.com/wso2/product-apim/issues/9641
https://github.com/wso2/product-apim/issues/9811

**Comment by malinthaprasan** [comment]
@Jayanie have we added this to master branch?
