### ISSUE TITLE
[Publisher]New revision create form's Revision name is displayed incorrectly

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#10293]
### Description:

The revision creation UI can't keep track of the next revision's `Revision Name`.

### Steps to reproduce:

1. Open Publisher and load an API deployments page.
2. Create 2 revisions (or more)
3. Delete one (or more) revision(s) and click new revision button. Note the UI counts the next revision name correctly.
4. Refresh the page and click new revision button again.
5. Note that it can't account for the deleted revision(s)

### Suggested fix
It would be better to have next available api revision name on the revision listing resource response.

Eg:

```
{
  count: 2,
  nextApiRevisionName: "Revision 6"
  list: [{displayName: "Revision 1", id: "e2451729-4e4e-47e2-83fe-d636aacfa892",…},…]
}
```

### Affected Product Version:
APIM 4.0.0 alpha

#### Suggested Labels:
Frontend, Publisher, UI/UX

#### Suggested Assignees:
@tmkasun

**Comment by Krishanx92** [comment]
This needs to fix from the REST API level, Now we remove showing the next revision name since there's no actual use case to the user. hence close the issue.
