### ISSUE TITLE
API Definitions UI

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#10295]
### Description:
API Definitions UI out of place.

### Steps to reproduce:

1. Login to API Publisher
2. Create new or go inside an existing API
3. Navigate to API Definition (image attached below)

#### Setup
* APIM 4.0.0 SNAPSHOT
* Oracle 11gv2 XE

![image4](https://user-images.githubusercontent.com/33457890/111300648-529a3480-8677-11eb-8872-84d9f136d8f5.png)

**Comment by malinthaprasan** [comment]
Looks like this is fixed from https://github.com/wso2/carbon-apimgt/pull/10009

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/10009
