### ISSUE TITLE
Reply button is not working under nested comments

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10302]
### Description:
There is a Reply button under a nested comment which is not doing anything. Should the user be able to reply to a nested comment with another nested comment?
![chrome-capture (7)](https://user-images.githubusercontent.com/32265029/111349952-d84dbe00-863e-11eb-8ae2-b319c5280d97.gif)

### Steps to reproduce:

- Comment on an API
- Reply to the comment
- Click Reply button under nested comment

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10

#### Suggested Labels:
API-M 4.0.0

**Comment by RakhithaRR** [comment]
This issue is present in the Comments section of the Publisher as well.
