### ISSUE TITLE
API Documents Markdown page is not aligned correctly

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10303]
### Description:
When adding an API document if the user select Markdown as the document source, user will be navigated the following editor page, which is not aligned properly.
![Capture](https://user-images.githubusercontent.com/32265029/111353091-2d3f0380-8642-11eb-8f00-5413be02663c.JPG)

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10

#### Suggested Labels:
API-M 4.0.0

**Comment by tmkasun** [comment]
Fixed with thi PR https://github.com/wso2/carbon-apimgt/pull/10009
