### ISSUE TITLE
Error when adding a new Revision after the Revision count exceeded

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10308]
### Description:
An error is thrown when trying to create a new revision after the maximum revision count is exceeded.
```
ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Failed to delete registry artifacts
```

![Screenshot from 2021-03-17 11-37-52](https://user-images.githubusercontent.com/25485273/111423278-0baf4c00-8716-11eb-9d66-0e9674072c10.png)

### Steps to reproduce:
1. Create an API
2. Go to Deployments and create 5 Revisions
3. Try to create the 6th Revision. At this point, we are asked to delete an existing Revision which is successful but when confirming to create the new Revision, the error is thrown.

If we close the popup and create the Revision manually, it gets created without any issues

### Affected Product Version:
4.0.0-alpha

**Comment by CrowleyRajapakse** [comment]
This seems due to a UI issue, 
In the 3rd step, UI is sending another delete request instead of create new revision although the button is "Create". 
Previously also reported seems not fixed yet
