### ISSUE TITLE
Removing clustering configs from the deployment.toml

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#10312]
### Describe your problem(s)
The deployment.toml file contains the following configs related to clustering which is not recommended in the latest versions of the API-Manager server. 
```
node_ip = "127.0.0.1"
mode = "single" #single or ha
```

### Describe your solution
Removing the above configs from the deployment.toml file. 

Additionally, since the API-Manager-3.x.x versions have these configs by default in the deployment.toml file, it would be better to add a note in the configuration catalogue [1] on removing the configs.

[1]. https://apim.docs.wso2.com/en/latest/reference/config-catalog/

---
#### Related Issues:
https://github.com/wso2/product-apim/issues/6792#issuecomment-552458179

#### Suggested Labels:
API-M 4.0.0

**Comment by tharindu1st** [comment]
@lkokila These configs need to be in Config Catalog +1 to remove from Deployment.toml

**Comment by rmsamitha** [comment]
The "node_ip" config is referenced as a value for another config in default.json.
i.e.
`  "clustering.local_member_host": "$ref{server.node_ip}"`

So when we remove the below line from deployment.toml,
` node_ip = "127.0.0.1" `
we have to remove the aforementioned default.json reference too. 
To do that in default.json file,

- Option 1: Remove  the complete line `  "clustering.local_member_host": "$ref{server.node_ip}",`  line.

- Option 2: Set the default value of `"clustering.local_member_host"` explicitly without referring `$ref{server.node_ip}`
     -   i.e.  `"clustering.local_member_host": "127.0.0.1" `

I suggest the option 2 will be fine to go-with.
@tharindu1st

**Comment by rmsamitha** [comment]
Anyway seems editing the line `  "clustering.local_member_host": "$ref{server.node_ip}",` in default.json is not possible through APIM repos. It comes from carbon-kernel, so that is not ideal to change there effecting all other products. So the viable option is non of the above.

What we can do is adding a new config line to the default.json prepared in product-apim.
That line is
`"server.node_ip":"127.0.0.1",`
