### ISSUE TITLE
Cancel button in comments does nothing

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10316]
### Description:
There is a cancel button for each comment and reply which does nothing.

For a root comment we can make the cancel button clear the text field.
For a nested comment we can make the cancel button click disappear the nested comment box.

![chrome-capture (9)](https://user-images.githubusercontent.com/32265029/111454634-16e08880-86d2-11eb-85dd-2e34e080252b.gif)

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: windows 10

#### Suggested Labels:
API-M 4.0.0

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10055
