### ISSUE TITLE
WebSocket Topic Schema tab does not render properly

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10319]
### Description:

![image](https://user-images.githubusercontent.com/28702407/111466201-fdc6ee80-8748-11eb-9a0c-a3ff18d37604.png)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by lasanthaS** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/10078, hence closing.
