### ISSUE TITLE
Error while changing application owner

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10328]
### Description:
Unable to change the application owner. Error "_Something went wrong when updating owne_r" is displayed

![chrome-capture (10)](https://user-images.githubusercontent.com/32265029/111515210-bec87700-870f-11eb-9768-7072f956122d.gif)

### Steps to reproduce:
Follow the steps in doc "[Changing the Owner of an Application](https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/)"

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
https://github.com/wso2/product-apim/issues/10645 this can be related but we need the error logs on the server console to check the issue directly.

**Comment by msm1992** [comment]
@TheRasanjana  This issue cannot be reproduced in the latest pack by following the instructions in the doc under normal conditions. Please specify the steps you followed to get this issue.
