### ISSUE TITLE
WebSocket Topic Properties save and close buttons are not working

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10320]
### Description:
Save and close buttons here take no action after click them
![image](https://user-images.githubusercontent.com/28702407/111467592-9ca01a80-874a-11eb-9f87-d26360ca3a07.png)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by lasanthaS** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/10078, hence closing.
