### ISSUE TITLE
Issue in Prototype implementation page of Endpoints

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10327]
### Description
In Prototype implementation page of Endpoints, when resource is expanded the editor is not aligned as expected.
![image](https://user-images.githubusercontent.com/32265029/111498523-4063d900-86ff-11eb-8ddd-543269ca4680.png)

### Steps to reproduce:

- Create an API with  OpenAPI URL  https://petstore3.swagger.io/api/v3/openapi.json
- Click Endpoints to navigate to the Endpoints page.
- Select Prototype Implementation

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10

---
#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
Working in the latest pack.

Seems fixed in https://github.com/wso2/carbon-apimgt/pull/10009
