### ISSUE TITLE
Error while accessing Resources in API Product

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10325]
### Description:
The following error can be seen when accessing the Resources tab for an API Product when POST or PUT resources from the PizzaShackAPI is used.

![Screenshot from 2021-03-17 18-36-34](https://user-images.githubusercontent.com/25485273/111472686-37e7be80-8750-11eb-9576-256d26dd80c6.png)

### Steps to reproduce:
1. Deploy the sample PizzaShackAPI
2. Create an API Product
3. Add either POST or PUT resource from PizzaShackAPI and create the Product.
4. Go to the Resources tab in API Product

### Affected Product Version:
4.0.0-alpha

**Comment by malinthaprasan** [comment]
@YasasRangika

**Comment by RakhithaRR** [comment]
The original UI issue seems to be fixed in the latest pack. However, the following error can be seen when accessing the Resources of the API Product after following the same set of steps.

![proderror](https://user-images.githubusercontent.com/25485273/112123669-76b1c480-8be7-11eb-908c-0a40aa50e917.png)
