### ISSUE TITLE
Rate limiting policies does not appear for runtime configuration of WebSocket API

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10326]
### Description:
![Peek 2021-03-17 19-02](https://user-images.githubusercontent.com/28702407/111476089-ce69af00-8753-11eb-9357-836b2508da4f.gif)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by Krishanx92** [comment]
This is fixed in latest version, hence closing
