### ISSUE TITLE
GraphQL API Trying Out Issue at Dev Portal

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#10339]
### Description:
Screen blacks out when going to the try out menu of GraphQL

### Steps to reproduce:
1. Create a GraphQL Application according to the docs
2. Create a Scope and assign it to an operation
3. Publish the API
4. Go to dev portal, click on the API and go to Application Creation and Key Generation Wizard
5. Go Through the steps and copy the API Token
6. To to Try out Section

[GIF is attached]

### Environment details (with versions):
- OS: Ubuntu 20.04
- Env (Docker/K8s): APIM 4.0.0(localhost) with DB setup as Oracle 11g v2 XE(via docker)
- Tenant - Email Username enabled tenant

![Peek 2021-03-18 11-13](https://user-images.githubusercontent.com/33457890/111579178-8e4e0f00-87db-11eb-8c4b-d1527cabdbce.gif)

**Comment by malinthaprasan** [comment]
Still reproducible in latest pack.

This happens when there is no deployment to the GQL API. Adding a deployment and going to the try it works properly.

**Comment by malinthaprasan** [comment]
Reduced the priority as it is not a blocker. Increased severity as this is misleading to users.

**Comment by chanaka3d** [comment]
This issue is fixed in the latest snapshot build
