### ISSUE TITLE
[Publisher] Can't change display in devportal when deployed 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10332]
### Description:

![image](https://user-images.githubusercontent.com/3313885/111567099-68694000-87c4-11eb-9001-7988aca41e0e.png)

When a revision is deployed, Publisher user can't change its (Deployed revision's) `Display in Developer Portal` option.
They have to un-deploy the revision, and change the `Display in Developer Portal` input and click deploy again,This is not very intuitive.

We might need to introduce `PUT` operation for
```
https://localhost:9443/api/am/publisher/v2/apis/{API_ID}/deploy-revision?revisionId={REVISION_ID}
```
to update only `Display in Developer Portal` option in a deployed revision.

**Comment by CrowleyRajapakse** [comment]
same issue: https://github.com/wso2/product-apim/issues/10281

**Comment by CrowleyRajapakse** [comment]
https://github.com/wso2/carbon-apimgt/pull/10039

**Comment by tmkasun** [comment]
Thanks @CrowleyRajapakse  , we need to update the UI logic here as well. 
Here
https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/Environments/Environments.jsx#L410-L419

We have to call the update deployment API to update the deployed revision with devportal visibility change
