### ISSUE TITLE
Delete comment option does not work for tenant user

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10345]
### Description:

- This delete option is only allowed for sub tenant user (reported: https://github.com/wso2/product-apim/issues/10343)
- After deletion, it does not remove comments from the tab
![Peek 2021-03-18 11-59](https://user-images.githubusercontent.com/28702407/111583115-e9830000-87e1-11eb-9c9e-33f4068edc30.gif)

### Steps to reproduce:

1. Go to comments tab
2. Add a new comment
3. Click delete (Error message will pop up)
4. Refresh browser (Comment is still there)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by kavishkafernando** [comment]
This seems to be a UI issue. Seems like commentId that is passed to the API call in undefined.

<img width="1657" alt="Screenshot 2021-03-22 at 5 10 43 PM" src="https://user-images.githubusercontent.com/19324135/111984606-97b7de00-8b31-11eb-8a9b-c1f60f6ef51a.png">
