### ISSUE TITLE
Cannot add endpoint security configurations to LB and Fail-over endpoints

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10349]
### Description:
Though there is an option to add endpoint security configurations to load balancing and fail over endpoints in Load balance and Failover Configurations in Endpoints tab, it does not perform any action when clicked

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by malinthaprasan** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10556
