### ISSUE TITLE
Comments feature does not allow admin to delete comments

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10343]
### Description:
Though it allows sub tenant admin to delete comments from comments tab as below,
![image](https://user-images.githubusercontent.com/28702407/111582230-8d6bac00-87e0-11eb-8355-02087c681f25.png)

super tenant admin doesn't have that option
![image](https://user-images.githubusercontent.com/28702407/111582372-bc821d80-87e0-11eb-97db-c02abf4e2a73.png)

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10055
