### ISSUE TITLE
Endpoint certificate count is always zero

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10348]
### Description:
Certificate count becomes zero after refreshing the page
![image](https://user-images.githubusercontent.com/28702407/111584868-729b3680-87e4-11eb-89cf-2585d32bf236.png)

### Steps to reproduce:

1. Add new endpoint certificate
2. Refresh browser tab or switch again from another tab to Endpoints tab

### Affected Product Version:
API-M 4.0.0 Alpha

**Comment by mushthaq33** [comment]
@YasasRangika - Did you try after saving the API?

**Comment by msm1992** [comment]
@YasasRangika This could not be reproduced in the latest APIM build (9.0.141-SNAPSHOT) hence closing.
