### ISSUE TITLE
Unable to copy the correct access token generation cURL using the copy button from the Store portal in APIM-2.6.0

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#10365]
### Description:
In the latest update of APIM-2.6.0, it is unable to copy the correct access token generation cURL using the copy button from the Store portal. That means, the copied content has not included the Gateway URL, even though it is correctly populated in the UI.

**Content in the UI**
```
curl -k -d "grant_type=password&username=Username&password=Password" \
   -H "Authorization: Basic Base64(consumer-key:consumer-secret)" \
     https://192.168.8.101:8243/token
```

**Copied content**
```
curl -k -d "grant_type=password&username=Username&password=Password" -H "Authorization: Basic Um5DaG5ReTFiN2NrMmQ1NzVJeVdRTVJydlhnYTpfNVN6Nl85UjFBN2VmTXg3cm9kaXRkelI4aXNh" /token
```

### Steps to reproduce:
* Start the updated APIM-2.6.0 and login to the store portal.
* Register an application and then generate keys.
* Then copy the content of generated cURL and it will not include the Gateway URL as above.

### Affected Product Version:
APIM-2.6.0

**Comment by Jayanie** [comment]
This is fixed in the latest.
