### ISSUE TITLE
Spelling issue when creating the sample API

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#10374]
### Description:
Spelling issue when creating the sample API. (Screenshot attached)

should be "Updating"

### Steps to reproduce:
1. Open the publisher portal
2. Click create and deploy sample application

### Environment details (with versions):
- OS: Ubuntu 20.04

![Screenshot from 2021-03-19 10-58-13](https://user-images.githubusercontent.com/33457890/111735651-61186400-88a2-11eb-92db-90b51ee79fcf.png)

**Comment by TheRasanjana** [comment]
We need to make each starting letter capital.

**Comment by rashm1n** [comment]
"Creating Sample API" text also need to be corrected.

**Comment by tmkasun** [comment]
This is fixed in the master now, We have improved the progress view and this issue is no longer in the master
![image](https://user-images.githubusercontent.com/3313885/112782528-df2af680-906a-11eb-8ccc-304ea1fdec46.png)
