### ISSUE TITLE
API Resources with trailing slash are invisible in the Publisher

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#10384]
### Description:

When there are API resources with trailing slash they are invisible in the publisher.

Also APIs cannot be created with the swagger definitions if it have a resource with trailing slashes. 

### Steps to reproduce:

Create a API with swagger file that has a resource with trailing slash.
It just redirects to API create with empty API create page.

### Affected Product Version:
AM-2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Jayanie** [comment]
This is fixed in the latest.
