### ISSUE TITLE
Improve API product onboarding page to a card design

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#10389]
### Describe your problem(s)

XD: https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/screen/afa2a149-2113-4628-bc38-ddc1723caa3b/
![image](https://user-images.githubusercontent.com/20179540/111945914-902c1100-8b00-11eb-8017-9cf465489316.png)

### How will you implement it

---

**Comment by tmkasun** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/10149
