### ISSUE TITLE
[Streaming API] Validate Endpoint URL button doesn't work for WebSocket Endpoints

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-apim#10399]
### Description:
The button in the **Endpoint** field (as shown below) is used to validate whether the mentioned endpoint URL is reachable or not. For WebSocket APIs, clicking this button results in the error `unknown protocol: ws`.

<img width="835" alt="Screen Shot 2021-03-22 at 1 49 15 PM" src="https://user-images.githubusercontent.com/24828296/111968600-54ed0a80-8b1f-11eb-9f84-2495c6fa4269.png">

### Steps to reproduce:
1. Create a WebSocket Streaming API
2. Provide a `ws` endpoint (eg: `ws://localhost:8080`) and click on the validate button.
3. `unknown protocol: ws` will be shown before the button.

### Affected Product Version:
API-M 4.0.0

**Comment by Arshardh** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10335/
