### ISSUE TITLE
API KEY not working as expected

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10396]
### Description:
Unable to invoke the API with API KEY generated. Observed in Windows with mssql 2019.
![image](https://user-images.githubusercontent.com/32265029/111953857-6fce6900-8aa4-11eb-803d-6f0cd5afe78c.png)

![image](https://user-images.githubusercontent.com/32265029/111955023-2ed75400-8aa6-11eb-8f95-6de631e93509.png)

### Steps to reproduce:

- Create and publish an API
- In Application Level Security Select API Key and click SAVE.
- Go to Dev portal and subscribe to an application
- Generate API key
- Go to Try out page and paste the API key and execute.

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
**- OS: Windows 10**
**- DB : MSSQL 2019**

#### Suggested Labels:
API-M 4.0.0

**Comment by tharindu1st** [comment]
@TheRasanjana did you create API revision after step 2  if not please create a revision and check the issue got fixed.

**Comment by TheRasanjana** [comment]
@tharindu1st this was due I have missed deploying a new revision step. I will be closing this issue.
