### ISSUE TITLE
Improve Scopes onboarding page to a card design

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#10390]
### Describe your problem(s)

XD: https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/screen/aa39e2ca-10a7-407f-b1d5-86f52d6733fc

![image](https://user-images.githubusercontent.com/20179540/111946315-4263d880-8b01-11eb-8b91-f86089edc521.png)

### How will you implement it

---

**Comment by tmkasun** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/10149
