### ISSUE TITLE
API request not going through

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10405]
### Description:

In a windows setup, intermittently some requests are not going through. Keeps loading. only after opening the console and pressing enter button, response returns.

![rec](https://user-images.githubusercontent.com/32265029/112030119-29562a00-8af7-11eb-8dcd-4471d5418fb6.gif)

### Steps to reproduce

- Create an API
- Subscribe to an application
- Generate the curl
- Keep executing requests

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL 2019

#### Suggested Labels:
API-M 4.0.0 , Priority/Highest

**Comment by malinthaprasan** [comment]
In windows when you click on the console (selected a square) the process will halt until you press enter and release the cursor. That is a typical behaviour on windows AFAIR. 

Other than that are there any other issue?

**Comment by TheRasanjana** [comment]
@malinthaprasan I am not sure If I made any interference with the console to halt the process. Any way I will be closing this for now as I am not sure. Will reopen if this happens without any interference
