### ISSUE TITLE
Prototype mock scripted APIs "Reset" button doesn't seem to work as intended and removes the script from the resource

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#10408]
### Description:

Once clicking the "Reset" button in the resource pane, the script should be reset to the original script generated from the OAS definition. But it doesn't seem to respond.

But if someone click on saves after clicking on reset, seems like the script gets removed from the API resource.

### Steps to reproduce:

![reset_script](https://user-images.githubusercontent.com/1591316/112080138-6f6ac680-8ba7-11eb-8de3-8a65bdbabebd.gif)

**Comment by YasasRangika** [comment]
This is in progress

**Comment by YasasRangika** [comment]
This issue has been fixed with latest changes in master. It is not reproducing in locally built pack.

![Peek 2021-03-24 10-21](https://user-images.githubusercontent.com/28702407/112257804-66532580-8c8b-11eb-8194-f0e52af455b3.gif)

 Hence we can close this.
