### ISSUE TITLE
Remove HTTP endpoint URL from Test Console servers list when HTTP is not used with APIs

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#10418]
### Description:
If we need to disable HTTP for APIs, we can follow one of the below options.

Option 1 - Remove HTTP from Runtime Configurations when creating a specific API.
Option 2 - Remove http_endpoint config from the deployment.toml file.

But in both the scenarios HTTP endpoint URL will be listed in the publisher test console.

### Steps to reproduce:
Option 1

1. Remove HTTP from Runtime Configurations when creating an API
2. Go to test console and list the server URLs

![image](https://user-images.githubusercontent.com/30709975/112110322-bd4bf280-8bd8-11eb-9c57-fc94baea124e.png)

Option 2

1. Remove _http_endpoint_ config from the deployment.toml file.
2. Go to test console and list the server URLs. HTTP URL will be listed as null.

![image](https://user-images.githubusercontent.com/30709975/112110706-495e1a00-8bd9-11eb-8c6d-f3bb6ac2e7a5.png)

### Affected Product Version:
APIM 3.2.0

**Comment by tmkasun** [comment]
Public fix https://github.com/wso2/carbon-apimgt/pull/10056
