### ISSUE TITLE
Creating sample API display an error in Publisher UI

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10421]
### Description:
Attempting to create the sample API after logging into publisher UI with user having Creator permissions results in the following error

![image](https://user-images.githubusercontent.com/6614042/112139443-c6e55280-8bf8-11eb-9a68-7a61a5d38ce2.png)

Refreshing the page shows the API was created successfully however

### Steps to reproduce:
1. Create a user with Creator permissions
2. Login to publisher and create the sample API

**Comment by tmkasun** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/10149
