### ISSUE TITLE
[DevPortal] Scope mapping based user restriction is not working properly in the DevPortal UI

### ISSUE THREAD

**Issue by isuruh15** [wso2/product-apim#10426]
### Description:
When we used [role based scope mapping](https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-roles/#adding-role-mappings) to restrict certain functions from specific set of users, restricted functionalities are not disabled/disappeared in the DevPortal. 
![image](https://user-images.githubusercontent.com/25496974/112274099-1c2a6e00-8ca4-11eb-8f26-5b4a619037cb.png)

### Steps to reproduce:
creating a custom role in the management console. (viewer)
Granted login permission
assigned following scopes to the created role

-   apim:mediation_policy_view
-   apim:ep_certificates_view
-   apim:api_view
-   apim:subscription_view
-   apim:client_certificates_view
-   apim:publisher_settings
-   apim:store_settings
-   apim:api_key
-   apim:subscribe

Saved the changes and created a user having the custom role.(ROLETESTUSER)
Tried to login to APIM Portals using the newly created user's credentials.

### Affected Product Version:
Affected APIM-3.2.0

### Environment details (with versions):
- OS:Ubuntu 18.04.5 LTS

**Comment by npamudika** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/10476
