### ISSUE TITLE
Developer Portal Visibility is not working as expected

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10430]
### Description:
If the user set API's Developer Portal Visibility as 'Visible to my domain' and logs in to that dev portal with a tenant user, that API is visible.

### Steps to reproduce:
Create and publish an API
Set API's Developer Portal Visibility as 'Visible to my domain'
![image](https://user-images.githubusercontent.com/32265029/112284232-40eff880-8c46-11eb-8e6c-90c2256a6967.png)
Go to the devPortal and logout (Can't see the our API anonymously)
Log in to the devPortal with a tenant user

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by vithu30** [comment]
This issue is not reproducible in the latest built pack with MSSQL configured.
Steps followed:

1. Created API as super tenant admin
2. Set the visibility as `Visible to my domain`
3. Logged in to Devportal as tenant user - The API is not listed
