### ISSUE TITLE
Subscription count is invalid and cannot manage subscription when Developer portal visibility is added

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#10443]
### Description:
Subscription count is invalid and cannot manage subscription when Developer portal visibility is added

### Steps to reproduce:

- Create a user role (**ROLE1**) and user (**USER1**) and assign the **ROLE1** with **Internal/Subscriber**.
- Publish an API via publisher portal by using admin user role. (In Design configuration section, add **Developer portal visibility** restriction with **ROLE1** user roles)
![Screenshot from 2021-03-22 17-19-24](https://user-images.githubusercontent.com/18566908/112439120-bce56000-8d6e-11eb-9581-d29627e95c50.png)

- Log into the dev portal by using **USER1** credentials and subscribe the API with an application.
- Go to the carbon management console and remove **ROLE1** from **USER1**.
- Go back to the dev portal and refresh the page (logged credentials should be **USER1**)
- Select the application and **Subscription** section and cannot see the subscription. But count is there.
![Screenshot from 2021-03-22 17-24-12](https://user-images.githubusercontent.com/18566908/112439125-bf47ba00-8d6e-11eb-868a-f632299f0d7a.png)

### Affected Product Version:
3.2.0

**Comment by chanaka3d** [comment]
GET applications/{applicationID} response contains the following

<img width="657" alt="Screen Shot 2021-04-11 at 9 08 43 AM" src="https://user-images.githubusercontent.com/3424539/114291554-0d1a2d00-9aa6-11eb-8804-343b25cc7ebf.png">

**Comment by malinthaprasan** [comment]
This appears in a different way in APIM 4.0 latest pack as per https://github.com/wso2/product-apim/issues/10420
Hence removing 4.0.0 label.

**Comment by npamudika** [comment]
Public fix is handled in https://github.com/wso2/product-apim/issues/10420
