### ISSUE TITLE
Able to invoke API when lifecycle state is changed to CREATED

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10440]
### Description:
User is currently able to invoke an API of which the lifecycle state has been changed to CREATED. Shouldn't the user be unable to access if the lifecycle state is not in PUBLISHED stage?

### Steps to reproduce:

- Create and publish API
- Subscribe to the API
- Create an Access token
- Change the lifecycle status to CREATED
- Invoke the API

### Affected Product Version:
API-M 4.0.0 

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
This is the expected behaviour. We are not removing the API from gateway when it is moved to created. Gateway runtime will be only changed when the API is retired (API will be removed from gateway)
