### ISSUE TITLE
Role validation fails after running the profile optimization in APIM 3.2.0

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/product-apim#10447]
We were able to observe that the users can log in to the devportal with only internal/publisher and internal/creator roles when the server is optimized as api-devportal and run as the profile.

Steps :

Get a wso2am-3.2.0 pack
Run the sh profileSetup.sh -Dprofile=api-devportal
Start the server sh wso2server.sh -Dprofile=api-devportal
Create a user with internal/publisher and internal/creator roles
Log in to the devportal.
This seems to be a bug. Kindly let us know how we can proceed further.

**Comment by SuKSW** [comment]
Fixed by https://github.com/wso2/product-apim/pull/10720

**Comment by rmsamitha** [comment]
Closing as fixed
