### ISSUE TITLE
Unable to delete a API category without removing category from the API

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10448]
### Description:
User is unable to delete an API category from the Admin Portal without removing category from all the API the said category is added.

![image](https://user-images.githubusercontent.com/32265029/112509221-7fbca600-8d4d-11eb-9d42-4c0992714e94.png)

### Steps to reproduce:
Create an API category
Add the category to the APIs in publisher
Try to delete the API category from Admin portal

### Affected Product Version:
API-M 4.0.0 

#### Suggested Labels:
API-M 4.0.0

**Comment by dushansilva** [comment]
closing this issue since this is the expected behaviour
