### ISSUE TITLE
Admin portal label changes cannot be done on the fly

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#10458]
### Description:
Changing the en.json of the admin portal does not have any effect. This was previously fixed for the Publisher. But the issue remains on the admin portal.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by npamudika** [comment]
Tested this in the APIM 4.0.0 latest pack (9.0.148-SNAPSHOT), and the values of the properties in the en.json file were updated correctly on the fly, without needing a server restart.

Checked for random property values.

Hence closing the issue.
