### ISSUE TITLE
API resources required to create API Product are not displayed

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10451]
### Description:
When attempting to create an API Product via the Publisher UI, when navigating to the API Selection window in order to select the resources that need to be added to the API Product, no resources are displayed when selecting a respective API as shown below

![image](https://user-images.githubusercontent.com/6614042/112572012-43517e80-8e0f-11eb-8fbf-97f30eff18dc.png)

This issue wasnt noticed in 9.0.77.SNAPSHOT, but this is occurring in the 9.0.79.SNAPSHOT.

### Steps to reproduce:
1. Follow the documentation https://apim.docs.wso2.com/en/latest/learn/design-api/create-api-product/create-api-product/ and import APIs via Swagger URL by copying the link location of the respective Swagger files attached in the docs(https://apim.docs.wso2.com/en/3.2.0/assets/attachments/learn/customer-info-api.yaml and https://apim.docs.wso2.com/en/3.2.0/assets/attachments/learn/leasing-api.yaml)

2. Create and API Product and attempt to add resources from the above created APIs. 

### Affected Product Version:
9.0.79.SNAPSHOT

**Comment by uvindra** [comment]
In 9.0.77 UI will send a request to api/<api-id>/swagger to download the Swagger file of the API so that resources can be displayed, when the respective API is selected. 

The API call is not being sent in 9.0.79 it seems by the UI.

**Comment by RakhithaRR** [comment]
This issue is fixed in the latest code. 
https://github.com/wso2/product-apim/issues/10439

**Comment by uvindra** [comment]
Closed because this is a duplicate of https://github.com/wso2/product-apim/issues/10439
