### ISSUE TITLE
It's difficult to identify when the server has finished starting  up

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#10459]
### Describe your problem(s)
It's difficult to identify when the server has finished starting  up. If we can add a log saying "Server started" or maybe have the portal URLs come to the end of the process it's better.

### How will you implement it

---

**Comment by malinthaprasan** [comment]
Due to the async nature of some of the steps of the server startup, this is complex to implement and we don't have a way to determine 100% whether the server is started or not.
