### ISSUE TITLE
integration with billing engine

### ISSUE THREAD

**Issue by webroboteu** [wso2/product-apim#1045]
In relation to integration with the billing-engine  can you find out how the subscription plans are defined so that it can automatically synchronize with the billing system? 
The example gives the user the ability to create plans but this must be the responsibility of the publishers of the api, not to those who consume it.

I would also like to integrate the billing system directly on the store but I see that the old instance is no longer functioning because the  code are change below

**Comment by chamilaadhi** [comment]
Hi,
You could use sample billing system source code for following versions
For AM 1.10: https://github.com/chamilaadhi/wso2-am-billing-engine/tree/am-1.10
For AM 2.0:  https://github.com/chamilaadhi/wso2-am-billing-engine/tree/am-2.0 .

Chamila
