### ISSUE TITLE
API Product | trying to add a duplicate resource is breaking the flow

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10455]
### Description:
If the user tries to add two resources with same attributes like the following, it will display an error.
_"API Product resource: /*, with verb: GET , is duplicated for id admin-EuropeVehicles"_
![image](https://user-images.githubusercontent.com/32265029/112587582-12dff500-8dbb-11eb-884e-a6ab620a0085.png)

However there after if user delete the duplicated resources and tries to add the valid resources, there is an error.

![chrome-capture (13)](https://user-images.githubusercontent.com/32265029/112588145-22ac0900-8dbc-11eb-951f-d80de89d30df.gif)

Console error:
```
[2021-03-26 11:16:34,099] ERROR - GlobalThrowableMapper Unrecognized property 'websubSubscriptionConfiguration'
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "websubSubscriptionConfiguration" (class org.wso2.carbon.apimgt.rest.api.publisher.v1.dto.APIProductDTO), not marked as ignorable (39 known properties: "securityScheme", "monetization", "revisionedApiProductId", "name", "businessInformation", "policies", "state", "visibility", "createdTime", "revisionId", "subscriptionAvailability", "accessControl", "id", "categories", "enableSchemaValidation", "enableStore", "scopes", "responseCachingEnabled", "accessControlRoles", "isRevision", "authorizationHeader", "transport", "visibleRoles", "testKey", "context", "provider", "hasThumbnail", "apiThrottlingPolicy", "apiType", "visibleTenants", "additionalProperties", "description", "subscriptionAvailableTenants", "cacheTimeout", "corsConfiguration", "tags", "gatewayEnvironments", "lastUpdatedTime", "apis"])
 at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 1960] (through reference chain: org.wso2.carbon.apimgt.rest.api.publisher.v1.dto.APIProductDTO["websubSubscriptionConfiguration"])
```
### Steps to reproduce:
Create two APIs with GET /* resources
Create an API product and add above two resources
Delete the resources and add valid resources to the API product.

### Affected Product Version:
API-M 4.0.0 

### Environment details (with versions):
- OS: windows 10
- DB: MSSQL 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by RakhithaRR** [comment]
This is not reproducible in the latest pack. Similar issues have been reported in https://github.com/wso2/product-apim/issues/10300 and https://github.com/wso2/product-apim/issues/10214. Those have been fixed by https://github.com/wso2/carbon-apimgt/pull/10095. Hence closing this issue.
