### ISSUE TITLE
API Product Try out page selects Sandbox as Key Type by default

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10463]
### Description:

In DevPortal, API Product Try out page selects Sandbox as Key Type  by default
![image](https://user-images.githubusercontent.com/32265029/112671116-05f4ed00-8e1f-11eb-9974-5212a5ef017c.png)

### Steps to reproduce:

- Create a API Product
- Go to DevPortal
- Click on API Product
- Go to Try out Page

### Affected Product Version:
API-M 4.0.0

#### Suggested Labels:
API-M 4.0.0

**Comment by Jayanie** [comment]
This issue has been fixed in the latest. But there is an alignment issue between `Key Type and Production` as follows.

![Screenshot from 2021-04-10 12-22-54](https://user-images.githubusercontent.com/35601987/114262984-84958100-9a00-11eb-9f88-d48739dd605b.png)
