### ISSUE TITLE
Refactor Publisher, Admin, & Devportal theming directory and file name

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10460]
### Describe your problem(s)

We have to make the theming procedure/story constant across all the three portal and update the docs,

What we have to do is:

- Change the name of the default theme file in the `/site/public` directory as `userTheme` to eliminate the confusion between `defaultTheme.js` file in the `/source` directory

- Put the `userTheme.js` file inside `/site/public/theme/` directory

**Comment by Mariangela** [comment]
@tmkasun , thanks loads for logging this Git issue based on our offline discussion.

**Comment by malinthaprasan** [comment]
Closing as per above commit message
