### ISSUE TITLE
Unable to delete the old configuration for abnormal request per minute under the configure alert in Dev portal

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#10474]
### Description:
Unable to delete the old configuration for abnormal request per minute under the configure alert in Dev portal, getting error as 'Error while deleting the configuration'

### Steps to reproduce:

1. Configure the API Manager Analytics with API Manager 3.2.0
2. Go to the publisher portal and publish an API. (PizzaShackAPI)
3. Go to the dev portal and create an application. (TEST_APP)
4. Subscribe to the PizzaShackAPI with TEST_APP.
5. Go to the Configure Alerts section in dev portal and check Abnormal Requests per Minute alert type and configure the PizzaShackAPI with TEST_APP.
6. After configuring the alerts, delete the relevant application.
7. Go back to the Configure Alerts section and will notice that the application name has been missed and alert configuration is there even after deleting the application.
8. Try to delete the alert configuration will get the error.

**The same issue can be observed if the API deleted instead of the application**

### Affected Product Version:
APIM-3.2
APIM-Analytics-3.2

---
#### Related Issues:
Another issue was observed as a result of the same cause (existence of the API/Application after removing the Alert configuration). This issue can be reproduce by following the below steps.

1. Follow up to the 7th step given above.
2. Try to update **Manage Alert Subscription** (by changing any field) of the devportal and click on save.
3. Will prompt an error on the UI.
4. Log in to the Admin portal and and go to the **Manage Alerts** section.
5. Try to update anything and click on save.
6. Will prompt the same UI error in here as well.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
