### ISSUE TITLE
Topics are not listed in the new overview page for webhooks APIs

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10470]
### Description:
The overview page does not have to list of topics defined in an webhooks API

<img width="1311" alt="Screen Shot 2021-03-29 at 9 25 25 AM" src="https://user-images.githubusercontent.com/6702569/112785217-1f8d7300-9071-11eb-9ab0-60738b4320ac.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by lasanthaS** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10078, hence closing.
