### ISSUE TITLE
Unable to invoke the API with token generated prior to deploying

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10486]
### Description:
If a user creates an API and publish it. Without deploying, subscribe to an App and generate the token, then deploy the API. With the previously generated token user is unable to invoke the API.
![image](https://user-images.githubusercontent.com/32265029/112873194-2a96d200-9076-11eb-86d0-555ee7312198.png)

### Steps to reproduce:

- Create an API without publishing
- Go to overview page and publish
- Go to devPortal and subscribe to an App
- Generate the token
- Go to Publisher and deploy the API
- Go to the devportal again and go to try out page
- Invoke the API with previously generated token

### Affected Product Version:
 API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB : MSSQL 2019

#### Suggested Labels:
 API-M 4.0.0, Priority/High

**Comment by Krishanx92** [comment]
This is not observe in latest pack.
