### ISSUE TITLE
[UX] Extra empty space in API listing

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#10496]
### Description:
$subject

![image](https://user-images.githubusercontent.com/3960742/112937688-b75c9100-9145-11eb-87cc-549b783c8b5a.png)

This is on Mac standard resolution.

**Comment by erangatl** [comment]
This is how it shows in Big Sur default resolution (1680*1050)
Cards has a fixed width and space after will differ according to the resolution and pagination per page count
![image](https://user-images.githubusercontent.com/20179540/113723120-a811b080-970e-11eb-9533-4ce527c91510.png)

At 1600 resolution bit of space is left over as it is not enough to accommodate a card.
![image](https://user-images.githubusercontent.com/20179540/113742518-52de9a80-9720-11eb-9776-7796b956cd50.png)


This is at 1920 * 1200 resolution - 10 per page
![image](https://user-images.githubusercontent.com/20179540/113740034-f8dcd580-971d-11eb-87eb-aedd82cab4e2.png)

This is at 1920 * 1200 resolution - 15 per page
![image](https://user-images.githubusercontent.com/20179540/113740376-46594280-971e-11eb-94b1-c96794dad810.png)

**Comment by bhathiya** [comment]
Mine has the default resolution, but with the dock on the left instead of bottom. That reduces the screen width a bit. That must be the reason for this. However, I think we should make it responsive. Can't we make the card size variable? @tmkasun
