### ISSUE TITLE
Internal server error when mapping ARNs to Resources

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10497]
### Description:
Internal server error comes up when adding a new Resource with function ARN mapping for AWS Lambda API as mentioned in https://apim.docs.wso2.com/en/next/tutorials/create-and-publish-awslambda-api/#step-3-map-function-arns-to-resources

Related issue: https://github.com/wso2/product-apim/issues/10110

**Comment by Nirothipan** [comment]
I also experienced the same
![Uploading Screenshot from 2021-03-30 11-32-14.png…]()

**Comment by Nirothipan** [comment]
I also experienced the same

![Screenshot from 2021-03-30 11-32-14](https://user-images.githubusercontent.com/24619763/112941099-af9feb00-914b-11eb-8da5-9d10de8cbe78.png)

**Comment by RakhithaRR** [comment]
When observing the logs of the distributed setup, I could observer the same stack trace mentioned in https://github.com/wso2/product-apim/issues/10110#issuecomment-800193864. This issue is not present in the latest pack since its fixed with https://github.com/wso2/carbon-apimgt/pull/10143. Hence this issue can be closed.
