### ISSUE TITLE
[Streaming API][Publiher] Text boxes are not reset when adding payload properties

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-apim#10499]
### Description:
When adding payload properties to the topics in WebSub APIs, the text boxes are not getting rest after clicking add 

![image](https://user-images.githubusercontent.com/5134757/112937948-4c5f8a00-9146-11eb-8152-7236daf60131.png)

**Comment by lasanthaS** [comment]
Fixes by https://github.com/wso2/carbon-apimgt/pull/10172, hence closing.
