### ISSUE TITLE
Self signup fails with an error

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#10490]
### Description:

Can't self signup from the signin/signup window of `/admin` portal. Says `Unexpected error`
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2655553/112936627-cb9f8e80-9143-11eb-9e2e-cdfcbfa0f5dd.png">

### Steps to reproduce:
- Visit `/admin`
- In the login window click create account
- Give a username and proceed
- Observer the error
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): APIM Test setup

**Comment by tharindu1st** [comment]
This was due to the localhost not available in Certificate of its own node
