### ISSUE TITLE
[Publisher][UI] Shows two vertical scroll bars when the page is long

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#10503]
### Description:

Two scroll bars are displayed when the page is long.
![Screenshot - 2021-03-30T105728 231](https://user-images.githubusercontent.com/10165411/112938424-31d9e080-9147-11eb-944c-5d0d28cc8ce4.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by binodmx** [comment]
It also shows a scroll bar in side bar when the page is long.
