### ISSUE TITLE
[Streaming API] Unable to delete WebSocket topics in the Publisher UI

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-apim#10501]
### Description:
WebSocket topics cannot be deleted.

### Steps to reproduce:
1. Create a WebSocket Streaming API.
2. In addition to the existing `/*` topic, create another topic.
3. Click on save, and reload the page.
4. Try deleting any of the topics, they won't get deleted.

**Comment by dushansilva** [comment]
looks like this is fixed in latest pack, hence closing
