### ISSUE TITLE
Custom scope assignments fails with 401

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10502]
When trying to do https://github.com/wso2/product-apim/issues/10493, getting a 401 response without the body.

Please find the attached har(please rename and remove the .txt extension).

[apislb.apim.com.har.txt](https://github.com/wso2/product-apim/files/6226361/apislb.apim.com.har.txt)

**Comment by malinthaprasan** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10498
