### ISSUE TITLE
Redundant Life Cycle option for prototype APIs

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#10505]
### Description:
Need to remove the redundant `Deploy as Prototype` button from UI. Refer the image given below: 

![prototype](https://user-images.githubusercontent.com/19728269/112938464-44ecb080-9147-11eb-9a1a-fbd7462c14b2.png)

(Need to recheck the Life cycle diagram. Diagram shows the API can be either published or demote to created. But the `Publish` button is disabled)

### Steps to reproduce:
Deploy an API as prototype and navigate to Lifecycle section

**Comment by malinthaprasan** [comment]
There's a transition in registry APILifecycle.xml :
`<transition event="Deploy as a Prototype" target="Prototyped"/>`
This can be removed.
