### ISSUE TITLE
[Aws Lambda] Unable to proceed Using stored AWS credentials 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#10500]
### Description:
The save button is inactive after filling the details

![Screenshot from 2021-03-30 10-57-21](https://user-images.githubusercontent.com/24619763/112938155-ba0bb600-9146-11eb-95ed-d2843b404439.png)

**Comment by RakhithaRR** [comment]
Observed the same issue. It seems the only was to proceed is if we define an Endpoint during the initial API creation step. Looks like UI validation does not happen properly.

**Comment by tmkasun** [comment]
I see, I got the same issue
https://github.com/wso2/product-apim/issues/10522
