### ISSUE TITLE
Password policies not giving error until the last step

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-apim#10516]
### Describe your problem(s)
When creating a new user with the Carbon Console, it's giving the password policy-related error when the user clicks on the Finish button. 
![image](https://user-images.githubusercontent.com/8156185/112939032-6c904880-9148-11eb-8bec-fa39ba661618.png)
When the user clicks the Ok button, all the filled data is gone and the user is redirected to the user list page. 
The ideal scenario would be to give the error on the first page,
![image](https://user-images.githubusercontent.com/8156185/112939202-b0834d80-9148-11eb-995d-d5d428acfad2.png)
This page is giving some errors, but they are not synced with the updated password policy. 
![image](https://user-images.githubusercontent.com/8156185/112939259-ca249500-9148-11eb-8de4-4e29cf7f2a04.png)

### Describe your solution
Give the same error message given at the end of the wizard at the first page of the wizard

**Comment by malinthaprasan** [comment]
It seems this is not reproduced in the distributed setup now.
Password is validated in both UI and backend side. There are two regexes for validations in place in configurations. There might be configuration issue earlier.

```
<Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>
<Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
```
