### ISSUE TITLE
Gateway list dropdown doesn't populate for GraphQL APIs

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#10517]
### Description:
When trying out a GQL API in devportal, the gateway drop-down list is empty.

![Screenshot 2021-03-30 at 11 07 25](https://user-images.githubusercontent.com/13759167/112939329-e6283680-9148-11eb-832b-5ad35e2bf5e4.png)

**Comment by malinthaprasan** [comment]
Reproducible

**Comment by prasa7** [comment]
Issue reproduced.

**Comment by prasa7** [comment]
Fixed with https://github.com/wso2/product-apim/issues/10517

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10183 hence closing
