### ISSUE TITLE
Login to publisher portal with publish and create roles gives 403 forbidden error

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10519]
### Description:
1. Create a user
2. Create a role which has publish and create permissions 
3. Assign that role to the user
4. Login to the publisher portal using that user credentials.
5. 403 Forbidden error is given

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Vathsan** [comment]
Encountered the same issue even after assigning the super admin permissions.

**Comment by shaniR** [comment]
Looks like the Internal/publisher has to be assigned to the user.

**Comment by wasuradananjith** [comment]
From APIM 4.0.0 onwards carbon permissions do not have an impact when performing tasks (such as Login etc). Hence closing this issue.
