### ISSUE TITLE
Do we need rivision selector for lifecycle tab

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10518]
Since there is no difference in lifecycles is it required to show revision selector for this page?

![image](https://user-images.githubusercontent.com/1345278/112939335-e9232700-9148-11eb-992b-6db307e1676e.png)

**Comment by Krishanx92** [comment]
It's to keep the consistency, and also if someone comes to the lifecycle page and then the user need to change the revisions user should able to do this. This is expected.
