### ISSUE TITLE
Publisher test console says API is not deployed when a revision is selected

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10514]
Since revisions are already deployed, this is not expected. 

![image](https://user-images.githubusercontent.com/1345278/112939072-7ade6480-9148-11eb-8a5d-4f2a75415386.png)

**Comment by rmsamitha** [comment]
@Krishanx92 Shall we close this since this is stated as duplicate in https://github.com/wso2/product-apim/issues/10535 ?

**Comment by malinthaprasan** [comment]
Return the particular API revision's deployment when getting `https://localhost:9443/api/am/publisher/v2/apis/:revisionId/deployments`
