### ISSUE TITLE
[UX] UX issues in the revisions page

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#10511]
### Describe your problem(s)
![image](https://user-images.githubusercontent.com/3960742/112938699-bc224480-9147-11eb-9c0b-a0d5dda696b3.png)

1. Isn't it better to have a deploy "this" revision button here?

2. Since the column name is "deployed revision" (past tense) it's not intuitive that we can "do" deploy here.

**Comment by Krishanx92** [comment]
> ### Describe your problem(s)
> ![image](https://user-images.githubusercontent.com/3960742/112938699-bc224480-9147-11eb-9c0b-a0d5dda696b3.png)
> 
> 1. Isn't it better to have a deploy "this" revision button here?
User can not directly deploy revision unless he selects the gateway/URLs, So we cant add the deploy option there the the users will confuse if we put the deploy option in multiple places

> 2. Since the column name is "deployed revision" (past tense) it's not intuitive that we can "do" deploy here.
Yes, since this column shows both **deployed revision**(Once deployed revision it will show the deployed revision) and **deploy option**(Deploy existing revision), How about change column name to **Manage revision**

**Comment by bhathiya** [comment]
1) Can't we open the same window (but filled) that's opened by the "Deploy new revision" button? To me, it looks natural to have a "deploy" button for each revision because that's what we really deploy at the end. 

2) How about just "API Revisions"?

**Comment by bhathiya** [comment]
Regarding 1, yes, having "deploy" in multiple places can be confusing. IMO what we should remove is the button from the table below and just show "deployed revisions" there. On the other hand, if someone wants to deploy a revision in all gateways, we need a lot of deploy clicks in that table. If we use the same pop up as I said, we only need 1 deploy click.  WDYT?

**Comment by bhathiya** [comment]
@tmkasun

**Comment by erangatl** [comment]
> Regarding 1, yes, having "deploy" in multiple places can be confusing. IMO what we should remove is the button from the table below and just show "deployed revisions" there. On the other hand, if someone wants to deploy a revision in all gateways, we need a lot of deploy clicks in that table. If we use the same pop up as I said, we only need 1 deploy click. WDYT?
> 
In the UX review we agreed to show deploy button only on the table as it was straight forward and caters the Pareto principle.
Yes, edge cases like user deploy a revision in all gateways, it will be a burden  to the user.

**Comment by bhathiya** [comment]
Since we think the current way is fine, I'll close the issue.
