### ISSUE TITLE
Link for forget password does not work

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/product-apim#10525]
### Description:
$subject. When click on the **Forget Password** link on the login screen, the portal navigates to the following page.

![Screenshot 2021-03-30 at 11 15 58](https://user-images.githubusercontent.com/12485208/112939560-51720880-9149-11eb-8466-2a707c274a3c.png)

**Comment by YasasRangika** [comment]
This issue is not reproducing in latest build of APIM (9.0.107 components). Hence we can close this issue.

**Comment by malinthaprasan** [comment]
This has happened due to a config issue
