### ISSUE TITLE
Scope Assignment fails intermittently under the load

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#10528]
### Description:
While the team stress testing on 30th March the adding new scope mapping fails intermittently.

### Steps to reproduce:
1. Create raji_subscriber role with relevant permission for subscriber
2. Assign a user to that role
3. Log in to admin portal and try to add role mapping for the role using internal/subscriber
4. Alert pops up saying something went wrong
5. This happens frequently but sometimes it gets successful

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This was an edge case where multiple admins logged in into same time to admin portal and change the scope mapping at same time.
