### ISSUE TITLE
API filter button is missing in Publisher

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10521]
### Description:
API filter button is missing in Publisher. There should be a way for users to filter the APIs in publisher.

<img width="540" alt="Screen Shot 2021-03-30 at 11 13 58 AM" src="https://user-images.githubusercontent.com/32265029/112939433-15d73e80-9149-11eb-85e9-117b632e9198.png">
<img width="540" alt="Screen Shot 2021-03-30 at 11 14 12 AM" src="https://user-images.githubusercontent.com/32265029/112939444-18d22f00-9149-11eb-90c5-e95e7d377390.png">

### Affected Product Version:
API-M 4.0.0

#### Suggested Labels:
API-M 4.0.0

**Comment by tmkasun** [comment]
We had a UI level filtering in the table view, Since REST API does not support such sorting, we have removed it until we get REST API support 
@malinthaprasan do we have any plans to add field wise sorting for apis list

**Comment by malinthaprasan** [comment]
This is not currently supported. We'll consider to implement this in near future for REST API.

**Comment by Krishanx92** [comment]
Currently on-hold.  we'll consider this once theres any requirement.
