### ISSUE TITLE
UI error when deploying sample API tenant creator user

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#10520]
### Description:
The following error is displayed when a tenant creator clicks on Deploy sample API.

When the page is reloaded the sample API has been deployed.

<img width="1615" alt="Screenshot 2021-03-30 at 11 07 43 AM" src="https://user-images.githubusercontent.com/19324135/112939375-fb9d6080-9148-11eb-8cf1-c08790cf34a3.png">

### Steps to reproduce:
Create a tenant
Create a creator user under tenant domain
Login to publisher portal and deploy sample API

### Affected Product Version:
APIM-4.0.0

**Comment by tmkasun** [comment]
![image](https://user-images.githubusercontent.com/3313885/113421687-286fa300-93e9-11eb-8190-ff716bc6989d.png)

Fixed in https://github.com/wso2/carbon-apimgt/pull/10196
Now creators will only see creating and updating API status
