### ISSUE TITLE
Comments with Foriegn Characters are not getting added correctly

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#10530]
### Description:
Try adding Hindi, Chinese characters to comments. The comments are not getting displayed properly. 

For example;
If you add as a comment,
我们的传家宝丨焦裕禄精神 习语典读丨和羹之美
王毅：中阿合作灌装中国疫苗为地区和全球抗疫作出新贡献
扫黑除恶专项斗争网上展览馆上线 奋斗百年路 启航新征程
王毅：西方一些国家的人权观并不代表国际人权观

It will be added as below.

![image](https://user-images.githubusercontent.com/25246848/112939837-cba28d00-9149-11eb-9b5f-6a867dd0a237.png)

For more examples refer to the full screenshot below.

![image](https://user-images.githubusercontent.com/25246848/112939890-e37a1100-9149-11eb-968a-05e6a8e895ee.png)

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS
- Web browser: Chrome

**Comment by malinthaprasan** [comment]
This should be because of the mysql deployment that was tested was having latin1 characterset.  There is a problem with upgrading it to unicode due to this issue [1]

[1] https://github.com/wso2/product-apim/issues/10147
