### ISSUE TITLE
Add new scope mapping - role search UI bug

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#10538]
### Description:

Two overlapping resulting dropdowns are displayed when type few letters and try to search for a mapping role (scope) in admin portal when trying add new role alias mapping.

![scope-role-mapping-search](https://user-images.githubusercontent.com/2484781/112940426-c2fe8680-914a-11eb-9393-f0125faf724f.jpg)

### Steps to reproduce:
1. Login to admin portal
2. Go to Scope Assignments >  Click "Add scope mapping"
3. Provide a name > Click "Next"
4. Under "Select permissions" select "Role Alias"
5. In "Mapping Role" search box type "internal"

You will see two overlapping resulting dropdowns. (here you have to select the role u prefer). This is confusing. Need to remove one drop down list.
![scope-role-mapping-search](https://user-images.githubusercontent.com/2484781/112940385-b5490100-914a-11eb-9985-3e6bdb917b80.jpg)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Seems like first overlay is coming from the browser (previously typed values as suggestions)
