### ISSUE TITLE
[AWS Lambda] Unable to Use Test Console

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#10533]
### Description:
After creating the Lambda in APIM, unable to test in publisher. Seems the call hasn't reached lambda

![Screenshot from 2021-03-30 11-24-59](https://user-images.githubusercontent.com/24619763/112940324-9cd8e680-914a-11eb-82d4-6a9e2679b06a.png)

**Comment by tmkasun** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/10478 hence closing the issue
