### ISSUE TITLE
Adding description to new revision is lagging

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10539]
### Description:
Below situation can be experienced when trying to add description to new revision in deployments page. The changes what we made is late to reflect in text box. It can not see any latency in other text boxes in same deployment.
![Peek 2021-03-30 11-13](https://user-images.githubusercontent.com/28702407/112940210-761ab000-914a-11eb-9e54-cfab08f93ad6.gif)

### Steps to reproduce:

- Create new API
- Go o deployment page
- Try to add description to new revision

### Affected Product Version:
APIM 4.0.0

### Environment details (with versions):
"APIM Distributed Testing  - 2 hour session" environment

---
#### Suggested Labels:
APIM 4.0.0

**Comment by Krishanx92** [comment]
Duplicate: https://github.com/wso2/product-apim/issues/10609
