### ISSUE TITLE
Revision deletion option is provided in deploy menu

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10537]
If no revision is reached 5, it asks to remove the existing g revision. But the option is provided in the deply menu. and looks it is misleading and no option to remove. 

![image](https://user-images.githubusercontent.com/1345278/112940523-df9abe80-914a-11eb-973a-998c0b7b439a.png)

**Comment by Krishanx92** [comment]
When user needs to delete revision when maximum revision count reached user need to select the revision in the drop down menu,
There's misleading term **Please delete** should be corrected as **Please select to delete**.
We will fix this separately, hence closing this issue.
