### ISSUE TITLE
Publisher Portal properties with unnecessary expanding section 

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-apim#10542]
### Describe your problem(s)
In the Publisher Portal -> Runtime Configurations, the Response Caching property under the Response sections, that property has a carrot icon to expand the section, but there's an only single property in that section. In the other sections of that page with single property does not have this carrot icon. SInce, it has only a single property there's no need to have this button to expand it (no expanding is needed)

![image](https://user-images.githubusercontent.com/8156185/112940797-4a4bfa00-914b-11eb-82b0-545053250f80.png)

### Describe your solution
Remove the expanding button from the Response Caching property.

**Comment by tmkasun** [comment]
There is an input field that appears when the response caching is enabled, so can't remove the icon, But here and also in the CORS configuration section there is a UX issue that this icon is visible even when the configuration switch is off or disabled.

![image](https://user-images.githubusercontent.com/3313885/114268485-f8468680-9a1e-11eb-8af5-a5a2dfdf98b3.png)


We should hide the `carrot icon` (down arrow) when the config is disabled and if enabled show both arrows (upward & downward)
