### ISSUE TITLE
External Reference Id Help description is invalid

### ISSUE THREAD

**Issue by rosensilva** [wso2/product-apim#10541]
### Description:
Description of the **External Reference Id** is displayed as a Sample description of the attribute

### Steps to reproduce:
1) Create Hello world App using doc: https://apim.docs.wso2.com/en/next/get-started/quick-start-guide/quick-start-guide/
2) Subscription & Key Generation Wizard in the devportal shows wrong description for the **External Reference Id** 
<img width="1028" alt="Screenshot 2021-03-30 at 11 28 55" src="https://user-images.githubusercontent.com/13344872/112940777-44eeaf80-914b-11eb-9e9d-b0610de52949.png">

### Affected Product Version:

API-M 4.0.0
### Environment details (with versions):
- OS: macOS BigSur
- Client: Safari
- Env (Docker/K8s): VM

---

**Comment by tharindu1st** [comment]
This was a deployment related issue
