### ISSUE TITLE
When the resource policies are switched to API level policy, it is applied without a revision.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#10547]
### Description:
When there are some resource policies added and deployed within the gateway it works as expected. (revision deployment is required to make that resource policy enabled)

When I switched the resource policy to an API policy, it gets applied without a revision deployement.

### Steps to reproduce:

Create two policies such that API level policy < resource level policy.
Create an API 
Add resource level policy
Deploy it and Make sure it is functioning
Then change it to API Level Policy. (but do not deploy)
Invoke the API till API level policy is met. 

### Affected Product Version:
4.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
AFAIK this is a known behavior, Do we have a proper solution to this?
@tharindu1st  @CrowleyRajapakse

**Comment by malinthaprasan** [comment]
This will be handled after beta is released
