### ISSUE TITLE
[Aws Lambda] No response when invoked

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#10540]
### Description:
When invoking an api configured with lamda, no response is received. Please note that I disable security for the API.
The same payload works n aws console without any issue.

**Comment by RakhithaRR** [comment]
Observed the same issue with security enabled as well.

**Comment by RakhithaRR** [comment]
Related issue: https://github.com/wso2/product-apim/issues/10478

**Comment by tmkasun** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/10478 hence closing the issue
