### ISSUE TITLE
Error when Creator user adds comment to API in publisher

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#10544]
### Description:
The following blank error pop up is displayed when a creator user adds a comment the API in Publisher portal.
<img width="1644" alt="Screenshot 2021-03-30 at 11 22 26 AM" src="https://user-images.githubusercontent.com/19324135/112941022-99922a80-914b-11eb-919b-d221cef3e527.png">

### Steps to reproduce:
Create a creator user in tenant domain
Create an API
Add a comment

**Comment by erangatl** [comment]
Publisher user also gets the same error

**Comment by prasa7** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10225
