### ISSUE TITLE
Remove tests step from non-REST APIs?

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#10543]
### Describe your problem(s)

Can we remove the test step from non-REST APIs? Or at least mention it's not supported?  

![image](https://user-images.githubusercontent.com/3960742/112940974-867f5a80-914b-11eb-8f1d-3d19cf052c33.png)

**Comment by bhathiya** [comment]
Is there any reason for using a yellowish green  colour? If not, how about using some "clean" green colour? (eg. #9eef75)

![image](https://user-images.githubusercontent.com/3960742/112945349-cc3f2180-9151-11eb-8de1-90d28e8ccdc3.png)

**Comment by malinthaprasan** [comment]
For graphql this is already removed (graphiQL UI is not yet supported). We might be able to do the same here.

**Comment by erangatl** [comment]
> Is there any reason for using a yellowish green colour? If not, how about using some "clean" green colour? (eg. #8ed868)
> 
> @erangatl
> 
> ![image](https://user-images.githubusercontent.com/3960742/112945658-33f56c80-9152-11eb-9499-fe1f4ce62ee4.png)

we can change it to default MUI light colors and make it configurable 
![image](https://user-images.githubusercontent.com/20179540/114217177-77877c00-9985-11eb-8246-def3decdf4b8.png)

**Comment by bhathiya** [comment]
This looks good.

**Comment by tmkasun** [comment]
Fixes 
![image](https://user-images.githubusercontent.com/3313885/114266567-8ff2a780-9a14-11eb-91fb-b5e5c419b4ea.png)
