### ISSUE TITLE
Can not create an account(Self Register) via the login page

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/product-apim#10558]
### Description:
$subject. 

### Steps to reproduce:
- Navigate to the login screen of the dev portal
- Click on the **Create Account** link
- Provide a name for the account
- Click **Proceed to Self Register** button
- You will be redirected to the following page

![Screenshot 2021-03-30 at 11 50 20](https://user-images.githubusercontent.com/12485208/112943029-951b4100-914e-11eb-89ff-2fad6976259f.png)

**Comment by Shehanir** [comment]
Issue is not reproducing. Hence closing
