### ISSUE TITLE
Add New Scope Button Colour Seems to be invisible

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#10559]
### Description:
When trying to create a shared scope the button seems like disabled although I used correct admin user. but can click and go inside and create a new shared scope.

<img width="1650" alt="Screenshot 2021-03-30 at 11 46 34" src="https://user-images.githubusercontent.com/23296184/112942994-892f7f00-914e-11eb-973a-a02a6dbb0953.png">

**Comment by tmkasun** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/10566 hence closing the issue
