### ISSUE TITLE
[Streaming API] Cannot update and save the endpoint urls in websoket

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-apim#10551]
### Description:
After creating a Websocket endpoint, the endpoint URLs cannot be changed and save.

### Steps to reproduce:

1. Create a WebSocket endpoint
2. go to the endpoint tab
3.  update the Urls, and try to save

**Comment by dushansilva** [comment]
Looks like this is fixed in latest pack therefore closing issue
