### ISSUE TITLE
Cannot Save Prototype Implementation

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10565]
### Description:
When trying to add a mock implementation for a resource, the "Save" button is disabled. So cannot save an edited mock implementation
![mockendpoint](https://user-images.githubusercontent.com/30455603/112943625-5afe6f00-914f-11eb-9917-25a56289db34.png)

### Steps to reproduce:
1. Login to Publisher
2. Create an API without adding an Endpoint
3. Go to Endpoints tab and Select Prototype Implementation
4. Open the implementation editor and add a prototype implementation
5. Try to "Save". The "Save" button is disabled

**Comment by RAVEENSR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10160
