### ISSUE TITLE
[DevPortal][UI] Business owner is blocked in the devportal UI

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#10569]
### Description:
The business owner of the API is blocked in the API overview

![image](https://user-images.githubusercontent.com/25485783/112944320-4a9ac400-9150-11eb-918e-21f2ba15d6bc.png)

### Steps to reproduce:
1. Create an API with a business owner
2. Publish to devportal
3. Open the overview of the API from the devportal

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by tmkasun** [comment]
Fixed with the new design 
PR: https://github.com/wso2/carbon-apimgt/pull/10162
