### ISSUE TITLE
Publisher Portal add tooltips to Endpoints action buttons

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-apim#10561]
### Describe your problem(s)
On the Endpoints page on Publisher Portal, to all the endpoint URLs, there are three action buttons. Those buttons are icons and there's no text for the buttons. Therefore, the users have no way to know what they do before clicking them. 

![image](https://user-images.githubusercontent.com/8156185/112943269-e62b3500-914e-11eb-9c16-8bd880427071.png)

### Describe your solution
Provide tooltips for those action buttons so that users would know what they do before clicking them.

**Comment by tmkasun** [comment]
This is already fixed in master hence closing the issue
