### ISSUE TITLE
Error displayed when trying to delete a parent comment (with a nested comment) as a Publisher user

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#10564]
### Description:
When deleting a parent comment with a nested comment, even though the comments are deleted you will get an error in the UI. (Tested as a Publisher user)

### Steps to reproduce:
1. Create an API and add a comment to it as a Publisher user.
2. Add another nested comment to the parent comment as shown below.
    ![image](https://user-images.githubusercontent.com/25246848/112943147-bd0aa480-914e-11eb-9b36-c2041ee4a70c.png)
3. Delete the parent comment. Even though the comment is deleted you will get an error as shown below in the UI.
![image](https://user-images.githubusercontent.com/25246848/112943212-d6135580-914e-11eb-90a7-eef7621da640.png)

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS
- Web browser: Chrome

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10144

**Comment by wasuradananjith** [comment]
> Fixed with [wso2/carbon-apimgt#10144](https://github.com/wso2/carbon-apimgt/pull/10144)

The issue which https://github.com/wso2/carbon-apimgt/pull/10144 addresses is the comment is not getting deleted. But what I face was, even though the comment is getting deleted the UI shows the error. I hope this will get solved with https://github.com/wso2/carbon-apimgt/pull/10144 as well.

**Comment by erangatl** [comment]
Yes it does

**Comment by wasuradananjith** [comment]
> Yes it does

Great thanks.
