### ISSUE TITLE
API properties of products are not visible in the dev portal

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10560]
API properties of products are not visible in the dev portal

![image](https://user-images.githubusercontent.com/1345278/112943155-c136c200-914e-11eb-9647-6a22b04a8419.png)
![image](https://user-images.githubusercontent.com/1345278/112943189-cbf15700-914e-11eb-82ef-276f940a2ad7.png)

**Comment by rmsamitha** [comment]
REST api GET /apis/{api_id} does't return the api propertis in the response.

**Comment by rmsamitha** [comment]
The same issue reported for APIs too in https://github.com/wso2/product-apim/issues/10111. The issue will be fixed once that is fixed. Hence closing.
