### ISSUE TITLE
Select API categories drop down list spread over the window

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10563]
### Describe your problem(s)
It will be easy to use this API Categories drop down list if we can change it as other drop down lists
(This happens with super user and further checking with tenant user, this was not reproduced)
![Peek 2021-03-30 11-51](https://user-images.githubusercontent.com/28702407/112943280-ea575280-914e-11eb-89f7-8a61eb5de33c.gif)

---
#### Suggested Labels:
APIM 4.0.0

**Comment by tmkasun** [comment]
@msm1992 

Try adding the following prop to select menu
```
MenuProps={{
                            anchorOrigin: {
                                vertical: 'bottom',
                                horizontal: 'left',
                            },
                            getContentAnchorEl: null,
                            keepMounted: true,
                            PaperProps: {
                                style: {
                                    maxHeight: 300,
                                },
                            },
                        }}
```

You can find example usage in API -> Details -> Endpoints -> AWS
