### ISSUE TITLE
VHost validation error lack of information

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10573]
### Description:

In case of a validation error, Create vhost popup goes away and only show an error message saying `Validation error`

![image](https://user-images.githubusercontent.com/3313885/112944917-28557600-9151-11eb-9315-c8f93a6251d6.png)

In the API response, it has the reason for the failure and needs to show the error in details
![image](https://user-images.githubusercontent.com/3313885/112945053-62bf1300-9151-11eb-9a47-967ead5935cd.png)

Otherwise, user get lost guessing what went wrong

**Comment by uvindra** [comment]
@SuKSW will be working on this
