### ISSUE TITLE
Application Keys (Consumer Key and Secret) are not available after restart.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#10577]
### Description:
After restart the application keys were not visible. (Super tenat was using at that moment). Then I generated keys again.
Using the newly generated key, the API cannot be invoked.

I was told that the cross tenant subscription is enabled during the restart. 

### Environment details (with versions):
- OS: MacOS Big Sur
- Browser: Chrome
- Env (Docker/K8s):

---

**Comment by chamilaadhi** [comment]
@VirajSalaka since there was a mistake in creating the keys on a different tenant, shall we close this?

**Comment by VirajSalaka** [comment]
Closing issue as it was occured due to my mistake.
