### ISSUE TITLE
UI issue when viewing a created API from a tenant account

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/product-apim#10581]
### Description:
$subject

### Steps to Reproduce
- Create a tenant and a user under that tenant
- Create an API via the publisher
- View it in Dev Portal

![Screenshot 2021-03-30 at 12 19 00](https://user-images.githubusercontent.com/12485208/112945889-7c148f00-9152-11eb-85a9-f7f9b3c7f23c.png)

**Comment by malinthaprasan** [comment]
Duplicated https://github.com/wso2/product-apim/issues/10215
