### ISSUE TITLE
Clicking on searched api listed in the dropdown does not open the API in Safari

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#10588]
![image](https://user-images.githubusercontent.com/15942605/112946746-8420fe80-9153-11eb-82e2-340a19d3ca52.png)

**Comment by mushthaq33** [comment]
Tried this in the latest pack in the pack with the Safari browser. Not getting reproduced

**Comment by tmkasun** [comment]
Yes, @mushthaq33  same here, I also can't reproduce this in the below Safari version

![image](https://user-images.githubusercontent.com/3313885/114296103-ea4c4080-9ac6-11eb-8c19-6c219e8f61e3.png)
