### ISSUE TITLE
Password validations should take at one place

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [wso2/product-apim#10586]
### Describe your problem(s)
When creating a user in APIM carbon console, the password validation takes in two places.

1. In **Step:1** -> for Ex. let's say password is '1234' it validates there and says "Password length should be within 5 to 30 characters" . 
![image](https://user-images.githubusercontent.com/17524063/112945028-58047e00-9151-11eb-9987-9afff5e945f9.png)

2. But if we give '12345' as the password, **Step:1** will takes forward and when we finish finally, it says the following error message when I click on finished.
![image](https://user-images.githubusercontent.com/17524063/112945449-ef69d100-9151-11eb-963d-3cd9454ce0c7.png)

### Describe your solution
I'm suggesting to make password validations at one place, in this case preferably at the Step:1

**Comment by malinthaprasan** [comment]
It seems this is not reproduced in the distributed setup now. 
Password is validated in both UI and backend side. There are two regexes for validations in place in configurations. There might be configuration issue earlier.
```
<Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>
<Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
```
