### ISSUE TITLE
Changes done in an Original API resource is not getting reflected in API Product

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10584]
### Description:
Changes done in an Original API resource is not getting reflected in API Product right away. User needs to go to the API Product -> Resources and click Edit Resources and just click Save to apply the changes to Product resources.

### Steps to reproduce:
Create APIs
Create an API product
Add a new scope to a resource of original API
Go to API product
Go to resources

### Affected Product Version:
API-M 4.0.0

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
This is the expected behaviour as per the current design. @tharindu1st to confirm

**Comment by tharindu1st** [comment]
@malinthaprasan @TheRasanjana  This was expected since API and APIPRoduct both can revision.
Since APIPRoduct was wire to base API.
