### ISSUE TITLE
Request count based throttling not working for GQL

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#10587]
### Description:

A subscription tier with 15 req per min did not throttle GQL API invocation.

**Comment by dushansilva** [comment]
I tried multiple times, This gets throttled out in about 16 or 17 requests, however i tried this in the all in one pack, in your scenario did it not get throttled out at all?

**Comment by fazlan-nazeem** [comment]
This was tested in the distributed setup. Not sure whether I was doing something wrong. If not reproducible you can close.

**Comment by dushansilva** [comment]
was not reproducible in distributed setup as well, hence closing issue
