### ISSUE TITLE
[Admin][Scope mapping] Can't add multiple scope mappings for rol

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#10589]
### Description:
When adding multiple scope mappings for role, the following error is shown. 

![image](https://user-images.githubusercontent.com/20040505/112946663-6eabd480-9153-11eb-8ae4-1501c641b57e.png)

**Comment by malinthaprasan** [comment]
This is not supported yet. Duplicate of https://github.com/wso2/product-apim/issues/10611
