### ISSUE TITLE
SOAP to REST API Invocation is failed.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#10599]
### Description:
API creation is successful but getting issues while trying to invoke the API through the swagger UI. I'm getting failed to fetch issue.
![image](https://user-images.githubusercontent.com/12996810/112947181-1de8ab80-9154-11eb-9c48-d40a3589a6e2.png)

CURL requests are working fine.

curl -X POST "https://gw.apim.com:8253/phoneverify1/1.0/checkPhoneNumber" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer eyJ4NXQiOiJZV1UyTVRsaFpXVXhNemRqTVdWbFl6a3hNRFZrWWpobU5qY3dabVF4TWpZMU5tRTFOell5WmprNE1XVTNORG--------" -d "{ \"CheckPhoneNumber\": { \"PhoneNumber\": \"string\", \"LicenseKey\": \"string\" }}" -k

{"CheckPhoneNumberResponse":{"CheckPhoneNumberResult":{"Valid":false,"OriginalNumber":"string","Wireless":false}}}

### Steps to reproduce:
Follow the instructions in the doc
https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/generate-rest-api-from-soap-backend/
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Did you accept the certificate of gateway from browser?

**Comment by malinthaprasan** [comment]
Duplicate https://github.com/wso2/product-apim/issues/10599
