### ISSUE TITLE
After adding devportal visibility roles, API is not visible in Publisher for searching

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#10597]
### Description:
After adding role based visibility for dev portal, API doesn't showup in search in publisher.

### Steps to reproduce:
1. Create two new role for publisher and creator (do not assign carbon permissions)
2. Create a new user and assign two roles
3. Assign Internal/creator and publisher scopes to the new roles from admin portal
4. Login to publisher by the user and create an API
5. Enable devportal visibility with a role which the user doesn't have
6. Try to search the API in the search bar. 
API is not visible.

But the API is visible in normal API Listing in Publisher.

**Comment by YasasRangika** [comment]
This is in progress
