### ISSUE TITLE
[Streaming API] Resource section is not getting loaded in websocket and webhook

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-apim#10596]
### Description:
The resources section is not getting loaded with topic and type in API overview page 

<img width="1438" alt="Screenshot 2021-03-30 at 12 32 01" src="https://user-images.githubusercontent.com/19290404/112947299-3f499780-9154-11eb-9fb8-ac1baa794244.png">

**Comment by malinthaprasan** [comment]
Seems like this is fixed in the latest pack:

![image](https://user-images.githubusercontent.com/1591316/114095179-c0cec180-98da-11eb-90f7-34403de992b5.png)
![image](https://user-images.githubusercontent.com/1591316/114095194-c3c9b200-98da-11eb-83be-7ceb7f4b4b03.png)
