### ISSUE TITLE
Unauthenticated request popup display when  click Run time Configuration 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#10601]
### Description:
Unauthenticated request popup display when  click Run time Configuration 
<img width="1680" alt="Screen Shot 2021-03-30 at 12 31 53 PM" src="https://user-images.githubusercontent.com/29066805/112947332-4a9cc300-9154-11eb-993d-cf3aa104d6c1.png">

### Steps to reproduce:
* Create new API with user1
* Login with another user who has internal/creator role
* When go to run time configuration of the API, it gives popup message "Unauthenticated request"

### Affected Product Version:
apim-4.0.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
This is expected when using the same browser due to cookies/headers which include partial tokens of REST API. When you logout from the previous user the token will be revoked. But if the browser tries to send the token which is already revoked and this situation happens.
