### ISSUE TITLE
[devportal] When multiple docs are added cages are not aligned in the overview page.

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10600]
### Description:

<img width="1499" alt="Screen Shot 2021-03-30 at 12 34 49 PM" src="https://user-images.githubusercontent.com/6702569/112947419-61431a00-9154-11eb-8f7b-3939454eea88.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chanaka3d** [comment]
Fixed with the new design
