### ISSUE TITLE
Delay when typing or removing "description" in Deploy New Revision section

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#10609]
### Description:
it takes a little bit of time (around 1s-2s for the typed content to appear). Same goes for removing

<img width="476" alt="Screenshot 2021-03-30 at 12 44 54 PM" src="https://user-images.githubusercontent.com/4861150/112948697-001c4600-9156-11eb-9136-9c2551048c47.png">

**Comment by ruwiniwj** [comment]
@Krishanx92 This behaviour can still be reproduced.

**Comment by Krishanx92** [comment]
> @Krishanx92 This behaviour can still be reproduced.

I could not re-produce this now, Did you check in the latest pack?

**Comment by ruwiniwj** [comment]
> > @Krishanx92 This behaviour can still be reproduced.
> 
> I could not re-produce this now, Did you check in the latest pack?

This was reproducible in the second distributed testing session. If it is fixed in latest pack let's close this issue. Thanks!
