### ISSUE TITLE
[Devportal][UI] The helper text of the External Reference Id field is not relavent.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#10606]
### Describe your problem(s)
The helper text line is showing "Sample description of the attribute" for the External Reference Id. This should be updated to the appropriate text.
<img width="760" alt="Screenshot 2021-03-30 at 11 21 47" src="https://user-images.githubusercontent.com/10165411/112940296-9185bb00-914a-11eb-9743-abe0a7e6de45.png">

### How will you implement it

---

**Comment by tharindu1st** [comment]
this was expected since the values given in toml as 
[[apim.devportal.application_attributes]]
required=true
hidden=false
name="External Reference Id"
description="Sample description of the attribute"
