### ISSUE TITLE
Can not edit a comment via Dev Portal

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10602]
### Description:
There is no option to edit or delete a comment on the Developer Portal.

<img width="1680" alt="Screenshot 2021-03-30 at 12 31 05" src="https://user-images.githubusercontent.com/5195851/112947368-538d9480-9154-11eb-9416-bf001a4cc15b.png">

The edit and delete option is there on other platforms, so it will be good to have it in the Developer Portal as well.
Example:
<img width="1324" alt="Screenshot 2021-03-30 at 12 32 10" src="https://user-images.githubusercontent.com/5195851/112947476-791a9e00-9154-11eb-85d1-9e2322cae6b2.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by daz96050** [comment]
Editing comments related to https://github.com/wso2/product-apim/issues/9318
