### ISSUE TITLE
[Publisher]Considerable network calls to `/thumbnail` when opening an API

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#10617]
### Description:
when we go to `/apis` and then select a specific API,  the `/thumbnail` calls remaining for API listing of `/apis` page should be terminated. 

### Steps to reproduce:
1. Open `/apis` from publisher portal
2. Select a specific API
3. Can see `/thumbnail` network calls for other APIs

Note: This is reproducible when the API count is high

**Comment by malinthaprasan** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/10348
