### ISSUE TITLE
Can not delete comments via Publisher

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10610]
### Description:
Can not delete a comment via Publisher.
Tried to delete the highlighted comment.
<img width="1288" alt="Screenshot 2021-03-30 at 12 44 54" src="https://user-images.githubusercontent.com/5195851/112948776-16c29d00-9156-11eb-8cc3-17c8be32e2be.png">

I get the following error.
<img width="1485" alt="Screenshot 2021-03-30 at 12 45 17" src="https://user-images.githubusercontent.com/5195851/112948909-3fe32d80-9156-11eb-8c5f-065e0b85391f.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10144
