### ISSUE TITLE
Only 3 nested replies are visible, and others get vanished

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#10618]
### Description:
Only the first 3 replies can be seen for a parent comment after refreshing the Publisher portal. (Same for Developer portal as well)

### Steps to reproduce:
1. Add comments to an API as shown below. (With one parent comment and more than 6 replies)
    ![image](https://user-images.githubusercontent.com/25246848/112949261-a8320f00-9156-11eb-8143-3ea9668bde1e.png)
2. Refresh the page, you can only see the first 3 replies for the parent comment.
    ![image](https://user-images.githubusercontent.com/25246848/112949405-d283cc80-9156-11eb-9ecf-511fdd74e259.png)

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS
- Web browser: Chrome

**Comment by erangatl** [comment]
Related #10261

**Comment by malinthaprasan** [comment]
Reduced the priority since this needs some more implementation and won't be completed before beta. Will take this after beta.
