### ISSUE TITLE
Edit API doc metadata doesn't show the existing file

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10612]
### Description:
1. Add API doc
2. Give type as file and upload a file and click on save button.
3. From the docs list select edit metadata option of the added doc 
4. It doesn't show the existing file

<img width="1499" alt="Screen Shot 2021-03-30 at 12 49 01 PM" src="https://user-images.githubusercontent.com/6702569/112949002-5b4e3880-9156-11eb-8681-f6e345661be9.png">
 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
"Edit Metadata" doesn't show the existing doc. It can be used to upload a new doc only. Current doc file is available in the listing view.

![image](https://user-images.githubusercontent.com/1591316/114088569-c922fe80-98d2-11eb-9ad8-806febc2bb6d.png)
