### ISSUE TITLE
Rows count and the actual number of rows shown does not match

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#10627]
### Description:
<img width="1365" alt="Screenshot 2021-03-30 at 13 14 19" src="https://user-images.githubusercontent.com/28379317/112952336-00b6db80-915a-11eb-8e65-7f0ed0683be3.png">

### Steps to reproduce:
List scope mappings in admin portal.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tgtshanika** [comment]
Duplicated in https://github.com/wso2/product-apim/issues/10590
