### ISSUE TITLE
Email generation failed when the account is locked after failed login attempts. 

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-apim#10622]
### Description: 
After the configured number of failed login attempts, the account is getting locked correctly. 
But the automatic email generation is not working. 

### Steps to reproduce:
Follow [link](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking-by-failed-login-attempts)

### Affected Product Version:
4.0.0

**Comment by malinthaprasan** [comment]
duplicate https://github.com/wso2/product-apim/issues/10066
