### ISSUE TITLE
Reset Button Does Not Disappear After the Button is Clicked in Prototype Implementation

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#10626]
### Description:
When adding a prototype implementation, initially a default script will appear. This will not have the "Reset" button
![beforereset](https://user-images.githubusercontent.com/30455603/112951049-96516b80-9158-11eb-9ed6-787a4b03cabe.png)

After a change is made to the default script, the "Reset" button appears.
![editmock](https://user-images.githubusercontent.com/30455603/112951151-aec18600-9158-11eb-9d8e-9bdfd4a0c0c2.png)

After the "Reset" button is clicked, the script will revert back to the default script. But the "Reset" button will still be there.
![afterreset](https://user-images.githubusercontent.com/30455603/112951275-cdc01800-9158-11eb-9fc4-9122dc3be3ec.png)

### Steps to reproduce:
1. Login to Publisher
2. Create an API without adding an Endpoint
3. Go to Endpoints tab and Select Prototype Implementation.
4. Click a resource. This will open an editor with the default script. The "Reset" button will not be there.
5. Modify the script. The "Reset" button will appear.
6. Click the "Reset" button. The script will revert back to the default script. But the "Reset" button will still be there.

### Solution:
It would be better to make the "Reset" button disappear after the "Reset" button is clicked so that the user will know that the initial script has not been changed.

**Comment by RAVEENSR** [comment]
When testing this Reset button, found out that it is not working as expected. Resetting the content is only working for the last resource. For and example, if we have post resource named "order1" and another post resource as "order2", only the reset button for order2 will work.
