### ISSUE TITLE
 Creating and uploading message mediation sequence using Integration Studio not working

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-apim#10625]
### Description:
I have followed the documentation  **Creating and Uploading using Integration Studio** and tried to upload a mediation sequence to the APIM publisher through the WSO2 Registry Check-In option. But it is not working as given in the documentation.

### Steps to reproduce:
1. Created an Integration project and added a sequence with a Log mediator. 
2. Right-click on the sequence and select WSO2 Registry -> Check in to WSO2 Registry
3. Provided the publisher URL and clicked on the Registry Browse button.
4. Then it is asking for the credentials, and once the admin credentials are entering, it is ending up with the below error message.
![Screenshot from 2021-03-30 12-33-21](https://user-images.githubusercontent.com/3735291/112950951-7a4dca00-9158-11eb-96ad-7ccedca9dc0e.png)
5. But after taking like one minute, it is loading the Registry Tree Browser window. But I cannot select any registry path. It is only rendering the root path. 
![Screenshot from 2021-03-30 12-34-54](https://user-images.githubusercontent.com/3735291/112950909-6f933500-9158-11eb-836d-b0abffaa9e17.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This was due to distributed deployment didn't have the option to expose the /registry and the certificates this was working with local pack.
