### ISSUE TITLE
When API is published, API creator cannot do any changes to the API

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#10636]
### Description:
1. Create an API using API creator role.
2. Publish the API using API publisher.
3. Relogin with API creator and try to change the endpoint of the API or add a resource. Most of the actions are mot editable for the API creator.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ruwiniwj** [comment]
Closing since duplicated in https://github.com/wso2/product-apim/issues/10635
