### ISSUE TITLE
API Latency BreakDown widget is not loading properly in the latest Chrome version

### ISSUE THREAD

**Issue by Methma** [wso2/product-apim#10638]
### Description:
The API Latency BreakDown chart in the publisher node is not loading properly in latest Chrome version on Linux and MacOS (Version 89.0.4389.90 (Official Build) (64-bit)).

### Steps to reproduce:
1. Configure APIM Analytics 2.6.0

2. Create an API, subscribe and invoke it

3. Load the API Latency chart in Publisher

### Affected Product Version:
2.6.0

**Comment by 1akshitha** [comment]
Closing the issue as the fix is merged.
