### ISSUE TITLE
Custom siddhi policy with $apiContext does not get throttled

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#10632]
### Description:
I have created custom policy with ket template $apiContext and the following siddhi query

```
FROM
  RequestStream
SELECT
  apiContext,
  (apiContext == '/custom/1.0.0') AS isEligible,
  str :concat('/custom/1.0.0', '') as throttleKey
INSERT INTO
  EligibilityStream;
FROM
  EligibilityStream [isEligible==true] #throttler:timeBatch(1 min) SELECT throttleKey, (count(apiContext) >= 2) as isThrottled, expiryTimeStamp group by throttleKey INSERT ALL EVENTS into ResultStream;
```
I have created an API with context /custom and version 1.0.0 from publisher UI. But the `900806` code is not coming after 2 requests as expected.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This couldn't reproduce in latest
