### ISSUE TITLE
Refactor UI permission validation logic to exclude API LC state

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10635]
### Description:

API Lifecycle state has been used for checking the UI permission in [here](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js#L188-L189).

Needs to revise this logic.

Previous PR: https://github.com/wso2/carbon-apimgt/pull/7039
issue: https://github.com/wso2/product-apim/issues/5471

@rmsamitha any help ?

**Comment by tmkasun** [comment]
> in general, the state shouldn't get in the way of doing anything to the API now

Are there any exceptions to this? @rmsamitha

**Comment by rmsamitha** [comment]
This is based on the decission/convention mentioned in https://github.com/wso2/carbon-apimgt/wiki/Permission-validation-on-the-Publisher-UI-elemets-for-API-update
```
Creator users are allowed to update any API field, only if the API is in "Created" life cycle status. This condition is handled within the function.
```

**Comment by tmkasun** [comment]
By going through the discussions and code, It seems we have used the LC state to prevent modifying a published API by an API creator

Carl is an API creator and Paul is a publisher, Carl creates an API and Paul publishes it, After publishing the API If Carl allowed changing API parameters, His (API Creators) gets affected to the published API, Indirectly making Carl (API Creator) an API publisher.

To prevent these side effects, we have checked the LC state combined with user roles(scopes) to prevent doing modifications to an API by the creator when it's in the published state.

**Comment by RakhithaRR** [comment]
Related issue: https://github.com/wso2/product-apim/issues/10636

**Comment by nuwand** [comment]
In older versions, updates done to an API in published state directly gets pushed to the Gateway. Therefore updates to APIs in published state had to very strictly controlled due to the risk of client applications breaking. With v4.0, we no longer have this problem. So IMO its ok to allow editing with a warning to indicate that developers are doing changes to a published API.

**Comment by malinthaprasan** [comment]
But the changes done by the creator will directly go to the developer portal.. Would that be ok?

**Comment by tmkasun** [comment]
Yes, @malinthaprasan , API creators become indirect publishers when API is in the published state

**Comment by nuwand** [comment]
Yes, this is a valid point. API creators kind of gets publisher privileges if we allow editing of APIs in published state to a person with API creator role only. Hence +1 to leave it un-editable for API creators when an API is in published state.

**Comment by malinthaprasan** [comment]
Closing this as we will continue supporting LC based restrictions.
Created: https://github.com/wso2/product-apim/issues/10748
