### ISSUE TITLE
Unable to switch between in revisions without a downtime.

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10644]
### Description:

When there are multiple revisions, and if you want to change a deployed revision, you first need to undeploy from the Gateway and then select the revision. There is no option to change the Revision directly. This creates a downtime for the API which result in the following error.

`{"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}`

<img width="950" alt="Screenshot 2021-03-30 at 13 23 45" src="https://user-images.githubusercontent.com/17047910/112967335-cdc81400-9168-11eb-8b11-545c55ce33d2.png">

### Steps to reproduce:
1. Create multiple revisions.
2. Try to switch to an older revision.
3. You only have the option to undeploy and then deploy.

### Affected Product Version:

APIM 4.0.0-alpha

**Comment by Krishanx92** [comment]
> ### Description:
> When there are multiple revisions, and if you want to change a deployed revision, you first need to undeploy from the Gateway and then select the revision. There is no option to change the Revision directly. This creates a downtime for the API which result in the following error.

Now there's no redeploy option(Deploy same revision).
If you add a new resource you need to create a new revision and deploy that new revision.
This 404 error occurs if you add a new resource and try to deploy the same revision.

> 
> `{"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}`
> 
> <img alt="Screenshot 2021-03-30 at 13 23 45" width="950" src="https://user-images.githubusercontent.com/17047910/112967335-cdc81400-9168-11eb-8b11-545c55ce33d2.png">
> 
> ### Steps to reproduce:
> 1. Create multiple revisions.
> 2. Try to switch to an older revision.
> 3. You only have the option to undeploy and then deploy.
> 
> ### Affected Product Version:
> APIM 4.0.0-alpha

**Comment by arunans23** [comment]
Is there a way to deploy Revision 1 without un-deploying revision 2 first? If so, we can close this issue.

**Comment by Krishanx92** [comment]
> Is there a way to deploy Revision 1 without un-deploying revision 2 first? If so, we can close this issue.

Currently no, there's an ongoing discussion to change the deployment view, will address this as well.
Let's keep this open until we get a proper solution

**Comment by malinthaprasan** [comment]
Increased priority as this will be prominent issue in production setups. We'll need to give support for directly deploying another revision without undeploy using POST /apis/{apiid}/deploy-revision?revisionId= API.

**Comment by Krishanx92** [comment]
Decide to keep this behavior same ATM, since reducing the priority.

**Comment by Krishanx92** [comment]
Duplicate: https://github.com/wso2/product-apim/issues/10769
Design discussion currently going with the above issue, hence closing this.
