### ISSUE TITLE
Regex policy doesn't work.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#10641]
### Description:
Tried to trigger a SQL injection. It worked without any issue.

### Steps to reproduce:
Follow the doc [1]
[1]. https://apim.docs.wso2.com/en/latest/learn/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway/
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Nirothipan** [comment]
After applying the policy, the api needs to be redeployed. I followed the steps in the docs and redeployed the api, was able to get the desired output. Hence closing.
