### ISSUE TITLE
 Rich Text Editor in API Manager Management Console is blank

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10659]
### Description:
When trying to disable the Simple Workflow Executor through API Manager Management Console, if user click  **Rich Text Editor**, it is displayed blank

![chrome-capture (14)](https://user-images.githubusercontent.com/32265029/112984719-186b7100-9114-11eb-99e7-556d2d3ef0de.gif)

### Steps to reproduce:

- Sign in to API Manager Management Console  
- Select Browse under Resources .
- Go to the /_system/governance/apimgt/applicationdata/workflow-extensions.xml
- Click Edit as Text
- Click **Rich Text Editor** radio button

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- DB: MSSQL 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
Rich text editor is not recommended to use.

**Comment by sahan29** [comment]
@malinthaprasan Shouldn't we remove the option then?

**Comment by malinthaprasan** [comment]
This is a common issue in all products so if we are to do so need to do as a general fix.

**Comment by Krishanx92** [comment]
Not specific to APIM product hence closing
