### ISSUE TITLE
Password validation in the first step

### ISSUE THREAD

**Issue by ruthryi** [wso2/product-apim#10656]
### Describe your problem(s)
When adding a User via the Carbon console, there is no validation for the password field when you click "Next". However, at the end, when clicking "Finish", the errors in the password is validated.

<img width="513" alt="Screen Shot 2021-03-30 at 12 15 03 PM" src="https://user-images.githubusercontent.com/23217207/112977255-73808080-9173-11eb-8a4b-9f954b294e8c.png">

### Describe your solution
Validate password when clicking "Next". Or provide a hint.

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
