### ISSUE TITLE
Unexpected error massage

### ISSUE THREAD

**Issue by SuKSW** [wso2/product-apim#10665]
### Description:
Gives the following response when an unexpected character is in the password
![Screenshot from 2021-03-30 20-09-58](https://user-images.githubusercontent.com/17605554/113008741-ee0dc800-9194-11eb-8568-a0ef894e963e.png)

### Steps to reproduce:
1. login to carbon as admin
2. create user with username abc@gmail.com, password abc@gmail.com

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushansilva** [comment]
I was unable to to reproduce this locally, Did you add any password policy ? also i would like to make note that password 
abc@gmail.com has 13 characters so what the error message says is valid

@malinthaprasan should we keep this open?

**Comment by SuKSW** [comment]
I did not add a password policy.

**Comment by malinthaprasan** [comment]
I think this happens in Distributed setup @SuKSW is that?. @dushansilva can you verify there?

**Comment by SuKSW** [comment]
This occured in the apim instance that was hosted for everyone to test. If it was a Distributed setup, then yes.

**Comment by dushansilva** [comment]
was able to successfully add in the distributed setup as well

**Comment by SuKSW** [comment]
I was unable to reproduce this in the beta version

**Comment by malinthaprasan** [comment]
Closing as per above comments
