### ISSUE TITLE
An OpenAPI path parameter can be defined without required set to true

### ISSUE THREAD

**Issue by SuKSW** [wso2/product-apim#10660]
### Description:
- When editing the OpenAPI definition, a parameter in path can be defined without adding the parameter to the path, here the parameter can be with or without the required key, and the required key can be set to false. The error is detected at the Resources page (when the relevant path dropdown is opened), but the OpenAPI definition can be edited and saved as mentioned.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
When trying, was able to see the error coming when trying to save with removed "required". 

![image](https://user-images.githubusercontent.com/1591316/113550171-410dd200-9610-11eb-82c0-db45ca83c293.png)
