### ISSUE TITLE
[UX] Doc listing entry can be improved

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#10672]
### Describe your problem(s)

I feel the content is very tight and we haven't utilised the space properly. Can we improve it somehow? 

![image](https://user-images.githubusercontent.com/3960742/113048434-27a7f880-91c0-11eb-8683-0a0ec375a2f4.png)

**Comment by tmkasun** [comment]
@erangatl Shall we come up with a new design for Docs card in Publisher

**Comment by erangatl** [comment]
XD: https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/screen/61e31aad-5fcf-4894-b7e9-addbeaf97ed0

![image](https://user-images.githubusercontent.com/20179540/113661799-63f9be00-96c4-11eb-810b-c6d7cda8c946.png)

**Comment by bhathiya** [comment]
This looks very nice. Is it possible to have the word "doc" inside the thumbnail image so that users can identify easily it's a doc but not an API?

**Comment by erangatl** [comment]
![image](https://user-images.githubusercontent.com/20179540/113663174-35311700-96c7-11eb-95f1-bff97bfb6ceb.png)

**Comment by bhathiya** [comment]
+1

**Comment by tmkasun** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3313885/114265729-12c53380-9a10-11eb-828b-3b3d59d657e9.png)
