### ISSUE TITLE
Unable to edit existing Subscription-level throttling policies

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10678]
### Description:
User can't edit the existing Subscription-level throttling policies. 
When edit button is clicked, fields are displayed blank with name field frozen. When trying to save error message "_Name is Empty_" is displayed.

![image](https://user-images.githubusercontent.com/32265029/113097992-b743ac00-91ac-11eb-977b-cec589b29e09.png)

### Steps to reproduce:

- Go to admin portal
- Click subscription policies
- Click edit in policy "Gold"

Expected output : 
Existing values should be loaded in the fields.

### Affected Product Version:
API-M 4.0.0

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
Someone please check this in Windows

**Comment by chanaka3d** [comment]
Tested in windows 10 Google Chrome
Version 89.0.4389.114 (Official Build) (64-bit)


And Microsoft Edge


![2021-04-10](https://user-images.githubusercontent.com/3424539/114293679-bae10800-9ab5-11eb-991e-70a69b535492.png)

![2021-04-10 (1)](https://user-images.githubusercontent.com/3424539/114293646-8ec58700-9ab5-11eb-8b55-856991abf433.png)

**Comment by TheRasanjana** [comment]
This is no longer reproducible for me as well. We can close this issue.

**Comment by vithu30** [comment]
This is reproducible in the latest built pack
