### ISSUE TITLE
Cannot delete service from Table view of Service Catalog

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#10686]
### Description:
Cannot delete service from Table view of Service Catalog. This works in Grid view.

<img width="1680" alt="Screenshot 2021-03-31 at 17 33 23" src="https://user-images.githubusercontent.com/8557410/113141641-93817400-9247-11eb-8171-464573ab53e2.png">

**Comment by MPincay** [comment]
> ### Description:
> Cannot delete service from Table view of Service Catalog. This works in Grid view.
> 
> <img width="1680" alt="Screenshot 2021-03-31 at 17 33 23" src="https://user-images.githubusercontent.com/8557410/113141641-93817400-9247-11eb-8171-464573ab53e2.png">
> 

What BD you aré using? If you use H2 recomend delete from table

**Comment by malinthaprasan** [comment]
Reduced priority for beta.
