### ISSUE TITLE
After closing View Definition in Service Catalog the overview page buttons become non clickable

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#10685]
### Description:
After closing View Definition in Service Catalog the overview page buttons become non clickable. Has to reload the page to make it work.

**Comment by tmkasun** [comment]
There is this dialog root left behind after closing the dialog window that's the problem 

![image](https://user-images.githubusercontent.com/3313885/113378823-938f8a00-9395-11eb-8980-7e6662b7e5ba.png)

probably we are unmounting the dialog component before setting it's close state
