### ISSUE TITLE
Ui Issue | Rectangular outline around progress bar

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10698]
### Description:
There is a Rectangular outline around progress bar when loading pages in Publisher. Visible in Chrome on windows.
This was not visible in Edge browser.
![Screenshot (2)](https://user-images.githubusercontent.com/32265029/113253312-ebd16980-9279-11eb-9a70-f98bf107e5db.png)

### Affected Product Version:
API-M 4.0.0

### Environment details (with versions):
- OS: Windows 10
- Browser: Chrome

#### Suggested Labels:
API-M 4.0.0

**Comment by Krishanx92** [comment]
This is fixed with latest release.
