### ISSUE TITLE
Publish button available even after API is Published

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#10690]
### Description:

Publish button is available when the API is in the Published state. Ideally, this should be Re-Publish.

![ipublish](https://user-images.githubusercontent.com/25485273/113147764-c0855500-924e-11eb-91c6-394d6492c678.png)

### Affected Product Version:
APIM-4.0.0 (9.0.95-SNAPSHOT)

**Comment by RAVEENSR** [comment]
@chanaka3d @tmkasun @malinthaprasan Do we need to change this to Re-Publish?

**Comment by Krishanx92** [comment]
Do we need this re-published button anymore? Since there's no meaning of re-publish now, 
Gateway effect changes anyway need deployments and not affect changes only need save from publisher.

**Comment by malinthaprasan** [comment]
For this we'll need to fix the lifecycle.xml and remove this unwanted transition. The same there for Deploy as Prototype as well.
