### ISSUE TITLE
If there are no revisions show the Deploy button only

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#10705]
### Describe your problem(s)
If there are no revisions, for the first time in the deployment page should show only the Deploy option.

**Comment by Krishanx92** [comment]
@erangatl @tmkasun  Any suggestions on this?

**Comment by erangatl** [comment]
XD: https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/screen/940c6602-084a-42d4-b935-52819ee51619

![image](https://user-images.githubusercontent.com/20179540/113376447-650eb080-938f-11eb-8a96-7867bda97551.png)
