### ISSUE TITLE
Throttling doesn't trigger at the correct value (stick to an old value)

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/product-apim#10726]
After following the below steps, the old throttling policy is taking into consideration, not the new throttling policy.

 Reproducing Steps.

- Create a throttling policy name 'PolicyOne' with the Burst Control (Rate Limiting) 5 req/min.
- Create a throttling policy name 'PolicyTwo' with the Burst Control (Rate Limiting) 50 req/min.
- Create an API and subscribe to the API with PolicyOne'.
- Unsubscribe and subscribe again with 'PolicyTwo'.

Even we use a new access token to invoke the API after subscribing with the new throttling policy, throttling happens based on the old throttling policy.

Seems the issue is intermittent but most of the time we can observe the incorrect behavior.

**Comment by rmsamitha** [comment]
Already fix is available in the public branch via https://github.com/wso2/carbon-apimgt/pull/8342 which addressed https://github.com/wso2/product-apim/issues/7507. Hence closing the issue.
