### ISSUE TITLE
[UI][Publisher] Styling issues in the API Overview page. 

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#10731]
### Describe your problem(s)
There are some noticeable styling issues on the overview page.

1. The colour and size of the circles represent the status of the API. 
Colour is not used in anywhere in publisher
The size of the circles is a little too large to the eye.

So better to use an existing color and reduce the size of the circles.

2. The alignment of the line connecting the circles is a little bit off to the upper side.
![Screenshot - 2021-04-02T191900 692](https://user-images.githubusercontent.com/10165411/113421898-74bae300-93e9-11eb-9510-cd9a6cb51565.png)

### How will you implement it

---

**Comment by menakaj** [comment]
![Uploading Screenshot - 2021-04-02T194525.064.png…]()

**Comment by menakaj** [comment]
Suggestion.

cricle height: 40px 
width: 40px
color: #095677

![Screenshot - 2021-04-02T194525 064](https://user-images.githubusercontent.com/10165411/113423341-f01d9400-93eb-11eb-8f11-90cdb70c2b58.png)

**Comment by Krishanx92** [comment]
> Suggestion.
> 
> cricle height: 40px
> width: 40px
> color: #95677
> 
> ![Screenshot - 2021-04-02T194525 064](https://user-images.githubusercontent.com/10165411/113423341-f01d9400-93eb-11eb-8f11-90cdb70c2b58.png)

I'm +1 with this color suggestions. @tmkasun @erangatl WDYT?

**Comment by erangatl** [comment]
Usually green colour is used to give the feeling of complete. I would suggest to have a green colour.

**Comment by tmkasun** [comment]
https://github.com/wso2/carbon-apimgt/pull/10229#issuecomment-813756187

Let's make it themeable

**Comment by dushansilva** [comment]
the tone of green color actually a bit hard on the eyes since this is a light color on a light background, can't we use more of a darker green then it should be easier on the eyes and easy to read
