### ISSUE TITLE
Refactor API thumbnail card view

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10755]
### Describe your problem(s)

Improve the card view by removing randomly picked icon and background grid 

![image](https://user-images.githubusercontent.com/3313885/113543477-1cabf880-9604-11eb-9aa0-2306cab6e099.png)

![image](https://user-images.githubusercontent.com/3313885/113543537-364d4000-9604-11eb-8e63-416c7c7b6a1f.png)

- Need to handle the migrated customized thumbnail images

**Comment by hisanhunais** [comment]
Has this issue been handled with this refactoring?
https://github.com/wso2/product-apim/issues/9402

**Comment by RakhithaRR** [comment]
Are we supporting multiple colours here or will be only this blue gradient one? IMO the landing page might be less lively if it is only just one colour

**Comment by bhathiya** [comment]
> Are we supporting multiple colours here or will be only this blue gradient one? IMO the landing page might be less lively if it is only just one colour

@tmkasun can you please show a multi color one as well, just to see how it looks?

**Comment by tmkasun** [comment]
@bhathiya 
![image](https://user-images.githubusercontent.com/3313885/113548166-b24b8600-960c-11eb-933e-96e1ed09a4a8.png)

when generating multiple colors what we could do is

```pseudocode
uniqueHash = hashFunction(api.name, api.version, api.context)
colorCode = getColorCode(uniqueHash)
```

something like, This could go haywire with generated random color codes, So I prefer a simple one color scheme with of course theming capability to change it, Additionally we can provide customization to choose the background color.

**Comment by bhathiya** [comment]
True that it can go haywire if go for a huge range of colors. but sticking to a few colors might be ok. maybe 5 or 6 colors just depending on the 1st character  of the API name?

**Comment by RakhithaRR** [comment]
> True that it can go haywire if go for a huge range of colors. but sticking to a few colors might be ok. maybe 5 or 6 colors just depending on the 1st character of the API name?

+1 to this suggestion if its possible
