### ISSUE TITLE
Change the wording for the "Deploy as a Prototype" to a meaningful one

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#10761]
### Describe your problem(s)
Need to change the wording for the "Deploy as a Prototype" to a meaningful one.

![Screenshot 2021-04-05 at 14 00 21 (2)](https://user-images.githubusercontent.com/19996612/113554815-8255b000-9617-11eb-92dc-93ffb7921930.png)

**Comment by tmkasun** [comment]
Here `Deploy as Prototype` refers to the transition from `PROTOTYPED` state to `PUBLISHED` state right?
So why can't we just say `Publish` similar to what we show when API is in `CREATED` state

![image](https://user-images.githubusercontent.com/3313885/113572900-b7252f80-9636-11eb-86ac-b9d74176d28e.png)

I think when someone wants to go from prototype to published, they will either update the existing prototype endpoint to production or change the endpoint type to HTTP and point to the corresponding production and sandbox endpoint.

So it's the same as publishing from the created state, except that when it has gone through an additional step?

So my suggestion is to use `Publish`

**Comment by malinthaprasan** [comment]
I think this is about changing the name of "Deploy as a Prototype" when going from Created to Prototyped state. The above image seems to be making a little confusion.
