### ISSUE TITLE
Disable the verify endpoint option when not applicable

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10773]
### Describe your problem(s)
Why do we provide the verify endpoint option here? When you try the create API basic flow for REST API and Streaming API it does not seem to be applicable. I would suggest disabling it or hiding it where not applicable.

<img width="910" alt="Screenshot 2021-04-05 at 19 18 23" src="https://user-images.githubusercontent.com/5195851/113597871-f5801600-9659-11eb-89fc-dd8dbd901f6c.png">
<img width="938" alt="Screenshot 2021-04-05 at 19 16 03" src="https://user-images.githubusercontent.com/5195851/113597880-f9ac3380-9659-11eb-8c95-2089a38e7a05.png">

**Comment by bhathiya** [comment]
it's valid for REST APIs.

**Comment by tmkasun** [comment]
For WS/WSS i'm agree with @Mariangela , If we can't verify or test the endpoint then better to hide the button if when endpoint URL starts with unknow schema / protocol
