### ISSUE TITLE
Rate limiting options not filtered based on users selection

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10772]
### Describe your problem(s)
It will be good if we can customize what rate limiting options a user sees when they select "Event based" or even disable the options that are not relevant.
Currently, when a user selects "Event Based" they even see the GraphQL option.
![eventrate](https://user-images.githubusercontent.com/5195851/113577532-07a08b00-963f-11eb-83c9-4315c8f777ef.png)

**Comment by sajithshn** [comment]
It was decided to leave the UI unchanged. Though some fields are relevant only to certain types due to the complexity involved in changing the UI it will be not changes.

However, we can consider this change in 4.1.0 release or later.
