### ISSUE TITLE
Cannot add new API properties after initial adding

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#10778]
### Description:
Cannot add new API properties after initial adding, in the publisher portal and hit save button.

### Steps to reproduce:

1. Create an API.
2. Go to properties tab and click "Add new property"
3. Provide the property details and click "Add". It will display as below.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2484781/113660525-e765e000-96c1-11eb-9f92-5437b01e72cf.png">
4. Click "Save". Now the UI will be displayed as below. (There is no button to add a new property)
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/2484781/113660646-3744a700-96c2-11eb-9226-9b506597dc68.png">

### Affected Product Version:
APIM 4.0.0-beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
>  (There is no button to add a new property)

There is actually but it's barely visible 😄
