### ISSUE TITLE
Developer portal overview blank page

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#10786]
### Description:

When there is no deployment, get an error 
![image](https://user-images.githubusercontent.com/20179540/113674345-b8f2ff80-96d7-11eb-93f2-ada45ef5d3c2.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Related issue https://github.com/wso2/product-apim/issues/10785
