### ISSUE TITLE
[APIM-4.0.0][Beta]-Getting empty page in devportal for the published APIs that doesn't have revisions deployed in the gateway

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#10785]
### Description:
In the WSO2 APIM-4.0.0 Beta release, even if an API is having the endpoint details, business plan details and published to the devportal if it doesn't have any versions deployed to the gateway, it is giving an empty page in the devportal. No error/warning messages were displayed on the publisher or devportal UI nor in carbon console logs.
This issue is not occurring for the APIs in the following scenario.
1. Sample Pizzashack API
2. If the "Create & Publish" button is clicked on the publisher portal
3. If the API has a revision and has been published in the gateway as follows
![image](https://user-images.githubusercontent.com/20519000/113674515-e344bd00-96d7-11eb-854b-c6745e62bd6f.png)

### Steps to reproduce:
1. Create an API in the publisher (click on create not on create and publish)
2. Add endpoint details and select the business plan
3. The API has completed all the requirements in order to get published
![image](https://user-images.githubusercontent.com/20519000/113673892-281c2400-96d7-11eb-8123-5e69e9364281.png)
4. Publish the API and check the API's overview tab in the publisher portal
![image](https://user-images.githubusercontent.com/20519000/113673936-35d1a980-96d7-11eb-8f39-6dc230d31df6.png)
5. Click on the "View in devportal" button on the right top corner
6. You will be directed to the devportal API list view
7. Select the published API
8. You will get the following empty page
![image](https://user-images.githubusercontent.com/20519000/113674065-60236700-96d7-11eb-8ba7-c17dccc2cea0.png)

### Affected Product Version:
wso2am-4.0.0-beta

**Comment by tmkasun** [comment]
Related issue https://github.com/wso2/product-apim/issues/10786

**Comment by dushansilva** [comment]
assigned to @erangatl  since its he is already working on similar issue, both can be closed together
