### ISSUE TITLE
Gateway environments are missing in JMS event when redeploying an API revision

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#10789]
### Description:
$subject (gatewayLabels are empty)

"gatewayLabels": [],

### Steps to reproduce:
1. Deploy an API revision to us-region environment (created an environment called us-region)
2. Create revision and deploy API (at once) with selecting us-region

![image](https://user-images.githubusercontent.com/23183042/113682891-3ec77880-96e1-11eb-86f2-6687ef347e9d.png)

JMS events received by Microgateway

```json
{
    "apiId": 2,
    "uuid": "3b37c2e0-5b08-4b1a-a67f-8e086873e2ad",
    "name": "SwaggerPetstore",
    "version": "1.0.5",
    "provider": "admin",
    "apiType": "HTTP",
    "gatewayLabels": [],
    "associatedApis": [],
    "context": "/v2/1.0.5",
    "eventId": "40d57b7b-bdf6-46ef-b448-3ff6cbac7af2",
    "timeStamp": 1617692681103,
    "type": "REMOVE_API_FROM_GATEWAY",
    "tenantId": 0,
    "tenantDomain": "carbon.super"
}
```

```json
{
    "apiId": 2,
    "uuid": "3b37c2e0-5b08-4b1a-a67f-8e086873e2ad",
    "name": "SwaggerPetstore",
    "version": "1.0.5",
    "provider": "admin",
    "apiType": "HTTP",
    "gatewayLabels": [
        "us-region"
    ],
    "associatedApis": [],
    "context": "/v2/1.0.5",
    "eventId": "b9161606-2af8-4ad9-9319-08bb6facf360",
    "timeStamp": 1617692681160,
    "type": "DEPLOY_API_IN_GATEWAY",
    "tenantId": 0,
    "tenantDomain": "carbon.super"
}
```

Gateway environments are not available in the event "REMOVE_API_FROM_GATEWAY".

But gateway environments are available in the event when directly click undeploy button instead of redeploying it.
```json
{
   "apiId": 2,
   "uuid": "3b37c2e0-5b08-4b1a-a67f-8e086873e2ad",
   "name": "SwaggerPetstore",
   "version": "1.0.5",
   "provider": "admin",
   "apiType": "HTTP",
   "gatewayLabels": [
       "us-region"
   ],
   "associatedApis": [],
   "context": "/v2/1.0.5",
   "eventId": "1b885826-6198-4298-b3eb-d340dba19320",
   "timeStamp": 1617696856935,
   "type": "REMOVE_API_FROM_GATEWAY",
   "tenantId": 0,
   "tenantDomain": "carbon.super"
}
```

### Affected Product Version:
APIM 4.0.0 beta

### Environment details (with versions):
- OS: macOS
- Client: MG
- Env (Docker/K8s): VM

**Comment by tharindu1st** [comment]
When redeploying Event happens there's no API un-deployment happens from Gateway.
Due to that If we receive API Deployment events into an already deployed gateway, we need to consider this as a redeployment.

**Comment by pubudu538** [comment]
This is a bug right.. For the same event, we miss to add a single value.
