### ISSUE TITLE
Error when uploading a file in Document section in Publisher

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#10782]
### Description:
Showing an error message when uploading a file in Document section in publisher portal. (This is happened when build the publisher component as a dev build)

### Steps to reproduce:

- Installed node dependencies by execute the below command inside the <APIM_HOME>/repository/deployment/server/jaggeryapps/publisher directory.

`npm install`

- Executed the below command to build the publisher component as a dev build.

`npm run build:dev`

- Started the API Manager and deployed the PizzaShackAPI.
- Inside the publisher portal -> **Documents** section, try to upload a file and show the error with a success message as below image.
![image](https://user-images.githubusercontent.com/18566908/113671885-96131c00-96d4-11eb-8d3d-d1136d593040.png)

### Affected Product Version:
3.1.0

**Comment by tmkasun** [comment]
Can't reproduce in master
