### ISSUE TITLE
401 Authentication issue for API

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#10795]
we have wso2 3.0.0 APIM installed in our production environment.

Suddenly for one of our clients for their API started getting a 401 authentication issue.
The token which was provided by us was a lifetime token.

is this issue with the product itself? could you please confirm? what precautions should be taken so that this should never happen again.

**Comment by Krishanx92** [comment]
This is not happen in latest product. Needed more information to sort this down. If require please re-open
