### ISSUE TITLE
[Publisher] Deployements state transition line breaks after adding new revision

### ISSUE THREAD

**Issue by AyeshW** [wso2/product-apim#10811]
### Describe your problem(s)
State transition line breaks **after adding new revision** as follows
![Issue2](https://user-images.githubusercontent.com/35717171/113844589-46a31d80-97b2-11eb-8554-e0eee16e1024.png)

---
#### Suggested Labels:
API-M 4.0.0, type/UI

**Comment by malinthaprasan** [comment]
What is the browser version used?

**Comment by Krishanx92** [comment]
Is this happens in the windows environment?  also what is the resolution of the window?

**Comment by AyeshW** [comment]
No, it is Ubuntu environment. Screen resolution is 2560x1440
