### ISSUE TITLE
Padding Issue on the DevPortal Response Field 

### ISSUE THREAD

**Issue by AyeshW** [wso2/product-apim#10817]
### Description:
1. "Download" word has moved too much right
2. "Download" word is not vertically centered on the button
3. In response header, 2nd line is broken into 2 lines and that causes to have different padding
![Issue4](https://user-images.githubusercontent.com/35717171/113862476-0f3e6c00-97c6-11eb-8124-0f7953025d34.png)

### Steps to reproduce:

- Subscribe an API
- Click on Try Out tab and execute a PUT request

### Environment details (with versions):
- OS: Ubuntu
- Client: Firefox
- Env (Docker/K8s):

---
#### Suggested Labels:
API-M 4.0.0, React-UI

**Comment by AyeshW** [comment]
The issue may be with small screens

**Comment by malinthaprasan** [comment]
As these are coming from swagger console library, reduced the priority of fixing.

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requiremnt.
