### ISSUE TITLE
Cannot list all the APIs in dropdown combo in Abnormal Request Time Configuration section.

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#10816]
### Description:
Can see only 25 APIs in the dropdown. 25 Limit is there.

### Steps to reproduce:

- Configure the API Manager Analytics with the API Manager and change the **[apim.analytics]** property as below in the **deployment.toml** file inside the <APIM_HOME>/repository/conf directory.

```
[apim.analytics] 
enable = true
```

- Publish 30 APIs via publisher portal.
- Go to the dev portal and click on the **Configure Alert** button.
- Put a tick to **Abnormal Requests per Minute** and popup appears.
- When looking the drop down, can see only 25 APIs.

### Affected Product Version:
3.1.0

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
