### ISSUE TITLE
Publisher Deployements "Display in Developer Portal" wording issue

### ISSUE THREAD

**Issue by AyeshW** [wso2/product-apim#10814]
### Describe your problem(s)
It seems like, un-ticking the toggle button near "Display in Developer Portal" should remove the API from the DevPortal though it is not the case.

### Describe your solution
Need to have better wording

**Comment by erangatl** [comment]
Suggestion - Change wording to `Gateway URL Visibility`
Have it next to Gateway Access URL
Tooltip - Display Gateway Access URLs in developer portal.

![image](https://user-images.githubusercontent.com/20179540/113897487-8b49ab80-97e8-11eb-9339-ffc4dc6b913b.png)
