### ISSUE TITLE
US English has not been used for Service Catalog

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#10823]
### Description:
Document [1] states that the following message will be printed in the SI logs. Catalog is the American way of spelling it and Catalogue is the British way of spelling it. As WSO2 uses American English when it comes to documentation, this standard should be followed in the UIs and logs as well.

<img width="1086" alt="Screenshot 2021-04-07 at 22 28 00" src="https://user-images.githubusercontent.com/5195851/113905333-aa4c3b80-97f0-11eb-8aa3-9630a03aea33.png">

[1] https://apim.docs.wso2.com/en/4.0.0-dev/use-cases/streaming-usecase/exposing-stream-as-managed-api-in-service-catalogue/#step-3-publish-the-asynchronous-api-definition

[2] https://www.grammarly.com/blog/catalog-catalogue/#:~:text=Catalogue%20and%20catalog%20are%20both,other%20parts%20of%20the%20world.

**Comment by uvindra** [comment]
@SuKSW will be working on this

**Comment by SuKSW** [comment]
Will not be working on this since a PR with the fix has been merged a few minutes ago.

**Comment by AnuGayan** [comment]
With the fix to the source code, wso2/carbon-analytics#1933,  document has to be changed
