### ISSUE TITLE
Blank Screen When Searching for SOAP to REST API in Developer Portal

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#10834]
### Description:
Screen blackens out when searching for a SOAP API which is Converted to REST, in the developer portal. (Screen Recording Attached)

### Steps to reproduce:
1. Follow to steps in the documentation 
https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/expose-a-soap-service-as-a-rest-api/#expose-a-soap-service-as-a-rest-api

2. Search for the API in developer portal
3. Click on the search result

### Environment details (with versions):
Distributed Setup Testing

![Peek 2021-04-08 11-05](https://user-images.githubusercontent.com/33457890/113973842-99381480-985a-11eb-8109-ccd200c7b059.gif)

**Comment by rashm1n** [comment]
Console Output

![image](https://user-images.githubusercontent.com/33457890/113975434-20868780-985d-11eb-96b6-5784b9fa18e3.png)

**Comment by YasasRangika** [comment]
This issue is not reproducing in latest (9.0.147 components) API-M pack. Hence we can close this issue.
