### ISSUE TITLE
[UI] Blank page in devPortal when click on APIs listed in search results

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#10843]
### Description:
When searching an API in devportal and cilck on one of the APIs listed, it rendered a black screen.

<img width="1546" alt="Screenshot 2021-04-08 at 11 25 25" src="https://user-images.githubusercontent.com/47380804/113975466-2e3c0d00-985d-11eb-95ec-806b4a156e54.png">

Blank page appears after clicking on one of the APIs in search result

<img width="1664" alt="Screenshot 2021-04-08 at 11 23 39" src="https://user-images.githubusercontent.com/47380804/113975490-36944800-985d-11eb-8350-7f8e62e5d110.png">

### Steps to reproduce:

- Create and Publish APIs via Publisher
- Then in devPortal search for the APIs published in the search bar.
- Click on one of the APIs appear in the search results

### Affected Product Version:
4.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushansilva** [comment]
not reproducible in latest pack, therefore closing
