### ISSUE TITLE
Service version is not getting selected when creating new version of API

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#10849]
### Description:

The service version is not getting selected when creating new version of API. Please refer the screenshot below:

![service-version](https://user-images.githubusercontent.com/19728269/113976959-73f9d500-985f-11eb-9194-619da988a02b.png)

The `serviceVersion` parameter is not passed to the back-end.

**Comment by tharikaGitHub** [comment]
@HiranyaKavishani This issue is already fixed with [1].

Duplicate: https://github.com/wso2/product-apim/issues/10689

[1] https://github.com/wso2/carbon-apimgt/pull/10220/commits/cf0efb8f76f448fff7234d445a8affb1bc3f0044

**Comment by Krishanx92** [comment]
Shall we close this? @tharikaGitHub
