### ISSUE TITLE
Number of usages not aligned in Service catalog list view

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10846]
### Description:

In the service catalog page, when you click on the list view, the number of usages is not aligned.

<img width="236" alt="Screenshot 2021-04-08 at 11 28 53" src="https://user-images.githubusercontent.com/17047910/113976095-24ff7000-985e-11eb-8f07-20043783930c.png">

### Steps to reproduce:
Create some service catalog entries and watch the list view.

### Affected Product Version:

wso2am-4.00-beta

**Comment by malinthaprasan** [comment]
duplicate https://github.com/wso2/product-apim/issues/10826
