### ISSUE TITLE
APIs search does not show matching search results more than amount ten

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#10848]
### Description:
Search results does not include expected result as shown below.

Publisher:

![Peek 2021-04-08 11-23](https://user-images.githubusercontent.com/28702407/113976474-d6060a80-985e-11eb-8623-a8dd2d03ab38.gif)

Devportal:

![Peek 2021-04-08 11-29](https://user-images.githubusercontent.com/28702407/113976515-e0280900-985e-11eb-914a-358e53671f8b.gif)

### Affected Product Version:
API-M 4.0.0 beta distributed testing deployment

#### Suggested Labels:
API-M 4.0.0

**Comment by tmkasun** [comment]
This is fixed in master hence closing the issue

![image](https://user-images.githubusercontent.com/3313885/117095984-80e9e580-ad85-11eb-9db9-4eb4e92c3e14.png)
