### ISSUE TITLE
When a new Comment added from devportal , comment shows only after a page refresh.

### ISSUE THREAD

**Issue by prasa7** [wso2/product-apim#10845]
When a comment gets added from the dev portal from a user who has publisher snd subscriber roles the comment adding page get  stuck, and there is no notification displayed as well. When you do a  page refresh the comment was there added successfully.

**Comment by rashm1n** [comment]
Fixed in the latest version. @tmkasun

**Comment by Krishanx92** [comment]
@rashm1n  Please point to the PR and close the issue.

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10317
