### ISSUE TITLE
[Publisher] Inconvenient UX for file uploading in Add New Document section (API-M 4.0.0)

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#10841]
### Description:
![image](https://user-images.githubusercontent.com/36144069/113973819-87ef0800-985a-11eb-9cf6-ec78a0103cbb.png)

1. The file types that can be uploaded are not mentioned here.
2. Also the maximum size of the file is not mentioned here. 
3. When I tried to upload image files neither it shows an error message nor it uploads the file. (everything seems fine but the file is not uploaded)
4. Some file names such as "sample-file.txt" causes the error as below.
![image](https://user-images.githubusercontent.com/36144069/113974553-bd482580-985b-11eb-887d-0eeb42652343.png)

Note that: I tried to upload 4MB text file which took >30s to upload. UI is not showing anything while uploading the file.

**Comment by chashikajw** [comment]
Tried with large text files and pdf files. It was uploaded without taking any time and UI is showing a progress circle when uplaoding.
