### ISSUE TITLE
Error displayed while reloading Publisher

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10840]
### Description:
An error message _"Error while loading the APIs_" is displayed if the user doesn't use the publisher for while and then tries to reload the page.

<img width="1680" alt="Screen Shot 2021-04-08 at 11 14 59 AM" src="https://user-images.githubusercontent.com/32265029/113974790-2039bc80-985c-11eb-85ab-1f930a962a16.png">

### Steps to reproduce:

- Log in to the publisher
- Wait 5 minutes
- Click on API Manager Publisher Banner

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- OS: ios
- Browser: Chrome
- 
---
#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
What is the username used to login?

**Comment by TheRasanjana** [comment]
Observed in our beta distributed setup.

**Comment by npamudika** [comment]
Tried in the distributed setup and locally, but couldn't reproduce the issue. Hence closing this.
