### ISSUE TITLE
Need a option to provide Array option in the Data Type when adding a resource param

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#10842]
### Description:
Currently we can't manually add a resource which has a query param which has a array list of items. Need to provide the drop down with Array option as well?

<img width="1432" alt="Screenshot 2021-04-08 at 11 19 09" src="https://user-images.githubusercontent.com/23296184/113975222-cf769380-985c-11eb-9874-ad3ed7ae74df.png">

What I wanted to achieve was this

<img width="1430" alt="Screenshot 2021-04-08 at 11 24 14" src="https://user-images.githubusercontent.com/23296184/113975433-1f555a80-985d-11eb-9d6a-bdee4e48b4c4.png">

**Comment by malinthaprasan** [comment]
We have to use swagger editor for advanced cases

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
