### ISSUE TITLE
Path Parameter type is missing in Resource Editor

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#10850]
### Description:
In Publisher Resource editor, the Path param type is not listed in the resource parameter type list.

<img width="1126" alt="Screen Shot 2021-04-08 at 11 41 48 AM" src="https://user-images.githubusercontent.com/4471756/113976992-86740e80-985f-11eb-8237-1a3ed78be763.png">

**Comment by malinthaprasan** [comment]
We cannot add new path parameters right? When adding the resource you can add path parameters at the same time.
