### ISSUE TITLE
Doc Content Search

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#10855]
### Description:
As per the search tool tip 4.0.0 supports doc content search, but trying to search doc content leads to error. (Distributed Test Setup)

https://user-images.githubusercontent.com/28379317/113978227-5463ac00-9861-11eb-88d2-e163e6bbcfbc.mov

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Current doc search implementation is legacy, hacky and it doesn't support proper pagination as well. Content search can be used instead of doc search. Need to remove doc: search.
