### ISSUE TITLE
Streaming Integrator not mentioned in the Service Catalog view

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10851]
### Description:

In Service catalog view, only Micro Integrator is mentioned and Streaming Integrator is not mentioned. As I understand, Streaming Integrator can be used to create services as well. 
https://apim.docs.wso2.com/en/4.0.0-dev/use-cases/streaming-usecase/exposing-stream-as-managed-api-in-service-catalog/
<img width="828" alt="Screenshot 2021-04-08 at 11 43 35" src="https://user-images.githubusercontent.com/17047910/113977258-f387a400-985f-11eb-8610-b2fc33c9c454.png">

### Affected Product Version:

wso2ami-4.0.0-beta

**Comment by sajithshn** [comment]
Removed AsyncAPI label as the fix has to be done in the service catalogue

**Comment by Jayanie** [comment]
Not required as this was changed in the master branch
