### ISSUE TITLE
 Cannot change ownership of applications to super tenant users with custom subscriber roles in the disctributed setup

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#10863]
### Description:
This issue is happening only for the **super tenant users in the distributed setup**. (For the tenant users this is working in the distributed setup. Locally working for both super tenant and tenant users)

### Steps to reproduce:
I followed the below steps for **super tenant** in the distributed setup.
1. Create "user1"
2. Create "role1" and assigned it to "user1"
3. Map scopes of Internal/subscriber to role1 from Admin portal.
4. Create "user2" and assign Internal/subscriber role.
4. Log into Devportal as user2
5. Create App2
6. Log into Devportal as user1. 
7. Now again login into Devportal as user 1. You will be able to successfully logged in.
8.  Create App1
9. Log into the admin portal as admin
10. Go to the Applications menu and search for "App1" and change ownership from user1 to user2. It will be successful.
11. Go to the Applications menu and search for "App2" and change ownership from user2 to user1. It will be **unsuccessful**. You will get a message saying that "user 1 is not a valid subscriber" from the UI.

### Affected Product Version:
APIM 4.0.0 Post Beta

### Environment details (with versions):
Distributed setup

#### Related Issues:
https://github.com/wso2/product-apim/issues/10640

**Comment by malinthaprasan** [comment]
TID: [-1234] [api/am/admin] [2021-04-09 04:40:43,944] ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - User does not have scope. Username : vuser1 Scope : apim:subscribe
