### ISSUE TITLE
Add new scope button not visible at all in the publisher

### ISSUE THREAD

**Issue by arunans23** [wso2/product-apim#10867]
### Description:

After creating the first scope, to create the second scope, the "Add new scope" button is not visible at all.

<img width="430" alt="Screenshot 2021-04-08 at 12 16 31" src="https://user-images.githubusercontent.com/17047910/113980721-73177200-9864-11eb-8a5e-fe82ca848a56.png">

### Affected Product Version:

wso2am-4.0.0-beta

**Comment by RAVEENSR** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/10531. Already fixed in the latest snapshot version. For more infor refer the screenshot attached in https://github.com/wso2/product-apim/issues/10531.

Since this is already fixed. closing the issue.

**Comment by arunans23** [comment]
This was global scope. Not local scope. Hope both are fixed.

**Comment by RAVEENSR** [comment]
> This was global scope. Not local scope. Hope both are fixed.

@arunans23 Sorry, my mistake. I checked this in the latest snapshot version. It is still there. Will re-open the issue. Thank you for letting me know :)
