### ISSUE TITLE
When using the "Try Out" option for a created REST API from a SOAP back-end with the developer portal it displays "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by Lasith650** [wso2/product-apim#10865]
### Description:
Created a REST API with an existing SOAP service by importing the WSDL of the SOAP service. Then I was able to successfully Publish and Subscribe the created API. 

Once I tried the "Try Out" option under the developer portal for the above created API, it displays "TypeError: Failed to fetch"

![Screenshot from 2021-04-08 12-12-47](https://user-images.githubusercontent.com/23395897/113980357-000dfb80-9864-11eb-863a-bcbf41846a1e.png)

### Steps to reproduce:

1. Log in to publisher portal
2. Create a REST API with an existing SOAP service by importing the WSDL of the SOAP service
3. Then Publish the created API
4. Then login to the developer portal
5. Create an application and subscribe the above API
6. Then navigate to the above subscribed API and use the "Try Out" option

### Affected Product Version:
4.0.0

### Environment details (with versions):
- OS: Linux
- Client:
- Env (Docker/K8s):

---

**Comment by lkokila** [comment]
@Lasith650, has the self-signed certificate of the API-Manager accepted in the browser for the 8243 port?

**Comment by malinthaprasan** [comment]
I think you have used an invalid gateway endpoint for this. That is not reachable.
