### ISSUE TITLE
Resource summary and description overflowing in devportal

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#10868]
### Description:

![image](https://user-images.githubusercontent.com/12208083/113981297-208a8580-9865-11eb-9cac-f7c728cb5dc7.png)

### Steps to reproduce:
Give a long string to summary and description

API-M 4.0.0 Beta

**Comment by tmkasun** [comment]
We need to check this in the latest Swagger-UI and if can't reproduce there, Need to update the swagger-ui library, if not has to create an issue on the swagger-ui side and get it fixed.

**Comment by tmkasun** [comment]
Could not reproduce in [editor.swagger.io](https://editor.swagger.io/), Let's update the dependency

**Comment by Krishanx92** [comment]
Could not reproduce in latest pack
