### ISSUE TITLE
Cannot import swagger v2 Petstore API via URL

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10871]
### Description:
When choosing to import the Petstore API via an OpenAPI URL, the error "OpenAPI content validation failed!" is displayed in the Publisher UI and the API import does not take place.

This fails for both Swagger v2 json(https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json) and yaml(https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml) formats as shown below.

![image](https://user-images.githubusercontent.com/6614042/113981460-54fe4180-9865-11eb-8473-bf46149062d2.png)

![image](https://user-images.githubusercontent.com/6614042/113981612-795a1e00-9865-11eb-9da2-c6ab5ce83b34.png)

**Comment by RakhithaRR** [comment]
Both of these would work if we use the raw location of the swagger definition (eg: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json)
