### ISSUE TITLE
Response Caching not working 

### ISSUE THREAD

**Issue by Jayanie** [wso2/product-apim#10874]
### Description:

Response Caching not working in **APIM 4 distributed setup**.

### Steps to reproduce:

1. Create a REST API with response caching enabled and deploy a revision.
2. Change the backend response and try to invoke the API again. 
3. The APIM backend sends the changed response from the backend instead of serving from the cache.

(Sometimes got the response as `400 Bad Request`) 
```
< HTTP/1.1 400 Bad Request
< activityid: 3a0aa3de-e622-42b5-a4ed-1789d264fd1f
< Access-Control-Expose-Headers: 
< cacheKey: 55201061665103-565984-115-25-86-33-7981-73
< messageType: text/plain
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,Internal-Key,Authorization
< Content-Type: text/plain; charset=UTF-8
< Date: Thu, 08 Apr 2021 06:45:46 GMT
< Transfer-Encoding: chunked
< Connection: Close
< 
* Closing connection 0
```

**Comment by rmsamitha** [comment]
I tested this locally in all-in-one pack. Response caching works there. So there can be an issue with the distributed setup. The response received above as "400 Bad Request" seems an issue with the backend but since different responses were received, caching hasn't work in the distributed setup.

**Comment by rmsamitha** [comment]
@tharindu1st Could you test this with the backend used by you earlier on the distributed setup?

**Comment by tharindu1st** [comment]
This happened due to two consecutive requests having two JWT tokens in the backend due to that headers got changed. In the actual scenario, for this kind of use case, it will not be able to handle the Response caching.
