### ISSUE TITLE
Cannot search APIs by custom properties in publisher and devPortal

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#10878]
### Description:
$Subject
 
<img width="1492" alt="Screenshot 2021-04-08 at 12 50 06" src="https://user-images.githubusercontent.com/47380804/113985255-94c72800-9869-11eb-8f17-784fdc6a7ac6.png">

<img width="483" alt="Screenshot 2021-04-08 at 12 50 25" src="https://user-images.githubusercontent.com/47380804/113985050-5c274e80-9869-11eb-869e-0f48b1490ee9.png">
<img width="1680" alt="Screenshot 2021-04-08 at 12 50 34" src="https://user-images.githubusercontent.com/47380804/113985076-647f8980-9869-11eb-89d6-f3770fd92509.png">
<img width="661" alt="Screenshot 2021-04-08 at 12 50 45" src="https://user-images.githubusercontent.com/47380804/113985103-6cd7c480-9869-11eb-8ec0-8ee344fe4ac1.png">
<img width="1680" alt="Screenshot 2021-04-08 at 12 51 08" src="https://user-images.githubusercontent.com/47380804/113985127-72cda580-9869-11eb-8f8f-d25a8abc4bce.png">

### Steps to reproduce:

- Create an API via publiser 
- Go to properties and add custom properties and save
- Go to search bar and search by property ( syntax: property_name:property_value

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Closed as not reproduced in the latest pack
