### ISSUE TITLE
[Devportal] Subscription available and get 409 when initially do try out

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#10888]
### Description:
Subscription with DefaultApplication is available after initially try out for an API. When the subscribe button is clicked it doesn't give any error messages in the UI. But upon inspection 409 response is coming for the subscribe API.

![image](https://user-images.githubusercontent.com/25485783/113987865-7f9fc880-986c-11eb-9022-2e7724b4c837.png)

### Steps to reproduce:
1. Create an API and publish.
2. Click try out from the devportal.
3. Navigate to the subscriptions.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Couldn't reproduce in the latest pack.
