### ISSUE TITLE
[AdminPortal] Unwanted Word Breaks in Subscription Policies

### ISSUE THREAD

**Issue by AyeshW** [wso2/product-apim#10881]
### Description:

1. Words are broken into multiple lines (on 14" screen)
2. Unwanted tailoring **'s'** for values like 1days, 1months instead on 1day, 1month

Solution1: We can expand column width as there is enough white space at the right

![Issue6](https://user-images.githubusercontent.com/35717171/113987260-d658d280-986b-11eb-8ea9-3f240b169c06.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
API-M 4.0.0, React-UI

**Comment by Krishanx92** [comment]
This is fixed in latest pack.
