### ISSUE TITLE
API properties search does not work as expected

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#10883]
### Description:
When trying to search APIs with API properties in Publisher it is not working as expected.

![ScreenShot Tool -20210408131344 (1)](https://user-images.githubusercontent.com/42435576/113988193-d60d0700-986c-11eb-803d-52d586c726e8.png)
![Screenshot from 2021-04-08 13-16-51](https://user-images.githubusercontent.com/42435576/113988195-d6a59d80-986c-11eb-9efa-cbefc757fa95.png)

### Steps to reproduce:
1. Create a new API as an API creator.
2. Add an custom API property.
3. Navigate to the search bar and search as `"propertyname:propertyValue"`

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
Checked in the latest setup. Doesn't see this issue.
