### ISSUE TITLE
[Publisher][API Lifecycle] When API deployed as prototype, lifecycle image show a transition to published state

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#10889]
### Description:
When an API deployed as prototype, lifecycle image show a transition to published state but the corresponding action button is not there.
<img width="1505" alt="Screenshot 2021-04-08 at 14 13 46" src="https://user-images.githubusercontent.com/20040505/113996549-e9bc6b80-9874-11eb-8660-5d26bc092f99.png">

### Steps to reproduce:
1. Create an API
2. Deploy it as a prototype

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
I think we should support the transition from prototype to published , it's a valid case

**Comment by Krishanx92** [comment]
This is now fixed with Pre-release state.
