### ISSUE TITLE
[Publisher][DevPortal][API Lifecycle] Error when viewing published API in devportal

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#10887]
### Description:
A REST API is created (without publishing) and then published using life cycle tab. When the API is viewed/opened from the dev portal, the page turns blue, and the browser console logs errors.  However, if we deploy a new revision of the published API, the API can be viewed from the dev portal successfully.

### Steps to reproduce:
1. Create a REST API from publisher
2. Publish the API from life cycle tab
3. Open the API from dev portal

Observation: The API starts to load but then the page turns blue and the following errors are logged in the browser console.

<img width="1680" alt="Screenshot 2021-04-08 at 13 41 40" src="https://user-images.githubusercontent.com/20040505/113991572-38b3d200-9870-11eb-8f47-06ffdd2d1f57.png">
<img width="1680" alt="Screenshot 2021-04-08 at 13 41 50" src="https://user-images.githubusercontent.com/20040505/113991548-33568780-9870-11eb-9cf8-2758186f0d37.png">

 
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ruwiniwj** [comment]
This behaviour is observed for new versions created and deployed as well

**Comment by malinthaprasan** [comment]
Could not reproduce in the latest pack
