### ISSUE TITLE
Cannot view Prototyped APIs in Dev Portal

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#10894]
### Description:
When click on **View in Dev Portal** button or when logged in to the Dev Portal and search for the Prototyped API and try to view it by clicking on it, it gives a blank black color page as below.

![Selection_146](https://user-images.githubusercontent.com/8363838/114012167-9bfb2f80-9883-11eb-9109-01c81927edf9.png)

### Steps to reproduce:
1. Create a Prototyped API.
2. Click on "View in Dev Portal" button from the Publisher for that particular API or logged into the Dev Portal and click in that API.
3. Gives a blank page as shown above.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment]
@npamudika you need to create a deployment for the prototyped API.
Deployments -> Create revision and deploy

**Comment by malinthaprasan** [comment]
Showing the blank page due to deployments not present will be addressed.

**Comment by npamudika** [comment]
Yes, after creating a deployment, is able to view the API.

@malinthaprasan Shall we link to the black page showing issue and close this?

**Comment by npamudika** [comment]
This will be handled via https://github.com/wso2/product-apim/issues/10843
