### ISSUE TITLE
WSO2 APIM Analytics 3.2.0 dashboard login page doesn't open

### ISSUE THREAD

**Issue by dsmohan** [wso2/product-apim#10902]
I am running WSO2 APIM 3.2.0 and Analytics 3.2.0 on different client servers. I did all the required settings to configure WSO2 APIM with WSO2 Analytics. Started both the servers successfully and WSO2 APIM URL's open well. But, when I open the Analytics Dashboard URL (https://<Analytics_Host>:9643/analytics-dashboard/login), I get the below warning in the dashboard server logs, and the login page does not appear. Only a blank screen appears.

`WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception feign.RetryableException: No subject alternative names matching IP address <APIM_IP> found executing GET https://<APIM_Host>:9443/api/am/admin/v0.16/custom-urls/carbon.super`

In the browser console I can see errors as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/66669898/114040995-c2c85e80-98a1-11eb-9989-d6a3242a1df0.png)

One more thing I noticed is in the management console of WSO2 APIM, difference in Service Providers list when compared with my local. I didn't find all the service providers on the client server which I can see on my local.

WSO2 APIM Carbon Console Service Providers list on my local:

![image](https://user-images.githubusercontent.com/66669898/114039213-310c2180-98a0-11eb-9de0-467d468038ea.png)

WSO2 APIM Carbon Console list on the client server:

![image](https://user-images.githubusercontent.com/66669898/114039304-42552e00-98a0-11eb-9e44-55173afa0912.png)

Am I missing out on some configurations? Need suggestions on this issue.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time and the Latest APIM (4.x.x) doesn't support On Prem Solution
