### ISSUE TITLE
[3.1.0] API Product appears in devportal when in created state

### ISSUE THREAD

**Issue by suksw** [wso2/product-apim#10912]
### Description:
1. An API in the created state appears in the devportal (but when clicked continues to load)
2. Unable to publish once created (when created using the "create" button in 2nd step of "Create an API Product")
3. "View in devportal" appears while in created state
![Screenshot from 2021-04-09 13-43-05](https://user-images.githubusercontent.com/17605554/114150441-b394ef80-9939-11eb-9fe2-7087c64b3256.png)

### Steps to reproduce:
1. Go to publisher
2. Create two APIs and publish
3. Create an API product (say API3) using resources from both the APIs (don't publish)
4. Go to dev portal. Click on the API product (API3) just created 

### Affected Product Version:
APIM 3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This is not reproduce in latest pack, hence closing
