### ISSUE TITLE
Multiple restAPI calls to the backend for a single search operation

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#10920]
### Description:

Search operation in the Publisher and dev portal is interactive. Each letter which the user is giving is routed as a rest API call.
Is this an expected behavior?

### Steps to reproduce:

1. Login to Publisher.
2. Create multiple APIs
3. Search for an API (eg: **name:pizza**)

We can observe that for each letter of **n**, **a**, **m** etc. a network call is routed to the backend.

Can we trigger the search operation only if the user clicks a button .

![Screenshot from 2021-04-10 00-41-28](https://user-images.githubusercontent.com/60866295/114229628-b58c9c00-9995-11eb-9cc4-6a04a676b05e.png)

### Affected Product Version:

APIM 4.0.0

**Comment by malinthaprasan** [comment]
This is for populating the matched APIs interactively when searching. If we give a button to click, that cannot be achieved right?

**Comment by malinthaprasan** [comment]
Closing as Won't Fix
