### ISSUE TITLE
Black screen appears while loading the Production Keys for Forgerock KM

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#10934]
### Description:

Black screen appears when trying to load production keys of the application under Forgerock Key Manager.

### Steps to reproduce:
 - Create an External KM for Forgeock
 - Try to navigate to Forgerock Km tab under Production Keys 

### Affected Product Version:
4.0

**Comment by shilmyhasan** [comment]
Testing of the following issue blocked by this issue
[https://github.com/wso2/product-apim/issues/10935](https://github.com/wso2/product-apim/issues/10935)

**Comment by chashikajw** [comment]
Is this only reproducible for Forgerock km?

**Comment by shilmyhasan** [comment]
It was not reproducible for resident key manager. Tried only forgerock as the external KM , so may be thats common to external KM

**Comment by shilmyhasan** [comment]
Following error is found in the browser console

![Uploading image.png…]()

**Comment by HeshanSudarshana** [comment]
This is reproducible for PingFederate KM as well

**Comment by dushaniw** [comment]
Reproducible for KeyCloak as well

**Comment by chashikajw** [comment]
> Reproducible for KeyCloak as well

Yes this is reproducible for other external KMs except WSO2 IS and Auth0.
