### ISSUE TITLE
Error while deploying new Revision with description

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10937]
### Description:
Validation error is displayed when deploying new Revision with description
![chrome-capture (15)](https://user-images.githubusercontent.com/32265029/114281847-9887b580-99f5-11eb-85e6-81e266aed549.gif)

Description added : 
```
Matific's Planned Activities feature allows you to quickly and effectively plan your scope & sequence for the entire year. Your children will be automatically assigned the right activities at the right time. With Matific’s Planned Activities, you will see your school year at a glance, stay paced all year, and end the year without rushing.
```

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- OS: Windows

---
#### Suggested Labels:
API-M 4.0.0

**Comment by chamilaadhi** [comment]
Error coming from the rest API is 

    {"code":400,"message":"Bad Request","description":"Validation Error","moreInfo":"","error":[{"code":"400_description","message":"description: size must be between 0 and 255","description":null}]}

We need to change the limit in the UI to 255
