### ISSUE TITLE
Alignment issue in Try out page

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10944]
### Description:
The following icons and text are not aligned properly in DevPortal **Try Out** Page.
![image](https://user-images.githubusercontent.com/32265029/114296691-82afda00-9a61-11eb-8b27-ca7e91f92e56.png)

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- Browser: Chrome

---
#### Suggested Labels:
API-M 4.0.0

**Comment by Krishanx92** [comment]
This is fixed in latest release.
