### ISSUE TITLE
Doc content search not working for tenants

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#10946]
### Description:
Doc content search not working for tenants

### Steps to reproduce:
- Login to publisher using a tenant
- Add a doc with an inline content to an API
- Search the API using a word in that inline content

### Environment details (with versions):
- OS: Mac
- SNAPSHOT - 9.0.144

**Comment by msm1992** [comment]
Document content update does not trigger the DocumentIndexer as the content is saved as a separate entity in registry. But if we update document **meta data**, it will trigger the DocumentIndexer as the document artifact is being updated and after that the document content search will work.
