### ISSUE TITLE
Publisher unified search response, Invalid pagination total count

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10949]
### Description:

unified search result response contains invalid pagination total count,

![image (3)](https://user-images.githubusercontent.com/3313885/114300262-ff33ce80-9adc-11eb-923e-4c1b54d6db9e.png)

**Comment by tmkasun** [comment]
it's always 0

**Comment by malinthaprasan** [comment]
As this is not fixed properly and pagination total returns the same as limit we specify.
