### ISSUE TITLE
Postman collection issue

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10947]
### Description:

If the user has a resource " /* "  [1] then when user downloads the postman collection, the request with " /* " has a " /* " in the URL [2]. Which is invalid and will result in 404 error.
[1] ![image](https://user-images.githubusercontent.com/32265029/114297358-fef7ec80-9a64-11eb-81dd-771de0d06021.png)
[2] 
![image](https://user-images.githubusercontent.com/32265029/114297393-3797c600-9a65-11eb-87d4-e89578cf654f.png)

### Steps to reproduce:

- Create an API with Resource "/*"
- deploy and publish
- Go to devPortal
- Go to Try out
- Download Postman Collection
- Import the collection to postman
- Try to invoke the api with token generated

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- OS: Windows

#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment]
Having /* at the end implies that user can add any resource afterwards. They have to modify it anyway when using postman.
