### ISSUE TITLE
Publisher unified search result page heading not correct

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10950]
### Description:

![image](https://user-images.githubusercontent.com/3313885/114300257-f17e4900-9adc-11eb-9ee3-d9e5b26956f1.png)

Search result heading title says `APIs`, though it could contain mix of things, APIs, Documents, API Products, etc

**Comment by tharikaGitHub** [comment]
This is fixed with commit https://github.com/wso2/carbon-apimgt/commit/f1e289f1e2d940d00db6b2b2695614c0de00af36. Hence closing.
