### ISSUE TITLE
Add the correct doc link to create a new Service from scratch

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#10955]
### Description:
The correct new doc link should be added to the Service Catalog UI when directing the users to create their own Service from scratch. Currently it is pointing to the landing page of docs.

<img width="396" alt="Screenshot 2021-04-11 at 18 07 03" src="https://user-images.githubusercontent.com/8557410/114304457-dddcdd80-9af0-11eb-943d-1d64ae449cf8.png">

**Comment by Mariangela** [comment]
@tharikaGitHub , let's point to the following link from the Get Started link. This is a new page that I will be adding newly. I had an offline discussion with Sanjeewa in this regard and he was ok with it.

https://apim.docs.wso2.com/en/4.0.0/design/create-api/create-an-api-using-a-service/

**Comment by tharikaGitHub** [comment]
Thanks @Mariangela
