### ISSUE TITLE
Refactor Publisher details page menu component

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#10958]
### Describe your problem(s)

We have been adding routes to the [Details](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Apis/Details/index.jsx) component and haven't optimized the performance and split it into multiple components.
 
![image](https://user-images.githubusercontent.com/3313885/114331693-37c9bb80-9b62-11eb-8a3a-b661199a6449.png)

Clicking on a menu items cause to re-render the entire page

**Comment by tharikaGitHub** [comment]
Fixed with commit https://github.com/wso2/carbon-apimgt/commit/b318b2024845bd880a396e43991c81fdfdc8884c. Hence closing.
