### ISSUE TITLE
Doc links in Admin Portal pointing to wrong URL

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#10954]
### Description:

$Subject. They are pointing to the old docs URL path.

![Screenshot from 2021-04-11 17-45-17](https://user-images.githubusercontent.com/60866295/114303829-b33d5580-9aed-11eb-92ba-9045207e7369.png)

### Affected Product Version:
APIM 4.0.0

**Comment by Krishanx92** [comment]
This is fixed in latest pack
