### ISSUE TITLE
Alert Subscriptions email list gets overridden when a new email is entered - Publisher and Devportal

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#10964]
### Description:
After entering the email addresses list in "Manage Alert Subscriptions" section of publisher and devportal, when we go back and navigate to the settings page again or refresh the page, the previously entered email list will be lost upon entering a new email address.

### Steps to reproduce:

1. Enable APIM analytics.
2. Enter email addresses under the "Emails" section of the Publisher/Devportal > Settings > Manage Alert Subscriptions and save. (1st attempt works without an issue)
3. Refresh the page or leave the settings page and come back.
4. Enter a new email address and the previously entered email list will be lost.

### Affected Product Version:
APIM 3.1.0

**Comment by AnuGayan** [comment]
This was fixed in APIM Analytics 3.2.0
