### ISSUE TITLE
Comments' show more button is not displayed as a clickable button

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#10965]
### Description:
In Publisher Comments' show more button is not displayed as a clickable button.
![Screenshot (4)](https://user-images.githubusercontent.com/32265029/114359525-ea7d2800-9b28-11eb-88a8-31a471b7d4d8.png)

### Steps to reproduce:
Add more than 5 comments for an API

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- Browser: Chrome

---
#### Suggested Labels:
API-M 4.0.0

**Comment by Krishanx92** [comment]
We don't observe this behavior with latest pack.
