### ISSUE TITLE
Devportal GraphQL tryout page error when no deployment is there

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#10969]
### Description:

![image](https://user-images.githubusercontent.com/20179540/114380885-2d321500-9ba8-11eb-84f8-f86bcd7262f8.png)

### Steps to reproduce:
Create a GraphQL API
do not deploy
go to Tryout page in devportal

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
We need to test the senario 

Any API type -> Published without deploy scenarios
