### ISSUE TITLE
1.10.x build issue

### ISSUE THREAD

**Issue by emmansun** [wso2/product-apim#1098]
There are no **carbon.apimgt.version**=**5.0.5-SNAPSHOT**, but after i changed to use 5.0.4, it reported below issue:

[INFO] --- carbon-p2-plugin:1.5.4:p2-profile-gen (p2-profile-generation-for-api-key-manager-profile) @ am-p2-profile ---
...
Installation failed.The installable unit org.wso2.carbon.apimgt.keymanager.feature.group/5.0.4 has not been found.

Application failed, log file location: D:\java-dev-tools\Maven\repository\org\eclipse\tycho\tycho-p2-runtime\0.13.0\eclipse\configuration\1469763788983.log

**Comment by harsha89** [comment]
the build was running fine:+1:. If u encounter it again please reopen.
