### ISSUE TITLE
[UI] Changing rows per page leads to Error Page

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#10988]
### Description:
Switch the rows per page in the API View Page in Publisher Portal

![Screenshot from 2021-04-13 11-36-34](https://user-images.githubusercontent.com/24619763/114504472-8bb0cf00-9c4c-11eb-97e4-2e5c5c35fa0a.png)

It lead to the following error

![Screenshot from 2021-04-13 11-37-08](https://user-images.githubusercontent.com/24619763/114504502-98352780-9c4c-11eb-9186-b08bf397de00.png)

**Comment by tharikaGitHub** [comment]
This is not reproducible in the latest APIM 4.0.0 pack. Hence closing the issue.
