### ISSUE TITLE
Unrestricted File Upload for API Thumbnails

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#11002]
### Description:
Any file format can be uploaded as an API Thumbnail using the PUT apis/{apiId}/thumbnail resource of the Publisher REST API.

### Steps to reproduce:
1. Create an API
2. Using the PUT apis/{apiId}/thumbnail resource of the Publisher REST API, upload any file (.html, .exe) as the API thumbnail

### Solution
Allow only "jpg", "png", "jpeg" and "gif" file formats to be uploaded as API thumbnails

**Comment by hisanhunais** [comment]
This issue has been fixed in master with https://github.com/wso2/carbon-apimgt/pull/10288

**Comment by vithu30** [comment]
Closing the issue as it is fixed in master with wso2/carbon-apimgt#10288
