### ISSUE TITLE
[APIM-3.2.0]-Deletion of the default version API synapse file when a new version API is created

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11015]
### Description:
In wso2am-3.2.0, when an API is created and published as the default version (Make this the default version = Yes) 2 synapse files were created in the **<APIM-Home>/repository/deployment/server/synapse-configs/default/api/** folder as follow.

- admin--gal_v111.xml
- admin--gal.xml

![image](https://user-images.githubusercontent.com/20519000/114854727-c197b400-9e02-11eb-852d-7099771f35ce.png)

Another version of the API was created and published. When the new version synapse was created as admin--gal_v222.xml, the default synapse file, admin--gal.xml was removed from the synapse folder.
![image](https://user-images.githubusercontent.com/20519000/114854802-d2482a00-9e02-11eb-97ac-aa3e6390c98c.png)

When we make v111 API as Make this the default version = No and then again as Make this the default version = Yes the admin--gal.xml was created. 
![image](https://user-images.githubusercontent.com/20519000/114854843-decc8280-9e02-11eb-9fe2-7c683aeb2e44.png)

### Steps to reproduce:
1. Create an API with version 111
2. Make it the default API and publish
3. The synapse files for the default API will be created. One with v111 prefix and another one without any version in the synapse file
4. Create a versioned API from the previously create API with version value 222 and publish it
5. Now, the synapse file for v222 will be created and the synapse file for the same API that doesn't have the version will be deleted from the **<APIM-Home>/repository/deployment/server/synapse-configs/default/api/** folder

### Affected Product Version:
wso2am-3.2.0

**Comment by praminda** [comment]
This is not applicable for 4.x.x. Please try with a 4xx version, this should get resolved.
