### ISSUE TITLE
Error when generating keys with ForgeRock key manager

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#11027]
### Description:
The following error occurs when trying to generate keys with ForgeRock km. This is when auth code and implicit grant types are not selected from the UI. Issue still occurs when those grant types are removed from the key manager in admin panel.

`[2021-04-16 11:04:35,181] ERROR - ApplicationsApiServiceImpl The callback url must have at least one URI value when using Authorization code or implicit grant types.`

This error reproduces with both ForgeRock 6.5.3 and the latest version 7.0.1.

### Steps to reproduce:
1. Add ForgeRock key manager following the documentation
2. Try to generate keys for an application using the km

**Comment by Sarangan0219** [comment]
This is fixed via https://github.com/wso2-extensions/apim-km-forgerock/pull/4
