### ISSUE TITLE
[UX] No endpoint type is selected for SOAP APIs

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#11030]
### Description:
Please refer the screenshot below:

![endpoint](https://user-images.githubusercontent.com/19728269/114978694-3290a780-9ea7-11eb-814d-632018a4bb25.png)

### Steps to reproduce:
Create SOAP API by providing name, version, context and endpoint.

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10461/commits/e16b968bc39c66c2c907fd00624f5682bce84cdb
