### ISSUE TITLE
A few UI improvement suggestions

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#11039]
Make the link image (chain image) clickable

![image](https://user-images.githubusercontent.com/3960742/115002706-b1470e00-9ec2-11eb-94a7-f72c25144b33.png)

**Comment by bhathiya** [comment]
Shall we make the "read only" part look like a label? Currently it looks like a button. 

![image](https://user-images.githubusercontent.com/3960742/115003092-18fd5900-9ec3-11eb-95e2-9c6c9dbac184.png)

**Comment by bhathiya** [comment]
Use  the standard download button

![image](https://user-images.githubusercontent.com/3960742/115003275-464a0700-9ec3-11eb-88f5-caa8c5536231.png)

**Comment by tmkasun** [comment]
Except for `Read only` label improvement other 2 suggestions were fixed in https://github.com/wso2/carbon-apimgt/pull/10420
