### ISSUE TITLE
Wrong context added when creating new version of API using a different version of Service

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#11043]
### Description:
When creating a new version of API by selecting different version of service, the old version and tenant domain get appended to the context. Refer the screenshots (The context of version 1.0 API is `/uber`):

![Tenant](https://user-images.githubusercontent.com/19728269/115012269-43ecaa80-9ecd-11eb-9928-0118251be1cb.png)

![superTenant](https://user-images.githubusercontent.com/19728269/115012368-61ba0f80-9ecd-11eb-8764-f25ac5c9180e.png)

This issue is not there if we create new version of API using same service version

**Comment by YasasRangika** [comment]
This issue is in-progress
