### ISSUE TITLE
UI Issue when a created application needs approval

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#11040]
### Description:
UI Issue when created application needs approval

### Steps to reproduce:
1. Enable application creation workflow in carbon
2. Create an application in devportal
3. INACTIVE and waiting for approval, alignment issue

![image](https://user-images.githubusercontent.com/33457890/115002601-91afe580-9ec2-11eb-9694-64befa3d1c64.png)

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version
