### ISSUE TITLE
Disable Deploy Sample API button for publisher users

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#11059]
### Description:

Disable Deploy Sample API button for publisher users
![image (1)](https://user-images.githubusercontent.com/20179540/115152662-91187a00-a08f-11eb-8c43-e148d6f76984.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
I think we need to come up with a new design to handle this use case,

The scenario is, Publisher user logs into the Publisher portal when there are no APIs created. The publisher couldn't do anything at this point, So we need to gracefully inform the user how to proceed.
Publisher's can't create API products either when there are no APIs.
So this is kind of a dead-end scenario.

@erangatl Shall we come up with a UI design to cover this scenario.

**Comment by erangatl** [comment]
> @erangatl Shall we come up with a UI design to cover this scenario.

+1 will do a design

**Comment by erangatl** [comment]
XD: https://xd.adobe.com/view/be3fc799-0d72-473d-a515-9f7665b5d08a-eb6c/screen/c74cd0bc-1cfa-4baf-81ab-3a17b6cd2180

![image](https://user-images.githubusercontent.com/20179540/115338953-7fcf8a80-a1c1-11eb-94ca-5f367784da4d.png)
