### ISSUE TITLE
Publisher V2 GET apis retrieves APIs and API Products when the query param is passed with version:1.0.0

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11062]
### Description:
When we use **Publisher V2 GET apis** to retrieve APIs by passing the query param to filter from the version, the API Products will also be retrieved if the version is passed as 1.0.0.

### Steps to reproduce:
1. Create an API with version 1.0.0.
2. Create an API Product.
3. Use cURL to GET apis using the Publisher V2 REST API as shown below, with the query as _"query=version:1.0.0"_.
```
wasura@wasura:~$ curl -k -H "Authorization: Bearer 01c11430-90b6-3f77-b033-1f294b8598fc" "https://localhost:9443/api/am/publisher/v2/apis?query=version:1.0.0"
{"count":2,"list":[{"id":"21254f5a-4fb4-47d8-b7f2-8792b601e837","name":"MyProduct","description":null,"context":"/myproduct","version":"1.0.0","provider":"publisher","type":"APIPRODUCT","lifeCycleStatus":"PUBLISHED","workflowStatus":null,"hasThumbnail":false,"securityScheme":[],"createdTime":"2021-04-19 07:20:42","updatedTime":"2021-04-19 07:20:42"},{"id":"937a927f-317f-4c62-85da-19c2b7158427","name":"PizzaShackAPI","description":null,"context":"/pizzashack","version":"1.0.0","provider":"creator","type":"HTTP","lifeCycleStatus":"CREATED","workflowStatus":null,"hasThumbnail":false,"securityScheme":[],"createdTime":"2021-04-19 07:19:43","updatedTime":"2021-04-19 07:19:44"}],"pagination":{"offset":0,"limit":25,"total":2,"next":"","previous":""}}
```
4. Both the API and the API Product will get retrieved.

### Affected Product Version:
APIM 4.0.0-RC1

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS

**Comment by wasuradananjith** [comment]
This behaviour results in **apictl get apis** command to give incorrect results as well if we pass the query as "version:1.0.0".

![image](https://user-images.githubusercontent.com/25246848/115188128-176da400-a102-11eb-92f2-15150f08a985.png)

**Comment by YasasRangika** [comment]
This issue is in-progress
