### ISSUE TITLE
Can not start Vhost context with a backslash `/`

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#11079]
### Description:

Pressing `/` gives no feedback and it took a while to understand `/` is not allowed as the first character

![image](https://user-images.githubusercontent.com/3313885/115342448-e9529780-a1c7-11eb-88e4-b2346c6942bd.png)

I think we should not block prepend `/` or starting a context with `/` character since it's natural to start a context with `/`, But to prevent getting multiple `/`s between hostname and context we should handle it internally

**Comment by Krishanx92** [comment]
This feature is no longer available now.
