### ISSUE TITLE
Is there anyway to upgrade only carbon version  inside API Manager 2.6.0 ?

### ISSUE THREAD

**Issue by gatsbys** [wso2/product-apim#11073]
### Description:
We have an installation of the API Manager 2.6.0 and we are affected by this issue : https://github.com/wso2/carbon-kernel/issues/1864 .

Since our 2.6.0 is using 4.4.35 of the carbon deps, is there anyway to bump only the carbon deps to the next one where the bug is fixed withouut make the major upgrade of the whole product?

We are using :

- TRAFFIC MANAGER
- IDENTITY SERVER
- GATEWAY
- PUBLISHER
- STORE
- ANALYTICS

### Steps to reproduce:

https://github.com/wso2/carbon-kernel/issues/1864 here is the problem described, time to time the publisher and the store start to have high response times and become unresponsive, the restart of the components is the unique solution

### Affected Product Version:

2.6.0

### Environment details (with versions):
- OS: Ubuntu
- Client:
- Env (Docker/K8s): K8s

---

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
