### ISSUE TITLE
Improve definitionType - OAS2 / OAS3 validation when importing services

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#11087]
### Description:
$subject. Currently, able to import a OAS 2.0 service definition, with `definitionType` set as `OAS3` in `metadata.yaml`.
The validation needs to be improved and the request to import services should be failed if the `definitionType` and the definition is not complied.

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
