### ISSUE TITLE
Revision description character count does not update when typing

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#11095]
### Description:

Deploy New Revision description character count does not update when typing. Only updates on click away.

![image](https://user-images.githubusercontent.com/20179540/115537841-db307400-a2b8-11eb-9af9-9bb8e444bc89.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Yeah, this is a bug. Could you do a little digging and see what we can do to fix it? Thanks!

**Comment by Arshardh** [comment]
Closing since these are already sorted
