### ISSUE TITLE
High CPU consumption with low TPS while enabling the 'Passing Enduser Attributes to the Backend Using JWT' feature

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#11090]
### Description:
Conducted performance tests for the APIM-3.2.0 while enabling the 'Passing Enduser Attributes to the Backend Using JWT' feature and observed a drastic reduction of TPS and an increase in CPU consumption compared to the 'Passing Enduser Attributes to the Backend Using JWT' feature disabled scenario.

### Steps to reproduce:
* Enable the 'Passing Enduser Attributes to the Backend Using JWT' feature as per documentation[1].
* Conduct a performance test while monitoring CPU consumption and Throughput.

### Affected Product Version:
APIM-3.2.0

---
#### References:
[1] - https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/

#### Suggested Labels:
X-JWT-Assertion, APIM-3.2.0

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/292f71d267ad339cf16bd2722dae88ec0ea0c5d8
