### ISSUE TITLE
Incorrect behaviour when passed query=deployed:false to Publisher V1 GET apis/{apiId}/revisions

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11091]
### Description:
When you pass `query=deployed:false` to the Publisher V1 GET apis/{apiId}/revisions REST API, both the deployed and undeployed revisions will be retrieved.

### Steps to reproduce:
1. Create and deploy the sample PizzaShackAPI from the Publisher portal (Here the Revision 1 will be deployed)
2. Now deploy a new revision (Revision 2)
3. Send a cURL request as below to retrieve the revisions that are not deployed (`query=deployed:false`)
```
curl -L -X GET 'https://localhost:9443/api/am/publisher/v2/apis/{apiId}/revisions?query=deployed:false' -H 'Authorization: Bearer <access-token>' -k | json_pp
```
4. You will get an output as below with deployed and undeployed revisions both which is wrong.
![image](https://user-images.githubusercontent.com/25246848/115520575-ecbd5000-a2a7-11eb-82b4-e5c37f92c526.png)
5. Now send the cURL request as below to retrieve the revisions that are deployed (`query=deployed:true`)
```
curl -L -X GET 'https://localhost:9443/api/am/publisher/v2/apis/{apiId}/revisions?query=deployed:true' -H 'Authorization: Bearer <access-token>' -k | json_pp
```
6. You will get an output as below with the deployed revisions which is correct.
![image](https://user-images.githubusercontent.com/25246848/115520766-20987580-a2a8-11eb-92a7-e6434cb680ce.png)

### Affected Product Version:
APIM 4.0.0-RC1

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS

**Comment by wasuradananjith** [comment]
Same thing is happening for API Product revisions as well

**Comment by YasasRangika** [comment]
This issue is in-progress
