### ISSUE TITLE
Email address field in Analytics email configuration have unintended behavior in dev portal

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11093]
### Description:
Email address field under the alert configurations in the dev portal have unintended behavior

### Steps to reproduce:
**Issue 1**
- Configure the APIM analytics 3.2.0 with API Manager 3.2.0
- Go to the dev portal.
- Click on the **Configure Alerts** section.
- Add an email address (Eg: a@b.com) to the email address section and remove it.
- Again add a different email address and the previous email address will add into the field.
![NMBSSUB-66](https://user-images.githubusercontent.com/18566908/115522198-86393180-a2a9-11eb-956e-75175d284f86.gif)

**Issue 2**
- Configure the APIM analytics 3.2.0 with API Manager 3.2.0
- Go to the dev portal.
- Click on the **Configure Alerts** section.
- Add an email address and save it.
- Again open the alert configuration section and we can see the email address that was added previously.
- When trying to add a new email address, that will remove the previously configured email address automatically.
![NMBSSUB-66_NEW](https://user-images.githubusercontent.com/18566908/115522223-8c2f1280-a2a9-11eb-9415-76d0cb95f180.gif)

### Affected Product Version:
3.2.0

**Comment by Krishanx92** [comment]
There's no Public fix since we revamp this is the latest release.
Hence close.
