### ISSUE TITLE
Error 404 on any API published in 4.0.0-rc

### ISSUE THREAD

**Issue by danijelt** [wso2/product-apim#11102]
### Description:
Any API deployed and published on 4.0.0-rc will return 404 when invoked through API gateway. Gateway returns error: `{"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}`
Log shows:
`INFO - LogMediator STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /testapi/1.0/test, HEALTH CHECK URL = /testapi/1.0/test`
### Steps to reproduce:
Download and extract API Manager 4.0.0-rc. Configure for MySQL database, add MySQL JDBC driver. Configure hostname, proxy ports for nginx as proxy server, and endpoint URLs in `[[apim.gateway.environment]]`. Start `api-manager.sh`.

Create new API of any kind, either new API or import OAPI definition file.

There will be no errors in logs or in API Publisher, API will be published without errors, but invoking, either via Publisher, Devportal or curl will produce 404 error as if API does not exist.

### Affected Product Version:
4.0.0-rc

### Environment details (with versions):
- OS: Linux Debian 10
- Env (Docker/K8s): Virtual machine

---

#### Suggested Labels:
4.0.0, Type/Bug

**Comment by danijelt** [comment]
Update: deploying API works on local machine with default configuration. When deploying on remote server with endpoint URLs and admin password changed, API is not added to Synapse.

Output on local machine:
```
[2021-04-21 20:02:16,957]  INFO - CommonUtil Creation of folder is successful. Directory Name : Definitions
[2021-04-21 20:02:17,072]  INFO - DependencyTracker Local entry : 558ae58e-bf6d-43e6-a8bd-f02f09dd3569 was added to the Synapse configuration successfully
[2021-04-21 20:02:17,075]  INFO - DependencyTracker Endpoint : testapi--v1.0_APIsandboxEndpoint was added to the Synapse configuration successfully
[2021-04-21 20:02:17,076]  INFO - DependencyTracker Endpoint : testapi--v1.0_APIproductionEndpoint was added to the Synapse configuration successfully
[2021-04-21 20:02:17,202]  INFO - DependencyTracker API : testapi:v1.0 was added to the Synapse configuration successfully
[2021-04-21 20:02:17,203]  INFO - API {api:testapi:v1.0} Initializing API: testapi:v1.0
```

This output is not present on remote server. Are there some changes in configuration needed between v3.x.x and v4.0.0?

**Comment by nrbw** [comment]
I'm trying to install an instance of API Manager 4.0.0 (update level 47) and I suffer from the same problem. I'm using a custom hostname and I changed the admin login and password.
Did someone found a solution before publishing the release version ? Did I miss something in my configuration ?

**Comment by danijelt** [comment]
Hi @nrbw 
I forgot to write a follow up, I discovered that the problem happens when I use MariaDB database instead of MySQL (regardless of the Java driver used). It worked fine in 3.2.0, and other WSO2 products also work fine on MariaDB so I don't know what happens here, but for now I'm using MySQL 5.7 for API Manager 4.0.0.

**Comment by nrbw** [comment]
Thanks for the follow up @danijelt . I'm using postgresql 11 :/
I guess I'll look into a driver issue :/

**Comment by seminerd** [comment]
I'm having this issue too, do we have any update on this, guys ?

**Comment by seminerd** [comment]
I think I know why this happens.
On a local machine, there's only 1 default API gateway which is localhost, so the resources are fine with that.
But on a remote one, in my case it's an EC2 Instance, it has 2 API gateways, one is its localhost, another is the DNS point to the IP of the machine. After changes, I only deploy it to the DNS API gateway and not the localhost. I just tried to deploy a new revision to all API Gateway it has, and now it works if we call it from Postman. However, it doesn't work on the UI and prompts me with TypeError : Load Failed.

**Comment by TheDigitalEagle** [comment]
The linked open issue is actually not related or relevant.  We need to figure this out because as it stands 4.0 is unusable in pretty much any instance.

**Comment by danijelt** [comment]
I'm closing this issue since I've found the solution for my case.

**Comment by cxyao** [comment]
> I'm closing this issue since I've found the solution for my case.
We also blocked by this Error 404.
Would you please tell us how to solve this error with your solution? @danijelt

**Comment by marmo94** [comment]
Help ! I'm facing same issue on 41.0. each time I publish a new API and then call it, it get 404 and when I restart the server it works then (so any time I need to add an API, I first add it and restart the server to get it ok)

**Comment by ha-ba-0405** [comment]
i am having same problem. Could you give me an advice @danijelt.
how you solved.

**Comment by wh0am111** [comment]
> Help ! I'm facing same issue on 4.1.0. each time I publish a new API and then call it, I get 404 and when I restart the server it works then (so any time I need to add an API, I first add it and restart the server to get it ok). in the UI we get the error :
> 
> Failed to fetch.Possible Reasons:CORSNetwork FailureURL scheme must be "http" or "https" for CORS request.
> 
> and on the server side we can see :
> {"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}

I have the same problem

**Comment by Hepzidavid** [comment]
I'm using the terraform WSO2 provider to create APIs in WSO2, but I got a 404 error. Because, provider was hitting the wrong endpoint instead of correct one. Also tried with curl, which also failed to reach the correct URL.

The wso2 installation is complete, and the API is also created via terraform which I can see on the UI, but still I'm getting the same error.

It seems there's a bug within the provider itself. To make sure, that this error lies within the provider only, I've verified it by installing other versions of wso2, but I'm still facing the same issue. I also verified the wso2 URL and authentication details, which seem correct configurations. Is there any other way to do this?

Tested versions of wso2- 4.3.0 & 3.2.0.

When using Terraform to create an API, getting an unsuccessful api call error. I've tried creating the API manually using curl, but got HTML response instead of JSON is returned with 200 OK status, which seems to indicate I'm being directed to the wrong endpoint.


Does anyone know how to resolve this error?

**Comment by hungpt99** [comment]
> Help ! I'm facing same issue on 4.1.0. each time I publish a new API and then call it, I get 404 and when I restart the server it works then (so any time I need to add an API, I first add it and restart the server to get it ok). in the UI we get the error :
> 
> Failed to fetch.Possible Reasons:CORSNetwork FailureURL scheme must be "http" or "https" for CORS request.
> 
> and on the server side we can see :
> {"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}
I have the same problem

**Comment by acastaneda-cv5** [comment]
I have the same problem in version 4.1.0, did anyone manage to solve it?
