### ISSUE TITLE
Gray tiles appear when searching APIs and Documentations - Publisher

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11105]
### Description:
When searching APIs and documentations by parsing keywords, grey tiles appear for documentations results and cannot click on that as well.

### Steps to reproduce:

- Publish multiple APIs via the publisher portal.
- Add documentations for each APIs.
- Go to the publisher portal home page and try to search docs by parsing keywords.
- We can see the APIs that matched with the search criteria. But we cannot see the documents as below image.

![Screenshot from 2021-04-21 18-23-48](https://user-images.githubusercontent.com/18566908/115647902-3eb2b400-a342-11eb-897e-8f23a5e4a2bf.png)

### Affected Product Version:
3.2.0

**Comment by kavishkafernando** [comment]
Not reproducible in master hence closing
