### ISSUE TITLE
Import open api3 spec - wrong endpoint auto filled

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#11114]
### Description:
Login to publisher portal
Go to Create API -> Import From Existing -> Upload
Import the Open API3 spec from the wizard
[openapi3.json.zip](https://github.com/wso2/product-apim/files/6362283/openapi3.json.zip)

The following happens.
The value supposes to go to context goes to URL filed.

<img width="814" alt="Screen Shot 2021-04-23 at 7 56 37 AM" src="https://user-images.githubusercontent.com/3424539/115809306-77699080-a409-11eb-9455-ea84ef245977.png">

### Version
3.2.0

**Comment by tmkasun** [comment]
I think the attached OAS definition having invalid server URL in the `servers` object

![image](https://user-images.githubusercontent.com/3313885/115819709-13e95e00-a41d-11eb-8ba4-916506f7f35a.png)

what we have auto filled is `servers[0].url` ('/api/v3') which is the correct behaviour
