### ISSUE TITLE
Secure proxy settings not correctly getting applied for HttpClient 

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#11129]
### Description:
We can't set the secured proxy configurations for the apache HttpClient. We don't have a configuration to set Username, Password and NonProxyHosts

### Affected Product Version:
3.2.0

**Comment by shagihan** [comment]
There is an issue with the ExtendedProxyRoutePlanner as well.

**Comment by tharikaGitHub** [comment]
Closing as the fix is added to the public branch - https://github.com/wso2/carbon-apimgt/pull/10598
