### ISSUE TITLE
Issue with API versioning when numbers are used as suffix of the version

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#11135]
### Description:
When we use "{letter}{number}" pattern as the version of an API (eg: v1), v10 is considered as a lower version than v9. Therefore v9 is displayed in the store instead of v10.
This issue is not observed when using "{number}" pattern (eg: 1.0)

### Steps to reproduce:

1. Create and publish an API by giving the version as "{letter}{number}" (eg:  v1).
2. Create a new version of this API as v9.
3. Publish this v9 API.
4. Again create a new API version as v10 and publish this API.
5. Go to the Store portal and we could see v9 API there instead of v10 API.

### Affected Product Version:
APIM 2.6.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
