### ISSUE TITLE
Unable to generate Frequent tier limit hitting with API manager 3.2.0 Analytics

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#11152]
### Description:
With API Manager 3.2.0 analytics, we couldn't generate 'Frequent tier limit' alert due to missing attributes in siddhi file.

### Steps to reproduce:

- Setup APIM 3.2.0 Analytics environment
- Create an application by setting 'per token quota' as '10PerMin'. You can also create an application throttling tier with lower request count (etc: 5) by logged into Admin Portal as well.
- Then subscribe to an existing API and send a burst of request until the throttling happens for 10 times or more within an hour.
- Then again logged into Admin Portal and check Alerts and you couldn't see alerts are generated for 'Tier Crossing'

### Affected Product Version:
API Manager 3.2.0 Analytics

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
