### ISSUE TITLE
Fails the WSS api call in the APIM 2.6.0

### ISSUE THREAD

**Issue by dumindurox777** [wso2/product-apim#11157]
### Description:
We are having some issue when invoking the WSS api. Unable to connect to the web socket api.

### Steps to reproduce:
After creating the wss websocket api by following steps in documentation[1]. Then try to invoke the api using wscat client in wss call. But observed the below error.

```
apple@Apples-MacBook-Pro-2.local:~$ wscat -n -c wss://localhost:8099/echowebsocket/1.0 -H "Authorization: Bearer 6888cbde-5d0c-3f1a-901e-c316aad6b6bc"
error: read ECONNRESET
```
Without any issue able to invoke the api using ws call.

[1] https://docs.wso2.com/display/AM260/Create+a+WebSocket+API

### Affected Product Version:
APIM-2.6.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
