### ISSUE TITLE
Visible only 25 APIs under the Alert Configurations - Publisher Portal

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11169]
### Description:
Cannot see all the APIs (show only 25 APIs) in the dropdown under the **Abnormal Response Time** and **Abnormal Backend Time** configurations

### Steps to reproduce:
- Configured API Manager analytics with API Manager.
- Published 26 APIs via the publisher portal.
- Clicked on the Settings in the publisher portal.

**Issue 1**
- Clicked on the gear icon right to the Abnormal Response Time configs.
- Listed down API names in the dropdown and we were able to see only 25 APIs.

**Issue 2**
- Clicked on the gear icon right to the Abnormal Backend Time configs.
- Listed down API names in the dropdown and we were able to see only 25 APIs.

### Affected Product Version:
3.1.0

**Comment by kavishkafernando** [comment]
Alert configurations has been removed from APIM product and moved to analytics hence closing the issue.
