### ISSUE TITLE
Get a black screen when searching documents via Dev Portal

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11164]
### Description:
Get a black screen when searching documents via Dev Portal

### Steps to reproduce:
- Published an API via publisher portal. (**TEST_API**)
- Navigated to the Documents section and added a document (**TEST_DOC**)
- Went to the dev portal and tried to search the API and the document by parsing a keyword (**TEST**) and we were able to observe a black screen as below image.

![Screenshot from 2021-04-30 14-20-43](https://user-images.githubusercontent.com/18566908/116899908-c4ddcd00-ac55-11eb-9791-5d0631d12e3b.png)

### Affected Product Version:
3.1.0

**Comment by kavishkafernando** [comment]
Not reproducible in master hence closing
