### ISSUE TITLE
Unable to remove Business Infromation

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#11175]
### Description:

Once the business information is added there is no way to remove it. Passing empty values in the fields too is causing errors.

![Screenshot from 2021-05-05 12-49-09](https://user-images.githubusercontent.com/60866295/117109126-cf0ce200-ada1-11eb-9daa-f32ac83dee1b.png)

There are no error logs. The Put request to the API is failing with 400.

### Steps to reproduce:

1. Create an API.
2. Add Business Information
3. Try to remove it.

### Affected Product Version:

APIM 4.0.0

**Comment by 1akshitha** [comment]
Closing the issue as the PR is merged to master
