### ISSUE TITLE
[Streaming API] [SSE] Throttling out does not occur in tenant mode

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-apim#11179]
### Description:
Throttling out does not occur in tenant mode for SSE Streaming APIs.

### Steps to reproduce:
1. Create a tenant
2. Create a SSE API
3. Create a Custom throttling policy, apply it to the SSE API, and deploy a revision of the SSE API
4. Start the SSE backend and invoke the SSE API.

**Comment by Nirothipan** [comment]
Seems the SseResponseStreamInterceptor is not getting engaged in tenant mode, need to check more into this.

**Comment by senthuran16** [comment]
Added the fix via commit: https://github.com/wso2/product-apim/pull/10992/commits/83cf28df41bee3fbd422c1575b48e8b74a8135cb

**Comment by Nirothipan** [comment]
https://github.com/wso2/product-apim/commit/83cf28df41bee3fbd422c1575b48e8b74a8135cb

**Comment by Krishanx92** [comment]
Close with the Fix https://github.com/wso2/product-apim/commit/83cf28df41bee3fbd422c1575b48e8b74a8135cb
