### ISSUE TITLE
Fix REST API schema errors

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#11170]
### Description:
Checking the publisher REST API definition, observed a couple of schema validation errors.

![image](https://user-images.githubusercontent.com/1591316/116969478-f2695b80-acd3-11eb-8dab-9aad209b436f.png)

Check other REST APIs too and fix all.

There are couple of warnings with unused models as well. Need to remove all unused ones.

eg:
ThreatProtectionPolicyList
EndpointList

**Comment by Krishanx92** [comment]
Fixed in the latest version, hence closing
