### ISSUE TITLE
Devportal websocket tryout page error in anonymous mode

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#11176]
### Description:

$subject

![websocket-error](https://user-images.githubusercontent.com/1591316/117116447-02ed0500-adac-11eb-808b-ad2f1ea8e1e9.gif)

### Steps to reproduce:
1. Create a websocket API and publish
2. Goto devportal and goto tryit page of the API without login-in

**Comment by tharikaGitHub** [comment]
This issue is not reproducible in the latest master branch. Hence closing.
