### ISSUE TITLE
IS-KM - JWT introspection validation config is missing in j2 template 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#11185]
### Description:
In IS-KM 5.9.0, the configuration related to <EnableJWTTokenValidationDuringIntrospection> in identity.xml is missing in the  identity.xml.j2 template file. Due to that following config in the deployment.toml file will not apply the expected configuration. 
`
[oauth]
enable_jwt_token_validation_during_introspection = true 
`

### Affected Product Version:
IS-KM v5.9.0

**Comment by Chamindu36** [comment]
This has been fixed in the latest version of the APIM, Hence Closing the ticket.
