### ISSUE TITLE
Fix UI fixes for APIM 4.0.0

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#11194]
### Description:
This issue is created to keep track of the following UI issues under Update 2.0 for APIM 4.0.0.

1. https://github.com/wso2/product-apim/issues/11108

2. https://github.com/wso2/product-apim/issues/11106

3. https://github.com/wso2/product-apim/issues/11067

4. https://github.com/wso2/product-apim/issues/11059

5. https://github.com/wso2/product-apim/issues/11039

6. https://github.com/wso2/product-apim/issues/11008 

7. https://github.com/wso2/product-apim/issues/11005

8. https://github.com/wso2/product-apim/issues/10991

9. https://github.com/wso2/product-apim/issues/11126

10. https://github.com/wso2/product-apim/issues/10760

11. https://github.com/wso2/product-apim/issues/11086

12. https://github.com/wso2/product-apim/issues/10426

13. https://github.com/wso2/product-apim/issues/11199

14. https://github.com/wso2/product-apim/issues/11200

**Comment by 1akshitha** [comment]
Closing the issue as the updates are released.
