### ISSUE TITLE
[u2] Fix issues with app import and default version

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#11192]
### Description:

- Support Importing Out-of-Band Application
- Deletion version is lost when when a new version API is created

### Affected Product Version:

3.2.0
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Related Issues:

#11125
#11015

**Comment by Krishanx92** [comment]
Above mention issues are closed hence closing main issue.
