### ISSUE TITLE
Syntax error in the SQL query that is used to retrieve application name by application consumer key.

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#11209]
### Description:
Getting "ORA-00933: SQL command not properly ended" error when executing the following query to retrieve application name by application consumer key on the oracle database ( Oracle Database 12c Enterprise Edition Release 12.1.0.2.0.).

`SELECT APP.NAME FROM AM_APPLICATION AS APP INNER JOIN AM_APPLICATION_KEY_MAPPING AS MAP ON APP.APPLICATION_ID = MAP.APPLICATION_ID WHERE CONSUMER_KEY = 'consumer_key';`

### Steps to reproduce:

- Execute the following query on a oracle database ( Oracle Database 12c Enterprise Edition Release 12.1.0.2.0.).
`SELECT APP.NAME FROM AM_APPLICATION AS APP INNER JOIN AM_APPLICATION_KEY_MAPPING AS MAP ON APP.APPLICATION_ID = MAP.APPLICATION_ID WHERE CONSUMER_KEY = 'consumer_key';`

- Then, the following error was observed in the output console.
`ERROR at line 1:
ORA-00933: SQL command not properly ended`

### Affected Product Version:
2.6.0

**Comment by HiranyaKavishani** [comment]
Public fix will be available when adding the public fix for https://github.com/wso2/product-apim/issues/9851. Hence close the issue
