### ISSUE TITLE
Error while retreiving the subscribe information for deleted subscriber

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11204]
### Description:
Subscriptions of the API is not deleting even after deleting the user via the carbon management console.

### Steps to reproduce:
- Publish an API via the publisher portal.
- Log into the dev portal by using the **admin's** credentials and subscribe to the API with the **DefaultApplication**.
- Create a user via carbon management console (**sub1**) with **Internal/subscriber** permission.
- Log into the dev portal by using the **sub1's** credentials and subscribe to the **DefaultApplication**.
- Go to the carbon management console and delete the **sub1** user.
- Go to the publisher portal and list down all the subscription of the API by click on the **Subscriptions** tab, will observe the below error in the UI.

![Screenshot from 2021-05-05 21-25-53](https://user-images.githubusercontent.com/18566908/117690507-8c4f6d80-b1d8-11eb-921a-63a5b0b75769.png)

- In the wso2carbon.log file, can see the below stack trace.

[`2021-05-05 21:25:53,693] ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving user claim values from user store`

### Affected Product Version:
3.2.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
