### ISSUE TITLE
"Download API" button downloads a corrupted archive

### ISSUE THREAD

**Issue by ragwap** [wso2/product-apim#11224]
### Description:
"Download API" in Publisher which downloads a zip of the API seems to download a corrupted archive.

### Steps to reproduce:

Try the following steps with 3.2.0 WUM 1619878562980:

When you navigate into any given API version in the Publisher, there is a link / button to "Download API" which downloads a zip of the API. This zip seems to be corrupted. It cannot be opened via graphical archive tools nor by unzip on the command line.

Try the same steps with an older WUM which is 1613729875626. This does not seem to have the issue.

### Affected Product Version:
APIM version: **3.2.0**
WUM level: **1619878562980**

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by msm1992** [comment]
This issue is not reproducible in latest APIM 4.0.1 pack. Hence resolving.
