### ISSUE TITLE
Intermittent issue in API subscription creation in a monetization enabled setup

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-apim#11222]
### Description:
This is an intermittent issue. When the same setup was tried previously it was working fine. And issue was noticed without any changes to the previously working setup.

### Steps to reproduce:
1. Setup APIM and Analytics for monetization
2. Try to subscribe to an api
3. Invoke a subscribed api and following issue is noticed in logs.

`WARN - APIAuthenticationHandler API authentication failure due to The subscription to the API is inactive`

and following in Tryi it tool

`<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
  <ams:code>900909</ams:code>
  <ams:message>The subscription to the API is inactive</ams:message>
  <ams:description>User is NOT authorized to access the Resource. API Subscription validation failed.</ams:description>
</ams:fault>`

Subscription status of the API was unblocked but there were pending subscription approvals at the Admin portal for working cases as well as for non-working cases. But in the working cases also it was not required to approve the tasks from Admin portal.

<img width="1092" alt="Screen Shot 2021-05-17 at 11 46 48 AM" src="https://user-images.githubusercontent.com/3957104/118442989-f56b3f80-b708-11eb-8b08-52f96ee0848e.png">

### Affected Product Version:
APIM 3.2.0 and Analytics 3.2.0

**Comment by AnuGayan** [comment]
This was fixed in the latest monetization implementation
