### ISSUE TITLE
 The disabling user claims in the backend jwt feature is not working.

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#11220]
### Description:
Can not disable adding user claims to the backend jwt.

### Steps to reproduce:

- Open the deployment.toml file and add the following lines to enable the backend jwt and disable the adding user claims to that.
```
[apim.jwt]
enable = true
encoding = "base64url" # base64,base64url
enable_user_claims = false
```

- Restart the server.
- Invoke a sample API and observe the backend jwt. ( decode it and observe the payload to find whether the user claims is included or not)

### Affected Product Version:
3.2.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9227
