### ISSUE TITLE
Embedded Micro Integrator server 4.0.0 doesn't start in Integration Studio 8.0.0

### ISSUE THREAD

**Issue by dsmohan** [wso2/product-apim#11239]
### Description:
I am new to Enterprise Integrator 7.1.0. I was following the documentation https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-service/#step-4-build-and-run-the-artifacts to create a simple service in EI 7.1.0. I am using Integration Studio 8.0.0 to create the project. After creating the project, when I try to deploy and run the project in the embedded Micro Integrator by following Step 4 in the documentation, I am getting the below error.

![image](https://user-images.githubusercontent.com/66669898/119133917-1b227c80-ba5a-11eb-8d61-e7deb3863689.png)

### Steps to reproduce:
1. Right click on the composite exporter project in the Integration Studio and select "Export Project Artifacts and Run".
![image](https://user-images.githubusercontent.com/66669898/119134433-bfa4be80-ba5a-11eb-8882-1b29ae5f57d4.png)

![image](https://user-images.githubusercontent.com/66669898/119134519-da773300-ba5a-11eb-8ede-457129461b7a.png)

### Affected Product Version:
Integration Studio 8.0.0

### Environment details (with versions):
- OS: Windows 10

I verified and found the path runtime/microesb to be present under the Integration Studio Home. Need suggestions on what could be causing the issue.

**Comment by ChoreoUptime** [comment]
By any chance, are you using any old workspace. Try using a new workspace with Integration Studio 8.0.0

**Comment by arunans23** [comment]
By any chance, are you using any old workspace. Try using a new workspace with Integration Studio 8.0.0

**Comment by dsmohan** [comment]
Hi Arun, I am using a new workspace only. When launching the Integration Studio 8.0.0, it automatically creates a new workspace.

Thanks,
Suman

**Comment by arunans23** [comment]
@dsmohan Normally, we have experienced this kind of issue, if we use an old workspace. 

Can you create a new workspace like below, and create a Hello World Project Sample, and check whether the sample is working? 
<img width="624" alt="Screenshot 2021-05-24 at 14 25 53" src="https://user-images.githubusercontent.com/17047910/119323637-8cea0880-bc9c-11eb-8c7a-3f974f0bcdc5.png">

If the issue still exists, can you zip the above workspace folder and attach it here?

**Comment by dsmohan** [comment]
@arunans23 I tried with new workspace as mentioned by you. The issue still persist. I have attached the zip of the new workspace folder.

Thanks,
Suman
[newWorkspace.zip](https://github.com/wso2/product-apim/files/6531483/newWorkspace.zip)

**Comment by arunans23** [comment]
@dsmohan  Thanks for attaching. 

```
java.nio.file.NoSuchFileException: D:\WSO2\WSO2-Integration-Studio-8.0.0-win32-x86_64\IntegrationStudio\runtime\microesb\conf\deployment.toml
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
```

According to the above logs, it says that it cannot find the deployment.toml file. Can you verify that the Micro Integrator server is available in the said location? (ie: `D:\WSO2\WSO2-Integration-Studio-8.0.0-win32-x86_64\IntegrationStudio\runtime\microesb`)

**Comment by dsmohan** [comment]
Thanks Arun for the help. The above mentioned folder path was missing. I have extracted the Integration Studio zip freshly and now the issue is resolved.

Thanks,
Suman
