### ISSUE TITLE
[APIM-3.1.0]-Can't create application that other user owns

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11246]
### Description:
In wso2am-3.1.0, when the application creation and sharing to a group are done at once it's throwing errors when they are done one by one it becomes successful.

### Steps to reproduce:
Observing a strange situation when sharing the applications in wso2am-3.1.0 as mentioned below.

- Created 2 users with organizations as userA -> orgA and userB -> orgB
- The userA created the application AppA and shared it in orgA. 
- The userB created the application AppA and shared it in orgA. Received the following error message.

`[2021-05-20 12:47:01,330] ERROR - UserAwareAPIConsumer A duplicate application already exists by the name - AppA
[2021-05-20 12:47:01,339] ERROR - ApplicationsApiServiceImpl An application already exists with name AppA
org.wso2.carbon.apimgt.api.APIMgtResourceAlreadyExistsException: A duplicate application already exists by the name - AppA`

- The relevant observations are as shown below.
![image](https://user-images.githubusercontent.com/20519000/119310684-bd767600-bc8d-11eb-8f19-a5fcc65f7881.png)

- The userB created the application AppA. Edited the application and added the sharing group as orgA. This flow was successful. 
![image](https://user-images.githubusercontent.com/20519000/119310705-c404ed80-bc8d-11eb-92e2-a5808baef5a3.png)
![image](https://user-images.githubusercontent.com/20519000/119310724-c8c9a180-bc8d-11eb-904f-ba72a7f67b60.png)

- Application list of userA from orgA is shown below.
![image](https://user-images.githubusercontent.com/20519000/119310745-d67f2700-bc8d-11eb-8ced-55c94bc666e1.png)

So now orgA has 2 AppA applications. This seems to be a bug.

### Affected Product Version:
wso2am-3.1.0
wso2am-3.2.0

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version
