### ISSUE TITLE
[APIM-3.1.0][Devportal][UI-Display]-Resource details in the devportal overview are not visible completely

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11259]
### Description:
In wso2am-3.1.0, when there are more than 5 resources created for an API, not all the resources are shown on the devportal overview page. One of the missing resources will be displayed partially as shown below. This indicates an incomplete list of resources.
![image](https://user-images.githubusercontent.com/20519000/119473212-95a81080-bd68-11eb-9865-00a67aa40926.png)

### Steps to reproduce:
1. Create an API with more than 5 resources (E.g: 10) in the publisher portal
2. Publish that API
3. Navigate to that API in devportal
4. You will see only the last 7 resources as shown below. 
https://user-images.githubusercontent.com/20519000/119473290-a789b380-bd68-11eb-8a73-b7d7cb3ee55c.mov

### Affected Product Version:
wso2am-3.1.0

**Comment by HiranyaKavishani** [comment]
Close the issue as it is not applicable with revamped UI in latest code
