### ISSUE TITLE
[APIM-3.2.0]-Create a custom role to block the subscriptions in the publisher portal

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11251]
### Description:
In wso2am-3.2.0 when a custom role is created to block the API subscriptions in the publisher portal, the following error is observed. This role shouldn't publish the API but only to block the subscriptions.
`[2021-05-18 21:54:11,142] ERROR - SubscriptionsApiServiceImpl Error while blocking the subscription 085f28fc-790f-43fc-89d1-6db7e880ac8d
org.wso2.carbon.apimgt.api.APIManagementException: User 'user' does not have the required permission: /permission/admin/manage/api/publish`

### Steps to reproduce:
1. In the carbon management console create a role called "blockRole" and assign the following permissions
     - Login
     - Configure > Governance and all underlying permission
     - Manage > Resources > Govern and all underlying permissions
2. Save the changes
3. Login to admin portal and in the scope management add a new role called "blockRole" and assign the following scopes to that role.
      - apim:api_view
      - apim:api_import_export
      - apim:publisher_settings
      - apim:subscription_block
      - apim:subscription_view
      - apim:tier_view
4. Save the changes
5. Login to carbon management console and create a new user called "blockUser"
6. Assign the "blockRole" to the "blockUser" and save it
7. Wait for some time for the registry cache to get cleared to you can restart the server
8. Login to the publisher portal as user who has the creator and publisher role
9. Create an publish an API
10. Login to devportal and subscribe that API
11. Again login to the publisher portal as "blockUser"
12. Under the subscriptions of the newly created API you can see the following options
![image](https://user-images.githubusercontent.com/20519000/119320156-e51f0b80-bc98-11eb-9b41-a4ba3159da01.png)
13. When clicked on the "Block All" or "Block Production Only" the following error will be logged.
`[2021-05-18 21:54:11,142] ERROR - SubscriptionsApiServiceImpl Error while blocking the subscription 085f28fc-790f-43fc-89d1-6db7e880ac8d
org.wso2.carbon.apimgt.api.APIManagementException: User 'user' does not have the required permission: /permission/admin/manage/api/publish`

### Affected Product Version:
wso2am-3.2.0

**Comment by Chamindu36** [comment]
This issue is already fixed in the public repository. Hence this issue can be closed.
