### ISSUE TITLE
Admin portal application search is not functioning

### ISSUE THREAD

**Issue by lathlk** [wso2/product-apim#11250]
### Description:
Use case: Have more than 100 applications in the environment and trying to search for an application from the 'Application Settings' UI in /admin portal. 

Issue: But we don't see any result even though we have an application with the name. But can see the application in /devportal but not in the /admin. 

Root cause: Web application doesn't make any rest API calls when the user triggers the search by entering the text into the search field. It is only trying to filter the result retrieved in the initial step("https://localhost:9444/api/am/admin/v1/applications?limit=100&offset=0" will call to retrieve the applications when the page is loaded). If the required application is not included in that first 100, we need to click "Show More" and get the first 200 and search. This behavior is not user-friendly since there may have thousands of applications and may search for the last application in the list.

### Steps to reproduce:
* Create more than 100 applications.
* Go to 'Application Settings' UI in /admin portal. 
* Search for the application name which is listed after the first 100 entries.
* We don't see the application in the result.

### Affected Product Version:
APIM 3.2.0

**Comment by kavishkafernando** [comment]
Master supports Search by application Owner and supports pagination as well. Hence this fix is not required
