### ISSUE TITLE
Grouping API in APIM publisher portal

### ISSUE THREAD

**Issue by Kalpanayella** [wso2/product-apim#11261]
### Describe your problem(s)
Grouping/tagging APIs in Publisher portal like we do/see in Dev portal. Our clients have APIs with almost similar names with minor changes like Service, ServiceAPI...Initially, there were few APIs but as the number of APIs is growing it is becoming difficult to search for the API we wanted for our development. We were looking for a feature where we can group the API based on functionality/portals/...We know we can categorize APIs but we can see them in categories only in the Dev portal. We were looking for the same feature in Publisher where we can group the APIs in the publisher and access that group during our development.

**Comment by Krishanx92** [comment]
This can be done with API Category feature.
https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping/
