### ISSUE TITLE
[2.6.0] Secondary User-Store Role Mappings are not working in JWT Bearer Grant

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#11267]
### Description:

In API Manager 2.6, when performing the JWT Bearer Grant with an external JWT token, the Role mappings made under the IDP configurations with Secondary User-store Roles are not honoured during the process. The Roles are getting mapped and returned without the Domain names and due to this, the requested scopes are not generated with the Access Tokens.

### Steps to reproduce:

- Start API Manager 2.6 (+1617817162459) and configure a Secondary User-store
- Publish an API along with a scope that is bound to a secondary user-store role
- Configure the API Manager for JWT Bearer Grant (create an IDP)
- Add a Role Mapping with the Secondary User-store role
- Perform the JWT Bearer Grant (with the scopes) and observe the behaviour

### Affected Product Version:

- API Manager v2.6.0 (+1617817162459)

**Comment by HiranyaKavishani** [comment]
Public fix https://github.com/wso2/carbon-apimgt/pull/8506/commits/a008d4b4c89df7ea07572e23fe5173e861ab8736
