### ISSUE TITLE
Issue when response cache is enabled for an API

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-apim#11270]
### Description:
When response cache is enabled for an API via the UI, even if the API is invoked multiple times during the timeout period, the events do not get published to Analytics. 
Hence the correct number of hits for the API does get reflected in the Usage Summary widget of APIM Publisher dashboard (the request count is only increased by 1).

### Steps to reproduce:
Create an API and enable response cache.
Invoke the API multiple times during defined timeout period.
View the usage stats in the Analytics dashboard.

### Affected Product Version:
3.1.0, 3.2.0

**Comment by isharac** [comment]
need to add below in the insequence of the api.

    <onCacheHit>
        <class name="org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler"/>
        <respond/>
    </onCacheHit>

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-apim/pull/11323
