### ISSUE TITLE
Publisher - Only searching APIs with lowercase

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#11279]
### Description:
When the APIs are searched by the API properties in the publisher, the search results will only show the lower case results. The issue is only occurring after the publisher web application is build.  

### Steps to reproduce:
Build the publisher app (npm run build:dev)
Add or update API properties as below in publisher portal
- API1 - testpropname:testpropval
- API2- TESTPROPNAME:TESTPROPVAL

Search APIs from TESTPROPNAME:TESTPROPVAL 

### Affected Product Version:
v3.2.0

**Comment by kavishkafernando** [comment]
this issue is not reproducible in master hence closing.
