### ISSUE TITLE
API Analytics UIs need to be more intutive

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#11289]
### Describe your problem(s)
Nuwan Dias wanted all the UIs in the API Analytics Portal to be reviewed to check whether it is intuitive. In instances where it is not intuitive, he wanted tooltips to be added as soon as possible. After this task is completed, he wanted all the pages under the viewing analytics section to be removed.

[1] https://apim.docs.wso2.com/en/latest/api-analytics/viewing/analytics-pages-introduction/

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
