### ISSUE TITLE
Cannot list inline documents when searching

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11281]
### Description:
Cannot list inline documents when searching via the publisher portal and the dev portal.

### Steps to reproduce:

- Publish an API via the publisher portal (**TEST_API**)

- Navigate to the **Documents** section and create an inline document for the API (**TEST_DOC**) as below image.
![Screenshot from 2021-05-28 22-02-04](https://user-images.githubusercontent.com/18566908/120185689-2894ef00-c230-11eb-8bf4-114e430a1aea.png)

_**Observations in the publisher portal**_

- Navigate to the publisher portal home page and try to search API and the document by parsing **TEST** as the keyword. Able to see only the API and the document is not in the list.
![Screenshot from 2021-05-28 22-02-29](https://user-images.githubusercontent.com/18566908/120185843-5aa65100-c230-11eb-808f-d2e1b51a5721.png)

- Even parse the exact document name (**TEST_DOC**) in the searching query. But cannot see the document.
![Screenshot from 2021-05-31 16-56-51](https://user-images.githubusercontent.com/18566908/120186536-3f881100-c231-11eb-848a-4bd21db1fe55.png)

_**Observations in the dev portal**_

- When trying to search the document by parsing the TEST keyword, can see only the API.
![Screenshot from 2021-05-28 22-13-04](https://user-images.githubusercontent.com/18566908/120186299-f20ba400-c230-11eb-8394-cc5a7d44a65e.png)

- Even parse the exact document name (**TEST_DOC**) in the searching query. But cannot see the document.
![Screenshot from 2021-05-31 16-56-02](https://user-images.githubusercontent.com/18566908/120186606-5890c200-c231-11eb-8416-5316fa99591f.png)

### Affected Product Version:
3.2.0

**Comment by msm1992** [comment]
This regression  issue is not reproducible in latest APIM 4.0.1 build. Hence resolving.
