### ISSUE TITLE
Migrated Application cannot update: throw an general error

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#11292]
### Description:

Migrated from APIM 2.6.0 to APIM 3.2.0, then tried to update an application that migrated from the old version. It is throwing a general error in UI and following the error log in the log file. 

```
ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Mapped applications are not allowed to update.
```
<img width="589" alt="Screenshot 2564-06-01 at 20 06 58" src="https://user-images.githubusercontent.com/15210142/120473021-35e2e280-c3c4-11eb-98a7-f2743c4ee447.png">

### Steps to reproduce:
- Migrated APIM 260 to 320
- In APIM 320, go to the Application list of the Devportal UI and select a migrtaed application
- Go to production Key tab and click "Update" button

### Affected Product Version:

APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:

Urgent

**Comment by EnricoDamini** [comment]
Hi, the issue is resolved?
