### ISSUE TITLE
EI Analytics UI needs to be renamed to MI

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#11290]
### Description:
Nuwan Dias said that it is incorrect to have the EI Analytics branded UIs with the MI content. He said that this has to be renamed. 

"Enterprise Integrator Analytics" needs to be renamed to "Micro Integrator Analytics" because after all it has the MI content in it.

After this task is completed, the documentation UIs in APIM 4.0.0 [1] and the other related pages need to be updated.

[1] https://apim.docs.wso2.com/en/latest/observe/mi-observe/using-the-analytics-dashboard/

<img width="954" alt="Screenshot 2021-06-01 at 23 42 53" src="https://user-images.githubusercontent.com/5195851/120421861-b8e44880-c384-11eb-92c0-63de05d6bcb8.png">

**Comment by Mariangela** [comment]
Damith Wickramasinghe mentioned that he will be working on this task

**Comment by dnwick** [comment]
Closing it as its done
