### ISSUE TITLE
[APIM-3.2.0][BUG]-Advanced throttling policy deletion

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11304]
### Description:
When trying to delete an advanced throttling policy that has active APIs attached to it, the policy is getting deleted. It shouldn't get deleted. This flow can be reproduced by following the below mentioned steps.

### Steps to reproduce:
1. Create 2 admin users in the carbon management console as admin1 and admin2
2. Log in as admin1 to the admin portal and create an advanced throttling policy
3. Log in as admin2 to the publisher portal and create an API with the newly created advanced throttling policy at the API level in the "Resource" UI.
4. Save the changes
5. Log in as admin1 to the admin portal and delete the created advanced throttling policy.
6. The message shown in the attached image will be displayed
<img width="1680" alt="image-2021-05-31-23-20-40-151" src="https://user-images.githubusercontent.com/20519000/120747622-f977c980-c51e-11eb-8625-45517e2a4e24.png">
7. When you click on the Delete button the policy will be deleted
8. Even after that, the API Definition in the publisher portal will still show the deleted policy name for API level x-throttling-tier
9. When you try to modify anything in that API, you will get a similar error message as shown below in the carbon management console.

`[2021-06-03 13:16:49,000] ERROR - APIProviderImpl Invalid x-throttling tier Demo found in api definition for resource GET /*
[2021-06-03 13:16:49,033] ERROR - ApisApiServiceImpl Error while updating the API : fcdb954f-dcdc-4d4b-af06-bb7391eac6d7 - Invalid x-throttling tier Demo found in api definition for resource GET /*
org.wso2.carbon.apimgt.api.APIManagementException: Invalid x-throttling tier Demo found in api definition for resource GET /*`
This behaviour cannot be reproduced if the same admin user who creates the API and tries to delete the policy from the admin portal. It only occurs when the API created admin user is different from the policy deleting admin user in admin portal. 

### Affected Product Version:
wso2am-3.2.0

**Comment by NethmiRanasinghe** [comment]
Advanced throttling policy is not allowed to be deleted once assigned to an API. So this issue is not reproducing in the latest version APIM 4.4.0.
