### ISSUE TITLE
403 error return when invoking API resources

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11302]
### Description:
403 error response returned when invoking API resources via the gateway

### Steps to reproduce:

- Publish an API.
- Delete the **local-entries** directory inside the <APIM_HOME>/repository/deployment/server/synapse-configs/default directory.
- Start the API Manager. During the start, run a JMeter script and invoke the API.
- After starting up the server, will receive a similar response as below.

`<ams:fault xmlns:ams="http://wso2.org/apimanager/security"><ams:code>900906</ams:code><ams:message>No matching resource found in the API for the given request</ams:message><ams:description>Access failure for API: /test/1.0.0, version: 1.0.0 status: (900906) - No matching resource found in the API for the given request. Check the API documentation and add a proper REST resource path to the invocation URL</ams:description></ams:fault>`

- In the carbon logs, can see the below warning log.

`[2021-06-03 21:12:16,257]  WARN - APIAuthenticationHandler API authentication failure due to No matching resource found in the API for the given request`

### Affected Product Version:
3.2.0

**Comment by tharikaGitHub** [comment]
Fixed in public branch - https://github.com/wso2/carbon-apimgt/pull/10588
