### ISSUE TITLE
Retrieve API definition/API synapse file when enabling Inbuilt artifact synchronization

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#11305]
### Description:
Currently, there is no mechanism to retrieve the synapse artifact of the API with the Inbuilt artifact synchronization[1]. The recommended approach is to fetch the data from GW REST APIs[2] where we have no API for this purpose. 

### Affected Product Version:
APIM 3.2.0

[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster/#inbuilt-artifact-synchronization
[2] https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/gateway-apis/gateway-v1/gateway-v1/#tag/Get-API-Artifacts

**Comment by binodmx** [comment]
## Pull requests:
### PMT - WSO2-CARBON-PATCH-4.6.0-1114
https://github.com/wso2-support/carbon-apimgt/pull/3026
https://github.com/wso2-support/carbon-apimgt/pull/3450
https://github.com/wso2-support/carbon-apimgt/pull/3452
https://github.com/wso2-support/carbon-apimgt/pull/3453
https://github.com/wso2-support/carbon-apimgt/pull/3456 (reverted)
https://github.com/wso2-support/carbon-apimgt/pull/3457 (reverted)
https://github.com/wso2-support/carbon-apimgt/pull/3466
https://github.com/wso2-support/carbon-apimgt/pull/3467 
https://github.com/wso2-support/carbon-apimgt/pull/3468 
https://github.com/wso2-support/orbit/pull/186
https://github.com/wso2-support/update-artifacts/pull/1377
### UMT - Update Number 1502
https://github.com/wso2-support/carbon-apimgt/pull/3470 
https://github.com/wso2-support/carbon-apimgt/pull/3477
https://github.com/wso2-support/carbon-apimgt/pull/3448 (Additional PR)
https://github.com/wso2-support/carbon-apimgt/pull/3484 (Additional PR)
### Integration tests
https://github.com/wso2-support/product-apim/pull/725 - PMT
https://github.com/wso2-support/product-apim/pull/738 - UMT
### Docs
https://github.com/wso2/docs-apim/pull/4278
