### ISSUE TITLE
Add case insensitive property for LDAP and AD userstore properties

### ISSUE THREAD

**Issue by ragwap** [wso2/product-apim#11318]
### Description:
Property "_**CaseInsensitiveUsername**_" needs to be added for LDAP and AD userstore properties.

### Affected Product Version:
apim-2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharikaGitHub** [comment]
This issue is fixed. Hence closing the issue.
