### ISSUE TITLE
API files get undeployed, when the NFS server goes down

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#11311]
### Description:
When the /server directory is mounted with NFS, all the APIs are undeployed from the gateway once the NFS Server goes down. This is due to the hot undeployment feature where missing files will be undeployed by running a scheduler task. The two scenarios where a single file gets deleted and the whole directory goes down due to NFS failures should be distinguished and we should stop hot undeployment when the whole directory disappears.

### Steps to reproduce:
- Mount the /server directory with NFS
- Create an API and invoke.
- Stop the NFS server and try to invoke the API.

### Affected Product Version:
APIM 3.2.0

**Comment by isharac** [comment]
duplicate https://github.com/wso2/product-apim/issues/7353
