### ISSUE TITLE
Error when using HTTP proxy and call HTTPS endpoint

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#11316]
### Description:
Even though we specify the protocol in the proxy configurations, Eventually it is reading protocol from the end URL. Which will ended up with Unsupported protocol exception.

Reason is protocol is override by this line https://github.com/wso2/carbon-apimgt/blob/315c009c1183ddeaf6bdb5b340a8e51b3df83bea/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/proxy/ExtendedProxyRoutePlanner.java#L110

### Steps to reproduce:
- setup a HTTP proxy
- Go to the publisher and navigate to the endpoint page.
- Provide with a HTTPS url and click on try-it button.

### Affected Product Version:
3.2.0

**Comment by Krishanx92** [comment]
Stale issue hence closing reconsidered if any requirements arise.
