### ISSUE TITLE
Email address field in Analytics email configuration have unintended behavior in publisher portal

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11315]
### Description:
Email address field under the alert configurations in the publisher portal have unintended behavior

### Steps to reproduce:

- Configure the API Manager 3.1.0 with API Manager analytics.
- Go to the publisher portal.
- Click on the Settings icon.
- Select an alert type and add an email address and save it.
- Again open the Settings section and able to notice the email address that was added previously.
- When trying to add a new email address, that will remove the previously configured email address automatically.
![3 1 0_publisher_issue](https://user-images.githubusercontent.com/18566908/121402227-415f7c00-c977-11eb-8078-c3a287fedb9f.gif)

### Affected Product Version:
3.1.0

**Comment by npamudika** [comment]
Closing as this is not applicable for the public branch.
