### ISSUE TITLE
Provide the capability to query details about any applications in the tenant by an tenant admin

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#11324]
### Describe your problem(s)
The dev portal GET applications/{applicationID} resource only provides the details of the applications relevent to the invoking user. However, it would be useful if we can have another resource to be used by the tenant admin where the admin user should be able to query any application by providing the application ID. This should return the general information of the application without sensitive information(Keys).

### Describe your solution
We will add a new resource to the admin REST API with apim:admin scope. 
Request template = GET https://localhost:9443/api/am/admin/v1/applications/{applicationID} 

Sample curl: 
```
curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" GET "https://localhost:9443/api/am/admin/v1/application/367a2361-8db5-4140-8133-c6c8dc7fa0c4" 
```

Response   
   
```
{
    "applicationId": "367a2361-8db5-4140-8133-c6c8dc7fa0c4",
    "name": "DefaultApplication",
    "throttlingPolicy": "Unlimited",
    "description": "This is the default application",
    "tokenType": "JWT",
    "status": "APPROVED",
    "groups": [],
    "subscriptionCount": 0,
    "attributes": {
        "Org Name": "Custom Attribute"
    },
    "subscriptionScopes": [],
    "owner": "admin"
} 
```  

---
### APIM Version
APIM 3.2.0

**Comment by riyazathali** [comment]
> Sample curl:
> 
> ```
> curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" GET "https://localhost:9443/api/am/admin/v1/application/367a2361-8db5-4140-8133-c6c8dc7fa0c4" 
> ```

The sample curl should be as  below.

`curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" GET "https://localhost:9443/api/am/admin/v1/applications/367a2361-8db5-4140-8133-c6c8dc7fa0c4"`
