### ISSUE TITLE
Issues when enabling Mutual SSL only and revert back to enable application-level security.

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#11362]
### Description:

**$Subject**

### Affected Product Version:
1. Create an API.
2. Navigate to **Runtime Configurations** -- > **Transport Level Security**  and select **_Mutual SSL_**.
3. Disable **Application Level Security**.

![Screenshot from 2021-06-25 00-34-07](https://user-images.githubusercontent.com/60866295/123318668-17987e80-d54d-11eb-82b7-ef862106b829.png)

4. Publish the API.

### Observations

- Now the published Mutual SSL API can be successfully invoked with the valid certificate and private key.

- And the user is not able to enable Application Level Security again.

![Screenshot from 2021-06-25 00-18-38](https://user-images.githubusercontent.com/60866295/123317424-9f7d8900-d54b-11eb-8db4-e9de53954348.png)

- And the user is not able to re-assign the business plans for this API as requested in the above error traces. Even if we assign tiers through the UI it is not getting populated and saved.

![Screenshot from 2021-06-25 00-24-05](https://user-images.githubusercontent.com/60866295/123317481-b2905900-d54b-11eb-941c-ab40c35ebe0d.png)

### Affected Product Version:

- APIM 3.2.0+1623485461485

**Comment by Krishanx92** [comment]
This is fixed in latest version hence cannot reproduce.
