### ISSUE TITLE
Issues in deleting Advanced throttling policies attached to a resource/API.

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#11361]
### Description:

- When following the **Steps to reproduce** erroneous behavior is observed.

### Steps to reproduce:

1. Create 2 admin users - **user1** and **user2**.
2. Create a custom advanced throttling policy **_testPolicy_** with the **user1**.
3. Create an API (eg:testAPI) with **user1**. 
4. Attach the **_testPolicy_** to testAPI at API/operational level.
5. Delete the **_testPolicy_** with **user2**.

### Observations:

- **_testPolicy_** is getting successfully deleted even though it is attached to an existing API.
- **_testPolicy_**  is not get deleted when trying to delete using **user1**

### Affected Product Version:

- APIM 3.2.0+1623485461485

**Comment by kavishkafernando** [comment]
This has been fixed in the latest WUM

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version (APIM 4.4.0)
