### ISSUE TITLE
The invalid swagger definition generates in the publisher portal for the APIs that import by using the APICTL tool

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#11368]
### Description:
The following error message is prompted in the publisher portal for the APIs that import by using the APICTL tool when navigating to the Resources tab.
![Screenshot 2021-06-25 at 16-37-13  Publisher WSO2 APIM](https://user-images.githubusercontent.com/73546297/123586836-f5c82180-d802-11eb-9331-28adf859aa0c.png)

### Steps to reproduce:
- Import the attached API project  [PizzaShackAPI-1.0.0.zip](https://github.com/wso2/product-apim/files/6723844/PizzaShackAPI-1.0.0.zip) by using the APICTL tool.
- log in to the publisher portal and select the respective API.
- The following error message will prompt when navigating to the Resources tab.

![Screenshot 2021-06-25 at 16-37-13  Publisher WSO2 APIM](https://user-images.githubusercontent.com/73546297/123586836-f5c82180-d802-11eb-9331-28adf859aa0c.png)

### Affected Product Version:
3.1.0

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/9544
