### ISSUE TITLE
Removing x-wso2-request-interceptor in API Definition

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11373]
### Description:
Automatically removing the x-wso2-request-interceptor (in the API level) property from the generated API resource when creating an API by using a swagger file with the **x-wso2-request-interceptor** in the API level.

### Steps to reproduce:

- Create an API by using a small swagger file with the **x-wso2-request-interceptor** property at the API level.
- After creating the API, Go to the publisher portal home page and click on the **API Definitions** section
- Check the generated API definition and able to see the provided **x-wso2-request-interceptor** through the swagger file is removed automatically.

### Affected Product Version:
3.2.0

**Comment by HiranyaKavishani** [comment]
Re-opening the issue to front port the fix in to APIM 4.0.0
