### ISSUE TITLE
Subscription upgrade not working - WSO2 APIM 3.1.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11372]
### Description:
The user cannot invoke the API after upgrading the subscription tier if the request has been throttled out already.

### Steps to reproduce:

- Create a Subscription Policy via the admin portal. (**1PER1DAY**)
- Go to the publisher portal and publish an API (Add **Unlimited** and **1PER1DAY** as subscription tiers.)
- Go to the dev portal and create an application. (**TEST_APP**)
- Subscribe to the created API to the **TEST_APP** with the **1PER1DAY** subscription tier.
- Invoke the API until the request gets throttled out.
- Delete the previous subscription and add a new subscription with the **Unlimited** tier.
- Generate a new access token through the dev portal and invoke the API and you will get the **429** response as below.
![SS1](https://user-images.githubusercontent.com/18566908/123740114-81a28200-d8c5-11eb-8142-926ceb5f7442.png)

### Affected Product Version:
3.1.0

**Comment by binodmx** [comment]
Please find the below summary of the fix below.

Patch number: WSO2-CARBON-PATCH-4.6.0-1174 
Update number: 1595

Support PRs:
https://github.com/wso2-support/carbon-apimgt/pull/3499 
https://github.com/wso2-support/carbon-apimgt/pull/3500 (x-full)
https://github.com/wso2-support/update-artifacts/pull/1409

Public PRs:
https://github.com/wso2/carbon-apimgt/pull/10640 
https://github.com/wso2/product-apim/pull/11383

Test PRs:
https://github.com/wso2-support/product-apim/pull/774 (x-full)
https://github.com/wso2-support/product-apim/pull/775

**Comment by npamudika** [comment]
Closing the git issue as the public fixes are added via https://github.com/wso2/carbon-apimgt/pull/10640 and https://github.com/wso2/carbon-apimgt/pull/10832

**Comment by npamudika** [comment]
This is fixed in APIM 3.2.0 as well.
