### ISSUE TITLE
Error in persisting throttling policies in API defintion and local entries

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#11396]
### Description:

When changing a Throttling Policy from Operation Level to API Level, in API swagger definition and local entries resource level `x-throttling-tier` is not getting removed. 

Vice-versa is fine where operational level throttling policy is get updated properly and API level policy is getting removed.

### Steps to reproduce:

1. Create an API
2. Assign operation level policy to a resource and deploy the API.
3. Change the policy to API level

### Affected Product Version:

APIM 3.2.0

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity.
