### ISSUE TITLE
Comments adding section in the dev portal is not visible

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11398]
### Description:
Comments adding section in the dev portal is not visible when enabling email as username feature

### Steps to reproduce:

- Enable email login feature by following the documentation [1]

```
[tenant_mgt]
enable_email_domain= true

[super_admin]
username = "admin@wso2.com"
password = "admin"
create_admin_account = true

[apim.throttling]
username = "admin@wso2.com@carbon.super"

[apim.throttling.jms]
username = "admin!wso2.com!carbon.super"

[user_store]
type = "database_unique_id"
username_java_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
```

- Start the API Manager server.
- Go to the publisher portal and publish an API (**PizzaShackAPI**). (logged by using admin@wso2.com users credentials.)
- Go to the dev portal and create 2 user accounts via the self-sign-up flow. (test@wso2.com, test@abc.com)

_Logged into the dev portal by using test@wso2.com username._

- After logging into the dev portal and select API and navigate to the **Comments** section and able to see the comment field as below image.
![Screenshot from 2021-07-03 02-51-43](https://user-images.githubusercontent.com/18566908/124409565-30cbd700-dd66-11eb-99aa-1ae61a3c2eb4.png)

_Logged into the dev portal by using test@abc.com username._

- After logging into the dev portal and select API and navigate to the **Comments** section and not able to see the comment field as below image.
![Screenshot from 2021-07-03 02-53-24](https://user-images.githubusercontent.com/18566908/124409634-522cc300-dd66-11eb-8194-f2e989c1e7c4.png)

[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#setup-an-e-mail-login

### Affected Product Version:
3.2.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/32
