### ISSUE TITLE
Improve the downloaded format of  custom mediation sequences

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#11392]
### Describe your problem(s)

When downloading the custom mediation sequences from Runtime configurations in API publisher the sequences are downloaded as a plain text file. eg: `custom_policy`
We can add the capability to download these sequences as `.xml` files. (`custom_policy.xml`)

### Affected Versions

3.2.0

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
