### ISSUE TITLE
Failure in unique name validation for API properties

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#11407]
### Description:
It is allowed to add the same property name twice even though it is mentioned as property name should be unique.

### Steps to reproduce:
Add the same property name twice as once with visibility option checked and next as visibility option unchecked from the UI.
![image](https://user-images.githubusercontent.com/30709975/124710145-ff940800-df19-11eb-9de9-c05497fe21c9.png)

### Affected Product Version:
APIM 3.2.0

**Comment by Chamindu36** [comment]
This is already fixed in the public repository. Hence this issue will be closed.
