### ISSUE TITLE
include user claims into backend JWT in Self JWT mode

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#11416]
### Describe your problem(s)
In current JWT authentication in order to include user claims into Backend JWT users have to embed the user claims into the Self Contain JWT which was used to invoke API. Therefore this needs to configure requested claims in Service provider of Oauth Application 

### Describe your solution

From the solution, We will call the Key Managers userinfo retrieval endpoint and retrieve the claims available in Key Manager.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2-extensions/apim-km-wso2is/pull/54
