### ISSUE TITLE
[3.0.0 ]Cannot update a parameter attached to an API resource due to a UI issue

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11427]
### Description:
When updating the parameters of a resource of an API, a duplicate parameter will be added rather than updating the existing one.

### Steps to reproduce:
1. Create an API and add some resources as shown below.
    ![image](https://user-images.githubusercontent.com/25246848/125406702-bee33580-e3d6-11eb-98e2-fe3ac7691bf8.png)
2. Expand one of the above, and add a parameter as shown below and click on Save.
    ![image](https://user-images.githubusercontent.com/25246848/125406833-e1754e80-e3d6-11eb-9dc7-5f8838f39fa1.png)
3. Again expand the same resource and click on the edit icon of the parameter and the below box will be displayed.
    ![image](https://user-images.githubusercontent.com/25246848/125407115-30bb7f00-e3d7-11eb-981e-f1611fca89ae.png)
4. **Note that the Type and the Format is not loaded properly**. Even you try to select either the Type or the Format, the UI will not get updated properly.
5. Finally, click on the **Done** button, another duplicate parameter will be added to the same resource.
    ![image](https://user-images.githubusercontent.com/25246848/125407428-7d9f5580-e3d7-11eb-91c1-fb0ce31b8d25.png)

### Affected Product Version:
WUM updated APIM 3.0.0 (wso2am-3.0.0+1625828890078.full.staging)

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS
- Browser: Chrome

**Comment by tharikaGitHub** [comment]
This is not reproducible in the latest master branch.
