### ISSUE TITLE
How to check api key in gateway??

### ISSUE THREAD

**Issue by allmind75** [wso2/product-apim#11421]
### Description:

Hello!
If you use the apikey issued from the developer portal, when you check the apikey at the gateway, do you check with the data stored in the db without communicating with the key manager?

https://apim.docs.wso2.com/en/3.2.0/learn/api-security/api-authentication/secure-apis-using-api-keys/

### Affected Product Version:

3.2.0

### Environment details (with versions):
- OS: linux
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
API key is a JWT token and this jwt token has all the details in it. So the gateway can validate the token itself without going to the key manager.

**Comment by allmind75** [comment]
@pubudu538
Thanks! 
I understand API key How it works.
