### ISSUE TITLE
[3.2.0] API Context and Version Appended Twice in Publisher Test Console when using Swagger 2.0

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#11432]
### Description:

The Publisher Test Console is appending the Context path and the Version of the API twice for Swagger 2.0 definitions. The OpenAPI definitions are working without any issues. Please find the screenshot of the Publisher Test Console for this behavior

<img width="1335" alt="Screenshot 2021-07-14 at 11 01 59" src="https://user-images.githubusercontent.com/29927177/125568208-fbfac470-7aff-4a2a-be94-aefd87ffe688.png">

### Steps to reproduce:

* Start API Manager v3.2.0
* Deploy the sample Pizzashack API (which has a Swagger 2.0 definition)
* Demote it to created state if it has been published and select Test Console to activate the Test Console (in Prototype mode)
* Try-out the API

### Affected Product Version:

- WSO2 API Manager v3.2.0

**Comment by vithu30** [comment]
This is fixed in public with https://github.com/wso2/carbon-apimgt/pull/10056
