### ISSUE TITLE
[3.2.0] WorkflowApprovalExecutorTest Failure in Postgres 13.3

### ISSUE THREAD

**Issue by rashm1n** [wso2/product-apim#11446]
### Description:
$Subject

### How to Reproduce
1. Set-up APIM 3.2.0 with Postgres 13.3
2. Run Intergration Tests
3. WorkflowApprovalExecutorTest fails

### Affected Product Version
APIM 3.2.0

**Comment by wasuradananjith** [comment]
This has been already fixed in master via [1]. Hence, closing the issue.

[1] https://github.com/wso2/carbon-apimgt/pull/10107
