### ISSUE TITLE
Cannot generate a REST API with a WSDL file on Windows

### ISSUE THREAD

**Issue by BuddhikaJayanarth** [wso2/product-apim#11448]
### Description:
**Windows** specific bug regarding generating a REST API with a WSDL file.

### Steps to reproduce:
On Windows OS:

1. Go to publisher portal -> "I have a SOAP endpoint"
2. Implementation type = Generate REST APIs
3. Input type = WSDL File/Archive
4. Choose a WSDL file (not a zip file)
5. Try to create API on next page and it will fail

### Affected Product Version:

APIM 3.2.0

### Environment details (with versions):
- OS: Windows 10

---

**Comment by wasuradananjith** [comment]
The fix for the master has been already done via https://github.com/wso2/carbon-apimgt/commit/5329a140308dc3c7ba99ed837a8d90e98738bf1f and https://github.com/wso2/carbon-apimgt/pull/10686. Hence closing the issue.
