### ISSUE TITLE
Backward compatible changes to additionalProperties related values in the velocity template

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#11443]
### Describe your problem(s)

Additional properties are passed to the velocity template to add any custom logic to the generated API synapse file (example: enable new handler based on the additional property, etc). 

But due to the displaying the additional properties in dev portal feature, `__display` is appened to the additionalProperty. This causes any logic written in the velocity template to not work.  This needs a backward compatible to work in both scenarios

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/10691
