### ISSUE TITLE
Adding Same Alert Configurations Entries by Multiple Users will show duplicate entries for the logged in User

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#11440]
## Description:
Could reproduce a behavior where multiple duplicate entries were displayed in the Alert Configuration UI if the same configurations were added by different users. 

This is similar when deleting the entries where duplicates are available.

### Adding

* User 1 logs into Publisher Portal and go to 'Settings'. Then click the Settings button of 'Abnormal Response Time' and then click '+ New Configuration'.

* After adding API1 as 'API Name', version as 1.0.0 and 'Abnormal Response Time' as 300 in 'Abnormal Response Time' alert, then click + mark to add. The entry should be successfully added and displayed in the list.  

* Then if User 2 logged into publisher and checked the Alert configurations, he/she can see the above configurations are also in the list of configurations even user2 didn't add anything and if User2 added entries with the same values, we could see duplicated entries listed in the UI as below,

<img width="990" alt="Screen Shot 2021-07-15 at 1 30 55 PM" src="https://user-images.githubusercontent.com/8849472/125766675-f7e6f71b-63f7-420d-a67a-a51e93e99ad1.png">

### Deleting

* If User2 deletes a single entry which has a duplicate, both the entries will be deleted and User1 will not be able to see his entry when he logged in.

 #### When All 3 entries there including a duplicated entry (API_A)

<img width="1335" alt="Screen Shot 2021-07-15 at 2 54 08 PM" src="https://user-images.githubusercontent.com/8849472/125766161-79d4f752-e322-417b-8427-8b2a0324be25.png">

 #### After deleting a single entry of API_A

<img width="1332" alt="Screen Shot 2021-07-15 at 2 54 21 PM" src="https://user-images.githubusercontent.com/8849472/125766149-9c02f91c-685f-4c18-8e35-bf4c46e6a7fd.png">

### Affected Product Version:
API Manager 3.2.0

**Comment by YasasRangika** [comment]
This issue is not reproducing in the master branch hence we can close this.
