### ISSUE TITLE
URL rewriting of the /oidc/logout is not happening when the ISKM reverse proxy is enabled

### ISSUE THREAD

**Issue by lathlk** [wso2/product-apim#11453]
### Description:
Trying to set up single sign-on with OpenID connect for the store and publisher portals.
But experiencing logout flow failure due to redirecting to KM instead of GW. Analyzed the source code and it seems that URL rewriting of the /oidc/logout is not happening in the gateway side[1]. (URL rewriting is happening only for /commonauth, /authorize and /oidc contexts).

### Steps to reproduce:

1. Setup APIM along with the ISKM

2. Enable the ISKM reverse proxy.
- GW: api-manager.xml
`<ISKMReverseProxyEnabled>true</ISKMReverseProxyEnabled>`
- KM: identity.xml
`<ReverseProxyConfig>
        <ReverseProxy>
            <DefaultContext>/oauth2/authorize</DefaultContext>
            <ProxyContext>/authorize</ProxyContext>
        </ReverseProxy>
 </ReverseProxyConfig>`

3. Configure Single Sign-on with OpenID Connect(Enable the consent)

4. Login and try to logout

oauth2_logout_consent.do is called from the KM side instead of GW. 
It was possible to resolve the issue by modifying the logic in order to rewrite the URL as below[1],

`.....
if (iskmReverseProxyEnabled) {
            // The logic is related if the API context is "/authorize", "/commonauth" or "/oidc" while status code is 302
            log.debug("Km revers proxy enabled for " + messageContext.getProperty(RESTConstants.REST_API_CONTEXT));
            if (messageContext.getProperty(RESTConstants.REST_API_CONTEXT)
                    .equals(APIMgtGatewayConstants.AUTHORIZE_CONTEXT) || messageContext
                    .getProperty(RESTConstants.REST_API_CONTEXT).equals(APIMgtGatewayConstants.COMMON_AUTH_CONTEXT)
                    || messageContext.getProperty(RESTConstants.REST_API_CONTEXT)
                    .equals(APIMgtGatewayConstants.OIDC_CONTEXT) || messageContext.getProperty(RESTConstants.REST_API_CONTEXT)
                    .equals("/oidc/logout")) {
                if (302 == (Integer) ((Axis2MessageContext) messageContext).getAxis2MessageContext()
                        .getProperty(SynapseConstants.HTTP_SC)) 
......
{`

### Affected Product Version:
2.6.0

[1] [https://github.com/wso2/carbon-apimgt/blob/e7b36b9211e77ca80720df664019386ac95e0fc3/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/SynapsePropertiesHandler.java#L92](https://github.com/wso2/carbon-apimgt/blob/e7b36b9211e77ca80720df664019386ac95e0fc3/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/common/SynapsePropertiesHandler.java#L92)

**Comment by hasuniea** [comment]
Fixed in master branch:
https://github.com/wso2/carbon-apimgt/pull/10700

Fixed in 2.6 support branch:
https://github.com/wso2/carbon-apimgt/pull/10700/

Fixed in full-x branch:
https://github.com/wso2-support/carbon-apimgt/pull/3643
