### ISSUE TITLE
Unauthenticated Request error when loading the Runtime Configurations - Publisher

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11458]
### Description:
When loading the Runtime Configuration section of the API by the publisher user, getting the **Unauthenticated request** error in UI

### Steps to reproduce:

- Create a user with the **Internal/publisher** user role.
- Log into the publisher portal and select an API.
- When navigating to the **Runtime Configurations** section of the selected API, we were able to see the **unauthenticated Request** error in the UI as below.
![Screenshot from 2021-07-13 21-22-16](https://user-images.githubusercontent.com/18566908/126595714-19534398-ae9f-4439-bc55-58c7da3eb1d6.png)

- Furthermore, we were able to see the below warnings in the carbon logs.

`[2021-07-13 21:11:00,287] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed`

### Affected Product Version:
3.2.0

### Similar Issues
https://github.com/wso2/product-apim/issues/9177

**Comment by YasasRangika** [comment]
Closing this issue since the public fix has been added via https://github.com/wso2/apim-apps/pull/60
