### ISSUE TITLE
[3.1.0] The users with the Internal/publisher role can't see the button to create an API Product unless there is at least one API Product already created

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11460]
### Description:
The button to create an API Product is only visible to the users who have the admin role. If there is at least one API Product created already then the button will be visible to the users who have the Internal/publisher role as well.

### Steps to reproduce:
1. Log in to the Publisher portal as the admin user and create two or more APIs. 
2. Now go to the API Products tab and the button to create an API Product will be visible.
    ![image](https://user-images.githubusercontent.com/25246848/126617973-8cf94712-af34-4d19-a739-081d82974c02.png)
3. Create a user with the Internal/publisher role
4. Log in to the Publisher portal using that user and go to the API Products tab. The button to create an API Product will not be visible.
![image](https://user-images.githubusercontent.com/25246848/126618443-b8db4cb2-88b9-4c6e-aa88-b249d6cc225e.png)
5. Again log in using the admin user and create an API Product.
6. Log in as the user with the Internal/publisher role and go to the API Products tab. Now, the button to create an API Product will be visible.
   ![image](https://user-images.githubusercontent.com/25246848/126618793-16964ed7-c83b-4ef2-8f79-81cd24bcbb12.png)

### Affected Product Version:
WUM wso2am-3.1.0+1626715309295.full

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS
- Browser: Chrome

**Comment by tharikaGitHub** [comment]
This is not reproducible in the pack built from the public branch.
