### ISSUE TITLE
[APIM 4.0]WebSocket API new topic additions doesn't align properly in UI

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#11487]
### Description:
Try out the WebSocket API creation in https://apim.docs.wso2.com/en/latest/design/create-api/create-streaming-api/create-a-websocket-streaming-api/

Go to Topics tab and see Pub and Sub doesn't get aligned properly

<img width="1680" alt="Screenshot 2021-07-27 at 11 12 20" src="https://user-images.githubusercontent.com/23296184/127102147-8903da4c-4d30-4beb-8de7-50c815127040.png">

**Comment by stefanonegri** [comment]
any update on this issue? when will it be solved? I wanted to show the websocket feature in a demo but it showed the issue reported here

**Comment by tharikaGitHub** [comment]
This issue is fixed in the latest code and also fixed in the reported APIM 4.0.0 version. Hence closing.
