### ISSUE TITLE
Having Read Only users in APIM Publisher Portal

### ISSUE THREAD

**Issue by mmmAlthaf** [wso2/product-apim#11498]
### Describe your problem(s)
A user (for example an internal developer) who has permission to only view the API details in the Publisher portal. The user should not be able to edit/create/publish APIs. The user should only be able to view the APIs and their configurations.

**Comment by Krishanx92** [comment]
https://apim.docs.wso2.com/en/latest/design/api-security/authorization/publisher-portal-in-read-only-mode/
