### ISSUE TITLE
Separate scope issuer from key manager core

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#11497]
### Describe your problem(s)
In order to use a separate scope issuers for the on premise apim product and the choreo product apim, we need to separate out the scope issuer classes from the key manager core component and have a separate feature for it.

The choreo product apim will use a separate scope issuer mentioned in https://github.com/wso2-enterprise/choreo/issues/6705

**Comment by Krishanx92** [comment]
Is this requirement still valid? We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
