### ISSUE TITLE
JIT provisioning - Removing locally assigned user roles in APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11499]
### Description:
Locally assigned roles get removed after performing JIT provisioning again for the same provisioned user.

### Steps to reproduce:

- Configure the WSO2 Identity Server 5.10.0 as an external IDP for the API Manager 3.2.0
- Perform a JIT provisioning by log into a portal. User will create in the API Manager side.
- Assign roles to the provisioned user on the API Manager side.
- Again perform a JIT provisioning by log into a portal.
- Check the user roles list that is assigned to the provisioned user and assigned local roles will get removed.

### Affected Product Version:
3.2.0

**Comment by msm1992** [comment]
public PR already merged with https://github.com/wso2/carbon-identity-framework/pull/3478/files. Hence closing.
