### ISSUE TITLE
Need to Increase TOKEN_SCOPE field length in tables

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#11501]
### Describe your problem(s)

Need to alter all existing `IDN_OAUTH2_ACCESS_TOKEN_SCOPE` tables to hold 100 varchars in `TOKEN_SCOPE` field.
This is in order to match the database script change introduced in: https://github.com/wso2/carbon-apimgt/pull/10704

### How will you implement it

---

**Comment by SwatiNEC** [comment]
Hi @chathuranga95 

I found this table in multiple repository of wso2. Is it required to update all of them or specific ones? As per my understanding all of them required update.
Please confirm.

**Comment by HiranyaKavishani** [comment]
Added the above to 4.1.0-4.0.0 migration scripts
