### ISSUE TITLE
Health check Implementation for APIM service

### ISSUE THREAD

**Issue by Jayanie** [wso2/product-apim#11509]
### Describe your problem(s)

It is required to have a health check implementation like liveness, startup, and readiness probes when starting and running API Manager.

### Describe your solution
- Implement a Rest service on the API manager side that we need to call when doing the health check in APIM service.
- We need to check health check conditions to set the health status to healthy or unhealthy.
- When checking the conditions we need to consider each profile in the API manager.
- When calling the health endpoint in apim service, we can set the health check state to ok if all the relevant conditions are satisfied. 
- We need to check and decide what are the conditions that we need to check when doing the health check.

**Comment by Krishanx92** [comment]
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/basic-health-checks/
