### ISSUE TITLE
[3.1.0] The users with the Internal/creator role get blocked after creating one document

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11549]
### Description:
The users with the Internal/creator role can only create one document from the Publisher Portal.

### Steps to reproduce:
1. Login to the Publisher Portal as a user with the Internal/creator role.
2. Create an API.
3. Add a document for that API.
4. If you check the documents tab now, the **Add New Document** button is nowhere to be found, which result in the creator users are getting blocked after adding one document using the UI.
    ![image](https://user-images.githubusercontent.com/25246848/129875122-38805dd0-0ade-4586-9c4e-6bcf2f023a25.png)
5. If you try the same steps with a user with the Internal/publisher role, that user can add multiple documents.

### Affected Product Version:
WUM: wso2am-3.1.0 1629088397606
U2: wso2am-3.1.0.63

### Environment details (with versions):
- OS: Ubuntu 20.04.2 LTS
- Browser: Chrome, Firefox

**Comment by wasuradananjith** [comment]
This issue exists in APIM 3.0.0 as well.

**Comment by thisaltennakoon** [comment]
I am not able to reproduce this behaviour in the master branch.
