### ISSUE TITLE
Issue when creating APIs with large OAS definition

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#11540]
### Description:
Following issue observed in browser console when creating API using large OAS definition:

```
Failed to execute 'setItem' on 'Storage': Setting the value of 'swagger-editor-content-cache' exceeded the quota.
```

**Comment by vithu30** [comment]
This issue is not reproducible in master pack. (built with carbon-apimgt version `9.0.280`)

**Comment by binodmx** [comment]
Issue can be reproduced in APIM-3.1.0. 

In UI it says 

```
Error while adding new API : <api-name> - Error while performing registry transaction operation
```

In carbon console log it says
```
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 65103
```

**Comment by Krishanx92** [comment]
This issue is not reproducible in master pack. Hence closing
