### ISSUE TITLE
The description tag is removed from the API definition when it is empty

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#11556]
### Describe your problem(s)
Description tags under the responses are getting removed automatically from the API definitions when it is empty. As per this comment [2], it is coming from [1] where we use the library to read the content from the parsed swagger. 

[1] - https://github.com/wso2-support/carbon-apimgt/blob/support-6.5.349/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/OAS3Parser.java#L954

### How will you implement it

---

**Comment by hasuniea** [comment]
This is not a bug in APIM itself but it comes from the swagger parser. Since the description tag is an empty string, it is parsed as null. Then the description is getting omitted when converting it to swagger string.This issue exists in the swagger-parser's latest release(2.0.27) as well. There is an open issue[1]  related to this issue in the swagger-parser repo.


[1]. https://github.com/swagger-api/swagger-parser/issues/1387

**Comment by hisanhunais** [comment]
The public fix has been done by upgrading the swagger-parser which was tracked using https://github.com/wso2/product-apim/issues/12258.
Hence closing this issue.
