### ISSUE TITLE
GraphQL Subscriptions support via Websockets

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#11574]
### Describe your problem(s)
Currently, APIM supports only queries and mutations for GraphQL APIs. We need to utilize the WebSocket protocol in APIM to route GraphQL subscription calls. 

### Describe your solution
- Subscription operations need to be routed to the backend via the WebSocket protocol.
- If the GQL has subscription operations,  we need to show an additional field to specify the subscription endpoint. This extra endpoint should be shown in publisher and devportal in the relevant places.
- Subscription endpoint should be invokable via the GraphiQL try out tool in devportal
- All existing functionalities that apply to GraphQL requests also should apply to GraphQL subscription requests (throttling, contract validation, query complexity, authentication/authorization, …)
- Analytics should capture the subscription operations under the same GQL API stats. (No need to count the messages flowing through the subscription endpoint)

### Identified Sub Tasks

- [x] #11689
- [x] #11690
- [x] #11692 
- [x] #11701
- [x] #11691
- [x] #11753
- [x] #11752
- [x] #11750
- [x] #11754
- [x] #11795
- [x] #11796
- [x] Evaluate adding a list of separate pipeline handlers to channel in InboundWebsocketChannelInitializer
- [x] #11847
- [x] #11848
- [x] #11849
- [x] #11850
- [x] Improve Endpoint UI to show both http and ws endpoints
- [x] Unit tests for GQL subscriptions
- [x] Integration tests with mock backend for GQL subscriptions
- [x] Documentation for GQL subscriptions

**Comment by fazlan-nazeem** [comment]
Some preliminary work done by an intern is documented here https://docs.google.com/document/d/19XEIwTb7AoqrThKyLz7taRDHLq83meY68joGpaIL5Rg/edit

**Comment by dushaniw** [comment]
Related PR

https://github.com/wso2/carbon-apimgt/pull/10895
https://github.com/wso2/product-apim/pull/12021
https://github.com/wso2/apim-apps/pull/100

Doc PR
https://github.com/wso2/docs-apim/pull/5041

Sample PR
https://github.com/wso2/samples-apim/pull/47

**Comment by dushaniw** [comment]
Related issues: https://github.com/wso2/product-apim/labels/feature%2FGraphQL%20Subs
