### ISSUE TITLE
read only user for the APIM Publisher portal

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#11575]
### Describe your problem(s)

The requirement is:
 A user (internal developer) who has permission to only view the API details in the Publisher portal. The user should not be able to edit/create/publish APIs. The user should only be able to view the API configurations. And only "privileged users" (internal developers they decide) will have permission to edit/create/publish APIs as it is possible right now. 

Currently, It kind of work but need to improve some places by doing error handling and hiding some UI components
https://www.youtube.com/watch?v=UwbNoQluH_o

### Related issue
https://github.com/wso2/product-apim/issues/8812

**Comment by hasuniea** [comment]
Please find the tasks
https://docs.google.com/spreadsheets/d/1-OnIxmgPeYWPoA8uwBmXujuZIpPf1iTQacrhf5W_6j4/edit#gid=0

**Comment by hasuniea** [comment]
I encountered permission issue [1].
[1].https://github.com/wso2/product-apim/issues/11991

**Comment by hasuniea** [comment]
Design doc : https://docs.google.com/document/d/1VNlv2HEB7EN_kk_57GmA65KtqO5vTu2eYjjS83VFf9E/edit?usp=sharing

**Comment by hasuniea** [comment]
Backend changes : https://github.com/wso2/carbon-apimgt/pull/10922
UI Changes: https://github.com/wso2/apim-apps/pull/107
