### ISSUE TITLE
Prototyped APIs to support normal API authentication mechanisms

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#11587]
### Describe your problem(s)
Currently prototyped APIs are not protected ones. Once they added to developer portal the consumers can try it without a token. But once it is published, it suddenly requires a token and all the client apps has to be changed which earlier used the prototyped APIs. If the prototyped APIs support authentication from day 1, the client apps can also create using authentication from that time and when API getting published, there's nothing much to change.

To get the older behaviour if need, we can disable the authentication for the API. But currently we need to do it for each resource. We can improve it to do from a single click from UI (can enable that option only when the API is prototyped. Ideally, disabling security shouldn't be an easy talk hence it shouldn't be enabled for Published APIs).

- [x] #11736
- [x] #11737
- [x] #11738
- [x] #11739
- [x] https://github.com/wso2/docs-apim/issues/4777

**Comment by dushansilva** [comment]
- [ ] Complete the required backend changes for security for prototype apis feature
- [ ] Complete frontend changes for security for prototype apis feature
- [ ] Fix test failures for security for prototype apis feature
- [ ] Improve performance of the remove security button added in resource page
