### ISSUE TITLE
where the apimgt 7.0.0-snapshot

### ISSUE THREAD

**Issue by liuhaif** [wso2/product-apim#1158]
Hi,
For c5 branch, where can I find the apimgt 7.0.0-snapshot.jar.
I want to compile the c5 branch.

liuhf

**Comment by abimarank** [comment]
@liuhaif You have to check in https://github.com/wso2/carbon-apimgt/ branch C5 (https://github.com/wso2/carbon-apimgt/tree/C5)

**Comment by liuhaif** [comment]
I got it. Thanks!
