### ISSUE TITLE
Test Console of the publisher portal hangs after updating the pack - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11596]
### Description:
Test Console of the publisher portal hangs after updating the pack to the latest Update level and the Test Console cannot load the swagger instance from the API response because according to the UI code, this swagger variable is assigning in an asynchronous way.

### Affected Product Version:
3.2.0

**Comment by hasuniea** [comment]
this issue is already fixed in master branch.
