### ISSUE TITLE
Too Many Redirects on Logout- [APIM 4.0.0] [Keycloak]

### ISSUE THREAD

**Issue by nuwankng** [wso2/product-apim#11617]
**Description**

After configuring federated authentication with  **keycloak 15.0.2** to the **APIM 4.0.0**, On the logout process it won't redirect the public API devportal. Instead browser shows Too many redirects message. There is a possibility of bounce back and fourth the logout request between keycloak and APIM. 

**Steps to Reproduce**

- Configure the keycloak and APIM 4.0.0 in a federated authenticated setup.
- Login in to the devportal using provisioned user from keycloak
- Logout from the portal and discover the behavior.

**Comment by msm1992** [comment]
PR : https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/87
