### ISSUE TITLE
Possible add white spaces for URL pattern - APIM 3.2.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#11630]
### Description:

In APIM 3.2.0, we can add resource URL patterns with white spaces.

eg: **GET /self care**
<img width="1217" alt="Screenshot 2021-08-31 at 15 19 13" src="https://user-images.githubusercontent.com/15210142/132214865-b3c48e0e-ea92-4140-a3c3-5e1a18511e7a.png">

This space is not detecting as invalid and this is leading to errors when invoking the API.
If we invoke this API by using the Try-out page of the dev portal, it is not detecting as an invalid protocol.
However, if tried to invoke the API through curl or other clients, it is showing 400 bad request. In the logs, we can see the below error.

```
ERROR - SourceHandler HttpException occurred 

org.apache.http.ProtocolException: Not a valid protocol version:  care HTTP/1.1

	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208) ~[httpcore-nio_4.3.3.wso2v4.jar:?]

:


Caused by: org.apache.http.ParseException: Not a valid protocol version:  care HTTP/1.1
```
The reason is the white space of the URL pattern.

If we compared this with APIM 2.6.0, it didn't allow us to create the URL pattern wite space. It is detecting while adding to the API.

**APIM 2.6.0 behaviour**
<img width="1298" alt="Screenshot 2021-08-31 at 15 20 26" src="https://user-images.githubusercontent.com/15210142/132215071-08d3f307-46b1-4ea6-87f6-3f3b0683f2cd.png">

However, APIM 3.2.0 doesn't have that capability and I tested with the latest update level of APIM 3.2.0 (075). APIM 320 can add and publish the API without any issue.

Need to fix this issue in the APIM 3.2.0.

### Affected Product Version:

APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:

bug

**Comment by Krishanx92** [comment]
Fixed with latest pack.
