### ISSUE TITLE
Improve existing PingFederate key-manager connector

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#11636]
### Describe your problem(s)
The default PingFederate key-manager connector does not contain the 'Client Authentication Type' and 'Restricted Scopes' parameters.

### Describe your solution
Include the 'Client Authentication Type' and 'Restricted Scopes' parameters for the PingFederate key-manager connector and use them for OAuth-client registrations in the PingFederate server.

### How will you implement it
Improve the existing connector implementation[1].

[1] - https://github.com/wso2-extensions/apim-km-pingfederate

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2-extensions/apim-km-pingfederate/pull/6
