### ISSUE TITLE
Add a new link to Public forum in Add new document section still asks for document content

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/product-apim#11647]
### Description:
When we are creating an API with APIM 3.0.0, Under documentation we can link a Public forum. Only option that is given is to enter the URL. After adding the URL, and press Add Document button, still the wizard asks to add content for the create document even though we can't add any content for PUBLIC_FORUM type.

### Steps to reproduce:

1. Create a new API.
2. Add a new document with the type of Public Forum.
3. After entering the URL, click Add Document.

### Affected Product Version:
APIM 3.0.0

**Comment by Sachini-Dissanayaka** [comment]
Fixed in the APIM latest release
