### ISSUE TITLE
Add new document URL validation is not displayed in the publisher APP

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/product-apim#11648]
### Description:
When we are adding a new document, if the source is provided as a URL, we have to add the url in the text field provided. However if there is a basic validation failure in the input url, UI does not show any error messages. ```ERROR - ApisApiServiceImpl Invalid document sourceUrl Format``` is printed in the wso2carbon logs. 
### Steps to reproduce:

1. Create a new API.
2. Add a document and select the source as URL.
3. Add a invalid URL eg: http:/

### Affected Product Version:
APIM 3.0.0

**Comment by Sachini-Dissanayaka** [comment]
Fixed in the APIM latest release
