### ISSUE TITLE
Primary key violations with persisted aggregation.

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-apim#11643]
### Description:
Running APIM-Analytics-3.2.0 with persisted aggregation the primary key violations can be observed relevant to the DAYS granularity levels.

### Steps to reproduce:
Generate a set of aggregation events that contain different timestamp values for AGG_TIMESTAMP and the AGG_EVENT_TIMESTAMP at HOURS level and try to trigger the aggregation based on the persisted aggregation to the DAYS level.

### Affected Product Version:
APIM-3.2.0

### Environment details (with versions):
- Not relevant

**Comment by dnwick** [comment]
Fixed with https://github.com/siddhi-io/siddhi/pull/1749
