### ISSUE TITLE
Cross Tenant Subscription feature is not working as expected

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#11640]
### Description:
The cross tenant feature is not working as expected in the master. Assume, I go to the Developer Portal of tenanta.com using a user in tenantb.com, and after I create an app that app is only available in the tenanta.com the Developer Portal. If I go to the tenantb.com the Developer Portal, the above-created app is not there.

But in 4.0.0 and lower versions, the apps are not limited to the organization that is selected. This is happening because of the org concept that we are using in Choreo [1].

### Steps to reproduce:
1. Create two tenants such as **tenanta.com** and **tenantb.com**.
2. Go to the Developer Portal and select the tenant domain as **tenantb.com**.
3. Go to the Applications tab and you can see the **DefaultApplication** is created.
![tenantb-tenantb](https://user-images.githubusercontent.com/25246848/132808723-9d537b39-8937-4d96-815f-2c35c97065c1.png)
4. Now switch the tenant to **tenanta.com**. Go to the Applications tab and you will not see the **DefaultApplication**. Now create a new application here.
![tenantb-tenanta](https://user-images.githubusercontent.com/25246848/132808893-0c140f39-6dd3-44a1-a801-94192470c029.png)
5. Now again switch the tenant to **tenantb.com** and you will only see the **DefaultApplication** not the **AppA**.
![tenantb-tenantb](https://user-images.githubusercontent.com/25246848/132808723-9d537b39-8937-4d96-815f-2c35c97065c1.png)

The applications are getting created separately organization-wise, which is wrong and affects the cross tenant subscription feature to get broken.

### Affected Product Version:
Master (Checked with carbon apimgt version 9.0.326-SNAPSHOT)

[1] https://github.com/wso2/carbon-apimgt/pull/10498/files#diff-12f710906e8ac379963b9527b560b589024a79f07c7395c425241e517048a0b0R293

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
