### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#11668]
Currently, in devportal, a hand-shaped cursor is used for the "copy to clipboard" option in Gateway URLs. (Screenshots are attached below)

![issue1](https://user-images.githubusercontent.com/44407066/69544169-30c5fb80-0fb5-11ea-8e4f-c34f36d2e79b.png)

![issue2](https://user-images.githubusercontent.com/44407066/69544539-f27d0c00-0fb5-11ea-9ac4-fd68f94d60b7.png)

It would look nice if we can change that pointer to something like in git.

![issue3](https://user-images.githubusercontent.com/44407066/69544756-64555580-0fb6-11ea-82f8-974247eb5f08.jpg)

**Comment by Krishanx92** [comment]
This is fixed in latest version.
