### ISSUE TITLE
Role name has character limitation in APIM-3.1.0

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11669]
### Description:
When a role is created in the carbon management console the role name can have only a character length up to 30. If we exceed we'll get the following error message in the UI.
![image](https://user-images.githubusercontent.com/20519000/87640414-51211100-c764-11ea-882c-f345c103a822.png)

### Steps to reproduce:
1. Navigate to the carbon management console
2. Create a new role with name length exceeding 30 characters. 
3. Click on finish/Next button
4. The error message will be displayed.

### Affected Product Version:
wso2am-3.1.0

**Comment by Krishanx92** [comment]
This validation coming from kernel side which affect to all the product.
