### ISSUE TITLE
Error Maven install

### ISSUE THREAD

**Issue by ahmedju** [wso2/product-apim#11674]
### Description:
command: mvn clean install
Its not working, its display me bellow error:

[ERROR] Failed to execute goal on project org.wso2.carbon.apimgt.impl: Could not resolve dependencies for project org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.impl:bundle:6.8.112-SNAPSHOT: Failed to collect dependencies at com.sun.java:tools:jar:11.0.1: Failed to read artifact descriptor for com.sun.java:tools:jar:11.0.1: Could not transfer artifact com.sun.java:tools:pom:11.0.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/sun/java/tools/11.0.1/tools-11.0.1.pom: Remote host terminated the handshake: SSL peer shut down incorrectly

### Steps to reproduce:
I follow same your steps to get source code carbon-apimgt project but not working, its fail in step 5 which is Maven clean install
![Error Maven install WSO2](https://user-images.githubusercontent.com/13928485/100857778-c41df080-3495-11eb-9e9d-e760395a8034.png)

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
