### ISSUE TITLE
[Publisher] Can not scroll Open API editor using mouse wheel

### ISSUE THREAD

**Issue by jhatzenb** [wso2/product-apim#11682]
### Description:
Can not scroll Open API defintion using mouse wheel when focusing Open API editor

### Steps to reproduce:
- Download WSO2 APIM 3.1.0
- Start server
- Go to publisher
- Create an API with an Open API Definition
- Save
- Edit API
- Go to API Definition > Edit
- Clic on left part and try to use mouse wheel
- The left part doesn't move

### Affected Product Version:
WSO2 APIM 3.1.0

### Environment details (with versions):
- OS: RedHat
- Client: Firefox 76.0.1
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
This is fixed in latest product, hence closing
