### ISSUE TITLE
Limitations caused when sslVerifyClient is read from the client side

### ISSUE THREAD

**Issue by sachi-d** [wso2/product-apim#11687]
**Description:**

In v6.4.50, limitations are caused when the server side property(sslVerifyClient) is read from the client side.

E.g. if the config value is not "require", the certificate is not loaded/sent over to the server at all.

https://github.com/wso2-support/carbon-apimgt/blob/support-6.4.50/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java#L6030

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
