### ISSUE TITLE
[Gateway] Validation schema not working for array of JSON

### ISSUE THREAD

**Issue by jhatzenb** [wso2/product-apim#11681]
### Description:
When an API returns an array of JSON the Schema validation fails if activated

### Steps to reproduce:
- Download WSO2 APIM 3.1.0
- Start server
- Deploy PizzaShackAPI
- Select Schema Validation in Runtime Configuration
- Save
- Try to consume with the resource `/menu` that returns an array of JSON Object
- The reponse contains the following error:
```
<am:fault xmlns:am="http://wso2.org/apimanager"><am:code>0</am:code><am:type>Status report</am:type><am:message>Runtime Error</am:message><am:description>A JSONObject text must begin with '{' at 1 [character 2 line 1]</am:description></am:fault>
```

### Affected Product Version:
WSO2 APIM 3.1.0

### Environment details (with versions):
- OS: RedHat
- Client: curl
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
Fixed with latest release APIM-4.4.0
