### ISSUE TITLE
[Publisher] Editing an API property after removing display deleted property

### ISSUE THREAD

**Issue by jhatzenb** [wso2/product-apim#11683]
### Description:
When editing API properties we cannot edit a property after deleting one

### Steps to reproduce:
- Download WSO2 APIM 3.1.0
- Start server
- Go to publisher
- Create an API
- Create two API properties 
- Click save
![image](https://user-images.githubusercontent.com/42028146/82996337-183aaa80-a005-11ea-9899-38515193947d.png)
- Delete the first element
- Click edit on the remaining element
- The edition display the deleted element
![image](https://user-images.githubusercontent.com/42028146/82996458-44eec200-a005-11ea-80c7-feb33eb0a8f8.png)

### Affected Product Version:
WSO2 APIM 3.1.0

### Environment details (with versions):
- OS: Red Hat
- Client: Firefox 76.0.1
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
Fixed with latest release APIM-4.4.0
