### ISSUE TITLE
[APIM-3.0.0] Devportal Try Out not generating cURL command with request payloads

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#11695]
### Description:
In APIM 3.0.0.48, Devportal is not generating correct cURL requests with the values provided in the request body.

### Steps to reproduce:
1. Create a sample API with a POST request and add a schema for the resource.
2. Invoke the POST resource from the developer portal by providing test values.
3. Check the cURL request and the test values are not getting added.

![notworking](https://user-images.githubusercontent.com/30709975/133404959-69ddf091-e779-4f9d-bc66-2ecf84e22471.png)

### Affected Product Version:
APIM 3.0.0

### Environment details (with versions):
APIM 3.0.0.48

**Comment by chashikajw** [comment]
Closing the issue sInce this only happens for 3.0
