### ISSUE TITLE
Error when selecting "Using IAM role-supplied temporary AWS credentials" access method

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-apim#11724]
### Description:
While trying to publish AWS Lambda API and with the IAM role-supplied temporary AWS credentials access method the following error has been observed in the Publisher.

`{org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl} - Unable to access Lambda functions under the given access method of API : 8540e9c5-aea2-40f2-868e-d86586784747 com.amazonaws.SdkClientException: Unable to load credentials from service endpoint`

Despite the error, it was possible to publish the API. However, while invoking the API following error trace can be observed in the Gateway.

`ERROR \{org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator} - Error while invoking the lambda function com.amazonaws.SdkClientException: Unable to load credentials from service endpoint at com.amazonaws.auth.EC2CredentialsFetcher.handleError(EC2CredentialsFetcher.java:183) at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:162) at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82) at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:151) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1164) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:762) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:724) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:2654) at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:2630) at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1497) at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1473) at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.invokeLambda_aroundBody2(AWSLambdaMediator.java:141) at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.invokeLambda(AWSLambdaMediator.java:106) at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.mediate_aroundBody0(AWSLambdaMediator.java:78) at org.wso2.carbon.apimgt.gateway.mediators.AWSLambdaMediator.mediate(AWSLambdaMediator.java:64) at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178) at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.apache.synapse.api.Resource.process(Resource.java:342) at org.apache.synapse.api.API.process(API.java:463) at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.net.ConnectException: Invalid argument (connect failed) at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) at java.base/java.net.Socket.connect(Socket.java:609) at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:54) at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:108) at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:79) at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:174) at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:122) 
... 40 more`

It seems the issue happens in the **InstanceProfileCredentialsProvider**[3] class in the com.amazonaws.auth package. According to the documentation[2], the IAM role-supplied method can only be used if the APIM instance and the Lambda function belong to the same AWS account. 
 
It seems by changing the **InstanceProfileCredentialsProvider**[3] class to the **DefaultAWSCredentialsProviderChain**[4] in the AWSLambdaMediator[5] is working fine. If we can fix this, it will enable the AWS Lambda API to be used with other than EC2 instances.

### Affected Product Version:
- WSO2 API Manager 4.0.0 

### Environment details:
- Docker

[1] https://support.wso2.com/jira/browse/MDFSUB-23
[2] https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-awslambda-api/
[3] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/InstanceProfileCredentialsProvider.html
[4] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html
[5] https://github.com/wso2/carbon-apimgt/blob/0bc69ca57fce13f87b386ce746207b41d7ff2028/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java#L164

**Comment by dnwick** [comment]
This is fixed in https://github.com/wso2/carbon-apimgt/pull/10815
