### ISSUE TITLE
Publisher endpoint landing page UI alignment issue

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#11733]
### Describe your problem(s)
In the welcome page cards, Card title dividers are not aligned properly

![image](https://user-images.githubusercontent.com/3313885/134463962-c8701624-6a83-4b53-95de-915a419f419c.png)

### Describe your solution

Define max-width and use css ellipsis for overflow text

**Comment by tmkasun** [comment]
![image](https://user-images.githubusercontent.com/3313885/134464455-23c348fb-274d-4bb8-b5ab-784c21fcdc47.png)

**Comment by nuwand** [comment]
The descriptions under each category should also ideally be of same length, for better aesthetics.

**Comment by rmsamitha** [comment]
This Card-based view is not available now in the "Endpoints" page. Hence the issue is not valid now.
