### ISSUE TITLE
Organization throttling policy is not possible

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-apim#11779]
### Describe your problem(s)

Currently, there is not possible to create a custom throttling policy based on the organization.
Multiple users can share applications if they belong to the same organization.
The use case is to throttle API invocation per organization (exp 5000 call/min) across all applications.

**Comment by bhathiya** [comment]
Please note that "Organization" is just another claim in the user profile, but not a first-class entity in WSO2 products. Therefore we don't plan to treat this claim in a special manner.
