### ISSUE TITLE
[APIM-3.2][REST API]  Consumer Secret is coming as null 

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#11797]
### Description:
When trying to get key details of a given type[1] via Store REST APIs, the consumer secret is coming as null. Please refer to the below.

```
 curl -k -H "Authorization: Bearer 48f10f0f-a79c-3529-a7fa-0296f7b829de" "https://localhost:9443/api/am/store/v1/applications/c73ad932-23d3-458b-b991-76910e598104/oauth-keys/f006c0da-2774-4548-a72d-554c885f6393"

Result:

{"keyMappingId":"f006c0da-2774-4548-a72d-554c885f6393","keyManager":"35aaf26e-b1d8-4d7a-a1e2-9963933f1367","consumerKey":"HG9_cCm4FdlB3WdlA7SZQyJyG7ca","consumerSecret":null,"supportedGrantTypes":null,"callbackUrl":null,"keyState":"COMPLETED","keyType":"PRODUCTION","mode":null,"groupId":null,"token":{"accessToken":null,"tokenScopes":[],"validityTime":0},"additionalProperties":null}
```

[1] https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/devportal-apis/devportal-v1/devportal-v1/#tag/Application-Keys/paths/~1applications~1{applicationId}~1oauth-keys/get

### Affected Product Version:
APIM 3.2

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This is expected, we didn't send Secret with REST API.
