### ISSUE TITLE
Some tags are not showing on the left side panel in DevPortal.

### ISSUE THREAD

**Issue by Abshan** [wso2/product-apim#11798]
### Description:
When the tags are listed alphabetically on the left side of the APIM-DevPortal, some tags are not showing on the left side panel in DevPortal.

### Steps to reproduce:
a) Create two APIS (test and SwaggerPetstore) on the APIM Publisher
b) Add 19 tags to the SwaggerPetstore API.
c) Add 31 tags to the Test API.
d) On APIM DevPortal, there are only 24 tags in alphabetical order. (IMG_PORTAL.png)
e) There is no paging option below to see the remaining tags.

![IMG_PORTAL](https://user-images.githubusercontent.com/40865976/135427955-99aa159f-d56b-4854-943d-5ccc03fdb28f.png)

### Affected Product Version:
WSO2AM-3.2.0

**Comment by hasuniea** [comment]
In the implementation level, we reuse the pagination concept but it is not nice to paginate the tags and it is not the recommend approach hence I removed pagination limits from the API call.
