### ISSUE TITLE
Add support for operation policies in API Products and API/Product Revisions

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#11846]

**Comment by 1akshitha** [comment]
Closing the issue as the architecture has been changed.

**Comment by 1akshitha** [comment]
At this level, we don't product API product itself to apply operation police to its resource. However, if the underlying APIs' operation has operation policies applied, these policies will be applied to the product's operation as well.

**Comment by 1akshitha** [comment]
Closing the issue as the PR https://github.com/wso2/carbon-apimgt/pull/11040 is merged.
