### ISSUE TITLE
Revision listing API does not return ordered response for Oracle DB

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#11858]
### Description:
When configured with Oracle DB, revision listing API (/apis/<apiID>/revisions) does not return the ordered response. This is returned correctly for other DBs such as MySQL , H2. Need to make it consistent.

### Steps to reproduce:

1. Setup APIM 4.0.0 with Oracle DB
2. Create an API 
3. Deploy 3 revisions.
4. Invoke https://localhost:9443/api/am/publisher/v2/apis/<api_id>/revisions or view the API response from browser network console.

For Oracle 

        {
        "count":3,
        "list":[
        {
            "displayName":"Revision 4",
            "id":"1a047090-a2e7-4fb3-9387-e546fb2a3dc6",
            "description":"Test Revision 1",
            "createdTime":1634019340000,
            "apiInfo":{
                "id":"8fb248da-e3c4-485c-9fcf-e17f676f7788"
            },
            "deploymentInfo":[
                {
                    "revisionUuid":null,
                    "name":"Default",
                    "vhost":"localhost",
                    "displayOnDevportal":true,
                    "deployedTime":1634019341000
                }
            ]
        },
        {
            "displayName":"Revision 5",
            "id":"546d67ec-1e00-4a7e-b037-23f72903be75",
            "description":"Test Revision 1",
            "createdTime":1634019464000,
            "apiInfo":{
                "id":"8fb248da-e3c4-485c-9fcf-e17f676f7788"
            },
            "deploymentInfo":[
                
            ]
        },
        {
            "displayName":"Revision 3",
            "id":"49ab7218-b38f-44fd-83d9-a8a7d95af103",
            "description":"Test Revision 1",
            "createdTime":1634019318000,
            "apiInfo":{
                "id":"8fb248da-e3c4-485c-9fcf-e17f676f7788"
            },
            "deploymentInfo":[
                
            ]
        }
        ]
    }

For MSSQL

    {
        "count":3,
        "list":[
        {
            "displayName":"Revision 3",
            "id":"236e99f5-d378-4537-b94b-8788df3de655",
            "description":"Test Revision 1",
            "createdTime":1633316824000,
            "apiInfo":{
                "id":"17d2293c-7f3e-4740-9153-c18902e1defc"
            },
            "deploymentInfo":[
                
            ]
        },
        {
            "displayName":"Revision 4",
            "id":"a2effb5e-173a-4297-9ec9-3375a1c15c50",
            "description":"Test Revision 1",
            "createdTime":1633316843000,
            "apiInfo":{
                "id":"17d2293c-7f3e-4740-9153-c18902e1defc"
            },
            "deploymentInfo":[
                {
                    "revisionUuid":null,
                    "name":"Default",
                    "vhost":"localhost",
                    "displayOnDevportal":true,
                    "deployedTime":1633316843000
                }
            ]
        },
        {
            "displayName":"Revision 5",
            "id":"73906ee1-44b8-4e1c-af96-6eedf6e06fd1",
            "description":"Test Revision 1",
            "createdTime":1633316964000,
            "apiInfo":{
                "id":"17d2293c-7f3e-4740-9153-c18902e1defc"
            },
            "deploymentInfo":[
                
            ]
        }
        ]
    }

### Fix:

Following query is used to retrieve revisions. 

    SELECT * FROM AM_REVISION AR LEFT JOIN AM_DEPLOYMENT_REVISION_MAPPING ADRM ON AR.REVISION_UUID = ADRM.REVISION_UUID  WHERE AR.API_UUID = ? 

Adding a `order by AR.ID` should work

### Affected Product Version:
APIM 4.0.0

### Environment details (with versions):
- OS:
- Client:
- DB : Oracle 12c

**Comment by YasasRangika** [comment]
This issue is no longer reproducing the latest APIM product. This has been solved via https://github.com/wso2/carbon-apimgt/pull/10874
