### ISSUE TITLE
Markdown documents get trimmed on the right side when shown in the dev portal - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11887]
### Description:
Markdown documents get trimmed on the right side when shown in the dev portal.

### Steps to reproduce:

- Publish an API via the publisher portal.
- Create a markdown document for the API. (with a long content)
- Load the API via the dev portal and load the document.
- The text of the created markdown document is getting trimmed from the right side.

### Affected Product Version:
3.2.0

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version
