### ISSUE TITLE
Endpoint suspension is not working based on a specific error code

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#11883]
### Description:
When a single error code is selected for suspending an endpoint from the Publisher, the configuration is not added to the API synapse file.

### Steps to reproduce:

1. Create an API from the publisher and select a single error code for endpoint suspension. (eg: 101504 : Connection timed out)
2. Save and publish the API.
3. Check the created API synapse file.

### Affected Product Version:
APIM 2.0.0

**Comment by msm1992** [comment]
This issue is only reproducible with the Jaggery API used in APIM 2.x. Issue cannot be reproduced in the REST API used in latest version. Hence resolving the ticket.
