### ISSUE TITLE
A new resource to Gateway REST API as a health check API to verify whether all the APIs are deployed or not

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/product-apim#11884]
### Describe your problem(s)
With the new Artifact Synchronization architecture since WSO2 APIM 3.2.0, APIs will be deployed from a storage instead of the file system. If there are several APIs waiting to be deployed at the startup, it will take some time to get all the APIs deployed in the gateway. There is no proper way to verify whether all the APIs are deployed in the gateway or not before routing the traffic to the gateway. 

### Describe your solution
A new resource to the Gateway Rest API, which will return the status of API deployment in the gateway. If all the APIs are deployed in the gateway, this resource should send 200 OK, and if there are APIs that are missing or waiting to be deployed, the resource should return the list of these APIS.

**Comment by 1akshitha** [comment]
After having a discussion with @tharindu1st , we will have it as just a health check endpoint. This will return 200 OK if all the apis are deployed and 403, if at least one API is not deployed. it will return 403. We can use the /apis resource of the Gateway REST API to get the list of APIs deployed in the gateway.

**Comment by Krishanx92** [comment]
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/basic-health-checks/
