### ISSUE TITLE
[APIM-4.0.0]-Admin portal requests /oidc/checksession from localhost

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11898]
### Describe your problem(s)
In the following case in wso2am-4.0.0, is it feasible to parameterize the following configuration at **<AM_HOME>/repository/deployment/server/jaggeryapps/admin/site/public/conf/settings.j**s to deployment.toml

```
 idp: {
        checkSessionEndpoint: 'https://localhost:9443/oidc/checksession',
    },
```
The concern is when the OIDC federations are enabled, the publisher and devportal **/checksesion** endpoint refers to the following url set at deploymet.toml

```
[apim.idp] 
oidc_check_session_endpoint = "https://localhost:${mgt.transport.https.port}/oidc/checksession"
```
Similarly, it should refer to it from deployment.toml instead of **/settings.js** to admin portal as well.

**Comment by msm1992** [comment]
This is addressed in the fix done in [1].

[1]. https://github.com/wso2/apim-apps/pull/17/files
