### ISSUE TITLE
[2.1.0] - To fix the issue that invokes system.getProperty() every time whenever the isConfigEnabled method is getting executed

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-apim#11941]
### Description:
The system.getProperty() method is getting invoked every time whenever the isConfigEnabled method is getting executed. 

### Describe your solution : 
We need to add the below parameter under the system property section in the wso2server.sh file.
`-DenableCorrelationLogs=false`

### Affected Product Version:
2.1.0

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity.
