### ISSUE TITLE
Resource level failover and load balance endpoints

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-apim#11947]
### Describe your problem(s)
In Open API Specification's (API definition's) resource level we cannot define failover and load balance endpoints. 
After defining above configuration in resource level, saved swagger definition does not contain (discards) the
added failover and load balance end points at the resource level.

Example:

```
paths:
  "/pet/findByStatus":
    get:
      responses:
        '200':
          description: OK
      x-wso2-production-endpoints:
        urls:
        -  https://localhost:2380/v1
        type: failover
```

### How will you implement it

---

**Comment by YasasRangika** [comment]
API-M is not supported for resource-level failover or load balance endpoint configurations. Hence this is not a valid requirement.

**Comment by YasasRangika** [comment]
Reopening this issue to track in a new feature.

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
