### ISSUE TITLE
Devportal renders a blank white page when after click view in devportal button in Publisher portal

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#11944]
### Description:
when I follow the below steps APIM-4.1.0 devportal gives a blank white page
- create a tenant and tenants user
- log in using tenant user
- create & publish a new API
- click view in devportal button

sometimes this happens when login in using carbon super admin user credentials as well.

![devportal](https://user-images.githubusercontent.com/28702407/140013541-74f2182f-eaa5-49ee-978f-aef2dae532ee.png)

### Affected Product Version:
APIM-4.1.0

**Comment by HiranyaKavishani** [comment]
The issue is not reproduced in latest pack
