### ISSUE TITLE
Integration with service registry

### ISSUE THREAD

**Issue by yhilem** [wso2/product-apim#1194]
APIM Gateway Routes client calls to services.
My requirement is to let APIM Gateway gets services locations from the service registry (Eureka, Apache Zookeeper, Consul, Etcd ...)

Is that possible?
Have you considered or planned this possibility?

see : https://github.com/wso2/msf4j/issues/274#issuecomment-260680491

![apigateway msf4j](https://cloud.githubusercontent.com/assets/13407261/20455320/6ce4a91a-ae59-11e6-92c5-774f1be78d31.jpg)

**Comment by yhilem** [comment]
Hi team,

FYI : The Benefits of Exposing Microservices in WSO2 API Manager : http://wso2.com/library/articles/2016/10/article-the-benefits-of-exposing-microservices-in-wso2-api-manager/

**Comment by chamilaadhi** [comment]
You won't be able to do it using out of the box API manager. But you could create a custom mediator and custom sequence and achieve this.[1]

This blog post[1] might be helpful (the blog addresses a different scenario. but you could use same method for your scenario). In this, the backend url is resolved using a mediator and some other parameters. You could use that kind of mediator to get the service urls and build the backend url

[1] https://docs.wso2.com/display/AM200/Adding+Mediation+Extensions
[2] http://nuwanzone.blogspot.com/2015/03/api-gateways-with-dedicated-back-ends.html

**Comment by yhilem** [comment]
Thank you.
spring-cloud-netflix-sidecar (https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-sidecar) seems also a viable solution : 
- How can I integrate my Rails / NodeJS / Express / PHP application into a Spring Cloud? (http://stytex.de/blog/2016/01/18/spring-cloud-sidecar-applications/)
- Example with Spring Cloud microservices and integrating sidecar applications : https://github.com/xetys/microservices-sidecar-example

**Comment by yhilem** [comment]
Hi Team,
With the future major version based on C5 and MSF4J, do you have any idea how to do it?
Our stack is based on Spring Cloud and we need to use WSO2 APIM Gateway instead of Zuul (Spring Cloud Netflix).
Thank you.

**Comment by uvindra** [comment]
Sorry for the delay in replying.

The C5 based APIM product will ship with the powerful ballerina integration language[1]. This will allow you to implement the logic required to make a call to a service registry and retrieve the actual service that needs to be called. 

[1] http://ballerinalang.org/

**Comment by harsha89** [comment]
Answered hence closing

**Comment by yhilem** [comment]
Here is a very interesting example :
Tuesday, October 10, 2017
WSO2 API Manager with Consul for Dynamic endpoints in distributed deployment
https://shammijayasinghe.blogspot.fr/2017/10/wso2-api-manager-with-cosul-for-dynamic.html

Thanks
Youcef HILEM

**Comment by adramazany** [comment]
hi 
It's also my problem!
but solution in the https://shammijayasinghe.blogspot.fr/2017/10/wso2-api-manager-with-cosul-for-dynamic.html article is not good
because It does not use endpoint and then lose many features of endpoints eg: failover,circuit breaker, ....
thanks  yhilem for this issue
