### ISSUE TITLE
API Property name validations do not work 

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#11980]
### Description:
Can add restricted property names without any UI validation issues, **when show in devportal is checked**.

<img width="1569" alt="Screenshot 2021-11-10 at 10 14 16" src="https://user-images.githubusercontent.com/28379317/141051375-0b169bb3-fa49-4be3-a5a6-27fd267d684a.png">

### Affected Product Version:
APIM 3.2.0 (U2 level 100)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Fixed in latest APIM-4.4.0
