### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Mars-2030** [wso2/product-apim#12003]
### Description:

I receive this error `api-manager.sh: line 320: /Library/Internet: No such file or directory`
not sure how to solve this 

### Steps to reproduce:
I set the Java home as  `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
`
then Run this `sh api-manager.sh ` inside wso2am-4.0.0/bin folder the received this error
```
JAVA_HOME environment variable is set to /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
CARBON_HOME environment variable is set to /users/usera/downloads/wso2am-4.0.0
Using Java memory options: -Xms256m -Xmx1024m
api-manager.sh: line 320: /Library/Internet: No such file or directory
```

I am not sure what should I do here

### Environment details (with versions):
- OS: Mac Big Sur

**Comment by Namratapaw** [comment]
Have you upgraded to wso2 4.0.0 from 3.2.0?

**Comment by Krishanx92** [comment]
@Mars-2030 Is this resolve?

**Comment by Krishanx92** [comment]
Closing the issue, please re-open if issue persist.
