### ISSUE TITLE
Consent Purposes Gets Deleted While User Exist

### ISSUE THREAD

**Issue by Abshan** [wso2/product-apim#12033]
### Description:
When we have configured User Self-Signup and created a consent purpose for SELFSIGNUP, the consent purpose is deletable even when an existing user has given the consent. This is not the expected behaviour. When there's a user existing who has given the consent, we should not be able to delete the Consent Purpose as an error should be prompted, as shown below. This should be the expected behaviour.
![image](https://user-images.githubusercontent.com/40865976/142829093-d13346c1-07f2-4771-a6be-53b24d67b671.png)
### Steps to reproduce:
1). Configure self-registration for the dev portal in the management console, under
**Identity Providers -> Resident -> Account Management Policies -> User Self Registration**
2). Set Enable Self User Registration to true
3). Click on Manage Self-Sign-Up purposes in the same window and add a new purpose as shown below.
![image](https://user-images.githubusercontent.com/40865976/142827965-93b5bfd9-f8f4-428c-bd4d-3caa3aefa4a2.png)
4). Then click on Finish and again Finish and then Update the configuration.
5). Once you have configured User Self Registration, go into devportal, click on the sign-in option, and click on Proceed to Self-Register and create a new user.
6). Once you have created a user using the self-registration process, go back to the management console, and under Consent Purposes -> List, you'll see the previously created consent purpose. If you click on the delete option and select Yes, consent will get deleted.

### Affected Product Version:
WSO2AM-3.2.0.86 - Latest (3.2.0.102)

**Comment by RakhithaRR** [comment]
Closing since all the fixes are merged.
