### ISSUE TITLE
Error while anlayzing query complexity for GraphQL subscriptions : Data fetcher must return a Publisher of events when using graphql subscriptions

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12044]
### Description:
The subscription type defined in schema is as follows
```
type Subscription {
  # Listens for changes in lift status
  liftStatusChange: Lift

  # Listens for changes in trail status
  trailStatusChange: Trail
}
```
When a GraphQL APIs is created by importing such a schema, query complexity and depth analysis throw an error in backend for requests which does not exceeds the complexity or depth.

```
[2021-11-22 12:41:11,910] ERROR - GraphQL Execution '0fb11ab7-ca89-42ab-8138-ed139033443b' threw exception when executing : query : 'subscription {
  liftStatusChange {
    id
    name
    status
  }
}
'. variables '{}'
java.util.concurrent.CompletionException: graphql.AssertException: You data fetcher must return a Publisher of events when using graphql subscriptions
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_251]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_251]
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) [?:1.8.0_251]
```
An issues was recently fixed in GraphQL java for similar stack trace from https://github.com/graphql-java/graphql-java/pull/1804. This is available with v15 release. In API-M we are using v13 of graphql-java library. We need to  update dependencies and check if our issues is getting resolved in v15 release. That need extensive testing of use cases where we use graphql-java library.

Can reduce the severity of the issue,  since for GQL subscription ops, the return type is always non nullable  and the request send for an API with following schema change works.

```
type Subscription {
  # Listens for changes in lift status
  liftStatusChange: Lift!

  # Listens for changes in trail status
  trailStatusChange: Trail!
}
```

### Steps to reproduce:
1. Create GraphQL API with schema [testschema.txt](https://github.com/wso2/product-apim/files/7586095/testschema.txt)
2. Invoke subscription endpoint with valid query.
3. Check carbon logs for above error.

### Affected Product Version:
4.1.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
