### ISSUE TITLE
Support graphql-ws protocol for GraphQL subscriptions 

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12043]
### Description:
Currently for GraphQL subscriptions, the sub protocol header "graphql-ws" is set as an axis2 property from the endpoint_template velocity template. However, now "graphql-ws" becoming obsolete and `graphql-transport-ws` (https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) is becoming the latest adaption of it. To support latest protocol,

1. Need to update GraphiQL editor to send `graphql-transport-ws` messages.
2. Change the axis2 property value from endpoint template or make the value configurable for all the APIs.

**Comment by dushaniw** [comment]
This should be done after websocket listener implementation in https://github.com/wso2/micro-integrator/issues/2407

**Comment by HiranyaKavishani** [comment]
Removing 4.1.0 tag and adding 4.x.x as we planned to ship this in next release

**Comment by HiranyaKavishani** [comment]
@wasuradananjith will add the fix for master
