### ISSUE TITLE
Harmless Error message "No throttle policies available in the tenant" getting printed while an API is published

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-apim#12047]
### Description:

When an API is created/published through the APIM3.2.0 latest update level, the following harmless error message getting printed without breaking the API creating/publishing process.

`[2021-11-23 12:06:56,852] ERROR - APIMappingUtil No throttle policies available in the tenant carbon.super`
### Steps to reproduce:

- Take the latest Update level of the APIM3.2.0
- Log in to the Publisher Portal and Create an API.
- Check the wso2carbon.log file and you will be able to observe the above error trace.

### Affected Product Version:

APIM3.2.0

**Comment by hasuniea** [comment]
This was resolved
