### ISSUE TITLE
Multiple Issues with JSON Schema Validation IN APIM 4.0.0

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#12052]
### Describe your problem(s)
1) Json-schema validation is not happening when lower case content-type header is used. 
2) When json schema validation is enabled for wildcard resource ( POST /* ) Publisher Try-out console validates the schema properly. But in devportal tryout tool it is not.

**Comment by Krishanx92** [comment]
Closing the issue with above PRs.
