### ISSUE TITLE
Defined allowed cipher for WSS endpoints in APIM

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/product-apim#12051]
### Description:
As per the source code[1], we can define the allowed ciphers for WSS endpoints through a configuration. But when checking locally we were not able to do that due to J2 limitation. 

[1] - https://github.com/wso2/product-apim/blob/master/modules/distribution/product/src/main/resources/conf/templates/repository/deployment/server/synapse-configs/default/inbound-endpoints/SecureWebSocketInboundEndpoint.xml.j2#L21-L24
### Affected Product Version:
APIM-3.2.0

#### Suggested Labels:
APIM-3.2.0

**Comment by npamudika** [comment]
Related issue https://github.com/wso2/product-apim/issues/10799

**Comment by npamudika** [comment]
Public PR https://github.com/wso2/product-apim/pull/11081

**Comment by npamudika** [comment]
Closing the git issue as the public PR is already merged.
