### ISSUE TITLE
Support "nonProxyHosts" proxy configurations in APIM-4.0.0

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-apim#12050]
### Describe your problem(s)
As per the current observations, APIM-4.0.0 does not support the "nonProxyHosts" property in the deployment.toml file.

### Describe your solution
The same issue has been discussed in the git issue[1].
[1] https://github.com/wso2/product-apim/issues/11129

**Comment by Sarangan0219** [comment]
This is already fixed in master via https://github.com/wso2/carbon-apimgt/pull/10472
