### ISSUE TITLE
Missing J2 config to enable the "APIEndpointPasswordRegistryHandler" in registry.xml file : APIM 400

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#12063]
### Description:

Below, "APIEndpointPasswordRegistryHandler" is available in the registry.xml file of APIM 400, but it is not enabled.
{code:java}

    
{code}
And "registry.xml.j2" file doesn't exist how to enable it too.

### Steps to reproduce:
- Check the configurations. 

### Affected Product Version:

APIM 400

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Chamindu36** [comment]
Hi @nadeepoornima,

Here are the steps to add to enable the "APIEndpointPasswordRegistryHandler" in APIM 4.0.0.

1. Navigate to the **<APIM_HOME>/repository/conf/ folder and open deployment.toml** file.
2. Add the following config there.
 
```
[[registry_handler]]
class="org.wso2.carbon.apimgt.impl.handlers.APIEndpointPasswordRegistryHandler"
method="GET,PUT"
filter_class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher"

[registry_handler.filter_properties]
mediaType = "application/vnd.wso2-api+xml"
```
 

3. Then start the server and check the **<APIM_HOME>/repository/conf/registry.xml** file.
4. The required config will be added there as follows.
```
  <!--Config for custom registry handlers.-->
 <handler class="org.wso2.carbon.apimgt.impl.handlers.APIEndpointPasswordRegistryHandler" method="GET,PUT">
 <filter class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher">
 <property name="mediaType">application/vnd.wso2-api+xml</property>
 </filter>
 </handler>
```
 This will solve the above issue.
