### ISSUE TITLE
Introduce full self-contained access tokens without a persistence layer

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#12075]
### Describe your problem(s)

The involvement of a persistent layer in the JWT token generation process causes a considerable performance impact. JTI of a JWT is stored in the DB for each new token generated even though its not directly used in the validation purposes. The involvement of such an insert query in the above flow can reduce the performance considerable due to the huge number of entries that can be available in the token table and the number of indexes at the token table.

### Describe your solution
Hence avoiding the persistence of the above JTI removes the involvement of a persistence layer in JWT process and improves the performance of the above flow by large.

**Comment by nandika** [comment]
This was implemented for APIM 4.3.0
