### ISSUE TITLE
[APIM 4.0] The error occurs when approving Applications if the ApplicationRegistrationApprovalWorkflowExecutor is enabled

### ISSUE THREAD

**Issue by shankeerthan-kasilingam** [wso2/product-apim#12071]
### Description:
If we enable ApplicationRegistrationApprovalWorkflowExecutor, We’ll receive an error message when we approve the application in the Admin portal .

### Steps to reproduce:

- Enable <ProductionApplicationRegistration executor="org.wso2.carbon.apimgt.impl.workflow.ApplicationRegistrationApprovalWorkflowExecutor" /> in /_system/governance/apimgt/applicationdata/workflow-extensions.xml

- Create Applications in the dev portal

- Check Code grant and update the call back URL

- Generate Production keys

- Go to Admin portal => “Application Registration”

- Click “Approve” on the application you have created

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Sarangan0219** [comment]
Fixed in master branch via https://github.com/wso2/carbon-apimgt/pull/10479
