### ISSUE TITLE
Unable to download the GraphQL Schema via devPortal

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#12072]
### Description:
Previously, users were able to download a GraphQL Schema via Developer Portal [1]. However, in wso2am-4.1.0-26-nov-2021-SNAPSHOT.zip there is no way to download a GraphQL Schema via Developer Portal [2].

[1] 

<img width="1027" alt="Screenshot 2021-11-29 at 10 39 19 AM" src="https://user-images.githubusercontent.com/5195851/143812224-6fba7ae8-45c8-47f7-9b06-9a0fbf8277b1.png">

[2] 

<img width="1390" alt="api-overview" src="https://user-images.githubusercontent.com/5195851/143812238-a28aa74a-8518-4218-9bf7-62201a13ce8a.png">

### Affected Product Version:
4.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
