### ISSUE TITLE
JDK 17 support

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#12084]
### Describe your problem(s)
APIM 4.1.0 GA should officially support JDK 17. 

### How will you implement it
Add JDK 17 as a new version in the JDK dimension in the TestGrid.  

#### Update
JDK 17 support should be available in APIM 4.2.0 as APIM 4.1.0 does not support JDK 17.

**Comment by dinusha92** [comment]
Hi guys, has this been tested?
