### ISSUE TITLE
Heap keeps continuously growing with tenant loading and Unloading due to Unnamed pool threads.

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-apim#12088]
### Description:

The heap memory keeps continuously growing with tenant loading and Unloading due to
### Steps to reproduce:

1.  Under the deployment.toml file of APIM 3.2.0 set less tenant idle timeout to replicate the issue.
 `[tenant_mgt]`
`tenant_idle_timeout='2'`
2.  Start the server.
3.  Create a few tenants.
4.  Publish and Subscribe APIs for each tenant.
5.  Capture a heap dump.
6.  Wait till the tenants are unloaded.
7.  Invoke the APIs to load the tenants again.
8.  Repeat steps 6 and 7 several times.
9. Capture a heap dump again.
10. You will observe that the heap keeps growing with the threads in the format of "pool-xxxx-thread-x

### Affected Product Version:

APIM 3.2.0

**Comment by HiranyaKavishani** [comment]
Close the issue with public fix https://github.com/wso2/carbon-apimgt/commit/68f4864f9c031a04c21fef1c6663e18c02c77461
