### ISSUE TITLE
IdP field "Identity Provider's Issuer Name" not correctly used

### ISSUE THREAD

**Issue by mmmAlthaf** [wso2/product-apim#12093]
### Description:
The issue occurs when we include the issuer URL in the Identity Provider's Issuer Name field when creating the IDP with a unique name given in the Identity Provider Name. But when we include the issuer URL in the Identity Provider Name, it works as expected.

### Steps to reproduce:

Basic Information:

Identity Provider Name: IDPTestName
Identity Provider's Issuer Name: https://localhost:9444/oauth2/token

The following error is thrown while trying to get the access token with the response as

{"error_description":"Internal Server Error.","error":"server_error"}

`[2021-11-17 18:24:23,728] ERROR - RoleBasedScopesIssuer No Registered IDP found for the JWT with issuer name : https://localhost:9444/oauth2/token [2021-11-17 18:24:23,729] ERROR - OAuth2Service Error occurred while issuing the access token for Client ID : N9WyUJgEBGIqI0Na9BoOjrj8X1Aa, User ID null, Scope : [] and Grant Type : urn:ietf:params:oauth:grant-type:jwt-bearer java.lang.NullPointerException: null at org.wso2.is.key.manager.core.tokenmgt.issuers.RoleBasedScopesIssuer.configureForJWTGrant(RoleBasedScopesIssuer.java:658) ~[wso2is.key.manager.core_1.0.16.6.jar:?] at org.wso2.is.key.manager.core.tokenmgt.issuers.RoleBasedScopesIssuer.getScopes(RoleBasedScopesIssuer.java:395) ~[wso2is.key.manager.core_1.0.16.6.jar:?] at org.wso2.is.key.manager.core.tokenmgt.issuers.RoleBasedScopesIssuer.validateScope(RoleBasedScopesIssuer.java:127) ~[wso2is.key.manager.core_1.0.16.6.jar:?] at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.validateScope(AbstractAuthorizationGrantHandler.java:263) ~[org.wso2.carbon.identity.oauth_6.4.2.40.jar:?] at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:281) ~[org.wso2.carbon.identity.oauth_6.4.2.40.jar:?] at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:254) [org.wso2.carbon.identity.oauth_6.4.2.40.jar:?] at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:319) [classes/:?] at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:94) [classes/:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]`

### Affected Product Version:
Product: APIM 3.2.0

**Comment by HiranyaKavishani** [comment]
Closing the issue as per above public commit
