### ISSUE TITLE
Set the defaultProp's value of URLs in TryoutController component 

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12102]
Without passing null you can also set the defaultProp's value of URLs in TryoutController component and leave it empty here.
```js
TryOutController.defaultProps = {
  URLs: null,
};
```

_Originally posted by @chanaka3d in https://github.com/wso2/apim-apps/pull/100#discussion_r754840547_

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity.
