### ISSUE TITLE
Content-Type wrongly set when having an API as SOAP Service with a SOAP endpoint.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#12104]
### Description:
The default optimization for a SOAP backend is set as SWA which seems not correct. Also, For the SWA, content-type is set to text/xml but this need to be something similar to below.

`Content-Type: Multipart/Related; boundary=MIMEBoundary_f09b46266c3d32b8b1a4f73185490293926d9ba527af4628; type=”text/xml”; start="<0.e09b46266c3d32b8b1a4f73185490293926d9ba527af4628@apache.org>"`

### Steps to reproduce:

- Create a SOAP API
- The default endpoint type has been set to SWA. (Issue 01)
- When calling the API, it is successful.
- But here the content-type is text/xml (Issue 02)
`"Content-Type: text/xml[\r][\n]"`

So the issues in this scenario is as below.
1. Incorrect Content-Type when SWA is selected.
2. Message content optimisation shouldn't be selected as SWA by default, this should be "Leave-As-Is"

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/apim-apps/pull/114
