### ISSUE TITLE
[APIM. 3.2]API product creation error when the API has parameters at path level

### ISSUE THREAD

**Issue by shankeerthan-kasilingam** [wso2/product-apim#12110]
### Description:
API product creation error when the API has parameters at path level.[1]

### Steps to reproduce:

- Create an API and modify it swagger file to have parameters at the path level

- Go to create API product 

- Select the previously created API and Click Add All

- There will be a resource which don’t exist in the API

- Click “Create and Publish”

### Affected Product Version:

APIM 3.2

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Assignees:

[1]: https://swagger.io/docs/specification/describing-parameters/

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
