### ISSUE TITLE
Where to put language files ? 

### ISSUE THREAD

**Issue by ftravaglia** [wso2/product-apim#1211]
Hello,

I made a french translation of the API manage store.

I would like to make the community benefit from this translation by integrating it into the deliverable of the api manager. However, after retrieving several GIT repositories I can not find where to drop those files (locale_fr.json and i18nResources_fr.json ).

Could you tell me in which GIT repository and in which directory I can push these files?

Thank you.

Regards,

Fabien T

I want

**Comment by praminda** [comment]
Hi Fabien,

Language files are picked up from carbon-apimgt repository. Please check following path in [carbon-apimgt](https://github.com/wso2/carbon-apimgt) repository

> https://github.com/wso2/carbon-apimgt/tree/master/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/conf/locales/jaggery

**Comment by ftravaglia** [comment]
Hi, 

Thanks for this informations. I pull request quickly .
