### ISSUE TITLE
Endpoint security is not working as expected for migrated APIs in APIM-3.2.0

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#12114]
### Description:
When migrating APIs from APIM-2.6.0 to APIM-3.2.0 with endpoint security enabled, it is not working as expected in APIM-3.2.0 after enabling the secure-vault feature to encrypt the endpoint passwords[1].

### Steps to reproduce:
- Enable endpoint security for APIM-2.6.0.
- Migrate from APIM-2.6.0 to APIM-3.2.0.
- Enable the secure-vault feature to encrypt the endpoint passwords[1].
- When invoking the APIs, the respective 'Authorization' header value will be invalid.

### Affected Product Version:
APIM-3.2.0.102

---
#### References:
[1] - https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords/#encrypting-secured-endpoint-passwords

**Comment by vithu30** [comment]
Public fix is N/A
