### ISSUE TITLE
Artifact retrieval is not working in APIM 4.0.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#12126]
### Description:
Artifact retrieval from the Control Plane node is not working if the gateway started first and then started the Control Plane node.

### Steps to reproduce:

- Configure a distributed deployment by using the API Manager 4.0.0 version. (Control Plane, Gateway-Worker)
- Start the Control Plane first and then the gateway.
- Publish an API.
- Stop all the nodes.
- Start the Gateway node first.
- After completing the gateway startup, start the Control Plane node.
- Try to invoke the API and be able to see the 404 response.
`{"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}`

### Affected Product Version:
4.0.0

**Comment by nalakas** [comment]
this issue ocures(time to time) even in the APIM 4.0.0 fresh pack.
