### ISSUE TITLE
Add support for taxonomy with multi-level categories for APIs

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-apim#12134]
### Describe your problem(s)
At the moment, APIM only supports one level of categories. But in most of the practical use cases, multiple levels of categories are needed. Hence this feature will be useful for such users. 

### Describe your solution
Add support for more than one level of categorization. 2 or 3 levels would be sufficient. 

### How will you implement it
Improve the existing categorization support.

**Comment by Krishanx92** [comment]
We are closing this as this feature is no longer required.
