### ISSUE TITLE
API products basic secured endpoints credentials are getting replaced in Migrated APIs

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#12136]
### Description:
When creating the API products, the endpoint basic security credentials are replaced in the API product artifact and due to that the invocation is getting unsuccessful

`                    <property name="Authorization" expression="fn:concat('Basic ', '$endpointsecurity.base64EncodedPassword')" scope="transport"/>`

 
This issue is only occurring with the migrated APIs. Also in these migrated APIs the Endpoint Secured registry property has to be set as **True**. 
### Steps to reproduce:
Create an API. 
Set the Endpoint Secured registry property in API to True.
Create a new API product using the changed API.
Invoke the API product.

### Affected Product Version:
v3.2.0

**Comment by chashikajw** [comment]
Applicable only for migrated APIs
