### ISSUE TITLE
Internal/publisher role users cannot created API products.

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12141]
### Description:
Logged in as a user with Internal/publisher role

![image](https://user-images.githubusercontent.com/12208083/146343332-e742c968-52b6-41ad-a5ce-279caf90acfa.png)

**Comment by chamilaadhi** [comment]
Works in the latest 4.3.0 pack
<img width="1728" alt="Screenshot 2024-03-05 at 10 50 09 AM" src="https://github.com/wso2/product-apim/assets/4861150/d6169393-8c17-49c8-b20f-40edfb306fad">
