### ISSUE TITLE
Support for SOAP WSDL Extensibility Elements

### ISSUE THREAD

**Issue by theyinyanguy** [wso2/product-apim#12149]
### Description:
I was trying to import a SOAP API as pass through and I noticed that the WSDL file failed validation. The only error message displayed in the Publisher portal is "WSDL content validation failed" and there was no additional information provided(See the screenshot). I tried previewing the API calls using the browser developer tools and noticed that the WSDL failed due to "WSDL extensibility element not supported" (See the screenshot attached). A prospect who has worked with the earlier version confirmed that it was supported with earlier version of the API Manager(I think it was version APIM 3.2 or 2.X)
![Uploading Screen Shot 2021-12-20 at 15.46.11.png…]

![Screen Shot 2021-12-20 at 15 46 11](https://user-images.githubusercontent.com/12360159/146721349-71153de4-b54d-48cc-a260-203d5acf8b5b.png)
### Steps to reproduce:
Below are the steps used
* On the API tab in WSO2 APIM Publisher portal, click on Create a new API
* Import a WSDL
* Browse for the WSDL containing the WSDL extensibility elements
 sample WSDL file can be provided on request.

### Affected Product Version:
WSO2 API Manager 4.0

### Environment details (with versions):
- OS: Mac/Windows
- Client: NA
- Env (Docker/K8s): NA

---
#### Suggested Labels:
![Screen Shot 2021-12-20 at 10 16 32](https://user-images.githubusercontent.com/12360159/146717776-7ab314ff-9e27-4f16-ad3d-e4a123f9083d.png)

#### Suggested Assignees:

Thanks,
Puneet (puneet@wso2.com)

**Comment by paulfwhite** [comment]
Here is a cut down sample which reproduces the problem.  At this stage the 4.0.0 demo is on hold.  
Let me know if we can help.
Paul

[play1.wsdl.txt](https://github.com/wso2/product-apim/files/7909546/play1.wsdl.txt)

**Comment by hisanhunais** [comment]
The fix has been done using the following PRs.
- https://github.com/wso2/carbon-apimgt/pull/10686
- https://github.com/wso2/carbon-apimgt/pull/10732
- https://github.com/wso2/carbon-apimgt/pull/11145
- https://github.com/wso2/carbon-apimgt/pull/11360
