### ISSUE TITLE
Reimporting Complex Graphql API Definition File Corrupts the API

### ISSUE THREAD

**Issue by Abshan** [wso2/product-apim#12144]
### Description:
While trying to re-upload the API schema file, all API operations get overruled, and the API is no longer operational. After importing the Graphql API, all the operations are listed as expected. The operations get overruled after reimporting the Graphql schema definition, and API is not usable afterwards.

This issue is only seen for complex Graphql schema definitions, and no error gets thrown in the console. I tested the same scenario with smaller Graphql files, and they are working as expected. 

### Steps to reproduce:

1. Import GraphQL API
2. Check operations are available
3. Go to Schema Definition
4. Import Definition
5. Use the same Graphql definition file
6. You will notice Operations were changed to /*

### Affected Product Version:

WSO2AM 3.2.0

**Comment by HiranyaKavishani** [comment]
Issue is not reproduced in master
