### ISSUE TITLE
The Publisher UI always show SOAP Optimization as “SWA” regardless of the Optimization was configured for the endpoint

### ISSUE THREAD

**Issue by shankeerthan-kasilingam** [wso2/product-apim#12154]
### Description:
The Publisher UI always show SOAP Optimization as “SWA” regardless of the Optimization was configured for the endpoint

### Steps to reproduce:

- Create an API with SOAP endpoint

- Configure the Optimization for the endpoint as “leave-as-is” and Save

- Save and Publish the API

- Click Edit API again

- Go to Endpoint configuration and check the Optimization

- The Optimization will be “SWA”

### Affected Product Version:

APIM 2.6
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
Cannot reproduce in latest master
