### ISSUE TITLE
Failing the API publishing flow when the swagger collection is not working

### ISSUE THREAD

**Issue by ShehanRavindu** [wso2/product-apim#12168]
### Description:
The customer was trying to create an API using a swagger file. But when deploying the API, the Customer faced an error. Previously the customer had used APIM 2.6 and the same swagger. Then he hadn't faced any issues. But when the customer used APIM 4.0.0, the errors were in the log. I also tried the attached swagger file and faced the same error.

We have given a fix as a solution for this. It is adding response descriptions to the swagger, this error gets resolved and every execution flow is working fine.

In the latest swagger spec, it is mentioned that this response description is mandatory and we need to provide that [1]. But in the previous swagger specs, it is not a mandatory field [2]. But even though the swagger definition is 3.0.0, this response description validation is happening which is intended to happen for 3.0.3. And that validation is not happening when creating the swagger definition.

**The problem which customer faces currently:**
The customer could not see any breaking in API publisher flow when they tried to publish API with a previous questionable swagger. The error showed only in the log.
 
So The customer asks to fail API publishing flow in such scenarios because the API publisher is unable to know whether API publishing flow is successful or fails.

The product team has identified an issue and raised it in wagger-parser [3]. The fix is released from the swagger side [4].

[1] https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#responseObject
[2] https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#response-object
[3] https://github.com/swagger-api/swagger-parser/issues/1631
[4] https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.29

### Steps to reproduce:

1. Start an APIM 4.0.0 server
2. Try to create an API using swagger(Mentioned in the support ticket).
3. Deploy API.
4. Check the wso2carbon.log file.

### Affected Product Version:
APIM 4.0.0

**Comment by hisanhunais** [comment]
The public fix for this issue will be done using the swagger-parser dependency upgrade

**Comment by hisanhunais** [comment]
The public fix has been done by upgrading the swagger-parser which was tracked using https://github.com/wso2/product-apim/issues/12258. 
Hence closing this issue.
