### ISSUE TITLE
Back port the DefaultVersion API fix to the APIM 3.2.0

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#12161]
### Describe your problem(s)
We are getting unexpected responses when invoking the default version API which exposes the SOAP service [1].
The issue is soap envelop and the body tags are duplicated in the response as mentioned below:

```
<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="[http://schemas.xmlsoap.org/soap/envelope/]"> 
  <soapenv:Body>
     <soapenv:Envelope>
          <soapenv:Body> 
               <data></data>
          </soapenv:Body> 
      </soapenv:Envelope>
   </soapenv:Body>
</soapenv:Envelope>
```

### Describe your solution
Backport the improvement introduced to the defaultVersion API flow in the APIM 4.0.0 [2] to the APIM 3.2.0

[1]: https://apim.docs.wso2.com/en/3.2.0/learn/tutorials/expose-a-soap-service-as-a-rest-api/#expose-a-soap-service-as-a-rest-api  
[2]: https://github.com/wso2/carbon-apimgt/pull/9965

**Comment by YasasRangika** [comment]
Since this is already fixed in the latest public branch, closing the issue.
