### ISSUE TITLE
[3.2.0] Cannot invoke GraphQL Subscriptions using OAuth tokens

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12165]
### Describe your problem(s)
When there are migrated applications with OAuth key type, even though the handshake is successful, the GraphQL subscriptions WebSocket frames cannot be invoked. Currently, only the JWT applications can invoke GraphQL subscriptions properly.

### Describe your solution
Handle the OAuth tokens separately for GraphQL WS frames.

**Comment by HiranyaKavishani** [comment]
Duplicate issue https://github.com/wso2/product-apim/issues/12197
