### ISSUE TITLE
After deployng APIM 3.2.0 patch level 113, the "api.ut.api" property returns a null value

### ISSUE THREAD

**Issue by vikumkbv** [wso2/product-apim#12178]
### Description:
After updating to APIM 3.2.0.113  then  with a non-secured API resources got null for the message context properties such that below.
## api.ut.apiPublisher= = null, api.ut.api= = null, api.ut.version= = null

Also able to see this error message in carbon console
`[2021-12-31 12:48:43,207] ERROR - APIMgtUsageDataBridgeDataPublisher RequestResponse event dropped due to unavailability of mandatory data: [API context, API name, API hostname] in event: Application consumer key: *one, Application name: None, Application ID: 0, Application owner: None, API name: null, API version: 1.0.0, API context: null, Username: anonymous, API resource path: /1.0.0/healthcheck, API resource template: /healthcheck, API method: GET, API creator: admin@carbon.super, API creator tenant domain: carbon.super, API tier: Unauthenticated, Username: anonymous, User tenant domain: carbon.super, Host name: null, User IP: 172.16.16.122, User Agent :Zabbix, Is throttled: false, Request timestamp: 1640954923180, Response time: 27, Service time: 6, Backend time: 21, Is response cache hit: false, Response size: 0, Protocol: https--1, Response code: 200, Destination: https://ei.pre.mcp.es/water/meters, Security latency: 0, Throttling latency: 0, Mediation latency: 2, Response mediation latency: 0, Backend latency: 21, Other latency: 0, Gateway type: SYNAPSE, Label: Synapse
`

We were able to reproduce this issue with APIM 3.2.0.113 when we use non-secured API resources. But not with the secured resource.

However, when checking the same use-case with APIM 3.2 GA release pack, the issue seems not there and both secured and unsecured resources, the following properties correctly printing the values in the carbon logs.

api.ut.apiPublisher , api.ut.api , api.ut.version

## For non-secured API resources:

    `[2022-01-02 16:39:51,452]  INFO - LogMediator
    Unknown macro: {api}`

    `api.ut.apiPublisher= = null, api.ut.api= = null, api.ut.version= = null`

 ## For secured API resources:

    `[2022-01-02 16:02:13,622]  INFO - LogMediator
    Unknown macro: {api}`

    `api.ut.apiPublisher= = admin, api.ut.api= = PizzaShackAPI, api.ut.version= = 1.0.0`

 
## With APIM 3.2 GA pack:
For both unsecured and secured resources, we could see the above properties correctly logging with the values. So this scenario works fine in the GA pack.
 
Hence it seems this has been broken with an Update level.

### Steps to reproduce:

- update apim to wso2am-3.2.0+1611933891844" wum level and with wso2update tool to "wso2am-3.2.0+113"
- Deployed a global sequence (WSO2AM-Ext-In.xml) with the provided code.

`<sequence name="WSO2AM-Ext-In" xmlns="http://ws.apache.org/ns/synapse">
   <log level="custom">
      <property name="api.ut.apiPublisher=" expression="$ctx:api.ut.apiPublisher" />           
      <property name="api.ut.api="          expression="$ctx:api.ut.api" />           
      <property name="api.ut.version="      expression="$ctx:api.ut.version" />           
   </log>
</sequence>`

- Then invoke it as non-secured API

### Affected Product Version:
APIM 3.2.0.113

**Comment by Krishanx92** [comment]
This is fixed in latest, hence closing
