### ISSUE TITLE
APIM server allow to create APIs with white spaces in API name.

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-apim#12174]
### Description:
Generally, the API creation with API names that contain white spaces was blocked. But when trying to create an API via the Restful endpoints of APIM-2.6.0(update level - 61), the white spaces are allowed in the API name.

### Steps to reproduce:
Create an API using the Restful Endpoint of the publisher with the attached JSON([data.json.zip](https://github.com/wso2/product-apim/files/7801105/data.json.zip)) file.

### Affected Product Version:
APIM-2.6.0(update level - 61)

### Environment details (with versions):
N/A

**Comment by chashikajw** [comment]
In choreo, it supports the APIs with whitespaces.
