### ISSUE TITLE
Token Revocation from IS KM is not reflecting for the token validation

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#12182]
### Description:

token revocation not reflecting immediately after the token is being revoked

### Steps to reproduce:

Reproducing Steps

- Get the latest IS KM 5.5.0 pack (wum update and then latest U2)

- APIM 2.2.0 configure ISKM as a key manager

- Disable Gateway Token Cache (validation call direct hit the key manager)

- Obtain a token using client credentials grant type

`curl -k -d "grant_type=client_credentials" -H "Authorization: Basic djZmTkZLbEVsa3lRX2YwbzRoV1NWXzJmWF9JYTpsRk5MUVRTeWpsZW9kZUlKMnlXQXZPTFdwWU1h" -H "Content-Type: application/x-www-form-urlencoded" https://localhost:9444/oauth2/token -v`

- Invoke an API

`curl -k -X GET "https://localhost:8243/pizzashack/1.0.0/menu" -H "accept: application/json" -H "Authorization: Bearer dc33a972-1b0a-3586-9145-e570009dad65"`

- Revoke the Token

`curl -k -v -d "token=dc33a972-1b0a-3586-9145-e570009dad65" -H "Authorization: Basic djZmTkZLbEVsa3lRX2YwbzRoV1NWXzJmWF9JYTpsRk5MUVRTeWpsZW9kZUlKMnlXQXZPTFdwWU1h" -H "Content-Type: application/x-www-form-urlencoded" https://localhost:9444/oauth2/revoke`

- Invoke the API again

`curl -k -X GET "https://localhost:8243/pizzashack/1.0.0/menu" -H "accept: application/json" -H "Authorization: Bearer dc33a972-1b0a-3586-9145-e570009dad65"`

- Returned a successful response

**The above token is valid for 5min after the revocation**

**Comment by HiranyaKavishani** [comment]
Issue is not reproducible in  public branch
