### ISSUE TITLE
Generated token are not visible in the devportal

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12190]
### Description:
When we try to generate a token for an Application from devportal, even though we don't select the token exchange grant type, a popup is displayed as follows. Because of this generated token is not displayed. The token call is sent in the background properly.

![Screenshot 2022-01-07 at 1 06 26 PM](https://user-images.githubusercontent.com/47380453/148512089-5f9f2692-6572-4e67-890f-98020d0c4e07.png)

### Steps to reproduce:
1. Create an Application from the dev portal.
2. Generate keys
3. Click Generate token button and proceed with the wizard

### Affected Product Version:
APIM 4.1.0-m3

**Comment by HiranyaKavishani** [comment]
This happened due to commit https://github.com/wso2/apim-apps/commit/dfb573d44a464c16c26b465000fcf5734ba74be9

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
