### ISSUE TITLE
[3.2.0] - The 'MANAGE APP' link is not working

### ISSUE THREAD

**Issue by dev-skd** [wso2/product-apim#12199]
### Description:
The '`MANAGE APP`' link which is residing in the API subscription page (devportal) is not working. When clicking on the '`MANAGE APP`' link is not redirecting the user to any of the devportal pages. 

### Steps to reproduce:

- Log in to the publisher portal and deploy a sample API.
- Log in to the developer portal and subscribe to the particular API.
- Select the relevant API in the devportal and navigate to the API subscription page.
- Then click on the MANAGE APP link in one of the subscriptions under the Subscriptions section.

### Affected Product Version:
3.2.0

**Comment by chamilaadhi** [comment]
Issue is not in the master branch
