### ISSUE TITLE
Error occurred while updating application when using Auth0 as KM

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/product-apim#12198]
### Description:
This is an error that occurred while working with Auth0 as KM with APIM 4.0.0. After configuring the Auth0 as KM for APIM 4.0.0 according to the documentation[1] the Generate Access Token button gets disabled if we generate the application keys with multiple grant types enabled. Also if reload the page or check the Auth0 tab for an existing application the previously checked grant types and other attribute information are missing in the UI.

### Steps to reproduce:

- Configure the Auth0 server as Key Manager according to the official document[1].
- Log into the devportal and create a new application.
- Select multiple grant types to generate the keys.
- Select authorization code grant type and add the callback URL.
- Generate the keys.
- Go to the Application page again and open the same application.
- Navigate to Production keys and open the Auth0 key Manager tab. 
- All grant types are unchecked and the callback URL added was missing.
- The Generate Access Token button is also disabled.

### Affected Product Version:
APIM-4.0.0

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-auth0-connector/

**Comment by BLasan** [comment]
APIM-3.2.0 issue will be tracked via this issue
