### ISSUE TITLE
Support analytics event publishing for graphql frame authentication success/failure

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#12197]
### Describe your problem(s)
Currently as similar to websocket analytics we only publish authentication  success/failure events for connection establishment only. Since we authenticate and authorize graphql ws frames, we need publish event for those as well.

**Comment by wasuradananjith** [comment]
I invoked the API as shown in the below network tab screenshot.
![image](https://user-images.githubusercontent.com/25246848/157602169-41b6091f-89be-419d-a927-ed325041af5b.png)

The Choreo analytics showed the below statisitics. Not clear how the statistics are getting generated.
![image](https://user-images.githubusercontent.com/25246848/157602327-c23cd43b-f6ea-4eaa-9909-1a1fa78ddd25.png)
