### ISSUE TITLE
[3.2.0] - J2 Mapping is not available for ServerInitializers in carbon.xml

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/product-apim#12204]
Description:
The following ServerInitializers property in carbon.xml file is not templated a with J2 mappings in the APIM 3.2.0. 
    <ServerInitializers>
        
    </ServerInitializers>
Therefore J2 Mapping needs to be added/templated for the above mentioned (<ServerInitializers> <Initializer>) property in the carbon.xml.

Affected Product Version:
APIM 3.2.0

**Comment by chashikajw** [comment]
Closing this since this is fixed.
