### ISSUE TITLE
"Context already exists" but it does not exist

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/product-apim#12203]
### Description:

When going to create an API with the context /scrm,  get "/scrm context already exists" warning but the exact context is not already there. But another API already have /int/scrm context.

### Steps to reproduce:

1. create and publish an API with the /int/scrm context.
2. Try to create another API with the /scrm context.
3. Get the "/scrm context already exists" warning and not be able to proceed.

### Affected Product Version:
API Manager 3.2.0.112

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This issue fixed with latest hence closing
