### ISSUE TITLE
WSO2 Bad_certificate in starting of API manager

### ISSUE THREAD

**Issue by dflores-compasso** [wso2/product-apim#12209]
### Description:

Good afternoon, I use api manager 3.2 in my company and I realized that the wso2carbon certificate at JKS is about to expire on the 25th of January. I tried to generate a new certificate following the documentation but I get the following error:
`
ERROR - BinaryDataReceiver Error while reading from the socket. javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate`

Can you help me?

Documents used:
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores/

https://docs.wso2.com/display/DS200/Troubleshooting+Guide

### Affected Product Version:
APIM-3.2

**Comment by nandika** [comment]
reported for the old version. Issue is fixed for 4.4
