### ISSUE TITLE
[4.1.0-M2][UI] Solace -  Introduce SOLACE-PUBSUB as API Type

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#12212]
### Describe your problem(s)
The current Solace AsyncAPIs Type is **WEBSUB**. 

![image-20220111-150931](https://user-images.githubusercontent.com/42435576/149872048-01e5db96-c8c9-4183-9978-1af534c03278.png)
![image-20220111-150607](https://user-images.githubusercontent.com/42435576/149872052-d7c96863-e1ac-4120-a56a-efa12abf126f.png)

But Solace APIs need to be recognised immediately as separate APIs.

### Describe your solution

- Introduce a Solace specific API type like **SOLACE PUBSUB** or just **SOLACE** 
- 
- Render Solace specific API type in APIs views (List and Tiles)

### How will you implement it

---

**Comment by Sarangan0219** [comment]
We are not going to fix it. Instead we will be displaying a chip as Solace in the Solace API card view.
https://github.com/wso2/product-apim/issues/12407
