### ISSUE TITLE
[4.1.0-M2][UI]Solace- WSO2 Developer Portal WAIT indicator is missing in Unsubscribe operation. 

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#12211]
### Description:
Clicking Unsubscribing of an AsyncAPI in various UI screens are does not render a WAIT indicator (spinning wheel, …) although it takes typically a significant amount of time (>5 seconds) until the action (unsubscribing) is finished. 

Clicking on SUBSCRIBE in the Applications screen does not render a WAIT indicator.

![image-20220113-095316](https://user-images.githubusercontent.com/42435576/149871625-e66118e4-6fc2-4776-b464-e6c6ede323d0.png)
![image-20220111-152412](https://user-images.githubusercontent.com/42435576/149871628-fdb31a4d-d953-4125-a50f-53b19202179c.png)

### Steps to reproduce:
1. Configure Solace environment
2. Create Solace Async API and deploy.
3.  Create Solace Subscription 
4. Unsubscribe from Application 

### Affected Product Version:
APIM 4.1.0 - Milestone 2

### Suggestion
Add WAIT indicators on appropriate screens/actions in Devportal UI.

**Comment by Sarangan0219** [comment]
We are not going to fix this as this issue is from Solace side.
