### ISSUE TITLE
"Context already exists" but it does not exist

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#12218]
### Description:
Create an API with the context /foo and get the "/foo context already exists" warning but the exact context is not already there. But another API already has /int/foo context.

Reproducing steps:

create and publish an API with the /int/foo context.
Try to create another API with the /foo context.
We also get the "/foo context already exists" warning as follows.

**Comment by Krishanx92** [comment]
This is not reproduce in latest pack
