### ISSUE TITLE
[3.0.0] - Unable to upload wsdl file when creating api

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#12220]
### Description:
Unable to create an api with a provided wsdl file.

Browser = Firefox
Product version = 3.0.
<img width="740" alt="Screenshot 2022-01-19 at 13 25 11" src="https://user-images.githubusercontent.com/3424539/150091843-fb7dae3e-4a2e-49f1-be11-f74c12728a35.png">
0

**Comment by paulfwhite** [comment]
I was able to fix this message by changing the file extension to .WSDL
Then ran into a different problem. See #12149
