### ISSUE TITLE
[APIM-3.2.0]-Publisher Portal Access Issues with the assigned user roles

### ISSUE THREAD

**Issue by nuwankng** [wso2/product-apim#12226]
[](url)**Description:**
When user is assigned with Internal/analytics, Internal/subscriber and Internal/everyone role, the publisher portal get loaded partially and freeze on the same screen.

**Steps to reproduce:**
Create a user from the management console of APIM
Assign roles Internal/analytics, Internal/subscriber and Internal/everyone role to the created user.
Try to access the publisher portal

**Affected Product Version:**
wso2am-3.2.0

<img width="1433" alt="publisherportal" src="https://user-images.githubusercontent.com/16064951/150472723-3a011282-61c8-403d-a2ba-bba592c7fd1f.png">

**Comment by chanaka3d** [comment]
Public fix is merged, hence we can close this issue.
