### ISSUE TITLE
Devportal home page is getting flickered once - API Manager 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#12233]
### Description:
When loading the dev portal, the UI will invoke the **logout** service call, and hence, there can be a flickering issue when loading the dev portal.

### Steps to reproduce:

- Start an API Manager pack.
- Load the dev portal and able to see the URL is getting redirected to the **logout** service call and again back to the dev portal home page.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/18566908/150728212-31cda49a-9052-41a9-a8af-06d7fac09ca4.gif)

### Affected Product Version:
3.2.0

**Comment by chanaka3d** [comment]
This issue is fixed in the main branch
