### ISSUE TITLE
Accumulation of backend payloads leading to OOM when the connection stale

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-apim#12237]
### Description:
We are seeing the backend payloads being accumulated when the backend connection is being stale.

### Affected Product Version:
APIM 3.1.0

**Comment by revkov** [comment]
+ since 2.6.0

**Comment by hisanhunais** [comment]
The issue has been fixed in master branch with the following PRs.
- https://github.com/wso2/wso2-synapse/pull/1678
- https://github.com/wso2/wso2-synapse/pull/1767
