### ISSUE TITLE
NullPointerException with Publisher API

### ISSUE THREAD

**Issue by ramiroll** [wso2/product-apim#12235]
### Describe your problem(s)
In the publisher rest api with this resource [1] we are getting an error message in the next scenario.
We tested locally and generally the endpoint works fine, but when we set the parameter **"expand=true"** we receive this response:
https://127.0.0.1:9443/api/am/publisher/v2/apis/?expand=true
_{
"code": 500,
"message": "Internal server error",
"description": "The server encountered an internal error. Please contact administrator.",
"moreInfo": "",
"error": []
}_
In the server logs we can see this exception :
[2022-01-20 18:16:28,080] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
 
This was tested in the last update level (64) of the api manager 4.0.0
We've confirmed that expand parameter is not supported in this version, anyway it not seems to be a correct behavior to return an exception message for this operation
 
Thanks Ramiro
[2] https://apim.docs.wso2.com/en/latest/reference/product-apis/publisher-apis/publisher-v2/publisher-v2/#operation/getAllAPIs
### Describe your solution
Ignore the parameter

**Comment by msm1992** [comment]
Fixed in master with following PRs.

[1]. https://github.com/wso2/carbon-apimgt/pull/11019
[2]. https://github.com/wso2/product-apim/pull/12320
