### ISSUE TITLE
Benchmark tests are failing after synapse and mediation bump

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12236]
### Description:
After the PR [1], benchmark tests are failing.

[1] - https://github.com/wso2/product-apim/pull/12217
### Affected Product Version:
latest

**Comment by rmsamitha** [comment]
The errors occurring are as below:

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createAnApplication[public void org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createAnApplication(java.lang.reflect.Method) throws java.lang.InterruptedException,java.io.IOException,org.json.simple.parser.ParseException,org.wso2.am.integration.test.utils.APIManagerIntegrationTestException](1)
[ERROR]   Run 1: BenchmarkTestCase.createAnApplication:240 » IO No such file or directory
[ERROR]   Run 2: BenchmarkTestCase.createAnApplication:240 » IO No such file or directory
[INFO]
[ERROR] org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createRestApi[public void org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createRestApi(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException,org.json.simple.parser.ParseException,org.wso2.am.integration.test.utils.APIManagerIntegrationTestException,org.wso2.am.integration.clients.publisher.api.ApiException](1)
[ERROR]   Run 1: BenchmarkTestCase.createRestApi:115 » IO No such file or directory
[ERROR]   Run 2: BenchmarkTestCase.createRestApi:115 » IO No such file or directory
[INFO]
[ERROR] org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createRevisionAndDeploy[public void org.wso2.am.integration.tests.benchmarktest.BenchmarkTestCase.createRevisionAndDeploy(java.lang.reflect.Method) throws java.lang.InterruptedException,java.io.IOException,org.json.simple.parser.ParseException,org.wso2.am.integration.test.utils.APIManagerIntegrationTestException,org.wso2.am.integration.clients.publisher.api.ApiException,org.json.JSONException](1)
[ERROR]   Run 1: BenchmarkTestCase.createRevisionAndDeploy:362 » IO No such file or directory
[ERROR]   Run 2: BenchmarkTestCase.createRevisionAndDeploy:362 » IO No such file or directory
....
...
