### ISSUE TITLE
Upgrade swagger-parser Dependency

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#12258]
### Description:
The root cause for issue [1] was identified as a bug of the `swagger-parser` and a new version [2] of swagger-parser has been released with the fix. But, when upgrading the swagger-parser using the orbit bundle [3] ,to the above mentioned released version, it is better to upgrade the `swagger-parser`, `swagger-parser-v2-converter` and `swagger-parser-v3` to keep all the artifacts in a consistent version. When doing this, the `swagger-core`, `swagger-models`, `jackson-annotations` dependencies also has to be upgraded for compatibility. 

This issue is created to track the dependency upgrades which is required to be done to upgrade the swagger-parser.

[1] https://github.com/wso2/product-apim/issues/12168
[2] https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.29
[3] https://github.com/wso2/orbit/blob/master/swagger-parser/2.0.20.wso2v1/pom.xml

**Comment by dulithsenanayake** [comment]
https://github.com/wso2/orbit/pull/594
https://github.com/wso2/orbit/pull/593
https://github.com/wso2/wso2-synapse/pull/1905
https://github.com/wso2/carbon-mediation/pull/1597
https://github.com/wso2/carbon-apimgt/pull/11081
https://github.com/wso2/product-apim/pull/12491
