### ISSUE TITLE
Remove TENANT_DOMAIN column in AM_GATEWAY_ENVIRONMENT

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#12260]
### Describe your problem(s)

As per, https://github.com/wso2/carbon-apimgt/pull/10855 new ORGANIZATION column was added to AM_GATEWAY_ENVIRONMENT to use instead of TENANT_DOMAIN. TENANT_DOMAIN column needs to be removed.

**Comment by tharikaGitHub** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/11116
