### ISSUE TITLE
Unable to access the admin portal when changed admin-role name

### ISSUE THREAD

**Issue by dumindurox777** [wso2/product-apim#12266]
### Description:
After changing the default admin role to a custom role unable to log in to the admin portal using admin user. Seems to be a scope issue.

### Steps to reproduce:

- Download the API manager pack and add the below config to the toml file.
```
[super_admin]
username = "admin"
password = "admin"
admin_role= "wso2admin"
create_admin_account = true 
```
-  Then start the server and try to log in to the admin portal using the admin user credentials.

After adding the below role mapping to the tenant-conf.json file able to resolve the issue. But the tenant-conf.JSON file still has some role names with default admin role names. Not with the recently newly configured custom admin role. Due to that most convenient way is to transfer the config which is defined in the toml file to tenant-conf.json file role and scope mapping section
 
"RoleMappings" : {
"admin" : "wso2admin"
},

### Affected Product Version:

apim-4.0.0.66

**Comment by Krishanx92** [comment]
Closing since there was no active discussions happened for this in internally as well.
