### ISSUE TITLE
[3.2.0] Alignment issue when listing GraphQL APIs in the Publisher Portal

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12263]
### Description:
In the Publisher portal APIs listing, the delete button of the GraphQL API goes out of the button and partially visible shown below.

![image](https://user-images.githubusercontent.com/25246848/151485018-fb1c10af-642e-43b3-b3e2-de85daa5f209.png)

### Affected Product Version:
APIM 3.2.0 Latest WUM (1643039142116)

### Environment details (with versions):
- OS: Ubuntu 20.04.03 LTS
- Browser: Chrome, Firefox

**Comment by Krishanx92** [comment]
This is fixed in latest version.
