### ISSUE TITLE
Add the documentation for operation policy feature

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12276]
### Describe your problem(s)
Add the documentation for the operation policy feature and update the publisher rest API.

**Comment by ashera96** [comment]
Feature documentation related PRs:
- https://github.com/wso2/docs-apim/pull/5276

**Comment by 1akshitha** [comment]
Doc link : https://apim.docs.wso2.com/en/latest/design/api-policies/overview/
