### ISSUE TITLE
A new UI to apply operation policies at the resource level

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12274]
### Describe your problem(s)
A new UI is needed to apply operation policies at the resource level.

**Comment by ashera96** [comment]
Feature PRs that introduces a new UI to apply policies (both common policies and operation level policies) at the resource level are listed below:

- https://github.com/wso2/apim-apps/pull/147
- https://github.com/wso2/apim-apps/pull/176

**Comment by ashera96** [comment]
Refer to the screen recording attached herewith which outlines the operation policy management capabilities introduced by this feature.

https://user-images.githubusercontent.com/30475839/156586285-f73f0134-7ea2-4a59-975a-e34a3c7e04fe.mov
