### ISSUE TITLE
Shared operation policies UI for operation policy feature

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12273]
### Describe your problem(s)
Need to develop a new UI to manage shared operation policies.

**Comment by ashera96** [comment]
Feature PRs which include the `Common Policies` UI are listed below:

- https://github.com/wso2/apim-apps/pull/147

**Comment by ashera96** [comment]
Refer to the screen recording attached herewith which outlines the common policy management related UI/UX of this feature.

https://user-images.githubusercontent.com/30475839/156585893-a2afd2f6-d3f5-43d5-a220-05b7d0b81396.mov
