### ISSUE TITLE
Forward slash character "/" is not accepting in the value field at BlackList Policies Section

### ISSUE THREAD

**Issue by Ramiiyan** [wso2/product-apim#12289]
### Description:
Forward slash character "/" is not accepting in the value field at BlackList Policies Section.

![recreated_behavior](https://user-images.githubusercontent.com/36502262/151925094-654bbd98-4a71-4374-86f8-0a88957d85bf.png)

### Steps to reproduce:
1. Created a user with LDAP with subscriber role permission.
2. Created an application with LDAP user.
3. Went to Admin portal with Admin privilege.
4. Went Black List Policies and Select the Condition type as Application and provide the value as "MYLDAP/ldapU1:ldapUserApp". In here, MYLDAP is the secondary user store name, ldapU1 is the username, and ldapUserApp is the application name.
5. Invoked the Blacklist button and got the "Invalid Input" UI error.

**Comment by chashikajw** [comment]
Closing the issue since this is already fixed in the master
