### ISSUE TITLE
issue in mock implementation api definition

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#12284]
### Steps to reproduce:
1. create an api
2. go to endpoints tab and select mock endpoint. but Don't save mock implementation.
3. go to API definition and now it has x-mediation script extension even though we have not saved or given any mock implementation.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
