### ISSUE TITLE
Mock implementation script generation with swagger examples

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#12281]
### Steps to reproduce:
1. create API importing https://petstore.swagger.io/v2/swagger.json
2. go to mock implementation endpont.
3. There you will see auto generated scripts under resources.
4. Following error can be seen in logs,
```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2080)
```
### Investigations
When swagger has example responses, they will be included in the auto-generated mock scripts. 
It might be related to this issue. -> https://github.com/swagger-api/swagger-inflector/issues/300

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
