### ISSUE TITLE
Unable get the X-JWT-Assertion header to the WS back-end (on-open) for WS APIs

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#12286]
### Description:
Unable get the X-JWT-Assertion header to the WS back-end (on-open) for WS APIs

### Affected Product Version:
APIM 3.2.0

**Comment by vidurananayakkara** [comment]
The issue is resolved. However, this can be further improved by **NOT** mandating the below configuration:

```
[transport.ws.sender]
enable = true

[transport.ws.sender.parameters]
"ws.custom.header" = "websocket-custom-header"

[transport.wss.sender]
enable = true

[transport.wss.sender.parameters]
"ws.custom.header" = "websocket-custom-header"
```

Please do resolve / close this issue accordingly.
