### ISSUE TITLE
Corrupted log4j jars in APIM 3.2.0.124

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#12288]
### Description:
In U2 level 124, the log4j jar files inside <APIM_HOME>/lib directory is corrupted. Due to this a ClassNotFoundException will be thrown if AppDynamics is configured with APIM.

### Steps to reproduce:
Navigate to <APIM_HOME>/lib directory and check the sizes of log4j-api-2.17.1.jar, log4j-core-2.17.1.jar and log4j-jcl-2.17.1.jar files. It is only 459 bytes in size and cannot be extracted.

### Affected Product Version:
APIM 3.2.0

**Comment by chamilaadhi** [comment]
Seems this issue is resolved in the latest u2 update. I checked in 3.2.0.334 and no issue found
