### ISSUE TITLE
Cannot generate token from the application view

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#12291]
### Description:
Generating application keys and then generating a token in the application view gives the following error.

<img width="637" alt="Screenshot 2022-02-01 at 14 51 35" src="https://user-images.githubusercontent.com/15942605/151953585-b8d1c0ef-c061-4b10-9a09-c07b9b539625.png">

### Steps to reproduce:
1. Login to devportal with the admin credentials
2. Go to the application listing and create an application (or use the default)
3. Go to the OAuth tokens view and generate keys
4. Then try to generate a token by clicking on Generate Access Token

### Environment details (with versions):
- OS: MacOS Big Sur
- Client: Chrome
- Env (Docker/K8s): Local

**Comment by HiranyaKavishani** [comment]
This has been already fixed. [1]

[1] https://github.com/wso2/apim-apps/pull/132/files
