### ISSUE TITLE
Inconsistent behavior in the developer portal after disabling the gateway URL visibility at Publisher

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#12300]
### Description:

After disabling publisher's gateway URL visibility, it says `No endpoints yet`, but the try button is enabled. 

Therefore, once click it, for Rest APIs, the keys are generated with a subscription and is navigated to tryout console. Servers dropdown shows invalid url as follows. 

<img width="1470" alt="Screen Shot 2022-02-03 at 11 19 22 AM" src="https://user-images.githubusercontent.com/29066805/152289223-ff19e1c4-f288-4d66-b7ba-4bfa17efb2f5.png">

for GraphQL APIs, it is redirected to a blank page.
<img width="1507" alt="Screen Shot 2022-02-03 at 11 40 23 AM" src="https://user-images.githubusercontent.com/29066805/152290581-9d0b27bd-c782-48b3-b5c4-2e5b4cef9ea0.png">

### Steps to reproduce:
1.Create REST & GraphQL API
2.Deploy a revision and making disable the gateway URL visibility for both APIs.
3.Go to Devportal and click TryOut buttons in both APIs.

### Affected Product Version:
APIM 4.1.0

### Environment details (with versions):
- OS: MAC OS
- Env (Docker/K8s): local setup

---

**Comment by CrowleyRajapakse** [comment]
The blank page in GraphQL is due to following improvement done recently : https://github.com/wso2/product-apim/issues/11750, will provide a fix to resolve that GraphQL API Try Out page not loading issue, so that it will be as consistent as the REST API behaviour with disabling gateway URL visibility option.
