### ISSUE TITLE
“createdTime” Is Returned Null When Using Publisher Rest API

### ISSUE THREAD

**Issue by Abshan** [wso2/product-apim#12308]
### Description:
When using the publisher Rest API to get API information, using the following Rest API call, the **createdTime** attribute is returned null, and **lastUpdatedTime** gets returned successfully.
`https://127.0.0.1:9443/api/am/publisher/v1/apis?expand=true`

### Steps to reproduce:
1. Deploy a sample API.
2. Use the Publisher API [1] to retrieve API details.
3. Use the **https://127.0.0.1:9443/api/am/publisher/v1/apis?expand=true** operation with the 'expand' attribute set to 'true'.
4. Check for the 'createdTime' attribute in the response.

[1] https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/APIs/paths/~1apis/get

### Affected Product Version:
WSO2AM-3.2.0.124

**Comment by wasuradananjith** [comment]
According to [1], the _expand_ in Publisher V2 GET APIs resource has been deprecated from APIM 4.0.0 onwards. Hence, no need for the master fix.

https://apim.docs.wso2.com/en/latest/reference/product-apis/publisher-apis/publisher-v2/publisher-v2/#operation/getAllAPIs
