### ISSUE TITLE
Unable to view created API in Safari 13.1.3 in Mac

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#12310]
### Description:
API can be created but when try to view the created API by navigating to ex: https://localhost:9443/publisher/apis/923f3cb4-9109-47ed-a314-3cbe82af1bda/overview following error is shown.

<img width="1680" alt="Screenshot 2022-02-07 at 11 28 57" src="https://user-images.githubusercontent.com/23296184/152732885-a3b6fabb-a4e8-4e1b-93f4-63a66d4abb01.png">

But in Chrome/Firefox same API can be viewed without issues.

### Steps to reproduce:

- Create API.
- Then Click the API to view.

### Affected Product Version:
APIM 4.1(Pre-Alpha)

### Environment details (with versions):
- OS: MacOS
- Client: Safari 13.1.3

**Comment by chanaka3d** [comment]
This issue can't reproduce in the 4.1.0 alpha
