### ISSUE TITLE
A not defined "http method + resource" in API returns 404 code (instead of 405)

### ISSUE THREAD

**Issue by ramiroll** [wso2/product-apim#12338]
On the api manager 2.6.0 when a resource is called with an http verb that is no defined in most cases the response is a 404 status not found, in the case of the patch verb a 405 status is returned what we understand is the correct response as we can see in this status definitions [1].

This was tested with the PizzaShack sample api. When we call the /menu resource with the Patch verb the response is this one:

<am:fault xmlns:am="http://wso2.org/apimanager">

<am:code>405</am:code>

<am:type>Status report</am:type>

<am:message>Runtime Error</am:message>

<am:description>Method not allowed for given API resource</am:description>

</am:fault>

but when we use other verbs like post or put the response is this one:

<am:fault xmlns:am="http://wso2.org/apimanager">

<am:code>404</am:code>

<am:type>Status report</am:type>

<am:message>Runtime Error</am:message>

<am:description>No matching resource found for given API Request</am:description>

</am:fault>

This was tested with the wum level 1640361868835 and with the las U2 updated version

[1]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by msm1992** [comment]
Fixed in wso2/carbon-apimgt with https://github.com/wso2/carbon-apimgt/commit/dec392b8a5cbbe083ac3e069a7dbf7ac23a6d498
