### ISSUE TITLE
Readme.md not updated in apim-apps 

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-apim#12341]
### Describe your problem(s)
https://github.com/wso2/apim-apps#readme

When we are trying to build the repo by following the readme.md in apim-apps, the files explained there are not available.
Ex:
`Open the portals/ directory (where the lerna.json is located)`

Cannot find a file called `lerna.json `.

Also when we perform the step, `Run npm run bootstrap to install the dependencies for all 3 portals` it gives below error
saying `stack Error: Missing script: "bootstrap"`.

Also we can update the copyright licence year.

### Describe your solution
Update the readme.md to match with latest updates in the repo.

### How will you implement it

---

**Comment by Krishanx92** [comment]
This is updated now.
