### ISSUE TITLE
APIM samples Readme.md file is not updated

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-apim#12355]
### Describe your problem(s)
https://github.com/wso2/product-apim/tree/master/modules/samples 
In the above link's `Readme.md` file explains about three samples to try out with product APIM.

![image](https://user-images.githubusercontent.com/40932779/153422039-0eab6f02-33b4-4bb7-b37e-ba8d66805f02.png)

But in the directory  some of the described samples are not available (as explained in below image).
![image](https://user-images.githubusercontent.com/40932779/153422624-ec674fe2-a04b-4555-9ab9-261eb89764c2.png)

### How will you implement it

---

**Comment by Krishanx92** [comment]
Currently there's no samples, hence not required
