### ISSUE TITLE
Inconsistency in error response for a retired API

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#12353]
### Description:
When invoking a retired API, the error response is different for a normal API and a default API

### Steps to reproduce:
Scenario 1

1. Create and publish an API.
2. Subscribe and invoke the API.
3. From the publisher portal change the life-cycle to Deprecated and Retired.
4. Invoke the API and receive 404 Not Found.

Scenario 2

1. Create an API, set it as the default version and publish the API.
2. Subscribe and invoke the API.
3. From the publisher portal change the life-cycle to Deprecated and Retired.
4. Invoke the API and receive 500 Internal Server Error.

### Affected Product Version:
APIM 3.2.0

**Comment by chamilaadhi** [comment]
Tried this in the latest build (4.3.0) and it gives the correct error message
<img width="967" alt="Screenshot 2024-03-05 at 10 28 04 AM" src="https://github.com/wso2/product-apim/assets/4861150/08ee6721-ad29-424a-82f6-472f218b4c93">
