### ISSUE TITLE
Can't download the Service definition when clicking the Download button

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-apim#12368]
### Description:

When trying to download the service definition from the service catalog service, it shows an UI error alert.

### Steps to reproduce:

2.  Go to the services by clicking the services Icon in the left menu
2. Click Add sample and deploy the sample service.
3. Go to the overview of the service and click the download button.

![image](https://user-images.githubusercontent.com/21282060/153556615-c59cd965-cefd-46c2-af57-33b0feb03de5.png)

### Affected Product Version:

APIM 4.1.0 pre alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/179
