### ISSUE TITLE
Incorrect lifecycle state name shown in the history table

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#12363]
### Description:
When changing the lifecycle state to PRE-RELEASED, the History table will show the state as PROTOTYPED.

![Screenshot from 2022-02-11 10-56-42](https://user-images.githubusercontent.com/25485273/153542159-7e5474f7-2025-4da0-b251-045198b8c28c.png)

**Comment by rmsamitha** [comment]
@IsuruMaduranga is working on this

**Comment by tharikaGitHub** [comment]
Fixed in above commit
