### ISSUE TITLE
Try out section in the left menu is hidden for API products

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#12364]
### Describe your problem(s)
Try out section is hidden for API products, in the left sided menu. But try out is supported for API products and can only be accessible via overview page try out button.

![image(2)](https://user-images.githubusercontent.com/25485783/153548950-5b2c9a06-7622-4f70-a192-7c63f460df3a.png)

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/174
