### ISSUE TITLE
Analytics URL in Publisher Portal needs to change

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#12374]
### Description:

It seems the analytics icon which is shown below navigates the user to the old analytics portal URL(https://analytics.choreo.dev/setup). 

<img width="1440" alt="Screenshot 2022-02-11 at 15 42 24" src="https://user-images.githubusercontent.com/13759167/153582499-71672705-f06f-46ba-a250-1d082fba2311.png">

This needs to change to the Insights page of the Choreo Console(https://console.choreo.dev/insights)

### Steps to reproduce:
As shown in the above screenshot

### Affected Product Version:
APIM 4.0
APIM 4.x

**Comment by fazlan-nazeem** [comment]
With the recent changes in Choreo end, it seems the url (https://console.choreo.dev/insights) will not be supported anymore. Hence we can point to the URL to the Choreo console homepage (https://console.choreo.dev)

**Comment by ashera96** [comment]
Reopening this issue as we still need to fix it for APIM 4.0.

**Comment by fazlan-nazeem** [comment]
@ashera96 we have done further improvements from Choreo end and now users can directly navigate to the insights page with console.choreo.dev/insights URL. Therefore can we also update the fix with this URL please.

**Comment by ashera96** [comment]
Reopening again as we still need to fix this for APIM 4.0.

**Comment by chamilaadhi** [comment]
closing since this is fixed in master.
