### ISSUE TITLE
UI - add_tenant.jsp not rendering properly after logging in to carbon console with user - admin@wso2.com

### ISSUE THREAD

**Issue by ak1801** [wso2/product-apim#1238]
I observed a bug in wso2 after changing username from admin to admin@wso2.com. The reason for doing this is to support Signature validation in dedicated mode.

OBSERVATION:
------------------------
After making the change, when I logged in to carbon console to add a new tenant, the add_tenant.jsp https://localhost:9443/carbon/tenant-mgt/add_tenant.jsp  page does not render properly.

The difference is that email address input is not displayed in the UI. So, when I try to submit the form, it gives a pop up saying “Please enter a valid email address.” (checked in Chrome and Mozilla)

Please find the attached screenshots to see the difference before change and after change.
<img width="960" alt="wso2_carbon_tenant_after1" src="https://cloud.githubusercontent.com/assets/6078058/20916138/317fc3e6-bbb0-11e6-8419-94bcd0f2feb3.png">
<img width="1705" alt="wso2_carbon_tenant_before" src="https://cloud.githubusercontent.com/assets/6078058/20916139/31bf84ea-bbb0-11e6-8dae-9ec0b5343403.png">
<img width="960" alt="wso2_carbon_tenant_after" src="https://cloud.githubusercontent.com/assets/6078058/20926458/5b519726-bbe2-11e6-8604-4e3720ed5ba4.png">

AFFECT:
--------------
With admin@wso2.com, we would not be able to add a new tenant in WSO2 from UI. I don’t know whether it will work from api or not. Consequently, we would have to change back the user to admin for adding a new tenant and republish all the APIs which would be unnecessary overhead.

Please look into this issue and let me know the alternatives.

**Comment by chamilaadhi** [comment]
If you want to use email as a user name (admin@wso2.com instead of admin) , first you have to do the configurations mentioned in https://docs.wso2.com/display/IS500/Email+Authentication

**Comment by ak1801** [comment]
@chamilaadhi - I followed the Email Authentication guide which you shared. I am not using any LDAP or Active Directory/JDBC-based user store, so I ignored configuration parameters of the user store managers. But I have correctly configured Realm configurations and set EnableEmailUserName, Email Authentication is working fine but still the issue persists. 

Let me know your thoughts on this.

**Comment by harsha89** [comment]
Please post about this at dev@wso2.org
