### ISSUE TITLE
[APIM-3.2.0][Workflows] - Missing ApplicationDeletion, SubscriptionDeletion and SubscriptionUpdate workflows

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#12393]
### Describe your problem(s)
In wso2am-3.2.0, ApplicationDeletion, SubscriptionDeletion, and SubscriptionUpdate workflows are not implemented to be worked as OOTB features just like other workflows in the product.

### Describe your solution
Just as ApplicaitonCreation, SubscriptionCreation, and APIStateChange workflows were implemented, the above-mentioned missing workflows also should be implemented in a way to work as OOTB features of the product.

**Comment by chamilaadhi** [comment]
These are available in the latest APIM versions now
