### ISSUE TITLE
WS connection not terminated when the backend URL is changed from Publisher

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/product-apim#12417]
### Description:
WS connection not terminated when the backend URL is changed from Publisher and re-deployed

### Steps to reproduce:

- Create a WS API with an WS backend that constantly sends back messages to the client
- Invoke the WS API
- Update the Production / Sandbox URLs of the publisher
- Re-deploy the WS API

You will notice that the WS connection to the old backend still exists.

### Affected Product Version:
WSO2 API Manager 3.2.0

### Environment details (with versions):
- OS: Any
- Client: `<Censored>`
- Env (Docker/K8s): Any

---
#### Related Issues:

- APIM Internal issue: https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1660
- CS ticket: `<Censored>`

#### Suggested Labels:
APIM320, P2, critical, patch

#### Suggested Assignees:
N/A

**Comment by vidurananayakkara** [comment]
- GIT Issue: https://github.com/wso2/product-apim/issues/12417
- APIM Internal Issue: https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1660
- CS ticket: `<Censored>`
- API Patch issue: https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1671

**Comment by Krishanx92** [comment]
This is on-hold ATM as per request. Hence closing
