### ISSUE TITLE
Role/Scope assignments are not shown on UI

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#12411]
### Description:
When a scope assignment is done from the Admin portal, the newly added assignment is not shown in the UI. However, this assignment can be seen under the tenant-conf in Advanced Configurations. It will show up automatically after some time or after a server restart.

![Peek 2022-02-17 10-00](https://user-images.githubusercontent.com/25485273/154411788-3c648271-d1c2-4565-844f-3d97ef17543d.gif)

### Affected Product Version:
4.1.0 Pre Alpha

**Comment by tgtshanika** [comment]
Scope mapping deletion also not getting reflected in the UI. It takes some time to remove the entry from the mapping list.
