### ISSUE TITLE
Cannot deploy the REST API when it is updated and invoked using postman

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#12421]
### Description:
When we update and invoke a REST API using postman, it shows the solace environment in Deployments tab and unable to deploy the API.

### Steps to reproduce:

![Screenshot 2022-02-18 16:08:04](https://user-images.githubusercontent.com/31464477/154671626-6aa24adf-40e8-4b34-839a-f83d39635a19.png)
![Screenshot 2022-02-18 16:09:05](https://user-images.githubusercontent.com/31464477/154671775-bfe8935d-d98b-4243-98f0-d467c031b214.png)

Following is the json data used to update the REST API.
`{
  "id": "71889e16-773e-471b-bc53-251569efff64",
  "name": "SwaggerPetstore_v3",
  "description": null,
  "context": "/SwaggerPetstorev3",
  "version": "1.0.0",
  "provider": "admin",
  "lifeCycleStatus": "PUBLISHED",
  "wsdlInfo": null,
  "responseCachingEnabled": false,
  "cacheTimeout": 300,
  "hasThumbnail": null,
  "isDefaultVersion": false,
  "enableSchemaValidation": false,
  "type": "HTTP",
  "transport": ["http", "https"],
  "tags": ["cat","dog","lion"],
  "policies": ["Unlimited"],
  "apiThrottlingPolicy": "Unlimited",
  "authorizationHeader": "X-Authorization",
  "securityScheme": ["oauth2", "oauth_basic_auth_mandatory"],
  "maxTps": null,
  "visibility": "PUBLIC",
  "visibleRoles": [],
  "visibleTenants": [],
  "mediationPolicies": [],
  "subscriptionAvailability": "ALL_TENANTS",
  "subscriptionAvailableTenants": [],
  "additionalProperties": [],
  "monetization": null,
  "accessControl": "NONE",
  "accessControlRoles": [],
  "businessInformation": {
    "businessOwner": null,
    "businessOwnerEmail": null,
    "technicalOwner": null,
    "technicalOwnerEmail": null
  },
  "corsConfiguration": {
    "corsConfigurationEnabled": true,
    "accessControlAllowOrigins": ["*"],
    "accessControlAllowCredentials": false,
    "accessControlAllowHeaders": ["authorization", "Access-Control-Allow-Origin", "Content-Type", "SOAPAction"],
    "accessControlAllowMethods": ["GET", "PUT", "POST", "DELETE", "PATCH", "OPTIONS"]
  },
  "workflowStatus": null,
  "endpointConfig": {
    "endpoint_type": "http",
    "sandbox_endpoints": {
      "url": "https://localhost:9443/publisher-new/apis/create/openapi"
    },
    "production_endpoints": {
      "url": "https://localhost:9443/publisher-new/apis/create/openapi"
    }
  },
  "endpointImplementationType": "ENDPOINT",
  "scopes": [
    {
      "scope": {
        "name": "SwaggerPetstore_v3",
        "description": "SwaggerPetstore_v3",
        "bindings": [
          "admin"
        ]
      }
    }
  ],
  "operations": [{
    "id": "",
    "target": "/pets",
    "verb": "GET",
    "authType": "Application & Application User",
    "throttlingPolicy": "Unlimited",
    "scopes": ["SwaggerPetstore_v3"]
  }, {
    "id": "",
    "target": "/pets",
    "verb": "POST",
    "authType": "Application & Application User",
    "throttlingPolicy": "Unlimited",
    "scopes": ["SwaggerPetstore_v3"]
  }, {
    "id": "",
    "target": "/pets/{petId}",
    "verb": "GET",
    "authType": "Application & Application User",
    "throttlingPolicy": "Unlimited",
    "scopes": []
  }],
  "threatProtectionPolicies": null
}`
### Affected Product Version:
4.1.0-alpha

**Comment by chamilaadhi** [comment]
Postman collections will be updated for 4.1.0 from https://github.com/wso2/product-apim/issues/12315 . Once it is done, we could check this

**Comment by YasasRangika** [comment]
This will be fixed with the fix of https://github.com/wso2/product-apim/issues/12315
