### ISSUE TITLE
[apim 4.0] - tenant user unable to generate access token.

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#12423]
### Description:
Tenant user is unable to generate access token for his/her own application.

### Steps to reproduce.
Create a tent admin say admin@wso2.com
Login to carbon console and create a tent user with subscriber role say sam@wso2.com
Login to devportal using sam@wso2.com
Create an application
Generate production or sandbox keys.
Click the "Generate Access Token" button.
Click the "Generate" button on the dialog that appears.
<img width="1412" alt="Screenshot 2022-02-18 at 19 49 18" src="https://user-images.githubusercontent.com/3424539/154699753-279d325e-9a96-4ec3-9ab2-d1e932b424e2.png">

**Comment by chamilaadhi** [comment]
not reproducing in APIM 4.3.0 alpha
