### ISSUE TITLE
Password recovery mail is not sent to the registered email 

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#12439]
### Description:

Password recovery capability is not working in the latest pack [1].
Even though in the UI it says the email sent to the registered email for password recovery, the email is not received.

![Screenshot from 2022-02-23 10-41-29](https://user-images.githubusercontent.com/60866295/155264946-d1a84288-0f52-4407-b520-b6fe042715ba.png)

**Stack trace :**

`[2022-02-23 10:46:50,759] ERROR - RecoverPasswordApiServiceImpl Unable to find an user with username: saran in the system.`

The Back end is looking for` saran` instead of `saran@flight.com`.

This is happening for super tenant users too.

`[2022-02-23 11:02:05,223] ERROR - RecoverPasswordApiServiceImpl Unable to find an user with username: test1 in the system.`

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery

### Steps to reproduce:

1. Create a tenant user.
2. Follow steps in [1]

### Affected Product Version:

 APIM 4.1.0

**Comment by mushthaq33** [comment]
Did we setup a valid [output_adapter.email]?

**Comment by Sarangan0219** [comment]
yes. For Account locking, after the failed login attempts the mail is successfully sent to the configured mail address. 
Only the password recovery is not working.

**Comment by mushthaq33** [comment]
Closing this as this is not reproducible in the latest pack.
