### ISSUE TITLE
Error in generating App keys with Okta KM in Distributed Setup

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#12446]
### Description:

After adding okay KM unable to generate App keys and keys are generated partially and need to clean up.

<img width="1680" alt="Screenshot 2022-02-23 at 12 13 12" src="https://user-images.githubusercontent.com/23296184/155272333-3b316956-95af-4117-b748-1c022235f26d.png">

Following error seems to present in carbon logs.

<img width="1378" alt="Screenshot 2022-02-23 at 11 27 30" src="https://user-images.githubusercontent.com/23296184/155272474-14716a48-43a9-4928-8cf4-e55790022b8b.png">

But, same okta configuration in an ALL in One local pack works without issues and keys and token can be generated.

### Steps to reproduce:

Follow the steps in https://apim.docs.wso2.com/en/4.1.0/administer/key-managers/configure-okta-connector/#configure-okta-as-a-key-manager

### Affected Product Version:
APIM 4.1-alpha

**Comment by Krishanx92** [comment]
Fixed in APIM-4.1.0-Beta
