### ISSUE TITLE
UI improvement to Account locking by an administrative user

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#12441]
### Describe your problem(s)

When the account is locked by admin user and when a user tries to login we are just popping up an authentication error.

![Screenshot from 2022-02-23 11-23-26](https://user-images.githubusercontent.com/60866295/155268212-ac32d6bc-997a-46d1-862d-41b30f46c123.png)

It is better to tell the user that the account is locked. And contact the admin user.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking-by-an-administrative-user

### Affected Product Version

APIM 4.1.0

**Comment by Krishanx92** [comment]
Currently on-hold, we'll consider this once theres any requirment.
