### ISSUE TITLE
Incorrect redirection when working with dynamic endpoints

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#12447]
### Description:
When we click the arrow button, it redirects us to Runtime Configurations. Since the policies and sequences are moved to Policies section, this should redirect to that.

![image](https://user-images.githubusercontent.com/25485273/155273176-26473e8b-170b-44c6-ac0d-367fc9c18d46.png)

### Affected Product Version:
4.1.0-alpha

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/apim-apps/pull/209
