### ISSUE TITLE
[Distributed Setup Publisher] Business plans page is keep loading when subscription Count > 0 and gives an error page 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#12455]
### Description:
<img width="1279" alt="Screen Shot 2022-02-23 at 2 37 34 PM" src="https://user-images.githubusercontent.com/29066805/155289192-cd050c9a-7c16-43a4-8cd9-aa0ec1cb3a8a.png">

<img width="1255" alt="Screen Shot 2022-02-23 at 2 39 30 PM" src="https://user-images.githubusercontent.com/29066805/155289511-e52d15d2-811d-4fbb-97d0-805a9bb11f9c.png">

### Steps to reproduce:
1. Create an API with tenant user
2. Deploy the API 
3. Subscribe to API 
4. Login to publisher portal and load the subscriptions

### Affected Product Version:
APIM-4.1.0

### Environment details (with versions): Distributed Setup 
- OS: 
- Client:
- Env (Docker/K8s): 

---

**Comment by Krishanx92** [comment]
Fixed in APIM-beta
