### ISSUE TITLE
Cannot select multiple external stores and publish at once in publisher

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-apim#12454]
### Description:

When trying to select multiple external stores at once, it only publishes the API to one external store. 

### Steps to reproduce:

1. Add multiple external stores via carbon console.
Follow  https://apim.docs.wso2.com/en/latest/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores/
2. Go to the publisher portal and create and publish an API.
3. Go to the External Dev Portal tab in the left menu and select multiple dev portals at once.
4. Click the save button you can see it only publish to one store and the tick only contains for one store after saving.

![image](https://user-images.githubusercontent.com/21282060/155289017-068fcad3-2114-4f27-81e5-55d44ff2d12c.png)

### Affected Product Version:

APIM 4.1.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by rmsamitha** [comment]
As per @chashikajw 's observation, at any given time only one store will be displayed as ticked eventhough the api is published to multiple stores.
Hence marking this as "Priority/High"
