### ISSUE TITLE
Cannot upload document as a zip in APIM 3.2.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#12457]
### Description:

 In APIM 2.6.0, we can upload a document as a zip for an API. 
<img width="965" alt="canUploadZipFiles" src="https://user-images.githubusercontent.com/15210142/155291612-dd575c3f-2ccf-412d-9859-99c0d2fd4ba8.png">
<img width="1076" alt="ShowUploadedZipFiles260" src="https://user-images.githubusercontent.com/15210142/155291637-3f9351b3-864b-4330-a7d0-a1c0d49c7a51.png">
However, when coming to APIM 3.2.0, it cannot upload a zip file as a document. So, when trying to upload a zip file, it couldn't upload those files and show them as restricted. 
<img width="877" alt="zipFileUploadDisabled" src="https://user-images.githubusercontent.com/15210142/155291707-e82fb565-4854-408b-bee9-56cd54ac3a73.png">

### Steps to reproduce:
1. Get an APIM 3.2.0 latest updated pack.
2. Start the pack and create an API.
3. Try to add a zip-type document to that API.

### Affected Product Version:

APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This is not applicable now, hence closing
