### ISSUE TITLE
Curl provided in the devportal UI for access token generation with Password Grant type fails

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#12466]
### Description:
The curl provided by the UI for access token generation using the Password Grant type responds with the following error:

`{"error_description":"Authentication failed for Username","error":"invalid_grant"}%` 

### Steps to reproduce:
1. Pick any API from the Developer portal API list.
2. Click on `Subscriptions`.
3. Subscribe to any application.
4. Click `PROD KEYS`.
5. Click `Generate Keys` and  click on the `CURL TO GENERATE ACCESS TOKEN` button. You should then be able to see the following screen:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/30475839/155336175-ff237ca4-a49c-4770-a9de-9ec417fb6177.png">

6. Try copying the first curl (i.e the curl corresponding to the Password Grant type) and executing that in a terminal. The below provided error should get logged.
           `{"error_description":"Authentication failed for Username","error":"invalid_grant"}%` 

7. Note that the curl provided for the access token using the Client Credentials grant type works as expected.

### Affected Product Version:
4.1.0-alpha

**Comment by mushthaq33** [comment]
This works fine for me. @ashera96 - Did you change the username and password to a valid one? The copied one has sample username and password.
