### ISSUE TITLE
[Publisher] Layout shift in lifecycle publish 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#12478]
### Description:
There is a layout shift effect and UX issue in the popup box which appears when trying to publish an API without a deployment

`See more` button should toggle expand/collapse not suddenly appear and disappear
![lifecycle](https://user-images.githubusercontent.com/3313885/155509272-1294ee2c-0d5a-4305-bcf0-d2785bf9c6ec.gif)

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/apim-apps/pull/216
