### ISSUE TITLE
[Developer portal] API definition page break with anonyomous user

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#12480]
### Description:

Complete while page

![image](https://user-images.githubusercontent.com/3313885/155510537-46f0f21c-604d-415e-9f33-4e53b705de07.png)

**Comment by tharikaGitHub** [comment]
This is not reproducible in the 4.1.0 beta pack. Hence closing.

**Comment by tmkasun** [comment]
Yes seems like this is fixed now, This happened with async websocket API, [Example definition](https://raw.githubusercontent.com/asyncapi/spec/master/examples/websocket-gemini.yml)
