### ISSUE TITLE
Restore a revision does not reload the policies page

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12483]
### Description:
When we restore a revision from the deployment page and immediately visit the policies page, it still shows the before restore state of the policies that are applied. We need to reload the page or visit the homepage and again visit the policies page to get the latest state.

### Steps to reproduce:
1. Revision an API without operation policies.
2. Add a policy and create a new revision.
3. Restore the 1st revision and immediately visit the policies page from the deployment page.
4. Even though 1st revision does not have any policies, there are policies displayed at the flows.
5. Refreshing the page will remove this from UI.

### Affected Product Version:
4.1.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ashera96** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/180/commits/9f21d13a46d634824a9028d67512bb1997efdd32 from [1]. 

### PR Link
1. https://github.com/wso2/apim-apps/pull/180
