### ISSUE TITLE
[Websocket] Async API definition does not update when endpoints are changed from publisher portal

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#12535]
### Description:
$subject

### Steps to reproduce:
Create a websocket API with an endpoint. 
Then try changing the endpoint from publisher portal and save.
Check the async api definition.

### Affected Product Version:
4.1.0-beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Fix https://github.com/wso2/carbon-apimgt/pull/11154
