### ISSUE TITLE
Performance Issue on using pax-logging 1.11.3 with log4j2 async logging.

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-apim#12547]
Hi All,
When we use pax-logging 1.11.3 with async logging we see the high latency introduced in the following stack trace due to push log events into the OSGi service.

The issue has been reported to pax logging team by @tharindu1st  (https://support-internal.wso2.com/jira/secure/ViewProfile.jspa?name=tharindua%40wso2.com) [1] and they have pushed the fix to the maven central [2] , [3] (official announcement is yet to be done).

Need to update library versions in APIM 3.1.0 (and other relevant versions) to get this update.

[1] - https://github.com/ops4j/org.ops4j.pax.logging/issues/480
[2] - https://mvnrepository.com/artifact/org.ops4j.pax.logging/pax-logging-log4j2/1.11.15
[3] - https://mvnrepository.com/artifact/org.ops4j.pax.logging/pax-logging-api/1.11.15

Regards,
PasinduJ

**Comment by binodmx** [comment]
Updated pax-logging version to 1.11.16
