### ISSUE TITLE
JWT claims conditions for advanced throttling is not working

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#12558]
### Description:
JWT claims condition for advanced throttling policies is not working

### Steps to reproduce:
1. Add `enable_jwt_claim_based_throttling = true` under apim.throttling in deployment.toml.
2. Start the server.
3. Define JWT Condition Policy in a new Advanced Policy.
4. Add the defined policy for an API.
5. Invoke and check whether requests get throttled.

Refer to [docs](https://apim.docs.wso2.com/en/latest/design/rate-limiting/adding-new-throttling-policies/#adding-a-new-advanced-rate-limiting-policy) for more info.

**Comment by tharindu1st** [comment]
This cannot reproduce in latest pack
