### ISSUE TITLE
[4.0.0] "Unauthenticated Request" Alert Pops-Up when a User with only Internal/publisher role Navigates to the Runtime tab Under API Configurations of an API

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#12563]
### Description:
`Unauthenticated request` alert pops-up when a user with only Internal/publisher role navigates to the Runtime tab under API Configurations of an API. Also, the following error logs in the console.
```
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

### Steps to reproduce:
1. Create an API
2. Create a user and assign only the Internal/creator role.
3. Log in to the Publisher portal with this user.
4. Click on the `Runtime` tab under `API Configurations` section of the API.
5. Then `Unauthenticated request` alert will pop-up from top right corner and the page will be displayed. The above mentioned error will be logged in the server console.

### Affected Product Version:
API-M 4.0.0

**Comment by chamilaadhi** [comment]
Seems this issue is not available in the latest 4.3.0 alpha pack
