### ISSUE TITLE
Access token generation fails in cross tenant subscription

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/product-apim#12570]
### Description:

Access token generation gives page not found error in cross tenant subscription

<img width="1429" alt="Screenshot 2565-03-07 at 18 30 06" src="https://user-images.githubusercontent.com/36605514/157039279-8045e1e1-2845-4589-8cbb-f6264fd4ca96.png">

### Steps to reproduce:
1. Subscribe to an API in a different tenant
2. Try to generate an access token

### Affected Product Version:

APIM-4.1.0-beta

### Environment details (with versions):
- OS: MacOS
- Client: Local

**Comment by prasa7** [comment]
Fixed with - https://github.com/wso2/carbon-apimgt/pull/11135
