### ISSUE TITLE
API products with mediation sequences are not working

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#12587]
### Description:
When invoking an API product with an API resource which includes a mediation sequence, we are getting  **500: Internal Server Error** with that particular resource of the API product. 
The following error response is coming in the invocation. 
`
{ "code": "0", "type": "Status report", "message": "Runtime Error", "description": "Sequence named Value \{name ='null', keyValue ='mine-test:v1.0.0--In'}
cannot be found"
}
`

### Steps to reproduce:
Create API and add any IN mediation sequence.  
Create API product with some resource of the earlier API. 
Invoke the selected resource in the API-product.

### Affected Product Version:
v4.0.0

**Comment by nandika** [comment]
It seems this issue is fixed in 4.1 onwards
