### ISSUE TITLE
Selecting multiple error codes is not obvious to the user - Publisher - Endpoint Advance Configuration  

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#12580]
It's a better user experience if we can provide checkboxes with the dropdown.

<img width="819" alt="Screenshot 2022-03-08 at 10 47 04" src="https://user-images.githubusercontent.com/3424539/157171032-123fe8c4-7133-444a-9b97-dafbd389fb38.png">

We update from the component given with the MUI documentation.

https://v4.mui.com/components/selects/#multiple-select

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/apim-apps/pull/209
