### ISSUE TITLE
Response Caching enable toggle button auto off after saving for API Product

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#12596]
### Description:
Below is the behavior when we try to enable Response Caching for API Product.

![Peek 2022-03-08 18-43](https://user-images.githubusercontent.com/28702407/157245084-3141cb43-6d5c-4826-995e-10e8889c2ede.gif)

### Steps to reproduce:
- Create API Product with some APIs
- Enable response caching with toggle button
- Click on Save

### Affected Product Version:
APIM 4.1.0-beta

### Environment details (with versions):
Distributed Env

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/12579

**Comment by chanaka3d** [comment]
From the UI the API put happens with the expected payload `responseCachingEnabled: true` but the backend does not update this value.
