### ISSUE TITLE
Disabling of publish button when creating an API Product

### ISSUE THREAD

**Issue by Tharanidk** [wso2/product-apim#12591]
### Description:
Related to API Product creating,

After creating API product, before making a revision the publish button that available under Lifecycle section is not giving any output when it is clicked. There is also an error in browser console as in the below figure.

![button_error](https://user-images.githubusercontent.com/42825038/157239866-7d58cea8-efe7-47ad-8f36-30e8cced0666.png)

after the revision is done, cannot publish it. the publish button under Lifecycle is in disabled mode.

![api_product_issue](https://user-images.githubusercontent.com/42825038/157205908-5c748c8b-7589-4082-9260-64a87dca77c7.png)

when we choose create and publish button to do both at the same time it is working.

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/apim-apps/pull/216
