### ISSUE TITLE
SAML Extension Grant request fails

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/product-apim#12598]
### Description:

SAML Extension Grant request fails with following error

```
{"error_description":"Error while validating the signature.","error":"invalid_grant"}
```

### Steps to reproduce:
Follow the steps in the [documentation](https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/saml-extension-grant/).

### Affected Product Version:

APIM-4.1.0-beta

### Environment details (with versions):
- OS: mac OS Big Sur ( Version 11.6 )
- Client: Local

**Comment by tharindu1st** [comment]
This is due to how we copy saml asserstion
