### ISSUE TITLE
UI does not validate Roles when saving changes for Publisher Access Control 

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#12600]
### Description:
When we enable Publisher Access Control via the publisher portal at least one role we have specified must be associated with the API creator to prevent API loss to that user.

### Steps to reproduce:
- log in to the carbon console and create a new role: Internal/test
- log in to the publisher portal as tenant admin or publisher privileged user and create and publish an API Product
- enable Publisher Access Control from Basic Info page and specify roles as the role we created initially or role which is not having to currently log in user
- when after clicking 'enter' you will see the error to add at least one role associated with the API creator
In this phase, if we save the API, the operation becomes successful which should not be happened.

### Affected Product Version:
APIM-4.1.0-beta

**Comment by YasasRangika** [comment]
Furthermore checking we can see it is not validating errors in any of the fields.

**Expected behavior:**
If any of the fields show an error, the 'Save' button should be in disabled mode

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/apim-apps/pull/209
