### ISSUE TITLE
501 response for inline prototyped APIs

### ISSUE THREAD

**Issue by akila95fernando** [wso2/product-apim#12604]
### Description:
When deploying a prototyped API with inline script mediator. 
It always returns 501. 

### Steps to reproduce:
Update wso2am-2.6.0 to level 78 
Create an API
In the Implement tab , select prototyped api and select inline implementation. 
Edit the response( uncomment )
Deploy the API
Invoke the APi
API returns 501 
### Affected Product Version:
APIM-2.6.0

**Comment by Krishanx92** [comment]
Could not reproduce in latest pack. hence closing
