### ISSUE TITLE
Incorrect error code in Role-Based Access Control Using XACML

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/product-apim#12610]
### Description:

Unauthorized requests give HTTP 500 error code.

<img width="1440" alt="Screenshot 2565-03-09 at 16 22 59" src="https://user-images.githubusercontent.com/36605514/157428995-c1e42450-0108-4f20-90f3-67e883d95e85.png">

### Steps to reproduce:
1. Follow the [documentation](https://apim.docs.wso2.com/en/latest/design/api-security/authorization/role-based-access-control-using-xacml/#enabling-role-based-access-control)
2. Log in to dev portal as api_user
3. Send a POST request to /order endpoint 

### Affected Product Version:

APIM-4.1.0-beta

### Environment details (with versions):
- OS: macOS Big Sur
- Client: Local

**Comment by tharindu1st** [comment]
reffer https://ei.docs.wso2.com/en/7.2.0/micro-integrator/references/mediators/entitlement-Mediator/
