### ISSUE TITLE
Even if it is a prototype, getting invalid credentials issue

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#12620]
### Description:
user@Users-MacBook-Pro bin % curl -X 'GET' \
  'https://localhost:8243/v3/1.0.11/pet/1' \
  -H 'accept: application/xml' \
  -H 'Authorization: Bearer undefined' -k
{"code":"900901","message":"Invalid Credentials","description":"Access failure for API: /v3/1.0.11, version: 1.0.11 status: (900901) - Invalid Credentials. Make sure you have provided the correct security credentials"}%

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
Now prototype apis need the authentication token
