### ISSUE TITLE
Issue in creating a read-only role from admin console

### ISSUE THREAD

**Issue by Tharanidk** [wso2/product-apim#12627]
### Description:
When creating a read-only role from admin console , we need to make scope configurations. when assigning permissions we need to check only the `apim:api_view ` permission under the Publisher.

But in the latest version that permission is not showing. It seems like a UI issue because that permission can be found when we inspect and see from the browser console

![read_only_role](https://user-images.githubusercontent.com/42825038/157627682-688784cf-e30a-4032-8e4f-898af0fc1b32.png)
e

**Comment by hasuniea** [comment]
This is not a UI issue. We can't get the service-catalog's scope.
