### ISSUE TITLE
Disable the "Operations" tab of Published GraphQL APIs for users with Internal/creator or Internal/publisher roles

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12624]
### Description:
Once a REST API is published, the users with the Internal/creator or Internal/publisher roles cannot edit the "Resources" tab. However, for GraphQL APIs we are allowing them to edit the "Operations" page from the UI. 
We need to disable the options for the users with Internal/creator or Internal/publisher roles in that page when the GraphQL APIs are published. (Otherwise, when they hit the save button, they will receive an error)

### Steps to reproduce:
1. Create a GraphQL API, deploy it and publish it.
2. Login to the Publisher Portal as a user with the Internal/creator or Internal/publisher roles.
3. Navigate to the **Operations** tab and you can see that the user can edit those. (We need to disable the options)
    ![image](https://user-images.githubusercontent.com/25246848/157615381-d5ee7c06-5114-4a9e-a92c-8d3a9911aa0d.png)
4. Unknowingly, when the user hits the Save button they will receive an error as below.
    ![image](https://user-images.githubusercontent.com/25246848/157616523-528cfba2-2321-4f4d-8f25-60c182b0ea47.png)

### Affected Product Version:
APIM 4.1.0-Beta

**Comment by chanaka3d** [comment]
Fixed with @tharikaGitHub commit here https://github.com/wso2/apim-apps/commit/84eb756fec1eba3f515794946bfe9d386d2ca6b3
