### ISSUE TITLE
Developer portal refresh page redirect to home page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#12635]
### Description:
- Open any page other than the home page
- refresh the page
- user gets redirected to home page
- AND also , It logged out the user from other portals (publisher & admin)

![refresh-issue](https://user-images.githubusercontent.com/3313885/157649405-0c1eb7b4-2d22-4a2e-840e-eaad8585c97c.gif)

**Comment by chanaka3d** [comment]
I am not able to reproduce this behavior in the chrome browser. Is there any specific env conditions set while you were testing this?

**Comment by tharikaGitHub** [comment]
This is happening in the Firefox browser and not in Chrome.
