### ISSUE TITLE
Exported API revisions does not contain the Policies folder inside the zip file

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12643]
### Description:
When you attach operational level policies, deploy a revision and export that particular revision, the Policies folder is not getting exported. The exported .zip will look like below.
![image](https://user-images.githubusercontent.com/25246848/157803664-03110a90-4311-4b85-b5c1-5fd9a2fc51d7.png)

The Policies folder is getting exported only when you export the current API.
![image](https://user-images.githubusercontent.com/25246848/157803819-de262b4d-465c-49f2-9102-0265a92cd552.png)

### Steps to reproduce:
1. Create an API
2. Add an operational policy
3. Deploy a revision
4. Export the revision either using the UI or apictl (_apictl export api -n PizzaShackAPI -v 1.0.0 -e production --rev 2_)
5. The exported .zip won't contain the Policies folder.
6. Export the current API either using the UI or apictl (_apictl export api -n PizzaShackAPI -v 1.0.0 -e production_)
7. The exported .zip will contain the Policies folder.

### Affected Product Version:
APICTL 4.1.0-Beta

**Comment by 1akshitha** [comment]
fixed via https://github.com/wso2/carbon-apimgt/commit/8562a85150afa79f961691a39411572dabdf6225
