### ISSUE TITLE
Grant types are not added by default when generating keys with IS as KM used as 3rd party KM

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#12642]
### Description:
Due to the above issue, tokens cannot be generated when using IS as KM as third party KM. No grant types are selected in the OAuth application that is created in the carbon console. This only works if key provisioning is done because we pre assign grant types.

<img width="1419" alt="Screenshot 2022-03-11 at 07 26 54" src="https://user-images.githubusercontent.com/8557410/157803166-06ce3bc2-ddca-46b0-adb0-356053f28a8f.png">

**Comment by chamilaadhi** [comment]
@tharikaGitHub Seems like you have missed to configure the supported grant types when you configure the Keymanager from the admin portal. See below image.

<img width="1334" alt="Screenshot 2022-03-14 at 11 35 51 AM" src="https://user-images.githubusercontent.com/4861150/158114620-f9bd79af-93ae-4bcf-83cd-9120a99a3a4d.png">

This configuration is mentioned in the https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/ as well.

Once this is configured, you would see the grant types in the dev portal. See below

<img width="1139" alt="Screenshot 2022-03-14 at 11 36 02 AM" src="https://user-images.githubusercontent.com/4861150/158114746-1ea4cd42-a6f9-4015-8a4f-6b549e499363.png">
