### ISSUE TITLE
Large fonts in the pop up dialog when switching gateway type in policies tab

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#12706]
### Description:

![image](https://user-images.githubusercontent.com/23183042/159146448-9ca1898e-e105-46ca-90d9-caf197d19a5e.png)

### Affected Product Version:
<carbon.apimgt.ui.version>9.0.292</carbon.apimgt.ui.version>

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by slahirucd7** [comment]
This was changed due to a review comment. https://github.com/wso2/apim-apps/pull/211#discussion_r824524996
Can apply smaller font size if need.
