### ISSUE TITLE
Newly added HTTP operations not getting applied already existing API policies in same resource

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#12711]
### Description:
CC supports only resource level API policies,
So if a new HTTP operation introduced to the same resource it should get API policies that already exists for same resource

### Steps to reproduce:
1. Create an API with resource /* GET, POST
2. Change gateway type to CC in policy view
3. Apply API policies, Add header, Add Query Param
4. Save API
5. Goto resources page
6. Add a new operation /* PUT
7. Save API
8. Download API and check api.yaml file
9. The newly added resource HTTP operation PUT did not applied the existing API policies

### Affected Product Version:
<carbon.apimgt.ui.version>9.0.292</carbon.apimgt.ui.version>
<carbon.apimgt.version>9.20.48</carbon.apimgt.version>

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Change the flow in latest release hence closing
