### ISSUE TITLE
Use a single Git repository to capture issues across API Manager components.

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#12715]
Use a common repository to capture all issues (including features) across runtimes APIM, MI and SI. Suggested repo https://github.com/wso2/api-manager. Source code can remain in separate repos as it makes sense, but we need to capture all issues in a single place for central visibility.

**Comment by tharikaGitHub** [comment]
This is done. The repository https://github.com/wso2/api-manager is used to maintain issues for all runtimes. Hence closing.
