### ISSUE TITLE
Cannot change the API product Lifecycle to publish after creation

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12724]
### Description:
When we create a new API product from the publisher UI, we have two options where we can just create the product and publish it later or create and publish at once. When we choose the first option and create the API, at the lifecycle section, publish button is disabled. However, we can change the status from the overview section as the publish button appears over there.

![chrome-capture (4)](https://user-images.githubusercontent.com/47380453/159407642-6f799c21-f3d4-44b1-98a2-792ceed9613b.gif)

### Steps to reproduce:
1. Create a new API product without publishing
2. Deploy the product
3. Try to change life cycle to publish from life cycle section
4. Try to change lifecycle from overview section

### Affected Product Version:
4.1.0 latest. UI version - 9.0.297

**Comment by tharikaGitHub** [comment]
This is fixed in the 4.1.0 RC2 pack. Hence closing.
