### ISSUE TITLE
Source code changes are not syncing properly with U2 updates

### ISSUE THREAD

**Issue by LayaniMal** [wso2/product-apim#12734]
### Description:

UI source code changes are not syncing properly with U2 updates.[1]

[1] https://github.com/wso2-support/carbon-apimgt/pull/4125/files 

### Affected Product Version:
APIM 3.2.0

#### Related Issues:

APIM Internal : https://support-internal.wso2.com/jira/browse/APIMINTERNAL-1827

**Comment by ashera96** [comment]
Source code changes done through [1] are shipped to the latest U2 updated APIM 3.2.0 and WUM updated APIM 3.2.0 packs upon the resolution of this reported issue. Relevant U2 PR can be found at [2] and the WUM PR can be found at [3].

#### Related Issues:
1. https://github.com/wso2/product-apim/issues/11995

#### Related PRs:
2. https://github.com/wso2-support/carbon-apimgt/pull/4125
3.  https://github.com/wso2-support/carbon-apimgt/pull/3899
