### ISSUE TITLE
Error log when starting API-M without APIs.

### ISSUE THREAD

**Issue by slahirucd7** [wso2/product-apim#12730]
### Describe your problem(s)
Below error log appears when we are restarting API-M without creating any APIs. 
(During the initial start-up)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40932779/159434020-08e8e3a7-84ed-4d6d-bec1-8dfb4c981bf6.png">

### Describe your solution
It's better if we can update it to an info log

### How will you implement it

---

**Comment by tharikaGitHub** [comment]
This error log is required to be thrown in an actual error scenario where no API artifacts are retrieved. Hence we cannot change this to an info log. The error log getting printed during startup when there are no APIs is harmless. Hence closing the issue.
