### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by HetongWang** [wso2/product-apim#1274]
Hi,
When I tried to do localization in client-side Javascript files. I found that `i18n.t()` cannot translate strings with `.` and `:`. i18n treats `.` and `:` as special chareacters to split the original strings by default. And wso2 doesn't pass any arguement to override the default options. 

What I did is changing the default options in i18next-1.5.9.js. 
``` javascript
  63     var o = {
  64         lng: undefined,
  65         load: 'all',
  66         preload: [],
  67         lowerCaseLng: false,
  68         returnObjectTrees: false,
  69         fallbackLng: 'dev',
  70         detectLngQS: 'setLng',
  71         ns: 'translation',
  72         nsseparator: ':',
  73         keyseparator: '.',
  74         selectorAttr: 'data-i18n',
  75         debug: false,
  76 
```

**Comment by harsha89** [comment]
We have done few fixes please try it with latest version and reopen the ticket
