### ISSUE TITLE
After an API is Published, certain properties can be edited only by the admin users

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12740]
### Describe your problem(s)
After an API is published, only the admin users can edit the endpoints, resources, runtime configurations etc. Not the users with the Internal/creator role nor the users with the Internal/publisher role.
If the creator wants to create a revision, the publisher needs to demote the API to the Created state, so that the creators can do the change and deploy a revision. 

Furthermore, when considering the API Products, after publishing those, the publishers can still edit.

### Describe your solution
There are two(2) possible fixes
1. Allows publishers to edit APIs that are in the Published state (this will bring consistency)
2. Remove all this unnecessary logic that makes the code complex and allow anyone with the necessary rights to edit the API without checking for its state
The most ideal solution would be the 2nd one.

**Comment by Arshardh** [comment]
This is expected. In-consistency with the product-apim is resolved in latest versions since a lifecycle is introduced for API products.
