### ISSUE TITLE
Error in Lifecycle page loading for a created API Product

### ISSUE THREAD

**Issue by Tharanidk** [wso2/product-apim#12762]
### Description:
After a API Product is created, and deployed , an error occurred when trying to view the life cycle page. The below error occured.

![api_product_lifecycle](https://user-images.githubusercontent.com/42825038/159904174-e0ddbef2-64e0-4dcd-a237-ad746e64fec6.png)

**Comment by tharikaGitHub** [comment]
This is fixed in APIM RC2 pack. Hence closing.
