### ISSUE TITLE
Subscription issue when create multiple API versions

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [wso2/product-apim#12787]
### Description:
Let's suppose we have version `1.0.0` of an API and it's published and subscribed to a devportal application.
Then If I create version `2.0.0` of the same API and publish it, the subscription of the second version will get automatically added to the same devportal application.

Meanwhile, we have observed that, if we add two different endpoints for those two versions, the second version's API invoke seems to go through the first version's endpoint.

Further, we checked this behavior with choreo-connect gateway and observed there, that we are not getting the subscription event to the gateway, even if the second version get auto subscribed.

### Steps to reproduce:

1. Create an API in publisher portal with version 1.0.0 and deploy -> publish -> subscribe to a devportal app -> invoke.
2. Now create a second version as 2.0.0, of the same API -> deploy -> publish.
Note : make sure to provide two different endpoints for the two versions, in order to see which endpoint is used when invoking.
4. Go to devportal and see the subscriptions for the application created in step 1. (you can see the second version's subscription is already added)
5. Now try to invoke the two versions of the API independently (you will observe both the API calls will go through the first version's endpoint)

### Affected Product Version:
4.1.0-rc

### Environment details (with versions):
- OS: Ubuntu 20.04

---

**Comment by Krishanx92** [comment]
@VajiraPrabuddhaka 
In step 4 once you change endpoint did you save and deploy the API before publish? This could happen if you didn't

**Comment by VajiraPrabuddhaka** [comment]
@Krishanx92 sorry for the confusion, yes I changed the endpoint and saved before deploy and publish.

**Comment by Krishanx92** [comment]
![Screenshot from 2022-03-27 09-41-47](https://user-images.githubusercontent.com/8374895/160266311-144e047b-0e38-4ac2-9ee2-ba109a4caf6d.png)

Also if you need to remove subscription you can check the re-quire subscription when publishing API.

**Comment by pubudu538** [comment]
Based on the offline discussion we had, I see two issues here.

1. When we create the second API and make that default or not, it automatically gets subscribed with the existing application. Based on the above comment, we can control that when we do the API publishing. Here the issue is that we don't receive the subscription event. Hence sub validation fails. If we are automatically subscribing to the app,  then we should shoot an event so that the gateways get the sub event.

2. Gateway is not routing the correct backend when the API request goes to the default route.

**Comment by VajiraPrabuddhaka** [comment]
I have checked this further and verified there are no issues when we are using with the synapse gateway..

@pubudu538 @Krishanx92 I have created this issue https://github.com/wso2/product-apim/issues/12790 for the subscription event not receiving issue. 

Hence closing this issue..
