### ISSUE TITLE
Subscription event is not publishing when auto subscribed into a new API version

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [wso2/product-apim#12790]
### Description:

When running APIM with choreo connect gateway, we have observed that when we create a new version(either default or not) and publish it, APIM is automatically subscribing that new version to the applications which were already subscribed to the first version.

In this case we have seen that there is no subscription event triggered (only triggering the `API_LIFECYCLE_CHANGE`).

Due to this behavior choreo connet unable to add the subscription for the new version and it causes for invocation failure.  

### Steps to reproduce:
1. Start APIM with choreo-connect gateway
2. Create an API in publisher portal with version 1.0.0 and deploy -> publish -> subscribe to a devportal app -> invoke
3. Now create a second version as 2.0.0, of the same API -> deploy -> publish.
4. Now we can see the second version is already subscribed to the application in step 1.
5. Then try to invoke the second version and it will shows the subscription validation failure.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
@tharindu1st Any input for this?
