### ISSUE TITLE
Added thumbnail image is not visible on publisher API Product listing page

### ISSUE THREAD

**Issue by YasasRangika** [wso2/product-apim#12803]
### Description:
An added thumbnail image is not visible on the publisher portal's API Product listing page, though it is visible in the devportal.

### Steps to reproduce:
Upload an image as a thumbnail image for API Product.

### Environment details (with versions):
- RC2 DS
- Local all in one setup - Ubuntu 20.04 LTS

**Comment by tharikaGitHub** [comment]
This is not reproducible. Hence closing.

**Comment by YasasRangika** [comment]
Reopening the issue since this is reproducing when saving the API using the Save button.

**Comment by Sachini-Dissanayaka** [comment]
Fixed in the APIM latest release
