### ISSUE TITLE
Self signup config is not honored when signing up tenant users

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#12809]
### Description:
Even though the self signup is disabled for tenants, it's not honored when signing up tenants to tenant dev portals.

### Steps to reproduce
1. Create a tenant
2. Login to the carbon console and check the signup configuration file in /_system/governance/apimgt/applicationdata/sign-up-config.xml. The signup for tenants is disabled by default.
3. Signup a subscriber user to the tenant domain
4. Login to the tenant dev portal. You will be able to successfully login, even though the signup is disabled in the config.

**Comment by shnrndk** [comment]
Already fixed by the #https://github.com/wso2/carbon-apimgt/pull/11310
