### ISSUE TITLE
Forward Basic Authorization data from a service exposed in the api manager to a backend

### ISSUE THREAD

**Issue by cristianwso2** [wso2/product-apim#12804]
### Description:
The customer tells us that he tries to forward the basic authorization data from a service exposed in the api manager to a backend service and it cannot be done. It works fine for the OAuth case but not for the Basic Authorization case.
We have checked locally for both Vanilla and the latest version and had the same situation.

### Steps to reproduce:
Using this configuration:
[apim.oauth_config]
enable_outbound_auth_header = true

### Affected Product Version:
WSO2 AM 4.0.0

**Comment by chamilaadhi** [comment]
Hi
This issue is fixed in the 4.0.0 latest updated pack. Please follow [2] to update the product. The public fix related to this can be found in this duplicate issue[2]

[1] https://updates.docs.wso2.com/en/latest/updates/new-user/
[2] https://github.com/wso2/product-apim/issues/12843
