### ISSUE TITLE
upgradation of WSO2 from 3.2.0 to 4.0.0

### ISSUE THREAD

**Issue by Namratapaw** [wso2/product-apim#12802]
### Description:
I have upgraded wso2 from 3.2.0 to 4.0.0 after doing all steps properly, while testing the APIs I am getting error as requested resource not found. Also I am not getting any error in log.

### Affected Product Version:
4.0.0
### Environment details (with versions):
- OS: Linux

**Comment by Namratapaw** [comment]
Can anyone please guide me on this issue?

**Comment by OmerGafar** [comment]
Try to redeploy the API and make sure the gateway is checked.

**Comment by nandika** [comment]
Please contact our support team https://wso2.com/contact/?src=subscription.

Regards
Nandika
