### ISSUE TITLE
[UX]Revision deploy option is not available for API definition updates

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#12810]
### Steps to reproduce:
1. Create a REST API
2. Navigate to API definition tab
3. Import an API definition

<img width="912" alt="Screenshot 2022-03-31 at 01 12 39" src="https://user-images.githubusercontent.com/4471756/160917751-a9c927ba-4d9e-4822-a7b5-3f493337fda7.png">

4. Only an import option is provided. There is no option for revision deployment. 
<img width="567" alt="Screenshot 2022-03-31 at 01 13 41" src="https://user-images.githubusercontent.com/4471756/160918021-d7c85501-213a-45a7-b1d2-5661d16842a2.png">

**Comment by Krishanx92** [comment]
This is fixed in latest pack.
