### ISSUE TITLE
[Operational Policies] Incorrect validation for allowed special characters in header values

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#12811]
### Description:
When adding a new header, there is an unwanted validation in UI for allowed special characters. _ :;.,\/"'?!(){}[]@<>=-+*#$&`|~^%

<img width="422" alt="Screenshot 2022-03-31 at 01 37 13" src="https://user-images.githubusercontent.com/4471756/160922567-d0dc3c3c-cee9-4407-9813-80bb44b10228.png">

**Comment by Krishanx92** [comment]
@ashera96 @1akshitha Any reason to add this validation?

**Comment by ashera96** [comment]
We need to modify this validation
