### ISSUE TITLE
Changing the backend request payload data types if there is an Enrich mediator - [APIM 2.6.0]

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#12814]
### Description:
Changing the backend request payload data types if there is an Enrich mediator.

### Steps to reproduce:

- Create an API through the publisher portal.
- Add the mediation sequence to the IN flow with the below content.
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="SAMPLE_IN_SEQUENCE" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
	<enrich>
        <source clone="true" type="body"/>
        <target property="REQUEST_PAYLOAD" type="property"/>
    </enrich>
	
    <enrich>
        <source clone="true" property="REQUEST_PAYLOAD" type="property"/>
        <target type="body"/>
    </enrich>
    <payloadFactory media-type="json">
        <format>{"dataList": {"data": $1 }
        </format>
        <args>
            <arg evaluator="json" expression="$."/>
        </args>
    </payloadFactory>
</sequence>
```
- Publish the API.
- Subscribe to the API through the store portal.
- Invoke the API by parsing the below payload.
```
{
  "customerName": "testUser",
  "delivered": true,
  "creditCardNumber": "12345",
  "qty_in_number": 340979756,
  "qty_in_string": "340979756",
  "booleanKey":true
}
```

- In the backend call, able to see the payload is getting modified through the Enrich mediator. (numbers sending as string converted as numbers)

```
{
  "customerName": "testUser",
  "delivered": true,
  "creditCardNumber": 12345,
  "qty_in_number": 340979756,
  "qty_in_string": 340979756,
  "booleanKey": true
}
```

### Affected Product Version:
2.6.0

**Comment by HiranyaKavishani** [comment]
Public fix is already added with https://github.com/wso2/wso2-synapse/commit/2980444abe713db24d0e193c8ab04c8bd4aecf1c
