### ISSUE TITLE
Custom sequences cannot access subscribed application name

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#12825]
### Description:
When JWTTokenIssuer is set as token_generator and subscription_validation_via_km is enabled, not able to access the APPLICATION_NAME through message context

### Steps to reproduce:

- Add the below lines to the <APIM_HOME>/repository/conf/deployment.toml file.
```
[oauth.extensions]
token_generator = "org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer"

[apim.jwt_authenitcation]
subscription_validation_via_km = true
```

-  Import the public certificate of the key manager of JWT into the <GW_HOME>/repository/resources/security/client-truststore.jks under the alias of the kid in the JWT token.

- Create an API with the following In Sequence .
```
<log level="custom">
<property name="AppName" expression="$ctx:api.ut.application.name"/>
</log>
```

- Restart the server and invoke the API with a new JWT .

- AppName will be logged as null.

### Affected Product Version:
APIM 3.1.0

**Comment by dushaniw** [comment]
Need to add it to master - in progress
