### ISSUE TITLE
APIM-3.2.0 - Axis2 transport proxy configuration issue

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/product-apim#12828]
### Description:
Axis2 transport configuration was not reflected in axis2.xml after the deployment.toml configuration was done according to the official documentation[1].

### Steps to reproduce:

- Configure the Axis2 transport configuration as below in the deployment.toml.
```
[transport.passthru_http.sender]
http.proxyHost = "proxy.abcd.com"
http.proxyPort = 3128
http.nonProxyHosts = ".*.abc-ab.def|.*.abc.com"
```
- Start the server.
- Check the transport proxy configurations in the axis2.xml.

### Affected Product Version:
APIM-3.2.0

[1][https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/advance-configurations/changing-the-default-transport/#transport-sender-parameters](https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/advance-configurations/changing-the-default-transport/#transport-sender-parameters)

**Comment by dumindurox777** [comment]
Same issue is there in the APIM 4.0.0 too.

**Comment by shnrndk** [comment]
Use this configuration instead.

```
[transport.http.proxy_profile]
profile.proxy_host = "proxy.abcd.com"
profile.proxy_port = 3128
profile.bypass_hosts = ".*.abc-ab.def|.*.abc.com"
```
