### ISSUE TITLE
Error when retiring solace APIs with subscriptions

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#12838]
### Description:

- When retiring Solace APIs with subscriptions, the corresponding created applications are not get updated/deleted in Solace broker.

### Steps to reproduce:

1. Create and publish a Solace API
2. Create an application and subscribe to solace API.
3. Retire the solace API

### Affected Product Version:

- API Manager 4.1.0

**Comment by SavinduDimal** [comment]
Closing this issue as it is already fixed in the master branch
