### ISSUE TITLE
An Edit button appears when refreshing the API Definition page of an API Product

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#12836]
### Description:
An Edit button appears when refreshing the API Definition page of an API Product

### Steps to reproduce:
1. Create an API Product.
2. Go to the API Definition page. You can see that there is no edit option (which is expected)
    ![image](https://user-images.githubusercontent.com/25246848/160590799-215de6ee-f795-4cdc-baf4-5b9973cb87b5.png)
3. Now refresh the page. An edit button will appear.
    ![image](https://user-images.githubusercontent.com/25246848/160590926-1cb4671d-b951-42a8-9680-8ffd699cad13.png)
4. You can click on it and edit the definition. But when you click on "Update Content" button, it will keep spinning forever.
    ![image](https://user-images.githubusercontent.com/25246848/160591121-b37d7f06-0592-4420-8c71-79cde34ec6c6.png)

The solution is to stop displaying the edit button after a page refresh.

**Comment by Tharanidk** [comment]
Hi @wasuradananjith ,

The import definition button also appears after the refresh. Shall we remove that also?

Thanks,
Tharani

**Comment by wasuradananjith** [comment]
> Hi @wasuradananjith ,
> 
> The import definition button also appears after the refresh. Shall we remove that also?
> 
> Thanks, Tharani

Hi @Tharanidk,

+1. It will be more consistent then.

Thanks,
Wasura Wattearachchi
