### ISSUE TITLE
Missing Download of AsyncAPI option  in Developer Portal

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#12842]
### Describe your problem(s)

Need to support downloading swagger definitions from developer portal. 

![image](https://user-images.githubusercontent.com/60866295/162557655-23e56860-d4cb-4e2a-9501-4f3c8f29f618.png)

**Comment by piyumaldk** [comment]
Resolved by Carbon-apimgt[1] and APIM-Apps[2] PRs
[1] - https://github.com/wso2/carbon-apimgt/pull/11489
[2] - https://github.com/wso2/apim-apps/pull/339
