### ISSUE TITLE
Incorrect error response for WebSocket API authentication error for no access_token/Authorization bearer

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#12845]
### Description:
When invoking a websocket API in the API-Manager, getting 401 response if we do not provide the access token. 
```
wscat -n -c wss://localhost:8099/test/1
error: Unexpected server response: 401
```

However if we define the access_token param in the wscat as URL parameter, we are getting different error without returning the 401.
```
wscat -n -c wss://localhost:8099/test/1?access_token=
error: socket hang up
```

### Steps to reproduce:
1. Create a Websocket API
2. Invoke using wscat with access_token passed in params.

### Affected Product Version:
APIM 3.2.0

**Comment by chamilaadhi** [comment]
@msm1992 shall we close this issue?

**Comment by msm1992** [comment]
This issue is not reproducible in latest APIM pack, hence closing.
