### ISSUE TITLE
Visual bug with list of subscriptions in publisher

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#12848]
### Description:
Subscription filter is not working in the publisher, when "rows per page" is >=25. 

### Steps to reproduce:

- Start the APIM 3.2 pack and go to the Publisher.
- Create and publish an API.
- Go to the Devportal and create more than 10 APPs.
- Subscribe the API with all these APPs.
- Go to the publisher portal and list the subscription.
- Select the "rows per page" as 25.
- So you will be able to see only 10 Subscriptions. Please refer to the below image.
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/28176167/162740735-d4a6ceaf-57d6-4857-966c-28444d68ff1f.png">

### Affected Product Version:
APIM 3.2 latest U2 level (3.2.0.145 latest ATM)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chamilaadhi** [comment]
@chanaka3d shall we close this issue since fixes are merged to the public branch?

**Comment by chanaka3d** [comment]
Public fix is merged
