### ISSUE TITLE
Need a detailed error message in UI when updating an invalid API definition

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#12847]
### Description:
When updating the API definition from the publisher portal, if there is a validation issue, only a generic error message is shown in the UI in APIM 3.2.0. Need to check the carbon log for the exact error. In APIM 2.6.0 a detailed message is shown in the UI.

### Steps to reproduce:

- Create a sample API.

- Update the API definition with an invalid content.

- Only a generic UI error message is displayed.
![UI_3 2](https://user-images.githubusercontent.com/30709975/162723613-024ddbf8-47d2-4d14-b9a8-4fb0df499e31.png)

- In APIM 2.6.0 a detailed message is displayed.
![UI_2 6](https://user-images.githubusercontent.com/30709975/162723692-7bd2d5d6-3adc-48a0-87ec-8078eb529f6b.png)

### Affected Product Version:
APIM 3.2.0

**Comment by chamilaadhi** [comment]
@chanaka3d shall we close this issue since fixes are merged to the public branch?
