### ISSUE TITLE
Invalid policy gateway type when import an exported API from apictl

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#12857]
### Description:
$subject

### Steps to reproduce:
1. Create an API
2. Go to policies and switched to choreo connect
3. Add policies
4. Save and deploy
5. Export API `apictl export api -n Any -v v1 -e local-apim`
6. Delete the created API
7. Import save API`apictl import api -f ~/.wso2apictl/exported/apis/local-apim/Any_v1.zip -e local-apim -k`
8. Check policy tab -> gateway type is switched to regular gateway

### Affected Product Version:
APIM 4.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by shnrndk** [comment]
Already fixed
