### ISSUE TITLE
Access logs are not generated when using the ConfigurableLoggerAccessLogValve

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/product-apim#12853]
In APIM 4.0.0, access logs are not generated when using the ConfigurableLoggerAccessLogValve. One customer is trying to print the access logs in the wso2carbon.log but it does not work as expected.

Steps to reproduce:

1. Add the below configuration to the deployment.toml file.
[http_access_log]
useLogger = true
2. Restart the server and check whether the access logs are printed in the wso2carbon.log file. 

This has been mentioned in the documentation [1] as well. 

[1]- https://apim.docs.wso2.com/en/4.0.0/observe/api-manager/monitoring-http-access-logs/

**Comment by chamilaadhi** [comment]
Fixed with the doc update https://github.com/wso2/docs-apim/pull/6343
