### ISSUE TITLE
[APIM-4.0.0] Invalid username reference for TopicConnectionFactory url in jndi-cp.properties.j2

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#12865]
### Description:
Currently,  **jndi-cp.properties.j2** file is referring only the **apim.event_hub.username** as the username to construct the TopicConnectionFactory when some conditions are true. This will break the configuration if email user is enabled in the deployment.toml and also when event_hub configurations are applied(TM seperation use case)
It will result constructing the endpoint setting the username as **admin@wso2.com@carbon.super**
Ideally this value should be **admin!wso2.com!carbon.super** to be success with the configurations.
Hence we need to refer apim.throttling.jms.username instead.

### Steps to reproduce:

1. Configure APIM-4.0.0 with email-user enabled configs
2. Apply event_hub configurations.
3. Start the server and check  jndi-cp.properties file.

### Affected Product Version:
APIM-4.0.0

### Environment details (with versions):
N/A

**Comment by nandika** [comment]
duplicate
