### ISSUE TITLE
Advanced Endpoint Configuration Unable to Save

### ISSUE THREAD

**Issue by gVien** [wso2/product-apim#1327]
I'm currently test driving WSO2 API Manager 2.0.0. I'm trying to save changes to the `Advanced Endpoint Configuration` under step 2 of the API creation (from the publishing portal), but I'm not seeing the changes being saved. You can access the `Advanced Endpoint Configuration` by clicking the "setting" icon either in Production Endpoint row or Sandbox Endpoint row.

**Comment by harsha89** [comment]
We have done fixes to the latest code.
