### ISSUE TITLE
"pizza-shack-api" folder has gone missing

### ISSUE THREAD

**Issue by Wilson-Wong-Haxgon** [wso2/product-apim#1344]
The **<APIM_HOME>/samples/PizzaShack/pizza-shack-api** folder has gone missing since API Manager 2.0.0. Looks like the folder has gone missing in the master branch, but still exists in the 1.10.x branch. Please merge it back into master.

**Comment by harsha89** [comment]
It has moved to component repostiory carbon-apimgt
