### ISSUE TITLE
Couldn't edit the call back URL of an application, when that application shared among few users

### ISSUE THREAD

**Issue by Susankha** [wso2/product-apim#1360]
I have followed the below steps to reproduce the issue.

1) Configure the APIM to sharing the applications and subscriptions among the users by following the steps mentioned in document [1].
2) Signup two users (user1 and user2) into API store with same organization name.
3) Create an application via user1 and add a callback URL and generate the production key.
4) Sign in to the API Store via user2 and can see the created application in step 3.
5) Edit the application name, tier of the created application in step 3 (via user2) without any issue.
6) When I tried to edit the callback URL of the application, via user2, I could see the attached exception in API manager and due to that
   we can't edit the callback URL of the application via user2.

[1] - https://docs.wso2.com/display/AM200/Sharing+Applications+and+Subscriptions

**Comment by harsha89** [comment]
We have revamped this feature and shared user can't edit the application. We have added change owner API to move the ownership
