### ISSUE TITLE
Sample API: Cannot subscribe to PizzaShackAPI - 1.0.0 

### ISSUE THREAD

**Issue by NimmiW** [wso2/product-apim#1362]
![image](https://cloud.githubusercontent.com/assets/26009680/24585103/d20645ec-179f-11e7-88cf-190d62d5cd2f.png)

When I hit subscribe, it gives the following erorror message.

![image](https://cloud.githubusercontent.com/assets/26009680/24585114/ffd534b0-179f-11e7-81b3-d43e0c6e210f.png)

What Can I do for that? I am a beginner for API manager.

**Comment by rswijesena** [comment]
Hi Nimmi,

You should select an application before subscribing. 

Please go through our quick start guide.

https://docs.wso2.com/display/AM210/Quick+Start+Guide

Regards

**Comment by harsha89** [comment]
Answered hence resolving
