### ISSUE TITLE
Providing support for changing application owner in APIM

### ISSUE THREAD

**Issue by chamarasilva** [wso2/product-apim#1369]
In APIM 2.0.0 does not have a support to move application owner after creates the application. As per the use case, there should be a way to change existing application owner at least via the super admin or person who having admin privileges. Currently, there are two workarounds to achieve this.
1. adding same "organization" claim group to multiple users and then uses can share the subscription.

2. change the application owner in DB level.

But it is good to have feature support from UI level.

Thanks,
Chamara Silva

**Comment by dushaniw** [comment]
Available now as a feature in the latest version. https://docs.wso2.com/display/AM260/Changing+the+Owner+of+an+Application.
