### ISSUE TITLE
Delete buttons are not working in Parameters of API definition (script error)

### ISSUE THREAD

**Issue by qwefgh90** [wso2/product-apim#1385]
### Environment
**Product:** wso2am-2.1.0 (for Windows x64)
**Access URL (in local):** https://localhost:9443/publisher/design?name=WorldBank&version=1.0.0&provider=admin

### Description
Script error occurs when clicking delete buttons in Parameters panel.
Although objects and parameters are assigned and they are verified in Chrome Inspector, It can not read property. I have attached two screenshots on this issue. 

![when clicked delete button2](https://cloud.githubusercontent.com/assets/7572251/26334682/be4d1dbc-3fa1-11e7-998d-49553402f52a.PNG)

![when clicked delete button](https://cloud.githubusercontent.com/assets/7572251/26334331/47f120b6-3f9f-11e7-9293-e75824cb5d9c.PNG)

**Comment by harsha89** [comment]
Please check the latest version this should be fixed.
