### ISSUE TITLE
Secondary UserStore users cannot login to admin-dashboard using the username

### ISSUE THREAD

**Issue by daneshk** [wso2/product-apim#1451]
Please find the below steps to recreate the issue.

* Add secondary user store(wso2.com) to apim server
* Create new role giving the permission to access admin dashboard.
* Create new user(testuser) in secondary user store and assign the role to the user.
* Try to logging to the system with new user credentials.

Expected Behaviour: user should be able to login, since he has required permissions.

Actual Behaviour: 
user cannot login to the admin dashboard with,

> username =  testuser

but he can login with with the domain id as below,

> username = WSO2.COM/testuser

**Comment by msm1992** [comment]
Duplicate issue https://wso2.org/jira/browse/APIMANAGER-5172. This has been already resolved.

**Comment by dewmini** [comment]
Closing the issue as per above comment.
