### ISSUE TITLE
Open redirect in redirect.gag

### ISSUE THREAD

**Issue by akoshcheyev** [wso2/product-apim#1464]
We get open redirect on APIM_HOME/repository/deployment/store/site/themes/wso2/templates/user/sign-up/redirector.jag
https://localhost:9443/store/site/themes/wso2/templates/user/sign-up/redirector.jag?redirectToHome=http%3A%2F%2F1432024300%2Fa%3F%2Fstore&tenant=null
API Manager 2.1.0
Can I make only context redirects (like a /store/somewhere) or restrict them to a domain name(s)?

**Comment by sambaheerathan** [comment]
This is already fixed https://github.com/sambaheerathan/carbon-
apimgt/commit/5d0eada2566a3b7dde1db5a50c1127301cfee12c
