### ISSUE TITLE
Cannot secure passwords in api-manager.xml

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-apim#1468]
As per the current implementation <DASPassword> cannot be secured via secure vault. I believe this true for all the other passwords given in api-manager.xml

There is no guarantee that the external Analytics/DAS usages the same credentials as "admin:admin". Specifying it as the placeholder "${admin.password}" will not work all the time. 

Hence it is needed to fix the places where it reads the api-manager.xml configuration to use the secure vault and properly resolve the passwords.

**Comment by chamilaadhi** [comment]
With the new config model in APIM 3.0.0 all the configurations are moved to a single file and secure vault is supported for all the passwords.
