### ISSUE TITLE
Change /policies/{tierLevel} resource in the Publisher API to /policies/{type}?level={level}

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#1469]
The current resource to retrieve rate limiting policies on the publisher API is as /policies/{tierLevel}. Examples are /policies/api, /policies/subscriptions, etc. This resource has been designed to support rate limiting policies only. If later we introduce policies of other types, such as threat protection policies we will not be able to use this resource. In order for the resource to be future compatible, I suggest that we change this resource to /policies/{level}.

Example to query rate limiting policies by API would then be like /policies/rate_limits?level=api

**Comment by chamilaadhi** [comment]
With new Rest API version for APIM 3.0.0 , a separate resource is introduced for throttling (ex: /throttling/policies/application ). 

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml#L112
[2] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml#L390
