### ISSUE TITLE
[C5][Publisher][UI] Error(415) while creating an API

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1471]
Get HTTP 415 **Unsupported Media Type** error when creating an API and updating policies. Regression issue caused by Upgrading SwaggerClient JS library migration.

![error](https://user-images.githubusercontent.com/3313885/28771435-6bfaafa8-7600-11e7-9336-bfc76c23c6f8.png)

**Comment by nuwand** [comment]
This issue is specific to Google Chrome only. It works fine on Firefox.

**Comment by tmkasun** [comment]
As I found this issue is caused by not using case insensitive HTTP headers when building the AJAX request by [Swagger-JS](https://github.com/swagger-api/swagger-js) library
As per [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2.2)
> A sender MUST NOT generate multiple header fields with the same field
>    name in a message unless either the entire field value for that
>    header field is defined as a comma-separated list [i.e., #(values)]
>    or the header field is a well-known exception (as noted below).

In chrome it handles the multiple headers with the same name(case insensitive), by concatenating each with commas but in FF case, it overrides the previous value with latest, which makes it works in FF but not in chrome. 

> Each header field consists of a case-insensitive field name followed
> by a colon (":"), optional leading whitespace, the field value, and
>    optional trailing whitespace.

https://tools.ietf.org/html/rfc7230#section-3.2

[Here](https://github.com/swagger-api/swagger-js/blob/master/src/execute.js#L142-L157) Swagger-JS has used lower case `content-type` header name,

```javascript
if (req.body || req.form) {
    if (requestContentType) {
      req.headers['content-type'] = requestContentType
    }
    else if (Array.isArray(operation.consumes)) {
      req.headers['content-type'] = operation.consumes[0]
    }
    else if (Array.isArray(spec.consumes)) {
      req.headers['content-type'] = spec.consumes[0]
    }
    else if (operation.parameters.filter(p => p.type === 'file').length) {
      req.headers['content-type'] = 'multipart/form-data'
    }
    else if (operation.parameters.filter(p => p.in === 'formData').length) {
      req.headers['content-type'] = 'application/x-www-form-urlencoded'
    }
```


should make the [following](https://github.com/swagger-api/swagger-js/blob/master/src/execute.js#L188) case insensitive 

```javascript
export function headerBuilder({req, parameter, value}) {
  req.headers = req.headers || {}
  if (typeof value !== 'undefined') {
    req.headers[parameter.name] = value
  }
}
```

Because of above `headerBuilder` behavior, From our [spec](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml#L242) `Content-Type` header name comes with capitalized naming, making it adding two Content-Type headers treating tow ways in Chrome and FF.

**Comment by malinthaprasan** [comment]
Looks like we have also done a mistake :(.

According to the [spec](https://swagger.io/specification/) we do not need to specify Content-Type parameter in our swagger definitions.

> If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.

Removing those from the swagger definitions will also fix the issue.
