### ISSUE TITLE
Error when loading a swagger definition file to create an API

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-apim#1490]
There is an error when attaching a swagger definition file (yaml or json) to create a new API in publisher. It works when the same file is attached several times.
Error:
`[2017-08-14 10:36:14,876] ERROR {org.wso2.carbon.kernel.internal.configprovider.ConfigProviderImpl} - configuration doesn't exist for the namespace: wso2.carbon.apimgt.publisher.rest.api in deployment yaml. Hence return null object`

Please refer the attached screenshot.
![error_adding swagger api json file](https://user-images.githubusercontent.com/16064696/29259088-0994214a-80dd-11e7-9ce9-d5ae1ff27adb.png)

**Comment by vlgunarathne** [comment]
![screenshot from 2017-08-14 11-47-49](https://user-images.githubusercontent.com/16064696/29260284-80c77452-80e6-11e7-9211-ddcdb821d91d.png)

**Comment by tgtshanika** [comment]
This issue cannot be reproduced with APIM 3.0.0
