### ISSUE TITLE
Store UI issue when generating the production keys using the client credentials after trying to generate the access token using the password grant type

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-apim#1511]
The client key and secret should be visible to the user after the user re-enables/selects client credentials (after first trying to generate the access token with the password grant type), but here the user has to give a page refresh in order to view the client key and secret. 

This issue can be reproduced by following the steps given below: 

1. Created a new application in Store.
2. Generate Keys with only Password Grant Type selected 
3. Error shown since user credentials is not selected
4. Re-enable/Select  Client Credentials, same error message is given and the Client Key and Secret is not visible.
5. Navigate to some other page and come back to the application again or refresh the page, the Client Key and Secret now is visible
![wso2_4](https://user-images.githubusercontent.com/13446645/29698875-57cc6010-8976-11e7-88d5-fb92b52aeeb7.png)

**Comment by chamilaadhi** [comment]
Fixed in 2.6.0 . Error is not generated and re-generated button is disabled till clien-credentials is selected
