### ISSUE TITLE
unlimited tier will still get throttle to sixty call a seconds.

### ISSUE THREAD

**Issue by simonpie** [wso2/product-apim#1512]
Hello,

I have the same problem as the gentlement on this website [https://stackoverflow.com/questions/35726600/unlimited-quota-for-unauthenticated-api](url).  I did follow the instructions from the answer.  That is, I modified all three tiers.xml file in the registry using the carbon console.  I restarted and verified that the settings were kept.  

Yet, an api which is published as public, unlimited will still be throttled to 60 calls by minute.

Any one as any idea ?

**Comment by harsha89** [comment]
We have set it to 500 per minute. You can change it from the admin dashboard. We switched to new throttling from 2.0.0

![image](https://user-images.githubusercontent.com/1561366/64592752-55ed9980-d3ca-11e9-901b-2f45538c243d.png)
