### ISSUE TITLE
Improvement to SAML bearer grant type to facilitate skipping user role validation

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#1513]
More details https://wso2.org/jira/browse/APIMANAGER-5831

**Comment by chamilaadhi** [comment]
Fix mentioned in the above JIRA can be found in the lates carbon-apimgt code. This is fixed in the latest APIM versions.

**Comment by Pushpalanka** [comment]
Do we this same fix for JWT bearer grant as well?
