### ISSUE TITLE
Implement "Search by Tags" in API Publisher

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#1522]
It would be better if we can consider this in our roadmap for future releases.

**Comment by SwatiNEC** [comment]
This feature is already available in API publisher. But this option is not mentioned in "search options of API". Please find the below image for the same.
![api_publisher](https://user-images.githubusercontent.com/38689838/50392956-a6f42980-0778-11e9-95c4-7077d958a014.png)

**Comment by SwatiNEC** [comment]
There is no need to add the same in API Manager as there is no "Tags" attribute while publishing the API. So this issue should be closed.

**Comment by chamilaadhi** [comment]
Tag search is provided in APIM 2.6.0 and also supported in APIM 3.0.0
