### ISSUE TITLE
Thumbnail URL should be returned with the get All APIs

### ISSUE THREAD

**Issue by chaturadilan** [wso2/product-apim#1524]
When retrieving APIs [1] thumbnail URLs should be returned with the result in APIM 2.0. This helps to show the thumbnail image with the APIs without doing additional HTTP calls to get thumbnail images.

[1] - https://docs.wso2.com/display/AM180/Publisher+APIs#PublisherAPIs-GetAllAPIs

**Comment by chamilaadhi** [comment]
This was fixed in the latest wum updated pack for AM 2.1.0 and will be in the AM 2.1.0-update5. API thumbnail url is in the APIInfo object . see below

https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#APIInfo
https://docs.wso2.com/display/AM210/apidocs/store/#!/models#APIInfo
