### ISSUE TITLE
Provide Profile Management Feature in API Manager to Manage OAuth tokens belong to user

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#1534]
With the current implementation, we cant do it because if we need to revoke access token then we should have a consumer key and secret key (which are specific to application). Usually, these key/secret embedded with the application and the end user cannot see it. As I see this is kind of limitation in OAuth implementation when token generation handled by the client application(not actual end users).
The only option we have now is to install full identity server and use APIM features on top of that(or use IS as key manager). Also in such cases, we can disable refresh grant to avoid app generating tokens on behalf of the user without his credentials.
Another solution is to use OAuth soap services and revoke tokens by logged in user. But to do this we need to implement custom web application and call soap services
I believe we need to add this feature to API Manager store profile management feature. At anytime user should be able to see what applications generated tokens on behalf of him. And he should be able to revoke them if he needs.
Also, there are some requests asking support for admin users to revoke tokens in case user complains about token misuse. API Manager admin dashboard would be an ideal place to do that. Then the admin can login to the system, list users and list applications generate by those users. And revoke tokens if users requested.
Shall we evaluate these requests and consider for future implementation. This requirement is more about end users who use application. 

Improvment suggested by Sanjeewa Malagoda - https://wso2.org/jira/browse/APIMANAGER-5220

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
