### ISSUE TITLE
Store and return audit meta data for artifacts that are created or modified via published API calls

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#1536]
It would be useful to add the following audit meta data fields to applicable artifacts that are created or modified via published API calls.

createdBy (user ID of user who created the item)
modifiedBy (userID of user who most recently modified the item)
createdAt (ISO8601 Timestamp)
lastModified (ISO8601 Timestamp)

Refer : https://wso2.org/jira/browse/APIMANAGER-3951

**Comment by chamilaadhi** [comment]
This information is sent from the rest API in AM 3.0.0 (This is verified with AM 3.0.0 9th September 2019 build)
