### ISSUE TITLE
Add validation for tiers associate with an API,before it published

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1540]
Created to track $subject. refer [1]

When publish an API and when subscribe at APIStore,it's required to have a subscription tier associate with the API.Better to add a logic to check if that API is already set atleast one tier,if not ask to update the tier,before publish the API.

[1] https://wso2.org/jira/browse/APIMANAGER-5630

**Comment by chamilaadhi** [comment]
This is the default behavior. Unless a tier is selected, we do not allow to publish the API. (UI validation is done)
