### ISSUE TITLE
Move Default tier data from code to sql script

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1541]
Created to track $subject [1]

Currently, default tier are populated to database from source code. Have to move them to SQL file.

[1] https://wso2.org/jira/browse/APIMANAGER-5626

**Comment by chamilaadhi** [comment]
There is no specific reason to move them to the database. These policies are provided as sample policies. If someone needs to change these values, they can use create new policies or use the rest apis/UI to update them once the pack is started
