### ISSUE TITLE
Store listing layout breaks for long API names

### ISSUE THREAD

**Issue by thusithak** [wso2/product-apim#1542]
long API names breaks the layout In all of APIM Store's listings.

![api_names](https://user-images.githubusercontent.com/11048376/29960970-67e85cce-8f1b-11e7-8a82-05fc95975dac.png)

Also related to the issue raised at https://github.com/wso2/product-iots/issues/1156

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4488
The names will be truncated when exceeding the bounding box and replaced with an ellipsis.

Full text will be visible on hover
<img width="851" alt="screen shot 2017-09-01 at 13 59 05" src="https://user-images.githubusercontent.com/11048376/29962300-6b972580-8f20-11e7-933b-a13ac06d0d9b.png">

Also fixed for prototyped and history API listing.
<img width="764" alt="screen shot 2017-09-01 at 13 57 47" src="https://user-images.githubusercontent.com/11048376/29962314-74056c86-8f20-11e7-9ec8-c79f51c12aae.png">

**Comment by malinthaprasan** [comment]
Closed as the PR is merged
