### ISSUE TITLE
Need a way to add custom headers to API console for SOAP APIs

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#1543]
Currently there is no way to add custom headers which required for back SOAP endpoints (for example, Authorization headers for WSO2 Admin APIs).
Need to find a way to add these in API Console.

Refer: https://wso2.org/jira/browse/APIMANAGER-4026

**Comment by chamilaadhi** [comment]
API Manager 2.6.0 has an improved wsdl import feature which can be used to Generate REST APIs using the wsdl file. Using this, you could add headers.
