### ISSUE TITLE
Ability to specify endpoint security separately for prod & sandbox endpoints

### ISSUE THREAD

**Issue by lakmali** [wso2/product-apim#1547]
When implementing endpoint security option in UI, it should allow specifying that separately for production and sandbox endpoints.

Refer : https://wso2.org/jira/browse/APIMANAGER-5743

**Comment by msm1992** [comment]
This has been implemented in api manager 3.0.0
![screenshot from 2018-01-25 12-40-30](https://user-images.githubusercontent.com/28379317/35377481-5988c5ba-01d5-11e8-9685-0d9eecc113ee.png)

**Comment by markokocic** [comment]
This was tagged for 3.0.0 release, but it's still not done.

Any plans to implement in one of the updates?

**Comment by dushansilva** [comment]
Hi @markokocic,
We plan to implement this for the up coming 3.1.0 Release
