### ISSUE TITLE
Storing arbitrary values for API application via Store UI

### ISSUE THREAD

**Issue by anuruddhal** [wso2/product-apim#1564]
From APIM Store-UI user should be able to store arbitrary values(key value pairs) for api application which can be used in any use-case. 

eg: In JWT token generation, values can be taken directly from the stored values in application.
Values should be entered as key value pairs, json or xml formats can be considered.

**Comment by HiranyaKavishani** [comment]
Close the issue as this feature has been already available after the 2.5.0 version and it can provide a set of custom attributes while creating an application.
More: https://docs.wso2.com/display/AM250/Add+Custom+Attributes+to+Applications
