### ISSUE TITLE
OpenAPI (Swagger) 3.0 Suupport

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#1568]

**Comment by girishchawla** [comment]
Hello: When is this expected to be done ? Our team does wants to use Swagger 3.0

**Comment by harsha89** [comment]
We will at this with our 3.0.0 release

**Comment by Fabriciu** [comment]
Hi guys. Please, can you tell me if WSO2 API Manager 2.1 supports OpenAPI/Swagger 3.0 specification? Thank you!

**Comment by dmr41** [comment]
Same here.  Any updates on a release schedule for OpenAPI support?

**Comment by ldipotetjob** [comment]
Even WSO2 API Manager 2.2 do not supports OpenAPI/Swagger 3.0 specification. So how is possible that we need to go back to swagger spec 2.0.

**Comment by pubudu538** [comment]
Newly released APIM 2.2.0 supports OpenAPI v2 and v3. Please refer - https://docs.wso2.com/display/AM220/Edit+and+Consume+APIs+using+Swagger+Tools

**Comment by ldipotetjob** [comment]
"Client side SDK generation feature is currently not available for APIs in OpenAPI 3.0 specification this is when you try with an existing api importing a yaml file from WSO2. Other different thing is when you try to create e new Api,

**Comment by ldipotetjob** [comment]
Client side SDK generation feature is currently STILL available for APIs in OpenAPI 3.0 specification when you try with an existing api importing a yaml file from WSO2. Only for new apis. Any news about this upgrade ??

**Comment by tomvesely** [comment]
hi, we are having issue with minor version OpenAPI v3.0.1 which is automaticaly generated, but APIM 2.2 and 2.5 is not consuming it. anyone has similar issue anyone solved it ?
err>Unsupported OpenAPI version provided. Please re-import with OpenAPI 3.0.0

**Comment by charithadeshapriya** [comment]
The Open Banking specification for Berlin (version 1.3.0) is also provided in the format of open API v3.0.1 and the OB team is also facing the same issue (error - Unsupported OpenAPI version provided. Please re-import with OpenAPI 3.0.0) while importing the API. Does anyone know any workaround if the product support is still not available for version 3.0.1?

**Comment by praminda** [comment]
Issue related to OAS 3.0.1 will be tracked with #3575.
