### ISSUE TITLE
securityDefinitions, basepath, host, schemes attributes are missing when using store rest APIs.  

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-apim#1573]
Following attributes missing when invoking store rest APIs. 

"securityDefinitions": {
		"default": {
			"type": "oauth2",
			"authorizationUrl": "https://172.19.0.1:8243/authorize",
			"flow": "implicit",
			"scopes": {
				"test": "test"
			}
		}
	},
	"basePath": "/test/1.0.0",
	"host": "172.19.0.1:8243",
	"schemes": ["https", "http"]

**Comment by dushaniw** [comment]
Cannot reproduce with 3.2.0 release or latest build. The above details are received in the OpenAPI definition, GET /apis/{apiId}/swagger. Hence closing.
