### ISSUE TITLE
[Publisher]Some methods return void in java client generated through swagger 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1575]
**Steps to re-create**
1. Generate java client for [publisher.yaml](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) through swagger/command line.

2. Verify following methods. 

_**Expected:**_ Following methods needs to return an api response. 
_**Actual:**_ They return a void instead. 

**Class:** 
tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/api/ApiCollection

**methods**

- public void apisHead(String query, String ifNoneMatch)

**Class:** 
tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/api/APIIndividualApi

**methods:**

- public void apisApiIdSwaggerGet(String apiId, String ifNoneMatch, String ifModifiedSince)
- public void apisApiIdSwaggerPut(String apiId, String endpointId, String ifMatch, String ifUnmodifiedSince)
- public void apisApiIdThumbnailGet(String apiId, String ifNoneMatch, String ifModifiedSince)
- public FileInfo apisApiIdThumbnailPost(String apiId, File file, String ifMatch, String ifUnmodifiedSince)
- public void apisApiIdWsdlGet(String apiId, String ifNoneMatch, String ifModifiedSince)
- public void apisApiIdWsdlPut(String apiId, File file, String ifMatch, String ifUnmodifiedSince)
- public void apisCopyApiPost(String newVersion, String apiId)
- public void apisApiIdLifecycleHistoryGet(String apiId, String ifNoneMatch, String ifModifiedSince)
- public void apisApiIdGatewayConfigGet(String apiId, String ifNoneMatch, String ifModifiedSince)
- public void apisApiIdGatewayConfigPut(String apiId, String gatewayConfig, String ifMatch, String ifUnmodifiedSince)
- public void apisApiIdDelete(String apiId, String ifMatch, String ifUnmodifiedSince)

**Class:**
tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/api/DocumentIndividualApi

**Methods:**

- public void apisApiIdDocumentsDocumentIdContentGet(String apiId, String documentId, String ifNoneMatch, String ifModifiedSince)
- public void apisApiIdDocumentsDocumentIdDelete(String apiId, String documentId, String ifMatch, String ifUnmodifiedSince)

**Class:**
tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/api/EndpointCollectionApi

**Method:**

- public void endpointsHead(String name, String ifNoneMatch)

**Class:**
tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/api/EndpointIndividualApi

**Method:**

- public void endpointsEndpointIdDelete(String endpointId, String ifMatch, String ifUnmodifiedSince)

**Comment by uvindra** [comment]
The **schema** attribute should be defined for these GET methods in swagger yaml to fix this issue

For example in the case of returning a string value, schema should be defined as follows

```yaml     
responses:
        200:
          description: OK
          schema:
            type: string
```
