### ISSUE TITLE
Multiple security elements for REST resources in APIM Store and Publisher

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-apim#1580]
This is a follow up to the issue [Multiple scopes for REST resources in APIM Store and Publisher](https://github.com/wso2/product-apim/issues/1579). The above issue is about multiple scopes for a single security element in a REST resource.
But according to the image[1] swagger also allows to have multiple security elements and under each security element they can have multiple scopes.

[1] Swagger Petstore 
![petstoreswagger](https://user-images.githubusercontent.com/16064696/30469953-6984e296-9a10-11e7-968a-56b175f018e1.png)

**Comment by dushaniw** [comment]
tagging https://github.com/wso2/product-apim/issues/7292

**Comment by dushaniw** [comment]
Will keep this track with https://github.com/wso2/product-apim/issues/7292
