### ISSUE TITLE
Fix pull requests comments on email notification feature

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#1584]

**Comment by harsha89** [comment]
@Krishanx92 please note :+1:

**Comment by krishanthasamaraweera** [comment]
@harsha89 seems you have assigned this to the wrong Krishantha:)

**Comment by harsha89** [comment]
@krishanthasamaraweera yes I already made the change :+1: Sorry for that.

**Comment by Krishanx92** [comment]
@harsha89   Done.
https://github.com/wso2/carbon-apimgt/pull/4537

**Comment by harsha89** [comment]
Thanks :+1:
