### ISSUE TITLE
API POST method returning "no response from server" from API console when we pass parameters with out body in multiple tenant mode

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#1592]
1. create an api with a POST method that accepts two query parameters, a custom header and return the second one as the response. (add the custom header name to supported headers field in CORS)
2. open the api xml file in synaps-cofigs folder and add <property name="DISABLE_CHUNKING" value="true" scope="axis2"/> to <inSequence> element of the POST resource.
3. create a tenant user and subscribe to the api, try to invoke the post method.
4. request will time out returning a 'no response from server'

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/carbon-kernel/commit/065ede107e2ee86c71bc194f75e554fb406bf12f and https://github.com/wso2/wso2-synapse/commit/dd45e379dada9797a45198d12dd9ac8e14075ad0
