### ISSUE TITLE
Preflight OPTIONS calls can give invalid Access-Control-Allow-Methods when there are overriding resources defined

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1593]
Steps to reproduce:

1. Create an API with below two resources and publish it.
```
GET /business-parties/{bpGuid}/{bpType}
PUT /business-parties/{patientGuid}/manufacturers
```

2. Login to store and send the below mentioned request to the API using the swagger console.
`PUT /business-parties/AABBCCDD/manufacturers`

The request will fail and below error appears in the browser's console 
`XMLHttpRequest cannot load https://10.100.22.33:8243/api1/v1.0/business-parties/AABBCCDD/manufacturers. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
`

**Comment by malinthaprasan** [comment]
The reason is that [CORSRequestHandler](https://github.com/wso2/carbon-apimgt/blob/v6.1.66/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java#L131-L134) does not differentiate GET /business-parties/{bpGuid}/{bpType}
and PUT /business-parties/{patientGuid}/manufacturers as it does not consider about the Acess-Control-Request-Methods header which indicates the server which HTTP method will be used when the actual request is made. It will only consider the resource path during preflight OPTIONS calls.

**Comment by bhathiya** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/4871/commits/7188533919c8ffa40b2f1d658aea3b42f20c3503
