### ISSUE TITLE
problem accessing https://localhost:9292/publisher

### ISSUE THREAD

**Issue by Dougliao** [wso2/product-apim#1594]
After wso2apim-3.0.0-m6 is started, access to the publisher stuck in error message 

              Please wait while initializing . . . 

Access to https://localhost:9292/store is ok.

Does anyone encountered the same and is there anyway to fix it?

**Comment by Dougliao** [comment]
Below are the versions of the components that are running on my sandbox:
==================
apache-activemq-5.14.0
wso2is-5.3.0
wso2apim-das-v3.0.0-m3
wso2apim-3.0.0-m6
wso2apim-gateway-v3.0.0-m3

**Comment by pubudu538** [comment]
Hi Dougliao,

Do you see any errors in the server log? Could you please check the console in the browser to see if there are any issues?

Thank you!
Pubudu.

**Comment by Dougliao** [comment]
Pubudu,

I did not see meaningful entry in the am log file, see attached.


Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>

**Comment by pubudu538** [comment]
Hi Dougliao,

Looks like you have missed to attach the log file. We have fixed some of the issues found in M6 [1] while accessing the publisher and store apps.

We have released the M7 [2] today. Please let us know if you find any issues in the latest.

[1] - https://github.com/wso2/product-apim/issues/1604
[2] - https://github.com/wso2/product-apim/releases/tag/v3.0.0-m7

Thank you!
Pubudu.

**Comment by Dougliao** [comment]
I will give it a try. Thank you.


Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>

**Comment by Dougliao** [comment]
Pubudu,

Can you please check that the following folder is empty in wso2apim-gateway-3.0.0-m7:

wso2apim-gateway-3.0.0-m7\org\wso2\carbon\apimgt\gateway


Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>
