### ISSUE TITLE
"Scope already assigned" when trying to attach a scope for a newly created version which already has scopes

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1595]
1. Create an API using below swagger.
`{
   "swagger":"2.0",
   "paths":{
      "/abc":{
         "get":{
            "responses":{
               "200":{
                  "description":""
               }
            }
         }
      }
   },
   "info":{
      "title":"dev1_ms_subjects",
      "version":"v1.0"
   }
}`

2. Attach a scope "read_abc" to the resource and save the API.
3. Create a new version.
4. Go to the Manage tab, we can see the "read_abc" scope is still there without an issue.
4. Update the swagger of the API for that using below using Import button in the design tab. 
`{
   "swagger":"2.0",
   "paths":{
      "/abc":{
         "get":{
            "responses":{
               "200":{
                  "description":""
               }
            }
         }
      },
      "/pqr":{
         "get":{
            "responses":{
               "200":{
                  "description":""
               }
            }
         }
      }
   },
   "info":{
      "title":"dev1_ms_subjects",
      "version":"v1.0"
   }
}`

5. Now when we go to the manage tab, the previous scope "read_abc" will be cleared as we imported a new swagger. Now try to add that scope again to the API.

We will get "Scope already assigned" and we will not be allowed to add the scope again.

**Comment by prasa7** [comment]
Not reproducible in 2.1.0 and in the latest version 3.2.0 as well.
