### ISSUE TITLE
org.apache.http.message.BasicHttpRequest cannot be cast to org.apache.http.message.BasicHttpEntityEnclosingRequest exception on empty PUT request with Content-Type:octet-stream

### ISSUE THREAD

**Issue by Kanishka7** [wso2/product-apim#1608]
**java.lang.ClassCastException: org.apache.http.message.BasicHttpRequest cannot be cast to org.apache.http.message.BasicHttpEntityEnclosingRequest
        at org.apache.synapse.transport.passthru.TargetRequest.processChunking(TargetRequest.java:327)
        at org.apache.synapse.transport.passthru.TargetRequest.start(TargetRequest.java:267)
        at org.apache.synapse.transport.passthru.TargetHandler.requestReady(TargetHandler.java:169)**

This happens in WSO2-APIM-2.1.0 when a PUT request is made without a payload with Content-type:octet-stream. To reproduce , adding the property DISABLE_CHUNKING=true in Synapse in-sequence of Api would do.

**Environment**:
wso2apim-2.1.0

**Reproduce steps:**
Add property name="DISABLE_CHUNKING" value="true" scope="axis2"
to the in-sequence of  Api. And make a PUT request without a payload with Content-Type:application/octet-stream.

**Actual:**
Down cast Exception would occur.

**Expected:**

A valid response from the backend with a status code

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/wso2-synapse/pull/1054
