### ISSUE TITLE
Issue with wso2apim-gateway-3.0.0-m7.zip

### ISSUE THREAD

**Issue by Dougliao** [wso2/product-apim#1609]
With m7 release the gateway can't be started due to content in org/wso2/carbon/apimgt/gateway directory are missing:

===========
[dliao@vmdevapi2 gateway]$ pwd
/opt/wso2apim-gateway-3.0.0-m7/org/wso2/carbon/apimgt/gateway
[dliao@vmdevapi2 gateway]$ ls
[dliao@vmdevapi2 gateway]$

**Comment by harsha89** [comment]
@Dougliao please follow the steps mention in thehttps://github.com/wso2/product-apim readme.

**Comment by harsha89** [comment]
![screen](https://user-images.githubusercontent.com/1561366/30779201-a7bee48c-a107-11e7-9f47-8d501b8d5910.png)

**Comment by Dougliao** [comment]
Harsha,

I followed the build instruction and the build failed with dependency errors, will try to pull the source and rebuild.

Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>

**Comment by Dougliao** [comment]
Here is build error:

Downloading: http://maven.wso2.org/nexus/content/groups/wso2-public/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0
.7.9.pom
Downloading: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9.pom (3.5 kB at
22 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] apimgt-gateway-modules ............................. SUCCESS [42:18 min]
[INFO] Ballerina Native Features for API Manager - Parent . FAILURE [20:01 min]
[INFO] APIM Ballerina plugin .............................. SKIPPED
[INFO] Ballerina Native Features for API Manager - Parent . SKIPPED
[INFO] APIM Ballerina Configs ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 h
[INFO] Finished at: 2017-09-26T10:27:00-04:00
[INFO] Final Memory: 32M/323M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.wso2.carbon.apimgt.ballerina.native: Could not resolve dependencies for pr
oject org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.ballerina.native:jar:7.0.43-SNAPSHOT: Failed to collect dependencies
at org.ballerinalang:ballerina-core:jar:0.89: Failed to read artifact descriptor for org.ballerinalang:ballerina-core:j
ar:0.89: Could not transfer artifact org.ballerinalang:ballerina-core:pom:0.89 from/to wso2.releases (http://maven.wso2.
org/nexus/content/repositories/releases/): Connect to maven.wso2.org:80 [maven.wso2.org/52.220.154.241] failed: Connecti
on timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.wso2.carbon.apimgt.ballerina.native

C:\Tools\wso2_v3_source\carbon-apimgt-master\gateway-modules>




Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>

**Comment by malinthaprasan** [comment]
@Dougliao Seems like a connection timeout issue while fetching a jar file from nexus.. are you getting this all the time?

Can you access this jar? 
http://maven.wso2.org/nexus/content/repositories/releases/org/ballerinalang/ballerina-core/0.89/ballerina-core-0.89.jar

{code}
 Could not transfer artifact org.ballerinalang:ballerina-core:pom:0.89 from/to wso2.releases (http://maven.wso2.
org/nexus/content/repositories/releases/): Connect to maven.wso2.org:80 [maven.wso2.org/52.220.154.241] failed: Connecti
on timed out: connect -> [Help 1]
{code}

**Comment by Dougliao** [comment]
Do you have any idea when is the next milestone release?

Thanks,
Doug Liao
Mortgage Web Services Development
Black Knight Financial Services
O: 904-854-5613 | M: 904-881-1156 | Email: doug.liao@bkfs.com<mailto:doug.liao@bkfs.com>
