### ISSUE TITLE
Optimize Database queries to use INSERT with SELECT

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#1613]
In situations where data belonging to a given entity is sperad out over multiple tables due to data normalization, we need to write INSERT with SELECT SQL for populating DB tables to avoid mutiple DB queries being written.

For example, the AM_API table has a column called API_TYPE_ID which is a foreign key on the AM_API_TYPES table. When we add a new API to the AM_API we simply specify the type of the API as the string value of the corresponding enum(example: "STANDARD"). We currently do a sperarte SELECT on the AM_API_TYPES table to determine what the corresponding ID is of the API Type string that has been provided. We then use that value in the INSERT statement to populate the AM_API table. This results in an additional SELECT being done separately before the INSERT.

This is not optimal and we can simply avoid this by writing a single INSERT with SELECT SQL that has all the foreign key table lookups included as SELECTS within the same INSERT. This will reduce latency related doing multiple DB queries. Below is an example of using INSERT with SELECT to improve the above example.

```SQL
INSERT INTO
    AM_API (UUID, API_TYPE_ID)
SELECT ?, TYPE_ID FROM AM_API_TYPES WHERE TYPE_NAME = ?
```

**Comment by rswijesena** [comment]
Nice approach! Only concern is, do all databases support multilevel subqueries?

**Comment by uvindra** [comment]
Yup, it should be supported by all DB's according to https://www.w3schools.com/sql/sql_insert_into_select.asp

W3schools always makes a distinction if a given way of doing things is DB implementation specific.
