### ISSUE TITLE
[C5][UI] Prevent setting unused cookies in browser 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1616]
When user logged to an UI application(i:e Publisher, Store), in the response to the login request `login/token/publisher` we set following cookies

- Set-Cookie:**WSO2_AM_TOKEN_MSF4J_Env**=-9280-9b4aa38deed2; path=/api/am/publisher; HttpOnly; Secure
- Set-Cookie:~~**WSO2_AM_TOKEN_1_Env**~~=8cb260d2-d880-370a; path=/publisher; Secure
- Set-Cookie:~~**WSO2_AM_TOKEN_2_Env**~~=-9280-9b4aa38deed2; path=/publisher; HttpOnly; Secure

But out of those cookies only  **WSO2_AM_TOKEN_MSF4J_Env** currently being used.
To make the things clear, it's better to remove other unused set-cookie headers.

![unwanted_cookies_apim3](https://user-images.githubusercontent.com/3313885/30794320-1db05030-a1e5-11e7-96b6-ce916f9725ea.png)

@Rajith90 WDYT ?

**Comment by Rajith90** [comment]
Hi Kasun,
I removed WSO2_AM_TOKEN_1, and change the context of the WSO2_AM_TOKEN_2 to "login/logout/{appName}" because in order to revoke the token when log out request comes.
MSF4j token is untouched

**Comment by tmkasun** [comment]
@Rajith90 ,

Can't we use one cookie name for both purposes, MSF4J token for both paths? It seems it is possible to set one cookie for two different paths[[1](https://tools.ietf.org/html/rfc6265#section-4.2.2)].
i:e

> Set-cookie: WSO2_AM_TOKEN_MSF4J=sfa3423rejdasda;Path=/am/api/publisher;http=true
> Set-cookie: WSO2_AM_TOKEN_MSF4J=sfa3423rejdasda;Path=/login/token/publisher

[1] : https://tools.ietf.org/html/rfc6265#section-4.2.2
[2] : https://stackoverflow.com/questions/4056306/how-to-handle-multiple-cookies-with-the-same-name

**Comment by tmkasun** [comment]
Fixed with: https://github.com/wso2/carbon-apimgt/pull/4745 hence closing the issue
