### ISSUE TITLE
[login] Remove JavaScript Accessible cookie and set the correct context for HTTP only cookie 

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#1618]
Since the JS accessible cookie is read from the login response, no need to save it in a cookie. 
HTTP only cookie should be set to rest api context and to logout context both. Rest api context cookie is read by interceptor, logout context cookie is read when the logout request comes.

**Comment by tmkasun** [comment]
Same issue #1616

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/4745
