### ISSUE TITLE
[M7][Publisher][ExportApis] Apis cannot be exported

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1622]
### **Description:**
Once it is trying to export APIs through a GET call, it returns a 404. 

### **Steps to reproduce:**
1. Create an API. (TestApi)
2. Send following cURL command. 

> curl -k -v -H "Authorization: Bearer [apim:api_view]" -H "Accept:application/zip" -X GET "https://127.0.0.1:9292/api/am/publisher/v1.0/export/apis?query=TestApi > exported-apis.zip"

**Expected Response:**
200 and zip file is created

**Actual Response:**
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 134
Content-Type: application/zip

**Comment by menuka94** [comment]
This is probably fixed with https://github.com/wso2/carbon-apimgt/pull/4680.
