### ISSUE TITLE
Issues with the Date of User Registration for particular API

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#1624]
**Description:**
In API Manager  Publisher under the Date of User Registration, it shows the date and time which the user is created in the user store. Not the subscription date and time which gain by the particular user for the particular API.

**Suggested Labels:**
apim

**Suggested Assignees:**

**Affected Product Version:**
apim 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1.Create a new user and subscribed to an API
2.Go to API Manager Publisher.
3.Go to Menu option API.
4.Select the subscribed API and go to user tab.
5.View the Active Subscriptions table.

**Related Issues:**

**Comment by chamilaadhi** [comment]
This section is removed in APIM 2.6.0 (User tab is removed)
