### ISSUE TITLE
basePath component missing in the API swagger file

### ISSUE THREAD

**Issue by sabeena1217** [wso2/product-apim#1633]
**Description:**
when we create an API from the API publisher, and retrieve its swagger file, the basePath component is missing

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by HiranyaKavishani** [comment]
This issue is cannot be reproducible in the latest pack
