### ISSUE TITLE
[API-Store] UI malfunction when the permission list is too long in application key generate tab

### ISSUE THREAD

**Issue by amalhub** [wso2/product-apim#1636]
**Description:**
In API-Store if we select a long list of permissions when generating the token, at one point when the list gets too large, UI alignments get out of order. Thereafter the "Regenerate" button goes unresponsive. 

**Suggested Labels:**
ui, medium, api-store, IoT

**Suggested Assignees:**
thusithak

**Affected Product Version:**
org.wso2.carbon.apimgt.api - 6.1.95 installed in IoT server.

**Steps to reproduce:**
- Create an Application
- Subscribe to multiple APIs
- Goto the application production key generate
- Select long list (10 to 20) of permissions
   - At this point, UI will malfunction.
- Try to click on "Regenerate" token button.
- The button goes unresponsive.
![image](https://user-images.githubusercontent.com/7391925/31168820-570affca-a914-11e7-888c-a74076016134.png)

**Comment by harsha89** [comment]
We have revamped the UI and addressed this. Hence closing the issue.
