### ISSUE TITLE
[M7][Publisher][POST/ import/apis] Response code 500 is thrown while trying to import an API given an invalid file.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1644]
**Description:**
When trying to import an API, given an invalid file(eg: JPG file, txt file) instead of zip file, it is expected to throw 400 as the response code. Instead of that, it is thrown 500. 

**Steps to reproduce:**
1. Send this curl command. 
curl -k -F "file=@./file.txt" -X POST -H "Authorization: Bearer [apim:api_update]" https://localhost:9292/api/am/publisher/v1.0/import/apis

Expected: 
Response code: 400

Actual:
Response code 500

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/product-apim/commit/0678b8aeff2a719a64d1b3d1d372195a62955fe9
