### ISSUE TITLE
Validate the SOAP/REST request payloads in Gateway based on WSDL/Swagger

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1646]
**Description:**
A WSDL contains all the required XSDs to validate all the requests coming to a particular SOAP service. For REST, swagger has request/response schemas. Those can be used to validate payloads generically in Gateway.

**Affected Product Version:**
2.1.0

**Comment by lendldigia** [comment]
Any plans for implementing this feature and if so how soon will this feature be made available ?

**Comment by dushaniw** [comment]
This feature to validate REST request payloads based on Swagger is available implemented in the latest 3.2.0 release. For more info, check https://apim.docs.wso2.com/en/latest/learn/api-security/api-request-response-schema-validation/json-schema-validator/#json-schema-validator
