### ISSUE TITLE
Automate the relevant config changes when starting APIM product profiles

### ISSUE THREAD

**Issue by sajhak** [wso2/product-apim#1647]
**Description:**
When an instance is started as a product profile, for eg: -Dprofile=traffic-manager, still there are prior configurations to be done and apps need to be deleted manually. Better to automate that during the profile config stage, so that the user doesn't have to do any manual changes.

**Affected Product Version:**
APIM 2.1.0

**Comment by npamudika** [comment]
We have done this improvement from APIM 2.5.0 version onwards. Please refer https://docs.wso2.com/display/AM250/Product+Profiles#ProductProfiles-StartinganAPI-Mprofile for more details. Now the product profile optimization has been automated with this.
