### ISSUE TITLE
No label on "custom grant type" chekbox on APIM Store -> Application->Production Keys

### ISSUE THREAD

**Issue by byvinx** [wso2/product-apim#1653]
I created a custom grant type named "mobile" as a guide
https://docs.wso2.com/display/AM210/Writing+Custom+Grant+Types
it works but only the tooltip and no label appears in the list of available grants for the application.
API Store-> Application-> Production Keys (Tab)

APIM 210

Linux Centos 7

Create a custom grant type as: 

https://docs.wso2.com/display/AM210/Writing+Custom+Grant+Types

![mobile](https://user-images.githubusercontent.com/7317029/31663869-aae04072-b343-11e7-89aa-4d9b05b237a8.png)

**Comment by bhathiya** [comment]
See the fix in https://wso2.org/jira/browse/APIMANAGER-5845

**Comment by chamilaadhi** [comment]
As mentioned in the above comment, you will have to add a custom theme to support this. (see https://docs.wso2.com/display/AM210/Adding+a+New+API+Store+Theme) . Using that you could apply the custom implementation similar to the fix provided in https://github.com/wso2/carbon-apimgt/commit/9d7dc2a31b7bf8de87a98b7edb3e11d1b890c26f
