### ISSUE TITLE
Faulty Invocations Dashboard in APIM does not show the appropriate value 

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#1655]
**Description:**
Faulty Invocations Dashboard in APIM does not show the appropriate value on popups

**Suggested Labels:**
BUG

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vanjikumaran** [comment]
![screenshot from 2017-10-23 20-44-08](https://user-images.githubusercontent.com/3397321/31924016-526561b2-b833-11e7-819f-bfe598c61b16.png)

**Comment by fazlan-nazeem** [comment]
The tooltip on the screenshot is for the Cofee-shop API in the table. Since the tooltip does not have information of the api and the x axis is not labled with the api name it may be confusing. 

We will add the api name to the X axis and the tool tip.

**Comment by fazlan-nazeem** [comment]
fixes as below. 

![stats](https://user-images.githubusercontent.com/13759167/34481024-bd025456-efd5-11e7-9cdc-474d57380e97.png)
