### ISSUE TITLE
[APIM][2.1.0]Update Advance Throttle Policy Does not Work Untill Cache Get Cleared

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#1656]
**Description:**

Create an advance throttle policy with condition pipeline.
Assign it to an API.
Throttle works fine.
Update the above policy conditions and invoke API.
Throttle does not work. Not even with previous condition of default condition.
After API republish, server restart or invoking API after 15 mins would result in working throttling as expected with updated conditions.
This happens due to caching time out.
Since this is not a common activity we can invalidate resource cache after an advance throttle policy update.

**Suggested Labels:**

APIM, 2.1.0, bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
related to https://wso2.org/jira/browse/APIMANAGER-5945

**Comment by chamilaadhi** [comment]
We could reduce the gateway cache timeout value if the above requirement is needed. but it would affect the performance of the gateway. so there would be a tradeoff. User has to decide which one is important and configure based on his need
