### ISSUE TITLE
APIM Migration Client for upgrading from previous release 2.0, contains an issue in db migration

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#1660]
**Description:**
AM_APPLICATION_REGISTRATION table has a column named INPUT and the default data type of that column is 1024, however in migration scripts column size is 256. The "18-19 migration" folder in api-manager migration client[1] has this issue. 

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM 2.0, APIM 2.1.0

**OS, DB, other environment details and versions:**
N/A    

**Steps to reproduce:**
Currently if there are 2/3 custom grant types, in addition to defaul grant type, this throws a SQL exception an issue when generating the application key through the store application.

[1] https://docs.wso2.com/display/AM200/Upgrading+from+the+Previous+Release?preview=/50518205/51250637/wso2-api-migration-client.zip

**Comment by harsha89** [comment]
Latest migrations scripts should address this. Hence closing the issue.
