### ISSUE TITLE
[Improvement] Implement a store REST API to get the scopes relevant to an application

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#1661]
**Description:**
Currently, there is no direct store-rest API to get the scopes of an application, based on subscribed APIs. There can be a requirement for the user to get the scopes, to be filtered based on the user-role as well.

**Suggested Labels:**
2.1.x, Improvement

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.1

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:** N/A

**Related Issues:** https://redmine.wso2.com/issues/6908

**Comment by Megala21** [comment]
This issue should be opened until this is implemented for APIM 3.0 as well

**Comment by Megala21** [comment]
Redmine Link - https://redmine.wso2.com/issues/6908

**Comment by chamilaadhi** [comment]
Added to APIM 3.0.0 from https://github.com/wso2/carbon-apimgt/pull/6562
