### ISSUE TITLE
Support fine grained authorization for API developers

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-apim#1663]
**Description:**
In the current implementation, users under the "Creator" role can modify APIs which has been created by other users who has the same "Creator" role. This can cause some problems in an environment where API developers needs to operate independently. Providing user level (fine grained) authentication for API creation and publishing would be a really useful feature

**Suggested Labels:**
feature, 2.1.0

**Suggested Assignees:**
nuwan

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04

**Steps to reproduce:**
1) Create 2 users in the API Manager called "user1" and "user2" and assign them the "creator" role
2) Now create an API by logging into publisher with "user1" account.
3) Log into API publisher with "user2" account. Now you can see the API create by "user1" and edit the API.

**Related Issues:**

**Comment by tharindu1st** [comment]
Hi @chanakaudaya ,
This has been addressed from the API Visibility control in publisher level from 2.1.0 WUM and 2.2.0 release
