### ISSUE TITLE
API Publisher: Add scope to multiple selected resources

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#1668]
**Description:**
For an API with a large number of resources, it's very tedious to click through and assign a scope to each resource. Please enhance the UI to allow a scope to be added to multiple selected resources. Refer attached screenshot.
![image-2017-11-01-19-23-22-125](https://user-images.githubusercontent.com/1875994/32318322-ed9a26a8-bfdc-11e7-8a2b-a9181f8ca86d.png)

**Comment by dushaniw** [comment]
Tagging https://github.com/wso2/product-apim/issues/7292

**Comment by dushaniw** [comment]
will keep this track with https://github.com/wso2/product-apim/issues/7292
