### ISSUE TITLE
Missing entries for Internationalization.

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#1670]
**Description:**
Some words on the "applications" page (store/site/pages/applications.jag) cannot be internationalized. For example the "Filter by" on the search seems to be hardcoded. Same thing for "Show X entries", and on other pages.
**Suggested Labels:**
type/UX, priority/high

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
This is re-written with the introduction of React based UI in APIM 3.0.0
