### ISSUE TITLE
TimestampSkew default vaue need to set 0 in identity.xml

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#1671]
**Description:**
When we generate access token first time it created with expiry time 3600 seconds as expected but when we invoke same command after few seconds expire time got increased to 3890 seconds which is not expected behavior.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
TimestampSkew is set to 0 by default in latest APIM (validated in APIM 2.6.0)
