### ISSUE TITLE
Access token not shown when selecting an application in api console

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1672]
**Description:**
Access token not shown when selecting an application in api console in the store

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM 2.1.0 wum updated.

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySQL DB with IS 5.3.0 as the Key Manager.

**Steps to reproduce:**
1. Create an API form the publisher.
2. Create an application named t1 from the store.
3. subscribe to the api with the created application.
4. generate keys and goto the apis api console.
![selection_003](https://user-images.githubusercontent.com/234736/32480982-705a117e-c3b7-11e7-941d-395e562fa592.jpg)

**Related Issues:**
N/A

**Comment by chamilaadhi** [comment]
Validate in the latest APIM 2.6.0 and it is working. Please use the latest APIM 2.6.0
