### ISSUE TITLE
Support pagination totalAPIs parameter in Store/Publisher GET /apis REST APIs

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1678]
**Description:**
Provide total API count to support pagination.

Request:
curl -k -v -H "Authorization: Bearer aa94a8ea-9272-37d1-ae5d-8ca6ce854444" https://<host>:<port>/api/am/publisher/v0.11/apis?limit=1

```
{
  "count": 1,
  "next": "",
  "previous": "",
  "list": [
    {
      "id": "2b200e15-ff8f-4a88-8e9e-f3a6ae29f508",
      "name": "ABC",
      "description": "",
      "context": "/testing",
      "version": "v1",
      "provider": "admin",
      "status": "PUBLISHED",
      "thumbnailUri": null
    }
  ],
  "pagination": {
    "offset": 0,
    "limit": 1,
    "total": 1987
  }
}
```

**Comment by dushaniw** [comment]
"total" count is included inside Pagination in latest v1 APIs. @malinthaprasan Are you referring to something different than that?

**Comment by kavishkafernando** [comment]
Public commit : https://github.com/wso2/carbon-apimgt/commit/1d29f9197f2cd4039fc405b21987fe57424b701a
