### ISSUE TITLE
Copying to clipboard functions of store does not work

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#1679]
**Description:**

Cannot copy using clipboard functions of the store.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. login to the store,
2. Selected an Application.
3. Clicked the Production Keys tab and Generated or Re-generated the access token.
4. Tried to copy a Key or Curl command or Access Token, clicking the Copy icon. But didn't copy and didn't show as the "Copied". 

The library (ZeroClipboard) used for this functionality, needs flash in order for this to work. Therefore this issue can be solved enabling the flash on **Chrome.**

**Related Issues:**

**Comment by chamilaadhi** [comment]
Since the solution is also provided, We'll close this issue
