### ISSUE TITLE
Server terminated without any warning when memmory usage was high and tenants started login in

### ISSUE THREAD

**Issue by nu1silva** [wso2/product-apim#1680]
**Description:**
Server terminated without any warning when memory usage was high and tenants started login in

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM 2.1.0 wum updated

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, MySQL 5.6, IS 5.3.0 as KM

**Steps to reproduce:**
1. Create 50 tenants using admin services.
2. increase the memory usage of the VM to use 99% of the memmory using stress tool \[1\]
```
stress --vm-bytes $(awk '/MemFree/{printf "%d\n", $2 * 1.1;}' < /proc/meminfo)k --vm-keep -m 1
```
3. using a jmeter script try login into those created tenants.

Observations:
The server had gone down without any warning logs, or head dump.

**Related Issues:**
N/A

\[1\] https://linux.die.net/man/1/stress

**Comment by harsha89** [comment]
We didn't encounter this in recent past hence closing the issue. If you encounter the issue in the latest products please reopen the ticket.
