### ISSUE TITLE
Log files should be fixed to have a rolling file appender

### ISSUE THREAD

**Issue by ChanakaCooray** [wso2/product-apim#1681]
**Description:**
Some of the APIM log files are not configured to have the rolling file appender. 
Ex: wso2-apigw-errors.log file log4j.appender.ERROR_LOGFILE=org.apache.log4j.FileAppender
Since this file is growing rapidly, this needs to have a rolling appender configured.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by tharindu1st** [comment]
tagging https://github.com/wso2/product-apim/issues/7228
