### ISSUE TITLE
[Improvement] search feature for applications at the point of subscribing

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#1688]
**Description:**
 search feature for applications at the point of subscribing

**Suggested Labels:**
Improvement

**Affected Product Version:**
2.1.0

**Steps to reproduce:**

1. Create about 20-30 applications
2. Access the API  and try to locate the newly create application at the time of subscribing

Since applications are listed in alphabetical order user has to scroll to view the applications. If we can provide a search if more than 10 applications are created on the UI the user selects the application to subscribe, this will be user friendly

**Comment by chanaka3d** [comment]
The application search feature is available with 3.x products
