### ISSUE TITLE
 Cannot do  multipart/form-data transformation on WSO2 API Manager 2.1.0

### ISSUE THREAD

**Issue by anuruddhal** [wso2/product-apim#1691]
**Description:**
 Cannot do a multipart/form-data transformation on WSO2 API Manager 2.1.0 as the resulting payload is missing the boundary value in the content-type header. 

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
All OS, any DB

**Steps to reproduce:**
1. Create a REST API with a mock backend.
2. Add the following mediation sequence as in-sequence. 
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="CreateMultiPart" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <payloadFactory media-type="xml">
        <format>
            <root xmlns="">
                <ns:payload content-type="application/xml" filename="payload" name="payload" xmlns:ns="http://org.apache.axis2/xsd/form-data">
                      <Test>
                                <MsgId>$1</MsgId>
                                <Message>$2</Message>
                            </Test>            
                </ns:payload>
            </root>
        </format>
        <args>
               <arg value="Some value 1"/>
               <arg value="Some value 2"/>
        </args>
    </payloadFactory>
<header name="Content-Type" scope="transport" value="multipart/form-data"/>
<property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="multipart/form-data"/>
</sequence>
```
3. Enable wire logs.
4. Invoke the API. The resulting message after payload mediator is missing boundry information in content-type header.

Expected:
`Content-Type: multipart/form-data; charset=UTF-8; boundary=MIMEBoundary_a606033650c728415426a1b901fb774b5c621fbba4877740`

Found:
`Content-Type: multipart/form-data; `

**Related Issues:**
https://github.com/wso2/product-ei/issues/780

**Comment by bhathiya** [comment]
Fixed by https://wso2.org/jira/browse/ESBJAVA-5041
