### ISSUE TITLE
Incorrect connection url in Analytics configuration

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#1696]
**Description:**
Readme has incorrect connection url as tcp://localhost:7612/,tcp://localhost:7613/,tcp://localhost:7614/ and due to this it gets Number format exception.

It should be tcp://localhost:7612,tcp://localhost:7613,tcp://localhost:7614. Due to 

https://github.com/wso2/carbon-apimgt/blob/v6.1.66/features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml#L138

**Suggested Labels:**
Minor, Readme

**Suggested Assignees:**
N/A

**Affected Product Version:**
2.1.x

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by tharindu1st** [comment]
with new config model api-manager.xml will not used
