### ISSUE TITLE
Cannot restrict the roles by visibility in WUM updated pack of 2.1.0

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#1697]
**Description:**
Cannot restrict the store visibility by roles in WUM updated pack of 2.1.0

**Suggested Labels:**
2.1.0, bug

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.1.0

**OS, DB, other environment details and versions:**  
Linux, default pack, running with localhost  

**Steps to reproduce:**
Add an API and add select the visibility to restricted and add some valid roles, even for valid roles, it will give in-valid roles name error. At the same time, in the back-end, following log message will be printed.

`INFO - add:jag CSRF Token error at /publisher/site/blocks/item-add/ajax/add.jag POST`

**Related Issues:**
N/A

**Comment by tgtshanika** [comment]
This issue is already fixed in the latest API Manager 2.1.0-update.
