### ISSUE TITLE
[Improvement]Access control support for APIM publisher

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#1699]
**Description:**
Currently we do not have an access control support for publisher. The APIs that are created in the publisher can be edited and viewed by all the other publishers. However, there is a requirement to restrict those acccess to publisher based on user-roles. The APIs can be un-restricted, which means all the publishers can view and edit the APIs of other publishers. If the API is restircted by roles, only the publishers who have the mentioned roles can edit/view the relevant APIs.

**Suggested Labels:**
APIM 2.1.0, Improvement.

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.1.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:** N/A

**Related Issues:**
Redmine - https://redmine.wso2.com/issues/6644

**Comment by Megala21** [comment]
User Story Doc - https://docs.google.com/document/d/1xGp88Yinu2jFt7eZ2VGcj-q1YF5OHR8n29ZKV_FyTDQ/edit#heading=h.hbws2cbnk0hf

**Comment by Megala21** [comment]
Documentation https://docs.google.com/document/d/1a4TA0W9aUyhFS5W8MVkw4pml_Nnh0ykcxAHOt97sw6M/edit

**Comment by npamudika** [comment]
This has been addressed in Permission Model and Group Sharing feature in APIM 3.0.0.
Refer the discussion thread [1] for further details.

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/APIM-C5-API-Manager-entities-APIs-Applications-Docs-etc-permission-model-and-group-sharing-td145177.html

**Comment by chamilaadhi** [comment]
Tested migration from AM 2.1.0 to 2.2.0 in https://github.com/wso2/product-apim/issues/2217
