### ISSUE TITLE
Field "context" is not populated when importing an API via swagger

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-apim#1702]
**Description:**
When an API is imported via the swagger, it doesn't populate the "Context" field.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
-

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    
All

**Steps to reproduce:**
1. Create an API using the import swagger. (this swagger file should file contain basePath information)

**Related Issues:**
None

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4839

**Comment by dinusha92** [comment]
Reopening the issue as this is affected in APIM 1.10.0.

**Comment by chamilaadhi** [comment]
FIx is provided in the latest versions (2.0.0 onwards). Cannot backport this fix to an older version since it is already released. Please use a latest version to get the fix
