### ISSUE TITLE
[AMHACK] Provide a notification on a successful creation of an API version

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1706]
**Description:**
When a version is created for an existing API, not message provided on the successful creation of an API version.

**Suggested Labels:**
Bug
API versionsing

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
DB - H2
Browser - Firefix 47.0 , Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Create an API
2. Create a version of an API and save it

![apiversion](https://user-images.githubusercontent.com/14962228/33016130-48579b72-ce13-11e7-9c54-a447dfc0a2b2.png)

**Observations**
Did not observe any success message on API version creation
Need to refresh the browser to view the newly created PAI version

**Expected Results**
Should provide a success message on API version creation

**Comment by chamilaadhi** [comment]
Tested it with latest APIM 2.6.0 and I was able to see a success message. See below image.
![Screen Shot 2019-09-10 at 4 08 24 PM](https://user-images.githubusercontent.com/4861150/64607053-53e50400-d3e5-11e9-82fc-07adb7ac2fd9.png)

Please try this on a latest pack.
Thanks
