### ISSUE TITLE
[AMHACK] Observed a blank page after selecting the thumbnail of the API

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1712]
**Description:**
If a user (admin) who has permission to 'lifecycle' tab access the lifecycle menu and later a user (ceator) who only have 'create permission' select the thumbnail of the API, will result in a blank page as in the below-attached image. 

**Suggested Labels:**
Bug
API Publisher

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in from admin user
2. Go to 'Lifecycle' tab and sign out 
![lifecycle](https://user-images.githubusercontent.com/14962228/33059813-def2e3cc-cebb-11e7-81da-f95a4470be3b.png)

3. Log in to API publisher console with a user who has API create permission
4. Click on the thumbnail of an existing API

**Observations**
1. Blank page appeared  (this should be because the creator do not have permission for the lifecycle tab)
![screenshot from 2017-11-21 12-25-52](https://user-images.githubusercontent.com/14962228/33059820-e5dfe568-cebb-11e7-9ec7-bb5669c1fd0d.png)

**Comment by Krishanx92** [comment]
This is now revamped with APIM-3.0.0
