### ISSUE TITLE
[AMHACK][APIM2.1.0][Internationalization and Localization]Changing the APIM UI to Spanish

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1713]
**Description:**
The UI of the API Manager needs to be changed to Spanish. Followed the following doc[1]
[1] - https://docs.wso2.com/display/AM210/Adding+Internationalization+and+Localization

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**   
MacOS Sierra/ Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) 

**Steps to reproduce:**
1. Go to API_HOME/repository/deployment/server/jaggeryapps/publisher/site/conf/locales/jaggery and make the locale_es.json file to  locale_default.json. 

2. Go to APIM_HOME/repository/deployment/server/jaggeryapps/publisher/site/conf/locales/js and make i18nResources_es.json to i18nResources.json. 

3. Go to settings in web browser > advanced settings > Languages > select Spanish

4. There is no way mentioned in the doc to add browser's encoding type to UTF-8 and found from an external source, in Google Chrome encoding type is auto-detected. 

5. Started the API Manager and accessed through an Incognito Window. 

Expected: UI of the API Manager should be changed to Spanish.
Actual: It remained English.

**Related Issues:**
https://wso2.org/jira/browse/DOCUMENTATION-6618
https://wso2.org/jira/browse/DOCUMENTATION-6630

**Comment by Krishanx92** [comment]
Cannot reproduce hence resolve.
