### ISSUE TITLE
[AMHACK][UI] Notification at a successful API creation is not visible to the user, unless the user scroll up the window

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1715]
**Description:**
Successful notification on successful API creation appears at the top of the page, whereas the save button it at the bottom of the page, where a user might confuse whether the API was created successfully or not

**Suggested Labels:**
Improvement

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to API publisher
2. Click the save button at the end of API creation
![apicreation](https://user-images.githubusercontent.com/14962228/33063015-23382898-cec7-11e7-9e50-77b80a1940cc.png)

**Observations**
When a user clicks the 'save' button, notification message appearing at the top of the page and will disappear in a while, which will confuse the user whether the API was created successfully or not.

**Comment by chamilaadhi** [comment]
This UI is re-structured in APIM 3.0.0
