### ISSUE TITLE
[AMHACK] Observed where the backend authentication is not working with basic auth secured endpoint

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1716]
**Description:**
I followed the doc [1] to execute securing endpoint scenario, and $subject.
[1] [https://docs.wso2.com/display/AM210/Basic+Auth]

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0
**OS, DB, other environment details and versions:**    
Oracle 12c jdbc
Email username enabled

**Steps to reproduce:**
- Create an API
- Configure secure endpoint with 'basic auth' at implementation tab
- Save and publish
- Subscribe to app and generate token
- Invoke the above api
I tried using a curl (1)with user credential(base64encode) and (2)without user credential as below, but observation is for both requests I could see success response. AFAIU the expected outcome should be authentication fail or error response for request(2) . Please correct me if I'm wrong. Doc not explaining well and raised a issue here [1]
(1)
`curl -k -X GET --user 'Authorization: Basic a2F2aTEyMzprYXZpMTIz' --header 'Accept: application/json' --header 'Authorization: Bearer 06ab03bd-c0e7-387f-8acb-3e2e8c2ca656' 'https://localhost:8243/text/1.0.0/*'`
(2)
`curl -k -X GET --header 'Accept: application/json' --header 'Authorization: Bearer 06ab03bd-c0e7-387f-8acb-3e2e8c2ca656' 'https://localhost:8243/text/1.0.0/*'`

[1] [https://wso2.org/jira/browse/DOCUMENTATION-6643]

**Related Issues:**

**Comment by uvindra** [comment]
The usage of the curl command in this scenario to invoke an API that fronts a secured backend is incorrect.

You dont need to specify the 'Authorization: Basic a2F2aTEyMzprYXZpMTIz' as in this case. The API Gateway will automatically do this when it forwards the request to the backend.

As far as the curl is concerned, you need to only specify the OAuth2 access token, the same as you would when invoking any other kind of API

**Comment by kavithasub** [comment]
Thank you for explanation. 
No I was checked with a mock backend which not secured.

**Comment by uvindra** [comment]
In that case, as far as I can see there is no issue here, the Mock backend is going to respond with 200 OK regardless. Can we close this issue?

**Comment by kavithasub** [comment]
+1. I will verify this with secured backend and if any issues I will raise it.

**Comment by uvindra** [comment]
Closing ticket as per the feedback, please re-open if you find an issue related to this
