### ISSUE TITLE
[AMHACK] "productionUnitTime" property seems not functioning 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1717]
**Description:**
productionUnitTime property in the api synapse configuration seems not working.

Note - The use case in this is to only allow 10 requests to the backend within 15 minutes.

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Create a API
2. Go to "<APIM_HOME>/repository/deployment/server/synapse-configs" and add following property
```
<handler class="org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler">
         <property name="productionMaxCount" value="10"/>
	<property name="productionUnitTime" value="900000"/>
      </handler>
```
3. Invoke the API by sending 15 requests within 15 minutes

**Observations**
More than 10 requests accepted within 15 minutes. (ex: 10 requests accepted per second)
note - If we send 300 requests (20 per minute, the backend will accept all)

**Expected Result**
Should only accept 10 requests within the 15 minutes

[creator--StockquoteAPI.xml.zip](https://github.com/wso2/product-apim/files/1491094/creator--StockquoteAPI.xml.zip)

**Comment by chamilaadhi** [comment]
I could not see any issue with this. I was able to get the throttled out response after exceeding the limit.
If you still see the issue, please enable following in the log4j.properties file and attach it here please
`log4j.logger.org.wso2.carbon.apimgt.gateway.handlers.throttling=DEBUG`
