### ISSUE TITLE
[AMHACK][Store][Forum]In the forum tab it is displayed as No Topics are available

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1719]
**Description:**
Even though there are topics created, once the user clicks on Forum tab, it says no forum topics are available which gives a wrong impression to the user. 

**Affected Product Version:**
2.1.0  

**Steps to reproduce:**
1. Create an API and publish it to the API Store. 
2. Go to specific API and Click on Forum tab. 
3. Create 3 new topics. 
4. Now click on Forum tab in the side. 

**Expected:** The set of topics to be displayed. 
**Actual:** It displays there are no topics available. But once it is searched for a topic, it appears. 

![1](https://user-images.githubusercontent.com/31693103/33072007-c49b9884-cee3-11e7-9612-bb4edccc1bee.png)

**Comment by chamilaadhi** [comment]
Hi,
Seems like an indexing issue. Can you check whether it is there after doing some refreshing the page. To me, it took couple of seconds . after that It was visible

**Comment by chamilaadhi** [comment]
Please re-open if the issue still exists. Also please attach the wso2carbon.log file to see if there are any issues logged
