### ISSUE TITLE
[AMHACK] Could not generate an access token with a scope as scope is not available 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1720]
**Description:**
Unable to add a scope to a application as mnetioned in [1]
[1]  https://docs.wso2.com/display/AM210/Subscribe+to+an+API

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Create an API
2. Create an application and subscribe the API to the application
3. generate access token with a scope as mentioned in [1]

[1] https://docs.wso2.com/display/AM210/Subscribe+to+an+API

**Observations**
The option is disabled. (ex: showing No scopes found in the field )
![scopesnotfound](https://user-images.githubusercontent.com/14962228/33072898-3427cea4-cee7-11e7-9041-50d0db244056.png)

**Comment by chamilaadhi** [comment]
In your steps you haven't mentioned about registering a scope to the API. you need to create a scope and assign it to the API. If scopes are not set for the api, scopes won't be shown in the token generation page. So please set a scope and check this.
