### ISSUE TITLE
[AMHACK] [Query] Can't I provision "out-of-band OAuth client" for existing applications? 

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1725]
**Description:**
Provision "out-of-band OAuth client" scenario I have tried and observed that I can map 'existing oauth keys' only for new apps which will be created after config changes. My question is do we support this for existing (already created before changes) app?

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Followed the steps in [1]
[1] [https://docs.wso2.com/display/AM210/Provisioning+Out-of-Band+OAuth+Clients]

**Related Issues:**

**Comment by chamilaadhi** [comment]
Existing oauth apps already have a client id and client secret generated for them. You can only map to applications which do not have key-secrets defined
