### ISSUE TITLE
[AMHACK][Blocker]Management console cannot be accessed 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1727]
**Description:**
Once trying to access management console in a fresh APIM pack, cannot get logged in. 
Error: 403 Forbidden
`JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.136, method:POST, uri:/carbon/admin/login_action.jsp, error:required token is missing from the request)`

**Affected Product Version:**
wum updated pack: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**    
macOS High Sierra
Version 10.13.1
Google Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
Firefox: 57.0

**Steps to reproduce:**
1. Get the wum updated API Manager pack and start APIM server. 
2. Navigate to Management console. 
3. Try to login with admin/admin credentials. 

Expected: User should be logged in. 
Actual: User is not allowed to log in. A message is displayed as 403-Forbidden.

**Comment by bhathiya** [comment]
This is due to the High Sierra SDK bug[1]. A workaround would be to switch off compression in tomcat for now.

[1] https://stackoverflow.com/questions/46539453/tomcat-with-compression-enabled-causes-error-on-os-x-high-sierra
