### ISSUE TITLE
[AMHACK] Rich Text Editor in the registry browser does not reflect the configurations coorectly

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1730]
**Description:**
Rich text editor in the governance registry browser does not reflect the text correctly 

**Use Case** - As a user, I want to enable self sign up option for my tenant domain by referring [1] 
[1] https://docs.wso2.com/display/AM210/Customizing+the+API+Store

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre-Requists
1. multiple tenant domains exists

**Steps to reproduce:**
1. Log in to management console with tenant domain admin user
2. Go to Browser and "/_system/governance/apimgt/applicationdata/sign-up-config.xml" registry location

**Observations**
Text not appearing in the correct manner

![richtexteditor1](https://user-images.githubusercontent.com/14962228/33116432-b4965fb2-cf8a-11e7-8a04-b6bc121be49c.png)

**Comment by chamilaadhi** [comment]
This editor is hardly used to configure this and there is no use of this editor when it comes to configure this file. 
please use the 'Plian test editor' to do the changes.
