### ISSUE TITLE
[AMHACK] Escape characters are returned with JWT token

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1732]
**Description:**
JWT token returned with having escape characters in json string (see attached). 

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add JWT configs
- Invoke the API
- Via wire logs can get a JWT assertion
- Decode it
![jwt](https://user-images.githubusercontent.com/15671620/33118765-d2097da6-cf92-11e7-950b-f7da7419bbf5.jpeg)

**Comment by chamilaadhi** [comment]
Hi, 
What did you use to decode this jwt token? I used the online jwt decode tool https://jwt.io and was able to see these urls without the escape characters 

> {
  "http://wso2.org/claims/role": [
    "Internal/subscriber",
    "Internal/creator",
    "Application/admin_DefaultApplication_PRODUCTION",
    "Internal/publisher",
    "Internal/everyone",
    "admin"
  ],
  "http://wso2.org/claims/applicationtier": "Unlimited",
  "http://wso2.org/claims/keytype": "PRODUCTION",
  "http://wso2.org/claims/version": "1.0.0",
  "iss": "wso2.org/products/am",
  "http://wso2.org/claims/applicationname": "DefaultApplication",
  "http://wso2.org/claims/enduser": "admin@carbon.super",
  "http://wso2.org/claims/enduserTenantId": "-1234",
  "http://wso2.org/claims/subscriber": "admin",
  "http://wso2.org/claims/tier": "Unlimited",
  "http://wso2.org/claims/applicationid": "1",
  "http://wso2.org/claims/usertype": "APPLICATION",
  "exp": 1568181579,
  "http://wso2.org/claims/apicontext": "/pizzashack/1.0.0"
}

Please use this and see
Thanks
