### ISSUE TITLE
[AMHACK] Failed to invoke the default version of the API

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1734]
**Description:**
"404 no matching resource found" exception when a user invoking the default version of an API (tenant mode)

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to tenant domain
2. Create an API as in the attached config
[APIs.zip](https://github.com/wso2/product-apim/files/1495733/APIs.zip)
Note - API is created by using SimpleStockQuote service as the backend

3. Create another version of the same API and mark as default
4. Invoke the API by version 
ex: https://10.100.8.9:8243/t/wso2.com/stock/tenant/2.0.0/tenant/stock
5. Invoke the API with its default version. (remove the version as defined in [1] )
ex: https://10.100.8.9:8243/t/wso2.com/stock/tenant/tenant/stock

[1] https://docs.wso2.com/display/AM210/Create+a+New+API+Version

**Observations**
1. API invocation failed due to following;

```
[2017-11-22 15:25:51,647]  INFO - LogMediator STATUS = Executing default 'fault' sequence, ERROR_CODE = 404, ERROR_MESSAGE = No matching resource found for given API Request
```

**Comment by bhathiya** [comment]
Tested in 2.1.0-update3. Unable to reproduce. Please use import/export tool and attach API if you can still reproduce this with >2.1.0-update3.

**Comment by sashikamw** [comment]
@bathiya The APIs that caused the issue is attached to the original ticket. You can find those in APIs.zip

**Comment by bhathiya** [comment]
Yes, I tried with them.
