### ISSUE TITLE
[AMHACK] Search operation in API Publisher does not work when hit enter from keyboard

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1735]
**Description:**
When a user login to the API Publisher and try to search for a available API with the search option and hit enter button from the keyboard. Search operation will not work

**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2. Log in to the API publisher using https://localhost:9443/publisher/
3. Go to the search option
4.Type a availble API name
5.Hit enter from the keyboard ( without clicking on the search icon from the UI )
6.Search operation will not give any result

**Related Issues:**
![search-api](https://user-images.githubusercontent.com/31848014/33125951-a09fb1fc-cfa8-11e7-9d49-ae65c6c89744.png)

**Comment by isharac** [comment]
Fixed in [6.x 2a6a471]
PR https://github.com/wso2/carbon-apimgt/pull/4859
