### ISSUE TITLE
[AMHACK] [UI] No notification created on a successful creation of a subscription tier

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1736]
**Description:**
API admin console will not provide a notification on successful tier creation

**Suggested Labels:**
Improvement

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to API admin console
2. Go to 'Subscription Tiers' under the Throttle Policies 
3. Add a tier and save it

[1] https://docs.wso2.com/display/AM210/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewsubscription-levelthrottlingtier

**Observations**
1. Did not observe any notification to notify that the tier was added successfully

**Comment by chamilaadhi** [comment]
but it gets redirected to the list page once tier is added successfully.
