### ISSUE TITLE
[AMHACK][Improvement] Allow and Deny labels for subscription tier will only applied after saving the configs

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1738]
**Description:**
When allowing or denying a particular role for a subscription tier, the way the label was added is not user-friendly and it's confusing the user

**Suggested Labels:**
Improvement
UI

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to API admin console
2. Add a subscription tier by allowing to a particular role (you can edit an existing subscription tier as well)

**Observations**
1. The label "Deny" or "Allow" will only get applied after saving the subscription tier, until when a user completes the subscription tier form even though the user allows access to a particular role 'Deny' label is there and vice versa.
![screenshot from 2017-11-23 12-06-10](https://user-images.githubusercontent.com/14962228/33161094-4abeb72a-d047-11e7-929c-f2752a3c1738.png)

**Comment by chamilaadhi** [comment]
That label shows the existing state of the tier (whether it is allowed or denied.) It shouldn't hv to change when the radio button is changed. It only has to change once the tier is created with the selected value
