### ISSUE TITLE
[AMHACK]Exported API cannot be unzipped

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1740]
**Description:**
Once an API is exported, it cannot be unzipped. Once it is trying to unzip, another zip folder gets created and continued zipping. 
eg:
myExportedAPI.zip 
myExportedAPI.zip.cpgz 
myExportedAPI.zip 2.cpgz

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    
macOS High Sierra
Version 10.13.1

**Steps to reproduce:**
Export an API through by running following cURL command. 
`curl -H "Authorization:Basic <base64-encoded-credentials-separated-by-a-colon>" -X GET "https://<APIM_HOST:Port>/api-import-export-<product-version>-<tool-version>/export-api?name=<API-name>&version=<API-version>&provider=<API-provider>" -k > <exportedApiName>.zip`

**Expected:** Zip file can be unzipped and the user can view the content. 
**Actual:** The zip file further gets zipped. 
`

**Comment by bhathiya** [comment]
Unable to reproduce. However this can happen if the curl command is incorrect.

For example, `<tool-version>=v2` instead of `v3`
