### ISSUE TITLE
[AMHACK] Duplicate content in the error description when the allocate quota exceeds 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1741]
**Description:**
Duplicate content is given in the error description when requests go beyond the allocated quota.

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to API admin console
2. Add a subscription tier with 20 requests per 5 minutes
3. Create an API and publish it
4. Invoke the API with more than 20 requests (around 25 requests)

**Observations**
1. Additional requests will fail with following error message.
2. Error message description contains duplicate information which should be corrected.

"_**You have exceeded your quotaYou have exceeded your quota**_ "

```
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode
                xmlns:axis2ns46="http://schemas.xmlsoap.org/soap/envelope/">axis2ns46:Server
            </faultcode>
            <faultstring>Message throttled out</faultstring>
            <detail>You have exceeded your quotaYou have exceeded your quota .You can access API after 2017-Nov-23 07:10:00+0000 UTC</detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>
```

**Comment by chamilaadhi** [comment]
I tried your steps but I couldn't see any issue
See below

> curl -X GET --header 'Accept: text/xml' --header 'Authorization: Bearer ab73fafd-db40-3ea8-a81d-92b25976357f' 'https://10.100.5.96:8243/pizzashack/1.0.0/menu' -k
<amt:fault xmlns:amt="http://wso2.org/apimanager/throttling"><amt:code>900804</amt:code><amt:message>Message throttled out</amt:message><amt:description>You have exceeded your quota</amt:description><amt:nextAccessTime>2019-Sep-11 06:19:00+0000 UTC</amt:nextAccessTime></amt:fault>

As you can see, I didn't get any soap response. Can you eleborate more on how you get this? If you have done a customization to change the payload, please check it for any issues

**Comment by chamilaadhi** [comment]
I went through the code and this kind of thing could happen if you remove the default sequences/_throttle_out_handler_.xml . You haven't mentioned this in your reproducing steps. If you have removed it, Is there any specific reason for doing it (We haven't mentioned anywhere to remove this file). If it is done by a mistake, please add it back and test

https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java#L703
