### ISSUE TITLE
[AMHACK] Test operation related to production endpoint url in creating Web Socket API prompts a error message even though the given url is correct

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1742]
**Description:**
Test operation related to production endpoint url in creating Web Socket API prompts a error message even though the given url is correct
**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Sign in to the API Publisher.
https://<hostname>:9443/publisher (e.g. : https://localhost:9443/publisher). Use admin as username and password.
2. In the APIS menu, click Add New API. 
3. Select the option to design a new WebSocket API and click Start Creating.
4. The Design tab of the API opens. Give the information in the table below and click Next: Implement > to proceed to the implementation phase.
5. Click the Managed API option.
Provide the production endpoint and sandbox endpoint, which is ws://echo.websocket.org:80
6. Click on the Test button
7. Will get a error message as Invalid (Even though the given url is correct)
![endpoint-url](https://user-images.githubusercontent.com/31848014/33162175-125c9044-d04e-11e7-9138-aad51e30e376.png)

**Related Issues:**

**Comment by chamilaadhi** [comment]
APIM does a HTTP HEAD method to check whether the backend is valid. Since it is not there for web socket, you would see this error. One option you could do is to use change the protocol to http to check whether the endpoint exists. This would give a warning with 404 not found (we could see whether at least the backend is existing)

**Comment by chamilaadhi** [comment]
Test button is

**Comment by tharindu1st** [comment]
From 4. x we remove the WebSocket test functionality
