### ISSUE TITLE
[AMHACK][UI] Observed an inconsistency in the tag sizes visible in API Store

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1745]
**Description:**
Observed an inconsistency in the tag sizes visible in the API Store

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre-Requists
1. Few APIs should exist in the API store

**Steps to reproduce:**
1. Log in to API Store

![screenshot from 2017-11-23 17-23-32](https://user-images.githubusercontent.com/14962228/33171735-72b66fbc-d073-11e7-951c-0988b31be5a0.png)

**Observations**
1. API tags appeared in different sizes in the API Store

**Comment by bhathiya** [comment]
Please mention which API has which tags.

**Comment by sashikamw** [comment]
@bhathiya ,

I have two APIs with tags.
1. SampleTest - 1.0.0 
Tag - test

![test_tag](https://user-images.githubusercontent.com/14962228/33198535-a4c6483a-d111-11e7-8829-e126db72a57f.png)


2. TenantSOAPStock - 1.0.0
Tags - stock,tenant

![other _tags](https://user-images.githubusercontent.com/14962228/33198543-ae344890-d111-11e7-9a4d-ef3b902477d9.png)

3. 
TenantSOAPStock - 2.0.0 - Default API
Tags - stock,tenant

![version2](https://user-images.githubusercontent.com/14962228/33198548-b4b0741e-d111-11e7-885e-cd8306df58a7.png)

**Comment by bhathiya** [comment]
So it looks like the count of each tag is aligned with the size of the font. Isn't it?

**Comment by sashikamw** [comment]
@bhathiya ,

As you can see in the below-attached image, reason for the inconsistency in the tag sizes should be the font size that got applicable for the tags included in the "TenantSOAPStock - 2.0.0" API.

![screenshot from 2017-11-24 13-15-46](https://user-images.githubusercontent.com/14962228/33200261-e48e2bc4-d119-11e7-8958-93f9bc2d8470.png)

**Comment by bhathiya** [comment]
Sorry it's not clear. Could you explain further?

**Comment by sashikamw** [comment]
What I mean here is, If you closely look at the highlighted area in the above image, you can see that API tags come with different font sizes. For the "test" tag one font-size and for other two different font-size. (which ultimately looks inconsistency in the tags for the end-user)

**Comment by bhathiya** [comment]
In tag clouds, font size is proportional to the each tag's usage. In your case, 

test = 1 (small tag)
tenant = 2 (large tag)
stock = 2 (large tag)

**Comment by sashikamw** [comment]
As as I understood what you mean here is, since I have two API versions with these tags its appearing in the larger size is it? please, correct me if i'm wrong.
What I expected was, since I have only one API version marked as default (which is visible in the store) font size should be same.

**Comment by bhathiya** [comment]
Well, that's not mentioned in the original description. :)
However, I don't think this is an issue. We consider each version as different APIs. In that point of view, it's ok to count in this way.

**Comment by isharac** [comment]
This is the expected behavior in tag Cloud.
