### ISSUE TITLE
[AMHACK]Cannot create users in Management Console even if the java version in downgraded. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1746]
**Description:**
Initially had the java version of 8u151. After that downgraded the Java version to 1.8.0_144 as discussed in the mail[1]. Added the following line to <APIM_HOME>Repository>Conf>Security>Owasp.CsrfGuard.Carbon.properties file. 
`org.owasp.csrfguard.unprotected.mgtconsolelogin=%servletContext%/carbon/admin/*`

Now I can login to Management Console with admin credentials. But once a user is going to be created getting an error as[2]

**Affected Product Version:**
APIM 2.1.0 Wum updated: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**   
macOS High Sierra
Version 10.13.1
Java: (build 1.8.0_144-b01) 

**Steps to reproduce:**
1. Make sure the Java version is not 8u151. Install Java: (build 1.8.0_144-b01) 
2. Get the wum updated pack wso2am-2.1.0.1511201090302.zip
3. Change the property as suggested in the mail [1]<APIM_HOME>Repository>Conf>Security>Owasp.CsrfGuard.Carbon.properties file. 
`org.owasp.csrfguard.unprotected.mgtconsolelogin=%servletContext%/carbon/admin/*`
4. Login to Management console with admin credentials. 
5. Try to create a user. 

Expected: User should be navigated to next screen
Actual: Error occurs - 403 Forbidden. 
`JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.136, method:POST, uri:/carbon/user/add-finish-ajaxprocessor.jsp, error:required token is missing from the request)`

**Related Issues:**
https://github.com/wso2/product-apim/issues/1727

**References**
[1] - [APIM]Cannot login to APIM Management console with admin credentials
[2] - 403 Forbidden
`JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.136, method:POST, uri:/carbon/user/add-finish-ajaxprocessor.jsp, error:required token is missing from the request)`

**Comment by chamilaadhi** [comment]
please change the `org.owasp.csrfguard.unprotected.mgtconsolelogin=%servletContext%/carbon/admin/*
 `
to 
`org.owasp.csrfguard.unprotected.mgtconsolelogin=%servletContext%/carbon/*
 `
and it should work
