### ISSUE TITLE
[AMHACK]Unable to import an API

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1748]
**Description:**
Once an API is going to be imported, following error is occurred. 
```
<html>
    <head>
        <title>Error 403</title>
    </head>
    <body>
        <h1>Error 403 - Forbidden</h1>
    </body>
</html>
```

**Affected Product Version:**
APIM 2.1.0 wum updated: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**    
macOS High Sierra
Version 10.13.1
Java: (build 1.8.0_144-b01)

**Steps to reproduce:**
1. Start APIM server and export an API as a zip file. 
2. Now with the following cURL command try to import the API. 
`curl -H "Authorization:Basic AbCdEfG" -F file=@"/Desktop/MyAPIFolder/myExportedAPI.zip" -k -X POST "https://192.168.2.100:9443/api-import-export-2.1.0-v2/import-api"`

Expected: API should be imported. 
Actual: Getting the following error. 
```
<html>
    <head>
        <title>Error 403</title>
    </head>
    <body>
        <h1>Error 403 - Forbidden</h1>
    </body>
</html>
```

Backend: 
`JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.136, method:POST, uri:/api-import-export-2.1.0-v2/import-api, error:required token is missing from the request)`

**Comment by bhathiya** [comment]
Webapp version should be v3, not v2.
