### ISSUE TITLE
[UI]the api latency breakdown chart has a null when attempting to compare

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#1749]
**Description:**
the api latency breakdown chart has a null when attempting to compare

**Affected Product Version:**
wso2am-2.1.0
**OS, DB, other environment details and versions:**    
Browser:Firefox:57
**Steps to reproduce:**
1.check the api latency breakdown

**Comment by chamilaadhi** [comment]
These charts are removed in AM 3.0.0 and it is moved to dashboards in the analytics server. Please check it on that

**Comment by chamilaadhi** [comment]
I tried this with the latest APIM and I was able to see the second version to compare in the drop down menu. see below

![Screen Shot 2019-09-11 at 1 08 10 PM](https://user-images.githubusercontent.com/4861150/64677538-63238a80-d495-11e9-865e-2c5070518635.png)


This compare capability is only provided to compare between two versions. If there is no versioned API created for a perticular API, this drop down is empty. I suspect this would be the case in your environment. Please check this as well
