### ISSUE TITLE
[AMHACK]Once the SDK is downloaded for android from API Manager, it doesn't generate the org.wso2.client.model.<API_Name>.*

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1751]
**Description:**
After creating an API, once the user downloads the SDK for Android, it gives a compile error which is it doesn't generate the org.wso2.client.model.<API_Name>.*

**Affected Product Version:**
APIM 2.1.0 Wum updated: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**    
macOS High Sierra
Version 10.13.1
Java: (build 1.8.0_144-b01)

**Steps to reproduce:**
1. Create an API. (Name: TestApi1)
2. Download the SDK for Android. 
3. Build the downloaded project as in the instructions given 

**Expected:** It should be successfully built. 
**Actual:** There is a compile error found due to not generating a mentioned import. (it doesn't generate the org.wso2.client.model.<API_Name>.*)
<img width="1440" alt="screen shot 2017-11-23 at 7 03 50 pm" src="https://user-images.githubusercontent.com/31693103/33175298-4ead69c8-d081-11e7-81bc-5f82f4723fa3.png">

**Related Issues:**

**Comment by sanjeewa-malalgoda** [comment]
This is a bug in swagger code. Their assumption was each service definition will have at least one model which describes data. But there can be situations we will not have any model associated with API. In API template file we have below entry

import {{modelPackage}}.*;

This means model package will add to each service class even if we have model or not. Ideally we should check we have models first and add above only if we have models. Other option is add default model even if we do not have any model in swagger definition. But it may confuse users IMO. We need to discuss this with swagger community and come to conclusion as this is generic issue.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
