### ISSUE TITLE
[AMHACK][API Store]Copy functionality does not work

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1754]
**Description:**
In API Manager store copy functionality does not work. 

**Affected Product Version:**
APIM 2.1.0 Wum updated: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**    
macOS High Sierra
Version 10.13.1
Java: (build 1.8.0_144-b01)
Google Chrome - Version 62.0.3202.94 (Official Build) (64-bit)

**Steps to reproduce:**
1. Start the APIM server and login to Store. 
2. Click on default application and go to Production Keys tab. 
3. Click on Show keys. 
4. Try clicking copy button in Consumer Key field. 
![dd](https://user-images.githubusercontent.com/31693103/33177644-602bf2e8-d089-11e7-91a8-853ce8e62572.png)

Expected: The value should be copied. 
Actual: The value is not getting copied.

**Comment by chamilaadhi** [comment]
Duplicate to https://github.com/wso2/product-apim/issues/1679

**Comment by chamilaadhi** [comment]
This issue can be solved enabling the flash on Chrome. See 
https://support.digication.com/hc/en-us/articles/115003963468-Enabling-Flash-for-Google-Chrome-Windows-Macintosh- on how to enable it
