### ISSUE TITLE
[AMHACK][UI] 'Cancel' button is disabled when user try to move out of the API edit window

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1755]
**Description:**
When a user (api creator) try to edit an API which is already published and have active subscriptions. The 'cancel' button appearing in the 'Manage' page is disabled, where the user cannot move out of the API edit page unless clicking an outside icon, which is not user-friendly.

**Suggested Labels:**
UI
Improvement

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Oracle 15.10
JDK - jdk1.8.0_66
DB - H2
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre-Requisites
1. Few APIs exists in tenant domain
2. APIs in published state with active subscribers

**Steps to reproduce:**
1. API creator select an API, and go to edit page -> 'Manage' section

**Observations**
1. 'Cancel button is disabled so that user should click somewhere outside to move out of the edit window.

![cancelbutton](https://user-images.githubusercontent.com/14962228/33198694-a4c743b0-d112-11e7-9aa0-c63f0242ae64.png)

**Expected Result**
Cancle button should not be disabled

**Comment by chamilaadhi** [comment]
Go To Overview button in the top is provided for this. Please use it to move out from this window
<img width="201" alt="Screen Shot 2019-09-11 at 3 03 59 PM" src="https://user-images.githubusercontent.com/4861150/64686009-953ce880-d4a5-11e9-9a0a-8d45e3025b9c.png">
