### ISSUE TITLE
[AMHACK] Authentication issue while login to pub/store after KM config with securevault enabled in apim only, email username enabled, and point to oracle db.

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1759]
**Description:**
Authentication issue while login to pub/store after KM config with securevault enable in apim, email username enabled, and point to oracle db.

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0
**OS, DB, other environment details and versions:**    
Oracle 12c jdbc, Email username enabled, KM: wum updated KM pack (22/11)
APIM secureVault enabled for password encryption

**Steps to reproduce:**
- Enable below configs for apim pack and start the server => works fine
email username, datasource for UM, AM, REG db, password encryption by run ciphertool, enable securevault for endpoint encryption
- Stop the apim server
- Clean the databases and created new schemas
- Do the KM configs using wum km pack (followed doc in [1])
- Run the DB script manually for AM, UM & REG databases as per said in doc
- Up the IS server with port offset to 1 => up and running success
- Up the APIM server => up and running success
- Login to publisher/store => gives an authentication error

[1] [https://docs.wso2.com/display/AM210/Configuring+WSO2+Identity+Server+as+a+Key+Manager]
stack trace at IS carbon logs:
`[2017-11-24 19:25:54,222]  WARN {org.wso2.carbon.core.util.AnonymousSessionUtil} -  Failed to retrieve Realm for the Invalid Domain : wso3.com
[2017-11-24 19:25:54,223] ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} -  Invalid domain or unactivated tenant login
`

**Comment by chamilaadhi** [comment]
Once you clean ur database, your user-related information will be lost. 
`Clean the databases and created new schemas`

It is not possible to login using that once the database is gone. As you can see `Invalid domain or unactivated tenant login`.
