### ISSUE TITLE
[AMHACK]Android SDK generation in SampleAPI contains a compilation error. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1762]
**Description:**
Once a sample API deployed and generates SDK for Android, it gets a compile error. 

**Affected Product Version:**
APIM 2.1.0 Wum updated: wso2am-2.1.0.1511201090302.zip

**OS, DB, other environment details and versions:**  
macOS High Sierra
Version 10.13.1
Java: (build 1.8.0_144-b01)  

**Steps to reproduce:**
1. Start APIM server and log in to the publisher. 
2. Deploy the sample API. 
3. Generate the SDK for Android. 
4. As in the doc[1] build the SDK through mvn. 

[1] - https://docs.wso2.com/display/AM210/How+to+use+SDK+generation+in+application#f1a706d6d4fb453880da578fc8122bd4

**Expected:** SDK should be successfully built. 
**Actual:** There is a compile error. 

```
Error:(63, 33) java: reference to Error is ambiguous
  both class org.wso2.client.model.PizzaShackAPI.Error in org.wso2.client.model.PizzaShackAPI and class java.lang.Error in java.lang match
```

**Related Issues:**
https://github.com/wso2/product-apim/issues/1751

**Comment by sanjeewa-malalgoda** [comment]
This can be common to any class name which loads from other liibs. So we will not have simple solution for this. 
Swagger code gen has concept of reserved words to avoid having language specific reserved words in generated code.  But we cannot limit this as class names can duplicate in other jars.
Other option is add model classes explicitly. But this may need considerable amount of code changes in swagger side. 

Better to discuss these with swagger community and come to conclusion on these issues.

**Comment by irham0019** [comment]
This issue is due to the class Error is available from multiple packages, due to that even though the package org.wso2.client.model.PizzaShackAPI.*(which has the Error class) has imported this error occurs. 
Since the above reason if the swagger file have any definitions with the name of native classes, the classes from the org.wso2.client.model.<api> package have to be imported manually to fix this.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
