### ISSUE TITLE
[AMHACK] [UI] Alignment issue for success message, when save at the API creation page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1766]
**Description:**
As $subject the successful message appears on top of page and it was hidden while click on save button (save button is at bottom and user cannot see the popup message after saved bcz it is only appears at top and when scrollup it disappears)

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create an API at publisher
- On implementation tab, save it
- Try to view popup message by scroll up

Suggestion: It is good if message displays on out panel (like where ever user in it should be viewable).

**Comment by chamilaadhi** [comment]
UI is re-done on AM 3.0.0 and these pages are removed. This issue is invalid due to this
