### ISSUE TITLE
[AMHACK] Warning message in the advanced throttling configuration window does not contain proper word seperation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1768]
**Description:**
Warning message in the advanced throttling policy configuration window does not contain proper word separation 

**Suggested Labels:**
UI
Bug

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to admin console
2. Throttling olicies -> advanced throttling -> add policy

**Observations**
1. There is a warning message at the bottom of the page with no proper separation of advanced throttling mechanisms that need to be configured.

![screenshot from 2017-11-27 14-06-25](https://user-images.githubusercontent.com/14962228/33257656-f1d0c7fa-d37c-11e7-8db2-f48a96f73ead.png)

Expected Result
Please add comma separated values for example : " Warning! Publishing Query Params, Header Data and JWT Token isn't configured. If a policy configured with any of these conditions, it won't be applied."

**Comment by dewmini** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/94c782471820a7aa5970643c9246c890f3bfbe6d
