### ISSUE TITLE
[AMHACK] Users are directed to the Manage phase even though the Production endpoint given under the implement phase is wrong in REST API creation 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1769]
**Description:**
Users are directed to the Manage phase even though the Production endpoint given under the implement phase is wrong in REST API creation 

**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Sign in to the WSO2 API Publisher.
https://<hostname>:9443/publisher (ex: https://localhost:9443/publisher). Use admin as username and password.
2. In the APIS menu, click Add New API.
3. Select Design New REST API and click Start Creating.
4. Give the information as below
name       -  xyz
context    -  /phoneverify
version    - 3.0

4. Click on next implement
5. Will prompt a message as resource not specified
6. click yes
7. click on managed API in implement phase
8. Input a wrong production endpoint (eg:- http://ws.cdyne.com/phoneverify2/phoneverify.asmx)
9. click on Test [2]
10. Will give a 404 error as invalid
11. Click on Next Manage
12. Will proceed to the Manage phase (next phase) eventhough the given production endpoint is wrong

[1]. https://docs.wso2.com/display/AM210/Create+and+Publish+an+API
[2]. config.png

Here better to provide a error message for the users without proceeding to the Manage phase
![config](https://user-images.githubusercontent.com/31848014/33259295-7238412a-d382-11e7-88c9-f81957093680.png)

**Related Issues:**

**Comment by chamilaadhi** [comment]
Test button is provided to check the backend. User should know that there could be an issue with the backend. If the user still want to create the API with this endpoint, what else can we do? 

We cannot prevent api creation due to the backend availability. What if the back end is not up yet. If the backend is not available, user will be notified during the API invocation time.
