### ISSUE TITLE
[AMHACK] Header based throttling does not work when multiple values allowed for a given header 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1772]
**Description:**
Unable to throttle based on multiple header parameter values for a given header name

Use Case -  I want to create an advanced throttling policy to allow only 2 requests per minute if the SOAPAction contains 'urn:getMarketActivity' or 'urn:getQuote'.

**Suggested Labels:**
Bug
header based Throttling

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

**Steps to reproduce:**
1. Log in to admin console
2. Throttling policies -> advanced throttling -> add policy
3. Create a policy based on header values to allow 2 requests per minute of the SOAPAction header contains 'urn:getMarketActivity' or 'urn:getQuote'.
4. Invoke the API
```
curl -k -X POST --header 'Content-Type: text/xml' --header 'Accept: text/xml' --header 'SOAPAction: urn:getMarketActivity' --header 'Authorization: Bearer f96ecac8-e078-32e2-87c6-89f0a393b184' -d '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.samples" xmlns:xsd="http://services.samples/xsd"> \ 
    <soapenv:Header/> \ 
    <soapenv:Body> \ 
       <ser:getMarketActivity> \ 
          <ser:request> \ 
             <!--Zero or more repetitions:--> \ 
             <xsd:symbols>IBM</xsd:symbols> \ 
          </ser:request> \ 
       </ser:getMarketActivity> \ 
    </soapenv:Body> \ 
 </soapenv:Envelope>' 'https://10.100.8.9:8243/carbon/stock/2.0.0/path/stock'
```

**Observations**
1.It's not possible to add two header values with 'SOAPAction' , hence configured as in the below-attached image. Throttling configuration did not work as expected.
![screenshot from 2017-11-27 17-01-22](https://user-images.githubusercontent.com/14962228/33264741-dd7ef1f6-d394-11e7-9e97-3744abb06c7d.png)

**Expected results**
1. Should only allow 2 requests per minute if the header value contains  'urn:getMarketActivity' or 'urn:getQuote'

Related to - https://wso2.org/jira/browse/DOCUMENTATION-6890?filter=14402

**Comment by chamindias** [comment]
Closing this since the [doc jira](https://wso2.org/jira/browse/DOCUMENTATION-6890) is resolved.
