### ISSUE TITLE
[AMHACK] Include an option to edit header values given in an advanced throttling policy

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1773]
**Description:**
Better to include an option to edit an existing header parameter given for advanced throttling

**Suggested Labels:**
Improvement
Header-based Throttling

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre-Requisists
An advanced throttling policy with multiple header based parameters exists

**Steps to reproduce:**
1. Log in to admin console
2. Select the above-advanced throttling policy and select the conditional group.

**Observations**
No option to edit the given header parameters

**Expected results**
It would be better to have an option to edit the existing header parameters if a user wishes to edit a parameter value

**Comment by chamilaadhi** [comment]
Editing is not provided for these conditions. Delete and re-create is the option you could use for this
