### ISSUE TITLE
Applications Listing Page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1776]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This UI has been implemented for APIM 3.0.0 m35
<img width="1420" alt="Screen Shot 2019-09-20 at 2 16 08 PM" src="https://user-images.githubusercontent.com/4471756/65313014-42ec7d80-dbb1-11e9-91ec-b1ad513f8e4c.png">
