### ISSUE TITLE
Create Application

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1777]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This UI has been implemented for APIM 3.0.0 m35
<img width="781" alt="Screen Shot 2019-09-20 at 2 19 01 PM" src="https://user-images.githubusercontent.com/4471756/65313234-a9719b80-dbb1-11e9-9e49-f0fc6d9326e1.png">
