### ISSUE TITLE
Manage Application Page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1778]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This UI has been implemented for APIM 3.0.0 m35.
![screenshot-localhost_9443-2019 09 20-14_35_43](https://user-images.githubusercontent.com/4471756/65314881-c2c81700-dbb4-11e9-9ede-5bd96633a5c2.png)
