### ISSUE TITLE
Edit Application

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1782]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This has been implemented in APIM 3.0.0 milestone 35 Store app
<img width="763" alt="Screen Shot 2019-09-20 at 3 01 45 PM" src="https://user-images.githubusercontent.com/4471756/65316487-b1ccd500-dbb7-11e9-91eb-cb6e26f84ee7.png">
