### ISSUE TITLE
[AMHACK] [Store] Add a place holder to email field found in Manage Alerts

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#1785]
**Description:**
In API Store Manage alerts we can specify emails but the user needs to press enter or comma separated before saving the changes for the email to be recognized. So its better to provide a placeholder similar to which is done in Publisher. Refer the image below.

**Suggested Labels:**
Improvement

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 14
JDK - jdk1.8.0
DB - h2
Browser - Chrome Version 62.0.3202.62
**Steps to reproduce:**

1. 1. Login to api store
2. Navigate to Analytics -> Manage alerts

![placeholder](https://user-images.githubusercontent.com/17248809/33304448-e4e7db0c-d42e-11e7-93ec-5ab5c398b45c.png)

**Comment by chamilaadhi** [comment]
This UI section is removed in AM 3.0.0 due to UI re-writing based on react.
