### ISSUE TITLE
Private Jet API Mode

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1831]
**Description:**

This feature enables users to deploy an API in a dedicated gateway node. When publishing an API, the publisher can publish the API to a dedicated gateway. By default, this will support container management systems such as Kubernetes and Openshift. This will create containers in Kuberntes/Openshift. You have the flexibility to run WSO2 API Manager inside the container management system as well as externally. 

![image](https://user-images.githubusercontent.com/1329596/35084663-02095686-fc4b-11e7-9f8b-932a7b2b4e34.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
PR - https://github.com/wso2/carbon-apimgt/pull/5092
