### ISSUE TITLE
Publisher web app - API Walkthrough

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#1832]
Add application walkthrough capability to Publisher and Store applications to make it easy for first-time users of the application.

**Comment by tmkasun** [comment]
@manjulaRathnayaka Could you give some suggestions and ideas for implementing this feature for API Manager 3.0 version

**Comment by manjulaRathnayaka** [comment]
@tmkasun We have found this is a very useful feature for new users to familiarize with the product. It would be good to extend this even to view analytics etc.

**Comment by tmkasun** [comment]
Thanks for the input,
After a quick check, Following are the libraries that we could use for implementing a walkthrough feature

- [ReactTour](https://github.com/elrumordelaluz/reactour)
- [ReactJoyRide](https://github.com/gilbarbara/react-joyride)

**Comment by Krishanx92** [comment]
Initial commit using [ReactJoyRide](https://github.com/gilbarbara/react-joyride) library for implement a walk-through feature.

https://github.com/wso2/carbon-apimgt/pull/6810

**Comment by CrowleyRajapakse** [comment]
similar issue https://github.com/wso2/product-apim/issues/1555

**Comment by tmkasun** [comment]
Similar feature implementation details for developer portal https://github.com/wso2/product-apim/issues/7787

**Comment by ruks** [comment]
Close since it is already fixed
