### ISSUE TITLE
[AMHACK]  SNI support doesn't contains in APIM servers

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#1885]
**Description:**
When we are having multiple hostnames in nginx configs, Client should send the SNI Information

**Suggested Labels:**
APIM clustering

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    
OS-ubuntu14.04
DB-Mysql
Fronted with Nginx 1.71 community version

**Steps to reproduce:**
Have a nginx with multiple hostname configuration in conf.d
Have an APIM distributed setup fronted by nginx
When calling through the nginx from publisher to keymanager or gateway,server was sending a wrong certificate to the client. enable openssl logs it will list down the client and server communication.

**Comment by chamilaadhi** [comment]
Workaround related to this issue can be found in this mail thread http://mail.wso2.org/mailarchive/dev/2017-November/074715.html

**Comment by chamilaadhi** [comment]
As the fix in that mail thread, force Nginx to send key manager certificates if SNI information is not present. Since there is a solution, I'll close this issue
