### ISSUE TITLE
[AMHACK] Error popup should be corrected with proper message for email username validation, when register a tenant

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1888]
**Description:**
Error popup should be corrected with proper message for email username validation, when register a tenant

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Enable email username
- Add a tenant
- Enter normal username an Register => an error popsup as below
Improve the error message say enter a valid email address for admin username (since we are giving 3 names)

![tenant](https://user-images.githubusercontent.com/15671620/33317757-21704d1e-d45e-11e7-974e-567c2a2f7c6e.jpeg)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
