### ISSUE TITLE
[AMHACK] [Query] Permission tree contains plenty of permission lists - Do we have a use of those permissions?

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1890]
**Description:**
As $subject I can see lists of permissions in permission tree at admin console. As I refered the doc in [1] I understood the role based permissions. There basically 4 roles was explained and limited number of permissions was assigned to those roles even.
Do we have use of other permissions? If so do we have any doc reference to understand what are those? (As I searched I couldn't find any other doc)
e.g. 
![perm](https://user-images.githubusercontent.com/15671620/33319707-9c5f41ae-d465-11e7-9e3f-dfda94567d3a.jpeg)

[1] [https://docs.wso2.com/display/AM210/Adding+User+Roles]

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Comment by msm1992** [comment]
Most of the permissions listed here come from components other than pure APIM, for example like IS and governance registry. When IS or G-reg components are used within APIM, these permissions are checked, therefore they cannot be removed from the permission tree.

**Comment by chamilaadhi** [comment]
answered.
