### ISSUE TITLE
[AMHACK] [UX] Text field validation for email address is not properly involving

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1892]
**Description:**
I can see $subject at the manage tab for create API page (see attached). The validation is there only if I don't enter '@' sign and only if I enter dot sign. Validation not available if I enter wrong (test@ttttttt) and press the tab. The validation triggering with red color randomly when typing characters.

**Suggested Labels:**
2.1.0
UX

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Go to Create API -> Manage
-  Business infor

**Comment by chamilaadhi** [comment]
fixed from https://github.com/wso2/carbon-apimgt/pull/4878
