### ISSUE TITLE
[AMHACK] [UI] Critical usability issue in plotting the API usage stats

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1895]
**Description:**
Inconsistency in plotting the API subscriptions count in the 'Overall API usage' graph. 

**Suggested Labels:**
Bug
Critical
APIM Analytics

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre -requisites
1. Several APIs should exist with subscriptions

**Steps to reproduce:**
1. Go to Publisher console -> Analytics -> API

**Observations**

- There is huge inconsistency among the points reflected in the graph.
- Some of the points are not even clearly visible

IMO this is a critical UX issue.

![screenshot from 2017-11-29 11-17-04](https://user-images.githubusercontent.com/14962228/33359918-55631644-d4f7-11e7-97cf-34a83eaeb6c9.png)

**Comment by TanyaM** [comment]
This is not a UI bug. This is a bubble chart where the size of the bubble represents the usage count. So the reason for the difference sizes of bubble for each api is depending on their usage count.
