### ISSUE TITLE
[AMHACK] Forum Rating in the API Store doesn't show the correct value to match with the number of stars selected when changing the choice repeatedly

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1896]
**Description:**
Forum Rating in the API Store doesn't show the correct value to match with the number of stars selected when changing the choice repeatedly
**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121
**Steps to reproduce:**
1. Create a user as  a subscriber
2. Login to the API store as the user created in step 1
3. Create a forum topic 
4. Select the created the forum from the list
5.Try add a rating 
6.First select all the 5 stars and it will display as 5.0 inside the yellow color star [1]. Then select 1 star in the same rating (like changing your choice) 
7.Inside the yellow color star it will show a wrong value ( Will show as 3.0 when proceed with step 6) [2]

[1]. rating1.png
[2]. rating2.png

![rating1](https://user-images.githubusercontent.com/31848014/33363073-d56d09a0-d504-11e7-9712-58c64c611ab2.png)
![rating2](https://user-images.githubusercontent.com/31848014/33363080-e251034c-d504-11e7-81d3-adfe075aa461.png)

**Related Issues:**

**Comment by isharac** [comment]
Feature is not available in the latest version 3.2.0
