### ISSUE TITLE
[AMHACK]Eclipse JavaEE Mars + API Manager Tooling 2.1.0 cannot open

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1897]
**Description:**
Eclipse JavaEE Mars + API Manager Tooling 2.1.0 downloaded under Full Distribution for MacOs cannot open. A message pops up as Eclipse is damaged. 

**Affected Product Version:**
API Manager Tooling 2.1.0

**OS, DB, other environment details and versions:**    
MacOs High Sierra
Eclipse JavaEE Mars + API Manager Tooling 2.1.0

**Steps to reproduce:**
1. Navigate to https://wso2.com/api-management/
2. Click download
3. Click Download Tooling
4. Under Full Distribution, select MacOs
5. Extract the downloaded dmg file and open Eclipse

Expected: The Eclipse should be started
Actual: An error message pops up as Eclipse is damaged.

**Comment by chamilaadhi** [comment]
This is fixed in the latest tooling kit. Please use the latest version
Thanks
