### ISSUE TITLE
[AMHACK] Cannot add API as "Restricted by roles" visibility with email-username enabled

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1901]
**Description:**
When I try to add an API with enabling visibility to only "Restricted by roles" where the environment set as email-username enabled, it was gives an error [1] and saving/implementing api not working. (see attached)
Using wum updated apim pack (wso2am-2.1.0.1510585460470.zip)
**Suggested Labels:**
2.1.0
Highest

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0

**OS, DB, other environment details and versions:**    
Oracle 12c jdbc
Configured KM
Enabled email username property in carbon.xml

**Steps to reproduce:**
- Add a API in publisher
- Select Visibility: Restricted by roles
- Enter role value : e.g. financer (note that this role should be exist) (see attached)
=> when entering role error is validated in UI (see attached)
- Try to save/ Click on next

![role1](https://user-images.githubusercontent.com/15671620/33368865-d8d9702e-d518-11e7-9987-80079be4ee51.jpeg)
![roles3](https://user-images.githubusercontent.com/15671620/33368914-015a7a84-d519-11e7-93ed-21fed1dafeca.jpeg)

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4889
