### ISSUE TITLE
[AMHACK] Validating wsdl uri at edit page is not posible due to registry path value picked to the filed

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1902]
**Description:**
If I need to validate the wsdl uri after adding API using soap endpoint, in the edit design page "WSDL" uri  I faced below issues:
- text filed is picking registry path 
- Test URI button still enabled
- Test uri failed

**Suggested Labels:**
2.1.0, bug

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0 wum updated pack (20th Nov downloaded)

**OS, DB, other environment details and versions:**    
Mysql 5.57 jdbc

**Steps to reproduce:**
- Add an API using SOAP endpoint
- Save and publish
- Go to edit API
- At design page try to validate wsdl uri by clicking Test uri button

![wsdl-api](https://user-images.githubusercontent.com/15671620/33371867-15b0f496-d522-11e7-83b0-551261aebdc6.jpeg)
![wsdl-api2](https://user-images.githubusercontent.com/15671620/33371872-185b49e4-d522-11e7-8def-0e937091ffb2.jpeg)

**Comment by chamilaadhi** [comment]
In APIM 3.0.0 M16 This functionality is not provided

![Screen Shot 2019-09-12 at 12 09 36 PM](https://user-images.githubusercontent.com/4861150/64760338-26b86300-d557-11e9-91c6-b3bdf820cbf1.png)
