### ISSUE TITLE
REST API do not validate Prototyped APIs with invalid inline scripts

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#1903]
**Description:**
When we are Deploying the API as Prototyped APIs with inline script using the [REST API|https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APICollection#apisPost], it does not validate the inline script therefore, we are allowed to create and update Prototyped APIs with erroneous scripts with REST API.
Public JIRA : https://wso2.org/jira/browse/APIMANAGER-6017

**Suggested Labels:**
2.1.0, 2.x.x
**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
