### ISSUE TITLE
A title is not showing properly in API Publisher sidebar

### ISSUE THREAD

**Issue by ashensw** [wso2/product-apim#1905]
**Description:**
A title is not showing properly in API Publisher sidebar as below.

![apim](https://user-images.githubusercontent.com/13478571/33374130-dbc8aa72-d52a-11e7-9177-853c035e2e30.png)

**Suggested Labels:**
2.1.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0 WUM updated pack (29th Nov 17)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
This has been fixed with referenced to the similar issue https://github.com/wso2/product-apim/issues/2218.
PR https://github.com/wso2/carbon-apimgt/pull/4904 contains the fix for this.

**Comment by ChamNDeSilva** [comment]
fix merged. Hence resolving the issue.
