### ISSUE TITLE
[AMHACK] Incorrect percentages appearing in stats for the number of API invocations per API versions

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1906]
**Description:**
Incorrect percentages appearing in stats for the number of API invocations per API versions

**Suggested Labels:**
Bug
APIM Publisher

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre -requisites
1. Several APIs with versions
2. API invocations should be available

**Steps to reproduce:**
1. Go to Publisher console -> Analytics -> API -> Top API Users section

**Observations**
Incorrect percentage appearing for the number of API calls

ex: There are overall 42 API calls (22 for version 3.0.0 and 20 for 4.0.0) for all these percentages is shown as 100% which is incorrect.
![stat1](https://user-images.githubusercontent.com/14962228/33374104-bdcf4c24-d52a-11e7-873b-46085a544f87.png)

For version 3.0.0 - > it should show the percentage based on the API calls received for the API ( around 52%)
![stats2](https://user-images.githubusercontent.com/14962228/33374108-c2059348-d52a-11e7-9e29-ec22c8f040a1.png)

![stats3](https://user-images.githubusercontent.com/14962228/33374109-c555db98-d52a-11e7-9c21-a347d6221f12.png)

**Comment by chamilaadhi** [comment]
Hi,
This percentage value shows the percentage each user did for that particular api (not the percentage amonge all versions). 

For example, User Shakila has done 20 requests for the version 4.0.0 and there are no other users done any requests for this version. So all the requests are done by shakila. that is 100% of the request. If there is another user called version 4.0.0, then the % value will be divided among them. See below image for two users

![Screen Shot 2019-09-12 at 10 30 45 AM](https://user-images.githubusercontent.com/4861150/64755536-dd611700-d548-11e9-93af-f13bca49bdca.png)
