### ISSUE TITLE
[AMHACK] API Last Access Time table consists some junk values in the headings

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#1907]
**Description:**
In "API Last Access Times (Across All Versions)" table found under "Analytics" section observed few junk values in the table headings. Please refer attachment.
![table](https://user-images.githubusercontent.com/17248809/33374376-f13f7862-d52b-11e7-9745-c6f18abdfede.png)

**Suggested Labels:**
Improvement

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics pack wum updated - wso2am-analytics-2.1.0.1511528208814.zip

**OS, DB, other environment details and versions:**    
APIM and analytics quick setup
OS - Ubuntu 14
JDK - jdk1.8.0
DB - h2
Browser - Chrome Version 62.0.3202.62

**Steps to reproduce:**

1. Login to APIM publisher portal
2. Navigate to Analytics -> API Last Access Times (Across All Versions) section

**Comment by chamilaadhi** [comment]
Fixed in latest APIM 2.6.0. See below image
<img width="1164" alt="Screen Shot 2019-09-12 at 10 09 35 AM" src="https://user-images.githubusercontent.com/4861150/64754581-81e15a00-d545-11e9-8ac0-8c23941d5ad4.png">
