### ISSUE TITLE
[AMHACK] Incorrect example provided for blacklisting APIs based on API context

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1908]
**Description:**
Incorrect example provided for blacklisting APIs based on API context

**Suggested Labels:**
Bug
APIM Admin console

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre -requisites
1. An API with subscriptions

**Steps to reproduce:**
1. Go to Admin console -> Throttling Policies -> Black list 
2. Add a blacklisting policy as given in the example 
ex: carbon/stock/1.0.0

![screenshot from 2017-11-30 11-12-27](https://user-images.githubusercontent.com/14962228/33415871-8ff60bb8-d5bf-11e7-9649-e2c0b740bc01.png)

**Observations**
1. Recognized the context path as invliad.
```
[2017-11-30 11:09:25,245] ERROR - condition-edit:jag Error occurred while adding conditions:  Couldn't Save Block Condition Due to Invalid API Context carbon/stock/1.0.0

```
![screenshot from 2017-11-30 11-15-01](https://user-images.githubusercontent.com/14962228/33415983-26d9e6d0-d5c0-11e7-9038-a214818058df.png)

2. Context should be given with "/" (ex: /carbon/stock/1.0.0 )

Note - Example should be corrected
![screenshot from 2017-11-30 11-15-10](https://user-images.githubusercontent.com/14962228/33415988-2e1e8928-d5c0-11e7-8f67-2c8025657509.png)

**Comment by dewmini** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/94c782471820a7aa5970643c9246c890f3bfbe6d
