### ISSUE TITLE
[AMHACK][UI] Error message does not contain required spaces between hard-coded content and parameterized values

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1909]
**Description:**
Error message does not contain required spaces between hard-coded content and parameterized values

**Suggested Labels:**
Bug
UI
APIM Admin console

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre -requisites
1. An API with subscriptions

**Steps to reproduce:**
1. Go to Admin console -> Throttling Policies -> Blacklist 
2. Add a blacklisting policy for non-existing application
ex: sashika:StockApplicationtest

**Observations**
1. Error message does not contain relevant spaces between the hardcoded values and parameterized values
```
[2017-11-30 11:27:16,336] ERROR - condition-edit:jag Error occurred while adding conditions:  Couldn't Save Block Condition Due to Invalid Application name StockApplicationtestfrom Application Owner sashika

```
![error](https://user-images.githubusercontent.com/14962228/33416415-5d0eda38-d5c2-11e7-9e9d-7aa71e80b379.png)

**Comment by dewmini** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/94c782471820a7aa5970643c9246c890f3bfbe6d
