### ISSUE TITLE
[AMHACK] Unable to define a blacklisting policy for API calls from a valid IPv6

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#1910]
**Description:**
Unable to define a blacklisting policy for API calls from a valid IPv6

**Suggested Labels:**
Bug
APIM Admin console

**Affected Product Version:**
APIM wum updated - wso2am-2.1.0.1510928473100.zip
APIM analytics - wso2am-analytics-2.1.0.1510935606971.zip

**OS, DB, other environment details and versions:**    
Standalone
Ubuntu 15.10
JDK - jdk1.8.0_66
DB - Postgres 9.6.3
Browser - Chrome Version 58.0.3029.96 (64-bit)

Pre -requisites
1. An API with subscriptions

**Steps to reproduce:**
1. Go to Admin console -> Throttling Policies -> Blacklist 
2. Add a blacklisting policy for with valid ipv6
ex: 2001:0db8:85a3:0000:0000:8a2e:0370:7334

**Observations**
1. IPv6 is not recognized as a valid input when defining the blacklisting policy
![screenshot from 2017-11-30 12-21-09](https://user-images.githubusercontent.com/14962228/33417849-1891e6aa-d5c9-11e7-9ed2-c3a7eda60f6f.png)

**Comment by chamilaadhi** [comment]
IPv6 is not supported at the moment. Please refer to https://github.com/wso2/product-apim/issues/1515 for this feature.
