### ISSUE TITLE
[AMHACK]UI is showing two "valid" message for in url validation

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#1915]
**Description:**
UI is showing two "valid" message for in url validation

**Suggested Labels:**
API creation

**Suggested Assignees:**

**Affected Product Version:**
WSO2 APIM 2.1.0

**OS, DB, other environment details and versions:**    
OS-ubuntu14.04
DB-Mssql 14
Userstore-JDBC
20th Nov WUM updated Pack

**Steps to reproduce:**
Go to the implementation tab 
Enter production and Sandbok url
Click on test button twice
![testbutton](https://user-images.githubusercontent.com/14923354/33425162-e79e6d96-d5e3-11e7-8453-2b1cc76b6631.png)

You will be able to see two valid message for two clicks.(Attached a screenshot)

**Expected results**
It should be one valid message for any number of clicks.

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/4869
