### ISSUE TITLE
[AMHACK] Copying the consumer key/secret is not working via UI icons

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#1916]
**Description:**
See attached.

![copy](https://user-images.githubusercontent.com/15671620/33427451-55cff774-d5eb-11e7-8cd4-e3e9a299b5c3.jpeg)

**Suggested Labels:**
2.1.0
UX

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.1.0
latest wum updated pack

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add an application
- Generate access token and keys
- Copy consumer key/secret using icon => it is not copying

**Comment by chanaka3d** [comment]
Issue is fixed with 059ebe544cb34d95bb95b682ba40b910ffa856de
