### ISSUE TITLE
[AMHACK]API visibility doesn't work as expected

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#1918]
**Description:**
API visibility doesn't work as expected

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0 

**OS, DB, other environment details and versions:**    
OS-ubuntu 14.04
DB-mssql 2014
Userstore-JDBC
20thNovWUM updated Pack

**Steps to reproduce:**
Create 3 tenants call eng.lk,finace.lk,hr.lk
Login to the hr tenant via publisher
Create an API with "public" visibility
Publish this API to the API store.
Login to the API store via eng.lk tenant
you are unable to view the created API.

**Expected Results**
This API is having public visibility, therefore other tenant also should be able to view this API

**Comment by abimarank** [comment]
This is expected behavior. Users from eng.lk tenant should go to ht.lk tenant's store to view APIs. Otherwise, you have to publish APIs to eng.lk store. 

You can check [1]

[1]: https://docs.wso2.com/display/AM210/Publish+to+Multiple+External+API+Stores

**Comment by chalitha87** [comment]
Hi Abimarank,
Since this API contains public visibility, shouldn't it be available for all the tenants?

**Comment by abimarank** [comment]
Public visibility is different from availability. Other tenant users can go to a particular tenant and view the APIs there, that doesn't mean, those APIs should be listed in their own tenant's store.

**Comment by isharac** [comment]
This is the expected behavior.
