### ISSUE TITLE
[AMHACK]No proper message when saving the content in registry

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#1920]
**Description:**
No proper message when saving the content in registry

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**   
OS-ubuntu 14.04
DB-Mssql 14
Userstore-JDBC
20th WUM updated pack 

**Steps to reproduce:**
Edit the external api store.xml file in registry.
When clicking save content button
No proper UI message to say whether contain is saved or not

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
