### ISSUE TITLE
[AMHACK]Overview section Displaying some invalid content in external API stores

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#1921]
**Description:**
Overview section Displaying some invalid content in external API stores

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    
OS- ubuntu 14.04
DB-Mssql 2014
APIM 20th/Nov WUM updated pack

**Steps to reproduce:**
As per [1] configure two API store as external API stores. 
Create a API using Soap endpoint
publish this API to externall API stores.
Go to the overview section of the API in external API store
It is showing wsdl path as WADL
When you click on the link, it will download the wsdl file as undefined.

[1] https://docs.wso2.com/display/AM210/Publish+to+Multiple+External+API+Stores

**Expected Behaviors**
Since this is a soap endpoint,it should be WSDL. not WADL
when you click download, it should download with correct name of the wsdl.
![externalapistores](https://user-images.githubusercontent.com/14923354/33431874-0262391a-d5fc-11e7-9aba-1ecb4f7914fc.png)

**Comment by dushaniw** [comment]
This is fixed in the latest 3.0.0 with https://github.com/wso2/carbon-apimgt/pull/7036. Hence closing the issue.
