### ISSUE TITLE
[AMHACK] Cannot access API store Applications after accessing a API from the API store

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1926]
**Description:**
When trying to access the Applications under API store, gets redirected to the API store login page and Login gets failed

**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2. Login to the API store
3. Go to APIs
4. Select an API
5. Then select Applications from the left menu bar
6. Direct to API store login page
7. Enter username and password
8. Login to the API store gets failed

Expected REsults
Should not ask a login to the API store to access the Applications

**Related Issues:**

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in the latest product update.
