### ISSUE TITLE
[AMHACK] API Store Embed Operations Copy functionality does not work

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1929]
**Description:**
In API Manager store copy functionality related to embed operation does not work.

**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121
**Steps to reproduce:**
1.Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2.Login to the API publisher
3.Create and publish a REST API
4.Login to API store
5.Select the created API 
6.Go to embed option 
7.Click on the copy icon [1]
8.Copy functionality will not work as expected

Expected Results 
The value should be copied
Actual Result
The value is not getting copied

[1]. embed-operation.png

![embed-operation](https://user-images.githubusercontent.com/31848014/33526284-b134bb4c-d864-11e7-88f5-06f9d8cde516.png)

**Related Issues:**

**Comment by bhathiya** [comment]
Duplicate https://github.com/wso2/product-apim/issues/1754
