### ISSUE TITLE
[AMHACK] In API Store there is no option to delete or edit a comment added by a subscriber

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1930]
**Description:**
API Store there is no option to delete or edit a comment added by a Subscriber

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1.Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2.Login to the API publisher
3.Create and publish a REST API
4.Login to API store as a subscriber (user type)
5.Select the created API
6. Add a comment from the comments option
7.There is no option to edit or delete the comment [1]
8.Login to the API store as admin
9.Select the previous API and try to delete the comment
10.There is no option to delete

Expected Results
Subscribers should have a option to edit or delete a comment added by them
Admin should have a option to delete a comment added by a subscriber

Actual Results
Subscribers cannot delete a comment added by them
Admin cannot delete a comment added by a subscriber

[1]. comments.png

![comments](https://user-images.githubusercontent.com/31848014/33526439-a9db8dfa-d867-11e7-8d0b-1da5447935f6.png)

**Related Issues:**

**Comment by chamilaadhi** [comment]
This feature is provided with APIM 3.0.0. Refer https://github.com/wso2/carbon-apimgt/pull/6931
