### ISSUE TITLE
[AMHACK] My Account Change Password option under API Store prompts wrong error messages

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1931]
**Description:**
My Account Change Password option under API Store doesn't provide correct error messages 
**Suggested Labels:** 
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**  
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121  

**Steps to reproduce:**
1. Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2. Login to the APIM management console
3. Create a user from the management console with the role subscriber
4. Login to the API store as the subscriber created in step 3
5. Go for My Accounts option from right hand side upper corner
6. Go for Change password section
7. Input the current password
8. For New password option input a unsecure password ( eg :- abc)
9. Repeat the password under retype password section
10.Bring the cursor on to the retype password text box area 
11. Will prompt a error message as password did not match [1]

Expected Result
Need to prompt a error message saying input a more secure password

Actual Results
Prompt a message as password did not match

[1]. password-change.png

![password-change](https://user-images.githubusercontent.com/31848014/33526707-195e9246-d86b-11e7-88f0-f3178b86bdbd.png)

**Related Issues:**

**Comment by Krishanx92** [comment]
This is not valid in 3.0.0, hence resolved.
