### ISSUE TITLE
[AMHACK] Import functionality under Design phase in API creation allows to upload any file type

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#1932]
**Description:**
Import functionality under Design phase in API creation allows to upload any file type

**Suggested Labels:**
Bug
**Suggested Assignees:**

**Affected Product Version:**
APIM WUM Updated - wso2am-2.1.0.1510585460470

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Run the APIM 2.1.0 Wum updated pack (wso2am-2.1.0.1510585460470)
2. Login to the API publisher
3. Select Add API and select REST API option
4. Under the Design phase click on Import
5. Select swagger file
6. Browse and select a file type that is not relevant for here (eg :- .jpg)
7. Allow to import the file without showing a error message

Expected Results
Should have a proper validation to upload only suitable files. Need to give a error message when a non relevant file is uploaded

Actual Results
Allows to upload any format of a file without prompting a error message

**Related Issues:**

**Comment by chamilaadhi** [comment]
Fixed in AM 2.6.0. Please check the following popup error message for this issue
![Screen Shot 2019-09-12 at 10 51 26 AM](https://user-images.githubusercontent.com/4861150/64756136-624d3000-d54b-11e9-99c1-0cf334be1cd9.png)
