### ISSUE TITLE
User and PRIMARY/User login treat as two users at the store

### ISSUE THREAD

**Issue by prabushi** [wso2/product-apim#1940]
**Description:**
We can login to primary domain using both **username** and **PRIMARY/username** with the same password. But at the store, they will be shown as two users. Applications created at username login will not be listed at PRIMARY/username login. User logged in shown (session user at login) at the store is username and PRIMARY/username respectively.

But for the secondary domain, both login using sec-user and DOMAIN/sec-user treat as the same user. Applications created at either login will appear in the application list for both logins. And, the session user at login will always be DOMAIN/sec-user for both logins.

Issue is with the session user at primary domain login. It works fine for secondary domain.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a user for the primary domain (user1)
2. Login to store as user1 and create an application.
3. Then, login to store as PRIMARY/user1 with the same password. Created application is not come under the application list.

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
