### ISSUE TITLE
Multi part form-data file uploading is getting failed in API Manager

### ISSUE THREAD

**Issue by anuruddhal** [wso2/product-apim#1947]
**Description:**
Multi-part form-data file uploading is getting failed in API Manager when the message is mediated due to following reasons:
1. File content is base64 encoded.
2. Filename="sample1.txt"[\r][\n]" attribute is missing.

**Suggested Labels:**

Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 1.10.0

**OS, DB, other environment details and versions:**    
Any OS, Any DB

**Steps to reproduce:**
1. Create a REST API with mock backend.
2. Add the below sequence as in-sequence for the created API.
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse"
          name="admin--SR-Document:v1.0--In"
          trace="disable">
   <property xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"
             xmlns:ns3="http://org.apache.synapse/xsd"
             name="accept"
             expression="$trp:accept"
             scope="default"
             type="STRING"/>
   <header name="Cookie" scope="transport" action="remove"/>
   <property name="Authorization" scope="transport" action="remove"/>
   <property xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"
             xmlns:ns3="http://org.apache.synapse/xsd"
             name="httpMethod"
             expression="$axis2:HTTP_METHOD"
             scope="default"
             type="STRING"/>
   <property xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"
             xmlns:ns3="http://org.apache.synapse/xsd"
             name="REST_URL_POSTFIX"
             expression="concat('/Document/Tags','?id=test')"
             scope="axis2"
             type="STRING"/>
</sequence>
```
3. Enable wire logs and invoke the API with multi-part form data message with a file attachment.
4. The outgoing message from APIM to backend will be changed like following.
- File content is base64 encoded.
- Filename="sample1.txt"[\r][\n]" attribute is missing.

**Related Issues:**

**Comment by isurulucky** [comment]
Fixed with https://github.com/wso2-support/wso2-axis2/pull/39 and https://github.com/wso2-support/wso2-synapse/pull/234.
