### ISSUE TITLE
Sharing React components between apps

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1968]
**Description:**

- Need to come up with a mechanisum to share common React component such as [Login](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Login/Login.js)  , [Message](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/components/Shared/Message.js)
- In same way need a mechanism to share common libraries (i:e [APIClient](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js), [User](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/User.js)) (to make it simple not through NPN package.json)

**Affected Product Version:**
 APIM 3.0.0

**Comment by chanaka3d** [comment]
This is addressed with the 3.2.0 release. Now we have a way to share components between the apps.
