### ISSUE TITLE
Adding additional meta-data/properties to API

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#1969]
**Description:**
Currently we have a pre-defined set of properties for an API. We do not have a way to add custom properties to API.  However there may a requirement to add custom properties to API, based on the different requirements of API creators. 

**Suggested Labels:**
Features, APIM 2.2.x

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.1.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
N/A

**Related Issues:**
https://redmine.wso2.com/issues/6339

**Comment by Megala21** [comment]
Please find the user-story document for this feature https://docs.google.com/a/wso2.com/document/d/1Pni-DZ9WdkWUrGO0Ad-pvyxA3aSLHG3UPxA4So0wy60/edit?usp=sharing

**Comment by Megala21** [comment]
Documentation for this feature - https://docs.google.com/a/wso2.com/document/d/14Oijrt5UTr4HnVyu9xX3hqhmfpvDKA7BjmAJDw7aJ68/edit?usp=sharing

**Comment by anuruddhal** [comment]
Doc link:
https://docs.wso2.com/display/AM2xx/Adding+Custom+Properties+to+APIs
