### ISSUE TITLE
Display scope list in API console

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#1974]
**Description:**
The scope name-key mapping should be displayed under each resource in API console

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Arshardh** [comment]
We found a way to achieve this use case by enabling the showExtensions property of the swagger UI.
This displays all the vendor extensions added per resource.

**But we will have to rethink this and implement a better version in the next release, similar to the way we have displayed scope information in Swagger 2.x.**

**Comment by Arshardh** [comment]
This can be tracked by the new issue: https://github.com/wso2/product-apim/issues/5039
