### ISSUE TITLE
[Store] when login redirect to /store/applications page throws an error

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#1978]
**Description:**
When login redirect to the following URL throws a ` 401 (Unauthorized)` error even redirect to it after successful login

> `https://<host>:<port>/store/login?referrer=%2Fapplications`

Following are the browser exceptions

> GET https://localhost:9292/api/am/store/v1.0/applications?limit=25&offset=0 401 (Unauthorized)
a @ index.js?8571:1
a @ index.js?8571:1
execute @ index.js?8571:1
(anonymous) @ index.js?8571:1
(anonymous) @ Application.js?9f7a:127
Promise resolved (async)
all @ Application.js?9f7a:125
componentDidMount @ Listing.js?960d:99
(anonymous) @ ReactCompositeComponent.js?d2b3:264
measureLifeCyclePerf @ ReactCompositeComponent.js?d2b3:75
(anonymous) @ ReactCompositeComponent.js?d2b3:263
.
.
.
Listing.js?960d:105 Error: Unauthorized
    at eval (index.js?8571:1)
    at <anonymous>

> Listing.js?960d:112 Uncaught (in promise) ReferenceError: qs is not defined
    at eval (Listing.js?960d:112)
    at <anonymous>
(anonymous) @ Listing.js?960d:112
Promise rejected (async)
componentDidMount @ Listing.js?960d:104
(anonymous) @ ReactCompositeComponent.js?d2b3:264
measureLifeCyclePerf @ ReactCompositeComponent.js?d2b3:75
(anonymous) @ ReactCompositeComponent.js?d2b3:263
notifyAll @ CallbackQueue.js?f006:76
.
.
.
batchedUpdates @ ReactDefaultBatchingStrategy.js?e9be:62
batchedUpdates @ ReactUpdates.js?8e6b:97
dispatchEvent @ ReactEventListener.js?944f:147

Things get resolved after a page refresh

**Affected Product Version:**
 - APIM 3.0.0-M9

**Steps to reproduce:**

- Logout from API Manager Store if you are already logout
-  Try to access `https://<host>:<port>/store/applications` page
- Give valid username and password when redirect to login page, and log in to Store app
- Once you log in and redirect to `/store/applications` page, it will show continues loading animation but no Applications will list
- Check the Browser console and will see above error messages

**Comment by tmkasun** [comment]
As shown below this could be because of the missing `authorization: Bearer` header value in API request
![image](https://user-images.githubusercontent.com/3313885/33868079-e6ea8c08-df26-11e7-8d70-25aa28db82ac.png)

**Comment by chanaka3d** [comment]
Fixed with 3.2.0 and checked with carbon-apimgt 6.8.42-SNAPSHOT
