### ISSUE TITLE
gateway packs LICENSE file contains some jar names that is no there in the pack 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#1991]
**Description:**
Need to verify the LICENSE.txt content with the files actually shipped in the pack 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
Updated gateway pack license https://github.com/wso2/product-apim/pull/2040/commits/61c999cb179ef4e8cb59caba9d64282cfbf9549a
