### ISSUE TITLE
in gateway pack samples folder need to ship with a README file 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#1994]
**Description:**
It is hard to understand what to do with the samples shipped with the pack 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
In the gateway we can't ship standalone samples. APIs are deployed in the gateway need to have subscription and by default authentication layer get invoked. Because this is impossible and samples need to be provided only with APIM core server.
Hence close the issue by removing ballerina samples.
