### ISSUE TITLE
gateway pack needs to ship sample source, only binaries are available

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#1995]
**Description:**
If I am to modify and play with samples I need the source. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
In the gateway we can't ship standalone samples. APIs are deployed in the gateway need to have subscription and by default authentication layer get invoked. Because this is impossible and samples need to be provided only with APIM core server.
Hence close the issue by removing ballerina samples.
