### ISSUE TITLE
Where is the documentation for samples shipped in the gateway pack? 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#1996]
**Description:**
Where can I find the docs? Should we not ship samples with its own folder and a README for each? 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
In the gateway we can't ship standalone samples. APIs are deployed in the gateway need to have subscription and by default authentication layer get invoked. Because this is impossible and samples need to be provided only with APIM core server.
Hence close the issue by removing ballerina samples.
