### ISSUE TITLE
wso2apim-3.0.0-m10: LICENSE file does not list jar licenses in the pack 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#2001]
**Description:**
license details for jars that come packed in is missing from LICENSE file

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
added product license https://github.com/wso2/product-apim/pull/2040/commits/a29a3744dfdc2f35ab126717801116208bfb1640
