### ISSUE TITLE
wso2apim-3.0.0-m10: bin/README.txt has no useful content 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#2005]
**Description:**
Does not explain how to run using the executables in there. 

Does not explain each file in bin 

Also has
${product.name} v${product.version}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
Hi @samisawso2 

Fixed the issue with "${product.name} v${product.version}" with https://github.com/wso2/product-apim/commit/0d1b3595b6cdcc8ed3cffb2f7d4740dd1f16bc0a

The file already contains information about each executable in the /bin folder.
```
WSO2 API Manager v3.0.0


This file explains the usages of all the scripts contained within
this directory.

1. README.txt
    - This file

2. kernel-version.txt
    - A simple text file used for storing the version

3. jartobundle.sh & jartobundle.bat
    - The script file which runs the org.wso2.carbon.jartobundle-tool.jar tool.

    - This tool is capable of converting specified jar files to their corresponding OSGi bundles.

    Usage: jartobundle.sh [source] [destination]

        -- source       source jar file/directory path containing jar file(s) to be converted to
                           OSGi bundle(s)

        -- destination  destination directory path in which the OSGi bundles are to be created

4. osgi-lib.sh & osgi-lib.bat
    - The script files which run the OSGi-Lib deployer tool.

    - This tool updates the bundles.info file of the specified Carbon Runtime.

    Usage : osgi-lib.sh [runtime]

        -- runtime      name of the Carbon Runtime to be updated or keyword 'ALL' to update all the runtimes.
```

Please reopen and let us know if there are any changes need to be done.
