### ISSUE TITLE
Publisher REST API issue when creating an API

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2051]
**Description:**
- Can't provide additional API information other than name, version, and context when calling `/apis` in `POST` method.
- When did a GET on newly created API it seems other API properties are got ignored

**Affected Product Version:**

- APIM 3.0.0-m11

**Steps to reproduce:**

-

**Comment by tgtshanika** [comment]
Cannot reproduce with APIM 3.0.0
