### ISSUE TITLE
[Doc] Include images to show the overview of API publisher and Store

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2071]
Refer to doc link [1]. Include some screenshots under Accessing API publisher and Accessing API store to show the overview of the API store and API publisher

[1]. https://docs.wso2.com/display/AM300/Quick+Start+Guide

**Comment by bhathiya** [comment]
Please use correct version label always.

**Comment by ShanikaWickramasinghe** [comment]
Will update the GIT issues with correct labels once the write access is granted
