### ISSUE TITLE
[Doc] Should issues be reported against both carbon-apimgt & product-apim

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2074]
**Description:**
The doc [1\] points to carbon-apimgt for a list of open issues but we have issues raised issues under product-apim [2\]. 

Do we allow to add issues to both repos? If so please update it in the doc as well with what type of issues should go to which repo.

[1\] [https://docs.wso2.com/display/AM300/About+this+Release](https://docs.wso2.com/display/AM300/About+this+Release)

[2\] [https://github.com/wso2/product-apim/issues](https://github.com/wso2/product-apim/issues)

**Suggested Labels:**
Doc, APIM 3.0.0

**Comment by pubudu538** [comment]
Hi Jason,

Thank you for pointing out.Please create issues only in product-apim repo. We will fix the documentation issue. 

Thank you!
Pubudu.

**Comment by pubudu538** [comment]
This is fixed now.
