### ISSUE TITLE
Pressing enter in console when api manager is running brings out osgi console

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2091]
**Steps**
1. Start api manager by <API-M_HOME>/wso2/default/bin/carbon.sh
2. Press enter in console once server started.

Goes to osgi console. Is this relevant to show as the user is not specifically connecting to it? Furthermore due to this when trying to exit from the osgi console, the server gets stopped

**Comment by bhathiya** [comment]
In 3.0 the behavior is not this. Hence closing.
