### ISSUE TITLE
[Doc] API Publisher does not support API version as a input field But document mention API version as a input field

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2093]
**Suggested Labels:**
APIM 3.0.0
**Description:**

Refer to Doc [1]. Under step 3 it mention version as a input field. But in the API publisher UI it mention as Version input not supported in this release [2]. If it is not supported please mention that in the document

[1]. https://docs.wso2.com/display/AM300/Create+and+Publish+an+API
[2]. version-ui.png
![version-ui](https://user-images.githubusercontent.com/31848014/34482641-50f045d4-efdf-11e7-8732-2675f5b16d29.png)

**Comment by tgtshanika** [comment]
This is invalid for APIM 3.0.0
