### ISSUE TITLE
[Store] Non functioning button in store login page

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2095]
**Description:**
When navigating to APIM Store login page there is a button as "GO BACK" which does not function. IMO it is not needed.

**Suggested Labels:**
APIM 3.0.0 M11, Bug

**Affected Product Version:**
APIM 3.0.0 M11

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by CrowleyRajapakse** [comment]
Irrelevant with the new login pages
