### ISSUE TITLE
Production and sandbox endpoints are not visible in overview

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2098]
OS: Ubuntu 16.04
JDK: 1.8.0_144
Browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
Pack: Milestone 11

**Steps**
1. Create an api
2. Go to overview

As shown below the production, sandbox endpoints are not visible.

**Comment by HiranyaKavishani** [comment]
This is not reproduced in currently
