### ISSUE TITLE
Specify the responsibility of Identity Server when installing APIM 3.0.0

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2106]
**Description:**
Document: [Installation Guide](https://docs.wso2.com/display/AM300/Installation+Guide)
Section: Prerequisites

Specify or provide reference the job of Identity Server when installing APIM300

**Affected Product Version:**
APIM300

**Comment by nuwand** [comment]
Usage of the Identity Server is a temporary measure until we have our own Identity Layer built on top of the Carbon 5 kernel. The component descriptions listed in [1] explain the role of the Key Manager, which is what the Identity Server is temporarily satisfying.

[1] - https://docs.wso2.com/display/AM300/Architecture
