### ISSUE TITLE
Invalid Current State in publisher lifecycle

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2111]
**Description:**
Invalid Current State in publisher's API lifecycle section once run the sample-scenario 7
_Note: we have a custom lifecycle state in this sample_

**Affected Version**
2.1.0-update4

**Steps to reproduce:**
1. Run the sample-scenario 7
2. Go to the publisher and click on the API Sales_promotions_API - 1.0.0

Lifecycle view is not correct with the state but lifecycle history captures the state change correctly. 
please see the below image.
![image](https://user-images.githubusercontent.com/7115693/34506001-04a8334c-f04f-11e7-884d-dcb3078b23ee.png)

**Comment by prasa7** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/5302

<img width="1329" alt="screen shot 2018-06-12 at 8 27 10 am" src="https://user-images.githubusercontent.com/805274/41267816-ab4332ee-6e1a-11e8-9fe0-417f2e1aa668.png">
