### ISSUE TITLE
Subscription column name appears as null on Versions section in the publisher

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2112]
**Description:**
Column name shows as null in the 'API Subscriptions by Versions' table in Versions section in the publisher

**Affected Product Version:**
2.1.0-update4

**Steps to reproduce:**
1. Run sample-scenario 7
2. Go to the publisher and click on Sales_promotions_API - 2.0.0 API
3. Click on Versions tab

![image](https://user-images.githubusercontent.com/7115693/34506402-5c22c18e-f052-11e7-9d76-485d71d154a4.png)

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in latest product pack.
