### ISSUE TITLE
[DOC] [AM220] Given url link in content should direct to proper content of relevant page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2118]
**Description:**
Url link given at page [1] content (see attached) is not navigated to proper content. It should go to view of API-Level throttling content at relevant page[2].

**Suggested Labels:**
APIM-2.2.0
documentation
Type/improvement

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
![link1](https://user-images.githubusercontent.com/15671620/34509729-51f60b96-f073-11e7-860f-c4fca3f2c4ca.jpeg)

[1] [https://docs.wso2.com/display/AM2xx/Introducing+Throttling+Use-Cases]
[2] [https://docs.wso2.com/display/AM2xx/Setting+Throttling+Limits#SettingThrottlingLimits-API-levelthrottling(APIpublisher)]

**Comment by taniamahanama** [comment]
Fixed.
