### ISSUE TITLE
Cannot find documentation for API Monetization and Rate Limiting

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2121]
Searched APIM 3.0.0 document space with string "api monetization" and the attached result set came that does have a direct link to the search. In 2.1.0 space there is [1] but the same documentation cannot be found in APIM 3.0.0 space. Please provide documentation on how to build up the API monetization use case with APIM 3.0.0

![apim_doc_issue_3](https://user-images.githubusercontent.com/15624590/34510464-23e09d32-f07a-11e7-9d6e-62e2a79e1a57.png)

[1] https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs

Furthermore same problem exists for API rate limiting documentation as well.

**Comment by npamudika** [comment]
Refer https://github.com/wso2/product-apim/issues/3889 for the Documentation updates regarding the monetization feature in APIM 2.6.

**Comment by npamudika** [comment]
Closing this issue as we will be discussing the same in https://github.com/wso2/product-apim/issues/3889
