### ISSUE TITLE
[DOC] [AM220] Correct all the alignment issues at the sample-scenario "Governance" page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2122]
**Description:**
Please update the doc page in [1] for $subject. 
- unecessary spaces between paragraphs
- image alignments
- user data font size can be small

**Suggested Labels:**
APIM-2.2.0
Document
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
[1]  [https://docs.wso2.com/display/AM2xx/API+Governance]

**Comment by taniamahanama** [comment]
Fixed
