### ISSUE TITLE
[DOC] [AM220] Navigation link for 'change statistics datasource' should be point to own version of doc page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2124]
**Description:**
Please correct the doc page [1] at step.4 for $subject (see attached).

**Suggested Labels:**
APIM-2.2.0
Document

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
[1] [https://docs.wso2.com/display/AM2xx/Configuring+APIM+Analytics]

![link2](https://user-images.githubusercontent.com/15671620/34510660-d8e62926-f07b-11e7-8ec8-6261a46d9404.jpeg)

**Comment by taniamahanama** [comment]
Fixed.
