### ISSUE TITLE
App Lifecycle usecase is not clear enough in the sample-scenario document

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2133]
**Description:**
We have mentioned the use case "App lifecycle management mechanisms in sync with API lifecycle management" in [1] but its not clear on how we capture this in the sample-scenario(scenario07). Have we really captured this part from the sample?
[1] https://docs.wso2.com/display/AM2xx/API+Lifecycle+Management

![image](https://user-images.githubusercontent.com/7115693/34514891-8d56ad68-f095-11e7-97d7-e82f3434f32f.png)

**Comment by chamindias** [comment]
Hi,

Yes. This reflects the changes in API W.R.T to the app as well. Eg : When the API is "blocked", subscribers cannot invoke it. When it is "unblocked", they can use it again. If we "retire" the API, subscription will also be removed as well. Etc..

Answered, hence resolving.
