### ISSUE TITLE
[AM220] [Bug]Thread "main" org.wso2.carbon.apimgt.samples.utils.publisher.rest.client.ApiException thrown when running API Versioning Sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2136]
**Suggested Labels:**
APIM 2.2.0
Bug

**Environment**
Standalone
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**
1. Run wso2am-2.1.0-update4 pack
2. Navigate to  [APIM_HOME]/sample-scenarios
3. Run sh run.sh command
4. Input no 8 to run API versioning sample

**Observation**
Following error [1] was thrown in the backend when trying to run scenario 8 API versioning sample. Please note that such a issue is not encounted when trying to run a different sample eg :- scenario 7

[1]. versioning-sample-bug.png

![versioning-sample-bug](https://user-images.githubusercontent.com/31848014/34516322-7d8008ec-f09c-11e7-8841-77c00e65e6c6.png)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
