### ISSUE TITLE
API Development: grammar mistake in use case section

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2142]
Please see the below sentence in [1] . This is grammatically wrong. Please correct it to reflect correct grammar

Selected APIs **should be** able to share with different business units (edit and view)

[1] https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Documentation

**Comment by erandidesilva** [comment]
Below the sentence is talking about departments, hence the sentence should change as given below
**Actual:**
Let ABC organisation is an organisation that has separate departments for finance and operations other than their core business department which is **mobile phone manufacturing**(manufacturing department)

**Expected:**
Let ABC organisation is an organisation that has separate departments for finance and operations other than their core business department which is **manufacturing department which manufactures mobile phones**

**Comment by erandidesilva** [comment]
Following sentence is grammatically wrong. Please correct it.

Actual:
Let the finance department handle salaries of employees while manufacturing department is **responsible to maintain** the mobile phone manufacturing stock while operations department handles maintenance work of the organization

**Comment by ChamNDeSilva** [comment]
Fixed.
