### ISSUE TITLE
API Development: grammar mistake in Business story section

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2143]
Please see the below sentence in [1]. This is grammatically wrong. Please correct the grammar

Let ****ABC organisation** is an organisation** that has separate departments for finance and operations other than their core business department which is mobile phone manufacturing(manufacturing department).

[1] https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Documentation

**Comment by ChamNDeSilva** [comment]
Page not found.
Please provide the correct link to the docs.

**Comment by erandidesilva** [comment]
Please check with the documentation team. The document may have been moved

**Comment by ChamNDeSilva** [comment]
Fixed in https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Sample+Documentation
