### ISSUE TITLE
API Development: Mixed case heading which doesn't adhere to a uniform mixing of cases

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2144]
Please see below in [1]. The following sentence is a mixed case sentence, but doesn't have a uniformity. Please correct

How this Business Scenario **can be achieved** Using WSO2 API Manager ?

[1] https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Documentation

**Comment by ChamNDeSilva** [comment]
Fixed
