### ISSUE TITLE
Include upgrading information from 2.1.0 to 2.2.0 in documentation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2146]
In [1] the latest available upgrade is from 2.1.0 to 2.2.0. Can we please include the details on upgrading from 2.1.0 to 2.2.0 as well in [1] since this seems to be a common document for APIM 2 series

[1] https://docs.wso2.com/display/AM2xx/Upgrading+from+the+Previous+Release

**Comment by ChamNDeSilva** [comment]
This will be documented when the migration client is implemented which will be released with the official release of API Manager 2.2.0

**Comment by taniamahanama** [comment]
Added an explanation and linked to the 2.2.0 upgrade instructions.
https://docs.wso2.com/display/AM2xx/Upgrading+from+the+Previous+Release
