### ISSUE TITLE
Documentation bugs in API Lifecycle Management section

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2147]
**Description:**
Following typo and unnecessary linen spaces can be noticed on the API Lifecycle Management section[1]
[1] https://docs.wso2.com/display/AM2xx/API+Lifecycle+Management

![image](https://user-images.githubusercontent.com/7115693/34550413-af52a40c-f136-11e7-848a-d5c212d32b91.png)
![image](https://user-images.githubusercontent.com/7115693/34550415-b204aba0-f136-11e7-8287-f8e19dd09aca.png)
![image](https://user-images.githubusercontent.com/7115693/34550418-b48cf364-f136-11e7-89ac-18de21f335c6.png)
![image](https://user-images.githubusercontent.com/7115693/34550419-b8ef3c32-f136-11e7-835b-4f6b3817f1d4.png)

**Comment by taniamahanama** [comment]
Fixed
