### ISSUE TITLE
[AM220] [Doc] Wrong Title under API versioning section

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2149]
**Suggested Labels:**
APIM 2.2.0

**Description:**
Refer to doc link [1]. Change the heading of the second image from " Old API in PUBLISHED state " to " New API in PUBLISHED state" [2]

[1]. https://docs.wso2.com/display/AM2xx/API+Versioning
[2]. new-api.png
![newapi](https://user-images.githubusercontent.com/31848014/34550596-48a412b6-f138-11e7-9aa4-6982b0e48fd5.png)

**Comment by taniamahanama** [comment]
This has already been fixed.
