### ISSUE TITLE
[AM220] [Doc] Add a reference for A/B Testing

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2150]
**Suggested Labels:**
APIM 2.2.0

**Description:**
Refer to doc link [1]. Add a note on what is refereed as A/B testing under API versioning use case section 

[1]. https://docs.wso2.com/display/AM2xx/API+Versioning

**Comment by ChamNDeSilva** [comment]
Fixed https://docs.wso2.com/display/AM2xx/API+Versioning
