### ISSUE TITLE
API Development: Tenant user permissions

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2151]
In [1] it states to create tenant users but no specific permission details are given. Please include the respective permission that the user should have. 

[1] https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Documentation

**Comment by chamindias** [comment]
In [Managing Tenants](https://docs.wso2.com/display/AM2xx/Managing+Tenants), it mentions that the user should have super user permissions in order to create a tenant.
