### ISSUE TITLE
Tenant creation: Include information on default "demo" usage plan and how to customize 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2152]
In [1] it explains the field usage plan for a tenant but does not include information on the default plan that exists which is "demo". Also information should be included how to change the plan if needed.

[1] https://docs.wso2.com/display/AM2xx/Managing+Tenants

**Comment by ChamNDeSilva** [comment]
Added information about the default plan in following docs.
https://docs.wso2.com/display/AM200/Managing+Tenants
https://docs.wso2.com/display/AM210/Managing+Tenants
https://docs.wso2.com/display/AM2xx/Managing+Tenants

Note that adding customized plans other than demo is no longer supported.
