### ISSUE TITLE
Tenant creation: Include information on mandatory and optional fields

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2153]
In [1] there is no indication of the mandatory and optional fields when creating a tenant. Please include that information in [1] 

[1] https://docs.wso2.com/display/AM2xx/Managing+Tenants

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.

https://docs.wso2.com/display/AM210/Managing+Tenants
https://docs.wso2.com/display/AM2xx/Managing+Tenants
