### ISSUE TITLE
Unable to login to store when navigated to login page from download sdk.

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2154]
**Description:**
Unable to login to store when navigated to login page from download sdk.

![sdklogin](https://user-images.githubusercontent.com/17248809/34551066-1c61ce2e-f13c-11e7-9e51-cca5e2afe5f0.png)

**Suggested Labels:**
APIM 2.1.0 update 4 , Bug, Priority/High Severity/Major 

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Steps to reproduce:**

1. Create an API and publish it
2. Go to store and click on the API (do not login to store)
3. Click on SDKs
4. Click on java or android
5. Provide valid credentials to the login page

**Issue**
Cannot login to store and no validation message is shown for incorrect login credentials.

**Comment by chamindias** [comment]
Checked in the latests pack. Issue does not exists. Hence resolving the issue.

Note : You will be [redirected to the login page](https://docs.wso2.com/display/AM2xx/Generating+SDKs) if you try to download SDK without login. After a successful login (i.e - with valid credentials), you can download it.
