### ISSUE TITLE
Tenant creation: Filter tenant using domain name

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2155]
In [1] the 3rd point discusses on filtering tenants using their domain name. Appreanlty since domain name is unique, entering the full domain name should only return one tenant. if a regex is entered then there can be a result set. The document way of explaining this is too generic and the reader may get the impression that he/she can search many tenants under a given domain name. Please change the wording so that it reflects the correct search mechanism

[1] https://docs.wso2.com/display/AM2xx/Managing+Tenants

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM200/Managing+Tenants
https://docs.wso2.com/display/AM210/Managing+Tenants
https://docs.wso2.com/display/AM2xx/Managing+Tenants
