### ISSUE TITLE
[AM220] Copying elements at store->application->generate keys page are not working via UI

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2158]
**Description:**
Copying elements (all available) at store->application->generate keys page is not working via UI

**Suggested Labels:**
APIM-2.2.0
Type/bug
UX
Priority/Highest
Seveority/minor

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create an application
- View/Edit
- Generate key (production / sandbox) tab
- Copy any of elements by click the copy symbol

**Related Issues:**

**Comment by tharikaGitHub** [comment]
This issue cannot be reproduced in latest 2.2.0 Update.
