### ISSUE TITLE
[AM220] [Doc] Documentation bugs under API versioning

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2159]
**Suggested Labels:**
APIM 2.2.0

**Description:**
Refer to the document link [1]. 

Available Sentences                                                           Expected Sentences 
there may be uses who are using the old API                    there may be users who are using the old API

Users the Old APi should know                                          Users of the Old API should know 

[1]. https://docs.wso2.com/display/AM2xx/API+Versioning

**Comment by taniamahanama** [comment]
This has already been fixed.
