### ISSUE TITLE
Cannot create an API without having 'apiDefinition' optional field

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2162]
**Description:**
Trying to add an API providing only the mandatory fields for the REST API [1]. According to [2] apiDefinition is an optional field.
But getting the response as 400 Bad Request and claim that the apiDefinition cannot be null.

[1] https://localhost:9443/api/am/publisher/v0.11/apis
[2] https://docs.wso2.com/display/AM210/apidocs/publisher/index.html#!/models#API
![image](https://user-images.githubusercontent.com/7115693/34551448-f2c53084-f13f-11e7-8571-9d9991c45eef.png)

**Steps to Recreate:**
1. Invoke [POST]/api/am/publisher/v0.11/apis API with the payload in below.
```
{
   "name": "TestAPIfromREST",
   "description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
   "context": "/apifromrest",
   "version": "1.0.0",
   "isDefaultVersion": false,
   "type": "HTTP",
   "transport":    [
      "http",
      "https"
   ],
   "tiers": ["Unlimited"],
   "visibility": "PUBLIC",
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\",\"config\":null},\"endpoint_type\":\"http\"}"
}
```
**Actual:**
Getting 400 Bad Request
"description": "Parameter: \"apiDefinition\" cannot be null",

**Expected**
User should be able to add an API without providing optional fields

**Comment by chamindias** [comment]
"apiDefinition" should not be optional. We need to fix this and regenerate the REST API docs.

**Comment by ruthryi** [comment]
Updated the following with the corrected parameter : 

[1] https://docs.wso2.com/display/AM2xx/apidocs/publisher/index.html#!/models#APIDetailed

**Comment by isharac** [comment]
Please update [1], [2] as well.

[1]https://docs.wso2.com/display/AM210/apidocs/publisher/index.html#!/models#API
[2]https://docs.wso2.com/display/AM220/apidocs/publisher/index.html#!/models#API

**Comment by memorais** [comment]
It seems that apiDefinition optional is the right thing. If I'm publishing an SOAP web service, what suppose to be the apiDefinition for that? For that case it should be possible to use empty API definition.

**Comment by RakhithaRR** [comment]
This issue is not present in API-M v3.0.0
_apiDefinition_ is not required in Publisher v1.0 to add an API.
