### ISSUE TITLE
API Delete: The deleting in-progress message doesn't get cleared even when the api is deleted

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2166]
Environment
OS: Ubuntu 16.04
JDK: Oracle 1.8.0_144
DB: Mysql ( carbon and apimgt databases only)

Note: Super administrator credentials are changed as mentioned in [1]

Steps
1. Log in to publisher from tenant publisher / tenant admin
2. Create API -> created state
3. Delete API

As shown in the below image the message is kept prolonged without being closed when the api is deleted. The user has to specifically refresh the page to see whether the api is deleted successfully

![apim_issue_2](https://user-images.githubusercontent.com/15624590/34552365-016a2aa2-f147-11e7-946a-f55bacd5dd9a.png)
 

[1] https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in the latest wum-update. (2.1.0-update-8)
