### ISSUE TITLE
[Improvement] API Store once password is changed better to log the user out

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#2167]
Description:
API Store User Profile behaviour needs improvement. Currently once a logged in user changes password successfully the user is kept at that page. However it will be better if the user can be directed back to the landing page

Two issues noted
1.Issue one
Once a logged in user changed password the system displays [1] but better would be to show [2]

[1] current message
"User password changed successfully. You can now sign in to the API store using the new password."

[2]Suggestion
"User password changed successfully. Please use the new password on next sign in"

2.Issue two
Better to direct the user to the API list page rather than keeping the user on the change password screen.

**Comment by chanaka3d** [comment]
I think it's bad UX to logout the user and let the user go through the extra trouble. Other suggestions can be done.
