### ISSUE TITLE
API Development Public, Partner, Private Sample: Provide instructions on trying out the sample

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2169]
In [1] there are no instructions in how to invoke the sample apis. Please provide instructions

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
We have done some improvements to the documentation (during the doc jira hackathon).However, please see [this comment](https://github.com/wso2/product-apim/issues/2140#issuecomment-360443981) about sample scenarios as well.

We have mentioned the necessary instructions [here](https://docs.wso2.com/display/AM2xx/Invoke+an+API+using+the+Integrated+API+Console), if needed.
