### ISSUE TITLE
API Development Public, Partner and Private sample: improper statement

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2171]
Following statement in [1] is improper to an official documentation. Please change

`The sample scenario I have created is mentioned below.`

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by ChamNDeSilva** [comment]
Fixed in https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation
