### ISSUE TITLE
[Store] Application search placeholder to be renamed to provide more meaning

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2172]
**Description:**
In the apim-store the application search box placeholder states "Filter By" IMO it should at least say "Filter By API Name" to be more meaningful for the user.

![filterbyname](https://user-images.githubusercontent.com/17248809/34553022-35a82a18-f14b-11e7-956f-df33314da171.png)

**Suggested Labels:**
APIM 2.1.0 update 4 , Improvement

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by chanaka3d** [comment]
With the 3.x application search UI this issue is addressed.
<img width="345" alt="Screen Shot 2020-09-25 at 6 10 04 PM" src="https://user-images.githubusercontent.com/3424539/94268172-6384ab80-ff5a-11ea-8a26-b90925f77ae3.png">
