### ISSUE TITLE
API Development Public, Partner and Private sample: include details on the apis that are being used by the departments

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2173]
In [1] after under business story, after describing the departments, straightaway a diagram is given that shows the sharing of an apis in between them. Before the diagram there should be a description of what the apis are and their respective usage.

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
Fixed in : https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation
