### ISSUE TITLE
[Bug] [AM220] Users are directed to the Manage phase even though the Production endpoint given under the implement phase is wrong in REST API creation

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2174]
**Description:**
Users are directed to the Manage phase even though the Production endpoint given under the implement phase is wrong in REST API creation

**Suggested Labels:**
Bug

**Affected Product Version:**
wso2am-2.1.0-update4

**OS, DB, other environment details and versions:**
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**

1. Sign in to the WSO2 API Publisher.
https://:9443/publisher (ex: https://localhost:9443/publisher). Use admin as username and password.

2. In the APIS menu, click Add New API.

3. Select Design New REST API and click Start Creating.

4. Give the information as below
name - xyz
context - /phoneverify
version - 3.0

5. Click on next implement

6. Will prompt a message as resource not specified

7. click yes

8. click on managed API in implement phase

9. Input a wrong production endpoint (eg:- http://ws.cdyne.com/phoneverify2/phoneverify.asmx)

10. click on Test [2]

11. Will give a 404 error as invalid [1]

12. Click on Next Manage

**Observation**
Will proceed to the Manage phase (next phase) eventhough the given production endpoint is wrong

[1]. implement-warning.png
![implement-warning](https://user-images.githubusercontent.com/31848014/34553165-02d11266-f14c-11e7-9442-5e00d06a5ecb.png)

**Comment by isharac** [comment]
This is not a bug but there are some valid use cases.
Ex: 1. Endpoints can be given as a template
      2. The endpoint may be temporarily unavailable at the time of api creation.
