### ISSUE TITLE
API Development Public, Partner and Private sample: confusing titles

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2175]
In [1] at the top the use case is explained. Then again there exists a title called "Business use cases". Apparently the section that is under "Business use cases" are morely related to how to get this done in WSO2 API Manager. Hence please change the titles accordingly.

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
Reducing the priority since this is a title change in the docs. (not a critical code level bug)

**Comment by Mariangela** [comment]
Fixed this issue in [1].
[1]https://docs.wso2.com/display/AM2xx/Managing+APIs
