### ISSUE TITLE
[Store] The info msg shown when no application is matched for the name it does not disappear

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2176]
**Description:**
In APIM Store in the Application search box if the user provides a name of an app which is not available it will show the below msg.

![infomsg](https://user-images.githubusercontent.com/17248809/34553264-86413b12-f14c-11e7-97ff-6c95af6ab01c.png)

If the user then searches for a valid Application name still the info msg is visible which should be removed when application search provides a filter of apps.

**Suggested Labels:**
APIM 2.1.0 update 4 , Bug

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5520
