### ISSUE TITLE
API Development Public, Partner and Private sample: include clear details of getting the sample implemented in api manager

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2177]
In [1] there are no steps that illustrates the implementation of the sample in api manager. Please include a comprehensive guide to any user who will try to learn from implementing the sample. Furthermore bind the steps to the specific api manager concept so the user can have a better understanding to why a specific thing is done

[1] API Development Public, Partner and Private sample:

**Comment by ChamNDeSilva** [comment]
@erandidesilva, can you add the link that specified as [1] please.

**Comment by erandidesilva** [comment]
Please find below
[1] https://docs.wso2.com/pages/viewpage.action?spaceKey=AM2xx&title=Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
We have improved the documentation (during the doc jira hackathon). Please see "How this Business Scenario can be Achieved Using WSO2 API Manager" section in the doc. Also, please see [this](https://github.com/wso2/product-apim/issues/2140#issuecomment-360443981) as well.
