### ISSUE TITLE
[Store] [Improvement] Make application search case incensitive

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2178]
**Description:**

Currently, application search in the store is case sensitive. Would be better to provide case incentive search for faster identification of applications available.

**Suggested Labels:**
APIM 2.1.0 update 4 , Improvement

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this improvement is still needed.
