### ISSUE TITLE
Relationship and method of operation between access control, visiblity on store and subscription permissions

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2181]
In [1] it mentions the relationship between visibility on store and subscriptions but does not factor in the values that can be there for access control (all / restricted by roles). Please include this information to the document.

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
Please note that this sample is for demonstrating API usage with respect to API Store (in other words, API consumption). Hence this is focused about the visibility in store. Access control is mainly for API Publisher related operations (which is not applicable for this sample use case).

**Comment by erandidesilva** [comment]
I do agree that this is on API usage with respect  to API Store and this is only a sample in demonstrating a one aspect. What I wanted to emphasize was that the different levels of visibility (public and restricted by roles)that can be configured in the api  has to be factored in and mentioned as it would be beneficial for the any user who is taking an entry point from this given sample. I think the confusion has risen due to using "all" which is a part of access control.

**Comment by chamindias** [comment]
Improved the [document](https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation).
