### ISSUE TITLE
[AM220] [Doc] Invoke an API using integrated API console given UI image doesn't match with current product UI

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2182]
**Labels**
AM 2.2.0

**Description**
Refer to doc link [1]. Screenshot given under step 5 is not matching with the current product version.Please update it as in [2] and mention there as to click on the Try it button to input the relevant values.

[1]. https://docs.wso2.com/display/AM2xx/Invoke+an+API+using+the+Integrated+API+Console
[2].invoke-api.png
![invoke-api](https://user-images.githubusercontent.com/31848014/34555805-be449330-f159-11e7-997f-aaa6c0c8ee01.png)

**Comment by ChamNDeSilva** [comment]
Fixed.
