### ISSUE TITLE
[Store] The mouse hover text for "API Store walkthrough" is shown as null

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2185]
**Description:**
The mouse hover text for "API Store walkthrough" is shown as null.
![null](https://user-images.githubusercontent.com/17248809/34556630-152c09aa-f15d-11e7-986b-0baca582447f.png)

**Suggested Labels:**
APIM 2.1.0 update 4 , Improvement, Priority/low  

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4991

**Comment by dewmini** [comment]
Closing the issue as fixed.
