### ISSUE TITLE
[AM220] [Doc] Mismatch between product and the doc related to Base URL in invoking an API using the integrated API console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2186]
**Suggested Labels:**
AM 2.2.0
product wso2am-2.1.0-update4

**Description:**
Refer to the doc link [1]. Under step 5 there is a input field as Base URL. But could not identify a place to input Base URL in the new product UI under API Store > Select the API > API Console as in [2]
Verify this mismatch and update the doc accordingly

[1]. https://docs.wso2.com/display/AM2xx/Invoke+an+API+using+the+Integrated+API+Console
[2]. post.png
![post](https://user-images.githubusercontent.com/31848014/34556635-1b7eb7f8-f15d-11e7-98d6-d69cc31d0d25.png)

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.

https://docs.wso2.com/display/AM210/Invoke+an+API+using+the+Integrated+API+Console
https://docs.wso2.com/display/AM2xx/Invoke+an+API+using+the+Integrated+API+Console
