### ISSUE TITLE
[Doc] Fix the links of "Related Tutorials" to 2xx docs found in "Create and Publish an API"  page

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2187]
**Description:**
The links to "Related Tutorials" found in "Create and Publish an API"  [1\] page should be pointed to 2xx docs its currently pointed to 2.1.0 docs

[1\] [https://docs.wso2.com/display/AM2xx/Create+and+Publish+an+API](https://docs.wso2.com/display/AM2xx/Create+and+Publish+an+API)

**Suggested Labels:**
docs, apim 2xx

**Comment by taniamahanama** [comment]
Fixed.
