### ISSUE TITLE
API Development Public, Partner and Private sample: repetitive sections

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2188]
In [1] under "Usecases" and "Sample Business Use Cases Related to Sample One" the same content is repeated. Can we please restructure these?

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
Improved the doc : https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation
