### ISSUE TITLE
[Doc] Fix the link of "Create and Publish an API" to 2xx docs found in "Test an API using a Testing Tool" page

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2189]
**Description:**
The link  "Create and Publish an API" [1\] is pointed to 2.0.0 docs please point it to 2xx docs.

[1\] [https://docs.wso2.com/display/AM2xx/Test+an+API+using+a+Testing+Tool](https://docs.wso2.com/display/AM2xx/Test+an+API+using+a+Testing+Tool)

**Suggested Labels:**
docs, apim 2xx

**Comment by taniamahanama** [comment]
Fixed. Also fixed the same link in the 2.1.0 docs.
