### ISSUE TITLE
[DOC] [AM220] There is no information for how to add rate limiting (burst control) in subscription tiers

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2190]
**Description:**
I coudln't find the details and screen shot for $subject in wso2 docs [1]. Please add a screen shot and details for how to add. Note that Expalanation for what is rate limiting is already available at page [1].

**Suggested Labels:**
APIM-2.2.0
Documentation
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add API 
- Select subscription tiers 
- Tried to add burst control for relevant subscription tier

[1] [https://docs.wso2.com/display/AM2xx/Setting+Throttling+Limits]

**Comment by ChamNDeSilva** [comment]
It is described in https://docs.wso2.com/display/AM2xx/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewsubscription-levelthrottlingtier section.
Added a link to that doc  under **Rate limiting (burst control)** description in https://docs.wso2.com/display/AM2xx/Setting+Throttling+Limits
