### ISSUE TITLE
Description of the Error message is not meaningful/clear when fail the API publishing

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2192]
**Description:**
User trying to publish an API which is created by REST API and also has not added any resource. 
Then user getting an error message which is not clear on the actual error happen.

**Steps to reproduce:**
1. Add an API without adding resources, by using the REST API.
2. Go to the Publisher >> Lifecycle section 

**Actual:**
Below error message is appeared.
![image](https://user-images.githubusercontent.com/7115693/34557074-0fe21988-f15f-11e7-9f71-29d43f6eb72e.png)
By referring the server logs, it can see this is due to unavailability of the resources

**Expected:**
Error message description should clearly mention about the missing resources in the API.
Validation messages should be meaningful even for the invalid(negative) scenarios.

**Comment by isharac** [comment]
The latest APIM( > 3.0.0) uses React based applications hence this error does not occur.
