### ISSUE TITLE
[AM220] [Doc] API Store API Console Product UI does not match with the UI images included under Deploy and Test as a Prototype

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2195]
**Suggested Labels:**
AM 2.2.0

**Affected Product Version:**
wso2am-2.1.0-update4

Refer to doc link [1]. Update the Given images under step 6 and 7 below the "Note the response that appears in the console." section as in [1] to match with the current product version

[1]. new-ui.png
[2]. https://docs.wso2.com/display/AM2xx/Deploy+and+Test+as+a+Prototype

![new-ui](https://user-images.githubusercontent.com/31848014/34558906-d878fc94-f165-11e7-9d1d-fbbed35738cb.png)

**Comment by ChamNDeSilva** [comment]
Already Fixed.
