### ISSUE TITLE
Provide latest doc link for "API Visibility and Subscription"

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2197]
**Description:**
In [1\] Key Concepts doc the "API Visibility and Subscription" link is pointed to 2.1.0 docs please link it to 2xx docs.

[1\] [https://docs.wso2.com/display/AM2xx/Key+Concepts](https://docs.wso2.com/display/AM2xx/Key+Conceptsrl)

**Suggested Labels:**
APIM 2.x.x Doc, bug

**Comment by taniamahanama** [comment]
Fixed and checked other similar links on the page.
