### ISSUE TITLE
Advance endpoint config needs to validate the values entered for duration

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2200]
**Description:**
While creating an API in the section where endpoint details should be provided the advanced endpoint config section allows users to allow any value for the duration which is not validated. Please refer below image for an example

![advancedendpointconfig](https://user-images.githubusercontent.com/17248809/34564422-ab7570c6-f17c-11e7-8252-04b6edf136d2.png)

**Suggested Labels:**
APIM 2.1.0 update 4 , Bug,  Priority/Normal Severity/Major 

**Affected Product Version:**
APIM 2.1.0 update 4

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Comment by HiranyaKavishani** [comment]
Fixed in master branch
