### ISSUE TITLE
Store analytics - Faulty Invocations per Application is not showing data at all

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2202]
**Description:**
Observered that there is no data appears for "Faulty Invocations per Application" section after invoks are getting failed. While execute the load there were a lot requests failed as mentioned in below steps, but there were no single data updated to view in analytics page

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/high

**Suggested Assignees:**

**Affected Product Version:**
apim-2.1.0-update4
apim-analytics-2.1.0-update3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Configure analytics
- Add an API and an application
- Invoke the api with load 
  make the requests fails with expired access token

Observed no data as in below image
![faulty](https://user-images.githubusercontent.com/15671620/34565189-d0ffa6e2-f17f-11e7-972c-658570f3bc13.jpeg)

Note that other stats was displayed e.g. API usage as in below image
![apiusage](https://user-images.githubusercontent.com/15671620/34565203-df6b2256-f17f-11e7-9433-eb7ba685dc9a.jpeg)

**Comment by nuwand** [comment]
Would you please mention what the failures are and how you captured them? What gets captured in here are request timeouts and connection failures, basically the stuff that prevents the Gateway from accessing the Backend. Unless you mention the failures its hard to debug this issue.

**Comment by kavithasub** [comment]
Hi,
Initially I made the request failure by requesting api access using expired tokens and recieved error response (code":900901). According to [1] such kind of failures should be captured to Faulty invocation stats I assume. 
Also I will try to capture other cases you mentioned (request timeouts and connection failures).
[1] [https://docs.wso2.com/display/AM2xx/Viewing+API+Statistics#ViewingAPIStatistics-FaultyInvocations]

**Comment by chamindias** [comment]
Hi,

Please let me explain the concept here. As Nuwan mentioned, request timeouts and connection failures are considered as faulty invocations. Error code 900901 is related to [invalid credentials](https://docs.wso2.com/display/AM1100/Error+Handling) (Invalid authentication information provided, using an older access token after an access token has been renewed). Therefore this is not an issue. Hence resolving.

Thanks
