### ISSUE TITLE
Create tenant using admin service: typo error

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2204]
In [1] in the below sentence there is a typo error

Although other tenant management operations such as activating, deactivating, updating and deletion are not possible via the Management Console UI, its possible **to so** via the RemoteTenantManager Admin Service

[1] https://docs.wso2.com/display/AM200/Managing+Tenants

**Comment by erandidesilva** [comment]
Below sentence is having a typo as well

This assumes that you are **runnignt** the SOAP UI client from the same machine as the API Manager instance is running.

**Comment by taniamahanama** [comment]
Fixed.
