### ISSUE TITLE
Is it ok to mention that some prod setups can have h2 db

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2210]
**Description:**
In [1\] we have mentioned the below sentence.

"This embedded H2 database is suitable for development, testing, and for some production environments."

Are we really ok with saying that some prod environments can run on h2 database?
[1\]  [https://docs.wso2.com/display/AM2xx/Working+with+Databases](https://docs.wso2.com/display/AM2xx/Working+with+Databases)

**Suggested Labels:**
doc , 2xx apim

**Comment by ChamNDeSilva** [comment]
Fixed removing the "and for some production environments" part from the sentence as next sentence describes what is our recommendation for production environments.

https://docs.wso2.com/display/AM2xx/Working+with+Databases
https://docs.wso2.com/display/AM210/Working+with+Databases
