### ISSUE TITLE
Configuring Claims Under Enabling notifications section points to a old IS Doc

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2215]
**Suggested Labels:**
APIM 2.2.0
Type/Docs

**Description**
Refer to document link [1]. Update the link Configuring Claims to direct to the latest IS Docs

[1]. https://docs.wso2.com/display/AM2xx/Enabling+Notifications

**Comment by taniamahanama** [comment]
Fixed.
