### ISSUE TITLE
Creating users using the ask password option under enabling notifications section points to a old IS Doc

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2216]
**Suggested Labels:**
APIM 2.2.0
Type/Docs

**Description**
Refer to document link [1]. Update the link Creating users using the ask password option to direct to the latest IS Docs

[1]. https://docs.wso2.com/display/AM2xx/Enabling+Notifications

**Comment by taniamahanama** [comment]
Fixed via https://github.com/wso2/product-apim/issues/2215.
