### ISSUE TITLE
Publisher rest apis: provide navigation and list of apis available in the page that loads

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2220]
In [1] in the page loaded when clicked on Publisher APIs does not have a listing of the APIs. It would be better to provide a list of apis that is provided by APIM. This will increase user experience and also readability

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/

**Comment by ChamNDeSilva** [comment]
when we go to the page [1] it lists all the APIs, Resources etc in the navigation bar. Adding this to the description will be a duplication. Hence will not fix.
