### ISSUE TITLE
Mention that user needs to login in order to download API SDKs

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2221]
**Description:**
In [1\] under "Generating client SDKs in the API Store" mention that users need to login to apim store in order to download the SDKs.

[1\] [https://docs.wso2.com/display/AM2xx/Generating+SDKs](https://docs.wso2.com/display/AM2xx/Generating+SDKs)

**Suggested Labels:**
docs, apim 2xx

**Comment by taniamahanama** [comment]
Fixed.
