### ISSUE TITLE
Provide information adding users and roles using apis in the relevant sections

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2222]
Currently in [1] and [2] information is only there to add users and roles from the management console. It would be great if this information is extended to support user and role adding using apis. This will be beneficial for the user to have all information in one stop.

[1] https://docs.wso2.com/display/AM200/Adding+Users
[2] https://docs.wso2.com/display/AM200/Adding+User+Roles

**Comment by chamindias** [comment]
Improved the docs (in the description) by adding instructions to add users/roles using APIs.
