### ISSUE TITLE
Why do we have 200 response code always appears at API Console -> default request section

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2223]
**Description:**
As per $subject I could see the 200 response code under Responses (see attached) even after I recieved deifferent response code. If it is an example for default request template can we remove after actual responses recieved for relevant requests?

**Suggested Labels:**
APIM-2.2.0
Type/improvement
Priority/high

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update4

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
![respons](https://user-images.githubusercontent.com/15671620/34597482-e8ba4c96-f20c-11e7-824d-1de0ba016a53.jpeg)

**Related Issues:**

**Comment by chamindias** [comment]
This is shown based on the swagger definition of the API. Please note that you have to specify it in publisher (see below images). Then you will get the response codes along with the details.

Publisher : 
![image](https://user-images.githubusercontent.com/8359365/36427323-ec30f9d0-1672-11e8-89bc-6f28641ae39c.png)

Store - Response
![image](https://user-images.githubusercontent.com/8359365/36427355-0697c5a6-1673-11e8-8671-9d4975d34705.png)

Store - Example
![image](https://user-images.githubusercontent.com/8359365/36427407-247f39c8-1673-11e8-9ace-c61308ff4b19.png)

Answered, hence resolving.
