### ISSUE TITLE
Generating SDKs screenshot needs to be updated with 2xx release

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2224]
**Description:**
In [1\] the screenshot provided in step 3 needs to be updated with the new APIM 2.1.0. 
![new](https://user-images.githubusercontent.com/17248809/34597535-37df823c-f20d-11e7-84e3-c71e9e1bb04c.png)
[1\] [https://docs.wso2.com/display/AM2xx/Generating+SDKs](https://docs.wso2.com/display/AM2xx/Generating+SDKs)

**Suggested Labels:**
docs, apim 2xx

**Comment by chamindias** [comment]
Fixed in : https://docs.wso2.com/display/AM2xx/Generating+SDKs
