### ISSUE TITLE
Update the hyperlinks for Enabling CORS for API and Adding mediation extensions

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2225]
**Suggested Labels:**
APIM 2.2.0
Type/Docs

**Description**
Refer to document link [1]. Update the hyperlinks for Enabling CORS for API and Adding mediation extensions

[1]. https://docs.wso2.com/display/AM2xx/Create+and+Publish+an+API

**Comment by taniamahanama** [comment]
Fixed.
