### ISSUE TITLE
Store analytics - selecting the "time interval" doesn't show the stats information

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2226]
**Description:**
Selecting the "time interval" doesn't show the stats information as I could see by clicking "hour" option at store analytics page -> API usage

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/critical

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update4

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Configure analytics
- Add an API and an app
- Invoke the api
- Verify the analytics at store page for API usage by selecting "Hour" => this shown infor as in image[1]
- Select the "time interval" at date & time drop down (e.g. api invoked between 10.40 to 11.40, hence selected 10.00 to 11.00) => this not shown any data as in image[2] 

[1]
![hour](https://user-images.githubusercontent.com/15671620/34597782-f1421bee-f20e-11e7-9157-2f7cbf7a8ecd.jpeg)

[2]
![hour2](https://user-images.githubusercontent.com/15671620/34597788-fbb038a4-f20e-11e7-9749-46a3b3340fe4.jpeg)

**Comment by msm1992** [comment]
Well this worked fine for me. You just have to select a valid time period.

Just one concern, the first screen-shot implies that the api invocation took place sometime in between 10.41 AM to 11.41 AM. So given that shouldn’t you select a time range that overlaps completely with 10.41 AM to 11.41 AM ? 10.00 AM to 11.00 AM time range leaves out 11.01 AM to 11.41 period and if the database tuple’s time field (API_REQUEST_SUMMARY) contained a time in 11.01-11.41 AM range then you will not be getting any data, which I assume is the same thing happening here.

However hour granulity in APIM analytics is to be removed and it is already done so in APIM publisher [1]. I have created [2] to track the same for APIM store. 

[1]. https://github.com/wso2/product-apim/issues/2183
[2]. https://github.com/wso2/product-apim/issues/2720
