### ISSUE TITLE
Error message given when enter a incorrect Prototype Endpoint will not disappear  

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2227]
**Suggested Labels:**
Type/Bug
APIM 2.2.0

**Affected Product Version:**
wso2am-2.1.0-update5

**OS, DB, other environment details and versions:**

Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**

1. Run APIM 2.1.0 update 5
2. Access API Publisher
3. Create a REST API
4. In the phase Implement > Prototype API > give a invalid prototype endpoint
5. Error message will be displayed

**Observation**
Error message displayed will not disappear when entering a new input [1]

[1]. prototype.png
![prototype](https://user-images.githubusercontent.com/31848014/34597971-150f5a04-f210-11e7-9b7e-acbfb2f585f7.png)

**Comment by chanaka3d** [comment]
This issue is addressed with the 3.x UIs
