### ISSUE TITLE
Improve the elaboration in "Generating SDKs" 

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2228]
**Description:**
In [1\] can we verify the first sentence of the elaboration. IMO the phrase "application using the OS to call the local API" is confusing. E.g what is local API

[1\] [https://docs.wso2.com/display/AM2xx/Generating+SDKs](https://docs.wso2.com/display/AM2xx/Generating+SDKs)

**Suggested Labels:**
docs, apim 2xx, improvement

**Comment by isurulucky** [comment]
Fixed.
