### ISSUE TITLE
Mention about the walkthrough of the store in QSG - Invoking your first API section

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2231]
**Description:**
In [1\] in step 6 shall we mention about the API walkthrough provided in Store as well because this will be the first time user will go through the store so better to mention about the walkthrough that the user will be greeted on the first login.

[1\] [https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-InvokingyourfirstAPI](https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-InvokingyourfirstAPI)

**Suggested Labels:**
docs, apim 2xx

**Comment by chamindias** [comment]
Fixed in : https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-InvokingyourfirstAPI
