### ISSUE TITLE
Mention how to enforce a grace period to upgrade to a new API version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2234]
**Labels**
APIM 2.2.0
Type/Docs

**Description**
Refer to doc link [1]. Under Use case section it has a sub point as " Enforcing a grace period to upgrade to the new version of the API " Please include in the doc how this can be acheived 

[1]. https://docs.wso2.com/display/AM2xx/API+versioning

**Comment by ChamNDeSilva** [comment]
It is described in following note.

> Enabling grace period to upgrade to a new version can be achieved by using the notifications when a new version of an API is created. At that time, when a new version of an API is created, a notification should be sent to existing subscribers to notify that the API will be deprecated in X months and retired in Y months. Then API Publisher have to perform those actions (deprecation and retiring) in X and Y months time period respectively.

And the document has linked to https://docs.wso2.com/display/AM2xx/Enabling+Notifications as well on how to enable notifications.
