### ISSUE TITLE
Improvements - sections listing - Publisher REST API document

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2238]
**Description:**

"Create a new API" section is under API (Collection) section. This should be listed under 'API (Individual)' section in [1]

![image](https://user-images.githubusercontent.com/7115693/34607698-c34817da-f23a-11e7-85bb-c61df04d1a56.png)

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/index.html

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5000 for 2.2.0, for 2.1 fixed under support branch.
