### ISSUE TITLE
Rest Create API : provide comprehensive parameter description

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2239]
In [1] there is no description on the parameters needed for the request and there is no indication of the mandatory params. Please include the information in the documentation

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APICollection#apisPost

**Comment by erandidesilva** [comment]
Seemingly its given in the latter part of the parent document. This is bit confusing. Can we link [2] with above [1] so that the user can click and go to [2] when needed from [1] ?

[2] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#API

**Comment by shaniR** [comment]
A link is already present to the API object under schema.
