### ISSUE TITLE
Rest Create API: Only the Content-Type is given in the header field description

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2240]
In [1] only the Content-Type is described when describing header params. Please include Authorization description as well.

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APICollection#apisPost

**Comment by shaniR** [comment]
Fixed for 2.2.0 with https://github.com/wso2/carbon-apimgt/pull/5000. For 2.1 changes are pushed to support branch,
