### ISSUE TITLE
Blacklisting requests section's screenshot needs to be corrected to latest one

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2242]
**Description:**
Blacklisting requests section's screenshot needs to be corrected to latest one at given page [1]

**Suggested Labels:**
APIM-2.2.0
Documentation
Type/improvment

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
[1] <https://docs.wso2.com/display/AM2xx/Managing+Throttling#ManagingThrottling-Blacklistingrequests>

**Comment by ruthryi** [comment]
Tested and changed screenshots
[1] : https://docs.wso2.com/display/AM2xx/Managing+Throttling
