### ISSUE TITLE
Error code '900805' should be added to the "error handling" doc and description as well

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2245]
**Description:**
Error code '900805' should be added to the "error handling" doc [1] and description as well. To get this error code see steps to recreate.

**Suggested Labels:**
APIM-2.2.0
Document
Type/bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add an api and publish it 
- Signup a user and login to store
- Add an application and suscribe it to above api and generate token
- Login to admin dashboard
- Add a blacklist for above user 
- Invoke the above api => you would get error (see attached)

[1] <https://docs.wso2.com/display/AM2xx/Error+Handling>

![block2](https://user-images.githubusercontent.com/15671620/34608381-19c5848c-f23e-11e7-8676-d43061793f34.jpeg)

**Comment by chamindias** [comment]
Fixed in the [official documentation](https://docs.wso2.com/display/AM2xx/Error+Handling), hence resolving.
