### ISSUE TITLE
Validate whether a url is provided when users click on "Test"

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2246]
**Description:**
While creating an API validate the field of production/sandbox endpoints to whether its empty. Currently, if the field is empty and if "Test" is clicked. Only a 'X' is shown no validation message is displayed. Refer the image below.

![image](https://user-images.githubusercontent.com/17248809/34608453-67c2c5fa-f23e-11e7-9bf0-d22c2b63db0e.png)

**Suggested Labels:**
APIM 2.1.0 Update 5, Bug, Priority/Normal

**Comment by kavishkafernando** [comment]
This has been fixed 
<img width="1007" alt="Screen Shot 2020-11-26 at 12 12 57 PM" src="https://user-images.githubusercontent.com/19324135/100316609-e5d42f00-2fe0-11eb-9277-57dd699ab19d.png">
