### ISSUE TITLE
No failures/restrictions when user try to publish an already published API from REST API

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2248]
**Description:**
No failures/restrictions when user try to publish an already published API from REST API

**Steps to reproduce:**
1. Add and publish an API from the REST API
2. Try to perform publishing the same API

**Actual:**
User getting 200 Success. No indication as the API has already in PUBLISHED state.

**Expected:**
Should return correct response with suitable response code+message.

**Comment by Rajith90** [comment]
According API Lifecycle , publish state can be a one target state available when api is already published. This is how the re publishing is achieved. Since we allow re publishing , the correct response code should be 200. AFAIU this is not a bug, this is the behavior of API Manager
