### ISSUE TITLE
When upload a API definition from a incorrect Swagger URL no error message is displayed or no any change in the UI

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2249]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/Normal

**Affected Product Version:**
wso2am-2.1.0-update5

**OS, DB, other environment details and versions:**    
Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**
1. Run APIM 2.1.0 update5
2. Access API publisher
3. Add REST API with mandatory fields
4. Go to Design Phase > API Definition
5. Click on Import
6. Select Swagger URL
7. Give a invalid input [1]
8. Click on Import

**Observation**
No error message is displayed or no any change in the UI for the user to get a idea on what he needs to do next.
[1] import.png
![import](https://user-images.githubusercontent.com/31848014/34609771-0c5770f2-f244-11e7-9e78-7b0933f5256f.png)

**Comment by chamilaadhi** [comment]
Fixed in latest APIM 2.6.0. See the image below for the error message
<img width="1102" alt="Screen Shot 2019-09-16 at 3 36 25 PM" src="https://user-images.githubusercontent.com/4861150/64949908-db27f100-d897-11e9-8746-5a37df021bfb.png">
