### ISSUE TITLE
Given sort option for added documents' output table at API -> Docs page has appeared unnecessary character symbol

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2251]
**Description:**
Given sort option at API -> Docs page has taken additional character symbol (see attached)

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Sevirity/major
UX

**Suggested Assignees:**

**Affected Product Version:**
apim-2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Add an API
- Goto overview and goto Docs page
- Add docs and see output table => as in below attached columns are get sorting but unnecesssary symbol appears

![sort](https://user-images.githubusercontent.com/15671620/34610306-93f6170a-f246-11e7-927b-757c44faf662.jpeg)

**Comment by chamindias** [comment]
Tested in the latest pack. Issue was not observed. Hence resolving.

![image](https://user-images.githubusercontent.com/8359365/36428113-0e3b1310-1675-11e8-9625-fa6a63da3cd7.png)
