### ISSUE TITLE
Rest Create API; Include possible values in description document

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2252]
In [1] the list of possible values are not there. But for some fields (e.g. visiblity [[PUBLIC, RESTRICTED, CONTROLLED, PRIVATE]) there are pre-defined value list where one/more can be used. The document should contain these information

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#API

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5000 for 2.2.0. For 2.1 added into support branch.
