### ISSUE TITLE
Rest Create API: error message given to client is not informative enough when wrong visibility is used

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2253]
With [1] when creating an api, if the value of visibility is given wrong then the following error message comes to the client
```
{"code":400,"message":"Bad Request","description":"One or more request body parameters contain disallowed values.","moreInfo":"","error":[]}
```
But the console prints a meaningful error as follows
```
[2018-01-05 19:05:05,215] ERROR - GlobalThrowableMapper One or more request body parameters contain disallowed values.
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type org.wso2.carbon.apimgt.rest.api.publisher.dto.APIDTO$VisibilityEnum from String "Visible to my Domain": value not one of declared Enum instance names: [PUBLIC, RESTRICTED, CONTROLLED, PRIVATE]

```
Please incorporate the console printed information to the client message so that it would be more meaningful

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APICollection#apisPost

**Comment by chamindias** [comment]
Reducing the priority since this is related to a change in the message. (not a critical functionality)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
