### ISSUE TITLE
Unable to copy the generated token

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#2256]
**Description:**
when a token is generated from the store, it is display in a textbox which is unable to selecect. because of that, we had to manually enter the token.

**Comment by Krishanx92** [comment]
![token](https://user-images.githubusercontent.com/8374895/34710874-fd1195bc-f542-11e7-9273-ad86fb220a86.png)
This issue Fixed already.

**Comment by tmkasun** [comment]
I was able to reproduce this issue with `FF Quantum 57.0.4 (64-bit)`

![image](https://user-images.githubusercontent.com/3313885/34714478-95a6485c-f54f-11e7-8c0f-8c567ee298f7.png)

The [issue](https://support.mozilla.org/en-US/questions/1190785) was firefox prevent interacting(selecting text ect) if an input element is disabled

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4916
