### ISSUE TITLE
Rest API: unable to create an api with a user who has specific permission

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2259]
Environment
OS: Ubuntu 16.04
JDK: Oracle 1.8.0_144
DB: Mysql ( carbon and apimgt databases only)

Note: Super administrator credentials are changed as mentioned in [1]

1. Created a user with permission as mentioned in [2] (the user has all create, publish and subscribe permission) as given below.

![apim_issue_5](https://user-images.githubusercontent.com/15624590/34659128-3e7a53e2-f45b-11e7-87a6-5b2b190e8e74.png)

2. Tried to create an api using the rest api with the above user. Failed with the below error

```
[2018-01-08 09:09:58,670] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed

```
[1] https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords
[2] https://docs.wso2.com/display/AM2xx/Adding+User+Roles

**Comment by Rajith90** [comment]
In tenant-conf.json(/_system/config/apimgt/applicationdata/tenant-conf.json) file only the users with roles "admin,Internal/creator" has the permission to get the access token with scope "apim:api_create". If we have any other users with any other roles the access token he gets does not have the "apim:api_create" scope. Thats why this user can not add the api. If you add the user role to scope "apim:api_create" in tenant-conf.json file then this user also can create the apis. Please refer doc[1] for more info

[1] - https://docs.wso2.com/display/AM210/apidocs/publisher/#configuring-rest-api
