### ISSUE TITLE
Cannot untick and disable a tenant from carbon console

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2260]
**Description:**
The option to untick an active tenant fails.

**Suggested Labels:**
APIM 2.1.0 Update 5, Bug, Priority/High

**Affected Product Version:**
APIM 2.1.0 Update 5

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - h2

**Steps to reproduce:**

1. Navigate to carbon console and a create a Tenant
2. Create few APIS and publish via the new Tenant space
3. Login to carbon console and navigate to Tenant section
4. Untick the Active Tenant 

**Issue**
The tenant will not be unticked and will remain in the active state.

**Comment by ChamNDeSilva** [comment]
Cannot reproduce.
