### ISSUE TITLE
REST API response msgs should be improved when user tries to change the state of a Retired API 

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2261]
**Description:**
Response message should be improved for a request in which the user trying to change the life cycle of retired APIs. Currently it returns the phrase 'Allowed actions are []'. sinec there is no any action support for Retired apis, its better giving proper message than empty array.

**Steps to Reproduce**
1. Create an API using publisher REST APIs
2. Promote it until Retire state using API[1]
[1] /api/am/publisher/v0.11/apis/change-lifecycle?apiId=<api_id>&action=<action>
3. Try to perform lifecycle change from retire to some other(publish, Demote to create, etc)

**Actual**
Getting following message and it has the phrase "Allowed actions are []" which is not quite nice.
{"code":400,"message":"Bad Request","description":"Action 'Publish' is not allowed. Allowed actions are []","moreInfo":"","error":[]}

**Expected**
Rather giving an empty array, better to give a proper validation response message for this specific case.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
