### ISSUE TITLE
No filtering or sorting available for lifecycle history view in publisher

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2263]
**Description**
The user has no option to do filtering and sorting for the lifecycle history view table in the publisher. This is a useful option when there are plenty of records for the same API. Currently all the history records are listing under the LifeCylce section and newest record is at the bottom.
Please see the screen below.
![image](https://user-images.githubusercontent.com/7115693/34659452-c71bb634-f45e-11e7-8e66-7946e353b926.png)

**Comment by chamindias** [comment]
Hi,

Normally it is unlikely to change the lifecycle of an API frequently (which will result so many records as shown in the issue). Practically there will be few records here. Hence this won't have a severe impact as stated. Hence reducing the priority and resolving.

Thanks.
