### ISSUE TITLE
Add Response error code 500 for Internal server error in the API document

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2267]
**Labels**
APIM 2.2.0
APIM 2.1.0
Type/Doc

**Description**
Refer to the doc link [1]. Include the response error code 500 in the document with the reason for the error code as follows.

{"code":500,"message":"Internal server error","description":"The server encountered an internal error }

[1].https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisCopyApiPost

**Comment by shaniR** [comment]
Adding 500 would not be bring much value addition to the API user as it is a general error code, stating that an Internal Server error has occurred, but we cannot provide any solid reason, as there are number of reasons why this could happen. Hence we will not add it to documents
