### ISSUE TITLE
The failure message shown should be fixed when password reset fails

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2268]
**Description:**
Related to issue #2264 the failure message shown states as below. Please remove "contact cloud@wso2.com"

![validationmsg](https://user-images.githubusercontent.com/17248809/34659718-145711ca-f462-11e7-8e8f-acc53e1f728e.png)

**Suggested Labels:**
APIM 2.1.0 update 5 , Bug, Priority/Highest

**Affected Product Version:**
APIM 2.1.0 update 5

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Version 63.0.3239.84 (Official Build) (64-bit)
DB - 5.5.58

**Steps to reproduce:**
Signup as a store user
Try to reset the password using "Forgot Password" option

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4903

**Comment by chamindias** [comment]
Tested in the latest pack and issue is not there.
