### ISSUE TITLE
Include response error code 401 in REST APIs related to API versioning in the API document

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2269]
**Labels**
APIM 2.2.0
APIM 2.1.0
Type/Doc

**Description**
Refer to the doc link [1]. Include the response error code 401 in the document with the reason for the error code as follows.

{"code":401,"message":"","description":"Unauthenticated request" }

[1].https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisCopyApiPost

**Comment by shaniR** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/5000 for 2.2.0 . For 2.1 added to support branch,
