### ISSUE TITLE
Document on how to configure APIM to use store password reset

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2270]
**Description:**
As per #2264 comments, we need to document on how to configure APIM in order for the store users to reset the password.

**Suggested Labels:**
Docs, APIm 2.x.x ,Priority/Highest

**Comment by ChamNDeSilva** [comment]
Already added as  a FAQ

https://docs.wso2.com/display/AM2xx/FAQ#FAQ-IsthereawaytorecoveraforgottenpasswordforaAPIstoreuser?
