### ISSUE TITLE
Rest api: provide real usable value for subscription and subscription available tenants fields

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2271]
In [1] for subscription field only one possible value is shown. Please give what are all possible values that will be taken as a valid value,

For subscription available tenants, please give proper sample other than null as null is also described as the default value.

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#API

**Comment by shaniR** [comment]
fixed in 2.2.0 with https://github.com/wso2/carbon-apimgt/pull/5000. for 2.1 added to support branch
