### ISSUE TITLE
Mention what API actions are allowed under the token scope Production in REST APIs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2273]
**Labels**
APIM 2.2.0
Type/Doc

**Description**
Refer to the doc link [1]. Include a note on the token scope = production related to the request section
{
    "callbackUrl": "www.google.lk",
    "clientName": "rest_api_publisher",
    "tokenScope": "Production",
    "owner": "admin",
    "grantType": "password refresh_token",
    "saasApp": true
}
Mention what API actions are allowed under the token scope = production

[1]. https://docs.wso2.com/display/AM210/apidocs/publisher/#guide

**Comment by ChamNDeSilva** [comment]
We do not use "tokenScope" when registering the auth app. It is something redundant in the payload.json. 
Hence removing with below PRs.
https://github.com/wso2/carbon-apimgt/pull/5005
https://github.com/wso2-support/carbon-apimgt/pull/746
