### ISSUE TITLE
The success message shown when password reset mail is sent needs to be corrected

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2274]
**Description:**
In APIM Store if a user resets the password the success message shown should be reworded. The current message shown is as below.

![storeconfirmation](https://user-images.githubusercontent.com/17248809/34660479-aca689dc-f468-11e7-9864-9b9cf5749d7f.png)

It should be corrected as the username is mentioned as the mail sent location.

**Suggested Labels:**
APIM 2.1.0 update 5 , Bug, Priority/Normal

**Affected Product Version:**
APIM 2.1.0 update 5

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
DB - 5.5.58

**Comment by isharac** [comment]
Fixed in the latest version.(3.2.0)
<img width="460" alt="Screen Shot 2020-10-23 at 5 39 52 PM" src="https://user-images.githubusercontent.com/8057793/97002018-fe22db00-1556-11eb-8a6a-87000c419c49.png">
