### ISSUE TITLE
Mention that the user details given in API STORE signup will be updated in the default profiles of users in the management console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2275]
**Labels**
APIM 2.2.0
Type/Doc

**Description**
Refer to link [1]. Under step 2 add a note and mention that users registered with the API Store Signup can be view by login to the management console and accessing Users List. Also mention that there details entered in the sign up will be updated in the default profile related to each user in the management console.

[1]. https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-SubscribingtotheAPI

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.
https://docs.wso2.com/display/AM210/Quick+Start+Guide
https://docs.wso2.com/display/AM2xx/Quick+Start+Guide
