### ISSUE TITLE
Create a REST API as a user with the create permission and no success message is shown after the API creation

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2279]
**Suggested Labels:**
Type/Bug
APIM 2.2.0

**Affected Product Version:**
wso2am-2.1.0-update5

**OS, DB, other environment details and versions:**

Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**

1.Run APIM 2.1.0 update 5
2.Access Management console
3. Create a user and a role with the permission to Login and API creation
4. Access the API publisher as the user created in step 3
5. Create a REST API

**Observation**
After the final save option no any success message is given for the user by mentioning that the API creation is successful. User needs to go back for the API section to see whether the API has been created successfully.

**Comment by chamilaadhi** [comment]
This is fixed with new UI changes in AM 3.0.0 . You could try this out in current 3.0.0 M35 https://github.com/wso2/product-apim/releases/tag/v3.0.0-m35
