### ISSUE TITLE
Warning message popup at api-policy-edit page is not clear 

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2283]
**Description:**
A warning message has been popupped at api-policy-edit page when goto Add new policy where relevant configurations were not done. But it is not understandable and not meaningful until read the doc page for conditional gruop in [1]. Please correct the mesage with including coma seperated for config details.

**Suggested Labels:**
APIM-2.2.0
Document
Type/improvement

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
See attached.
![warn](https://user-images.githubusercontent.com/15671620/34664838-caf2b490-f483-11e7-9e3a-c8688f33726f.jpeg)

[1] <https://docs.wso2.com/display/AM2xx/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewadvancedthrottlingpolicy>

**Comment by chamilaadhi** [comment]
Grammar issues fixed in latest AM 2.6.0.
<img width="1163" alt="Screen Shot 2019-09-16 at 3 54 19 PM" src="https://user-images.githubusercontent.com/4861150/64950975-58ecfc00-d89a-11e9-8f32-1ae9f8ddf1f0.png">
