### ISSUE TITLE
API resource description alignment issue with multiple lines

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2288]
**Description:**
Description label bottom aligned when it has multiple lines of value.

![image](https://user-images.githubusercontent.com/7115693/34663528-50ec2592-f47d-11e7-8f9c-582059bcdab1.png)

**Comment by chanaka3d** [comment]
This issue is already fixed as of the latest build

<img width="1028" alt="screen shot 2018-03-12 at 12 18 07 pm" src="https://user-images.githubusercontent.com/3424539/37269221-7c852d40-25ef-11e8-8330-d242b0873f03.png">
