### ISSUE TITLE
Meaningless tip given at mouse click over option given for HTTP resource parameter (Parameter Type)

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2289]
**Description:**
Meaningless tip given at mouse click over option given for HTTP resource parameter (Parameter Type) at resource edit section. See attached below. 

**Suggested Labels:**
APIM-2.2.0
Type/bug
UX

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
![param](https://user-images.githubusercontent.com/15671620/34669129-45e7ceb2-f496-11e7-8933-29ccc002eb63.jpeg)

**Comment by chanaka3d** [comment]
<img width="955" alt="screen shot 2018-03-12 at 3 04 30 pm" src="https://user-images.githubusercontent.com/3424539/37276041-b679d688-2606-11e8-9557-1ea4dd05e69f.png">

Fixed with the PR https://github.com/wso2/carbon-apimgt/pull/5219
