### ISSUE TITLE
Need to correct the formatting when multiple SDKs are enabled

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2290]
**Description:**
In-store if all supported sdk's are enabled [1\] the labels shown needs to be formatted correctly.

![formating](https://user-images.githubusercontent.com/17248809/34669930-1353e324-f49a-11e7-90f5-7608e4014015.png)

[1\] [https://docs.wso2.com/display/AM2xx/Generating+SDKs#GeneratingSDKs-GeneratingclientSDKsintheAPIStore](https://docs.wso2.com/display/AM2xx/Generating+SDKs#GeneratingSDKs-GeneratingclientSDKsintheAPIStore)

**Suggested Labels:**
APIM 2.1.0 update 5 , Bug, Priority/Normal

**Affected Product Version:**
APIM 2.1.0 update 5

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
DB - 5.5.58

**Comment by prasa7** [comment]
Fixed in 3.x.x
