### ISSUE TITLE
API Manager 2.1.0 error for specific API (Could not save JSON payload)

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#2291]
**Description:**

When trying to invoke an API PUT resource without passing a body. And getting a request timeout. The issue has been reproduced by using content-aware message mediators.

PUT /platform/enabler/re/rule/1.0.0/test3878252/start HTTP/1.1
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXX
Content-Length: 0

**Suggested Labels:**
API Manager, severity/critical, Bug

**Suggested Assignees:**

**Affected Product Version:**
API Manager 2.1.0, 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create API  with content-aware message mediators in synapse config.
2.  Invoke PUT resource without passing a body

Related Issues:
1. https://github.com/wso2/product-ei/issues/1680

**Comment by SiluniPathirana** [comment]
Duplicate

**Comment by ChamNDeSilva** [comment]
Fix added with will fix once APIM have moved to latest JSON message builders and formatters.
PR already merged. 
Hence Closing the issue.
https://github.com/wso2/product-apim/pull/2432
