### ISSUE TITLE
'Enable Notification' section describes only the email as the notification option and only version change as the event

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2295]
**Description:**
When we consider notifications we have several events(ex: Check LC item, Update, Delete, LC Approved, etc) but we have mentioned only the change version option in the doc.
And also we have several output even adapters(ex: UI, JDBC, kafka, websocket, http, soap, etc) but we mention only the email option in the doc.
It will be more useful to provide information on other existing options on both subscription events and output adapters.
[1] https://docs.wso2.com/display/AM2xx/Enabling+Notifications

**Comment by bhathiya** [comment]
This APIM feature OOTB supports only "email notifications for API new version events". The default implementation is [1]. As mentioned in the docs, if you want to change the notification mechanism, you have to write your own implementation of `org.wso2.carbon.apimgt.impl.notification.Notifier`.

Notifications for Check LC item, Update, Delete, LC Approved, etc. is a registry feature, which is explained in [2].

[1] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/notification/NewAPIVersionEmailNotifier.java 
[2] https://docs.wso2.com/display/Governance530/Adding+a+Subscription
