### ISSUE TITLE
Publisher analytics - click on one of analytics sub option expands all parent options, and it is a usability issue

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2297]
**Description:**
Click on one of analytics sub option expands all parent options at publisher analytics, and it is a usability issue. See attached below.

**Suggested Labels:**
APIM-2.2.0
UX
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Goto publisher analytics
- Expand one option (subscription)
- Click on one sub option
![pun-analytic](https://user-images.githubusercontent.com/15671620/34708192-8257e994-f537-11e7-9f2d-763234499d1d.jpeg)

**Comment by chanaka3d** [comment]
Fixed with the https://github.com/wso2/carbon-apimgt/pull/5211
