### ISSUE TITLE
In "RESTful APIs" doc we have pointed  "WSO2 REST client" to previos doc version

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2298]
**Description:**
In [1\] the link of "WSO2 REST client" points to 2.1.0 docs. but there is a 2.x.x doc version for the same. Shall we point it to the 2.x.x docs?

[1\] [https://docs.wso2.com/display/AM2xx/RESTful+APIs](https://docs.wso2.com/display/AM2xx/RESTful+APIs)

**Suggested Labels:**
Docs, APIM 2.x.x

**Comment by taniamahanama** [comment]
Fixed.
