### ISSUE TITLE
Add -k to the curl command in Getting started guide first 

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2306]
**Description:**
In [1\], for the first curl command, lets improve it by adding a **-k** as below. Else the curl command will fail at first and then suggest to add -k.

`curl -k -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d @payload.json https://localhost:9443/client-registration/v0.11/register`

[1\] [https://docs.wso2.com/display/AM210/apidocs/publisher/index.html#guide](https://docs.wso2.com/display/AM210/apidocs/publisher/index.html#guide)

**Suggested Labels:**
Docs, APIM 2.x.x, Priority/High,Type/Bug

**Comment by shaniR** [comment]
fixed with 
1) 2.2.0 - https://github.com/wso2/carbon-apimgt/pull/4989
2) 2.1.0 - on support branch

**Comment by chamindias** [comment]
Fixed : https://github.com/wso2/carbon-apimgt/pull/4996
