### ISSUE TITLE
API governance sample - sample apps are created under admin user, it should be corrected to create under subscriber users

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2307]
**Description:**
API governance sample - sample 9
Two applications are created under admin user, but those should be created under subscriber users

**Suggested Labels:**
APIM-2.x.x
Type/improvement
sample-scenario

**Suggested Assignees:**
@prasa7 

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
-See attached below
![superuser](https://user-images.githubusercontent.com/15671620/34717017-a368883a-f557-11e7-80ed-002af20f2710.jpeg)

**Comment by chamilaadhi** [comment]
not necessarily. Application is created by an admin user. users can generate token using this application using password grant type.
