### ISSUE TITLE
Ownership, permission and collaborative API development

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2308]
In order to achieve $subject between different departments following perspectives can be used
1. Different tenant domains collaborating for API development and ownership and visibility should be maintained across tenants
2. Same tenant space can be used where the different departments are represented by roles.

AFAIK above 1 is not currently available with APIM 2.x.x as there is tenant space separation for created APIs. Hence in order to demonstrate a sample can above 2 be used?

**Comment by chamindias** [comment]
We have included a complete guide for this in : [Ownership, permission and collaborative API development - Sample Documentation](https://docs.wso2.com/display/AM2xx/Ownership%2C+permission+and+collaborative+API+development+-+Sample+Documentation)
