### ISSUE TITLE
store rest api - "apiIdentifier" parameter should be corrected for add subscription

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2309]
**Description:**
As $subject, the given page details [1] should be updated for "apiIdentifier" parameter description as well as example value.

**Suggested Labels:**
APIM-2.2.0
Documentation
Type/improvement
Priority/high

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update5

**Steps to reproduce:**
[1] <https://docs.wso2.com/display/AM210/apidocs/store/#!/models#Subscription>

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4989 for 2.2.0. For 2.1 fixed in support branch,
