### ISSUE TITLE
wso2am-runtime-puppet-module-hieradata-2.1.0.zip cannot be found in mentioned location or inside the downloaded folder. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2311]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6)
Section: 2.2 - Configure the Puppet Master
Step 6

1. It cannot be found wso2am-runtime-puppet-module-hieradata-2.1.0.zip in the respective download location or in the downloaded file.  The respective pointed repository in the doc has been updated. 

2. wso2-wso2am_runtime-2.1.0.tar.gz and wso2am-runtime-puppet-module-hieradata-2.1.0.zip points to the same download location.

**Affected Product Version:**
AM2xx docs

**Comment by isurulucky** [comment]
Fixed in [1].

[1]. https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6
