### ISSUE TITLE
Do we support Transferring contracts with app developers to newer versions in APIM 2.2.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2314]
**Labels**
APIM 2.2.0
Type/Doc
Priority/Highest

**Description**
Refer to document link [1]. Under usecase section there is a sub point as " Transferring contracts with app developers to newer versions " Is this feature available in APIM 2.2.0. If so please add details on how this is facilitated through APIM 2.2.0

[1]. https://docs.wso2.com/display/AM2xx/API+versioning

**Comment by bhathiya** [comment]
Here it is talking about "Require Re-Subscription" which is explained in [2].

[2] https://docs.wso2.com/display/AM2xx/Publish+the+New+Version+and+Deprecate+the+Old
