### ISSUE TITLE
When access control is implemented as restricted by roles. the expected functionality of that to the creator of the api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2319]
If a user who is a API CREATOR creates an api and provides access only to a separate role, then if the user does not specify one of the roles which he belongs to then the api will not be visible to the creator itself as per [1]. Is this the correct behavior? Following questions are there

1. Shouldn't the creator of the API irrespective of role should be able to view the api created by him the in the publisher?
2. By providing one of the roles that the creator is belonging it may be a case of conspiracy as the restrictions might get deviated from whats intended

**Comment by chamilaadhi** [comment]
API creator needs to have the role in-order to restrict from this role. (ex: create needs to have roleXx in-order to restrict the visibility using roleX ) . This validation is also there for this. Please check this in AM 2.6.0 . See the below image

<img width="837" alt="Screen Shot 2019-09-16 at 4 29 25 PM" src="https://user-images.githubusercontent.com/4861150/64953056-7bcddf00-d89f-11e9-9973-2fb3fa67144d.png">
