### ISSUE TITLE
Access control: the given steps are they only applicable/not applicable for WSO2 API Manager 2.1.0 - Update 2

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2322]
In [1] some steps are given as skip-able if the pack version is WSO2 API Manager 2.1.0 - Update 2. Are these only applies if the pack is WSO2 API Manager 2.1.0 - Update 2 ? What about the updates afterwards. How is the steps applicability after WSO2 API Manager 2.1.0 - Update 2 ? 

[1] https://docs.wso2.com/display/AM2xx/Enabling+Access+Control+Support+for+API+Publisher

**Comment by taniamahanama** [comment]
This has been fixed.
