### ISSUE TITLE
API Search field tool tip text is not clear enough in the Store

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2330]
**Description:**
Due the current color theme in the store, the tool tip text of the search bar is not clear. Better to have a suitable color like white for the font.

Please see the screen below. 
![image](https://user-images.githubusercontent.com/7115693/34774301-cf533264-f634-11e7-98c7-0ddca7cdfeee.png)

**Comment by chanaka3d** [comment]
Fixed with the PR https://github.com/wso2/carbon-apimgt/pull/5219
