### ISSUE TITLE
Entries in common.yaml is incorrect in the doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2333]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6)
2.2 - Configure the Puppet Master
Step 9)v
 The given value of the host entry in the /etc/puppet/hieradata/production/wso2/common.yaml to be updated is incorrect. 
It should be as below. 

`puppetmaster:
    ip: [ip of puppetmaster]
    name: puppet
`
**Suggested Labels:**
AM2xx docs

**Affected Product Version:**
AM2xx

**Comment by ChamNDeSilva** [comment]
Fixed.
