### ISSUE TITLE
No API available for adding notification subscriptions for APIs

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2335]
**Description:**
I want to automate adding a subscription for notifications for lifecycle change of an API. Currently this can be done by mgt console API metadata section. Please see the below image.

![image](https://user-images.githubusercontent.com/7115693/34776502-2f7e8f46-f63d-11e7-8285-3674667951e0.png)

couldn't find any API exist for the above in [1], do we have any other way to do this?

[1] https://docs.wso2.com/display/AM2xx/Product+APIs

**Comment by bhathiya** [comment]
You can do this by `InfoAdminService`[1]

[1] https://docs.wso2.com/display/Governance530/Adding+JMX+Subscriptions+to+a+Resource
