### ISSUE TITLE
Incomplete information about key manager configuration - APIM2xx puppet modules

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2337]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#pattern6)
Step 5 - Update the clustering related configurations

Please include puppetmaster configuration details for key manager. 
1. Download wso2is-prepacked-puppet-module-hieradata-5.3.0.zip from https://github.com/wso2/puppet-apim/releases/ 

2. Extract it and copy the  hieradata folder to the /etc/puppet/ directory.
Once it is done, /etc/puppet/hieradata/production/wso2 folder structure should be as below. 
`common.yaml  wso2am_analytics  wso2am_runtime wso2is_prepacked`

3. Download wso2-wso2is_prepacked-5.3.0.tar.gz file from https://github.com/wso2/puppet-apim/releases/ 

4. extract the folder and rename as wso2is_prepacked
5. copy the renamed folder into /etc/puppet/environments/production/modules

6. Finally copy the latest  wso2is-5.3.0.zip file in to /etc/puppet/environments/production/modules/wso2is_prepacked/files. 
Download the pack from http://product-dist.wso2.com/downloads/api-manager/2.1.0/identity-server/wso2is-5.3.0.zip as per README.md

**Affected Product Version:**
AM2xx

**OS, DB, other environment details and versions:**    
Ubuntu 14.04

**labels:**
clustering 
puppetModules

**Comment by ChamNDeSilva** [comment]
Note that API Manager puppet module **pattern-6** does not use any Prepackaged IS as Key Manager. It is used in pattern-7.
And also it is not related to Step 5 - Update the clustering related configurations in non of the patterns where clustering configurations are described.

Added some missing steps in pattern-7 related to prepackaged IS as Key Manager hieradata in following docs.
https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+7
https://docs.wso2.com/display/AM210/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+7
