### ISSUE TITLE
Specify database configuration details in AM2xx puppet modules doc. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2340]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#pattern6)
Step 5 - Update the clustering related configurations

Please specify the details about database configurations as below. 
 - what are the databases need to be created using which database scripts
 - Specify if the databases should be created using a separate instance. 

**Suggested Labels:**
AM2xxPuppetModules
AMclustering

**Affected Product Version:**
AM2xx

**Comment by ChamNDeSilva** [comment]
Fixed in https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#UsingPuppetModulestoSetupWSO2API-MwithPattern6-Step5-Updatetheclusteringrelatedconfigurations
Convering all the patterns.
