### ISSUE TITLE
wso2-wso2am_runtime-2.1.0.tar.gz cannot be find in the specified location 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2341]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#pattern6)
2.2 - Configure the Puppet Master
Step 6

The . download location has been pointed as https://github.com/wso2/puppet-apim/releases/tag/v2.1.0, but wso2-wso2am_runtime-2.1.0.tar.gz file cannot be found. 

**Affected Product Version:**
AM2xx docs

**Comment by isurulucky** [comment]
Fixed in [1]. 

[1]. https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6
