### ISSUE TITLE
The path of the common yaml file is incorrect

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2342]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#b32839f08c01498abbe85fc8907dc2b2)
Step 5 - Update the clustering related configurations
Step 3

The path of the common.yaml should be corrected as below. 
`/etc/puppet/hieradata/production/wso2/wso2am_runtime/[pattern-number]/ common.yaml
`

**Suggested Labels:**
bug
AM2xxPuppetModules
Clustering

**Affected Product Version:**
AM2xx

**Comment by Mariangela** [comment]
Updated the paths related to all the patterns in step 1 as follows:
/etc/puppet/hieradata/dev/wso2/wso2am_runtime/pattern-0/default.yaml
OR
/etc/puppet/hieradata/dev/wso2/wso2am_runtime/pattern-6/common.yaml

I used the environment name as "dev" as opposed to "production"

https://docs.wso2.com/display/AM2xx/Configuring+Clustering+for+a+Selected+Pattern
https://docs.wso2.com/display/AM210/Configuring+Clustering+for+a+Selected+Pattern
https://docs.wso2.com/display/AM220/Configuring+Clustering+for+a+Selected+Pattern
