### ISSUE TITLE
Rest Search API in Store: provide a sample of using X-WSO2-Tenant header in request

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2343]
In [1] it states either of the following should be present for the request to work in tenant
1. X-WSO2-Tenant header with tenant domain
2. Bearer token generated for the specific tenant.

Usually a user would glance at the information and the sample provided and proceed. In the sample it does not provide a bearer token, hence he might try out with that at once. Since this does not work for tenants, can we include a sample on how it will work for tenants. Samples should be organized so that it explains super tenant flow as well as tenant flows with an explanation with why we need to include something if we are required to do so.

[1] https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#APICollection#apisGet

**Comment by shaniR** [comment]
fixed in 2.2.0 with https://github.com/wso2/carbon-apimgt/pull/5000. Added to support branch 2.1
