### ISSUE TITLE
Include Response code 500 under Change API status

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2344]
**Suggested Labels:**
APIM 2.2.0
Type/Doc

**Description:**
Refer to doc link [1]. Add the response code 500 Under Change API status as
Response code: 500
Response message: Internal Server Error

[1].https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisChangeLifecyclePost

**Comment by shaniR** [comment]
Adding 500 would not be bring much value addition to the API user as it is a general error code, stating that an Internal Server error has occurred, but we cannot provide any solid reason, as there are number of reasons why this could happen. Hence we will not add it to documents
