### ISSUE TITLE
Inadequate description on the topic - Configuring a Single Node

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2347]
**Description:**
The section is about configuring Single Node Deployment, but no any description or introduction prior going to configurations. Only a notification section is there which giving information on KeyManager setup. So this is bit confusing. Prior to that notification section, better if we can give brief intro on the exact topic we discuss.

[1] https://docs.wso2.com/display/AM2xx/Configuring+a+Single+Node

**Comment by isurulucky** [comment]
Added a description [1].

[1]. https://docs.wso2.com/display/AM2xx/Configuring+a+Single+Node
