### ISSUE TITLE
No contents are on the page

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2350]
**Description:**
No contents are on the page [1] and it is misformated.

[1] https://docs.wso2.com/pages/createpage.action?spaceKey=AM210&title=Configuring+the+Proxy+Server+and+the+Load+Balancer&linkCreation=true&fromPageId=57764133

![image](https://user-images.githubusercontent.com/7115693/34811834-e75b0e24-f6c8-11e7-8d26-1eab64367c2b.png)

**Comment by taniamahanama** [comment]
This is not a bug. It looks like you are trying to create a new page in the docs and that is the Edit mode of Confluence. How did you get here? If you were re-directed from another page, please provide that link and reopen this issue.
