### ISSUE TITLE
Add details related to using Registry REST APIs in APIM Scenarios

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2351]
**Suggested Labels:**
APIM 2.2.0
Type/Docs
Priority/Highest
Severity/Critical

**Description:**
No information is available in the APIM Docs related to REST APIs that need to be used for updating/adding a registry resource file. These details are available in Governance 5.4.0 [1]. But it is not providing any guidance for a user who is using APIM and needs to update a registry resource file using a registry API. Please provide these details in the APIM Doc [2].

[1]. https://docs.wso2.com/display/Governance540/Registry+REST+API
[2]. https://docs.wso2.com/display/AM210/WSO2+Admin+Services

**Comment by isurulucky** [comment]
This is added to APIM 2.1 docs now [1]. There is a discussion whether to add the registry rest API webapp by default to APIM 2.2.0. The 2.2.0 page should be updated accordingly. 

[1]. https://docs.wso2.com/display/AM210/Using+Registry+Rest+API

**Comment by ChamNDeSilva** [comment]
Added the page to 2.x.x docs. 
I will keep the issue opened until the final conclusion made about adding keeping this doc in 2.2.0

**Comment by bhathiya** [comment]
Reducing priority as we can do the same with ResourceAdminService[1] SOAP service. It comes with APIM itself.

[1] https://github.com/wso2/carbon-registry/blob/master/components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/ResourceAdminService/ResourceAdminService.wsdl

**Comment by bhathiya** [comment]
Fixed and updated https://docs.wso2.com/display/AM210/Using+the+Registry+REST+API
