### ISSUE TITLE
No information on how Enforcing a grace period to upgrade to the new version of the API is facilitated in APIM 2.2.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2352]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Priority/Highest

**Description:**
Refer to doc link [1]. Doc mention as " Enforcing a grace period to upgrade to the new version of the API" under use case section. But there is no any information how this is facilitated through APIM 2.2.0 in the APIM Docs. Please add the following details related to this

How this can be achieved is by using the notifications functions when new API versions are created and by the API deprecation feature. So what will happen when a new version of an API is published is that a notification should be sent to existing subscribes to notify them that the API will be deprecated in X months and retired in Y months. Then the API publisher has to actually perform those actions (deprecate and retire) in X and Y respectively.

[1]. https://docs.wso2.com/pages/viewpage.action?spaceKey=AM2xx&title=API+Versioning

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM2xx/API+Versioning
