### ISSUE TITLE
Why do we specify a callback url when creating an application via api call

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2356]
**Description:**
As per [1\] we need to provide a call back url when creating an application. But that url is not visible in production / sandbox call back url section in the store. Where is this specified call back url been used?

[1\] [https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#ApplicationIndividual#applicationsPost](https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#ApplicationIndividual#applicationsPost)

**Suggested Labels:**
APIM 2.1.0 update 5 , Bug, Priority/High

**OS, DB, other environment details and versions:**    
Ubuntu 14
Java version "1.8.0_51"
Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
DB - 5.5.58

**Comment by chamindias** [comment]
It will be used when using the [token API](https://docs.wso2.com/display/AM2xx/Token+API). For example, please see [Authorization Code Grant](https://docs.wso2.com/display/AM2xx/Authorization+Code+Grant). Answered hence resolving.
