### ISSUE TITLE
Specify it needs to be created the related databases which is specified in wso2am_analytics - default.yaml 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2359]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#b32839f08c01498abbe85fc8907dc2b2)
Step 5 - Update the clustering related configurations
3)a

Please explain the following. 
- According to the wso2am_analytics - default.yaml file, which databases need to be created in the database instance. 
- what are the database scripts which should be used to create them? 
- Specify that database instance needs to be pointed out in [1] 

[1] - /etc/puppet/hieradata/production/wso2/wso2am_analytics/pattern-1/default.yaml 

**Suggested Labels:**
AM2xxpuppetmodules

**Affected Product Version:**
AM2xx

**Related Issues:**
https://github.com/wso2/product-apim/issues/2357

**Comment by ChamNDeSilva** [comment]
Fixed.
