### ISSUE TITLE
Specify how to created following tables referring which scripts?

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2360]
**Description:**
Document: [Using Puppet Modules to Set up WSO2 API-M with Pattern 6](https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#b32839f08c01498abbe85fc8907dc2b2)
Step 5 - Update the clustering related configurations
3)a

Specify which database scripts should be referred to create the following databases. 
- analyticseventstoredb
- analyticprocesseddatastoredb
- statdb

**Suggested Labels:**
AM2xxpuppetmodules

**Affected Product Version:**
AM2xx

**OS, DB, other environment details and versions:**    
Ubuntu 14.04

**Related Issues:**
https://github.com/wso2/product-apim/issues/2359

**Comment by ChamNDeSilva** [comment]
we do not need to run db scripts against the above mentioned databases as the tables created at runtime for those databases.
Added these details in https://docs.wso2.com/display/AM2xx/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6#UsingPuppetModulestoSetupWSO2API-MwithPattern6-Step5-Updatetheclusteringrelatedconfigurations
