### ISSUE TITLE
Typo in Enabling+Role-Based+Access+Control+Using+XACML doc

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#2362]
**Description:**
Check the text "You can test the service by clicking Try option infront of the entitlement policy. It is the tryIt tool developed for XACML in WSo2 Identity Server and you an access the same tryIt tool by navigating to Tools > XACML > TryIt." in step 11 if [1]

Which should be corrected as 
You can test the service by clicking Try option in front of the entitlement policy. It is the tryIt tool developed for XACML in WSo2 Identity Server and you can access the same tryIt tool by navigating to Tools > XACML > TryIt.

[1] https://docs.wso2.com/display/AM210/Enabling+Role-Based+Access+Control+Using+XACML

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.

https://docs.wso2.com/display/AM210/Enabling+Role-Based+Access+Control+Using+XACML
https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML
