### ISSUE TITLE
unrecognizable messages and popups appear in publisher

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#2366]
**Description:**
1. when Try to delete API in API Overview page this popup message appear 
![test1](https://user-images.githubusercontent.com/8374895/34827336-cb98f78c-f6ff-11e7-8c66-a017cc47330c.png)

2. After deleting All API in list view, it showing some unwanted message 
![test2](https://user-images.githubusercontent.com/8374895/34827461-43024ff8-f700-11e7-8e37-c84a39095d3d.png)

**Comment by tmkasun** [comment]
This will be a part of this https://github.com/wso2/product-apim/issues/1951 issue, removing `antd` library

**Comment by Krishanx92** [comment]
![image](https://user-images.githubusercontent.com/8374895/34872840-a13d938a-f7b8-11e7-92fb-9d4d6da339d7.png)

![image](https://user-images.githubusercontent.com/8374895/34872878-c260eeae-f7b8-11e7-810e-7ae18b810ab6.png)
