### ISSUE TITLE
Small grammer error in delete user admin service (RemoteUserStoreManagerService) error message

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2370]
Please see the below error message with deleteUser in RemoteUserStoreManagerService

```
Caused by: org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist

```
This should be `Cannot delete user who does not exist`

**Comment by chamilaadhi** [comment]
Fixed in Latest versions. Following error message is shown in APIM 2.6.0

`Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User test does not exist in: PRIMARY`
