### ISSUE TITLE
Mention what is the purpose of setting the  preserveProvider parameter value to false.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2375]
**Suggested Labels:**
APIM 2.2.0
Type/Docs

**Description:**
Refer to doc link [1]. Related to the section API import/export in a tenanted environment Mention what is the purpose of setting the preserveProvider parameter value to false.

[1].https://docs.wso2.com/display/AM2xx/Migrating+the+APIs+to+a+Different+Environment#MigratingtheAPIstoaDifferentEnvironment-ExportanAPI

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.

https://docs.wso2.com/display/AM210/Migrating+the+APIs+to+a+Different+Environment
https://docs.wso2.com/display/AM2xx/Migrating+the+APIs+to+a+Different+Environment
