### ISSUE TITLE
Remove unnecessarily enabled hyperlink for data types at api docs pages

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2383]
**Description:**
I have observed hyperlinks enabled for primitive data types in api docs and if I click on that, it is directing to blank page. If it is not useful can we remove the hyperlinks from all relevant places at pub/store/admin rest api doc pages as example in here [1, 2 & 3]?

**Suggested Labels:**
APIM-2.2.0
Documentation
Type/improvement

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
[1] <https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#API>
[2] <https://docs.wso2.com/display/AM210/apidocs/store/#!/models#string>
[3] <https://docs.wso2.com/display/AM210/apidocs/admin/#!/models#AdvancedThrottlePolicyList>

**Comment by ruthryi** [comment]
These HTML files are auto-generated from the corresponding YAML files. Therefore formatting these changes each and every time is an unnecessary overhead.
