### ISSUE TITLE
Mention that a server restart is needed after setting DisplayMultipleVersions to true to see the applied changes

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2384]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Priority/Highest

**Description:**
Refer to doc link [1]. Under step 7  there is a Tip which mention to set the DisplayMultipleVersions element to true in the APIM_HOME/repository/conf/api-manager.xml file.

Here mention that a server restart is needed to see the applied changes after doing this configuration

[1]. https://docs.wso2.com/display/AM2xx/Create+a+New+API+Version

**Comment by chamindias** [comment]
Fixed in : https://docs.wso2.com/display/AM2xx/Create+a+New+API+Version and https://docs.wso2.com/display/AM210/Create+a+New+API+Version
