### ISSUE TITLE
Add a message in listing pages when there is no APIs/Applications

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2386]
**Description:**
User is taken in to blank listing pages when there is no APIs/Applications in the listings. Add a not found message.

**Suggested Labels:**
UI/UX, Store

**Comment by erangatl** [comment]
Fixed in latest

![image](https://user-images.githubusercontent.com/20179540/64243063-54ccf000-cf24-11e9-8dbc-36e3bc8ea331.png)
