### ISSUE TITLE
Clean up JSON files

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#2389]
**Description:**

Noticed comments on site.json files and some validation issue in other files.

#### wso2am-2.1.0.1515157274195
====================================

- `wso2am-2.1.0\repository\deployment\server\jaggeryapps\admin\site\conf\site.json` _- (comments)_

- `wso2am-2.1.0\repository\deployment\server\jaggeryapps\portal\extensions\locales\locale_si.json` _- (unexpected characters)_

- `wso2am-2.1.0\repository\deployment\server\jaggeryapps\publisher\site\conf\site.json` _- (comments)_

- `wso2am-2.1.0\repository\deployment\server\jaggeryapps\store\site\conf\site.json` _- (comments)_

#### wso2am-analytics-2.1.0.1514437201537
====================================

- `wso2am-analytics-2.1.0\repository\components\features\org.wso2.carbon.analytics.gadget.chart.template_5.1.7\charts\geo-map\config.json` _- (ending commas)_

- `wso2am-analytics-2.1.0\repository\components\features\org.wso2.carbon.dashboards.portal_2.0.0\portal\extensions\locales\locale_si.json` _- (unexpected characters)_

- `wso2am-analytics-2.1.0\repository\deployment\server\jaggeryapps\portal\extensions\chart-templates\geo-map\config.json` _- (ending commas)_

- `wso2am-analytics-2.1.0\repository\deployment\server\jaggeryapps\portal\extensions\locales\locale_si.json` _- (unexpected characters)_

**Suggested Labels:**
[2.1.0] [Priority/High] [Severity/Minor]

**Comment by chamilaadhi** [comment]
above mentioned files are removed with APIM 3.0.0 new UI changes. Analytics are also move to SP.
