### ISSUE TITLE
Include details on the APIM specific pre-configured roles in Adding user section

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2390]
In [1] currently there is a mentioning on the default roles shipped with all WSO2 products. Since there are some default roles packed with which are APIM specific, please include them in [1] so that the user would get an idea what the roles are what their intended usage is

[1] https://docs.wso2.com/display/AM2xx/Adding+Users

**Comment by chamindias** [comment]
Improved the doc : https://docs.wso2.com/display/AM2xx/Adding+Users
