### ISSUE TITLE
Configuring secondary user store reference in Add User section directs to WSO2 App Store

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2391]
In [1] the link for "Configuring secondary user store" directs to WSO2 App Store. When logged in there is no page content. Please include the content.

[1] https://docs.wso2.com/display/AM2xx/Adding+Users

**Comment by taniamahanama** [comment]
Related to https://wso2.org/jira/browse/DOCUMENTATION-4185

**Comment by ChamNDeSilva** [comment]
Fixed with https://wso2.org/jira/browse/DOCUMENTATION-4185
with correct re-directions.
