### ISSUE TITLE
Configure secondary user store: search result does not bring out relevant page

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2393]
Please see the below image which is the search result for the string "configure secondary user store". Apparently the relevant page is not listed.

![apim_doc_issue_5](https://user-images.githubusercontent.com/15624590/34872335-83367dae-f7b6-11e7-8b8b-0e11e0f53960.png)

Also the string "secondary user store" is not bringing out expected pages.

**Comment by taniamahanama** [comment]
Related to https://wso2.org/jira/browse/DOCUMENTATION-4185

**Comment by ruthryi** [comment]
Closing this since the linking has been fixed from 2.2.0 onwards.

![screen shot 2018-09-11 at 1 42 12 pm](https://user-images.githubusercontent.com/23217207/45347003-91436580-b5c8-11e8-9fde-fb60aec58cd8.png)
