### ISSUE TITLE
Advance throttling policy cannot be added with unit time for seconds via UI

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2394]
**Description:**
When adding an advance throttling policy from admin dashboard, user cannot select unit time as second; But this can be done using admin rest api (see attached)

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/highest
Severity/major

**Affected Product Version:**
2.1.0-update5

**Steps to reproduce:**
- Enable advance throttling in api-manager.xml
- Go to admin dashboard and create an advance throttling policy
- Select unit time as second => user cannot see "sec" value in the drop down. This is observed in both "default time limit" and unit time under conditional group.
Note that this can be achieved by rest api, therfore this needs to be fixed in UI as well.

![persec](https://user-images.githubusercontent.com/15671620/34872627-a88b5894-f7b7-11e7-8413-ab85a2239f3a.jpeg)

**Comment by chamindias** [comment]
PR : https://github.com/wso2/carbon-apimgt/pull/5065
