### ISSUE TITLE
Admin analytics - "filterby" option doesn't work at the API availability stats page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2395]
**Description:**
As $subject see attached.

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/major

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    
enabled apim analytics (apim-analytic-2.1.0-update3)

**Steps to reproduce:**
- Crate some APIs in publisher
- Goto admin dashboard -> Analytics
- Click on availability of API section
- Try with filterby optin to search api name

**Comment by isharac** [comment]
Latest APIM 3.2.0 has changed to Analytics dashboard. Please reopen if you still encounter this issue with the latest version.
