### ISSUE TITLE
publisher app footer logo missing

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2397]
**Description:**
Footer shows WSO2 APIM Publisher v3.0.0 | © 2017 Inc.

Needs to add logo in-between 2017 and Inc

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanaka3d** [comment]
We do not place a logo at the footer according to the 3.x design
