### ISSUE TITLE
Add tip/small description for "invertCondition" at admin rest apidocs for adding conditional type twice

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2400]
**Description:**
When adding conditional group for advance throttling policy while created policy from rest api, there is a parameter call "invertCondition" and it should be given same value (true/fasle) for same type of conditional group. If we give different value in payload, it will be taken last "invertCondition" value for given type and update. this is because multiple raws can be added for one type and can make invertible.

So please update the doc [1] with a small tip or under description, saying that to keep same value for "invertCondition" if user adding two value set for same type like in attached.
![cond](https://user-images.githubusercontent.com/15671620/34876772-137c6592-f7c9-11e7-8776-fa8b1244d15d.jpeg)

**Suggested Labels:**
APIM-2.2.0
Documentation
Type/improvemement
Priority/high

**Affected Product Version:**
2.1.0-update5

**Steps to reproduce:**
[1] <https://docs.wso2.com/display/AM210/apidocs/admin/#!/models#AdvancedThrottlePolicy>

**Comment by ruthryi** [comment]
This has been updated in the docs [1] for AM2xx
[1] : https://docs.wso2.com/display/AM2xx/apidocs/admin/#!/models#ThrottleCondition
