### ISSUE TITLE
Provide samples for at least few of the major languages to invoke APIM endpoint

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2401]
**Description:**
Similar to [1\] it is better to provide guides for at least few other SDK's which will be helpful for the users to quickly. E.g Android, C#, php.

[1\] [https://docs.wso2.com/display/AM2xx/Write+a+Client+Application+Using+the+SDK](https://docs.wso2.com/display/AM2xx/Write+a+Client+Application+Using+the+SDK)

**Suggested Labels:**
Docs, 2.x.x APIM, Type/Improvement, Priority/High

**Comment by chamindias** [comment]
This is related to [another JIRA](https://wso2.org/jira/browse/DOCUMENTATION-6858) which was reported earlier. There we have added a description as a comment. Also please see [this JIRA](https://wso2.org/jira/browse/DOCUMENTATION-6931) and [article](https://wso2.com/library/articles/2017/03/article-introducing-sdk-support-with-wso2-api-manager/).
