### ISSUE TITLE
Include a description for "conditionalGroup" at admin rest apidoc

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2402]
**Description:**
Include a description for "conditionalGroup" at admin rest api doc. Since it is having some parameters to be inserted as an array it will be help the user to uderstand what should be the parameter and values.

**Suggested Labels:**
APIM-2.2.0
Type/document
Type/bug
Priority/high

**Affected Product Version:**
2.x.x

**Steps to reproduce:**
[1] <https://docs.wso2.com/display/AM210/apidocs/admin/#!/models#AdvancedThrottlePolicy>

**Related Issues:**
#2400

**Comment by ChamNDeSilva** [comment]
Fixed with 
https://github.com/wso2/carbon-apimgt/pull/5002
https://github.com/wso2-support/carbon-apimgt/pull/745
