### ISSUE TITLE
The JMeter SDK downloadaded needs a README on how to use the script provided

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2403]
**Description:**
Need to provide a guide / README for the JMeter SDK provided via api SDK download section because the JMeter script needs to be configured to get it to running state. It does not run OOB.

**Suggested Labels:**
APIM 2.2.x Update 5, Bug, Priority/High

**Comment by sanjeewa-malalgoda** [comment]
We are using Open API code generator here and do not have option to inject our own documents to this. Latest Jmeter scripts generated works with some minor changes(adding token etc). So we are closing issue.
