### ISSUE TITLE
Context Path limitations

### ISSUE THREAD

**Issue by samtonyclarke** [wso2/product-apim#2405]
Hi,
This is a follow up to: https://wso2.org/jira/browse/APIMANAGER-6046

Thanks @uvindra 
I understand your suggestion. However it looks like a large workaround for a short coming in WSO2,  Give than WSO2 knows the context path and knows all the resource paths from the swagger what prevents WSO2 from correctly routing to the back end?

Tony

**Comment by kavishkafernando** [comment]
Hi Tony,

We consider Context path as a unique identifier otherwise there is no way for the GW to tell two different APIs apart.
