### ISSUE TITLE
Update cipher tool version 

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#2408]
**Description:**
Current cipher tool version in APIM 2.1.0 is "org.wso2.ciphertool-1.0.0-wso2v3".
With this version -Dchange option is not working. That means we can not change the password after setting the password from cipher tool.
Hence We need to update it to latest version.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamindias** [comment]
Fixed : https://github.com/wso2/product-apim/pull/3370
