### ISSUE TITLE
Need to provide statistics for SDK specific invocations

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2414]
**Description:**
We provide different SDKs  ( java, python, php etc.) for each API. In a situation where two or more client apps are created against one API using the SDKs provided, the app developers should be able to view statistics for each client app specific. Currently, we provide only application respective statistics which will have cumulative information. 

Refer dev mail : [APIM] [Analytics] Can we analyze api invocations against the app language

E.g API 1 : Java SDK -> provide analytics for specifically java app
       API 2 : PHP SDK - > provide analytics specifically for PHP app

**Suggested Labels:**
 Type/Improvement, APIM 2.x.x, Priority/High

**Comment by bhathiya** [comment]
I don't think there is a way we can identify which SDK was used to do an invocation. User-Agent header also can be different as per the HTTP client used inside the application.
