### ISSUE TITLE
PHP SDK is failing

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2417]
**Description:**
Downloaded the PHP SDK and followed the README. It seems to fail due to mismatch of folder structure changes in the SDK. 
When I ran the sample code I am given the below error. Can we verify the php sample and improve the readme.

![php](https://user-images.githubusercontent.com/17248809/34927625-8d8ddb5c-f9dd-11e7-8610-bb0f40356fd9.png)

E.g - $api_instance = new Swagger\Client\Api\DefaultApi(); 
When I searched for the DefaultApi.php class its located at -> `SwaggerClient-php/lib/org/wso2/client/api/PizzaShackAPI`

**Suggested Labels:**
Type/Bug, APIM 2.x.x, Priority/Highest

**Comment by chamindias** [comment]
These instructions are auto generated from the swagger-codegen itself. Hence, we are unable to do customizations for those files from APIM code base.

**Comment by jsonds** [comment]
Then the README provides contradicting information to get the sample to run. What can be the recommendation or the guide I can use to get started with since the README is auto generated.
