### ISSUE TITLE
Rest API: Subscription to an API with specific_tenants and tenant list [] fails for non creator tenants

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2418]
OS: Ubuntu 16.04
JDK: 1.8.0_144
DB: Mysql 5.7 (apimdb and carbondb)

Steps
1. Created API with the following payload
```
{
   "name": "${apiname}",
   "description": "This document describe a RESTFul API for TestAPIfromREST API.\r\n",
   "context": "${context}",
   "version": "1.0.0",
   "provider":"${username}",
   "apiDefinition":"{\"swagger\":\"2.0\",\"paths\":{\"${resource}\":{\"get\":{\"responses\":{\"200\":{\"description\":\"this is test\"}},\"parameters\":[{\"name\":\"id\",\"in\":\"path\",\"allowMultiple\":false,\"required\":true,\"type\":\"string\"}],\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Unlimited\"}}},\"info\":{\"title\":\"${apiname}\",\"version\":\"1.0.0\"}}",
   "isDefaultVersion": false,
   "type": "HTTP",
   "transport":    [
      "http",
      "https"
   ],
   "tiers": ["Unlimited"],
   "visibility": "${visibility}",
   "endpointConfig": "{\"production_endpoints\":{\"url\":\"http://${tomcathost}:${tomcatport}/${backend}\",\"config\":null},\"sandbox_endpoints\":{\"url\":\"${backend}\",\"config\":null},\"endpoint_type\":\"http\"}",
   "subscriptionAvailability": "specific_tenants",
   "subscriptionAvailableTenants": null
}
```
Since the tenant list in above is [] (empty array], shouldn't other tenants (other than the creator tenant) be able to subscribe to this api?

**Comment by chamindias** [comment]
In this case, the system behaves as expected. Other tenants (other than the creator tenant) should not be able to subscribe. Please see references [1],[2] and [3].

[1] https://docs.wso2.com/display/AM210/Key+Concepts#KeyConcepts-APIvisibilityandsubscriptionAvailability
[2] https://wso2.com/library/articles/2016/08/article-multi-tenant-api-management-with-wso2-api-manager/#apimanagement
[3] https://www.yenlo.com/blog/wso2easy-determining-api-visibility-subscriptions-and-invocation-in-wso2-api-manager-2.1.0
