### ISSUE TITLE
Need to mention the exact locator of the parameter "stringType"

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2427]
**Description:**
under the step 2 section In "Configuring databases" section in [1], we have mentioned to do mysql specific change in the <API-M_ANALYTICS_HOME>/repository/conf/analytics/spark/spark-jdbc-config.xml file. 
In above config file there are multiple stringTypes and multiple typeMapping objects. The user might do the change under first typeMapping instance in the file but it is related to H2. So better to mentioned typeMapping under <database name="mysql"> section.

[1] https://docs.wso2.com/display/AM2xx/Configuring+a+Single+Node

![image](https://user-images.githubusercontent.com/7115693/34978404-1d26a992-fac4-11e7-9bf0-fe15bd465833.png)

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM2xx/Configuring+a+Single+Node
