### ISSUE TITLE
Rest API: usage of "visibleTenants" when creating an api

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2428]
In [1] there is an indication of **visibleTenants** which can be used when creating an api. But for both access control and visibility on store there is no option to limit the visibility of the api in specific tenants. There is **subscriptionAvailableTenants** to control the subscription to tenants. Please indicate the usage of this particular field and where exactly this is associated in the UI

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/models#API

**Comment by shaniR** [comment]
Fixed with 
1) 2.2.0 - https://github.com/wso2/carbon-apimgt/pull/4989
2) 2.1.0 - https://github.com/wso2-support/carbon-apimgt/pull/739
3) 2.0.0- https://github.com/wso2-support/carbon-apimgt/pull/737
