### ISSUE TITLE
Mention the file location where we need to set offset for the identity server

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2429]
**Suggested Labels:**
APIM 2.2.0
Type/DocS
Type/Improvement

**Description:**
In the doc link [1] under step 6 mention in which .xml file we need to set the offset in identity server 

eg :- <Identity_server_home>/repository/conf/carbon.xml file

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
Fixed in following docs.
https://docs.wso2.com/display/AM210/Log+in+to+the+API+Store+using+Social+Media
https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
