### ISSUE TITLE
Typo needs be corrected at prototype api page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2430]
**Description:**
Typo needs be corrected at prototype api page in [1], under Step.5 (see attached)

**Suggested Labels:**
APIM-2.2.0
Type/documentation
Type/bug
Priority/medium

**Affected Product Version:**
2.x.x

**Steps to reproduce:**
![typo](https://user-images.githubusercontent.com/15671620/34979536-90867d10-fac7-11e7-8e32-25f8ed838628.jpeg)

**Comment by ruthryi** [comment]
This is not a typo. Therefore, closing this issue.
