### ISSUE TITLE
No clue in the doc for that we have separate scripts for MySQL5.7

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2436]
**Description:**
Better put a note in here[1], saying about mysql script deviation for 5.7 versions. We have to specifically mention it here even if we mention it in a different place since single point of access for the information is useful for the user.

[1] https://docs.wso2.com/display/AM210/Changing+the+Default+API-M+Databases

**Comment by ChamNDeSilva** [comment]
Fixed in docs.

https://docs.wso2.com/display/AM210/Changing+the+Default+API-M+Databases
https://docs.wso2.com/display/AM2xx/Changing+the+Default+API-M+Databases
