### ISSUE TITLE
Few hyperlinks points to old IS Docs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2438]
**Description:**
Update the hyperlink "Management console" in [1] to point to the latest IS doc
Update the hyperlink "Federated Authentication" in [1] to point to the latest IS doc
Update the hyperlink "Claim Management" in [1] to point to the latest IS doc
Update the hyperlink "Email Authenticationt" in [1] to point to the latest IS doc

**Suggested Labels:**
APIM 2.2.0
Type/Doc

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
Fixed in https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
