### ISSUE TITLE
Provide a sample value that needs to be given for the Callback URL in configuring SSO for API Store using Facebook

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2439]
**Description:**
Refer to doc link [1]. Under step 9, provide a sample value that needs to be given for the callback URL

**Suggested Labels:**
APIM 2.2.0
Type/Doc
Priority/Highest

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
https://docs.wso2.com/display/AM210/Log+in+to+the+API+Store+using+Social+Media
