### ISSUE TITLE
Mention the purpose of giving a Scope value in SSO for API store using Facebook

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2440]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Priority/Highest

**Description**
Refer to doc [1]. Under step 9 mention the purpose of giving a scope value

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
Fixed 
https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
https://docs.wso2.com/display/AM210/Log+in+to+the+API+Store+using+Social+Media
