### ISSUE TITLE
Include details on configuring SAML SSO as the inbound authentication when configuring STORE/PUBLISHER as the SP

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2443]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Severity/Crtical
Priority/Highest

**Description:**
Refer to doc [1]. Under the topic "Configure service providers to the Publisher and Store with the Facebook Identity Provider" doesn't mention any configuration details related to configuring SAML SSO Inbound Authentication for the Service Provider. Please include these details or point the users for a location where these configuration details are mentioned.

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
In the introductory description, it says 

> Before following these steps, configure WSO2 Identity Server to provide Single Sign On for WSO2 API Manager by following Configuring External IDP through Identity Server for SSO.
