### ISSUE TITLE
Add a note to mention the mandatory configurations that are required to be done related to SSO with Facebook

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2444]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Type/Improvement

**Description:**
In link [1]. Under the topic " Configure Facebook login with Identity Server" refer to the step 2 which has a hyperlink as "Configure Single Sign On with WSO2 API Manager 2.1.0.". This hyperlink points the users for a page that has several other configurations. Here under step 2 it is better to add a note and mention what are the mandatory configurations which the user needs to follow related to Login to the API Store using Facebook. 

[1]. https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media

**Comment by ChamNDeSilva** [comment]
Fixed with https://github.com/wso2/product-apim/issues/2602
