### ISSUE TITLE
Login to store is not working at first step when accessing store page through 'View in store' option

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2445]
**Description:**
Login to store is not working at first step when accessing store page through 'View in store' option, and user can login only after click on 'goback' to store and come again

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/Highest
Severity/critical

**Affected Product Version:**
apim-2.1.0-update6

**OS, DB, other environment details and versions:**    
apim-2.1.0-update4 analytics configured

**Steps to reproduce:**
- Add an API
- Go to View API and click on "View in Store" option => User will be navigated to store page
- Enter username and password and click login button => Login not works (see attached)
Click on "Goback" button and click login and come to login page and then proceed login is works
Make sure to clear login session or try in private browser before recreate the issue.
![login](https://user-images.githubusercontent.com/15671620/35029973-67250290-fb83-11e7-9822-00fa60b32014.jpeg)

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in APIM-2.1.0-update-8 even with a private browser.
