### ISSUE TITLE
Listing all APIs in store page by selecting 'All' dropdown is not working

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2446]
**Description:**
Listing 'All' APIs in store page not working. See attachements for three option selected and how list behaves.

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Sevirity/major

**Affected Product Version:**
apim-2.1.0-update6

**OS, DB, other environment details and versions:**    
apim-2.1.0-update4 analytics configured

**Steps to reproduce:**
- Add more than one APIs
- Goto store page -> API
- List all apis by selecting dropdown value => not listing all apis
- Select "All"
![all](https://user-images.githubusercontent.com/15671620/35030398-d1f072f2-fb84-11e7-9439-91b50f05b166.jpeg)

- Select "Production"
![prod](https://user-images.githubusercontent.com/15671620/35030454-fd74a236-fb84-11e7-9d3e-ab250c506140.jpeg)

- Select "Prototyped"
![proto](https://user-images.githubusercontent.com/15671620/35030458-025d5f54-fb85-11e7-95e5-b37176d60ad9.jpeg)

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in APIM 2.1.0-update8
Tested for both tenant and super tenant store.
