### ISSUE TITLE
API store Walkthrough - No actions happen when there is no any API in the store

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2448]
**Description:**
Nothing happen once click on the 'API store Walkthrough' when there is no any API.
Eeven this is a rare case in a production setup, better to fix this.

**Comment by ChamNDeSilva** [comment]
In this situation, As there is no API, we cannot perform the API Subscription etc. Due to that reason API Workthrough will not appear. 
@chaminda, what would you suggest in fixing this ? Having a dummy API ?

**Comment by tmkasun** [comment]
API walkthroughs / guided tours are not available in 3.x series, Feature implementation for API developer portal walkthroughs are tracked though this https://github.com/wso2/product-apim/issues/7787 issue, Will close this issue and address this when implementing the new feature on next releases.
