### ISSUE TITLE
[puppetmaster]km.dev.wso2.org should be changed in common.yaml file and api-key-manager.yaml

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2452]
**Description:**
In Puppetmaster,km.dev.wso2.org should be changed to is.dev.wso2.org in common.yaml file and api-key-manager.yaml files. 

**Suggested Labels:**
bug
Priority/high
Severity/Critical

**Affected Product Version:**
AM2xx puppet scripts

**OS, DB, other environment details and versions:**    
ubuntu 14.04

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
