### ISSUE TITLE
The "Add Parameter" should provide a validation message when "Parameter name" is empty

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2455]
**Description:**
In publisher under Design phase the "Add Parameter" button should show a validation message if a user clicks on "Add Parameter" without providing a "Parameter Name".

![addparameter](https://user-images.githubusercontent.com/17248809/35037757-7546a728-fb9e-11e7-868a-46799f3b4f57.png)

**Suggested Labels:**
Type/Bug, Priority/Low, 2.2.x Update 6

**Comment by HiranyaKavishani** [comment]
Not applicable for master
