### ISSUE TITLE
Under Sharing the user store mention that we need to run the db scripts to suit the mysql version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2456]
**Suggested Labels:**
APIM 2.2.0
Type/Doc

**Description:**
Refer to link [1]. Under the topic "sharing the user store". Mention that the user need to run the db script according to the mysql version that they are using. 

[1]. https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO

**Comment by ChamNDeSilva** [comment]
Fixed in docs.
https://docs.wso2.com/display/AM210/Configuring+External+IDP+through+Identity+Server+for+SSO
https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO
