### ISSUE TITLE
[APIM-2.1.0]Unable to invoke the APIs of a tenant, when there is an failure to unload the tenant before

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#2464]
**Description:**

If the tenant loading fail due to a failure of service registration, it will keep giving error messaged when unloading the tenant.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
