### ISSUE TITLE
Access Control and Visibility on Store is not included in the screenshot nor did in the description 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2466]
**Description:**
Document: https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-CreatinganAPIfromscratch
Creating an API from scratch - Step 4

Please include Access Control drop down and Visibility on Store dropdowns in the screenshot. Provide a simple explanation about them according to the given example. 

**Suggested Labels:**
AM2xx docs

**Suggested Assignees:**
N/A

**Affected Product Version:**
wso2am-2.1.0-update 6
am2xx docs

**Comment by chamindias** [comment]
Fixed : https://docs.wso2.com/display/AM2xx/Quick+Start+Guide#QuickStartGuide-CreatinganAPIfromscratch
