### ISSUE TITLE
Cannot create scopes for multiple roles

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2470]
**Description:**
It is not allowed to add multiple roles to the scopes as a comma-separated list. 

**Suggested Labels:**
Type/Bug
Severity/Major
Priority/High
Affected/2.1.0-update6

**Suggested Assignees:**
N/A

**Affected Product Version:**
wso2am-2.1.0-update 6

**OS, DB, other environment details and versions:**    
OS: macOS High Sierra
Browser: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Steps to reproduce:**
1. Start APIM server and login to the publisher. 
2. Create an API. 
3. Login to the Management Console and create 2 roles. (Finance & Accounts)
4. Add users to it. 
5. Now edit the API and click on Managed Tab. 
6. Click on Add Scopes. 
7. Provide following details. 
```
Scope Key: add_user
Scope name: add user
Roles: Accounts, Finance
Description: Users in Accounts and Finance roles can add users. 
```

7. Click on 'Add Scope'

**Expected:** The scope should be successfully created. 
**Actual:** An error message pops up as below. 
![scop1](https://user-images.githubusercontent.com/31693103/35081882-9fafe904-fc3c-11e7-8a34-754df0d45a87.png)

**Related Issues:**

**Comment by ChamNDeSilva** [comment]
When adding multiple roles it has mentioned with an example that we need to use comma separated values. 
![image](https://user-images.githubusercontent.com/11647526/35548343-ca2e2242-05a4-11e8-9593-662c3ab1c544.png)

In your example you are adding multiple roles with comma + space.
Please try the same with removing the space in between.
