### ISSUE TITLE
Scope Management with OAuth Scopes points to outdated information 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2471]
**Description:**
Document: https://docs.wso2.com/display/AM2xx/Scope+Management+with+OAuth+Scopes
This points to outdated information for APIM2xx. When invoking a resource, if it is limited to OAuth scopes, now we do not have to get the access token using a curl command. User can select the scope from the drop down and access token is generated. This can be directly used to invoke the particular allowed resource. 
Please provide them in the 2xx apim docs. 

![scope2](https://user-images.githubusercontent.com/31693103/35084118-6f0a1f0c-fc48-11e7-8a19-6ce97dadec47.png)
![scope1](https://user-images.githubusercontent.com/31693103/35084213-e141705c-fc48-11e7-8b72-200f204f7281.png)

**Suggested Labels:**
Type/Docs
Priority/High
Affected/2xx

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim 2.1.0 update 6
apim 2xx docs

**OS, DB, other environment details and versions:**    
OS: macOS High Sierra

**Comment by isurulucky** [comment]
Using the curl command is also a valid way to generate a token. This page [1] just points to the article as it explain a real world scenario. Also, the article correctly shows examples for generating access tokens with scopes. 

[1]. https://wso2.com/library/articles/2017/01/article-an-overview-of-scope-management-with-wso2-api-manager/
