### ISSUE TITLE
Variable name issue in authenticator api

### ISSUE THREAD

**Issue by RenukaFernando** [wso2/product-apim#2482]
**Description:**
- Rename `httpOnlyCookieWithLogInContext` to `logoutContextCookie`.
(login context -> logout context)
- Remove `httpOnly` part since both `logoutContextCookie` and `restAPIContextCookie` are http only cookies.

**Comment by pubudu538** [comment]
Fix in https://github.com/wso2/carbon-apimgt/pull/4964
