### ISSUE TITLE
Configure Option in SAML Inbound Authentication configs in APIM management console doesn't display any configs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2486]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/Highest
Severity/Critical

**Affected Product Version:**
APIM 2.1.0 Update6 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**
1. Run the APIM 2.1.0 update 6 pack
2. Access APIM management console
3. Add a service provider from the service provider option available in the APIM management console
4. Try to configure SAML 2 Web SSO configuration for the SP created in step 3

**Observation**
When click on the configure option a blank page [1] will be displayed and no configurations are displayed
 
If we are adding service providers and IDP for the APIM through IS server what is the purpose of having these options in the APIM management console.

[1]. sp.png

![sp](https://user-images.githubusercontent.com/31848014/35135467-7f6991fa-fd03-11e7-81af-b625dc8a7702.png)

**Comment by bhathiya** [comment]
APIM doesn't support SAML SSO. This happens as corresponding bundles are not available in APIM. 

You need to have Identity Server for this.
