### ISSUE TITLE
Mention the default values need for given for keystore password and keystore name under publisher/store SSO

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2487]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
SSO
Prority/Highest

**Description:**
Refer to link [1]. Under the topic configuring publisher/Store for SSO, Mention what are the values need to be given for the parameters Keystore password and keystore name

[1].https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-RelatedLinks

**Comment by ChamNDeSilva** [comment]
Fixed 
https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO
https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO
