### ISSUE TITLE
Mention how users can change the default value of NameIDPolicyFormat and provide sample values for available options

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2488]
**Description:**
Refer to link [1]. Under the topic configuring the carbon console for sso, mention how users can change the default value of the parameter NameIDPolicyFormat as per users needs and provide sample values for available options.

**Suggested Labels:**
APIM 2.2.0
Type/Docs
Priority/Normal

[1].https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-RelatedLinks

**Comment by ChamNDeSilva** [comment]
Fixed in docs.
https://docs.wso2.com/display/2xx/Configuring+API+Manager+for+SSO
https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO
