### ISSUE TITLE
Mention whether the ServiceProviderID in the APIM side and Issuer value in IS side are similar

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2489]
**Description:**
Refer to doc [1]. Under configuring carbon console for SSO, mention whether the parameter value for "ServiceProviderID" needs to be similar with the SP configuration done in the IS side.
eg :- Issuer value used for SP configs in the IS side and the ServiceProviderID value under carbon console SSO configs in APIM side

**Suggested Labels:**
APIM 2.2.0
Type/Doc

[1].https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-RelatedLinks

**Comment by ChamNDeSilva** [comment]
Already fixed with following note.
"Note that following parameters should be matched with the Service Provider configurations of Identity Server that you are configuring" as there are many other parameters as well that need to be matched.
