### ISSUE TITLE
Add a note to mention the parameter values that should match with IS side configs in publisher/store SSO

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2490]
**Description:**
Refer to doc [1]. Under configuring publisher/store for SSO add a note and mention that the following parameter values should match with the IS side SP configs

Publisher issuer value 
Store issuer value
Publisher spEntityId 
Store spEntityId

**Suggested Labels:**
APIM 2.2.0
Type/Doc
SSO

[1].https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-RelatedLinks

**Comment by ChamNDeSilva** [comment]
Fixed in docs.
https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO
https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO
