### ISSUE TITLE
Update the hyperlink configuring SAML2 web single sign on to point latest IS doc

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2491]
**Suggested Labels:**
APIM 2.2.0
Type/Doc
Linking

**Description:**
In link [1] update the hyperlink for configuring SAML2 web single sign on to point to the latest IS doc

[1].https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-RelatedLinks

**Comment by taniamahanama** [comment]
Fixed.
