### ISSUE TITLE
API Search option under Community Features does not work as expected when search using API sub context 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2496]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/Highest

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1. Run the APIM 2.1.0 update 7 pack
2. Access API publisher
3. Create a REST API giving a API definition with a sub context [1] eg:- CheckPhoneNumber 
4. Publish the API
5. Access API Store
6. Search the API with subcontext:/CheckPhoneNumber  as in [2]

**Observation**
The relevant API will not be prompted when searched using subcontext [3]

[1]. apidef.png
[2]. https://docs.wso2.com/display/AM2xx/Use+the+Community+Features
[3]. search1.png

![apidef](https://user-images.githubusercontent.com/31848014/35139063-6a9dd34e-fd17-11e7-9554-b5ba40cff6db.png)

![search1](https://user-images.githubusercontent.com/31848014/35139297-7adc3236-fd18-11e7-922b-53a47f2aeeb1.png)

**Comment by chamindias** [comment]
Fixed in : https://github.com/wso2/carbon-apimgt/pull/5434
