### ISSUE TITLE
Cannot add images on Forum topics/replies

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2497]
**Description:**
User cannot add/attach images on the text editor when he adds replies or new topic in Forum section. Once added via file browser no error can be seen but the uploaded image cannot be seen in the editor

**Comment by tmkasun** [comment]
Forum feature is not available 3.x yet, Hence this is not applicable. We have considered replacing the forum feature with a nested threaded commenting feature. Therefore closing this issue.
https://github.com/wso2/product-apim/issues/7669
