### ISSUE TITLE
No Warning message is given before the cancel operation in creating a new Forum topic

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2499]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/High
Severity/Major

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1. Run the APIM 2.1.0 update 7 pack
2. Create and publish a REST API from API Publisher
3. Add a subscriber  from API Store sign up page and Access API Store using that subscribers credentials
4. Select the particular API and go to overview section
5. Click on the Forum tab [1]
6. Click on Create New Topic
7. Include a subject and a description
8. Click on Cancel

**Observation
No warning message is given before the cancel operation when a user click on cancel.

**Comment by ChamNDeSilva** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5014/files
