### ISSUE TITLE
Duplicate parameters can be added to an API resource

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#2500]
**Description:**
In API definition UI, duplicate parameters can be added and there is no validation on it. But the generated api definition is invalid so that it gives validation error on swagger editor.

**Steps to reproduce:**
Add two query params to an API with the same name. Then go to API editor and check for validation errors.

**Comment by kavishkafernando** [comment]
In the latest release you cannot add duplicate parameters to resources. Hence closing the issue.

<img width="1330" alt="Screen Shot 2020-11-26 at 12 05 00 PM" src="https://user-images.githubusercontent.com/19324135/100316059-c5f03b80-2fdf-11eb-80a8-871cd8282c4d.png">
