### ISSUE TITLE
One user can use other user's generated access token and invoke the resource. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2502]
**Description:**
Assume we have two users, userA and userB, assigned to 'Accounts' role. 'Accounts' role is configured with scope:search_user. UserA's access token can be used by UserB and invoke the resource. 

**Suggested Labels:**
Type/Bug
Severity/Major
Priority/High
Affected/apim-2.1.0 update 6

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0 update 6

**OS, DB, other environment details and versions:**    
OS: macOS high sierra

**Steps to reproduce:**
1. Login to carbon console and create a role called Accounts and assign userA and userB to it. 
2. Login to Publisher, create an API.
3. Edit the API, add a scope and assign the above-created role Accounts and assign it to a resource.
4. Publish the API. 
5. Now login to Store as userA and create an application. App-A
6. Subscribe the API from App-A and generate the access token as below in order to invoke the resource. 
`curl -k -d "grant_type=password&username=userA&password=Test123&scope=search_user" -H "Authorization: Basic R1ROZ1dOZldQbGZJZGhmU1phaXlOeEF3MWVzYTpKVVNQeXBRaDk1cXo3V1I3bW1oczVpME0xcE1h"  -H "Content-Type: application/x-www-form-urlencoded" https://localhost:8243/token`
7. Try to invoke the resource and it will be invoked successfully. 
8. Now login as userB and perform 5-6 steps. 
9. Now invoke the resource by using the access token of userA. 

**Expected:** userB should not be able to invoke the resource using userA's access token. 
**Actual:** Resource is invoked successfully.

**Comment by CrowleyRajapakse** [comment]
This working as expected
