### ISSUE TITLE
Email sending under Community Features doesn't capture spelling mistakes in the email Subject 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2505]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/Normal

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1. Run the APIM 2.1.0 update 7 pack
2. Create and publish a REST API from API Publisher
3. Add a subscriber from API Store sign up page and Access API Store using that subscribers credentials
4. Select the particular API and go to overview section
5. Click on Email option to send API details via email option
6. In the subject and body section type some words with wrong spelling [1]
7. Click on Spelling option

**Observation**
When click on the spelling option wrong spellings which are in the email body section will be captured but spelling mistakes in the email subject section are not captured.  

[1]. email-sending.png

![emai-sending](https://user-images.githubusercontent.com/31848014/35143532-e0a66ffa-fd27-11e7-94d3-3e93ce792f27.png)

**Comment by ChamNDeSilva** [comment]
> When click on the spelling option wrong spellings which are in the email body section will be captured but spelling mistakes in the email subject section are not captured.
I can see that the spelling mistakes in the email subject have been captured in above image.

**Comment by ChamNDeSilva** [comment]
And it capture the spelling mistakes even in the description page.
![image](https://user-images.githubusercontent.com/11647526/35560133-8a81e11e-05d2-11e8-89fa-c4e564913161.png)
