### ISSUE TITLE
Provide a description or a link on what is a .car app

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2508]
**Description:**
It will be good to provide a link to read more on what is a .car files, in [1\] under "Install additional cApp" which will be beneficial for new users to the platform.

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs)

**Suggested Labels:**
Improvement, 2.x.x Docs, Priority/High

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs
https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs
