### ISSUE TITLE
If a User accidentally click on Create new Topic option having a word typed on the search field User will be logged out of the API Store 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2509]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/High
Severity/Major

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1. Run the APIM 2.1.0 update 7 pack
2. Create and publish a REST API from API Publisher
3. Add a subscriber from API Store sign up page and Access API Store using that subscribers credentials
4. Select the particular API and go to overview section
5. Select Forum tab
6. Type a search word in the search field [1]

**Observation**
After typing a word in the search field if a user accidentally click on create new topic option (as both of these buttons are designed so close to each other) without clicking on search option user will be logged out of the system and will be directed to the login page.
 
[1].store-bug.png

![store-bug](https://user-images.githubusercontent.com/31848014/35144829-c2d4ec96-fd2b-11e7-9c8a-4e30b536ced2.png)

**Comment by ChamNDeSilva** [comment]
Cannot reproduce in APIM 2.1.0-update8 pack.
