### ISSUE TITLE
"Configuring the billing engine" step 5 is incomplete

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2512]
**Description:**
In [1\] under "Configuring the billing engine" step 5 is incomplete. It does not tell how to get into the shown web pages and why we need to configure it at this point.

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs)

**Suggested Labels:**
Type/Bug, 2.x.x, Docs , Priority/High, Severity/Critical

**Comment by ChamNDeSilva** [comment]
Already fixed.
