### ISSUE TITLE
Mention what is refereed as Remote Instance URL in Sharing registry space

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2515]
**Labels**
APIM 2.2.0
Type/Docs

**Description**
Refer to link [1]. Under sharing the registry space step 3, mention what is refereed as remote instance url. 

[1]. https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO

**Comment by ChamNDeSilva** [comment]
Fixed.
