### ISSUE TITLE
Rest API: Provide the API invocation url with path param

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2519]
In [1] there is only a sample to what the delete invocation should be. Ideally first the format of the request is given., Then the explanation of the parameters and afterwards the sample should be given. Please order the document so that the request uri is given with path param at first

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisApiIdDelete

**Comment by shaniR** [comment]
Fixed for 2.2.0 with https://github.com/wso2/carbon-apimgt/pull/5000. 2.1 is fixed in support branch,
