### ISSUE TITLE
Need to reword the a phrase found in "Enabling and disabling billing related developer subscriptions"

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2520]
**Description:**
In [1\] under the "Enabling and disabling billing related developer subscriptions" topic the last sentence needs to be reworded a bit to be meaningful. It currently starts with a lower-case letter and fix it as below example.

**Current**
publisher can disable subscription of particular API/APIs by clicking Block. if so store user could not invoke API until it re-enable.

**Example**
Publisher can disable the subscription of a paritcular API/APIs by clicking Block. If so a store user will not be able to invoke the API until it is re-enabled.

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs) 

**Suggested Labels:**
Bug, Docs, Priority/High

**Comment by taniamahanama** [comment]
Fixed.
