### ISSUE TITLE
Explain the difference between Token API/ RESTful API/Private/Partner APIs

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2522]
**Description:**
Document: https://docs.wso2.com/display/AM2xx/Product+APIs
Explain the difference between Token API/ RESTful API/Private/Partner APIs

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0-update 6

**Comment by chamindias** [comment]
Improved the doc : https://docs.wso2.com/display/AM2xx/Product+APIs
