### ISSUE TITLE
Explain why we need to configure an Identity Provider in when configuring Kerberos Grant with API Manager

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2524]
**Description:**
Document: [Kerberos OAuth2 Grant](https://docs.wso2.com/display/AM2xx/Kerberos+OAuth2+Grant#69c8ee30ff1b4f30a15b43efd39f25c3)
Section: Configuring Kerberos Grant with API Manager
Step 7
Explain why we need to configure an Identity Provider in when configuring Kerberos Grant with API Manager

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
AM2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed
