### ISSUE TITLE
Explain Service Principle name in configurations in Kerberos Grant with API Manager

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2525]
**Description:**
Document: [Kerberos OAuth2 Grant](https://docs.wso2.com/display/AM2xx/Kerberos+OAuth2+Grant#69c8ee30ff1b4f30a15b43efd39f25c3)
Section: Configuring Kerberos Grant with API Manager
Step 7
Explain what is Service Principal Name 

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
AX2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed.
https://docs.wso2.com/display/AM210/Kerberos+OAuth2+Grant
https://docs.wso2.com/display/AM2xx/Kerberos+OAuth2+Grant
