### ISSUE TITLE
Configuring API Manager for SSO link redirects to an old version 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2527]
**Description:**
Document: [SAML Extension Grant](https://docs.wso2.com/display/AM2xx/SAML+Extension+Grant)
Section: Configuring the token exchange

Configuring API Manager for SSO link redirects to an old version of the APIM doc. 

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
AM2xx docs

**Comment by chamindias** [comment]
Fixed in the [SAML Extension Grant](https://docs.wso2.com/display/AM2xx/SAML+Extension+Grant) page.
