### ISSUE TITLE
Explain or provide a reference for exporting the public certificate of WSO2 IS and importing it. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2528]
**Description:**
Document: [SAML Extension Grant](https://docs.wso2.com/display/AM2xx/SAML+Extension+Grant)
Section: Configuring the token exchange
Step 3

Please provide steps or reference for exporting the public certificate of WSO2 IS and importing it to IDP.  

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed
