### ISSUE TITLE
Typo error in sample document

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2531]
In [1] there exists the following sentence
```
For example, let’s take ABC organization which is a bank which providing financial facilities 
```
In above the usage of **which providing** is grammatically wrong. Please correct the grammar error

[1] https://docs.wso2.com/pages/viewpage.action?spaceKey=AM2xx&title=Developer+Optimized+APIs+Development+-+Sample+Documentation

**Comment by ChamNDeSilva** [comment]
Fixed
