### ISSUE TITLE
Redirect user to Scope Management with OAuth Scopes document. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2535]
**Description:**
Document: [Enabling Role-Based Access Control Using XACML](https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML)
In the document, it is said that there are two ways to restrict users, which are OAuth 2.0 and 
XACML. It is better if we can provide the API Manager doc (https://docs.wso2.com/display/AM2xx/Scope+Management+with+OAuth+Scopes) as the reference to the document how users are restricted using OAuth2.0 rather than providing the OAuth 2.0 Authorization Framework doc. 

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by Mariangela** [comment]
Updated the following pages based on the feedback.

[1] https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML
[2] https://docs.wso2.com/display/AM210/Enabling+Role-Based+Access+Control+Using+XACML
[3] https://docs.wso2.com/display/AM220/Enabling+Role-Based+Access+Control+Using+XACML
