### ISSUE TITLE
Rest API- Please provide a sample in how to add a custom sequence

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2537]
In [1] there is a parameter to add the sequences but no clear way of using that is given. A custom sequence is not just a parameter as a synapse configuration needs to be sent via the rest call. Please add sample value that describes an actual case so that the user referring to the document can make use of that and work on his/her need

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisApiIdPut

**Comment by shaniR** [comment]
Ideally by giving a  value as {
   "name": "add_custom_header_fault",
   "type": "fault",
   "config": "<sequence xmlns=\"http://ws.apache.org/ns/synapse\" name=\"add_custom_header_fault\">\n    <property name=\"CustomHeader\" scope=\"transport\" value=\"example\"/>\n<\/sequence>\n"
} 

for sequences it should work as it is done for adding a sequence to an already created API. This does not work, as the DTO conversion happens using SequenceDTO, which is different to MediationDTO used in the latter method. This seems to be a bug. Need to correct this and update the docs accordingly.

**Comment by bhathiya** [comment]
This is not a bug. 

The correct value is this.

    "sequences": [{"name":"json_validator","type": "in"},{"name":"log_out_message","type": "out"}]

Updated samples by https://github.com/wso2/carbon-apimgt/pull/5163
