### ISSUE TITLE
Specify external LDAP or AD should be read-only or readwrite according to the example

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2538]
**Description:**
Document: [Enabling Role-Based Access Control Using XACML](https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML)
Section: Enabling role-based access control
Step 1

The user is redirected to 'Configuring an external LDAP or Active Directory user store' doc [1].
In that, there are configurations provided for read-only mode and read/write mode. In this example, it has not been specified what mode should be needed. Therefore please specify if it should be read-only mode or read/write mode. 

[1] - https://docs.wso2.com/display/AM2xx/Configuring+Primary+User+Stores#ConfiguringPrimaryUserStores-ConfiguringanexternalLDAPorActiveDirectoryuserstore

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed.
