### ISSUE TITLE
Sample-scenarios: document gives running instructions to a location inside the pack

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2539]
In [1] it states the following
```
Running the sample to populate the sample data
Start the wso2am-2.2.0-updateX distribution.

Go to <API-M_HOME>/sample-scenarios. Execute the run.sh file. Enter the scenario number as 1, when prompted.
```
But from wso2am-2.1.0-update6 pack the sample-scenarios location is not there inside the pack. Please direct to the correct location where the sample can be accessed from.

[1] https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation

**Comment by chamindias** [comment]
Fixed in : https://docs.wso2.com/display/AM2xx/Managing+Public%2C+Partner+vs+Private+APIs+Sample+Documentation
