### ISSUE TITLE
"Deploying the extended workflow" step 1 needs to provide the link to checkout the code

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2541]
**Description:**
In [1\] under Deploying the extended workflow" the step 1 states to checkout and build the code. But we have not provided the git url to check out the code.

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Deployingtheextendedworkflow](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Deployingtheextendedworkflow)

**Suggested Labels:**
Type/Bug, Doc ,2.x,x update 7, Priority/Highest, Severity/Critical

**Comment by chamindias** [comment]
Reducing the priority since this a small change in docs.

**Comment by Mariangela** [comment]
Added the source for subs-billing-workflow in the following pages, based on the API-M version

- https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Deployingtheextendedworkflow
- https://docs.wso2.com/display/AM220/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Deployingtheextendedworkflow
- https://docs.wso2.com/display/AM210/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Deployingtheextendedworkflow
