### ISSUE TITLE
"Test the system" Step 6 and 7 needs to be corrected

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2544]
**Description:**
In [1\] under "Test the system" the step 6 and 7 is not the behaviour the current application performs.

If a new user registers and logins to the apim store he can subscribe to a monetized tier using an application( defaultapplication) this user will then be navigated to login page of the billing engine where he needs to get registered. Upon successful registration he will be navigated back to the apim store successfully. ( he does not need to login again to the billign engine app)

![image](https://user-images.githubusercontent.com/17248809/35216933-634f7a78-ff8f-11e7-9bf9-4a97e171a93d.png)

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs)

**Suggested Labels:**
Type/Bug, Doc ,2.x,x update 7, Priority/High, Severity/Critical

**Comment by ChamNDeSilva** [comment]
Fixed
https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs
