### ISSUE TITLE
Specify if it needs to disable the default JDBC configuration in user-mgt.xml

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2547]
**Description:**
Document: [Enabling Role-Based Access Control Using XACML](https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML)
Section: Enabling role-based access control
Step 1
By default JDBC configuration is enabled in APIM user-mgt.xml. Specify if we need to disable this when sharing IS LDAP user store as two user stores in active state won't work and a user would not know specifically if the information is not provided.

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed in docs.
https://docs.wso2.com/display/AM2xx/Enabling+Role-Based+Access+Control+Using+XACML
https://docs.wso2.com/display/AM210/Enabling+Role-Based+Access+Control+Using+XACML
https://docs.wso2.com/display/AM200/Enabling+Role-Based+Access+Control+Using+XACML
