### ISSUE TITLE
UI break in API overview forum section

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2548]
**Description:**
Elements needs to be placed properly in overview forum section

**Suggested Labels:**
APIM 3.0, UX

**Comment by tgtshanika** [comment]
This is fixed for APIM 3.0.0 
<img width="1221" alt="Screen Shot 2019-09-12 at 12 05 38 PM" src="https://user-images.githubusercontent.com/4471756/64759749-b230f480-d555-11e9-9501-6435e7923434.png">

**Comment by chanaka3d** [comment]
Since the Forum feature is deprecated and replaced with multi level comments with 3.x products, we can close this issue.
