### ISSUE TITLE
Store - Maintain consistency of back button throughout the app

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2549]
**Description:**
Only Create Applications page contains the back action, add this to other relevant pages as well.

**Suggested Labels:**
APIM 3, UX

**Comment by tgtshanika** [comment]
This is fixed for APIM 3.0.0
<img width="1221" alt="Screen Shot 2019-09-12 at 12 05 38 PM" src="https://user-images.githubusercontent.com/4471756/64759803-cd9bff80-d555-11e9-8c22-e6345f7e9a81.png">
