### ISSUE TITLE
UX improvement in Application production keys section

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2550]
**Description:**
When the keys are not generated the UI should only contain a message as "Click on the following button to generate consumer key and secret" and a "Generate Keys" button.

When user clicks on the "generate keys" button the consumer key and secret keys should be shown and a message as "Click on the following button to generate access token" and a "Generate Token" button should be appeared. 

**Suggested Labels:**
APIM 3.0, UX

**Comment by chanaka3d** [comment]
Fixed with 3.x products.
