### ISSUE TITLE
Store - Remove bottom navigation from API listing and add button toggle to switch from grid and list

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2551]
**Description:**
Store - Remove bottom navigation from API listing and add button toggle to switch from grid and list

**Suggested Labels:**
APIM 3.0 , UX

**Comment by erangatl** [comment]
Fixed in latest

![image](https://user-images.githubusercontent.com/20179540/64242860-edaf3b80-cf23-11e9-8f17-53f808da101b.png)
