### ISSUE TITLE
API overview should show average rating of the API

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2552]
**Description:**
API overview should show average rating of the API

**Suggested Labels:**
APIM 3.0, UX
![average-rating](https://user-images.githubusercontent.com/9837443/35220640-2f2d46a4-ff9d-11e7-9b1f-8fb001c484f1.png)

**Comment by tharikaGitHub** [comment]
Fixed

![1](https://user-images.githubusercontent.com/8557410/64759023-b4924f00-d553-11e9-81e5-105ea6405933.png)
