### ISSUE TITLE
User can add an application without giving application name

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2553]
**Description:**
User can add an application without giving application name

**Suggested Labels:**
APIM 3.0, UX

**Comment by tgtshanika** [comment]
This is fixed in master branch.
Fixed version : APIM 3.0.0

<img width="819" alt="Screen Shot 2019-09-12 at 11 45 37 AM" src="https://user-images.githubusercontent.com/4471756/64758716-ec4cc700-d552-11e9-99f8-eee354e89acb.png">
