### ISSUE TITLE
Correct ReadWriteLDAPUserStoreManager section in user-mgt.xml

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2558]
**Description:**
In user-mgt.xml file in <APIM-HOME>/Repository/Conf folder, 'ReadWriteLDAPUserStoreManager' has been started as ISUserStoreManager. In the doc, the user has been directly asked to uncomment it. Therefore, please correct it as UserStoreManager. 

**Suggested Labels:**
Type/Bug
Severity/Major
Priority/High
Affected/apim-2.1.0update 6

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0update 6

**Comment by ChamNDeSilva** [comment]
@isuruuy429, can you please provide the doc link related to this as well. So that we can fix both doc and product.

**Comment by ChamNDeSilva** [comment]
related issue :  https://wso2.org/jira/browse/CARBON-15917
