### ISSUE TITLE
Specify if an offset is given, connection url port needs to be changed accordingly. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2559]
**Description:**
Document: [Configuring an external LDAP or Active Directory user store](https://docs.wso2.com/display/AM2xx/Configuring+Primary+User+Stores#ConfiguringPrimaryUserStores-ConfiguringanexternalLDAPorActiveDirectoryuserstore)
Section: Configuring an external LDAP or Active Directory user store

Specify if an offset is given, the connection url port of the ReadWriteLDAPUserStoreManager needs to be changed accordingly. 

Eg: if offset is 1
 <Property name="ConnectionURL">ldap://localhost:10390&lt</Property>

**Suggested Labels:**
Type/Docs
Severity/Minor
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by bhathiya** [comment]
Port offset of the APIM server is not related to the LDAP connection URL.
