### ISSUE TITLE
Store - Search bar should be in line with the "All APIs" title in API listing 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2560]
**Description:**
Currently the search is in header and should be aligned with All APIs title.

**Suggested Labels:**
APIM 3.0, UX

**Comment by bhathiya** [comment]
I assume this is invalid for 3.0. Please confirm. @Minoli @tmkasun

**Comment by kavishkafernando** [comment]
Closing this issue since this is resolved in 3.x.x products
<img width="1557" alt="Screen Shot 2020-06-15 at 12 27 33 PM" src="https://user-images.githubusercontent.com/19324135/84626942-a8348b80-af03-11ea-9905-642d59a784cd.png">
