### ISSUE TITLE
API Console does not set Authorization header with Petstore

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#2571]
**Description:**

When using **custom security definitions** in swagger for an API, during the API invocation through the Store console, Authorization header is not set in the curl command. 

**Suggested Labels:**

**Suggested Assignees:**

@tgtshanika 

**Affected Product Version:**

APIM 2.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Download petstore swagger definition example from here: http://petstore.swagger.io/v2/swagger.json.
2. Use it to create an API in publisher.
3. Go to store and subscribe to it with DefaultApplication.
4. Go to DefaultApplication's production tab and generate keys.
5. Go back to petstore API and select API Console.
6. Select any API resource to test and click on "Try it out" button.

Notice that resulting curl command does not have Authorization header with OAuth2 AccessToken set. 

**Related Issues:**

**Comment by tgtshanika** [comment]
This has been fixed in APIM 2.6.0
