### ISSUE TITLE
Discribe the usage of Throttling related configurations

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#2572]
**Description:**
It would be better to describe what each following configuration element does related to throttling in api-manager.xml. No any description (what they do), is mentioned in the clustering docs [1] (or any other docs pages) even though it is instructed to configure them.
```
- <EnableAdvanceThrottling>
- <DataPublisher>
- <ReceiverUrlGroup>
- <AuthUrlGroup>
- <PolicyDeployer>
- <BlockCondition>
- <JMSConnectionDetails>
- <JMSConnectionParameters>
- <JMSEventPublisherParameters>
```

[1] https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager

**Comment by chamindias** [comment]
Improved [2.1.0 documentation](https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager) and [2.x.x documentation](https://docs.wso2.com/display/AM2xx/Distributed+Deployment+of+API+Manager).

**Comment by lahirus** [comment]
<JMSEventPublisherParameters> config is not explain in 2.1.0 doc. See [1].

[1] https://docs.wso2.com/display/AM210/Deploying+WSO2+API-M+in+a+Distributed+Setup#DeployingWSO2API-MinaDistributedSetup-Step1-InstallandconfigureWSO2API-M

Thanks.
