### ISSUE TITLE
API AVAILABILITY section in the Admin portal, shows/lists APIs incorrectly 

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2574]
**Steps to reproduce:**
1. Add API, publish and subscribe to it from the Store and then invoke the API
2. Remove the API
![image](https://user-images.githubusercontent.com/7115693/35262457-d7c35b08-003a-11e8-8073-6c7ecefcdbf2.png)
3. After some time(10/15 mins) access the admin portal and go to ANALYTICS>>API AVAILABILITY section and see.

**Actual Result**
The API is shown as available,
![image](https://user-images.githubusercontent.com/7115693/35262579-3e4bbec4-003b-11e8-9122-205de7f46e14.png)

**Expected Result**
API should be listed as not available.

**Comment by fazlan-nazeem** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/5057
