### ISSUE TITLE
Jaggery Rest API returns 200 response code for unauthenticated requests

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#2576]
**Description:**
Try to invoke the the store jaggery api to add an subscription. It will return the code 200, even though it does not add the subscription. We need to fix this as an improvement. 

**Affected Product Version:**
2.1.0

**Steps to reproduce:**

- Add a API with name "Sample"and version 1.0.0 using API publisher and publish it.
- Then use the following curl command to add the subscription. It will give the 200 response code.

`curl -X POST -b cookies http://localhost:9763/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag -d 'action=addAPISubscription&name=Sample&version=1.0.0&provider=admin&tier=Unlimited&applicationName=DefaultApplication' -i -v`

**Comment by tgtshanika** [comment]
Jaggery APIs have been deprecated in past few releases of APIM upto 2.6.0. These APIs have been removed from APIM master branch.
