### ISSUE TITLE
No any API exist for Analytic feature in Publisher or Store

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2577]
**Description:**
Currently there is no any API available for the user to access analytic information in publisher, store and Admin portal
This is an useful feature when the user want to implement their own analytics UIs/Apps for the APIs/Applications which has been published on wso2 api manager.

Currently we have only the below listed[1] of REST APIs available
https://docs.wso2.com/display/AM2xx/RESTful+APIs

**OS, DB, other environment details and versions:**    
JDK1.8, macOS

**Comment by chamilaadhi** [comment]
Stats on AM 2.6 will be implemented using Stream processor 4.3 rest apis. Users can query these rest apis if they need to implement their own ui
https://docs.wso2.com/display/SP430/Store+APIs
