### ISSUE TITLE
Need to format the url which is found in "Setting Maximum Backend Throughput Limits" 

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2579]
**Description:**
In [1\] "Setting Maximum Backend Throughput Limits" there is a link which is ->"_<API_HOME>/repository/tenants/<TenantID>/synapse-configs/default/_" goes beyond the documentation page. Please format it accordingly.

[1\] [https://docs.wso2.com/display/AM2xx/Setting+Maximum+Backend+Throughput+Limits](https://docs.wso2.com/display/AM2xx/Setting+Maximum+Backend+Throughput+Limits)

**Suggested Labels:**
Type/Bug, Doc ,2.x,x update 7, Priority/Medium, Severity/Major

**Comment by taniamahanama** [comment]
Fixed in 2.0.0, 2.1.0 and 2.x.x spaces.
