### ISSUE TITLE
Need to validate if production / sandbox tps fields are empty if throttling policy is set as "Specify"

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2580]
**Description:**
If "Maximum Backend Throughput" is selected as "Specify" and if no values are given still the system saves it. Ideally it should show a validation message prompting to enter the sandbox / production tps rates. Follow the steps below to reproduce the issue

**Steps**

1. Create and API and navigate to "Manage" section
2. Select the throttling policy as "specify" and do not provide values for production and sandbox tps fields
3. Click on save or save and publish
4. The api will be saved or published successfully

**Expected**
The system should validate it and prompt the user to fill the fields. 

![current](https://user-images.githubusercontent.com/17248809/35268780-205bdc90-0050-11e8-80d2-df43a4eb7dae.png)

**Suggested Labels:**
Type/Bug, 2.x,x update 5, Priority/High, Severity/Critical

**OS, DB, other environment details and versions:**
APIM and analytics quick setup
Ubuntu 14
JDK - jdk 1.8.0_51
DB - mysql
Browser - Chrome Version 62.0.3202.62

**Comment by dushaniw** [comment]
When a user selects the throttling policy as "specify" and do not provide values for production and sandbox tps fields and save the api, the  "maximum backend throughput" value of the saved api will be "unlimited". This is the expected behavior according to the design.
