### ISSUE TITLE
If throtling policy values are entered under "specify" policy and then if "unlimited" throttling policy is selected and saved, Maximum Backend Throughput setting changes to "specify"

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2582]
**Description:**

The "unlimited" throttling policy gets changed to "specify" policy if values are given to the specified policy found under "Maximum Backend Throughput ". refer below steps.

**Steps**

1. In API publisher wizard navigate to "manage" section
2. Under throttling settings navigagate to "Maximum Backend Throughput"
3. Select the "specify" radio button and provide some values for production and sandbox
4. Click Save
5. Navigate back to view all apis in publisher portal and click on edit for the above saved api
6. In manage section notice that the "Maximum Backend Throughput " has changed from "unlimited" to "specify"

**Suggested Labels:**
Type/Bug, 2.x,x update 5, Priority/High, Severity/Critical

**OS, DB, other environment details and versions:**
APIM and analytics quick setup
Ubuntu 14
JDK - jdk 1.8.0_51
DB - mysql
Browser - Chrome Version 62.0.3202.62

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5049
