### ISSUE TITLE
[Admin Portal] Data does not visualize correctly when user switch selections on Date Range Picker

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2583]
##**Description:**
Data does not visualize/refresh correctly when user switch options on Date Range Picker in the ACCESS TOKEN ERRORS section under LOG ANALYZER in Admin Portal.

**OS, DB, other environment details and versions:**
JDK.1.8, macOS

**Steps to reproduce:**
1. Access the Admin Portal >> LOG ANALYZER >> ACCESS TOKEN ERRORS section when there is applicable data for last 30 days. See the screen below.
![image](https://user-images.githubusercontent.com/7115693/35273775-c41fa3ac-005f-11e8-8c4f-b824d4f23e8e.png)

2. Then switch the Data Range Picker selection to Yesterday or any custom range where applicable data is not available. See the screen below.
![image](https://user-images.githubusercontent.com/7115693/35274129-f78d59ae-0060-11e8-9d1b-2e80a8824bdc.png)

3. Then switch back to previous selection(last 30 days) where data were exist.

**Actual Result**
User is still getting the same view as in step3 and cannot see the data as in step1.

**Expected Result**
The page/gadgets should dynamically sync and visualized data when user switch different options.

**Comment by tgtshanika** [comment]
This feature has been deprecated from APIM 2.2.0 and this is not available in APIM 3.0.0 m35
