### ISSUE TITLE
Update the Register new service provider screenshot to suit current product version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2587]
**Suggested Labels**
APIM 2.2.0
Type/Doc
Priority/High

**Description**
The screenshot given under Register new service provider in [1] needs to be updated to suit the current product update. According to the current product, Certificate Alias will get enable if a user checks Enable signature validation check box. As this is not captured in the given screenshot please update it as in [2] 

[1]. https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO
[2]. sp-apim.png

![sp-apim](https://user-images.githubusercontent.com/31848014/35314755-3953eb22-00ee-11e8-8bcd-714a1248843e.png)

**Comment by ChamNDeSilva** [comment]
Fixed 
https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO
