### ISSUE TITLE
Move source map files out of the distribution

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2588]
**Description:**
- Considering the size of the generated source-map files for Store, Publisher & Admin SPA apps, It would be better to move them out of the product distribution and host them in a CDN/SVN location

**Affected Product Version:**

- API Manager 3.0.0-m13

**Steps to reproduce:**
-  Unzip an API Manager V3 product distribution (i:e wso2apim-3.0.0-SNAPSHOT.zip)
- Examine it using a disk usage analyzing tool
![apim3](https://user-images.githubusercontent.com/3313885/35314907-3cdab6f8-00ef-11e8-93fb-9526ce969725.png)

**Comment by tmkasun** [comment]
As per webpack [documentation](https://webpack.js.org/configuration/devtool/#production), use `nosources-source-map` if no need to expose source to external users

**Comment by tgtshanika** [comment]
This is fixed
