### ISSUE TITLE
Setting up primary and secondary logins - Cannot login with the email address

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2589]
**Description:**
Document: [Maintaining Logins and Passwords](https://docs.wso2.com/display/AM2xx/Maintaining+Logins+and+Passwords)
Section: Setting up primary and secondary logins

```
<LoginConfig>
    <UserIdLogin primary="true">
         <ClaimUri></ClaimUri>
    </UserIdLogin>
    <EmailLogin primary="false">
         <ClaimUri>http://wso2.org/claims/emailaddress</ClaimUri>
    </EmailLogin>
 </LoginConfig>
```
As per the doc, when the above configuration is enabled in api-manager.xml file, user should be able to login with the email address as well as the username.  But once user tries to login, it is not allowed and getting the below error message. 

`ERROR - APIStoreHostObject Invalid tenant domain.`

**Suggested Labels:**
Type/Bug
Severity/Critical
Priority/Highest

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0 update 6

**OS, DB, other environment details and versions:**    
OS: macOS High Sierra
Browser: Google Chrome - Version 63.0.3239.132 (Official Build) (64-bit)
apim-2.1.0 update 6
am2xx docs
java version "1.8.0_144"
Config changes in APIM pack except above: <APIM-HOME>/repository/conf/tomcat/catalina-server.xml, compression property is set to 'off' due to the issue of [1](mail thread)

[1] - [APIM]Cannot login to APIM Management console with admin credentials

**Steps to reproduce:**
1. Enable login config property in <APIM_HOME>/repository/conf/api-manager.xml file as above. 
2. Start the APIM server and navigate to API Store. 
3. Self-signup with following details.

> username: Ann123
> password: Test123
> First name: Ann
> Lastname: Ann Jay
> email: ann123@gmail.com

4. Try to login with email and password. 

Expected: user should be able to login. 
Actual: An error message pops up. 
`ERROR - APIStoreHostObject Invalid tenant domain.`

**Related Issues:**
Mail thread: Setting up primary and secondary logins

**Comment by msm1992** [comment]
This feature is not supported in APIM. Docs have been updated to leave out 'Setting up primary and secondary logins' part. Anyway the error message you saw is because APIM identified gmail.com part in email as a tenant domain.
