### ISSUE TITLE
Correct the typo in the beginning of the doc - Log in to the API Store using Social Media

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2591]
**Description:**
Document: https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media
Please remove this line in the beginning of the doc. 

> adding a new identity provide

**Suggested Labels:**
Type/Docs
Severity/Minor
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed.
