### ISSUE TITLE
Store API overview page missing information

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2595]
**Description:**

- API Overview page endpoint URL(s) are missing

![image](https://user-images.githubusercontent.com/3313885/35317105-1914c842-00fb-11e8-8453-d3442a88eebf.png)

**Steps to reproduce:**

- Create an API from publisher
- Visit API overview page in Store
- Missing Endpoint URLs

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 m35
<img width="1027" alt="Screen Shot 2019-09-11 at 11 16 23 PM" src="https://user-images.githubusercontent.com/4471756/64721503-42d1eb00-d4ea-11e9-9121-8bf9882c712e.png">
