### ISSUE TITLE
Sharing a new API link from digg does not work as expected

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2596]
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/High
Severity/Major

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1. Run the APIM 2.1.0 update 7 pack
2. Create a digg account
3. Create and Publish a REST API from API Publisher as admin
4. Access API Store as admin
5. Select the Particular API from API Store. Go to Overview Section
6. Click on digg icon
7. The Link will be copied to the digg home page
8. Click on submit button

**Observation**
An error message will be displayed as saying invalid url [1] for the automatically copied url.

[1]. digg-error.png
![digg-error](https://user-images.githubusercontent.com/31848014/35317270-fe2b55cc-00fb-11e8-8307-1bf7869b905d.png)

**Comment by ChamNDeSilva** [comment]
Cannot reporoduce in APIM 2.1.0 update-8. Working as expected.
![image](https://user-images.githubusercontent.com/11647526/35552129-9c95ae72-05b8-11e8-96aa-d8567e65cb0b.png)
