### ISSUE TITLE
Specify exactly which elements need to be updated for connection details in UserStoreManager class. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2597]
**Description:**
Document: [Configuring Primary User Stores](https://docs.wso2.com/display/AM2xx/Configuring+Primary+User+Stores#b53a68e76f0a41119e7b11cec84930bb)
Section: Configuring an internal/external JDBC user store
Step 4

Please mention specifically which elements need to be updated for connection details in UserStoreManager class. 

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim 2xx docs

**Comment by ChamNDeSilva** [comment]
This is completely on user preference. Therefore linked to details of the parameters that need to be configured in the same place so that the user can specify if they want to modify them according to their requirement.
