### ISSUE TITLE
Binary-Relay don't expand SOAP message

### ISSUE THREAD

**Issue by ggianoglio** [wso2/product-apim#2599]
**Description:**
The response message of a our web service has content type "application/dime". We changed axis2.xml to use binary-relay (builder and formatter) with that content type.

```
<messageFormatter contentType="application/dime"                          
   class="org.wso2.carbon.relay.ExpandingMessageFormatter"/>

<messageBuilder contentType="application/dime"
   class="org.wso2.carbon.relay.BinaryRelayBuilder"/>
```
The response SOAP message is not expanded, so we have a return envelope like this

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Body>
    <ns:binary xmlns:ns="http://ws.apache.org/commons/ns/payload">DCAAAAApACkAAAJxdXVpZDo3MTRDNk...U9GCgA=</ns:binary>
</soapenv:Body>
</soapenv:Envelope>
```

**Affected Product Version:**
EI 6.1.1, AM 2.1.0

**Comment by kavishkafernando** [comment]
HI @ggianoglio 

Apologies for not attending to this issue. We assume that this issue has been resolved. Please re-open the issue if you are still encountering this issue.
