### ISSUE TITLE
Explain why responseSigningEnabled element should set to true in APIM 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2600]
**Description:**
Document: [Configuring External IDP through Identity Server for SSO](https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO)
Section: Configuring WSO2 Identity Server as a SAML 2.0 SSO Identity Provider
Step 7

In the perspective of a fresh user there is no detail or reference found what exactly below configs do. Threfore please explain why **responseSigningEnabled** element should set to true in below files.

> <APIM_HOME>/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json
> <API-M_HOME>/repository/deployment/server/jaggeryapps/store/site/conf/site.json

**Suggested Labels:**
Severity/Major
Priority/Normal
Type/Docs

**Suggested Assignees:**
N/A

**Affected Product Version:**
am2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed.
