### ISSUE TITLE
Provide a reference or a screenshot of details included in configuring external IDP

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2601]
**Description:**
Document: [Configuring External IDP through Identity Server for SSO](https://docs.wso2.com/display/AM2xx/Configuring+External+IDP+through+Identity+Server+for+SSO)
Section: Configuring WSO2 Identity Server as a SAML 2.0 SSO Identity Provider
step 8 - Add a new Identity Provider in WSO2 Identity Server.

Please provide what should be set for below values in terms of this context. Provide a reference/ screenshot.
- Service Provider Entity ID
- Identity Provider Entity Id

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
am2xx docs

**Comment by ChamNDeSilva** [comment]
Screenshot is already available in provided link in the same place.
