### ISSUE TITLE
Specify which topic should be followed exactly - Configuring Single Sign-on with SAML2

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2602]
**Description:**
Document: [Configure Facebook login with Identity Server](https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureFacebookloginwithIdentityServer)

Step 2 redirects to the page[1]. It has three main scenarios which are Configuring API Manager for SSO, Configuring External IDP through Identity Server for SSO, Configuring Identity Server as IDP for SSO. Clearly specify which section of which document should be followed from these three. 

[1] - [Configuring Single Sign-on with SAML2](https://docs.wso2.com/display/AM2xx/Configuring+Single+Sign-on+with+SAML2)

**Suggested Labels:**
Type/Docs
Priority/Normal
Severity/Major

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by ChamNDeSilva** [comment]
Fixed.
