### ISSUE TITLE
Specify in the BEGINNING of the doc that email as username should be enabled - Log in to the API Store using Social Media

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2610]
**Description:**
Document: [Log in to the API Store using Social Media](https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media#LogintotheAPIStoreusingSocialMedia-ConfigureFacebookloginwithIdentityServer)
In order to login to publisher/Store with Facebook credentials, it has to enable email as username in IS. It has been mentioned in the bottom of the document, after all the service providers/Identity Providers have been configured. When this change is done at last, user is not able to view the Service Providers created before. Further, they are not allowed to create the same service Providers since they are already existing in the system, but not viewable. 
Therefore please mention this step in the beginning of the document in order to avoid the hassle and the rework. 

**Suggested Labels:**
Type/Docs
Severity/Critical
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim2xx docs

**Comment by chamindias** [comment]
Improved the [official documentation](https://docs.wso2.com/display/AM2xx/Log+in+to+the+API+Store+using+Social+Media).
