### ISSUE TITLE
Supporting Pattern swagger parameter with swagger-codegen

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-apim#2613]
**Description:**
With current swagger-codegen version 2.2.0 we cannot include pattern parameter in swagger definition. Doing so breaks the SDK download for Python. We have to evaluate whether this get's fixed with codegen 2.3.0 and update the versions in APIM 2.2.0.

**Suggested Labels:**
Type/Imporvement

**Suggested Assignees:**
Bhathiya

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
Fixed with swagger codegen and parser upgrade. https://github.com/wso2/carbon-apimgt/pull/5104
