### ISSUE TITLE
Preflight OPTIONS calls can give invalid Access-Control-Allow-Methods when there are overriding resources defined

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#2627]
**Description:**

Steps to reproduce:
1. Create an API with below two resources and publish it. 
        GET /business-parties/{bpGuid}/{bpType}
        PUT /business-parties/{patientGuid}/manufacturers
2. Login to store and send the below mentioned request to the API using the swagger console.
        PUT /business-parties/AABBCCDD/manufacturers 
The request will fail and below error appears in the browser's console

XMLHttpRequest cannot load https://10.100.22.33:8243/api1/v1.0/business-parties/AABBCCDD/manufacturers. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4871
