### ISSUE TITLE
Configuring caching; DefaultCacheTimeout setting is not mentioned

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2628]
In [1] there is a reference as follows for cache configuration which points to the carbon.xml. It will be helpful for the user to mention what exact configuration they should look for or maybe provide a link to another page that might consist of the information of a global cache configuration

```
All caches in WSO2 products can be configured using the PRODUCT_HOME>/repository/conf/carbon.xml 
```
[1] https://docs.wso2.com/display/AM2xx/Configuring+Caching

**Comment by ChamNDeSilva** [comment]
Fixed.
