### ISSUE TITLE
A log statement within a log appender resulted in the code going into a recursive method stack

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#2633]
**Description:**
There is a log statement within a log appender which resulted in the code going into a recursive method stack. We need to get rid of this recursion.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update9, 2.1.0 WUM, 2.0.0 WUM

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
This has been fixed with https://github.com/wso2/shared-analytics/commit/25411e1fa5d19d5db2ebc1b110a190d5267280b1

**Comment by ChamNDeSilva** [comment]
Closing the issue as the fix is merged.
