### ISSUE TITLE
Include wso2 registry rest apis in WSO2 APIM

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2635]
**Description:**
Currently the registry apis[1] are not supported by default in APIM. For provide better usage and complete developer experience, please bundle the registry apis with APIM.

**Comment by ChamNDeSilva** [comment]
Related issue https://github.com/wso2/product-apim/issues/2351

**Comment by bhathiya** [comment]
Reducing priority as we can do the same with ResourceAdminService[1] SOAP service. It comes with APIM itself.

[1] https://github.com/wso2/carbon-registry/blob/master/components/registry/org.wso2.carbon.registry.resource.ui/src/main/resources/ResourceAdminService/ResourceAdminService.wsdl

**Comment by bhathiya** [comment]
Fixed and updated https://docs.wso2.com/display/AM210/Using+the+Registry+REST+API
