### ISSUE TITLE
APIs published without assigning a subscription tier created for monetization is also shown the paid label in store

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2636]
**Description:**
Configured monetization as per [1\]. When a API was published a API with a subscription tier e.g Bronze, Gold (which does not have subscription fee or charge per extra custom attributes). Even these APIs are being labeld as paid in the store.

**Steps**  
Configure apim monetization as per [1\]
Create and publish an API with a OOB subscription tier
Login to Store

**Issue**
The created API is been labeld as "Paid" since a subscription tier with subscription fee / charg per extra was not selected this should not be classified as a paid API.

![image](https://user-images.githubusercontent.com/17248809/35550412-41869e36-05b0-11e8-88db-1d709ae42535.png)
![image](https://user-images.githubusercontent.com/17248809/35550426-59afd4d2-05b0-11e8-8200-fde1bb451695.png)

[1\] [https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs](https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs)

**Suggested Labels:**
APIM-2.1.0 Update 7
Type/bug
Priority/high
Severity/Critical

**OS, DB, other environment details and versions:**    
    OS: Ubuntu 14.04
    DB: MySQL 5.5.58
    JDK: Oracke jdk-8u121
    Setup: puppet pattern 6
    Note: enabled log4jdbc

**Comment by jsonds** [comment]
This was observed when only unlimited tier was selected.

**Comment by chamindias** [comment]
Hi,
This works as expected in the latest pack. Please see the image below.
![image](https://user-images.githubusercontent.com/8359365/36478179-db37d074-1729-11e8-9765-36452817ce6f.png)

Note about custom attribute : This is used to specify additional details related to the tier. These attributes have no impact on the monetization category. It will be decided based on the billing plan of the respective tier.

![image](https://user-images.githubusercontent.com/8359365/36478395-82d22244-172a-11e8-93ff-f75525d62453.png)

Answered, hence resolving.
