### ISSUE TITLE
Create API using WSDL is based on ANT

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#2638]
**Description:**
Need to refactor that based on MUI.

Fixed in:
https://github.com/wso2/carbon-apimgt/pull/4999

**Comment by Mariangela** [comment]
Related Doc JIRA issue:
https://wso2.org/jira/browse/DOCUMENTATION-7689

**Comment by Mariangela** [comment]
The following UI issues in terms of grammar errors were identified. Please fix these issues.

- https://github.com/wso2/product-apim/issues/2652
- https://github.com/wso2/product-apim/issues/2649

**Comment by tmkasun** [comment]
Documentation issues are fixed with https://github.com/wso2/carbon-apimgt/pull/5023

**Comment by Mariangela** [comment]
The documentation corresponding to this Git issue can be found at the following location:

https://docs.wso2.com/display/AM300/Create+a+SOAP+API
