### ISSUE TITLE
Copyrights need to be changed to 2018

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2647]
**Description:**
- The copyrights are outdated for the Store, Publisher, and Admin consoles. It needs to be changed from 2017 to 2018
- The copyrights for the Store states "WSO2 APIM Publisher v3.0.0 | © 2017 WSO2 Inc" which is incorrect. It should be "WSO2 APIM Store v3.0.0 | © 2018 WSO2 Inc"

**Affected Product Version:**
Pack to be released as the M16 release
![screen shot 2018-02-01 at 2 46 50 pm](https://user-images.githubusercontent.com/5195851/35670588-f6907c16-075e-11e8-840a-e1fb4007843e.png)

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5023

![image](https://user-images.githubusercontent.com/3313885/35680017-0c90c5dc-077f-11e8-9b36-20eccadc0f98.png)

**Comment by Mariangela** [comment]
@tmkasun in the attached screenshot I only see that the date has changed to 2018. Did you fix the following issue that I reported in this Git issue as well? According to the screenshot it has not been fixed.

The copyrights for the Store states "WSO2 APIM Publisher v3.0.0 | © 2017 WSO2 Inc" which is incorrect. It should be "WSO2 APIM Store v3.0.0 | © 2018 WSO2 Inc"

![screen shot 2018-02-01 at 10 05 31 pm](https://user-images.githubusercontent.com/5195851/35690590-3c8d15ca-079c-11e8-8d4b-65fa05ff0aab.png)
