### ISSUE TITLE
Grammar error under Select WSDL URL

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2649]
**Description:**
The following needs to be fixed in the UI.
- Change "WSDL will be validate upon submit" to "The WSDL will be validated upon submission"
- Change "validate WDSL url" to "Validates WDSL URL"

**Affected Product Version:**
M16
_Tested with pack that will be released as M16_

**Related Issues:**
https://github.com/wso2/product-apim/issues/2652

![screen shot 2018-02-01 at 1 24 11 pm](https://user-images.githubusercontent.com/5195851/35674086-8b7269ac-0769-11e8-95a2-fc6f946069a8.png)

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5023
![image](https://user-images.githubusercontent.com/3313885/35680079-4255a3e0-077f-11e8-8a3c-5b616a161383.png)

**Comment by Mariangela** [comment]
@tmkasun the UI has not been changed entirely based on the following feedback that I gave previously. 
Change "validate WDSL url" to "Validates WDSL URL"

When changing this sentence you can future improve the suggestion as follows: 
Change "validates WDSL url" to "Validates the WDSL URL"

**Comment by Mariangela** [comment]
Please refer my last comment for the reason as to why I am reopening this Git Issue.

**Comment by tgtshanika** [comment]
This is fixed in
![Uploading Screen Shot 2019-09-11 at 10.05.56 PM.png…]()
 APIM 3.0.0 m35
