### ISSUE TITLE
[Chaos] NPE while DB service restart

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2651]
**Description:**
NPE occurred on pub/store, analytics, gateway nodes while restart the DB server while doing chaos testing. Better to handle the situation properly from the code.

**Affected Product Version:**
APIM2.1.0 WUM

**OS, DB, other environment details and versions:**    
Ubuntu 14.04, jdk1.8.0_121,mysql5.6

**Steps to reproduce:**
Restart the database instance

**Comment by bhathiya** [comment]
Please post the exception trace.

**Comment by isharac** [comment]
Please reopen with the stack trace if this occurs again.
