### ISSUE TITLE
Grammar error under Create API

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2652]
**Description:**
The following needs to be fixed in the UI.
- Change "Design new REST API using WSDL" to "Design **a** new REST API using WSDL"
- Change "You can configure the advance configurations later" to "You can configure the **advanced** configurations later"
-  Change "Version input not support in this release" to "Version input **is** not supported in this release"

**Affected Product Version:**
M16

**Related Issues:**
https://github.com/wso2/product-apim/issues/2649

![screen shot 2018-02-01 at 1 30 55 pm](https://user-images.githubusercontent.com/5195851/35675415-e7592838-076d-11e8-95fe-3f6b6ed67c1b.png)

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5023
![image](https://user-images.githubusercontent.com/3313885/35681093-5cbf18da-0782-11e8-9421-7000ad46677c.png)

**Comment by Mariangela** [comment]
This change is ok.

**Comment by tgtshanika** [comment]
Fixed for APIM 3.0.0 m35

<img width="401" alt="Screen Shot 2019-09-11 at 9 43 52 PM" src="https://user-images.githubusercontent.com/4471756/64715653-83c40280-d4de-11e9-8781-be18cf63dd7f.png">
<img width="733" alt="Screen Shot 2019-09-11 at 9 51 53 PM" src="https://user-images.githubusercontent.com/4471756/64715654-83c40280-d4de-11e9-9d21-b985d42c2504.png">
