### ISSUE TITLE
Improve access token auto refresh

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2653]
**Description:**

- Improve access token auto-refresh mechanism to intercept the API call and do access token regenerate, if it's about to expire and inject new access token into currently intercepted API request.Make sure won't fail due to 401 Unauthorized error

- With the current SwaggerJS [interceptor implementation](https://github.com/swagger-api/swagger-js#http-client), it expects a request object to be returned from the interceptor function. But we have to return a promise with the access token regenerate because it's an asynchronous  call which requires a network IO

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tmkasun** [comment]
It seems that, now SwaggerJs interceptors accept  Promise object as the response of the interceptor function.

```javascript
responseInterceptor: (res: Response) => Response | Promise<Response>
```

We might able to refresh the tokens on the fly if the access tokes have expired. 👏 🙏 🇱🇰

**Comment by tgtshanika** [comment]
Fixed
