### ISSUE TITLE
Remove unwanted links on "Maintaining Separate Production and Sandbox Gateways" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2669]
**Description:**
Please remove the unwanted hyperlinks on environments config in [1].

[1]https://docs.wso2.com/display/AM2xx/Maintaining+Separate+Production+and+Sandbox+Gateways

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/Normal

**Affected Product Version:**
APIM 2.X.X documentation

**Comment by taniamahanama** [comment]
This seems to be a limitation in Confluence when using the Code Block macro [1]. We either need to remove the code block, or live with the links. I think having the code in a code block takes precedence so I'm leaving it as it is for now. 
[1] https://community.atlassian.com/t5/Confluence-questions/How-do-I-remove-link-in-code-block/qaq-p/268590.
