### ISSUE TITLE
Please include some reference or link how we can configure different gateways in multi-tenanted setup

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2681]
**Description:**

1. I was going through the [1] in order to configure different gateways including publisher and other component  in multi tenant environment. 
2. Document contains information saying we can do this. But it doesn't contain any reference or link which we can refer.
3. Please include those information.

[1] https://docs.wso2.com/display/AM2xx/Maintaining+Separate+Production+and+Sandbox+Gateways

**Suggested Labels:**
Type/Docs
Type/Bug
Severity/Critical
Priority/High

**Comment by tgtshanika** [comment]
The only difference in configuring the gateways in a multi-tenanted environment is, sharing the User DB and Registry DB in gateway nodes. This has been mentioned in https://docs.wso2.com/display/AM260/Understanding+the+Distributed+Deployment+of+WSO2+API-M
