### ISSUE TITLE
Need pre-packaged WSO2 Identity Server for latest IS versions

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2686]
**Description:**
The doc link[1] has pre-packaged WSO2 Identity Server for only IS 5.3. Need to have pre-packaged  IS for latest release versions as well.  

[1] https://docs.wso2.com/display/AM210/Configuring+an+External+IdP+as+a+Key+Manager

**Suggested Labels:**
Improvement

**Comment by tgtshanika** [comment]
Pre packages IS as KM can be download from https://wso2.com/api-management/previous-releases/ and this has been mentioned in each APIM version doc spaces.

APIM 2.1 -> IS KM 5.3.0
APIM 2.2 -> IS KM 5.5.0
APIM 2.5 -> IS KM 5.6.0
APIM 2.6 -> IS KM 5.7.0
