### ISSUE TITLE
[Doc] Include IS latest release versions for pre-packaged Identity Server as a Key Manager

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2687]
Doc Link: https://docs.wso2.com/display/AM210/Configuring+an+External+IdP+as+a+Key+Manager

**Description:**
- Currently only pre-packaged Identity Server 5.3 is mentioned in the docs. Latest pre-packaged Identity Server versions need to be included in Configuring WSO2 Identity Server as a Key Manager.

**Suggested Labels:**
- Improvement

**Related Issues:**
- https://github.com/wso2/product-apim/issues/2686

**Comment by tgtshanika** [comment]
This is fixed
