### ISSUE TITLE
[Doc] Add path to find carbon.xml file in configure port offset for WSO2 API-M or WSO2 IS

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2688]
**Description:**
Doc link: https://docs.wso2.com/display/AM210/Configuring+WSO2+Identity+Server+as+a+Key+Manager#ConfiguringWSO2IdentityServerasaKeyManager-Step3-Optionally,configureportoffsetforWSO2API-MorWSO2IS

**Suggested Labels:**
Improvement

**Comment by tgtshanika** [comment]
This is fixed in https://docs.wso2.com/display/AM210/Configuring+WSO2+Identity+Server+as+a+Key+Manager#ConfiguringWSO2IdentityServerasaKeyManager-Step2-Optionally,configureportoffsetforWSO2IS
