### ISSUE TITLE
Generating access tokens from API Store without Client Credentials grant type leads to error

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#2691]
The API Store relies on the Client Credentials grant type to generate the Application access token that will be displayed in the respective Application subscription.

If the Client Credentials grant type is unselected and the Access token for the Application is generated for the first time the store throws an error. 

This needs to be handled smoothly so that a message is communicated to the user saying that the Access token cannot be generated to be displayed in the UI because Client Credentials is disabled.

**Comment by bhathiya** [comment]
This is fixed in 2.2.0
