### ISSUE TITLE
UI rendering issue in "Design a new REST API using WSDL" page

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2692]
**Description:**
1) The "Business Plans" caption tends to overlap with the selected business plans at times. For example when selecting the Implementation Type.

2) There is no spacing between "Select a plan for the API and enable API level throttling." and "Implementation Type" is not enough.

**Affected Product Version:**
M16

**OS, DB, other environment details and versions:**    
Mac OS, Chrome

**Related Issues:**

https://github.com/wso2/product-apim/issues/2652
https://github.com/wso2/product-apim/issues/2649

![issues](https://user-images.githubusercontent.com/5195851/35850170-ed9bba00-0b49-11e8-8623-d4f681113302.png)

**Comment by tgtshanika** [comment]
Fixed in master branch.
<img width="755" alt="Screen Shot 2019-09-11 at 7 05 37 PM" src="https://user-images.githubusercontent.com/4471756/64701869-31c3b280-d4c7-11e9-8d14-1e78d783360f.png">
