### ISSUE TITLE
Please include information of database scripts which we need to run on the different dabases

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2693]
**Description:**
In [1], we have information on what are the databases we need to create for each APIM profile.
But it doesn't contain information on which db script should use manually  in each database.
Please include those details on [1]

[1] https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager

**Suggested Labels:**
Type/Docs
Type/Bug
Severity/Critical
Priority/High
Affected/2.2.0

**Comment by tgtshanika** [comment]
This information is included in 
https://docs.wso2.com/display/AM210/Changing+the+Default+API-M+Databases
https://docs.wso2.com/display/AM210/Installing+and+Configuring+the+Databases docs
