### ISSUE TITLE
Please include the information on different gateway endpoints in the distributed environment

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2698]
**Description:**

1. When we configuring gateway environment in publisher node [1], it includes the information on hybrid gateway configuration.
2. if we want to have two different gateway endpoints in there, please include resources or a reference how we can setup different gateway endpoint environments.

[1] https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager
 

**Suggested Labels:**
Type/Bug
Type/Docs
Priority/High
Severity/Major
Affected/2.2.0

**Comment by tgtshanika** [comment]
This is available in https://docs.wso2.com/display/AM210/Publish+through+Multiple+API+Gateways doc
