### ISSUE TITLE
Content is ignored in 202 response messages

### ISSUE THREAD

**Issue by matslundberg** [wso2/product-apim#2713]
**Description:**
When an API returns HTTP 202 on a POST, WSO2 API Manager fails to return anything and the request times out.
The following appears in the carbon.logs.
```
TID: [-1234] [] [2018-02-08 09:18:57,972] ERROR {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender} -  Failed to submit the response {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender}
org.apache.axis2.AxisFault: Payload could not be written as JSON.
        at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:276)
        at org.apache.synapse.commons.json.JsonFormatter.writeTo(JsonFormatter.java:62)
...
TID: [-1234] [] [2018-02-08 09:18:57,985]  WARN {org.apache.synapse.core.axis2.Axis2Sender} -  Trying to send a response to an already responded client request - Rest API Context : /test202/LATEST {org.apache.synapse.core.axis2.Axis2Sender}
TID: [-1] [] [2018-02-08 09:19:57,621]  WARN {org.apache.synapse.transport.passthru.SourceHandler} -  Connection time out after request is read: http-incoming-96 Socket Timeout : 60000 Remote Address : /127.0.0.1:39768 {org.apache.synapse.transport.passthru.SourceHandler}
```

This has been tested on version 2.1.0-update8 and using a mock API definition which goes against http://httpstat.us/202

This may be a duplicate of [APIMANAGER-5731](https://wso2.org/jira/browse/APIMANAGER-5731). While a pull request exists and has been merged in April 20171. It does not say in which version of WSO2 API Manager it will be fixed.

**Affected Product Version:**
WSO2 API Manager v2.1.0-update8

**OS, DB, other environment details and versions:**    
CentOS 7, MariaDB, jdk1.8.0_151

**Steps to reproduce:**
1. Define a mock API in APIM, with one request: POST /202 (see swagger def below). Production/Sandbox Endpoint: http://httpstat.us/
```
swagger: "2.0"
paths:
  /202:
    post:
      responses:
        "200":
          description: ""
      parameters:
        - name: Payload
          description: Request Body
          required: false
          in: body
          schema:
            type: object
            properties:
              payload:
                type: string
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
info:
  title: Test202
  version: LATEST
```
2. Subscribe to API and try to Execute request in Store. Request times out and above lines will appear in `/wso2carbon.log`.

**Related Issues:**
[APIMANAGER-5731](https://wso2.org/jira/browse/APIMANAGER-5731)

**Comment by uvindra** [comment]
This cannot be reproduced in the latest build of the upcoming 2.2.0 release, therefore resolving the issue

This will be available with 2.1.0-update14
