### ISSUE TITLE
Even though user is actually not logged in audit.log shows the user as logged in for /admin console

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2719]
**Envrionment**
OS: Ubuntu 16.04
JDK: 1.8.0_144
Pack; APIM 2.1.0

**Steps**
1. Create a user with api creator permission
2. Log in to /admin console using the above user

The user is not logged in to the console. But the audit log prints the log as the user has logged in. This is a high priority issue as in real environments audit.log is printing a misleading information. Hence this should be fixed to cater the real production audit purposes

**Comment by bhathiya** [comment]
Reduced priority as this is not a blocker.

**Comment by bhathiya** [comment]
Here authentication is successful but authorization is failed. Therefore, we can't remove this particular audit log. As a fix, added another log entry for the authorization failure.

https://github.com/wso2/carbon-apimgt/pull/5436
