### ISSUE TITLE
Alerts not sending emails when using a token from Resource Owner

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#2728]
**Description:**
Create Api and Subscribe.
Subscribe into alerts.
Generate a token for a user1 (Resource Owner) and generate alert

Expected
Alert need to come to the actual subscriber.
Actual
Alert not came to the emails subscribed.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
