### ISSUE TITLE
Supporting Correct REST API convention for the REST service used for scope retrieval of a particular Application

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#2738]
**Description:**
The way that we have defined the applicationsScopesApplicationIdGet service which use to get scopes associated with particular application based on subscribed APIs [2] in APIM 2.1.0 (and in 2.x as well) is not following the REST API conventions.

The resource path of the request URL is as follows for this service.

(1) applications/scopes/{applicationId}

Which should be corrected as 

(2) applications/{applicationId}/scopes

if we follow the correct REST API conventions.

Therefore we need to deprecate the existing REST service and create new REST service to support the correct REST API convention (applications/{applicationId}/scopes) without removing the old one.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by bhathiya** [comment]
We shouldn't do API changes in 2.x. This issue is not there in 3.x. Hense closing the issue.
