### ISSUE TITLE
Support to extract username form <saml:AttributeStatement> in SAML2 Response

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#2752]
**Description:**
Currently in API Manager level, username is always extracted from Subject Name ID, we should provide a flexibility to extract username from attribute based on a configuration

**Suggested Labels:**
Improvement, APIM 2.1.0

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.1.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:** N/A

**Related Issues:**
https://wso2.org/jira/browse/IDENTITY-1893

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5080
