### ISSUE TITLE
Scroll option not available in the Publisher

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#2754]
**Description:**
In M18, the scroll option is not there for the Publisher; therefore, when interfaces are long, users are not able to fill out the required information and actually complete the task that they set out to do.

For example:
A user is not able to create a SOAP based API.
![screen shot 2018-02-15 at 10 42 29 pm](https://user-images.githubusercontent.com/5195851/36299572-a4b02a88-1323-11e8-9be7-229f4768cd33.png)

**Suggested Labels:**

**Suggested Assignees:**
@chanaka3d 

**Affected Product Version:**
APIM 3.0.0 M18

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This UI design has been changed for publisher app in master branch.
