### ISSUE TITLE
Error occur when restarting the server after migrating from WSO2AM-2.0.0 to WSO2AM-2.1.0

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-apim#2755]
**Description:**
After running apim200_to_apim210_gateway_artifact_migrator.sh and restarting the new APIM 2.1.0 instance, the APIs with caching enabled throw the below exception.

> Caused by: org.apache.synapse.SynapseException: Specified class for the hashGenerator is not a DigestGenerator. It *must* implement org.wso2.carbon.mediator.cache.digest.DigestGenerator interface

**Suggested Labels:**
Bug

**Affected Product Version:**
AM-2.1.0, AM-2.0.0    

**Steps to reproduce:**
Follow the steps in the attached documentation [1] for **Upgrading from 2.0.0 to 2.1.0**
Then start the WSO2AM-2.1.0 server

[1] https://docs.wso2.com/display/AM210/Upgrading+from+the+Previous+Release

**Comment by lzelus** [comment]
Specifically it happens on API's that have caching enabled.  Re-publishing the API in 2.1.0 will solve the issue, but would have to be done for each effected API.

**Comment by tgtshanika** [comment]
This has been fixed
