### ISSUE TITLE
Error while creating an API with SOAP endpoint

### ISSUE THREAD

**Issue by dewmini** [wso2/product-apim#2763]
**Description:**
Getting an error "Failed to process wsdl" when creating an API with SOAP endpoint where multiple addresses are defined in the WSDL port as in the following example.

<wsdl:port binding="tns:WSHttpBinding_SampleSoap" name="WSHttpBinding_SampleSoap">
         <soap12:address location=xxx /> 
         <wsa10:EndpointReference>         
            <wsa10:Address>xxx</wsa10:Address>
            <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
               <Spn>host/localhost</Spn>
            </Identity>
         </wsa10:EndpointReference>
      </wsdl:port>

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**    

- Add new API with a SOAP endpoint. WSDL should contain multiple addresses defined in the WSDL port.
- Click on "Next: Implement". 

A pop-up will appear with "Failed to process the WSDL"

**Related Issues:**
No

**Comment by isharac** [comment]
Fixed .
https://github.com/wso2/carbon-apimgt/pull/5649
https://github.com/wso2/carbon-apimgt/pull/5657
