### ISSUE TITLE
Getting error "Failed to process the WSDL." 

### ISSUE THREAD

**Issue by SureshG02** [wso2/product-apim#2767]
I am trying to create new version API using WSO2 2.1 APIM and getting error as Failed to process the WSDL . Can anybody tell me how to fix this ?

**Comment by SureshG02** [comment]
Well there seems to be some workaround for this issue mentioned on WSO2 documentation. From github link https://github.com/wso2/product-apim/issues/1966 it seems issue is already fixed but wanted to know under which version ?

**Comment by uvindra** [comment]
This will be available in the upcoming 2.2.0 APIM release

**Comment by tgtshanika** [comment]
Fixed in master branch
