### ISSUE TITLE
[IS-AS-KM] APIM version should be corrected on "Configure IS as KM" section

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2768]
**Description:**
Section [1] mentions the APIM version is as 2.1.0, ideally it should be 2xx or 2.1.0-update(until 2.2.0 is released in future) otherwise there is no point of having this section under 2xx.

[1] https://docs.wso2.com/display/AM2xx/Configuring+WSO2+Identity+Server+as+a+Key+Manager

**Affected Product Version:**
2.1.0-update(2xx)

**Comment by chamindias** [comment]
Added 2.1.0-updateXX in the doc. Hence resolving.
