### ISSUE TITLE
[APIM 1.9.0]After publishing, when trying to update an API with swagger definition, the API update fails with exception.

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#2769]
**Description:**
After publishing, when trying to update an API with swagger definition, the API update fails with exception.
org.wso2.carbon.apimgt.api.APIManagementException: At least one resource is required

**Suggested Labels:**
Bug, APIM 1.9.0

**Suggested Assignees:**
N/A

**Affected Product Version:** APIM 1.9.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
1. Create an API
2. Publish the API
3. Update the API

**Related Issues:**

**Comment by chamilaadhi** [comment]
We have deprecated jaggery related publisher and store APIs. For publisher and store related new Rest APIs can be found in   https://docs.wso2.com/display/AM210/apidocs/store/ and https://docs.wso2.com/display/AM210/apidocs/publisher/
