### ISSUE TITLE
Address PR comments in https://github.com/wso2/carbon-apimgt/pull/5048/files

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#2778]
**Description:**
This requested changes in the PR should be address.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
Requested changes are applied. Hence resolving
