### ISSUE TITLE
Move swagger codegen versions to root pom

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#2779]
**Description:**
The versions are introduced in this PR https://github.com/wso2/carbon-apimgt/pull/5000

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This is fixed for APIM 3.0.0
