### ISSUE TITLE
NULL is published for  api_version when default api becomes suspended.

### ISSUE THREAD

**Issue by minudika** [wso2/product-apim#2784]
**Description:**
When the default API get suspended, NULL is published for the api_version.

This might cause issues in the apim-analytics when trying to insert those NULL values into tables.
Therefore spark script could be failed to execute.

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
