### ISSUE TITLE
Giving 'Authentication Failed' for Authorization failures

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2789]
**Description:**
When the an valid user with creator permission is trying to publish an API, getting below[1] as the response and [2]logs is in the server console. Conceptually, the information giving by the product is wrong and also misleading the user.  Particular user is an valid user in the system but he is not authorized to perform particular action(publish). So these messages and responses should be corrected.

[1] 
```json
{"code":401,"message":"","description":"Unauthenticated request","moreInfo":"","error":[]}
```
[2]
```
[2018-02-22 12:27:22,181] ERROR - AMDefaultKeyManagerImpl Invalid OAuth Token : Invalid Access Token. Access token is not ACTIVE.
[2018-02-22 12:27:22,181] ERROR - WebAppAuthenticatorImpl Authentication failed. Please check your username/password
```
**Affected Product Version:**
wso2-apim-2.1.0-update11

**OS, DB, other environment details and versions:**    
macOS HS, JDK1.8

**Steps to reproduce:**
Note: used available admin services and rest apis to perform below steps
1. Create and user with Internal/creator permissions
2. Above created user creates an API.
3. Above user try to publish the created API.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
