### ISSUE TITLE
Better to have a successful message when creating an API version

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2797]
**Description:**
When we create a version of an API, it better to have successful message in UI

**Suggested Labels:**
Type/Improvement
Severity/Major
Priority/Normal
Affected/2.2.0 update 12

**Affected Product Version:**
APIM 2.1.0 update 12

**OS, DB, other environment details and versions:**    
OS-macOS high Sierra
DB-Mssql 2014
Userstore-JDBC

**Steps to reproduce:**
1) Create a version of an API.
2) Version is created but there's no successful message of created version.

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5111
