### ISSUE TITLE
[Staging] [UI] issue in selecting create new application from the subscription step 

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#2798]
Description:
an issue in selecting create new application from the subscription step

Preconditions
1.A large number of applications should exist when viewing the dropdown

Affected Product Version:

Note: the system allows the user to create a new application at the point of subscription. However, if there are a large number of applications then this option cannot be accessed. 

Steps to reproduce:
1.Attempt to create a new application by scrolling from the UI that allow the user to select the application to subscribe

**Comment by tgtshanika** [comment]
The subscription flow has been changed in APIM 3.0.0 and in the revamped Store UI of APIM 3.0.0, create new application option has been isolated and it's not available with the application list dropdown.
