### ISSUE TITLE
API search not get worked Correctly

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#2815]
**Description:**
Create two APIs as below.

1. API with name pizza1 and pizza12
2. Search API with below.
`curl -k -H "Authorization: Bearer <>" https://localhost:9443/api/am/publisher/v0.11/apis?query=name:pizza1&provider:admin&context:/pizzashack`

Expected
pizza1 API only to be retieved.
Actual
Both APIs get retrieved.

**Comment by tharindu1st** [comment]
We will going to support this from giving exact match to the values by double quoting the values

**Comment by ruthryi** [comment]
Fixed in the following : 

[1] : https://docs.wso2.com/display/AM2xx/apidocs/publisher/#!/operations#APICollection#apisGet
