### ISSUE TITLE
How to add application tokenScopes when user generates Keys

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2818]
**Description:**
No information or steps available in the document[1] on how to give/define required token scopes when the user is generating token for an application. Please add relevant information on applicable places in the document.
[1]
https://docs.wso2.com/display/AM2xx/apidocs/store/#!/operations#ApplicationIndividual#applicationsGenerateKeysPost

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5433
