### ISSUE TITLE
Improve the 'About' page with appropriate information

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#2819]
**Description:**
Provide a proper description on ' About' page in APIM management console. Current description contains the products that are deprecated. It is important to provide valid and appropriate information in the 'About' page as the first impression matters.

**Affected Product Version:**
APIM 2.1.0 update 12

**OS, DB, other environment details and versions:**    
Ubuntu 15.10
DB - H2
JDK - 1.8

**Steps to reproduce:**
Go to management console -> 'About' page

![screenshot from 2018-02-28 14-56-56](https://user-images.githubusercontent.com/14962228/36779961-ab082ebc-1c97-11e8-94aa-a51469bf885a.png)

**Comment by ChamNDeSilva** [comment]
Fixed with https://github.com/wso2/product-apim/pull/3035
