### ISSUE TITLE
Include a note that SDK generation is not supported with OpenAPI 3.0

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#2838]
**Description:**
Include a note to the document [1] that SDK generation is not supported with the APIs that are created using OpenAPI 3.0 support. 

For example: generating server stubs and client SDKs are not disabled from the API Publisher and client SDK download is not supported in API Store.

When a user selects the option OPENAPI 3.0 there is the notification in the product mentioning that we do not support SDK generation with OpenAPI 3.0 but we need to get this documented in the official API docs, for the users who are evaluating the capabilities via the docs. 

[1] https://docs.wso2.com/display/AM2xx/Generating+SDKs

**Comment by Mariangela** [comment]
Added the following note in [1] and [2].
SDK generation is not supported with the APIs that are created using OpenAPI 3.0 support.

[1] https://docs.wso2.com/display/AM2xx/Generating+SDKs
[2] https://docs.wso2.com/display/AM220/Generating+SDKs
