### ISSUE TITLE
Define a valid status for the API creation REST call

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#2839]
**Description:**
When we create an API through the REST API as mentioned in [1] the status of the request sample is in the "PUBLISHED" status, But when a user created an API the status of the API will be maintained in 'CREATED' status. Therefore we need a provide a valid API creation request with a valid value in 'STATUS' field.

[1] https://docs.wso2.com/display/AM2xx/apidocs/publisher/#!/operations#APICollection#apisPost

![screenshot from 2018-03-02 12-30-19](https://user-images.githubusercontent.com/14962228/36887197-0f8dd434-1e16-11e8-97ee-77d9ce8f6fda.png)

**Comment by ruthryi** [comment]
Changed in the following:
[1] : https://docs.wso2.com/display/AM2xx/apidocs/publisher/#!/operations#APIIndividual#apisPost
