### ISSUE TITLE
Client error message does not reflect the reason for the failure when the scope validation failed

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#2840]
**Description:**
The error message does not reflect the reason for the failure when the scope validation failed.

**Affected Product Version:**
APIM 2.1.0 update 12

**OS, DB, other environment details and versions:**    
DB - H2
OS - Ubuntu 15.10
JDK - 1.8

**Steps to reproduce:**
1. Generate access token as defined in [1]
ex:  
```
grant_type=password&username=${adminUsername}&password=${adminPassword}&scope=apim:api_view apim:api_create apim:api_publish
```
2. Get application details using the token generated from the above step ( using the access token generated from above step)
```
curl -k -H "Authorization: Bearer 6df1ea45-b3e6-3a9d-91e3-594906a41879" "https://localhost:9443/api/am/store/v0.11/applications"
```

**Observations**
Following error appeared in the APIM terminal
```
[2018-03-02 14:24:13,640] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

Client error message does not reflect the reason for the failure.
```
{  
   "code":401,
   "message":"",
   "description":"Unauthenticated request",
   "moreInfo":"",
   "error":[  

   ]
}
```

**Expected Results**
Client message should reflect the reason for the failure (Ex: scope validation failed)

Note - if we define the "apim:subscribe" scope when generating the token, get application call will be successful

[1] https://docs.wso2.com/display/AM2xx/apidocs/publisher/#guide

**Comment by tgtshanika** [comment]
If the token scopes are not matched with the required scopes to access the API resource, it is considered as an authentication failure. Hence, this is the expected behavior by design.
