### ISSUE TITLE
When can we expect APIM 2.2.0

### ISSUE THREAD

**Issue by crognon** [wso2/product-apim#2842]
**Description:**
When can we expect APIM 2.2.0 so we can use IS 5.4.0 as a KM ?

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
win32 & linux

**Related Issues:**
We cannot use IS 5.4.0 as KM for APIM 2.1.0 due to feature compatibility. We are seing many interesting features in IS 5.4.0 that we cannot touch. We need a coarsed grain release date to make the right decision : either to stick to IS 5.3.0 or to wait for APIM 2.2.0

Thanks
Cyril

**Comment by tgtshanika** [comment]
APIM 2.2.0 is already released and APIM 2.5.0 and 2.6.0 versions were the immediate releases after that.
