### ISSUE TITLE
Publisher Access Control - Public visibility apis not visible once logged in

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#2844]
**Description:**
After enabling publisher access control feature [1], the public visible apis of the store are not visible in the store once logged in.

[1] - https://docs.wso2.com/display/AM210/Enabling+Access+Control+Support+for+API+Publisher

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
1. Create API with user "user1" 
2. Set Access control to restricted by role(role1) and apply a role that user1 has
3. Leave Visibility on store as public
4. Publish API
5. Go to store app. API will be visible to the public.
6. Log in with another user for instance user2
7. API is no longer visible.

**Related Issues:**
https://github.com/wso2/carbon-apimgt/issues/4899

**Comment by tgtshanika** [comment]
Fixed
