### ISSUE TITLE
It is required relevant information on GDPR compliancy in the documentation

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2852]
**Description:**
Currently, there is no any detail/content related to GDPR compliancy in the documentation[1] but we have already released GDPR compliance feature on apim2.1.0-update13
[1] https://docs.wso2.com/display/AM2xx/

**Affected Product Version:**
wso2apim2.1.0-update13

**Comment by tharikaGitHub** [comment]
Available in https://docs.wso2.com/display/AM2xx/Removing+References+to+Deleted+User+Identities
