### ISSUE TITLE
UpdatedBy column is not populated for AM_API table

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#2854]
**Description:**
There is no easy way to find out who updated an API if a different user edits an API and republishes after some changes. This should be at least populated in the db table correctly. Currently the value is null.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
