### ISSUE TITLE
[UX] Forum link not working on carbon console

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2859]
**Description:**
Forum link not working on carbon console

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:** 
Ubuntu 16.10 

**Steps to reproduce:**
1. load carbon console
https://localhost:9443/carbon/admin/login.jsp
2. Click on forum link on the left side
3. Linked URL(https://wso2.com/forum/187) returns 404 not found

**Comment by tgtshanika** [comment]
This is fixed and the link is pointing to https://wso2.com/library/
