### ISSUE TITLE
[UX] Incorrect footer note on carbon console

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2861]
**Description:**
incorrect footer note on carbon console

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.10

**Steps to reproduce:**
1. load carbon console
https://localhost:9443/carbon/admin/login.jsp

© 2005 - 2016 WSO2 Inc. All Rights Reserved.

year need to be updated

**Comment by tgtshanika** [comment]
This is fixed for APIM 2.6.0
