### ISSUE TITLE
[UX] Login page help content are outdated

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2862]
**Description:**
this page contains few links to different doc pages and those are outdated. IMO we can remove those from the login page

About link: https://<host>:9443/carbon/product/about.html
Sign-in Help: https://172.17.0.1:9443/carbon/docs/signin_userguide.html

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
