### ISSUE TITLE
Store REST API : API details return default gateway URL not the custom URL

### ISSUE THREAD

**Issue by Dilhasha** [wso2/product-apim#2864]
**Description:**
When API details are retrieved for a tenant domain which has a custom URL enabled, it returns the default gateway URL and not the custom URL. But the correct custom URL is shown in the Store overview UI.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Enable a custom URL for a tenant
2. Retrieve API information using REST API [1].

**Related Issues:**
None

[1] https://docs.wso2.com/display/AM210/apidocs/store/#!/operations#APIIndividual#apisApiIdGet

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/4c91de3a1e0f6248f86140dc8d5b6bbb8912b772
