### ISSUE TITLE
[Docs] Update REST API version in Docs

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#2865]
**Description:**
REST API version in docs should be updated from v0.11 to v0.12 for all 4 APIs.

- Publisher - https://docs.wso2.com/display/AM2xx/apidocs/publisher
- Store - https://docs.wso2.com/display/AM2xx/apidocs/store
- Admin - https://docs.wso2.com/display/AM2xx/apidocs/admin
- DCR - "Getting Started" sections in each of above links

**Comment by ruthryi** [comment]
Fixed 

[1] : https://github.com/wso2/carbon-apimgt/pull/5153

**Comment by ruthryi** [comment]
Changes done and docs hosted.
