### ISSUE TITLE
[UX] Incorrect instruction on Install.txt file

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2869]
**Description:**
in the Install.txt file 

3. To start WSO2 AM one can use either wso2server.sh or daemon.sh in all Unix
   systems & wso2server.bat file on Windows operating systems.

There is no such file called "deamon.sh" inside the bin folder. 

**Affected Product Version:**
2.1.0 pack

**Comment by rmsamitha** [comment]
Closing as the mentioned sentence is not available now in latest product (APIM-4.1.0-m3)
