### ISSUE TITLE
[Gateway] Design a New Websocket API

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2879]
**Description:**
* Existing feature in 2.2.x
* Support WS and WSS support in gateway

**Comment by tgtshanika** [comment]
The option to create WebSocket APIs is given in API Publisher, but the following issues are there with WebSocket API creation flow in publisher.

- REST API create page is given as the websocket API create page. If it is a WebSocket API, there should be a clear indication in the page topic and the description as well, that the creating API is a WS API.
<img width="782" alt="Screen Shot 2019-09-19 at 12 26 25 PM" src="https://user-images.githubusercontent.com/4471756/65240024-ebd9a080-dafd-11e9-8962-c73aa0ef8fc9.png">
- API Definition tab should be hidden in WS APIs.
- Prototyping API option should be hidden in WS APIs
- Loadbalancer, failover endpoint configs, Endpoint type selection dropdown, and endpoint security options should be removed from Endpoint tab of a WS API
- Transport selection option, response caching, API security, mutual ssl, Authorization header customization option should be removed from WS APIs
- Scopes and resources tab should be removed

**Comment by Arshardh** [comment]
Creating a websocket API, creates an API of type **HTTP**. Instead it should be of type **WS**

**Comment by Arshardh** [comment]
The Environments show the HTTP endpoints instead of WS and Microgateway component is visible
