### ISSUE TITLE
[Publisher] Improvements to API overview page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2886]
**Description:**
* Add following UI features to publisher `Overview` tab which was in Desing phase of the API creation wizard in 2.2.x.
  * Visibility on Store
  * API Description
  * Tags
  * Thumbnail Image upload
  * Date Last Updated
  * API Labels

* This is how it was in 2.2.x
![desing_migration](https://user-images.githubusercontent.com/3313885/37072499-eedafa84-21e7-11e8-9169-00cd5c984a41.gif)

**Comment by tgtshanika** [comment]
This has been implemented for APIM 3.0.0 m35. 

![image](https://user-images.githubusercontent.com/4471756/65219486-47903380-dad6-11e9-8be4-6869b6e93eb1.png)
