### ISSUE TITLE
[Publisher] Improve resource tab to have missing features which were in 2.2.x

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2888]
**Description:**
* Current `Resource` tab in Publisher is lack of following capabilities which were there in 2.2.x
  * Add Produces/Consumes
  * Resource Description
  * **Parameters**
    * Description
    * Parameter Type
    * Data Type
    * Required
    * Delete

* This is how it was in 2.2.x
![resource_edits](https://user-images.githubusercontent.com/3313885/37073085-b53cb58a-21ea-11e8-83f5-2fc8377c0168.gif)

**Comment by tgtshanika** [comment]
This is available in APIM 3.0.0 alpha
<img width="1173" alt="Screen Shot 2019-09-23 at 7 21 38 PM" src="https://user-images.githubusercontent.com/4471756/65431650-73454d80-de37-11e9-921a-4fb7075e280a.png">
