### ISSUE TITLE
[Publisher] Improvements to Endpoints tab

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2889]
**Description:**
* Add following UI features to Endpoints tab in Publisher
  * Manage Certificates
![image](https://user-images.githubusercontent.com/3313885/37073597-eb76593c-21ed-11e8-89a5-1b3f994e2095.png)

  * Load Balanced/Failover
  * Dynamic Endpoints
![image](https://user-images.githubusercontent.com/3313885/37073620-07b9f464-21ee-11e8-9ff1-fe8045d3bddd.png)

  * **Advanced Configuration**
    * Suspend State
    * Timeout State
    * Connection Timeout

![advnc_cnf_endpoints](https://user-images.githubusercontent.com/3313885/37073548-97275dcc-21ed-11e8-9ba1-228badf44454.gif)

**Comment by tgtshanika** [comment]
This has been implemented for APIM 3.0.0 m35 publisher UI
<img width="1192" alt="Screen Shot 2019-09-19 at 11 51 28 AM" src="https://user-images.githubusercontent.com/4471756/65218344-e8312400-dad3-11e9-8e55-8e1636954aa2.png">
