### ISSUE TITLE
[Publisher] Improvements to the Subscriptions page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2891]
**Description:**
* Add following UI features to `Subscription` page in Publisher API info
  * Default version
  * Transports
  * Response Caching
  * Authorization Header
* The above configurations were located in Manage Step(3rd) in the API creation wizard APIM 2.2.x
![image](https://user-images.githubusercontent.com/3313885/37074334-48f5f3d4-21f2-11e8-809c-54518da42d1b.png)

**Comment by tgtshanika** [comment]
This has been implemented in APIM 3.0.0 m35.

![image](https://user-images.githubusercontent.com/4471756/65218439-16166880-dad4-11e9-9040-bb15fa4723b4.png)
