### ISSUE TITLE
[Publisher] Add Stats tab in API info view

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2892]
**Description:**
* Add new tab named `Stats` in API info page to organize following API base statistic information
  - Active Subscriptions
  - Usage by Current Subscribers
  - API Subscriptions by Versions
  - API Usage by Versions

* The above information was in `Users` and `Versions` tab in 2.2.x
![image](https://user-images.githubusercontent.com/3313885/37074592-9804899e-21f3-11e8-9af1-5c98582c6bbd.png)

![image](https://user-images.githubusercontent.com/3313885/37074812-9df788c8-21f4-11e8-8bb8-705081ee78f3.png)

**Comment by tgtshanika** [comment]
Stat graphs have been moved to the analytics dashboard.
