### ISSUE TITLE
[UX] API Implementation - Cannot delete Endpoints in random order 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2893]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and standards - Is flow maintain the same patterns and consistency?

***Related task:***
Create API

***Issue:***
Production and Sandbox failover endpoints cannot be deleted in random order, have to delete the last entry first to delete the endpoint which needs to be deleted. 

***Proposed Solution:***
Have a delete inline option for added failover endpoints

**Suggested Labels:**
UX, Improvement, 2.1.0

**Affected Product Version:**
2.1.0

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0
