### ISSUE TITLE
[Publisher] Can't edit inline Document

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2894]
**Description:**
* Can't edit documents defined inline, Click on edit button redirects to APIs listing page
* Can't access Documents uploaded as Files, It also redirects to APIs listing page

![image](https://user-images.githubusercontent.com/3313885/37076264-d80221ca-21fb-11e8-9274-ccd493723f56.png)

**Comment by tgtshanika** [comment]
This has been implemented for APIM 3.0.0 publisher UI. 

<img width="1430" alt="Screen Shot 2019-09-19 at 11 27 55 AM" src="https://user-images.githubusercontent.com/4471756/65217059-989d2900-dad0-11e9-91f8-d3384a9a3608.png">
