### ISSUE TITLE
[Publisher] Improve resources tab to assign scopes to a resource

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2897]
**Description:**
* Implement UI feature to add scopes to an API
* Implement UI feature to assign above-created scope for that API

* Following is how it works in 2.2.x
![image](https://user-images.githubusercontent.com/3313885/37078157-177bd4b0-2204-11e8-8100-627ffaf111fb.png)

![adding_scopes](https://user-images.githubusercontent.com/3313885/37078284-9f5aef74-2204-11e8-8e29-75c205fe0374.gif)

**Comment by tgtshanika** [comment]
This has been implemented for APIM 3.0.0 Publisher UI

- Scope create UI
<img width="622" alt="Screen Shot 2019-09-19 at 11 21 22 AM" src="https://user-images.githubusercontent.com/4471756/65216790-b5852c80-dacf-11e9-9226-a6ae3c9c6fa7.png">

- Scope listing page with scope edit, scope delete functionality
<img width="1212" alt="Screen Shot 2019-09-19 at 11 21 09 AM" src="https://user-images.githubusercontent.com/4471756/65216829-ce8ddd80-dacf-11e9-9bed-f7f22baea8a3.png">

- Scope assign view
<img width="1032" alt="Screen Shot 2019-09-19 at 11 20 14 AM" src="https://user-images.githubusercontent.com/4471756/65216844-d9e10900-dacf-11e9-8956-ddbc7f01b8ef.png">
