### ISSUE TITLE
[UX] API Implementation - Both Production & Sandbox endpoints are marked as required but can proceed leaving one field empty

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2898]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and standards-Is flow maintain the same patterns and consistency

***Related task:***
Create API

***Issue:***
Both Production & Sandbox endpoints are marked as required but can proceed leaving one field empty

***Proposed Solution:***
Add validation by make both fields required

**Suggested Labels:**
UX, Improvement, 2.1.0

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0
