### ISSUE TITLE
[UX] Add Cancel action on Add new tenant view - carbon console

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2904]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
User control and freedom --Is there a clear exit to the task

***Issue:***
No way to cancel the adding action directly, Also breadcrumb links also not working. 

***Proposed Solution:***
Need to have an option to cancel once user go to the add new tenant view
Add working breadcrumb navigation option
	
***Doc Link:***

**Affected Product Version:**
2.1.0

**Comment by chanaka3d** [comment]
This UI is replaced with the new React base UIs, hence the issue is not valid now.
