### ISSUE TITLE
[UX] Add new API - No validations in select API types: SOAP endpoint and Existing API 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2905]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error prevention - Is validations provided

***Related task:***
Create API

***Issue:***
Add new API Validations are not provided for SOAP endpoint and Existing API Swagger File  Swagger URL.
API Design - No validations in "import API definition" for Swagger File  Swagger URL.

***Proposed Solution:***
Add file extensions validations for API Swagger File and URL validations for Swagger URL and SOAP endpoint URL

**Suggested Labels:**
UX, Improvement, 2.1.0

**Affected Product Version:**
2.1.0

**Comment by chanaka3d** [comment]
Fixed with the 3.x.
