### ISSUE TITLE
Cannot add Consent Purposes from Management console

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2906]
**Description:**
Management console doesn't allow to add a consent purpose.

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/2.1.0 update 13

**Affected Product Version:**
APIM 2.1.0 update 13

**OS, DB, other environment details and versions:**    
OS-Mac high sierra
DB-H2
Fresh APIM 2.2.0 update 13

**Steps to reproduce:**
Login to the APIM management console
Go to the Consent Purposes -> in Manage section
Click on add link
provide the required details.
Click on the Finish Button.

**Results:**
No Consent Purposes are added.
Error message is showed in the console.(Screen shot is attached)
No errors in the Backend.

<img width="850" alt="screen shot 2018-03-07 at 3 43 18 pm" src="https://user-images.githubusercontent.com/14923354/37086781-6a41ce1a-221e-11e8-96bd-1e7cf9706f1a.png">

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/product-apim/pull/2935 and https://github.com/wso2/carbon-apimgt/pull/5174
