### ISSUE TITLE
Listing the Consent Purposes shows an error message

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2907]
**Description:**
When we click on the list option in Consent Purposes section, it will show an error message.

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/High
Affected/update13

**Affected Product Version:**
APIM 2.1.0 update13

**OS, DB, other environment details and versions:**    
OS-Mac high sierra
DB-H2
Fresh APIM 2.2.0 update 13

**Steps to reproduce:**
Go to the Consent Purposes section in Management console
Click on the List UI.

**Results:**
An error message will show as attached screenshot

<img width="1180" alt="screen shot 2018-03-07 at 3 48 21 pm" src="https://user-images.githubusercontent.com/14923354/37087192-980110ee-221f-11e8-95cf-03b78cc129ec.png">

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/product-apim/pull/2935 and https://github.com/wso2/carbon-apimgt/pull/5174
