### ISSUE TITLE
No Documentation is about Consent Purposes

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2908]
**Description:**
I couldn't documentation related to consent purposes in API Manager
What is consent purpose
Why we are using those.
What will do the consent purpose.
Please include those information in the AM2xx documentation.

**Suggested Labels:**
Type/Docs
Severity/Critical
Priority/Highest
Affected/AM2xx

**Affected Product Version:**
APIM 2.1.0 update 13

**Comment by tharikaGitHub** [comment]
Available in https://docs.wso2.com/display/AM2xx/Customizing+User+SignUp+in+API+Store#CustomizingUserSignUpinAPIStore-AddingConsentPurposes
