### ISSUE TITLE
[UX] Cannot remove tenants from management console

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2911]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
User control and freedom--Can the user undo the action

***Related task:***
Adding tenants

***Issue:***
You can add the tenants from the UI, but cannot remove from it. The document suggests using admin service to remove it. 

***Proposed Solution:***
Add the capability of removing tenants from the UI
	
***Doc Link:***
https://docs.wso2.com/display/AM210/Managing+Tenants

**Affected Product Version:**
2.1.0

**Comment by kavishkafernando** [comment]
Tenants can be de-activated through the admin service hence closing the issue.
