### ISSUE TITLE
[UX][Store] After re-generating token Grant type checkboxes do not get updated till page refresh

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2912]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Recognition rather than recall-Is the objects, actions, and options clearly visible? 

***Related task:***
Subscribe to an application

***Issue:***
when re-generating keys after updating the grant type checkboxes the updated checked/unchecked checkboxes do not get updated in the UI. The values get updated only on page refresh.

**Suggested Labels:**
Bug, UX

**Affected Product Version:**
2.1.0

**Comment by bhathiya** [comment]
This is fixed in 2.2.0
