### ISSUE TITLE
[UX] HTML tag is visible on error notification

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2913]
**Description:**
HTML tag is visible on error notification

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0

** Steps to reproduce**
1. Login to carbon console
2. go to Configure->multitenancy-> add new tenant
3. Click save
4. Error message appear with "\<br \/\>" tag

**Comment by tgtshanika** [comment]
Cannot reproduce this with APIM 3.0.0 milestone pack
