### ISSUE TITLE
[UX][Store] Subscriptions listing API image field shows a colored square without content

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2914]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Recognition rather than recall-Is the objects, actions, and options clearly visible

***Related task:***
Subscribe to an application

***Issue:***
In application subscriptions when there is no image added to API the listing does not show the first letter on the API image field.
![subscription-listing](https://user-images.githubusercontent.com/9837443/37090606-022e0750-222b-11e8-97d6-cb055765286b.png)

***Proposed Solution:***
When there is no uploaded API image add the first letter of the API to as in publisher API listing

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by chanaka3d** [comment]
Fixed in 3.x
