### ISSUE TITLE
Incorrect error message when login failed due to insufficient privilages

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2915]
**Description:**
when we try to login to API publisher without have login permission, it doesn't show the correct error message.

**Suggested Labels:**
Type/Bug
Severity/Major
Priority/Normal
Affected/Update 13

**Affected Product Version:**
APIM 2.1.0 update 13

**OS, DB, other environment details and versions:**    
OS-Mac high sierra
DB-H2
Fresh APIM 2.2.0 update 13

**Steps to reproduce:**
Create a user without having login permission.
Try to login to the Publisher with above user

**Results:**
Incorrect error message is showing as "Error! Login failed. Please recheck the username and password and try again.."
This should be due to insufficient privileges.

<img width="1193" alt="screen shot 2018-03-07 at 5 31 13 pm" src="https://user-images.githubusercontent.com/14923354/37091240-70aee4cc-222d-11e8-868c-aa7717bb7896.png">

**Comment by dushaniw** [comment]
This is fixed in the latest 3.1.0-Alpha, showing a 403 -Forbidden Error for unprivileged users.

![Screenshot from 2020-02-11 17-56-12](https://user-images.githubusercontent.com/12208083/74236753-e7ee2b00-4cf7-11ea-95d0-f1efbdc70572.png)


Hence closing the issue.
