### ISSUE TITLE
[UX][Store] API console - When trying the API Inform user to generate access token for not generated and expired access tokens

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2916]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error recognition - Is validations provided

***Related task:***
Invoke API

***Issue and Proposed solution:***
API console- When user select an application which has not generated access tokens or when the access token has been expired, the user should be given an info message with a link to generate keys.

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by kavishkafernando** [comment]
Closing since it is fixed in latest release.
