### ISSUE TITLE
[UX] Password not matched error message contains the regex pattern 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2920]
**Description:**
Password not matched error message contains the regex pattern

Passwords do not match.Password policy violation. Please enter your password to follow the regex.^[\S]{5,30}$

Need to add a human-readable error message instead machine-readable

**Suggested Labels:**
Bug

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
1. log into carbon console
2. goto configure-> multitenancy-> create Tenants
3. add different passwords to password fields 

Passwords do not match.Password policy violation. Please enter your password to follow the regex.^[\S]{5,30}$

**Related Issues:**

**Comment by tgtshanika** [comment]
In APIM 3.0.0, the regex has been removed from the error message.
