### ISSUE TITLE
[UX] Publisher login page error message not showing after click on close notification icon

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2921]
**Description:**
Publisher login page error message not showing after click on close notification icon

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 13

**Steps to reproduce:**
1. load publisher
2. Enter incorrect user name and password
3. click on the close button in error message
4. reenter  incorrect user name and password
5. click sign in
6. Now you can't see the error message

but XHR return comes with correct info
{"error" : true, "message" : "Login failed. Please recheck the username and password and try again.."}

**Related Issues:**

**Comment by tgtshanika** [comment]
This is fixed in the API Publisher login page of APIM 3.0.0
