### ISSUE TITLE
[UX] User should be able to view subscribed applications of the API 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2923]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Recognition rather than recall - Is the objects, actions, and options clearly visible

***Related task:***
Subscribe to an application

***Issue:***
Subscribed application list is not shown in the API overview page. User needs to be able to view the subscribed application list in API overview. 
	
**Suggested Labels:**
UX, Improvement, 2.1.0

**Affected Product Version:**
2.1.0

**Comment by kavishkafernando** [comment]
Closing since it is fixed in latest release.
