### ISSUE TITLE
config.json, default directory paths should be set to the relative paths as to working OB

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#2929]
**Description:**
default directory paths should be set to the relative path in the config.json[1], since this will not be changed in many cases.
[1] <AM_HOME>/repository/components/tools/identity-anonymization-tool/conf/config.json
```
the values are now as in below these should be changed to relative paths
"log-file-path" : "logs",
 "dir": "datasources",
```
**Affected Product Version:**
wso2am-2.1.0-update13

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/identity-anonymization-tool/pull/57
