### ISSUE TITLE
[APIM] Issues through extracted webapps in IS as Key Manager pack.

### ISSUE THREAD

**Issue by abimarank** [wso2/product-apim#2942]
**Description:**
Hi,

Since we install Key Manager feature manually by starting the IS, WAR files are extracted, but when a fix is given for WAR, we replaced the WAR file, and it never used as there will be an extracted web application. 

So when we release IS as Key Manager, we have to manually remove those extracted web application.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
With WUM model, it is not required to manually apply the fixes to webapps within the IS an KM distribution. Hence, this is fixed for all the versions which support wum updates.
