### ISSUE TITLE
[Store] Page title show as Publisher

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#2943]
**Description:**

- In page header, App name shows as `Publisher`

![image](https://user-images.githubusercontent.com/3313885/37155132-14aa0950-2308-11e8-8238-ee83607f8e98.png)

- Links added by `<Link>` react-router-dom shows generic anchor link styling(Underline and text color is blue)

**Affected Product Version:**

- API Manager 3.0.0-m21

**Comment by chanaka3d** [comment]
Fixed rom https://github.com/wso2/carbon-apimgt/pull/5243
