### ISSUE TITLE
Thumbnail image of the API and tag group image are not visible in Internet Explorer 11

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#2948]
**Description:**

The image is not visible when browsing from IE 11.

![image](https://user-images.githubusercontent.com/1591316/37255753-decad4a6-2576-11e8-8f75-fae2df5c3805.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu538** [comment]
Kernel Fix - https://github.com/wso2/carbon-kernel/pull/1719

**Comment by pubudu538** [comment]
Fix for carbon-apimgt - https://github.com/wso2/carbon-apimgt/pull/5181

We need to upgrade the kernel to incorporate the fix.

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5226
