### ISSUE TITLE
[UX] Notification for grant type update action

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2949]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Visibility of system status -Is the user given relevant feedback after a particular action ? ex: notification, status bar, loading indicator

***Related task:***
Subscribe to an application

***Issue:***
After generating access token when updating the grant types there is no notification displayed for the update action

***Proposed Solution:***
Add a notification for the update sucess and unsuccessful scenarios and update the fields onthe UI.

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by kavishkafernando** [comment]
Closing since it is fixed in latest release.
