### ISSUE TITLE
[UX][Publisher] After adding a new version the new API is not shown in API listing till page refresh

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2951]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Recognition rather than recall - Is the objects, actions, and options clearly visible? 

***Related task:***
Create new API version

***Issue:***
After adding a new API version when redirected to listing the newly added version is not visible till page refresh

**Suggested Labels:**
UX, Bug

**Affected Product Version:**
2.1.0

**Comment by kavishkafernando** [comment]
This issue has been fixed in the 3.x.x releases of APIM.
