### ISSUE TITLE
Can we have a compatible KM p2 repo for IS 5.5.0

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2954]
**Description:**
In order to verify the IS as Key manager features, can you please provide us p2 repo which compatible with APIM 2.1.0 update packs.

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/APIM 2.1.0 update 13

**Comment by tgtshanika** [comment]
IS 5.5.0 is not compatible with APIM 2.1.0.
