### ISSUE TITLE
[UX] [Publisher] Misleading action description on empty publisher API listing view

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2964]
**Description:**
There are two buttons listed on the main page. but the message says to click the button below to get started. 

![api publisher listing](https://user-images.githubusercontent.com/6497326/37211506-22de5fba-23d2-11e8-82e7-50bc6e2615fc.png)

IMO we need to change the text to remove the confusion of end users. 

**Affected Product Version:**
2.1.0-update13

**Related Issues:**

**Comment by tgtshanika** [comment]
This improvement has been added to APIM 3.0.0 publisher UI.
<img width="1409" alt="Screen Shot 2019-09-10 at 6 43 39 PM" src="https://user-images.githubusercontent.com/4471756/64616865-fc519300-d3fa-11e9-8a66-55a78a475496.png">
