### ISSUE TITLE
[UX] [Publisher] Misleading ellipsis usage with New API button

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2965]
**Description:**
Once you log into the main page without any APIs you can see the button to create new API. but label added with "New API...". ellipsis means the situation in which words are left out of a sentence but the sentence can still be understood: but this case we don't have such scenario. 

**Affected Product Version:**
2.1.0-13

**Comment by tgtshanika** [comment]
This improvement is added to APIM 3.0.0.
![Uploading Screen Shot 2019-09-10 at 6.42.34 PM.png…]()
