### ISSUE TITLE
Tooltip not set for Resouce Level Tiers when advanced throttling is disabled

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#2971]
**Description:**

![screenshot from 2018-03-09 23-12-23](https://user-images.githubusercontent.com/13759167/37221389-c15b807e-23ef-11e8-8f06-8427f87b025d.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
Closing this issue since the tooltip is displayed. 
<img width="935" alt="Screen Shot 2020-11-27 at 2 14 48 PM" src="https://user-images.githubusercontent.com/19324135/100429254-138da680-30bb-11eb-968f-3bbc1c736e79.png">
