### ISSUE TITLE
Update Dynamic ssl endpoint config document

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#2983]
**Description:**

Add following information to the Dynamic ssl endpoint config document[1]

-  It takes 10min for the cert to get applied in the default pack. it can be be configured in the <APIM_HOME>/repository/conf/axis2/axis2.xml (<fileReadInterval>)
- For a clustered environment, publisher and gateways should share the same location in /repository/resources/security/sslprofiles.xml . 

[1] https://docs.wso2.com/display/AM2xx/Dynamic+SSL+Certificate+Installation

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
Fixed in the following : 
[1] : https://docs.wso2.com/display/AM2xx/Dynamic+SSL+Certificate+Installation
[2] : https://docs.wso2.com/display/AM210/Dynamic+SSL+Certificate+Installation
