### ISSUE TITLE
[UX][Publisher] Need validations for new API version field

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2988]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error Prevention - Is validations provided

***Related task:***
Create new API version

***Issue:***
Can create an API with a version number lesser than the latest API version.
	
**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by tgtshanika** [comment]
The users cannot be restricted with the version number and by design, the API creators are allowed to pick a preferred value for the new version number.
