### ISSUE TITLE
[UX] No validations provided for tenant-conf.json

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2990]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error Prevention - Is validations provided

***Related task:***
Notify subscribers about new API version

***Issue:***
No validations provided for /_system/config/apimgt/applicationdata/tenant-conf.json when saving changes from management console.	

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by tgtshanika** [comment]
As per the current implementation, it is impossible to perform an explicit validation for the content of tenant-conf.json. This particular file is a registry resource, and it cannot be specially treated and perform validation when it has been updated from registry browse pane.
