### ISSUE TITLE
Changing the Default API-M Databases doc does not mention anything about consent DB

### ISSUE THREAD

**Issue by ushanib** [wso2/product-apim#3015]
Changing the Default API-M Databases doc [1] does not mention anything about consent DB.

It should mention information to the user to how to configure consent DB and its scripts.

[1] https://docs.wso2.com/display/AM2xx/Changing+the+Default+API-M+Databases

**Comment by ushanib** [comment]
Labels : Priority/Highest
            Type/Doc

**Comment by tharikaGitHub** [comment]
Consent tables are available in AM_DB scripts in later releases and we don't have separate scripts for consents. Hence no documentation is required.
