### ISSUE TITLE
[DB2] Error when creating tables for STAT_DB in APIM-Analytics

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#3025]
**Description:**
DB2 script given in documentation [1] is outdated and it needs to be modified adhering to the latest spark script changes.

[1] [https://docs.wso2.com/display/AM2xx/Configuring+APIM+Analytics](https://docs.wso2.com/display/AM2xx/Configuring+APIM+Analytics)

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
The stat db script to db2 is changed and uploaded to https://docs.wso2.com/display/AM2xx/Configuring+APIM+Analytics doc space
