### ISSUE TITLE
Cannot update versioned API with scopes

### ISSUE THREAD

**Issue by lasanthaS** [wso2/product-apim#3027]
**Description:**
When 2 versions of the same API exists with the same set of scopes, the second API cannot be updated. Following console error will be logged.

```
[2018-03-13 19:06:43,003] ERROR - APIProviderHostObject Scope list is already assigned by another API
```

**Suggested Labels:**
Bug

**Affected Product Version:**
APIM 1.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add API with scopes.
2. Create a copy of the API and save it as a new version.
3. Edit the second API and try to update.
4. An error will be displayed.

**Comment by tmkasun** [comment]
Already fixed in latest 2.2.x branch
