### ISSUE TITLE
JWT Token expiry can not be configured when cache is enabed 

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-apim#3033]
See the doc [1],  It is mentioned

" If caching is enabled for the Gateway Manager or the Key Manager, the JWT expiry time is the same as the cache expiry time by default."

When caching is enabled, expiry time must be slightly larger than the default cache timeout value.  If cache time out is 15m  JWT expiry must be 20m (15m + X) as JWT is passing to the external system.  If it is not, it would be failed  even if time is sync.  

As a fix,  when cache is enable,  we need to take the property in "JWTClaimCacheExpiry" as the expiry time & update the doc that "JWTClaimCacheExpiry" must be higher than the cache time out if cache is enabled.

[1] https://docs.wso2.com/display/AM210/Passing+Enduser+Attributes+to+the+Backend+Using+JWT#PassingEnduserAttributestotheBackendUsingJWT-ExpirytimeoftheJWT

**Comment by bhathiya** [comment]
Let's say the cache expiry time is 15 mins and JWT expiry is 20 mins. After 15 mins, we have to call the key manager anyway. We have 2 options at that point.

1) Generate a new JWT. - In this case, it's useless to have 20 min expiry time for the JWT as we regenerate it after 15 mins.  
2) Give the same token - In this case, the JWT will be expiring in 5 mins and we will be adding it to a 15 min cache, which is a problem. 

The ideal way to solve this is by considering a time skew when validating the JWT, considering network and other delays.
