### ISSUE TITLE
Already submitted user signup requests cant be seen to new approver user 

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#3034]
Description:
Already submitted requests for user signups cant be seen to new approver user

Suggested Labels:

Suggested Assignees:

Affected Product Version:

OS, DB, other environment details and versions:
APIM 2.1.0- APIM point into IS as KM pack
With custom approver role

Steps to reproduce:

    Create a new user and grant him approver role permission
    Submit few user signup requests via APIM store SignUp
    Login to the APIM admin app and make sure request are available
    Create a new user and grant him approver role permission
    Submit few user signup requests via APIM store SignUp
    Login to the APIM admin app and make sure request are available including previously submitted ones

Issue:
The newly created user can see only the lately submitted requests, not the previous one. Ideally, new user also should approve all the pending signup requests

**Comment by isharac** [comment]
Issue is not observed in the latest version 3.2.0
