### ISSUE TITLE
Need an alterantion in forgetme.tool Document

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#3036]
**Description:**
Following Document in [1],
Under Running the tool in API Manager section -> Before you begin.. -> 1st point
Please alter the information as mentioned below.

**Required Correction:**
This DB lock will happen if at least one of your databases point to the H2. 
Let's say you have User,REG and AM databases are pointed to Mysql but your carbon db is in 
H2, Then also you can get this mentioned db lock error. 

[1] https://docs.wso2.com/display/AM2xx/Removing+References+to+Deleted+User+Identities

**Suggested Labels:**
Type/Docs
Type/Bug
Priority/Normal
Affected/update 14

**Comment by tharikaGitHub** [comment]
Fixed
