### ISSUE TITLE
[UX] Select one of the option by default - Create API view

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3063]
**Description:**
Currently, the user needs to click on each section and perform another action before continue with the creation process. IMO we can remove the additional overheads by select one of the option

![add api](https://user-images.githubusercontent.com/6497326/37454940-e140ae34-2861-11e8-9a95-6fef2a06bf9e.png)

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
Ubuntu, chrome

**Comment by kavishkafernando** [comment]
Swagger File option is selected by default.

<img width="1167" alt="Screen Shot 2020-11-27 at 11 44 56 AM" src="https://user-images.githubusercontent.com/19324135/100417119-26e24700-30a6-11eb-9d37-7f9fc55a2ec9.png">
