### ISSUE TITLE
[UX] Need to have a confirmation option before retiring an API

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3066]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error prevention - Is there a confirmation option before committing to actions

***Related task:***
Retire API

***Issue:***
Since we cannot undo retiring API, we need to have a confirmation option for retire API as same as deprecate API

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0 update 14

**Comment by kavishkafernando** [comment]
This has been implemented hence closing the issue.

<img width="1163" alt="Screen Shot 2020-11-27 at 12 10 51 PM" src="https://user-images.githubusercontent.com/19324135/100419063-c523dc00-30a9-11eb-8e36-ac64a503cf20.png">
