### ISSUE TITLE
[UX] API create with existing API needs to have validation steps - "I Have an Existing API"

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3067]
**Description:**
$subject

**Suggested Labels:**
Bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOs 

**Steps to reproduce:**
1. log into the publisher
2. click create new API
3. select "I have an Existing API"
4. Click start creating 

you can't see anything happening, now select one of the radio boxes, its appear with an error.

We can disable the action until user paste URL or select file

**Comment by kavishkafernando** [comment]
This has been fixed.

<img width="1349" alt="Screen Shot 2020-11-27 at 12 33 49 PM" src="https://user-images.githubusercontent.com/19324135/100420741-f5b94500-30ac-11eb-9dff-761057be04e1.png">
