### ISSUE TITLE
[UX] API create with  - "I Have an Existing API" browse option issue

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3069]
**Description:**
Currently, we need to click on browse button to get the file window trigger. IMO we need to create entire space clickable for upload

**Suggested Labels:**
Bug, improvement 

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
Mac HS

**Steps to reproduce:**

Sample fix: https://codepen.io/washaweb/pen/ygzavZ

**Comment by kavishkafernando** [comment]
Closing this issue since this has been fixed in 3.x.x products.
