### ISSUE TITLE
[UX] API create with "I Have an Existing API" file type validation

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3071]
**Description:**
$subject, currently you can select any type of file and you need to hit start creating to get the server side validation of swagger file. IMO we can simply push the client side validation to limit the upload file types

to fix: add accept=".json" or valid file format type
<input id="swagger-file" name="swagger-file" type="file" title="swagger-file" class="form-control" multiple="" accept=".json">

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14
**OS, DB, other environment details and versions:**    
MacOS High sierra

**Comment by kavishkafernando** [comment]
Closing this issue since this has been fixed in 3.x products.
