### ISSUE TITLE
[UX] If validation failed API walkthrough path will get broken

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3074]
**Description:**
If the user accidentally typed name with space and hit tab to next step they can't go back and continue the walkthrough. 

![walkth](https://user-images.githubusercontent.com/6497326/37461725-526e2682-2875-11e8-9156-d541b7a358b0.png)

The same thing happened if you missed any of the steps and try to fix the previous step. 

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14
**OS, DB, other environment details and versions:**    
MacOS High sierra

**Comment by tgtshanika** [comment]
Will be tracked with https://github.com/wso2/product-apim/issues/1832
