### ISSUE TITLE
[UX] Auto Fix the API name field 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3075]
**Description:**
Since we are only supported the API name without spaces, shall we remove the whitespaces automatically to improve the UX

**Suggested Labels:**
improvement

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14
**OS, DB, other environment details and versions:**    
MacOS High sierra

**Steps to Reproduce**
Import http://petstore.swagger.io/v2/swagger.json 
this will automatically filled name " Swagger Petstore", but it generates an error. IMO this is bit problematic.  Shall we auto fix the name path ?

**Comment by bhathiya** [comment]
I think we should not update the API name automatically. They may not see that we have changed it and they might go ahead and publish it, to see the name is not correct later. 

The user may choose to replace space with an underscore. So I think we should give the chance to the user to correct it.

**Comment by kavishkafernando** [comment]
Since we provide white space validation we should allow user to manually correct the API Name. Hence closing the issue.
