### ISSUE TITLE
admin portal login failed when SSO is enabled

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#3077]
**Description:**
when SSO is enabled, cannot login to the admin app and following error log printed in Identity server side.

> [2018-03-15 14:59:34,290]  WARN {org.wso2.carbon.identity.sso.saml.processors.SPInitSSOAuthnRequestProcessor} -  Destination validation for Authentication Request failed. Received: [null]. Expected one in the list: [https://localhost:9444/samlsso]

Tested with IS 5.5.0 RC2 pack and API Latest build as at 15/03/2018

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5280
