### ISSUE TITLE
Password recoverty

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3083]
**Description:**
<img width="1232" alt="screen shot 2018-03-16 at 10 15 48 am" src="https://user-images.githubusercontent.com/3424539/37504247-14c228ea-2903-11e8-99bf-98ac771724e3.png">
<img width="1165" alt="screen shot 2018-03-16 at 10 15 58 am" src="https://user-images.githubusercontent.com/3424539/37504248-14f80208-2903-11e8-9cd6-896174183d99.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
Closing this issue as we have implemented this in the latest release.
