### ISSUE TITLE
My Account - change password feature

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3084]
**Description:**
The following feature needs to be implemented for 3.0.0

<img width="819" alt="screen shot 2018-03-16 at 11 06 05 am" src="https://user-images.githubusercontent.com/3424539/37505321-39dd6e6c-290a-11e8-8a4c-4f6b3b9aac6d.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
Closing this issue as we have implemented this in the latest release
