### ISSUE TITLE
Rating missing from the API thumbnails

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3085]
**Description:**
3.0.0 view
<img width="309" alt="screen shot 2018-03-16 at 11 09 57 am" src="https://user-images.githubusercontent.com/3424539/37505429-d264c2b6-290a-11e8-918c-f5385f36ca39.png">

2.2.0 view
<img width="310" alt="screen shot 2018-03-16 at 11 10 10 am" src="https://user-images.githubusercontent.com/3424539/37505430-d2984438-290a-11e8-81be-61f99f80eb8b.png">

**Comment by vithu30** [comment]
Fixed in [Add Rating in API thumbnail #5525](https://github.com/wso2/carbon-apimgt/pull/5525).

**Comment by tgtshanika** [comment]
This is available in APIM 3.0.0 Alpha
<img width="292" alt="Screen Shot 2019-09-25 at 2 51 03 PM" src="https://user-images.githubusercontent.com/4471756/65587719-ee2b7700-dfa3-11e9-9c8a-1a712bbf8c44.png">
