### ISSUE TITLE
[UX] [Publisher] API Create - I have a SOAP endpoint inside options are bit technical to understand by novice user

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3090]
**Description:**
The user will get confused on SOAP endpoint selection, the user has to select options such as pass-through or generate REST APIs. IMO we need to provide a simple label in order to understand the options.  Pass through is bit technical jargon and many users won't get it 

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
--Does the task cater to both experienced and inexperienced users?
--Was user able to clearly define the next action to perform?

**Suggested Labels:**
Improvement 

**Affected Product Version:**
2.1.0 update 14
**OS, DB, other environment details and versions:**    
MacOS High sierra

**Comment by kavishkafernando** [comment]
we can only provide the URL in APIM-2.1.0

<img width="1357" alt="Screen Shot 2020-11-27 at 2 26 20 PM" src="https://user-images.githubusercontent.com/19324135/100430652-14bfd300-30bd-11eb-9255-a14963b4f344.png">
