### ISSUE TITLE
[UX][publisher] API rating can  be added by the user who doesn't have subscription permission to that API

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3092]
**Description:**
$subject. 

**Suggested Labels:**
Bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
