### ISSUE TITLE
[UX] [Publisher] API Create upload thumbnail image file type restriction 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3093]
**Description:**
$subject. seems we need to add accept attrib to fix this.

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
