### ISSUE TITLE
[UX] [APIM] API create Upload error message not clearly positioned

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3094]
**Description:**
$subject
![screenshot-2018-3-16 api publisher - add rest api](https://user-images.githubusercontent.com/6497326/37512941-7bc45312-2929-11e8-8041-ac485cd9d480.png)

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
