### ISSUE TITLE
Flattening of wsdl inside wso2 APIM

### ISSUE THREAD

**Issue by SureshDigia** [wso2/product-apim#3099]
Can we add feature in WSO2 APIM 2.1 or higher version which could do first flattening of wsdl file and then create APIs ?

**Comment by tgtshanika** [comment]
This requirement is addreesed by the wsdl archive upload feature which has been introduced in APIM 2.6.0. Please refer [1] for more information.
[1] https://github.com/wso2/product-apim/issues/3716
