### ISSUE TITLE
Once an API is rated there is no way to remove it

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3102]
**Description:**

We need to implement the same in the 2.x product.

<img width="839" alt="screen shot 2018-03-16 at 7 48 18 pm" src="https://user-images.githubusercontent.com/3424539/37551156-778c5dc0-29c0-11e8-95bf-a31001794718.png">

If time permits we can do better by implementing something like the following..

1 - Not rated by the user
<img width="195" alt="screen shot 2018-03-17 at 8 49 16 am" src="https://user-images.githubusercontent.com/3424539/37551163-8e165e9c-29c0-11e8-9471-8699b45c1e45.png">

2 - Rating experiance
<img width="393" alt="screen shot 2018-03-17 at 8 49 26 am" src="https://user-images.githubusercontent.com/3424539/37551164-8e61e9ca-29c0-11e8-8c57-67242447723a.png">

3 - After rating
<img width="205" alt="screen shot 2018-03-17 at 8 49 46 am" src="https://user-images.githubusercontent.com/3424539/37551166-8eeecfd4-29c0-11e8-8225-af7bdf025365.png">

4 - Trying to remove the rating
<img width="380" alt="screen shot 2018-03-17 at 8 50 07 am" src="https://user-images.githubusercontent.com/3424539/37551167-8f3b5a34-29c0-11e8-9f58-4e2a44381df8.png">

**Comment by tgtshanika** [comment]
This feature is available in APIM 3.0.0 alpha
<img width="1037" alt="Screen Shot 2019-09-23 at 10 32 08 PM" src="https://user-images.githubusercontent.com/4471756/65446461-0a1f0380-de52-11e9-9644-d7577d4286ac.png">
