### ISSUE TITLE
Store - Overview tab is not providing essential information 

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3103]
**Description:**
Overview tab is not providing essential information as the 2.x version. See the following screen comparison.

**2.x** 
<img width="1162" alt="screen shot 2018-03-17 at 9 06 38 am" src="https://user-images.githubusercontent.com/3424539/37551270-bea5d040-29c2-11e8-9d56-430034a22f44.png">

**3.0.0**
<img width="1045" alt="screen shot 2018-03-17 at 9 07 07 am" src="https://user-images.githubusercontent.com/3424539/37551271-bedf9e74-29c2-11e8-8bf0-f9991df0f0d4.png">

**Comment by pubudu538** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5580
