### ISSUE TITLE
Forum feature in 2.x is reduced to api comments

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3106]
**Description:**
We can find the full forum implementation in 2.x.
<img width="1376" alt="screen shot 2018-03-19 at 9 18 28 am" src="https://user-images.githubusercontent.com/3424539/37577289-6c1e87c2-2b57-11e8-9ce7-29f379bd48e3.png">

But the feature is reduced to adding a comment in 3.0.0
<img width="1466" alt="screen shot 2018-03-19 at 9 18 00 am" src="https://user-images.githubusercontent.com/3424539/37577311-8904a9ac-2b57-11e8-829c-87dd213749e2.png">

Are we dropping the Forum feature in 3.0.0 ?

**Comment by tgtshanika** [comment]
This change has been applied in APIM 3.0.0 Alpha
