### ISSUE TITLE
Application listing page some helpful columns are missing

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3107]
**Description:**

Number of subscriptions column is missing in new Application listing page. Also the pagination and ability to sort from each column are missing.

**2.x**

<img width="1508" alt="screen shot 2018-03-19 at 9 29 48 am" src="https://user-images.githubusercontent.com/3424539/37577523-a3152cd0-2b58-11e8-9c05-557527d79415.png">

**3.0.0**

<img width="1396" alt="screen shot 2018-03-19 at 9 30 02 am" src="https://user-images.githubusercontent.com/3424539/37577530-aec411d6-2b58-11e8-8908-1ae694343c3b.png">

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 alpha
<img width="1265" alt="Screen Shot 2019-09-23 at 10 26 43 PM" src="https://user-images.githubusercontent.com/4471756/65446106-49992000-de51-11e9-9abf-ad501c0e8507.png">
