### ISSUE TITLE
Application Details Page - Overview Tab - Information missing

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3108]
**Description:**

Some of the essential information are missing from the new application overview tab.

- No need to show the API Name again in the details
- Description about the Throttling tier is missing

2.x
<img width="827" alt="screen shot 2018-03-19 at 9 40 20 am" src="https://user-images.githubusercontent.com/3424539/37577682-9b7080aa-2b59-11e8-8ddc-e1b15ac776e9.png">

3.0.0
<img width="1098" alt="screen shot 2018-03-19 at 9 38 19 am" src="https://user-images.githubusercontent.com/3424539/37577686-a00b6814-2b59-11e8-90de-fa6ae07b8052.png">

**Comment by tgtshanika** [comment]
This UI is available in APIM 3.0.0 alpha
<img width="522" alt="Screen Shot 2019-09-23 at 10 25 07 PM" src="https://user-images.githubusercontent.com/4471756/65446014-1191dd00-de51-11e9-9149-b781a2324536.png">
