### ISSUE TITLE
Features missing in the production key generation page

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3109]
**Description:**

- Copy to clipboard.
- Select grant types
- Provide callback url
- Select scopes
- Display curl after generating the access . tokens.

The above features are missing comparing the following screens

**2.x**
<img width="1155" alt="screen shot 2018-03-19 at 9 46 41 am" src="https://user-images.githubusercontent.com/3424539/37577962-5aae7728-2b5b-11e8-8e67-205f88bc64a3.png">

**3.0.0**
<img width="1118" alt="screen shot 2018-03-19 at 9 47 46 am" src="https://user-images.githubusercontent.com/3424539/37577964-62a5e4de-2b5b-11e8-9737-40e3f925b6cf.png">

**Comment by Krishanx92** [comment]
Fix Callback URL and Grant type
https://github.com/wso2/product-apim/issues/3224

**Comment by tgtshanika** [comment]
Fixed APIM 3.0.0 Alpha
