### ISSUE TITLE
[1.10]Considering refresh token validity period for Client credential

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#3114]
**Description:**
When access tokens are issued for the client credential grant type, it considers the refresh token validity period. According to the OAuth spec, it shouldn't be considered.
This created unexpected behaviors. For example, new access tokens would be generated within the access token validity period, if the refresh token validity period expired.

**Suggested Labels:**

identify, oauth, bug

**Suggested Assignees:**

**Affected Product Version:**
1.10
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Make the access token validity period 10min
2. Make the refresh token validity period 15 min.
3. Create an access token at T=0, then the refresh token expiry time = 15 min
, access token expiry time = 10min
4. Within T < 10 min, if you generate an access token, you get the same access token.
4. At T=12min, call to token end point, new access token with be generate with access token V.P = 10min, with same refresh token and refresh token expiry time 5 min.
In client credential grant type, refresh token validity period should not be considered.
However, current implementation takes that into consideration in APIM 1.10
5. At T=16min, access token validity period is 6 min. However since refresh token is expired, it generated an new access token, if token endpoint is called.

**Related Issues:**

https://wso2.org/jira/browse/IDENTITY-6777

**Comment by tgtshanika** [comment]
Fixed with: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/538
