### ISSUE TITLE
Improve Publisher walkthrough to prompt only when a user logs into the first time not every time APIs page loads.  

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-apim#3124]
**Description:**
The current behaviour of the publisher walkthrough is that when there is no APIs created, every time user accesses the APIs page publisher walkthrough triggers. It would be best if we can trigger the publisher walkthrough only when the customer logs into the API publisher for the first time. (Since there is a button API Walkthrough button if the customer needs he can use the Walkthrough as required )

**Suggested Labels:**
Improvement 

**Suggested Assignees:**
mushthaq@wso2.com

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Login to API Publisher using a user who hasn't created any APIs previously. 
2. When the publisher walkthrough pop-ups close it.
3. Refresh the APIs page

**Comment by tgtshanika** [comment]
This will be tracked in https://github.com/wso2/product-apim/issues/1832. Hence resolving this issue considering this as a duplicate.

**Comment by tgtshanika** [comment]
This will be tracked in #1832. Hence resolving this issue considering this as a duplicate.
