### ISSUE TITLE
Introduce a configuration to disable API publisher Walkthrough.

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-apim#3125]
**Description:**
Currently, there isn't any configuration to disable API publisher walkthrough. There should be an option to disable publisher walkthrough if necessary.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
mushthaq@wso2.com

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Comment by tgtshanika** [comment]
This will be tracked in #1832. Hence resolving this issue considering this as a duplicate.
