### ISSUE TITLE
DELETE requests without payload get appended with "xformValues" and giving 404 for requested resou

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#3128]
**Description:**
Additional xformValues append to the request URL as below for the DELETE requests without payload.

TID: [-1] [] [2018-03-21 14:55:09,658] DEBUG {org.apache.synapse.transport.http.wire} -  HTTP-Sender I/O dispatcher-1 << "DELETE /ProfileREST/v1/public/deleteMessage/31/**xformValues** HTTP/1.1[\r][\n]" {org.apache.synapse.transport.http.wire}

Therefore the response gives 404 as the requested resource is not available.

Note: This happens only when there's a content-aware mediator in the flow.

**Suggested Labels:**
2.1.0
synapse

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This is already fixed as per https://github.com/wso2/product-ei/issues/3302
