### ISSUE TITLE
Swagger-ui auth errors

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3135]
**Description:**
1 - Unable to access API with the CORS issues.
<img width="588" alt="screen shot 2018-03-29 at 12 28 28 pm" src="https://user-images.githubusercontent.com/3424539/38074659-1cca3d4e-334d-11e8-9e89-df626c59366a.png">

<img width="644" alt="screen shot 2018-03-29 at 12 28 41 pm" src="https://user-images.githubusercontent.com/3424539/38074669-23f57714-334d-11e8-8b17-ffdf624aaccc.png">

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 Alpha
