### ISSUE TITLE
Key and Secret need to change base on the application for production/sandbox

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3136]
**Description:**

Key and Secret need to change base on the application for production/sandbox.

![image](https://user-images.githubusercontent.com/3424539/38079907-b5ab1fd2-335d-11e8-8f7d-5ab898309a42.png)

<img width="644" alt="screen shot 2018-03-29 at 12 28 41 pm" src="https://user-images.githubusercontent.com/3424539/38079897-ac1b55a4-335d-11e8-8083-089cac7bfd7d.png">

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 Alpha
