### ISSUE TITLE
Error while activating ConsentManagerComponent

### ISSUE THREAD

**Issue by ThiagoMenezesAbreu** [wso2/product-apim#3140]
When starting wso2-apim 2.2.0 with -Dsetup to populate an empty database for a new install I get this FIleNotFoundExeception:

[2018-03-29 09:50:27,659] ERROR - ConsentManagerComponent Error while activating ConsentManagerComponent.
org.wso2.carbon.consent.mgt.core.exception.ConsentManagementRuntimeException: Could not find the database script at /wso2am-2.2.0/dbscripts/consent/mysql.sql.

APIM 2.2.0
MariaDB 5.5

**Comment by andybarber** [comment]
I encountered the same with initial startup against an empty Oracle DB.  The error did not reoccur when running again with -Dsetup, and looking at the DB there are several CM_ tables created.  They are part of the regular apimgt SQLs and not setup as separate scripts.  A cosmetic bug.

**Comment by tgtshanika** [comment]
-Dsetup option is deprecated from APIM 2.2.0 onwards. Please refer [1] for more information regarding this. 

> the proper practice is for the DBA to run the DDL statements manually so that the DBA can examine and optimize any DDL statement (if necessary) based on the DBA best practices that are in place within the organization.

[1] https://docs.wso2.com/display/AM220/About+this+Release
