### ISSUE TITLE
[UX] Add policy pages primary button should be "Add Policy"

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3152]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and Standards -Is flow maintain the same patterns and consistency

***Related task:***
Add advanced/application-level/subscription-level policy 

***Issue & solution:***
Add advanced/application-level/subscription-level policy page main action should be "Add Policy" instead of "Save"
	
**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
