### ISSUE TITLE
APIM 2.1.0 To 2.2.0 migration

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#3160]
When following the steps on[1] to migrate the database as on step6  the below error is thrown
[1] https://docs.wso2.com/display/AM220/Upgrading+from+the+Previous+Release

precondition
1.The APIM2.2.0 pack is not started
2.Data was populated using the APIM2.1.0 Setup
error
```
Msg 5074, Level 16, State 1, Line 1
The object 'PK__AM_SUBSC__96AC7A74A43EAA60' is dependent on column 'ACCESS_TOKEN'.
Msg 4922, Level 16, State 9, Line 1
ALTER TABLE ALTER COLUMN ACCESS_TOKEN failed because one or more objects access this column.
```

Note: ideally the migration script on step 6 of doc[1] should handle the dropping of the index refereed via the error

**Comment by shavantha** [comment]
Doc Impact :N/A

**Comment by tgtshanika** [comment]
This is fixed in the latest migration client.
