### ISSUE TITLE
Encrypted data migration to new self-contained ciphertext 

### ISSUE THREAD

**Issue by prasa7** [wso2/product-apim#3168]
Migrate persisted (in DB/Filesystem/Registry) RSA encrypted data to self-contained ciphertext

    Datasource configuration
    Syslog password
    Userstore configurations
    Key Store registry entries
    Subscriber registry entries
    Service security policies
    Event publishers configurations

**Comment by tgtshanika** [comment]
Fixed in APIM 2.2.0 onwards.
