### ISSUE TITLE
Footer incorrect in 2.2.0 pack

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3175]
**Description:**

- The footer in the APIM 2.2.0 Store states "WSO2 API Manager 2.1.0 | © 2018  Inc.". This should be corrected as "WSO2 API Manager 2.2.0 | © 2018  Inc."

- The footer in the APIM 2.2.0 Publisher states the following. When fixing the above issue please update the following if needed so that both have the same standard format
"WSO2 API Manager | © 2018  Inc."

**Suggested Labels:**
2.2.0, UX

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
![store](https://user-images.githubusercontent.com/5195851/38360908-41e6ecb6-38e9-11e8-978e-ab8eef5a1979.png)
![publisher](https://user-images.githubusercontent.com/5195851/38360946-62af6e50-38e9-11e8-9456-1f656fda5c1c.png)

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/5318
