### ISSUE TITLE
Update doc links in UI

### ISSUE THREAD

**Issue by taniamahanama** [wso2/product-apim#3177]
**Description:**
Update the doc links referred from the UI to 2.2.0 docs

**Suggested Labels:**
2.2.0, Type/Bug, Type/UX

**Suggested Assignees:**
-
**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Log in to API Publisher before configuring Analytics and click on one of the Analytics options. The doc link leads to 2.1.0 docs.
![analytics-link-in-publisher](https://user-images.githubusercontent.com/16956230/38405088-b063f90c-398b-11e8-9b73-432add85bb70.png)
2. Log in to API Store before configuring Analytics and click on one of the Analytics options. The doc link leads to 2.1.0 docs.
![analytics-link-in-store](https://user-images.githubusercontent.com/16956230/38405098-b9cd93e0-398b-11e8-8649-a114717dd1f3.png)
3. In the API Publisher, choose to edit an API and click the **Manage** tab. Under the **Advanced Throttling Policies** section, there's a doc link for throttling. This leads to the 2.1.0 docs.
![throttling-link-in-publisher](https://user-images.githubusercontent.com/16956230/38405104-c1104e40-398b-11e8-9502-ed4a6ca038a5.png)
**Related Issues:**
N/A

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/5318
