### ISSUE TITLE
Minor UI fix in API Publisher/Implement tab

### ISSUE THREAD

**Issue by taniamahanama** [wso2/product-apim#3178]
**Description:**
The help icon next to the Production endpoint label is not on the same line.

**Suggested Labels:**

2.2.0, Type/UX

**Suggested Assignees:**
N/A

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
Log in to the API Publisher, choose to edit an API and click the **Implement** tab. It would be nice to move the help icon (question mark) of the Production endpoint field to the same line as the field name, similar to the Sandbox endpoint label.
![implement-tab-production](https://user-images.githubusercontent.com/16956230/38405338-fa70aae4-398c-11e8-8c97-5bd0fc304f30.png)

**Related Issues:**
N/A

**Comment by chanaka3d** [comment]
Fixed with 3.x and 2.6
