### ISSUE TITLE
Minor update to UI help text 

### ISSUE THREAD

**Issue by taniamahanama** [wso2/product-apim#3179]
**Description:**
Update the help text for API Properties in the **Manage** tab.

**Suggested Labels:**
2.2.0, Type/UX

**Suggested Assignees:**
-

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Log in to the API Publisher, choose to edit an API and click the **Manage** tab. Expand the **API Properties** section. 

Suggestion is to change the help text to something similar to the following:
The property name must not contain any white spaces and must not use any of the following reserved keywords: name, description, provider, version, context, doc, tags, Icstate, status, subcontext.

Also, it would be nice to update the prompt text to have the first letter in title case, i.e. Property name and Property value.
![manage-tab-api-properties](https://user-images.githubusercontent.com/16956230/38406274-dce81552-3991-11e8-8169-96bf28dbc97b.png)

**Related Issues:**
N/A

**Comment by chanaka3d** [comment]
This is fixed with the 3.x.
