### ISSUE TITLE
Upgrade dependencies in AM 3.0 

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#3189]
**Description:**
Upgrade following dependencies to latest versions

nimbus-jose-jwt_2.26.1.wso2v2.jar -> nimbus-jose-jwt_5.4.0.wso2v1
javax.ws.rs-api_2.0.0.jar -> javax.ws.rs-api-2.1
com.fasterxml.jackson.core.jackson-databind_2.8.9.jar -> jackson-databind-2.9.4.jar

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
The aforementioned dependencies have been upgraded to following versions.
nimbus-jose-jwt -> 7.3.0.wso2v1
javax.ws.rs-api -> 2.1.1
com.fasterxml.jackson.core.jackson-databind -> 2.9.9
