### ISSUE TITLE
Unable to add APIS with multple scopes in swagger after running the migration script

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#3201]
**Description:**
Unable to add APIS with multple scopes in swagger after running the migration script

**Suggested Labels:**
Migration

**Preconditions:**
Delete any duplicate records  added to the IDN_OAUTH2_SCOPE 
The migration script for mssql for IS-migration 5.4.0 step2 should NOT be applied
The Payment AP Should NOT be created

**Affected Product Version:**
1.APIM 2.2.0
2.ISKM 5.3.0

**OS, DB, other environment details and versions:**    
MSSQL DB

**Steps to reproduce:**
1.Download the migration script available in step 3 in [1]
[1]https://docs.wso2.com/display/IS540/Upgrading+from+a+Previous+Release

2.Extract the wso2is-5.4.0-migration.zip and get the mssql.sql file available in the path /is-migration/is-migration/migration-resources/5.4.0/dbscripts/step2/

3.Run the migration script

4.Deploy an API with multiple scopes in the swagger.json

Note: The API deployment fails.

**Related Issues:**
https://github.com/wso2/product-apim/issues/3190

**Comment by shavantha** [comment]
Doc Impact :N/A

**Comment by tgtshanika** [comment]
This is fixed in APIM 2.6.0
