### ISSUE TITLE
Updating application disables the implicit and code grant types

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#3208]
**Description:**
 while updating application in store UI by default below grant types are getting disabled, which are enabled after creating an application
- Implicit
- code

**Suggested Labels:**
APIM-2.1.0
**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Below are the steps performed 
1)After creating application enabled below two grant types and callback URL is updated 
Grant: implicit, code
2)Next Editing the application without touching any field and just clicked on update 
3)After updating the application the particular grant types are getting disabled by default

**Comment by pubudu538** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/5335
