### ISSUE TITLE
Make token length configurable

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#3211]
**Description:**
Make access and refresh token length configurable

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nuwand** [comment]
Why is a feature required to make the token length configurable? And how do we guarantee length and uniqueness?

**Comment by ruks** [comment]
Issue is not valid and closed.
