### ISSUE TITLE
Application group name length validation do not required

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#3213]
**Description:**
Currently, application group name has 30 length restrictions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
SImilar issue : https://github.com/wso2/product-apim/issues/3176
