### ISSUE TITLE
"ERROR - UserAwareAPIConsumer Failed to get API" was observed when viewing subscriptions of the application when subscription sharing feature is enabled.

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-apim#3245]
**Description:**
When using application sharing feature, there is a scenario that an user has permission to view an application. He logs in to store and try to view that Application details. When he tries to view the details, all the API details that Application is subscribed with are loaded too. But when he doesn't have permission to View some of the APIs, which that Application is subscribed to, user gets an error alert window as attached.

**Suggested Labels:**
2.1.0, Type/Bug, Severity/Major
[error-log.txt](https://github.com/wso2/product-apim/files/1939072/error-log.txt)

[](url)
**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
OS : Mac OS high sierra

**Steps to reproduce:**

1. Enabled application sharing feature.
2. Created 2 users given the same organization (through the carbon console)
3. Assigned role1 for one of the users
4. Created an API restricting visibility for role1 only.
5. In the store created an application and subscribed to that API using user who has role1 assigned.
6. logged into store using other user and view subscription tab of the shared application

Error log is attached.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5744
