### ISSUE TITLE
Need to make Store REST API errors customizable 

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3252]
**Description:**
When extension points in WSO2 API Manager are used, there are situations where error response codes and error messages are required to be customized depending on the error thrown in the custom extension implementation. 

This can be done by extending the GlobalThrowableMapper class when using the REST API.

When using the Store REST API, when Internal server errors are encountered, we need to have a proper way to backtrack the original exception/error thrown. 

In the current implementation, a **generic** Internal server error is passed to the GlobalThrowableMapper level when such exceptions are thrown. This makes it impossible to track the original exception from the extended GlobalThrowableMapper.

**Requirements :** 
1. We should have a mechanism to pass the original error message to the GlobalThrowableMapper level.
2. All exceptions extending the WebApplicationException class does not go through the GlobalThrowableMapper when handling errors. Ex: MethodNotAllowedException, InternalServerErrorException etc. Hence if an Exception is required to be caught by the GlobalThrowableMapper, it shouldn't extend WebApplicationException. Unless we will need to specifically configure the selection order of the ExceptionMappers through a property in beans.xml.

**Affected Product Version:**
APIM 2.1.0

**Comment by kavishkafernando** [comment]
Closing this issue since this has been improved in latest versions of APIM.
