### ISSUE TITLE
java.lang.NumberFormatException is thrown when an api is invoked with a non existent API resource path

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#3256]
**Description:**
java.lang.NumberFormatException is thrown when an api is invoked with a non existent API resource path

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Please refer [APIMANAGER-5017](https://wso2.org/jira/browse/APIMANAGER-5017)

**Related Issues:**
 [APIMANAGER-5017](https://wso2.org/jira/browse/APIMANAGER-5017)

**Comment by ruks** [comment]
Cannot reproduce with latest release APIM 2.2.0
