### ISSUE TITLE
Change script mediator engine to nashornJs for prototyped APIs

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#3259]
**Description:**
API Manager 2.2.0 supports nashornJs as the script mediator engine but since it is not configured in prototyped API's velocity file prototyped APIs created from Publisher are still getting configured with old script mediator engine (Mozilla).

It is better if we can provide an option in the UI for users to select the script mediator engine type when defining inline scripts in implement tab for Prototyped APIs.

**Affected Product Version:**
API Manager 2.2.0

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still need this requirement.
