### ISSUE TITLE
[Doc] Correct directory path for enabling WSO2 Log Analyzer 

### ISSUE THREAD

**Issue by prabushi** [wso2/product-apim#3264]
**Description:**
Following directory paths to copy portal.zip and shinding.war should be corrected at [1].

1. repository/deployment/jaggeryapps --> repository/deployment/server/jaggeryapps

2. repository/deployment/webapps --> repository/deployment/server/webapps

[1] - https://docs.wso2.com/display/AM220/Configuring+APIM+Analytics#0f877ff3ccda4dd5b15155483255b108

**Suggested Labels:**
Documentation

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This feature has been deprecated from APIM 2.5.0. Hence resolving.
