### ISSUE TITLE
roles with spaces and any cases should support for scopes

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#3273]
**Description:**
Roles name should be case insensitive and should support space when scope valiate

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prasa7** [comment]
Mater PR
Fixed the master fixes with the following PR's

https://github.com/wso2/carbon-identity-framework/pull/3953
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1812
