### ISSUE TITLE
Supporting the JWT token generation for the federated users who grant access token from the KM

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-apim#3281]
Federated user's attributes are stored in the session table w.r.t to the access token. Therefore they can be used to generate the JWT by default.

**Comment by isurulucky** [comment]
Need to write a new JWT generator, which should be called if there are no claims found for the current user in the primary user store, using super.populateCustomClaims(validationContext):

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.wso2.carbon.apimgt.api.APIManagementException;
import org.wso2.carbon.apimgt.keymgt.service.TokenValidationContext;
import org.wso2.carbon.apimgt.keymgt.token.JWTGenerator;
import org.wso2.carbon.identity.application.common.model.ClaimMapping;
import org.wso2.carbon.identity.oauth.cache.AuthorizationGrantCache;
import org.wso2.carbon.identity.oauth.cache.AuthorizationGrantCacheEntry;
import org.wso2.carbon.identity.oauth.cache.AuthorizationGrantCacheKey;
import org.wso2.carbon.utils.multitenancy.MultitenantUtils;

import java.util.Map;
import java.util.TreeMap;

/**
 * Retrieve claims from session store
 */
public class FederatedUserJWTGenerator extends JWTGenerator {

    private static final Log log = LogFactory.getLog(FederatedUserJWTGenerator.class);


    @Override
    public Map<String, String> populateCustomClaims(TokenValidationContext validationContext) throws APIManagementException {

        Map<String, String> claimValues = new TreeMap<String, String>();

        AuthorizationGrantCacheKey key = new AuthorizationGrantCacheKey(validationContext.getAccessToken());
        AuthorizationGrantCacheEntry entry = AuthorizationGrantCache.getInstance().getValueFromCacheByToken(key);

        if(entry != null){
            Map<ClaimMapping, String> attributes = entry.getUserAttributes();
            for(Map.Entry<ClaimMapping, String> mapEntry : attributes.entrySet()) {
                claimValues.put(mapEntry.getKey().getLocalClaim().getClaimUri(), mapEntry.getValue());
            }
        }

        if(claimValues.isEmpty()) {
	    // log a warning that no claims are found for the user
        }

        claimValues.put("sub", MultitenantUtils.getTenantAwareUsername(validationContext.getTokenInfo().getEndUserName()));

        return claimValues;
    }
}

**Comment by tgtshanika** [comment]
This is fixed with https://github.com/wso2/carbon-apimgt/pull/5906
