### ISSUE TITLE
UI issue in Add Application page in Store

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#3294]
**Description:**
In adding applications page in Store in APIM 2.1.0, the wordings in the UI "**Per Token Quota**" is incorrect and misleading. 

The application quota is per end-user, meaning that two different application tokens will share the allocated quota for that application. Thus the wordings should be corrected.

![screenshot from 2018-05-28 18-47-42](https://user-images.githubusercontent.com/8363838/40616172-a75a8b2e-62a7-11e8-9114-0a83e5d2c6bd.png)

**Comment by chanaka3d** [comment]
<img width="644" alt="Screen Shot 2020-10-05 at 5 26 43 PM" src="https://user-images.githubusercontent.com/3424539/95076819-178eef00-0730-11eb-9581-227b8820c417.png">
