### ISSUE TITLE
Add swagger validation before saving the API

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#3296]
**Description:**
API Manager allows to save swagger file with syntax errors. For example, if we remove the HTTP method in the swagger file using the in-built swagger editor, we could save the API without resources.  

Refer image
<img width="1323" alt="screen shot 2018-05-29 at 4 46 26 pm" src="https://user-images.githubusercontent.com/4861150/40655731-e90a0d8e-635f-11e8-89eb-97260e92508a.png">

Publishing the API (with errors) is possible after that. Add a validation to the swagger  definition before continuing the flow

**Affected Product Version:**
APIM 2.1.0

**Comment by rajeshrai248** [comment]
does this feature also supports custom validations?
