### ISSUE TITLE
Leading and trailing spaces of API endpoint URLs are not trimmed

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#3299]
**Description:**
When we create and publish an API with an endpoint with a leading whitespace character, using publisher REST APIs, the leading space is not trimmed. And it is persisted into the published API synapse file as it is. This is validated only in WSO2 APIM Publisher UI level so if we try to publish API with Publisher, this issue is not visible. Leading/trailing white spaces are trimmed in that case. 

It would be better to do this validation at REST API level itself. And check for other required String validations too.

**Affected Product Version:**
2.1.0

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
