### ISSUE TITLE
Uncaught TypeError: Cannot read property 'msie' of undefined in APIM Store UI

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3300]
**Description:**
The following error is shown in the APIM Store, Chrome developer console when accessing the Overview tab of an API.

_Uncaught TypeError: Cannot read property 'msie' of undefined
at jquery.ba-bbq.min.js:1
at jquery.ba-bbq.min.js:1_

![image](https://user-images.githubusercontent.com/8557410/40712327-07f630f4-641b-11e8-9f9d-0605b250b3e8.png)

The reason being the JQuery version. 

This issue happens due to the $.browser method being removed as of jQuery 1.9. We use JQuery 1.11.

This can be resolved by using the JQuery Migrate Plugin [1]. There are other workarounds as well.

[1] https://github.com/jquery/jquery-migrate/

**Affected Product Version:**
APIM 2.1.0 

**Steps to reproduce:**

Pre-requisite: There should be a published API in Store.

1. Go to APIM Store UI from **Chrome** browser.
2. Login and access the **overview** tab of the API.
3. Check the Chrome Developer console by right-click -> Inspect

**Related Issues:**
https://github.com/wso2/product-apim/issues/3301
https://github.com/wso2/product-apim/issues/3302

**Comment by tgtshanika** [comment]
Cannot reproduce with APIM 3.0.0 milestone 35.
