### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined in APIM Store UI

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3301]
**Description:**
The following error is shown in the APIM Store, Chrome developer console when accessing the Overview tab of an API. This is intermittent, but more frequent.

![image](https://user-images.githubusercontent.com/8557410/40713768-685bb614-641e-11e8-85fb-d0dbe7c9af73.png)

**Affected Product Version:**
APIM 2.1.0

**Steps to reproduce:**

Pre-requisite: There should be a published API in Store.

1. Go to APIM Store UI from Chrome browser.
2. Login and access the overview tab of the API.
3. Check the Chrome Developer console by right-click -> Inspect

**Related Issues:**
https://github.com/wso2/product-apim/issues/3300
https://github.com/wso2/product-apim/issues/3302

**Comment by tgtshanika** [comment]
Cannot reproduce with APIM 3.0.0 milestone 35
