### ISSUE TITLE
Roboto font resources not found in APIM Store UI

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#3302]
**Description:**
The following error is shown in the APIM Store, Chrome developer console / network tab when accessing the Overview / API Console tab of an API.

![image](https://user-images.githubusercontent.com/8557410/40714123-5c25c370-641f-11e8-849f-a3585263fd82.png)

The issue here is that all the relevant files in <APIM_HOME>/repository/deployment/server/jaggeryapps/store/site/themes/wso2/libs/theme-wso2_1.0/fonts/Roboto should be changed to the form referenced in the css files. 

This should be changed in the code base where the Roboto library files are included in carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs/theme-wso2_1.0/fonts/Roboto

For example

Roboto-Light-Italic.woff2 should be changed to Roboto-LightItalic.woff2 removing the last hyphen.

**Affected Product Version:**
APIM 2.1.0    

**Steps to reproduce:**

Pre-requisite: There should be a published API in Store.

1. Go to APIM Store UI from Chrome browser.
2. Login and access the overview tab / API Console tab of the API.
3. Check the Chrome Developer console or network tab by right-click -> Inspect

**Related Issues:**
https://github.com/wso2/product-apim/issues/3300
https://github.com/wso2/product-apim/issues/3301

**Comment by tgtshanika** [comment]
Cannot reproduce with APIM 3.0.0 milestone 35.
