### ISSUE TITLE
[UX][Publisher] Couldn't find a way to edit version after creating an API

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3308]
**Description:**
> There should be an option to change version from the UI if user accidentally add a wrong version number. And if the API is already published we can inform that to the user and drive user to the create new version page and ask user to create a new version and deprecate the old version. 

**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**Comment by kavishkafernando** [comment]
We do not support editing the API version. The version along with the context is used as a unique identifier for the API. Once the API has been published the version cannot be changed.
