### ISSUE TITLE
[UX][Publisher] List un-published API versions in the versions tab

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3310]
**Description:**
> When user navigates to API details page and navigates to versions tab, currently its only list down the published APIs. We should list down the unpublished ones also there with a label that indicates the status of it (published/created/deprecated etc ...)

**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**Comment by tgtshanika** [comment]
The purpose of having the 'Versions' tab is to summarize and display active API subscriptions created under each version of the API. The APIs which are not published cannot have subscriptions, hence it does not make sense to list down unpublished APIs in 'API Subscriptions by Versions' tab.
