### ISSUE TITLE
View Publisher Store button does not redirect to the publisher's store

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3319]
**Description:**
When publishing to multiple external API Stores, the "View Publisher Store" button does not work as mentioned in the documentation [1].

[1] https://docs.wso2.com/display/AM220/Publish+to+Multiple+External+API+Stores

**Suggested Labels:**
API-M 2.2.0

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Access http://localhost:9764/store/
2. Click Sign in and sign in using admin/admin credentials. You get redirected to https://192.168.8.100:9444/store/?tenant=carbon.super
3. Click "View Publisher Store". It takes your to the following address. http://localhost:9764/store/apis/info?name=PhoneVerification&version=1.0.0&provider=admin&tenant=carbon.super
4. Where as according to the documentation, the user should be redirected to http://localhost:9763/store

![visit-publisher-store](https://user-images.githubusercontent.com/5195851/40833777-7d369222-65ac-11e8-8f1f-c290776b738f.png)

**Related Issues:**
N/A

**Comment by Mariangela** [comment]
@isharac Attached herewith is the /_system/governance/apimgt/externalstores/external-api-stores.xml file of the first instance.

[external-api-stores.xml.zip](https://github.com/wso2/product-apim/files/2145161/external-api-stores.xml.zip)

**Comment by isharac** [comment]
@Mari,
SroreURL port should be 9763 which is the publisher's store in
<StoreURL>http://localhost:9764/store</StoreURL>

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7036 in APIM 3.0
