### ISSUE TITLE
[UX][Publisher] Guiding information missing for API Migration

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3320]
**Description:**
> IMO there should be a way that we guide users from the API publisher app itself for "Migrate API environment" documentation. Because user who starts evaluating API manager from the app will loose this feature. And will not know until find it through googling or read the documentation separately.
> 
> May be we can have a top level help link and navigate to these sort of information as regular applications does.

**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**Comment by dushaniw** [comment]
Pointing to documentation from the Publisher portal on using "API Controller to migrate APIs to a different environment" could be misleading, as the users in the current publisher portal do not directly involve with CI/CD tasks.
