### ISSUE TITLE
[UX][Publisher] Guiding information missing for API version update notification

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3321]
**Description:**
> IMO in the publisher app UI we should have an action for "Notify Subscribers" on product version update in somewhere with the information saying that user needs to configure it, in order to get it activated. 
>
> And from there we can guide user to the documentation.

**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**Comment by dushaniw** [comment]
This is available now with 3.1.0 and 3.2.0. Providing product version update notification in publisher portal is wrong. The product update is handled by system admins etc. hence, now when starting the server, similar log to following is getting printed.

```
[2020-11-27 16:16:02,744]  INFO - CallHomeExecutor 
..............................................................................
There are 129 updates available for the product 'wso2am-3.2.0'.[WARNING] There
are 10 critical security updates for the product 'wso2am-3.2.0'. WSO2 strongly
recommends to apply these updates in production as soon as possible.
```
