### ISSUE TITLE
[UX][Publisher] Lifecycle Management action buttons should have clear separation

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3322]
**Description:**
> Currently all the action buttons shows as "Primary". We need to clearly differentiate Primary and Secondary actions here.
>
> ![image](https://user-images.githubusercontent.com/7569427/40836101-2b902288-65b3-11e8-88df-b2c20c98cc52.png)
 
**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**Steps to reproduce:**
> Navigate to API details page and click on the Lifecycle tab

**Comment by kavishkafernando** [comment]
This has been fixed in latest 3.x products.
