### ISSUE TITLE
APIM 2.5.0 Label Add feature 

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#3323]
**Description:**
API Manager need to allows adding labels to the APIs in create/update phases from the publisher, so that labels help to grouping APIs into API manager gateway.
If the user requests the particular label, then it provides the set of APIs that deploy in the same gateway.
Labels should be defined by the admin(Super/Tenant) using admin dashboard.

**Suggested Labels:**
APIM 2.5.0

**Comment by dinusha92** [comment]
Closing the issue as it is been fixed with above referenced commit.
