### ISSUE TITLE
REST API to Fetch API Details to APIM-Gateway

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#3325]
**Description:**
Need REST API to fetch API details to APIM gateway from the publisher. Fetching of APIs is based on labels, i.e certain set of APIs can be grouped into a certain gateway instance by a label. 

**Suggested Labels:**
APIM 2.5.0

**Comment by dinusha92** [comment]
Closing the issue as this as been fixed with above referenced commit.
