### ISSUE TITLE
Performance Issue when default H2 DB is moved to mysql

### ISSUE THREAD

**Issue by xxCoDeBoX** [wso2/product-apim#3338]
The DB is moved from H2 (wso2 default) to mysql and it seems like there is a major drop in performance.
All the API calls made from UI takes a lot of time and response time is high when compared to data stored in wso2 default DB (h2) .
 
Mysql Instance is running on aws with :
8gb RAM.
50gb mem.

WSo2 is hosted on aws with:
4gb RAM.
60gb mem.

Can someone please help me with this . 

Thanks in advance

**Comment by tgtshanika** [comment]
Hi,
The default H2 database is embedded within the APIM server itself and the connections to the database are established locally. Hence, network latency is considerably low. But when the database has been pointed to an external mysql server, the performance is affected by connection status from APIM server to mysql database server. If there is high network latency, when establishing the connection with the database, the performance can be degraded. Thus, please check the connection status from APIM server to the database server and fix the latency issues.
