### ISSUE TITLE
Unable to Add Certs vis REST APIs.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#3339]
**Description:**

Using the Dynamic SSL Certificate Installation feature we can add certs via publisher UI and Jaggery APIs
but the same is not facilitated via REST APIs. 
We need to facilitate them via REST APIs as an Improvement.

https://docs.wso2.com/display/AM220/Dynamic+SSL+Certificate+Installation

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**
All.

**Comment by tgtshanika** [comment]
This is fixed with https://github.com/wso2/carbon-apimgt/pull/5615
