### ISSUE TITLE
[Store] Average rating star disappears when removing rating 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3344]
**Description:**
When user clicks on remove rating button in API Overview and forum pages, the average rating star disappears 
![remove-star](https://user-images.githubusercontent.com/9837443/41025406-634dfa1c-698f-11e8-9884-3f68bf0064d9.png)

![rate-remove2](https://user-images.githubusercontent.com/9837443/41030190-5e429a1c-699b-11e8-86e1-7ffcf6705572.png)

**Suggested Labels:**
UX

**Affected Product Version:**
2.2.0

**Comment by kavishkafernando** [comment]
This issue has been fixed in latest releases of APIM.
