### ISSUE TITLE
[Store] "Your Rating" section is shown in forum topics before user sign in

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3346]
**Description:**
Your Rating section is shown and user can click on ratings in forum topics before user sign in. This section should be hidden before sign in.

![rating-without-login](https://user-images.githubusercontent.com/9837443/41030729-9136483c-699c-11e8-8977-70f440ff674d.png)

**Suggested Labels:**
UX

**Affected Product Version:**
2.2.0

**Comment by kavishkafernando** [comment]
This has been fixed.

<img width="1674" alt="Screen Shot 2020-11-27 at 3 17 53 PM" src="https://user-images.githubusercontent.com/19324135/100435410-e72a5800-30c3-11eb-891e-e3ef07f95f10.png">
