### ISSUE TITLE
Improvment to define group extractor claim

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3355]
**Description:**
This is an improvement to the existing DefaultGroupExtractor to be able to configure the user claim from a configuration file rather than the hard-coded organization claim URI.

To enable this add the following configuration under <APIStore> tag in `<APIM_HOME>/repository/conf/api-manager.xml file`

```xml
<DefaultGroupExtractorClaimUri>http://wso2.org/claims/role</DefaultGroupExtractorClaimUri>
```
Affected DOCs: [Sharing Applications Between Multiple Groups](https://docs.wso2.com/display/AM210/Sharing+Applications+Between+Multiple+Groups#SharingApplicationsBetweenMultipleGroups-ExtendingthegroupIDextractor) and onwards

Note: The fix was given in WSO2-CARBON-PATCH-4.4.0-2810 as WUM Update

**Comment by Mariangela** [comment]
@tmkasun , here is the draft page [1] that I did with this WUM update. Please let me know whether any further changes are needed before I add these changes into the live docs. [1] https://docs.wso2.com/display/AM210/Copy+of+Sharing+Applications+Between+Multiple+Groups#CopyofSharingApplicationsBetweenMultipleGroups-Definingacustomuserclaimasthegroupextractorclaim

**Comment by Mariangela** [comment]
Based on the following WUM updates [4], I updated the APIM 2.1.0 [1], 2.2.0 [2] and 2.5.0 [3] docs with details on this new feature.

[4]
WSO2-CARBON-PATCH-4.4.0-2810 | API Manager 2.1.0 | kasunte@wso2.com | 06/12/2018 | 
WSO2-CARBON-PATCH-4.4.0-3665 | API Manager 2.2.0 | tharika@wso2.com | 12/09/2018 | 
WSO2-CARBON-PATCH-4.4.0-3792 | API Manager 2.5.0 | dushans@wso2.com | 01/08/2019 | 

[1] https://docs.wso2.com/display/AM210/Sharing+Applications+Between+Multiple+Groups#SharingApplicationsBetweenMultipleGroups-Definingacustomuserclaimasthegroupextractorclaim
[2] https://docs.wso2.com/display/AM220/Sharing+Applications#SharingApplications-Definingacustomuserclaimasthegroupextractorclaim
[3] https://docs.wso2.com/display/AM250/Sharing+Applications#SharingApplications-Definingacustomuserclaimasthegroupextractorclaim

**Comment by Mariangela** [comment]
This information was added in APIM 2.6.0 based on the fix done in https://github.com/wso2-support/carbon-apimgt/pull/1420

[1] https://docs.wso2.com/display/AM260/Sharing+Applications#SharingApplications-Definingacustomuserclaimasthegroupextractorclaim
