### ISSUE TITLE
[Store] Application Generate keys button doesn't generate keys in one click

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3357]
**Description:**

* When given a `Callback URL` Generate keys button does not generate the keys in a single click
* In the first click it auto check the disabled `Implicit` & `Code` checkboxes
* User has to click again on `Generate keys` button to generate keys for Application

**Affected Product Version:**

* wso2am-2.5.0-Beta

**OS, DB, other environment details and versions:**    
Browser:
```

Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
-- | --
Revision | dc3469be277cc962ba01d9c0cb5bb1a265676c36-refs/branch-heads/3325@{#725}
OS | Linux
JavaScript | V8 6.5.254.41

```

**Steps to reproduce:**

* Login to store and create an Application
* Goto either Production or Sandbox tabs
* Give a `Callback URL` and click on `Generate keys`
* You will need to click twice to generate keys

![key_gen_issue](https://user-images.githubusercontent.com/3313885/41140731-acc4c6ac-6b0c-11e8-8b5a-b6c84837b63e.gif)

**Comment by chanaka3d** [comment]
These UX issues are addressed with the 3.x product.
