### ISSUE TITLE
Improvements for Removing Unused Oauth2 Tokens from the AM Database

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-apim#3358]
**Description:**
We are currently removing unused Oauth2 tokens from the AM database using a script [1].
In this script for removing the unused tokens form the database we only delete token entries which have expired/inactive or revoked tokens keeping the latest entry for each combination of consumerKey + user + scopes. The reason for keeping the latest combination is to use refresh grant. 

This improvement is to remove any existing invalidated token entries at the time of new token generation from the code level. This way, there wouldn't be a need to have a separate removal script. If the operation could be expensive for use cases with high token generation frequency, it can be provided as a switchable feature. This can be improved to remove tokens which have expired refresh tokens as well.

[1][https://docs.wso2.com/display/AM200/Removing+Unused+Tokens+from+the+Database#57d4816ce2d2427eb93f2bc3a2b2b074](url)

**Affected Product Version:**
APIM2.0.0

**Comment by tgtshanika** [comment]
This has been fixed in APIM 2.6.0 [1]

[1] https://docs.wso2.com/display/AM260/Removing+Unused+Tokens+from+the+Database
