### ISSUE TITLE
[UX][Publisher] Users tend to miss add parameter section after adding API resources

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3368]
**Description:**
After adding API resources users are unable to identify the section to add parameters though UI.  
Need to have a link/indication on the resource to expand the parameter section. 

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.0.0

**Comment by kavishkafernando** [comment]
This has been fixed in latest versions of APIM by facilitating users to add parameters by expanding the resource.
