### ISSUE TITLE
[UX][Publisher] Users are unable to edit API name, version, context after completing design phase

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3369]
**Description:**
Users are unable to edit API name, version, context after completing the design phase

**Suggested Labels:**
UX Bug

**Affected Product Version:**
2.2.0

**Comment by chamindias** [comment]
This is the expected behavior.
Reason : When you complete the "Design" stage and goto the next step, the artifact will be created. (with API name, version, context as attributes). Hence, user will not be allowed to update it after creation.

**Comment by chamindias** [comment]
Reopening this and adding label "3.0.0"

**Comment by tgtshanika** [comment]
This is the expected behavior. Hence resolving
