### ISSUE TITLE
[UX][Publisher] User should be able to edit resource path, parameter name after adding a resource and parameter

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3371]
**Description:**
User has to 
- delete and create a new resource if s/he wants to change the edit resource path. 
- delete and create a new parameter if s/he wants to change the edit parameters.

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by dushaniw** [comment]
Users can edit parameters with the latest released 3.2.0. Hence closing.
