### ISSUE TITLE
[UX][Publisher] Improvements in Implement API

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3373]
**Description:**
- Add URL validations to production, sandbox, prototype endpoint input fields

- Add a link to relevant ESB documention from the endpont error message
![endpoint](https://user-images.githubusercontent.com/9837443/41188959-7e2d74d2-6be4-11e8-8bd1-5ab48bc228af.png)

- Remove the endpoint results tags(invalid, valid etc) when endpoint input text change.

- Remove input validation message on keypress, otherwise the error message is will be there even input is given
![end-val](https://user-images.githubusercontent.com/9837443/41189120-542d0bbe-6be6-11e8-8627-047f9f5964c8.png)

**Suggested Labels:**
UX improvements

**Affected Product Version:**
2.2.0

**Comment by dushaniw** [comment]
Fixed with latest release 3.2.0. Hence closing.
