### ISSUE TITLE
[Doc] Add management console URL in Adding Users

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3375]
**Description:**
Add "Log in to the management console (https://<APIM_Host>:<APIM_Port>/admin) as admin (default credentials are admin/admin)" as the first point in [1] as users can get confused on finding management console URL. This is added on adding roles. 

[1] https://docs.wso2.com/display/AM220/Adding+Users

**Suggested Labels:**
Doc, Improvement

**Affected Product Version:**
2.2.0

**Comment by ruthryi** [comment]
Added the following in [1] and [2] 

> Log in to the Management Console (https://<hostname>:9443/carbon) and click Add under Users and Roles in the Main menu.

[1] https://docs.wso2.com/display/AM2xx/Adding+Users
[2] https://docs.wso2.com/display/AM220/Adding+Users
