### ISSUE TITLE
[Docs] Change jks path in billing engine war app datasource.properties to <AM_HOME>/repository/resources/security/wso2carbon.jks

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#3380]
**Description:**
In documentation [1], change the jks path configuration as "AM_HOME>/repository/resources/security/wso2carbon.jks". This should be applied to all the three documentations of 2.1.0, 2.2.0 and 2.5.0 versions.

Update the war file given to download in step 2 of [1] to the latest version of https://github.com/ruks/wso2-am-billing-engine/tree/am-2.2.0/apim-billing-engine. 

Also, give optional instructions to build the maven project https://github.com/ruks/wso2-am-billing-engine/tree/am-2.2.0/apim-billing-engine to get the war file.

[1] https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs#EnablingMonetizationofAPIs-Configuringthebillingengine

**Suggested Labels:**

**Suggested Assignees:**
@ruthryi 

**Affected Product Version:**
wso2am-2.5.0-Beta

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
Updated the following with the corresponding war files. Also, linked off to the source.

[1] https://docs.wso2.com/display/AM2xx/Enabling+Monetization+of+APIs
[2] https://docs.wso2.com/display/AM220/Enabling+Monetization+of+APIs
