### ISSUE TITLE
On Environment drop-down box does not appear

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3384]
**Description:**
The environments you define in the <API-M_HOME>/repository/conf/api-manager.xml file under the  <Environments> element is not visible in a drop-down list in the API Console tab of the API Store of instance 1 as mentioned in APIM 2.2.0 doc under step 7 [1].

The "On Environment" drop-down box does not appear when:
- When api-console="true" [2]
- When api-console="false" [3]
- When api-console element is not defined [4]

[1.] https://docs.wso2.com/display/AM210/Publish+through+Multiple+API+Gateways
[2]
{code}
<Environment type="production" api-console="true"> <Name>Production Gateway</Name> <Description>Production Gateway Environment</Description> <ServerURL>https://localhost:9444/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8281,https://localhost:8244</GatewayEndpoint> </Environment> <Environment type="sandbox" api-console="true"> <Name>Sandbox Gateway</Name> <Description>Sandbox Gateway Environment</Description> <ServerURL>https://localhost:9445/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8282,https://localhost:8245</GatewayEndpoint> </Environment>
{code}

[3]
{code}
<Environment type="production" api-console="false"> <Name>Production Gateway</Name> <Description>Production Gateway Environment</Description> <ServerURL>https://localhost:9444/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8281,https://localhost:8244</GatewayEndpoint> </Environment> <Environment type="sandbox" api-console="false"> <Name>Sandbox Gateway</Name> <Description>Sandbox Gateway Environment</Description> <ServerURL>https://localhost:9445/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8282,https://localhost:8245</GatewayEndpoint> </Environment>
{code}

[4]
{code}
<Environment type="production"> <Name>Production Gateway</Name> <Description>Production Gateway Environment</Description> <ServerURL>https://localhost:9444/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8281,https://localhost:8244</GatewayEndpoint> </Environment> <Environment type="sandbox"> <Name>Sandbox Gateway</Name> <Description>Sandbox Gateway Environment</Description> <ServerURL>https://localhost:9445/services/</ServerURL> <Username>admin</Username> <Password>admin</Password> <GatewayEndpoint>http://localhost:8282,https://localhost:8245</GatewayEndpoint> </Environment>
{code}

![screen shot 2018-06-11 at 6 31 33 pm](https://user-images.githubusercontent.com/5195851/41237164-821835be-6db0-11e8-90c2-76c023c8818a.png)

**Suggested Labels:**
2.2.0, 2.5.0, Bug

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@isharac, I am still facing this issue when testing API-M 2.5.0. Please refer [1] for more details. 

[1] https://wso2.org/jira/browse/DOCUMENTATION-8033

**Comment by Mariangela** [comment]
@tgtshanika troubleshooted this issue with me in API-M 2.5.0 and got it working. This was perceived as an error due to the missing information in the note of the tutorial which gives users the wrong impression and sets wrong expectation and also due to api-console="true" missing in the example code block.

**Comment by dushaniw** [comment]
Closing the issue as per above comment
