### ISSUE TITLE
Store UI issue when more than 100 tags are available

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-apim#3393]
**Description:**
Store UI left pane tiles get out of order if there are more than 100 tags available.

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Use attached Jmeter (4.0) script [admin.zip](https://github.com/wso2/product-apim/files/2096783/admin.zip) to generate 100 tags.
2. Use scroll bar appeared in the left pane.
3. Observe tiles getting out of order

![screenshot from 2018-06-13 11-27-02](https://user-images.githubusercontent.com/11774310/41332926-5387b028-6efd-11e8-8533-05019c111c78.png)

**Comment by jeradrutnam** [comment]
PR: https://github.com/wso2/carbon-apimgt/pull/5454

**Comment by tgtshanika** [comment]
Fixed
