### ISSUE TITLE
Improvement to JMS Performance in dual channel scenario - Producer level caching 

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3405]
**Description:**
Current JMS performance in dual channel scenario could be improved by introducing producer-level caching in axis-transport level. 

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
