### ISSUE TITLE
[Threat Protection] Regex patterns are too broad

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3406]
**Description:**
When the regex_policy is selected for the inflow of an API, And invoke it with a payload, header or query params containing the letters DROP, SELECT and ALTER, The request get fails with 400 HTTP Code.
Following is an example API payload and it's corresponding GW response.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<breakfast_menu>
    <food>
        <name>Homestyle Breakfast</name>
        <message>Alter my name</message>
        <description>
    Two eggs, bacon or sausage, toast, and our ever-popular hash browns
    </description>
        <calories>950</calories>
    </food>
</breakfast_menu>
```
```xml
<ns0:fault xmlns:ns0="http://wso2.org/apimanager">
    <ns0:code>400</ns0:code>
    <ns0:message>Bad Request</ns0:message>
    <ns0:description>SQL-Injection Threat detected in Payload</ns0:description>
</ns0:fault>
```
IMHO, it's not good to capture all the words and phrases containing above mentioned words.
This issue has caused by using any character matching surrounding [those words](https://github.com/wso2/product-apim/blob/2.x/modules/distribution/resources/customsequences/in/regex_policy.xml#L26)

**Affected Product Version:**

* APIM 2.5-Beta

**Steps to reproduce:**
* Create an API from the publisher
* In the implementation step, Enable the message mediation and select `regex_policy` for inflow
* Publish the API, and invoke it with following string in its Headers, Query Param or  Body
  * I got selected to College
* The request will fail with 400 Response code as given above

**Comment by hasuniea** [comment]
fixed from https://github.com/wso2/product-apim/pull/3474/

**Comment by tmkasun** [comment]
Closing the issue as this was fixed by https://github.com/wso2/product-apim/pull/3474 PR
