### ISSUE TITLE
The /token endpoint returns 500 with java.lang.NullPointerException after setup

### ISSUE THREAD

**Issue by marceloavan** [wso2/product-apim#3411]
**Description:**

On a new setup of WSO2 API product without any customization, just following section "Steps do reproduce", the `/token` endpoint returns an internal error with follow body:

```xml
<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat">
    <ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">java.lang.NullPointerException</ns1:faultstring>
</ns1:XMLFault>
```

After server restart, the endpoint works as expected, and for now, it is my workaround. The problem is that we have many automation tools to provision a setup with WSO2 and docker, and this bug requires some extra and unecessary work.

**Suggested Labels:**
- Bug
- 2.2.0

**Suggested Assignees:**

**Affected Product Version:**
product-apim bundle version 2.2.0 update4 (tested with update 7 also)

**OS, DB, other environment details and versions:**    
Tested on windows, linux and docker;

**Steps to reproduce:**
- Start server following documentation steps;
- Use `/client-registration/v0.12/register` endpoint to get client ID and secret;
- Calls `/token` and the error happens;
- Restart server and call `/token` again. It's works.

**Related Issues:**

**Comment by kavishkafernando** [comment]
Hopefully you were able to solve the issue. Please re-open the issue if it gets reproduced.
