### ISSUE TITLE
[API Publisher] [API Store] The error message displayed for incorrect Analytics profile configuration points to older doc page

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-apim#3435]
**Description:**
The message displayed when viewing API-M Statistics where the Analytics profile is properly configured points to an older doc page.

**Suggested Labels:**
TBD

**Suggested Assignees:**
@nuwand @sanjeewa-malalgoda 

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
TBD

**Steps to reproduce:**
1. Got the API-M 2.2.0 pack from [Atuwa](http://atuwa.private.wso2.com/WSO2-Products/api-manager/2.2.0/wso2am-2.2.0.zip) and started the profile.
2. Signed in to the API Publisher with admin credentials.
3. Created and published the sample API.
4. Signed in to the API Store with admin credentials.
5. Created an application and subscribed to the API with it.
6. Created application keys.
7. Invoked the API.
8. Accessed the reports at the API Store. The following error message gets displayed. The link in the error message points to a [2.1.0 doc page](https://docs.wso2.com/display/AM210/Configuring+APIM+Analytics).
![image](https://user-images.githubusercontent.com/9816314/41458213-9411d1d0-70a3-11e8-9f5e-62dac608b7f0.png)
The behaviour is same for API Publisher statistics. 
Please check. 

**Related Issues:**
TBD

**Comment by taniamahanama** [comment]
This was already fixed as part of 2.2.0-update 1. See https://github.com/wso2/product-apim/issues/3177.
