### ISSUE TITLE
[Threat Protection] Resource naming limitation

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3437]
**Description:**
* When the regex_policy inflow mediation is selected for an API, Users can't create resources with its name containing  `DROP`, `SELECT` or `ALTER` in any case.

sample request and response
 
```xml
GET /sample/1.1.1/dropPayments HTTP/1.1
Accept-Encoding: gzip, deflate
Authorization:  Bearer d9af9f24-c45f-3c82-944b-6f6d03d3108a
Connection: keep-alive
Host: 172.16.22.1:8243
User-Agent: HTTPie/0.9.2
accept:  application/json



HTTP/1.1 400 Bad Request
Accept-Encoding: gzip, deflate
Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
Access-Control-Allow-Methods: POST,GET
Access-Control-Allow-Origin: *
Connection: Close
Content-Type: application/xml; charset=UTF-8
Date: Fri, 15 Jun 2018 09:07:44 GMT
Transfer-Encoding: chunked

<ns0:fault xmlns:ns0="http://wso2.org/apimanager">
    <ns0:code>400</ns0:code>
    <ns0:message>Bad Request</ns0:message>
    <ns0:description>SQL-Injection Threat detected in Query Parameters</ns0:description>
</ns0:fault>

```

**Affected Product Version:**

- API Manager 2.5.0 RCx

**Steps to reproduce:**

1. Create an API with from Publisher
2. add a resource name containing any of  `DROP`, `SELECT` or `ALTER` words in it.
3. _Enable Message Mediation_ in the implementation step and select `regex_policy` as the inflow mediator.
4. Invoke the API with above-created resource name
5. HTTP 400 response will be returned

i:e
```xml
<ns0:fault xmlns:ns0="http://wso2.org/apimanager">
    <ns0:code>400</ns0:code>
    <ns0:message>Bad Request</ns0:message>
    <ns0:description>SQL-Injection Threat detected in Query Parameters</ns0:description>
</ns0:fault>
```

**Related Issues:**

* https://github.com/wso2/product-apim/issues/3406

**Comment by chamindias** [comment]
Fix : 
https://github.com/wso2/product-apim/pull/3474
https://github.com/wso2/carbon-apimgt/pull/5511
