### ISSUE TITLE
[REST API] [Store] Incorrect REST URL for scopes for applications

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#3448]
**Description:**
`/applications/scopes/{applicationId}` should be  `/applications/{applicationId}/scopes`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/5719
