### ISSUE TITLE
[REST API] [Store] Cannot get API tags of carbon.super from a different tenant

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#3449]
**Description:**

The issue only appears when a tenant subscriber trying to get super tenant tags. super tenant -> tenant, tenant -> tenant, super tenant -> super tenant combinations works without an issue.

- Sample request

```
GET https://localhost:9443/api/am/store/v0.13/tags HTTP/1.1
X-WSO2-Tenant: carbon.super
Authorization: Bearer 1ba74512-4817-35f7-a737-e12d43bc68b1
```

Say this bearer token "1ba74512-4817-35f7-a737-e12d43bc68b1" is owned by a subscriber in a tenant, the above request should retrieve the tags in tenant specified in X-WSO2-Tenant which is super tenant. But the response gives the tags in the subscriber's tenant.

The reason for the issue is tenant flow is not properly started for the required tenant in when the required tenant is super tenant. [Source](https://github.com/wso2/carbon-apimgt/blob/e38f3c483fa88432a8a2af159732fda50ef33f6a/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConsumerImpl.java#L1412-L1416)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed https://github.com/wso2/carbon-apimgt/pull/5697/files
