### ISSUE TITLE
Deleting a certificate freezes the publisher UI

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#3450]
**Description:**
When a cert is deleted via the publisher UI, the UI hangs until the page is reloaded.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.0.RC2
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
This has been fixed.
