### ISSUE TITLE
Label attach to the API not save in IE 11

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#3453]
**Description:**
Label attached to the API not save in IE 11 browsers.

Steps to reproduce
Define label.
Create new API
Go to API implementation tab select newly added label and publish API.
Click Edit API, the label not attached to the API.

Error in browser console "Object doesn't support property or method 'endsWith'"

**Comment by chamindias** [comment]
Fixed : https://github.com/wso2/carbon-apimgt/pull/5504
