### ISSUE TITLE
[UX][Store] Improvements in API rating and share options

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3456]
**Description:**
![screenshot-store](https://user-images.githubusercontent.com/9837443/41578121-40f3f43e-73ae-11e8-8c65-966681263f62.png)

1) In the current store API overview, the rating option is given with the overview details. Remove the rating option from details section and add with the share comment options as shown in the below image. Only the average rating needs to be shown with the API details. 

2) All the Share options can be added as follows without having a button panel for social login, embed and email. When embed is clicked the embed URL should be shown in a modal.

![fullsizerender](https://user-images.githubusercontent.com/9837443/41578432-efa335d4-73af-11e8-923f-a447c2e957c6.jpg)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.5.0

**Comment by dushaniw** [comment]
API Ratings are treated as a separate feature to API Comments and it is one of the general details of the API which also needed to show in thumbnail view in API Listing page. The second issue no longer exists as the sharing option is removed from API-M 3.0 onwards.
