### ISSUE TITLE
Making connection timeout configurable for publisher/store logins

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#3464]
**Description:**

Connection timeout for publisher/store login is not configurable. This needs to be configurable.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with above PR.
