### ISSUE TITLE
[Threat Protection] Exceeding the max attribute length does not return 400

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3470]
**Description:**

With the `xml_validator` mediator selected for API inflow, When invoking the API which has exceeded the max attribute length(default 100) in its payload, It dose not drop from the gateway.
The request is forwarded to the BE.

As we have stated in the documentation under [XML Payload validation properties](https://docs.wso2.com/display/AM2xx/XML+Threat+Protection+for+API+Gateway#XMLThreatProtectionforAPIGateway-XMLpayloadvalidationproperties)
The expected behavior is, to drop the request from the gateway and return 400 BAD Request code to the client.

```xml
<property name="maxAttributeLength" value="100"/>
```

**Affected Product Version:**
- API Manager 2.5.0-RC3

**Steps to reproduce:**
- Create an API from the Publisher
- Select `xml_validator` as the in-flow mediator and save and publish the API
- Use below sample payload and invoke the API, It has an attribute name which exceeded the defined `maxAttributeLength` limit
```xml
<?xml version="1.0" ?>
<root>
	<revenue serviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceserviceservice="interest" type="str">white</revenue>
</root>
```
- The request will reach to back end and you would receive the response code returned from the backend

**Related Issues:**
- N/A

**Comment by hasuniea** [comment]
Identified the woods stox only validates the attribute value.
ATTRIBUTE_SIZE (default: 512,000 characters): specifies the maximum allowed length of attribute values, in characters

created a doc jira to modify to be able to convince the idea.

https://wso2.org/jira/browse/DOCUMENTATION-7997

**Comment by hasuniea** [comment]
Resolved the issue hence we have updated the docs [1]
[1] https://docs.wso2.com/display/AM2xx/XML+Threat+Protection+for+API+Gateway#XMLThreatProtectionforAPIGateway-XMLpayloadvalidationproperties

**Comment by tmkasun** [comment]
Thanks @hasuniea 

Closing the issue as per above comment
