### ISSUE TITLE
ApplicationRegistrationTask-1.0.0.zip: Patch 2730 is incorrect

### ISSUE THREAD

**Issue by ClimberBear** [wso2/product-apim#3481]
**Description:**
The patch 2730 is incorrect, and not solve the issue with ApplicationRegistrationTask-1.0.0.zip

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
API Manager 2.1.0-update 14 
API EI 6.1.1-update24

**OS, DB, other environment details and versions:**    
Not relevant

**Steps to reproduce:**

The patch described in
https://github.com/wso2/product-apim/pull/2730/files
and included in APIM 2.1.0 update 14 is not correct

The included ApplicationRegistrationTask-1.0.0.zip file is zipped with the folder name (instead of flat zipped), and make it fail when deployed in EI Business Process profile

Unzip del HumanTaskRegistrationTask (Incorrect)
$ unzip ApplicationRegistrationTask-1.0.0.zip 
Archive: ApplicationRegistrationTask-1.0.0.zip
creating: ApplicationRegistrationTask-1.0.0/
inflating: ApplicationRegistrationTask-1.0.0/htconfig.xml 
inflating: ApplicationRegistrationTask-1.0.0/ApplicationRegistrationTaskService.wsdl 
inflating: ApplicationRegistrationTask-1.0.0/ApplicationRegistrationTask.ht

Unzip del HumanTaskRegistrationTask (desired)
$ unzip ApplicationRegistrationTask-1.0.0.zip 
Archive: ApplicationRegistrationTask-1.0.0.zip
inflating: htconfig.xml 
inflating: ApplicationRegistrationTaskService.wsdl 
inflating: ApplicationRegistrationTask.ht

Failing log in EI Business Process
Error en EI / Business process / wso2carbon.log
TID: [-1234] [] [2018-06-24 09:44:31,508] ERROR

{org.wso2.carbon.humantask.deployer.HumanTaskDeployer} - Error deploying HumanTask package : ApplicationRegistrationTask-1.0.0.zip {org.wso2.carbon.humantask.deployer.HumanTaskDeployer}
org.wso2.carbon.humantask.core.deployment.HumanTaskDeploymentException: htconfig.xml file not found for the ApplicationRegistrationTask-1.0.0
at org.wso2.carbon.humantask.core.deployment.ArchiveBasedHumanTaskDeploymentUnitBuilder.buildDeploymentConfiguration(ArchiveBasedHumanTaskDeploymentUnitBuilder.java:159)
at org.wso2.carbon.humantask.core.deployment.ArchiveBasedHumanTaskDeploymentUnitBuilder.<init>(ArchiveBasedHumanTaskDeploymentUnitBuilder.java:104)
at org.wso2.carbon.humantask.core.store.HumanTaskStore.createNewDeploymentUnit(HumanTaskStore.java:497)

**Related Issues:**
Bug registered in JIRA: https://wso2.org/jira/browse/APIMANAGER-6089
Original (incorrect) patch: https://github.com/wso2/product-apim/pull/2730/files#diff-737be153055f194110665b96252dcebe

**Comment by isharac** [comment]
This is already fixed apim 2.2.0
Fix is in https://github.com/wso2/product-apim/commit/24692e8fb834d0539e047ec95b55a5f77c2eb6db
