### ISSUE TITLE
Exception thrown while Starting an API-M profile with -Dprofile=gateway-manager

### ISSUE THREAD

**Issue by ClimberBear** [wso2/product-apim#3482]
**Description:**
When starting the API Manager with gateway profile, we see an exception in wso2carbon.log, related to event publication.

TID: [-1234] [] [2018-06-24 11:43:35,798]  WARN {org.wso2.carbon.apimgt.impl.internal.APIManagerComponent} -  Exception occurred while creating WSO2 Event Adapter. Request Blocking may not work properly {org.wso2.carbon.apimgt.impl.internal.APIManagerComponent}
org.wso2.carbon.event.output.adapter.core.exception.OutputEventAdapterException: Output Event Adapter not created as no adapter factory is registered with type wso2event
	at org.wso2.carbon.event.output.adapter.core.internal.CarbonOutputEventAdapterService.create(CarbonOutputEventAdapterService.java:90)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.configureEventPublisherProperties(APIManagerComponent.java:591)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate(APIManagerComponent.java:230)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 API Manager 2.1.0-update14
NOTE: This is a new bug, detected after updating to update14 release.

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
I have found a similar bug in JIRA
https://wso2.org/jira/browse/APIMANAGER-5292
but not equal (the missing topic was jms, not wso2event)

**Comment by sarubi** [comment]
@ClimberBear, Please set the "PolicyDeployer" value to false in the api-manager.xml file. 
For more information refer to this reported issue,
[https://github.com/wso2/product-apim/issues/3287](url)

**Comment by kavishkafernando** [comment]
This has been fixed with the latest WUM updates.
