### ISSUE TITLE
Exceptions in repository/components/default/configuration/xxxxxxx.log

### ISSUE THREAD

**Issue by sanigo** [wso2/product-apim#3483]
**Description:**

There are exceptions in repository/components/default/configuration/xxxxxxx.log.
java.lang.NoClassDefFoundError: org/objectweb/asm/commons/SerialVersionUIDAdder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:638)
Could that be fixed in the coming new release?
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environment details and versions:**    
Linux/Mac, Postgresql, H2
**Steps to reproduce:**
Run wso2server.sh, then go to repository/components/default/configuration/ to check the created log file.

**Related Issues:**

**Comment by jpvadell** [comment]
I have the same problem with version 2.5 and working with profile gateway-worker.

I fixed it copying http://central.maven.org/maven2/org/ow2/asm/asm-commons/4.2/asm-commons-4.2.jar to $wso2am_home/repository/components/plugins

Please add this jar to the distribution.

Thanks
