### ISSUE TITLE
APIs not getting visible from store in distributed mode without clustering

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#3484]
**Description:**
In Store and Publisher separated environments,  APIs that are created from publisher profile isn't visible in the store. This is mostly happening for APIs names which contains uppercase letters.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create separate store and publisher without clustering.
Create API from publisher

**Related Issues:**

**Comment by chamindias** [comment]
Fixed : https://github.com/wso2/carbon-kernel/pull/1807
