### ISSUE TITLE
Handle whitespaces in the names provided in Throttling Tiers during a product upgrade

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#3490]
**Description:**
When names are provided with whitespaces in the following files while defining tiers in API-Manager 1.10.0. execution policies are not deployed successfully after an upgrade to API-Manager 2.2.0

- app-tiers.xml  
- res-tiers.xml  
- tiers.xml

Following error is logged when the upgraded API-Manager pack is started. 

```
ERROR - EventProcessorDeployer Execution plan is not deployed and in inactive state : carbon.super_api_1 per minute_default.siddhiql
org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: Execution plan name 'carbon.super_resource_1 per minute_default' contains whitespaces. Please remove whitespaces.

```

**Affected Product Version:** 
API-Manager 2.0.0 onwards based on the upgrade

**Steps to reproduce:**
Create throttle tiers with whitespaces in the names in API-Manager 1.10.0
Upgrade the pack to 2.2.0

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2-support/product-apim/pull/261

**Comment by tgtshanika** [comment]
This has been fixed in the migration client.
