### ISSUE TITLE
Throttling policies/rate limit not working across tenants

### ISSUE THREAD

**Issue by ftoresan** [wso2/product-apim#3491]
**Description:**
If one tenant publishes an API and another tenant subscribe it with a tier that is not present in its own policies, every call to the API returns an error (forbidden). If a tier is created in the subscriber tenant with the same name, the API call works fine.
Also, the rate limit applied is the one in the subscriber tier, not the one defined by the publisher.

**Suggested Labels:**
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
2.2.0 update 4

**OS, DB, other environment details and versions:**    
AWS Linux, Postgres 9.6

**Steps to reproduce:**
- Create a tenant A
- Create a new subscription throttling policy, e.g. "Tier 1"
- Publish an API available to all tenants, with "Tier 1" enabled 
- Create a tenant B
- Subscribe to it using "Tier 1"
- Try to call the API

// rate limit problem
- Create "Tier 1" in Tenant B with another rate limit than the one defined by tenant A for Tier 1
- Redo the subscription to the API using this tier
- The rate limit enforced is the one defined by tenant B, not by tenant A (the publisher of the API)

**Related Issues:**
n/a

**Comment by marceloavan** [comment]
I have the same issue here

**Comment by joaors** [comment]
Same here too.

**Comment by luankevinferreira** [comment]
here too.

**Comment by nimanthag** [comment]
Root cause Analyze.
The underlying query does not return any data from the subscription policy table. As a result, API returns an error 900908 (forbidden). In the query, There is an equality check for policy subscriber tenant id and subscriber tenant id which fail in this scenario.

**Comment by nimanthag** [comment]
Developer testing record.
### Before
<img width="1680" alt="screen shot 2018-12-05 at 2 07 19 pm" src="https://user-images.githubusercontent.com/42195796/49510065-2e9ef480-f8ad-11e8-92cf-30e02b404705.png">
### After
<img width="1680" alt="screen shot 2018-12-05 at 2 13 35 pm" src="https://user-images.githubusercontent.com/42195796/49510041-1fb84200-f8ad-11e8-99b6-d8921474b5fe.png">


### Rate test
[CrossThrottling.mov.zip](https://github.com/wso2/carbon-apimgt/files/2648557/CrossThrottling.mov.zip)
