### ISSUE TITLE
[UX][Publisher] Add multi select option for adding roles when restricting access

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3493]
**Description:**
When creating an API->selecting "Restricted by roles" for "Access control" and "Store visibility", Users needs to copy paste or type in the role names. 

![screenshot-1](https://user-images.githubusercontent.com/9837443/42076383-8f276d02-7b92-11e8-8875-0ebd57a8bb5a.png)

Suggestion: Add multiple select functionality for role input textbox. e.g https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

**Suggested Labels:**
Ux, Improvement

**Affected Product Version:**
2.2.0, 2.5.0

**Comment by kavishkafernando** [comment]
By facilitating this a security issue will arise because all available roles will be exposed even if it's relavant or not. Hence we encourage users to type in the required roles.
