### ISSUE TITLE
[UX] Improve API Lifecycle graph

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3494]
**Description:**
The current API lifecycle graph need to be more clear for the user to identify the lifecycle states and transitions. 

![lifecycle-current](https://user-images.githubusercontent.com/9837443/42124733-f345ea7c-7c85-11e8-94d9-dbda0ff42eb1.png)

**Suggestion:**
Without adding the action buttons sepeartely add the action buttons to the graph instead. Make the relevant action buttons on active state and the others in disable state as shown in below image

![lifecycle1](https://user-images.githubusercontent.com/9837443/42124765-78413664-7c86-11e8-8552-3c976849cfa1.png)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.5.0

**Comment by kavishkafernando** [comment]
This has been improved in latest versions of APIM.
![image](https://user-images.githubusercontent.com/19324135/100441182-0c22c900-30cc-11eb-8802-a7b14c58c9be.png)
