### ISSUE TITLE
[UX][Publisher] Users tend to miss adding the resource path before implementation step

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3496]
**Description:**
Users tend to miss on clicking add button before going to implementation stage. 

![api-def-add](https://user-images.githubusercontent.com/9837443/42125495-bf75301c-7c95-11e8-841e-a73a28665405.png)

**Suggestion:**

![api-res](https://user-images.githubusercontent.com/9837443/42133627-e3d4a108-7d4a-11e8-8128-466a504aa4ca.png)

**Suggested Labels:**
UX Improvement

**Affected Product Version:**
2.5.0

**Comment by kavishkafernando** [comment]
This has been fixed in latest versions of APIM.

![image](https://user-images.githubusercontent.com/19324135/100441339-4e4c0a80-30cc-11eb-9d9c-98fb7f31d2e2.png)
