### ISSUE TITLE
[UX][Publisher] Alerts cannot be seen when page scroll down in API Implementation and Manage 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3498]
**Description:**
The alerts are placed relative on top of the page in API implementation and manage, hence the user can not see them when scrolled down.

Eg:- when save is clicked the alert is added to top of the page where the user is unable to see it
![screenshot-manage](https://user-images.githubusercontent.com/9837443/42145191-7dc262cc-7ddd-11e8-88dc-df32cb7d121f.png)

**Suggestion:**
Make alerts fixed of top 

![alert-fixed](https://user-images.githubusercontent.com/9837443/42145207-97527f7e-7ddd-11e8-8aeb-2f179e016eb1.png)

**Suggested Labels:**
UX improvement 

**Affected Product Version:**
2.5.0

**Comment by isharac** [comment]
Jaggery based publisher app is no longer in use. Please reopen the issue if this is still a concern in the latest version.
