### ISSUE TITLE
[UX][Publisher] API Definition URL pattern prefix disappears when the version is given without the context

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3499]
**Description:**

<img width="1438" alt="screen shot 2018-06-21 at 12 29 12 pm" src="https://user-images.githubusercontent.com/9837443/42145965-1917897e-7de2-11e8-9451-9b4950fc68d6.png">

The prefix should be {context}/v1.0.0 till the context is given

**Suggested Labels:**
Bug

**Affected Product Version:**
2.5.0

**Comment by isharac** [comment]
Jaggery based publisher app is no longer in use. Please reopen if this happens with the latest version.
