### ISSUE TITLE
[UX][Store] Only show the functionalities which user can perform without log into the store

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3503]
**Description:**
Currently, users who have not logged in is shown the actions of a logged in user and directed to login when performing those actions. These actions include view applications, create new forum topic, manage subscriptions etc.

When user is not logged in, without directing users to login hide and only show the functionalities which they can perform without log into the store.

**Suggested Labels:**
UX Improvements

**Affected Product Version:**
2.5.0

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this is still needed with the latest version.
