### ISSUE TITLE
[Improvement] Rest API support for Dynamic Certificate Installation.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#3504]
**Description:**
The functionality of dynamic certificate installation feature should be exposed as REST apis.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
https://github.com/wso2/carbon-apimgt/pull/5615
