### ISSUE TITLE
Validating not to support French characters

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#3506]
**Description:**

The user can create Application with French Characters like (é).

When Generating token we are creating service provider using IS it validates the app name with a service provider, therefore from Application creation we have to validate the app name.

**Comment by tmkasun** [comment]
We have fixed this, In APIM 3.x latest master source


![image](https://user-images.githubusercontent.com/3313885/96454495-8d6b7e00-1239-11eb-91d5-37867cb6f53f.png)


hence closing this issue
