### ISSUE TITLE
Cannot use swagger file in publisher which starts with an UTF-8 BOM

### ISSUE THREAD

**Issue by thomasmey** [wso2/product-apim#3507]
**Description:**
When I try to create an api definition with an swagger file which is encoded with utf-8 with a bom the swagger file is shown as invalid.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
apim 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
store an valid swagger file with utf-8 bom, try to use this file in the api publisher to define an api.

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
