### ISSUE TITLE
Official OpenJDK support

### ISSUE THREAD

**Issue by bmaupin** [wso2/product-apim#3508]
Along the same lines as wso2/product-is#2115, are there any plans to officially support OpenJDK? My understanding is Oracle Java 8 will no longer be freely available after 2018.

Thanks!

**Comment by DMHP** [comment]
@bmaupin 
Thanks for reporting the issue. Wso2 products do support for openjdk. Please find the doc as follows.

[1] https://docs.wso2.com/display/compatibility/Tested+Operating+Systems+and+JDKs

**Comment by bmaupin** [comment]
Glad to hear that was added, thanks!
