### ISSUE TITLE
Add documentation on how to use the APIM analytics with mysql cluster

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#3514]
**Description:**
By default mysql cluster uses innodb engine. If that is used, the tables will not be automatically replicated across mysql nodes. So in APIM and other databases when we are providing sql script we add the engine specification in the create table statement itself. However analytics tables are created using spark scripts, so we need to have a way to achive this.

Adding following in datasource configuration will solve the issue,
`<connectionProperties>sessionVariables=default_storage_engine=ndbcluster</connectionProperties>`
```
<datasources>
    	<datasource>
	  <name>WSO2AM_STATS_DB</name>
	  <description>The datasource used for setting statistics to API Manager</description>
	  <jndiConfig>
	    <name>jdbc/WSO2AM_STATS_DB</name>
	    </jndiConfig>
	  <definition type="RDBMS">
	    <configuration>
	      <url>jdbc:mysql://10.100.0.10:3306/test</url>
	      <username>root</username>
	      <password>root</password>
	      <driverClassName>com.mysql.jdbc.Driver</driverClassName>
	      <maxActive>50</maxActive>
	      <maxWait>60000</maxWait>
	      <testOnBorrow>true</testOnBorrow>
	      <validationQuery>SELECT 1</validationQuery>
	      <validationInterval>30000</validationInterval>
 	      <defaultAutoCommit>false</defaultAutoCommit>   
<connectionProperties>sessionVariables=default_storage_engine=ndbcluster</connectionProperties>      
	      </configuration>
	    </definition>
	</datasource>
```

**Suggested Labels:**
doc, improvement

**Suggested Assignees:**
N/A

**Affected Product Version:** 2.x version

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**N/A

**Related Issues:** N/A

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
