### ISSUE TITLE
Prototyped API fails when changing the lifecycle to "Demote to created" state

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#3517]
**Steps to reproduce:**
1. Create an api and publish as a prototype API (set inline configuration)
2. Go to lifecycle tab and change the state to "Demote to created" State

Following error is thrown
<img width="1136" alt="screen shot 2018-07-06 at 1 53 42 pm" src="https://user-images.githubusercontent.com/4861150/42368223-1c9af8fc-8124-11e8-86ee-6a0c3a50ef41.png">

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5616
