### ISSUE TITLE
Management Console points to old APIM docs

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3520]
**Description:**
In the APIM 250 RC4 pack the two links in the Management Console (See screenshot) points to APIM 2.1.0 docs. This needs to be corrected by changing the links to the APIM 250 docs [2].

[1] https://docs.wso2.com/display/AM210/WSO2+API+Manager+Documentation

[2] https://docs.wso2.com/display/AM250/WSO2+API+Manager+Documentation

**Suggested Labels:**
2.5.0, Bug

**Suggested Assignees:**
Chamin

**Affected Product Version:**
APIM 2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
![screen shot 2018-07-07 at 8 06 23 pm](https://user-images.githubusercontent.com/5195851/42412198-3ee4281e-8225-11e8-84fe-1c1e05379bd7.png)

**Comment by isharac** [comment]
fixed in APIM-4.0.0-m1

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/product-apim/pull/9575
