### ISSUE TITLE
Forum link in Management console is wrong

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3521]
**Description:**
When u click "Forum" in the sign in page of the APIM 2.5.0 RC4 pack of the Management console it takes you to a "page not found" link. Please fix this.

**Suggested Labels:**
2.5.0, bug

**Suggested Assignees:**
Chamin

**Affected Product Version:**
APIM 2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

![screen shot 2018-07-07 at 8 38 04 pm](https://user-images.githubusercontent.com/5195851/42412253-360ac800-8226-11e8-862e-09f200d6b3d5.png)
![link-redirects-to-this-page](https://user-images.githubusercontent.com/5195851/42412257-4afd78d4-8226-11e8-8ff6-fd5a7adf6a2d.png)

**Comment by isharac** [comment]
fixed.
duplicate witn https://github.com/wso2/product-apim/issues/2859
