### ISSUE TITLE
Cannot add hybrid role exception is thrown when assigning multiple roles from UI

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#3532]
**Description:**
When assigning multiple roles from UI cannot assign roles exception is thrown

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:** APIM 2.0.0, IS-KM 5.2.0

**OS, DB, other environment details and versions:**    Ubuntu 16.04, JDK 1.8

**Steps to reproduce:**

1. Add multiple roles, so that roles will be listed in pagination view
2. Click on assign roles
3. Assign multiple roles by moving between different pages
4. Click on Update . (Update will succeed)
5. After that click on Finish button without selecting any new roles. Duplication entry exception will be thrown.

**Related Issues:**
N/A

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
