### ISSUE TITLE
Configuring Identity Server is missing in APIM SSO configuration documentation 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3535]
**Description:**

Users can't configure the Single Sign-On(SSO) for API Manager using WSO2 Identity server(Which is mandatory for configuring SSO) by following the corresponding documentation. [ [2.1.0](https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO) / [2.2.0](https://docs.wso2.com/display/AM220/Configuring+API+Manager+for+SSO) ]
That is because We have not emphasized the **[Configuring Identity Server as IDP for SSO](https://docs.wso2.com/display/AM2xx/Configuring+Identity+Server+as+IDP+for+SSO)** topic within the SSO **Configuring API Manager for SSO** documentation, Rather we have added a link to **Configuring Identity Server as IDP for SSO** documentation in `Related Links` section.

IMO we should provide the link to **[Configuring Identity Server as IDP for SSO](https://docs.wso2.com/display/AM2xx/Configuring+Identity+Server+as+IDP+for+SSO)** topic at the end of the **Configuring API Manager for SSO** documentation  [ [2.1.0](https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO) / [2.2.0](https://docs.wso2.com/display/AM220/Configuring+API+Manager+for+SSO) ]

**Affected Product Version:**

- API Manager 2.1.0
- API Manager 2.2.0

**Steps to reproduce:**

- Follow the SSO documentation for 2.1.0 or 2.2.0 and try to login with SSO
- Login will not be successful since IDP service provider configurations are missing

**Related Issues:**
- N/A

**Comment by ruthryi** [comment]
Updated this in [1].

[1] https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-Step4-ConfiguringanIdentityprovider

**Comment by ruthryi** [comment]
Updated the same in the following as well.

[2] https://docs.wso2.com/display/AM2xx/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-Step4-ConfiguringanIdentityprovider
[3] https://docs.wso2.com/display/AM220/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-Step4-ConfiguringanIdentityprovider
[4] https://docs.wso2.com/display/AM250/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-Step4-ConfiguringanIdentityprovider
