### ISSUE TITLE
Document on how to access API properties in velocity xml

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#3540]
**Description:**
Currently we do not have a documentation on to how to access api properties in velocity xml, this may be useful for the customers who are customizing this documentation

**Suggested Labels:**
Documentation, improvement

**Suggested Assignees:**
N/a

**Affected Product Version:** 2.1

**Related Issues:**
N/A

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still find this useful.
