### ISSUE TITLE
When you add a tag from Publisher to an API, Swagger does not contain those tags

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#3541]
**Description:**

You can add a tag to an API. Swagger does not have those tags. Need to fix this.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
