### ISSUE TITLE
API Gateways dropdown box does not adjust to text size

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3542]
**Description:**
When I added the following code in the <API-M_HOME>/repository/conf/api-manager.xml file I noticed that the dropdown box had a fixed length and did not adjust based on the size of the Environment name. It will be better if the "API Gateways" dropdown box can adjust to the text as required.

`<Environment type="production" api-console="true">
      			<Name>Production Gateway</Name>
      			<Description>Production Gateway Environment</Description>
      			<ServerURL>https://localhost:9444/services/</ServerURL>
      			<Username>admin</Username>
      			<Password>admin</Password>
      			<GatewayEndpoint>http://localhost:8281,https://localhost:8244</GatewayEndpoint>
   		</Environment>
   		<Environment type="hybrid" api-console="true">
      			<Name>Production and Sandbox Gateway</Name>
      			<Description>Hybrid Gateway Environment</Description>
      			<ServerURL>https://localhost:9445/services/</ServerURL>
      			<Username>admin</Username>
      			<Password>admin</Password>
      			<GatewayEndpoint>http://localhost:8282,https://localhost:8245</GatewayEndpoint>
   		</Environment>`

**Suggested Labels:**

**Suggested Assignees:**
Thilini Shanika

**Affected Product Version:**
APIM 2.5.0 RC 4=GA

**OS, DB, other environment details and versions:**    
Mac OS, Safari

**Steps to reproduce:**

**Related Issues:**
![screen shot 2018-07-16 at 5 41 10 pm](https://user-images.githubusercontent.com/5195851/42758198-5b534c94-8920-11e8-9248-d8c08656e56b.png)

**Comment by chanaka3d** [comment]
This issue is addressed with 3.x product.
