### ISSUE TITLE
APIM 2.0.0 does not start when the MB db is corrupted

### ISSUE THREAD

**Issue by gnudeep** [wso2/product-apim#3544]
**Description:**

APIM 2.0.0 does not start when the MB db is corrupted.

Related Logs:
[Framework Event Dispatcher] ERROR ApplicationRegistry org.wso2.andes.kernel.AndesException: Connecting to database failed with jndi lookup : WSO2MBStoreDB. data source username : wso2carbon. SQL Error message : General error: "java.lang.ArrayIndexOutOfBoundsException: 

[Framework Event Dispatcher] ERROR Main Exception during startup. Triggering shutdown
org.wso2.andes.kernel.AndesException: Unable to initialise application registry

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.0.0

**OS, DB, other environment details and versions:**    
Linux

**Steps to reproduce:**
This error goes away after replacing the corrupted MB_DB.

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
