### ISSUE TITLE
[Store] Feature to share applications between groups

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3547]
**Description:**
In APIM 2.5.0, we have applications sharing feature in API Store to share applications among users who are in shared groups. It is missing in APIM 3.0.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by CrowleyRajapakse** [comment]
This is implemented
