### ISSUE TITLE
wso2is-km-5.6.0.zip download link gives a zip with  version with RC4   

### ISSUE THREAD

**Issue by robbla** [wso2/product-apim#3549]
the link to download  wso2is-km-5.6.0.zip on the page

https://github.com/wso2/product-apim/releases/tag/v2.5.0

![afbeelding](https://user-images.githubusercontent.com/11582659/42932254-195d22b4-8b42-11e8-858e-bba4c3cc4a4e.png)

**Comment by chamindias** [comment]
Fixed the file : https://github.com/wso2/product-apim/releases/download/v2.5.0/wso2is-km-5.6.0.zip
