### ISSUE TITLE
Alignment issues in Material-UI beta version

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3553]
**Description:**
We are implementing APIM 3.0.0 UIs with Material - UI framework, in which there are alignment issues (Ex : with table pagination). We should upgrade it to newer version.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this is still valid.
