### ISSUE TITLE
APIs created through the REST API interface cannot be deleted properly in UI/REST API

### ISSUE THREAD

**Issue by davekennedyOJ** [wso2/product-apim#3554]
**Description:**
When an API is created through the REST API interface (Curl Commands). It cannot be deleted properly though the User Interface or through a REST API Command.

When trying to delete through the UI, The User is presented with a null error (See Screenshot 1). Attempting to delete again results in the following error (See Screenshot 2).

Refreshing the page after either error removes the API from the user interface, making it appear as though the API has been deleted from the Publisher View. Even though its no longer visible in the UI, the database entries are still present. 

This leads to problems when attempting to create another API with the same name. Both the UI and the REST API cannot see the existing entry in the Database but the creation of the new API fails to be created as there already is an entry in the Database.

Our current workaround is to remove the entries from the database manually once a delete has been attempted. 

**Suggested Labels:**
REST_API, 2.1.0, 2.2.0 

**Affected Product Version:**
APIM 220, 2xx

**OS, DB, other environment details and versions:**    
MySQL Ver 15.1 Distrib 10.1.26-MariaDB, for Linux (x86_64) using readline 5.1

**Steps to reproduce:**
### **To Create (REST API):** 
Create an API through the REST API Curl Command:
e.g curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -H "Content-Type: application/json" -X POST -d @data.json https://localhost:9443/api/am/publisher/v0.11/apis

Publish the API through the REST API:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -X POST "https://localhost:9443/api/am/publisher/v0.11/apis/change-lifecycle?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish"

Create an Application for the API through the REST API:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -H "Content-Type: application/json" -X POST -d @data.json "https://localhost:9443/api/am/store/v0.11/applications"

Generate the Keys for the Application:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -H "Content-Type: application/json" -X POST -d @data.json  "https://localhost:9443/api/am/store/v0.11/applications/generate-keys?applicationId=c30f3a6e-ffa4-4ae7-afce-224d1f820524"

Add a Subscription for the Application:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -H "Content-Type: application/json" -X POST  -d @data.json "https://localhost:9443/api/am/store/v0.11/subscriptions"

### **To Delete (REST API):**
Delete the Subscription:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -X DELETE "https://localhost:9443/api/am/store/v0.11/subscriptions/5b65808c-cdf2-43e1-a695-de63e3ad0ae9"

Delete the Application:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -X DELETE "https://localhost:9443/api/am/store/v0.11/applications/367a2361-8db5-4140-8133-c6c8dc7fa0c4"

Delete the API:
e.g. curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -X DELETE https://localhost:9443/api/am/publisher/v0.11/apis/6fb74674-4ab8-4b52-9886-f9a376985060

### **To Delete (UI):**
Press the delete button under the API (See Screenshot 3)(Note: delete any active subscriptions and applications first). 

Note the API entry is still present in the Database.
* wso2_am.am_api
* wso2_am.am_api_lc_event

Creating a new API with the same name returns an error as there already is an entry in the DB
Repsonse:{"code":409,"message":"Resource Already Exists","description":"Error occurred while adding the API. A duplicate API already exists for TestAPI-0.57.0","moreInfo":"","error":[]}

![screenshot1](https://user-images.githubusercontent.com/19532047/42995541-0a58de26-8c09-11e8-9584-9ff69a90fd38.png)
![screenshot2](https://user-images.githubusercontent.com/19532047/42995543-0a834fee-8c09-11e8-84fe-e840584bb383.png)
![screenshot3](https://user-images.githubusercontent.com/19532047/42995544-0ac1daa2-8c09-11e8-8c9d-79da2aaebffc.png)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
