### ISSUE TITLE
Response messages differ when duplicate API create via rest APIs when different database types used

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#3557]
**Description:**
Integration test case name APIMANAGER3226APINameWithDifferentCaseTestCase is getting failed with mysql or mssql db type is used.
Further when H2 db type is used in the product, the response message is returning with the content **"A duplicate API name already exists for <APIName>"** which is hardcoded message in **publisher/modules/api/add.jag**.
Then, if we run the same test when the product is pointed to MySQL, the response message is **"A duplicate API already exists for <APIName>"** where the word 'name' is missing and this message can be scene in the ApisApiServiceImpl.java and APIProviderHostObject.java on carbon-apimgt
No any difference can be scene on request parameters which are sending out from the tests on both attempts
**Affected Product Version:**
2.x

**OS, DB, other environment details and versions:**    
H2, MySQL
2.x, wso2am-2.5.0

**Steps to reproduce:**
Run integration test case 'APIMANAGER3226APINameWithDifferentCaseTestCase' while the product is pointing to MySQL db.

**Comment by chaminda** [comment]
Found that, when its come to MySQL, the response message is exactly retuned from **jsFunction_addAPI** method of APIProviderHostObject.java(line:1360)

**Comment by bhathiya** [comment]
FIx by https://github.com/wso2/carbon-apimgt/pull/5686
