### ISSUE TITLE
[APIM 2.5.0] API store walkthrough doesn't work properly

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#3559]
**Description:**
APIM store walkthrough get stuck without going to the swagger console. Image is attached indicating the last step before freezing.
<img width="1671" alt="apim 2 5 0" src="https://user-images.githubusercontent.com/8377610/43092827-f3cde0aa-8ecb-11e8-8ee1-23ab7ed7b334.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
API walkthroughs / guided tours are not available in 3.x series, Feature implementation for API developer portal walkthroughs are tracked though this #7787 issue, Will close this issue and address this when implementing the new feature on next releases.
