### ISSUE TITLE
Store don't work properly on click View Subscriptions

### ISSUE THREAD

**Issue by LorHua** [wso2/product-apim#3561]
When the subscription is successful, click View Subscriptions on the information message that appears.It can't jump to the web "View Subscriptions".The same problem appears in the APPLICATIONS tag.

**Comment by LorHua** [comment]
@tharikaGitHub Hi, I have reslove this problem by restarting the server.Thanks.

**Comment by tharikaGitHub** [comment]
Thanks for the update @LorHua. I'll close this ticket based on your comment above.
