### ISSUE TITLE
Use a proper config for "iss" rather than using existing <RevokeAPIURL>

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#3562]
**Description:**
We have currently used `<RevokeAPIURL>` as the "iss" of the inbound JWT access token.

Ideally, we need to use a separate configuration for that. identity.xml already contains a config `<IDTokenIssuerID>` which is used in JWTTokenIssuer in IS. In APIMTokenIssuer, we need to use the same config.

The default value of the config should be changed to /token API URL in the gateway.

**Comment by chamindias** [comment]
Dev mail : https://mail.wso2.org/mailarchive/dev/2018-July/077894.html

**Comment by tharindu1st** [comment]
From the above change if you want to change the issuer URL you need to below steps.
1. Replace the **IDTokenIssuerID** value in identity.xml which located at <APIM_HOME>/repository/conf/identity.
2. Replace the **issuer** value into an aforementioned value in **micro-gw.conf** in micro gateway distribution under <micro-gw>/resources/conf folder.
