### ISSUE TITLE
APIM does not load the general details of an API when creating the API using a swagger file

### ISSUE THREAD

**Issue by NipunaDilhara** [wso2/product-apim#3564]
**Description:**
APIM does not load the general details of an API when creating the API using a swagger file in wum updated pack (timestapm 1527704328444).

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
- Start the APIM instance
- Go to APIM publisher and start to create a new API
- Import a swagger file from the API Definition section of the Design tab.

**Comment by pedrorozoc** [comment]
Fixed in APIM version 2.2.0
