### ISSUE TITLE
[APIM][2.2.0] Extending life cycle redirect to earlier version.

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#3568]
**Description:**
When I was navigating through the document https://docs.wso2.com/display/AM220/Extending+the+API+Life+Cycle#ExtendingtheAPILifeCycle-ExtensionPointsofAPILifecycle , there is a link on "Define your own life cycle state" and it redirects to a 2.1.0 version page.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
Fixed links in the following : 

[1] https://docs.wso2.com/display/AM2xx/Extending+the+API+Life+Cycle
[2] https://docs.wso2.com/display/AM250/Extending+the+API+Life+Cycle
[3] https://docs.wso2.com/display/AM220/Extending+the+API+Life+Cycle
