### ISSUE TITLE
Support for OpenAPI Specification Version 3.0.1

### ISSUE THREAD

**Issue by defter89** [wso2/product-apim#3575]
**Description:**
OpenAPI Specification 3.0.1 is released at Dec 7, 2017. 
See https://github.com/OAI/OpenAPI-Specification/releases

There are API-Definitions out there which uses this version of OpenAPI Specification.
It is not possible to import them in WSO2 API Manager Version 2.5.0. If I try I get the
following error:
	

> Unsupported OpenAPI version provided. Please re-import with OpenAPI 3.0.0

**Affected Product Version:**
Problem exists in the latest release: 2.5.0.

**Steps to reproduce:**
As an example you can save this file locally and try to import in WSO2 Version 2.5.0:
https://github.com/opengeospatial/WFS_FES/blob/master/openapi.yaml
Therefore you go to the publisher -> Add New API -> I have an existing API -> Upload the locally saved file

**Comment by vgpranav** [comment]
I am facing same issue

**Comment by yosuf** [comment]
In favour of this change as we experience the same issue.
We have found a (rather ugly) workaround. And that is to manually change the API version to 3.0.0 from 3.0.1 which will succesfully be imported. We have not encountered any issues, as of yet. However, we are busy testing.

**Comment by dushaniw** [comment]
This is fixed in API-M 3.0.0 onwards. Please find the Git issue [https://github.com/wso2/product-apim/issues/4711]

The above is fixed in latest wum updated packs of API-M 2.5 and 2.6 as well.
