### ISSUE TITLE
Host value become empty in API Console's swagger definition

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-apim#3583]
**Description:**
If we have removed https URL from <GatewayEndpoint> configuration, then issue mentioned in $subject can be reproduced. 
In addition to that curl commands displayed in API console's try it shows the STORE host name instead  of gateway URL.

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
- In the api-manager.xml change <GatewayEndpoint> section only keeping http URL as follows.
<GatewayEndpoint>http://${carbon.local.ip}:${http.nio.port}</GatewayEndpoint>
- Go to API console of one of the published API in API Store. Check the swagger.json and try it UI. swagger.json shows the host as empty value. Try it curl commands shows host as localhost (store host).

It seems like, in code, we have taken host of the HTTPS url configured in <GatewayEndpoint>. If <GatewayEndpoint> has configured only one URL configured, we should use that host when generating swagger.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
