### ISSUE TITLE
Timestamps are getting same for both create and publish statuses of an API, intermittently

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#3585]
**Description:**
While running the integration tests below kind of responses getting intermittently in some instances of test run. Here both the date fields have the same timestamp(1533181182000)

API status Change is invalid in API Name:CopyAPIWithReSubscriptionTest API Version:2.0.0 API Provider Name :admin Response Data:{"error" : false, "lcs" : [{"username" : "admin", "newStatus" : "**CREATED**", "oldStatus" : "", "date" : "**1533181182000**"}, {"username" : "admin", "newStatus" : "**PUBLISHED**", "oldStatus" : "CREATED", "date" : "**1533181182000**"}], "wfstatus" : null, "status" : {"workflowResponse" : {"jsonPayload" : ""}, "stateChangeStatus" : null}} expected:<true> but was:<false>

**Affected Product Version:**
2.x

**OS, DB, other environment details and versions:**    
last found environment: CentOS - 7.4 | OPEN_JDK8 | mysql - 5.7

**Steps to reproduce:**

This can be noticed intermittently with **testInvokePOSTAndGETResourceAfterAddingPOSTResource** and **testCustomLifeCycle** test cases.
Above test cases are getting failed due to this unexpected behavior.

**Comment by bhathiya** [comment]
This is a test issue. Fixed in https://github.com/wso2/product-apim/pull/3704/commits/ee7a811cd4ca52038afdf8b74261f63c9b470376
