### ISSUE TITLE
Error in status code in response when calling REST API resource of self-sign up

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3588]
**Description:**
When calling REST API resource of self-sign up from browser, it returns **200** (successful) status code for error response as well. When try to create a new user with already existing user name, it returns an error response with 200 status code.
Response is : 
{"code":900604,"message":"User creation failed","description":"Error occurred while creating user. ","moreInfo":{"USERNAME":"username"},"error":[]}

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
