### ISSUE TITLE
Issues when uploading the mediation policies of IN/OUT/Fault Sequences in APIM Publisher

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#3591]
**Description:**
When uploading the mediation policies of IN/OUT/Fault Sequences in APIM Publisher getting some issues intermittently.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
API Manager 2.0.0 

**Steps to reproduce:**
When uploading sequences from the filesystem getting some issues,
(1). Combobox does not show the newly uploaded sequence 
(2). File chooser does not let you upload the sequence 

This issue is reproducible in the Linux environment and the Windows environment also.

**Comment by npamudika** [comment]
Closing the issue as this has been fixed from https://github.com/wso2/carbon-apimgt/pull/5594
