### ISSUE TITLE
When we send a request to the api manager[1.10.0 and 2.1.0] with an invalid character % the system generates an exception which is displaying an internal implementation

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#3595]
**Description:**
When we send a request to the api manager[1.10.0 and 2.1.0] with an invalid character % the system generates an exception which is displaying an internal implementation

**Suggested Labels:**
**api manager**

**Affected Product Version:**
1.10.0 and 2.1.0 and
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1.start api manager 1.10.0
2.deploy the calculator api
3.subscribe to the api 
4.run the request as 
curl -k -X GET "https://172.17.0.1:8243/calc/1.0/multiply?x=20&y=2%" -H "accept: application/json" -H "Authorization: Bearer    63722d7eb5f6f75d4526da80478a13b1" -H "Accept: application/json" -v

Due to the % symbol ex:x=20&y=2% the system generates a message <faultstring>URLDecoder: Incomplete trailing escape (%) pattern</faultstring>
**Related Issues:**

**Comment by isharac** [comment]
fixed with https://github.com/wso2/wso2-synapse/pull/1177/
