### ISSUE TITLE
SQL Error Pool empty Unable to fetch a connection in 60 seconds

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#3603]
**Description:**

Following exception occur while accessing the publisher/store node.

TID: [-1234] [] [2018-07-23 00:00:11,059] ERROR {org.wso2.carbon.registry.core.dataaccess.TransactionManager} -  Failed to start new registry transaction. {org.wso2.carbon.registry.core.dataaccess.TransactionManager}
org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-9443-exec-50] Timeout: Pool empty. Unable to fetch a connection in 60 seconds, none available[size:50; busy:49; idle:0; lastwait:60000].
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:703)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:200)

**Affected version**
APIM-2.1.0

**Comment by Krishanx92** [comment]
This is now fixed in the kernel latest branch. Hence closed

**Comment by jadam1212** [comment]
Hi, 

we have APIM 3.1.0. installed and I see similar PoolExhaustedException but from org.wso2.carbon.identity.base.IdentitRuntimeException . 

Which version was it fixed for?

In our case its a single user logging in and out and modifying APIs caused this (and this is not the first time I see it happen).

So connections must be leaking somewhere...

Is there any other way of solving this than restarting the API manager (which means downtime)?

Thanks,
Adam
