### ISSUE TITLE
IDN_OIDC_SCOPE table is not created in IS as a KM pack

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#3604]
**Description:**
When IS as a KM pack is started, a MySQLSyntaxErrorException is thrown with the error message **Table 'IDN_OIDC_SCOPE' doesn't exist**.  
Database scripts for creating this table available in <KM_HOME>/dbscripts/identity/mysql.sql. But it is **not** included in the <KM_HOME>/dbscripts/apimgt/mysql.sql

![error](https://user-images.githubusercontent.com/9979373/43956956-aea9faa8-9cc3-11e8-9393-e19653fb1406.png)

**Suggested Labels:**
2.6.0

**Suggested Assignees:**

**Affected Product Version:**
2.6.0-M1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create an IS as KM pack 
2. Start the KM product 
3. A MySQLSyntaxErrorException will be thrown in the carbon logs

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
This has been fixed with the 2.6.0 Alpha release
