### ISSUE TITLE
Swagger export in store not standardized in APIM-2.0.0

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#3606]
**Description:**
When creating an API with variable resource path, the generated swagger definition is erroneous. The reason is, the swagger definition contains **"allowMultiple": false,** property and it is not valid in swagger 2.0. 

**Suggested Labels:**
swagger 2.0, APIM-2.0.0

**Affected Product Version:** APIM-2.0.0

**Steps to reproduce:**
1. Create a simple API with variable resource path.
2. Publish the API and see it in the store.
3. Generate the swagger definition in "API Console"
4. Add the generated swagger definition to [1]. It contains errors.

**References:**
[1] http://editor.swagger.io/

**Comment by npamudika** [comment]
Closing the issue as this has been fixed in APIM 2.0.0.
