### ISSUE TITLE
Issues when importing the same API as default APIs from different versions into the same environment

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#3610]
**Description:**
Issues when importing the same API as default APIs from different versions into the same environment
**Suggested Labels:**
Type/Improvment

**Affected Product Version:**
API Manager 2.1.0 

**Steps to reproduce:**

- Create an API, selecting it as the Default API and publish it as TestwebAPI-1.0.0 in one API Manager server (APIM server 01).
- Export the published API (TestwebAPI-1.0.0) using API Export-Import tool.
- Import the exported API in another API Manager server(APIM server 02) and login to the Publisher and publish the API.
- Created a new API version as TestwebAPI-1.1.0 in APIM server 01.
- Export the newly created API.
- Import the created API into APIM server 02 using the APIM Export-Import tool. As you have mentioned before, TestwebAPI-1.1.0 API is in the CREATED state.
- Default API Version has set into 1.1.0 in both APIs.
- But when invoking the TestwebAPI using default URL it gives the response related to TestwebAPI-1.0.0 if it hasn't marked as default. 
- Then uncheck the Make this the Default version: checkbox of TestwebAPI-1.1.0 API and save it.
- Default API Version has set into None in both APIs.

**To solve this issue need to do the following improvement.**
If an API already has in one environment, when importing the same API from the different versions, will check is there a default API related to that API. If there was a default API, will not allow importing another API with the different version as the default API.
Or else when importing the APIs using API import-export tool no need to consider about the default version.

**Comment by praminda** [comment]
Fixed with #4479
