### ISSUE TITLE
[doc] "View in Store" has incorrect link when reverseProxy is enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-apim#3612]
**Description:**
-When we enable reverseProxy in site.json for store or/and publisher, it doesn't update the "View in Store" button's link in publisher pages and still uses value from api-manager.xml.

<API-M_HOME>/repository/deployment/server/jaggeryapps/store/site/conf/site.json
<API-M_HOME>/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json

```
"reverseProxy" : {
        "enabled" : true, 
        "host" : "apistore.com", // If reverse proxy do not have a domain name use IP
        "context":"/apimanager/store",
        "regContext":"" // Use only if different path is used for registry
    }
```
We have to update  URL under APIStore in <API-M_HOME>/repository/conf/api-manager.xml file.
```
<APIStore>
    <URL>https://apistore.com/apimanager/store</URL>
</APIStore>
```

[1] https://docs.wso2.com/display/AM210/Configuring+the+Proxy+Server+and+the+Load+Balancer
[2] https://docs.wso2.com/display/AM191/Adding+a+Reverse+Proxy+Server
[3] https://docs.wso2.com/display/AM200/Configuring+a+Single+Node
[4] https://docs.wso2.com/display/AM210/Configuring+the+Proxy+Server+and+the+Load+Balancer
[5] https://docs.wso2.com/display/AM200/Configuring+an+Active-Active+Deployment

**Suggested Labels:**
Doc, Improvement

**Comment by rksk** [comment]
None of the above documents describes about the change to be done in api-manager.xml

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
