### ISSUE TITLE
Allow admin to edit/view other users application

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#3616]
**Description:**
There could be a requirement to see, edit and user's application to tenant admin in order to diagnose the user's data. Such cases there is no way to check user's applications to admins. Application sharing can be used to share amoung a group but cannot be limited it to admins.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this improvement is still valid in the  latest version.
