### ISSUE TITLE
Micro gateway will not build if API has special characters in the name

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-apim#3618]
My API name was "markets-Lob-API", once I create this api from the publisher and use the micro-gw tool to generate the micro-gw it will not build. It will throw B7a exceptions at compile time.

The name "marketsLobAPI" works fine.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
