### ISSUE TITLE
Micro gateway will not build if URI templates have B7a reserved keywords

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-apim#3619]
I had a URI template like

`/orderServices/order/lock`

When I generate the micro-gw it will not build and will throw compile errors because I have `lock` in my path.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.

**Comment by isharac** [comment]
This is supported in the latest version.
https://apim.docs.wso2.com/en/latest/learn/design-api/endpoints/endpoint-security/oauth-2.0/
