### ISSUE TITLE
Support for OAuth 2.0 based backends

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#3630]
**Description:**

Provide support for OAuth 2.0 based backend endpoints

**Suggested Labels:**

Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
This is supported with the latest version 3.2.0
https://apim.docs.wso2.com/en/latest/learn/design-api/endpoints/endpoint-security/oauth-2.0/
