### ISSUE TITLE
Root path element not get removed completely when deleting all resources

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#3639]
**Suggested Labels:**
Bug

**Affected Product Version:**
APIM-2.1.0  

**Steps to reproduce:**
- Delete a resource of an API
- Open the editor
- Click _Apply changes_
- Save changes 
Error message appears as **HTTP methods are not defined for the deleted resource**

**Related Issues:**
https://github.com/wso2/product-apim/issues/3296

**Comment by tgtshanika** [comment]
This is fixed in APIM 2.6.0
