### ISSUE TITLE
[doc] Error when creating a tenant in IS-KM

### ISSUE THREAD

**Issue by rksk** [wso2/product-apim#3644]
**Description:**
When trying to create a new tenant, following error log can be seen. Tenant creation is successful anyway.
> ERROR {org.wso2.carbon.apimgt.impl.ThrottlePolicyDeploymentManager} -  Error while deploying policy to global policy server.The service cannot be found for the endpoint reference (EPR) https://localhost:9443/services/EventProcessorAdminService

What happen here is, when a new tenant is created, it tries to deploy the throttle policies to the KM node itself which doesn't have event processor features. To fix this, we have to change below configuration in KM's api-manager.xml to point to Traffic Manager node.
```
<PolicyDeployer>
    <ServiceURL>https://localhost:${mgt.transport.https.port}${carbon.context}services/</ServiceURL>
    <Username>${admin.username}</Username>
    <Password>${admin.password}</Password>
</PolicyDeployer>
```
It is better to include this in the APIM docs for configuring IS as KM.

**Suggested Labels:**
Doc, Improvement

[1] https://docs.wso2.com/display/AM2xx/Configuring+WSO2+Identity+Server+as+a+Key+Manager
[2] https://docs.wso2.com/display/AM210/Configuring+WSO2+Identity+Server+as+a+Key+Manager
[3] https://docs.wso2.com/display/AM210/Configuring+an+External+IdP+as+a+Key+Manager
[4] https://docs.wso2.com/display/AM210/Configuring+an+External+IdP+as+a+Key+Manager

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
