### ISSUE TITLE
WSO2 API-M error on invoking published API with large message

### ISSUE THREAD

**Issue by nadastra** [wso2/product-apim#3648]
**Description:**
When calling a published API with large messages (10MB+), the call returns within 1-2 seconds with no error but API-M logs the error below. This behavior is not consistent as post API-M restart, the invocation is seen to be successful.  One or two messages from a large number of invocations also goes through.

Invoking the API directly with same messages is successful.

API-M error:

`[2018-08-23 17:22:56,690]  WARN -  Request message body data received while 
the handler is in an inconsistent state REQUEST_DONE 
{org.apache.synapse.transport.passthru.SourceHandler}

[2018-08-23 17:22:56,695]  WARN -  Trying to submit a response to an already 
closed connection : http-incoming-366 
{org.apache.synapse.transport.passthru.PassThroughHttpSender}
It appears that an erroneous state change is flagged while the input blocks are still being read.`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** wso2am-2.5.0

**OS, DB, other environment details and versions:**    
RHEL 7.3

**Steps to reproduce:**
Invoke a published API (all API & API-M config is default) with large message (>10MB).

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
