### ISSUE TITLE
Stats are not shown in API store when invoked using Default Application

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#3651]
Invoke api using the Default application. Following error is thrown . Stats are not shown in the store. For other users, application name is shown as '**undefine**'

Additionally, if two subscribers subscribe and invoke using **DefaultApplication** no one will see the stast in store

`[2018-09-02 16:20:19,515] ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (/store/site/blocks/stats/topUsers/ajax/stats.jag#51)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (/store/site/blocks/stats/topUsers/ajax/stats.jag#51)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at `

**Comment by chamilaadhi** [comment]
steps to reproduce
1. create default application and invoke an api
2. create new user and create a new application and invoke the api
3. now view stats. user who doesn't have the default app has an entry with "undefine"
<img width="1098" alt="screen shot 2018-09-02 at 10 19 24 pm" src="https://user-images.githubusercontent.com/4861150/44958473-5d987980-aefe-11e8-9f5f-c7cc74975b16.png">

Also stats are not shown in application usage page
<img width="806" alt="screen shot 2018-09-02 at 10 20 46 pm" src="https://user-images.githubusercontent.com/4861150/44958479-83258300-aefe-11e8-9e6a-a6a82881cf36.png">

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/carbon-apimgt/pull/5645
