### ISSUE TITLE
Publisher stats disappear after around 10-15 mins without doing a request

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#3652]
Steps

- Setup APIM with analytics and invoke an API.
- view stats on publisher (say API Usage ) . Stats can be viewed.
- Keep 10-15 mins without doing any request to the server
- Now view stats on publisher (say API Usage ) and stats are not visible this time

If a request is sent to the gateway again, stats starts to display again

**Comment by chamilaadhi** [comment]
Following query returns empty after some time `{"records":[]}` and as a result next query does not get executed
 
`{"appName":"APIM_ACCESS_SUMMARY","query":"from ApiUserPerAppAgg_SECONDS select AGG_TIMESTAMP order by AGG_TIMESTAMP limit 1;"}`

**Comment by tharikaGitHub** [comment]
Fixed with PR https://github.com/wso2/carbon-apimgt/pull/5644
