### ISSUE TITLE
MB store  mysql 5.7 DB script is missing from pack 

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#3661]
**Description:**
MB store  mysql 5.7 DB script is missing from pack 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:*2.1.0*

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
