### ISSUE TITLE
Advanced Endpoint config -> Message Content -> Format nodifications are not reflected through publisher UI

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#3664]
**Description:**
Advanced Endpoint config -> Message Content -> Format nodifications are not reflected through publisher UI.

**Affected Product Version:**
2.5.0

**Steps to reproduce:**
In Implement tab select 'HTTP/SOAP Endpoint' as endpoint type.
Expand Advanced endpoint configurations and under Message Content -> Format select SOAP 1.1 (or any). Save changes and revisit Advanced endpoint configurations. Message Content -> Format is set back to Leave As-Is

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
