### ISSUE TITLE
auto_increment keyword used in apimgt mssql db scripts

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#3672]
**Description:**
User cannot run existing api manager database scripts on a mssql database. 
AUTO_INCREMENT keyword has been used in SP_TEMPLATE table.

**Affected Product Version:**
wso2am-2.6.0-beta2-SNAPSHOT

**OS, DB, other environment details and versions:**    
MSSQL

**Steps to reproduce:**
Execute dbscript/apimgt/mssql.sql script on a mssql database.

**Comment by bhathiya** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5653
