### ISSUE TITLE
Publisher context validation doesnt happen anymore in 2.6.0

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#3681]
**Description:**
There is a validation in APIM publisher for context field, which is it cannot have {version} or /{version}. The validation does not happen anymore. Need to add the fix here. 

**Suggested Labels:**
2.x 

**Suggested Assignees:**

**Affected Product Version:*2.x*

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
