### ISSUE TITLE
Unable send JMS_EXPIRATION header using an tenant API

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-apim#3705]
**Description:**
We cannot send JMS_EXPIRATION header When we are using tenant API to publish messages to a JMS endpoint. We can add the JMS_EXPIRATION header by adding the following property to the synapse configurations.
`<property name="JMS_TIME_TO_LIVE" value="10" scope="axis2" type="STRING"/>
`

**Affected Product Version:**
2.1.0  

**Steps to reproduce:**
Create a sample API with JMS endpoint using tenant user.
Add `<property name="JMS_TIME_TO_LIVE" value="100000" scope="axis2" type="STRING"/>` property to the synapse configuraions.
Publish a message to the API and check for the JMS_EXPIRATION header.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/1854
