### ISSUE TITLE
Application sharing breaks store Analytics

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#3727]
**Description:**
When application sharing is enabled and the organization claim value is configured for a user, the store analytics graphs cannot be loaded for that particular user

**Comment by pubudu538** [comment]
This is fixed in APIM 2.6.0 with https://github.com/wso2/carbon-apimgt/pull/5599. APIM 2.5.0 is fixed with updates.

**Comment by iloshinik** [comment]
This is reproducible in APIM 2.2.0.
