### ISSUE TITLE
Sharing API in facebook is not working

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#3744]
**Description:**

Social sharing on facebook results in following error. 

"Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later."

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.0, 2.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Click on facebook icon on an API overview in store potal.

**Related Issues:**

**Comment by HiranyaKavishani** [comment]
The issue is not related to the product pack.
The Facebook API cannot resolve "localhost:9443" but it works fine when the relevant IP and port number is provided.
