### ISSUE TITLE
[Store][UI] Analytics drop-down error

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-apim#3747]
The drop-down icon in the analytics tab doesn't perform as expected (doesn't close).
<img width="200" alt="45539776-4f185f00-b828-11e8-9a57-4d81b674b9ce" src="https://user-images.githubusercontent.com/18033158/45673110-797b5c80-bb47-11e8-9545-6ace3a67fd57.png">

**Comment by tgtshanika** [comment]
This is fixed in the revamped UI of APIM 3.0.0.
