### ISSUE TITLE
Invalid Domain Name error when generating the JWT

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#3750]
**Description:**

When SAML bearer grant type is used and exchange that token to an OAuth token, token stored in the DB with SUBJECT_IDENTIFIER values appended with the prefix FEDERATED in IDN_OAUTH2_ACCESS_TOKEN table after refreshing the token.

**Suggested Labels:**

AM-2.2.0

**Comment by mefarazath** [comment]
Fixed with the changes done for https://github.com/wso2/product-is/issues/4189

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1000. Hence closing.
