### ISSUE TITLE
Cannot preview Implicit Grant Flow diagram

### ISSUE THREAD

**Issue by iaoiui** [wso2/product-apim#3757]
**Description:**
I found a link out in following page.
https://docs.wso2.com/display/AM210/Implicit+Grant

But other grant flow diagram is linked to a diagram in identity server documentation with following description.
'The grant type is further explained with the use of a sequence diagram here.'

Therefore , it should link to implicit grant page like other grant flow diagram, right?

I assume that what we should do is adding above description and linking to 
https://docs.wso2.com/display/IS530/Implicit+Grant.

![cantpreviewimplicitgrantflow](https://user-images.githubusercontent.com/6523614/45759180-4ed1f680-bc62-11e8-85c4-f493b1f605da.png)

Thanks

**Suggested Labels:**
doc

**Affected Product Version:**
APIM 1.1.0 to 2.6.0

**Comment by ruthryi** [comment]
We have checked repeatedly and ensured that the diagram is viewable. Please clear your browser cache and check again.

Do reach out to us if anything else needs to be done!
