### ISSUE TITLE
The provider can be change after creating a API

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#3766]
**Description:**
When user creates a API and  published it. It's possible to change the provider name while editing the API in the page source which leads to create a new API with same name with a any provider value.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Creare a API and publish it
Edit the API and change the provider name from browser source
You can see another API with same name gets created.

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5777/files
