### ISSUE TITLE
WSO2 startup error because of relative path start with repository/ within the code

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#3767]
**Description:**
When we use above way of starting the server we get some error regarding relative path which start with repository/ within the code.

We also have found out following classes having above path problem.

APITemplateBuilderImpl.java
ThrottlePolicyTemplateBuilder.java
APIUtil.java

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Comment out the cd to carbon home command in the server startup script and start the server.

**Related Issues:**

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5748
