### ISSUE TITLE
Tags going out of page

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#3770]
**Description:**
On creation of multiple tags in the publisher console of APIM 2.2.0, the tags are going out of the layout.
In the Publisher's overview tab of the relevant API tag field going out of the page. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create an API with quite a number of tags. 

**Related Issues:**

**Comment by tgtshanika** [comment]
This is fixed.
Fixed version : 3.0.0
