### ISSUE TITLE
Add 'Hit Count' to API Usage by Resource Path table in APIM Store Analytics

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#3771]
**Description:**
Add a column to view API hit count to store analytics, API Usage from Resource Path view.

existing view
![stat](https://user-images.githubusercontent.com/28379317/45995709-cd8dc000-c0b6-11e8-80fd-deafa9b2ed14.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
Already fixed with https://github.com/wso2/carbon-apimgt/commit/0b3ccaa7e5914adbd1ade224fc676c5ffe9608a3#diff-7b14c560e19194431e287107d4449983
Hence closing.
