### ISSUE TITLE
Fix handling POST request without Content-Type for Token API to support backward compatibility

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#3773]
**Description:**
POST requests without Content-Type gets handled as application/octet-stream which has caused "/token" API calls to fail. This is introduced with the fix done [1] at synapse level to comply with HTTP spec.

As per the specifications, it is mandatory to send the Content-Type to the Token Endpoint for the client. But in the AM 1.10.0, we had no issues with this as we were setting the Content-Type as application/x-www-form-urlencoded in synapse level, if no Content-Type is provided with the request.

In AM 2.2.0, product teams have fixed this in to correct behavior as specification and now it is mandatory to send the Content-Type with the request (if it is not sent "application/octet-stream" will be set by-default. ). But in order to preserve the backward compatibility, Content-Type will need be set as  "application/x-www-form-urlencoded" if no Content-Type header was sent with the request.

[1] https://github.com/wso2/wso2-synapse/pull/1015

**Affected Product Version:**
APIM 2.2.0

**Steps to reproduce:**
Call /token endpoint without adding the Content-Type header. (some clients like cURL will add Content-Type header as "application/x-www-form-urlencoded" by default, but Postman will not )

**Comment by Prasadi-R** [comment]
The same issue has been reported in APIM 2.1.0 version.
