### ISSUE TITLE
When role name has spaces Publisher access control can not be configured

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#3774]
**Description:**

When the role name consists of spaces, publisher access control does not work.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1) Configure IS ldap as a secondary userstore in APIM
2) Create a role name with spaces in that secondary userstore. Assign publisher/creator permissions.
3) Create a user in that secondary userstore and assign the above-created role
4) Login to the publisher with the above user
5) Enable publisher access control and provide the role name with spaces created in step 2

Error can be seen in publisher UI.

**Related Issues:**

**Comment by kavishkafernando** [comment]
Public commit : https://github.com/wso2/carbon-apimgt/commit/c24e2ca2b46b9105990c549923fc312707173a8b
