### ISSUE TITLE
Support for  aspNet5, spring, haskell  languages in SDK generation is missing

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#3775]
**Description:**
During the orbit bundal creation these languages resources wasn't copied to orbit bundle. We need to make sure all the resources are getting copied from orginal swagger codegen library
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
latest openapi-generator 4.0.1.wso2v2 https://github.com/wso2/orbit/blob/master/openapi-generator/4.0.1.wso2v2/pom.xml exposes all these 

https://github.com/wso2/carbon-apimgt/blob/master/pom.xml#L1702
