### ISSUE TITLE
XACML Scope Validator option is not available in the WSO2IS-KM-5.6.0

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-apim#3777]
**Description:**
XACML Scope Validator option is not available in the WSO2IS-KM-5.6.0 pack when trying to create an SP and access to Inbound Authentication Configuration --> OAuth/OpenID Connect Configuration --> Configure --> try to choose XACML Scope Validator.

This is because of the identity.xml file of the WSO2IS-KM-5.6.0 pack having the below property in the identity.xml file.

`OAuthScopeValidator class="org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator`

This property gets prioritized and scopes are getting read from here though the following property is also available in the identity.xml file.

```
<ScopeValidators>
            <ScopeValidator class="org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator" />
            <ScopeValidator class="org.wso2.carbon.identity.oauth2.validators.xacml.XACMLScopeValidator"/>
</ScopeValidators>
```

Removing the property, "**OAuthScopeValidator class="org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator**" from the identity.xml file of the WSO2IS-KM-5.6.0 pack and restarting the server will solve the problem. 

**Suggested Labels:**
IS-KM

**Affected Product Version:**
IS-KM-5.6.0
IS-KM-5.5.0

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
