### ISSUE TITLE
Stack trace exposed in the browser developer console when trying to unsubscribe API from an application

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#3788]
**Description:**

Stack trace is exposed as an error responce when invalid application is passed to the **subscription-remove** request.

**Suggested Labels:**
2.5.0
Type/Improvement

**Affected Product Version:**
* 2.5.0

**Steps to reproduce:**

* Change application ID to invalid application ID which is locate inside the application.js file in below location,
wso2am-2.5.0/repository/deployment/server/jaggeryapps/store/site/themes/wso2/js
* Try to unsubscribe an API from Apim-store
* Observe the output in the network tab of developer console.

**Comment by TanyaM** [comment]
The same behaviour is observed in multiple places in the store , publisher and admin apps. This issue will be used to track all those scenarios.

**Comment by TanyaM** [comment]
Fixed in carbon-apimgt 6.x branch
