### ISSUE TITLE
Sequences not sorted in Ascending order in Publisher

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#3791]
**Description:**
In the Publisher UI, while selecting the mediation flows, the global sequences are not in sorted order. This happens only when the registry is mounted. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM 2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nalakas** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/5822
