### ISSUE TITLE
Rest api for SOAP to REST feature

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-apim#3793]
**Description:**
Need to add the publisher RestFul apis support to create apis using SOAP to REST feature

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamindias** [comment]
Related PR : https://github.com/wso2/carbon-apimgt/pull/5814
