### ISSUE TITLE
Error while downloading WSDL using the Store with a secondary domain user in a tenant. 

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#3795]
**Description:**

APIUtil Failed to get API artifact from : /apimgt/applicationdata/provider/admin-AT-token.com/testing/1/api

org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/governance/apimgt/applicationdata/provider/admin-AT-token.com/testing/1/api

Above Error produces when trying to download the WSDL of a SOAP API using the Store for a user created in a secondary user store under a tenant (not super tenant).

**Suggested Labels:**

AM-2.5.0

**Steps to reproduce:**

Create a tenant and add a secondary user store under it and create a user in the secondary user store. create a SOAP API using the secondary user and try to download the WSDL file from the store.

**Comment by rextca** [comment]
Thanks, Jones.  I had looked at that update a couple of times, but I decided that it probably didn't apply, since we don't have any tenants set up.

I have a meeting with the team tomorrow and we'll decide how to proceed and whether we need help with WUM, then I'll update the ticket.

Rex
