### ISSUE TITLE
WSO2 API Manager Scopes for Federated Users

### ISSUE THREAD

**Issue by hastef88** [wso2/product-apim#3816]
**Description:**
I have WSO2 API Manager federated setup with Azure AD. I can use the implicit and code grant type to generate the access tokens.

Now I want to use the WSO2 API Manager scope functionality to limit the access on certain API resources. I have created the role in API manager and added the scope on API publisher for the API resource. But when I generate the access token using scope value, it doesn't return the token with correct scope. But if I assign the local user to that role and generate the access token it works fine.

I wonder if WSO2 API manager support scope management for Federated users.

Any help would be appreciated.

**Suggested Labels:**
apim-2.5.0, IS 5.6.0

**Suggested Assignees:**

**Affected Product Version:**
APIM-2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gusto2** [comment]
To be checked: 

 - You can create an inbound provisioning - IS will store external users into a local database including their roles from (saml) assertions. To access local claims from federated users you may update repository/conf/identity/identity.xml  check MapFederatedUsersToLocal element or SAML/UserType

 - there was a java property attribute enabling mapping user roles directly from SAML assertions, though I am unable to recall right now, needs to be found

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
