### ISSUE TITLE
APIM adds a Content-Type header to DELETE requests

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#3843]
**Description:**

When sending a DELETE request without a Content-Type header the message gets sent out from the APIM with the Content-type as application/octet-stream (APIM 2.5.0) / application/x-www-form-urlencoded (APIM 2.2.0).

**Affected Product Version:**
AM 2.2.0
AM 2.5.0

**Comment by malinthaprasan** [comment]
Duplicated with #3983

**Comment by SupunTharakaSandaruwan** [comment]
The same behavior can be observed with APIM 2.0.0 as well.

- DELETE request without a Content-Type header the message gets sent out from the APIM with the Content-type as / application/x-www-form-urlencoded (APIM 2.0.0).
