### ISSUE TITLE
Default subscription tiers are not created automatically in tenant mode in distributed setup

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#3857]
**Description:**
Default subscription tiers are not created automatically in tenant mode in distributed setup

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:** APIM 2.6.0 WUM updated version

**OS, DB, other environment details and versions:**    Ubuntu 18.04, mysql

**Steps to reproduce:**
1. Create a fully distrbuted setup
2. Add a new tenant from publisher
3. Login to publisher before logging into the carbon console.
4. Try to deploy the sample API. Sample API deployement fails with a front end error, due to missing tiers

**Related Issues:**
None

**Comment by bhathiya** [comment]
This can happen is the `AuthManager` configuration in the publisher portal is configured to point to the KM. Then the tenant loads in KM and throttling policies are not getting published to TM. 

Making that configuration default (i.e. localhost) should fix the issue.
