### ISSUE TITLE
[APIM 2.5.0] API are not visible to LDAP roles with spaces when Publisher Access Control Enabled 

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#3858]
**Description:**
1. When entering a role with spaces into the "Access Control" section, in the "Visible to Roles" box, on a save, the spaces are removed. When the page is refreshed the spaces are gone and when you click in the box and there is an error saying "Invalid role name[s] ..."

2. When  change the Access Control to a role with spaces, and then log into the Publisher site, the APIs that are under the defined roles are not visible to a user with the role .

**Comment by HiranyaKavishani** [comment]
It was fixed

**Comment by isharac** [comment]
Could you please add a comment with the PR for tracking purpose?

**Comment by HiranyaKavishani** [comment]
related Issue: https://github.com/wso2/carbon-apimgt/issues/5812 

Fixed in
https://github.com/wso2/carbon-apimgt/commit/848546aed8e8e2ee19a384a9ca67147eb3628236

**Comment by isharac** [comment]
Closing the issue as it is fixed.
