### ISSUE TITLE
Issue with Shared Applications in ApiStore with same names

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#3869]
**Description:**>

 when sharing applications across users from the Store, if the shared applications have the same name then there's issues accessing them through the Store.
For example, 
User A - has an application called TestApp
User B - has an application called TestApp
User B shares this application with User A
If user A (who can now see both TestApp from the UI) deletes their own TestApp, then User B also has their application deleted.

**Comment by npamudika** [comment]
Fixed with the above mentioned PRs.
