### ISSUE TITLE
Wrong header content in "WWW-Authenticate" header when the subscription is blocked.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#3871]
**Description:**

When the subscription is blocked for a API using the publisher, when invoking such API, the response sends back to the client have the "WWW-Authenticate" header as [OAuth2 realm="WSO2 API Manager", error="invalid token", error_description="The access token expired"] which contains wrong information.

**Suggested Labels:**

AM-2.1.0

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
