### ISSUE TITLE
Implement tests for APIM React applications

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3892]
**Description:**
The word _testing_ in the $subject refers to both UI Testing and React Component functional testing.
We need to come up with a test framework(2) to cover both aspects.

Suggestion for libraries:

- https://jestjs.io/

**Related Issues:**

- https://github.com/wso2/product-apim/issues/2661

**Comment by tmkasun** [comment]
Check the feasibility of using [nightwatchjs](https://nightwatchjs.org/) for webdriver based E2E testing

**Comment by tmkasun** [comment]
The end-to-end testing framework, tools etc.

- [cypress](https://docs.cypress.io/guides/overview/key-differences.html#Architecture)
  - [Jest integration](https://github.com/cypress-io/cypress/issues/281)
- [puppeteer](https://github.com/GoogleChrome/puppeteer)
  - [Settingup](https://itnext.io/testing-your-javascript-in-a-browser-with-jest-puppeteer-express-and-webpack-c998a37ef887)

**Comment by tmkasun** [comment]
Available libraries for mocking data for API testing:

- https://github.com/stoplightio/prism
- https://github.com/Redocly/openapi-sampler

**Comment by chanaka3d** [comment]
The test framework and few tests are available with the publisher and devportal from 3.1.
