### ISSUE TITLE
Second request fails if the first request is GET with body and through the same connection

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-apim#3893]
**Description:**
The second request sents a HTTP 400 bad request from the API GW when the first request is GET with the payload and through the same connection.

**Suggested Labels:**
Priority/High
Severity/Critical

**Affected Product Version:** APIM 1.9.0

**Steps to reproduce:**
Refer [1] under related issues in order to reproduce the issue. 

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4668

**Comment by yhilem** [comment]
Hi,
Please can you tell us when this issue will be fixed?
We have same issue with Kafka-REST that uses "GET with payload to get topic offset".
Thanks
Youcef HILEM

**Comment by praminda** [comment]
Hi @shefandarren , @yhilem 

This issue is already fixed in never versions of APIM [1] (in 2.x series). Let us know if you have the same issue in later versions of the APIM
https://wso2.org/jira/browse/ESBJAVA-4716

Thanks,
Praminda
