### ISSUE TITLE
Provide a meaningful error message when forward slash is added while building the microgateway project. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#3894]
**Description:**
When following [step3](https://docs.wso2.com/display/AM260/Microgateway+Quick+Start#MicrogatewayQuickStart-GenerateadistributionforasingleAPI), if the project is built as follow with a forward slash, it provides the following error message which misleads the user. 
`micro-gw build <project_name>/`
eg: `micro-gw build pizzashack-project/`

```
Error: 
Compiling source
    src:0.0.0
Compiling tests
    src:0.0.0
 could not find package wso2/gateway:*
Running tests
    src:0.0.0
 No tests found
Generating executable
    ./target/pizzashack-project/.balx
ballerina: failed to write the compiled program to '/Users/IsuruUyanage/Desktop/Support/Rotation2/NIJIFRDEV-198/cus/wso2am-micro-gw-2.6.0/bin/pizzashack-project/target/pizzashack-project/.balx'
micro-gw: Internal error occurred while executing command.
```

Therefore, please provide a meaningful error message. 

**Suggested Labels:**
Priority/High
Type/Improvement
Severity/Major

**Affected Product Version:**
wso2am-2.6.0

**Steps to reproduce:**
1. Follow the steps in https://docs.wso2.com/display/AM260/Microgateway+Quick+Start
2. In Generate a distribution for a single API section, when executing the steps 3, build the project as below with a forward slash in the end. 
`micro-gw build pizzashack-project/`

**Comment by isharac** [comment]
Fixed.
