### ISSUE TITLE
 Missing primary key in some tables

### ISSUE THREAD

**Issue by SaubhagyaW** [wso2/product-apim#3923]
**Description:**
Mysql InnoDB cluster requires a primary key for each table to work and below tables don't set a primary key.
REG_RESOURCE_COMMENT
REG_RESOURCE_RATING
REG_RESOURCE_TAG
REG_RESOURCE_PROPERTY
UM_SHARED_USER_ROLE
AM_API_SCOPES

**Note:** Any migration scripts related to this should be fixed as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
The issue was identified in APIM 2.1.0, other versions should also be verified.

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-is/issues/3898

**Comment by isharac** [comment]
Duplicate in https://github.com/wso2/product-apim/issues/9505
