### ISSUE TITLE
Command to check the current export path CLI Tool

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3924]
**Description:**
Currently we can set the export path using the following command [1] . However, it will be good if the user has another command to be able to view what the current export directory has been set to.
apimcli set --export-directory <export-directory-path>

[1] https://docs.wso2.com/display/AM260/Migrating+the+APIs+and+applications%20to+a+Different+Environment#MigratingtheAPIsandApplicationstoaDifferentEnvironment-Setexportdirectory

**Suggested Labels:**
Improvement

**Suggested Assignees:**
Praminda

**Affected Product Version:**
APIm 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
