### ISSUE TITLE
404 on documentation links

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#3925]
**Description:**
When access Management Console and click on the Help in the right top corner it redirects to 404 Not Found. 
Please find below some of the not found links,
https://(HOST)/carbon/userstore/docs/userguide.html
https://(HOST)/carbon/identity-claim-mgt/docs/userguide.html
https://(HOST)/carbon/application/docs/userguide.html
https://(HOST)/carbon/idpmgt/docs/userguide.html 
(Accesibility of above links are depend on the version)

**Suggested Labels:**

**Affected Product Version:**
Some of the help link in
2.6.0, 2.5.0, 2.2.0, 2.1.0

**Steps to reproduce:**
(As an example)
- Access to the management console
- Click on the list under users and roles under the main tab
- Click Help in the right top corner

**Related Issues:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
