### ISSUE TITLE
_threat_fault.xml sequence is not getting copied into tenant space during tenant creation time

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#3927]
**Description:**
_threat_fault.xml sequence has to be copied as a default sequence in tenant space, during tenant creation time. But the file is not getting copied to tenant's synapse config locatin.

**Comment by pubudu538** [comment]
@SParaparan Could you please add more details to the github issue? This is not enough for the product team to investigate about the issue.

**Comment by vithu30** [comment]
Reopened the issue as this is not fixed in 2.6.0
