### ISSUE TITLE
RegularExpressionProtector documented patterns prevent valid requests from proceeding

### ISSUE THREAD

**Issue by erandiganepola** [wso2/product-apim#3930]
**Description:**
Recently a customer wanted to combine all the regex patterns to detect all kinds of threats at once. As a solution (since the current implementation don't allow specifying multiple sequences for each threat type) I combined all the documented regex patterns to one:

> *'.*|.*ALTER.*|.*ALTER TABLE.*|.*ALTER VIEW.*|.*CREATE DATABASE.*|.*CREATE PROCEDURE.*|.*CREATE SCHEMA.*|.*create table.*|.*CREATE VIEW.*|.*DELETE.*|.*DROP DATABASE.*|.*DROP PROCEDURE.*|.*DROP.*|.*SELECT.*|.*#include.*|.*#exec.*|.*#echo.*|.*#config.*|.*Exception in thread.* | .*'.*|.*or.*|.*1=1.*|.*SELECT.*|&lt;\s*script\b[^>]*>[^&lt;]+&lt;\s*/\s*script\s*>|/?(ancestor(-or-self)?|descendant(-or-self)?|following(-sibling))

As you may notice, it contains patterns like **.*or.***, **.*select.*** (coming from XPath Injection pattern) and etc which prevent the request from having any word containing _or_ or _select_ and etc.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Follow the [documentation](https://docs.wso2.com/display/AM250/Regular+Expression+Threat+Protection+for+API+Gateway) as in below steps
- Editing the sequence through registry artifacts
- Applying the Regular Expression Policy
- Testing the regex threat protector

I deployed the sample api (pizzashack API) in APIM and used the following curl request (the default post request):

`curl -k -X POST "https://localhost:8243/pizzashack/1.0.0/order" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer xxxx" -d "{ \"customerName\": \"string\", \"delivered\": true, \"address\": \"string\", \"pizzaType\": \"string\", \"creditCardNumber\": \"string\", \"quantity\": 0, \"orderId\": \"string\"}"`

**Related Issues:**
#3406

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
