### ISSUE TITLE
Active scanning through ZAP of the developer portal 

### ISSUE THREAD

**Issue by nmarher** [wso2/product-apim#3933]
**Description:**

Hello, 

Three vulnerabilities have been detected in the WSO2 developer portal api manager through the tool: OWASP ZAP. We attached analysis report. 
Could you help us solve these vulnerabilities? 
Thank you. 

[zapWSO2Portal.zip](https://github.com/wso2/product-apim/files/2548288/zapWSO2Portal.zip)

**Affected Product Version:** API Manager 2.5.0 

**Steps to reproduce:**
 Introduce the url of the developer portal here:
![image](https://user-images.githubusercontent.com/22592848/47997566-94f0f580-e0fc-11e8-9fa9-218f0e749ab8.png)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
