### ISSUE TITLE
Abstract the Tenant name in the API URL context

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-apim#3957]
**Description:**
The requirement to customize the API URLs by abstracting out the tenant context (/t/{tenant-domain}) from the URL, seems to be a common use-case among several customers. Therefore it would be better if we can add the following information to the official APIM docs, for any future references.

Sample use-case.

Default URL of an API deployed in the tenant domain

http://<host-name>:8280/t/{tenant-domain}/{api-name}

Required customized URL

http://<host-name>:8280/{api-name}

This requirement can be catered by using a reverse proxy such as NGINX.

Following is a sample server configuration in NGINX which defines rules to proxy requests.

server {
       listen 8280;
       server_name <host_name>;
   
        location / {
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Server $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header Host $http_host;
           proxy_pass http://<host_name>:8280/t/{tenant-domain};
           proxy_redirect  http://<host_name>:8280/t/{tenant-domain} /;
       }

This can go under section "Load Balancer, Revers Proxy configuration scenarios" in [1].

[1] https://docs.wso2.com/display/AM250/Configuring+the+Proxy+Server+and+the+Load+Balancer

**Suggested Labels:**

Docs/No Impact
Priority/Normal
Type/Improvement

**Suggested Assignees:**

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if this still a requirement with the latest version.
