### ISSUE TITLE
Unable To Use API Import Export 2.2.0 v4

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#3967]
**Description:**
Cannot export or import an API using APIM tool. Generating an error when executing command through Postman.

**Affected Product Version:**
APIM 2.2.0 

**Steps to reproduce:**
Use Postman to execute import export command (through the provider).
Gives an export error.

**Comment by HiranyaKavishani** [comment]
It was fixed by https://github.com/wso2/carbon-apimgt/pull/5428
