### ISSUE TITLE
The API name appears incorrectly after creating the API with Chinese letters

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#3969]
**Description:**
Created a API with API name "电话验证" (Chinese letters).  But API created with name "????".
 After API manager 2.0.0 release product allows API creation with any language (for H2 DBs ) without any configurations. [1]

[1] https://medium.com/working-with-wso2-products/how-to-use-non-english-languages-with-wso2-api-manager-851a3124c436

**Suggested Labels:**
Type/bug
Priority/High

**Affected Product Version:**
 2.6.0

**DB:**
H2

**Steps to reproduce:**
1. Create the API with name "电话验证" and all mandatory values.
2. Check created API name

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
