### ISSUE TITLE
Advanced Policies" reset throttle bandwidth unit on editing

### ISSUE THREAD

**Issue by tdkmalan** [wso2/product-apim#3979]
**Description:**
Advance throttle policy added with bandwidth in MB [1], but when editing the same policy UI shows the bandwidth unit as KB [2]
So I believe that this need to patched since this is a valid requirement.

**Suggested Labels:**
APIM 2.5.0

**Affected Product Version:**
APIM 2.5.0

  
**Steps to reproduce:**
Steps to reproduce :

Access the admin console @ .../admin
Menu -> Throttling Policies -> Advanced Policies
Enter details of a new policy, ensuring that 
Type = Request Bandwidth
Bandwidth Unit = MB
all other fields can sensibly default
Save the policy
Locate the policy in the list and click 'Edit'
Bandwidth Unit = KB (the default option), should be MB

**Comment by HiranyaKavishani** [comment]
This is not applicable in master
