### ISSUE TITLE
WSO2 API Manager JMX “SendingFaultTable” and "ReceivingFaultTable" doesn't return all errors

### ISSUE THREAD

**Issue by alexandrejuma** [wso2/product-apim#3985]
**Description:**

WSO2 API Manager JMX “SendingFaultTable” and "ReceivingFaultTable" doesn't return all errors specified in https://docs.wso2.com/display/AM260/Error+Handling

Other documented errors, such as transport errors (i.e: 101503 in SendingFaultTable), are being added to JMX Metrics but not others API handler error codes for example.

Don't know if this is a Bug or a Feature Request because I'm not sure if there's some reason for some error codes being recorded while others aren't. Anyway it would be great if JMX would record all Faults.

**Suggested Labels:**

2.5.0, Type/BUG

**Affected Product Version:**

API-M Version: 2.5.0

**OS, DB, other environment details and versions:**    

Operating System: Red Hat Enterprise Linux Server release 7.5 (Maipo)
Java Version: OpenJDK 1.8.0_171

**Steps to reproduce:**

1. Configure a tight throttling policy in some API-M Endpoint
2. Stress the API until you get 90080x error (Message throttled out)
3. Check that JMX Metrics (SendingFaultTable and ReceivingFaultTable) for Endpoint has no recorded faults

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
