### ISSUE TITLE
DISABLE_CHUNKING property is not passing content-length header to the back-end  intermittently

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#3998]
**Description:**
Disable chunking property is not passing content-length header when we send the requests with large payloads (conent length more than 40000).Also this behavior is intermittent. 

This can happen due to content length header being set before the PassThroughHttpSSLSender calculates the message size. If it takes longer time to content-length calculation and if the the TargetRequest start is executed before that, the "Transfer-Encoding" header will be sent.

**Steps to reproduce:**
Create an API with a POST resource.
Add a mediation extension (in sequence) with following property

<property name="DISABLE_CHUNKING" value="true" scope="axis2"/>

Invoke the API in high frequence with the large payload.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
