### ISSUE TITLE
[DB Scripts] CON_APP_KEY constraint contains TOKEN_ID column

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#4006]
**Description:**
 A token field is included(TOKEN_ID) in the CON_APP_KEY constraint definition, which leads to allow multiple access tokens even other constraints are unique(i:e same grant type, same user, the same set of scopes but 2 access tokens).
This issue is there in [oracle_rac.sql](https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/oracle_rac.sql#L99), [postgresql.sql](https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/postgresql.sql#L95) and [oracle.sql](https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/oracle.sql#L99) scripts
This issue has observed in  an IS-as-KM cluster with high concurrency level(~200 identical token requests)

**Affected Product Version:**

- Latest IS-KM server ATM

**OS, DB, other environment details and versions:**    
- Oracle 12C rac

**Steps to reproduce:**
- Create an Application from API Manager store
- Make burst of an access token requests with client credential grant type
- You will see multiple access token records created for the same application

**Comment by mefarazath** [comment]
Related to https://github.com/wso2/product-is/issues/4197
