### ISSUE TITLE
JDBC Deadlocks when Updating API scopes in APIM 2.1.0

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#4012]
**Description:**

Deadlocks occur intermittently when updating API scopes.

TID: [-1234] [] [2018-11-18 17:37:42,266] ERROR {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO} -  Error occurred while creating scopes  {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO}
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

**Suggested Labels:**

Bug

**Affected Product Version:**

APIM 2.1.0

**Steps to reproduce:**

This can be reproduced when performing long running tests of creating/updating/deleting API's.

**Comment by chamindias** [comment]
PR : https://github.com/wso2/carbon-apimgt/pull/5883

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5883
