### ISSUE TITLE
Icon '*' to  all mandatory fields.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#4027]
**Description:**
This is as a UI enhancement. Some of the mandatory fields  in the UI not mention with the icon '*'. Specially fields are that mandatory but they set with the default values. 
Ex: API publisher design page ,
-Visibility on Store filed
-Resources fled

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
