### ISSUE TITLE
Regex Threat Protector causing higher load average and unresponsive gateway

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#4031]
**Description:**
Regex Threat Protector causing higher load average and unresponsive gateway [1]
[1] https://docs.wso2.com/display/AM250/Regular+Expression+Threat+Protection+for+API+Gateway

**Suggested Labels:**
product-apim

**Affected Product Version:**
2.5.0, 2.2.0

**Comment by HiranyaKavishani** [comment]
Doc should have to mention below noted features regarding system properties.

1. Payload size limit (in KB) has to be given with system property 
    "payloadSizeLimitForRegexThreatProtector", when starting the server.

2. Tenants who are allowed to use the Regular Expression Threat Protector mediator has to be given with the system property "regexThreatProtectorEnabledTenants" as comma separated values when starting the server.
e.g.  ./wso2server.sh -DregexThreatProtectorEnabledTenants=wso2.org,abc.com -DpayloadSizeLimitForRegexThreatProtector=5

Those are optional properties. And if they are not set, those limitations will not be applied.

**Comment by npamudika** [comment]
Fixed in 2.6 version
