### ISSUE TITLE
Can't get the created API list after attempt to creat a API with  too long  value for API vesion.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#4037]
**Description:**
Attempt to create API with more than 30 character for  API version name, gives JdbcSQLException at  get all API request. Existing  API not display in the API publisher page. 

error:
2018-12-03 16:06:42,428] ERROR - ApiMgtDAO Unable to find the API: admin-test3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb in the database
[2018-12-03 16:06:42,429] ERROR - index:jag org.wso2.carbon.apimgt.api.APIManagementException: Unable to find the API: admin-test3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb in the database

bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb  = the version which contain more than 31 characters
test3 = API name that I try to create with above version name 

**Suggested Labels:**
Label: Product scenario

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    
H2 DB, Ubuntu OS

**Steps to reproduce:**
1. Create a API with valid data for mandatory fields
2. Attempt to create another API with more than 30 characters for version name 
3. Navigate to the All API page.

Expected Result:
Page display created API

Actual Result:
Created API not displayed

**Related Issues:**
Can be see the same behavior when attempt to create a API with more than 255 characters for API name.

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
