### ISSUE TITLE
API publish can be done with invalid endpoint url

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#4048]
**Description:**
API publish can be done with the invalid endpoint url for sandbox and production. 

**Suggested Labels:**
Product Scenario

**Affected Product Version:**
APIM 2.6

**OS, DB, other environment details and versions:**    
DB: H2

**Steps to reproduce:**
01. Design API in API publisher
02. Implement API with invalid production or sand box endpoint url (Ex: testurl)
03. Publish the API

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
