### ISSUE TITLE
Create a REST api with the resource which has not allowed special characters

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#4051]
**Description:**
Create a REST API from scratch by providing the API name, version, context and at least 1 resource. Resource should not contain invalid characters

Currently resource path support all special characters and strings, no validation. 
For e.g.
GET: /$#%^&*
GET: /!)-(#[']"

**Suggested Labels:**
Product-scenario
Type/bug
Priority/Highest

**Affected Product Version:**
apim-2.6.0

**OS, DB, other environment details and versions:**

**Comment by HiranyaKavishani** [comment]
This is not applicable in master
