### ISSUE TITLE
Dynamic SSL Certificate Installation option available in the UI for  dynamic endpoint types.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#4052]
**Description:**
Dynamic SSL Certificate Installation feature supports only HTTP/REST and HTTP/SOAP endpoints. But in the UI "manage certificate " option is available for dynamic endpoint also

Reference: https://docs.wso2.com/display/AM260/Dynamic+SSL+Certificate+Installation 

**Suggested Labels:**
Type/product scenario
Type/UX
Type/Bug
Severity/Major
version/2.6

**Affected Product Version:**
2.6 

**Steps to reproduce:**
1. Log in to the API publisher
2. Design API
3. Navigate to the implement API tab
4. Select the end point type as dynamic

Expected result:
Manage certificate option should  be unavailable

Actual result:
Manage certificate option available.

**Comment by dushaniw** [comment]
This is fixed in the latest 3.1.0-Alpha. We do not allow adding endpoint certificates if the endpoint is dynamic.
![Screenshot from 2020-02-11 17-35-22](https://user-images.githubusercontent.com/12208083/74235433-fab33080-4cf4-11ea-9b6c-93b54bc1df0f.png)

Hence closing the issue.
