### ISSUE TITLE
Wrong word: "Proper Value" in  API Store Additional Property Table

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#4055]
**Description:**

**Proper Value**  Should be corrected as **Property Value**
![image](https://user-images.githubusercontent.com/2655553/49543522-107dc800-f89e-11e8-908f-e403a64afdd8.png)

**Affected Product Version:**
2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Add some additional attributes to an API
1. Visit the API page in the Store and observe the additional property table

**Comment by nimanthag** [comment]
### Developer testing record.
<img width="1677" alt="screen shot 2018-12-06 at 9 28 52 am" src="https://user-images.githubusercontent.com/42195796/49560926-89caf880-f93a-11e8-90f4-2caef56c531d.png">
