### ISSUE TITLE
Binary data receiver accepts requests before Traffic Manager fully up

### ISSUE THREAD

**Issue by lasanthaS** [wso2/product-apim#4062]
**Description:**
When the binary data receiver is used in the Traffic manager, throttling fails since the data receiver accepts requests before the Traffic manager is fully up and running.

**Suggested Labels:**
Bug

**Affected Product Version:**
API Manager 2.2.0

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-analytics-common/pull/575
