### ISSUE TITLE
Issue when publishing API through proxy

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4068]
**Description:**
Issue when publishing API to external store through proxy. Configured proxy related parameters are not used when creating httpclient.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
Fixed
