### ISSUE TITLE
Add Observability feature for version 2.2.0

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/product-apim#4073]
**Description:**
At the moment Observability feature[1] is available for versions 2.10, 2.5.0 and 2.6.0 except for 2.2.0. We have to enable this feature for version 2.2.0.

**Affected Product Version:**
APIM 2.2.0

[1]https://docs.wso2.com/display/AM260/Working+with+Observability

**Comment by dushaniw** [comment]
Available in latest wum of 2.2.0.
