### ISSUE TITLE
API State Change Flow Problem when reject the workflow request  

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#4079]
**Description:**

If configured a workflow for API state change[1] and It is working fine when approved the request for API State change action(Published or Blocked) by the admin user other states changing or action will working fine such as "deploy as a prototype", "Demote to Created" and "Deprecated".

However if we "Rejected" any workflow requests regarding state changing(Published or Blocked) before doing any other actions like deprecated, demote or deploy as a prototype, those actions update will fail and show the below UI error. But we cannot see any other error from the backend side of APIM or BPS. 

![hapoalimprodsub](https://user-images.githubusercontent.com/15210142/49816697-74b7f480-fd94-11e8-982d-3d580dd97389.png)

**Suggested Labels:**

BUG

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Configure the workflow for API state changing[1]
2. Created an APi and tried to publish the API, then it will send workflow request to admin
3. Visit to Admin portal and reject it
5. Back to Publisher UI and instead of trying to publish, change the action as "Deploy as a Prototype"
6. Then you can see the above UI error and check both backends from APIM and BPS, there are no errors appearing. 

[1]. https://docs.wso2.com/display/AM220/Adding+an+API+State+Change+Workflow

**Comment by tgtshanika** [comment]
Fixed
