### ISSUE TITLE
Quotes in claims are not properly escaped in JWT

### ISSUE THREAD

**Issue by rksk** [wso2/product-apim#4085]
**Description:**
When [passing enduser attributes to the backend using JWT](https://docs.wso2.com/display/AM1100/Passing+Enduser+Attributes+to+the+Backend+Using+JWT), if a user claim has quotes (") in the value, it is not properly escaped in the JSON produced for the JWT.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
APIM 1.10.0

**Steps to reproduce:**
1. Configure AM 1.10 (IS as KM) to [produce JWT tokens for backend](https://docs.wso2.com/display/AM1100/Passing+Enduser+Attributes+to+the+Backend+Using+JWT)
2. Add a user who has quotes in one of the claims (e.g: street address)
3. Generate an OAuth token for the user
4. Use the OAuth token to invoke an API through AM
5. Observe the generated JWT token for the backend

**Comment by tgtshanika** [comment]
This is fixed in API 2.6.0
