### ISSUE TITLE
[subscription tier] Request rate value for burst control limit can be added more than the quota allocation.

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#4086]
**Description:**
Updating a burst control with more than allocated quota is successfully saved. As in below example
 quota allocation = 1000/min
 request rate = 1001/min
 (see the image)
Expected: It should validate not to add burst control limit as more than the allocated quota.

**Suggested Labels:**
Type/bug
Priority/High
Product-scenario

**Suggested Assignees:**

**Affected Product Version:**
2.6.0 wum updated (1544376048263)

**OS, DB, other environment details and versions:**    

[1]
![burst](https://user-images.githubusercontent.com/15671620/49867930-f01bb380-fe31-11e8-89a1-b6082721de4a.jpeg)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
