### ISSUE TITLE
UX issues in APIM analytics dashboards

### ISSUE THREAD

**Issue by chalitha1989** [wso2/product-apim#4091]
**Description:**
Need to improve some of the graphs in analytics dashboards.

1. Time range in 'Created APIs Over time' graph is not descriptive enough. Date range is from 2015 but the graph doesn't have the year information. 

<img width="1632" alt="created apis over time" src="https://user-images.githubusercontent.com/13028527/49982430-82cb6800-ff82-11e8-86df-7d207050680d.png">

2. 'Faulty invocation' graph is confusing to some users since the faults are stacked on top of successes. Users misinterpreted this as there were higher number of failures than the successes. Need to check whether we can improve this chart or change the chart type to a simple bar chart.

<img width="571" alt="faulty invocation" src="https://user-images.githubusercontent.com/13028527/49982452-9bd41900-ff82-11e8-8bde-b24e7d20fba8.png">

3. Compare button in API Latency BreakDown graph is not usable since it is not possible to select anything from 'Compare to' dropdown. 

<img width="1357" alt="api latency breakdown" src="https://user-images.githubusercontent.com/13028527/49982460-a393bd80-ff82-11e8-8d05-ae61f2f96df7.png">

**Suggested Labels:**
Analytics

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Analytics dashboards have beed changes in the latest version.I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
