### ISSUE TITLE
Application name validation error if contains special language chars

### ISSUE THREAD

**Issue by waqasalirazzaq** [wso2/product-apim#4094]
**Description:**
Getting form validation error if the application name contains special language char. see below screenshot.
![image](https://user-images.githubusercontent.com/30646233/50046057-3e80ba80-009d-11e9-8d37-1611f10ee35b.png)

I tested on version 2.5.0 and works fine.

**Suggested Labels:**

APIM

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vithu30** [comment]
This validation has been added to resolve the issue - [The applications created with special character names throws errors when generating keys](https://github.com/wso2/product-apim/issues/3515)
