### ISSUE TITLE
Empty response received by the backend is replaced by the request payload

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#4100]
**Description:**
The JSON stream is not cleared if we receive an empty payload from the backend. The BlockingMsgSender should be fixed to handle scenarios if the response from the backend is empty as well as if the JsonInputStream is not empty. 

**Affected Product Version:**
APIM 1.9.1

**Comment by tgtshanika** [comment]
Fixed in latest APIM release(2.6.0)
