### ISSUE TITLE
Gateway Timeout 

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#4101]
**Description:**
The gateway gives the following error  - "Connection time out while reading the request" when a request is sent with a large payload and invalid/empty access token. Note that the size of the payload with reproduces this error might depend on the performance of the machine.

**Affected Product Version:**
APIM 2.1

**Steps to reproduce:**
1. Deploy sample API
2. Use a curl loop with of 20 request to invoke the API. Use a large payload (tested with content length - 11728326) and invalid/empty access toke.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1274 and https://github.com/wso2/wso2-synapse/pull/1231
