### ISSUE TITLE
[Doc] incorrect navigation from the given links

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#4127]
**Description:**
Incorrect navigation from the given links
1) 'Step 1.2.2 - Configure WSO2 API-M 2.6.0 for Analytics' -> step 7
2) 'Step 1.2.2 - Configure WSO2 API-M 2.6.0 for Analytics' -> step 8

**Suggested Labels:**
Type/documentation

**Suggested Assignees:**
@Mariangela 

**Affected Product Version:**
api-2.6.0
https://docs.wso2.com/display/AM260/Upgrading+from+the+Previous+Release#UpgradingfromthePreviousRelease-Step1.2-Optionally,migratetheconfigurationsforWSO2API-MAnalytics

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
