### ISSUE TITLE
API Life cycle event changed to Prototype API cleared the endpoint details.

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#4133]
**Steps to reproduce:**
1) Deployed sample PizzaShackAPI .

2) Edited it and added Endpoint Security  (added basic auth).

3) Saved and Published.

4) Again edited the published, endpoint secured API and demoted it to Prototype state (edit -> implement -> prototyped api -> deploy as a prototype -> keep editing API -> refresh browser UI)

5) After refreshing the browser UI, Endpoint Security information added from UI are not visible in the UI anymore.

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
