### ISSUE TITLE
Able to create API by enabling endpoint security scheme without giving credentials

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4140]
**Description:**
When creating an API, user is able to create API by enabling endpoint security scheme using jaggery API and REST API. When creating API from Publisher, we have UI validation to handle it.
![issue_git](https://user-images.githubusercontent.com/19728269/50764476-befb9b00-1298-11e9-817a-4499221d317b.png)

When retrieving the API, the part of the response looks as:

`"endpointSecurity":{"type":"basic","username":null,"password":""}`

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
