### ISSUE TITLE
Issue in saving Websocket APIs

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#4147]
**Description:**
The tiers selected for Websocket APIs isn't saved due to a change introduced to the api-manage.js via the mutual ssl feature. 

**Affected Product Version:** APIM 2.6

**Steps to reproduce:** Create new Websocket API via the API Publisher

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5908
