### ISSUE TITLE
Incorrect certificate location when configuring application creation workflow

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#4164]
**Description:**
Certificate path should be correct according to the BPS profile path of the EI server

**Affected Product Version:**
APIM 2.5.0 doc

When configuring workflow feature in we need to import the certificate of the API Manager to the following location "<EI_HOME>/wso2/business-process/repository/resources/security " instead of "<BPS_HOME>/repository/resources/security"

**Comment by tgtshanika** [comment]
Fixed
