### ISSUE TITLE
In/Out/Fault Flow's is setting to 'None', if we edit an API in the Publisher

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#4170]
**Steps to reproduce:**

1. Create API with existing mediation policies in the drop down list such as json_to_xml_in_message, log_out_message, json_fault.
2. Publish the API
3. Edit the API and go to implement tab.
4. We could observe that mediation policies set to 'None' in IE and firefox old version browser.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5917
