### ISSUE TITLE
DB Scripts MySQL 5.7 scripts missing for WSO2MB_DB and WSO2METRICS_DB

### ISSUE THREAD

**Issue by kevinadamz** [wso2/product-apim#4172]
**Description:**
There are no MySQL 5.7 specific scripts for WSO2MB_DB, WSO2METRICS_DB.

The documentation here, https://docs.wso2.com/display/AM260/Changing+the+Default+API-M+Databases#ChangingtheDefaultAPI-MDatabases-CreatedatabasetablesintheMetricsdatabase, says to  use <API-M_HOME>/dbscripts/mb-store/mb-store/mysql5.7.sql" and "use <API-M_HOME>/dbscripts/metrics/metrics/mysql5.7.sql script file."

However they are not present.  Only the older mysql.sql script is there.
Where can I find these scripts?

**Suggested Labels:**
MySQL5.7,APIM2.6

**Suggested Assignees:**

**Affected Product Version:**
API Manager 2.6

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Read the documentation here: https://docs.wso2.com/display/AM260/Changing+the+Default+API-M+Databases#ChangingtheDefaultAPI-MDatabases-CreatedatabasetablesintheMetricsdatabase,

**Related Issues:**

**Comment by dushaniw** [comment]
Hi @kevinadamz 
You can use the same scripts with name mysql.sql for MB and Metrics DBs. Did you run into any SQL errors with the existing scripts?
