### ISSUE TITLE
Application sharing using role - fix for enable multiple group sharing for 2.2.0

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#4183]
**Description:**
Application sharing using role - fix for enable multiple group sharing for 2.2.0
We need to front port the fix given for 2.1.0 in https://github.com/wso2-support/carbon-apimgt/pull/1113/files

**Suggested Labels:**
Type / patch

**Affected Product Version:**
2.2.0

**Steps to reproduce:**
- Enable the config for multiple group as described in https://docs.wso2.com/display/AM220/Sharing+Applications+Between+Multiple+Groups
- Configured role claim ```<DefaultGroupExtractorClaimUri>http://wso2.org/claims/role</DefaultGroupExtractorClaimUri> ```
- Role(e.g. subscriber1) created in apim server
- Add application using store api, with groupId 

https://docs.wso2.com/display/AM220/apidocs/store/#!/operations#ApplicationIndividual#applicationsPost

**Comment by tgtshanika** [comment]
Fixed
