### ISSUE TITLE
APIM Store layout gets corrupted after page refresh

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#4194]
**Description:**

When have published a large number of APIs and we can view by scrolling. But with a scroll down or up (a little bit) and if refreshed the store page the UI view will corrupt as the below.

![admin](https://user-images.githubusercontent.com/15210142/51536216-c4351a00-1e42-11e9-8613-be8e44ebe21b.png)
  

**Suggested Labels:**

BUG- UI

**Affected Product Version:**
APIM 2.6.0

**Steps to reproduce:**
steps:

1. Created 20 APIs and published
2. Went to store API and logged to the store
3. Refresh the page no issue
4. Little bit scroll down and refresh the page, then the issue reproduced as the above screenshot.

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/carbon-apimgt/commit/6a13f64a195f18378b769b3a1d4defe00af21236
