### ISSUE TITLE
Uploading malformed sequences in to mediation extensions cause to broke the sequence drop down

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-apim#4198]
**Description:**
when we upload a malformed sequence configuration to the Message Mediation Policies it will not indicate in the UI that the sequence is malformed. After uploading the malformed sequence we can't list down the mediation policies including existing mediation policies as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Wso2am-2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create and API and upload Incorrect Sequence configuration (Sequence.xml) or A simple XML file with correct XML format which not includes the sequence configurations as a Message Mediation Policy and save the API.
It is showing that the sequence not uploading in UI without warning.
After that if we list down the mediation policies we can't observe the existing list as well.

**Related Issues:**

**Comment by nalakas** [comment]
fixed with fixed with https://github.com/wso2/carbon-apimgt/commit/f291906f66cd5ced49c1cbc0c0dfb414e2afbe84,https://github.com/wso2/carbon-apimgt/commit/a2f65d89b369aada3693207dbfdd70ef35921194,https://github.com/wso2/carbon-apimgt/commit/cd8166d21db392047f60fc9768b24a95f868acfc
