### ISSUE TITLE
unnecessary warning in REST API creation flow

### ISSUE THREAD

**Issue by aselarbd** [wso2/product-apim#4199]
**Description:**
Getting Unnecessary warnings in REST API creation flow.

> WARN {org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject} -  provided wsdl archive/file is null {org.wso2.carbon.apimgt.hostobjects.APIProviderHostObject}

 

**Affected Product Version:**
APIM-2.6.0  

**Steps to reproduce:**

- Add a new REST API via the publisher
- Fill all necessary details on the "Design" tab and then click "Next: Implement >" button

**Comment by nalakas** [comment]
fix :https://github.com/wso2-support/carbon-apimgt/pull/1278

**Comment by nalakas** [comment]
fixed in public with https://github.com/wso2/product-apim/issues/3716
