### ISSUE TITLE
Cannot open the resources in Implement tab when values added to the Summary field in the Design tab 

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-apim#4201]
**Description:**
When we creating a REST APIs by following up the documentation [1], we can observe that the resources cannot be opened as stated in Step 10 in [1]. If we add value to the Summary field from the Design tab as below.

**Suggested Labels:**

**Affected Product Version:**
wso2am-2.5.0
 

**Steps to reproduce:**

Create a rest API by following the documentation [1].
Add a summury value to the HTTP method under API definituion in Design tab.
![image](https://user-images.githubusercontent.com/37293166/51596932-1009c100-1f20-11e9-8cdd-4318925460c6.png)
Navigate to the SOAP to REST Mapping section in Implement tab. 
Click on a resource to view the In and Out sequences of the API same as the step 10 metioned in documentation [1].
![image](https://user-images.githubusercontent.com/37293166/51597084-6840c300-1f20-11e9-9de9-309a4aa760ae.png)

[1] https://docs.wso2.com/display/AM250/Generate+REST+API+from+SOAP+Backend

**Comment by nalakas** [comment]
fixed with https://github.com/wso2/carbon-apimgt/commit/f9b9bcada1598f179100009c9402fb267b566f0d
