### ISSUE TITLE
Able to get access token after deleting key set ( delete application)

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-apim#4204]
**Description:**
Able to generate Access Token using the same ConsumerKey, ConsumerSecret even after deleting the application using store APIs

**Affected Product Version:**
APIM 1.10.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Login to Store
curl -X POST -c cookies http://10.150.7.80:9763/store/site/blocks/user/login/ajax/login.jag -d 'action=login&username=admin&password=admin'

2. Add application	
curl -X POST -b cookies http://10.150.7.80:9763/store/site/blocks/application/application-add/ajax/application-add.jag -d 'action=addApplication&application=test3&tier=Unlimited&description=&callbackUrl='

3. Generate keys
curl -X POST -b cookies http://10.150.7.80:9763/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag -d 'action=generateApplicationKey&application=test3&keytype=PRODUCTION&callbackUrl=&authorizedDomains=ALL&validityTime=360000'

Get the ConsumerKey and ConsumerSecret and base64 encode to create the basic token

4. Generate Access token

curl -k -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic QlU1c0RHYWIxWnFkeDJ2WDlSZk1sWWhDZUhjYTptRmtwNkdYWWJHaFdQQzJiWXJmM0txMnRTQkVh" -H "Content-Type: application/x-www-form-urlencoded" https://10.150.7.80:8243/token

5. Remove application
curl -X POST -b cookies http://10.150.7.80:9763/store/site/blocks/application/application-remove/ajax/application-remove.jag -d "action=removeApplication&application=test3"

6. Genertae Access token again
curl -k -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic QlU1c0RHYWIxWnFkeDJ2WDlSZk1sWWhDZUhjYTptRmtwNkdYWWJHaFdQQzJiWXJmM0txMnRTQkVh" -H "Content-Type: application/x-www-form-urlencoded" https://10.150.7.80:8243/token

**Comment by nalakas** [comment]
This issue does not exist in the master brach
