### ISSUE TITLE
API export does not include certificate

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#4205]
**Description:**
Endpoint related certificates are not export via the api-import-export tool.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/product-apim/pull/4336
