### ISSUE TITLE
Use WSClient instead of Thrift Client for key validation by default

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#4213]
**Description:**
By default we use thrift client for key validation and we ask users to move to WSClient when fronting the KM with a LB. By going forward we have decided to move to WSClient by default.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tharindu1st** [comment]
This is done in 3.0
