### ISSUE TITLE
Missing Error messages popup in Swagger file import at API Definition section.

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#4215]
**Description:**
Create an API from Scrache.
Give API Name , context and version.
At API definotion section try to import an API doc.

1. Try to upload an invalid file (xx.jpg) 
It should give an error "xx.jpg is not a valid Swagger Definition file"

2. Try to give n invalid URL
It should give an error "Input URL is not a valid Swagger Definition url"

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
