### ISSUE TITLE
APIM 2.6.0 /admin jaggeryapp does not respect http.nonProxyHosts

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#4217]
**Description:**
When we setup wso2 server behind the proxy for outside connections, in order to use internal connections directly we've set up noproxy hosts in wso2server.sh like bellow:
-Dhttp.nonProxyHosts="*.myhost.com|localhost"

It gives the following error when we try to login to the admin.
"Peer is not authenticated"

**Comment by rmsamitha** [comment]
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.
