### ISSUE TITLE
Proxy configurations are ignored when calling publisher 'Test' button behind a proxy

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-apim#4218]
**Description:**
The Publisher 'Test' button does not work when the server is fronted by a proxy. Even though the values for proxy port and the proxy host is set, it will bypass the proxy configurations and directly call to the provided backend.

Product - APIM 2.2.0

**Comment by isharac** [comment]
The fixed component[1] is no longer used in the latest product as it has moved to react based publisher app.

[1 ] org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/HostObjectUtils.java
