### ISSUE TITLE
Able to create restricted api with none existing roles

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#4256]
**Description:**
When creating an api with restricted publisher access control or restricted store visibility, by calling the add.jag with the addAPI action we are able to create an api with roles that are not existing. This has been validated in the publisher frontend but if we call the addAPI jaggery call directly the api will be created.

**Suggested Labels:**
Bug, Since this was found during scenario testing shall we assign a new label for this type ?

**Affected Product Version:**
Tested in 2.6

**Steps to reproduce:**
create an api with publisher access control, by using the jaggery api
Jaggery action - addAPI
Jaggery url - publisher/site/blocks/item-add/ajax/add.jag

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time. Also in the latest versions, jaggery is removed. So this issue won't be in the latest versions
