### ISSUE TITLE
Error when publishing API when endpoint algorithm is selected as other

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#4271]
**Description:**
When configuring load balanced endpoint type with algorithm as other(not round robin), the provided algorithm class does not get saved. Instead the value "Other" always gets saved. This leads to an error when publishing the API.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
Fixed with WUM.
