### ISSUE TITLE
API failing when accessControlRoles having more user roles

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-apim#4273]
Description:
REST API "**curl update**" fails when there are more than 3 user roles 

Affected Product Version:
**2.5.0**

Steps to reproduce:
* Create several user roles in the management console
* Create a REST API
* Assign those user roles to that API
* Try to update the API through the CURL command but did not reproduce the issue
* Decrease the 'MaxRoleNameListLength' property value
* Try to update the API through the CURL command again and reproduced the issue.

Related Issues:
https://github.com/wso2/product-apim/issues/2485

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/1313
