### ISSUE TITLE
Error while resetting keys in apimcli

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#4282]
**Description:**
When ~/.wso2apimcli/env_keys_all.yaml is populated with null values (This can happen when a wrong registration endpount is given while creating the environment) there is no way to reset those wrongly generated keys, other than clearing the keys file and regenerating. 

**Affected Product Version:**
api-import-export-2.6.0-v1.war

**Steps to reproduce.**
Add an environemnt as below.
./apimcli add-env -n test --registration https://localhost:9443/identity/connect/register --apim  https://localhost:9443 --token https://localhost:8243/token

Run below command to list apis
./apimcli list apis -e test -u admin -p admin -k --verbose

This will populate keys file with an empty client key as below. 
environments:
  test:
    client_id: ""
    client_secret: RklRO4iDNkfvONyauBXbVg==
    username: admin

apimcli commads issued after this point will return following error. (even reset-user command)
[ERROR]: parsing /home/sachini/.wso2apimcli/env_keys_all.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x749ce2]

**Comment by Krishanx92** [comment]
Tis issue is no longer valid, hence closing
