### ISSUE TITLE
Improve audit logs with grouping attributes when adding/modifying and deleting an application

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#4288]
**Description:**

When grouping feature is enabled [1], either an existing application is updated with a new user group or a new application is created with a user group, this is not reflected in the audit logs [2] for the API Store that are generated.

This is an audit log gap as there is no traceability of the groups when creating/modifying/deleting an application.

**Suggested Labels:**
Improvement, APIM 2.1.0
 
**Suggested Assignees:**
maneesha@wso2.com

**Affected Product Version:**
API Manager 2.1.0

**Steps to reproduce:**

1. Enable grouping feature by following [1]

Check audit logs after doing below,

* Create an application by adding a group and save
* Modify an existing application with a new group or remove an existing group
* Delete an existing application

[1] https://docs.wso2.com/display/AM210/Sharing+Applications+Between+Multiple+Groups
[2] https://docs.wso2.com/display/AM210/Working+with+Audit+Logs

**Comment by npamudika** [comment]
Fixed with above PR.
