### ISSUE TITLE
APIM 2.6.0 does not allow to generate token for the scope without role

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-apim#4290]
**Description:**
In APIM 2.6.0 it does not allow to generate a token for the scope without a role. Access token will be generated with default scope.

**Affected Product Version:**
APIM 2.6.0   

**Steps to reproduce:**
1. Create an API, scope without specifying a role, add this scope to a resource and publish an API:
2. Create an application (with the same user as in step 1), subscribe for the created API.
3. Go to the application in UI, choose a scope and generate keys.
4. Try to invoke the API from the store. Result: 403 Forbidden response.
5. Generate the token for the scope with curl. Result: access token from the response is having only the default scope.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5975
