### ISSUE TITLE
Add missing configs to broker.xml / Error when trying to read property

### ISSUE THREAD

**Issue by liepinshw** [wso2/product-apim#4296]
**Description:**
Default transaction/maxWaitTimeout value missing in broker.xml

Warning thrown while executed sh wso2swerver.sh:

`TID: [-1234] [] [2019-02-04 16:20:31,854]  WARN {org.wso2.andes.configuration.AndesConfigurationManager} -  Error when trying to read property : transaction/maxWaitTimeout. Switching to default value : 30 {org.wso2.andes.configuration.AndesConfigurationManager}`

**Suggested Labels:**
Warning, bug

**Suggested Assignees:**
NA

**Affected Product Version:**
wso2am/2.6.0

**OS, DB, other environment details and versions:**    
NA

**Steps to reproduce:**
set up WSO2am as per manuals

**FIX:**
 

```
<transaction>
       .....
        <!-- Maximum wait time (in seconds) for a transactional publisher commit,
         rollback or close event to complete on server side -->
        <maxWaitTimeout>30</maxWaitTimeout>
    </transaction>
```

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
