### ISSUE TITLE
SOAP to REST feature does not support generating OpenAPI3.0 swagger definitions

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#4305]
**Description:**
In the current implementation of SOAP to REST feature in 2.5 and 2.6, the generated swagger API is based on OpenAPI 2.0 specifications. It does not support generating OpenAPI 3.0 supported swagger APIs. It is because we are currently using openapi 2.x swagger parser in our implementation. When there is a requirement to have OpenAPI 3.0 in client side, according to the current implementation, the client has to maintain two OpenAPI definitions for client and backend (apim swagger definition and converted OpenAPI3 definition) .

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
2.5.0, 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lkokila** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130
