### ISSUE TITLE
Poor usability on API Store left nav menu

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#4308]
**Description:**
When you initially login to API store, left navigation menu looks like below,
<img width="216" alt="screen shot 2019-02-06 at 2 35 40 pm" src="https://user-images.githubusercontent.com/27903/52378597-f76bd180-2a1c-11e9-8e4b-46efb165e587.png">

Once you click on analytics it jumps to the top.
<img width="214" alt="screen shot 2019-02-06 at 2 35 50 pm" src="https://user-images.githubusercontent.com/27903/52378622-0783b100-2a1d-11e9-8f46-3916e9d4d172.png">

Then once you click on Applications that item jumps to the top,
<img width="210" alt="screen shot 2019-02-06 at 2 35 59 pm" src="https://user-images.githubusercontent.com/27903/52378647-18ccbd80-2a1d-11e9-8dad-4200015e6b61.png">

This result in poor usability for the end user. Typically menu items don't jump around.

**Affected Product Version:**
API Manager 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Download the distribution
2. Unzip, start and login to API Store by going to https://localhost:9443/store
3. Click on items on left nav menu

**Comment by chamilaadhi** [comment]
We have revamped the UIs in the latest versions. Closing since this is reported in an older version of the apim
