### ISSUE TITLE
Application's Token Type is shown as OAuth when it is updated as JWT

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#4311]
Description:
When the application's token type is updated into JWT, it is shown as OAuth. But when the token is generated using generate-keys/regenerate, the generated token is a JWT token.

Suggested Labels:
Bug, UI

Suggested Assignees:

Affected Product Version:
2.x

OS, DB, other environment details and versions:  
MacOS 10.14.2

Steps to reproduce:
Go to https://localhost:9443/store.
Click on "Add Application"
Change the token type to "JWT" and update. And we can see that it is not updated properly.
Go to "Production Keys" and click "generate keys" option. We can see that the generated token is a JWT token.

**Comment by nalakas** [comment]
In the latest master branch issue does not exists
