### ISSUE TITLE
Remove _build_.xml sequence file

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#4313]
**Description:**

The _build_.xml sequence was used in the _throttle_out_handler_.xml sequence in WSO2 API-M 1.6.0. However, there is no reference whatsoever to the _build_.xml sequence in the more recent code base. This file needs to be removed when cleaning the codebase.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
API-M 2.1.0, 2.2.0, 2.5.0, 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time.
