### ISSUE TITLE
Unable to view details of an API on API store mobile resolution 375x667

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-apim#4321]
**Description:**
API Store mobile resolution (375x667), it's not possible to select an API detail when the pagination is active.

**Affected Product Version:**
APIM 2.1.0

**Steps to reproduce:**
1. Create and publish 15 APIs using publisher (until paginate the available APIs)
2. Login to the store using Chrome and set the resolution to 375x667
3. 1st page APIs can click and able to see the API details.
4. 2nd page APIs are not responding when clicking on them to view API details.

**Comment by isharac** [comment]
Duplicate. https://github.com/wso2/product-apim/issues/4328
