### ISSUE TITLE
[DOC] Link for RESTful APIs for AM 2.1.0 not accessible 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#4323]
The following links provided in the documentation [1] and [2] cannot be accessible 

https://docs.wso2.com/apidocs/apimanager/am210/apipublisher
https://docs.wso2.com/apidocs/apimanager/am210/apistore

[1] https://docs.wso2.com/display/AM210/Store+APIs

[2] https://docs.wso2.com/display/AM210/Publisher+APIs

**Comment by nalakas** [comment]
corrected links in docs : 
https://docs.wso2.com/display/AM210/apidocs/store/ 
https://docs.wso2.com/display/AM210/apidocs/publisher
