### ISSUE TITLE
API import export tool allows to import APIs with the same API context. 

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#4331]
**Description:**
When importing an API with already available context tool imports it successfully. It only throws an error when trying to publish as below.

![image](https://user-images.githubusercontent.com/29249776/52624314-7b6a0180-2ed4-11e9-9a11-12bae0223160.png)

Need to validate contexts when importing the API. For now it validates only for duplicate API names. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Create an API with the context /test/1.0
Import an API which has different name but same API context context /test/1.0.
API gets imported successfully without any error eventhough we do not allow duplicate API context. 

**Related Issues:**

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/product-apim/pull/4342
