### ISSUE TITLE
Example and model values of API definition are not visible in API Console

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#4339]
**Description:**
In the Swagger Editor, I can see examples etc correctly, but when the API is published it miss all the examples etc.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nalakas** [comment]
fix in master :https://github.com/wso2/carbon-apimgt/commit/2d477f073de7caf76c0ee70bddecf4c7cc30ad1c
