### ISSUE TITLE
Document Aliases for APIM Analytics Related Passwords

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#4343]
**Description:**
According to code implementation passwords at following xpaths must have the below aliases when encrypting them using cipher-tool. Otherwise the decryption fails.

1. file - repository/conf/data-bridge/data-bridge-config.xml 
    xpath to password - dataBridgeConfiguration/keyStorePassword
    expected alias - DataBridge.Config.keyStorePassword
2. file - repository/conf/api-manager.xml
    xpath to password - APIManager/Analytics/DASPassword
    expected alias - Analytics.DASPassword
3. file - repository/conf/api-manager.xml
    xpath to password - APIManager/Analytics/DASRestApiPassword
    expected alias - Analytics.DASRestApiPassword
Please add these information to api manger docs as appropriate.

**Comment by Mariangela** [comment]
Updated [1] based on the feedback in this Git issue and the discussion that I had with Sachini.

[1] https://docs.wso2.com/display/ADMIN44x/Encrypting+Passwords+with+Cipher+Tool
