### ISSUE TITLE
Document Aliases to be used in cipher-tool encryption

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#4346]
**Description:**
Since arbitrary password aliases cannot be given in cipher tool encryption process please consider documenting then properly.

**Related Issues:**
https://github.com/wso2/product-apim/issues/4343

**Comment by Mariangela** [comment]
@msm1992 , is it possible to provide all the expected aliases for cipher tool, so that we can document it.

**Comment by AnuGayan** [comment]
The latest documentation has been updated with the relevant details
