### ISSUE TITLE
Cannot delete application when logged in with case insensitive username

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#4351]
**Steps to reproduce:**

- Log in to an API store with lowercase username
- Create an Application

- Login to the API store with uppercase username
- Try to delete the application - the following error message would appear.

`Only application owner can delete the application`

The above issue happens since **wso2am-2.1.0\repository\deployment\server\jaggeryapps\store\site\blocks\application\application-remove\ajax\application-remove.jag** file is checking the subscriber and  username without considering the insensitive usernames.

```
        var application = consumer.getApplicationById(applicationId);
        var subscriber = application.getSubscriber().getName();
        if (subscriber != username) {
            print({
                error: true,
                message: "Only application owner can delete the application"
            });
            return;
        }
```

**Comment by isharac** [comment]
Fixed with dc7772e1f20245d33e609844b58d661a66c6774f
