### ISSUE TITLE
Improvements to registry indexing to prevent hanging due to DB I/O operations

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4362]
**Description:**

There is a possibility for registry indexing threads to be hanged due to the slowness of the underlying database calls. The main problem is most of the time this doesn't give any warning logs or anything, The indexing process silently becomes hanged and sometimes none of the APIs published from Publisher appears in Store (or take a lot of time to appear).

There are some probable improvements we can do such as:

1. Using API specific RXT indexer rather than using the generic one. 
This can reduce a couple of DB calls during each indexing call.

2. Detect hanging threads and kill them with a warning etc. 
We need to implement a mechanism to detect hanging threads and need to be bit careful when killing those as they might forever take the acquired locks and no one will be able to take them again. 

3. Prevent hanging due to I/O operations. Currently, we are not using any timeouts for DB calls. It seems like, there are some options we can do, using JDBC driver [setNetworkTimeout](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setNetworkTimeout(java.util.concurrent.Executor,%20int)) and datasource level socketTimeout (eg: for [MSSQL](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-2017)). Once the timeout is hit, the DB operation will be aborted and an SQLException will be logged.  

**Affected Product Version:**
All versions of API Manager based on Registry
(Current latest release: 2.6.0)

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time
