### ISSUE TITLE
Timeout configure does not work for Key validation

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-apim#4372]
**Description:**
Axis2 Client CONNECTION_TIMEOUT and SO_TIMEOUT parameter change not working for WSClient verification in APIM 2.0.0. Same issue has resolved by fix in APIM 2.1.0 (https://github.com/wso2/product-apim/issues/1631)

**Suggested Labels:**
APIM-2.0.0

**Steps to reproduce:**
1. Configure a Key Manager node that will responce with latency.
2. Configure by changing the following configuration details in the <API-M_HOME>/repository/conf/axis2/axis2_client.xml file. All timeout values are in milliseconds.
```
<transportSender name="https" class="org.apache.axis2.transport.http.CommonsHTTPTransportSender">
<parameter name="SO_TIMEOUT">5000</parameter>
<parameter name="CONNECTION_TIMEOUT">5000</parameter>
</transportSender>
```
3. Create an API from API Publisher.
4. Create new application from API Store and call the new API from client.
5. This will get more than 5000ms  to timepout and configured values are not used.

**Related Issues:**
https://github.com/wso2/product-apim/issues/1631

**Comment by kavishkafernando** [comment]
Fixed by https://github.com/wso2-support/carbon-apimgt/pull/1355
