### ISSUE TITLE
[Doc] Update documentation with hostname configuration recommendations.

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#4373]
**Description:**
Please update the doc https://support.wso2.com/jira/browse/APIMINTERNAL-2?focusedCommentId=767616&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-767616 with below information.

How to properly change the hostnames of APIM? 
In order APIM to work properly, we need to change correct host name for
APIStore.URL  - This is to access store web app from publisher application.
APIPublisher.URL - This is to Access Tenant Store and Public Store.
Environments.GatewayEndpoint - Required for Environment configurations.
Environments.GatewayWSEndpoint – Required for Environment configurations.

**Comment by Mariangela** [comment]
Fixed. Updated the following pages.

https://docs.wso2.com/display/AM260/Changing+the+Hostname
https://docs.wso2.com/display/AM250/Changing+the+Hostname
https://docs.wso2.com/display/AM220/Changing+the+Hostname
https://docs.wso2.com/display/AM210/Changing+the+Hostname

**Comment by AndreasRusjaev** [comment]
The URL
https://docs.wso2.com/display/AM300/Changing+the+Hostname
is not open. The reader must be logined. 
Can you please open for evrybody?
