### ISSUE TITLE
Use "ThreadLocalRandom" to get unique ID in HandlerUtils to make it thread safe

### ISSUE THREAD

**Issue by chamindias** [wso2/product-apim#4386]
**Description:**
Please use "ThreadLocalRandom" to get unique ID in HandlerUtils (org.wso2.carbon.analytics.message.tracer.handler)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AnuGayan** [comment]
Fixed in the latest version
