### ISSUE TITLE
Fix not-null constraint violation for 'destination' column in ApiPerDestinationAgg table

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#4399]
**Description:**
When APIM 2.6.0 is configured with analytics, and the user creates an API with dynamic endpoints, once the API is invoked from API store the following error will appear in the APIM analytics server;

`INSERT INTO ApiPerDestinationAgg_SECONDS (AGG_TIMESTAMP , AGG_EVENT_TIMESTAMP , apiContext , apiHostname , destination , AGG_LAST_EVENT_TIMESTAMP , apiName , apiVersion , apiCreator , apiCreatorTenantDomain , gatewayType , label , regionalID , AGG_COUNT  ) VALUES  ..... was aborted: ERROR: null value in column "destination" violates not-null constraint`

This occurs due to the dynamic endpoint not being set as the 'destination'.

**Affected Product Version:**
APIM 2.6.0

**Steps to reproduce:**

1. Set up APIM 2.6.0 with APIM analytics
2. Create and API with dynamic endpoints.
3. Invoke the API from API store

**Comment by isharac** [comment]
Fixed.
