### ISSUE TITLE
Latest API Manager CLI tool 1.2.0 show older version

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#4401]
**Description:**
Latest API Manager CLI tool report an older version

**Affected Product Version:**
API Manager 2.6.0, API Manager CLI 1.2.0  

**Steps to reproduce:**
Download latest API Manager CLI from - https://wso2.com/api-management/tooling/

```
➜ tar xvf apimcli-1.2.0-macosx-x64.tar.gz
x apimcli/
x apimcli/LICENSE
x apimcli/README.html
x apimcli/apimcli
➜ cd apimcli
➜ ./apimcli version
apimcli Version: 1.1.0
```

**Comment by AnuGayan** [comment]
This is fixed in the latest versions
