### ISSUE TITLE
Cannot generate the access token with a scope if didn't add a role when creating the scope

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#4420]
**Description:**
Cannot generate the access token with a scope if didn't add a role when creating the scope

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
API Manager 2.5.0

**Steps to reproduce:**
1. Login to the Publisher and created an API and created a scope without adding a role.
2. Assigned the scope to a resource and published the API.
3. Login to the Store and created an application and subscribed to the created API.
4. When trying to generate keys list of scope has disabled. But if add a role when creating the scope, Ican see the scope under scopes of the Store and generate the keys with the scope.

**Note**: This is working fine in APIM 2.1.0 and APIM 2.6.0. The issue is with APIM 2.5.0.

**Comment by AnuGayan** [comment]
This was fixed in the latest versions
