### ISSUE TITLE
[Improvement] Using email addresses with plus sign (+)  breaks when creating an application

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-apim#4421]
**Description:**
When we use the plus sign("+") for user name (e.g. users having a plus sign in their email address or any of non-allowed character), then it will not allow creating an application in APIM

Stacktrace of the error when creating an application.

2019-02-28 21:46:24,480||ERROR|org.wso2.carbon.apimgt.impl.utils.APIUtil| Error occurred while creating ServiceProvider for app IDP.DEV.ENCO.IO_kngeerts+dev4-AT-gmail.com_46c46fac-0faa-44b7-ba0a-beb58ca5f689_PRODUCTION  The Application name IDP.DEV.ENCO.IO_kngeerts+dev4-AT-gmail.com_46c46fac-0faa-44b7-ba0a-beb58ca5f689_PRODUCTION is not valid! It is not adhering to the regex ^[a-zA-Z0-9 ._-]*$ org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:128)
 org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo_aroundBody0(APIKeyMgtSubscriberService.java:160)
 org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo(APIKeyMgtSubscriberService.java:108)
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
 org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
 org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
 org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
 org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
 org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
 org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:146)
 org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:231)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
 org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
 org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
 org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
 org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
 org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:128)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
 org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
 org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
 org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
... truncated for brevity ...

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2-support/carbon-identity-framework/commit/6ae7e9f75133fa70ac83045b74bdf7c8e543768a
