### ISSUE TITLE
[APIM 2.6.1] When a JWT regenerate through the application the old generated JWT token gets added as an expired token in database although it uses the revoke endpoint and instead of JTI claim whole JWT is sending in the revoke request

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#4423]
**Description:**
Each time a new jwt generated by using regenerate button, the old jwt's jti claim is added as an expired token in WSO2AM_DB.h2.db instead of revoked token although it uses revoke endpoint. 

I've overridden the revoke feature onPostTokenRevocationByClient method and the use case is , when a JWT token get's revoked i need to do some post processing stuff. That part work fine, but when i try to regenerate a JWT using the APIM application, regeneration process make a revoke request using whole JWT instead of using the JTI. also instead of being revoked the token is displayed in the audit table as expired. So there are two main issues which i see,

1.) when jwt regenerates it sends whole JWT instead of jti to revoke endpoint.
2.) Although the jwt being sent through the revoke endpoint it displays expired in the audit table.

**Suggested Labels:**
APIM 2.6.1 , JWT revocation, JWT regeneration

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.1- commit 82d68f13078e85b968c4b027232c61327562d52a (HEAD) Tue Feb 12 
Carbon Apimgt : commit 97390fc7846ff3599c47f8a8e9f924b82e223101 (HEAD, tag: v6.4.118)
**OS, DB, other environment details and versions:**    
Mac-OS

**Steps to reproduce:**

1.) Go to Store -> Create New Application with JWT token type.
2.) Generate a JWT token.
3.) New Token's jti will be stored in IDN_OAUTH2_ACCESS_TOKEN table as an active access key.
4.) Regenerate a new JWT token.
5.) Old JWT token's jti will be removed from the IDN_OAUTH2_ACCESS_TOKEN table and will be added to the IDN_OAUTH2_ACCESS_TOKEN_AUDIT table.
6.) Check the toke state field. (It is seen as expired instead of revoked).

Refer the following screenshots.
<img width="1277" alt="screen shot 2019-03-07 at 2 31 56 pm" src="https://user-images.githubusercontent.com/23296184/53945113-dfa06f80-40e6-11e9-86ad-88094fbd296e.png">
This screenshot refers the audit table entry of a token which revoked but showing Expired while regenerating a new key.

<img width="1680" alt="screen shot 2019-03-07 at 2 36 36 pm" src="https://user-images.githubusercontent.com/23296184/53945126-e8914100-40e6-11e9-8bef-384e83262a34.png">
This screenshot refers to the revoke request which happens when a regenerate button clicked. As you can see in the revokeRequestDTO, as the access token to be revoked, JWT is being sent instead of JTI

**Related Issues:**

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
