### ISSUE TITLE
Improving profileSetup Script

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-apim#4427]
**Description:**

The profile setup script doesn't remove jars from plugins folder that is not there in the bundle.info of corresponding profile. Removing unused jar by a profile could reduce the distribution/image size of a profile. Is there any tech issue by doing this?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.6.0
**OS, DB, other environment details and versions:**    
MacOS
**Steps to reproduce:**
Size different between before removing the unused jar and after for gateway-worker profile of WSO2 APIM 2.6.0
338M	wso2am-2.6.0 gateway-worker
294M	wso2am-2.6.0 gateway-worker

**Related Issues:**

**Comment by chamilaadhi** [comment]
There are technical difficulties in removing the jars based on the profile during the optimization script. Closing this issue since this is not possible
