### ISSUE TITLE
Two different claim-config.xml files available in IS and IS-as-KM

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#4428]
**Description:**
since claim management related features need to come with claim management feature, there is not logical reason for have 2 different claim management conf files. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
claim-config.xml in IS-KM is equal same as the claim-config.xml in IS.

Checked and compared in latest versions
is-km-5.7.0 and is-5.7.0
