### ISSUE TITLE
BACKENDLATENCY will be saved as 0 in the API_EXE_TIME_MIN_SUMMARY table when there is a send timeout happened for a particular API invocation

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#4431]
When there is a send timeout fault happened for a particular API, the value for the BACKENDLATENCY will be saved as 0 in the API_EXE_TIME_MIN_SUMMARY table. 
This can affect the latency graphs showing wrong implementations regarding the latencies.

This is happening because we are publishing execution time-related data to the analytics server when the API call hits the fault sequence as well.
This is already fixed in WSO2 APIM-2.6.0 version and should be fixed in other versions as well.

Affected Product Version: APIM-2.10

**Comment by tgtshanika** [comment]
This is fixed with https://github.com/wso2/carbon-apimgt/commit/f2e3a0903334f5734bcf30d5d4cee3c25cf507a2
