### ISSUE TITLE
[Store] [API Console] Bearer Token not Populating in API Console in Store intermittently

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#4432]
**Description:**
Steps to reproduce: Subscribe to an API with both a production and sandbox token, go to that API in the store, go to API Console, swap between production and sandbox endpoints a few times and it will not render a token in the field.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6036
