### ISSUE TITLE
Fix places where app-id is not properly set

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4436]
**Description:**

1. Any arguments of the createApplication() method in the key manager interface do not include applicationId which is already created in APIM side. We need to include the applicationId in the OAuthAppRequest parameter
2. In SubscriptionCreationWorkflow execute(WorkflowDTO workflowDTO) method workflowDTO object does not contain the applicationId. We need to set the applicationId variable inside the workflowDTO object. (which is an
instance ofSubscriptionWorkflowDTO)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by HiranyaKavishani** [comment]
This won't be  added to the product
