### ISSUE TITLE
Facilitate hidden application attributes

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4437]
**Description:**
We need to have an option to specify whether a property should be visible in the UI or not. The use case is, some properties can be populated internally (using extension points etc) and not meant to be shown in the UI.

For example: Add a new parameter to each attribute in App attributes in api-manager.xml to specify whether it is hidden or not. 

eg:
```
<ApplicationConfiguration>
    <ApplicationAttributes>
        <Attribute required="true" hidden="true">
            <Name>External Reference Id</Name>
            <Description>Sample description of the attribute</Description>
        </Attribute>
    </ApplicationAttributes>
</ApplicationConfiguration>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 m35. Following is the config which needs to be included in api-manager.xml to hide attribute.
```xml
<ApplicationConfiguration>
    <ApplicationAttributes>
        <Attribute required="true" **Hidden**="true">
            <Name>External Reference Id</Name>
            <Description>Sample description of the attribute</Description>
            <Default>Test</Default>
        </Attribute>
    </ApplicationAttributes>
</ApplicationConfiguration>
```
