### ISSUE TITLE
ApplicationNotFoundException when accessing Shared Application with an organization name with '&'

### ISSUE THREAD

**Issue by Methma** [wso2/product-apim#4441]
**Description:**
ApplicationNotFoundException when accessing Shared Application with an organization name with '&'. Checked in APIM 2.1.0 WUM level 1549711825566 and 1536073464050 in MySQL DB.

Error popping up:

> DataTables warning: table id=subscription-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
 
Terminal error:

> [2019-03-14 15:02:40,438] ERROR - APIStoreHostObject Application user4App does not exist for user user1
[2019-03-14 15:02:40,442] ERROR - subscription-list:jag org.wso2.carbon.apimgt.api.ApplicationNotFoundException: Application user4App does not exist for user user1

When an application contains multiple groups, the error is occurring when we have the organization with '&' as the first group.

**Affected Product Version:**
wso2am-2.1.0

**Steps to reproduce:**
1. Add application sharing related configurations to the api-manager.xml file.
2. create two users for the same organization. Organization name should contain the '&' character. (eg: a&b)
3. Create an app by logging from one user.
4. Add organization names under groups.
5. Login from the second user and view applications. Then the ajax error is popping up.

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6043/files
