### ISSUE TITLE
Upload sub-theme via admin portal always give warning

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#4442]
**Description:**
<img width="1057" alt="Screen Shot 2019-03-15 at 5 06 26 AM" src="https://user-images.githubusercontent.com/3424539/54398449-1fb3b380-46e0-11e9-82dc-3816dc95653f.png">

I am trying to upload a subtheme with the following folder structure.

.
├── css
│   └── custom.css
└── images
    └── google.png

This ZIP file is fire up a the warning given in the screen.

Expected behavior is to fire up this warning when only there are template or js files and show a success message for the above.

**Comment by isharac** [comment]
This is no longer a valid requirement as of the latest requirements of the product
