### ISSUE TITLE
APIM 2.6.0: Error while exporting the API using /export-api REST endpoint

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#4446]
Description:
After upgrading apim to 2.6.0 and adding api-import-export-2.6.0-v1.war, when try to export an API with a request like 

curl -H "Authorization:Basic <base64-encoded-credentials-separated-by-a-colon>" -X GET "https://<APIM_HOST:Port>/api-import-export-<product-version>-<tool-version>/export-api?name=<API-name>&version=<API-version>&provider=<API-provider>" -k > <exportedApiName>.zip

and provide login without userstore name in the Authorization header, it gives an error
"Error retrieving certificate meta data. tenantId [x] hostname xxxxx". 

**Suggested Labels:**

**Suggested Assignees:**

Affected Product Version:APIM 2.6.0

**OS, DB, other environment details and versions:**    

Steps to reproduce:
1.get the apim 2.6.0 pack and add api-import-export-2.6.0-v1.war file
2. create a user from secondary user store and create an API
3. export API without userstore name in the Authorization header

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-apim/pull/4465
