### ISSUE TITLE
Subscription approval requests do not get removed even the API is deleted

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4453]
Moved https://github.com/wso2/carbon-apimgt/issues/6033 to product-apim

**Description:**
When using API subscription workflow, when the API is deleted from the Publisher, the subscription approval request still exists and when approving the task, the status of the database entry gets updated from CREATED to APPROVED. As per the expected behavior, this task should be removed from the portal when there are no active subscriptions available.

**Steps to reproduce:**
1. Use wso2am-2.1.0 WUM pack and the BPS profile of wso2ei-6.1.1 or wso2bps 3.6.0.
2. Create a new API in the Publisher.
3. Enable application and subscription sharing and create a new Application.
4. Subscribe to the API.
5. Go to the admin portal and check the approval request with groups added to the subscription request.
6. Go to the Publisher and delete the API by changing the state from published to deprecated to retire and then delete.
7. The approval request still exists in the admin portal.
8. Then when trying to approve the task, observe a NullPointerException or the task is successfully approved even though the API doesn't exist.

**Comment by tgtshanika** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/7149
