### ISSUE TITLE
[APIM][2.6.0] Register application without providing the secondary userstore domain name

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-apim#4462]
**Description:**
According to the current implementation when we try to register an application for a user in the secondary userstore we need to specify the username with the secondary userstore domain appended. 

The relevant CURL request which currently works 
`curl -X POST \
  https://<ip-address>:<port-no>/client-registration/v0.14/register \
  -H 'Authorization: Basic base64encode($secondary_userstore_domain + “/” + $username)' \
  -H 'Content-Type: application/json' \
  -d '{
    "callbackUrl": "http://localhost:8888",
    "clientName": "DefaultApplication",
    "tokenScope": "Production",
    "owner": $secondary_userstore_domain + “/" + $username,
    "grantType": "client_credentials",
    "saasApp": true
}'`

Customer's requirement is to use the username alone without the userstore domain name. 

**Suggested Labels:**
APIM-2.6.0

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by niranRameshPeiris** [comment]
This behavior can be observed in APIM 3.1.0 as well.

**Comment by niranRameshPeiris** [comment]
This needs to be fixed in APIM 3.2.0 as well.
