### ISSUE TITLE
External file/url references to parameters and responses are not being resolved in the Resource UI

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#4464]
**Description:**
When creating an API resource containing External file/url reference to parameters and responses, these references do not get resolved when displaying  in the Resource UI(API definition under API design tab)

**Suggested Labels:**
APIM 2.5.0

**Affected Product Version:**
API-M 2.5.0

**Steps to reproduce:**
1. Create an API resource containing parameters and responses with edit references.
2. Navigate to the Resource UI 
_Outcome_: The parameter configuration will not be displayed in the Resource UI

**Comment by nirmal070125** [comment]
ref: 001E000000vajA0

**Comment by ruwiniwj** [comment]
@nirmal070125, we are unable to fix this for the immediate upcoming release(3.0.0). We will be fixing this in a future release.
