### ISSUE TITLE
Missing DB configuration information in 2.6.0 APIM

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#4470]
**Description:**
APIM analytics 2.6.0 document [1] missing the following DB configuration details.

* Do not need to run the database scripts against the analytic databases as the tables for the data sources are created automatically at runtime through the siddhi scripts.
* For Mysql, the database should be created manually for analytics before configured the deployement.yml files in profiles.
* It should specify, that it won't add the DB configuration to master-datasources.xml of the APIM 2.6.0 

**Affected Product Version:**
Analytics 2.6.0

[1]https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#standardsetup

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
