### ISSUE TITLE
Upgrade Google Gson to the latest version

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#4481]
**Description:**
Upgrade Gson to 2.8.5 ( the latest version )
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by fazlan-nazeem** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6125
