### ISSUE TITLE
When the API end points are defined as URI templates API tried to build the message

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-apim#4486]
**Description:**

It seems that when the endpoint of API is defined as below aforementioned code segment try to build the message. Message payload should not build at the API manager.
<http uri-template="{uri.var.dkcserviceurl}/GradeUploadService">

**(Please notice the variables part(endpoint) where address -> {uri.var.test}/foo.com)**
![image](https://user-images.githubusercontent.com/19922157/54980830-d2332280-4fcc-11e9-9b8c-44ed45f97220.png)

**(It hits the buildMessage(synCtx))**
![image](https://user-images.githubusercontent.com/19922157/54980881-f0991e00-4fcc-11e9-9506-6b70d82323c7.png)

**Affected Product Version:**
APIM 2.1.0
**OS, DB, other environment details and versions:**    
Linux
**Steps to reproduce:**
1. Create a global sequence as below,
```
<sequence xmlns="http://ws.apache.org/ns/synapse" name="WSO2AM--Ext--In">
    <property name="uri.var.foourl" value="https://localhost:8080"/>
</sequence>
```

2. Then create a sample API and use the uri templates for the endpoints. For example in the synapse configuration of the API,
```
...
<endpoint name="admin--TestAPI_APIproductionEndpoint_0">
                     <http uri-template="{uri.var.foourl}/hello">
                        <timeout>
...
```
 3. Now you can see that the in the APIM the message is going to build insode the APIM.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1282
