### ISSUE TITLE
APIM CLI tool does not import subscriptions when importing applications

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#4498]
**Description:**
When importing applications "with subscriptions" using the APIM CLI tool, the subscriptions are not copied. The following error is logged even though the API subscribed to the application is in the published state in the target environment.

```
Partially imported Application
NOTE: One or more subscriptions were not imported due to unavailability of APIs/Tiers
```
 
**Affected Product Version:**
2.5.0

**Comment by npamudika** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5729
