### ISSUE TITLE
high CPU on internal API gateways.

### ISSUE THREAD

**Issue by nipun-sachintha** [wso2/product-apim#4502]
**Description:**

This happens when we have custom mediation in the out path meaning content aware tries to build the message. But we are sending soap message as content-type "text/javascript". Usually, this message can be built using a JSON builder. But this soap message fails and CPU goes high.

**Suggested Labels:**
wso2-APIM

**Affected Product Version:**
2.6.0

**Steps to reproduce:**

Create API
Add custom sequence in the out path
Send soap message with content type "text/javascript" as the response from back end
Set accept header as "application/json" from client
Then the CPU usage goes high.

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
