### ISSUE TITLE
Improve Management console UI in API Manager

### ISSUE THREAD

**Issue by nalakas** [wso2/product-apim#4507]
Description:
Current API manager management console UI is not fine-grained UI. Even though UI component available (because other features use the same UI) backend component not available since the feature is not using(ex:saml SSO) 

Suggested Labels:
UI Improvement

Affected Product Version: APIM 2.6.0

**Comment by chamilaadhi** [comment]
APIM uses its own portals for its tasks. Management console is there for admin-related tasks such as user creation, etc. We won't be doing any improvements to the management console
