### ISSUE TITLE
Update JQuery library version used in Jaggery applications

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#4533]
**Description:**
- We have been using [JQuery 1.11.3]( https://github.com/wso2/carbon-apimgt/tree/6.x/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/libs
) for a long time and  it's out of maintainance. No longer receving surity or functionality patches.
Because of that ,IMHO It's a must to do upgrade the JQuery library in next release (Major)

**Affected Product Version:**
- API Manager 2.6

**Comment by tgtshanika** [comment]
JQuery has not been used in APIM 3.0.0 web portals since the store/publisher apps in APIM 3.0.0 are react based.
