### ISSUE TITLE
There is no next button on the API state change tab in the admin portal

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#4545]
**Description:**
there is no next button on the API state change tab in the admin portal even if there are more than 10 tasks remaining to approve. (10 is the paginated threshold set from the UI)

**Affected Product Version:**
APIM 2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Configure the state change workflow using apim 260 and EI 620.
- send more than 10 api state change request 
- log into the admin portal
- can observe there is no next button and only 10 tasks were listed

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6036
