### ISSUE TITLE
Error validation API scopes

### ISSUE THREAD

**Issue by osanzs** [wso2/product-apim#4548]
**Description:**

I have a WSO2 installation distributed with WSO2 Identity Server as Key Manager.

If I configure an API with scopes and use a token with the scope needed to invoke the API, I get an error 900900.

If I check the logs, I get a message indicating that the tennat id is null.

I have reviewed the source code and class "org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator" method (private int getTenantId (User user) throws UserStoreException) throws to Exception because the "user.getTenantDomain ()" is null.

If I check this condition the code works fine.

   private int getTenantId (User user) throws UserStoreException {

    int tenantId = -1;
    
    if (user.getTenantDomain ()! = null)
    tenantId = IdentityTenantUtil.getTenantId (user.getTenantDomain ());

        if (tenantId == 0 || tenantId == -1) {
            tenantId = IdentityTenantUtil.getTenantIdOfUser (user.getUserName ());
        }

        return tenantId;
    }

**Affected Product Version:**
WSO2 API Manager 2.6
WSO2 Identity Server 5.7 + Key Manager

**OS, DB, other environment details and versions:**    
Redhat 7.5

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
