### ISSUE TITLE
Content-Type header is not preserved

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-apim#4558]
**Description:**
I'm having a backend which is responding with content-type: application/pdf. But in the response which has received from the APIM is having an added suffix for content type, as charset=UTF-8 (Full content type header is like Content-Type=application/pdf; charset=UTF-8). In the outflow, if we did not build the message, it returns the same content type which is content-type: application/pdf. If the message gets build the suffix get append.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2am-2.5.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. create an endpoint which returns content type without encoding type. (ex: Content-Type=application/pdf)
2. create an API configuring above created endpoint (use a content-aware mediator in the outflow)
3. publish the API and invoke the service through API console or a rest client

Even though backend send Content-Type as application/pdf ESB will append encoding type to the content type as Content-Type=application/pdf; charset=UTF-8

**Related Issues:**

**Comment by nalakas** [comment]
https://github.com/wso2-support/wso2-synapse/commit/a4c744cc08d3504a5b8570b52bf70f45c45a478e

https://github.com/wso2-support/wso2-synapse/commit/7e34747d4ffa838905f7a9b5922db87d61faa54b

**Comment by nalakas** [comment]
https://github.com/wso2/wso2-synapse/commit/0867fecf58b8f043fdff27c776dc3ba1c01274bb

**Comment by WathsalaKoralege** [comment]
# Description
The character encoding is not removing from the content type while sending the message from APIM GW to BE.
 
`APIM version: 2.5.0`

With the following property, character encoding can be removed **only for application/json** type.
`<property name="setCharacterEncoding" value="false" scope="axis2"/>`

The fix [1] already is available in the APIM 2.5 version and it is checking the below condition in PassThroughHttpSender. So it is required to build the message to remove the character encoding.
`if (!noEntityBodyResponse && msgContext.isPropertyTrue(PassThroughConstants.MESSAGE_BUILDER_INVOKED) && pipe != null) {`

However, even though build the message, it is identified that PassThroughConstants.MESSAGE_BUILDER_INVOKED has been removed from the message context at the above point even after setting it true in the RelayUtils as below.
`messageContext.setProperty(PassThroughConstants.MESSAGE_BUILDER_INVOKED, Boolean.TRUE);`

# Steps to reproduce

- Create and publish an API along with a mediation including below property.
 `<property name="setCharacterEncoding" value="false" scope="axis2"/>`

- Invoke the Post method along with a different content type other than application/json.
`ex: curl -k -X POST "https://localhost:8243/test/1.0/foo1" -H "Content-Type: text/xml" -H "Authorization: Bearer c6cfaa49-3f48-3457-8739-30f7191901a9" -d "<a>bb</a>"`

[1] https://github.com/wso2-support/wso2-synapse/commit/7e34747d4ffa838905f7a9b5922db87d61faa54b

**Comment by rmsamitha** [comment]
One solution to get this to work for content types other than "application/json" is by adding the following configuration in <PRODUCT_HOME>/repository/conf/passthru-http.properties.

`http.headers.preserve = Content-Type`

But since this applies for all APIs globally, it is not an ideal solution. There should be a solution that can apply this fix, per API level.
