### ISSUE TITLE
Sign-up page displays view additional details when no extra fields available

### ISSUE THREAD

**Issue by brendon-stephens** [wso2/product-apim#4573]
When customizing the sign-up page to remove default fields the "View Additional Details" button remains even when there are no extra fields to display.

Steps to reproduce:
1. Enable sign-up screen on APIM
2. Remove claims under "View Additional Details" (eg. country, mobile, IM, etc..)
3. View sign-up page.

Suggested Fix:

<APIM_HOME>/repository/deployment/server/jaggeryapps/store/site/themes/wso2/templates/user/sign-up/template.jag

Line #109 - <a class="add-margin-bottom-4x sign-up-additional" title="<%= i18n.localize("View Additional Details")%>"><%= i18n.localize("View Additional Details")%></a>

Needs to be rendered only when fields array contains a field with a property of required = false.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
