### ISSUE TITLE
When creating an API using a SOAP endpoint, we are setting the namespace value in the WSDL definition as the target namespace, which is the http://mgt.user.carbon.wso2.org, instead of the namespace value of the Operation's namespace, http://org.apache.axis2/xsd

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-apim#4580]
**Description:**
when trying to create and publish a REST API using a SOAP endpoint below issue is happening. When trying to invoke an admin service operation from the SOAP UI, encountered the following error which depicts a namespace mismatching.
ERROR - RPCMessageReceiver Exception occurred while trying to invoke service method listAllUsers
org.apache.axis2.AxisFault: namespace mismatch require http://org.apache.axis2/xsd found http://mgt.user.carbon.wso2.org

According to the source code, this happens as when creating an API using a SOAP endpoint, we are setting the namespace value in the WSDL definition as the target namespace, which is the http://mgt.user.carbon.wso2.org, instead of the namespace value of the Operation's namespace, http://org.apache.axis2/xsd. Please refer [1] and [2]. The correct behavior should be to extract the namespace value from the particular operation's namespace as the target namespace.

Operation's namespace value is http://org.apache.axis2/xsd;
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:listAllUsers>
         
         <xsd:filter>?</xsd:filter>
         
         <xsd:limit>?</xsd:limit>
      </xsd:listAllUsers>
   </soapenv:Body>
</soapenv:Envelope>

 
WSDL definition's namespace value is http://mgt.user.carbon.wso2.org;
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://mgt.user.carbon.wso2.org"xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://org.apache.axis2/xsd"xmlns:ax2980="http://common.mgt.user.carbon.wso2.org/xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://mgt.user.carbon.wso2.org">...</wsdl:definitions>

This can be fixed by setting the correct namespace value for each operation via the "SOAP to REST Mapping" section of the Publisher UI. 

[1]. https://github.com/wso2/carbon-apimgt/blob/v6.4.50/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/WSDL11SOAPOperationExtractor.java#L129

[2]. https://github.com/wso2/carbon-apimgt/blob/v6.4.50/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/soaptorest/model/WSDLSOAPOperation.java#L72

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6178
