### ISSUE TITLE
Claims are getting changed for SAML2 Response in WSO2 APIM 2.6.0/ 2.5.0

### ISSUE THREAD

**Issue by subhkritianand** [wso2/product-apim#4583]
**Description:**
Claims are getting changed for an SAML2 Service Provider.  We have upgraded to WSO2 2.6.0 APIM on Ubuntu 16 machine. Earlier we were using 2.5.0. We use Local Claim dialect to add claims from our LDAP which is configured with WSO2 APIM embedded IS. Till 2.5.0 all were working fine and we were getting our desired claim field in `<saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**P99939393**</saml2:NameID>`

But now with 2.6.0 it's getting changed intermittently. Can you please check and update us, whether its a known Issue or there are any workaround of this.

find below are samples of SAML2 data.

`<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**P99939393**</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/hrservices"/></saml2:SubjectConfirmation></saml2:Subject>`

`<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**john.joe**</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/hrservices"/></saml2:SubjectConfirmation></saml2:Subject>`

`<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**IN/john.joe**</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/hrservices"/></saml2:SubjectConfirmation></saml2:Subject>`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

2.6.0

**Steps to reproduce:**

**Related Issues:**

**Comment by subhkritianand** [comment]
Claims are getting changed for an SAML2 respone. We use Local Claim dialect to add claims from our LDAP which is configured with WSO2 APIM embedded IS. On both of the versions of WSO2 APIM 2.5.0 and 2.6.0 it's Intermittent, sometimes we are getting our desired claim field in <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**C99939393**</saml2:NameID> But sometimes it's getting changed to {username} or {domain}/{username}. Whenever we are landing to such descrepency we are getting a WARNING in wso2carbon.log as. "Subject claim could not be found. Defaulting to Name Identifier"
 
Can you please check and update us, whether its a known Issue or there are any workaround of this ?
 
find below are samples of SAML2 data.
 
<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">P99939393</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/sample"/></saml2:SubjectConfirmation></saml2:Subject>
 
<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">john.joe</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/sample"/></saml2:SubjectConfirmation></saml2:Subject>
 
<saml2:Subject><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">IN/john.joe</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData NotOnOrAfter="2019-04-15T14:05:34.277Z" Recipient="https://xxxx.com/xx/bc/bsp/sap/xxx?sap-client=123&amp;RedirectURL=https://xxx.xx.com/sample"/></saml2:SubjectConfirmation></saml2:Subject>

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
