### ISSUE TITLE
NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper after setting EnableJWTGeneration to true for IS-KM

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#4608]
**Description:**
NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper after setting EnableJWTGeneration to true for IS-KM. Need to add the com.fasterxml.jackson.core.jackson-databind_2.9.5.jar to the IS-KM pack dropins directory.

**Steps to reproduce:**
- Setup an APIM 2.6.0 pack with IS-KM 5.7.0 (JWT Generation enabled).
- Create a sample API and publish it.
- Create an Application and add an application attribute.
- Subscribe the API using this application.
- Generate Application Keys and Access token/
- Invoke the API.

**Comment by survivingwithandroid** [comment]
We have the same error. Even if we added the library to the KM dropins directory it still doesn't work.
Did it work for you?
Thank you
