### ISSUE TITLE
Usernames are sometimes case sensitive but other times the aren't

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-apim#4614]
**Description:**
Username is case sensitive when trying to delete the applications. But it has not considered when login using user credentials. 

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
API Manager 2.5.0

**Steps to reproduce:**

1. Login to Management console.
2. Create a user as dev.
3. Login to the Store using username Dev.
4. Create an application.
5. Delete the created application. It will fail with the following error.

`Only application owner can delete the application`

6. Logout from Dev user and then login from the username dev. 
7. The application will be deleted.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6216
