### ISSUE TITLE
APIM doesn't scale horizontally

### ISSUE THREAD

**Issue by kratosmat** [wso2/product-apim#4621]
**Description:**
Hi all,
I am trying to scale apim 2.6.
I have installed APIM with Pattern2 with IS as KM as below
- 2 VM (ubuntu, 1CPU, 2GB RAM): GW + Portal (publisher, store, traffic)
- 2 VM (ubuntu, 1CPU, 2GB RAM): IS as KM + HAPROXY as LB
- 1 (ubuntu, 2CPU, 4GB RAM) Postgresql
- 2 [Additional] VM (ubuntu, 1CPU, 2GB RAM): GW

I have published on APIM a spring boot hello world running on the host.

My JMeter plan as:
- 1 http request to get access token
- 1 http request that call the API using the access token
- 1000 thread and for each token it calls the api 500 times

The average time for each call is 935 ms, but if I turn on the other 2 [Additional] GW the average time is 1230, so degrades. 

Do you have some similar situations? Do you have some advices?

**Suggested Labels:**
Performance, scaling, jmeter, apim.

**Affected Product Version:**
APIM 2.6, IS as KM 5.7

**OS, DB, other environment details and versions:**    
ubuntu, postgresql

Best regards,
Matteo.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
