### ISSUE TITLE
To back port the application ownership changing feature to APIM 2.5.0

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#4622]
**Description:**
Need to backport the application ownership changing feature to APIM 2.5.0 according to a customer's request.

**Affected Product Version:**
APIM 2.5.0

**Comment by nalakas** [comment]
https://github.com/tgtshanika/carbon-apimgt/commit/185e245ad7220a868382aeac16275134a985988a

https://github.com/wso2-support/identity-inbound-auth-oauth/commit/163f46c52ddc3cdb77e84483728b37adb6adc881,https://github.com/wso2-support/carbon-identity-framework/commit/bba1780ee65b9729a06d41f91291aedbcc521167,https://github.com/wso2-support/carbon-apimgt/commit/656a5d56613f903e1523fa0736fa005680b0e80f

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/1440
