### ISSUE TITLE
Remove HTTP access logs automatically.

### ISSUE THREAD

**Issue by nalakas** [wso2/product-apim#4631]
Description:
Configure the AccessLogValve as follows to remove the old HTTP access logs after given days,

rotatable="true" maxDays="2" fileDateFormat="yyyy-MM-dd"

This will affect the files only which have following format.
http_access_2019-04-30.log
Here there will remain only HTTP access logs for the current day and the previous day.

Suggested Labels:Doc
Product versions: APIM-2.1.0

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
