### ISSUE TITLE
Changing the API Manager Analytics credential in APIM

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#4637]
**Description:**
If the API Manager Analytics has been configured, when changing the super admin credentials in APIM it is not needed to change the credentials in <API-M_HOME>/repository/conf/log4j.properties file.

So the following entries are not needed in <API-M_HOME>/repository/conf/log4j.properties file as those are deprecated.

_log4j.appender.DAS_AGENT.userName=admin
log4j.appender.DAS_AGENT.password=admin

log4j.appender.LOGEVENT.userName=admin
log4j.appender.LOGEVENT.password=admin_

**Suggested Labels:**
APIM 2.6.0, APIM-Analytics

**Affected Product Version:**
APIM 2.6.0

**Comment by chamilaadhi** [comment]
Not applicable with choreo analytics in the latest APIM version. It uses token to connect with choreo
