### ISSUE TITLE
Blocked Subscriptions are propagated to new versions in unblocked state

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#4639]
**Description:**
When a new version of an API is created, we automatically re-subscribe to the new version unless the creator have opted out of it. In this case, we re-subscribe blocked subscriptions in the unblocked state.

**Affected Product Version:** 1.10.0, 2.1.0, 2.2.0, 2.5.0, 2.6.0

**Steps to reproduce:**
1. Create, publish and subscribe to the API
2.  Block the subscription from the publisher
3. Create new version of this API
4. Publish the new version of the API (make sure to untick "require re-subscription" )
5. Then you can see the UNBLOCKED subscription for the new version.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6276
