### ISSUE TITLE
Secure Vault / Ciphertool fails on Windows

### ISSUE THREAD

**Issue by robbla** [wso2/product-apim#4642]
When trying out Ciphertool on Windows it fails when we want to configure it for the first time. 

This is a windows 10 environment with JDK 8 121.

![afbeelding](https://user-images.githubusercontent.com/11582659/57133772-2091c900-6da4-11e9-9056-379cc366d1f1.png)

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
