### ISSUE TITLE
OIDC Logout Endpoint not white listed in Owasp.CsrfGuard.Carbon.properties

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4643]
**Description:**
Encountered the problem that an OIDC logout results in a 403 status code (forbidden). When /oidc/logout is called, the logout consent page appears. After confirming the dialog with "Yes", we receive a 403.

The solution was adding
org.owasp.csrfguard.unprotected.oidc=%servletContext%/oidc/*

to /repository/conf/security/Owasp.CsrfGuard.Carbon.properties.

Affected versions APIM 250

**Comment by nalakas** [comment]
https://github.com/wso2/product-apim/commit/4980c1f7f34b17d94f482f7c9d5615f97d7696d7
