### ISSUE TITLE
Custom Subscription Workflow hits default workflow during execution

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4663]
**Description:**
Custom Subscription workflow hits the general workflow as default. This feature has been broken.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0 WUM

**Comment by nalakas** [comment]
public fix :https://github.com/wso2/carbon-apimgt/commit/52003cd1128dd9be4ae0eb2d7d2a9488d28f4488
