### ISSUE TITLE
Analytics events getting dropped when User-Agent is null

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#4668]
**Description:**
ERROR - APIMgtUsageDataBridgeDataPublisher RequestResponse event dropped due to unavailability of mandatory data: [User agent] in event: Application consumer key: *************************3Ia, Application name: DefaultApplication, Application ID: 1, Application owner: admin, API name: Test, API version: v1.0.0, API context: /test/v1.0.0, Username: admin@carbon.super, API resource path: /foo, API resource template: /foo, API method: GET, API creator: admin, API creator tenant domain: carbon.super, API tier: Unlimited, Username: admin@carbon.super, User tenant domain: carbon.super, Host name: 192.168.8.100, User IP: 192.168.8.100, User Agent :null, Is throttled: false, Request timestamp: 1557224179688, Response time: 543, Service time: 1, Backend time: 542, Is response cache hit: false, Response size: 0, Protocol: https-8243, Response code: 200, Destination: http://www.mocky.io/v2/5cd129e43300005717b126eb, Security latency: 0, Throttling latency: 0, Mediation latency: 0, Response mediation latency: 0, Backend latency: 542, Other latency: 0, Gateway type: SYNAPSE, Label: Synapse

**Suggested Labels:**
APIM 2.6.0, APIM-Analytics

**Affected Product Version:**
APIM 2.6.0

**Steps to reproduce:**
* Create and publish an API.
* Invoke the API without User-Agent header. Refer to below example curl command.

curl -k -X GET "https://192.168.8.100:8243/test/v1.0.0/foo" -H "accept: application/json" -H "Authorization: Bearer 5cd2c989-86ce-3467-a844-f10154016fae" -H 'User-Agent:'

**Comment by npamudika** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/9039
