### ISSUE TITLE
Display last updated time of Application on UI

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#4678]
Display the last updated time of an Application through the Store UI. If the application was never updated, display the created time instead. Make the same capability available through the REST APIs as well. Make sure to convert the display time to the web browser timezone when displaying.

Moved from: https://wso2.org/jira/projects/APIMANAGER/issues/APIMANAGER-6038

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
