### ISSUE TITLE
Allow to define conditional groups with query parameter values as null

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#4679]
> Requirement: In a particular end point for different queries parameter we want to have different throttling policies. Example: /resource/1?view=selective should be 5 TPS and /resource/1?CountOnly =true should be 10 TPS and /resource/1?view=selective&CountOnly=true should be 15 TPS.
> 
> This is the answer I got from Harsha on how to do this.
> 
> his requirement can be achieved using advanced policies as well as custom policies. Custom policy approach may comple for him. When defining advance throttle policy, we currently don't have a way to check parameter is empty or not. Hence he will need some modification to siddhi query generated by API Manager until we provide that it. Basically he needs to create three condition groups as below
> Conditional Group 1 : Add query parameter condition with view=selective and another query parameter with CountOnly = null which later need to edited in siddhi  query to check is Null with limit 5
> Conditional Group 2 : Add query parameter condition with CountOnly=trye and another query parameter with view = null which later need to edited in siddhi  query to check is Null with limit 10
> Add query parameter condition with view=selective and another query parameter with CountOnly = true which later need to edited in siddhi  query to check is Null with limit 15
> 
> But, at the moment we cannot define a conditional group to check if query params are null. We need this support in api cloud.

By @amilam 
From: https://wso2.org/jira/projects/APIMANAGER/issues/APIMANAGER-5401

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
