### ISSUE TITLE
[APIM 3.0.0] Support API Monetization

### ISSUE THREAD

**Issue by chamindias** [wso2/product-apim#4680]
**Description:**
APIM should have OOTB support for monetization with an existing billing platform. For the initial implementation, we are planning to use stripe for this.

Discussion : **[Architecture] [APIM][Monetization] Monetization Model For WSO2 API	Manager**

[1] http://mail.wso2.org/mailarchive/architecture/2019-April/032107.html

**Comment by chamindias** [comment]
PR : https://github.com/wso2/carbon-apimgt/pull/6448

**Comment by chamindias** [comment]
PR : https://github.com/wso2/carbon-apimgt/pull/6480

**Comment by chamindias** [comment]
Until we get the official repo for this, we will be using [this location](https://github.com/chamindias/wso2-am-stripe-monetization) to keep track of the code changes related to the extension.

**Comment by shilmyhasan** [comment]
PR:
[https://github.com/wso2/carbon-apimgt/pull/6524](https://github.com/wso2/carbon-apimgt/pull/6524)

**Comment by chamindias** [comment]
New code repo : https://github.com/wso2-extensions/wso2-am-stripe-plugin

**Comment by chamindias** [comment]
Related issues : 

- [APIM 3.0.0] Monetization UI : https://github.com/wso2/product-apim/issues/5005
- [APIM 3.0.0] Migration script changes : https://github.com/wso2/product-apim/issues/5006

**Comment by chamindias** [comment]
PR (get current usage in store - REST API) : https://github.com/wso2/carbon-apimgt/pull/6961

**Comment by chamindias** [comment]
PR : Modify store REST API to return monetization data in tiers - https://github.com/wso2/carbon-apimgt/pull/6985

**Comment by shilmyhasan** [comment]
When deleting an Application subscription removal workflow is not called, so that when deleting an application with active subscriptions , that monetization related logic in the subscription removal workflow is ignored.  #https://github.com/wso2/product-apim/issues/5205

**Comment by chamindias** [comment]
PR : 
https://github.com/wso2-extensions/wso2-am-stripe-plugin/pull/5
https://github.com/wso2/carbon-apimgt/pull/7373
https://github.com/wso2/carbon-apimgt/pull/7306
https://github.com/wso2/carbon-apimgt/pull/7194

**Comment by chamindias** [comment]
Improve invoice data display options : https://github.com/wso2-extensions/wso2-am-stripe-plugin/pull/6

**Comment by chamindias** [comment]
Preserve monetization status on update : https://github.com/wso2/carbon-apimgt/pull/7479/

**Comment by chamindias** [comment]
Closing this since the feature is functional.

**Comment by chamindias** [comment]
Monetization for API product: https://github.com/wso2/carbon-apimgt/pull/7662/

**Comment by chamindias** [comment]
Monetization for API product subscription add and deletion: https://github.com/wso2/carbon-apimgt/pull/7680
