### ISSUE TITLE
APIM become slow/unresponsive and all synapse threads wait on PassThroughMessageProcessor-[IdentityEncoder]

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#4682]
> Due to the following locked state in I/O Listener threads, PassThroughMessageProcessor threads go to waiting state and Gateway Node become slow/unresponsive..
> 
> [logs]
> "HTTPS-Listener I/O dispatcher-1" #413 prio=5 os_prio=0 tid=0x00007f408c291800 nid=0x508 runnable [0x00007f405d23c000]
> java.lang.Thread.State: RUNNABLE
> at org.apache.http.impl.nio.codecs.*IdentityEncode*r.write(IdentityEncoder.java:110)
> at org.apache.synapse.transport.passthru.Pipe.consume(Pipe.java:159)
> at org.apache.synapse.transport.passthru.SourceResponse.write(SourceResponse.java:264)
> at org.apache.synapse.transport.passthru.SourceHandler.outputReady(SourceHandler.java:343)
> at org.apache.http.impl.nio.DefaultNHttpServerConnection.produceOutput(DefaultNHttpServerConnection.java:312)
> at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.produceOutput(LoggingNHttpServerConnection.java:125)
> at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:87)
> at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:39)
> at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:150)
> at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
> at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
> at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
> at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
> at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
> at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
> at java.lang.Thread.run(Thread.java:745)
> 
> I found the below similar bug during code study of "wso2-httpcore-nio" plugin:
> https://wso2.org/jira/browse/APIMANAGER-5607
> 
> Its fix is provided at below PR link:
> https://github.com/wso2/wso2-httpcore-nio/pull/17/files/01f558436c7a4765dc8cc8d196d8540315b18b8c
> 
> We can apply the similar fix in I*dentityEncoder.java* class. Please suggest.
> 
> Although I am not able to reproduce this high load condition using below link:
> https://github.com/wso2/performance-apim/
> 
> Is there any other way to reproduce this issue?

Moved from: https://wso2.org/jira/projects/APIMANAGER/issues/APIMANAGER-6108

**Comment by sajinieKavindya** [comment]
Closing the issue as the fixes are merged
