### ISSUE TITLE
When response cache enabled with binary content producing backend, API call fails during cache hit

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#4687]
**Description:**
Steps to reproduce the Issue,

1) Enable the following message Builder and Formatter in axis2.xml. 

In the Message Builders section:

```
<messageBuilder contentType="image/jpeg" class="org.wso2.carbon.relay.BinaryRelayBuilder"/>
In the Message Formatters section: 
```

`<messageFormatter contentType="image/jpeg" class="org.wso2.carbon.relay.ExpandingMessageFormatter"/>`

2) Deploy sample API configuration to API manager.

Note: The backend API used by this API will return a response with the bellow content type. 

`Content-type: image/jpeg`

3) Call the API with the bellow curl command  

`curl -k -v -X GET  'https://localhost:8243/attachmentAPI'`
 

4) API will respond properly for the first call and failed for the second call. Curl command retrieved empty reply from the server during the second call and following is the error noticed in the wso2carbon.log file. 

```
[2019-05-08 15:36:42,767] ERROR - PassThroughHttpSender Failed to submit the response
java.lang.RuntimeException: ContentID is null
at org.apache.axiom.om.impl.llom.OMTextImpl.getDataHandler(OMTextImpl.java:404)
```

**Sample API Configurations**

```
<api xmlns="http://ws.apache.org/ns/synapse" name="TestAttachmentAPI" context="/attachmentAPI">
  <resource methods="GET" uri-template="*" protocol="https">
     <inSequence>
        <log>
           <property name="in" value="===== IN ====="/>
        </log>

         <cache scope="per-host"
                collector="false"
                hashGenerator="org.wso2.caching.digest.REQUESTHASHGenerator"
                timeout="300">
            <implementation type="memory" maxSize="500"/>
         </cache>

        <send>
           <endpoint>
              <address uri="http://localhost:8000/img.JPG"/>
           </endpoint>
        </send>
     </inSequence>
     <outSequence>
        <log>
           <property name="out" value="=== OUT ===="/>
        </log>
        <cache scope="per-host" collector="true"/>
        <send/>
     </outSequence>
  </resource>
</api>

```

**Comment by kavishkafernando** [comment]
Public commit: #https://github.com/wso2-support/carbon-mediation/commit/ab163ecf0759232a28d5b7fd5f6f2eb7869501e7
