### ISSUE TITLE
The UPDATED_BY column in AM_API  table of AM_DB does not get updated when a developer updates an API

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#4689]
**Description:**
The UPDATED_BY column in AM_API  table of AM_DB does not get updated when a developer updates an API

**Suggested Labels:**
API-M 2.5.0
API-M 2.6.0

**Affected Product Version:**
API-M 2.5.0
API-M 2.6.0

**Steps to reproduce:**
1. Create an API
2. Update the API
3. Check the value for the UPDATED_BY column in AM_API table of AM_DB

**Comment by npamudika** [comment]
Fixed with above PR.
