### ISSUE TITLE
Error printing in the carbon log after Management console login

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#4697]
**Description:**
When login to the management console the below log entry printed after successful login.
ERROR - BeanUtil Cannot find the field UUID inside the class class org.wso2.carbon.registry.ws.api.WSResource

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by menakaj** [comment]
What is the api manager version that this issue was observed?

**Comment by thecrown666** [comment]
Hello, i observed this in 5.7

**Comment by npamudika** [comment]
Fixed with above PR

**Comment by iloshinik** [comment]
This is reproducible in APIM-2.1.0 as well.
