### ISSUE TITLE
CON_APP_KEY constraint violation recovery doesn't work with PostgreSQl

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-apim#4698]
**Description:**
Issue 1 :
With PostgreSQl, the constraint name in the exception message comes in lower case. Whereas we are checking for the uppercase match. This seems to be fixed in the [master](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/TokenMgtDAO.java#L404), but not for the APIM-2.0.0 (identity.oauth-5.1.1).
Fix : 
`if (StringUtils.containsIgnoreCase(e.getMessage(), "CON_APP_KEY")) {`

Issue 2 
Recover method uses the same connection as the one caused the CON_APP_KEY constraint failure for recovery attempts as well. This doesn't work in Postgre. If there was a previous error, use a new connection.
Fix :
Check if connection is Postgre. If yes, close existing connections. Create new connection and do the recovery.

**Affected Product Version:** APIM-2.0.0

**OS, DB, other environment details and versions:**    DB : PostgreSQL

**Steps to reproduce:**
Use PostgreSQL as Identity DB.
Apply patch 0579.
Do a load test with refresh grant or any other method that will violate the CON_APP_KEY constraint.
Even with the patch, it won't recover due to above two issues.

**Comment by npamudika** [comment]
Fixed.
