### ISSUE TITLE
Policy tiers aren't getting listed in the dropdown when trying to create a New Rest API in publisher

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#4709]
**Description:**
Policy tiers aren't getting listed in the dropdown when trying to create a New REST API in publisher

**Suggested Labels:**
APIM-3.0 UI

**Affected Product Version:**
APIM-3.0

**Steps to reproduce:**
Login to the publisher and try to create a new REST API from the UI.

**Comment by malinthaprasan** [comment]
Fix at the backend side by https://github.com/wso2/carbon-apimgt/pull/6316
