### ISSUE TITLE
 Swagger validation for API definition import functionality available in the design phase and the REST API layer

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#4711]
**Description:**
Need to add Swagger validation for API definition import functionality available in the design phase and the REST API layer.

**Affected Product Version:**
APIM 250
  
**Steps to reproduce:**

**A. Rest API**
- Try to update the swagger definition using [1] and an invalid swagger
**Can observe followings,**
- Responded the invalid swagger.
- In the publisher, could not find any resource method (even previously added methods). 
- No any log trace in the carbon.log.

**B. API definition import functionality available in the design phase**
- Create and published an API using Publisher (eg. test)
- Then again go to the EDIT API (of the created test API)
- In the Design tab click on the Import under API Definition
- Import an invalid swagger definition as a swagger file
- Then click on the Import to submit
**Can observe followings,**
- Nothing happened (No "invalid swagger message"/ log trace/ resource method update)
- Remain the previous resource methods.

1.https://docs.wso2.com/display/AM250/apidocs/publisher/#!/operations#APIIndividual#apisApiIdSwaggerPut

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6598
