### ISSUE TITLE
APIM-1.9.1 does not support TLS 1.2

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#4715]
**Description:**
APIM-1.9.1 does not support TLS 1.2

**Affected Product Version:**
APIM-1.9.1

**Steps to reproduce:**
Get two APIM packs to act as two nodes.
Configure pass through listener sender of nodeA TLS version as 1.2.
Then create a API in one node (node A) that calls a API in other node (node B).
Invoke node A and API call for node B will fail with unsupported TLS versiion.

**Comment by malinthaprasan** [comment]
Later APIM versions support TLS 1.2
