### ISSUE TITLE
API Manager Store UI not showing all the scopes while generating Access tokens

### ISSUE THREAD

**Issue by nipun-sachintha** [wso2/product-apim#4723]
**Description:**
number of scopes can be shown in drop down list of APIM Store is limited to 10.if we have more scopes than 10 , then scopes which exceed 10 are disappeared from drop down list.

**Suggested Labels:**
WSO2-APIM

**Affected Product Version:**
2.5.0

**Steps to reproduce:**
Login to the API Publisher using primary admin user.
Create 11 APIs each having a scope (ex. api_view_1) and with the primary admin role
subscibe all 11 APIs to one application in the store.
observe scope drop down list when generating access token.
scope related to last subscription is missing.
(In above it is not necessary to use only admin user and admin role)

**Comment by npamudika** [comment]
Fixed with above PR
