### ISSUE TITLE
Move to new configuration API - Publisher UI

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#4766]
Currently, we have [hardcoded values](https://github.com/wso2/carbon-apimgt/blob/6.5.x/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/services/configs/config.jag#L5) in Auth flow and some other places. The objective of this enhancement is to remove those hardcoded values and use configurations from the new [/settings API](https://github.com/wso2/carbon-apimgt/blob/6.5.x/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml#L4299).

![image](https://user-images.githubusercontent.com/3313885/58071919-b8bcea00-7bbb-11e9-9088-bf0e97f1694c.png)

**Comment by TanyaM** [comment]
It was decided to hardcode localhost in the configs in the calls for the same server. And the port will be read using the configuration service as there can be port offset configured.

**Comment by tmkasun** [comment]
@TanyaM Can we close this issue now ?
