### ISSUE TITLE
Resources with URL templates should be able to arrange in order they should get hit.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4775]
**Description:**

> When defining resources there is a possibility of using URL Templates but currently there is no way to priorities how they get hit by an incoming request.
> 
> Some times we might define two templates where an incoming request can be matched. In this case you should be able to push the more descriptive template to top so that it will be hit first than the generic template.
> 
> Ex. Consider "/cars/*" and "/*" In this case request with cars in URL should be hit "/cars/*" resource instead of "/*"

By @hevayo from https://wso2.org/jira/browse/APIMANAGER-4152

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time.
