### ISSUE TITLE
No error when malformed URL is given for the callback URL

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4783]
**Description:**

> Steps
> 
> 1. Create an Application by specifying a malformed URL for the callback URL.
> 
> Issue : There is no error indicated in the UI if a malformed URL is specified. If you edit an application which already has a valid URL with a malformed URL the callback URL will be empty.

By @yasassri from https://wso2.org/jira/browse/APIMANAGER-4694

**Comment by tharindu1st** [comment]
This is fixed in latest release.
