### ISSUE TITLE
WSO2 APIM 2.2.0 contains store showing version 2.1.0 in footer

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4786]
**Description:**

> Forum Topic edit link is visible to all the users including self signed up users in the same tenant and also for other tenant users as well.
> 
> When any user click the edit link it goes to the edit page and when they edit and try to save it only it shows a pop up error message.
> 
> It is more convenient making this edit link visible only to the party (Topic Owner) who can actually edit this.

From https://wso2.org/jira/browse/APIMANAGER-4788

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
