### ISSUE TITLE
Edit option should be removed from the application details page for inactive apps

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4790]
> **Preconditions**
> 
> 1. Application creation workflow must be enabled by following documentation
> 2. There should be an application created in 'Inactive' mode and corresponding application creation task should be listed on 'Admin-dashboard' > Tasks > Application creation page having accurate application information.
> 
> **Issue Description**
> 
> For inactive and rejected applications 'edit' option is not visible in list applications page. But edit option is available when user goes to application detail page of the particular application. (Please refer to the attached screenshots)
> 
> **Expected results**
> 
> Edit option should get removed from application details page for the inactive apps.

From https://wso2.org/jira/browse/APIMANAGER-5138
<img width="1135" alt="Edit_option_removed_for_inactive_apps" src="https://user-images.githubusercontent.com/4471756/58091640-c38d7400-7be7-11e9-9189-a57d367f36db.png">
<img width="1038" alt="Edit_option_in_view_page" src="https://user-images.githubusercontent.com/4471756/58091644-c5efce00-7be7-11e9-968c-17e8b242c0d8.png">

**Comment by tharindu1st** [comment]
due to ui revamp this is no longer valid
