### ISSUE TITLE
When there are two workflow admins 'Approve/Reject' dropdown disappear for one of them.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4794]
**Description:**

> **Pre conditions**
> 
> 1. Workflow should be configured
> 2. Admin role and username changed in user-mgt.xml. (admin123)
> 3. Another admin user (admin) is created and assigned the admin role
> 4. Users with admin role can log into admin dashboard.
> 
> **Steps**
> 1. Subscriber logs into API store and send application creation tasks for
> 
> app1
> app2
> app3
> app4
> app5
> 2. admin logs in and assign app1, app2 and app5 by clicking on 'Assign To Me' button.
> 3. Then admin123 logs into admin dashboard and assign app3 and app4.
> 4. admin123 clicks on start button.
> Actual Results
> 
> 'Approve/Reject' dropdown box is not visible for admin123. When he refreshes the page it appears. (refer to the screenshot attached)

> 
<img width="1135" alt="missing_approve_reject_dropdown" src="https://user-images.githubusercontent.com/4471756/58111930-0c592300-7c10-11e9-8e12-3ddcae336405.png">

From https://wso2.org/jira/browse/APIMANAGER-5161

**Comment by tharindu1st** [comment]
Not applicable for react ui revamp
