### ISSUE TITLE
When user defines a new tier attribute given a name of an existing tier attribute, system updates only the attribute value of the original to updated. 

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4795]
**Description:**

> Issue Description
> 
> When there is an already defined custom attribute for application level tier, on the edit view of the tier attributes (admin dashboard > throttling tiers > 'Edit tier' page ) are visible as non editable fields.
> 
> Yet when user adds an attribute, given an attribute name same as existing attribute with a different value system updates the original attribute's name with the new value and when user saves changes system saves and exit from the edit tier page.
> 
> Expected
> 
> 1) attributes also should be editable. 
> 2) When user tries to add an attribute given the same name system should validate for duplicates

From https://wso2.org/jira/browse/APIMANAGER-4521

**Comment by tgtshanika** [comment]
This behavior is slightly different in APIM 3.0.0 milestone pack and the users are allowed to add duplicate attributes for subscription throttling tiers (same parameter key with same parameter value and the old attribute value is not getting replaced with the new one)

**Comment by tharindu1st** [comment]
Invalid due to  ui revamp
