### ISSUE TITLE
Need help text for UI options

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4796]
**Description:**

> Can we please the following help text to the two UI options that appear when publishing a new API:
> 
> Deprecate Old Versions: Automatically deprecates all prior versions of the API, if any.
> 
> Require Re-Subscription: If unchecked, all users who are subscribed to the older version of this API will be automatically subscribed to the new version. If not, they need to subscribe to the new version again.

From https://wso2.org/jira/browse/APIMANAGER-4617

**Comment by chamilaadhi** [comment]
Since this information is available in the documents, we won't be adding it to the UI
