### ISSUE TITLE
The Pagination is not properly displayed on admin-console with large amount of data

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4797]
**Description:**

> The Pagination is not properly displayed on admin-console with large amount of data
> steps
> 1.view the attached screen shot.

![UI](https://user-images.githubusercontent.com/4471756/58152449-3e0ed000-7c8a-11e9-8b27-e9e19af76fa6.png)

From https://wso2.org/jira/browse/APIMANAGER-4789

**Comment by tharindu1st** [comment]
Invalid due to ui revamp
