### ISSUE TITLE
Provide a 'Select All/Unselect All' option in API Usage statistics in Publisher

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4798]
**Description:**

> When there are higher number of APIs are available and a user needed to select a particular API to view statistics with a better view, an 'Unselect all' or 'Select all' option would be useful. (check attachment)

![Unselect option for APIs](https://user-images.githubusercontent.com/4471756/58163186-2f7fe300-7ca1-11e9-8ff1-a75408549d3f.png)

By @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-5288

**Comment by chamilaadhi** [comment]
Stats pages are not available in APIM portals in the latest versions
