### ISSUE TITLE
[Publisher] [UI] Validation message should be shown to all required fields

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4803]
**Description:**

> In Add New Document under "docs" in API publisher, validation message should be available for all required fields.
> 
> Steps
> Create an API
> Navigate to "Docs" section and click on Add "New Document"
> 
> Issue
> Validation message is shown only in the Summary section it should show a message for the Name as well. Please refer attachment.

From https://wso2.org/jira/browse/APIMANAGER-5986

**Comment by tgtshanika** [comment]
The required field validation should be implemented in the revamped UI of publisher webapp in APIM 3.0.0

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
