### ISSUE TITLE
Introduce Primary Keys for the missing tables

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4805]
**Description:**

> The following list APIM tables lack primary keys, causing replication operations to result in delays.
>
> - am_alert_emaillist_details
> - am_alert_types_values
> - am_api_scopes
> - am_api_scopes
> - mb_binding
> - mb_durable_subscription
> - mb_expiration_data
> - api_destination_summary
> - api_fault_summary
> - api_last_access_time_summary
> - api_request_summary
> - api_resource_usage_summary
> - api_response_summary
> - api_throttled_out_summary
> - api_version_usage_summary

By @chamilad from https://wso2.org/jira/browse/APIMANAGER-5939

**Comment by chamilad** [comment]
:pinched_fingers:
