### ISSUE TITLE
DisableForumFeature not working properly

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4811]
**Description:**

> When using the disable forum features as described here the forum is not completely disabled. If the users presses the manage alerts button the forum menu item reappers.
> 
> This is due to a bug in the template.jag file at
> 
> {APIM_HOME}
> /repository/deployment/server/jaggeryapps/store/site/themes/wso2/templates/menu/primary. The manage alerts section i missing the isForumEnableFilter.
> 
> Please see attached a modified version of the file where the issue it fixed.
> 
> Thanks
> Björn

From https://wso2.org/jira/browse/APIMANAGER-6120

**Comment by AmaliMatharaarachchi** [comment]
Same issue as https://github.com/wso2/product-apim/issues/4978.
Fixed in WUM.

**Comment by tharindu1st** [comment]
Forum feature no longer available
