### ISSUE TITLE
All API dropdown doesn't displayed properly in Usage by Destination Statistics in Firefox on Windows 7

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4814]
**Description:**

> 1. Go to Statistics -> APIs -> Usage by Destination in Publisher
> 
> All APIs, My APIs drop down doesn't displayed properly in UI. (Check Attachment)

![API Usage desti](https://user-images.githubusercontent.com/4471756/58226282-a5d52180-7d43-11e9-9b3e-fc850dd03f1e.jpg)

By @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-5004

**Comment by tgtshanika** [comment]
This has to be fixed in the revamped publisher UI in APIM 3.0.0

**Comment by tharindu1st** [comment]
Feature no longer available.
