### ISSUE TITLE
Broken zipfiles when trying to dowload client sdk from the store

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4815]
**Description:**

> The downloaded zipfiles has a leading whitespace (LF).
> 
> **Steps to reproduce**
> Go to the store
> Click on the api
> Click on the SDKs-tab
> Download any client
> Try to open zip

From https://wso2.org/jira/browse/APIMANAGER-6077

**Comment by tgtshanika** [comment]
This has to be addressed when implementing SDK generation feature in APIM 3.0.0 revamped UI

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
