### ISSUE TITLE
Getting error with open ID connect after giving consent as server_error Error while handling consent.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4817]
**Description:**

> Followed steps in https://docs.wso2.com/display/AM260/Configuring+Single+Sign-on+with+OpenID+Connect#fef2f9c7ed1c4a15babfeb25eafbbb3e for openID with singke sign on 
>
> getting error as below after the consent page 
![image-2019-05-08-01-52-57-875](https://user-images.githubusercontent.com/4471756/58231415-97433600-7d54-11e9-943c-8d8805ebb18b.png)
![image-2019-05-08-01-50-33-517](https://user-images.githubusercontent.com/4471756/58231420-98746300-7d54-11e9-8c75-9e06ebc51aa8.png)

By Abhilash K R from https://wso2.org/jira/browse/APIMANAGER-6119

**Comment by tgtshanika** [comment]
Can you please 

1. Add following two entries into <APIM>/repository/conf/log4j.properties file

```
org.wso2.carbon.identity.consent.mgt
org.wso2.carbon.identity.application.authentication.framework
```
2. Restart the server
3. Reproduce the issue
4. Provide <APIM>/repository/logs/wso2carbon.log file,
                                                                    in order to identify the root cause of this issue?

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
