### ISSUE TITLE
Custom Authentication Handler : Client certificate from MessageContext is not set and null

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4821]
**Description:**

> The client certificates from Axis Message context is always null inside the custom handler.
> 
> org.apache.axis2.context.MessageContext axis2MessageContext = ((Axis2MessageContext) messageContext).getAxis2MessageContext();
> 
> // sslCertObject  is null
> Object sslCertObject = axis2MessageContext.getProperty("ssl.client.auth.cert.X509");
> 
> I tried with clean installation of WSO2 API Manager 2.2.0 and added custom handler that can access certificate like above. The API is called with client certificate using SOAPUI or apache http client and the result is same.

From https://wso2.org/jira/browse/APIMANAGER-6057

**Comment by tgtshanika** [comment]
Did you try the following?

`messageContext.getProperty("sl.client.auth.cert.X509");`

**Comment by AmaliMatharaarachchi** [comment]
Issue description link needs to be corrected to https://wso2.org/jira/browse/APIMANAGER-6070

**Comment by tharindu1st** [comment]
please go through https://xacmlinfo.org/2015/06/02/securing-apis-using-mutual-ssl-with-wso2-api-manager/
