### ISSUE TITLE
Grammatical error in UI - Lifecycle section

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4824]
**Description:**

> <img width="656" alt="Screen Shot 2019-05-23 at 3 56 40 PM" src="https://user-images.githubusercontent.com/4471756/58245882-70e0c300-7d73-11e9-996d-2e9430ad8229.png">
> ![Screen Shot 2016-12-18 at 11 19 33 PM](https://user-images.githubusercontent.com/4471756/58245907-7a6a2b00-7d73-11e9-8208-18223caf8e18.png)

By @Mariangela from https://wso2.org/jira/browse/APIMANAGER-5544

**Comment by tgtshanika** [comment]
This has been tested APIM 3.0.0  and was able to reproduce the same issue with revamped publisher UI as well

**Comment by AmaliMatharaarachchi** [comment]
refer https://github.com/wso2/product-apim/issues/5090 as well

**Comment by chamilaadhi** [comment]
This test is taken from APILifecycle.xml file. Changing this would require a migration. So instead of changing it in the APILifecycle.xml file, we could fix it from the UI level

**Comment by chamilaadhi** [comment]
Fix in latest

<img width="705" alt="Screenshot 2024-03-04 at 3 22 59 PM" src="https://github.com/wso2/product-apim/assets/4861150/e609b507-7982-40a1-9e16-079b8f0e1d3d">
