### ISSUE TITLE
“Created on” time zone is parsing mismatch between the backend and client browser

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4827]
**Description:**

> When server location is different from the browser timezone so when generate some statistics and try to check for the last hour statistics then you find the incorrect results.
> ![timemismatch](https://user-images.githubusercontent.com/4471756/58259809-ec05a180-7d92-11e9-8300-a0a307428b9d.png)

By @kasundsilva from https://wso2.org/jira/browse/APIMANAGER-5832

**Comment by tharindu1st** [comment]
statistics feature not available and revamped
