### ISSUE TITLE
[Doc] Need to improve the documentation on deploying API Microgateway in docker when Oauth2 access token is used.

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-apim#4834]
**Description:**

In the documentation on deploying API Microgateway in docker, it is mentioned that, if an Oauth2 access token is used to call Microgateway services, Microgateway is need to be connected with Key Manager to validate the token. Therefore Microgateway should be pointed to the Key Manager using the Key Manager details in the micro-gw.conf configuration file of the Microgateway. This documentation suggests to use following sever URL to connect Key Manager.

[keyManager]
   serverUrl="https://localhost:9443"
   username="admin"
   password="admin"
   tokenContext="oauth2"
   timestampSkew=5000

However, it is impossible to access localhost from docker environments. Therefore, above given URL will not connect with Key Manager which will subsequently prevent users from executing Microgateway services with Oauth2 access tokens.
 
Therefore, documentation needs to be updated to use IP address of the host instead of localhost to connect with Key Manager. 

Furthermore, it should be updated to set the verifyHostName parameter value to false to avoid any host verification issue.

**Suggested Labels:**
Documentation, Microgateway, Type/Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dushaniw** [comment]
moved the issue to https://github.com/wso2/product-microgateway/issues/632.
