### ISSUE TITLE
HTTP/SOAP Endpoint issue

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4842]
**Description:**

> 1. Create a REST API with a resource with GET method.
> 2. Use a SOAP backend URL with a certain SOAP version (following the documentation)
> 3. With earlier virsions of API-M, the UI provides the selction options such as SOAP1.1/SOAP1.2. But on API-M version 2.1.0, this is not available.
> 4. Even if HTTP/SOAP Endpoint type is selected as the endpoint type of the backend service, this appends resource path segments and query parameters to the URL when invoking the backend service
> 5. e.g. "GET /globalweather.asmx/weather?city=london&country=uk" instead of "POST /globalweather.asmx"
> 6. With the latest WUM updated package (on 18/10/2017), this was observed.

From https://wso2.org/jira/browse/APIMANAGER-5936

**Comment by dushaniw** [comment]
The options SOAP1.1/1.2 is available in 3.0. The above issue is not applicable to 3.0/3.1.0. Hence closing.
