### ISSUE TITLE
logging synchronization in apim 1.9.1 cluster

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4843]
**Description:**

> There is an issue when changing the log level (from carbon UI) from the cluster manager (Hazelcast), could not see any hazelcast message in the worker nodes and the new configuration is not applied to the worker node.

From https://wso2.org/jira/browse/APIMANAGER-6123

**Comment by kavishkafernando** [comment]
public commit: https://github.com/wso2/carbon-commons/commit/40ec405128d7a3e444e2436a482b8a2b94c4a907
