### ISSUE TITLE
OutOfMemory on message tracing.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4844]
**Description:**

> When enable "Dump message content" in message tracing tab, memory usage increased. If try to send 1000 requests by jmeter or other benchmark. I got a OOM error:
> ```
> {{ERROR
> 
> {org.apache.axis2.transport.base.threads.NativeWorkerPool} - Uncaught exception {org.apache.axis2.transport.base.threads.NativeWorkerPool}
> java.lang.OutOfMemoryError: Java heap space
> at java.io.BufferedInputStream.fill(BufferedInputStream.java:233)
> at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
> at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
> at java.io.FilterInputStream.read(FilterInputStream.java:107)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
> at org.apache.synapse.commons.json.JsonUtil.writeJsonStream(JsonUtil.java:956)
> at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:274)
> at org.apache.synapse.commons.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:70)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:614)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:280)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:217)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:530)
> at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
> at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
> at org.apache.synapse.rest.Resource.process(Resource.java:351)
> at org.apache.synapse.rest.API.process(API.java:338)
> at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
> at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
> at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:58)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
> at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:570)
> at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:193)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)}}
> ```
> 
> Please fix this.

From https://wso2.org/jira/browse/APIMANAGER-6122

**Comment by isharac** [comment]
This is fixed in the latest react based publisher application.

**Comment by tharindu1st** [comment]
Feature not available in latest release.
