### ISSUE TITLE
Wrong debug message print when KM cache is disabled

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4846]
**Description:**

> Following debug message print even KM caching is disabled.
> 
> DEBUG
> 
> {org.wso2.carbon.apimgt.keymgt.util.APIKeyMgtUtil}
> Storing KeyValidationDTO for key: xxxxxxxxxxxxxxxxxx
> We need to move this debug log under the if condition that we checking KM cache is enable.
> 
> https://github.com/wso2/carbon-apimgt/blob/api-product/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIKeyMgtUtil.java#L125

From https://wso2.org/jira/browse/APIMANAGER-6095

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9346

**Comment by BeParis** [comment]
Hi,

Any advice and/or workaround for this:  https://github.com/wso2/product-apim/issues/9381
 
Bernard
