### ISSUE TITLE
Call-mediator (or sequance-mediator) causes validation of WSA-headers

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4850]
**Description:**

> We are using call-mediator in our default global in- and out-flows to do logging of payloads. I've attached the mediator files to this bug report (global_ext_in.xml and global_ext_out.xml). These work fine for some of our backends but it seems that for a backend implemented with SOA Suite 11g (11.1.1.6.0) call/sequence mediator seems to start validation WSA-headers. As default SOA Suite 11g returns in the response message incomplete set of WS Addressing headers and when we have call/sequence-mediator in use this will result in an error and execution continues from fault-flow. We can see this error in the WSO2 APIM 2.1.0 logs:
> 
> [2018-08-16 14:52:45,477] ERROR - admin--GetCustomerInformationService Error while building message
> org.apache.axis2.AxisFault: A required header representing a Message Addressing Property is not present
> 
> Client (for example SoapUI in this case) will get following error from WSO2 API Manager:
> ```xml
> <soapenv:Fault>
> <faultcode xmlns:axis2ns1="http://schemas.xmlsoap.org/soap/envelope/">axis2ns1:Server</faultcode>
> <faultstring>Error while building message</faultstring>
> </soapenv:Fault>
> ```
> 
> When we forced 11g SOA Suite to not return any WSA-headers the calls worked fine. We are wondering two things:
> 1) Is this a bug or a feature
> 2) Is it possible to disable the WSA-headers checking (we know that the whole WSA Addressing module can be disabled, but it seems that it strips away all the WSA-headers in that case)
> 
> Attached also server log about the situation (server_log.txt).

global_ext_out sequence
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="WSO2AM--Ext--Out"> 
<log level="full"/>
<clone continueParent="true">
<target>
<sequence>
<call>
<endpoint>
<address uri="http://dil-osb-dev1.dna.fi/WSO2LogHandler/LogServlet"/>
</endpoint>
</call>
<drop/>
</sequence>
</target>
</clone>
<log level="custom">
<property name="MESSAGE" value="Before call mediator"/>
</log>
</sequence>
```
global_ext_in sequence
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="WSO2AM--Ext--In">
<log level="full"/>
<clone continueParent="true">
<target>
<sequence>
<call>
<endpoint>
<address uri="http://dil-osb-dev1.dna.fi/WSO2LogHandler/LogServlet"/>
</endpoint>
</call>
<drop/>
</sequence>
</target>
</clone>
<log level="custom">
</log>
</sequence>
```

[server_log.txt](https://github.com/wso2/product-apim/files/3222307/server_log.txt)

From https://wso2.org/jira/browse/APIMANAGER-6097

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
