### ISSUE TITLE
Cannot test a inline prototype API from store console agains sandbox gateway

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4857]
**Description:**

> We have applied the path for the previous bug 5954.
> This solve the issue, and now we can deploy inline prototyped APIs in both gateways (sandbox and production).
> But when we go to store, trying to test the inlined prototyped API from Console, the button "Try out" always execute agains Production gateway.

**Environment**
WSO2 2.1.0 on Ubuntu 16.04 LTS
2 different gateways deployed (sandbox and production)
Path for bug 5954 applied (only this path applied, rest of installation in original state)

By JOSE MANUEL SEGOVIANO from https://wso2.org/jira/browse/APIMANAGER-6071

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time. Please check with the latest APIM 4.2 for the behaviour
