### ISSUE TITLE
If there are spaces in between Swagger supported language list, SDK generation fails

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4858]
**Description:**

> If there is a space between the languages in the api-manager config file, SDK generation fails. For example, 
> <SupportedLanguages>android, java, scala</SupportedLanguages>
> 
> note the space before the java and scala. in this case java and scala generation not working but android works. To fix this we can trim the language name before populating the link in the store UI.
> 
By @dineshjweerakkody   from https://wso2.org/jira/browse/APIMANAGER-6068

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
