### ISSUE TITLE
Embed start and finish time calculation as debug log in each DB call

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4860]
**Description:**

> In current implementation, there are no debug logs added in granular level to record start/finish time calculation taken for database query execution.
> 
> For example, none of the DAO methods inside org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.java has debug logs added to record start and finish time for query execution as follows.
> ```java
>        if (log.isDebugEnabled()) {
>                 log.debug("State before executing get subscription details sql query " + new java.util.Date(System.currentTimeMillis()));
>             }
>             rs = ps.executeQuery();
>             if (log.isDebugEnabled()) {
>                 log.debug("State after executing get subscription details sql query " + new java.util.Date (System.currentTimeMillis()));
>             }
> ```
> These logs will be useful when an issue arises to find the time taken to each database call in a roundtrip analysis. So it will be a good practice to embed start/finish time calculation as debug logs whenever implementing a DAO and executing a query.

By @dushaniw from https://wso2.org/jira/browse/APIMANAGER-6061

**Comment by dushaniw** [comment]
As we can achieve the same using Observability, we would not be modifying the code to add debug logs, as it would not be a good practice.
