### ISSUE TITLE
APIM tries to connect to the DAS/Analytics thrift port, eventhough a custom publisher is plugged

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4861]
**Description:**

> - UsageData handler, FaultData handler, ResponseData handler, Throttle usage data handler uses a common data publisher which is APIMgtUsageDataPublisher.
> - But WorkFlowData publisher uses a different data publisher than the above ones.
> - In WorkflowData publisher the usage of WSO2 DAS is hard corded. We cannot publish WorkFlowData to other analytics engine than WSO2 DAS. So Even when we use custom data publisher, and when there are work flow related events generated, store tries to connect to DAS via the related WorkFlow Data publisher in which the DAS configs are hard coderd. Due to this continuous connection try, errors are logged continuously on the console.

By @rmsamitha from https://wso2.org/jira/browse/APIMANAGER-5900

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
