### ISSUE TITLE
APIAuthenticationHandler throws java.lang.NumberFormatException when DEBUG enabled in a distributed setting

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4863]
**Description:**

> I have set up a distributed deployment of WSO2 APIM 2.1.0 in my local machine running each profile in separate ports. I have enabled debug for org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler class from log4.properties. When I create a simple API and tries to invoke it, it throws the following exception,
> ```
> 
> java.lang.NumberFormatException: null
> at java.lang.Long.parseLong(Long.java:552)
> at java.lang.Long.parseLong(Long.java:631)
> at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.logMessageDetails(APIAuthenticationHandler.java:268)
> at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:123)
> at org.apache.synapse.rest.API.process(API.java:325)
> at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
> at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
> at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
> at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:371)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:748)
> ```
> 
> This occurs inside APIAuthenticationHandler's handleRequest method. when debug is enabled it tries to execute logMessageDetails method. Inside the logMessageDetails method, the exception throws due to parsing of null object returned from Axis2MessageContext as "wso2statistics.request.received.time".
> 
> However it works fine and no exception is thrown when we run the single pack of api manager.
> 
> My requirement is to enable existing debug log for APIAuthenticationHandler class to log the elapsed time to authentication response. Since it throws this exception in debug mode, I am unable to put any new debug logs or use existing debug logs within the class for the purpose.

By @dushaniw from https://wso2.org/jira/browse/APIMANAGER-6062

**Comment by isharac** [comment]
null check is available in [1].

[1] https://github.com/wso2/carbon-apimgt/blob/3463a1ee657bdbd078b34ebf35ad76df0aad85be/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/APIAuthenticationHandler.java#L618
