### ISSUE TITLE
Sequence not added in In flow

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4866]
**Description:**

> I make case in document "Map the Parameters of your Backend URLs with the API Publisher URLs", https://docs.wso2.com/display/AM210/Map+the+Parameters+of+your+Backend+URLs+with+the+API+Publisher+URLs
> 
> I commit file on step 13, but on step 14 i can't engage "In Flow" since TestSequence not on the list

By Pavel Kiselev from https://wso2.org/jira/browse/APIMANAGER-6057

**Comment by chamilaadhi** [comment]
This feature is now changed with the new API Policy feature. Please check with the latest 4.2.0
