### ISSUE TITLE
WSDL validation fails when creating SOAP endpoint using a WSDL that import schema(s) in API Publisher

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4867]
**Description:**

> Suppose I have a WSDL that imports a schema
> ```xml
> <?xml version="1.0" encoding="UTF-8"?>
> <definitions name="TestService" ... >
>   <types>
>     <xsd:schema>
>       <xsd:import namespace="sample.com" schemaLocation="test_schema.xsd"/>
>     </xsd:schema>
>     ...
>   </types/>
>   ...
> </definitions>
> ```
> While creating a SOAP endpoint using this WSDL, at the "Define API" phase click on the "Test URI" button to validate the WSDL. And publisher says its invalid (see the attached api-publisher.png).
> 
> 

> ![api-publisher](https://user-images.githubusercontent.com/4471756/58422754-0ac8a880-80b1-11e9-9aa3-49c037435bac.png)

By @SupunS from https://wso2.org/jira/browse/APIMANAGER-6051

**Comment by livanmay27** [comment]
I have the same error, how to fix???

**Comment by malinthaprasan** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/commit/d595436c0c7b991950601bb477ae840f7bfccbb1

**Comment by malinthaprasan** [comment]
For APIM 3.0.0 GA, use absolute paths instead of relative paths when defining schemaLocation.
