### ISSUE TITLE
[IE11] Download YAML/JSON options did not respond

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4871]
>**Description:**
> Go to publisher, Edit API and Edit source
> 
> - Edit the configuration and save.
> - Try to download JSON/YAML format of configuration.
> - Nothing happens and no file is downloaded.
> 
> **Affected Product Version:**
> 1.9.0
> **OS, DB, other environment details and versions:**    
> API-M 1.9.0 GA build
> On Windows server 2012 R2
> IE 11.0.9600.17107

By Pavithra Madurangi from https://wso2.org/jira/browse/APIMANAGER-3917

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time.
