### ISSUE TITLE
Error: Method not allowed for given API resource

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4872]
> **Description:**
> no response:
> ```xml
> <am:fault xmlns:am="http://wso2.org/apimanager">
> <am:code>405</am:code>
> <am:type>Status report</am:type>
> <am:message>Runtime Error</am:message>
> <am:description>Method not allowed for given API resource</am:description>
> </am:fault>
> ```
> 
> 2) Checking the log viewer (error message):
> 
> ```
> STATUS = Executing default 'fault' sequence, ERROR_CODE = 405, ERROR_MESSAGE = Method not allowed for given API resource
> Thu Feb 16 2017 12:23:46 GMT-0200 (E. South America Daylight Time)ERRORorg.wso2.carbon.apimgt.usage.publisher.APIMgtFaultHandlerCannot publish event. nulljava.lang.NumberFormatException: null
> at java.lang.Long.parseLong(Long.java:404)
> at java.lang.Long.parseLong(Long.java:483)
> at org.wso2.carbon.apimgt.usage.publisher.APIMgtFaultHandler.mediate(APIMgtFaultHandler.java:30)
> at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:84)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
> at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
> at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:215)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
> at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
> at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.onResourceNotFoundError(CORSRequestHandler.java:232)
> at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.handleResourceNotFound(CORSRequestHandler.java:211)
> at org.wso2.carbon.apimgt.gateway.handlers.security.CORSRequestHandler.handleRequest(CORSRequestHandler.java:149)
> at org.apache.synapse.rest.API.process(API.java:325)
> at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
> at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:300)
> at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:75)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:621)
> at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:560)
> at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:370)
> at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:228)
> at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:78)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:745)
> ```
>![success_evidence_before_error](https://user-images.githubusercontent.com/4471756/58424040-297c6e80-80b4-11e9-9bab-47740f3cb13d.png)

By  Etni Silva from https://wso2.org/jira/browse/APIMANAGER-6039

**Comment by isharac** [comment]
Fix with https://github.com/wso2/carbon-apimgt/pull/9347

**Comment by chamilaadhi** [comment]
Closing since PR is merged
