### ISSUE TITLE
Optimization of JVM and Mysql

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4873]
**Description:**

> Dear Sir 
> I am investigating an issue with same API that we have a big response time. This big response time happens when there are a lot of requests to that API. The API is asking whether to allow to view some football Live Streaming (i.e have a lot of request at the time that we have football games). 
> At one stress test we use to simulate the problem we found out that we have same requests with huge time to established connection with the API Manager ( more than 5 seconds). I have changed the JVM parameters from -Xms256m -Xmx1024m -XX:MaxPermSize=256m to -Xms2048m -Xmx2048m -XX:MaxPermSize=1024m in order to improve performance for the API gateway. This conses a new problem with the number of connections in Mysql which is (or was) 151. 
> Please can you suggest to us some optimization values for JVM and Mysql or anything else that can help us to resolve the issue. 
> Regards 
> Marios Koudounias

By Marios koudounias from https://wso2.org/jira/browse/APIMANAGER-6032

**Comment by chamilaadhi** [comment]
Closing Since the issue has been stale for a long time. If you still have the issue, please use a profiling tool to analyze the behaviour
