### ISSUE TITLE
need more detailed information for health of an API

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4874]
> **Description:**
> need more detailed information for health of an API. The message generated is as below. However I was not able to identify for which API the alert was generated for. It will be better if the specific API name is given
> 
> Message
> ```
> APIM Analytics Alert : healthAvailabilityPerMin
> 
> msg:Server error occurred,
> type:healthAvailabilityPerMin,
> alertTimestamp:1463744987238
> ```

By @shavantha from https://wso2.org/jira/browse/APIMANAGER-4867

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
