### ISSUE TITLE
Publishing API Runtime Statistics Using WSO2 DAS & WSO2 APIM

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4877]
> **Description:**
> Shown as the image attached. 
> When success count is '38' and throttle count shows as '0' graph shows as dot (for success count) in red color which is the color for the throttle count.
> ![Screenshot from 2016-09-23 11-01-38](https://user-images.githubusercontent.com/4471756/58424839-ffc44700-80b5-11e9-99a1-9b1ef9c2982b.png)
> 

By @dimuthud from https://wso2.org/jira/browse/APIMANAGER-5395

**Comment by chamilaadhi** [comment]
DAS is no longer a supported product
