### ISSUE TITLE
API Latency in Publisher statistics is not shown when API contains two version without any data for 1st version

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4879]
> **Description:**
> 
> 1. Create an API with v1.0.0.
> 2. Don't do any API requests.
> 3. Create another version of the API (eg: v2.0.0).
> 4. Do a number of API requests.
> 5. After the spark scripts ran, Go to publisher statistics. and select API Latency.
> 6. No graphs will be shown.
> 
> **Note: It will try to load statistics for the API selected and for its 1st version. And since there are no data, the following will be shown.**
> <img width="409" alt="Screen Shot 2017-10-03 at 4 56 01 PM" src="https://user-images.githubusercontent.com/4471756/58425082-8e38c880-80b6-11e9-93a4-a81f169d3f09.png">

By @ramindu90 from https://wso2.org/jira/browse/APIMANAGER-5922

**Comment by isharac** [comment]
This is invalid in the latest product version 3.2.0  as we no longer use spark. 
Hence closing.
