### ISSUE TITLE
Invoking APIM with MutualSSL and email login can result in redundant DB entries

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4882]
> **Description:**
> Configure IS as Key Manager and configure APIM to use MutualAuthentication as follows,
> 
> wso2am-1.10.0\repository\conf\tomcat\catalina-server.xml: clientAuth = want
> wso2am-1.10.0\repository\deployment\server\jaggeryapps\store\site\conf\site.json, mutualAuthConfiguration.enabled=true
> Set EnableEmailUserName to true in carbon.xml
> 
> It seems that the default tenant domain is not automatically appended when only an e-mail address is set in the MutualAuthUserName HTTP header.
> 
> As an example, a call on store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag to setup a subscription: Set admin@wso2.com as MutualAuthUserName HTTP header. Subscription will be successfully created, though it will not be shown nor be usable for the user. When using admin@wso2.com@carbon.super as value for the HTTP header, another subscription will be created; this one is visible in APIM Store UI. Verified and multiple records are inserted in the am_subscriber and am_subscription tables.
> 
By @uvindra from https://wso2.org/jira/browse/APIMANAGER-4586
> Same issue occurs for other operations, such as the creation of new applications. Result is always the same: db is cluttered with unnecessary records that, in the end, are never used.
>

**Comment by tharindu1st** [comment]
invalid due to ui revamp
