### ISSUE TITLE
Throttling level increases with the number of gateway nodes used

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4884]
**Description:**
In a clustered gateway setup throttling levels get increased proportionately to the number of gateway nodes used.

According to observations throttleDataHolder in ThrottleUpdateClusterMessage class turns up to be null even the cluster messages are received successfully.

By @mpmunasinghe from https://wso2.org/jira/browse/APIMANAGER-4540

**Comment by SwatiNEC** [comment]
Hi 

I am also facing similar type of issue. I am using wso2apim 2.6.0. Is it fixed in upgraded version?

**Comment by tharindu1st** [comment]
This is already being fixed
