### ISSUE TITLE
Unable to add a document when the doc name have parenthesis

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4886]
> **Description:**
> 1. Go to 'Docs' section of a published API in Publisher
> 2. Click Add New Document button
> 3. Give a name including parenthesis ( Ex : Doc Visibility (Public) ) 
> 4. Give a summary, type and source and press Add Document button
> 
> Window isn't redirect to 'docs' page by adding the document and there wasn't any error message either.
> 
> Note: It won't work either open or close parenthesis use in a single instance as well.

By @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-4709

**Comment by praveen-kg** [comment]
Hi,

I would like to contribute towards fixing issues. Please let me know shall I pick this defect

**Comment by AmaliMatharaarachchi** [comment]
This issue does not exist in version 3.0.0. Hence we can close the ticket.

**Comment by AmaliMatharaarachchi** [comment]
@praveen-kg We would appreciate your contribution. You can follow this guideline[1] on contributing to the codebase. You can use this channel[2] to raise your concerns and discuss with the team.
[1] http://wso2.github.io/
[2] https://wso2-apim.slack.com/join/shared_invite/enQtNzEzMzk5Njc5MzM0LTgwODI3NmQ1MjI0ZDQyMGNmZGI4ZjdkZmI1ZWZmMjNkY2E0NmY3ZmExYjkxYThjNzNkOTU2NWJmYzM4YzZiOWU?src%3Dsidebar&sa=D&source=hangouts&ust=1568265414013000&usg=AFQjCNHD-wMGtbyC7jBpnMAaqoZXqlWmxQ
