### ISSUE TITLE
Replace WSO2CARBON_DB.h2.shipped with wso2is-km-5.3.0 pack

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4887]
> **Description:**
> During APIM with IS as keymanager deplyments in docker containers. when starting IS node(starting new container), resource permissions related to apimgt resources get removed from the system.
> 
> e.g: for /_system/governance/apimgt/applicationdata resource has permisions for below
> 
> Before IS node starts.
> INTERNAL/creator - read/write/delete
> INTERNAL/everyone - read
> INTERNAL/publisher - read/write/delete
> SYSTEM/wso2.anonymous.role - read
> 
> After starts
> INTERNAL/everyone - read
> 
> all the custom permissions added for that resource removed during IS node startup.
> 
> This happens because when we setup mount in IS node(override=true), system delete all the resources under the mounted path(under /_system/governance if we mount gov registry) in local embedded db(h2 db). when deleting the resource, it also deletes the permissions associated with the resource. During this process, the system deletes permissions of /_system/governance/apimgt/applicationdata resource as well, because /_system/governance/apimgt/applicationdata resource already exists in the local h2 database which is shipped with the default pack.
> 
> As a solution replace WSO2CARBON_DB.h2.shipped with wso2is-km-5.3.0 pack with WSO2CARBON_DB.h2.shipped with IS 5.3 pack.

By @sambaheerathan from https://wso2.org/jira/browse/APIMANAGER-5861

**Comment by isharac** [comment]
Since APIM 3.2.0 we have got rid of the IS-KM dependency hence there is no IS_KM pack.
