### ISSUE TITLE
No indication to identify the distribution using API Usage pie chart without clicking it

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4888]
> **Description:**
> Pre-Condition - Few APIs should be available and invocation of APIs has to be done before.
> 
> 1. Go to 'Statistics' in Publisher
> 2. Click 'API Usage Comparison'
> 3. A pie chart and a table should be displayed.
> 
> Sections in pie chart couldn't distinguish properly since there're no labels for APIs or percentage.

By @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-5016

**Comment by chamilaadhi** [comment]
Analytics related pages are not available in the latest APIM versions.
