### ISSUE TITLE
Message mediator with validation sequence is not working

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4890]
> **Description:**
> We have an SOAP API that we will schema validation before the soap enveloping part is removed and the payload is sent to the back end system.
> When we add the validation part to our mediation component (mediator sequence with a schema validation) the publisher UI in step "2 Implementation" throws an error and the mediator component is not being added at the in flow.
> We have the exact same setup in wso2am 1.10 where this is working.
> 
> Mediator component (Note!, if I just use a x-path validation and not use schema and resources I get same error):
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <sequence name="pHUB0005-A2A-GoodsReceiptConfirmationSequnce"
> trace="enable" xmlns="http://ws.apache.org/ns/synapse">
> <log level="full">
> <property name="IN_MESSAGE" value="IN_MESSAGE"/>
> </log>
> <validate>
> <schema key="gov:apimgt/applicationdata/wsdls/phub/erprs/pHUB0047-Resources-PhoenixRS-WSO2AMWSDL/Ura-Phx-pHub-Contract-Outbound.xsd"/>
> <resource
> key="gov:apimgt/applicationdata/wsdls/phub/erprs/pHUB0047-Resources-PhoenixRS-WSO2AMWSDL/Ura-Phx-pHub-Contract-Outbound.xsd" location="Ura-Phx-pHub-Contract-Outbound.xsd"/>
> <resource
> key="gov:apimgt/applicationdata/wsdls/phub/erprs/pHUB0047-Resources-PhoenixRS-WSO2AMWSDL/Ura-Phx-pHub-Contract.xsd" location="Ura-Phx-pHub-Contract.xsd"/>
> <on-fail>
> <makefault version="soap11">
> <code value="soap11Env:Client" xmlns:soap11Env="http://schemas.xmlsoap.org/soap/envelope/"/>
> <reason expression="get-property('ERROR_MESSAGE')"/>
> <role/>
> </makefault>
> <log level="full"/>
> <property name="RESPONSE" scope="default" type="STRING" value="true"/>
> <header action="remove" name="To" scope="default"/>
> <send/>
> </on-fail>
> </validate>
> <property name="messageType" scope="axis2" type="STRING" value="application/xml"/>
> <log level="full">
> <property name="IN_MESSAGE" value="IN_MESSAGE"/>
> </log>
> </sequence>
> ```
> ![Design](https://user-images.githubusercontent.com/4471756/58426960-cabaf300-80bb-11e9-864a-4818457c666c.JPG)
> 
> ![Overview](https://user-images.githubusercontent.com/4471756/58426967-d0b0d400-80bb-11e9-80b4-0c677a43ad44.JPG)
> [partofstacktrace.txt](https://github.com/wso2/product-apim/files/3224171/partofstacktrace.txt)
> 
> 
By Johan Kitti from https://wso2.org/jira/browse/APIMANAGER-5501

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
