### ISSUE TITLE
Couldn't save an application without including a callback url after adding the url for the first time

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4896]
> **Description:**
> 1. Logged into store, create an application.
> 2. Go to 'Production Keys' or 'Sandbox Keys' of the created application (Let's say 'Production Keys')
> 3. Provide a 'call back url' and click 'Generate Keys' to generate production keys.
> 4. Now remove callback url and press update
> 
> 'Implicit' and 'Code' grant types should be unselected. (check attachment - No implicit and code)
> 
> 5. Again go to Application
> 
> Previously defined callback url can be seen in here. (check attachment - Callback url after remove)
> 
> ![Callback url after remove](https://user-images.githubusercontent.com/4471756/58429563-eb874680-80c3-11e9-847b-e8f02687f8d5.png)
> ![No implicit and code](https://user-images.githubusercontent.com/4471756/58429565-ec1fdd00-80c3-11e9-9b18-b3c8cdb92b06.png)

BY @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-5188

**Comment by tharindu1st** [comment]
This is fixed in latest ui
