### ISSUE TITLE
API Usage statistics chart should be more visible in IE11 on Windows

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4897]
> **Description:**
> Pre-Conditions - Few APIs should be available and need to invoke few of them.
> 
> 1. Go to Statistics -> APIs -> API Usage in Publisher
> 
> The statistics graph is proportionally small (check attachment - API Usage 1) and it's hard to observe the stats on graph when the Hit count is 0 for an API (check attachment - API Usage 2)
> ![API Usage 1](https://user-images.githubusercontent.com/4471756/58434409-20ea5f00-80d9-11e9-8dca-d3c89076ac1d.jpg)
> ![API Usage 2](https://user-images.githubusercontent.com/4471756/58434411-221b8c00-80d9-11e9-9835-185fb035e52d.jpg)
> 

By @maneeshaheshan from https://wso2.org/jira/browse/APIMANAGER-5007

**Comment by chamilaadhi** [comment]
Stats pages are not available in latest APIM versions
