### ISSUE TITLE
Applications list in store fail when there is a mix of encrypted and un-encrypted keys

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4899]
> **Description:**
> Applications are not loaded when there is a mix of encrypted and un-encrypted keys.Following error is observed.
> 
> to reproduce
> 
> 1. enable token encryption(EncryptPersistedTokens and TokenPersistenceProcessor).
> 2. login to store and create app and generate keys.
> 3. disable token encryption.
> 4. login to to store and create a new app and generate keys.
> 5. enable token encryption.
> 6. login to store and goto application page.
> 
> ```
> [2016-07-08 11:24:45,757] ERROR - AMDefaultKeyManagerImpl Can not retrieve OAuth application for the given consumer key : AwQGXLBYYIJG2sYfscy_nBeCSSka
> java.lang.NullPointerException
> 	at java.io.StringReader.<init>(StringReader.java:50)
> 	at org.json.JSONTokener.<init>(JSONTokener.java:84)
> 	at org.json.JSONObject.<init>(JSONObject.java:321)
> 	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication(AMDefaultKeyManagerImpl.java:244)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getClientOfApplication(ApiMgtDAO.java:2401)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getOAuthApplications(ApiMgtDAO.java:2365)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplications(ApiMgtDAO.java:4501)
> 	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplications(APIConsumerImpl.java:3108)
> 	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.getApplications(UserAwareAPIConsumer.java:36)
> 	at org.wso2.carbon.apimgt.hostobjects.APIStoreHostObject.jsFunction_getApplications(APIStoreHostObject.java:3074)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.store.modules.application.c1._c_anonymous_1(/store/modules/application/list.jag:9)
> 	at org.jaggeryjs.rhino.store.modules.application.c1.call(/store/modules/application/list.jag)
> 	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
> 	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
> 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.store.modules.application.c0._c_anonymous_2(/store/modules/application/module.jag:9)
> 	at org.jaggeryjs.rhino.store.modules.application.c0.call(/store/modules/application/module.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.c0._c_anonymous_3(/store/site/blocks/application/application-list/block.jag:16)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.c0.call(/store/site/blocks/application/application-list/block.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:278)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_29(/store/jagg/jagg.jag:338)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:273)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_29(/store/jagg/jagg.jag:338)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_28(/store/jagg/jagg.jag:273)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
> 	at org.jaggeryjs.rhino.store.jagg.c0._c_anonymous_50(/store/jagg/jagg.jag:659)
> 	at org.jaggeryjs.rhino.store.jagg.c0.call(/store/jagg/jagg.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.store.site.pages.c3._c_anonymous_1(/store/site/pages/applications.jag:17)
> 	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/applications.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> 	at org.jaggeryjs.rhino.store.site.pages.c3._c_script_0(/store/site/pages/applications.jag:10)
> 	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/applications.jag)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> 	at org.jaggeryjs.rhino.store.site.pages.c3.call(/store/site/pages/applications.jag)
> 	at org.jaggeryjs.rhino.store.site.pages.c3.exec(/store/site/pages/applications.jag)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:587)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:507)
> 	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
> 	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-07-08 11:24:45,760] ERROR - applications:jag org.wso2.carbon.apimgt.api.APIManagementException: Can not retrieve OAuth application for the given consumer key : AwQGXLBYYIJG2sYfscy_nBeCSSka
> [2016-07-08 11:24:46,002] ERROR - PassThroughHttpSSLSender IO Error sending response message
> org.apache.axis2.AxisFault: Invalid white space character (0x14) in text to output (in xml 1.1, could output as a character entity)
> 	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
> 	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.sendUsingOutputStream(PassThroughHttpSender.java:307)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:271)
> 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> 	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:43)
> 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
> 	at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:146)
> 	at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:231)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:59)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: com.ctc.wstx.exc.WstxIOException: Invalid white space character (0x14) in text to output (in xml 1.1, could output as a character entity)
> 	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:462)
> 	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.writeCharacters(MTOMXMLStreamWriter.java:289)
> 	at org.apache.axiom.om.impl.llom.OMTextImpl.writeOutput(OMTextImpl.java:261)
> 	at org.apache.axiom.om.impl.llom.OMTextImpl.internalSerialize(OMTextImpl.java:426)
> 	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
> 	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:875)
> 	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
> 	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:875)
> 	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
> 	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:875)
> 	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
> 	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:875)
> 	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.serializeInternally(SOAPEnvelopeImpl.java:283)
> 	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:245)
> 	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serializeAndConsume(OMSerializableImpl.java:193)
> 	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
> 	... 60 more
> Caused by: java.io.IOException: Invalid white space character (0x14) in text to output (in xml 1.1, could output as a character entity)
> 	at com.ctc.wstx.api.InvalidCharHandler$FailingHandler.convertInvalidChar(InvalidCharHandler.java:55)
> 	at com.ctc.wstx.sw.XmlWriter.handleInvalidChar(XmlWriter.java:623)
> 	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:554)
> 	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:460)
> 	... 75 more
> [2016-07-08 11:24:46,006] ERROR - AMDefaultKeyManagerImpl Can not retrieve OAuth application for the given consumer key : AwQGXLBYYIJG2sYfscy_nBeCSSka
> java.lang.NullPointerException
> 	at java.io.StringReader.<init>(StringReader.java:50)
> 	at org.json.JSONTokener.<init>(JSONTokener.java:84)
> 	at org.json.JSONObject.<init>(JSONObject.java:321)
> 	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication(AMDefaultKeyManagerImpl.java:244)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getClientOfApplication(ApiMgtDAO.java:2401)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getOAuthApplications(ApiMgtDAO.java:2365)
> 	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplications(ApiMgtDAO.java:4501)
> 	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplications(APIConsumerImpl.java:3108)
> 	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.getApplications(UserAwareAPIConsumer.java:36)
> 	at org.wso2.carbon.apimgt.hostobjects.APIStoreHostObject.jsFunction_getApplications(APIStoreHostObject.java:3074)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.store.modules.application.c1._c_anonymous_1(/store/modules/application/list.jag:9)
> 	at org.jaggeryjs.rhino.store.modules.application.c1.call(/store/modules/application/list.jag)
> 	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
> 	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
> 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.store.modules.application.c0._c_anonymous_2(/store/modules/application/module.jag:9)
> 	at org.jaggeryjs.rhino.store.modules.application.c0.call(/store/modules/application/module.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0._c_anonymous_1(/store/site/blocks/application/application-list/ajax/application-list.jag:38)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0.call(/store/site/blocks/application/application-list/ajax/application-list.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0._c_script_0(/store/site/blocks/application/application-list/ajax/application-list.jag:4)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0.call(/store/site/blocks/application/application-list/ajax/application-list.jag)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0.call(/store/site/blocks/application/application-list/ajax/application-list.jag)
> 	at org.jaggeryjs.rhino.store.site.blocks.application.application_list.ajax.c0.exec(/store/site/blocks/application/application-list/ajax/application-list.jag)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:587)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:507)
> 	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
> 	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-07-08 11:24:46,008] ERROR - application-list:jag org.wso2.carbon.apimgt.api.APIManagementException: Can not retrieve OAuth application for the given consumer key : AwQGXLBYYIJG2sYfscy_nBeCSSka
> ```

By Dumidu Handakumbura from https://wso2.org/jira/browse/APIMANAGER-5213

**Comment by tharindu1st** [comment]
invalid issue
