### ISSUE TITLE
Issuing multiple requests to Store API in parallel results in NPE

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4904]
> **Description:**
> When issuing multiple simultaneous requests against the Store API to perform the following sequence of actions:
> 
> - create a user
> - login as the user
> - create an application
> - generate production tokens
> - generate sandbox tokens
> 
> WSO2 API Manager sporadically results in the following NullPointerException:
> 
> ```
> [2015-10-22 19:09:15,122] ERROR - APIStoreHostObject Error while obtaining the application access token for the application:zls80py14i
> java.lang.NullPointerException
> 	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.requestApprovalForApplicationRegistration(APIConsumerImpl.java:2247)
> 	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.requestApprovalForApplicationRegistration(UserAwareAPIConsumer.java:34)
> 	at org.wso2.carbon.apimgt.hostobjects.APIStoreHostObject.jsFunction_getApplicationKey(APIStoreHostObject.java:757)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
> 	at org.jaggeryjs.rhino.store.modules.subscription.c1._c_anonymous_2(/store/modules/subscription/key.jag:39)
> 	at org.jaggeryjs.rhino.store.modules.subscription.c1.call(/store/modules/subscription/key.jag)
> 	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
> 	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
> 	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
> 	at org.jaggeryjs.rhino.store.modules.subscription.c0._c_anonymous_9(/store/modules/subscription/module.jag:32)
> 	at org.jaggeryjs.rhino.store.modules.subscription.c0.call(/store/modules/subscription/module.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0._c_anonymous_1(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag:239)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0.call(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0._c_script_0(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag:3)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0.call(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0.call(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag)
> 	at org.jaggeryjs.rhino.store.site.blocks.subscription.subscription_add.ajax.c0.exec(/store/site/blocks/subscription/subscription-add/ajax/subscription-add.jag)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
> 	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
> 	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:541)
> 	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
> 	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
> ```
> Attached is a simple NodeJS application that can reproduce the error by running the following command:
> `node publish.js localhost 9763`
> 
> If I change the example to execute the requests sequentially, no NPE is thrown. Also, changing the number of simultaneous processes to just 1 or 2 results in success. If I change the example to use "admin" / "admin" instead of creating a new user, it also succeeds.
> 
> This bug is reproducible in both 1.9.0 and 1.9.1.

By Shane Gibson from https://wso2.org/jira/browse/APIMANAGER-5791

**Comment by isharac** [comment]
Invalid as jaggery APIs are no longer in use in the latest version 3.2.0.
