### ISSUE TITLE
No ability to edit Swagger for SOAP APIs

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4905]
**Description:**

> I created a SOAP API in API Cloud by importing WSDL file. I want to then edit the Swagger definition to add parameter descriptions and add schema for the request. Yet, when API is created with WSDL import, API Cloud does not give any way to edit the Swagger definition - so there is no way for me to provide parameter descriptions or request schema.
By Dmitry Sotnikov from https://wso2.org/jira/browse/APIMANAGER-4174

**Comment by isharac** [comment]
This is fixed in the latest react based publisher application.
