### ISSUE TITLE
Can not save API's - api publisher using Windows Authenticated SQL Server connection

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4915]
> **Description:**
> Windows authentication can be achieved using JTDS driver. However when APIM is currently not supporting this Driver. We get errors while trying to save APIs. Need to implement this driver support.

By @dimuthud from https://wso2.org/jira/browse/APIMANAGER-4136

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
