### ISSUE TITLE
Session invalidate not handled properly

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4917]
> **Description:**
> When a user clicks on logout button jagg.setUser(null) get called and seems session invalidation not handled successfully.
> 
> If you try to call any other set session property, you can get those with previously logged user settings.
> 
> To reproduce:
> 
> 1. Set session variable when user login : session.put("KEY", "val")
> 2. Retrieve on block level print(session.get("KEY'));
> 3. Click log out on top. this will redirect you to home page
> 4. Go back again to the previous block
> 
> you can still see the previous sets values

By @dakshika from https://wso2.org/jira/browse/APIMANAGER-5428

**Comment by isharac** [comment]
This issue is invalid as latest versions(> 3.0.0 ) use react based web applications
