### ISSUE TITLE
ServerWorker Error processing GET reguest for

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4920]
> **Description:**
> Hi,
> 
> I've created a custom authentication handler. Now, it's silly and it hasn't security.
> 
> I've used this link:
> 
> https://docs.wso2.com/display/AM210/Writing+Custom+Handlers
> 
> My code is:
> 
> ```java
> package com.example.custom.wso2.apimanager;
> 
> import java.util.Map;
> 
> import org.apache.synapse.MessageContext;
> import org.apache.synapse.core.axis2.Axis2MessageContext;
> import org.apache.synapse.rest.AbstractHandler;
> 
> public class CustomAPIAuthenticationHandler extends AbstractHandler {
> 
> public boolean handleRequest(final MessageContext messageContext)
> 
> { return authenticate(messageContext); }
> 
> public boolean handleResponse(final MessageContext messageContext) { return authenticate(messageContext); }
> public boolean authenticate(MessageContext synCtx)
> 
> { return true; }
> private String getAuthorizationHeader(Map headers)
> 
> { return (String) headers.get("Authorization"); }
> private Map getTransportHeaders(MessageContext messageContext)
> 
> { return (Map) ((Axis2MessageContext) messageContext).getAxis2MessageContext() .getProperty(org.apache.axis2.context.MessageContext.TRANSPORT_HEADERS); }
> }
> 
> I deploy it. And then I change /wso2am-2.1.0/repository/deployment/server/synapse-configs/default/api/*.xml file. In the log, it's printed:
> 
> [2017-11-24 12:28:16,888] INFO - API Initializing API: admin--Example:v1.0.0
> [2017-11-24 12:28:16,891] INFO - DependencyTracker API : admin--Example:v1.0.0 was updated from the Synapse configuration successfully
> [2017-11-24 12:28:16,891] INFO - APIDeployer API: admin-Example:v1.0.0 has been updated from the file: /wso2am-2.1.0/repository/deployment/server/synapse-configs/default/api/admin-Example_v1.0.0.xml
> [2017-11-24 12:28:18,891] INFO - API Destroying API: admin--Example:v1.0.0
> 
> Then if it access to any resource with API Manager, this error is showed:
> 
> 2017-11-24 12:34:55,556 [-] [PassThroughMessageProcessor-4] ERROR ServerWorker Error processing GET reguest for : /Example/1.0.0/access/findallZones. Error detail: null. 
> java.lang.NullPointerException
> at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doRoleBasedAccessThrottlingWithCEP(ThrottleHandler.java:189)
> at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.doThrottle(ThrottleHandler.java:497)
> at org.wso2.carbon.apimgt.gateway.handlers.throttling.ThrottleHandler.handleRequest(ThrottleHandler.java:445)
> at org.apache.synapse.rest.API.process(API.java:325)
> at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
> at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
> at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:330)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:159)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> ```
> 
> The same error is showed if I restart the server. No error are showed in the startup but when I call to resource in API Manager the same error is showed.
> 
> Thanks
By Luis Durán from https://wso2.org/jira/browse/APIMANAGER-6012

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
