### ISSUE TITLE
Endpoint advanced configurations are not available with get API payload.

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#4921]
**Description:**
After saving the endpoint advanced configurations from the old publisher UI as follows.

<img width="999" alt="Screen Shot 2019-05-28 at 12 34 58 PM" src="https://user-images.githubusercontent.com/3424539/58457787-27aebb80-8145-11e9-902f-7b642ab49a92.png">

They are not available with the payload of get api call from new rest api.

<img width="358" alt="Screen Shot 2019-05-28 at 12 30 19 PM" src="https://user-images.githubusercontent.com/3424539/58457716-fb933a80-8144-11e9-9494-d476932b49b2.png">

**Comment by malinthaprasan** [comment]
Fixed by switching to the older endpointConfig element which was already there from 0.x REST APIs
