### ISSUE TITLE
[API -Migration] When migrating from APIM 1.8 to 2.00 it transfers the NULL values in GRANT_TYPES column

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4924]
> **Description:**
> When migrating from APIM 1.8 to 2.0.0, The GRANT_TYPES column in IDN_OAUTH_CONSUMER_APPS fills with null values. When the user has not selected any grant types in APIM 1.8. It should be an empty string rather than a null value for GRANT_TYPES.
> 
By @tmkasun from https://wso2.org/jira/browse/APIMANAGER-5685

**Comment by isharac** [comment]
Need to fix the migration client add the supported grant types in the identity.xml instead of null when migrating the GRANT_TYPES .

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
