### ISSUE TITLE
WSO2 APIM call returns Resource forbidden ((900908) with valid a token and a valid subscription

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#4925]
> **Description:**
> We recently had one case where one of our WSO2 APIM subsriber was unable to call the service as it was always returning authentication fault:
> <faultstring>Authentication Failure</faultstring>
> <detail>Access failure for API: /GetInstances-ILD-sit/0, version: 0 status: (900908) - Resource forbidden</detail>
> 
> Same authentication token was working fine with other subscribed APIs. We checked the API subscription from Store UI and it showed that the API was subsribed to the user/application. We also checked WSO2 APIM database for this particular API subscription according to the database the API was allready subscribed:
> 
> `mysql> select * from AM_API where API_NAME='GetInstances-ILD-sit';`
> 
>` API_ID API_PROVIDER API_NAME API_VERSION CONTEXT CONTEXT_TEMPLATE API_TIER CREATED_BY CREATED_TIME UPDATED_BY UPDATED_TIME`
> 
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 729 acbpublisher GetInstances-ILD-sit 0 /GetInstances-ILD-sit/0 /GetInstances-ILD-sit NULL acbpublisher 2018-08-07 15:02:10 NULL 2018-08-07 15:02:10
> 
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 1 row in set (0.00 sec)
> 
>` mysql> select * from AM_SUBSCRIPTION where API_ID='729';`
> ----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> `SUBSCRIPTION_ID TIER_ID API_ID LAST_ACCESSED APPLICATION_ID SUB_STATUS SUBS_CREATE_STATE CREATED_BY CREATED_TIME UPDATED_BY UPDATED_TIME UUID`
> 
> ----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 793 Gold 729 NULL 1 UNBLOCKED SUBSCRIBE admin 2018-08-20 14:43:44 NULL 2018-08-20 14:43:43 b75abd9c-9604-42c9-987b-411d5d76b770
> 1420 Gold 729 NULL 10 UNBLOCKED SUBSCRIBE d040000 2018-11-01 12:15:44 NULL 2018-11-01 12:15:44 2cdac5f0-247c-4ec0-88b4-9982cfda8f88
> 1408 Gold 729 NULL 12 UNBLOCKED SUBSCRIBE b2b 2018-10-31 08:40:34 NULL 2018-10-31 08:40:34 a594eaff-c5f7-4dbe-a5e4-7d4dc830949f 
> 609 Gold 729 NULL 20 UNBLOCKED SUBSCRIBE healthcheck 2018-08-07 15:22:33 NULL 2018-08-07 15:22:32 25b01f2a-fc5a-47dd-bc4f-4fe210f8e94d
> 1422 Gold 729 NULL 31 UNBLOCKED SUBSCRIBE a065600 2018-11-01 14:59:36 NULL 2018-11-01 14:59:35 f4ed225c-98dc-4620-96c7-1ff412c837d7
> 1102 Gold 729 NULL 43 UNBLOCKED SUBSCRIBE testautomation 2018-10-04 13:00:19 NULL 2018-10-04 13:00:19 91e07ff5-6b75-4f4e-b4d0-6d71f1d8055e
> 
By Tero Marttinen from https://wso2.org/jira/browse/APIMANAGER-6105

**Comment by kavithasub** [comment]
Hi, Do you have any update on this issue? We experience the same issue using apim-2.6.0.

**Comment by chathurabuddi** [comment]
I had the same problem and solved it by disabling `Advance Throttling`  from IS (IS-AS-KM). 

```xml
<ThrottlingConfigurations>
        <EnableAdvanceThrottling>false</EnableAdvanceThrottling>
        ...
</ThrottlingConfigurations>
```

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
