### ISSUE TITLE
Gateway profile looks for MBStoreDB in startup

### ISSUE THREAD

**Issue by mcvidanagama** [wso2/product-apim#4926]
**Description:**
Even when the node is started as gateway worker[1], it looks for mb store db at startup. If we havent added mbstore in any of the datasources files the startup fails.

**Suggested Labels:**
APIM, 260,gateway_profile
**Suggested Assignees:**
N/A
**Affected Product Version:**
260 -wum updated up to date of creation of this issue
**OS, DB, other environment details and versions:**    
RHEL7, Puppet controlled deployment
**Steps to reproduce:**
Remove mb store db configs from datasources file.
Start server with command[1]

[1] - ./bin/wso2server.sh --optimize -Dprofile=gateway-worker -DworkerNode=true start
**Related Issues:**
N/A

**Comment by dushaniw** [comment]
Even though we are not using MB store DB in Gateway, during the server startup, when the broker component tries to initialize, it looks for the MB store DB. Hence we need to keep the default H2 configuration as it is in master-datasource.xml. Need to update the documentation.

**Comment by dushaniw** [comment]
Tracking the documentation in https://github.com/wso2/product-apim/issues/5042.
