### ISSUE TITLE
Cannot list more than 50 roles in the permission panel of a registry collection in the carbon console.

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-apim#4929]
**Description:**
When an user have more than 50 roles, it will not listed under the permission panel of a registry collection in carbon console. For an example, browse to following registry collection in the carbon console and open permission panel. 

/_system/governance/apimgt/customsequences

If you have more than 50 roles, those will not listed under the role dropdown. 

This will prevent users from giving permissions to different roles to access and modify registry resources, if they have more than 50 roles.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tharindu1st** [comment]
This is an invalid use case where APIM doesn't need to assign roles from the registry console to APIM resources.
