### ISSUE TITLE
store-new and publisher-new logos are low resolution

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-apim#4947]
please see - https://www.dropbox.com/s/hqb6b1q1xwul4t0/Screenshot%202019-05-31%2017.11.45.png?dl=0

This is a mac retina display.

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="1437" alt="Screen Shot 2019-10-11 at 2 31 28 PM" src="https://user-images.githubusercontent.com/4861150/66639131-e589a080-ec33-11e9-9a5a-46ad653b1fa2.png">
