### ISSUE TITLE
Add extension point to sign-up-config.xml password field for encryption

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#4948]
There can be a requirement to encrypt password in the sign-up-config.xml file. Since we do not have a method to encrypt/decrypt passwords in the registry files, it is better if we can provide an extension to plug custom implementation to sign-up-config.xml file (similar to what we do in workflow-extensions.xml). This way anyone can implement their own method to decrypt the values.

**Comment by AmaliMatharaarachchi** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/6650
