### ISSUE TITLE
Custom policies are not allowed to edit, keeping the same Key Template and Name.

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#4949]
When trying to edit an existing custom policy via UI or REST API, we get the error, "Key Template Already Exists. Add a new Key Template".

When we are updating custom policies, we check whether any policies are available with same key template and policy name using the following query.

`SELECT KEY_TEMPLATE FROM AM_POLICY_GLOBAL WHERE TENANT_ID =? AND KEY_TEMPLATE =? AND NAME =?
`
At that point, since the DB has the same policy name and key template for the current policy we are editing, the update fails with error "Key Template Already Exists". The NAME field in AM_POLICY_GLOBAL table is not unique, and we are letting to change both Name and KeyTemplate when editing the policy. Hence according to the current implementation having multiple policies with the same name is allowed.

So we need to restrict the UI to edit the name when trying to update the existing policies. Remove the Key Template exists check from update policy flow. Add policy name exist check when adding new policies.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6467
