### ISSUE TITLE
Custom policy with $resourceKey variable does not throttle requests

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#4950]
**Description:**
When $resourceKey is used as the key template for custom throttle policies, requests are not throttled out.

**Affected Product Version:**
API Manager 2.1.0  

**Steps to reproduce:**
1. Create a new custom throttling policy from Admin UI.
2. Use the following policy. ($userId:$resourceKey is the Key Template). Replace the userId and the resourceKey accordingly in the query below.

FROM RequestStream
SELECT userId, ( userId == 'admin@carbon.super' AND resourceKey == '/sample2/1.0/1.0/myresource1:GET') AS isEligible ,
str:concat('admin@carbon.super',':','/sample2/1.0/1.0/myresource1:GET') AS throttleKey

INSERT INTO EligibilityStream;
FROM EligibilityStream[isEligible==true]#throttler:timeBatch(1 min)
SELECT throttleKey, (count(userId) >= 2) as isThrottled, expiryTimeStamp group by throttleKey
INSERT ALL EVENTS INTO ResultStream;

3. Check whether the requests throttle out based on the condition specified in the policy.

**Comment by npamudika** [comment]
Fixed with above PR.
