### ISSUE TITLE
[Micro GW] Few hyperlinks are pointing to old APIM docs

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-apim#4957]
Most of the hyperlinks in the Micro GW docs point to old APIM(2.5) docs

- "**View documentation**" link on the download page
- See "**Microgateway quick start**" hyperlink of [this](https://docs.wso2.com/display/AM260/Overview+of+the+Microgateway) doc

**Comment by pubudu538** [comment]
Could you please create this issue in https://github.com/wso2/product-microgateway ?

**Comment by rnavagamuwa** [comment]
Will do.

**Comment by rnavagamuwa** [comment]
https://github.com/wso2/product-microgateway/issues/594

**Comment by pubudu538** [comment]
Thank you!
