### ISSUE TITLE
Swagger-UI intergration regression can't provide custom plugins, presets etc

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#4958]
We have used the [swagger-ui-react](https://www.npmjs.com/package/swagger-ui-react) library due to some [know issues](https://github.com/swagger-api/swagger-ui/issues/4745) in swagger-ui library when used with React 16.x versions.
But the `swagger-ui-react` flavor is not configurable as much as it is with the default version. So we will need to :monkey_face:  patch the `swagger-ui` library until a proper configuring mechanism introduces to `swagger-ui-react` component.

**Comment by tmkasun** [comment]
Related to : https://github.com/wso2/product-apim/issues/4762

**Comment by tgtshanika** [comment]
Fixed in APIM 3.0.0 Alpha
