### ISSUE TITLE
Gracefully handle redirect to login page when token expires

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#4960]
**Description**
When the user access token expires, the redirect to the login page should be handled gracefully, rather than redirecting abruptly.

**Suggested labels**
3.0.0

**Comment by tmkasun** [comment]
IMHO We could address the user handling of completely log out users returning to store/publisher protected page.

For example, I haven't logged into publisher application before, But I got a link to `publisher-new/apis/6d5sa76das7da87da6ds87ad8sa7da/security` page. In this case, We should initiate the authorization flow on behalf of the user and after the user has been successfully logged-in. We should re-direct he/she to their original requested resource page in this case `publisher-new/apis/6d5sa76das7da87da6ds87ad8sa7da/security`

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6514, https://github.com/wso2/carbon-apimgt/pull/6599
