### ISSUE TITLE
[Doc]Missing information on registry mounting in a clustered setup

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-apim#4961]
The mounting 'config' registry between KM and APIM. The recommended approach is to use different targetPath for each product. Add this to the documents

 So we have to change the following configuration lines share in this comment to mount to separate targetPath in KM and APIM.

<mount path="/_system/config" overwrite="true">
   <instanceId>gov</instanceId>
   <targetPath>/_system/config</targetPath>
</mount>

Need to correct as,
In KM nodes,

<mount path="/_system/config" overwrite="true">
   <instanceId>gov</instanceId>
   <targetPath>/_system/config/is</targetPath>
</mount>

In APIM nodes,

<mount path="/_system/config" overwrite="true">
   <instanceId>gov</instanceId>
   <targetPath>/_system/config/apim</targetPath>
</mount>

**Comment by chamilaadhi** [comment]
2.6.0 docs are no longer updated and this content is invalid for the latest releases. Hence closing
