### ISSUE TITLE
[Doc] Missing information about updating token validity period in identity.xml

### ISSUE THREAD

**Issue by MalshaL** [wso2/product-apim#4968]
Validity period of access tokens can be modified by configuring the following parameters in `identity.xml`.

```
<AccessTokenDefaultValidityPeriod>
<UserAccessTokenDefaultValidityPeriod>
```

These changes will only take effect on **new applications** created through the API Store. This information should be added to the documentation at [1].

[1] https://docs.wso2.com/display/AM260/Token+API#TokenAPI-Configuringthetokenexpirationtime

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
