### ISSUE TITLE
endpointConfig needs improvement (Publisher REST API)

### ISSUE THREAD

**Issue by brendon-stephens** [wso2/product-apim#4975]
The endpointConfig model is confusing and not documented well anywhere. There are duplicate property names (eg. endpoint_type is used both at the root level of the document and within child object properties). Boolean property encapsulated within text (eg. failOver = "True".) Pointless properties - (eg. template_not_supported). Spelling mistake - (eg. retryErroCode).

The Swagger documentation gives one example, but it does not explain how to use for loadbalanced or failover endpoints. We have had to work this out by updating the UI and then retrieving the API using the REST API.

It also does not make sense from our perspective to embed these details into a JSON document.

**Comment by ruks** [comment]
There is a sample in the doc[1]. Please have a look.

[1] https://docs.wso2.com/display/AM260/apidocs/publisher/#!/models#APIDetailed

**Comment by bstep93** [comment]
Hi @ruks 

As mentioned, it is not documented completely. 

Also another issue to note is that the production_endpoints property can either be an object (when endpoint_type = http) or an array (when endpoint_type = load_balance). 

Thanks,
Brendon

**Comment by vithu30** [comment]
Hi @brendon-stephens,

The latest REST API doc has been improved. Please refer [1]. Examples are included for load balanced and fail-over endpoints as well.

[1] https://apim.docs.wso2.com/en/latest/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/APIs/paths/~1apis/post

**Comment by ruks** [comment]
Close the issue since the doc has been updated.
