### ISSUE TITLE
The name property in POST /apis/id/mediation is redundant

### ISSUE THREAD

**Issue by brendon-stephens** [wso2/product-apim#4976]
When creating mediation using the publisher API (POST /apis/id/mediation), the name property is mandatory. This property is not actually used and will be overwritten by the name attribute specified within the config sequence xml.

Step to reproduce:
1. Create a mediation resource using POST /apis/id/mediation. Ensure the name property is different to the name attribute specified in the config sequence xml.
2. Retrieve the API using GET /apis/id
3. Note the sequence definition has the name property as the attribute in the config sequence xml.

AM v2.6, REST API v0.14.

**Comment by kavishkafernando** [comment]
Public commit: #https://github.com/wso2/carbon-apimgt/commit/a32ad1b675ed1a992c795449d1682db530b1497d
