### ISSUE TITLE
"Deprecate Old Versions" not work in rest api when new version is published.

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#4982]
In the doc[1], says to use "lifecycleChecklist=Deprecate Old Versions:true". But this is not worked and noticed that "Deprecate old versions after publish the API:true" needs to be used instead "Deprecate Old Versions:true". This may not work for "Require Re-Subscription:true" as well.

So Docs or code level need to be updated.

[1] https://docs.wso2.com/display/AM260/apidocs/publisher/#!/operations#APIIndividual#apisChangeLifecyclePost

**Comment by dushaniw** [comment]
The documentation needs to be fixed. When providing lifecycleChecklist parameters needs to be specified as follows:

Deprecate old versions after publish the API:true
Requires re-subscription when publish the API:true
Sample curl command could be:

curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -X POST "https://localhost:9443/api/am/publisher/v0.14/apis/change-lifecycle?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish&lifecycleChecklist=Requires%20re-subscription%20when%20publish%20the%20API:true,Deprecate%20old%20versions%20after%20publish%20the%20API:true"
Please note that these parameters need to be URL encoded as it is having spaces.

**Comment by ruks** [comment]
Close since a solution has provided
