### ISSUE TITLE
Update documentation with the steps to hexify x5t claim in JWT header

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4983]
We have introduced a new system property to be enabled to hexify the x5t claim in JWT header in WUM update for API-M 2.2.0.
If the x5t claim needs to be hexified, the system property enableThumbprintHexify has to be set as true, as mentioned below:
`./wso2server.sh -DenableThumbprintHexify=true`

The documentation of "Passing end-user attributes to back-end using JWT" - [1] needs to be updated with the above information.

[1] https://docs.wso2.com/display/AM220/Passing+Enduser+Attributes+to+the+Backend+Using+JWT

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
