### ISSUE TITLE
[APIM 2.6.0] Distribued Deployment Documentation Issue

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#4985]
Distributed deployment [documentation](https://docs.wso2.com/display/AM260/Understanding+the+Distributed+Deployment+of+WSO2+API-M#UnderstandingtheDistributedDeploymentofWSO2API-M-UnderstandingtheWSO2API-Marchitecture) contains following issues.

1. Keeps referring to STAT DB. But in APIM analytics 2.6.0, there are no datasource called STATS_DB. (Available APIM_ANALYTICS_DB and WSO2AM_MGW_ANALYTICS_DB)

2. Diagram still depicts, that portals read data from stats_db.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
