### ISSUE TITLE
Alert email does not generated when subscribed from the APIM store.  

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#4999]
Steps to reproduce:
* Follow the steps in the docuemnetation[1] and subscribe to alerts from the store console.
* Although the alerts are generated in the admin console, the email alert was not received.
* This works fine in the GA pack.

Affected product version:
APIM-2.6.0 with APIM-Analytics-2.6.0

[1] https://docs.wso2.com/display/AM260/Configuring+Alerts#ConfiguringAlerts-ConfiguringalertsviatheStore

**Comment by npamudika** [comment]
Fixed with above PR.
