### ISSUE TITLE
[APIM 3.0.0] Monetization UI

### ISSUE THREAD

**Issue by chamindias** [wso2/product-apim#5005]
W.R.T [1], we need to add the UI related to,

1. Monetization enable/disable (publisher UI)
2. Display monetization data of subscription tiers (publisher UI)
3. Display monetization data of subscription tiers (store UI)

[1] https://github.com/wso2/product-apim/issues/4680

**Comment by chamindias** [comment]
Please find the PRs related to admin dashboard (to capture additional attributes for monetization purposes)

1. https://github.com/wso2/carbon-apimgt/pull/6448/commits/0eda604cae0aedafd6103a7703a1d47e0177d601
2. https://github.com/wso2/carbon-apimgt/pull/6468

**Comment by shilmyhasan** [comment]
Please find the PR to Monetization enable/disable (publisher UI)
[wso2/carbon-apimgt#6700](https://github.com/wso2/carbon-apimgt/pull/6700)

**Comment by chamindias** [comment]
Also, we need to add a buttons to get revenue (for metered billing, per subscriber);

a) For each subscription : getCurrentUsageForSubscription in [1]
b) For the whole API : getTotalRevenue in [1]

**Equivalent (old) UI :** 

![image](https://user-images.githubusercontent.com/8359365/62383915-a7ef0400-b56e-11e9-83ca-bd0906c8ad52.png)


[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Monetization.java

**Comment by chamindias** [comment]
In addition to the above, we need to add a buttons to get revenue (for metered billing, per subscriber) in store.

**Comment by chamindias** [comment]
Add capability in Publisher UI to view monetization invoice [Publisher] [UI/UX] : https://github.com/wso2/carbon-apimgt/pull/7085

**Comment by chamindias** [comment]
Show monetization pricing info in subscription tier dropdown : https://github.com/wso2/carbon-apimgt/pull/7051

**Comment by chamindias** [comment]
Improve monetization UI screens : https://github.com/wso2/carbon-apimgt/pull/6914

**Comment by chamindias** [comment]
Add a button to view the invoice in store : https://github.com/wso2/carbon-apimgt/pull/7128

**Comment by chamilaadhi** [comment]
closing since the feature is completed

**Comment by chamindias** [comment]
See : https://github.com/wso2/carbon-apimgt/pull/7694
