### ISSUE TITLE
Anonymous view in Store check LDAP and database for wso2.anonymous.user when checking roles

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#5008]
When we load the store using the "/store" URL, we load the API resources from the registry. Each registry resource has a permission tree attached. So when loading the APIs in the anonymous view, we get the role list from the permission tree of each API and check whether the user "wso2.anonymous.user" has any of the roles in the list. These roles are checked sequentially via a loop [1].

If there are non-internal roles in the allowed role list of API registry resources, we check whether these roles are there in the userstores. For example, if LDAP is used as the primary userstore, ReadOnlyLDAPUserStoreManager will initialize the connection to LDAP for each API to check the roles of the anonymous use until the role in the role list is "SYSTEM/wso2.anonymous" is read in \[1]. Then we allow access for the anonymous user according to [2].

However, ideally when checking the roles for wso2.anonymous.user, we need to check whether the roles list of the resource has "SYSTEM/wso2.anonymous" role and if the user is "wso2.anonymous.user", we should allow access and skip checking the other roles and return. 

[1] https://github.com/wso2/carbon-kernel/blob/v4.4.36/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/authorization/JDBCAuthorizationManager.java#L295
[2] https://github.com/wso2/carbon-kernel/blob/v4.4.36/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L3916

**Comment by nadeepoornima** [comment]
PR for the APIM 2.5.0 is here[1].
[1]. https://github.com/wso2-support/carbon4-kernel/pull/662

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/2296
