### ISSUE TITLE
URL parameter retrieval issue

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#5012]
If I need to perform a  GET operation on a resource with a repeated parameter, as a way of passing a list, for example:

 `http://<host-name>/sampleapi/endpoint?id=1&id=2&id=3`

If  API is called with those parameters and try different ways of retrieving the parameter values, followings were obserced.

$url:id  is equal to "1"
ctx:query.param.id is equal to "3"

There seems to be no way to get an array containing the three values, which is what I'd like (other than parsing REST_URL_POSTFIX from scratch, which I was hoping I wouldn't have to do.)

**Comment by npamudika** [comment]
Since this needs to be handled in the product-ei repo, created https://github.com/wso2/product-ei/issues/4322 to track.
