### ISSUE TITLE
Scope validation skips for the Apps which doesn't have any scope validators set

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5015]
With https://github.com/wso2/carbon-apimgt/pull/6460, we support optional scope validation for apps. But the new apps are created without any scope validators set; causing those apps to skip the scope validation.

This can be fixed by setting scope validator to SPs properly when generating keys. But it is not a solution for previously created apps.

This needs to be fixed by considering both new and already created apps to avoid any possible migrations.

**Comment by npamudika** [comment]
Fixed with above PRs.
