### ISSUE TITLE
Required Scopes Not Shown in Swagger UI

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#5039]
In API Manager 2.6, the required scope that was needed to call a method was shown in the API Console:
<img width="426" alt="Screen Shot 2019-06-19 at 9 36 54 AM" src="https://user-images.githubusercontent.com/19324135/59736085-cd9da380-9275-11e9-9b29-0d32b985bb04.png">
**Affected version:** APIM-2.6.0

**Comment by Arshardh** [comment]
We found a way to achieve this use case by enabling the showExtensions property of the swagger UI.
This displays all the vendor extensions added per resource.

**But we will have to rethink this and implement a better version in the next release, similar to the way we have displayed scope information in Swagger 2.x.**
