### ISSUE TITLE
Grammatical error in whitepaper in documentation

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5055]
An error in the whitepaper titled: "Building an API Strategy Using an Enterprise API Marketplace"  By Mifan Careem. 
Link - https://wso2.com/whitepapers/building-an-api-strategy-using-an-enterprise-api-marketplace/#06
Location :  
1st paragraph under the heading:  "3. Beyond API Management - The API Marketplace" in the sentence - 
"As we mentioned above, a marketplace and its role in building an effective **an** API strategy involves business and human aspects as well in addition to the technology aspect (Figure 2)."

The extra "an" before "API strategy" needs to be removed.

**Comment by fazlan-nazeem** [comment]
@arshita-kakkar thanks for reporting the mistake. We will get this corrected soon.

**Comment by fazlan-nazeem** [comment]
@arshita-kakkar This has been fixed and the article is updated. Thank you.
