### ISSUE TITLE
Publisher could not permitted to add certificates when endpoint host-name is like 'abcdef45'.

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#5065]
## Steps to reproduce:
* Login to the publisher and start to create an API.
* Create endpoint as like 'https://abcdef45/'.
* Then try to add the certificate by clicking on the 'Add new certificate'.
* It will return an error of 'You must first enter Production/ Sandbox endpoints to add a certificate or the Endpoints you have entered are not valid.'

## Reason:
* But the hostname is valid according to the original specification of hostnames in (RFC 952)[1] and the subsequent specification (RFC 1123)[2].

## References
[1] - https://tools.ietf.org/html/rfc952
[2] - https://tools.ietf.org/html/rfc1123

**Comment by dushaniw** [comment]
Need to check in 3.0 release after React UI revamp

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="660" alt="Screen Shot 2019-10-12 at 10 54 25 AM" src="https://user-images.githubusercontent.com/4861150/66695394-b54b0c00-ecde-11e9-842d-4847964c811c.png">
