### ISSUE TITLE
Label names are visible in 'Store-Overview' after deleting them from Admin portal

### ISSUE THREAD

**Issue by erandiganepola** [wso2/product-apim#5074]
**Description:**
After creating a label and assign it to a specific API, that label details are visible in Store-Overview. Next we delete that label and when we visits Store-Overview, that deleted label name is still visible in the UI.

APIM versions: 2.6.0, 2.5.0

Steps to reproduce:
1) Create a label named "Marketing" by going to the Admin portal
2) Deploy the sample ''PizzaShackAPI'' API
3) Add "Marketing" label to ''PizzaShackAPI'' in the ''Manage'' stage
4) Go to Store-Overview of that API and "Marketing" label's data is visible in the overview
5)  Go to Admin portal and delete "Marketing'' API
6) Go to Store-Overview of that relevant API and still the label name is visible (with no other data/access URLs).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
This issue is fixed in the latets version (3.2.0) as it does not allow to delete the label if it is attached to an API.
