### ISSUE TITLE
Bug in carbondump.sh in open JDK 8

### ISSUE THREAD

**Issue by nipun-sachintha** [wso2/product-apim#5075]
**Description:**

In JDK 8 permstat property is not available any more.
 'jmap -permstat $PID > $MEMORY_DUMP_DIR/java_permgen_statistics.txt` in carbondump.sh
**Suggested Labels:**
Apim
**Affected Product Version:**
2.1.0
**Steps to reproduce:**
When getting carbon dump in open JDK 8 version this issue is reproduced

**Comment by tharindu1st** [comment]
Removed in latest version
