### ISSUE TITLE
"Resource forbidden" message returned for key validation failure

### ISSUE THREAD

**Issue by lahirugmg** [wso2/product-apim#5076]
**Description:**
APIM 2.1.0 returns following message with 500 status code for key validation failure.

{"fault":{"code":900900,"message":"Unclassified Authentication Failure","description":"Resource forbidden"}}

Message is misleading and needs to be fixed

**Affected Product Version:**
APIM 2.1.0

**Comment by oscarvesga** [comment]
Hello, I am get this error and the way I fix was make a restart of the apimanager, but I don't know what is the cause. Can you clarify the causes of this error? 

Thank you

**Comment by lahirus** [comment]
@oscarvesga , What is the version you are using?

This message can be returned for multiple possible causes. Check the APIM logs to see if there are any other information about the reason of the failure.
{"fault":{"code":900900,"message":"Unclassified Authentication Failure","description":"Resource forbidden"}}

**Comment by oscarvesga** [comment]
My apim is version 2.2.0 and use an identity 5.5.0 like keymanager. In the wso2carbon.log file of apim I get a message error that said `Hazelcast instance is not active`

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
