### ISSUE TITLE
[Doc] Inconsistencies in Configuring Geolocation Based Statistics doc

### ISSUE THREAD

**Issue by isharailanga** [wso2/product-apim#5077]
**Description:**
The [doc](https://docs.wso2.com/display/AM260/Configuring+Geolocation+Based+Statistics) contains below issues:

- should mention the database should be created before configuring
- the attached zip file contains 
   - a space character in the name, which should be removed
   - several .DS_Store files

**Suggested Labels:**
Type/docs

**Comment by chamilaadhi** [comment]
invalid content for 4.3.0. Hence closing
