### ISSUE TITLE
[UI][React] propType warning due to using deprecated API

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5078]
Getting following warning message for using deprecated propType API in [here](https://github.com/wso2/carbon-apimgt/blob/C5-reactjs-development/components/web/apps/org.wso2.carbon.apimgt.publisher_originaluufapp/src/main/pages/src/app/components/Apis/Create/FormComponents/Select.js#L39-L45) (and several other places)

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

As stated in [documentation](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) we would need to use the `prop-types` library instead.

**Comment by tgtshanika** [comment]
Fixed in APIM 3.0.0 Alpha
