### ISSUE TITLE
Change lifecycleChecklist - query parameters into short form

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5090]
When changing the life cycle status of API using publisher REST APIs [1], lifecycleChecklist can be specified in order to achieve following:

1. **Deprecate old versions after publish the API**: Setting this to true will deprecate older versions of a particular API when it is promoted to Published state from Created state.
2. **Requires re-subscription when publish the API**: If you set this to true, users need to re subscribe to the API although they may have subscribed to an older version.

We need to make this parameters in short form, as the user need to specify a long sentence as query parameter.

[1] https://docs.wso2.com/display/AM260/apidocs/publisher/index.html#!/operations#APIIndividual#apisChangeLifecyclePost

**Comment by chamilaadhi** [comment]
If fixed, we need to handle the migration scenario as well
