### ISSUE TITLE
Improve log4j.properties in an operations friendly manner

### ISSUE THREAD

**Issue by thilinaba** [wso2/product-apim#5093]
Hi,

Please ensure following changes done in default "log4j.properties" file. These will make sure the production deployments are more stable in terms of underlying storage utilization. 

1. "log4j.appender.ERROR_LOGFILE" is a "DailyRollingFileAppender" in default log4j.properties file

2.  Make the rotated log files are zipped (gzip) in default log4j.properties file

**Comment by Krishanx92** [comment]
This is already supported in log4j2 hence resolve.
