### ISSUE TITLE
Remove grammatical error from first line

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5107]
Error in the first paragraph of whitepaper in API Documentation. 
Whitepaper title: **A Pragmatic Approach to Rock Your API Strategy**
present at : https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
under heading "1. API First Concepts":
"A very easy analogy might be: .... Most people have no clue about how a car works under the hood, but **knows** that...
**knows** should be changed to **know** as people is a plural word.

**Comment by arshita-kakkar** [comment]
@tharikaGitHub Can you please update on this issue?

**Comment by tharikaGitHub** [comment]
@arshita-kakkar Thank you for pointing this out. We will correct it and let you know.

**Comment by tharikaGitHub** [comment]
This is fixed now
