### ISSUE TITLE
Spelling mistake in doc

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5109]
Hi team,
There's a spelling mistake in a whitepaper.
Whitepaper title: A Pragmatic Approach to Rock Your API Strategy
present at : https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
under heading "1. API First Concepts":
API strategy or the API economy **emcompasses** several aspects; these include adopting the right strategy to expose such internal capabilities in the organizations...."
**emcompasses** should be changed to **encompasses** which is the correct spelling.

**Comment by arshita-kakkar** [comment]
@tharikaGitHub Can you please update on this issue?

**Comment by arshita-kakkar** [comment]
@pubudu538 Hi, pleaes update on this too.

**Comment by tharikaGitHub** [comment]
@arshita-kakkar Thank you for pointing this out. We will correct it and let you know.

**Comment by tharikaGitHub** [comment]
This is fixed now
