### ISSUE TITLE
[API Store] [UI] Regenerate button is disabled after generating a token and show keys button is clicked

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#5111]
Regenerate button to regenerate a token is disabled when the show keys button is clicked after generating a token for an application. The Regenerate button is re enabled only when the page reloads.

Steps to reproduce
1.     Create a new application in store
2.     Generate tokens by clicking "Generate keys" button in the "Production Keys" tab
3.     Now we can observe that the "Regenerate" button is enabled
4.     Now click "Hide Keys" button
5.     Then the "Regenerate" button is automatically disabled
6.     The will not be re-enabled even if we click "Show Keys" button
7.     The issue is fixed only when we refresh the web page

**Comment by AmaliMatharaarachchi** [comment]
Fixed in https://github.com/wso2-support/carbon-apimgt/pull/1532
