### ISSUE TITLE
Incorrect word usage

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5112]
**Criterias** is being used at several places in the whitepaper "A Pragmatic Approach to Rock Your API Strategy". Criterias is no word. In "Figure 2" as well. 
Correct word is Criteria which is the plural of Criterion. Please update **criterias** to **criteria**.
Link to the doc: https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/

**Comment by arshita-kakkar** [comment]
@tharikaGitHub Can you please update on this issue

**Comment by tharikaGitHub** [comment]
@arshita-kakkar Thank you for pointing this out. We will correct it and let you know.

**Comment by tharikaGitHub** [comment]
This is fixed now
