### ISSUE TITLE
[APIM 2.6.0] Need to set additional multi-tenant message context properties read from multitenant-msg-context.properties file

### ISSUE THREAD

**Issue by chamindias** [wso2/product-apim#5116]
Need the fix for APIM 2.6 for the issue https://github.com/wso2/product-apim/issues/3705

**Comment by chamindias** [comment]
To read the properties such as "JMS_WAIT_REPLY", we need this fix.

**Comment by dushaniw** [comment]
Will keep track of the issue via https://github.com/wso2/product-apim/issues/3705
