### ISSUE TITLE
[Doc] Missing instruction on configuring Session Persistence in Key Manager

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#5145]
Affected: All versions

Need to add doc references pointing the Identity Server Authentication Session Persistence [1] documentation in the API-Manager docs.

One important instruction we could highlight is that in only one APIM-KM node needs to have the session data cleanup task enabled.

We could add this to the APIM-HA Deployment doc. [2]

[1] https://docs.wso2.com/display/IS5XX/Authentication+Session+Persistence
[2] https://docs.wso2.com/display/AM260/Configuring+an+Active-Active+Deployment

**Comment by chamilaadhi** [comment]
Content is not valid for the latest APIM versions (4.2.0)
