### ISSUE TITLE
fixing url encode issue in password reset flow when protocol is http

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#5167]
**Description:**
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot find function forHtmlAttribute in object [object Object]. (/store/site/themes/wso2/templates/ui/dialogs/template.jag#35)
when try to reset password using http protocol
http://localhost:9763/store/site/pages/reset.jag?confirmation=3ffd1af4-75ce-4820-a910-8ef1ed605aaa&userstoredomain=PRIMARY&id=selaka&tenantdomain=carbon.super

**Steps to reproduce:**
- Enable PasswordRecovery
- Got the email for changing the password (https://localhost:9443/store/site/pages/reset.jag?confirmation=3ffd1af4-75ce-4820-a910-8ef1ed605aaa&userstoredomain=PRIMARY&id=selaka&tenantdomain=carbon.super)
- Try the received URL using HTTP protocol (instead of https)
http://localhost:9763/store/site/pages/reset.jag?confirmation=3ffd1af4-75ce-4820-a910-8ef1ed605aaa&userstoredomain=PRIMARY&id=selaka&tenantdomain=carbon.super
But instead of the password changing window, we could observe 
Error 500 : The page cannot be displayed.

**Affected version:**
APIM 2.6.0

**Comment by isharac** [comment]
since 3.x we are using react based apps and it is not recommended to use HTTP anymore.
