### ISSUE TITLE
Incorrect documentation of RESTful API search/retrieve 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#5168]
**Description:**
1. In docs, it says;
Eg. "provider:wso2" will match an API if the provider of the API is exactly "wso2". [1] 
However, provider:wso2 does a wildcard search, whereas provider:"wso2" return an exact match. 
2. The documentation doesn't mention the attribute modifier "name:" even though it can be used to search API's by name.
3. The documentation does not mention combined modifiers in the documentation.
E.g. name:pizzashack version:v1

**Suggested Labels:**
APIM-docs improvement

**Affected Product Version:**
2.6.0

[1] https://docs.wso2.com/display/AM260/apidocs/publisher/index.html#!/operations#APICollection#apisGet

**Comment by npamudika** [comment]
Doc has been updated with the requested changes.
