### ISSUE TITLE
setting window.location in the render() method cause two consecutive requests 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5180]
In the React web apps, If we set `window.location` and do redirection inside a render() method, the initial request will be canceled by the browser (This is happening in chrome browser in both OSX and Ubuntu environments). And it will initiate another request to the same address.
This two consecutive request will case jaggery level panic and will give unexpected exceptions and errors.

**Comment by tgtshanika** [comment]
fixed
