### ISSUE TITLE
Not able to access subscribe API of quantumleap with WSO2 API Manager

### ISSUE THREAD

**Issue by SwatiNEC** [wso2/product-apim#5185]
Hi

I am accessing QuantumLeap APIs via WSO2 APIM using mediator and policy files. The GET entities API executes successfully. But I am facing an issue while executing the subscribe API of QuantumLeap via WSO2 API Manager, i.e., Quantumleap becomes unresponsive for subscribe API, and in this unresponsive duration we are not able to access any other API of QL directly.
But after some time the timeout error occurs for Subscribe API on WSO2 APIM and then we are able to access any API of QL directly.

Versions:
WSO2 APIM - 2.6.0
WSO2 IS - 5.7.0
QuantumLeap - 0.5.0

Note: I have checked the logs of WSO2 APIM and confirmed that WSO2 APIM sends request to QuantumLeap for “subscribe API”, but QuantumLeap becomes unresponsive to the request and there are no error logs at QuantumLeap side as well as WSO2 APIM side.
Could anyone help in finding the root cause of this issue.

**Comment by SwatiNEC** [comment]
I have also raised an issue on QL for the same [#222](https://github.com/smartsdk/ngsi-timeseries-api/issues/222)

**Comment by chamilaadhi** [comment]
Closing since no active participation in the thread
