### ISSUE TITLE
OpenID SLO doesn't work

### ISSUE THREAD

**Issue by ort0lan** [wso2/product-apim#5191]
**Description:**
I configured SSO in Publisher and Store according to the [1]. Login works as it should. Logout doesn't work from second application.

**Steps to reproduce:**
- open first tab in browser and login to Store with SSO
- open second tab in browser and login to Publisher with SSO
- logout from Store
- Store is logged out
- go to the Publisher in second tab and refresh page
- Publisher is still login and can take actions
- logout from Publisher
- error appears: 

> Invalid Request 
> access_denied
> opbs cookie not received. Missing session state. 

**Affected version:**
APIM 2.6.0
IS 5.8, IS 5.7

[1] https://docs.wso2.com/display/AM260/Configuring+Single+Sign-on+with+OpenID+Connect

**Comment by Arshardh** [comment]
Not reproduced in APIM 3.x (uses openid SSO by default)

**Comment by malinthaprasan** [comment]
This is already fixed after 3.0.0 as default portal login/logout works as OIDC
