### ISSUE TITLE
Remove packing unnecessary files in store/conf/site/locales/ to product distribution

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#5193]
**description**
There are several files inside the <PRODUCT_HOME>/repository/deployment/server/jaggeryapps/store/site/conf/locales which were packed to the distribution when building the product.

extract_locale.sh, dynamic.po, jaggery.pot, master.pot, javascript.pot

(Note that they can be downloaded without any authentication. e.g. https://localhost:9443/store/site/conf/locales/extract_locale.sh)

**version**
2.1.0
2.6.0

**Comment by isharac** [comment]
This is fixed as we are using react based applications in 3.x
