### ISSUE TITLE
Mistake in the Product-Brochure 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5214]
Under the heading "WSo2 API Manager Benefits", sentence -
"Full lifecycle API Management capabilities reduces the need for future investment" should be corrected to "Full lifecycle API Management capabilities reduce the need for future investment" as capabilities is plural.
Link - https://b.content.wso2.com/sites/all/pdfs/product-brochures/product-brochure-APIM-v1.pdf

**Comment by pubudu538** [comment]
Hi Arshita,

Thank you for pointing out. We will correct this. 

Thank you!
Pubudu.

**Comment by pubudu538** [comment]
This is fixed.
