### ISSUE TITLE
Tenant information is not set if clone mediator is used.

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-apim#5217]
When logged in using a tenant, the tenant information is not printed in front of the log event inside the clone mediator. Log mediators outside of the clone mediator works fine. It seems the reason here is tenant information is not set inside the clone mediator. This is evident from the TID in the wso2carbon.log(inside clone mediator its -1). 

**Steps to Reproduce**

- Create an API
- In the in sequence add a clone mediator 
- Inside clone mediator target add a log mediator
- Add some log mediators after clone mediator too.
- Send a request to the API.
- In the wso2carbon.log you can see tenant information is not printed in logs inside clone mediator while tenant information is printed in the logs outside the clone mediator.

**Comment by kavishkafernando** [comment]
public commit: #https://github.com/wso2/wso2-synapse/commit/ecfe8d24a361ab26367f0febecdb5758fa03b1af,
