### ISSUE TITLE
Add visual feedback to resource delete button.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#5234]
The current resource delete button does not show any visual feedback for mouse hover, click events. Also the delete action does not seems noticeable.

**Comment by chamilaadhi** [comment]
This behavior is changed in AM 3.0.0 beta. now there is an option to undo this.  saving it to the api is done at the end. (not during the resource removing time)

<img width="1223" alt="Screen Shot 2019-10-12 at 8 24 08 AM" src="https://user-images.githubusercontent.com/4861150/66693728-dbb27c80-ecc9-11e9-8856-2ceb1ca3208e.png">
