### ISSUE TITLE
Email field in API Store SignUp form restricts top level domain length of an email

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#5245]
When filling the sign up for of the API Store, the email field restricts the maximum length of the top level domain(TLD) section to 4 characters. 

For example, the following emails with TLDs which are 4 characters or less are allowed, 

john@born.**edu**
john@born.**com**
john@born.**work**

But a TLD exceeding 4 characters, as below, is not allowed

john@born.**world**

This is reproducible in APIM 2.6.0

**Comment by uvindra** [comment]
![image](https://user-images.githubusercontent.com/6614042/98811406-d1236300-2446-11eb-83bc-097ed93b2f52.png)

**Comment by isharac** [comment]
this issue is not reproduced in 3.2.0 as this UI validation is not available.

Created an improvement[1] to track this.

[1] https://github.com/wso2/product-apim/issues/9516
