### ISSUE TITLE
APIM should provide the capability to change the subscription tier

### ISSUE THREAD

**Issue by chamindias** [wso2/product-apim#5246]
The product should support to upgrade/downgrade subscription tiers on demand (for a given app which already has a subscription for a given API)

**Comment by chamindias** [comment]
Also, we need to evaluate the use-cases w.r.t. monetization extension point [1] when supporting this.

[1] https://github.com/wso2-extensions/wso2-am-stripe-plugin

**Comment by tgtshanika** [comment]
We will address this feature request in the future release
