### ISSUE TITLE
React UIs beyond APIM 3.0.0

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5255]
Following are the suggestions for improvements in SPA

- Integrate Redux like React state management system, If not we could survive with Hooks , Context etc APIs
- Migrate to `TS` incrementally for better maintainability and support
- Strong accessibility support
- Improve both unit and integration test coverage
- Move away from Jaggery JS for serving the React Applications
  - Check best other alternatives for serving the SPA apps
- Make common components used in Store, Publisher apps sharable. For example login, logout, search etc.
![imp](https://github.com/tmkasun/images/blob/master/Oct-24-2019%2020-05-30.gif?raw=true)
Since the above changes require drastic changes to the SPA apps architecture, We will stack these improvements to be done in later versions.

**Comment by tmkasun** [comment]
- https://github.com/wso2/product-apim/issues/5295

**Comment by tmkasun** [comment]
Re: Integration tests

Automation tools
- [playwright](https://playwright.dev/)

Test frameworks

- testcafe
- cypress

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
