### ISSUE TITLE
Incorrect Documentation - APIM Product Brochure

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5258]
Under the heading- "WSO2 API Manager Benefits" in APIM Product Brochure, please correct the last point : 
API usage, analytics and insights **enables** you to make data-driven decisions.
to
API usage, analytics and insights **enable** you to make data-driven decisions 
as API usage, analytics and insights are plural. 
Link - https://b.content.wso2.com/sites/all/pdfs/product-brochures/product-brochure-APIM-v1.pdf

**Comment by arshita-kakkar** [comment]
@shaniR Can you please update on this too?

**Comment by MithraVishva** [comment]
The brochure has been updated.
