### ISSUE TITLE
Add react hooks eslint plugin

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5263]
As recommended in React [documentation](https://reactjs.org/docs/hooks-overview.html), Add the https://www.npmjs.com/package/eslint-plugin-react-hooks plugin to eslint rule set

**Comment by tmkasun** [comment]
Correct documentation [link](https://reactjs.org/docs/hooks-rules.html#eslint-plugin)

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
