### ISSUE TITLE
Support Json schema validation in swagger 2 and OpenAPI

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#5265]
Both request and response message should be validated against the defined schema in the swagger file.

**Comment by hasuniea** [comment]
Documentation:
https://docs.google.com/document/d/14AYpwVtRMpe2-KbFILRqRzFA-_Gt7nlHZCCCPzs0jw0/edit?usp=sharing

**Comment by hasuniea** [comment]
https://github.com/wso2/carbon-apimgt/pull/6776

**Comment by nirmal070125** [comment]
ref: 001E000000vajA0
