### ISSUE TITLE
ID Token should be validated

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#5266]
If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to validate the issuer in place of checking the token signature. The Client MUST validate the signature of all other ID Tokens according to JWS [JWS] using the algorithm specified in the JWT alg Header Parameter. The Client MUST use the keys provided by the Issuer.

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
