### ISSUE TITLE
Analytics server not found" when using log analyzer

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-apim#5270]
Refer https://wso2.org/jira/browse/WUM-13

Dear WSO2 team,

What do i miss when i'm trying to use Log Analyzer then open log analyzer at Api Manager : admin, and there is show an exception Analytics Server Not Found, even thoughi already install Api Manager Analytics.
need help please from WSO2 team.

thanks

**Comment by tgtshanika** [comment]
This feature has been deprecated from APIM 2.2.0 onwards and won't be available in APIM 3.0.0
