### ISSUE TITLE
Add CORS support to Publisher, Store v1.0 REST APIs

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5274]
**Description:**

This is mandatory when someone creates a custom Store/Publisher app and hosted in a different domain than REST APIs and wants to communicate with REST APIs.

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/product-apim/pull/6284, https://github.com/wso2/carbon-apimgt/pull/7348
