### ISSUE TITLE
Migrate to material UI 4

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5284]
Need to do the migration as suggested in following documentations

- For tests use [this](https://v3.material-ui.com/guides/testing/#testing)
- For components use [this](https://material-ui.com/guides/migration-v3/)
- For comparison with V3 here is the [V3 documentation](https://v3.material-ui.com/)

**Comment by tgtshanika** [comment]
This is fixed

**Comment by dushansilva** [comment]
Fixed for store from https://github.com/wso2/carbon-apimgt/pull/7147

**Comment by dushansilva** [comment]
related issue https://github.com/wso2/product-apim/issues/5694
