### ISSUE TITLE
SAML and Password Grant Types produce invalid Refresh Token

### ISSUE THREAD

**Issue by harshab95** [wso2/product-apim#5287]
While using SAML Extension Grant, and refresh token grant, the refresh token provided by the SAML Extension Grant type, after using the refresh token is an old refresh token that was already used.

WSO2 returns returns an error saying that the refresh token is not valid among the persisted tokens.

This issue was seen on API Manager 2.6.0.

**Comment by vithu30** [comment]
Hi @harshab95,

We have tested the SAML Extension Grant and did not encountered any issues when renewing the token using refresh token. We understood that you are trying to refresh the token using the old refresh token.

When requesting token using Refresh token Grant, you will get a new accesstoken as well as refresh token. An example response for this call could be:
```
{"access_token":"d6f6f269-622d-3e8f-9574-360b30da6981","refresh_token":"ba2b6d8d-55c7-3149-a0e3-0b9566f9dfbf","scope":"default","token_type":"Bearer","expires_in":3600}
```
You will have to use the returned token to refresh token thereafter, as the previous refresh token will not be valid. 

If your use-case is different than this, could you provide the exact steps to reproduce the same behavior?

**Comment by harshab95** [comment]
Hi @vithu30, 
I had used the new refresh token knowing that the old one will expire. However, There must have been some configuration error. I'll try to reproduce the problem and mention it as soon as I can so that you guys know. I didn't see that behaviour again recently.
My use case is that my application is a wrapper API on top of WSO2 token endpoint. Since after SSO my application doesn't have the user's credentials, and I cannot use a regular password grant type to fetch tokens on their behalf, so I used saml extension grant and I had initially faced this problem on about 3 different instances of WSO2. So I was revoking refresh tokens to recieve a new working refresh token.
Also, if there is a faster way to provide a SAML Assertion than the Jar file provided to create it, please let me know. I have made a Python Application that makes the SAML Assertion for me instantly but I'm having errors in signing it with the correct signature.
Although, Thank you very much for the help.

**Comment by isharac** [comment]
Closing the issue as it is not reproduced. Please reopen if it occurs again
