### ISSUE TITLE
AM2.6, OpenAPI 3.0 : RequestBody API not show in Store after Publishing

### ISSUE THREAD

**Issue by ciske-1** [wso2/product-apim#5288]
Which API Manager 2.6.0

When I define the basic API as :
openapi: 3.0.0
paths:
  /post:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: string
        required: true
      responses:
        "200":
          description: ""
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
info:
  title: ATest
  version: v0
  description: Test OPenAPI 3.0

When I deploy the API as a Prototype, I can access the requestBody of this API in  the store.
When I publish the API, the requestBody block is not show in the store

**Comment by erikskruze** [comment]
Faced the same problem. 
OpenAPI 3.0 on WSO2 APIM 2.6 does not show request body. 
Older versions (tried 2.1 and 2.5) show request body ok. 

For example petstore post sample from github:
[https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml](url)

Are there any progress on this bug?
