### ISSUE TITLE
[APIM 2.6]Include download link to APIM CLI tool in the documentation 

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#5290]
When referring the documentation https://docs.wso2.com/display/AM260/Building+a+CICD+Pipeline+for+APIs, it does not point users to any download link of the APIM CLI tool. This makes users confuse when following the guide.
Hence could we include the download link at the above documentation?

**Comment by ruthryi** [comment]
The download and deployment steps are given as part of the instructions in [1] and [2]. This page is simply a home page for all the content. Please comment if you feel otherwise.
