### ISSUE TITLE
[2.6.0][CI/CD] Missing link in CI/CD documentation

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#5291]
While I was referring document https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool#9f0a840a47fa4bddb5d41a6756c6675e on initializing project using cli tool. Under step 3, it describes the files in the project directory.
![image](https://user-images.githubusercontent.com/8377610/62846979-5e7e8180-bcf1-11e9-9bf7-4baf1ea1c18e.png)
It is missing a link to regarding editing env specific details.
Thanks,
DinushaD

**Comment by ruthryi** [comment]
Added the correct link in [1]

[1] https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool#InitializingprojectsusingtheCLITool-CreateanewAPIproject
