### ISSUE TITLE
Keep one of "subscriber" or "owner" in ApplicationDTO

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5298]
Let's keep one of "subscriber" or "owner" in ApplicationDTO. If "subscriber" is always the logged-in user, I don't think it makes sense to keep it. Let's remove it and keep only the "owner" field.

_Originally posted by @malinthaprasan in https://github.com/wso2/carbon-apimgt/pull/6800#issuecomment-520729150_

**Comment by tgtshanika** [comment]
Fixed in APIM 3.0.0 Alpha
