### ISSUE TITLE
Support API publish for Multiple environments

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#5300]
API needs to publish to multiple environments using API publisher.

**Comment by falconmfm** [comment]
There are few ways to publish to different environments, by default you have a production/sandbox gateway. You can add more gateways and publish your API to it, so you can deploy a gateway for production and another different for sandbox ( https://docs.wso2.com/display/AM210/Publish+through+Multiple+API+Gateways ).

Another approach is to manage the api creation out of API Publisher and deploy it with apimcli tool ( https://wso2.com/library/articles/2019/07/building-a-cicd-pipeline-for-apis/?utm_source=linkedin&utm_medium=organicpost&utm_campaign=liorgarti_aug19_api ) .

Also, if you are looking to publish the API to different stores for different consumers you should read ( https://docs.wso2.com/display/AM210/Publish+to+Multiple+External+API+Stores ).


 If your are looking to publish the api to different stores

**Comment by Krishanx92** [comment]
Thanks @falconmfm 
Previous API Manager versions had this support through API manager Publisher. We could select multiple gateway environments and published through Publisher.
![gateways](https://user-images.githubusercontent.com/8374895/63929395-ddd5ba00-ca40-11e9-8466-3e0803c18651.png)

But upcoming API manager version 3.0.0 does not have this support yet. Needs to add to API Manager 3.0.0 as well.
