### ISSUE TITLE
Alert messages css effect to whole page styling when pops up

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5302]
When an alert message appears in the UI, Its styling makes an effect on the styling of the whole page. i:e when an alert popup, the font size in the whole page increase.

**Comment by tmkasun** [comment]
This is fixed in publisher and needs to be fixed in the Store with the MUI 4.x upgrade. @dushansilva can you please update the issue if you are working on this?

**Comment by tgtshanika** [comment]
Fixed
