### ISSUE TITLE
Redesign Publisher API overview/configure pages

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5303]
This is about redesigning or rather arranging the API Manager publisher API overview and API configuration pages.
Currently, we have a very flat UI design. Where it's hard to map the information in the page with usage or runtime of the API.
The purpose behind this effort is to, give the users a clear idea about where each configuration/information is fit-in in the API runtime/design flow. 

Following is the initial design for structuring the information/configuration elements in API details overview and configurations pages.

![API flow](https://user-images.githubusercontent.com/3313885/63107954-80069400-bfa3-11e9-924b-885582368104.png)

[Google drawing](https://docs.google.com/drawings/d/1PNrRJ9pXslLSJ7hD_9Vk2S_8_HjtRzH4dUQoUTbCE50/edit)

**Comment by tmkasun** [comment]
AWS API Gateway UI : [Video](https://youtu.be/j55NVv5Nd5g)
Microsoft Azure APIM UI: [Video](https://youtu.be/hJJj4CI1lp4)

**Comment by erangatl** [comment]
Fixed https://github.com/wso2/carbon-apimgt/pull/7450
