### ISSUE TITLE
Cannot create scopes for  API  [apim 3.0.0] 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5311]
It fails to create scopes for an API in publisher

**Comment by chanaka3d** [comment]
![Screen Shot 2019-08-21 at 3 43 39 PM](https://user-images.githubusercontent.com/3424539/63423801-b07a8200-c42a-11e9-8673-eaa91c782f8f.png)

1. Role should be validated
2. UI is non responsive
3. Add tag is displayed in the role text box
