### ISSUE TITLE
Cannot add or delete a resource in publisher 

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#5314]
Following in error is printed when we try to add a new resource or delete resources in publisher
`ERROR - ApisApiServiceImpl Error while parsing OpenAPI definition`

1. Got to api publisher
2. create an api
3. go to resources page and add a new resource.
4. click save

Error can be seen in carbon console

**Comment by ruks** [comment]
This is may due to the OAS parser mismatched. Will be support when the OAS2 and 3 fixes are done
