### ISSUE TITLE
API Thumb properties missing

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#5315]
API Thumb 
1 - lifecycle state missing
2 - API type missing

![Screen Shot 2019-08-21 at 3 17 44 PM](https://user-images.githubusercontent.com/3424539/63421848-eae22000-c426-11e9-8e7e-40faa122de04.png)

**Comment by TanyaM** [comment]
Lifecycle state missing issue is fixed with https://github.com/wso2/carbon-apimgt/pull/6838
