### ISSUE TITLE
Monetization support

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#5326]
1 - Publisher - Monetization is not getting rendered ( Loading animation continues.. )
2 - Subscribe to API needs improvements to list the additional information for the paid tiers.

![Screen Shot 2019-08-21 at 5 02 12 PM](https://user-images.githubusercontent.com/3424539/63428570-7662ad80-c435-11e9-987f-cdae9f32716c.png)

**Comment by chamindias** [comment]
(1) Is fixed : 
![image](https://user-images.githubusercontent.com/8359365/66647683-35be2e00-ec47-11e9-980a-305e2dc427a0.png)

(2) Is fixed : https://github.com/wso2/carbon-apimgt/pull/7051
![image](https://user-images.githubusercontent.com/8359365/66647765-6b631700-ec47-11e9-8b05-fc84b6faf4af.png)

(Checked in the latest pack - 2019/10/11)
