### ISSUE TITLE
Home page dummy content should have a meaning

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#5327]
![Screen Shot 2019-08-21 at 5 23 01 PM](https://user-images.githubusercontent.com/3424539/63429723-757f4b00-c438-11e9-9236-27bf172b4c88.png)

**Comment by tgtshanika** [comment]
The home page enable/disable config should be introduced and it should be disabled by default

**Comment by chanaka3d** [comment]
By default we have disabled the home page now.
