### ISSUE TITLE
Doesn't loggout correctly - Store/Publisher both

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5331]
When logout, the page keeps stucked in below view.

<img width="1680" alt="Screen Shot 2019-08-21 at 5 37 13 PM" src="https://user-images.githubusercontent.com/2484781/63430785-13741500-c43b-11e9-8823-4d6e45121226.png">

Reason: Browser local storage is not cleared correctly.

As an effect if logged into another user in same browser, we see the same old username as logged in user.

**Comment by tgtshanika** [comment]
Fixed in APIM 3.0.0 m35
