### ISSUE TITLE
Throttling policies edit page is missing from new UI

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#5333]
<img width="740" alt="Screen Shot 2019-08-21 at 5 44 01 PM" src="https://user-images.githubusercontent.com/3424539/63430940-65b53600-c43b-11e9-9f6f-56e1ddd7a62e.png">

Overview page throttling policies link is going to documents page. This need to redirect to the subscriptions page and the functionality to edit policies need to be implemented.

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7391
