### ISSUE TITLE
Issue with secure vault lookup in mediation flow

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#5338]
**Description**
When we follow the documentation[1], it manually encrypts the text plain password using the cipher-tool.
By default, the cipher-tool uses an encryption algorithm like RSA.
But in the mediation flow, we try to decrypt the password using the algorithm mentioned in the carbon.properties file.
This flow can break due to the mismatch of the decryption algorithm and the encryption algorithm.
Due to that, the property in the mediation can be returned as null.

**Steps to reproduce**
1. Follow [1] to encrypting passwords for mediation flow
2. Log in to the management console.
3. Select Browse under Resources to access the registry browser and go to the /_system/config/repository/components/secure-vault location.
3. Add a new property with name and the encrypted value as a property.
4. Add a log mediator to log the above value using wso2:vault-lookup

**Version**
2.6.0

[1] https://docs.wso2.com/display/AM260/Working+with+Encrypted+Passwords#WorkingwithEncryptedPasswords-Encryptingpasswordsformediationflow

**Comment by seethalakshmi26** [comment]
Hi ALL ,
im also facing this issue , is there a solution for this.

regards,
Seetha
