### ISSUE TITLE
Tooltips doesn't work in publisher Overview page

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5339]
Tooltips on Overview page, on the Configuration section do not pop out consistently. They don't pops out when you move the cursor on it.  But in chrome in Mac, it pops up if you switch active window and switch back to browser window.

<img width="932" alt="Screen Shot 2019-08-22 at 11 49 47 AM" src="https://user-images.githubusercontent.com/2484781/63490855-5e416b80-c4d3-11e9-879f-a2d78c7feae3.png">

**Comment by tgtshanika** [comment]
This issue is not reproducible in APIM 3.0.0 Alpha
