### ISSUE TITLE
Configuration tab page - UI imporovement

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5340]
The configuration tab page seems mostly empty and feels as incomplete. The organizations. and structure of the contents can be changed to resolve this.
![Screen Shot 2019-08-22 at 1 52 12 PM](https://user-images.githubusercontent.com/2484781/63499025-a61cbe80-c4e4-11e9-8a35-b87a0a584f8b.png)

**Comment by erangatl** [comment]
Related issues
#5332 - Configurations page - UX
#5303 - Redesign Publisher API overview/configure pages

**Comment by rmsamitha** [comment]
Closing as similar issue reported as above
