### ISSUE TITLE
Cannot add/update/delete a API resource

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5343]
Once add a summary to an API resource, and then click "Save", nothing happens expect the below log on console. So the resource summary cannot be added. Deleting a resource, adding  a new resource too gets failed with below error.

[2019-08-22 15:00:19,098] ERROR - ApisApiServiceImpl Error while parsing OpenAPI definition,

**Comment by tgtshanika** [comment]
This is fixed in APIM 3.0.0 Alpha
