### ISSUE TITLE
The changed API state is not reflected on the top bar 

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5344]
When we change the API status, the changed status is not reflected into the top bar, where the status is displayed.

E.g. In below screenshot the API status is to demoted to created state, but still the previous "published" state is displayed.
![Screen Shot 2019-08-22 at 4 18 48 PM](https://user-images.githubusercontent.com/2484781/63509032-ca829600-c4f8-11e9-82f2-63b94bc8f034.png)

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6881
