### ISSUE TITLE
"No matching records found" page appears for a blink before loading the apis listing in store

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-apim#5352]
When URL https://localhost:9443/store-new/apis is accessed below page appears before the store listing page. Can be observed with slow network properly. Better to have a loading gif instead.

<img width="677" alt="screenshot_1" src="https://user-images.githubusercontent.com/3957104/63587849-a2f80000-c5c2-11e9-9b9d-bba4af7c74d7.png">

**Comment by tharikaGitHub** [comment]
Reopening due to https://github.com/wso2/product-apim/issues/5892
