### ISSUE TITLE
UI style Issue in Scopes table

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5362]
Steps:
1. Create an API and add scopes
2. Assign them to resources
3. Go to the overview page
4. Click edit button
5. It redirects to the scope page

<img width="1094" alt="Screen Shot 2019-08-25 at 5 36 41 PM" src="https://user-images.githubusercontent.com/29066805/63649730-f4d58d00-c75e-11e9-9e33-26349f639931.png">

<img width="1084" alt="Screen Shot 2019-08-26 at 2 45 14 PM" src="https://user-images.githubusercontent.com/29066805/63679981-3bcf8b00-c810-11e9-8a1e-578b14833d69.png">

6. Once refresh the scope page, that style issue is gone

**Comment by ruks** [comment]
This is not reproducible now. Hence closing.
