### ISSUE TITLE
Unable to do user self registration after updating the dependencies.

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#5384]
## Issue

css files aren't getting fetched correctly when loading the register.do jsp in accountrecoveryendpoint.war.

- Previous Dependencies in which this worked without issues.
<carbon.identity.version>5.13.41</carbon.identity.version>
<carbon.identity.governance.version>1.2.9</carbon.identity.governance.version>        <carbon.identity.event.handler.account.lock.version>1.2.1</carbon.identity.event.handler.account.lock.version>
- Latest Dependencies in which this error occured.
<carbon.identity.version>5.14.15</carbon.identity.version><carbon.identity.governance.version>1.3.5</carbon.identity.governance.version>   <carbon.identity.event.handler.account.lock.version>1.3.0</carbon.identity.event.handler.account.lock.version>

<img width="1678" alt="Screen Shot 2019-08-27 at 12 00 44 PM" src="https://user-images.githubusercontent.com/23296184/63747516-fb7e1480-c8c4-11e9-97d2-bad5b438710a.png">

**Comment by CrowleyRajapakse** [comment]
Tags: APIM 3.0, UI

**Comment by CrowleyRajapakse** [comment]
This issue has been addressed from https://github.com/wso2/product-is/issues/6346 and updating the identity dependencies to latest should fix the above issue.

**Comment by chamilaadhi** [comment]
signup can be done in AM 3.0.0 beta
