### ISSUE TITLE
Implement input validations to Publisher user inputs

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5391]
Needs to implement the user input validation as it was there in old jaggery UI

[This file](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/utils/custom-validation/custom-validation.js) contains most of the validation patterns/methods

[Here is the usage](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/template.jag#L149) of those custom validators as class names in input elements

We need to implement these validations in React input files (Material-UI TextFiels etc)

Implement those custom validation [in APIValidation.js](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/source/src/app/data/APIValidation.js)

**Comment by praminda** [comment]
Trailing slash (`/`) is not validated in publisher API context input
![image](https://user-images.githubusercontent.com/2655553/66670253-efed6f80-ec1e-11e9-8d72-d1c223778625.png)

**Comment by praminda** [comment]
`-` is allowed in the Publisher's API Name input field but UI validation message says spaces or special characters are allowed.

**Comment by tmkasun** [comment]
Closing this issue, since we have migrated the 2.6 JS migrations into 3.x and now it’s been evolved to 4.0 as well
