### ISSUE TITLE
Overview Doc error

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5416]
In sentence  - 
"If your setup requires to govern more than APIs, we recommend you to use WSO2 API manager for API governance and WSO2 Governance Registry for **the** other artifacts.";
'the' needs to be omitted as we are talking about other artifacts in general and mentioning any specific artifacts.
Link of Doc - https://docs.wso2.com/display/AM260/Overview

**Comment by shaniR** [comment]
Thank you for reporting. We have fixed this.
