### ISSUE TITLE
Release Doc mistake

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5417]
In doc - https://docs.wso2.com/display/AM260/About+this+Release

Update 
'WSO2 API Manager comprises of several modules.' to
'WSO2 API Manager comprises of several modules:'

Also, a full-stop should be added to last point 
'API Traffic Manager: Performs rate limiting of API requests' to maintain parallelism in all points.

**Comment by shaniR** [comment]
Thank you for reporting. This is fixed.
