### ISSUE TITLE
Doc  - https://docs.wso2.com/display/AM260/About+this+Release

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5418]
Under heading  - Gateway Manager profile,
sentence -
Therefore, the Gateway Manager profile (-Dprofile=gateway-manager) has now been deprecated as it is redundant.
should b updated to 
'Therefore, the Gateway Manager profile (-Dprofile=gateway-manager) has now been deprecated as it **was** redundant.'
as the task has already been done and the file 'was' redundant.

**Comment by shaniR** [comment]
The Publisher can now also be the Gateway Manager. The Gateway Manager profile is now deprecated. But it is redundant only from the 2.6.0 release (this release)  onwards. I believe the sentence is worded correctly. Please do re open if you think it should be otherwise.
