### ISSUE TITLE
Error in Guide

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5419]
In doc - https://docs.wso2.com/display/AM260/Quick+Start+Guide#QuickStartGuide-InvokingyourfirstAPI
Update  -
'This Deploy Sample API option is available only when there are no APIs in API Publisher. If you have already created a API, this option will not be available.'
TO
'This Deploy Sample API option is available only when there are no APIs in API Publisher. If you have already created **an** API, this option will not be available.'

**Comment by shaniR** [comment]
Thank you for reporting. We have fixed this.
