### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5420]
Document  - https://docs.wso2.com/display/AM260/Key+Concepts
Under Heading - "Access Tokens", 
'DoS attacks with the same fake **acess** token can affect the Gateway as well ).' 
needs to be updated to 
'DoS attacks with the same fake **access** token can affect the Gateway as well ). '

**Comment by shaniR** [comment]
Thank you reporting. We have fixed this.
