### ISSUE TITLE
Whitepaper Documentation error

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5421]
Whitepaper present at - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
has an error in line -
'Define a short and agile sprint/delivery based on **a** MVP and MVA'.

It should be updated to 
'Define a short and agile sprint/delivery based on **an** MVP and MVA'.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
