### ISSUE TITLE
Incorrect sentence in Whitepaper

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5423]
In doc - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
The sentence - 
'The Hostelera team decided that they will start **their business developing their website** in order to attract end customers; they start with some questions as follows:'
has excess 'their' making it ambiguous.
Update it to - 
The Hostelera team decided that they will start **business developing their website** in order to attract end customers; they start with some questions as follows:

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
