### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5424]
In doc - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
The sentence -
'As a result, many agencies can book our offers **into** our desktop system and we take care of the logistics.'
Update it to -
As a result, many agencies can book our offers **at** our desktop system and we take care of the logistics.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
