### ISSUE TITLE
Whitepaper 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5434]
In Doc - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/ 
in sentence -
"You had solved the initial issues and/or opportunities to execute your first APIs, and now you can **proof** that your initiative is able to attract investments and get boosted."
to 
"You had solved the initial issues and/or opportunities to execute your first APIs, and now you can **prove** that your initiative is able to attract investments and get boosted."
as proof is a noun and unsuitable here.Prove, a verb should be used here.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
