### ISSUE TITLE
Whitepaper - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5435]
Correct framing on this sentence -
"Keep in mind that once the MVP is ready, never forget about the basics regarding agile methods because at any moment you evaluate your architecture and promote/expose services in the most convenient way for you."
would be - 
"Keep in mind that once the MVP is ready, never forget about the basics regarding agile methods because at any moment you **can** evaluate your architecture and promote/expose services in the most convenient way for you."
as we are giving the user a convenient method to evaluate.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
