### ISSUE TITLE
Whitepaper Documentation 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5436]
Documentation link - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/

The sentence is long and incorrectly framed. Added a line-break and changed 'happens' to 'happen' as things is plural.

To transform, it’s necessary to gain as much insights, information, and indicators as you can, evaluate them, and based on facts and definitely with a pinch of creativity and courage make things **happens**.

To transform, it’s necessary to gain as much insights, information, and indicators as you can and evaluate them. **Then, on the basis of facts** and definitely with a pinch of creativity and courage, make things **happen**.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
