### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5437]
Documentation link - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
The sentence-
How are you treating your analytics? **Does real-time analytics impacts** your business?
uses Does(plural) with impacts(plural).
Update it to - 
How are you treating your analytics? Does real-time analytics **impact** your business?

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
