### ISSUE TITLE
Whitepaper Doc - incorrect sentence

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5438]
Documentation link - https://wso2.com/whitepapers/a-pragmatic-approach-to-rock-your-api-strategy/
Line - 
It demonstrates the most pragmatic way with some insights, and by sharing real experiences from some of our consultants on the field, the ones that had looked at some eyes **that found happiness in had delivered a good value,** and others that are still looking to solve their issues.

The sentence is very long and incorrectly framed. Added a line-break and removed excessively used words like 'some' to convey the real meaning of sentence.
Updated - 
It demonstrates the most pragmatic way with some insights, and shares real life experiences from some of our consultants on the field. They had looked at eyes that found happiness when their issues were resolved with a good delivered product, and others that are still looking to solve their issues.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
