### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5439]
Documentation link - https://wso2.com/whitepapers/building-an-api-strategy-using-an-enterprise-api-marketplace/
Line -
We will look at the advantages of building an **enterprise API marketplace** and the steps for launching an effective **enterprise API marketplace**.

Updated it to be more meaningful and avoid using same words repeatedly -

**We will look at the advantages of building and the steps for launching an effective enterprise API marketplace.**

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
