### ISSUE TITLE
Error in whitepaper

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5441]
Doc at - https://wso2.com/whitepapers/building-an-api-strategy-using-an-enterprise-api-marketplace/
Please update the sentence - 
'The focus during these events **were** on building applications using APIs and to build newer APIs on top of the existing APIs as well. '
to
'The focus during these events **was** on building applications using APIs and to build newer APIs on top of the existing APIs as well. ' 
as focus is singular.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
