### ISSUE TITLE
Whitepaper 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5442]
Doc at -https://wso2.com/whitepapers/building-an-api-strategy-using-an-enterprise-api-marketplace/
Please update the point -
'Promote participation via incentives - Incentives always help nurture supply and demand and this no different in a virtual API marketplace. '
to
'Promote participation via incentives - Incentives always help nurture supply and demand and this **is** no different in a virtual API marketplace.'

**Comment by MithraVishva** [comment]
I have edited the text as suggested.

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
