### ISSUE TITLE
Wso2 whitepaper 

### ISSUE THREAD

**Issue by arshita-kakkar** [wso2/product-apim#5444]
Doc - https://wso2.com/whitepapers/building-an-api-strategy-using-an-enterprise-api-marketplace/

Update the sentence as "look" is inappropriate here.
"Complex transformation might require an integration platform; most customers **look to bring** their own ID systems (BYOID) - in which case the API Manager needs to allow consumers to authenticate against the existing system by federating to them. "

"Complex transformation might require an integration platform; most customers **seem** to bring their own ID systems (BYOID) - in which case the API Manager needs to allow consumers to authenticate against the existing system by federating to them. "

**Comment by MithraVishva** [comment]
I have edited the text as suggested.
