### ISSUE TITLE
Forgot Password Enabled is checked on Axis2 Configuration

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#5445]
Now this is being checked in the axis2.xml by checking whether SMTP transport sender is configured in the axis2.xml. But now with an IS upgrade email needs to be configured in the output-event-adapter.xml. Hence, even though we set the email configurations in axis2.xml this feature breaks.

We need to introduce a new configuration to check if the forgot password feature is enabled to make it independent from IS.

**Comment by isharac** [comment]
Since APIM 3.0.0 it uses output-event-adapter config
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#!
