### ISSUE TITLE
Issue/Bug with "Production and Sandbox URLs" when running WSo2 on Docker

### ISSUE THREAD

**Issue by prats2017** [wso2/product-apim#5447]
Hi, I am stuck with an issue from last couple of days.
My "Production and Sandbox URLs" has docker IP as service IP when my wso2 is running on docker.
When I do same steps on windows, "Production and Sandbox URLs" are correctly indicated.
Attaching, screenshots for easier understanding.

In nutshell, My SOAP service is available at running on http://192.168.xx.yy:8080/ws/countries and I correct IP in my endpoints when I am creating my API. However once API is published, Endpoints are pointing to 172.17.0.2 which is docker ip.
Please note, i see correct IP in endpoint when WSo2 is running on Windows.
Not sure if is a bug or missing configuration but look like WSo2 on Docker is an issue. 

[WSO2 issue.docx](https://github.com/wso2/product-apim/files/3560784/WSO2.issue.docx)

**Comment by a-titorenko** [comment]
Hi! 

I have the same issue. As I understand, in the Store we see URLs of gateway endpoints, not service implementation endpoints. And it seems correct to me. But API is actually docker container API. For some reason, using API Console is not woking with this IP/hostname as well as proposed curl script. When I change docker hostname to 'localhost' then curl script is working. But API console is not working, since I cannot change hostname there...

**Comment by vozzy** [comment]
You can customize the Gateway URLs that appear in the API Store/Developer portal by changing the following value in {carbon_home}/repository/conf/api-manager.xml

```xml
<APIGateway>
    <Environments>
        <Environment type="[environment-type]" api-console="true">  
            <!-- Endpoint URLs for the APIs hosted in this API gateway.-->
            <GatewayEndpoint>http://anyhost:7777,https://anyotherhost</GatewayEndpoint>
            <!-- Endpoint of the Websocket APIs hosted in this API Gateway -->
            <GatewayWSEndpoint>ws://[gateway-hostname]:[gateway-ws-port]</GatewayWSEndpoint>
        </Environment>
    </Environments>
</APIGateway>
```

The Store will simply display the URLs comma seperated in `//APIGateway/Environments/Environment/GatewayEndpoint`

Please see this [document](https://docs.wso2.com/display/AM260/Changing+the+Hostname) for a reference.

**Comment by prats2017** [comment]
Thanks for looking into this...
