### ISSUE TITLE
API Properties Page UX Improvement

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#5448]
The UI in API Additional Properties page  in Publisher needs to be improved.

![properties](https://user-images.githubusercontent.com/8557410/64089992-797b6900-cd66-11e9-97ee-958deedebccc.png)

The way the UI is seen on page load needs to be fixed to improve the UX aspect.

**Comment by chanaka3d** [comment]
The improvement done is by adding an animation when click the save button and disabling the button until the success or fail message comes.
