### ISSUE TITLE
Localization label breaks API Lifecycle view

### ISSUE THREAD

**Issue by apercova** [wso2/product-apim#5460]
I'm translating WSO2 API Publisher to spanish and I've found that API Lifecycle view gets broken when I translate following label  From `"Lifecycle": "Lifecycle",` To `"Lifecycle": "Ciclo de vida",`

Locale is found under: `$APIM_HOME/repository/deployment/server/jaggeryapps/publisher/site/conf/locales/jaggery/locale_default.json` at  `Line 292`

Before translating `Lifecycle` label:  
![before](https://user-images.githubusercontent.com/14076184/64200028-43ff7a00-ce51-11e9-9c95-55428ed66691.png)

After translating `Lifecycle` label:  
![after](https://user-images.githubusercontent.com/14076184/64200113-701afb00-ce51-11e9-83b7-53603e5a2723.png)

I've found several labels that can not be localized but by now It just had been up to a translation problem, but translating this label does affect the way API Publisher works.

Thanks in Advance.

**Comment by tharindu1st** [comment]
Invalid due to ui-ravamp
