### ISSUE TITLE
Track DB migrations for APIM-3.0.0

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#5464]
This issue has been created to track the migrations that are necessary for APIM-3.0.0

**Comment by kavishkafernando** [comment]
The datatype of the **COMMENT_ID** coloumn of **AM_API_COMMENTS** table in WSO2AM_DB has been changed from INTEGER AUTO_INCREMENT to **VARCHAR(255)**

**Comment by chamindias** [comment]
Add the changes in [1] to support monetization.

[1] https://github.com/wso2/carbon-apimgt/commit/bb6593b4d84862bc6be39fdf1a4530cde3d516e0

**Comment by vithu30** [comment]
Doc related improvements required in migration are reported in https://github.com/wso2/product-apim/issues/5182, https://github.com/wso2/product-apim/issues/5183

**Comment by dushaniw** [comment]
EXTERNAL_STORES related changes are reported in https://github.com/wso2/product-apim/issues/5505
