### ISSUE TITLE
Cannot create an api product

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#5478]
Cannot create an api product, process will create an api instead.

![image](https://user-images.githubusercontent.com/20179540/64329560-1b13ec00-cfed-11e9-8bb2-54e05714d8ac.png)

![image](https://user-images.githubusercontent.com/20179540/64329802-76de7500-cfed-11e9-8357-c5dee8f79382.png)

**Comment by HiranyaKavishani** [comment]
Fixed with https://github.com/wso2/product-apim/issues/5484
