### ISSUE TITLE
[Publisher] Created scopes are not listed properly

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5502]
In Publisher, there are inconsistencies when adding scopes to an API. Added scopes are not listed properly. If scopes are added to an API, with the onclick function of create, it redirects to following page:

![Redirect](https://user-images.githubusercontent.com/19728269/64584399-2894f180-d3b2-11e9-8cb9-80d6b0be70db.png)

It should not show the create scope page, it should be redirected to scope listing page. Once page is reloaded it is listing the scopes correctly:

![listing](https://user-images.githubusercontent.com/19728269/64584452-55490900-d3b2-11e9-9900-8ebea804eaba.png)

There is UX issue here, the row length should be equal to the length of table.

**Comment by ruks** [comment]
This is due to the scope listing page not update after a scope added(same as https://github.com/wso2/product-apim/issues/5659). This is not reproduced now.
