### ISSUE TITLE
UX issue in document listing page

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5508]
If there are no documents added to an API, page should render some message like as follows:

![document](https://user-images.githubusercontent.com/19728269/64609833-6bbf8680-d3eb-11e9-9d6e-996531277f5f.png)
Currently, documentation has following view:
![Currentvirew](https://user-images.githubusercontent.com/19728269/64609881-8d207280-d3eb-11e9-8c5c-56fa8178a99a.png)

Further added documents not listed properly:
![listing](https://user-images.githubusercontent.com/19728269/64610188-59921800-d3ec-11e9-8996-3bff2decdcb5.png)

**Comment by nalakas** [comment]
This is fixed in the latest version.
