### ISSUE TITLE
API Product create UI issues 

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5541]
![image](https://user-images.githubusercontent.com/3960742/64774176-51171a00-d571-11e9-8d34-cb121386f5f6.png)

1) The error message should be more user-friendly (without a regex preferably) 
2) "value" should be fixed
3) Checkbox color is hardly visible and does not match the rest of the UI.

**Comment by tmkasun** [comment]
> 3. Checkbox color is hardly visible and does not match the rest of the UI.

@HiranyaKavishani , Please note that out of above 3 issues, except 3rd issue , 1 & 2 are still exist
