### ISSUE TITLE
API Overview page issues

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5545]
![image](https://user-images.githubusercontent.com/3960742/64779312-5f6a3380-d57b-11e9-8fff-89b4479b0bd6.png)

1) Fonts/sizes/spaces are not consistent
2) "Not configured" sounds odd for description
3) Extra comma
4) ? does not look nice
5) 2) "Not configured" sounds odd for business information

**Comment by bhathiya** [comment]
@erangatl does the PR cover (1) too?
Looks like (3) seems not fixed yet.

**Comment by erangatl** [comment]
> @erangatl does the PR cover (1) too?
> Looks like (3) is not fixed yet.

1 is already fixed, will fix 3

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7278
