### ISSUE TITLE
Certificate domain is not validated

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5550]
![image](https://user-images.githubusercontent.com/3960742/64782347-9263f580-d582-11e9-8d1e-4f1c6f363f8d.png)

The certificate domain should match with one of the URLs given as endpoints. Otherwise, the certificate is not added properly. 

And close button color is too light.

**Comment by bhathiya** [comment]
A few more issues.

![image](https://user-images.githubusercontent.com/3960742/65146395-4bba4380-da39-11e9-8ea6-4e10d17dce10.png)

1. Alignment error
2. "This can't be undone" part is not needed?
3. Cancel button doesn't look active.

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7099
