### ISSUE TITLE
Access-Control-Allow-Headers value is empty in response headers

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#5551]
When an API deployed in WSO2 API Manager is invoked, **Access-Control-Allow-Headers** returning in the response is empty. Instead it should have the values 

**authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction** 

by default.

**Comment by chamindias** [comment]
PR : https://github.com/wso2/product-apim/pull/6487

**Comment by chamindias** [comment]
Closing because https://github.com/wso2/product-apim/pull/6487 is merged.
