### ISSUE TITLE
Cannot create an API Product

### ISSUE THREAD

**Issue by amerireza** [wso2/product-apim#5561]
Cannot create an API Product, the create button is always disabled.
_I tried the very latest release "m35", then shared the issue._

![image](https://user-images.githubusercontent.com/1961219/64908681-a4779c80-d718-11e9-9fcb-3d2a976288db.png)

1. The Error is not showing (if there is any) https://github.com/wso2/product-apim/issues/5541

**Comment by pubudu538** [comment]
Hi @amerireza,

We have recently released wso2am-3.0.0-m35. Could you please try that? 

https://github.com/wso2/product-apim/releases/tag/v3.0.0-m35

Thank you!

**Comment by amerireza** [comment]
I tried the very latest release "m35", then shared the issue.

**Comment by HiranyaKavishani** [comment]
This issue has not been reproduced in alpha release
