### ISSUE TITLE
[3.0.0] Publisher UI to configure maximum TPS for backends

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5563]
The UI to set max backend throoughput for production and sandbox endpoints has to be implemented under configure tab.
<img width="629" alt="Screen Shot 2019-09-15 at 12 15 24 PM" src="https://user-images.githubusercontent.com/4471756/64917836-89596b00-d7b2-11e9-9e51-70b1217189fd.png">

**Comment by tmkasun** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7151
