### ISSUE TITLE
[3.0.0] API Business policy config location should be moved from subscriptions page

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5565]
API business policy config UI is located below the API subscriptions blocking table. But this should be moved from subscriptions tab since it does not fit API subscriptions page and it should be moved since it has a significant value compared to API subscriptions listing table.

<img width="894" alt="Screen Shot 2019-09-15 at 12 26 32 PM" src="https://user-images.githubusercontent.com/4471756/64925785-509dae00-d813-11e9-8312-b094a56423ce.png">

**Comment by kavishkafernando** [comment]
Manage subscriptions box will move to the bottom and Subscription policies will move to the top.

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7391
