### ISSUE TITLE
Need to update the tenant URL param when logged in as different tenant.

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#5568]
**Steps to reproduce:**

1. Log in to the store using https://localhost:9443/store-new/ and it will list down the tenants available in store.

2. Go to one of the tenant without logged in.
For example https://localhost:9443/store-new/apis?tenant=abc.com

3. Then click the sign in button and logged in as separate tenant.
For example as wso2.com

4. URL still shows the tenant=abc.com instead of wso2.com

![error](https://user-images.githubusercontent.com/8374895/64939064-806aa700-d84f-11e9-87d4-4d3239db1ece.png)

This will impact to the tenant theme loading since it will take tenants from the URL.

**Comment by dushansilva** [comment]
since we are following the same approach in previous versions as well, we decided to this is ok therefore closing this issue.
