### ISSUE TITLE
When Access-Control-Allow-Origin value  with whild card, cannot invoke API successfully because "Access-Control-Allow-Origin" become empty.

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#5577]
When using the domain with a wildcard (eg: *abc.com) for the "Access-Control-Allow-Origin" value. 
If using the exact domain (eg: "tabc.com"), it could able to invoke the API successfully. 
When checking the code level[1], the wildcard is not supported and we need to configure the exact value of the origin to invoke the API successfully.

Here[1] checking exact value and in order to fix, need to check this by using regex to achieve this requirement.  

[1]. https://github.com/wso2/carbon-apimgt/blob/d41dc326449b3b2003e3aad2de7c352a08043911/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java#L360

**Comment by vithu30** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7161
