### ISSUE TITLE
[UX] Change the error message shown when validation fails

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5581]
Currently, error message is shown in following pattern when validation fails:
![value](https://user-images.githubusercontent.com/19728269/65013159-8fc51f80-d937-11e9-9ee0-227edb130c74.png)

We can customize the error messages without having "value". For instance,

> Provided API name fails to match the pattern

> Provided context fails to match the pattern

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="794" alt="Screen Shot 2019-10-13 at 6 41 48 PM" src="https://user-images.githubusercontent.com/4861150/66716254-22e35f00-ede9-11e9-8413-c5a91382d6f3.png">
