### ISSUE TITLE
Cancel button not working for the first time in 'I have an Existing Rest API' option

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5593]
Steps:
1. Select Create API > I Have an Existing REST API
2. Without filling anything select Cancel

Cancel not working and OpenAPI URL gets highlighted. After that cancel works

<img width="782" alt="Screen Shot 2019-09-18 at 10 47 22 AM" src="https://user-images.githubusercontent.com/4861150/65113687-c9faf380-da01-11e9-8a65-0a47b22f0cea.png">

**Comment by chanaka3d** [comment]
This issue is fixed with the latest snapshot build ( 6.8.33-SNAPSHOT )
