### ISSUE TITLE
[Store] Applications subscriptions page UI issues

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5601]
Following issues has to be fixed in applications subscription page

1. No subscription available info message should be displayed when subscriptions are not available ie : 'This application has not yet been subscribed to an API ..'
2. Checkboxes in API subscriptions pane are not required
3. The icons like 'search', 'print' etc should be removed from the subscribe to APIs pane
4. The fonts, font colors in applications page should be consistent and the size should be visible.

![screenshot-localhost_9443-2019 09 18-12_20_16](https://user-images.githubusercontent.com/4471756/65122793-6bd50d00-da0f-11e9-9b6c-bfba8f4ac831.png)

**Comment by Arshardh** [comment]
2 and 3 are fixed

**Comment by Arshardh** [comment]
But 1 and 4 is yet to be fixed

![image](https://user-images.githubusercontent.com/15942605/67275649-ae8f7680-f4e0-11e9-803d-9b403ebf77c1.png)

**Comment by dushaniw** [comment]
closing the issue as the UI is revamped in the latest 3.1.0 alpha
