### ISSUE TITLE
[3.0.0][Store]Test link should be renamed as 'Try out'

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5602]
'Try out' or 'API Console' would be more appropriate to name the links to navigate to API Console in order to try out the APIs.

![screenshot-localhost_9443-2019 09 18-12_34_45](https://user-images.githubusercontent.com/4471756/65123437-d89cd700-da10-11e9-9a0c-4b201192a964.png)
<img width="336" alt="Screen Shot 2019-09-18 at 12 36 00 PM" src="https://user-images.githubusercontent.com/4471756/65123453-e5212f80-da10-11e9-91a9-8c1e296f2ac0.png">

**Comment by Arshardh** [comment]
This is fixed now

![image](https://user-images.githubusercontent.com/15942605/67274755-ba7a3900-f4de-11e9-83c2-ee9c2f73a4c0.png)
