### ISSUE TITLE
Create new API UI issues

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5610]
![image](https://user-images.githubusercontent.com/3960742/65147181-3a723680-da3b-11e9-8be8-283f3fc4baa6.png)

1. Better to remove tab-stop from the tooltip.
2. Need to fix grammatically.

**Comment by shaniR** [comment]
1) I am not sure if this description is really needed, as the label ("Make this this the default version") is self descriptive. 
2) I guess the message given here is not exactly correct, is it? It states that this option selection will/will not make this API the default API version among **API's of the same name**.  It should be name and context correct? If so, it should be, among different versions of the same API.
3) There is a tool tip  and a description both in place. IMO, I think one of it is enough.
4) A message such as "Determines if this should be the default version among multiple versions of this same API."  can be used at the bottom, and if we are going ahead with the tool tip, we can explain a bit more.
