### ISSUE TITLE
[APIM 3.0.0][ UI] Cannot enable CORS via UI

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5628]
1) Create API
2) Navigate to "Configuration" tab
3) Try to enable CORS by sliding. Observe that it does not work.
![Screenshot from 2019-09-19 15-37-59](https://user-images.githubusercontent.com/7173347/65235177-bcbe3180-daf3-11e9-957d-eb2b19e3c4c3.png)

**Comment by sanjulamadurapperuma** [comment]
This works as per the latest pack.

![CORSConfigTest](https://user-images.githubusercontent.com/32578617/66544004-90c32880-eb54-11e9-96d8-49ca27c87195.gif)
