### ISSUE TITLE
Need to list the enpoints in a drop down in endpoint certificates page

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#5631]
We need to list the endpoints in a drop down in the endpoint certificate component so that it will be validated.

<img width="1012" alt="Screen Shot 2019-09-19 at 3 57 41 PM" src="https://user-images.githubusercontent.com/15009816/65236987-5affc680-daf7-11e9-8244-8e8fdb624379.png">
![Screen Shot 2019-09-19 at 1 46 49 PM](https://user-images.githubusercontent.com/15009816/65236988-5b985d00-daf7-11e9-810d-9bbc9d10e38d.png)

**Comment by menakaj** [comment]
Fixed 
![Screenshot(16)](https://user-images.githubusercontent.com/10165411/66863072-e44bd100-efaf-11e9-8fc5-f550b7f75792.png)
