### ISSUE TITLE
[APIM 3.0.0][UI]  API overview page shows technical owner as "loading ..."

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5634]
1) Click on an API from the API listing page
2) Observe the Technical owner field
![Screenshot from 2019-09-19 16-54-11](https://user-images.githubusercontent.com/7173347/65240150-35c28680-dafe-11e9-8cd9-b2b8a2ec7ee6.png)

**Comment by tmkasun** [comment]
Fixed in APIM 3.0.0 beta
