### ISSUE TITLE
[APIM 3.0.0][UI] Publishing an API without an Endpoint assigned is allowed

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5636]
1) the UI allows publishing an endpoint without an endpoint.
2) step 1 generates an error in the server console " ERROR - APIUtil Unable to parse endpoint config JSON org.json.simple.parser.ParseException: null"
3) Shows a UI error, which is hard to read. 
![Screenshot from 2019-09-19 17-34-12](https://user-images.githubusercontent.com/7173347/65242478-b768e300-db03-11e9-89fd-8cb0833b8696.png)

**Comment by tmkasun** [comment]
Fixed in APIM 3.0.0 beta
