### ISSUE TITLE
Invoking API Product with JWT access token fails

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#5637]
Invoking an API Product using a JWT access token returns the following error

`{"fault":{"code":900918,"message":"Internal Server Error","description":"JWT authentication cannot be performed."}}`

Following error is displayed in wso2carbon.log
`
OAuthAuthenticator  Swagger is missing in the gateway. Therefore, JWT authentication cannot be performed`.

**Comment by kalevivek11** [comment]
Hi is this issue still present in 3.0

**Comment by fazlan-nazeem** [comment]
the fix is already available in 3.0 release.

**Comment by kalevivek11** [comment]
@fazlan-nazeem  we are getting this issue in gateway Log
ERROR - OAuthAuthenticator Swagger is missing in the gateway. Therefore, JWT authentication cannot be performed

but this issue is indeterminant

do i have to add anything in toml? or any configuration
