### ISSUE TITLE
[APIM 3.0.0][UI] Developer portal cards are not aligned

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5638]
API Developer portals API Credentials and Resources cards are not aligned
![Screenshot from 2019-09-19 17-45-25](https://user-images.githubusercontent.com/7173347/65243175-72de4700-db05-11e9-9aaa-ccac174dd583.png)

**Comment by binodmx** [comment]
Also options(with a default application, with a new application) in 'Subscribe to an Application' are very small to notice.

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="1351" alt="Screen Shot 2019-10-11 at 1 43 19 PM" src="https://user-images.githubusercontent.com/4861150/66635573-216d3780-ec2d-11e9-872b-4023684caf3e.png">
