### ISSUE TITLE
[APIM 3.0.0][UX] The Store application is named as "WSO2 developer portal", but the react application has the "store" context

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5639]
The store application is renamed from API Store to API Developer portal. However, the context of the application is still store/. Should we rename it to developer?
![Screenshot from 2019-09-19 17-50-55](https://user-images.githubusercontent.com/7173347/65243491-10397b00-db06-11e9-89aa-0cf5484f0dc7.png)

**Comment by isharac** [comment]
fixed.
