### ISSUE TITLE
[APIM 3.0.0][UI/UX] Delete button in the delete API message box looks inactive

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5643]
![Screenshot from 2019-09-19 18-25-31](https://user-images.githubusercontent.com/7173347/65245841-f6e6fd80-db0a-11e9-8d0b-02e9c29cb789.png)

**Comment by chamilaadhi** [comment]
Theme changed in AM 3.0.0 beta
<img width="503" alt="Screen Shot 2019-10-13 at 6 25 11 PM" src="https://user-images.githubusercontent.com/4861150/66715955-d9921000-ede6-11e9-97b5-601f2ddfb694.png">
