### ISSUE TITLE
[APIM 3.0.0][UI] Deleting API with active subscriptions shows a loading action

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5644]
1) Create an API and publish it
2) Add Subscription to the API from the developer portal
3) Delete the API from the publisher portal
4) Observe that no error message is shown on the UI, and loading action is showed.
5) Server console logs error message "ERROR - ApisApiServiceImpl Requested API with Id '3fc64576-0808-4e2a-98ab-09ccb61b67b1' not found
org.wso2.carbon.apimgt.api.APIMgtResourceNotFoundException: Failed to get API. API artifact corresponding to artifactId 3fc64576-0808-4e2a-98ab-09ccb61b67b1 does not exist
"

**Comment by dushaniw** [comment]
This cannot be reproduced in the latest 3.1.0-Alpha. Hence closing the issue.
![Screenshot from 2020-02-11 17-26-46](https://user-images.githubusercontent.com/12208083/74234806-b5423380-4cf3-11ea-83d5-5a241c59cdf7.png)
