### ISSUE TITLE
[APIM-3.0.0][UX] Issue when deleting and creating scopes.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#5659]
Steps:

1. Create an API and add a scope.
2. Delete the created scope.
3. Create a new scope.

Observation: 
The newly created scope is not added.

**Comment by AmaliMatharaarachchi** [comment]
Could not reproduce the above issue in 3.0.0-alpha pack. However, this may have observed due to the following issues,
https://github.com/wso2/product-apim/issues/5707
https://github.com/wso2/product-apim/issues/5619
