### ISSUE TITLE
When updating any claim fields with boolean values in the user profile that will be converted as checkbox

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#5673]
**Description:** 
If the user entered a value to **any field** as 'true' or 'false' and updated in the user profile screen (Users and Roles > List > Users > User Profile > default) of the management console, then it will be converted as a checkbox.

For example, if someone mistakenly entered "true" or "false" to "First Name" field and updated, it will be converted to a checkbox. After that, there is no proper way to enter the correct name again.

**Affected Product Version:**
IS-AS-KM 5.6.0
IS-AS-KM 5.7.0
APIM 2.6.0

**Steps to reproduce:**
1. Create a new user from the management console.
2. Update the user profile text fields with boolean values (true or false).
3. Then it will be converted into a checkbox.  
4. There is no proper way to convert it to a text box again.

**Comment by isharac** [comment]
Won't fix as this is a minor user error.
