### ISSUE TITLE
Swagger populating issue for Graphql APIs in Store

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5679]
![Screen Shot 2019-09-21 at 12 56 29 PM](https://user-images.githubusercontent.com/29066805/65369791-5d852c00-dc6f-11e9-9068-448c8d53ec5f.jpg)

Related issue:
https://github.com/wso2/carbon-apimgt/issues/7032

**Comment by AmaliMatharaarachchi** [comment]
I was able to reproduce this issue by following the below steps. 

**Steps to reproduce**
Create a graphQL api.
Goto business info and update the api.
Publish and go to dev portal Test tab.

**Comment by HiranyaKavishani** [comment]
@AmaliMatharaarachchi Can you look into this?

**Comment by AmaliMatharaarachchi** [comment]
> @AmaliMatharaarachchi Can you look into this?

sure.
