### ISSUE TITLE
[APIM 3.0.0][UX] Mediation Policies should be shown in Request/ Response sections in Configuration Page

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#5682]
![Screenshot (9)](https://user-images.githubusercontent.com/10165411/65383026-5ff98b80-dd2c-11e9-89bc-52dcfc9afadf.png)

A link to mediation policies should be shown in the request/ response sections.

**Comment by erangatl** [comment]
related: https://github.com/wso2/product-apim/issues/5481
