### ISSUE TITLE
Make Response caching more configurable

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#5683]
Response caching should be more configurable. At least the cachable status codes. 

This is already supported by the runtime. (by `responseCodes` below). 

         <cache collector="false" timeout="100">
            <protocol type="HTTP">
               <methods>*</methods>
               <headersToExcludeInHash/>
               <responseCodes>.*</responseCodes>
               <enableCacheControl>false</enableCacheControl>
               <includeAgeHeader>false</includeAgeHeader>
               <hashGenerator>org.wso2.carbon.mediator.cache.digest.REQUESTHASHGenerator</hashGenerator>
            </protocol>
            <implementation maxSize="500"/>
         </cache>

Above is the current default in the runtime, which caches all responses. (ie.. `responseCodes=.*`) This can be wrong in many cases.

There should be a way to configure this in the UI.

**Comment by fabrii** [comment]
I think there should also be a way to configure if we want the caché to apply only to GET requests. Reading the issue it seems that all methods are cached? Might be wrong.

`<methods>*</methods>`
