### ISSUE TITLE
[UI] No Message is displayed when creating the sample api using a user with creator role

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5687]
Deploy the sample API using a user with creator role. Nothing is shown. Once the page is refreshed, API can be displayed in created state. Need to handle this case

**Comment by Sarangan0219** [comment]
This issue is not present in 3.1.0 . Hence It can be closed.

![Screenshot from 2020-03-03 11-41-04](https://user-images.githubusercontent.com/60866295/75748370-4b8ed580-5d45-11ea-82ef-385f93dc0b0e.png)

**Comment by prasa7** [comment]
Fixed in 3.x.x
