### ISSUE TITLE
When the user is provisioned, provisioned claims are not included in the backend JWT.

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#5696]
When the user is provisioned, provisioned claims are not included in the backend JWT.It's just checking the authorization cache and return the claims excisting in it only.

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/dec392b8a5cbbe083ac3e069a7dbf7ac23a6d498. Hence closing.
