### ISSUE TITLE
Need to prevent access to the analytics data for a user who has only 'create and login' permission

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#5703]
**Description:**
We need to hide the analytics data in the publisher portal from one who has only 'create and login' permission. 

Can we add this improvement to APIM 3.0 as per the tenant-wise configuration? 
So that admin can create roles which can only create APIs without allowing them to see analytics data.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
