### ISSUE TITLE
[3.0.0] URL based swagger import is missing in API definitions page

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5711]
URL and File-based swagger import option should be provided in API definitions page 
![screenshot-localhost_9443-2019 09 24-11_49_22](https://user-images.githubusercontent.com/4471756/65486285-aaf8d780-dec1-11e9-8998-ed1a712f80d6.png)

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
