### ISSUE TITLE
Errors occurs in API product API DEFINITION and RESOURCE tabs after updating product

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#5720]
**Version**
3.0.0

**Steps to reproduce**
Issue 1 : 
Go to configuration tab. Click save.
Click on RESOURCE tab

**Error**
<img width="1040" alt="Screenshot 2019-09-24 at 14 55 58" src="https://user-images.githubusercontent.com/17607322/65499559-7265f780-dedb-11e9-9f0d-72681a6ddd5c.png">

**Comment by HiranyaKavishani** [comment]
This has been resolved in the latest code
