### ISSUE TITLE
Inconsistent font usage in API tiles in API listing page

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#5725]
<img width="708" alt="Screen Shot 2019-09-24 at 3 40 56 PM" src="https://user-images.githubusercontent.com/4471756/65503056-c1af2680-dee1-11e9-9094-2de8ef4d4f25.png">

**Comment by chamilaadhi** [comment]
This is re-structured in 3.0.0 beta
<img width="727" alt="Screen Shot 2019-10-12 at 10 10 08 AM" src="https://user-images.githubusercontent.com/4861150/66694991-8c277d00-ecd8-11e9-9b19-f5f7f9a016d4.png">
