### ISSUE TITLE
Context is not aligned properly in API card

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#5726]
Context is not aligned properly in API card

<img width="675" alt="Screen Shot 2019-09-24 at 3 32 23 PM" src="https://user-images.githubusercontent.com/19324135/65503065-c96ecb00-dee1-11e9-8552-c28da3bb8b4f.png">

**Comment by chanaka3d** [comment]
Fixing with https://github.com/wso2/carbon-apimgt/pull/7261
