### ISSUE TITLE
API creator attempts to create a REST API with API context contains exactly 255 characters

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5729]
**Description**

- I typed 31 characters for the context field and when I click the version box to type the version a red coloured msg appears as {"value" with value "wqwqwwqwqwqwqwqwqwqwqwwqwqwqwwq" fails to match the required pattern: /^[a-zA-Z0-9{}\/]{1,30}$/ }. Therefore, the create button also disappeared. But this issue doesn't appear with 30 characters. Anyway, the above issue disappears when I clicked the red colored message or the "version" field. 

- I also typed a 255 characters long string for the context, but APIM didn't allow me to create the API. It logged an error in the terminal saying that my context has 262 characters(But I checked it and it was only 255)
![Screenshot from 2019-09-24 16-52-09](https://user-images.githubusercontent.com/44407066/65569072-caebd200-df79-11e9-9ca5-42c8186d9a80.png)
(When I typed 30 characters)

![Screenshot from 2019-09-24 16-52-13](https://user-images.githubusercontent.com/44407066/65569103-ece55480-df79-11e9-8eec-1dcc7252c0e6.png)
(When I typed 31 characters the create button got disabled, but when I clicked the red message the "create" button reappeared)

**Comment by chamilaadhi** [comment]
Rest API level validation is added to prevent this kind of issue. User would get an error message 
![Screen Shot 2019-10-07 at 6 36 33 PM](https://user-images.githubusercontent.com/4861150/66314296-6f362700-e931-11e9-8850-22f23710c470.png)
