### ISSUE TITLE
Error while genarating the production, sandbox keys for an application

### ISSUE THREAD

**Issue by Thidasala** [wso2/product-apim#5730]
Description-:
Test case:
 4.1.1.3- Application owner should be able to generate production keys for an application.

Result:
If the application name includes white spaces, production keys or sandbox keys cant be generated.

![Screenshot from 2019-09-24 16-45-38](https://user-images.githubusercontent.com/45654571/65507149-e8258f80-deea-11e9-8cee-4dc8862fc680.png)

**Comment by kavishkafernando** [comment]
This is no longer reproducible in latest 3.0.0 pack

<img width="1498" alt="Screen Shot 2020-01-03 at 5 26 50 PM" src="https://user-images.githubusercontent.com/19324135/71722255-3fbe8a00-2e4e-11ea-8988-a554964ae41c.png">
