### ISSUE TITLE
[Publisher] Resource level throttling policy cannot be set

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#5733]
Select the **Rate limiting** level as **Operation Level** and try to set a policy for a resource. Policy cannot be set (drop down menu is disabled)

<img width="800" alt="Screen Shot 2019-09-24 at 5 00 02 PM" src="https://user-images.githubusercontent.com/4861150/65508019-dba23680-deec-11e9-939e-a1d3b7d6d597.png">

**Comment by chamilaadhi** [comment]
First need to save Rate limiting level and after that this dropdown menu gets enabled. reducing the levels . 

I think need to improve this . I think Save/Reset is not needed in the radio button section in the rate limiting level section

**Comment by erangatl** [comment]
Fixed in latest

![image](https://user-images.githubusercontent.com/20179540/74308187-91333080-4d8d-11ea-90ab-5aa4f5e526a2.png)
