### ISSUE TITLE
Error while Publishing an API without selecting a single policy plan

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5735]
Use Case : API publisher wants to provide several business plans for subscribers to use
Test Case Name: [N] Publishing an API without selecting single policy plan should not be allowed

Details of Issues Encountered :Issue found in the error message prompted, while publishing the API without selecting a single policy plan. Error Message only includes the string "" without specifying the error which has occurred in detail. 

The Screenshots relevant to the error context :
 
![Screenshot from 2019-09-24 17-20-13](https://user-images.githubusercontent.com/38970634/65510313-473ad280-def2-11e9-82aa-d1b24117c121.png)
![Screenshot from 2019-09-24 17-22-19](https://user-images.githubusercontent.com/38970634/65510326-4b66f000-def2-11e9-820f-e3fe5e934709.png)

**Comment by chamilaadhi** [comment]
This is not allowed in 3.0.0 beta.

Disabled the create and publish button
<img width="827" alt="Screen Shot 2019-10-12 at 9 27 50 AM" src="https://user-images.githubusercontent.com/4861150/66694602-bb3af000-ecd2-11e9-9fdd-28fa3c19f093.png">

Added a checklist in LC page
<img width="1190" alt="Screen Shot 2019-10-12 at 9 27 31 AM" src="https://user-images.githubusercontent.com/4861150/66694603-bd9d4a00-ecd2-11e9-9245-438f0af4067b.png">
