### ISSUE TITLE
APIDefinition tab in API Product has been broken after updating resources

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5738]
Steps to reproduce
1. Create an API Product
2. Navigate to the resource page and click Edit
3. Add resources to product
4. Navigate to APIDefinition
5. Error is shown
![Screen Shot 2019-09-24 at 8 24 52 PM](https://user-images.githubusercontent.com/29066805/65523630-2c745800-df0a-11e9-84f2-6c61b5d76e7c.jpg)

6. Refresh the URL
7. Even, Swagger has been loaded, resources are not showing in it

**Comment by tmkasun** [comment]
I too experienced this issue, I think the problem is after resource edit it updates the state with plan JSON object not an object from API class

**Comment by HiranyaKavishani** [comment]
This has been resolved
