### ISSUE TITLE
[APIM-3.0.0][UI] Websocket APIs are created as HTTP

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#5740]
The api type of the WebSocket apis are set as HTTP.
![Screenshot (12)](https://user-images.githubusercontent.com/10165411/65528231-9a704d80-df11-11e9-9bc5-a106933ca588.png)

**Comment by Arshardh** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/7206
