### ISSUE TITLE
Test case [4.1.1.8]: When creating an application, it allows to add more than 70 characters to application name

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5743]
Description-:
Test case:
4.1.1.8- [N] Nobody should be allowed to add more than 70 characters to application name

Result:
It allows to create an application with more than 70 characters

![Screenshot from 2019-09-25 09-01-00](https://user-images.githubusercontent.com/54613992/65567374-a0971600-df73-11e9-826e-fd47ef5de278.png)

**Comment by chamilaadhi** [comment]
Need to add a validation. Error message is shown in the popup window
