### ISSUE TITLE
Error while trying to navigate to the API-publisher  after the first time.

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5745]
Description:
After shutting down the server  and then tries to login to the  https://localhost:9443/publisher-new/ after restating the server following massage is displayed in the console.
when  the cookies are cleared in the browser users can log in to the API publisher again.

![Screenshot from 2019-09-25 09-24-10](https://user-images.githubusercontent.com/42222921/65568369-1d77bf00-df77-11e9-898b-14266fbd64f5.png)
![Screenshot from 2019-09-25 09-26-28](https://user-images.githubusercontent.com/42222921/65568371-1f418280-df77-11e9-9096-49caa028411b.png)

**Comment by tmkasun** [comment]
Thanks for reporting the issue, We have already identified this issue and have created following https://github.com/wso2/product-apim/issues/5655 git issue, Hence I will close this issue.
