### ISSUE TITLE
Publisher login error for users from newly created roles

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#5746]
**Steps:**
1. Create a new Role in wso2 carbon with 'All Permissions'.
2. Create a new user in carbon with that new role.
3. Try to login to the publisher.
4. Click on the login button on the store.
5. Click on the APIs tab.
6. Click on an available API in the store.

**Issue:**
When I try to login to the publisher, it shows an 403 Forbidden error on the publisher UI.
When I click on the login button on the store, the user is logged into the store. When I click on an available API in the store, UI is navigated to the home page and the user is shown as logged out.
Also, there was an error log in the terminal after I click on an API.

![Screenshot from 2019-09-24 17-06-53](https://user-images.githubusercontent.com/35653110/65568342-03d67780-df77-11e9-9630-830b40335978.png)

![Screenshot from 2019-09-25 09-33-06](https://user-images.githubusercontent.com/35653110/65568470-8a8b5480-df77-11e9-95af-cfca9cd69126.png)

**Comment by chamilaadhi** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/7309
