### ISSUE TITLE
Error when subscribing to multiple policies

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#5747]
Test case : 7.1.2 API publisher wants to expose the API with only few plans based on an agreement, so that subscriber will be able to select specific plan/s

Issue when the subscriber cannot select more than one policies exposed by admin.
The available policies exposed by admin are listed down, but subscriber cannot select multiple policies, only one out of them can be selected.

![Screenshot from 2019-09-25 10-13-58](https://user-images.githubusercontent.com/54226167/65569992-40a56d00-df7d-11e9-80f6-23441bc8ec03.png)

**Comment by rmsamitha** [comment]
Not a bug
