### ISSUE TITLE
[Store] Overlapping value and label in Key field on API Test Page

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5751]
![key_overlap](https://user-images.githubusercontent.com/27700915/65571838-adbc0100-df83-11e9-83a5-ac096b52ede9.png)

**Issue**
Label and the value in the Key field in the API Test page of the API Store are overlapping when a value was selected from the drop down menu.

**Steps**

1. Select a value for the key field from the drop down menu
2. Click anywhere else in the screen

**Comment by nalakas** [comment]
suggested label: UX improvement

**Comment by Arshardh** [comment]
This is fixed in the latest build

![image](https://user-images.githubusercontent.com/15942605/67274515-345df280-f4de-11e9-86bd-624af61367a7.png)
