### ISSUE TITLE
Bug when trying to login to the API-Store as an API-Creator

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5755]
Description:

When a user who has the permission level of an API-Creator tries to logs in to the api store and the if the user tries to browse the APis or try to navigate to the Application tab user is automatically logged out from the system and redirected to the landing page
Without showing any proper information to the end user and the following error[1] logs in the  console.
[1]![Screenshot from 2019-09-25 11-05-31](https://user-images.githubusercontent.com/42222921/65572962-50c24a00-df87-11e9-9df6-9b8b0b4bd795.png)

**Comment by chamilaadhi** [comment]
fixed as part of https://github.com/wso2/carbon-apimgt/pull/7309
