### ISSUE TITLE
Error when try to logout from the system

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5757]
Description:

When a user presses the logout button on the API-Publisher and chose the option **NO** 
Instead of directing the user back to the previous page user is shown  following massage[1].
 
[1]![Screenshot from 2019-09-25 11-39-22](https://user-images.githubusercontent.com/42222921/65574117-33db4600-df8a-11e9-83e7-b0f3c7e796e3.png)

**Comment by chamilaadhi** [comment]
Fixed in 3.0.0 beta. Now redirect back to the publisher page without login out the user
