### ISSUE TITLE
[store] Users can update application names with a case insensitive duplicate name.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5760]
![image](https://user-images.githubusercontent.com/40932779/65575198-e9a79400-df8c-11e9-9704-1de10d2e7a43.png)

**Here app developer can change application names in a case insensitive manner.**
(Tester & tester application names)

**Comment by dushansilva** [comment]
duplicate issue https://github.com/wso2/product-apim/issues/5744
fixed with https://github.com/wso2/carbon-apimgt/pull/7314
