### ISSUE TITLE
[Publisher]API Create Page name contains more than 255 characters

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#5761]
![Screenshot from 2019-09-25 11-52-43](https://user-images.githubusercontent.com/31029812/65574981-65eda780-df8c-11e9-9786-b633d6d3c684.png)
![Screenshot from 2019-09-25 12-10-25](https://user-images.githubusercontent.com/31029812/65575464-836f4100-df8d-11e9-8e65-702c9f6ff54f.png)

Test case - 
API creator attempts to create a REST API with API name contains more than 255 characters
 
Problem Encountered - After the name input field validation, container alignment is changing for both super tenant and tenants.

**Comment by chamilaadhi** [comment]
Related issue https://github.com/wso2/product-apim/issues/5732
