### ISSUE TITLE
Bug Two Error message are overlapping on each other

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5764]
Description:

In the Manage subscription page of a published API
If the user tries to uncheck all the subscription policies two error messages are shown overlapping on each other.[1]
The error message is also unclear to the end user.
[1]![Screenshot from 2019-09-25 12-19-21](https://user-images.githubusercontent.com/42222921/65576089-e31a1c00-df8e-11e9-9894-41578c893266.png)

**Comment by tharikaGitHub** [comment]
Related issue https://github.com/wso2/product-apim/issues/5784
