### ISSUE TITLE
[store] Signup page in API Store page

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5772]
Sign-up button in API store home page not in the current version.
But it can be retrieved by going through the login button.
After creating account, redirection does not happen.
Login to the newly created account is also not possible.

Some pages say that there is a Signup button in the API store home page.
[https://docs.wso2.com/display/AM260/Sharing+Applications](url)

![image](https://user-images.githubusercontent.com/40932779/65589230-5f6c2980-dfa6-11e9-9d2e-1ee4d76670c6.png)

![image](https://user-images.githubusercontent.com/40932779/65589330-7b6fcb00-dfa6-11e9-93ed-d15b5c3fa34c.png)

**Comment by rmsamitha** [comment]
@tharikaGitHub Can we close this?

**Comment by tharikaGitHub** [comment]
This issue will be addressed in https://github.com/wso2/product-apim/issues/5911
