### ISSUE TITLE
[store] API filters are not working

### ISSUE THREAD

**Issue by Thidasala** [wso2/product-apim#5773]
![Screenshot from 2019-09-25 15-13-11](https://user-images.githubusercontent.com/45654571/65589747-2bddcf00-dfa7-11e9-8032-745975fe8d17.png)

**Comment by rmsamitha** [comment]
@chanaka3d Is this API filtering option disabled now? It is not visible.

**Comment by chanaka3d** [comment]
Yes. The filtering is disabled because it is not a requirement for the api listing table.
