### ISSUE TITLE
A user with creator role cannot update details of an prototyped API

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#5775]
Issue:
A user with creator role cannot edit configurations, endpoints, business info, etc of an prototyped API.

**Comment by chamilaadhi** [comment]
Are you trying this after publishing the API? creator won't be able to edit the api once it is published.

**Comment by ThaminduDilshan** [comment]
@chamilaadhi  After deploying as a prototype

**Comment by chamilaadhi** [comment]
Fixed
