### ISSUE TITLE
[Publisher] Create API button is visible to a user logged in with an API publisher role

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5776]
![Selection_007](https://user-images.githubusercontent.com/27700915/65591280-d1923d80-dfa9-11e9-8dbb-846aaf3b80ea.png)

**Issue:**
Create API button is visible and accessible to a user who has logged in with an API publisher role. How ever the APIM does not let him create the API.

**Error log:**
[2019-09-25 15:20:36,630] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed

**Steps**

1. Log in to API publisher using a publisher role.
2. Click on Create API button

**Comment by ThaminduDilshan** [comment]
I got the same error when I try to edit an API from a user with a publisher role. The error was logged in the terminal when I click on Configuration and Endpoint tabs.

**Comment by rmsamitha** [comment]
This is fixed now
