### ISSUE TITLE
UI Issue in "ENDPOINTS" tab in Publisher

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5780]
**Description**

- I entered a production endpoint in "ENDPOINTS" page but the publisher doesn't check whether the "Production Server url" field is empty in real-time. We need to click somewhere else to get the red message disappeared.
![Screenshot from 2019-09-25 16-54-19](https://user-images.githubusercontent.com/44407066/65597111-fbe9f800-dfb5-11e9-80f0-9f978fbf8cc0.png)

**Comment by chamilaadhi** [comment]
I think a real time validation is not needed here.
