### ISSUE TITLE
UI Issue regarding signing-in in the API Manager Store

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5781]
When I signed out and tried to sign in by using a different tenant, the UI does not directly redirects to the sign in page. Instead it redirects to the the page as per the below screenshot.  

![Screenshot from 2019-09-25 17-03-48](https://user-images.githubusercontent.com/38970634/65597687-58014c00-dfb7-11e9-80a4-d970ae3c183f.png)

**Comment by chamilaadhi** [comment]
That is the behaviour. when you sign out from the store, it goes back to the public store
