### ISSUE TITLE
[Suggestion] Display the URL pattern when adding resources at the publisher

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5782]
![image](https://user-images.githubusercontent.com/47671237/65598574-605a8680-dfb9-11e9-9c58-753da96d8ed9.png)

![image](https://user-images.githubusercontent.com/47671237/65599038-79176c00-dfba-11e9-9700-54ff32a38f75.png)
![image](https://user-images.githubusercontent.com/47671237/65599537-b3cdd400-dfbb-11e9-8901-c2a7fe752a92.png)

It would be better to show the URL pattern when adding resources for an API at the publisher as in the previous version or else it would be a bit confusing.

**Comment by chamilaadhi** [comment]
New UI implementation provides a clean resource view. ATM no plan to add this
