### ISSUE TITLE
Cant import APIS to micogateway 3.0.1

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5783]
we cant import APIs to the micro gateway v3.0.1.When we use the import command it gives an error
micro-gw import -l CALCULATING calculator
Enter Username: 
admin
Enter Password for admin: 

Enter APIM base URL [https://localhost:9443]: 

You are using REST version - v0.14 of API Manager. (If you want to change this, go to <MICROGW_HOME>/conf/toolkit-config.toml)
Enter Trust store location: [lib/platform/bre/security/ballerinaTruststore.p12]

Enter Trust store password: [ use default? ]

micro-gw: Internal error occurred while executing command. - Error occurred while creating oAuth application Status code: 500

**Comment by rmsamitha** [comment]
@ShanJayaweera Shall we move the issue to the product-mgw repo and close this issue?

**Comment by ShanJayaweera** [comment]
@rmsamitha Ok. I'll move the issue to the repo product-mgw
