### ISSUE TITLE
Success messages overlaps each other

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#5784]
The success message notification displayed after updating the subscription policy in the publisher window overlaps with another message.

![Screenshot from 2019-09-25 17-14-44](https://user-images.githubusercontent.com/54226167/65608650-3068ae80-dfcc-11e9-821f-b7a6caf9069f.png)

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7601
duplicate https://github.com/wso2/product-apim/issues/5764
