### ISSUE TITLE
[Store] UI related issues in the comments page

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5786]
**Suggestions to improve the UI**

1. Either remove the icon which is used for the comments heading (shown below) or add a more relevant icon (since this feels like a dropdown icon) with a padding between the icon and the word "Comments". Also note that no other tab under the APIs (overview, credentials, test, docs, etc.) have any icon before the heading, hence there is a lack in consistency.

![2](https://user-images.githubusercontent.com/30475839/65597608-2a1c0780-dfb7-11e9-98e3-5f17a82ace39.png)

2. Move up the "write a comment" section and move down the already added comments. As shown through the screenshot below, suggestion is to interchange the sections 1 and 2. This is the better approach, since in a usecase where there are previously added comments, and in order to add a new comment, it is a must to scroll down and this is not that user friendly.

![4](https://user-images.githubusercontent.com/30475839/65613664-061aef00-dfd4-11e9-9c1c-2b9b1b9a6714.png)

3. Considering the sections numbered as 1 and 2 in the screenshot provided below, it is better to align all text to the same line, i.e. to start the "write a comment" input field from the section labeled as 2 (rather than having it under the section labeled as 1).
Also section 3 indicates that the count is not aligned with the rest of the section. Here the suggestion is to align it with the cancel button or with the input field or completely remove the count and provide an error message when the maximum character count is reached in realtime.
Section 4 in the screenshot given below shows that there is alot of unutilized space in the UI. 

![5](https://user-images.githubusercontent.com/30475839/65617957-28fcd180-dfdb-11e9-8185-15be06907ed4.png)

4. Input field line could be extended from the current location (marked as 1 in below screenshot) upto the location marked as 2 in the below screenshot. This will provide better alignment.

![6](https://user-images.githubusercontent.com/30475839/65618561-2058cb00-dfdc-11e9-9d76-4502ec62e079.png)

**Comment by chamilaadhi** [comment]
Fixed

<img width="1410" alt="Screen Shot 2019-10-10 at 10 17 25 PM" src="https://user-images.githubusercontent.com/4861150/66589301-dc54f100-ebab-11e9-83a7-49e49d2b5a99.png">
