### ISSUE TITLE
[Publisher]API Create Page API context contains white spaces

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#5788]
![Screenshot from 2019-09-25 16-36-57](https://user-images.githubusercontent.com/31029812/65624986-9105e480-dfe8-11e9-955b-fabf50b84045.png)
![Screenshot from 2019-09-25 17-21-09](https://user-images.githubusercontent.com/31029812/65624991-9400d500-dfe8-11e9-89d5-701e33e39989.png)
![Screenshot from 2019-09-25 17-21-16](https://user-images.githubusercontent.com/31029812/65625006-98c58900-dfe8-11e9-8843-0b6e498ade1a.png)

Test Case: API creator attempts to create a REST API with API context contains white spaces

Problem Encountered: Users still can create REST APIs with white spaces in the context field. This should not be happen. users should not be able to create APIs with white spaces in the context field.

**Comment by npamudika** [comment]
This issue has been fixed in the latest APIM 3.0.0 pack (as per 7th October 2019). Hence closing the issue.
