### ISSUE TITLE
[Store] The curl command does not contain the '-k' tag

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5797]
![image](https://user-images.githubusercontent.com/47671237/65657309-7eb79500-e040-11e9-935a-501be9ffe3af.png)

![image](https://user-images.githubusercontent.com/47671237/65657323-9000a180-e040-11e9-85ed-372a63d6c392.png)

![image](https://user-images.githubusercontent.com/47671237/65657388-e241c280-e040-11e9-9aa8-12ca5104c5b1.png)

When invoking an API at the store, the curl command generated does not contain the '-k' tag as in the 2.6 version API store.

**Comment by tharindu1st** [comment]
Gateway hostnames use CA sign certificates therefore -k is not required
