### ISSUE TITLE
In the API Create page the mandatory fields are not checked at real-time

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5799]
**Description**

- In the create page of the API publisher even if we fill all the mandatory fields (Name, Context & Version) the "Create" button doesn't appear automatically. We have to click elsewhere to make it appear.

![Screenshot from 2019-09-26 10-00-02](https://user-images.githubusercontent.com/44407066/65658229-6fd2e180-e044-11e9-91b7-15ffd9d55383.png)

**Suggestion**

- It would be nice if we can check the emptiness of the fields in real-time.

**Comment by SachithKasthuriarachchi** [comment]
@tmkasun can we close this issue if this is not relevant now?

**Comment by Krishanx92** [comment]
Validation happen with foucs so this will be current behavior, hence closing
