### ISSUE TITLE
Error/Bug when trying to publish an API with no resources

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5800]
Test Case:

[N] An API
(a) in CREATED state
(b) doesn't Include all the mandated information in design, implement and manage stages
(c) by a user with publish permissions
should not be able to promote to PUBLISHED state.

Validations:
(a) The request should return 4XX.
(b) Final life-cycle state of the API is CREATED

Description:

After creating a REST API  and after deleting All the default resources users are still able to publish the API and in the store API is displayed and in the resource section it shows loading.

[1] Error Log- https://drive.google.com/open?id=1l3wNo-Ih9qFAiGD6t56_B1ar8YZZtMaT

**Comment by chamilaadhi** [comment]
UI error message is shown when you try to delete all resources. At least one resource needs to be there. this will prevent publishing without any resource

<img width="1354" alt="Screen Shot 2019-10-10 at 10 00 21 PM" src="https://user-images.githubusercontent.com/4861150/66588171-7ff0d200-eba9-11e9-85b2-cf1be1327f48.png">
