### ISSUE TITLE
[Store]Can't generate keys to invoke the API

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#5801]
![Screenshot from 2019-09-26 10-02-42](https://user-images.githubusercontent.com/31029812/65658554-dd334200-e045-11e9-9506-88cef0fc880a.png)
![Screenshot from 2019-09-26 10-02-19](https://user-images.githubusercontent.com/31029812/65658559-e15f5f80-e045-11e9-889a-273f4f3309ab.png)
![Screenshot from 2019-09-26 10-02-18](https://user-images.githubusercontent.com/31029812/65658567-e6bcaa00-e045-11e9-8b45-607e0b702781.png)

Test Case: Tried to generate keys to invoke an API.

Problem Encountered: can't generate keys, screen freezes

**Comment by chamilaadhi** [comment]
No issue in 3.0.0 beta
