### ISSUE TITLE
[store] Application's Per Token Quota is not in the correct order 

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5802]
When updating application details, **application per token quota drop down** is not in the correct order. 

![image](https://user-images.githubusercontent.com/40932779/65658983-7020ac00-e047-11e9-924b-0eeeee2391eb.png)

**Comment by kavishkafernando** [comment]
Per Token Quota is now displayed in order in latest 3.0.0 pack.
<img width="981" alt="Screen Shot 2020-01-03 at 5 16 42 PM" src="https://user-images.githubusercontent.com/19324135/71721879-e570f980-2e4c-11ea-8dc3-f15f728917dc.png">
