### ISSUE TITLE
[Store] Improvement needed when testing the API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5807]
This is the flow that I follow when trying to test an API which already has a subscription with OAUTH as the token type:
1. Select the relevant API
2. Click on the "CREDENTIALS" tab
3. Go to "MANAGE APP" of the relevant Application
4. Click on "GENERATE ACCESS TOKEN"
5. Click on "GENERATE"
6. Copy the access token and click close
7. Then in order to test that same API I need to move back to the APIs tab and then select the API which I initially intended to test. Then go to the "TEST" tab and select the relevant application to test it out 

Improvement suggested here is to provide a link or button to navigate back to the same API from where the credentials tab was selected.

**Comment by chamilaadhi** [comment]
This page is refactored in 3.0.0 beta. for example, there is a button in the API info page to subscribe. Please check it with the new release
<img width="1241" alt="Screen Shot 2019-10-11 at 8 45 06 AM" src="https://user-images.githubusercontent.com/4861150/66621960-9166c800-ec03-11e9-83b1-69cc0d856ce4.png">
