### ISSUE TITLE
[Publisher] Can save the Endpoint page without giving mandatory crdentials 

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5808]
End Point page can be saved by selecting Endpoint Security & without giving any mandatory credentials,username and password.
![Screenshot from 2019-09-26 11-09-31](https://user-images.githubusercontent.com/31464477/65661246-c5ac8700-e04e-11e9-896b-50e284627347.png)

**Comment by chamilaadhi** [comment]
duplicate https://github.com/wso2/product-apim/issues/5907
