### ISSUE TITLE
Error while Adding an endpoint after prototyping an API

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5809]
Description :

After creating the API without the endpoint and deployed it as a prototype without  adding the endpoint after clicking the HTTP/REST endpoint and not adding any details.when try to add an HTTP/REST endpoint after prototyped routed to the following page [1].Following log is displayed [2]

[1]
![Screenshot from 2019-09-26 11-10-08](https://user-images.githubusercontent.com/42222921/65661383-263bc400-e04f-11e9-8290-3590347b186e.png)

[2]
![Screenshot from 2019-09-26 11-15-09](https://user-images.githubusercontent.com/42222921/65661396-305dc280-e04f-11e9-99fa-100fa3c79c01.png)

**Comment by menakaj** [comment]
Fixed
