### ISSUE TITLE
[store] Applications can't search in the Application Page search bar.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5810]
In the Application page's search bar placeholder is texted as Search APIs and it has a drop down also. 
**Applications can't search using the search bar.**

![image](https://user-images.githubusercontent.com/40932779/65661988-bfb7a580-e050-11e9-8c86-4ff27b46eae1.png)

**Comment by chamilaadhi** [comment]
search bar is there to search apis (as mentioned in the placeholder text)
