### ISSUE TITLE
[Publisher] Users with publisher roles can demote and depricate APIs even when there are active subscriptions

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5811]
**Issue:**
Users with publisher roles can demote an API to created state or deprecate it even when there are active subscriptions to that API.

**Steps to reproduce the issue**

1. Subscribe to an API using the store.
2. Deprecate or demote the API using the API publisher.

**Comment by chamilaadhi** [comment]
That is the default behaviour. deprecate an API can be done with active subscription
