### ISSUE TITLE
Test case: 4.5.1.1 SDK generation and SDK download does not support some languages.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5819]
Description-:
Test case:
4.5.1.1- SDK generation and SDK download should be supported for language JAVA, ANDROID, SCALA,CSHARP,CPP,dart,flash,go,groovy,javascript,Jmeter,nodejs,perl,php,python,ruby,swift,clojure,aspnet5,asyncscala,spring,csharpdotnet12,haskell.

Result:
CPP, go, aspnet5, asyncscala, spring, haskell are missing.
![Screenshot from 2019-09-26 12-26-13](https://user-images.githubusercontent.com/54613992/65665782-f2b26700-e059-11e9-955b-7c6769c9b4e2.png)

**Comment by chamilaadhi** [comment]
You need to enable them. only default enabled stuff is shown.
