### ISSUE TITLE
[Store] Issue in the APIs page when logged in as a user after creating a new tenant

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5822]
Consider a scenario where a new tenant is created. When logged in as a user, https://localhost:9443/store-new/apis page should be the same as the page which is found when no user is logged in

This is the page found when logged in 

![loggedin](https://user-images.githubusercontent.com/30475839/65665949-44f38800-e05a-11e9-880a-18c1dcffeac4.png)

This is the page found when not logged in

![notloggedin](https://user-images.githubusercontent.com/30475839/65665348-f42f5f80-e058-11e9-919a-c0733f3b3a30.png)

**Comment by chamilaadhi** [comment]
Since there is two public stores now, user has to decide which store he needs to go to . that's why the UI in the second image is shown. If we show the super tenant's store every time, tenant users will have to go to that second page specifically again and then go to his store
