### ISSUE TITLE
APIM microgateway analytic documentation issue #DOCUMENTATION

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5825]
In the doc https://docs.wso2.com/display/MG301/Analytics+for+Microgateway in the section "Configuring the API-M Analytics Server", we are asked to Create the AM_USAGE_UPLOADED_FILES table in the WSO2AM_STATS_DB database. But it hasn't clearly mention where that WSO2AM_STATS_DB is located. Furthermore, there is a line stating "Make sure that you correctly configured the WSO2AM_STATS_DB between WSO2 API Manager and WSO2 API-M Analytics." But there is no WSO2AM_STATS_DB in the new WSO2 API Manager. So the reader may be little confused while reading this. And also it has not mentioned how to configure STATS_DB between these 2. 
![Screenshot from 2019-09-26 13-55-40](https://user-images.githubusercontent.com/51467737/65672730-20ea7380-e067-11e9-95e2-29e65a5df2d3.png)

**Comment by rmsamitha** [comment]
@ShanJayaweera Shall we move the issue to the appropriate repo; product-mgw?

**Comment by ShanJayaweera** [comment]
@rmsamitha Ok. I'll move the issue to product-mgw
