### ISSUE TITLE
[Publisher] In Endpoint page password field gets empty when saved.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5827]
![Screenshot from 2019-09-26 14-00-29](https://user-images.githubusercontent.com/31464477/65672312-6fe3d900-e066-11e9-8a4c-6379c3aaade1.png)
**Issue**
When saving the Endpoint page by selecting Endpoint security with username & password,password field gets emptied after saved.

**Comment by rmsamitha** [comment]
@menakaj Are you working on a similar issue ATM?

**Comment by menakaj** [comment]
Yes... I'm working on the fix
