### ISSUE TITLE
Different names are shown in multiple places for same option (throttling policies)

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5828]
Following 3 names are referred to the same option which confuses a new user.

- Business plan
- Throttling policy
- Subscription policy

![Screenshot from 2019-09-26 14-03-25](https://user-images.githubusercontent.com/36144069/65673135-e7663800-e067-11e9-92a2-0ea1f20ca848.png)
![Screenshot from 2019-09-26 14-04-23](https://user-images.githubusercontent.com/36144069/65673144-ecc38280-e067-11e9-8dce-ea337e83d47d.png)

**Comment by kavishkafernando** [comment]
Need to change this in the lifecycle page as well in the requirements checklist.
