### ISSUE TITLE
[Suggestion] Difficulty in adding business plan after creating an API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5831]
When creating an API, providing a business plan is not mandatory. But when publishing the API there is an error showing, if a business plan is not provided. But when we try to add the business plan after creating the API, it was hard to find the place to add the business plan. It would be a bit confusing for a fresh user when trying to publish an API.

**Comment by chamilaadhi** [comment]
business plan is under subscription tab. You could add it from there
<img width="850" alt="Screen Shot 2019-10-11 at 8 42 02 AM" src="https://user-images.githubusercontent.com/4861150/66621825-19989d80-ec03-11e9-86ca-34efc2e8aa32.png">
