### ISSUE TITLE
Micro gateway reset method is not documented #DOCUMENTATION

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5832]
when we import an API through Labels we need to add the username and password of the user. as I used the store in admin admin credentials I entered it. But if we import another API again it keeps that username in his memory and directly asks to add the password of the admin. So we need to use the command "micro-gw reset" if we want to add a different user name. But i was unable to find this scenario in the documentation of Micro gateway.
I have attached the cmd responses with this. 
![Screenshot from 2019-09-26 14-22-06](https://user-images.githubusercontent.com/51467737/65674437-2c8b6980-e06a-11e9-8002-a68704d5ae33.png)

**Comment by rmsamitha** [comment]
Closing since this should be fixed in product-mgw
