### ISSUE TITLE
[Error][Publisher]Attempts to add 20,000 characters in description

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#5835]
![Screenshot from 2019-09-26 14-28-46](https://user-images.githubusercontent.com/31029812/65674781-c3582600-e06a-11e9-96c4-a3fab8a35db1.png)

Test Case: An API creator attempts to create the REST API with more than 20000 characters for the description and publish the API

Error Encountered: After adding more than 20,0000 characters in the API description, the API overview page is changing like in the above-attached screenshot.

**Comment by vithu30** [comment]
This issue is not reproducible in the latest build pack.
