### ISSUE TITLE
Users with publisher role can view and delete documentation of an API

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#5836]
Users with publisher role can view and delete documentation of an API. Also, the "Edit Content" button is clickable and the following error will be in the terminal when saving the edited content.

![Screenshot from 2019-09-26 14-36-32](https://user-images.githubusercontent.com/35653110/65676020-cd7b2400-e06c-11e9-9317-4d98f11f0e9b.png)

**Comment by rmsamitha** [comment]
@TanyaM Did we fixed this?
