### ISSUE TITLE
Bronze, Silver, Gold tiers are not in order in API create page

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5838]
Bronze, Silver, Gold tiers are not in order in API create page. It should be Bronze<Silver<Gold

![Screenshot from 2019-09-26 14-57-17](https://user-images.githubusercontent.com/36144069/65677277-f1d80000-e06e-11e9-8777-82c0799769e9.png)

**Comment by chamilaadhi** [comment]
Order is based on the name and not based on the requests/min value
