### ISSUE TITLE
[Publisher] Overlapping error prompts when updating an API resource get failed

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5839]
![WSO2 APIM Publisher-new - Chromium_011](https://user-images.githubusercontent.com/27700915/65677932-154f7a80-e070-11e9-9b63-61635cf813f9.png)

**Steps to reproduce:** 

1. Log in to publisher using creator or publisher.
2. On resources page, select an resource.
3. Click on the security toggle.
4. Click save.

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7601
duplicate https://github.com/wso2/product-apim/issues/5764
