### ISSUE TITLE
[store] Self-Sign up not get disabled even the feature is turned off.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5843]
Can enable or disable the self sign-up option by following the below documentation.
[https://docs.wso2.com/display/AM250/Customizing+the+API+Store](url)
But sign up feature not get disabled even after the self signup option is disabled.

In the older version of the API manager it get disabled. But in the new version, still new user 
registration link appears.

### **Older version**
![image](https://user-images.githubusercontent.com/40932779/65740059-0ff03f80-e105-11e9-9474-8b6e9794849b.png)

### **New version**
![image](https://user-images.githubusercontent.com/40932779/65740091-357d4900-e105-11e9-8492-c529f488129f.png)

**Comment by chamilaadhi** [comment]
Add following to the deployment.toml to disable self signup

    [identity_mgt.endpoint]
    enable_self_signup_endpoint=false

**Comment by nrbw** [comment]
It still works for 4.0.0 ... but why is the documentation not up to date ?
https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/
