### ISSUE TITLE
Null Pointer Exception occurred during API runtime 

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5844]
A Null Pointer Exception was occurred regarding the API runtime error while mediating the message.

Screenshot:
![Screenshot from 2019-09-26 15-40-06](https://user-images.githubusercontent.com/38970634/65683749-b68ffe00-e07b-11e9-9f59-42dcaa40284d.png)

**Comment by chamilaadhi** [comment]
What was the mediation sequence you added here? Can you provide more information

**Comment by chamilaadhi** [comment]
It is working on 3.0.0 beta without any issue.
