### ISSUE TITLE
Failed to Fetch the API created and pulished by the Admin Tenant

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5845]
A "Failed to Fetch" Error was occurred while invoking the API, which I created and published under the role of the Admin Tenant. But, there was no error occurred while I created and published under the role of admin in Carbon super.

Screenshot relevant to Invoking an API under the role of Admin Tenant (admin of foo.com) -> when failed to fetch error occurred
![Screenshot from 2019-09-26 17-24-14](https://user-images.githubusercontent.com/38970634/65686598-c7903d80-e082-11e9-88e2-bc022741784e.png)

Screenshot relevant to invoking an API under the role of Admin in Carbon Super-> Invoking successful
![Screenshot from 2019-09-26 17-22-51](https://user-images.githubusercontent.com/38970634/65686624-e7bffc80-e082-11e9-845b-8ac75806e3c3.png)

**Comment by bhathiya** [comment]
Is this happening not because of self-signed certificate?

**Comment by Krishanx92** [comment]
> Is this happening not because of self-signed certificate?

It should be. I could not reproduce this in latest pack.
https://localhost:9443/devportal/apis/7b5801f5-75f6-4788-8d1e-2d1c74f8f5d7/test?tenant=abc.com

![image](https://user-images.githubusercontent.com/8374895/66893401-87670f80-efdd-11e9-8437-8a8ee8897f22.png)
![image](https://user-images.githubusercontent.com/8374895/66893415-90f07780-efdd-11e9-9704-6f6df465f182.png)
