### ISSUE TITLE
Bug when "Requires re-subscription when publish the API"

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5847]
**Description:**
When demoting a published API to "create stage"  and the publishing the API again with the check box ticked name "Requires re-subscription when publish the API" subscribers doesn't need to subscribe to the API again.

**How to reproduce:**

1. Create a new version of API
2. Publish the API
3. Demote to created stage
4. Publish the API again while cheeking the check box option "requires re-subscription"

![Screenshot from 2019-09-26 14-26-40](https://user-images.githubusercontent.com/42222921/65687293-c4974c00-e086-11e9-8340-d8e2dcc570f4.png)
![Screenshot from 2019-09-26 17-45-14](https://user-images.githubusercontent.com/42222921/65687300-c5c87900-e086-11e9-89dc-2fac91a2aea4.png)
![Screenshot from 2019-09-26 17-45-32](https://user-images.githubusercontent.com/42222921/65687303-c7923c80-e086-11e9-80dc-b4b48d77da3e.png)
![Screenshot from 2019-09-26 17-45-43](https://user-images.githubusercontent.com/42222921/65687308-c8c36980-e086-11e9-996c-5051ea9aef46.png)

**Comment by chamilaadhi** [comment]
'Requires re-subscription when publish the API' button is there for the newly created version of the same api.
