### ISSUE TITLE
Application created with space separated name unable to generate keys

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#5849]
Application can be created with a space separated name, but it cannot generate keys.
Once the name is modified without any spaces, it prompts to clear the partially created keys and re-generate the keys.

![Screenshot from 2019-09-26 17-51-41](https://user-images.githubusercontent.com/54226167/65687543-2c4d9700-e087-11e9-9f4b-625aad0da6de.png)

![Screenshot from 2019-09-26 17-58-58](https://user-images.githubusercontent.com/54226167/65687719-746cb980-e087-11e9-8cf1-1507f8d94207.png)

**Comment by dushansilva** [comment]
Hi all, 
This is issue is occurring due IS not supporting to create an SP with spaces in its name now (which was not the case earlier) . we are discussing this with IAM team
