### ISSUE TITLE
[store] Application deletion cannot confirm.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5852]
When shared application is enabled the user who created the application can delete it.
But it doesn't provide confirmation message box. Due to this if it accidentally clicked, it will be deleted and there is no mentioning  about other users' application usage. 
Others who are using the application also cannot use it due to this.

Better if there is a confirmation message box. (Accidental app deletions can avoid due to this.)

**Comment by dushansilva** [comment]
Duplicate issue
https://github.com/wso2/product-apim/issues/5723
