### ISSUE TITLE
Issued jwt is already expired and accepted by the gateway

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim#5855]
I got a token from APIM developer portal. It has following exp and iat values.

 "exp": 1569504000,
  "iat": 1569504000,

But when submitted to gateway it successfully validates the token. 

affected version : 3.0.0-alpha

**Comment by rmsamitha** [comment]
@fazlan-nazeem 
Can we close this now?

**Comment by fazlan-nazeem** [comment]
Isn't seem to reproducible in the latest pack. @Rajith90 can you please check?

**Comment by tharindu1st** [comment]
This was not reproduced in 3.1.0
