### ISSUE TITLE
Error in Quota Allocation of a Republished API 

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5857]
Use Case: Help the subscribers to evenly distribute the allocated quota among application users
Test Scenario : Edt already set subscription policy to limit the max requests per time within the allocated subscription policy plan,
- where subscription plan has already used in subscription (subscribed to API) , 
- and now publisher re-publish the API
 burst control limit <= allocated plan
Should change the subscription qouta for already subscribed APIi

Details of the Issue: When I changed the quota of the Silver Subscription tier from 10 per minute to 5 per minute and re-published the currently published API and Invoked it, 6 requests were allowed per minute.

Screenshot:
![Screenshot from 2019-09-26 18-54-18](https://user-images.githubusercontent.com/38970634/65693601-32954080-e092-11e9-8b51-bb21a59fb228.png)

**Comment by rmsamitha** [comment]
Will need to test whether the invocation is restricted at some point at least, after the republishing.

**Comment by chathuranga95** [comment]
This issue is fixed in the latest product version.
