### ISSUE TITLE
After creating API as SOAP or GraphQL, endpoints page has missing items

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5864]
Items to set endpoint security and select endpoint type are missing. 
Also after adding soap endpoint using wsdl file endpoints page displays endpoint types again.

![Screenshot from 2019-09-26 19-54-09](https://user-images.githubusercontent.com/36144069/65696756-72125b80-e097-11e9-986a-4c033ebd1fa2.png)

**Comment by malinthaprasan** [comment]
Looks like page is rendered as 'WS' type API. We need to get the normal endpoint page for HTTP, SOAP, SOAPTOREST and GRAPHQL types too.
