### ISSUE TITLE
Bug when tries to make changes to published API

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5871]
Test Scenario:

After API is Published, ensure a user with publish permission can do modifications to:

Transports
Subscription tiers
Subscription availability

Description:

When an user with internal/Publisher permissions are unable to change to Transports of the API when published

![Screenshot from 2019-09-26 21-47-00](https://user-images.githubusercontent.com/42222921/65706133-6f1f6700-e0a7-11e9-9d13-d278de48d834.png)

**Comment by rmsamitha** [comment]
Addressed in https://github.com/wso2/product-apim/issues/6032.
And publisher is not allowed to update transport info.
