### ISSUE TITLE
Problem when updating the Gateway environments for a published APIs

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5873]
I have got 3 different gateway environments. When we add one Gateway environment and publish the API by the Publisher, it is visible under Available Environments in the store . 

![Screenshot from 2019-09-26 21-28-47](https://user-images.githubusercontent.com/51467737/65705500-3468ff00-e0a6-11e9-97d7-73a349043d50.png)
![Screenshot from 2019-09-26 21-29-02](https://user-images.githubusercontent.com/51467737/65705534-49459280-e0a6-11e9-9891-ff29abfc832b.png)

Think of a situation where we want to add different gateway environment while the api is published. for the 1st change it is changing the store with the correct environment

![Screenshot from 2019-09-26 21-29-16](https://user-images.githubusercontent.com/51467737/65705854-d7217d80-e0a6-11e9-85f3-97b9f021ec92.png)
![Screenshot from 2019-09-26 21-29-24](https://user-images.githubusercontent.com/51467737/65705860-db4d9b00-e0a6-11e9-810c-f36a250e90df.png)
 
But if we change it again it wont allow to change. In the  APIM Store also it shows nothing under Available Environment.
![Screenshot from 2019-09-26 21-29-31](https://user-images.githubusercontent.com/51467737/65706417-143a3f80-e0a8-11e9-884d-98bc81978e43.png)
![Screenshot from 2019-09-26 21-30-03](https://user-images.githubusercontent.com/51467737/65706426-1bf9e400-e0a8-11e9-937d-5498af5805e9.png)

**Comment by chamilaadhi** [comment]
Tried this with 3.0.0 beta and couldn't observe any issue. I think there could be a misconfiguration in the gateway endpoint configuration in your deployment.toml file
