### ISSUE TITLE
[Store] Test case: 4.8.1.5: To new application developer, it allows to input a password that consists of characters less than 6 and more than 30 during the signup.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5874]
Description-:
Test case:
4.8.1.5- [N] No body should be allowed to input a password that consists of characters less than 6 or more than 30 during the signup.

Result:
It allows to input a password that consists of characters less than 6 and more than 30 during the signup.

**Comment by rmsamitha** [comment]
Cannot reproduce now
