### ISSUE TITLE
[Store] UI issue in response download button

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5875]
![Screenshot from 2019-09-26 17-35-54](https://user-images.githubusercontent.com/31464477/65742511-20f17e80-e10e-11e9-9c8c-8216bd6f3dd1.png)
**Issue**
In download button,button text is out of button field.

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="1146" alt="Screen Shot 2019-10-11 at 12 05 22 PM" src="https://user-images.githubusercontent.com/4861150/66629488-8326a500-ec1f-11e9-9da0-f73a48527e3c.png">
