### ISSUE TITLE
[store] Application search bar text deletion 

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5882]
Application / API search bar text get deleted when applications are switched or
another application is clicked.

### **Before switching application**
![image](https://user-images.githubusercontent.com/40932779/65744406-e25fc200-e115-11e9-959d-9f33691de5ee.png)

### **Typed text not available after switching applications.**
![image](https://user-images.githubusercontent.com/40932779/65744579-674adb80-e116-11e9-9e54-76aa3ac6a583.png)

**Comment by prasa7** [comment]
Fixed in 3.x.x
