### ISSUE TITLE
[Publisher] Issue when adding or deleting multiple scopes

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#5883]
Steps 01:
1. Add a new scope for an API from the publisher. Click on the save button.
2. Add another scope for the same API without refreshing the page.
3. Add more scopes or refresh the page.

Steps 02:
1. Delete a scope for an API from the publisher.
2. Delete another scope for the same API without refreshing the page.
3. Delete more scopes or refresh the page.

Issue:
Only the last scope will be affected (created or deleted).

**Comment by ruks** [comment]
This is due to a refreshing issue same as https://github.com/wso2/product-apim/issues/5659. This is already fixed.
