### ISSUE TITLE
[Store] Test case: 4.8.1.6: To new application developer, it allows to input a password that does not consist of numbers

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5884]
Description-:
Test case:
4.8.1.6- [N] No body should be allowed to input a password that does not consist any numbers during the signup
Result:
It allows to input a password which is not consist of numbers.

**Comment by rmsamitha** [comment]
@tharikaGitHub 
Do we have this condition now?
And shall we add a label displaying the password conditions?

**Comment by tharikaGitHub** [comment]
@rmsamitha No this condition is not there now. We are using the self registration form of Identity server for this purpose. And we are checking the condition that the Password length should be within 5 to 30 characters only.  Hence closing.
