### ISSUE TITLE
Copy - Paste working in a wrong mannner in Swagger tools

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5885]
**Description**

- Tried to paste something in the swagger definition in swagger tool. But it always pastes at the top of the file despite of where we clicked

**Comment by chamilaadhi** [comment]
Related issues https://github.com/wso2/product-apim/issues/5997, https://github.com/wso2/product-apim/issues/5885

**Comment by chamilaadhi** [comment]
duplicate of https://github.com/wso2/product-apim/issues/5997
