### ISSUE TITLE
[store] Error in the Store UI

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5887]
When signing in the store, even without providing the admin-admin credentials I was automatically logged in as Carbon super Admin.

Screenshot:
![Screenshot from 2019-09-27 11-15-13](https://user-images.githubusercontent.com/38970634/65745197-86e30380-e118-11e9-9347-1def5f349eeb.png)

**Comment by chamilaadhi** [comment]
Were you logged in to the publisher app on the same browser? This is the behavior of SSO
