### ISSUE TITLE
[Store] Test case: 4.8.1.7: To new application developer, it allows to input a password that does not consist of any special character

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5888]
Description-:
Test case:
4.8.1.7- [N] No body should be allowed to input a password that does not consist any special characters during the signup
Result:
It allows to input a password without any special characters.

**Comment by vithu30** [comment]
Password policy is configurable. The default password policy configured in 3.1.0 is `^[\S]{5,30}$`. Hence, if user wants to force special characters they can modify it using following configuration in deployment.toml:
```
[user_store]
properties.PasswordJavaScriptRegEx = $password-regex
properties.PasswordJavaRegEx = $password-regex
```
