### ISSUE TITLE
[Store] Test case: 4.8.1.9: To new application developer, it allows to input a user name with more than 30 characters.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5889]
Description-:
Test case:
4.8.1.9- [N] No body should be allowed to input a username that has characters more than 30 during the signup.

Result:
It allows to create a user name with more than 30 characters.

**Comment by kavishkafernando** [comment]
Username has been validated.
<img width="1058" alt="Screen Shot 2019-10-14 at 4 55 25 PM" src="https://user-images.githubusercontent.com/19324135/66747941-74e8bb00-eea3-11e9-97d1-712fec2bb9d4.png">
