### ISSUE TITLE
API description is not updated in api definition

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5890]
![Screenshot from 2019-09-27 11-33-07](https://user-images.githubusercontent.com/36144069/65745832-a11de100-e11a-11e9-91c6-93956e3639fc.png)

![Screenshot from 2019-09-27 11-33-15](https://user-images.githubusercontent.com/36144069/65745834-a5e29500-e11a-11e9-8204-bdf6909aec36.png)

**Comment by chamilaadhi** [comment]
fixed
