### ISSUE TITLE
[Publisher] Console log error when selecting Endpoint security as digest auth & when sending a request

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5891]
![Screenshot from 2019-09-27 11-15-41](https://user-images.githubusercontent.com/31464477/65745188-834f7c80-e118-11e9-9250-dcbaf54f6d63.png)
![Screenshot from 2019-09-27 11-14-44](https://user-images.githubusercontent.com/31464477/65745191-85194000-e118-11e9-87c0-846fdaf27e96.png)
**Issue**
In Endpoint page by selecting Endpoint Security type as digest auth & sending a request it gets an error in console as " ERROR - DigestAuthMediator The endpoint does not support digest authentication : null
java.lang.NullPointerException: null ".
.

**Comment by chamilaadhi** [comment]
Reason for this error is that you are trying to invoking a backend that does not support Digest Authentication. If backend supports Digest Authentication, it sends WWW-Authenticate header with 401 which is used to continue the flow

**Comment by accountnujen** [comment]
> Reason for this error is that you are trying to invoking a backend that does not support Digest Authentication. If backend supports Digest Authentication, it sends WWW-Authenticate header with 401 which is used to continue the flow

and then what do I have to do to make the digest supported?
