### ISSUE TITLE
[Admin Portal] Improvement Needed in filters of Subscription Policy Manage Page

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5893]
In my opinion, I think the Filters in Subscription Policy Manage Page can be improved, in a way which it detects the the Letters at the initial typing. At the moment it only filters when it detects the difference of the character typed. It will be feasible for the user if the filters worked more efficiently.

Screenshots:
![Screenshot from 2019-09-27 11-30-46](https://user-images.githubusercontent.com/38970634/65745944-01148780-e11b-11e9-956a-c36bd668a437.png)

![Screenshot from 2019-09-27 11-31-07](https://user-images.githubusercontent.com/38970634/65745947-0376e180-e11b-11e9-92a7-f69436a9e03d.png)

![Screenshot from 2019-09-27 11-31-14](https://user-images.githubusercontent.com/38970634/65745954-05d93b80-e11b-11e9-8a83-2d5666037300.png)

**Comment by chamilaadhi** [comment]
It is bit unclear what improvement is needed because Current filter works well and it does the required job (filtering). Hence we will keep it  as it is
