### ISSUE TITLE
Publisher user doesn't get notified of an error when trying to create SOAP, GRAPHQL, SWAGGER APIs

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5894]
When a user with the role of an "Internal/publisher" is logged in to the publisher, that user normally has no authority to create an API. This is shown through an alert message when trying to create a REST API as shown in the below screenshot.

![11](https://user-images.githubusercontent.com/30475839/65745314-f0631200-e118-11e9-9315-867d6899cb78.png)

But when trying to create an API where there is an option to drag and drop a file, the user is not clearly notified of the error in the UI, but the error is logged in the console.

When importing a SWAGGER definition from a file, the user is not notified of the proper error message in the UI although the action is blocked. Screenshot of the UI after the blocked action is given below along with the logs in the console. In order to maintain the consistency between the UIs, it is better to have an alert message as shown in the above screenshot.

![22](https://user-images.githubusercontent.com/30475839/65745581-c5c58900-e119-11e9-8226-1a57a9a9ae42.png)

![Screenshot from 2019-09-27 11-25-41](https://user-images.githubusercontent.com/30475839/65745531-a4649d00-e119-11e9-9762-ba13eafdd377.png)

When trying to create an API by importing a WSDL file, similar behavior can be observed as shown below. But here there is no indication of any error to the user, although a similar error is logged in the console and it needs to be handled (drag and drop area won't even get a red border like in the above scenario).

![33](https://user-images.githubusercontent.com/30475839/65745953-0540a500-e11b-11e9-9b27-1d2b682d3a23.png)

When trying to create an API using a GRAPHQL SDL schema, a similar behavior can be observed.

![44](https://user-images.githubusercontent.com/30475839/65746102-7e3ffc80-e11b-11e9-9fec-aa87f39b79dc.png)

**Comment by chamilaadhi** [comment]
Creating API needs to be blocked for publisher user

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7453
