### ISSUE TITLE
Error/Bug Email validators are not working in Business information page

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5895]
Description:

When adding business information  in the email fields users can add values which are not compatible with type e-mail 
![Screenshot from 2019-09-27 11-55-21](https://user-images.githubusercontent.com/42222921/65747239-8fd6d380-e11e-11e9-927e-00f596cb6eb1.png)

**Comment by chamilaadhi** [comment]
Reported issue is fixed in beta.
