### ISSUE TITLE
[Publisher] Issue in the API Create Page Error Message Display when trying to create an API, while logged in as Publisher

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5896]
Issue was encountered when I tried to create an API as a publisher of tenant. The error message wasn't displayed at once. For several minutes the functionality seemed to be stuck.

Screenshot:
![Screenshot from 2019-09-27 11-52-32](https://user-images.githubusercontent.com/38970634/65747512-40dd6e00-e11f-11e9-823c-4a427631015a.png)

**Comment by chamilaadhi** [comment]
Create API function shouldn't be provided for a publisher user

**Comment by chamilaadhi** [comment]
API Creation is disabled for publisher https://github.com/wso2/carbon-apimgt/pull/7361
