### ISSUE TITLE
When creating REST APi using SOAP endpoint, get "Cannot access referenced schema for the schema defined at: " + schemaUrl" warn if not having the "schemaLocation" as an attribute

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#5897]
**Steps for reproducing**:

1. Used this wsdl[1] and generated the REST api 
2. Then print the warn as follows.

**WARN {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor} -  Cannot access referenced schema for the schema defined at: http://schemas.xmlsoap.org/soap/encoding/ {org.wso2.carbon.apimgt.impl.soaptorest.WSDL11SOAPOperationExtractor}**

**Debug result**:
referenced schema become null and print the warn. Reason is schemaLocation become null and unable to find that through the namespace value.
```
Schema referencedSchema = ((SchemaImport) schemaVector).getReferencedSchema();
if (referencedSchema != null && referencedSchema.getElement() != null) {
    if (referencedSchema.getElement().hasChildNodes()) {
        schemaNodeList.addAll(SOAPOperationBindingUtils
                .list(referencedSchema.getElement().getChildNodes()));
    } else {
        log.warn(
                "The referenced schema : " + schemaUrl + " doesn't have any defined types");
    }
} else {
    log.warn("Cannot access referenced schema for the schema defined at: " + schemaUrl);
}  
```
In this case, only the WSDL namespace will be populated in the schemaVector object since there's no defined schemaLocation in the import. We might need to investigate if there's a way to get the referenced schema only using WSDL namespace in wsdl4j library.

**Workaround**: 

If set the "schemaLocation" in the WSDL as an attribute like below, can overcome this issue.

```
<s:schema targetNamespace="http://ws.cdyne.com/PhoneVerify/query/AbstractTypes">
      <s:import namespace="http://schemas.xmlsoap.org/soap/encoding/" schemaLocation="http://schemas.xmlsoap.org/soap/encoding/"/>
      <s:complexType name="StringArray">
```

**Action Item**: 

Need to check this behaviour further and identify a mechanism to get the schema when only configured the namespace on WSDL.
 
[1]. http://ws.cdyne.com/phoneverify/phoneverify.asmx?wsdl

**Comment by rmsamitha** [comment]
@nadeepoornima In which version, is this reproduced?
Please add or suggest appropriate labels (issue type, priority, etc.) to the issues when you create them.

**Comment by nadeepoornima** [comment]
Hi Samitha,

It is reproducing in APIM 2.6.0. Please not we don’t have put labels or set
priority permission. If possible please add them.

Thanks,
Nadee

**Comment by malinthaprasan** [comment]
Tag

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by vithu30** [comment]
This is reproducible in 3.1.0 as well
