### ISSUE TITLE
[Store] UI issue when interchanging from Applications to APIs

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5898]
![Screenshot from 2019-09-27 12-03-40](https://user-images.githubusercontent.com/31464477/65747529-505cb700-e11f-11e9-9123-2e67aa1a31b6.png)
![Screenshot from 2019-09-27 12-03-46](https://user-images.githubusercontent.com/31464477/65747553-5eaad300-e11f-11e9-98cd-52204041eaec.png)
**Issue**
When interchanging from Applications to APIs it appears a window "Sorry,no matching records found" in between Applications & APIs for a very small time.
![Screenshot from 2019-09-27 12-02-14](https://user-images.githubusercontent.com/31464477/65747875-340d4a00-e120-11e9-9de6-7e9a29b8176d.png)

**Comment by dushansilva** [comment]
closing this Issue seems to fixed in latest APIM pack
