### ISSUE TITLE
Error/Bug when creating an API product

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5901]
Description:

A user with internal/Creator level permission is enable to  browse the "API products" tab even though API-Creators has no permission to create  API-Products when the user enters the  API products tab   he is shown the APIs not the API products

Following logs in the console:
[2019-09-27 12:27:06,334] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
[2019-09-27 12:27:07,120] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed

**Comment by chamilaadhi** [comment]
Creator cannot access the API product in the latest build
![Screen Shot 2019-10-07 at 5 17 36 PM](https://user-images.githubusercontent.com/4861150/66309144-7c014d80-e926-11e9-815c-b82dad1f31fb.png)
