### ISSUE TITLE
[Publisher] Issue when trying to import a new schema for a GRAPHQL API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5903]
Consider a scenario where there are existing APIs in the API Manager Publisher. When navigating to the APIs tab and then the "API DEFINITION" section of a REST API, we can successfully import a new swagger definition. But when trying to do the same for a GRAPHQL API, an error was encountered. The screenshot given below is the error which was logged in the browser console.

![111](https://user-images.githubusercontent.com/30475839/65748744-3c668480-e122-11e9-9d14-507c58fa7215.png)

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
