### ISSUE TITLE
[Store] Automatically signing-in as a tenant even without signing-in

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5904]
When I logged out as Carbon super Admin and tried to log in as another user, I was automatically logged in as tenant2, which in the Publisher I have currently logged in as tenant2 ( tenant2 was provided with publisher role. )

![Screenshot from 2019-09-27 12-24-14](https://user-images.githubusercontent.com/38970634/65748948-b5fe7280-e122-11e9-8993-cce93ccc75a3.png)

**Comment by chamilaadhi** [comment]
This is the default behaviour (Single Sign On)
