### ISSUE TITLE
[Publisher] Can publish and subscribe API by selecting Endpoint Security as basic auth without auth credentials

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5907]
![Screenshot from 2019-09-27 12-37-54](https://user-images.githubusercontent.com/31464477/65749487-c3682c80-e123-11e9-9208-d8156043b26a.png)
![Screenshot from 2019-09-27 12-36-31](https://user-images.githubusercontent.com/31464477/65749514-d3800c00-e123-11e9-8dc9-80ed17f262cd.png)
![Screenshot from 2019-09-27 12-35-24](https://user-images.githubusercontent.com/31464477/65749528-d844c000-e123-11e9-9eb6-68f07e810eb6.png)
**Issue**
Can publish and subscribe an API successfully by selecting Endpoint security in Endpoint page as basic auth without auth credentials.

**Comment by chamilaadhi** [comment]
similar issue https://github.com/wso2/product-apim/issues/5910
