### ISSUE TITLE
[Store] Test case: 4.8.4:  Application Developper is not allowed to reset password.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#5909]
Description-:
Test case: 4.8.4: Application developers should be allowed to reset password in case they forgot it.

Result:
When click the forgot password, it does not direct to change password. It shows like this.
![Screenshot from 2019-09-27 12-36-11](https://user-images.githubusercontent.com/54613992/65749474-c19e6900-e123-11e9-8e01-cde7a0b7b593.png)

**Comment by sanjulamadurapperuma** [comment]
Observed that this issue persists when trying to reset the username as well.
