### ISSUE TITLE
API Availability Analytics Not Shown

### ISSUE THREAD

**Issue by thiloshon** [wso2/product-apim#5917]
In the API Availability tab of the admin portal in api manager we get no data to be shown when email is used as username.

**Comment by thiloshon** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/1646

**Comment by rmsamitha** [comment]
@thiloshon Is this fixed in the public branch? If yes, please refer the PR and close this issue.

**Comment by kavishkafernando** [comment]
Public commit: #https://github.com/wso2/carbon-apimgt/commit/8a3ddd453eb0f3718b7a76edd4f769f524420d62
