### ISSUE TITLE
API creator is not able to update the visibility of a published API

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5918]
**Description**

- The above problem appears when a creator tried to update the visibility of a published API. The fields are not editable for the creator. 

![Screenshot from 2019-09-27 15-06-36](https://user-images.githubusercontent.com/44407066/65759421-822e4780-e138-11e9-8478-63ae42ad6afa.png)

**Comment by chamilaadhi** [comment]
Creator cannot modifiy content of an API if it is in published state.
