### ISSUE TITLE
Bug in the API Developer Portal list view

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5934]
Description:

When clicking on the sorting arrows list doesn't get sorted
![Screenshot from 2019-09-27 17-29-51](https://user-images.githubusercontent.com/42222921/65767850-bc094900-e14c-11e9-8690-550389c9fac8.png)

**Comment by Arshardh** [comment]
We cannot supporting sorting at the moment because the backend does not support it at the moment. 
Therefore we will be removing sorting for the remaining 2 columns.
I have created this issue to track this: https://github.com/wso2/product-apim/issues/6503
