### ISSUE TITLE
Subscription policy accepts more than the defined no.of requests for 2 users

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#5935]
Test case [7.1.4.4] - When two users (user1 & user2) subscribed to same application, 
the total number of requests from both users(sum) in given time should be equal/less to the defined #Request per Time.

Following is a table representing the results of testing the no.of requests accepted from applications subscribed with different subscription tiers in jmeter.

| Subscription Tier  | Defined Requests | Requests Accepted |
| ------------- | ------------- | ------------- | 
| Bronze  | 1000  | 1020  |
| Silver  | 2000  | 2374  |
| Gold  | 5000  | 9745  |

**Comment by chamilaadhi** [comment]
We cannot get 100% accuracy for the high TPS scenario
