### ISSUE TITLE
[store] Access token generation button not get disabled.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#5936]
When IWA-NTLM grant type is selected without any other grant type, access token generation button get disabled in the old version. 
But in the new version it doesn't get disabled and users allowed to open generate access token 
pop up window. But nothing generates after that

**Regenerate button get disabled in the old version** (When only the IWA-NTLM is selected).

![image](https://user-images.githubusercontent.com/40932779/65768271-2373c880-e14e-11e9-9f51-b66f7b9fcfb8.png)

**Access token generation button not get disabled in the new version**.

![image](https://user-images.githubusercontent.com/40932779/65768482-b3197700-e14e-11e9-9c6e-3b20ffd96a3a.png)
![image](https://user-images.githubusercontent.com/40932779/65768512-c9bfce00-e14e-11e9-96a3-29a211413c7a.png)

**Comment by 7slcode7** [comment]
Generate access token button not get disabled if Client Credentials is not selected. But older version of the APIM disables it when user not marked the Client Credentials.

**Comment by kavishkafernando** [comment]
This has been fixed in the latest pack
<img width="1523" alt="Screen Shot 2019-10-16 at 12 04 21 PM" src="https://user-images.githubusercontent.com/19324135/66894070-2a834d80-f00d-11e9-9960-cccece19453b.png">
