### ISSUE TITLE
Flicker subscriptions page content in Publisher SPA api details page

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#5939]
The content of the api details resource page get change after receiving the content, should have used a loader there.
![image](https://github.com/tmkasun/images/blob/master/with_nt_throttle.gif?raw=true)

## this is clearly visible when network throttling is applied 

![img](https://github.com/tmkasun/images/blob/master/default.gif?raw=true)

**Comment by bhathiya** [comment]
There is a flicker in search as well. 

Is @ruwiniwj working on this?

**Comment by ruwiniwj** [comment]
@bhathiya, no I'm working on analytics. Shall we assign it to someone else?

**Comment by bhathiya** [comment]
@AmaliMatharaarachchi can you check this?

**Comment by AmaliMatharaarachchi** [comment]
@bhathiya Sure. I will work on this.
