### ISSUE TITLE
[Publisher] "Duplicate document name" wrong error message

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#5942]
- Create a new doc via publisher
- The given name is not added, but it displays as "Duplicate document name"

<img width="956" alt="Screen Shot 2019-09-27 at 11 30 44 AM" src="https://user-images.githubusercontent.com/3397321/65793295-569c6480-e11a-11e9-9f63-bc19346555c5.png">

**Comment by vanjikumaran** [comment]
added tag for the tittle

**Comment by AmaliMatharaarachchi** [comment]
duplicate issue - https://github.com/wso2/product-apim/issues/5688
It's fixed now.
