### ISSUE TITLE
[Publisher] API product in "Created" lifeCycle is displayed as published API in store

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#5943]
API product created in the publisher is not in published status but in created status

<img width="852" alt="Screen Shot 2019-09-27 at 11 35 07 AM" src="https://user-images.githubusercontent.com/3397321/65793551-f823b600-e11a-11e9-9107-924d4cb89051.png">

However it is displaed in the API Store

<img width="852" alt="Screen Shot 2019-09-27 at 11 35 37 AM" src="https://user-images.githubusercontent.com/3397321/65793553-fa861000-e11a-11e9-9c5c-7a077924aedb.png">

**Comment by uvindra** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7262
