### ISSUE TITLE
[Publisher] MEDIATION POLICIES is not displaying anything in the API products

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#5944]
<img width="877" alt="Screen Shot 2019-09-27 at 11 37 59 AM" src="https://user-images.githubusercontent.com/3397321/65793761-71bba400-e11b-11e9-8df6-c3a7cdd78bf3.png">

**Comment by uvindra** [comment]
Note that for API Products, we do not support specifying mediation policies directly. Therefore we need to remove this from the API Product side panel in the publisher UI.

However, if the underlying API that a given resource belongs to contains mediation policies, then these will get associated with the API Product automatically at synapse level. So the API Product will enforce the same mediation policies that apply to its resources which are specified at the API level.

**Comment by vanjikumaran** [comment]
@uvindra , In that case,  Please remove the UI visibility of this button would help users to not to get confused.

**Comment by HiranyaKavishani** [comment]
It has been removed in beta pack
