### ISSUE TITLE
[Publisher] Scope is not getting added in the API products

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#5945]
<img width="877" alt="Screen Shot 2019-09-27 at 11 41 33 AM" src="https://user-images.githubusercontent.com/3397321/65794151-6321bc80-e11c-11e9-9d17-e1e7b36dd111.png">

<img width="877" alt="Screen Shot 2019-09-27 at 11 44 04 AM" src="https://user-images.githubusercontent.com/3397321/65794227-88aec600-e11c-11e9-8d0e-1766091541a2.png">

**Comment by HiranyaKavishani** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7224
