### ISSUE TITLE
Scopes cannot be added when generating application credentials

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#5946]
**Steps to reproduce**
Create and publish API in publisher. Add a scope.
Go to devportal and create an application
Try generate key with scope. but scope is not listed to add.

**version**
3.0.0

**Comment by chamilaadhi** [comment]
Scope only gets displayed when that application is used to subscribe to that API. 

![Screen Shot 2019-10-07 at 3 46 13 PM](https://user-images.githubusercontent.com/4861150/66303873-9ed93500-e919-11e9-8ec7-d15e41263a4f.png)
