### ISSUE TITLE
Issue in editing the Name of API Level Throttling Policies

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5953]
Use Case: API administrator should be able to Add/Edit API level throttling and Resource level throttling by defining an advanced throttling tier

Details of the Issue: When I logged in as the admin of a tenant, in the admin portal I was unable to edit the name of the API Level Advanced Throttling Policies.

Screenshot:
![Screenshot from 2019-09-28 15-05-57](https://user-images.githubusercontent.com/38970634/65814635-23cd9b80-e202-11e9-84ee-4582701ab7b1.png)

**Comment by chamilaadhi** [comment]
Editing the Policy name is not supported.
