### ISSUE TITLE
[APIM 3.0.0] HTTP verb drop down remove colors

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5960]
In the resources tab, can we remove colors in the HTTP verb drop down? 
![Screenshot from 2019-09-29 03-47-40](https://user-images.githubusercontent.com/7173347/65823039-5d3af100-e26c-11e9-8002-5a1b094275c0.png)

**Comment by rmsamitha** [comment]
To stay consistent with Swagger UI we may keep these colors.
