### ISSUE TITLE
[APIM 3.0.0] [Intermittent] Scope created without a role does not get created

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5961]
Creating a scope without a role, shows the UI message that the scope is created successfully. However, the scope is not listed, even after refreshing. Happens intermittently. 
![Screenshot from 2019-09-29 03-54-56](https://user-images.githubusercontent.com/7173347/65823091-4648ce80-e26d-11e9-85e0-ca59451e3ddf.png)

**Comment by kavishkafernando** [comment]
Fixed in latest pack.
