### ISSUE TITLE
[APIM 3.0.0] API Product synapse files are not getting deleted upon API Product delete

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#5963]
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java#L6783 this part is yet to be implemented.

**Comment by dushaniw** [comment]
This is fixed and cannot be reproduced in latest 3.1.0-alpha. Hence, closing the issue.
