### ISSUE TITLE
Improvement on consistency of notifications

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#5964]
The success notification messages are displayed with different colors and design in publisher and store, while other components remains consistent throughout the site. Preferred to have similar design for each notifications.

![Screenshot from 2019-09-29 17-45-26](https://user-images.githubusercontent.com/54226167/65833157-a467c700-e2ea-11e9-99e3-68c3cc814e00.png)
![Screenshot from 2019-09-29 17-50-07](https://user-images.githubusercontent.com/54226167/65833160-a92c7b00-e2ea-11e9-8d26-6c96c069ee13.png)

**Comment by chanaka3d** [comment]
The alert messages suppose to give prominence over the general UI components. Hence it's by design ( Material UI ) is displaying these messages in different colors ( error - red , info - blue etc.. )
