### ISSUE TITLE
[Publisher] Satus of the API does not change after a creator change it to prototyped status

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5969]
When a user with creator role changes the API status to prototyped and save, at the endpoints page, a message is shown that the API is updated successfully. But at the overview page, it still displays that the API is in 'CREATED' state.

![image](https://user-images.githubusercontent.com/47671237/65849661-0ebf4c80-e369-11e9-8d29-6493a314f2a9.png)

![image](https://user-images.githubusercontent.com/47671237/65849780-a1f88200-e369-11e9-9fe9-1e5c087e75b9.png)

**Comment by chamilaadhi** [comment]
User with a publish role needs to change the Lifecycle to 'Prototype' for this api to become a prototyped api. untill then it is in created state
