### ISSUE TITLE
[Publisher] Field alignment error when entering a long text for the summary of a resource

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5974]
![image](https://user-images.githubusercontent.com/47671237/65851327-2d751180-e370-11e9-93df-775451486e94.png)

When providing the summary for a resource at the publisher, if a very long text is given, the field alignment changes as follows: 
![image](https://user-images.githubusercontent.com/47671237/65851359-47aeef80-e370-11e9-901c-adb96501624d.png)

**Comment by chamilaadhi** [comment]
Seem fixed in AM 3.0.0 beta
<img width="1206" alt="Screen Shot 2019-10-12 at 11 46 44 AM" src="https://user-images.githubusercontent.com/4861150/66696056-0f9b9b00-ece6-11e9-911a-3987a8436670.png">
