### ISSUE TITLE
[improvement] There is no back option when subscribing

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#5975]
In the dev portal when we go to the Credentials section and try to Subscribe to a new app, we can make a new app to subscribe by filling the necessary criteria. Think of a situation where I accidentally click next button without setting the Token type to OAuth2. Although it was JWT by default I wanted to use Oauth2 as the Token type. But we don't have an option there to go back and edit it. I hope it is better to have that back option allowing people to go back and edit.

![Screenshot from 2019-09-30 10-50-11](https://user-images.githubusercontent.com/51467737/65851660-5ba72100-e371-11e9-9194-08a54764e984.png)

![Screenshot from 2019-09-30 10-50-18](https://user-images.githubusercontent.com/51467737/65851787-c5bfc600-e371-11e9-9876-2f51fdc54a80.png)

**Comment by chamilaadhi** [comment]
Hi, you could edit the application once it is created
