### ISSUE TITLE
Edited Application Tier accepts requests slightly more than the allocated quota

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5976]
Use Case: API administrator can add/edit the application tiers, so that application developer can limit the access to the  application user by define new per token quota
Test Scenario: Edit default 50PerMin per token quota application tier with new #Request and Time, and define for an application. So that application users granted maximum number of request to the API is newly added #Request and Time

Details of the Issue: When I edited the 50perMin application tier to accept 76 requests per minute, it accepted 79 requests.

![Screenshot from 2019-09-30 10-59-58](https://user-images.githubusercontent.com/38970634/65851931-2bac4d80-e372-11e9-8f63-52a73d7c78f1.png)
![Screenshot from 2019-09-30 10-59-46](https://user-images.githubusercontent.com/38970634/65851935-31a22e80-e372-11e9-998a-e83912de9ce1.png)

When I edited 20 perMin application tier to accept 30 requests per 2 minutes, it accepted 32 requests.

![Screenshot from 2019-09-30 11-13-29](https://user-images.githubusercontent.com/38970634/65852472-dcffb300-e373-11e9-8e3a-8e426d19fb5b.png)

![Screenshot from 2019-09-30 11-13-18](https://user-images.githubusercontent.com/38970634/65852479-dffaa380-e373-11e9-97e0-534df3696a70.png)

When I edited 10perMin application tier to accept 30 requests per 2 minutes, it accepted 35 requests.

![Screenshot from 2019-09-30 11-41-06](https://user-images.githubusercontent.com/38970634/65853516-6fee1c80-e377-11e9-8bc0-0c8104ef05c8.png)
![Screenshot from 2019-09-30 11-40-54](https://user-images.githubusercontent.com/38970634/65853522-77adc100-e377-11e9-8778-7b6b72b64972.png)
![Screenshot from 2019-09-30 11-40-45](https://user-images.githubusercontent.com/38970634/65853532-7aa8b180-e377-11e9-9817-639b5053b1bf.png)

**Comment by chamilaadhi** [comment]
We cannot get 100% accuracy from the throttling on a high TPS scenario
