### ISSUE TITLE
Bug when deleting multiple API documents:

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5978]
Once an API document is deleted in the API documents tab A check box  is displayed in-front of each document in the list. Once those check-boxes are checked and press the delete all button API documents are only get deleted from the front end display and not from the database and No confirmation is asked  from the user.
![Screenshot from 2019-09-30 11-15-03](https://user-images.githubusercontent.com/42222921/65852389-99a54480-e373-11e9-8448-80434ac7f9a3.png)

**Comment by chamilaadhi** [comment]
select all and delete all function is removed

![Screen Shot 2019-10-07 at 3 12 35 PM](https://user-images.githubusercontent.com/4861150/66301535-ef9a5f00-e914-11e9-8a37-aa0b9a7197ae.png)
