### ISSUE TITLE
[Publisher] Error message when a user with creator role edits the subscriptions page of a published API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5979]
When a user with create only permission tries to edit the 'Subscription availability' at the subscription page of a published API, an error message is shown as below:

![image](https://user-images.githubusercontent.com/47671237/65852319-6cf12d00-e373-11e9-8a06-c30d610c8cdd.png)

**Comment by TanyaM** [comment]
Subscription availability UI is disabled for a creator when the api is in PUBLISHED state.
