### ISSUE TITLE
[Publisher] Error message when a user with creator role edits the mediation policies of a published API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5980]
When a user with create only permission tries to edit the mediation policies of a published API, an error message is shown as below:

![image](https://user-images.githubusercontent.com/47671237/65852561-1e905e00-e374-11e9-841f-4feabaffd10b.png)

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7427
