### ISSUE TITLE
[Store] Inability for a user with Internal/creator role to view an API within developer portal

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5981]
**Steps followed:**

Created a new tenant (abc.com)
Created a new user within abc.com with the role of Internal/creator
Then created and published a new API within abc.com after logging in as the admin of the created tenant
In the developer portal, logged in as the created user (this user has the role of Internal/creator).
Then when clicked on the published API, user cannot view the relevant API, instead, the user is redirected to another page as shown below.

![11](https://user-images.githubusercontent.com/30475839/65852349-7ed2d000-e373-11e9-8193-788b0a6cb0ee.png)

After clicking on FakeREST API, the user is redirected to the page given below. Instead of this redirection, the user should be able to view the contents found within the API.

![22](https://user-images.githubusercontent.com/30475839/65852355-84301a80-e373-11e9-830c-e56f53d10781.png)

This is the error which gets logged in the terminal

![33](https://user-images.githubusercontent.com/30475839/65852362-87c3a180-e373-11e9-92de-27df800b3c67.png)

Similar behavior can be observed when the logged-in user has the role of a publisher (Internal/publisher).

**Comment by chamilaadhi** [comment]
User shouldn't be able to login to the store with creator role. this is fixed from https://github.com/wso2/carbon-apimgt/pull/7309. From that PR this is fixed
