### ISSUE TITLE
[Publisher] Issue when a user with creator role tries to edit the 'Backend throughput' of a published API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5983]
![image](https://user-images.githubusercontent.com/47671237/65852962-83988380-e375-11e9-86d2-cad72831d413.png)

A user with create only permission can edit the 'Backend throughput' but when saving it the following error occurs.

![image](https://user-images.githubusercontent.com/47671237/65853057-dc681c00-e375-11e9-8f82-9dfdc2cf1dde.png)

![image](https://user-images.githubusercontent.com/47671237/65853094-f7d32700-e375-11e9-9ae4-b13443ea11f0.png)

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7311
