### ISSUE TITLE
[Store] UI issue in  API ceredentials

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#5984]
![Screenshot from 2019-09-30 11-33-09](https://user-images.githubusercontent.com/31464477/65853342-ce66cb00-e376-11e9-9032-288063e196fa.png)
**Issue**
In API overview page,option links(with a default application, with a new application) in 'Subscribe to an Application' are in the same line,difficult to notice.

**Comment by chamilaadhi** [comment]
That section is refactored in the latest build
