### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5985]
**Description**

- The "With an Existing Application1 Applications AvailableWith a New Application" appears in a single line in the following image in the DevPortal, which is not good for user experience.

![image](https://user-images.githubusercontent.com/44407066/65853651-d4a97700-e377-11e9-8a3c-46d0038a4512.png)

**Suggestions**

- It would look nice if you can improve the UI

**Comment by chamilaadhi** [comment]
This UI is changed now. See below
![Screen Shot 2019-10-08 at 1 09 33 PM](https://user-images.githubusercontent.com/4861150/66376298-f1275e00-e9cc-11e9-992c-78c845b1b77c.png)
