### ISSUE TITLE
[Publisher] Parameters added using swagger editor are not visible under parameters heading in API resource page  

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5986]
**Issue:**
When parameters are added to the API using swagger editor, they are not visible under parameter heading in the API resource page of API Publisher.

**Steps to recreate:** 

1. Add a parameter to an existing API resource using the swagger editor.
2. Check in the API resource page.

![Selection_015](https://user-images.githubusercontent.com/27700915/65853640-ce1aff80-e377-11e9-88d5-f1ac31b877f7.png)

**Comment by tharikaGitHub** [comment]
The parameters added from the swagger editor are shown in the DevPortal Test Console. Hence reducing the severity.

**Comment by chamilaadhi** [comment]
Ref property are not shown as well. https://github.com/wso2/product-apim/issues/5273

**Comment by dushaniw** [comment]
Closing since the issue is tracked from https://github.com/wso2/product-apim/issues/5273
