### ISSUE TITLE
[Publisher] User with creator role can edit the thumbnail of a published API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5987]
![image](https://user-images.githubusercontent.com/47671237/65853684-eee35500-e377-11e9-93c5-61a0bc6b21e3.png)

Even though a user with create only permission cannot edit a published, deprecated or retired API, at the overview page and configurations page, the thumbnail can be edited and changed. 

![image](https://user-images.githubusercontent.com/47671237/65853810-5ef1db00-e378-11e9-8a3c-715dc0666472.png)

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7259
