### ISSUE TITLE
Business owner's name is not displayed in devportal

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5988]
If API business information is defined, the business owner should be shown instead of the provider in devportal. But still the provider name is displayed instead of the business owner.

See PizzaShackAPI1 in following screen shots.

![Screenshot from 2019-09-30 11-45-34](https://user-images.githubusercontent.com/36144069/65853834-70d37e00-e378-11e9-9fec-830886d1f84e.png)

![Screenshot from 2019-09-30 11-45-43](https://user-images.githubusercontent.com/36144069/65853841-7761f580-e378-11e9-9795-f5e2e25b7759.png)

**Comment by AmaliMatharaarachchi** [comment]
This issue also occurs for API products.
