### ISSUE TITLE
 [DevPortal/Bug] in API-Product overview page

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#5989]
Once a user browse to the API-Product overview in devportal and then if the user clicks the Overview tab user is directed to   white screen and following logs in the browser console
![Screenshot from 2019-09-30 11-51-45](https://user-images.githubusercontent.com/42222921/65854430-41257580-e37a-11e9-8573-afccf60b1699.png)

**Comment by ThaminduDilshan** [comment]
Same issue when click on the "More" button.

**Comment by chamilaadhi** [comment]
Duplicate issue https://github.com/wso2/product-apim/issues/5923
