### ISSUE TITLE
Problem with the "Next" button

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5990]
**Description**

- The "Next" button in the "Generate Keys" page of "Subscribe to New Application" doesn't work.

- When hitting the button an error log is logged saying that "Keys already generated for the application".

![image](https://user-images.githubusercontent.com/44407066/65854522-834eb700-e37a-11e9-869a-7ed57139994a.png)

![image](https://user-images.githubusercontent.com/44407066/65854572-a4afa300-e37a-11e9-9d16-df3474e0a2a1.png)

![image](https://user-images.githubusercontent.com/44407066/65854670-dc1e4f80-e37a-11e9-83e2-dd63e6b3bb47.png)

**Comment by chamilaadhi** [comment]
fixed in latest build
