### ISSUE TITLE
[Publisher] Inability to deploy a GraphQL API as a prototype

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#5991]
When we consider a REST API, under the LIFECYCLE tab, the "DEPLOY AS A PROTOTYPE" button is disabled. When we go to the "ENDPOINTS" tab and select the "Prototyped" option and click on "SAVE", this button becomes activated.

![1](https://user-images.githubusercontent.com/30475839/65854919-71b9df00-e37b-11e9-885e-aa75e9bb5e36.png)

Similarly in GraphQL APIs, this "DEPLOY AS A PROTOTYPE" button is disabled. But when it comes to GraphQL APIs, there is no way to activte this button. Shown below is the screenshot, of the "ENDPOINTS" tab within a GraphQL API.

![2](https://user-images.githubusercontent.com/30475839/65854692-e4768a80-e37a-11e9-847c-7aa14c12ba82.png)

This is the screenshot of the "LIFECYCLE" tab. This "DEPLOY AS A PROTOTYPE" button cannot be activated.

![3](https://user-images.githubusercontent.com/30475839/65854704-e93b3e80-e37a-11e9-8f1f-03af27195254.png)

**Comment by chamilaadhi** [comment]
Deploy as Prototype is not supported for GraphQL
