### ISSUE TITLE
[Publisher] Issues when editing the API definition using swagger editor

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5997]
**Issue:**
Sometimes the cursor moves to the beginning of the page when typing in the swagger editor. 

**Related issue** : https://github.com/wso2/product-apim/issues/5885

**Comment by chamilaadhi** [comment]
Related issue https://github.com/wso2/product-apim/issues/5071

**Comment by menakaj** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/7446
