### ISSUE TITLE
[Publisher] API tags updating with special characters

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#5999]
![Screenshot from 2019-09-30 14-13-40](https://user-images.githubusercontent.com/31029812/65862810-a97d5280-e38c-11e9-81fb-852ac5e1620b.png)

Error encountered - After editing the API tags with special characters, an error message is showing, but it's not showing any validations.

**Comment by chamilaadhi** [comment]
Validation is there in AM 3.0.0 beta. 
<img width="661" alt="Screen Shot 2019-10-12 at 11 28 01 AM" src="https://user-images.githubusercontent.com/4861150/66695814-681d6900-ece3-11e9-9812-ba4e9299d353.png">
