### ISSUE TITLE
UI is not Responsive

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6000]
**Description**

- The UI is not responsive. 

![Screenshot from 2019-09-30 14-30-14](https://user-images.githubusercontent.com/44407066/65864142-02e68100-e38f-11e9-9278-85a7a35be754.png)

**Comment by npamudika** [comment]
@SachithKasthuriarachchi, Can you please provide more details on this? When did you observe this behaviour? What were you trying to do?

**Comment by kavishkafernando** [comment]
UI is responsive in latest pack
<img width="1113" alt="Screen Shot 2019-10-10 at 7 02 28 PM" src="https://user-images.githubusercontent.com/19324135/66573744-cab22000-eb90-11e9-9160-08c61e3001e1.png">

**Comment by SachithKasthuriarachchi** [comment]
> @SachithKasthuriarachchi, Can you please provide more details on this? When did you observe this behaviour? What were you trying to do?

@npamudika I resized the window and some of the components were out of the boxes.
