### ISSUE TITLE
Error in selecting key type in TEST page of DevPortal

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6004]
When we have only a "production" gateway environment, we need to invoke the API only by using a "production" type token. When we change the key type to SANDBOX and try with the same Production key it executes. This is happening other way round also. When we have a "sandbox" gateway environment and a sandbox key although we change the key type to PRODUCTION it executes.

**Comment by chamilaadhi** [comment]
Sanbox environment can be invoked using both production end sandbox keys but production environment cannot be invoked using a sandbox token. 

I tested this on the APIM 3.0.0 beta by setting the gateway type to production and saw it is happening correctly

    [[apim.gateway.environment]]
    name = "Production"
    type = "production"

See the below responses for both type of tokens

    $ curl -X GET "https://localhost:8243/tokentest/1/resource" -H "accept: */*" -H "Authorization: Bearer 088f33fc-7d93-3bc8-b073-cd50e3498dbf" -k
    <error><message>Sandbox Key Provided for Production Gateway</message></error>

jwt

        $curl -X GET "https://localhost:8243/tokentest/1/resource" -H "accept: */*" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlpqUm1ZVE13TlRKak9XVTVNbUl6TWpnek5ESTNZMkl5TW1JeVkyRXpNamRoWmpWaU1qYzBaZz09In0=.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllciI6IjUwUGVyTWluIiwibmFtZSI6IlRlc3QiLCJpZCI6MzN9LCJzY29wZSI6ImFtX2FwcGxpY2F0aW9uX3Njb3BlIGRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJTQU5EQk9YIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiVG9rZW5UZXN0IiwiY29udGV4dCI6IlwvdG9rZW50ZXN0XC8xIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifV0sImNvbnN1bWVyS2V5IjoiTm93ZzdKYlozN3NPN3pBaU1XZjhOdDNqb2hzYSIsImV4cCI6MTU3MDc3Mzg3MCwiaWF0IjoxNTcwNzcwMjcwLCJqdGkiOiJjZTRkZDBkZC1hZTE5LTQ3YmQtODkyNC1lZDQ0MjA5MWM1OGQifQ==.CXPGrHsa1Fro6os3CAtlFnbvpjBXXgFaENWwQPxBb5WNW2Mnav7_EF0uj3hIaQBPF2AqmpW5GNccuTTT1lJAhotomV67k9yUursNoCWphFtGvGUXKXAKoNao6wBF9RUv1p7Yt40EBnVO3slOc-m09uUJkKNc-ne63ExFAzGnb0lhi-baonApgIboz1QP_hQay1QgGfRKvXJe1U-pOqmHWB8c9OYkLTkRk-d-nplTsmbRtsijNlkhb0hJa8Oub236xGiwacwMeLya8lZquJ2LfDQHtO1R4PCFkm80qFrMjzybegtKsQ7wvjx8sWGGczeBqypyudeX2H9rdlpnnHfEOw==" -k
    <error><message>Sandbox Key Provided for Production Gateway</message></error>
