### ISSUE TITLE
Issue with the toast comming after a API is updated in Gateways page of Publisher

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6005]
In the Publisher- Gateways page after we update an API a toast appears stating that API is successfully updated. But it seems to be two Toasts are coming overlapping each other.  

![Screenshot from 2019-09-30 13-58-38](https://user-images.githubusercontent.com/51467737/65866513-85bd0b00-e392-11e9-8c20-21611eb47bcd.png)

**Comment by ShanJayaweera** [comment]
I noticed this only with the sample PizzaShack API

**Comment by chamilaadhi** [comment]
seems no issue found here
<img width="537" alt="Screen Shot 2019-10-12 at 11 52 49 AM" src="https://user-images.githubusercontent.com/4861150/66696142-f9daa580-ece6-11e9-9a24-affc88fa29f2.png">
