### ISSUE TITLE
Issue with invoking the Api after an Gateway environment is updated

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6008]
We have initialized different Gateway Environments by using deployment.toml

![Screenshot from 2019-10-09 14-58-11](https://user-images.githubusercontent.com/51467737/66469258-2e5f1f00-eaa5-11e9-9a33-204484f1c8c4.png)

when we Publish the API by using one gateway environment that we have deployed, we can execute the API properly in the DevPortal.

If we change the gateway environment of that published API, in the first instance it shows that the API is updated successfully. Although it shows like that, we cant invoke the API with the correct token even. The updated gateway environment is visible on the overview page of the dev portal. But although we have the correct key, we won't be able to invoke the API. 

![Screenshot from 2019-09-30 15-20-06](https://user-images.githubusercontent.com/51467737/65868363-b9e5fb00-e395-11e9-9b20-6ea86686b9fe.png)

**Comment by npamudika** [comment]
Republishing the API will solve the issue. We need to check and fix the logic behind save operation to publish to newly added gateway environments.

**Comment by Krishanx92** [comment]
This issue cannot reproduce in APIM-3.0.0-beta, hence resolve.
