### ISSUE TITLE
[Store] Issue with POST method when testing a GraphQL API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6010]
When trying to test the GraphQL API named HackerNews, using the POST method, the below given mutation was passed.

![11](https://user-images.githubusercontent.com/30475839/65868785-9ff8e800-e396-11e9-8985-fcb0803d2fa8.png)

But this gives a failed to fetch error because the generated curl was not valid.

![22](https://user-images.githubusercontent.com/30475839/65868798-a4250580-e396-11e9-9953-b5bc1dcdb703.png)

**Comment by HiranyaKavishani** [comment]
@AmaliMatharaarachchi Could you please looking this issue?

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7345
