### ISSUE TITLE
Subscription Tier when edited allowed requests more than the allocated quota 

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6014]
Test Scenario: Edit default subscription tier by update new Time value, and define for an API. So that subscribers are granted maximum number of request to the API should be valid for new Time.
e.g. 1000PerMin -> 1000/2min

Details of the Issue: When I edited the Gold tier to 50 requests per minute, it allowed to send 51 requests per minute. Also when the quota 50 requests per 2 minutes were given for the Gold tier 95 hits were successful in 2 minutes.

![Screenshot from 2019-09-28 22-18-06](https://user-images.githubusercontent.com/38970634/65873289-53b2a580-e3a0-11e9-96ca-abbb942a5c6d.png)
![Screenshot from 2019-09-28 22-18-45](https://user-images.githubusercontent.com/38970634/65873294-56ad9600-e3a0-11e9-93be-98867ff5e134.png)
![Screenshot from 2019-09-28 22-25-26](https://user-images.githubusercontent.com/38970634/65873297-590ff000-e3a0-11e9-9d4d-bfc1797c59f9.png)

**Comment by rmsamitha** [comment]
> When I edited the Gold tier to 50 requests per minute, it allowed to send 51 requests per minute.
@SabinaPrasadhi this is possible and a norm.

> Also when the quota 50 requests per 2 minutes were given for the Gold tier 95 hits were successful in 2 minute
When it was restricted? At 95 itself?

**Comment by SabinaPrasadhi** [comment]
Yes at 95th request itself.
