### ISSUE TITLE
[Publisher] Issue with the "NEXT" button when creating APIs using file uploads 

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6018]
For example, consider a scenario where a GraphQL API is created. The API creator is prompted to upload a GraphQL file as shown below.

![a1](https://user-images.githubusercontent.com/30475839/65876316-97101280-e3a6-11e9-884a-238800ce8e54.png)

Once the "NEXT" button is clicked, the API creator will be redirected to the page which is shown below.

![a2](https://user-images.githubusercontent.com/30475839/65876320-9d05f380-e3a6-11e9-9763-11100264dc55.png)

And once the "BACK" button is clicked, since the already added file exists, the "NEXT" button should not be inactive. The screenshot given below shows this screen. To remedy this issue the "NEXT" button should be made active.

![a3](https://user-images.githubusercontent.com/30475839/65876330-a1321100-e3a6-11e9-942b-54e921b9eb6d.png)

**Comment by HiranyaKavishani** [comment]
Fixed in new pack

**Comment by pahans** [comment]
I was able to reproduce this issue in RC1. @HiranyaKavishani Shall we reopen this.
