### ISSUE TITLE
Users can view restricted APIs in API devportal without required role.

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#6022]
1. The first issue is that any user who has any role can login to the devportal.
2. Users who have internal roles can view restricted apis in devportal without the required role.

**Comment by chamilaadhi** [comment]
login issue is fixed in https://github.com/wso2/carbon-apimgt/pull/7309

**Comment by AmaliMatharaarachchi** [comment]
This was not observed in the latest pack. 
Note that internal/publisher and internal/creator roles can see all apis even when store visibility was enabled and restricted.
