### ISSUE TITLE
[Publisher] Issue when a publisher tries to edit the monetization of a published API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6027]
If a user with publisher permission tries to edit published APIs and try to edit monetization:

![image](https://user-images.githubusercontent.com/47671237/65933606-cb7be100-e42f-11e9-9e39-acbdcd4be842.png)

Without changing anything and just clicking the save icon, the following error message can be seen:

![image](https://user-images.githubusercontent.com/47671237/65933690-34fbef80-e430-11e9-85dd-dedf81d20ed3.png)

After ticking the Enable Monetization field and saving, the same error message is prompted:

![image](https://user-images.githubusercontent.com/47671237/65933744-53fa8180-e430-11e9-9d3d-f6589cd9221b.png)

The following error log can be seen for both instances:

![image](https://user-images.githubusercontent.com/47671237/65933772-7a202180-e430-11e9-8f17-1e4f3f193873.png)

**Comment by chamindias** [comment]
Please see: https://github.com/wso2/carbon-apimgt/pull/7373

**Comment by chamindias** [comment]
Fixed: https://github.com/wso2/carbon-apimgt/pull/7408 (for all scenarios)

![image](https://user-images.githubusercontent.com/8359365/66479347-ed253a00-eab9-11e9-8dd8-e9f4feb24fd3.png)

![image](https://user-images.githubusercontent.com/8359365/66479351-f1515780-eab9-11e9-8182-b8c52b593d09.png)
