### ISSUE TITLE
No warning messages on subscribing to production only blocked application

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6028]
When an application is blocked for production only in publisher portal, and then subscribing to that application in devportal, it shows no warning message for not completing the process. It remains in the same page without any notifications.

The below image shows that the application "my1" is blocked for production only.

![Screenshot from 2019-10-01 09-45-35](https://user-images.githubusercontent.com/54226167/65933910-04688580-e431-11e9-811b-666db0652ab1.png)

When the same application is selected to subscribe, it does not allow to subscribe but shows no constructive messages on why it cannot be subscribed.
 
![Screenshot from 2019-10-01 09-31-06](https://user-images.githubusercontent.com/54226167/65934040-8a84cc00-e431-11e9-9bbe-b034d32315d9.png)

**Comment by vithu30** [comment]
This is not reproducible in the latest pack. Credentials page has been revamped with wizards:
![image](https://user-images.githubusercontent.com/19728269/66649256-538d9200-ec4b-11e9-9b1a-19cf46585d7c.png)
