### ISSUE TITLE
[Publisher] Issue with the Operations under the Overview Page of a GraphQL API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6030]
Shown below is the overview page of a GraphQL API where a mock backend was used to create the API. Under the Operations section within the Overview page, all operations are listed down. Here there is no limit to the number of displayed operations. The suggestion made here is to limit the number of operations displayed at a time (since this is the overview page and the viewer only needs a rough idea of the content within the API).

![111](https://user-images.githubusercontent.com/30475839/65936025-bc4d6100-e438-11e9-9af0-bd8a6baf5fef.png)

![222](https://user-images.githubusercontent.com/30475839/65936034-c3746f00-e438-11e9-8869-15f30f1eb7ea.png)

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
