### ISSUE TITLE
[DevPortal/Error] SDK generation options available for Web socket APIs

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6035]
In a published web-socket API user is shown the option to generate a SDK which is not possible due to there is no swagger definition is available.Following error logs in the console.
![Screenshot from 2019-10-01 11-06-20](https://user-images.githubusercontent.com/42222921/65937046-3a5f3700-e43c-11e9-88f4-207cf4370e6a.png)
![Screenshot from 2019-10-01 11-06-39](https://user-images.githubusercontent.com/42222921/65937050-3b906400-e43c-11e9-91f0-e909e2db6117.png)

**Comment by Arshardh** [comment]
This is fixed with the pr: https://github.com/wso2/carbon-apimgt/pull/7282
