### ISSUE TITLE
[Publisher] Endpoint certificate error

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6039]
![Screenshot from 2019-10-01 11-20-10](https://user-images.githubusercontent.com/31029812/65937693-52d05100-e43e-11e9-93ea-b37ea53d4a53.png)
![Screenshot from 2019-10-01 11-20-17](https://user-images.githubusercontent.com/31029812/65937694-5532ab00-e43e-11e9-9a25-9a04647eea72.png)

I was able to add an endpoint certificate but after I save it, I was getting an error as I mentioned in the screenshots.

**Comment by kavishkafernando** [comment]
Fixed in the latest pack.
<img width="1680" alt="Screen Shot 2019-10-07 at 11 28 59 AM" src="https://user-images.githubusercontent.com/19324135/66288130-b7375880-e8f5-11e9-94e7-34bbf9ee481e.png">
