### ISSUE TITLE
[Publisher]Can not add several endpoint certificates 

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6041]
![Screenshot from 2019-10-01 11-45-27](https://user-images.githubusercontent.com/31029812/65938709-5d401a00-e441-11e9-9bad-333dd95f40e0.png)

I was not able to add two endpoint certificates under a different alias. After pressing the save button it gives an error.

**Comment by chamilaadhi** [comment]
another certificate related issue https://github.com/wso2/product-apim/issues/6041

**Comment by kavishkafernando** [comment]
Fixed in latest pack.
