### ISSUE TITLE
[Publisher] Issue with the "Go To" search option for GraphQL APIs

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6042]
![Screenshot from 2019-10-01 11-30-25](https://user-images.githubusercontent.com/30475839/65937980-3a146b00-e43f-11e9-9257-ebf3f9795039.png)

Here the menu options which can be searched should be altered for GraphQL APIs .For example there are no options for the "Schema Definition" - API definition in REST, "Operations" - Resources in REST, etc. They should be altered accordingly in order to fit GraphQL APIs. Note that here when searched for the "Swagger" as a menu option, the user is redirected to the "Schema Definition" accordingly, but the relevant tab in the menu does not get highlighed.

Also as shown in the screenshot below, under the "CONFIGURATION" tab, the "Schema Validation" under the "Request" section should be removed.

![WSO2 APIM publisher](https://user-images.githubusercontent.com/30475839/65938797-ab551d80-e441-11e9-80be-8c049514290c.png)

**Comment by chamilaadhi** [comment]
graphQL related issues https://github.com/wso2/product-apim/issues/6030

**Comment by HiranyaKavishani** [comment]
Fixed the issue with https://github.com/wso2/carbon-apimgt/pull/7400/commits/685b3750fd63ff57ecc72494da74878c3471654b
