### ISSUE TITLE
[Publisher] Production endpoint field ovelapping

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6045]
![Screenshot from 2019-10-01 11-50-23](https://user-images.githubusercontent.com/31464477/65938973-23bbde80-e442-11e9-9e60-d1cbca2a222f.png)
**Issue**
In Endpoints page,after adding production endpoint or sandbox endpoint,if we select Load balanced option or Failover option and if we click on that endpoint & then if we click on another field label overlaps with the endpoint url.

**Comment by menakaj** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7473
