### ISSUE TITLE
[Publisher][UX][Listing] Styling issue in the api listing card in tenant mode.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#6046]
![Screenshot (13)](https://user-images.githubusercontent.com/10165411/65939278-16ebba80-e443-11e9-9930-d04d348244d3.png)

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="265" alt="Screen Shot 2019-10-14 at 3 38 43 PM" src="https://user-images.githubusercontent.com/4861150/66743936-be7fd880-ee98-11e9-9d55-b54e6b88475b.png">
