### ISSUE TITLE
Enhance Custom Throttling Policies by Adding Client IP Address To Key Template

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#6047]
**Use Case:**
- All the clients invoke an API with different IP addresses and have the same access token.
- These IP addresses are not known in advance.
- Therefore throttle decisions need to be taken considering client IP addresses. 
- When creating custom throttling policies currently following keys can be used.
         resourceKey, userId, apiContext, apiVersion, appTenant, apiTenant, appId

**Comment by tharindu1st** [comment]
Sample custom key template 
FROM RequestStream
SELECT messageID,(cast(map:get(propertiesMap,'ip'),'Long')==174327189l) AS isEligible , str:concat(cast(map:get(propertiesMap,'ip'),'Long'),'') as throttleKey
INSERT INTO EligibilityStream;

FROM EligibilityStream[isEligible==true]#throttler:timeBatch(1 min)
SELECT throttleKey, (count(messageID) >= 5) as isThrottled, expiryTimeStamp group by throttleKey
INSERT ALL EVENTS into ResultStream;
