### ISSUE TITLE
[Publisher] Missing menu items when searched through "Go To" search option within an API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6050]
Consider a scenario where a user is logged into the publisher and an API is selected. Under the "Go To" option some menu items cannot be searched. Some of them are:
- Overview, Configuration, Gateways, Subscriptions, Mediation Policies, Monetization.

![Screenshot from 2019-10-01 11-24-55](https://user-images.githubusercontent.com/30475839/65939971-f9b7eb80-e444-11e9-93db-0aee71ced695.png)

**Comment by chamilaadhi** [comment]
issues related to GO TO option https://github.com/wso2/product-apim/issues/6042
