### ISSUE TITLE
  [DevPortal] Bug when trying to deleting an Application

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6051]
When a user clicks  the delete API button in the ./devportal/applications page no confirmation is asked from the end user.
![Screenshot from 2019-10-01 12-09-29](https://user-images.githubusercontent.com/42222921/65939990-03d9ea00-e445-11e9-89bb-35b4bbb6249b.png)

**Comment by dushansilva** [comment]
duplicate issue 
https://github.com/wso2/product-apim/issues/5723
