### ISSUE TITLE
Test case 4.7.3.1: Unable to import an application by the application owner

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6052]
Test case 4.7.3.1:
Should support Export and Import (migrating) an Application preserving the application owner.

Result:
When try to import an application created by admin, cannot import.

**Comment by chamilaadhi** [comment]
Related issues https://github.com/wso2/product-apim/issues/6044, https://github.com/wso2/product-apim/issues/6143

**Comment by dushaniw** [comment]
Can reproduce the issue during both update and import applications
