### ISSUE TITLE
[DevPortal] Cannot subscribe to an Application with already entered default values

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6053]
When I tried to subscribe to an application with already entered default values in the devportal UI , I was unable to subscribe to it. No message was displayed either.

![Screenshot from 2019-10-01 12-18-03](https://user-images.githubusercontent.com/38970634/65940427-228cb080-e446-11e9-8bc8-aa79eb2571e9.png)
![Screenshot from 2019-10-01 12-17-55](https://user-images.githubusercontent.com/38970634/65940437-27516480-e446-11e9-8d43-b3c84685220e.png)

**Comment by chamilaadhi** [comment]
related to https://github.com/wso2/product-apim/issues/6054 as well

**Comment by chamilaadhi** [comment]
Fixed
