### ISSUE TITLE
[Devportal] Unable to click subscribe with default selected options

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6054]
Unable to click subscribe unless default selected options in the drop-down menu are re-selected.
Only able to subscribe when re-select the options and then click subscribe.
Also no notifications are popped-up to re-select the options and then to click subscribe.

![Screenshot from 2019-10-01 12-22-47](https://user-images.githubusercontent.com/54226167/65940582-7dbea300-e446-11e9-9c02-150be5bcb67f.png)

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
