### ISSUE TITLE
[store] When ReadWriteLDAPUserStore is enabled, users cannot create applications

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6055]
When ReadOnlyLDAPUserStore is enabled users can login to the system.
![image](https://user-images.githubusercontent.com/40932779/65944330-16f1b780-e44f-11e9-9fb4-05cf8cb3763e.png)

After login 
![image](https://user-images.githubusercontent.com/40932779/65944555-98494a00-e44f-11e9-9ea8-1dfd2d898f95.png)

But when application view is selected it shows as below.

![image](https://user-images.githubusercontent.com/40932779/65944633-c464cb00-e44f-11e9-9cfc-e2c351b661ae.png)

**Comment by 7slcode7** [comment]
Since I haven't configured user roles, above error has occurred. After creating user roles it worked. 
But (when user roles not configured) the restriction message to the user not shown and it shows user hasn't login to the system.

**Comment by chamilaadhi** [comment]
Storelogin permission related issue is fixed in https://github.com/wso2/carbon-apimgt/pull/7309
