### ISSUE TITLE
[Publisher] Bug when publishing an API

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6058]
When a user tries to publish an API which has no previous version while checking the checkbox  no proper error message shown to the end user and following logs in the console 
![Screenshot from 2019-10-01 13-56-06](https://user-images.githubusercontent.com/42222921/65946556-0d1e8300-e454-11e9-8ad1-14b7d5255a8d.png)
![Screenshot from 2019-10-01 13-56-15](https://user-images.githubusercontent.com/42222921/65946559-0e4fb000-e454-11e9-9b56-4fe0a53b0b53.png)

**Comment by AmaliMatharaarachchi** [comment]
Seems that you have api products as well. This error is related to https://github.com/wso2/product-apim/issues/6164
