### ISSUE TITLE
[Publisher] A user with publisher permission should not be able to update tier collection

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6059]
According to the test case, API Publisher(who has publisher permission only) should NOT be able to update tier collection. The fields should not be editable.
But a user with publisher permission only can update tier collection (subscription policies) of both created and published APIs.

![image](https://user-images.githubusercontent.com/47671237/65946475-d7799a00-e453-11e9-8fc3-decf0754bafc.png)
![image](https://user-images.githubusercontent.com/47671237/65946561-0ee84680-e454-11e9-9c6c-34dd2deaacc6.png)

**Comment by TanyaM** [comment]
As per the wiki publisher should be able to update the subscription tiers [1]
Hence closing the issue.

[1] https://github.com/wso2/carbon-apimgt/wiki/Permission-validation-on-the-Publisher-UI-elemets-for-API-update
