### ISSUE TITLE
Deleted Microgateway labels are still visible on the Devportal

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6060]
I created a label by admin portal and published an API along with that Micro gateway label. Although Admin has deleted it by admin portal it still keeps visible under Available Microgateways. But that label is not visible in the Publisher even. It is only visible the name of the micro gateway label. Micro gateway URLs have disapered. 

![Screenshot from 2019-10-01 14-07-25](https://user-images.githubusercontent.com/51467737/65946951-dbf28280-e454-11e9-9efa-758d838aec6b.png)
![Screenshot from 2019-10-01 14-07-29](https://user-images.githubusercontent.com/51467737/65946959-ddbc4600-e454-11e9-9c36-4d08cbedcdab.png)

**Comment by chamindias** [comment]
Closing because of : https://github.com/wso2/carbon-apimgt/pull/7634
