### ISSUE TITLE
Updated Label name is still visible in the DevPortal

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6064]
When we update and change a label name from the admin portal it gets removed from the publisher used Microgaetways and it appeared as a new micro gateway. But the old name is still visible in the dev portal and as it has removed from used Micro gateways by the publisher Micro gateway URLs are missing.
In the ss I have changed earlier name Depo to Deyot.

![Screenshot from 2019-10-01 14-34-04](https://user-images.githubusercontent.com/51467737/65948850-a485d500-e458-11e9-9f05-5e497964cde0.png)
![Screenshot from 2019-10-01 14-34-06](https://user-images.githubusercontent.com/51467737/65948853-a5b70200-e458-11e9-8737-a3277a8a8b20.png)

**Comment by chamilaadhi** [comment]
label related issues https://github.com/wso2/product-apim/issues/6063
