### ISSUE TITLE
[Publisher] In firebox browsers can add  non-numeric values in time duration fields under advanced endpoint configuration"

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6066]
![Screenshot from 2019-10-01 14-36-45](https://user-images.githubusercontent.com/31464477/65949271-7fde2d00-e459-11e9-9889-46a678bb5467.png)
![Screenshot from 2019-10-01 14-36-56](https://user-images.githubusercontent.com/31464477/65949278-810f5a00-e459-11e9-9c6f-a6f7d2b3cb3e.png)
**Issue**
In Firefox browsers,non-numeric values can be added & saved successfully in time duration fields under advanced endpoint configuration" of Endpoints page.

**Comment by mushthaq33** [comment]
This is an issue with material-ui as per [1]. Hence reducing the priority

[1] - https://github.com/mui-org/material-ui/issues/6220
