### ISSUE TITLE
Unauthorized actions will be listed in "Go To" search in Publisher

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6067]
Steps:
1. Login to the publisher from a creator account.
2. Click on an API and search for lifecycle and click on the listed item.

Issue:
Lifecycle will be listed for a creator account even it is not allowed. However, the resulted page is shown as unauthorized.
![Screenshot from 2019-10-01 14-46-27](https://user-images.githubusercontent.com/35653110/65950104-0e9f7980-e45b-11e9-8797-b8e7cd84c1c4.png)

![Screenshot from 2019-10-01 14-47-00](https://user-images.githubusercontent.com/35653110/65950109-119a6a00-e45b-11e9-8417-6edf98bc2efb.png)

**Comment by chamilaadhi** [comment]
Since page content is not shown, this would be harmless.
