### ISSUE TITLE
WebSocket API isn't creating even after entering a valid WSDL url

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6068]
**This occurs only in the following scenario**

- I tried to create a web socket API by providing an invalid WSDL endpoint and the API wasn't created which is fine.

![Screenshot from 2019-10-01 14-42-01](https://user-images.githubusercontent.com/44407066/65950059-fa5b7c80-e45a-11e9-8d20-6f687616c8b5.png)

- But then **without refreshing** the page I just replaced the invalid WSDL endpoint with a valid one and clicked the "Create" button. But then a blue circular line on the create button kept rotating without creating the API.

![Screenshot from 2019-10-01 14-42-15](https://user-images.githubusercontent.com/44407066/65950085-06dfd500-e45b-11e9-9171-c5239af38d1e.png)

- But this problem doesn't occur when I refreshed the page

**Comment by chamilaadhi** [comment]
need to add a url validation for the endpoint url

**Comment by npamudika** [comment]
This issue has been fixed in the latest APIM 3.0.0 pack (as at 7th Oct 2019). Hence closing the issue.
