### ISSUE TITLE
Problem when deleted a published label and again make a label with the same name

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6069]
I have got 2 labels created in my admin portal. Pizza and Deyot. pizza is from localhost:8000 at the beginning. I used both of those Labels as available Micro gateways by the publisher.

![Screenshot from 2019-10-01 14-41-11](https://user-images.githubusercontent.com/51467737/65949771-730e0900-e45a-11e9-9b99-662ba0257604.png)
![Screenshot from 2019-10-01 14-41-21](https://user-images.githubusercontent.com/51467737/65949774-74d7cc80-e45a-11e9-9e41-e26dbe413f81.png)
 
Then i deleted the Pizza label from the admin portal and check the publisher. It gets removed from the publisher and still the name is visible in the DevPortal.

![Screenshot from 2019-10-01 14-50-18](https://user-images.githubusercontent.com/51467737/65949991-d1d38280-e45a-11e9-8cbd-34cb4c22ae27.png)
![Screenshot from 2019-10-01 14-50-28](https://user-images.githubusercontent.com/51467737/65949993-d26c1900-e45a-11e9-9b99-bb22fd333eec.png)

But then if we add another label with the exact same name with a different host 9096 (considering the upper case and lower case as well) it automatically uses it as an available Micro Gateway. and it updates both the publisher and the DevPortal. 
![Screenshot from 2019-10-01 14-50-10](https://user-images.githubusercontent.com/51467737/65950537-e401f080-e45b-11e9-9ede-8b5707c3b7cd.png)

![Screenshot from 2019-10-01 14-42-16](https://user-images.githubusercontent.com/51467737/65950468-c0d74100-e45b-11e9-92aa-20d997a3f0a0.png)

![Screenshot from 2019-10-01 14-42-23](https://user-images.githubusercontent.com/51467737/65950477-c5035e80-e45b-11e9-88a3-140ffbf1624e.png)

**Comment by chamindias** [comment]
Closing because of: https://github.com/wso2/carbon-apimgt/pull/7634
