### ISSUE TITLE
[publisher] Create API dropdown not viewing properly

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6073]
When list view is enabled and Create API drop down API is clicked, it appears behind the table headers as follows.

![image](https://user-images.githubusercontent.com/40932779/65956719-a0fa4a00-e468-11e9-9471-dbf47aaf0bda.png)

**Comment by chamilaadhi** [comment]
duplicate https://github.com/wso2/product-apim/issues/5715
