### ISSUE TITLE
[Dev Portal] When a user signup for the devportal,confirmation link is not receving to their email.

### ISSUE THREAD

**Issue by Thidasala** [wso2/product-apim#6078]
![Screenshot from 2019-10-01 16-36-52](https://user-images.githubusercontent.com/45654571/65957438-78734f80-e46a-11e9-81b7-d56d05562c89.png)
When user signup for the dev portal, although they get a message saying confirmation email has been sent to their email, confirmation email is not receiving

**Comment by chamilaadhi** [comment]
Need to disable email sending option.
