### ISSUE TITLE
[Publisher] API Products can not contain endpoints 

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6079]
![Screenshot from 2019-10-01 16-41-25](https://user-images.githubusercontent.com/31029812/65957510-a062b300-e46a-11e9-9788-a3bffd3fa238.png)

Error encountered: In the API product section, in the configuration page there is a link called endpoint, logically this can not happen. because API products can not have an endpoint.

![Screenshot from 2019-10-01 16-48-29](https://user-images.githubusercontent.com/31029812/65957769-5928f200-e46b-11e9-8e82-ac1e69f679d7.png)

After clicking that link an error is displaying.

**Comment by chamilaadhi** [comment]
API product ui related issues https://github.com/wso2/product-apim/issues/6081

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7250
