### ISSUE TITLE
[Publisher]API Product section contains mediation policies

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6081]
![Screenshot from 2019-10-01 16-53-10](https://user-images.githubusercontent.com/31029812/65958178-6eeae700-e46c-11e9-86bf-f5af9c7215bc.png)
 
API product section contains the mediation policies tab in the side menu. This should be removed.

**Comment by kavishkafernando** [comment]
Mediation policies are no longer present in the tab

<img width="688" alt="Screen Shot 2020-01-03 at 4 54 30 PM" src="https://user-images.githubusercontent.com/19324135/71721073-cfae0500-2e49-11ea-99dc-f71284e91316.png">
