### ISSUE TITLE
[publisher] API Product search bar

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6082]
When API product view is selected, search box  placeholder in the API product appears same as search APIs.

![image](https://user-images.githubusercontent.com/40932779/65958526-37c90580-e46d-11e9-9c78-111ab79f7611.png)

Placeholder of the API should be changed as **Search Products** or **Search API products**.

**Comment by HiranyaKavishani** [comment]
We can't search API Products when routing the API Product tab. But we have to make proper placeholders here. you can use  'type:APIPRODUCT' property search to search API products at here

**Comment by HiranyaKavishani** [comment]
![Screen Shot 2019-10-16 at 9 42 23 PM](https://user-images.githubusercontent.com/29066805/66937952-f2582b00-f05d-11e9-8d99-7cc2b8435670.jpg)
