### ISSUE TITLE
Error while granting access for an API using an unauthenticated tier

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6096]
Test Scenario: [N] Grant access for an application using Unauthenticated tier, by selecting authentication type as None for a resource, so that subscribers should be able to 
- request for relevant resource without tokens
- maximum #Request quota 500 

{can check max + 1 request

Details of the Issue encountered: When 501 requests were sent, the additional 501th request was a successful hit.

Screenshots:
![Screenshot from 2019-10-01 17-33-34](https://user-images.githubusercontent.com/38970634/66018088-3fcf8680-e4fb-11e9-8faa-278553c3a778.png)

![Screenshot from 2019-10-01 17-33-28](https://user-images.githubusercontent.com/38970634/66018093-4231e080-e4fb-11e9-869f-41e549fce9bd.png)

**Comment by chamilaadhi** [comment]
Due to latency, etc, you won't be able to get 100% accuracy for throttling. were you able to get a throttled out message after passing some additional requests or you didn't see any throttle out message at all?

**Comment by SabinaPrasadhi** [comment]
After passing some additional requests I was able to see a throttled out message.
