### ISSUE TITLE
Error logged while deploying sample api

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6097]
**Steps to reproduce**
deploy sample api in publisher.
Log will be printed as below:
`[2019-10-02 10:03:39,449] ERROR - EndpointAdminServiceClient Error while removing endpoints for updating endpoints. Endpoints not found`

**version**
3.0.0

**Comment by chamilaadhi** [comment]
Not seen in 3.0.0 beta
