### ISSUE TITLE
Adding special charaters to the label name

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6100]
When we create new API we are only allowed to use a-z A-Z and 0-9. But when we creating a label by the admin portal it allows using some special characters like

1.  (    ) brackets
2.  [     ] square brackets
3.  / forward slash
4.  : colon
5.  ` back quote
6. - dash
7.  _ underscore
8.  ? question mark

![Screenshot from 2019-10-02 14-10-51](https://user-images.githubusercontent.com/51467737/66030156-66eb7f80-e51e-11e9-87c8-3d8b76370775.png)

**Comment by nalakas** [comment]
By adding this limitation might need to migrate existing users.
