### ISSUE TITLE
Cannot remove or add roles for an scope of an API when editing

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6101]
Cannot remove an existing role or add a new role for a scope of an API. Nothing will happen if I click on the close icon(x) or type a role and press enter.

![Screenshot from 2019-10-03 15-30-41](https://user-images.githubusercontent.com/35653110/66117964-dfbc0b80-e5f2-11e9-89cf-2f2665c751c9.png)

**Comment by ashera96** [comment]
This behavior can be seen for REST APIs, GraphQL APIs and SOAP APIs as well.

**Comment by chamilaadhi** [comment]
Edit scope is not provided in previous versions. Need to remove this button

**Comment by ruks** [comment]
@chamilaa yes this is a new improvement. Since Rest API supports this and this is worked earlier, I have fixed this.
Fixed https://github.com/wso2/carbon-apimgt/pull/7397.
