### ISSUE TITLE
UI is not responsive and items are not well alligned

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6105]
**Description**

- The spacing between items and the margin seem not enough as in the following screenshot (When the I resized the browser window)

![image](https://user-images.githubusercontent.com/44407066/66022050-5204f100-e50a-11e9-93b4-1997f3cf7410.png)

**Comment by chamilaadhi** [comment]
This ui is refactored in 3.0.0 beta
