### ISSUE TITLE
Separator goes away when the username is long

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6107]
![image](https://user-images.githubusercontent.com/3960742/66023149-ede42c00-e50d-11e9-82db-0a9559b3c89d.png)

**Comment by chamilaadhi** [comment]
similar issue https://github.com/wso2/product-apim/issues/6029

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7582
