### ISSUE TITLE
Issue when having a duplicate name in the lable 

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6111]
When we use a duplicate name when a label is created it gives a back end error. it is better is we can display an error like "The name is duplicated" under the label name field. 

![Screenshot from 2019-10-02 13-52-56](https://user-images.githubusercontent.com/51467737/66029371-cb0d4400-e51c-11e9-8ae1-7815cfaa99a5.png)

**Comment by nalakas** [comment]
This PR contains the fix for handling error https://github.com/wso2/carbon-apimgt/pull/7524
