### ISSUE TITLE
[devportal] Users can allocate applications to groups which are not existing.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6114]
When application sharing is enabled and when user is creating an application to share, users can enter organization groups which are not existing. 
Due to this, if user enters mistakenly a different organization name it will get assigned and no error message will be shown to the user.

![image](https://user-images.githubusercontent.com/40932779/66030688-846d1900-e51f-11e9-8484-e59c93b053a3.png)

**Comment by dushansilva** [comment]
As discussed offline will not be doing this as we do not keep a list of valid organizations
