### ISSUE TITLE
[Publisher] Certificates cannot be added for production or sandbox endpoints.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6115]
![Screenshot from 2019-10-02 14-21-48](https://user-images.githubusercontent.com/31464477/66031187-82578a00-e520-11e9-904e-00cd7aa980fb.png)
**Issue**
In Endpoints page,If we click "Add Certificate" option,after giving production endpoint or sandbox endpoint it gets following error.
![Screenshot from 2019-10-02 14-20-50](https://user-images.githubusercontent.com/31464477/66031190-84214d80-e520-11e9-85dd-2562f276862f.png)

**Comment by chamilaadhi** [comment]
certificate related issues https://github.com/wso2/product-apim/issues/6041, https://github.com/wso2/product-apim/issues/6056, https://github.com/wso2/product-apim/issues/6197, https://github.com/wso2/product-apim/issues/6168, https://github.com/wso2/product-apim/issues/6177, https://github.com/wso2/product-apim/issues/6144, https://github.com/wso2/product-apim/issues/6131
