### ISSUE TITLE
Can not upload a WSDL file

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6117]
- The WSDL file is not uploading. Nothing happens when I selected a valid WSDL file.
![Screenshot from 2019-10-02 14-46-55](https://user-images.githubusercontent.com/44407066/66032703-8042fa80-e523-11e9-8212-7fd57257e527.png)

**Comment by chamilaadhi** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/7229
