### ISSUE TITLE
Can not upload a WSDL archive file

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6118]
- Nothing happens when I selected a WSDL archive file.

![Screenshot from 2019-10-02 14-49-52](https://user-images.githubusercontent.com/44407066/66032918-e92a7280-e523-11e9-9d99-c57d147f20fe.png)

**Comment by chamilaadhi** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/7229
