### ISSUE TITLE
[Devportal] Throttle APIs based on HTTP request headers exceeds the defined limit

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6122]
When defining the Header condition under advanced policies in admin portal with request limit of 5 requests per minute, then testing through jmeter, it exceeds the defined limit of 5 requests per minute and accepts upto 47 requests within a minute.
![Screenshot from 2019-10-02 14-49-52](https://user-images.githubusercontent.com/54226167/66033642-4c68d480-e525-11e9-985b-dc43360278b0.png)
![Screenshot from 2019-10-02 14-47-28](https://user-images.githubusercontent.com/54226167/66033663-568ad300-e525-11e9-9475-7abbd8bb1815.png)

**Comment by chamilaadhi** [comment]
You won't be able to get 100% accuracy for High TPS scenarios with a low throttling limit. What you could do is apply a low Burst Control (Rate Limiting) limit for the subscription policy to work with this. that way we could reduce the exceeding requests
