### ISSUE TITLE
[Store/Error] While subscribing to an API 

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6123]
Soon After creating an Application and tries to subscribe to an  API with that application sometimes the subscriber button is not working and no error message is shown to the end user.. Following logs in the browser console.

![Screenshot from 2019-10-02 14-56-01](https://user-images.githubusercontent.com/42222921/66034254-8a1a2d00-e526-11e9-8f0c-d25aebea9a65.png)

**Comment by isharac** [comment]
@VimukthiMayadunne 
We have done a fix in https://github.com/wso2/carbon-apimgt/pull/7230
DO you observe the issue in the latest pack?

**Comment by VimukthiMayadunne** [comment]
Issue has been fixed
