### ISSUE TITLE
[Publisher] Can add more than one certificate to one production or sandbox endpoint.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6131]
![Screenshot from 2019-10-02 15-31-07](https://user-images.githubusercontent.com/31464477/66036298-85577800-e52a-11e9-89d0-1271a98fb1c6.png)
![Screenshot from 2019-10-02 15-31-36](https://user-images.githubusercontent.com/31464477/66036306-88526880-e52a-11e9-8c06-f465db578703.png)
![Screenshot from 2019-10-02 15-31-39](https://user-images.githubusercontent.com/31464477/66036313-8be5ef80-e52a-11e9-81ee-5fc948f6a4da.png)
**Issue**
Can add more than one certificate with different Alias to one production or sandbox endpoint.

**Comment by kavishkafernando** [comment]
This is the expected behaviour.
