### ISSUE TITLE
[devportal] API rating update not reflected in the top navigation bar of the API review

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6136]
When API rating is not updated it's not reflected in the top navigation pane. But it updates after refreshing the page.

### ** It shows as not rated even after editing rates.**

![image](https://user-images.githubusercontent.com/40932779/66040406-f308a180-e534-11e9-8eab-87e9dcac9040.png)

**Comment by tharikaGitHub** [comment]
This issue is already fixed in the latest API Manager pack. Hence closing the issue.
