### ISSUE TITLE
[Devportal] Spelling mistake under "Contact Us" in Home page.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6137]
There is a spelling mistake under "Contact Us" in the home page of Dev portal. Under the message area word 'write' is written as 'wirte'.

![Screenshot from 2019-10-02 16-52-25](https://user-images.githubusercontent.com/54613992/66040547-5d214680-e535-11e9-89a3-5bf73ab4173b.png)

**Comment by nirmal070125** [comment]
I think the bigger question is whether there's a need for a home page. It currently has some default html. 
<img width="1669" alt="Screen Shot 2019-10-02 at 9 44 13 AM" src="https://user-images.githubusercontent.com/413016/66049366-4bba4900-e4f9-11e9-8c23-d4755a43c328.png">
Is this a mistake?
