### ISSUE TITLE
[Publisher] Can create,publish & subscribe an API without specifying a failover endpoint when the failover endpoints is selected.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6141]
![Screenshot from 2019-10-02 17-20-53](https://user-images.githubusercontent.com/31464477/66042080-1e8d8b00-e539-11e9-9cb4-68b9fbe3ed5c.png)
![Screenshot from 2019-10-02 17-13-43](https://user-images.githubusercontent.com/31464477/66041850-88f1fb80-e538-11e9-9983-ef40ac2e37f0.png)
**Issue**
Can create,publish & subscribe an API successfully without specifying a failover endpoint,when the failover option is selected in the Endpoints page.

**Comment by menakaj** [comment]
Duplicate https://github.com/wso2/product-apim/issues/6455
