### ISSUE TITLE
[Publisher] Error while creating an API from importing a swagger definition via URL

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6142]
Test case:
Creating an API by providing a link to an invalid OAS 2.0 document to API definition should be prevented.

Description:
When tries to complete the above test scenario following massage is displayed in the 3.0 UI but more descriptive error massage is shown in the 2.6 U

[1]Error Shown in the 3.0 UI
![Screenshot from 2019-10-02 17-18-37](https://user-images.githubusercontent.com/42222921/66042198-75936000-e539-11e9-8fc8-b3600a4ce539.png)

[2]Error shown in the 2.6 UI
![Screenshot from 2019-10-02 17-18-30](https://user-images.githubusercontent.com/42222921/66042230-893ec680-e539-11e9-96a2-ea1d06e18018.png)

[3]Log

![Screenshot from 2019-10-02 17-25-05](https://user-images.githubusercontent.com/42222921/66042252-978ce280-e539-11e9-9792-c53d67abd85f.png)

**Comment by isharac** [comment]
The error shown in the 3.0.0 UI is meaningful since we have provided a supported version, but the doc is invalid.
We can check the feasibility of improving the message to state 'The document is invalid. Please re-import with a valid document'

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta.
