### ISSUE TITLE
[Store] Issue with the comment visibility when not logged in

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6146]
As shown in the screenshot below, there is a comment which was added by the super tenant admin. This is visible when logged in with admin admin credentials as shown below.

![11](https://user-images.githubusercontent.com/30475839/66043324-7ed1fc00-e53c-11e9-9df6-ade999b0bdc6.png)

When not logged in (when logged out of admin), the already added comments are not 
displayed. Here all added comments should be visible even if logged in or not.

![22](https://user-images.githubusercontent.com/30475839/66043336-82fe1980-e53c-11e9-808b-d75b45136bdf.png)

**Comment by ashera96** [comment]
Also, these comments are not visible under the Comments section in the Overview page when no user is logged in

**Comment by isharac** [comment]
@ashera96 
Are the comments visible once a user is logged in?

**Comment by ashera96** [comment]
@isharac 
Yes, the comments are visible when a user is logged in. They seem to disappear only when no one is logged into the developer portal

**Comment by chamilaadhi** [comment]
This needs to be public. also overview does not indicate there are comments even with or without login in 
<img width="793" alt="Screen Shot 2019-10-11 at 9 46 12 AM" src="https://user-images.githubusercontent.com/4861150/66624038-1bb32a00-ec0c-11e9-91b4-bd0a7e245459.png">
