### ISSUE TITLE
[Publisher] Icons are not placed properly under "Select an icon from the Material Icons for you api".

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6152]
For some categories, Icons are not placed in proper manner. And first option under "Select a Background" is not working.

![Screenshot from 2019-10-03 09-55-34](https://user-images.githubusercontent.com/54613992/66099425-79b88f80-e5c4-11e9-8e03-1c003bfd291e.png)

**Comment by chamilaadhi** [comment]
First option is working. 
<img width="532" alt="Screen Shot 2019-10-11 at 8 28 25 AM" src="https://user-images.githubusercontent.com/4861150/66621297-3d5ae400-ec01-11e9-9cfe-70e8f55a9bf8.png">
