### ISSUE TITLE
[Publisher] Upload option is not working under API's Icon.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6156]
When click the upload option,it directs to something like this,

![Screenshot from 2019-10-03 10-13-42](https://user-images.githubusercontent.com/54613992/66099941-8211ca00-e5c6-11e9-8f05-5ce503ad7b83.png)

![Screenshot from 2019-10-03 09-54-49](https://user-images.githubusercontent.com/54613992/66099825-03b52800-e5c6-11e9-9a1a-a9ea89734115.png)

**Comment by ruks** [comment]
Not reproducible. Hence closing.
