### ISSUE TITLE
[Publisher] API Icon change is not reflected in APIs' list view.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6157]
After changing the API's icon, change is not reflected in API's list view.

![Screenshot from 2019-10-03 10-24-21](https://user-images.githubusercontent.com/54613992/66100305-0fa1e980-e5c8-11e9-9d3b-5749e46c7374.png)

![Screenshot from 2019-10-03 10-24-45](https://user-images.githubusercontent.com/54613992/66100306-0fa1e980-e5c8-11e9-8ac3-fee5e98856e0.png)

**Comment by chanaka3d** [comment]
Will be fixed with https://github.com/wso2/carbon-apimgt/pull/7679
