### ISSUE TITLE
APIs based on a SOAP service are not invokable

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#6158]
* Try to create an API using WSDL.
* Publish the API and subscribe and try to test.
* API request fails with 
`
ERROR - OAuthAuthenticator Swagger is missing in the gateway. Therefore, JWT authentication cannot be performed.
WARN - APIAuthenticationHandler API authentication failure due to Internal Server Error
`
Reason being the relevant local entry which contains the swagger definition is not getting created.

Seeing in 3.0 alpha2.

**Comment by chamilaadhi** [comment]
fixed in AM 3.0.0 beta.
