### ISSUE TITLE
Can't upload an image as the API icon

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#6160]
* Edit an existing API.
* Try to change the icon.
* Click on "upload" and the UI goes to following error page;

<img width="1301" alt="Screen Shot 2019-10-03 at 1 05 48 AM" src="https://user-images.githubusercontent.com/413016/66100797-52d56b80-e57a-11e9-95f8-ac279dd86849.png">

**Comment by AmaliMatharaarachchi** [comment]
This was fixed with https://github.com/wso2/carbon-apimgt/pull/7227
