### ISSUE TITLE
[Documentation] Missing step in RESTFull API

### ISSUE THREAD

**Issue by shananjana** [wso2/product-apim#6162]
When we directly go the Restfull API and click on either Store API or Admin API, in the Getting Started section this note is missing.

Note: The consumer key and consumer secret keys must be Base64 encoded in the format `consumer-key:consumer-secret`

This is there in the Publisher API  Getting Started section. But if a user directly goes to Store API or Admin API this Base 64 encoding step is not mentioned in there.

**Comment by HiranyaKavishani** [comment]
Closing the issue as it is not reproducing now
