### ISSUE TITLE
[Devportal] Created APIs are not in order.

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6163]
The created APIs in Devportal are neither in alphabetical order nor created order. So it is hard to search for an API in the store.
![Screenshot from 2019-10-03 10-58-01](https://user-images.githubusercontent.com/54226167/66101609-1d0da280-e5cd-11e9-89cb-4fb868023c5d.png)

**Comment by chamilaadhi** [comment]
Fixed in 3.0.0 beta
<img width="1281" alt="Screen Shot 2019-10-11 at 8 24 40 AM" src="https://user-images.githubusercontent.com/4861150/66621129-a130dd00-ec00-11e9-8382-780b40ab8c57.png">
