### ISSUE TITLE
problem when we create 2 gateway environments with same name.

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6165]
If we make 2 different types of gateway environments with the same name it shows only one gateway Environment in the publisher. It doesn't display any notice or error while executing the code. 

![Screenshot from 2019-10-03 11-03-16](https://user-images.githubusercontent.com/51467737/66102032-922da780-e5ce-11e9-9f09-a4ca99c7fa2c.jpg)

![Screenshot from 2019-10-03 11-08-08](https://user-images.githubusercontent.com/51467737/66102048-9bb70f80-e5ce-11e9-8ebd-98b764780eef.png)

**Comment by chamilaadhi** [comment]
Obvious user configuration issue.
