### ISSUE TITLE
[Publisher] Issue regarding the alignment of subscriptions, while creating an API

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6166]
The alignment of the subscription drop down is not in alphabetical order, while creating an API.

![Screenshot from 2019-10-03 11-07-45](https://user-images.githubusercontent.com/38970634/66102112-d3be5280-e5ce-11e9-9966-d30a78402e70.png)

**Comment by kavishkafernando** [comment]
Duplicate https://github.com/wso2/product-apim/issues/5838
