### ISSUE TITLE
Filter button not working in APIM Publisher

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6167]
**Steps:**
1. Login to the API Publisher and navigate to the API listing page.
2. Click on the API listing button and then click on the API filter button.
3. Apply any filter available.

**Issue:**
All available APIs will be listed without filtering.

![Screenshot from 2019-10-03 11-12-34](https://user-images.githubusercontent.com/35653110/66102163-f94b5c00-e5ce-11e9-918a-5e8e535d9a75.png)

**Comment by chamilaadhi** [comment]
Related issues https://github.com/wso2/product-apim/issues/6087 , https://github.com/wso2/product-apim/issues/5932
