### ISSUE TITLE
Fix Exception logic to be compatible with the standard

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#6172]
All exception throwing/handling code needs to be fixed in order to be compatible with the standard that has been documented[1]

This is essential to ensure that correct error messages and response codes are sent from the REST API.

[1] https://github.com/wso2/carbon-apimgt/wiki/Exception-handling-in-REST-APIs

**Comment by malinthaprasan** [comment]
To be prioritize and fix after APIM 4.0 release
