### ISSUE TITLE
[Devportal] APIs' details are not organized properly.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6174]
APIs' version and context are not placed in proper manner as follows. 

![Screenshot from 2019-10-03 11-41-10](https://user-images.githubusercontent.com/54613992/66103376-28fc6300-e5d3-11e9-938c-ef058a4120e8.png)

**Comment by isharac** [comment]
Duplicate with https://github.com/wso2/product-apim/issues/6230
