### ISSUE TITLE
SDK interface design should be improved in Developer Portal

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6176]
The SDK tab of an API is displayed as below in the developer portal when the user is not signed in. UI design should be improved. Also, the logo and the text of the warning message is not properly aligned.

![Screenshot from 2019-10-03 11-54-17](https://user-images.githubusercontent.com/35653110/66104243-8c879000-e5d5-11e9-8ee8-49629d286908.png)

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7643
