### ISSUE TITLE
[Store] Align issue in the responses description.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6178]
![Screenshot from 2019-10-03 12-01-08](https://user-images.githubusercontent.com/31464477/66104354-eee09080-e5d5-11e9-8b7c-2664c0043141.png)
**Issue**
In Test page,responses description is not aligned with the responses code.

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="1215" alt="Screen Shot 2019-10-11 at 12 03 43 PM" src="https://user-images.githubusercontent.com/4861150/66629394-3f33a000-ec1f-11e9-8165-c7658c14bec0.png">
