### ISSUE TITLE
Alignment issue in Developer Portal

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6181]
The alignment of subscription buttons should be properly organized in the "Subscriptions" tab of an Application.

![Screenshot from 2019-10-03 12-21-43](https://user-images.githubusercontent.com/35653110/66105300-bdb58f80-e5d8-11e9-958e-e42199422a6f.png)

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="1414" alt="Screen Shot 2019-10-11 at 12 09 18 PM" src="https://user-images.githubusercontent.com/4861150/66629951-cfbeb000-ec20-11e9-8123-5550ec4f5268.png">
