### ISSUE TITLE
[Publisher] Cancel option is not working

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6182]
When change the icon for API, I clicked cancel option to cancel the changes I have made. But until refresh the page, it shows the changes.

![Screenshot from 2019-10-03 12-35-17](https://user-images.githubusercontent.com/54613992/66106140-cad37e00-e5da-11e9-8f39-710cddc7d556.png)

**Comment by chamilaadhi** [comment]
fixed in https://github.com/wso2/product-apim/issues/5641
