### ISSUE TITLE
[Publisher] A user with creator role cannot edit Backend Throughput fields

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6185]
A user with creator permission only cannot edit the 'Max Production TPS' or 'Max Sandbox TPS' fields of the 'Specify' option of Backend Throughput, in the configuration page.

![image](https://user-images.githubusercontent.com/47671237/66111423-76360000-e5e6-11e9-8421-114edd82d24c.png)
![image](https://user-images.githubusercontent.com/47671237/66111448-864ddf80-e5e6-11e9-9e64-4d02f212add5.png)

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7311
