### ISSUE TITLE
[Publisher] Can not update API with mock endpoint

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6187]
![Screenshot from 2019-10-03 14-19-53](https://user-images.githubusercontent.com/31029812/66112667-e776b280-e5e8-11e9-9d4c-467c35653a26.png)
![Screenshot from 2019-10-03 14-14-27](https://user-images.githubusercontent.com/31029812/66112673-eb0a3980-e5e8-11e9-83a7-bcf2896bca4a.png)

When I tried to update my API with a mock endpoint, it gives me above error in the log

**Comment by chamilaadhi** [comment]
Seems like the double quotations are causing the issue.
need to set the payload as following
      mc.setProperty('CONTENT_TYPE', 'application/json');
      mc.setPayloadJSON('{ "data" : "sample JSON"}');
