### ISSUE TITLE
[DevPortal/Bug] Sorting not working in the applications page

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6188]
Description: Sorting only works correctly in the Edit application column.
![Screenshot from 2019-10-03 14-20-21](https://user-images.githubusercontent.com/42222921/66112957-6ff55300-e5e9-11e9-9141-54b6048e419e.png)

**Comment by chamilaadhi** [comment]
Works in AM 3.0.0 beta
