### ISSUE TITLE
[Publisher] Displaying incorrect no.of API products

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6189]
When API products are deleted, the products are no longer displayed in the API Products page, but the count is not updated at the top left corner.

Here I have created 2 API products and deleted 1, but it still shows "Displaying 2 API Product(s)", which should be shown as 1.

![Screenshot from 2019-10-03 14-17-46](https://user-images.githubusercontent.com/54226167/66112844-391f3d00-e5e9-11e9-8e0d-dd395a739ed7.png)

**Comment by tharikaGitHub** [comment]
This issue is intermittent and can be observed for APIs Listing as well.

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7513
