### ISSUE TITLE
Throttle APIs based on JWT claims exceeds the defined limit

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6190]
Use Case: Limit access based on user attributes

Details of the Issue: When JWT claims were specified for the newly added throttling policy with the condition to allow 2 requests per minute, 6 simultaneous hits were successful.

![Screenshot from 2019-10-03 13-55-59](https://user-images.githubusercontent.com/38970634/66113169-e42ff680-e5e9-11e9-9c31-0a23910914ef.png)

![Screenshot from 2019-10-03 14-27-55](https://user-images.githubusercontent.com/38970634/66113230-06297900-e5ea-11e9-8348-c324eba65241.png)

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version
