### ISSUE TITLE
[publisher] Business view's email fields not get validated

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6191]
Users can enter wrong email formats and system accepts them as valid email addresses.

![image](https://user-images.githubusercontent.com/40932779/66113475-7637ff00-e5ea-11e9-860b-344789d8b437.png)

**Comment by chamilaadhi** [comment]
fixed in 3.0.0 beta
<img width="845" alt="Screen Shot 2019-10-11 at 2 37 47 PM" src="https://user-images.githubusercontent.com/4861150/66639585-baec1780-ec34-11e9-93cf-0985df23c645.png">
