### ISSUE TITLE
[Devportal] Spelling mistake and words are repeating under API Credentials in APIs overview page

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6192]
Under API Credentials, there is a spelling mistake and words are repeating.

![Screenshot from 2019-10-03 14-33-49](https://user-images.githubusercontent.com/54613992/66113715-f65e6480-e5ea-11e9-8e37-3982117e07f1.png)

**Comment by tharikaGitHub** [comment]
In the latest pack, the UI for API Credentials is different.
