### ISSUE TITLE
[publisher] Resources view's rate limiting policies are not ordered properly.

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6193]
Limiting policies are not not sorted in proper manner and they appear as a random ordering style.

![image](https://user-images.githubusercontent.com/40932779/66115082-c2387300-e5ed-11e9-82b8-ba6bd544cc42.png)

**Comment by chamilaadhi** [comment]
related issue https://github.com/wso2/product-apim/issues/6166
