### ISSUE TITLE
[Publisher] Text alignment issues in "Roles" text box in Update scope page

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6194]
**Description**
Text entered in to the "Roles" textbox when editing a scope, does not aligned properly within the text box area. The first seven characters will align properly and if more characters were added, the whole text goes out of alignment.

![roles](https://user-images.githubusercontent.com/27700915/66115599-c5802e80-e5ee-11e9-8682-f7efcb4e3e21.png)

**Comment by ruks** [comment]
<img width="1035" alt="Screen Shot 2019-10-09 at 2 05 14 PM" src="https://user-images.githubusercontent.com/1345278/66465180-00c2a780-ea9e-11e9-9fb3-50fb44b8274c.png">

Fixed in https://github.com/wso2/carbon-apimgt/pull/7397
