### ISSUE TITLE
[Publisher] Certificates in formats other than jks or crt can be added.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6197]
![Screenshot from 2019-10-03 15-27-15](https://user-images.githubusercontent.com/31464477/66117641-a5526e80-e5f2-11e9-8864-ba8e31075598.png)
**Issue**
In Endpoints page,certificates in format other than .jks or .crt can be added successfully.

**Comment by chamilaadhi** [comment]
duplicate https://github.com/wso2/product-apim/issues/5846
