### ISSUE TITLE
[Publisher] An existing SOAP API cannot be edited using a new WSDL url or file

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6198]
There is no place to edit the WSDL url or WSDL file of a created or published SOAP API at the publisher. 

For an existing SOAP API, the following tasks cannot be done.

Update the API with a new WSDL 1.1 URL
Update the API with a new WSDL 2.0 URL
Edit with an invalid WSDL url
Update the API with a new WSDL file
Update the API with a new WSDL archive

**Comment by chamilaadhi** [comment]
Editing is not supported. SOAP API is created using the provided WSDL. modifying the WSDL means changing the API. If you want to do it, you have to delete the api and create it again (since allowing to modify would cause inconsistencies between the Created API and the WSDL).
