### ISSUE TITLE
[Public] Can not create API with WSDL 2.0 URL

### ISSUE THREAD

**Issue by Uvindu96** [wso2/product-apim#6199]
![Screenshot from 2019-10-03 16-38-33](https://user-images.githubusercontent.com/31029812/66122062-65908480-e5fc-11e9-9bb0-d1c09bf1dd5e.png)

can not create APIs with a WSDL 2.0 URL, gives an error message.
WSDL URL: https://www.w3.org/2007/06/wsdl/wsdl20.xsd?wsdl

**Comment by chamilaadhi** [comment]
APIM supports only WSDL 1.1 (see doc https://docs.wso2.com/display/AM260/Generate+REST+APIs+from+SOAP+Backends)
