### ISSUE TITLE
[Dev Portal] Exception in the terminal when updating ratings

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim#6200]
**Steps:**
1. Login to the Dev Portal (using admin account).
2. Click on an API and add a rating on the overview page.
3. Try to change the rating by clicking on a star icon.

**Issue:**
An exception will be printed in the terminal. However, the ratings won't be updated. In order to update the rating, I have to remove it and then add a new rating.

![Screenshot from 2019-10-03 16-25-15](https://user-images.githubusercontent.com/35653110/66122110-848f1680-e5fc-11e9-9215-10acfc5f72b8.png)

**Comment by sanjulamadurapperuma** [comment]
Duplicate issue at [wso2/product-apim#5769](https://github.com/wso2/product-apim/issues/5769) and already been fixed at [wso2/carbon-apimgt#7335](https://github.com/wso2/carbon-apimgt/pull/7335).

**Comment by ThaminduDilshan** [comment]
fixed
