### ISSUE TITLE
Issue when we add options as Resources from Publisher UI

### ISSUE THREAD

**Issue by ShanJayaweera** [wso2/product-apim#6206]
When we add OPTIONS as a Resource it shows that API is updated successfully. But the resource list is not getting updated.

![Screenshot from 2019-10-03 17-09-52](https://user-images.githubusercontent.com/51467737/66124419-f6b62a00-e601-11e9-9a7a-ca0cb67f9e9b.png)
![Screenshot from 2019-10-03 17-07-33](https://user-images.githubusercontent.com/51467737/66124425-f9188400-e601-11e9-9557-48489df6c054.png)

**Comment by chamilaadhi** [comment]
Fix in 9th October build

<img width="641" alt="Screen Shot 2019-10-09 at 4 29 11 PM" src="https://user-images.githubusercontent.com/4861150/66475940-fe6a4880-eab1-11e9-9bba-4eba162072f3.png">
