### ISSUE TITLE
Readonly(Stats view) Role for Publisher

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-apim#6212]
When the APIs are published through CICD there should be a read-only role for people who want to see statistics. It is not desirable to assign people to a publisher/creator roles just for viewing stats since they could mesh up CICD created APIs. It is good to have a role to view the stats of all the APIs

**Comment by chamilaadhi** [comment]
We have moved stats from publisher/store to the dashboards in analytics. This usecase can be achieved from there
