### ISSUE TITLE
[Publisher] Issue when trying to delete all resources from an already published API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6214]
When trying to delete all resources from an already published API, first time gives an error as shown below.

![Screenshot from 2019-10-03 17-26-44](https://user-images.githubusercontent.com/30475839/66125293-3251f380-e604-11e9-91c7-dfbc6522f00e.png)

When trying to delete all again (for the second time), all resources successfully gets deleted.

![Screenshot from 2019-10-03 17-26-54](https://user-images.githubusercontent.com/30475839/66125296-34b44d80-e604-11e9-9cbb-9a72247967fb.png)

**Comment by ashera96** [comment]
Here the already published API can also reach a state where there are no resources, which should not be allowed.

**Comment by sanjulamadurapperuma** [comment]
This issue has already been fixed in [wso2/product-apim#7340](https://github.com/wso2/carbon-apimgt/pull/7340). Hence, this issue can be closed.
