### ISSUE TITLE
[Publisher] Improvement needed with the listing of the created scopes

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6216]
Once scopes are created for a given API, these created scopes are not shown in any order (looks to be random). One such example is shown below, where the order of creation of scopes are: "Scope 1", "Scope 2", "Scope 3", "Scope 4", "bar". But as shown below, they are not listed in any order.

![11111](https://user-images.githubusercontent.com/30475839/66181921-59ee9d80-e690-11e9-8bc8-4d761d29dde4.png)

**Comment by isharac** [comment]
+1 to sort the scopes by 'Name' by default.
