### ISSUE TITLE
[Publisher] Suggest available roles when trying to create a new scope

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6218]
When trying to create a new scope, under the "Roles", it is better to suggest the available roles to the user, rather than letting them type the entire role. This will make it more user-friendly and easier to use. For example, "publisher" is not a valid role, but "Internal/publisher" is valid. The user can only know for sure once they have typed the who text in and pressed enter.

![22222](https://user-images.githubusercontent.com/30475839/66182193-abe3f300-e691-11e9-8477-e5d65799663c.png)

**Comment by chamilaadhi** [comment]
purpose of setting the scope is to restrict resources based on some user roles. so when publisher comes to this page he already knows what roles he needs to set.
