### ISSUE TITLE
[Publisher] If a new user is assigned with a newly created user role, user's can't login to the publisher

### ISSUE THREAD

**Issue by Thidasala** [wso2/product-apim#6221]
Steps:
1. Create a new user role with all permissions using carbon
![Screenshot from 2019-10-04 10-07-00](https://user-images.githubusercontent.com/45654571/66182931-78ef2e80-e694-11e9-8e16-aa47dfd3df92.png)
![Screenshot from 2019-10-04 10-07-29](https://user-images.githubusercontent.com/45654571/66182932-7ab8f200-e694-11e9-8aa2-3b3a25562d21.png)

2. Assign a new user to the newly created user role
![Screenshot from 2019-10-04 10-21-07](https://user-images.githubusercontent.com/45654571/66182954-8f958580-e694-11e9-9b28-f6f8c7ff7d7f.png)

3. When the new user try to login to the publisher, follwoing error message displayed. 
![Screenshot from 2019-10-04 10-46-42](https://user-images.githubusercontent.com/45654571/66183014-db482f00-e694-11e9-9eb5-0f52f35a731c.png)

**Comment by chamilaadhi** [comment]
You need to add this role the tenant-conf.json file /_system/config/apimgt/applicationdata/tenant-conf.json under the relevent publisher scopes (say apim:api_publish, etc)
