### ISSUE TITLE
Publishing failure error message is empty

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6228]
![image](https://user-images.githubusercontent.com/3960742/66192598-726db080-e6ae-11e9-88b0-4ba272fc8016.png)

To reproduce this you can use invalid credentials in GW config and publish the API.

**Comment by tmkasun** [comment]
![image](https://user-images.githubusercontent.com/3313885/66829679-7e405900-ef71-11e9-889d-dc86b3997135.png)

**Comment by tmkasun** [comment]
![image](https://user-images.githubusercontent.com/3313885/67022259-93a6b600-f11e-11e9-879a-8a9719849e79.png)

Fixed in https://github.com/wso2/carbon-apimgt/pull/7538
