### ISSUE TITLE
[Publisher] Navigation arrow locates in a different position when drop downs are expanded

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6229]
![image](https://user-images.githubusercontent.com/40932779/66193276-d349b880-e6af-11e9-835e-44501e0e4c4a.png)

Above marked arrow get located in a different position when drop downs are expanded. 

![image](https://user-images.githubusercontent.com/40932779/66193658-b19d0100-e6b0-11e9-8454-9d0c2c615862.png)

**Comment by isharac** [comment]
@7slcode7 
Couldn't reproduce this.
In which browser you are experiencing this?

<img width="1032" alt="Screen Shot 2019-10-07 at 3 37 32 PM" src="https://user-images.githubusercontent.com/8057793/66303403-916f7b00-e918-11e9-9f55-08f69c3ea141.png">

**Comment by 7slcode7** [comment]
In Firefox browser and when the page zoom is 120% .

**Comment by kavishkafernando** [comment]
Can be reproduced in latest 3.1.0 pack as well in Firefox browser

<img width="1383" alt="Screen Shot 2020-01-03 at 4 17 35 PM" src="https://user-images.githubusercontent.com/19324135/71719512-9b841580-2e44-11ea-8a8f-a70e37f2de91.png">

**Comment by erangatl** [comment]
> Can be reproduced in latest 3.1.0 pack as well in Firefox browser
> 
> <img alt="Screen Shot 2020-01-03 at 4 17 35 PM" width="1383" src="https://user-images.githubusercontent.com/19324135/71719512-9b841580-2e44-11ea-8a8f-a70e37f2de91.png">

Actually issue is not reproduced  :)

**Comment by erangatl** [comment]
Cannot be reproduced even when zoomed.

![image](https://user-images.githubusercontent.com/20179540/75317284-9912ca80-588d-11ea-96ce-088ee21786a6.png)
