### ISSUE TITLE
[Store] UI issue with the API card listings

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6230]
Consider the API named "January" given in the below screenshot. Here the "Context" section needs to be aligned like the "Version". Also a few letters like "y", "j", etc. get cut down after a certain level as shown below.

![1](https://user-images.githubusercontent.com/30475839/66193679-bcf02c80-e6b0-11e9-9482-fa11397892d2.png)

**Comment by isharac** [comment]
It should looks consistent as in publisher

 
<img width="280" alt="Screen Shot 2019-10-07 at 12 56 27 PM" src="https://user-images.githubusercontent.com/8057793/66292475-097e7680-e902-11e9-8027-7649b2baa8ff.png">

**Comment by erangatl** [comment]
Context fixed in latest

![image](https://user-images.githubusercontent.com/20179540/66371934-588be080-e9c2-11e9-9e49-fa97e941613f.png)

**Comment by isharac** [comment]
@erangatl 
Could you please share the commit?

**Comment by sanjulamadurapperuma** [comment]
> It should looks consistent as in publisher
> 
> <img alt="Screen Shot 2019-10-07 at 12 56 27 PM" width="280" src="https://user-images.githubusercontent.com/8057793/66292475-097e7680-e902-11e9-8027-7649b2baa8ff.png">
> 
> Also, better if we change the positions of the version and context since context could be lengthy.

The position of the context and the version in Publisher has been fixed in [wso2/carbon-apimgt/pull#7271](https://github.com/wso2/carbon-apimgt/pull/7271)
