### ISSUE TITLE
[Store] Issue when loading the test page for an API after deleting all the wildcard resources

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6231]
After deleting all the wildcard resources for an API, at the devportal, the test page is not loading for that API. At the overview page, the resources field is showing 'loading'. Even after adding resources to the API, the same issue is there.

![image](https://user-images.githubusercontent.com/47671237/66193571-7dc1db80-e6b0-11e9-82ab-959697ef55f8.png)
![image](https://user-images.githubusercontent.com/47671237/66193604-903c1500-e6b0-11e9-9129-f5b1ce2050a6.png)
![image](https://user-images.githubusercontent.com/47671237/66193631-9df19a80-e6b0-11e9-807f-302292ebd2fc.png)

![image](https://user-images.githubusercontent.com/47671237/66193940-2cfeb280-e6b1-11e9-8b49-cd0a6c1cd5bf.png)

**Comment by chamilaadhi** [comment]
Not seen in AM 3.0.0 beta. now cannot remove all the resources (need to have atleast one)
