### ISSUE TITLE
DevPortal UI-Issue

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6234]
Description:
Details about the application in the /devportal/applications/{API-ID}/subscriptions page is unclear
![Screenshot from 2019-10-04 14-40-08](https://user-images.githubusercontent.com/42222921/66196066-87017700-e6b5-11e9-9d1e-7ccaef2c953e.png)

**Comment by erangatl** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7386
