### ISSUE TITLE
[devportal] API list view coulmn preferences can appear whithout any meaning

### ISSUE THREAD

**Issue by 7slcode7** [wso2/product-apim#6235]
When user customize API list view's  columns it can customized in a way to provide no meaning to the users.

![image](https://user-images.githubusercontent.com/40932779/66195921-4a358000-e6b5-11e9-9eb0-fd82cf0a9c5f.png)

**>___________________________________________________________**

![image](https://user-images.githubusercontent.com/40932779/66196007-6c2f0280-e6b5-11e9-89d9-1bb95ebc54a7.png)

**>___________________________________________________________**

![image](https://user-images.githubusercontent.com/40932779/66196074-8d8fee80-e6b5-11e9-873d-444f93c5fb4c.png)

**Comment by isharac** [comment]
May be we can mandate API Name, version

**Comment by chamilaadhi** [comment]
It is up to the user to select what he wan't to see
