### ISSUE TITLE
Error in Example Tab and Response Tab of the documentation regarding the "Changing the API endpoint URL via etcd"

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#6238]
In WSO2 API Microgateway documentation, the tabs ( Example Tab and Response Tab ) under the heading "Changing the API endpoint URL via etcd" seems to be stuck/ not working. All 3 tabs leads to the same content i.e. format.

Documentation Link: 
https://docs.wso2.com/display/MG301/Service+Discovery#response-auth-token

![Screenshot from 2019-10-04 15-07-10](https://user-images.githubusercontent.com/38970634/66197745-ab128780-e6b8-11e9-80be-79faa2e0d358.png)

**Comment by isharac** [comment]
@SabinaPrasadhi 
Please move this issue to https://github.com/wso2/product-microgateway repo

**Comment by SabinaPrasadhi** [comment]
Issue Moved to the above link.
