### ISSUE TITLE
[Publisher] [Store] Issue when searching a documentation from the unified search

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#6239]
In both publisher and store, when a query from the content of a document is entered for the unified search, after clicking the suggested item, the following error message can be seen even though the document is available for the API. 

![Screenshot from 2019-10-04 15-13-10](https://user-images.githubusercontent.com/47671237/66198219-91257480-e6b9-11e9-844a-bb2f8fbc4d01.png)
![Screenshot from 2019-10-04 15-13-31](https://user-images.githubusercontent.com/47671237/66198220-9256a180-e6b9-11e9-95d0-576e1ceb1a10.png)

**Comment by isharac** [comment]
URL should be changed to https://localhost:9443/publisher/apis/85c1b5d5-5c3d-4bc0-8114-ec8b15b51508/documents/cabe98eb-9a5d-4bb1-8aa3-407f45773dd8/**view** instead 
https://localhost:9443/publisher/apis/85c1b5d5-5c3d-4bc0-8114-ec8b15b51508/documents/cabe98eb-9a5d-4bb1-8aa3-407f45773dd8/**details**
