### ISSUE TITLE
[Devportal] Applications table header "Edit Application" is not suitable

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6240]
The first column header of Applications table under Store is named as "Edit Application", but it has no useful meaning. Preferred to have "Applications" or related heading.

![Screenshot from 2019-10-04 15-04-45](https://user-images.githubusercontent.com/54226167/66198398-f4afa200-e6b9-11e9-8605-9f3b7e00bca4.png)

**Comment by bhathiya** [comment]
This is now fixed. 

![Uploading image.png…]()
