### ISSUE TITLE
[Publisher] Issues when selecting an operational scope for an API resource

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6241]
**Description**
Once a scope was assigned for an API resource, it can not be unassigned. There is no option like "None" in the drop-down menu to clear the assigned scope for the resource. 

![scope_sselection](https://user-images.githubusercontent.com/27700915/66198647-7dc6d900-e6ba-11e9-9ec6-0e7bdab5dafb.png)

**Comment by isharac** [comment]
+1 to add ''None  to unset the scope.
Also, RESET button should clear the data in the fields and unset the scope.

**Comment by tharikaGitHub** [comment]
Related issue https://github.com/wso2/product-apim/issues/6370
