### ISSUE TITLE
[Publisher/Improvment] Adding a dialog box when Deprecate and Retiring an API

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6243]
Description:
Since Deprecating and Retiring API steps are cannot be undone and they are mission critical adding a dialog box asking the user for re-assurance is better.

**Comment by isharac** [comment]
+1

**Comment by chamilaadhi** [comment]
Since there is an image with arrows pointing, user can get an idea about the direction of the LC.

**Comment by VimukthiMayadunne** [comment]
Yes I agree. But what if the user accidentally press the button without any intention of pressing the  button. That happened to me once that is why I came up with the above suggestion
