### ISSUE TITLE
[Store] Issues when trying to subscribe to a new app

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6244]
As shown in the screenshot below, the "TEST" and "RESET" buttons are disabled for steps 1, 2, 3 and 4. These become active at the last step, but this will redirect the user back to step 1. Here the better option is to give that button at the last step as "RESTART", since once that 5th step is reached that application is already created. Also to remove the "TEST" and "RESET" button from the intermediate steps where they have no use.

Also when the close (X) button is clicked, at any intermediate step, the user should be notified that such an application is already created.

![2](https://user-images.githubusercontent.com/30475839/66198855-f75ec700-e6ba-11e9-8eec-b21b041c055a.png)

**Comment by isharac** [comment]
-1 to change the button to "RESTART" as the "TEST" and "RESET" buttons are disabled at first 4 steps.
But we need to make sure that RESET button properly rollbacks the created application.

It is intuitive that moving from one tab to the other completes it's task.
Anyway +1 to give an information message about what has been done and what to be done when the close button is clicked at an intermediate step.

@chanaka3d  thoughts?
