### ISSUE TITLE
[Publisher] The url of Gateways tab is named as environment

### ISSUE THREAD

**Issue by keshiha96** [wso2/product-apim#6245]
The url of the Gateways tab in the Publisher portal is referred as "/environment", which should be named to "/gateways"

![Screenshot from 2019-10-04 15-32-07](https://user-images.githubusercontent.com/54226167/66199632-a9e35980-e6bc-11e9-9c0e-f7cb263b3ae0.png)

**Comment by sanjulamadurapperuma** [comment]
This issue no longer persists as the 'Gateways' tab has been renamed to 'Environments'.

![image](https://user-images.githubusercontent.com/32578617/66624027-11912b80-ec0c-11e9-82ca-5abcd3ab8df7.png)
