### ISSUE TITLE
[Store] Issue when invoking API resource with a token obtained using password grant type

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6249]
**Description**

A valid access token which was generated using password grant provides a valid response instead of failing with the error code 401 when invoking a resource where the security type is set to "Application"

Test Case ID: 3.1.1.12

**Comment by chamilaadhi** [comment]
@nipunsampath how did you set the security type to 'Application' for the resource? Asking because in AM 3.0.0 this concept is not there. It has either secured or not only

**Comment by nipunsampath** [comment]
@chamilaadhi I set the `x-auth-type` to "Application" in swagger definition.

**Comment by chamilaadhi** [comment]
This Application/Application User separation is removed in AM 3.0.0. What is supported now whether the resource is, secured or not.  `x-auth-type: "None"` is considered as not secured and anything other than that (ex: Application, Application User) will be considered as secured. (to provide backward compatibility for APIs created from previous APIM version)
