### ISSUE TITLE
APIs with role based restricted give different message in tenant

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#6255]
If an API is restricted by roles and try to access it with store rest API, it gives a different response in super tenant and tenant.
This affect to test case org.wso2.am.integration.tests.api.lifecycle.APIVisibilityWithDirectURLTestCase

**super tenant**
{
    "code": 404,
    "message": "Not Found",
    "description": "Requested API with Id '42c21f53-ad4e-4227-a762-a36592f92093' not found",
    "moreInfo": "",
    "error": []
}

**tenant**
{
    "code": 403,
    "message": "Forbidden",
    "description": "You don't have permission to access the API with Id 87e63638-17d0-411e-9dc8-637c06435954",
    "moreInfo": "",
    "error": []
}

**Comment by vithu30** [comment]
Tested the same scenario in 2.6.0 as well. Same results are observed.
