### ISSUE TITLE
[Publisher] APIM 3.0.0 does not allow API name or context to have dashes

### ISSUE THREAD

**Issue by ayomawdb** [wso2/product-apim#6264]
APIM 3.0.0 has a UI level validation that prevents users from creating a URL with dashes ("-") in the "API name" or the "context". 

This makes it harder for users to migrate into the new version and will also conflict with API practices/guidelines followed by users (since using dashs in API name is a common practice). 

This was identified during @eufossa eu-hackathon-2019

**Comment by vithu30** [comment]
This is fixed in https://github.com/wso2/carbon-apimgt/pull/7390
