### ISSUE TITLE
APIM 3.0 Dev Portal "WSO2_AM_TOKEN_1" is NOT "http-only"

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-apim#6265]
The APIM 3.0 API security protection mechanism relies on a split access token approach with one part of the token stored as a secure, http-only cookie called "WSO2_AM_TOKEN_1". However, this cookie doesn't seem to contain the http-only flag.

This to be completed at @eufossa eu-hackathon-2019

**Comment by tmkasun** [comment]
Yes, there is an issue with setting `HttpOnly` flag via jaggery `addCookie` method,
Even though we set the flag in [cookie object](http://jaggeryjs.org/documentation.jag?api=response) , it's not getting reflected in the response headers (`set-cookie`)
![image](https://user-images.githubusercontent.com/3313885/66255752-0c178980-e7a5-11e9-9532-077613e36a43.png)

Either we need to fix the `addCookie` method or add `set-cookie` headers manually using `addHeader` method in jaggery.

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
