### ISSUE TITLE
[Store] Issue when invoking API resource with a token obtained using client_credentials grant type

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6271]
**Description**

A valid access token which was generated using client_credentials grant type provides a valid response instead of failing with the error code 401 when invoking a resource where the security type is set to "Application User"

Test Case ID: 3.1.1.13

**Comment by chamilaadhi** [comment]
@nipunsampath how did you set the security type to 'Application User' for the resource? Asking because in AM 3.0.0 this concept is not there. It has either secured or not only

**Comment by nipunsampath** [comment]
@chamilaadhi I changed the x-auth-type to "Application User" in swagger definition.

**Comment by tmkasun** [comment]
Can you please provide the error response that you are getting, and what is the value you provided for `x-auth-type`

**Comment by nipunsampath** [comment]
I have set `x-auth-type` as `x-auth-type: "Application User"`. Also, I'm getting a valid response, instead of an error message. Test Case ID: **3.1.1.13** in Testing with scenarios (google sheet) states that I should not be getting a valid response when invoking a API resource with **"Application User"**  security type using a token obtained using **client_credentials** grant.

**Comment by chamilaadhi** [comment]
This Application/Application User separation is removed in AM 3.0.0. What is supported now whether the resource is, secured or not.  `x-auth-type: "None"` is considered as not secured and anything other than that (ex: Application, Application User) will be considered as secured. (to provide backward compatibility for APIs created from previous APIM version)
