### ISSUE TITLE
[Publisher] Issues when invoking an API resource with custom authorization header

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6272]
**Description**

When using a custom authorization header for an API, invoking an API resource using the correct custom authorization header fails with error code `401 Unauthorized`.

**Error in the log**

`[2019-10-07 08:53:15,040]  WARN - APIAuthenticationHandler API authentication failure due to Missing Credentials`

**Comment by isharac** [comment]
@nipunsampath 
Please provide the request and response with header information to recreate the issue.

**Comment by nipunsampath** [comment]
**Request header**

```
> GET /electronics/1.0.0/* HTTP/1.1
> Host: localhost:8243
> User-Agent: curl/7.58.0
> accept: application/json
>  foo: Bearer f04be608-8e88-3133-a19c-0025bc687d51
```

**Response Header**

```
< HTTP/1.1 401 Unauthorized
< Access-Control-Expose-Headers: 
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: DELETE,POST,PUT,PATCH,GET
< WWW-Authenticate: OAuth2 realm="WSO2 API Manager", error="invalid_token", error_description="The access token expired"
< Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction, foo
< accept: application/json foo: Bearer f04be608-8e88-3133-a19c-0025bc687d51
< Content-Type: application/xml; charset=UTF-8
< Date: Mon, 07 Oct 2019 03:21:37 GMT
< Transfer-Encoding: chunked
```
The access token I used was not expired since I generated it about 2 or 3 minutes before. And I tested this multiple times using several tokens. However, It seems that now I cannot recreate the issue.
