### ISSUE TITLE
[Store] API can be accessible even if the authorization header does not follow the proper format

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#6273]
**Description**

API resources provides a valid response even when the authorization header in the request is in the following format.

`Authorization: Bearer <token>; Bearer <token>`

**Comment by chamilaadhi** [comment]
Please provide more information (screenshot maybe). Bit hard to understand the issue

**Comment by chamilaadhi** [comment]
Ok so you invoke the api with above header from a curl command?

**Comment by nipunsampath** [comment]
> Ok so you invoke the api with above header from a curl command?

I used postman for invoking. The authorization header is like this.  
`Bearer f04be608-8e88-3133-a19c-0025bc687d51;Bearer f04be608-8e88-3133-a19c-0025bc687d51`

**Comment by chamilaadhi** [comment]
Since this is a user issue, we could reduce the severity
