### ISSUE TITLE
Improve OAS definition to support Micro GW

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#6274]
At the moment follwing custom attributes are support in OAS definition. Please review and suggest if there is anything to improve.

`x-wso2-auth-header: "Authorization"`
`x-throttling-tier: "Unlimited"`
`x-wso2-cors: `
`  corsConfigurationEnabled: false`
`  accessControlAllowOrigins: `
`    - "*"`
`  accessControlAllowCredentials: false`
`  accessControlAllowHeaders: `
`    - "authorization"`
`    - "Access-Control-Allow-Origin"`
`    - "Content-Type"`
`    - "SOAPAction"`
`  accessControlAllowMethods: `
`    - "GET"`
`    - "PUT"`
`    - "POST"`
`    - "DELETE"`
`    - "PATCH"`
`    - "OPTIONS"`
`x-wso2-production-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`x-wso2-sandbox-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`x-wso2-basePath: "/sample/1.0.0"`
`  x-wso2-transports: `
`    - "http"`
`    - "https"`

For each endpoint type, it's configuration is as follows.

**HTTP**
`x-wso2-production-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`x-wso2-sandbox-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`

**HTTP failover**
`x-wso2-production-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`  endpoint_config: "failover"`
`x-wso2-sandbox-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`  endpoint_config: "failover"`

**HTTP load balance**
`x-wso2-production-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`  endpoint_config: "load_balance"`
`x-wso2-sandbox-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "http"`
`  endpoint_config: "load_balance"`

**SOAP** 
`x-wso2-production-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`
`x-wso2-sandbox-endpoints: `
`  url: "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`

**SOAP fialover** 
`x-wso2-production-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`
`  endpoint_config: "failover"`
`x-wso2-sandbox-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`
`  endpoint_config: "failover"`

**SOAP load balance** 
`x-wso2-production-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`
`  endpoint_config: "load_balance"`
`x-wso2-sandbox-endpoints: `
`  url: `
`    - "https://localhost:9443/publisher/apis/create/rest"`
`  endpoint_type: "address"`
`  endpoint_config: "load_balance"`

**Default endpoints**
`x-wso2-production-endpoints: `
`  endpoint_type: "default"`
`x-wso2-sandbox-endpoints: `
`  endpoint_type: "default"`

**Comment by Rajith90** [comment]
Could we change the 
endpoint_type: "http" -> type: "http"

**Comment by praminda** [comment]
Need `x-wso2-disable-security` to disable security for resources https://github.com/wso2/product-microgateway#microgateway-supported-open-api-extensions

**Comment by VirajSalaka** [comment]
Needs to change
url -> urls

**Comment by hasuniea** [comment]
x-throttling-tier: "Unlimited" 
This should be x-wso2-throttling-tier

**Comment by VirajSalaka** [comment]
whether a single endpoint or not, it has to be an array.
url: "https://localhost:9443/publisher/apis/create/rest" -> 
urls:
- "https://localhost:9443/publisher/apis/create/rest"

**Comment by VirajSalaka** [comment]
```
HTTP failover
x-wso2-production-endpoints:
url:
- "https://localhost:9443/publisher/apis/create/rest"
- "https://localhost:9443/publisher/apis/create/rest"
endpoint_type: "http"
endpoint_config: "failover"
```
needs to be changed to 
```
HTTP failover
x-wso2-production-endpoints:
url:
- "https://localhost:9443/publisher/apis/create/rest"
- "https://localhost:9443/publisher/apis/create/rest"
type: "failover"
```

**Comment by ruks** [comment]
> Need `x-wso2-disable-security` to disable security for resources https://github.com/wso2/product-microgateway#microgateway-supported-open-api-extensions

This information is already there under the name 'x-auth-type". Can we reuse that?

**Comment by ruks** [comment]
> x-throttling-tier: "Unlimited"
> This should be x-wso2-throttling-tier

This information is already there with name 'x-throttling-tier'. Can we resue it? otherwise there will be duplicate information in the swagger.

**Comment by Rajith90** [comment]
> x-throttling-tier

Right now micro gateway supports x-throttling-tier, hence it is a duplication of data, I assume we can keep it as it as

**Comment by Rajith90** [comment]
> x-auth-type

Yes we can use this extension, since we support it at MGW

**Comment by ruks** [comment]
This issue is fixed. Hence closing.
