### ISSUE TITLE
Create API funtionalities fail silently when logged in as a publisher

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-apim#6278]
A user with a publisher role is not allowed to create apis. But api create options are enabled for a user who has only the publisher role. And when click on the "Create" button, it throws a backend error "ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed" which is correct, but there is no any indication in the UI.

Either we have to disable / hide api creation flows to publisher users or show an error message upon clicking the create button. First approach would be good IMO.

**Comment by chamilaadhi** [comment]
API create button is disabled for publisher in https://github.com/wso2/carbon-apimgt/pull/7361
