### ISSUE TITLE
Error thrown when removing all resources from an API when the API is published

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#6293]
Steps to reproduce.
1. Create an API with default resources (/*).
2. Publish the API.
3. Go to the Resources section and try to remove all resources from the API. This will throw an error. The cause in the log says you need at least 1 resource for the API.

The above behaviour is due to the fact that the API is being re-published with 0 resources. This is not allowed in the system. We need to find a way to prevent the user from removing all resources in an API.

**Comment by tmkasun** [comment]
This issue is fixed in the APIM 3 beta

![image](https://user-images.githubusercontent.com/3313885/66974474-d2098a00-f0b8-11e9-82a8-464eaf29ccf9.png)

UI doesn’t allow to delete all the resources
