### ISSUE TITLE
Provide the swagger URL in Publisher REST API for api creation.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-apim#6294]
In automating the API creation process using Publisher REST APIs, for creating an API we can use the below API:

https://host:port/api/am/publisher/v0.11/apis.

But, in the request JSON we have to pass the swagger definition as a string in "apiDefinition" parameter.

It is much convenient to provide the swagger URL in request JSON instead of the entire swagger as a string.

**Comment by tmkasun** [comment]
With APIM 3.0 Publisher REST API (V1.0) you can provide the swagger URL with additional properties and create an API. Please refer the REST API V1.0 [documentation here](http://wso2.github.io/carbon-apimgt/apidocs/publisher/v1/#!/operations#APIs#importOpenAPIDefinition)

![image](https://user-images.githubusercontent.com/3313885/66749401-6e5c4280-eea7-11e9-81de-7fb7fbbb2cf1.png)
