### ISSUE TITLE
[Store] Issue when navigating to "TEST" after adding scopes to a GraphQL API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6297]
**Steps followed:**

1. Created a GraphQL API, and created 2 different scopes. Then added one scope each to 2 operations. Then saved the relevant changes.
2.  Moved to the developer portal and generated an access token with the 2 assigned scopes.
3. Navigated to the "TEST" tab. Then the page keeps on loading as shown in the screenshot below.

![Screenshot from 2019-10-08 10-47-57](https://user-images.githubusercontent.com/30475839/66369281-61c47f80-e9b9-11e9-9231-f5ef1a108ec5.png)

This is the error that is logged in the console.

![Screenshot from 2019-10-08 10-52-34](https://user-images.githubusercontent.com/30475839/66369367-c4b61680-e9b9-11e9-9315-4b24fb74bd3d.png)

**Comment by HiranyaKavishani** [comment]
This cannot be reproducible
