### ISSUE TITLE
JWT Token Revocation [Upgrade needed]

### ISSUE THREAD

**Issue by shananjana** [wso2/product-apim#6306]
We use ETCD v2 APIS to update the key values of a revoked token. But now v2 is just like a version that has deprecated. Suggest it would be better if we could upgrade to ETCD v3.

![imageedit_1_8321861770](https://user-images.githubusercontent.com/51467737/66385999-19b85380-e9df-11e9-93a0-d8d62d6f569a.png)

link :- https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImpl.java#L84

**Comment by tharindu1st** [comment]
ETCD based implementation no longer available.
