### ISSUE TITLE
[Store] Unnecessary horizontal scrollbar appear in overview and docs pages

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6307]
In the developer portal, an unwanted horizontal scrollbar appears in the overview page and in the docs page. This is not the case for the other pages. Shown in the below screenshot is one such page.

![aaaaa](https://user-images.githubusercontent.com/30475839/66386541-0954a880-e9e0-11e9-98f4-fe5b6f34baa0.png)

**Comment by ashera96** [comment]
Also as shown in the below screenshot, there appear to be 2 background images for the "comments" and "documents" sections under the overview page. 

![xxx](https://user-images.githubusercontent.com/30475839/66426067-afc79a80-ea2e-11e9-998b-c31edf4a1b6a.png)

But once a comment is added to that particular API, both the backgrounds disappear as shown below (Here since the documents section is still empty, the image should not dissapear).

![yyyy](https://user-images.githubusercontent.com/30475839/66426068-b2c28b00-ea2e-11e9-9db7-35efc90d1634.png)

**Comment by ashera96** [comment]
Consider a scenario where the admin is logged in and an API is selected. As shown below, under the API Credentials section, there is a subheading called "View Credentials". Here "1 Subscriptions" is a link, but it just looks like a text. Therefore suggestion is to improve the UI so that it is clearly visible that it is a link.

![xxx](https://user-images.githubusercontent.com/30475839/66443945-d30a3e00-ea5e-11e9-9226-c8dbb1371bee.png)

**Comment by ashera96** [comment]
Similarly when just a document is added the background should disappear, instead it remains as shown in the screenshot below. Also there should be a "SHOW MORE>>" option as indicated with "1", so that the user is redirected to the "DOCS" page.

![44](https://user-images.githubusercontent.com/30475839/66480304-fadbbf00-eabb-11e9-9558-dd268835a63f.png)

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7568

**Comment by chanaka3d** [comment]
This issue is fixed in the latest source
