### ISSUE TITLE
[Store] Issue with the message which is displayed when there are no APIs

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6321]
There is a grammar mistake with the message which is displayed when there are no APIs. Shown below is the screenshot, and the suggestion here is to turn it to "There are no APIs to show you right now."

![33](https://user-images.githubusercontent.com/30475839/66455982-e979bf00-ea89-11e9-8530-538411826a5d.png)

**Comment by menakaj** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7367
