### ISSUE TITLE
[devportal] Issues with the Get CURL to Generate Access Token

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#6330]
<img width="594" alt="Screen Shot 2019-10-09 at 4 29 22 PM" src="https://user-images.githubusercontent.com/8057793/66475952-04602980-eab2-11e9-936c-17e5d75427d0.png">

Sample curl command gives error
curl: (3) Port number ended with ' '

**Comment by chamindias** [comment]
Related issue: https://github.com/wso2/product-apim/issues/6461

**Comment by isharac** [comment]
@chanaka3d 
we need to get the  <TokenURL> in apimanager.xml here
need a space  in between the Authorization header and -H
consumer-key:consumer-secrete values are undefined:undefined once decoded.
need to set the correct values.

**Comment by isharac** [comment]
copied curl command port is incorrect and -H is missing before the Authorization header

**Comment by isharac** [comment]
clientid:clientSecrete is undefined:undefined

**Comment by chanaka3d** [comment]
This is fixed with the PR 7609
