### ISSUE TITLE
[Store] Issue with redirection when logging out of the portal

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6332]
Consider a scenario where there is only carbon.super tenant and admin is logged in using admin admin credentials. When the admin tries to log out, the admin is redirected to the /home page, which is no longer a page found in the main UI. As shown in the screenshot below, eventhough the menu no longer has a HOME option, user is redirected to that page. This works fine when an additional tenant is added.

![a](https://user-images.githubusercontent.com/30475839/66477462-ce24a900-eab5-11e9-8d50-9f6ffa0933a2.png)

**Comment by vithu30** [comment]
This is not observed in the latest built pack
