### ISSUE TITLE
WSO2 APIM 2.6.0 publishing APIs using RestAPIs gives API authentication failure due to No matching resource found in the API for the given request

### ISSUE THREAD

**Issue by 2437850** [wso2/product-apim#6333]
Using restAPIs, I am creating APIs in publisher and then I am publishing the APIs. Both of the functionalities are working fine. But, I do see one issue while invoking the API.

So to test it, I am subscribing to the API which is published and using correct token I am invoking it. While invoking the API for the first time, I am getting below error

TID: [-1234] [] [2019-10-08 14:58:16,370]  WARN {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} -  API authentication failure due to No matching resource found in the API for the given request {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler}

TID: [-1234] [] [2019-10-08 14:59:29,462]  WARN {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} -  API authentication failure due to No matching resource found in the API for the given request {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler}

This is response when I am getting when I am hitting API

<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
    <ams:code>900906</ams:code>
    <ams:message>No matching resource found in the API for the given request</ams:message>
    <ams:description>Access failure for API: /updatedroles/1.0.0, version: 1.0.0 status: (900906) - No matching resource found in the API for the given request. Check the API documentation and add a proper REST resource path to the invocation URL</ams:description>
</ams:fault>

After pressing Save button from /publisher node, API gets updated and the same resource paths are accessible

**Comment by tmkasun** [comment]
Can you please mention the API Manager version that you are using?

**Comment by 2437850** [comment]
@tmkasun : APIM version 2.6.0

**Comment by 2437850** [comment]
@tmkasun : 
Any update on this issue? is this valid scenario or am I missing anything?

**Comment by 2437850** [comment]
@malinthaprasan here is the API creation payload used
[APICreate_payload.json.txt](https://github.com/wso2/product-apim/files/3736503/APICreate_payload.json.txt)

**Comment by 2437850** [comment]
@malinthaprasan @tmkasun : can you please share some update?
