### ISSUE TITLE
[Improvement] Create API using  GraphQL UI / WSDL  URL needs to be more intuitive

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#6337]
![2019-10-09](https://user-images.githubusercontent.com/7173347/66491493-6af44000-ead0-11e9-8b69-f995bb70daaa.png)

Can we make the UI look more like this?

Label suggestions:
Remove "Provide GraphQL File" label as the drag and drop zone should be intuitive.
Display files in a list,  or a table. Remove the label "Files" by default.

**Comment by tmkasun** [comment]
@Shani thanks for pointing this out, IMHO when there is only file drag and drop option, The drag zone should be large enough to make it easy for the user to drop the file.

**Comment by tmkasun** [comment]
Related issues:

- https://github.com/wso2/product-apim/issues/6571
- https://github.com/wso2/product-apim/issues/5865
- https://github.com/wso2/product-apim/issues/5778
- https://github.com/wso2/product-apim/issues/6381

**Comment by tmkasun** [comment]
@pahans FYI
