### ISSUE TITLE
[Publisher] Issue with the cursor when hovering over the operation type in a GraphQL API

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6348]
Under the operations page of a GraphQL API, when hovering over the operation type (query, mutation or subscription), the cursor changes like it is a link, but this is just a label.

![Screenshot from 2019-10-10 10-26-09](https://user-images.githubusercontent.com/30475839/66540575-f2ca6080-eb49-11e9-9a83-952254bf0ae8.png)

**Comment by HiranyaKavishani** [comment]
Close the issue as above commit
