### ISSUE TITLE
[Devportal - 3.0.0-alpha2] Cannot subscribe to the sample API using default application

### ISSUE THREAD

**Issue by chintana** [wso2/product-apim#6349]
Steps to reproduce,
1. Unpack alpha 2 pack
2. Login to publisher as admin and publish pizzashack sample API
3. Click on view on dev portal link, login as admin
4. Click on Credentials and click on Subscribe to Available App
5. Select DefaultApplication and Unlimited then click subscribe
6. Nothing happens but if you look at network calls it's returning a 400 bad request. See below screenshot,

<img width="1133" alt="subscribe-error" src="https://user-images.githubusercontent.com/27903/66542890-aac72180-eae8-11e9-812c-fa6f6009f9c4.png">

**Comment by chintana** [comment]
This only happens when you don't have keys generated for an app. If you generate keys then subscription works fine.

May be we can provide 1) a descriptive message other than 400 bad request 2) detect that error to show a hint to the user that he/she should generate keys first? Or may be provide a button to "Click here to generate keys for the app before you subscribe" type message

**Comment by tmkasun** [comment]
We have fixed this issue in APIM 3.0.0 and we have changed the above UI as follows

![image](https://user-images.githubusercontent.com/3313885/66747985-9cd81e80-eea3-11e9-9dcd-de274d3b6654.png)


please re-open the issue if you still experience this subscription issue.
