### ISSUE TITLE
[Devportal - 3.0.0-alpha2]Show a human readable access token lifetime

### ISSUE THREAD

**Issue by chintana** [wso2/product-apim#6350]
After generating a token, token lifetime is displayed in seconds. Displaying these large values in a human readable form is much more useful. Otherwise users will end up googling a calculator and copy pasting this number to find out how long it is.

<img width="580" alt="token-lifetime" src="https://user-images.githubusercontent.com/27903/66543122-57090800-eae9-11e9-95c8-1e6264686945.png">

**Comment by chamilaadhi** [comment]
Fixed in 3.0.0 beta

<img width="690" alt="Screen Shot 2019-10-11 at 12 21 59 PM" src="https://user-images.githubusercontent.com/4861150/66630381-c6821300-ec21-11e9-9494-8e7dc778cc8d.png">
