### ISSUE TITLE
[Publisher - 3.0.0-alpha2] Workflow status on overview section shows a question mark

### ISSUE THREAD

**Issue by chintana** [wso2/product-apim#6351]
When viewing an API, the workflow status show a question mark. Should we display/disable/hide depending on whether workflows are engaged or not? 

<img width="381" alt="workflow-status" src="https://user-images.githubusercontent.com/27903/66544561-583c3400-eaed-11e9-854c-67b980502c5e.png">

**Comment by tmkasun** [comment]
This is fixed in APIM 3 beta

![image](https://user-images.githubusercontent.com/3313885/66747875-36530080-eea3-11e9-9d7e-5724011aab31.png)
