### ISSUE TITLE
[Publisher- 3.0.0-alpha2] Show default cache duration after enabling response caching

### ISSUE THREAD

**Issue by chintana** [wso2/product-apim#6352]
Right now users have to read the documentation to find out what's the default cache duration after enabling response caching. It'll be useful to show default response cache duration and whether it's a local / distributed cache right in the publisher portal itself.

<img width="492" alt="response-cache" src="https://user-images.githubusercontent.com/27903/66544978-7ce4db80-eaee-11e9-87cb-61d18174e2b2.png">

**Comment by mushthaq33** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7531
