### ISSUE TITLE
[Publisher - 3.0.0-alpha2] Provide an easier way to navigate/list available roles when restricting an API visibility by roles

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6353]
At the moment we're asking users to enter role names when restricting APIs by roles. Users (API publishers) have to know the roles beforehand. If it's LDAP then they have to use an LDAP browser or ask an admin to provide a list of roles.

After typing a role we're doing a validation check to make sure role is valid. If we can extend this to list out / browse all available roles and let the user to select a subset, that'll provide a better user experience

<img width="362" alt="role-validation" src="https://user-images.githubusercontent.com/27903/66545340-51aebc00-eaef-11e9-87bf-a9719ba87665.png">

**Comment by tmkasun** [comment]
Won't there be any security risk when exposing available roles, With the current implementation also, an attacker could brute force to guess the available roles, but still we could throttle out such requests?

**Comment by chintana** [comment]
I don't see why this is a security risk. You need to be able to have an account and then have the publisher role to login to the publisher. This is not a security risk anymore than any valid user trying to brute force any internal system - AD, LDAP, Email etc...

**Comment by nankiefantia** [comment]
I'm using wso2am-4.0.0,  do this issue resolved in 4.0.0? I want to customize restrict by roles to give it a list do expand roles.
