### ISSUE TITLE
[Devportal] Add token type to the application listing table

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#6354]
<img width="1266" alt="Screen Shot 2019-10-10 at 12 39 18 PM" src="https://user-images.githubusercontent.com/8057793/66546620-016d4380-eb5b-11e9-8bf6-4d0aea58266d.png">
It is better to add token type in the applications listing table

**Comment by tmkasun** [comment]
Do we need to show that here, Eventually, we will be moving to application with only jwt token type. So IMO it's not necessary to show the token type here.

**Comment by tmkasun** [comment]
@nuwand WDYT ?

**Comment by nuwand** [comment]
I don't think we need to show the token type here. Its an implementation detail which the application shouldn't really worry about.
