### ISSUE TITLE
Digest Auth with Wso2 - gives error - Payload could not be written as JSON.

### ISSUE THREAD

**Issue by prats2017** [wso2/product-apim#6366]
I am trying to reach out to a SOAP service from WSo2 rest interface.
I am using Digest Auth here.
I see a 401 Unauthorized and then a 200 OK in wso2 logs. [Wirelogs are enabled]
I am getting **org.apache.axis2.AxisFault: Payload could not be written as JSON.** Can someone please look and help?

[2019-10-10 14:11:37,403] ERROR - JsonUtil #writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:f77469d8-698b-478d-8f3f-d7811ae4de79
[2019-10-10 14:11:37,404] ERROR - PassThroughHttpSSLSender Failed to submit the response
org.apache.axis2.AxisFault: Payload could not be written as JSON.

I read somewhere that I should write implementation for "HTTP digest authentication" then you can plug them in to synapse config as Class Mediator. Can someone please elaborate and provide pointers?

[digestError.txt](https://github.com/wso2/product-apim/files/3714024/digestError.txt)

**Comment by prats2017** [comment]
[digestError.txt](https://github.com/wso2/product-apim/files/3714022/digestError.txt)

**Comment by prats2017** [comment]
I checked backend-api logs and it seems Wso2 is sending a new cookie with each request. How do I handle this in wso2?
[10/Oct/2019:15:50:45 +0100] "POST http://myExample.com/ABC.php HTTP/1.1" 401 - "https://10.10.10.10:9443/store/apis/info?name=TEST1008&version=1.0.0" "Synapse-PT-HttpComponents-NIO"
[10/Oct/2019:15:50:45 +0100] "POST http://myExample.com/ABC.php HTTP/1.1" 200 - "-" "Synapse-PT-HttpComponents-NIO"
45.17.108.113|        5p15vf4s1rmk2pr9537aqorgvc |2019-10-10T15:50:45.714358+0100|2|***** Vision TEST ABC v1.9.0 ©2009-2019 New ABC session
45.17.108.113|        5p15vf4s1rmk2pr9537aqorgvc |2019-10-10T15:50:45.742439+0100|2|VisionTEST4.2.0-moray-20190913:ABC1.9.0|HTTP:401|ABC reply [ABC:0.041] [Synapse-PT-HttpComponents-NIO]
45.17.108.113|        7930fc5tg4br4hr8qpfo8mhqor |2019-10-10T15:50:45.916674+0100|2|**** Vision TEST ABC v1.9.0 ©2009-2019 New ABC session *************************
45.17.108.113|        7930fc5tg4br4hr8qpfo8mhqor |2019-10-10T15:50:45.916818+0100|2|VisionTEST4.2.0-moray-20190913:ABC1.9.0|HTTP:200|ABC reply [ABC:0.011] [Synapse-PT-HttpComponents-NIO]
The second pipe delimited field in the log shows the session cookie being used and it is changing between the 401 and the authentication being sent, for me to remain logged in and send requests the session cookie needs to be maintained through the session across all requests.

**Comment by tmkasun** [comment]
What is the API Manager version you are using?

**Comment by prats2017** [comment]
@tmkasun - I am using wso2am-2.6.0
