### ISSUE TITLE
Business Information page form has no required validation

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#6367]
Business Information page form has no required validation.
Can save an empty form.
Related: https://github.com/wso2/product-apim/issues/5895

![image](https://user-images.githubusercontent.com/20179540/66585848-369e8380-eba5-11e9-9fa3-3692a5bbdddb.png)

**Comment by ruks** [comment]
@erangatl @chanaka3d @tmkasun @harsha89 do we need this validation? Since anyone can create an API without this information, I think we should not make any of these parameters mandatory.

**Comment by tmkasun** [comment]
Agree with @ruks , I think we can't mandate these fields or even no need to do so. AFAIK these are only for information purposes, not involved in API runtime.

**Comment by erangatl** [comment]
+1 no need to have mandate fields, but at the moment users can save an empty form, we need to validate it.

**Comment by tmkasun** [comment]
So if they want to clear the values they would save empty form ?

**Comment by ruks** [comment]
I did changes to enable the save button only if the form is updated. If there are changes to any field will enable the save button. Hope it is fine.

**Comment by erangatl** [comment]
> So if they want to clear the values they would save empty form ?

Shall we add a button to delete the Business Information?
