### ISSUE TITLE
Implement revers proxy support for SPA apps 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#6369]
We need to replace the hardcoded app contexts in static file URLs in the [index.html](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/pages/index.html) page with the app context given in [defaultTheme.js](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/public/theme/defaultTheme.js#L109)

**Comment by isharac** [comment]
Fixed hard coded context in devportal with
https://github.com/wso2/carbon-apimgt/pull/7510

Fixed hard coded context in publisher with
https://github.com/wso2/carbon-apimgt/pull/7485

**Comment by isharac** [comment]
Duplicate https://github.com/wso2/product-apim/issues/6467
