### ISSUE TITLE
[3.0.0][Publisher] Reset button on resource

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6370]
**Description**
A reset button is there for each resource on publisher resource page but it does nothing(except for removing scopes if only they are not saved previously and descriptions and other modifications remain same) when clicked and it is unclear the purpose of it.

<img width="555" alt="Screenshot 2019-10-10 at 21 51 10" src="https://user-images.githubusercontent.com/17607322/66587766-b7ab4a00-eba8-11e9-85f0-497127ef4637.png">

**Comment by npamudika** [comment]
We have removed the Save and Reset buttons from the Resource level. Hence the issue is not relevant now.
