### ISSUE TITLE
[3.0.0][Publisher]Api provider name of product in tenant 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6376]
**Description**
provider-AT-domain format needs to be in provider@domain format

<img width="695" alt="Screenshot 2019-10-11 at 09 46 27" src="https://user-images.githubusercontent.com/17607322/66624351-684b3500-ec0d-11e9-86b2-9f971382821a.png">

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7511
