### ISSUE TITLE
[3.0.0][devportal] Issue in servers in test console

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6377]
**Description**
See the below image. The server URL repeated the tenant domain several times. This can be observed in API product.

**Steps to  reproduce**
Deploy the sample product and Sign in to devportal as a tenant and go to test tab

<img width="618" alt="Screenshot 2019-10-11 at 10 26 35" src="https://user-images.githubusercontent.com/17607322/66625511-1a84fb80-ec12-11e9-8e70-b9a67f3895e4.png">

**Comment by AmaliMatharaarachchi** [comment]
This issue is related to https://github.com/wso2/product-apim/issues/6401

**Comment by tharikaGitHub** [comment]
The sample API Product is not available now in the UI for deployment. 

When tested with a new API Product, 2 URLs are shown for **http** an **https** as expected. Hence closing the issue.

![test-server-urls](https://user-images.githubusercontent.com/8557410/70118137-588c2200-168d-11ea-845f-ed4f5c229897.png)
