### ISSUE TITLE
API property page issues

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6385]
![image](https://user-images.githubusercontent.com/3960742/66632417-0ba84400-ec26-11e9-8d7f-56e494be310b.png)

1) input boxes should be longer
2) "is" case sensitive
3) reserved word validation doesn't work
4) Buttons need to be of the standard size (this one is too small)
5) Space is too much. Need to be the standard value. 
6) The redundant button should be removed.

**Comment by chanaka3d** [comment]
Fixed all except item 4 and 2. 

2 - The documentation says the same as the text in the UI. https://docs.wso2.com/display/AM260/Adding+Custom+Properties+to+APIs.

4 - The button size is the default button size of MUI.

**Comment by bhathiya** [comment]
@shaniR what do you think of 2?

**Comment by shaniR** [comment]
Yes we should change the documentation as well. It should be "is not". In addition to it, I think the helper text is too long. Should we add those as validation text? and as a tool tip? 
    Property name :
       - should be unique.
       - should not contain spaces.
       - should not be case-sensitive.
       - should not be any of the following reserved keywords: provider, version, context, status, description, subcontext, doc, lcState, name, tags.

Please consider the following as well:
1) The mandatory asterisk should be on the field name.
2) The space validation also does not happen.
3) The table listing the properties should have table headings

**Comment by bhathiya** [comment]
reopening to fix 2.

**Comment by erangatl** [comment]
> Property name :
> - should not be case-sensitive.


@shaniR it should be
" is case-sensitive "

and -1 for tooltip this information needs to be always visible

**Comment by bhathiya** [comment]
I still can observe issue (3).

![Uploading image.png…]()

**Comment by kavishkafernando** [comment]
Issue [3] has been fixed with https://github.com/wso2/carbon-apimgt/pull/7873
