### ISSUE TITLE
[APIM][3.0.0] Publisher Portal menu can be placed such that it appears a part of the API

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#6397]
Currently the publisher right menu could give the impression that it is a global navigation menu. In order to overcome this, we could do a minor change in the UI to  give the impression that the actions are to be performed for the API.
![Screenshot from 2019-10-01 14-28-50](https://user-images.githubusercontent.com/7173347/66644404-79606a00-ec3e-11e9-9634-46e24154b84e.png)

Maybe we could revisit the design for a future release, and consider the options below.

Have the left hand side menu underneath the top heading, which introduces the API. This gives the impression that the actions are done for this API, as opposed to being global actions.
![Screenshot from 2019-10-01 11-35-25](https://user-images.githubusercontent.com/7173347/66644382-6ea5d500-ec3e-11e9-9272-0efa3af81144.png)

**Comment by chamilaadhi** [comment]
Portals are refactored in the latest versions 
<img width="694" alt="Screenshot 2024-03-04 at 3 53 04 PM" src="https://github.com/wso2/product-apim/assets/4861150/a1da558b-ca61-4011-9081-cb7d7aabb6d0">
