### ISSUE TITLE
[Publisher][UI/UX] Product Runtime Configs empty Backend section

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6405]
**Version**
3.0.0 beta

<img width="1435" alt="Screenshot 2019-10-11 at 17 23 56" src="https://user-images.githubusercontent.com/17607322/66649567-2097ce00-ec4c-11e9-8d08-ed41af887910.png">

**Comment by tmkasun** [comment]
@erangatl Can you please confirm whether this issue still exsist ?

**Comment by erangatl** [comment]
> @erangatl Can you please confirm whether this issue still exsist ?

@tmkasun API Product backend section has nothing to show. We can keep the section for illustration purposes.

**Comment by tmkasun** [comment]
> @tmkasun API Product backend section has nothing to show. We can keep the section for illustration purposes.

Yes, @uvindra  Shall we give some information here, how backend works in API Products ?

**Comment by uvindra** [comment]
Yes we could mention that endpoint information needs to be referred to by looking at the respective APIs which are used to create the API Product
