### ISSUE TITLE
Devportal token generation issue

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#6410]
When i try to generate new token through the API details page , `Update Keys` button is disabled with a message as below

![image](https://user-images.githubusercontent.com/3313885/66659348-f43a7c80-ec60-11e9-986d-71900453344a.png)

**Comment by dushansilva** [comment]
This should get fixed with https://github.com/wso2/carbon-apimgt/pull/7491/files 
Related issue https://github.com/wso2/product-apim/issues/5629

Does it still exists in latest pack?

**Comment by kavishkafernando** [comment]
Closing the issue since it has been fixed with PR https://github.com/wso2/carbon-apimgt/pull/7491
