### ISSUE TITLE
Publisher subscriptions page loading issue

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#6414]
When the network connection is slow, the Initial UI element arrangement looks odd, until it gets fully rendered.

![Image](https://raw.githubusercontent.com/tmkasun/images/master/slow_sub_3g.gif)

Please check the following items with UI changes

* Responsiveness of the page
* Behavior of the UI with slow networks
  * ![image](https://user-images.githubusercontent.com/3313885/66666209-c9a2f080-ec6d-11e9-876f-ca6b1846294c.png)
* Performance impact with a long run and a higher number of elements
   * Infinite loops, i:e doing a state update inside `useEffect`
   * Redundant rendering of child components

**Comment by tmkasun** [comment]
Duplicate of this issue https://github.com/wso2/product-apim/issues/5939

**Comment by AmaliMatharaarachchi** [comment]
This is fixed from https://github.com/wso2/carbon-apimgt/pull/7586
