### ISSUE TITLE
Error creating an API with scopes it this scopes were created in another API

### ISSUE THREAD

**Issue by nmarher** [wso2/product-apim#6430]
Hello. 

If you delete an API with scopes in linux, it's not possible create another API with this scopes, because the ddbb is inconsistent.

There are several bugs identified with this issue:

- https://github.com/wso2/carbon-apimgt/pull/5253/files
- https://github.com/wso2/product-apim/issues/2978

But  if you download the product 2.6.0 the issue is not resolve. Can you help us with a patch? 

I also tried to generate the wso2am-2.6.0.zip from sources following this [steps](https://wso2.github.io/using-maven.html)
from this [repository](https://github.com/wso2/carbon-apimgt), it compiles, but I can't generate the final .zip. Can you help me generate the binary with the bug fixed?

Thanks!

**Comment by ruks** [comment]
This is not reproducible. Hence close.
