### ISSUE TITLE
[IMPROVEMENT] Typing Error in Publisher

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6442]
**Description**

- The following grammar mistakes need to be corrected.

1. "Deprecate old versions after **publish** the API"
2. "Requires re-subscription when **publish** the API" 

**Suggested Solutions**

1. Deprecate old versions after **publishing** the API
2. Requires re-subscription when **publishing** the API

![Screenshot from 2019-10-14 16-36-39](https://user-images.githubusercontent.com/44407066/66748168-238cfb80-eea4-11e9-9031-4b521f11f2f6.png)

**Comment by tmkasun** [comment]
Can you please mention the APIM version that you are using ?

**Comment by SachithKasthuriarachchi** [comment]
> Can you please mention the APIM version that you are using ?

I cloned the latest master branch today morning and built it(version 6.5.252-SNAPSHOT)

**Comment by SachithKasthuriarachchi** [comment]
@tmkasun the issue has been updated with a screenshot.

**Comment by bhathiya** [comment]
@sanjulamadurapperuma
