### ISSUE TITLE
[IMPROVEMENT - 3.0.0] Improvements for Fonts

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#6451]
**Description**

- As shown in the following screenshot, the fonts used in the UI seem to be different ( in the green cloured boxes) and it is somewhat ugly.

![Screenshot from 2019-10-15 09-10-48](https://user-images.githubusercontent.com/44407066/66798828-df920900-ef2c-11e9-9475-81a7d8636d8b.jpg)

**Suggestions**

- It would look nice if the fonts were consistent.

**Comment by menakaj** [comment]
Fixed
