### ISSUE TITLE
Migrating the application from one environment to another environment with client credential is not supported in API Manager 2.2.0

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#6453]
Description:- When exporting the application using the apim import export tool with --withKeys option the keys(client credentials) are not getting exported with the JSON file. When analyzing the code that feature is not supported in 2.2.0. By modifying the code that feature can be achieved in API Manager 2.2.0. But --withKeys option is supported in API Manager 2.6.0. 

Affected Version: -API Manager 2.2.0

**Comment by chamindias** [comment]
Please see: https://github.com/wso2/carbon-apimgt/issues/6707

It contains the PR, hence resolving.
