### ISSUE TITLE
APIM3.0.0-beta - Text and typos

### ISSUE THREAD

**Issue by lakshikap** [wso2/product-apim#6454]
1) Generate text is capital although it is used again in simple thereafter.
2) Text - click away to validate URL doesn't have an action because validation is shown automatically.
3) Instead of 'is default', is can be more descriptive as "Mark this version as default".
4) Typo in the sentence - "enabling JSON schema validation will cause to build the payload in [every...<ERROR>"] it should be corrected to - 'request and response'.

All screens are named and given in this folder.
https://drive.google.com/drive/u/0/folders/1rRQw-_8WY0sIJDqzwvb4q_kVoep8NRsl

**Comment by Mariangela** [comment]
@lakshikap , thanks for reporting!

@bhathiya , I checked the issues that were reported and detailed them further in [1].

[1] https://docs.google.com/spreadsheets/d/1n_ija26hkghkKbkpGFOobQ8_daG_3U2vY8qCkgHPfGg/edit?usp=sharing

**Comment by bhathiya** [comment]
@sanjulamadurapperuma can you please check this?

**Comment by tharikaGitHub** [comment]
Some issues referenced in [1] are reported with [2].

[1] https://docs.google.com/spreadsheets/d/1n_ija26hkghkKbkpGFOobQ8_daG_3U2vY8qCkgHPfGg/edit?usp=sharing
[2] https://github.com/wso2/product-apim/issues/6777

**Comment by erangatl** [comment]
Issue number 13 is also fixed
