### ISSUE TITLE
APIM3.0.0-beta - UI/UX issues

### ISSUE THREAD

**Issue by lakshikap** [wso2/product-apim#6459]
1) Two buttons are overlapping in the Dev Portal.
2) Dropdown doesn't collapse after selecting one option.

Screens - https://drive.google.com/drive/u/0/folders/1rRQw-_8WY0sIJDqzwvb4q_kVoep8NRsl

**Comment by bhathiya** [comment]
@sanjulamadurapperuma

**Comment by sanjulamadurapperuma** [comment]
Since the Business Plan drop-down allows multiple selections it would not be feasible to make it collapsible.

![image](https://user-images.githubusercontent.com/32578617/66982380-93cd9400-f0d3-11e9-94db-92dd9d569b99.png)
