### ISSUE TITLE
APIM3.0.0-beta - Can duplicate and save access control methods - see GET and PUT

### ISSUE THREAD

**Issue by lakshikap** [wso2/product-apim#6460]
Can duplicate and save access control methods - see GET and PUT added twice. 

Screens - https://drive.google.com/drive/u/0/folders/1rRQw-_8WY0sIJDqzwvb4q_kVoep8NRsl

**Comment by chamindias** [comment]
The fix is in https://github.com/wso2/carbon-apimgt/pull/7611 (see: https://github.com/wso2/carbon-apimgt/pull/7611)

**Comment by chamindias** [comment]
PR sent, hence resolving.
