### ISSUE TITLE
APIM3.0.0-beta - No error message when adding the same API Doc

### ISSUE THREAD

**Issue by lakshikap** [wso2/product-apim#6462]
The same API doc (as a URL) was added with a different name. It wasn't added, but the screen did not throw an error saying this already exists. Should we allow the same doc/URL to be added with a different name/ summary? Because there can be an instance where different info can be in one URL and it can be added multiple times to share different topics under the same URL. 

Screen - https://drive.google.com/drive/u/0/folders/1rRQw-_8WY0sIJDqzwvb4q_kVoep8NRsl

**Comment by nalakas** [comment]
In the latest version, you can add the same URL with a different name and summary.

**Comment by chamindias** [comment]
Closing this as per the above comment.
