### ISSUE TITLE
[Publisher] In Mutual SSL configurations uploaded certificate does not exist in truststore

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#6465]
![Screenshot from 2019-10-15 17-04-59](https://user-images.githubusercontent.com/31464477/66828530-e04b8f00-ef6e-11e9-848c-ad284af501b5.png)
**Issue**
When configuring Mutual SSL in Runtime Configurations page,the uploaded certificate does not exist in truststore.

**Comment by HiranyaKavishani** [comment]
Close the issue as the uploaded certificate does exist in the client trust store with **[alias]_-[tanantId]** 
Eg: main_-1234
