### ISSUE TITLE
Remove self signup from publisher login page

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#6475]
Remove **Register Now** url from publisher login page
<img width="562" alt="Screen Shot 2019-10-16 at 1 47 44 PM" src="https://user-images.githubusercontent.com/4861150/66901130-b43a1780-f01b-11e9-8b93-6faea72043a3.png">

**Comment by dushaniw** [comment]
Fixed in latest 3.1.0 Alpha 

![Screenshot from 2020-02-11 13-46-48](https://user-images.githubusercontent.com/12208083/74220227-042ca080-4cd5-11ea-98a9-dde72dac33e7.png)
