### ISSUE TITLE
NPE when invoking an API which has request bandwidth limit

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#6477]
Steps to reproduce:
- Create and publish an API with x-auth-type as None and advanced throttling policy with request data bandwidth.
![image](https://user-images.githubusercontent.com/44961438/66903967-f580f600-f020-11e9-9d02-afbef916aeac.png)
![image](https://user-images.githubusercontent.com/44961438/66903953-ef8b1500-f020-11e9-9b5d-3f97b5331cc9.png)

- Invoke the API without any subscriptions.
 
Description:
This error occurs as it is checking the content aware policies when validating the keys.

Error trace:

> ERROR - AbstractStreamProcessor Dropping event chunk EventChunk{first=StreamEvent{timestamp=1571205237058, beforeWindowData=[true], onAfterWindowData=[{ip=174327833}], outputData=[/test/1.0/1.0/foo:GET_default, null, 1571205600000, W10=], type=CURRENT, next=null}}, error in processing org.wso2.carbon.apimgt.throttling.siddhi.extension.ThrottleStreamProcessor, null
> java.lang.NullPointerException
> 	at org.wso2.siddhi.core.query.selector.attribute.aggregator.SumAttributeAggregator$SumAttributeAggregatorLong.processAdd(SumAttributeAggregator.java:245)
> 	at org.wso2.siddhi.core.query.selector.attribute.aggregator.SumAttributeAggregator.processAdd(SumAttributeAggregator.java:71)
> 	at org.wso2.siddhi.core.query.selector.attribute.aggregator.AttributeAggregator.process(AttributeAggregator.java:86)
> 	at org.wso2.siddhi.core.query.selector.attribute.processor.executor.GroupByAggregationAttributeExecutor.execute(GroupByAggregationAttributeExecutor.java:121)
> 	at org.wso2.siddhi.core.executor.condition.compare.CompareConditionExpressionExecutor.execute(CompareConditionExpressionExecutor.java:38)
> 	at org.wso2.siddhi.core.executor.condition.compare.CompareConditionExpressionExecutor.execute(CompareConditionExpressionExecutor.java:25)
> 	at org.wso2.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:38)
> 	at org.wso2.siddhi.core.query.selector.QuerySelector.processInBatchGroupBy(QuerySelector.java:223)
> 	at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:78)
> 	.............

Version : 2.6

**Comment by bhathiya** [comment]
@Krishanx92 Let's fix this for 3.1.0

**Comment by isharac** [comment]
Closing since the public fix is merged.
