### ISSUE TITLE
Generate proper error message when the "Authorization" header is not present in web socket client

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#6478]
Description:
When the "Authorization" Header is not provided during the web socket handshake, there is no proper log message in the carbon log to indicate that.

Steps to reproduce:
- Create a websocket API and publish it.
- Call the websocket API using a web socket client, without "Authorization" Header. (You can use the [sample client](https://docs.wso2.com/download/attachments/97565113/sample-ws-client.zip?version=2&modificationDate=1562750222000&api=v2) mentioned in the documentation)

Affected versions:
2.6

**Comment by bhathiya** [comment]
The problem is the authentication check is done at the handshake and when the authentication fails the handshake fails. There is no way to let the user know the real reason.

**Comment by Arshardh** [comment]
This is true, we have no way to let the user know. But for the moment we do log this error in the carbon console.

https://gist.github.com/Arshardh/3b0609f31e739b25ff406c6bebadf132
