### ISSUE TITLE
The changes made in the In Flow section in the implement tab of the publisher is not working in the tenant mode.

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#6493]
Description: When we modify the In Flow section in the publisher and changes are not persisted in the UI and as well as in the file system (<WSO2AM_Home>/repository/tenants/<tenant_name>/synapse-configs/default/api/<Name of the API.xml>).  But it is working in the super tenant mode. 

Steps to reproduce:- Create a tenant user in the carbon console.
Go to the publisher and create an API. 
In the implement, tab make some changes in the In Flow section( Not the In Flow section in the message mediation). See the attached image for reference. 
The changes made in the In Flow is not persisted in the UI as well as in the File system.
![image](https://user-images.githubusercontent.com/32807418/66979449-2b7ab480-f0cb-11e9-970a-fda1ed08e149.png)

It is working in the super tenant mode.

**Comment by bhathiya** [comment]
what's the APIM version?

**Comment by Senthuran100** [comment]
API Manager 2.2.0

**Comment by kavishkafernando** [comment]
public commit: #https://github.com/wso2/carbon-apimgt/commit/81bd4bfb85dde3d7685a26dc6d6036862d54b362
