### ISSUE TITLE
[UI/UX] API thumbnail in Publisher vs devportal

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6494]
**version**
3.0.0 beta

**Description**
It is better if API thumbnail is identical in publisher and devportal.
<img width="272" alt="Screenshot 2019-10-17 at 11 39 34" src="https://user-images.githubusercontent.com/17607322/66982602-2110e880-f0d4-11e9-890e-5ae2a6b8ee10.png">
<img width="263" alt="Screenshot 2019-10-17 at 11 48 53" src="https://user-images.githubusercontent.com/17607322/66982608-253d0600-f0d4-11e9-843e-3af1ca9bf384.png">

1. corners
2. Font colors and styles
3. context is with and without version

**Comment by vithu30** [comment]
Similar concern is observed when there is an image uploaded in thumbnail. Refer below image.
Appearance in publisher:
![image](https://user-images.githubusercontent.com/19728269/66998264-950db980-f0f1-11e9-808a-91646f232c60.png)

Appearance in dev portal:
![image](https://user-images.githubusercontent.com/19728269/66998309-a787f300-f0f1-11e9-9f7c-39af3f940cae.png)

**Comment by Hervinho** [comment]
Thumbnail background in Devportal not displaying with right colors as in Publisher, although changes were made in defaultTheme.js in devportal.

### **Devportal defaultTheme.js**
`
thumbnail: {
            backgrounds: [ 
                { prime: 0x67C2EB, sub: 0xffffffff },
            ],
        },
`
### **Publisher defaultTheme.js**
`
thumbnail: {
                backgrounds: [ 
                    { prime: 0x67C2EB, sub: 0xffffffff },
                ],
`

**Screenshots**: **Devportal** vs **Publisher**
![devportal](https://user-images.githubusercontent.com/6742076/104439410-bf228580-5599-11eb-9559-bb58decb1a00.PNG)
![publisher](https://user-images.githubusercontent.com/6742076/104439413-c0ec4900-5599-11eb-840e-9ea4bfa257bd.PNG)
