### ISSUE TITLE
Error in enabling schema validation for API Product

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#6510]
Steps:
1.Create an API Product.
2. Go to Runtime Configurations -> Schema Validation
Enable and save.
Below error is printed in the carbon.log.

ERROR - GlobalThrowableMapper Unrecognized property 'enableSchemaValidation'
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "enableSchemaValidation" (class org.wso2.carbon.apimgt.rest.api.publisher.v1.dto.APIProductDTO),

we need to add enableSchemaValidation attribute in the swagger definition.

**Comment by HiranyaKavishani** [comment]
closed the issue as per above commit
