### ISSUE TITLE
[Store]Error when generating an access token

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-apim#6524]
**Description:**
Error when trying to generate the access token from UI

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
APIM 3.0.0 Beta 

**OS, DB, other environment details and versions:**
macOS 10.15 (19A583)

**Error log**
[Please refer this error log](https://github.com/wso2/product-apim/files/3745006/error.log)

**Comment by rnavagamuwa** [comment]
Faced the same issue on APIM 3.0.0-RC3 as well.

**Comment by kavishkafernando** [comment]
Cannot reproduce this issue in the latest pack. Please reopen if you encounter this issue again.
