### ISSUE TITLE
Issue with rate limiting in GraphQL APIs

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6525]
As shown in the screenshot below, an advanced throttling policy named "policy_2" was created with 1 request per minute.
![API Policies](https://user-images.githubusercontent.com/30475839/67116468-15b9dc00-f1fe-11e9-953f-7ddaf3d49504.png)

Afterward, this policy was assigned to the "countries" operation as shown below. Then under the Lifecycle tab, demoted to created and then published the API again.
![WSO2 APIM Publisher](https://user-images.githubusercontent.com/30475839/67116485-1bafbd00-f1fe-11e9-8cb4-8296abd98644.png)

Then when trying that particular API, the below-given query was used. This query clearly uses the "countries" operation, but the rate was not limited to 1 request per minute.
![WSO2 APIM Developer Portal](https://user-images.githubusercontent.com/30475839/67116492-1fdbda80-f1fe-11e9-9c21-ba357f49428c.png)

**Comment by HiranyaKavishani** [comment]
The reason for this issue is due to operations are appended in to query as nested level

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7687
