### ISSUE TITLE
Hide LC checklist items for apis without version

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#6530]
<img width="483" alt="Screen Shot 2019-10-19 at 2 10 14 PM" src="https://user-images.githubusercontent.com/4861150/67140681-91596e80-f27a-11e9-9be8-ef1dd12f33fb.png">

ATM checklist items is not causing any issue.

**Comment by chathuranga95** [comment]
fixed in 3.1.0-beta.

**Comment by chathuranga95** [comment]
According to the [documentation](https://docs.wso2.com/display/AM260/Publish+the+New+Version+and+Deprecate+the+Old), the checklist item: Requires re-subscription when publish the API should also be hidden when there are no higher versions are available for an API.
