### ISSUE TITLE
How about renaming the wizard button?

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6544]
Here, the 2 available options are subscribing to an existing app vs new app. So I think renaming it will make it more intuitive about what's button is about.

![image](https://user-images.githubusercontent.com/3960742/67156458-69324400-f33c-11e9-80cc-b18386d79ee1.png)

WDYT?

**Comment by fazlan-nazeem** [comment]
+1

**Comment by mushthaq33** [comment]
+1. I guess this needs to give the user an idea on what this button is about.

**Comment by pubudu538** [comment]
+1. That makes sense.

**Comment by menakaj** [comment]
+1

**Comment by rmsamitha** [comment]
+1 "Wizard" implies nothing useful actually.

**Comment by erangatl** [comment]
+1 if the most use case is subscribing to an existing one we can take that section to top too.

**Comment by bhathiya** [comment]
> +1 if the most use case is subscribing to an existing one we can take that section to top too.

I like this idea too. @chanaka3d @tmkasun WDYT?
