### ISSUE TITLE
API Product Resource page issues

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#6546]
![image](https://user-images.githubusercontent.com/8557410/67157746-33965680-f34e-11e9-968d-fceea40ccc73.png)

1. Spelling mistake in RESET button.
2. Even though there is a message saying "You may change the rate limiting policies per operation
Expand an operation below to select a rate limiting policy for an operation" when operation level rate limiting is selected, we do not allow to edit the resources in Products. Better to change the message.
3. For a user with publisher only role, **Save** and **Reset** buttons are enabled even though they are not permitted to do any changes in the main resources page apart from adding and deleting resources of APIs included in it.
![image](https://user-images.githubusercontent.com/8557410/67158435-92ab9980-f355-11e9-901d-253ade0c561d.png)

**Comment by chamilaadhi** [comment]
Fix spelling mistake in https://github.com/wso2/product-apim/issues/6546

**Comment by tmkasun** [comment]
2. Fixed in 
![image](https://user-images.githubusercontent.com/3313885/67259443-7faedb80-f4b3-11e9-82ac-e900cd3eb077.png)

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
