### ISSUE TITLE
Response is not showing when Graphql invocation in tenant domain with invalid query

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#6560]
Steps to recreate:
1. Log in to store with the tenant domain
2. invoke the graphql API with invalid query.
3. The server shows the following WARN.

2019-10-20 22:26:46,483]  WARN - MultitenantMessageReceiver Tenant domain is not available in tenant request message context, hence it might not be set in the thread-local carbon context

**Comment by HiranyaKavishani** [comment]
Fixing https://github.com/wso2/carbon-apimgt/pull/7687/commits/92a8c2c4b5766d00f4cbf2b761755b6d6069e4a3

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7687
