### ISSUE TITLE
Issue in adding API Documentation

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6561]
1. Following dialog box pops up which is not required for documents with **URL** as source. If we click on `ADD CONTENT` button, it redirects to a blank page.
Similar behavior observed when adding documentation with **file** source.
Similar behavior observed when adding documentation with **Public forum**.

![image](https://user-images.githubusercontent.com/19728269/67172251-3c336f00-f3d8-11e9-9f9d-b32bfe4e9ad0.png)

2. `OPEN` button in Documents listing page is not working (in Publisher). This is observed for Forum as well

**Comment by vithu30** [comment]
When creating/editing docs with unsupported file format (tried importing a JSON file), 415 response can be observed from browser console, but UI does not shows it, nothing happens when clicking on `save` button.

**Comment by npamudika** [comment]
When click on the Open button, it should redirected to the provided URL. Currently the button click does nothing.
![Selection_025](https://user-images.githubusercontent.com/8363838/67851327-381df480-fb30-11e9-898d-0541d2e5e144.png)

**Comment by kavishkafernando** [comment]
> When creating/editing docs with unsupported file format (tried importing a JSON file), 415 response can be observed from browser console, but UI does not shows it, nothing happens when clicking on `save` button.

**Unsupported files cannot be uploaded anymore.**
