### ISSUE TITLE
[Publisher/Bug] Importing a swagger definition

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#6563]
How to reproduce:

1. Go to Create an API using Open-API definition tab
2. Provide an OAS document
3. Click Next
4. Click Back

Event though the uploaded file is shown under the files next button is disabled  

![Screenshot from 2019-10-21 09-54-14](https://user-images.githubusercontent.com/42222921/67176701-c97ebf80-f3e8-11e9-8914-493d051aa35a.png)

**Comment by kavishkafernando** [comment]
Cannot be reproduced in latest pack.
