### ISSUE TITLE
Different font types used in API Publisher

### ISSUE THREAD

**Issue by dakshitha** [wso2/product-apim#6571]
<img width="1356" alt="Screen Shot 2019-10-21 at 11 13 00 AM" src="https://user-images.githubusercontent.com/11885043/67179522-2c298880-f3f4-11e9-9496-bbd395310117.png">

**Comment by dakshitha** [comment]
In API-M 3.0.0 beta.

**Comment by tmkasun** [comment]
@pahans FYI
