### ISSUE TITLE
[Publisher] Scope cannot be created by user with publisher role

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6572]
**version**
3.0.0

**Description**
<img width="942" alt="Screenshot 2019-10-21 at 11 42 43" src="https://user-images.githubusercontent.com/17607322/67180679-ee2e6380-f3f7-11e9-9ac1-d8fe4d864d28.png">

<img width="675" alt="Screenshot 2019-10-21 at 11 55 26" src="https://user-images.githubusercontent.com/17607322/67181259-b32d2f80-f3f9-11e9-80f8-d90284c6ceba.png">

**Comment by mushthaq33** [comment]
This is the expected behavior.
