### ISSUE TITLE
[3.0.0] Third party key manager configuration 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6592]
**Labels**
3.0.0
improvement
critical

**Description**
Needs to add configuration template for third party key manager. Current deployment.toml file does not have configurations for this.

**Comment by rmsamitha** [comment]
@AmaliMatharaarachchi  shall we elaborate the issue further. And please add the labels/ label suggestions on issue type, priority, affecting version, etc.

**Comment by tharikaGitHub** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/7750
