### ISSUE TITLE
Monetization properties for the Tier are not retrieved for API Product. 

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#6593]
When subscribing to an API Product through API Credentials tab, the API object retrieved does not have monetization attributes in the API tiers. In the SubscibeToAPI.jsx , the monetization attributes are specifically looked and printed if the Tier type is "Commercial", but for the API product the API tiers retrieved does not contain that information. So it throws a monetization attributes null error.
![image](https://user-images.githubusercontent.com/24529961/67228571-2f099500-f457-11e9-8291-3de74089e164.png)
![image](https://user-images.githubusercontent.com/24529961/67228882-cec72300-f457-11e9-8bce-bb6a60c3ef45.png)

**Comment by chamindias** [comment]
Please see : https://github.com/wso2/carbon-apimgt/pull/7739/files
