### ISSUE TITLE
Better to make the tenant list ordered in the alphabetical order

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6598]
![image](https://user-images.githubusercontent.com/3960742/67263997-70d22400-f4c7-11e9-95e3-ddd84049509a.png)

and maybe have a title saying "Tenants" or something?

**Comment by erangatl** [comment]
title - "API Developer Portals available on this server" ?

**Comment by bhathiya** [comment]
> title - "API Developer Portals available on this server" ?

"API" is not correct. And I think we should mention the word tenant. How about one of these? 

1. Tenant Developer Portals
2. Tenants

**Comment by erangatl** [comment]
> 1. Tenant Developer Portals

+1
