### ISSUE TITLE
Cannot invoke API / API Products when Schema Validation enabled

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#6602]
The following error is displayed.

![image](https://user-images.githubusercontent.com/8557410/67267924-f3131600-f4d0-11e9-80d4-01cda9eacafe.png)

This error is logged in the management console.

```
INFO - LogMediator STATUS = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = json string can not be null or empty
```
Same error for all types of Authentication - JWT, OAuth, API Key, Basic

**Comment by hasuniea** [comment]
https://github.com/wso2/carbon-apimgt/pull/7745
