### ISSUE TITLE
[3.0.0][Store][Publisher]Supporting custom roles with Admin, API creator, API publisher and API subscriber 

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#6605]
APIM 3.0.0 store publisher app UIs are populated by APIM REST APIs and all the authentication and authorization to access the different components in the UI solely depend on the scope role mapping defined in tenant-conf.json[1]. 
By default, the scope-role mapping contains Internal/creator, Internal/publisher, Internal/subscriber as the default roles. If there are custom roles defined with API creator, API publisher, admin and API subscriber permissions, those roles have to be configured in tenant-conf.json under relevant scopes. Hence, there should be a way of specifying which custom role to be accepted as admin, api publisher, creator and subscriber roles and manage the scope role mapping according to role alias and role mapping.

ie:
Alias : Role mapping
----------------------------
apicreator : creator1, creator2,
apipublisher: publisher1,publisher2

"RESTAPIScopes":{
      "Scope":[
         {
            "Name":"apim:api_publish",
            "Roles":"apicreator"
         },
 

[1] https://docs.wso2.com/display/AM260/apidocs/publisher/#configuring-rest-api

**Comment by dushansilva** [comment]
Related https://github.com/wso2/product-apim/issues/6622

**Comment by malinthaprasan** [comment]
1. We can add a new config "RoleMappings" to tenant-conf.json as below:

```
{ 
    "RESTAPIScopes":{
    "Scope":[
      {
        "Name": "apim:api_publish",
        "Roles": "admin,Internal/publisher"
      },
      {
        "Name": "apim:api_view",
        "Roles": "admin,Internal/publisher,Internal/creator,Internal/analytics"
      },
     ],
    "RoleMappings" : { 
          "Internal/publisher" : "abc_publisher",
          "Internal/creator" : "abc_creator",
          ...
}
```

2. Modify APIUtil.getRESTAPIScopesFromConfig() method to correctly return the role. If a mapping exists for a particular role refined in scope, we should use that mapped role. If a mapping doesn't exist, use the role defined in the scope.

For the above example: it should return as below:
```
apim:api_publish -> admin,abc_publisher
apim:api_view -> admin,abc_publisher,abc_creator,Internal/analytics
```

3. Improve the admin app's tenant-conf UI to add role mappings as well.

**Comment by Krishanx92** [comment]
@msm1992 Working on this.
