### ISSUE TITLE
endpoints gets cleared when selecting a different endpoint type

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#6618]
Steps to reproduce 
1. Deploy the sample API
2. Go to endpoints section. You can see that production and sandbox endpoint filled already under HTTP/REST Endpoint section
3. Select HTTP/SOAP Endpoint 
4. Select HTTP/REST Endpoint again. Everything has been cleared.

Assume the values set here should not be cleared when he navigates back to the HTTP/REST Endpoint section

**Comment by bhathiya** [comment]
@menakaj didn't we fix this?
