### ISSUE TITLE
[3.0.0] [UX] Strange behaviour in Response Caching configuration

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#6625]
Steps:

1. Click on Response Caching. (This will set the expansion panel expanded)
2. Click on the switch to enable.

Observation:
Caching configuration does not show. 

The same behaviour can be observed for CORS configuration.

**Comment by Krishanx92** [comment]
Fixed in latest version hence resolve.

**Comment by tmkasun** [comment]
This happens due to the bubbling effect of the collapsible onClick event

![image](https://user-images.githubusercontent.com/3313885/94302270-93977300-ff89-11ea-89f6-6fa791b58aa7.png)


need to fix as we have done in the resources page delete resource button
