### ISSUE TITLE
Improvements for API resources parameter pane

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#6629]
Following issues has to be fixed in API resource parameter defining UI

- The fonts have to be consistent
- The scope wizard should be removed when security is disabled
- The parameter location should be renamed as parameter type
- Parameters can be added without specifying the Parameter type
- Param add button should be highlighted
- Param edit UI is not available
- Param data type and required property cannot be configured
- Param wizard is not available for sample UI

few other issues are specified and marked in the following screenshot.

![screenshot-localhost_9443-2019 10 23-17_15_46](https://user-images.githubusercontent.com/4471756/67390757-deab4800-f5ba-11e9-8187-351521716718.png)

**Comment by tgtshanika** [comment]
https://github.com/wso2/carbon-apimgt/pull/7780

**Comment by dushaniw** [comment]
Tagging https://github.com/wso2/product-apim/issues/5733

**Comment by erangatl** [comment]
@tmkasun has fixed these in latest, 
![image](https://user-images.githubusercontent.com/20179540/74308319-e4a57e80-4d8d-11ea-803a-d488aaf58de2.png)

**Comment by isuruh15** [comment]
The fonts have to be consistent - fixed
    The scope wizard should be removed when security is disabled - fixed
    The parameter location should be renamed as parameter type - fixed
    Parameters can be added without specifying the Parameter type - fixed
    Param add button should be highlighted - fixed
    Param edit UI is not available - not fixed
    Param data type and required property cannot be configured - not fixed
    Param wizard is not available for sample UI - not fixed
