### ISSUE TITLE
[UI]Localization should be supported across all UI components

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#6631]
Localization is not supported in all the components available in Store and Publisher UI. Need to support this.

**Comment by dushaniw** [comment]
Need to test in latest 3.1.0 alpha.

**Comment by Sarangan0219** [comment]
The issue does not exist in WSO2 APIM 3.1.0-beta.

When  localizing the strings to french in dev-portal:

![Screenshot from 2020-02-18 15-08-29](https://user-images.githubusercontent.com/60866295/74723441-934f3080-5260-11ea-84b0-26588995ebf1.png)

Strings are getting localized in Publisher too. Hence this issue can be Closed.
