### ISSUE TITLE
TryOut is broken for API products?

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#6636]
* Deploy the sample API product
* Select a few resources of sample PizzaShack API and publish.
* Click on TryOut and a resource from DevPortal. You see a few errors;

<img width="1655" alt="Screen Shot 2019-10-23 at 9 33 47 PM" src="https://user-images.githubusercontent.com/413016/67446061-36f34180-f5dd-11e9-9cf8-d2c3749496db.png">

**Comment by bhathiya** [comment]
Is this 3.0.0-RC?

**Comment by nirmal070125** [comment]
RC1.. heard it got fixed in RC2?

**Comment by uvindra** [comment]
Yes this is fixed in RC2
