### ISSUE TITLE
Application Security - Mandatory/Optional selection is disabled

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#6637]
I cannot select 'Optional' from the UI. Is it intentional?

<img width="1058" alt="Screen Shot 2019-10-23 at 9 43 04 PM" src="https://user-images.githubusercontent.com/413016/67446285-24c5d300-f5de-11e9-8398-8ba76f1ee39a.png">

**Comment by menakaj** [comment]
You have to select Mutual SSL to select the application-level security mandatory or optional.

**Comment by kavishkafernando** [comment]
Please re-open the issue if you need further assistance.
