### ISSUE TITLE
Less bright colors can be used for http methods and resources

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#6644]
It's better to use less bright shades of the same color, to make the UI more apprealing.
<img width="206" alt="Screen Shot 2019-10-24 at 11 26 24 AM" src="https://user-images.githubusercontent.com/4471756/67458405-c1768800-f653-11e9-8673-c28b4acc3380.png">

**Comment by dushaniw** [comment]
Would this be valid for the release 3.0 version as well?

**Comment by chamilaadhi** [comment]
UI is revamped in the latest version (4.2.0)
<img width="211" alt="Screenshot 2024-03-04 at 3 54 39 PM" src="https://github.com/wso2/product-apim/assets/4861150/d5501d35-ed97-4225-a8f1-23a891d380a7">
