### ISSUE TITLE
[3.0.0] API creation with same context 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6648]
**version**
3.0.0 rc2

**Description**
Different APIs creation with same context is allowed.

**Steps to reproduce**
Create API1 with context(context) version(v1)
We can create API2 with context(context) version(v2). Note that this should not be allowed as context is same as the API1.
Create a new version of API1 with version v2. Now we have 2 apis with context/v1. This should be validated in REST API level as well.

**Comment by Meruja** [comment]
Try to reproduce the issue with the latest pack(3.1.0), but couldn’t do this.
As described above API2 is not allowed to create and a copy of API1 with v2 could be created.
The issue has been already fixed.
