### ISSUE TITLE
Sample API is not displayed to subscribe in Applications in Tenant mode

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#6650]
**Steps to reproduce:**

- Login as tenant
- Deploy sample API
- Login to devportal with same tenant
- Go to public devportal and select the same tenant domain
- Got to Applications and select an applications
- Go to Subscriptions
- You cant see the sample API in the Subscription Management section.

<img width="1415" alt="Screen Shot 2019-10-24 at 1 16 44 PM" src="https://user-images.githubusercontent.com/19324135/67464933-d823db80-f661-11e9-9338-7d99347e14c6.png">

**Comment by dushaniw** [comment]
This is fixed in 3.1.0 alpha. hence closing.
