### ISSUE TITLE
Implicit grant doesn't regenerate the JWT

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#6654]
APIMTokenIssuer needs to override the newly introduced method in OauthTokenIssuer. Please refer [1]

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1193

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1193
