### ISSUE TITLE
When user with publisher only permission logged into publisher allowed to see "deploy sample API" click on it. But it nothing happens.

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#6657]
Please attached screenshot. This button need to be disabled when users logged in with only API publisher role.

![Screen Shot 2019-10-24 at 1 17 00 PM](https://user-images.githubusercontent.com/7975153/67473851-0b219b80-f671-11e9-9823-de739ce8bfe3.png)

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7799
