### ISSUE TITLE
Retired API resources for API Product

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#6674]
**Description**
Discuss how retired api resources should handle in API Products.

- Currently, we can create api product using retired api resources.
- We can invoke retired api resources in a product.

**Comment by uvindra** [comment]
We have addressed this in APIM 3.1.0 in the fix done for https://github.com/wso2/product-apim/issues/6912

Creating API Products using APIs that in the following states are no longer allowed

PROTOTYPED
BLOCKED
DEPRECATED
RETIRED
