### ISSUE TITLE
Add the admin REST API to the publisher profile

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6686]
Profile optimizer needs to be change to add the admin REST API to the publisher profile.

**Comment by dushaniw** [comment]
Need to add it devportal profile as well

**Comment by bhathiya** [comment]
do we need it? we usually access admin APIs and portal in the publisher node.

**Comment by dushaniw** [comment]
what about using application import export cli from devportal ?

**Comment by bhathiya** [comment]
I see, ok.
