### ISSUE TITLE
Scopes can be added with non existing roles

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#6694]
A role validation doesn't happen to check whether the provided role is available in the environment, when adding a new scope

Affected version : APIM 3.0 rc3

**Comment by kavishkafernando** [comment]
working in latest 3.1.0 pack.
<img width="1107" alt="Screen Shot 2019-11-15 at 3 20 50 PM" src="https://user-images.githubusercontent.com/19324135/68933856-8b907380-07bb-11ea-97a7-1af53db3a29c.png">
