### ISSUE TITLE
[Publisher][UI] Same scope key can be assigned to scope of multiple APIs

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#6696]
There should be a UI validation to block the creation of scopes by the same name across APIs.
in RC3 we can create the same scope for two APIs. But when trying to assign the scope to the second API (after assigning it to one API) an error is logged in console and no error is shown in UI.
ERROR - ApisApiServiceImpl Scope test is already assigned by another API

Affected version : APIM 3.0 rc3

**Comment by kavishkafernando** [comment]
Fixed in latest 3.1.0 pack

<img width="1281" alt="Screen Shot 2019-11-15 at 3 24 32 PM" src="https://user-images.githubusercontent.com/19324135/68934204-3f91fe80-07bc-11ea-8f4a-a3720819a3f1.png">
