### ISSUE TITLE
[Publisher] [UI] Make visual workflow aspect of 3 step publishing process clearer

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6707]
Current visual representation of the API publishing flow looks like following after clicking on 'Deploy sample API'.

<img width="997" alt="Screen Shot 2019-10-28 at 1 13 24 PM" src="https://user-images.githubusercontent.com/27903/67700801-087eb900-f985-11e9-8f76-530e99c8e648.png">

Can we please make this visual styling clearer? May be we need to collapse the status icons into the box itself. Maybe we can adopt a coloring scheme? Can we please try some alternatives?

**Comment by kavishkafernando** [comment]
We currently decided on this overview stepper as it was simple for a user to understand. 

We discussed about colour scheming the boxes previously, but it did not look very nice and we thought that it makes it complex as it will include conditional rendering and it would require the users to understand the purpose of the colour schemes as well.

We will try to do some changes and make this stepper more intuitive.
