### ISSUE TITLE
JWTExpiryTime property under APIKeyValidator element cannot be set in the new config model

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#6709]
This section is available in the 2.6.0 docs:
https://docs.wso2.com/display/AM260/Passing+Enduser+Attributes+to+the+Backend+Using+JWT#PassingEnduserAttributestotheBackendUsingJWT-ExpirytimeoftheJWT

This was removed in the 3.0.0 docs since this cannot be set from the deployment.toml file.

**Comment by Krishanx92** [comment]
taggin: https://github.com/wso2/product-apim/issues/7228
