### ISSUE TITLE
Repeating same API resource with different verb while doing an intermediate save leads to duplication

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#6711]
When creating an API, 

1. Add an API resource '/foo' with verb GET and then save the API.
2. Now add and API resource '/foo' with the verb POST to the same API and save it.
3. Generated Swagger definition contains a duplicate entry for '/foo' resource, instead consolidating the GET and POST under a single '/foo' resource. 
4. Final result is an invalid swagger definition.

This issue does not arise if we add both '/foo' GET and '/foo' POST at once and then save the API. Issue is specific to doing a intermediate save between adding resources.

**Comment by Sarangan0219** [comment]
This issue is not present in the latest version of APIM .Hence it can be closed.

![Screenshot from 2020-03-03 09-48-49](https://user-images.githubusercontent.com/60866295/75742651-483f1e00-5d34-11ea-8b91-2f0614bb825a.png)
