### ISSUE TITLE
Creator of the API only can configure the Abnormal Response Time Manage alert.

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#6714]
**Description:-** We have created an API(Pizzashack) using a user(say Abc) then we are able to configure the Abnormal Response Time alert in manage alert tab. But when we login to the publisher using the admin account we are not able to see the API in the dropdown menu. We have attached an image for reference.

**Affected version:-** API Manager 2.6.0

**Steps to reproduce:-**  

- Configure the APIM with apim analytics node.
- Create a new user in the carbon console in the API Manager
- Publish an API using the created user.
- Then go and check whether that user can configure the Abnormal Response Time in manage alert tab. Here the user can configure the manage alert and API is listed in the drop-down menu.
- Go to the publisher using the admin account and check whether the admin user can configure the manage alerts. 
- When listing the apis in the API dropdown menu apis are not showing for the admin user but it is showing for the creator of the API(user Abc).

![image](https://user-images.githubusercontent.com/32807418/67762370-4bb35780-fa6b-11e9-9405-a7472a629d5f.png)

Ideally, if the API is public and visible to all the users, when configuring the Abnormal Response Time in the manage alert tab, the API should be visible to all users. But here it is available only to the API Creator.

**Comment by kavishkafernando** [comment]
Public comment: #https://github.com/wso2/carbon-apimgt/commit/80bb6e61a969df33699f1ff005f85f9dfdde01aa
