### ISSUE TITLE
Create api from GraphQL definition UI overlaps footer

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-apim#6716]
<img width="1435" alt="Screen Shot 2019-10-29 at 1 35 50 PM" src="https://user-images.githubusercontent.com/525801/67807147-798ba280-fa51-11e9-9736-9182277d3483.png">
See above screenshot.

**Comment by Sarangan0219** [comment]
In the latest version APIM this overlapping is resolved. Hence this can be closed.

![Screenshot from 2020-02-25 10-40-24](https://user-images.githubusercontent.com/60866295/75216848-5aacdb00-57bb-11ea-80bd-788112324ecf.png)
