### ISSUE TITLE
[Publisher] [UI] API overview page inconsistencies

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6717]
Looking at following page there seems to be couple of inconsistencies and oddities,
<img width="1323" alt="Screen Shot 2019-10-29 at 5 10 09 PM" src="https://user-images.githubusercontent.com/27903/67809505-2fb1b500-fa6f-11e9-9016-fa3e9b99b484.png">

1. There's too much information there, is it possible to refactor and simplify?
2. Endpoints, Resources and some parts of Configuration section repeats at the left hand menu. However, not everything. Why? May be we can collapse everything to the left menu?
3. Some information can be changed, like for example Transports, Endpoints. Some information cannot be changed - the version, context. There's no visual (or textual) indication that there's a difference
4. Some information, I feel can be simplified and made a little easy to read. For example Provider can be renamed as 'Created By'
5. Workflow Status seems out of place. There's no information to indicate the presences (or lack of) workflow configuration. Should we detect whether workflow engine is configured and display status here?

**Comment by tmkasun** [comment]
Hi @chintana ,

There's too much 

> information there, is it possible to refactor and simplify?

Could you please point of the fields that you think it's not fitting here?

> Endpoints, Resources and some parts of Configuration section repeats at the left hand menu. However, not everything. Why? May be we can collapse everything to the left menu?

If we show all the resources and endpoint details here, There would be too much information on the overview page. Idea was to show the essential information here.

> Some information can be changed, like for example Transports, Endpoints. Some information cannot be changed - the version, context. There's no visual (or textual) indication that there's a difference

This is a read-only page, If user want's to change any parameter they need to navigate to respective pages. IMO showing editable and non-editable (or immutable API properties) in overview page might confuse the user  

> Some information, I feel can be simplified and made a little easy to read. For example Provider can be renamed as 'Created By'

Agree

> Workflow Status seems out of place. There's no information to indicate the presences (or lack of) workflow configuration. Should we detect whether workflow engine is configured and display status here?

Agree, We can hide the workflow status field if they haven't enabled workflow.

**Comment by chintana** [comment]
First off, we need to ask the question "what information is absolutely necessary for the end user that's looking at this overview page". To me it looks like a summary. If that's true, then we need to be able to show this in a much more user friendly manner. May be we can hide sections to reveal additional info.

If we're showing a summary, then we also need to ask the question, by showing that section, what user can/cannot do. Just by showing the rest resources have meaning/usefulness here? User can always click on Resources on the left menu and go there to view the full resource list.

The point I'm trying to make here is that we seem to have shown the exact same information that was in previous UI. We haven't thought about the actual user experience of this UIs. Please do correct me if I'm wrong

**Comment by nuwand** [comment]
Yes this is a summary page. And from my judgement, this contains the bare minimum information of an API that is important to view at first glance for an API developer. We can probably remove 'workflow status' and 'endpoint security' from this page. But other than that the other information is quite useful IMO. For example, the resources are the "meat" of the API. That's essentially where the operations of the API are defined in. While its true that one can view the resources in its own tab, giving a first glance at the resources I think is absolutely necessary because that is what gives an indication of what this API does. And as you can see we don't show all resources here, its only a few because the intention here is to provide a quick glance at the API and not display all the detail, which are available in their respective tabs.

**Comment by chintana** [comment]
> Yes this is a summary page. And from my judgement, this contains the bare minimum information of an API that is important to view at first glance for an API developer. We can probably remove 'workflow status' and 'endpoint security' from this page. 

IMO this page needs to be redesigned from a UX point of view.

> But other than that the other information is quite useful IMO. For example, the resources are the "meat" of the API. That's essentially where the operations of the API are defined in. While its true that one can view the resources in its own tab, giving a first glance at the resources I think is absolutely necessary because that is what gives an indication of what this API does. And as you can see we don't show all resources here, its only a few because the intention here is to provide a quick glance at the API and not display all the detail, which are available in their respective tabs.

What this glance of resources trying to show? Is it the most used resources? If there are 10 resources, what do we show here? If it's arbitrary then it's of no value.

As a developer, you care about how your API is being used, who is using it, from what applications, who changed it, what changed last (was there any new resources added, who added them etc...), were there any errors, what's the error rate, response times from the backend and so on.

Yes, most of these you can find from the stats page. However, that's more useful for the API developer as the overview page. You come to an API and you see a summary of useful info.

**Comment by Tomas-Mrazek** [comment]
My 2¢
-  "tags" should be in the left, because it's just a different way to describe API. It really shouldn't be under "Configuration".
- Metadata should contain, if this API version is default or not. That is IMO mandatory property.
- I agree with @nuwand , I would remove Endpoint Security and Workflow Status, but the rest is just fine.
