### ISSUE TITLE
[Publisher] [UI] URL pattern editing doesn't render correctly in Safari 13.0.2 (macos Catalina)

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6721]
<img width="558" alt="url-pattern" src="https://user-images.githubusercontent.com/27903/67824522-2daa1f00-fa8c-11e9-8c3a-744a2a55dbdc.png">

**Comment by chanaka3d** [comment]
Checked with the carbon-apimgt -  6.8.42-SNAPSHOT. This issue is fixed.
