### ISSUE TITLE
[Publisher] [UI] Scrolling becomes jittery in Resources section after you expand API resources. Scrolling is fast on other pages.

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#6722]
Happens in Safari 13.0.2 (macos Catalina)

Here's a link to a video - https://giphy.com/gifs/hu1JELWOUwsbQ9Juw7

**Comment by tmkasun** [comment]
Yes, This is a known issue we have done some improvements to make the transitions/animations smooth (Prevent blocking main thread), But still, there are some areas we need/can improve in order to work smoothly with low-end devices.

https://github.com/wso2/product-apim/issues/5736

**Comment by chintana** [comment]
FYI this is not happening on a low-end device. Here are the specs,

<img width="275" alt="Screen Shot 2019-11-01 at 4 36 59 PM" src="https://user-images.githubusercontent.com/27903/68062167-dd1e0600-fcc5-11e9-8429-192feee9920e.png">

**Comment by tmkasun** [comment]
Hi @chintana-zz ,

We have done various improvements to the resources page since 3.0.0 GA and  I tried to reproduce this issue recently in the latest Safari version, but could not reproduce the issue

This is how its work in Safari 13.0.4 (same os version as yours)  https://youtu.be/enh6yHMFyrc

**Comment by daz96050** [comment]
This issue is evident on APIs that have a lot of resources. 
I've noticed this to be very prevalent when importing the APIM Publisher OAS into the publisher. (it has a lot of resources)

**Comment by tmkasun** [comment]
@daz96050 , We have made some improvements in this resources page in publisher to handle API definitions with a large amount of resources/operations. Are you using the latest version of API Manager(3.2.0), Even if not, can you please attach the swagger/open API definition that you have imported to API Manager ?

**Comment by daz96050** [comment]
I was importing the swagger found [here](https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml)

And I noticed these issues in 3.1.0, I have not tried to re-create the issue in 3.2.0 yet.

**Comment by tmkasun** [comment]
Ok thanks
