### ISSUE TITLE
WSDL Element Types do not properly mapped when generating Rest APIs using SOAP Endpoints

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#6732]
**Description**
When generating the swagger definition while creating a Rest API using a WSDL definition, the WSDL types are not mapped accordingly. Thus, the attribute lists of the models are empty in the API definition.

**Affected product version**
wso2am-2.6.0

**Steps to reproduce**
1. Use a wsdl file in which the complex types of elements are defined separately.
ex:- 
2. Generate Rest API by providing the relative path to the wsdl file from Publisher.
> I have a SOAP Endpoint -> WSDL Url -> Generate REST APIs
3. Check the swagger definition.

**Comment by vithu30** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130
