### ISSUE TITLE
Get rid of the 'Logout confirmation' page

### ISSUE THREAD

**Issue by shazni** [wso2/product-apim#6735]
It's nice that API-M 3.0.0 is using OIDC to login and also uses SSO to login to the developer portal if you are already logged into the API publisher. But when someone logs out, I think it's unusual to ask for a 'logout confirmation'. It's better to get rid of it.

**Comment by CrowleyRajapakse** [comment]
The above issue is addressed from the mentioned PR hence the issue can be resolved.
