### ISSUE TITLE
[3.0.0][UI] Deleting one resource parameter deletes all the existing parameters

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#6737]
Steps:

- Create an API
- Go to the Resources page and add Resource Parameters and Save the api.
- Delete one of the Parameters from the list.

**Comment by kavishkafernando** [comment]
Fixed in latest pack

**Comment by kavishkafernando** [comment]
Seems like if you delete a parameter in the middle of the parameter list parameters below that will also get deleted
