### ISSUE TITLE
[Store] Request URLs are wrong on tryout window

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-apim#6744]
When switching between "http" and "https" on tryout window, the request URLs are not changing accordingly.  Instead only the protocol part is changing. Please refer below screenshots. Note that the port should have changed accordingly.

**HTTP**
<img width="1416" alt="Screenshot 2019-10-31 at 14 25 30" src="https://user-images.githubusercontent.com/8380840/67932905-cbb3fb80-fbea-11e9-900b-72af90a7ea18.png">

**HTTPS**
<img width="1156" alt="Screenshot 2019-10-31 at 14 27 56" src="https://user-images.githubusercontent.com/8380840/67932936-d7072700-fbea-11e9-9c33-ecba13bc8b0d.png">

**Affected Product Version:**
APIM 3.0.0

**Browser**
Chrome 78.0.3904.70 (Official Build) (64-bit)

**OS Version**
System Version: macOS 10.15 (19A602)
Kernel Version: Darwin 19.0.0
Boot Volume: HDD
Boot Mode: Normal
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled

**Comment by dushaniw** [comment]
Same issue https://github.com/wso2/product-apim/issues/6878
