### ISSUE TITLE
Configuring app_access_token_validity validity under oauth.token_validation in toml not populated in the UI for new applications

### ISSUE THREAD

**Issue by nalakas** [wso2/product-apim#6750]
we can customize access token validity period in UI for a new application we are creating by modifying in toml file.

when we use curl command it takes the configured validity period from toml.
when we try to generate a token from UI it shows the validity period 3600 which is an old one.

product version:3.0.0

**Comment by vithu30** [comment]
Same behavior is observed for migrated applications (from 2.6.0) which have custom access token validity period configured.
Tested db: PostgreSQL
