### ISSUE TITLE
Hard-coded localhost j2 Config Templates and Repository Config

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6752]
Hello everybody,
I've noticed that you've hard-coded "localhost" in many places in the j2 templates and in / config directory.
These settings result in an external call from / publisher's website redirecting to localhost and the page can not be displayed.
Is this the desired behavior or error?
I observed this behavior when installing Binary, because our main partition does not have enough space and we need to install on separate /data partition.
I'm using SUSE Enterprise Server 12 sp 4
I'm using wso2am-3.0.0.

Thanks

**Comment by ruks** [comment]
@AndreaNim, we have parameterized only the variable field in the configuration. Hence configuration that no need to be configured is hardcoded in the J2 templates. If you noticed any error can you please mention the related configuration?

**Comment by AndreasRusjaev** [comment]
Hello everybody,
I tried the recipes:
[https://apim.docs.wso2.com/en/latest/Administer/ProductConfigurations/changing-the-hostname/](https://apim.docs.wso2.com/en/latest/Administer/ProductConfigurations/changing-the-hostname/)
But at startup, the HostName and MgtHostName are overwritten with localhost.
Only thing that helped, that in all configurations and in all j2 files localhost with the computer name search and replace and afterwards the server certificate change as in:
[https://docs.wso2.com/display/IS580/Changing+the+hostname](https://docs.wso2.com/display/IS580/Changing+the+hostname).
Do you have better recepies how to change hostname?
Thanks

**Comment by uvindra** [comment]
Sorry about the confusion @AndreasRusjaev, we are doing some changes to the docs and the information you are referring to regarding the configuration is being updated.

In APIM 3.0.0 you need to edit the _<APIM_HOME>/repository/conf/deployment.toml_ file in order to change the hostname. The default value is localhost as shown below,


```
[server]
hostname = "localhost"
```

Change this to the desired hostname and restart the server for the changes to take effect. Do not edit the .j2 files directly. The changes you make to the deployment.toml file will be applied to the .j2 files at startup.

**Comment by AndreasRusjaev** [comment]
Hallo @uvindra 
Thank you.
I will try as soon as possible.
I will report on the results.
Best regard

**Comment by uvindra** [comment]
Please refer to https://apim.docs.wso2.com/en/latest/Reference/ConfigCatalog/ in order to learn about the various configurations that are available via the deployment.toml file. 

Unlike in previous APIM versions, you do not directly edit the individual config files(carbon.xml, api-manager.xml, etc..). We have provided a single deployment.toml config to provide a single point to do all configurations in order to improve the user experience.

**Comment by AndreasRusjaev** [comment]
Hello @uvindra 
I tried your suggestion.
It worked thank you.
There are only 2 points where the localhosts are presented:
1) _JMXServerManager JMX Service URL: service: jmx: rmi: // **localhost**: 11111 / jndi / rmi: // **localhost**: 9999 / jmxrmi._
2) The apllications on Catalina:
_[2019-11-04 19: 31: 54,788] INFO - TomcatGenericWebappsDeployer Deployed webapp: StandardEngine [Catalina] .StandardHost [**localhost**] .StandardContext [/ accountrecoveryendpoint] .File [/data/wso2/wso2am-3.0.0/repository/deployment / server / webapps / accountrecoveryendpoint]_
etc
My question: should be like this or I miss something in deployment.toml?

**Comment by uvindra** [comment]
Hi @AndreasRusjaev,

Here is what needs to change for the above,

1. For JMXServerManager related server URL, add following entry to the deployment.toml file

```
[monitoring.jmx]
rmi_hostname = "your-custom-domain"
```

2. For Catalina server URL, it seems we have not templated this value in the corresponding _catalina-server.xml.j2_ file by default. Therefore to make this work open the file _<APIM_HOME>/repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2_ and do the following change,

```xml
<Engine name="Catalina" defaultHost="{{server.hostname}}">

            <Realm className="org.wso2.carbon.tomcat.ext.realms.CarbonTomcatRealm"/>

            <Host name="{{server.hostname}}" unpackWARs="true" deployOnStartup="false" autoDeploy="false"
                  appBase="${carbon.home}/repository/deployment/server/webapps/">
                <Valve className="org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve"
                       headerToCorrelationIdMapping="{'activityid':'Correlation-ID'}" queryToCorrelationIdMapping="{'RelayState':'Correlation-ID'}"/>
                <Valve className="org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve"/>
                <Valve className="org.apache.catalina.valves.AccessLogValve" directory="${carbon.home}/repository/logs"
                       prefix="http_access_" suffix=".log" pattern="%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %T"/>
                <Valve className="org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve" threshold="600"/>
                <Valve className="org.wso2.carbon.tomcat.ext.valves.CompositeValve"/>

                <!-- Authentication and Authorization valve for the rest apis and we can configure context for this in identity.xml  -->
                <Valve className="org.wso2.carbon.identity.auth.valve.AuthenticationValve"/>
                <Valve className="org.wso2.carbon.identity.authz.valve.AuthorizationValve"/>
                <Valve className="org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve"/>
                <!--Error pages -->
                <Valve className="org.apache.catalina.valves.ErrorReportValve" showServerInfo="false" showReport="false"/>
            </Host>
        </Engine>

```

Note the change done to `<Engine name="Catalina" defaultHost="{{server.hostname}}">` and `<Host name="{{server.hostname}}" unpackWARs="true" deployOnStartup="false" autoDeploy="false" appBase="${carbon.home}/repository/deployment/server/webapps/">`

Here we have reused the same value you have already cofigured in the deployment.toml for the **server.hostname**


This should get rid of the reference to localhost that you are seeing. Let us know if you need any further assistance.

**Comment by AndreasRusjaev** [comment]
Thanks

**Comment by dushaniw** [comment]
Hi @AndreasRusjaev  we are closing the issue. Feel free to reopen if you run into any issue.
