### ISSUE TITLE
Error on Update of Message Tracing Configuration 

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6753]
Hello Everybody,
I have Error is i enable message tracing. see Image and log.
All my computer have the same error.
Wich service must i intall to message tracing in api manager?

I have wso2am-3.0.0.
Computer: windows 7 x64, Ubuntu 18:04 x64, SLES 12 sp4.

[Message Tracing Configuration Error.Log](https://github.com/wso2/product-apim/files/3800670/Message.Tracing.Configuration.Error.Log)
![Message Tracing Configuration Error](https://user-images.githubusercontent.com/18263592/68073686-e7f29c80-fd92-11e9-8b8e-784561659281.jpg)

Thanks

**Comment by uvindra** [comment]
Hi @AndreasRusjaev,

Are you trying to view the message flow in the Gateway when APIs are being invoked?

In that case you can achieve this by enabling synapse wire logs on the gateway as follows,

In _<APIM_HOME>/repository/conf/log4j2.properties_, append the entry **synapse-wire** to the end of the _loggers_ string as follows,

`loggers = AUDIT_LOG, trace-messages, org-apache-coyote, com-hazelcast, Owasp-CsrfGuard, org-apache-axis2-wsdl-codegen-writer-PrettyPrinter, org-apache-axis2-clustering, org-apache-catalina, org-apache-tomcat, org-wso2-carbon-apacheds, org-apache-directory-server-ldap, org-apache-directory-server-core-event, com-atomikos, org-quartz, org-apache-jackrabbit-webdav, org-apache-juddi, org-apache-commons-digester-Digester, org-apache-jasper-compiler-TldLocationsCache, org-apache-qpid, org-apache-qpid-server-Main, qpid-message, qpid-message-broker-listening, org-apache-tiles, org-apache-commons-httpclient, org-apache-solr, me-prettyprint-cassandra-hector-TimingLogger, org-apache-axis-enterprise, org-apache-directory-shared-ldap, org-apache-directory-server-ldap-handlers, org-apache-directory-shared-ldap-entry-DefaultServerAttribute, org-apache-directory-server-core-DefaultDirectoryService, org-apache-directory-shared-ldap-ldif-LdifReader, org-apache-directory-server-ldap-LdapProtocolHandler, org-apache-directory-server-core, org-apache-directory-server-ldap-LdapSession, DataNucleus, Datastore, Datastore-Schema, JPOX-Datastore, JPOX-Plugin, JPOX-MetaData, JPOX-Query, JPOX-General, JPOX-Enhancer, org-apache-hadoop-hive, hive, ExecMapper, ExecReducer, net-sf-ehcache-config-ConfigurationFactory, axis2Deployment, equinox, tomcat2, StAXDialectDetector, trace, synapse, synapse_transport, axis2, axis2_transport, org-wso2-carbon, hunsicker, thrift-publisher, service_logger, trace_logger, org-wso2-carbon-apimgt-gateway-mediators-BotDetectionMediator,correlation,` **synapse-wire**

Save the file and the changes will automatically take affect without having to do a restart.

Now you will be able to see the wire level messages in the wso2carbon.log that are being received and sent by the gateway.

Hope this helps you achieve you requirement. If not please let us know what you are trying to achieve.

**Comment by AndreasRusjaev** [comment]
Hallo @uvindra
Thank you.
I will try as soon as possible.
I will report on the results.
**But I would like to point out this error again because it has worked in 2.6.0.**
Best regard
