### ISSUE TITLE
Error creating custom request message mediation om Windows 7 and 10

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6754]
Hello everybody,
i have error at create custom request mediation see image and log.
Error comes after save click
I send mediation xml file to.
I tested on windows 7 (behind corporate proxy) and 10 (in free internet)
I have WSO2 Api Manager 3.0.0 installed with windows installer.

Reproduction steps:
1 click edit mendiation.
2. in pop-up window choose custom
3. cklick on cloud image and choose file from hard disk.
4. click select.
5. click save button.

![Request Message Mediation Error](https://user-images.githubusercontent.com/18263592/68074117-f1323800-fd97-11e9-99a0-918e1de23eb9.jpg)
[Request Message Mediation Error.log](https://github.com/wso2/product-apim/files/3800715/Request.Message.Mediation.Error.log)
[set_api_key_to_backend_api.txt](https://github.com/wso2/product-apim/files/3800716/set_api_key_to_backend_api.txt)

Thanks

**Comment by Rajith90** [comment]
It seems like this is a bug, we have used File.separators when accessing registry path, which causes wrong path for registry. When accessing registry always have to be the "/" not the File.separator

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7835
