### ISSUE TITLE
Make API Monetization checkbox color primary

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-apim#6762]
1. Make API Monetization checkbox color primary

![image](https://user-images.githubusercontent.com/3960742/68117489-75fd8d00-ff23-11e9-8020-87adfa6094a0.png)

2. Page title style does not match the other pages.

3. Fix scrollbars

4. Fix input boxes to match with other pages.

**Comment by chanaka3d** [comment]
This is fixed with the latest snapshot build (6.8.33-SNAPSHOT)
