### ISSUE TITLE
Incorrect selection in the side bar in Dev Portal

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#6767]
**Description**
In the API Developer portal, if we navigate to an APIs 'Try out' tab (Try-out page.png) and then go back to API listing and again open  the same API, although the overview page(overview.png) is rendered, the sidebar selection still shows 'Try out'

<img width="1678" alt="Try-out page" src="https://user-images.githubusercontent.com/20040505/68270239-b1fb3400-0082-11ea-997f-02b75bd8627d.png">
<img width="1680" alt="overview" src="https://user-images.githubusercontent.com/20040505/68270238-b1629d80-0082-11ea-9fbb-23797236ca4b.png">

**Comment by kavishkafernando** [comment]
Fixed in latest pack 3.1.0 pack.

<img width="791" alt="Screen Shot 2019-11-25 at 11 21 52 AM" src="https://user-images.githubusercontent.com/19324135/69515821-cd68a900-0f75-11ea-8bca-978b6ef6e6f6.png">

**Comment by ruwiniwj** [comment]
This error reoccurred in the latest build

<img width="1680" alt="Screen Shot 2019-12-12 at 5 31 04 PM" src="https://user-images.githubusercontent.com/20040505/70711352-5a965680-1d07-11ea-87c7-74c6b654b02c.png">

**Comment by ruwiniwj** [comment]
this issue is not reproducible in the latest pack, hence closing.
