### ISSUE TITLE
Insufficient error messages while using the Publisher Rest API when updating the API

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#6770]
**Description:-** When we publish the api they are inputting a not valid subscription tier. So when they update the api using the rest publisher api they are only getting the following information.
{"code":500,"message":"Internal server error","description":"Error while updating API : 3ca7c17e-4257-4869-b287-ec96836969ea","moreInfo":"","error":[]}
This information is not enough for us to troubleshoot the problem. When we use the publisher api to create the api we are getting more information which is enough to troubleshoot the problem.
{"code":500,"message":"Internal server error","description":"Error while adding new API : admin-PizzaShackAPI-1.0.0 - Invalid x-throttling tier Bronze_Auto_Approved found in api definition for resource POST /order","moreInfo":"","error":[]}
When we further analyze the code (org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl)  we figured out that in the apisPost() method we had following code in the error message 

```
String errorMessage = "Error while generating the swagger since the wsdl url is null for: " + body.getProvider() + "-" + body.getName() + "-" + body.getVersion(); 

RestApiUtil.handleInternalServerError(errorMessage, log);
```

But in the apisApiIdPut() method we had following code.
```
String errorMessage = "Error while updating API : " + apiId;
RestApiUtil.handleInternalServerError(errorMessage, e, log);
```
That’s the reason for getting more information about the error when creating the API and they are not getting more info about the error when updating the API.

**Steps to reproduce** 
Use the publisher rest API to update the API without a valid subscription tier. Then we get the following error message.
{"code":500,"message":"Internal server error","description":"Error while updating API : 3ca7c17e-4257-4869-b287-ec96836969ea","moreInfo":"","error":[]}

**Affected version:-** API Manager 2.6.0

**Comment by chamilaadhi** [comment]
Following messages are provided for API update and swagger update APIs. 

Update API with invalid tier

    curl -k -H "Authorization: Bearer 696fa32c-8c89-3a65-9ede-61babb04b874" -H "Content-Type: application/json" -X PUT -d @data.json https://localhost:9443/api/am/publisher/v0.14/apis/ea0fdd46-0b3f-4fd4-ae66-598d6430263b

Response

    {"code":500,"message":"Internal server error","description":"Error while updating the API : ea0fdd46-0b3f-4fd4-ae66-598d6430263b - Invalid x-throttling tier Invalid_Tier_Name found in api definition for resource GET /test","moreInfo":"","error":[]}


Update swagger with invalid tier

    curl -k -H "Authorization:Bearer 696fa32c-8c89-3a65-9ede-61babb04b874" -F apiDefinition="{\"swagger\":\"2.0\",\"paths\":{\"/test\":{\"get\":{\"responses\":{\"200\":{\"description\":\"\"}},\"x-auth-type\":\"Application & Application User\",\"x-throttling-tier\":\"Invalid_Tier_Name\"}}},\"info\":{\"title\":\"TestAPI\",\"version\":\"1.0\"}}" -X PUT "https://localhost:9443/api/am/publisher/v0.14/apis/ea0fdd46-0b3f-4fd4-ae66-598d6430263b/swagger"

Response

     {"code":500,"message":"Internal server error","description":"Error while updating the swagger definition of the API: ea0fdd46-0b3f-4fd4-ae66-598d6430263b - Invalid x-throttling tier Invalid_Tier_Name found in api definition for resource GET /test","moreInfo":"","error":[]}
