### ISSUE TITLE
[Question] 3.0.0 database active-active deployment?

### ISSUE THREAD

**Issue by Tomas-Mrazek** [wso2/product-apim#6778]
I'm very confused about the new configuration and datasources, could you please provide me some details?

According to documentation, there are 5 databases:
* AM
* Shared
* Carbon
* Metrics 
* MB

1) Which of these databases should stay in H2 and which are free to migrate to different database? 

2) To further confuse me, in `deployment.toml` there are only two databases set up, `[database.apim_db]` and `[database.shared_db]`. How about the rest? I have looked into the j2 template `master-datasources.xml.j2`, where `WSO2_CARBON_DB` and `WSO2_MB_STORE_DB` are hardcoded to H2. And on top of that, there are parametrized databases `WSO2USER_DB` and `WSO2CONFIG_DB`, but there is no single mention anywhere in the documentation about them. Could somebody please clarify proper configuration?

3) Which database scripts belong to which database? There are only four scripts
* /dbscripts/postgresql.sql – Shared or Carbon database? Either way one of them is missing.
* /dbscripts/metrics/postgresql.sql – Metrics
* /dbscripts/mb-store/postgresql-mb.sql – MB (Why, when it's hardcoded in j2 template?)
* /dbscripts/apimgt/postgresql.sql – AM ???

3) Which externalized databases can be shared in both nodes in active-active all-in-one deployment?

Thank you.

APIM Version: 3.0.0
DB: PostgreSQL 11

**Comment by ruks** [comment]
HI @Tomas-Mrazek,

Please find my feedback.

1) Only AM and Shared DB need migration
2) You need to configure only the AM, Shared and User DB. Other DBs can be kept as default.
3) You need to share the AM, Shared and User DB among other components.

Also, note that we are working on document improvement and once complete will update the issue.

**Comment by Tomas-Mrazek** [comment]
So Carbon, Metrics and MB should be H2 even in production environment?

**Comment by Tomas-Mrazek** [comment]
@ruks  In updated documentation, there's this quote: 

> The embedded H2 databases shipped with your product are suitable for suitable for development and testing environments. However, for production environments, it is recommended to use an industry-standard RDBMS such as Oracle, PostgreSQL, MySQL, MS SQL, etc.


This again does raise unanswered questions from my original post:
1) There are only four scripts, but five databases. Where is the fifth script?

- /dbscripts/postgresql.sql – Shared or Carbon database? Either way one of them is missing.
- /dbscripts/metrics/postgresql.sql – Metrics
- /dbscripts/mb-store/postgresql-mb.sql – MB
- /dbscripts/apimgt/postgresql.sql – AM

2) Why there are two databases hardcoded in `master-datasources.xml.j2` instead of being configurable via `deployment.toml`?

**Comment by ruks** [comment]
> So Carbon, Metrics and MB should be H2 even in production environment?
> Why there are two databases hardcoded in master-datasources.xml.j2 instead of being configurable via deployment.toml?

These databases contain the metadata and some runtime data. Since it's those databases are not shared and doesn't contain data to be migrated, we recommend to keep in local H2. Hence we have hardcoded to h2, so dev-ops don't need to worry about them. 

> /dbscripts/postgresql.sql – Shared or Carbon database? Either way one of them is missing.

Carbon, UM and Registry databases use this script. The shared database is also a combination of Carbon, UM and Registry databases, shared database based used the same script.

**Comment by Tomas-Mrazek** [comment]
Ok, understood. Thank you.
