### ISSUE TITLE
Support multiple YAML (Swagger) files when creating an API

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-apim#6794]
Sometimes users need to manage huge API definitions by splitting that into multiple files. From Swagger 2.0 onwards, it supports referencing data residing in other files with $ref keyword. This is somewhat similar to XML references. This would be a handy feature to have in the API Manager product.

**Comment by ruks** [comment]
I think this is support in APIM 3.2.0. @Sarangan0219 can you confirm?

**Comment by Sarangan0219** [comment]
Yes,  We are supporting this from APIM 3.2.0 and the docs are also updated regarding this.https://github.com/wso2/carbon-apimgt/pull/8509
