### ISSUE TITLE
How can i make install bundle from source code of api manager product?

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6801]
Hello everybody
i have seen on the page:
https://wso2.github.io/github-repositories.html.
The product product-apim consists of two repositories:

    carbon-apimgt
    product-apim

How can i integrate carbon-apimgt build in product-apim if i want to make an installation bundle from source code?
Thanks and best regards

**Comment by pubudu538** [comment]
Hi Andreas,

As you can see in [1], it has the version of the carbon-apimgt. If you want to build a pack from the same carbon-apimgt version, then you can use the same version in product-apim [2] and then build the product-apim.

[1] - https://github.com/wso2/carbon-apimgt/blob/master/pom.xml#L9
[2] - https://github.com/wso2/product-apim/blob/master/pom.xml#L1175

Thank you!

**Comment by kavishkafernando** [comment]
If you need further assistance please re-open the issue.
