### ISSUE TITLE
How to change /devportal for /store route in WSO2 API manager V 3.0.0 ?

### ISSUE THREAD

**Issue by JUANPARBELAEZ** [wso2/product-apim#6802]
Hello WSO2 community. 

I had previously implemented WSO2 API manager 2.6 and shared the /store route to potential customers.

I upgraded to the new version, and still have not found a way to change /devportal for /store, and keep the previously communicated routes.

Hope anyonce can help me out, if they know how to set it up, so /store redirects to /devportal, or change the service name altogether.

Kindest regards.

JP

**Comment by tmkasun** [comment]
Hi @JUANPARBELAEZ ,

In the APIM 3.0.0 GA Developer portal apps, There is a configuration file for controlling the application context and reverse proxy configurations.

- goto

```
<APIM-3.0.0-ROOT_DIR>repository/deployment/server/jaggeryapps/devportal/site/public/theme/
```

- and open the `settings.js` file. It contains the application context and reverse proxy configurations parameters.

```javascript
const Settings = {
    app: {
        context: '/devportal',
        reverseProxy: {
            enabled: false,
            origin: 'https://localhost:9443',
        },
    },
.
.
.

};
```

- Change the `app.context` to your desired context name (note: No trailing `/`) and enable the reverse proxy.

- After that login to the carbon console

```
https://<host:port>/carbon
```

- goto `Service Providers > List`

![image](https://user-images.githubusercontent.com/3313885/68669222-082f1200-0570-11ea-85b7-b6fd8fa8edfc.png)

- locate the `admin_admin_store` service provider, click on the edit button
  -  (Note: if you haven't tried to log in to dev portal app, You won't see the above SP created.)

![image](https://user-images.githubusercontent.com/3313885/68669246-141ad400-0570-11ea-9848-217ece86e397.png)

- Open expand `Inbound Authentication Configuration` and  `OAuth/OpenID Connect Configuration` settings and click edit.

- Then update the callback URL pattern in the service provider configurations.

![image](https://user-images.githubusercontent.com/3313885/68668904-3eb85d00-056f-11ea-819f-c253f18aee35.png)

-Click update and update the service provider configurations

- Now try to access your app with modified app context

**Comment by bhathiya** [comment]
Reverse proxy config can be found in https://github.com/wso2/product-apim/issues/6467

**Comment by isharac** [comment]
@JUANPARBELAEZ 
you may refer``,
https://ishara-cooray.blogspot.com/2019/11/how-to-change-devportal-to-different.html

**Comment by kavishkafernando** [comment]
Please re-open the issue if you need further assistance.
