### ISSUE TITLE
Security of newly added resources are off by default

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#6809]
In API Manager 3.0 when you add a new resource to an API the security of the resource is shown as off by default, when its actually on. See image.
<img width="563" alt="error_security_resources" src="https://user-images.githubusercontent.com/6469654/68694985-30cf0000-05a0-11ea-8dc9-9c20e9d1c76d.png">

**Comment by tmkasun** [comment]
@nuwand , I was able to reproduce this issue and noticed the following behavior 

- When click `save` in the resource page API PUT does not add the `x-wso2-auth` parameter to the resource (unless the user explicitly enables or disable security), Expecting it to be set by REST API implementation. We set only the minimum required parameters for operation unless user add/remove or modify them after adding the resource

i:e 

```json
"/sample": {
      "get": {
        "responses": {
          "200": {
            "description": "ok"
          }
        },
        "parameters": []
      }
    }
```

- In the response of the above PUT we get 

```json
"/sample": {
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "description": "ok"
          }
        },
        "security": [
          {
            "default": []
          }
        ],
        "x-auth-type": null,
        "x-throttling-tier": null
      }
    }
``` 

the diff between the above operation definition and the one we originally set was added by REST implementation when updating the swagger.

- And now if we re-publish the API , The `x-auth-type` parameter gets `Application & Application User` even user does not change the security status.

**Comment by tmkasun** [comment]
Reopening this issue, Since the https://github.com/wso2/carbon-apimgt/pull/7855 PR only address the UI issue. We need to set the `x-auth-type` parameter to `Application & Application User` if the user hasn't specified any value to `x-auth-type` parameter when updating the swagger.

**Comment by tmkasun** [comment]
@tharindu1st Hope you are working on this 😃

**Comment by msm1992** [comment]
If x-auth-type is not defined in the imported swagger definition, it will be auto set to “Any” which is then converted to ‘Application & Application User’ at updateOperationManagedInfo() in swagger parsers.
