### ISSUE TITLE
Implemet whitelisted hostname in devportal

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#6810]
We need to implement whitelisted hostname feature described in [1] .

[1] https://docs.wso2.com/display/AM260/Whitelisting+Hostnames+for+API+Store

**Comment by dushaniw** [comment]
APIM 3.0 DevPortal is a SPA application and we do not specifically use the host header value within the application. The authorization and login redirection URLs are constructed using the server hostname in deployment.toml or using the X-Forwarded-Host header value when using custom store URLs.  Even though, someone changes the host header in the middle of the request, the redirections would fail as the callback urls of the client application will be validated against the persisted URL created from the config. Hence, currently, there is no security issue of the host header attack for Publisher SPA, so we would not need this feature for that usecase.
