### ISSUE TITLE
scheme's port dose not change from https to http in Api Devportal [APIM 3.0.0]

### ISSUE THREAD

**Issue by YEOUNUIHA** [wso2/product-apim#6811]
**Description:**
In Api Devportal's Try Out, I try to change schemes "https" to  "http".
But, Just chanage protocol like this, https://localhost:8243 to http://localhost:8243.

when select scheme as http and execute api ,I saw warning "SourceHandler I/O error: Unrecognized SSL message, plaintext connection?"

**Comment by tmkasun** [comment]
Hi @YEOUNUIHA ,

We do not recommend nor support serving web or REST API requests over HTTP (unsecured HTTP), So I think it's better if you can switch to use HTTPS.

**Comment by kavishkafernando** [comment]
Please re-open the issue if you need further assistance.
