### ISSUE TITLE
Problem with getting Car Application structure in API Manager 3.0.0

### ISSUE THREAD

**Issue by igkononov** [wso2/product-apim#6820]
Hello,

I have a question about Carbon functionality.

My steps:
- deploy car application in API Manager console. As a result:
<img width="1156" alt="Screen Shot 2019-11-13 at 1 41 51 PM" src="https://user-images.githubusercontent.com/56588985/68760980-c2c81e80-061b-11ea-81cd-7a98c511694e.png">
- get car application structure using link from applications list. Result:
<img width="1167" alt="Screen Shot 2019-11-13 at 1 42 14 PM" src="https://user-images.githubusercontent.com/56588985/68761039-e12e1a00-061b-11ea-88b0-b8cafcabad63.png">
So, it's impossible to get car application structure.

Could you, please, clarify, is it a bug?

Thanks in advance.

**Comment by Tomas-Mrazek** [comment]
Look into logs, if car was really deployed. There is probably something like "There is no artifacts to deploy". That means you need to enable ServerRole `EnterpriseServiceBus` and/or `EnterpriseIntegrator` in APIM Carbon console -> Configuration -> Server Roles

**Comment by tharindu1st** [comment]
HI @igkononov @Tomas-Mrazek ,
API Manager design to deploy APIs , Therefore we don't have Carbon application deployer feature on APIM product.

**Comment by igkononov** [comment]
Hi @tharindu1st

Thanks for your answer.

**Comment by Tomas-Mrazek** [comment]
@tharindu1st Is there any risk on enabling said Enterprise Integrator and ESB roles in API Manager 3.0.0 and deploying Composite Applications?
