### ISSUE TITLE
WSO2 API Manager - Based on product backend Test Module FAILURE [33:59 min]

### ISSUE THREAD

**Issue by maozhentan** [wso2/product-apim#6823]
I have some problems after compiling through source code. what should i do？

problem：
信息: Jacoco coverage HTML report path : F:\project\product-apim-3.0.0\modules\integration\tests-integration\tests-backend\target\jacoco\coverage\index.html
[ERROR] Tests run: 281, Failures: 2, Errors: 0, Skipped: 27, Time elapsed: 1,995.706 s <<< FAILURE! - in TestSuite
[ERROR] deployWebApps(org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig)  Time elapsed: 51.168 s  <<< FAILURE!
java.lang.NullPointerException
	at org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig.createAPIs(AdvancedWebAppDeploymentConfig.java:100)
	at org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig.initialize(AdvancedWebAppDeploymentConfig.java:95)
	at org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig.deployWebApps(AdvancedWebAppDeploymentConfig.java:83)

[ERROR] cleanUpArtifacts(org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig)  Time elapsed: 0.001 s  <<< FAILURE!
org.wso2.am.integration.clients.publisher.api.ApiException: Missing the required parameter 'apiId' when calling apisApiIdDelete(Async)
	at org.wso2.am.integration.tests.other.AdvancedWebAppDeploymentConfig.cleanUpArtifacts(AdvancedWebAppDeploymentConfig.java:89)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AdvancedWebAppDeploymentConfig.cleanUpArtifacts:89 » Api Missing the required ...
[ERROR]   AdvancedWebAppDeploymentConfig.deployWebApps:83->initialize:95->createAPIs:100 » NullPointer
[INFO] 
[ERROR] Tests run: 266, Failures: 2, Errors: 0, Skipped: 12
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WSO2 API Manager - Aggregator Module 3.0.0:
[INFO] 
[INFO] WSO2 API Manager - Aggregator Module ............... SUCCESS [  6.053 s]
[INFO] WSO2 API Manager - Styles Parent ................... SUCCESS [  0.039 s]
[INFO] WSO2 API Manager - Styles .......................... SUCCESS [  4.449 s]
[INFO] WSO2 Stratos  API Manager - UI styles .............. SUCCESS [ 16.296 s]
[INFO] WSO2 API Manager - Multi Tenant Dashboard .......... SUCCESS [  2.479 s]
[INFO] WSO2 API Manager - Features Parent ................. SUCCESS [  0.029 s]
[INFO] WSO2 API Manager - Features Aggregator Module ...... SUCCESS [  0.078 s]
[INFO] WSO2 API Manager - Styles Features ................. SUCCESS [  2.114 s]
[INFO] WSO2 API Manager - Multi Tenant Dashboard Feature .. SUCCESS [  3.314 s]
[INFO] Samples ............................................ SUCCESS [  3.937 s]
[INFO] Clients for samples ................................ SUCCESS [  0.361 s]
[INFO] Publisher API client ............................... SUCCESS [  6.805 s]
[INFO] Developer Portal API client ........................ SUCCESS [  1.960 s]
[INFO] Admin API client ................................... SUCCESS [  2.484 s]
[INFO] Back end Service ................................... SUCCESS [  6.251 s]
[INFO] Sample Utils ....................................... SUCCESS [ 10.488 s]
[INFO] Sample One ......................................... SUCCESS [16:16 min]
[INFO] Sample Two ......................................... SUCCESS [ 44.592 s]
[INFO] Sample Four ........................................ SUCCESS [ 41.801 s]
[INFO] Sample Seven ....................................... SUCCESS [ 37.561 s]
[INFO] Sample Eight ....................................... SUCCESS [ 50.242 s]
[INFO] Sample Nine ........................................ SUCCESS [ 51.250 s]
[INFO] Sample Ten ......................................... SUCCESS [ 45.089 s]
[INFO] WSO2 API Manager - P2 Profile Generation Parent .... SUCCESS [  0.057 s]
[INFO] WSO2 API Manager - P2 Profile Generation ........... SUCCESS [  01:09 h]
[INFO] API Manager : oauth2-grant-types ................... SUCCESS [ 12.076 s]
[INFO] API Manager : outbound-authenticators .............. SUCCESS [  1.328 s]
[INFO] WSO2 API Manager - Distribution Parent ............. SUCCESS [  4.768 s]
[INFO] WSO2 API Manager - Distribution .................... SUCCESS [11:04 min]
[INFO] WSO2 API Manager - Integration Tests ............... SUCCESS [ 17.192 s]
[INFO] WSO2 API Manager - Integration Test Common Module .. SUCCESS [  1.766 s]
[INFO] WSO2 API Manager - Integration Admin Clients Module  SUCCESS [ 35.227 s]
[INFO] WSO2 API Manager - Integration Clients Module ...... SUCCESS [  1.871 s]
[INFO] Publisher API client ............................... SUCCESS [ 42.755 s]
[INFO] Store API client ................................... SUCCESS [ 13.219 s]
[INFO] WSO2 API Manager - Integration Common Test Module .. SUCCESS [ 14.915 s]
[INFO] WSO2 API Manager - Test Artifacts Tests ............ SUCCESS [  1.916 s]
[INFO] WSO2 API Manager - RestFul Backend Module for Integration Tests SUCCESS [  3.808 s]
[INFO] WSO2 API Manager - ArtifactDeploymentMonitor WebApp  SUCCESS [02:10 min]
[INFO] org.wso2.am.framework.extensions ................... SUCCESS [  4.424 s]
[INFO] WSO2 API Manager - Integration Extensions Module ... SUCCESS [  3.391 s]
[INFO] WSO2 API Manager - Integration UI Pages Module ..... SUCCESS [  2.574 s]
[INFO] WSO2 API Manager - Integration New Test Module ..... SUCCESS [  1.865 s]
[INFO] WSO2 API Manager - Based on product backend Test Module FAILURE [33:59 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:21 h
[INFO] Finished at: 2019-11-14T16:00:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project org.wso2.carbon.am.integration.backend.test: There are test failures.
[ERROR] 
[ERROR] Please refer to F:\project\product-apim-3.0.0\modules\integration\tests-integration\tests-backend\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.wso2.carbon.am.integration.backend.test

**Comment by mushthaq33** [comment]
Hi @maozhentan , 

Thanks for getting back to us. This issue seems to be fixed now. Could you please try and build the latest source code and see if you are getting the same issue?

Thanks
