### ISSUE TITLE
Internal Role names are not validated properly when defining scopes in publisher

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#6824]
**Description:**
When creating scope from the publisher, it will always validate the role. If we enter an invalid role it won’t allow creating the scope and it will show an error message. 
![image](https://user-images.githubusercontent.com/32807418/68842760-f0c96380-06ec-11ea-9a3a-40777aabdb41.png)

But when we create an internal role (for example:- internal/test instead of Internal/test) with simple ‘i’, ideally it shouldn’t allow creating the scope. But it is allowing to create the scope. So when we analyze the code we saw that in some places when validating the role "Internal".equalsIgnoreCase(userStore.getDomainName()). This becomes an issue when getting the access token from the store and when invoking the API.

**Steps to Reproduce:** Create a scope in the publisher. When giving the role name give the role name as internal/subscriber instead of Internal/subscriber ('i' as simple). Then you will be allowed to create the scope. Actually it has to show the error message.

**Affected version:**  2.6.0

**Comment by HiranyaKavishani** [comment]
This is expected behavior, we have to fix this logic in API invocation flow to avoid the request failure for internal user store.

https://github.com/wso2/product-apim/issues/6962
