### ISSUE TITLE
API Manager 3.0.0 - Error occurred when trying to import API definition for already created REST APIs.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#6827]
**Steps to reproduce:**

1. Create an API with the option "I Have an Existing REST API".
2. Choose the OpenAPI file option and upload the swagger definition.
3. Give the necessary information and create the API.
4. Then go to the API definition and click on "Import Definition"
5. Upload the same swagger definition which is used to create this API.
6. Observed below error.
<img width="1150" alt="Screen Shot 2019-11-14 at 5 18 24 PM" src="https://user-images.githubusercontent.com/28176167/68854794-d39f8f80-0702-11ea-9e41-6aa32df915a0.png">

**Comment by tmkasun** [comment]
I tried to reproduce this issue but couldn't reproduce with example in [here](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0)

Can you please provide the OpenAPI definition that you have used when this issue occurred.
And also please provide the browser console logs as well
