### ISSUE TITLE
Issue with importing APIs using CLI tool when the Secure Endpoint is enabled

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#6829]
**Description**
With the current implementation, the endpoint password is removed from the import and export web application. This needs to be fixed by setting endpointSecured false or set a dummy password and ask users to configure it via the available options. 

**Affected product version**
wso2am-2.6.0

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8123
