### ISSUE TITLE
Avoid Endpoint Suspended in Dynamic Endpoint Scneario

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#6839]
**labels**
3.1.0
improvement

**Description**

There is no any OOTB method to configure the endpoint timeout values for a dynamic endpoint (specially to avoid the dynamic endpoint suspensions) from the publisher portal. 
Since this is a valid requirement can we add this feature (under "Advanced Endpoint Configuration" in [1] ) as an improvement?

1. https://docs.wso2.com/display/AM260/Working+with+Endpoints

**Comment by dushaniw** [comment]
This is supported from REST API level already if we provide the endpoint_config properly as follows. 

```
{\"endpoint_type\":\"default\",
\"sandbox_endpoints\":
	{\"url\":\"default\"},
\"failOver\":\"False\",
\"production_endpoints\":
	{\"url\":\"default\",
	\"config\":{
		\"actionDuration\":\"300\",
		\"actionSelect\":\"fault\",
		\"factor\":\"1\",
		\"retryDelay\":\"10\",
		\"retryErroCode\":[\"101001\",\"101500\",\"101000\"],
		\"retryTimeOut\":\"3\",
		\"suspendDuration\":\"100\",
		\"suspendErrorCode\":[\"101001\",\"101000\"],
		\"suspendMaxDuration\":\"10\"
		}
	}	
}

```
We only need to add UI capability.
