### ISSUE TITLE
Font issue: APIs title

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#6842]
![image](https://user-images.githubusercontent.com/20179540/69041837-34d2a600-0a16-11ea-9770-033fd2eab628.png)

**Comment by tmkasun** [comment]
This is already fixed in the latest APIM 3.1.0-m1 hence closing the issue.

![image](https://user-images.githubusercontent.com/3313885/69061809-ea661f00-0a3f-11ea-8515-abbc14dab8b6.png)
