### ISSUE TITLE
[Doc]Improve the geolocation documentation.

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-apim#6843]
In geolocation documentation [1] an example is given only for the MySQL. It is better to add examples for the other databases like MsSQL, Oracle, IBM DB2, PostgreSQL as well.

[1] https://docs.wso2.com/display/AM220/Configuring+Geolocation+Based+Statistics

**Comment by tharindu1st** [comment]
invalid due to analytics revamp in latest release.
