### ISSUE TITLE
WSO2 Api Manager 3.0  Data Mapper does not work

### ISSUE THREAD

**Issue by ssshaik** [wso2/product-apim#6847]
I have installed wso2 Api Manager 3.0 on my windows by downloading the binaries.

I wonder if the datamapper does work in the v3.0 of the Api Manager.

it does not work in my case.

I am using OOTB sequences,  but unfortunately unable to actually save it: 

The logs are saying that the XML sequence are not found for the datamapper, regarding the apache-synapse configuration.

Steps to reproduce the issue:

1.)Downlaod AM3.0 Binaries and install in windows machine
2.)Open publisher and create a dummy api and in request mediator select the json_to_xml or any ootb sequences. and click on save button.

SAME FLOW WORK PERFECTLY FINE IN 2.6

Please find the errror log file attached.

[erroe.txt](https://github.com/wso2/product-apim/files/3858850/erroe.txt)

**Comment by ssshaik** [comment]
Hi guys,

Is it a bug (or) am I doing something wrong ??

**Comment by dushaniw** [comment]
Yes, it seems to be a bug. It would be the same issue, https://github.com/wso2/product-apim/issues/6754. 
This is fixed in latest master branch with https://github.com/wso2/carbon-apimgt/pull/7835

**Comment by ssshaik** [comment]
@dushaniw Thanks for the response.

Can you please guide me on how to get the latest binaries of this fix.?

**Comment by dushaniw** [comment]
Hi @ssshaik 

Sorry for the late reply. Yes this will be fixed in 3.1.0 :)
