### ISSUE TITLE
A null pointer is thrown when subscribing APIs

### ISSUE THREAD

**Issue by imesh94** [wso2/product-apim#6850]
Steps to reproduce:
    1) Send a DCR request
    3) Delete the application.
    4) Send a new DCR request

When subscribing to an API, an exception is thrown because the application mapping to the given applicationId retruns null. However, the deleted application can still be retrieved from the dbConnection. This appears to be a issue due to db connections not properly closing.

**Comment by Krishanx92** [comment]
@imesh94 Can you please give more information about this? Which app are you going to delete? is it sp app?

**Comment by imesh94** [comment]
@Krishanx92 the API Store application. It can be reproduced from the API store UI. 
1.Create an application, generate keys and subscribe APIs
2.Delete the application from the store.
3.Repeat step 1.

**Comment by isharac** [comment]
The issue is not reproduced in 2.6.0 wum pack.
