### ISSUE TITLE
API thumbnail background improvement

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#6858]
API Image backgrounds look horrible, either we should give transparent background or white backgrounds

Issues raised by Usability Testing candidates

**Comment by chanaka3d** [comment]
We need to revert this change since it is not visually appealing to have a white background randomly coming from a list of all colored api thumbs.

The same can be achieved by having only the following config in the defaultTheme.js

```
 thumbnail: {
                backgrounds: [ // These backgrounds are use to generate the thumbnails.
                    { prime: 0xffffffff, sub: 0xffffffff },
                ],
....
}
```
