### ISSUE TITLE
Errors while adding documents [Intermittent]

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#6872]
- Error message is popped up when uploading file while adding a document. But once viewing the document list the document is available in the list.

**This issue is intermittent.**

<img width="1244" alt="Screen Shot 2019-11-20 at 10 40 37 AM" src="https://user-images.githubusercontent.com/19324135/69210951-75e7c900-0b82-11ea-9f59-fdbd58a33418.png">

- The following errors are displayed in the console.
<img width="1679" alt="Screen Shot 2019-11-20 at 10 40 45 AM" src="https://user-images.githubusercontent.com/19324135/69210954-7e400400-0b82-11ea-9d98-5f74bfb0e18e.png">

**Comment by prasa7** [comment]
Can not reproducible
