### ISSUE TITLE
Release 3.1.0 Plan

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/product-apim#6875]
Hello everybody,
I would like to know when the completion of release 3.1.0 is planned.
thank you in advance
best regards

**Comment by tmkasun** [comment]
Hi @AndreasRusjaev ,

You can find the planed milestone, Alpha, Beta and Release candidate releases in [here](https://github.com/wso2/product-apim/milestones)

**Comment by AndreasRusjaev** [comment]
Thanks
