### ISSUE TITLE
API Manager try it UI shows http url with https port.

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#6878]
When you create API with both http and https transports enabled users can use tryout UI to invoke API with both http and https. URL is selectable on the top of API store page. But when you select http url its appear with 8243 port. And invocation get failed.

If someone need to use API developer portal over http then they can switch to http URL. And in that case users should be able to invoke http url as it do not cause mixed content issues which we get when trying to access 2 transports from same page. 

If we do not allow http access for developer portal then we need to mention that and disable same in tryit too.

**Comment by dushaniw** [comment]
Same issue https://github.com/wso2/product-apim/issues/6811

**Comment by dushaniw** [comment]
Reopening as this is only fixed for openapi3.

**Comment by isharac** [comment]
We have fixed this for OpenAPI 3.0 from APIM 3.1.0 onwards and APIM 3.0.0 wum
It cannot be fixed for swagger 2.0 due to swagger 2.0 does not support multiple hosts.
