### ISSUE TITLE
Test fauilre APIScopeTestCase

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#6885]
Following test fail APIScopeTestCase.testSetScopeToResourceTestCase

java.lang.AssertionError: Admin user cannot access the GET Method expected:<200> but was:<201> at org.wso2.am.integration.tests.other.APIScopeTestCase.testSetScopeToResourceTestCase(APIScopeTestCase.java:193)

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/product-apim/pull/6898
