### ISSUE TITLE
SDK support is limited compared to APIM 2.6.0

### ISSUE THREAD

**Issue by manjulaRathnayaka** [wso2/product-apim#6894]
APIM 3.0.0
![image](https://user-images.githubusercontent.com/3263607/69319141-a011b780-0c64-11ea-9f63-f57b82b4ba91.png)

APIM 2.6.0
![image](https://user-images.githubusercontent.com/3263607/69319210-c5062a80-0c64-11ea-9f59-9cace4540b1b.png)

**Comment by chanaka3d** [comment]
By default, 2.x products have only four languages enabled. We can enable additional lanuages by changing configuration. The behavior is same with the 3.0.
