### ISSUE TITLE
Custom theme: social features can not be disabled completely

### ISSUE THREAD

**Issue by manjulaRathnayaka** [wso2/product-apim#6895]
It would be good if the user can disable all social features in dev portal.
Theme changes: 
 "social": {
          "showRating": false
        },

But,
![image](https://user-images.githubusercontent.com/3263607/69319968-43170100-0c66-11ea-94b7-377a07748625.png)

**Comment by manjulaRathnayaka** [comment]
And it would be good to remove comments section as well.

![image](https://user-images.githubusercontent.com/3263607/69320332-013a8a80-0c67-11ea-9c04-e22cdea3de3b.png)

**Comment by chanaka3d** [comment]
Fix with the reference PR.

The comment section can be disabled by setting apiDetailPages.showComments value.
