### ISSUE TITLE
[Publisher] Improvement to endpoints listing in Runtime Configurations

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6906]
When a prototype API is created with prototype endpoint, endpoints are listed as follows in **Runtime Configurations** page:

![image](https://user-images.githubusercontent.com/19728269/69399955-0efb1900-0d16-11ea-84b3-ea45e8135d22.png)

For migrated APIs, both production and sandbox endpoints are marked with the given prototype endpoint:

![image](https://user-images.githubusercontent.com/19728269/69399983-3c47c700-0d16-11ea-917d-03f47af399fa.png)

Behavior should be consistent for all APIs, and can we change the section as prototype endpoints for APIs in Prototype state.

**Comment by dushaniw** [comment]
The existing behavior of showing the prototype endpoint as production and sandbox is wrong. Hence we need to improve the Overview and RunTime config UIs to remove prod and sandbox endpoints if API is prototype.
