### ISSUE TITLE
Wrong message when saving a file type document, without the file

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#6910]
![image](https://user-images.githubusercontent.com/20179540/69409247-8d63b500-0d2e-11ea-834b-fba826aaa376.png)

**Comment by erangatl** [comment]
@tmkasun Shall we disable the add button if the file is not attached?

**Comment by kavishkafernando** [comment]
> @tmkasun Shall we disable the add button if the file is not attached?

@erangatl the user can go to the Edit option in the listing and then add the file. So imo I don't think that we should make it mandatory to add a file when adding a document.

**Comment by tmkasun** [comment]
IMO what is wrong here is the message content, We could simply remove the inner description and just say 

```
Document created successfully!
```

@chanaka3d  , @erangatl  WDYT ?
