### ISSUE TITLE
[Devportal] The subscription count is not shown in the API Credentials tile

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#6926]
In the Overview section of an API in Dev Portal, the subscription count is not shown.

![image](https://user-images.githubusercontent.com/8557410/69491631-b0709f00-0ebd-11ea-8542-3b5cbcb3c94c.png)

**Comment by Sarangan0219** [comment]
The above issue  is not present in the latest APIM release. The subscription count is being shown. Hence this can be closed.

![imageedit_2_4399747628](https://user-images.githubusercontent.com/60866295/74334654-57c7e880-4dc0-11ea-946e-4b6ad22fb9cc.jpg)

**Comment by tharikaGitHub** [comment]
Closing as per the above comment.

**Comment by tharikaGitHub** [comment]
In the latest build of APIM we have changed the API Credentials tile to Subscriptions as follows.

![image](https://user-images.githubusercontent.com/8557410/74405309-cd7c9480-4e52-11ea-85c6-63a8f458d2ce.png)

We do not show the number of subscriptions here. @dushansilva do we need to show this number in this tile now?

**Comment by menakaj** [comment]
@tharikaGitHub In Subscription section, I think we need to show the existing subscription count.

**Comment by chanaka3d** [comment]
Fixed with the above PR
