### ISSUE TITLE
[Devportal] Application name not shown in Application Overview Page

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#6927]
The application name is not shown in the Info Bar of the overview page of an Application. This makes it difficult to know which Application is being viewed when moving across other sections of the same page.

![image](https://user-images.githubusercontent.com/8557410/69491703-a3a07b00-0ebe-11ea-8f26-369ec79549d4.png)

**Comment by kavishkafernando** [comment]
Application name can be seen in latest pack.

<img width="708" alt="Screen Shot 2019-11-26 at 4 41 33 PM" src="https://user-images.githubusercontent.com/19324135/69624991-b1dfca00-106b-11ea-8bf9-35532e2be668.png">
