### ISSUE TITLE
[UI] Scopes per resources are not shown in UI for migrated APIs

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6932]
When migrating an API which has scopes from 2.6.0, scopes per resources are not shown in UI in Resources tab.
Scopes are listed in the drop-down but not selected (Operation scope field is empty). 
![image](https://user-images.githubusercontent.com/19728269/69514307-da36ce00-0f70-11ea-8102-5ea621c5db63.png)
In devportal, scope binding is working as expected.

**Comment by npamudika** [comment]
For the migrated APIs, in the **Scopes** tab, the scope is there in the 3.0 Publisher UI. But, the scopes are not added in the resource level.
