### ISSUE TITLE
Cannot see the APIs in Publisher when login as a tenant user for the first time

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#6939]
Cannot see the migrated APIs in the Publisher in the first login as a tenant user and it gives the following error in the logs.

```
[2019-11-25 16:36:28,484] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

In the Developer Portal, it is able to see the APIs without an issue.

After restarting the server, the APIs are visible in the tenant mode.

Note: Not specific to any DB type. Reproduced in MySQL and PostgreSQL.

**Comment by vithu30** [comment]
Same behavior observed in devportal as well. If you logged into the Dev portal as tenant admin for the first time (in migrated environment), it is able to see the APIs and when trying to view applications, getting logged out and tenant listing page is shown. Same error is logged:
```
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

**Comment by npamudika** [comment]
Same behaviour can be observed in MSSQL too.

**Comment by npamudika** [comment]
Same error is there in DB2.

**Comment by tharindu1st** [comment]
Couldn't reproduce in latest apim 4.0.0
