### ISSUE TITLE
Enable Event Statistics API Manager 3.0.0 Carbon

### ISSUE THREAD

**Issue by igkononov** [wso2/product-apim#6941]
Hi,

In API Manager 3.0.0 in Carbon https://localhost:9443/carbon there is possibility to choose Event Metrics. However, this metrics must be enabled:
<img width="1440" alt="Screen Shot 2019-11-25 at 2 58 39 PM" src="https://user-images.githubusercontent.com/56588985/69542446-247d7680-0f94-11ea-98e0-c9dded0b88ba.png">
However, as I understand in true way, for configuring such cases developer should use deployment.toml file. It looks strangely, that I see message with link to carbon.xml file.

Is it a bug?
One more question - how to enable Event Statistics in deployment.toml file?

Thanks for your answer in advance.

**Comment by igkononov** [comment]
Is it possible to get answer on this question?

**Comment by fazlan-nazeem** [comment]
Hello @igkononov 

Yes. Currently, the APIM deployment.toml file doesn't have a config to modify this configuration. Temporarily, you should be able to modify this config in the carbon.xml.j2 file which could be found in the following location.

repository/resources/conf/templates/repository/conf/carbon.xml.j2

We will track this and evaluate the necessity of this config and try to fix in upcoming release.

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7228

**Comment by tharindu1st** [comment]
Hi @igkononov ,
We are no longer support in house monitoring since this can be done from outside analysis tools.
