### ISSUE TITLE
Update mediation policy using inline content is not implemented

### ISSUE THREAD

**Issue by Meruja** [wso2/product-apim#6949]
Need to implement this. Adding mediation policy using inline is implemented and hence we need to support 'PUT' as well.

**Comment by dushaniw** [comment]
We will not add this functionality for the upcoming 3.1.0 release. Will consider in future 3.x releases.

**Comment by Krishanx92** [comment]
Mediation policy is now change to operation policy view and please check if this align with it and re-open if needed.
