### ISSUE TITLE
Failover or Load Balanced Endpoints cannot be listed after adding

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#6953]
In Publisher, after adding Failover or Load Balanced Endpoints from the UI, the added endpoints are not shown.

![failover](https://user-images.githubusercontent.com/8557410/69610255-6c160800-1051-11ea-9b15-8a76340f662e.png)

**Comment by kavishkafernando** [comment]
Seems like this is working fine in latest pack

<img width="1388" alt="Screen Shot 2019-11-26 at 3 26 39 PM" src="https://user-images.githubusercontent.com/19324135/69619174-2e20e000-1061-11ea-931e-fa435915271c.png">
