### ISSUE TITLE
Cannot Invoke API from Devportal Test console In MS Edge

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#6954]
Cannot invoke an api from devportal test console using MS Edge
Using Edge 18
Windows 10
<img width="1421" alt="Screen Shot 2019-11-26 at 2 26 21 PM" src="https://user-images.githubusercontent.com/18071381/69614229-c9fa1e00-1058-11ea-9c08-d96b3d9ffce3.png">

**Comment by chanaka3d** [comment]
Same issue can be observed from the Firefox as well.

**Comment by chanaka3d** [comment]
Working carbon-apimgt 6.8.42-SNAPSHOT against Microsoft Edge 85.0.564.68.
