### ISSUE TITLE
toml configuration issue for database type

### ISSUE THREAD

**Issue by Khelnor** [wso2/product-apim#6956]
When using the publisher profile TOML file, I change the database.shared_db and database.apim_db type to oracle and only the sharedDB datasource is changed correctly in the master-datasources.xml file. The APIMDB datasource is partially reconfigured: with correct username/password and pool options but it remains stick to h2 database type and h2 JDBC driver . If I use the type = mysql it works, it seems oracle type is not managed in case of database.apim_db.

**Comment by dushaniw** [comment]
@Khelnor this is a known issue in 3.0.0. The same issue is reported in https://github.com/wso2/product-apim/issues/6796, which is already fixed with https://github.com/wso2/product-apim/pull/6832 for next 3.1.0 release.

**Comment by dushaniw** [comment]
In 3.0, you can make it work by using the following config in deployment.toml,

```
[database.apim_db]
type = "mssql"
driver = "oracle.jdbc.OracleDriver"
url = "jdbc:oracle:thin:@SERVER_NAME:PORT/SID"
validationQuery="SELECT 1 FROM DUAL"
username = "root"
password = "pass"  

```

**Comment by dushaniw** [comment]
Closing the issue as we have fixed in the latest version and answered a possible solution. Please reopen if you need further assistance.
