### ISSUE TITLE
UI issue in the Bot Detection dashboard in admin portal

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#6957]
When analytics is disabled, clicking on **Bot Detection** is not rendering anything in drop down. It would be better if we show the options and have a not saying - `It requires analytics` or `Analytics is disabled`.
The same behavior we have in remaining place.

![image](https://user-images.githubusercontent.com/19728269/69619986-96bc8c80-1062-11ea-915d-6952b28c115b.png)

**Comment by chanaka3d** [comment]
This issue is fixed with the 3.2 new admin portal.
