### ISSUE TITLE
Publisher API create forms UI issue in MS Edge

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#6959]
In Microsoft Edge all api create form's background paper is not rendered

How it should be
<img width="1096" alt="Screen Shot 2019-11-26 at 4 53 08 PM" src="https://user-images.githubusercontent.com/18071381/69625775-50b8f600-106d-11ea-9ded-0a231c90214e.png">

How it is
<img width="1554" alt="Screen Shot 2019-11-26 at 4 41 50 PM" src="https://user-images.githubusercontent.com/18071381/69625791-57476d80-106d-11ea-95de-4404dd112246.png">

**This issue is seen in** 
Create an API
Create an API using an OpenAPI definition.
Expose a SOAP Service as a REST API
Expose a SOAP Service as a REST API
Create an API using a GraphQL SDL definition
Create a WebSocket API

Tested in 
edge 18
Windows 10

**Comment by chanaka3d** [comment]
Working carbon-apimgt 6.8.42-SNAPSHOT against Microsoft Edge 85.0.564.68.
