### ISSUE TITLE
AsyncAPI support in WSO2 APIM

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-apim#6972]
What're our plans on supporting AsyncAPI https://www.asyncapi.com/

**Comment by nirmal070125** [comment]
SF ID: 0012S000026NCLW

**Comment by nuwanbando** [comment]
whats the update on this ? @kavishkafernando I don't think this is a Type/Question. This has to be a feature request. can you please revisit.

**Comment by Krishanx92** [comment]
This is now supported with latest APIM: https://apim.docs.wso2.com/en/latest/design/create-api/create-streaming-api/create-a-streaming-api-from-an-asyncapi-definition/
