### ISSUE TITLE
Namespace modifications occur in the payload of Rest API with SOAP WSDL Endpoint implementation

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-apim#6973]
In the Rest APIs with soap WSDL endpints[1] implementation, the SOAP payload generated by our API manager is undergoing certain modifications.

It picks the namespace and is adding the XML namespace prefix "xmlns:web" for SOAP envelope. Whatever the namespace is being removed and is adding the default namespace "web". And  the namespace is being added to all the XML elements of the soap payload.

Example:
When the payload is not having any namespace, at that time too a namespace "web" is getting added.

The backend expects: (Soap UI payload)

**_<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <SWIFTVerifyOrderNOVA>
         <Event_Name>SWIFTVerifyOrderNOVA</Event_Name>
         <Message_Id>OK</Message_Id>
         <NOVA_Order_Id>1-554433</NOVA_Order_Id>
      </SWIFTVerifyOrderNOVA>
   </soapenv:Body>
</soapenv:Envelope>_**

How API manager sends:

**<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.tm.com.my/hsbb/eai/SWIFTVerifyOrderNOVA/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:SWIFTVerifyOrderNOVA>
         <web:Message_Id>Test</web:Message_Id>
         <web:Event_Name>SWIFTVerifyOrderNOVA</web:Event_Name>
         <web:NOVA_Order_Id>1-111111</web:NOVA_Order_Id>
      </web:SWIFTVerifyOrderNOVA>
   </soapenv:Body>
</soapenv:Envelope>**

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130
