### ISSUE TITLE
Start publisher instance with offset: How to set the callback url ?

### ISSUE THREAD

**Issue by Khelnor** [wso2/product-apim#6976]
With wso2 apim 3.0.0, I start a publisher instance with the correct profile option. I have set an offset parameter in the deploiment.toml file but when I try to login to the UI, I have an Invalid Callback url error in the Oauth2 workflow. Is there any configuration file that needs to be updated manually to have the publisher functional with offset ?

**Comment by tmkasun** [comment]
Hi @Khelnor 

I have answered a similar question [here](https://github.com/wso2/product-apim/issues/6802#issuecomment-552861233)

**Comment by Khelnor** [comment]
Thanks. It works by using the carbon UI of keymanager and setting manually the callback url in the provider.
