### ISSUE TITLE
Admin credentials not used in TOML

### ISSUE THREAD

**Issue by Khelnor** [wso2/product-apim#6977]
When I set an admin account in the deployment.toml, it seems that the password is not used at startup. I always need to log with admin/admin.

**Comment by kavishkafernando** [comment]
Hi @Khelnor ,

Please confirm whether you changed the following property in the deployment.toml file,
**[super_admin]
username = "admin123"
password = "admin123"
create_admin_account = true**

Did you change the password before the initial server startup?

**Comment by Khelnor** [comment]
No, I think that I first boot with the default admin and change the TOML after.
By using the carbon ui to change the admin password, it works on all WSO2 apim instances.
