### ISSUE TITLE
Login with old password makes a series of introspect calls

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#6990]
**Steps to reproduce:**
- Start the APIM server
- Loging to publisher with admin credentials.
- Stop the server
- Change the super admin password in the deployment.toml and restart the server
- Login to Publisher with old username and password

This results in a loop of introspect calls.
<img width="1651" alt="Screen Shot 2019-11-27 at 5 43 54 PM" src="https://user-images.githubusercontent.com/19324135/69777007-71e02a80-11c4-11ea-9965-c25fce69f775.png">

**Comment by CrowleyRajapakse** [comment]
The above doesn't seems to be available in the latest APIM master and issue can be closed.

> When changing the super user password, user need to change the password not only in the deployment.toml but also by login in to the Management Console(carbon). Then user won't be able to login to the portals by using old password.
