### ISSUE TITLE
Graph QL content validation failed

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-apim#6992]
When I'm creating a GraphQL API using GraphQL schema, it gives me an error saying "GraphQL content validation failed". But when I edit my schema and remove comments in that file, and retry, that error does not appear. 
But adding a comment should not affect the schema validation as per my understanding. 

<img width="1680" alt="Screen Shot 2019-11-28 at 11 49 10 AM" src="https://user-images.githubusercontent.com/10182430/69781929-a1e3f980-11d5-11ea-95fd-255f3c41eb09.png">

**Comment by krishnilak** [comment]
Following is the content of my schema.graphql file

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | OBJECT | INTERFACE
enum CacheControlScope {
  PUBLIC
  PRIVATE
}

type Continent {
  code: String
  name: String
  countries: [Country]
}

type Country {
  code: String
  name: String
  native: String
  phone: String
  continent: Continent
  currency: String
  languages: [Language]
  emoji: String
  emojiU: String
}

type Language {
  code: String
  name: String
  native: String
  rtl: Int
}

type Query {
  continents: [Continent]
  continent(code: String): Continent
  countries: [Country]
  country(code: String): Country
  languages: [Language]
  language(code: String): Language
}

# The `Upload` scalar type
 represents a file upload.
scalar Upload**

**Comment by HiranyaKavishani** [comment]
Close the issue as per the information take from https://github.com/graphql-java/graphql-java/issues/1705
