### ISSUE TITLE
intermittent message drop in the GW

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-apim#7001]
Incoming request messages are dropped intermittently while the GW received the request just before an idle TCP connection (between GW and backend) is about to be closed (socket timeout is 60s).

We need to add maximum-connection-lifespan and connection-idle-timeout parameters to passthru-http.properties. Here if a connection is persisted in the connection pool for a time more than the maximum-connection-lifespan or if a connection is idle for a time more than connection-idle-timeout then the connection is removed from the connection pool with the PR in [1]. But the relevant properties are not applicable.

**Comment by dushaniw** [comment]
Closed with https://github.com/wso2/wso2-synapse/pull/1472
