### ISSUE TITLE
[Publisher] registry resource is added as the mediation sequence file name 

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#7003]
In previous versions of API Manager we use sequence name in the mediation sequence file to derive the registry path.
In APIM 3.0.0 file name itself is used instead.
This was done to avoid unnecessary processing of the xml file.
However, with a recent fix(wso2/product-apim/#6565) we are already processing the xml file at this point.
Therefore we can obtain the sequence name.

To maintain the backward compatibility we need to add the sequence name instead of the file name in the resource path in add mediation policy request.

POST /apis/{apiId}/mediation-policies

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8151
