### ISSUE TITLE
BeanCreationException when starting the traffic manager

### ISSUE THREAD

**Issue by mrderban** [wso2/product-apim#7005]
Hi guys, I've got the following error when starting the traffic manager, could you point me in the right direction to solve the issue, what could be the cause of this ?? (wso2 apim v 2.2.0)

ERROR org.springframework.web.context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘services’ : Cannot create inner bean ‘org.wso2.carbon.consent.mgt.endpoint.ConsentsApi#303a4bfd’ of type [org.wso2.carbon.consent.mgt.endpoint.ConsentsApi] while setting bean property ‘serviceBeans’ whith key [0] ; nested exception is org.springframework.beans.factory.Beancreationexceton : Error creating bean with name ‘org.wso2.carbon.consent.mgt.endpoint.ConsentsApi#303a4bfd’ defined in ServletContext resource [/WEB-INF/beans.xml] :Instantion of bean failed ; nested exception is org.springframework.BeansInstantionException :Failed to instantiate [org.wso2.carbon.consent.mgt.endpoint.ConsentsApi] : Constructor threw exception ; nested exception is java.lang.NoClassDefFoundError : org/wso2/carbon/consent/mgt/core/exception/ConsentManagementClientException

**Comment by dushaniw** [comment]
Hi @mrderban 

Do you have the webapp `api#identity#consent-mgt#v1.0.war` in <TrafficManager>/repository/deployment/server/webapps directory?

**Comment by mrderban** [comment]
Hi @dushaniw ! Yes absolutely, i do have the api#identity#consent-mgt#v1.0.war in the webapps directory, i still get the same error when executing the following command: 
sh $APIM_HOME/trafficmanager/bin/wso2server.sh -Dprofile=traffic-manager start

**Comment by dushaniw** [comment]
@mrderban we do not need that particular jar for traffic-manager profile. You can remove that. We do not need any of the default webapps for the trafficmanager.

Step3 in https://docs.wso2.com/display/AM220/Product+Profiles#TM consists of the web apps we need for each profile.

**Comment by mrderban** [comment]
Well we actually do need this war to activate the autoenrollment functionnality (autoenroll button),
the doc is actually wrong on this particular topic.

**Comment by dushaniw** [comment]
Sorry, I couldn't get you properly. what is the exact purpose of this functionality which you are using specifically on the traffic manager?

**Comment by mrderban** [comment]
This specific war file (**api#identity#consent-mgt#v1.0.war**) has to be deployed on each component (tfm, store etc..) in order for the auto enroll button to be working in the store.

**Comment by tharindu1st** [comment]
This is fixed in latest release.
