### ISSUE TITLE
[Developer Portal] - API Console / Tryout with APIKey

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7006]
- API Manager version 3.0.0
- Developer Portal
- Tryout (Swagger based console)
- Trying out the **API Key** based authorization approach
- Authorize » Available Authorizations » api_key (APIKey)
- Paste the generated APIKey and try the APIs

**_Issue:_**
- The header created for the APIKey is `api_key`
- WSO2 API Manager expects the header as `apikey` ( without the _ )
- Check the generated curl command below.
```
curl -X GET "https://localhost:8243/v2/1.0.3/pet/4" -H  "api_key: eyJ4***-w==" -H  "Authorization: Bearer d912f***1e4b" -H  "accept: application/json" 
```
**_Suggestion:_**
Either to use `api_key` as the header in API-M or to modify the API Console to generate header as `apikey`.

**Comment by dushansilva** [comment]
Duplicate https://github.com/wso2/product-apim/issues/6742
