### ISSUE TITLE
[Store Visibility] Store visibility issue in API Documents

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#7007]
Steps to reproduce:

1. Create and publish an API with a document.
2. Set developer portal visibility to a role.
3. Go to developer portal and login using a user with a different role.
4. Do a content search which matches both the API and the document.
5. API will not be visible (expected) but the document will be visible. (not expected)

**Comment by tharikaGitHub** [comment]
This issue is not reproducible in the latest API Manager pack. Hence closing the issue.
