### ISSUE TITLE
When navigating from another tab to Subscription tab loading text appears

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7018]
**Network:** Fast 3G
**CPU:** 4x slowdown

When navigating from another tab to Subscriptions tab loading text appears before the UI elements are loaded.

<img width="1680" alt="Screen Shot 2019-11-29 at 11 58 14 AM" src="https://user-images.githubusercontent.com/19324135/69848506-47fc3600-12a0-11ea-809f-d98e29fb4cc3.png">

**Comment by chanaka3d** [comment]
Fixed from above PR.
