### ISSUE TITLE
Comments shows no comments for brief moment when navigating from another tab

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7020]
**Network:** Fast 3G
**CPU:** 4x slowdown

Comments tab shows no comments for brief moment even when comments exist when navigating from another tab

<img width="1657" alt="Screen Shot 2019-11-29 at 12 32 29 PM" src="https://user-images.githubusercontent.com/19324135/69850159-a6c3ae80-12a4-11ea-8c19-09044554346e.png">

**Comment by chanaka3d** [comment]
Fix with above PR.
