### ISSUE TITLE
Edit application details loads after awhile

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7026]
**Network:** Fast 3G
**CPU:** 4x slowdown

- After clicking on edit application from the application list
- It first loads the create application UI and shows an empty form for a few seconds. (A user can type within these few seconds)
<img width="1676" alt="Screen Shot 2019-11-29 at 2 52 36 PM" src="https://user-images.githubusercontent.com/19324135/69858735-a03f3200-12b8-11ea-9412-8bd2d2535042.png">

- After a few seconds the application details are loaded.
<img width="1667" alt="Screen Shot 2019-11-29 at 2 52 43 PM" src="https://user-images.githubusercontent.com/19324135/69858776-ba791000-12b8-11ea-977c-b574f7035213.png">

**Comment by chanaka3d** [comment]
Fixed by providing a loading animation while doing the API call to get the application information.
