### ISSUE TITLE
OAuth tab contents takes more time to load

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7031]
**Network:** Fast 3G
**CPU:** 4x slowdown

1. In the application page, when switching between Oauth and API Key tabs in boeth Production and Sanbox keys UI, Oauth tab takes quite some time to load.

<img width="1661" alt="Screen Shot 2019-11-29 at 3 38 06 PM" src="https://user-images.githubusercontent.com/19324135/69861533-915b7e00-12be-11ea-93df-49fcd298f81b.png">

2. Generate Keys button loads after awhile.

<img width="1658" alt="Screen Shot 2019-11-29 at 3 45 24 PM" src="https://user-images.githubusercontent.com/19324135/69861943-6de50300-12bf-11ea-9a56-155774768c77.png">

**Comment by prasa7** [comment]
This UI is outdated as of 3.2.0
