### ISSUE TITLE
Applications are not sorted when arrow is clicked

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7034]
Nothing happens when the following arrow is clicked.

<img width="1334" alt="Screen Shot 2019-11-29 at 3 52 05 PM" src="https://user-images.githubusercontent.com/19324135/69862438-67a35680-12c0-11ea-986b-9d48d94a4301.png">

**Comment by Meruja** [comment]
In H2 database, DISTINCT does not properly work with ORDER BY.
Applications are sorted when the arrow is clicked when we use MySQL database.
<img width="1590" alt="asc" src="https://user-images.githubusercontent.com/28688743/70117735-28904f00-168c-11ea-8bbe-0ca8258be227.png">
<img width="1508" alt="desc" src="https://user-images.githubusercontent.com/28688743/70117744-2ded9980-168c-11ea-9ee3-ad60a4230e08.png">

**Comment by Meruja** [comment]
Fixed with wso2/carbon-apimgt/pull/8005
