### ISSUE TITLE
Have a different color scheme to differentiate API Developer Portal from Publisher

### ISSUE THREAD

**Issue by mifanc** [wso2/product-apim#7056]
The APIM Developer Portal and Publisher are only distinguishable by its names in the default version. Its good to easily differentiate these based on colour.

**Comment by tmkasun** [comment]
WIth basic level customization, Users could easily change the appearance (color scheme, positioning etc) of both Publisher and Developer portal, So IMHO having a common color theme for default apps won't be a problem. 
In the 2.x product lines also, We had common color theme (wso2 theme) for all the apps in the product. 

@chanaka3d , @jeradrutnam  @erangatl , @bhathiya any comment on this?

**Comment by nuwanbando** [comment]
I think it's a perception question. During customer demos the store has to be clearly different from the publisher. the Look and feel can create that differentiation. One way I have seen is that the publisher is more boring looking, and in few shades of gray etc.

**Comment by mifanc** [comment]
Agreed. I think having a common color theme for both is not correct and gives the wrong perception. The Publisher (and admin portal) and Developer Portal are for totally different purposes and user groups so its good to clearly differentiate.

**Comment by chanaka3d** [comment]
Introduced a slightly different blue colors for the devportal with the above PR.
