### ISSUE TITLE
[Developer Portal] - Usability / API credentials options before login

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7058]
UI: Details view of the of an API

If a user clicks on an API to view its details, the user can also see the information that is relevant to API credentials.  At this stage, the potential user may not have an idea about the subscription mechanism and it is not necessary to push that knowledge at this stage which would result in information overload. Also, it increases the number of clicks (back and forth travel) as the user might click on subscription to know what is meant by 'Application', 'Credentials', 'Subscription' etc and then learns to create an account and login in the next screen. 

<img width="707" alt="Screenshot 2019-12-02 at 13 23 31" src="https://user-images.githubusercontent.com/146158/69963774-d70b8700-1508-11ea-9b17-4c55a5485d03.png">

Therefore, it would be best to hide the "**API Credentials**" box/panel in the developer portal under the details view of an API by default and make it ONLY visible if the user is logged in. Instead of the API Credentials box/panel, it would be good to have with a box/panel with a message/button prompting to "**Sign-in**" to use/try the API.

**Comment by kavishkafernando** [comment]
Maybe in anonymous view we can hide the API credentials box. IMO I don't think we should display another sign-in button there because we have a sign-in button at the top.

@tmkasun @chanaka3d @erangatl WDYT?

**Comment by knightbeat** [comment]
Making the panel invisible or providing a sign-in button is a choice. But sometimes, it's good to have redundant UI elements to support the story/user-interaction-flow making it intuitive. In that way, the user doesn't even have to read another documentation page to realise that creating a user account and sign-in is necessary to try-out and subscribe to an API.

**Comment by chanaka3d** [comment]
Fixed with the new UI/UX changes done with the above PR.
