### ISSUE TITLE
[Developer Portal] - Usability / API credentials options after login

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7059]
UI: Details view of the of an API

<img width="704" alt="Screenshot 2019-12-02 at 13 41 18" src="https://user-images.githubusercontent.com/146158/69964058-7cbef600-1509-11ea-916e-36b868603599.png">

**Point 1**
Provided two options for the subscription can confuse the user.
1. KEY GENERATION WIZARD
2. SUBSCRIBE TO AN APPLICATION

**Point 2**
The terminology used to describe the second option is not accurate. In this case, it's not the Application that the user subscribes to but to an API using an Application. 
Based on these 2 reasons, it would be better to re-design these two buttons as,

Fieldset title: "**Subscribe with ...**"  
↳Button 1 title: "**A New Application**"
↳Button 2 title: "**An Existing Application**"

**Comment by chanaka3d** [comment]
Fixed with the changes done with above PR
