### ISSUE TITLE
[Developer Portal] - Usability / Hyperlinks are not intuitively recognisable 

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7061]
The Hyperlinks are styled without the usual text styling with Underline and the Blue colour.  They also do not have a hover effect to teach the users that these elements are Clickable.

eg. <span style="color:blue">**How To**</span> and <span style="color:blue">**3 Subscriptions »** </span>below
<img width="184" alt="Screenshot 2019-12-02 at 14 07 31" src="https://user-images.githubusercontent.com/146158/69966043-7a5e9b00-150d-11ea-9e54-ce43e3bc5be7.png">
<img width="125" alt="Screenshot 2019-12-02 at 14 07 38" src="https://user-images.githubusercontent.com/146158/69966054-7f234f00-150d-11ea-9fe6-c0eb9469e7c3.png">

**Comment by chanaka3d** [comment]
<img width="743" alt="Screen Shot 2019-12-13 at 4 48 50 PM" src="https://user-images.githubusercontent.com/3424539/70797104-cf31c980-1dc9-11ea-97e6-778c4b72f9e4.png">
