### ISSUE TITLE
Registering as tenant user not working as expected.

### ISSUE THREAD

**Issue by imchivaa** [wso2/product-apim#7065]
Environment: Windows 10 & Linux (Ubuntu 19.10)
APIM Version : 3.1.0-M2

Issue:
Unable to register an user as tenant. user navigated to a blank page with only the wso2 navigation bar visible upon clicking register now button. User navigated to `/accountrecoveryendpoint/processregistration.do` after clicking register now button.

Step to reproduce:
1. Create a new tenant (example.com) in Carbon
2. Navigate to devportal and select the newly created tenant
3. Provide username (customer@example.com)
4. Complete the basic sign up details. Use customer@example.com as the email
5. Seeing a blank page with only the navigation bar on top upon clicking on the Register now button.

Error Log:
[wso2-apim-3.1.0-m2-register-user-as-tenant-error_log_1.log](https://github.com/wso2/product-apim/files/3914205/wso2-apim-3.1.0-m2-register-user-as-tenant-error_log_1.log)
[wso2-apim-3.1.0-m2-register-user-as-tenant-error_log_2.log](https://github.com/wso2/product-apim/files/3914206/wso2-apim-3.1.0-m2-register-user-as-tenant-error_log_2.log)

Screenshot:
![image](https://user-images.githubusercontent.com/5532832/70014970-0aa4ea80-15b7-11ea-8058-2c67a7c680c4.png)

**Comment by tharikaGitHub** [comment]
Hi @imchivaa,
    
 For self registration to work for tenants, you need to follow the steps given in [this documentation](https://apim.docs.wso2.com/en/latest/Learn/ConsumeAPI/Customizations/CustomizingTheAPIStore/enabling-or-disabling-self-signup/). Although this is enabled for the super tenant by default without further configuration, you have to follow the steps given in the documentation to enable self registration for tenants.

**Comment by imchivaa** [comment]
Cool. Got it working following the documentation. Let me close the issue.
