### ISSUE TITLE
[Publisher] "View in Dev Portal" link in menu bar redirects to localhost

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#7067]
Though deployment.toml is configured correctly, "View in Dev Portal" link in menu bar redirects to localhost.

![Screenshot from 2019-12-03 10-24-06(1)](https://user-images.githubusercontent.com/36144069/70021998-a7b45300-15b8-11ea-9e65-1af2f4687492.jpg)

![Screenshot from 2019-12-03 10-24-11](https://user-images.githubusercontent.com/36144069/70022000-abe07080-15b8-11ea-8a58-3b0cb779c884.jpg)

**Comment by kavishkafernando** [comment]
Hi @binodmx 

have you set the devportal url in the deployment.toml file?

**[apim.devportal]
url = "https://localhost:${mgt.transport.https.port}/devportal"**

**Comment by binodmx** [comment]
I only changed **[server] hostname** earlier. After enabled **[apim.devportal]** and replaced localhost with hostname (**url = "https://hostname:${mgt.transport.https.port}/devportal"**), it worked properly. 

However, I was able to visit **devportal** directly using https://hostname:9443/devportal/ without enabling **[apim.devportal]**. In that case, I suppose **View in Dev Portal** should not redirect to localhost.

**Comment by kavishkafernando** [comment]
For redirection the Settings API reads the devportal url thats is why we have to change the devportal url as well.

**Comment by teodora-mitrovic** [comment]
Hey @kavishkafernando,

I have the same problem with redirection, and I have changed apim.devportal url to https://hostname:${mgt.transport.https.port}/devportal , but it still redirects to localhost.
Do you have any idea why?

Thanks!
