### ISSUE TITLE
Significant drop in TPS for GET

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-apim#7070]
I have performed some tests using [this](https://github.com/wso2/performance-common/tree/master/components/netty-http-echo-service) "netty-http-echo-service" and found out that the TPS APIM gives for GET is significantly less when compared to POST. 

**WSO2 Products**
    
    Product : wso2am-2.6.0+1574508899827
    DB : Default H2 DB

**Jmeter Configurations**

    Number of threads(users) : 5
    Ramp-up period(seconds) : 1
    Loop count : 15000000
    Same user on each iteration : true

**Hardware Overview:**

     Model Name: MacBook Pro
     Model Identifier: MacBookPro14,3
     Processor Name: Quad-Core Intel Core i7
     Processor Speed: 2.9 GHz
     Number of Processors: 1
     Total Number of Cores: 4
     L2 Cache (per Core): 256 KB
     L3 Cache: 8 MB
     Hyper-Threading Technology: Enabled
     Memory: 16 GB
     Boot ROM Version: 202.0.0.0.0
     SMC Version (system): 2.45f1
     Serial Number (system): C02W33WGHTD6
     Hardware UUID: DF75513B-E1C1-5771-B10E-71DB5B24C3DC

Please find the attached flamed graphs for each case. Note that the tests have been carried out for 5 mins for each case after enabling JFR.
[JFR_flamegraphs.zip](https://github.com/wso2/product-apim/files/3915875/JFR_flamegraphs.zip)

**Comment by chamilaadhi** [comment]
Please attach your wso2carbon.log file as well to check for errors for both GET and POST scenario
