### ISSUE TITLE
[Developer Portal] - Wrong HTTP Port on the API Console for GraphQL APIs

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-apim#7072]
<img width="403" alt="Screenshot 2019-12-03 at 14 14 00" src="https://user-images.githubusercontent.com/146158/70058696-4fd91480-15d7-11ea-93c4-b5711e2f3e79.png">

Both HTTP and HTTPS ports are 8243 instead of HTTP port being 8280 by default.

**Comment by dushaniw** [comment]
@knightbeat Thank you for reporting. This is a known issue. 
Refer https://github.com/wso2/product-apim/issues/6878.

We have fixed this for OpenAPI3 for next release 3.1.0. We will address this for Swagger2 as well.

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/product-apim/issues/6878
