### ISSUE TITLE
SOAP to REST conversion with complexType Lists getting converted to a string type in the swagger

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-apim#7076]
Hi, 

When we try to create REST API by referencing a WSDL file/URL some of the data types are not getting converted properly in the swagger definition. Due to this when we try to build the SDK created for this API there are errors with missing classes. 

**complexType** definition of **Lists** in the WSDL file with an **Array** are getting converted to a **string** type in the swagger, which should ideally be converted into an **object** type.
For example, 
```
<xs:complexType name="CustomSearchOrderByList">
  <xs:complexContent>
		<xs:restriction base="soapenc:Array">
			<xs:sequence>
				<xs:element name="OrderByStruct" type="tns:CustomSearchOrderByStruct" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="soapenc:arrayType"/>
		</xs:restriction>
	</xs:complexContent>
</xs:complexType>
```
**CustomSearchOrderByList** complex type is converted as the following in the swagger definition generated for the API.
```
CustomSearchOrderByList:
    type: string
    properties:
      OrderByStruct:
        type: array
        items:
          $ref: "#/definitions/CustomSearchOrderByStruct"
    xml:
      namespace: "http://www.w3.org/2001/XMLSchema"
      prefix: xs
```

Since the **type: string** there is no object getting created for this complex type and thus gives 
**"Class not found"** errors when building the SDK of the API.

**Comment by lkokila** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by rmsamitha** [comment]
Closing as SOAP to REST feature is to be deprecated from apim-4.1.0
