### ISSUE TITLE
SOAP to REST conversion some of the simpleType date objects mapped to a string type in the swagger definition

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-apim#7077]
Hi, 

When we try to create REST API by referencing a WSDL file/URL some of the data types are not getting converted properly in the swagger definition. Due to this when we try to build the SDK created for this API there are errors with missing classes.

Some of the **simpleType** objects are mapped to a string type in the swagger definition that omits the class creation for these data types. Due to that, there are some, class not found errors.

For example, if the WSDL contains a simpleType **ParameterName** like below
```
<xs:simpleType name="ParameterName">
	<xs:restriction base="xs:string">
		<xs:maxLength value="256"/>
	</xs:restriction>
</xs:simpleType>
```

**ParameterName** simpleType is converted as the following in the swagger definition generated for the API.
```
  ParameterName:
    type: string
    xml:
      namespace: "http://www.w3.org/2001/XMLSchema"
      prefix: xs
```
Since the **type: string** there is no object getting created for this simple type and thus gives
"Class not found" errors when building the SDK of the API.

**Comment by lkokila** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by rmsamitha** [comment]
Closing as SOAP to REST feature is to be deprecated from apim-4.1.0
