### ISSUE TITLE
[Devportal] Improvement to comments UI

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#7084]
If we put a very long comment we have to scroll the UI to the end to see the comment and the comment cart also is extended as an empty white space. 
<img width="1651" alt="Screen Shot 2019-12-04 at 6 03 27 PM" src="https://user-images.githubusercontent.com/18071381/70143047-9fdfd600-16c0-11ea-816d-57e1c2060337.png">

Can we improve this so that the comment displayed will break into several lines?  and can be viewed without scrolling

**Comment by chanaka3d** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8019
