### ISSUE TITLE
Cannot specify "Display Name" of a scope in Publisher UI

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#7090]
In 2.x.x versions of API Manager we allowed users to specify a Scope key, display name, description and roles when creating a new scope in the Publisher UI.

But from 3.0.0 on there is no field for specifying the Display Name of a scope

![image](https://user-images.githubusercontent.com/6614042/70209485-635eb980-1756-11ea-92c5-ee6049c1c437.png)

**Comment by dushaniw** [comment]
We will not be fixing this for 3.1.0. Will consider this for future release, with scope management revamping

**Comment by tmkasun** [comment]
@mushthaq33 , Hope we have covered this in shared global scopes ?

**Comment by dushaniw** [comment]
we have done this in shared global scopes. but shouldn't we do this to the local scopes as well?
