### ISSUE TITLE
[APIM 3.0.0] Postgre type configs are not working for AM_DB

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#7091]
### Description

When configuring the APIM 3.0.0 with the Postgre the `type` defined for the `AM_DB` is not getting reflected at the `master-datasource.xml` artifacts (the `validation query` and `driver`).

But the `type` and `driver` and `validation query` related configurations are getting applied for the `SHARED DB` configurations.

Given below is an extract used to reproduce the issue ...

```deployment.toml
[database.apim_db]
type = "postgre"
url = "jdbc:postgresql://localhost:5432/apimgtdb"
username = "postgres"
password = "postgres"

[database.shared_db]
type = "postgre"
url = "jdbc:postgresql://localhost:5432/shareddb"
username = "postgres"
password = "postgres"
```

### Affected Versions

* APIM 3.0.0 and above

**Comment by dushaniw** [comment]
Fixed in latest with https://github.com/wso2/product-apim/pull/6832
