### ISSUE TITLE
Error when importing API Definition File from "IMPORT DEFINITION"  in API Definition tab

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7092]
Steps To Reproduce:

1. Create an API using petstore-swagger.json
2. Then go to 'API Definition' tab and click on "IMPORT DEFINITION" 
3. Upload the same petstore-swagger.json from file.

Output:
API is getting created without any backend error logs. But the UI throws the following error.

![Screenshot from 2019-12-05 13-19-32](https://user-images.githubusercontent.com/12208083/70214725-f0f3d680-1761-11ea-98db-3bd4f8911080.png)

[petstore.zip](https://github.com/wso2/product-apim/files/3925634/petstore.zip)

**Comment by kavishkafernando** [comment]
Duplicate https://github.com/wso2/product-apim/issues/6827
