### ISSUE TITLE
Analytics events are dropped from the APIM

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#7096]
Description
When a semaphore lock is not released properly, the number of threads that used for event publishing reduces to zero and the publisher will always be in the locked state. Due to that, the queue is dropping the events.

**Comment by kavishkafernando** [comment]
public commit: #https://github.com/wso2/carbon-analytics-common/pull/574/commits/258b5a9f7547634abf715a8a1142268dc745ba7f
