### ISSUE TITLE
The tenant information is not found when the token regeneration is triggered.

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#7101]
We need tenant information to determine the external key manager when the Key Manager operation is triggered. But we observed that the tenant flow is not initiated when the token regeneration is invoked.

APIM VERSION: 2.6.0

**Comment by kavishkafernando** [comment]
SUpport commit: #https://github.com/wso2-support/carbon-apimgt/commit/1e25fdfbc56d68ef0e75b152644987e2c14e1a5b
