### ISSUE TITLE
Visibility to Domain option in Visibiltiy Role restriction is not working

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-apim#7106]
When clicking on visibility to Domain option for restricting only the users of the particular tenant domain, all the users of the tenant couldn't be able to view the API in the store instead of the publisher.
Only the users having role given for publisher API accessibility could able to view the particular API but the API should able to be viewed by all the users of that particular tenant if we specify "Visible to Domain" option.

Example:
Access control(publisher): Administrator role only.
Visible to store: Visible to My Domain

Only users having Administrator role can view the APIs in store too.

**Comment by chamindias** [comment]
PR : https://github.com/wso2-support/carbon-apimgt/pull/1783

**Comment by chamindias** [comment]
PR : https://github.com/wso2/carbon-apimgt/pull/8039

**Comment by nadeepoornima** [comment]
Please note this issue has reported for APIM 3.0.0. Shall we front port this fix?
