### ISSUE TITLE
WSO2 Api Manger 3.0.0 how to use HA routing of services

### ISSUE THREAD

**Issue by k10gaurav** [wso2/product-apim#7109]
We have two API servers running in HA mode i.e. same set of services are running on both VMs with same environment. We would like to use WSO2 APIM for API Security but the problem is that we have not been able to find how to use HA routing services in WSO2 APIM. E.g.

API Server 1- http://192.168.0.2/getCustomerDetails
API Server 2- http://192.168.0.3/getCustomerDetails
API Gateway(APIM)- 192.168.0.10

Once registered on API Gateway, the service endpoints become-
URL1- https://192.168.0.10:8243/getCustInfo1
URL2- https://192.168.0.10:8243/getCustInfo2

Now the question is how does WSO2 APIM decides where to route the request i.e. URL1 or URL2 for accessing the same business service since single endpoint is required for actual consumption in web app? Or there is some concept like virtual ip usage in WSO2 APIM?

**Comment by dushaniw** [comment]
Hi @k10gaurav 

As far as I understood, you have two backend API servers running in 192.168.0.2 and 192.168.0.3 and you have a single WSO2 API Gateway. And you are looking for a way to send the API requests to the backend servers through WSO2 API Gateway in a load-balanced manner. If this is the case, you can use the loadbalance endpoints for the API. 

[1] For APIM 2.6 ->  https://docs.wso2.com/display/AM260/Working+with+Endpoints
[2] For APIM 3.0 -> https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/Endpoints/high-availability-for-endpoints/

**Comment by dushaniw** [comment]
Let us know if this answers your concern or whether you need more help.

**Comment by k10gaurav** [comment]
@dushaniw thanks a lot for your response. I have tried out and implemented the Load Balancer and Failover option available during the API Design under Endpoints section. However either LB is working or failover at a Time but not both i.e. I have a requirement of both options concurrently i.e. services should be discovered via LB and if any LB endpoint is down, then instead of throwing error request should be served from next available node. Currently if I choose LoadBalancer option then if any node is down then it throws error of network failure (round robin )
![APIM_Failover_LB](https://user-images.githubusercontent.com/4989950/71738610-1cf79a00-2e7d-11ea-8030-e26eff8ed6a3.png)
