### ISSUE TITLE
WSO2 AM deploy error java.net.NoRouteToHostException: No route to host (Host unreachable) on Centos7 Server

### ISSUE THREAD

**Issue by TrugNIng** [wso2/product-apim#7113]
I'm using AM 2.6.0. When I deploy in PC using Window everything OK. But when I deploy it on Centos7 Server it has error below https://i.stack.imgur.com/xjYVR.png. I try config as the following docs https://docs.wso2.com/display/SP430/Installing+as+a+Linux+Service but still has this error.

Please let me know if you have any other solutions in my case. Tks all!

**Comment by dushaniw** [comment]
Hi @TrugNIng 

The reason for this error in the startup is that Qpid server hasn't bound to the port 5672. There may be some firewall rules bound with the Centos server which causes to block this port.

When you see the above exception, without shutting the server down, could you please check whether any process bound to the port 5672?
