### ISSUE TITLE
AuthManager Setting using Deployment.toml in apim 3.0

### ISSUE THREAD

**Issue by ashishpilania18** [wso2/product-apim#7126]
Unable to find any custom setting  for setting up auth manager url  in api-manager.xml using deployment.toml  Please help
As I m deploying in distributed setup need to update serverurl and checkpermissionRemotely

 <AuthManager>
        
        <ServerURL>https://localhost:${mgt.transport.https.port}${carbon.context}services/</ServerURL>
        
        <Username>${admin.username}</Username>
        
        <Password>${admin.password}</Password>
        
        <CheckPermissionsRemotely>false</CheckPermissionsRemotely>
    </AuthManager>

**Comment by dushaniw** [comment]
Hi @ashishpilania18 

We do not support this in deployment.toml. In APIM 3.0, we recommend using the local publisher/store server's Authentication Manager service. However, you need to share the userstores among both servers.
