### ISSUE TITLE
Missing space after "Authorization: Bearer" in curl command

### ISSUE THREAD

**Issue by BeParis** [wso2/product-apim#7128]
Using devportal then trying to execute a curl request, the curl generated statment shows that the token value is merged with the string bearer in the header. 
Example of generated curl command: 
curl -X GET "http://localhost:8280/hello/v1" -H "accept: */*" -H "Authorization: BearereyJ0eXAiOiJKV1QiLCJhb.............;"

![image](https://user-images.githubusercontent.com/48685040/70625461-b2a75d00-1c22-11ea-8c57-42dafa876e1d.png)

**Comment by dushaniw** [comment]
Hi @BeParis 

Could you please let us know the API version you are using?

**Comment by dushaniw** [comment]
There was a similar issue reported with M4 and we have fixed it in M5 release.
Please refer [1].

[1] https://github.com/wso2/product-apim/issues/7098
