### ISSUE TITLE
Issue in adding authorization_manager and realm_manager configurations in deployment.toml

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7133]
The configuration changes are not reflected in user-mgt.xml, to add properties to authorization_manager configuration, if we add following property to `deployment.toml`, 

```
[authorization_manager.properties]
PreserveCaseForResources = false
```

This is because, the default value has been defined as set of object - [1]. This needs to be changed as follows until https://github.com/wso2/config-mapper/issues/11 is fixed. Same issue observed with `realm_manager` as well.

```
"authorization_manager.class": "org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager",
"authorization_manager.properties.AdminRoleManagementPermissions": "/permission",
"authorization_manager.properties.AuthorizationCacheEnabled": "true",
"authorization_manager.properties.GetAllRolesOfUserEnabled": "false",
```

[1] https://github.com/wso2/carbon-kernel/blob/4.5.x/distribution/kernel/carbon-home/repository/resources/conf/default.json#L9

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/carbon-kernel/pull/2457
