### ISSUE TITLE
Styling error in Subscription wizard

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#7135]
**Description**
In the subscription creation wizard in Dev Portal the content of the steps 'Generate Keys' and 'Generate Access Token' doesn't have the same left indentation as the content of the previous steps.

<img width="1450" alt="Screen Shot 2019-12-12 at 5 42 16 PM" src="https://user-images.githubusercontent.com/20040505/70711236-07bc9f00-1d07-11ea-96b6-0f93999c748c.png">
<img width="1452" alt="Screen Shot 2019-12-12 at 5 42 22 PM" src="https://user-images.githubusercontent.com/20040505/70711237-07bc9f00-1d07-11ea-8b82-54f517e0d775.png">
<img width="1543" alt="Screen Shot 2019-12-12 at 5 36 36 PM" src="https://user-images.githubusercontent.com/20040505/70711233-07240880-1d07-11ea-8fa1-7681e225e78a.png">
<img width="1477" alt="Screen Shot 2019-12-12 at 5 37 32 PM" src="https://user-images.githubusercontent.com/20040505/70711235-07240880-1d07-11ea-9ac4-660d7c391b26.png">

**Comment by chanaka3d** [comment]
Fixed with the bove PR.
