### ISSUE TITLE
Access Log pattern is not configurable in APIM 3.0.0

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#7137]
The access log pattern which is defined in repository/conf/tomcat/catalina-server.xml file has not been templated in new config model. The following config has to be introduced to repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2

```xml
<Valve className="org.apache.catalina.valves.AccessLogValve" directory="${carbon.home}/repository/logs"
prefix="http_access_" suffix=".log" pattern="{{http_access_log.pattern}}"/>
```

**Comment by Krishanx92** [comment]
tagging https://github.com/wso2/product-apim/issues/7228

**Comment by tharindu1st** [comment]
fix in https://github.com/wso2/product-apim/commit/bf83c0727b49499025c715657de2c943a542530a
