### ISSUE TITLE
Click on 'edit' new documentation return error

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-apim#7139]
**Description** :
Edit new document gives error page 

<img width="804" alt="Screen Shot 2019-12-12 at 6 40 26 PM" src="https://user-images.githubusercontent.com/13038128/70760704-1bb8ce80-1d10-11ea-8779-781518d62f59.png">

**Step to produce:**
In APIM publisher under the _Documentation section_, I click on **Add New Document**.
Provided **Name** and **Summary** and click on **Save** button.
On popup click on **Add Content** button.

<img width="723" alt="Screen Shot 2019-12-12 at 6 42 51 PM" src="https://user-images.githubusercontent.com/13038128/70760705-1bb8ce80-1d10-11ea-8112-50ab483b04b5.png">

If I click on **back to listing**  button and on it click on Edit content the error is not shown and I can edit page.

**Comment by dushaniw** [comment]
hi @lpastor74 

I was able to reproduce this when trying to add documentation for inline type, but not for others? Could you please confirm the same?

**Comment by dushaniw** [comment]
Duplicates https://github.com/wso2/product-apim/issues/7153

**Comment by lpastor74** [comment]
Yes, it only happens for inline doc

**Comment by dushaniw** [comment]
Thanks for the info. We will provide a fix for this.
