### ISSUE TITLE
Can only upload certificates with .crt extension for backend certificates

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7151]
For APIM 3.0, we can only add certs with .cert extension from UI

**Comment by kavishkafernando** [comment]
Other certificate types seems to be supported by the UI.
<img width="436" alt="Screen Shot 2020-01-03 at 10 08 00 AM" src="https://user-images.githubusercontent.com/19324135/71708366-ceafb000-2e16-11ea-8284-67e86b0710b4.png">

I noticed the following issue.

- Once an invalid cert type is uploaded and then when you re-upload a valid cert type it is still displayed as invalid.
- Even if you press cancel and re-open the certificate upload UI and upload a valid certificate it still shows as invalid.
- Once the page is refreshed the valid certificate can be added.

<img width="450" alt="Screen Shot 2020-01-03 at 10 54 41 AM" src="https://user-images.githubusercontent.com/19324135/71708451-788f3c80-2e17-11ea-9b31-91bd6b3f7a9d.png">
