### ISSUE TITLE
UI Error when adding inline content doc for an API

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7153]
1. Create an API
2. Add a documentation with type inline
3. Add inline content (Click 'Add Content' from the UI dialog box after adding the documentation')
4. Getting the following error
![Screenshot from 2019-12-16 11-44-08](https://user-images.githubusercontent.com/12208083/70883621-911aec80-1ff9-11ea-81cb-d729ec243b2b.png)

If we refresh and go back to the document tab and try to edit, it works without any issue.

**Comment by kavishkafernando** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7897 in 3.1.0

**Comment by kavishkafernando** [comment]
@CrowleyRajapakse FYI
