### ISSUE TITLE
URL type API documentation shows option to add content.

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7154]
URL type documentation does not have content. Hence showing an option to add content for such documentation is not needed. 

1. Add an API and add documentation with type "URL".
2. In the confirmation dialog box getting the button "Add content"
![Screenshot from 2019-12-16 11-49-23](https://user-images.githubusercontent.com/12208083/70884035-c5db7380-1ffa-11ea-88f5-de62f158f51f.png)

3. If someone clicks on "Add Content", we are getting an empty screen

![Screenshot from 2019-12-16 11-48-50](https://user-images.githubusercontent.com/12208083/70884056-d390f900-1ffa-11ea-99e5-f28918e5df3c.png)

**Comment by kavishkafernando** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7897 in 3.1.0

**Comment by kavishkafernando** [comment]
@CrowleyRajapakse FYI
