### ISSUE TITLE
After adding a documentation "file" type, Publisher does not redirect to documentation list

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7155]
1. Create an API and add a documentation type "File"
2. After successfully adding the doc, instead of redirecting to the documentation list, Publisher shows the following UI.
![Screenshot from 2019-12-16 11-59-56](https://user-images.githubusercontent.com/12208083/70884283-9a0cbd80-1ffb-11ea-83d7-577e19425810.png)

**Comment by kavishkafernando** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/7899 in 3.1.0

**Comment by kavishkafernando** [comment]
@CrowleyRajapakse FYI
