### ISSUE TITLE
DevPortal not loading

### ISSUE THREAD

**Issue by imchivaa** [wso2/product-apim#7169]
Hi there,
API Manager Version: 3.1.0-M2
Environment: Windows Server 2012 & 2016

I downloaded 3.1.0-M2 from the release page and started API Manager. Upon navigating to DevPortal url, it just loading and this error was thrown in the log

```
TID: [-1234] [api/am/store/v1.0] [2019-12-18 05:23:31,457] ERROR {org.wso2.carbon.apimgt.rest.api.util.interceptors.PostAuthenticationInterceptor} - Authentication failed: Bearer/Basic authentication header is missing
```

In the carbon.xml and api-manager.xml, i changed `localhost` to IP address. But i don't think that causing the issue. Can advice on how to fix this issue?

Thank you.

**Comment by imchivaa** [comment]
Never mind, i found that using the deployment.toml solve the issue.

**Comment by teodora-mitrovic** [comment]
Hey @imchivaa, can you tell what exactly did you do in deployment.toml file to solve the issue?
Thank you in advance!
