### ISSUE TITLE
Custom Mediation Policies get saved even without clicking the select button

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7170]
1. Click edit button Message Mediation.
2. Upload the sequence file. Just after uploading the file is attached to the API. There is no use of the "Select" button of the UI dialog box.
![Screenshot from 2019-12-19 12-42-52](https://user-images.githubusercontent.com/12208083/71156513-26221d80-2266-11ea-80e0-ac988aedca4d.png)

**Comment by kavishkafernando** [comment]
The Select button makes sense when multiple sequences are uploaded. A user can select which sequence they want to apply. 
<img width="651" alt="Screen Shot 2020-01-03 at 11 21 05 AM" src="https://user-images.githubusercontent.com/19324135/71709072-47b10680-2e1b-11ea-8861-93f1014d4d79.png">

Hence closing the issue.
