### ISSUE TITLE
Cannot create API resources with variable resource path(/{abc}) while generating REST API from SOAP backend

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#7173]
**Issue description**
When generating REST API from SOAP backend as per the documentation[1], the APIM has the capability of editing the resources.
But when we try to save the API, it fails with the below error if there is a variable resource path like '/checkPhoneNumber/{abc}'.

`[2019-12-19 14:39:34,191] ERROR - APIUtil Error occurred while accessing the registry to save api sequence
org.wso2.carbon.registry.core.exceptions.RegistryException: The path '/_system/governance/apimgt/applicationdata/provider/admin/sample/1.0.0/soap_to_rest/in/checkPhoneNumber/{abc}_post.xml' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
	at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:262)`

**Steps to reproduce:**
* Follow the steps in the documentation[1].
* Then change the API resource path as '/checkPhoneNumber/{abc}' by editing the source.
* Try to click on the 'Next: Implement' button.

**Affected product version:**
APIM-2.6.0

**References**
[1] - https://docs.wso2.com/display/AM260/Generate+REST+APIs+from+SOAP+Backends

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by vithu30** [comment]
In 3.10, if a resource is edited to have path parameter, then in-sequence for that resource is not visible in Publisher

**Comment by vithu30** [comment]
There is issue in adding new resources to API with parameters and editing existing resources with path parameters
