### ISSUE TITLE
Issue while following configuration guide on Using Email Address as the Username

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7175]
**labels**
3.0.0

**Description**
Restart the server after following [1] configurations. 

Cannot log in to publisher with updated super username. (that user is only given internal/everyone role which contradicts to what the doc [1] says. )
`After this configuration, the user having the username admin@wso2.com is considered the super administrator. The user having the username admin is considered as a normal administrator.`
[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/LoginsAndPasswords/maintaining-logins-and-passwords/#setting-up-an-e-mail-login
[2] https://is.docs.wso2.com/en/5.9.0/learn/using-email-address-as-the-username/

**Comment by CrowleyRajapakse** [comment]
This issue seems to be fixed in the latest APIM 3.1 and issue can be closed.
