### ISSUE TITLE
Improper location of listenerprofiles.xml.j2 and sslprofiles.xml.j2 template files.

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/product-apim#7187]
**Description:**
According to the axis2.xml file below are the files that should be updated from the toml file when configuring a new Keystore;
- <AM_HOME>\repository\resources\security\sslprofiles.xml
- <AM_HOME>\repository\resources\security\listenerprofiles.xml

But these files are not getting updated due to improper location of above j2 template files.

**Suggested Labels:**
Improvement

**Affected Product Version:**
AM-3.0.0

**Comment by kavishkafernando** [comment]
https://github.com/wso2/product-apim/issues/7228

**Comment by tharindu1st** [comment]
fix in https://github.com/wso2/product-apim/commit/58620b5b58ca13359c7b4661b74b768520f4e369
