### ISSUE TITLE
Error occurred when creating new API resources in a REST API  which generated from SOAP backend.

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#7190]
**Issue description**
When generating REST API from SOAP backend as per the documentation[1], the APIM has the capability of editing the resources.
When adding or changing the resources which included another resource's name in the particular resource path, it will break the flow.

> [2019-12-20 17:53:34,896] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [B (/publisher/site/themes/wso2/templates/item-implement/template.jag#737)org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [B (/publisher/site/themes/wso2/templates/item-implement/template.jag#737)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
            .....
    Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [B (/publisher/site/themes/wso2/templates/item-implement/template.jag#737)
            .....
    Caused by: java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to [B
            .....

**Steps to reproduce:**
* Follow the steps in the documentation[1].
* Then add a new API resource path as '/checkPhoneNumber/ID' by editing the swagger source.[2] 
* Try to click on the 'Next: Implement' button.
![image](https://user-images.githubusercontent.com/38488254/71270045-a59f1200-2376-11ea-98fa-e6d8a828b64e.png)

**Affected product version:**
APIM-2.6.0

**References**
[1] - https://docs.wso2.com/display/AM260/Generate+REST+APIs+from+SOAP+Backends
[2] - sample swagger source
> {
  "swagger": "2.0",
  "paths": {
    "/checkPhoneNumber": {
      "post": {
        "operationId": "CheckPhoneNumber",
        "parameters": [
          {
            "in": "body",
            "name": "Payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/checkPhoneNumberInput"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/checkPhoneNumberOutput"
            }
          }
        },
        "x-wso2-soap": {
          "soap-action": "http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber",
          "soap-operation": "CheckPhoneNumber",
          "namespace": "http://ws.cdyne.com/PhoneVerify/query",
          "x-soap-version": "1.2"
        }
      }
    },
    "/checkPhoneNumbers": {
      "post": {
        "operationId": "CheckPhoneNumbers",
        "parameters": [
          {
            "in": "body",
            "name": "Payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/checkPhoneNumbersInput"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/checkPhoneNumbersOutput"
            }
          }
        },
        "x-wso2-soap": {
          "soap-action": "http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumbers",
          "soap-operation": "CheckPhoneNumbers",
          "namespace": "http://ws.cdyne.com/PhoneVerify/query",
          "x-soap-version": "1.2"
        }
      }
    },
    "/checkPhoneNumber/ID": {
      "post": {
        "operationId": "CheckPhoneNumber2",
        "parameters": [
          {
            "in": "body",
            "name": "Payload",
            "required": true,
            "schema": {
              "$ref": "#/definitions/checkPhoneNumberInput"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/checkPhoneNumberOutput"
            }
          }
        },
        "x-wso2-soap": {
          "soap-action": "http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber",
          "soap-operation": "CheckPhoneNumber",
          "namespace": "http://ws.cdyne.com/PhoneVerify/query",
          "x-soap-version": "1.2"
        }
      }
    }
  },
  "info": {
    "title": "ejhkjs",
    "version": "1.0.0"
  },
  "definitions": {
    "checkPhoneNumberInput": {
      "type": "object",
      "properties": {
        "CheckPhoneNumber": {
          "$ref": "#/definitions/CheckPhoneNumber"
        }
      }
    },
    "checkPhoneNumberOutput": {
      "type": "object",
      "properties": {
        "CheckPhoneNumberResponse": {
          "$ref": "#/definitions/CheckPhoneNumberResponse"
        }
      }
    },
    "checkPhoneNumbersInput": {
      "type": "object",
      "properties": {
        "CheckPhoneNumbers": {
          "$ref": "#/definitions/CheckPhoneNumbers"
        }
      }
    },
    "checkPhoneNumbersOutput": {
      "type": "object",
      "properties": {
        "CheckPhoneNumbersResponse": {
          "$ref": "#/definitions/CheckPhoneNumbersResponse"
        }
      }
    },
    "StringArray": {
      "type": "string",
      "properties": {
        "String": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "CheckPhoneNumber": {
      "type": "object",
      "properties": {
        "PhoneNumber": {
          "type": "string"
        },
        "LicenseKey": {
          "type": "string"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "CheckPhoneNumbersResponse": {
      "type": "object",
      "properties": {
        "CheckPhoneNumbersResult": {
          "$ref": "#/definitions/ArrayOfPhoneReturn"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "ArrayOfString": {
      "type": "object",
      "properties": {
        "string": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "ArrayOfPhoneReturn": {
      "type": "object",
      "properties": {
        "ArrayOfPhoneReturn": {
          "$ref": "#/definitions/ArrayOfPhoneReturn"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "CheckPhoneNumbers": {
      "type": "object",
      "properties": {
        "PhoneNumbers": {
          "$ref": "#/definitions/ArrayOfString"
        },
        "LicenseKey": {
          "type": "string"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "PhoneReturn": {
      "type": "object",
      "properties": {
        "PhoneReturn": {
          "$ref": "#/definitions/PhoneReturn"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    },
    "CheckPhoneNumberResponse": {
      "type": "object",
      "properties": {
        "CheckPhoneNumberResult": {
          "$ref": "#/definitions/PhoneReturn"
        }
      },
      "xml": {
        "namespace": "http://www.w3.org/2001/XMLSchema",
        "prefix": "s"
      }
    }
  }
}

**Comment by lkokila** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by vithu30** [comment]
This is not reproducible in 3.10
