### ISSUE TITLE
Customizing Error Pages for Management Console 

### ISSUE THREAD

**Issue by asatiratnesh** [wso2/product-apim#7215]
To Customizing Error Pages for Management Console in **API-M 3.0.0,** I followed the steps mentioned in the below link:
https://apim.docs.wso2.com/en/latest/Administer/ProductConfigurations/customizing-the-management-console/#customizing-error-pages

My configured code of web.xml file gets reverted after restarting the management server(wso2server.bat --run).

Please, anyone suggests, how to configure the error-page on deployment.toml file

**Comment by CrowleyRajapakse** [comment]
It seems we haven't templated the <CARBON_HOME>/repository/conf/tomcat/carbon/WEB-INF/web.xml properly for the new config model to include error page configs in deployment.toml file. We will provide the necessary fix in a future release. 

Until then just for testing purposes, you can directly change the values in <CARBON_HOME>/repository/resources/conf/templates/repository/conf/tomcat/carbon/WEB-INF/web.xml.j2 . This is the default code which get applied when you restarts the server currently.

**Comment by CrowleyRajapakse** [comment]
Tagging https://github.com/wso2/product-apim/issues/7228

**Comment by tharindu1st** [comment]
after the above pull request, you can configure the error pages as below in deployment.toml
    [error_page] 
     code_400.location = "/carbon/errors/error_400.html"
     code_401.location = "/carbon/errors/error_401.html"
     code_403.location = "/carbon/errors/error_403.html"
