### ISSUE TITLE
Parameters are missing in the payload when parameters have the same resource name - SOAP to REST conversion

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#7216]
**Steps to reproduce:**
1. Create an API with WSDL file (with Generate REST APIs options)
2. Move into Implement tab

As in the screenshot some parameters are missing in the payload (Here resource name and missing parameter name is "code")

![image](https://user-images.githubusercontent.com/44961438/71724244-9ed3cd00-2e55-11ea-9e4f-75b636e51e7f.png)

Sample swagger definition:

> swagger: "2.0"
> paths:
>   /code:
>     post:
>       operationId: code
>       parameters:
>         - in: body
>           name: Payload
>           required: true
>           schema:
>             $ref: "#/definitions/codeInput"
>       responses:
>         default:
>           description: ""
>           schema:
>             $ref: "#/definitions/codeOutput"
>       x-wso2-soap:
>         soap-action: ""
>         soap-operation: code
>         namespace: "http://sample:8080/wsdl"
>         x-soap-version: "1.1"
> info:
>   title: Test4
>   version: ""
> definitions:
>   codeInput:
>     type: object
>     properties:
>       codeRequest:
>         $ref: "#/definitions/codeRequest"
>   codeOutput:
>     type: object
>     properties:
>       codeResponse:
>         $ref: "#/definitions/codeResponse"
>   codeRequest:
>     type: object
>     properties:
>       code:
>         type: string
>       status:
>         type: string
>   codeResponse:
>     type: object
>     properties:
>       returnMessage:
>         type: string
> 

![image](https://user-images.githubusercontent.com/44961438/71724108-089fa700-2e55-11ea-9b45-2bac2f46f2d2.png)

**Version: 2.2**

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/7130

**Comment by vithu30** [comment]
This issue is not reproducible in 3.1.0.
