### ISSUE TITLE
Grant type refresh token vs client credentials grant type

### ISSUE THREAD

**Issue by mrderban** [wso2/product-apim#7223]
Hi everyone,
I'm wondering what's the point of using the refresh token grant type vs using the client credentials grant type in order to get a new access token in a situation where the access token is **already expired**.
In both the refresh token grant type and client credentials grant type we have to send the application credentials anyway. Is one faster than the other ? there's something i'm missing here.

Thanks !

**Comment by bhathiya** [comment]
The refresh and client-credentials are used in 2 different use cases. 

Client credentials are used to take tokens NOT on behalf of a user. Those are basically app tokens, but not user tokens. That's why it does not require any user information.

Unlike the above, the Refresh grant type can't work alone. It needs refresh token returned in the response of another grant type such as password or authorization code. Those are user tokens. 

Hope this is clear.

**Comment by mrderban** [comment]
Hi bhathiya,

Thanks for your answer. I do understand the difference between a user access token (which you get using the password type grant) and an application access token (which you get using the client credentials grant type). But let's consider the following situation: My application token has expired but the refresh associated to it is still valid, i'm now faced with two choices: either i get a new  application token using the **credentials grant type** (i need to send the credentials in order for the app to be authorized) or either i get a new application token using the **refresh grant type** (now i need to send not only the credentials because i still need to authorize the application but also the refresh token !). So my question is what should i do ? Am i missing something ?

Thanks !

**Comment by bhathiya** [comment]
I see. So you're talking about an application token. 

I didn't know APIM gives a refresh token in the client credential response. If it gives, your confusion makes sense. There is no use of refresh token in case of client credentials grant.

**Comment by mrderban** [comment]
Yes, absolutely ! a refresh token SHOULD not be obtained when using the client credentials grant, yet it is possible in wso2 apim. 

So now considering the user access token, if i'm right: Let's say i'm the application I just need to ask the end user its username and password once, send those with my credentials to the authorization servers (keymanagers) to get a user access token on behalf of the user (+ a refresh token), then when this user access token is expired, i don't need to ask the user for its username and password anymore, i can just get a new user access token on his behalf using his refresh token ? am i right ?

Thanks again !

**Comment by bhathiya** [comment]
Yes, your understanding is correct about refresh tokens. 

However, I just tried to get a token by client credentials grant in APIM 3.0 and it didn't give me a refresh token.

```
[17:21:04] bhathiya@MacBookPro:~/wso2am-3.0.0/bin$ curl -k -X POST https://localhost:8243/token -d "grant_type=client_credentials" -H"Authorization: Basic Nk5JQ09DTEVvZ3JzYlpfZklTTnVlZzVDVUVBYTpmWnRucjhFYm5BV2pEMjVvM1Eya2VIVTZPUXNh" | jsonpp

{
  "access_token": "82214177-e89d-35da-871f-99cad633ef1b",
  "scope": "am_application_scope default",
  "token_type": "Bearer",
  "expires_in": 3576
}
```

**Comment by mrderban** [comment]
i'm using the APIM 2.2.0, maybe it's not possible anymore, but if i'm not mistaken, by default there is no refresh tokens sent back with the client credentials grant type, yet you can activate the option by modifying a .xml file, the identity.xml i believe.

**Comment by mrderban** [comment]
Anyway thanks a bunch Bhathiya for your answers !
