### ISSUE TITLE
In and Out sequences of an API resource, generated using SOAP to REST feature is not available in the UI.

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#7224]
**Issue description:**
When generating REST API from SOAP backend as per the documentation[1], the API resources should have the capability of editing the swagger definitions of the In and Out sequences from the UI.
But when we click on an API resource, it is not showing the swagger definitions of the In and Out sequences from the UI, even though the documentation [1] - point 7, is explaining the capability.

**Affected product version:**
APIM-3.0.0

**References:**
[1] https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPI/generate-rest-api-from-soap-backend/

**Comment by Prasadi-R** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by Krishanx92** [comment]
https://github.com/wso2/carbon-apimgt/pull/7818
