### ISSUE TITLE
SP does not terminate the local session before initiating SLO.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-apim#7238]
### Description
Publisher and Store apps don't terminate their local sessions before sending the logout request to IDP. They wait until the logout response comes from IS. This behavior causes the apps to stay logged in even after the user clicked on the logout button.
The [(SAML) V2.0 Technical Overview](https://support.wso2.com/jira/browse/CLOUDPROD-1331#5.3.2.SP-Initiated%20Single%20Logout%20with%20Multiple%20SPs) says that the SP has to clear its local session before sending the logout request to the IDP.

> The SP sp1.example.com destroys the local authentication session state for the user and then sends the idp.example.org identity provider a SAML <LogoutRequest> message requesting that the user's session be logged out.

**Comment by tmkasun** [comment]
@ruks ,Do we need to patch this in 3.x.x as well, we no longer use SAML based sso in 3.x.x ?

**Comment by ruks** [comment]
@tmkasun We need to support the same behaviour in 3.x even it is SAML or OIDC. So we need to find a fix for the new implementation.

**Comment by ruks** [comment]
Close since it is fixed in 400
