### ISSUE TITLE
Cannot generate access tokens specifying a scope which is assigned to multiple API resources

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#7249]
**Description**
If the scope doesn't tie to any role and is assigned to multiple API resources, the scope doesn't get applied accordingly when trying to generate an access token after selecting this particular scope. Instead, the default scope gets applied.

**Steps to reproduce**

1. From Publisher, create an API and for that API, create a scope that doesn't tie to any role.
2. Assign it to multiple resources of the API.
3. Go to the Store, subscribe to the API from an application.
4. Try to generate an access token for the application after specifying the particular scope.
5. Check the assigned list of the scopes for the generated access token.

**Affected version**
wso2am-2.6.0

**Comment by ruks** [comment]
Not reproducible in later APIM version(3.1.0 snapshot). Hence closing
