### ISSUE TITLE
Error in the Dashboard visualization

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-apim#7250]
dear team, there is an error in the Dashboard; in the APIM Publisher View, API Proxy Performance, when I choose for example 1 day range and minute as granularity, it shows the data with the following time scale: 5:30, 8:30, 9:25, **9:24** 

please see picture attached
<img width="1269" alt="Screen Shot 2020-01-15 at 09 33 37" src="https://user-images.githubusercontent.com/39225773/72404401-33ee9400-377b-11ea-868c-29b265e518b4.png">

**Comment by fazlan-nazeem** [comment]
Yes, we fixed this in the apim analytics 3.1 milestone releases.
