### ISSUE TITLE
Publisher login problem. Cannot read property "length" from undefined

### ISSUE THREAD

**Issue by grego9** [wso2/product-apim#7254]
Hi. I am trying to configure an Active-Active deployment as in [here](https://apim.docs.wso2.com/en/next/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment/)

I have already setup two nodes and nginx community as the reverse proxy/balancer.

Both /carbon and /devportal work great, but whenever I try to login on publisher, I got a blank page, and the following error in the log:

`ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)`

This is my SP callback url for publisher:

`regexp=(https://mywso2cluster.com/publisher/services/auth/callback/login|https://mywso2cluster.com/publisher/services/auth/callback/logout)`

Thank you

**Comment by grego9** [comment]
Thanks! After adding those lines it shows:

`[2020-01-16 09:30:18,748] ERROR - login_callback:jag {"data" : "{\"error_description\":\"Client Authentication failed.\",\"error\":\"invalid_client\"}", "xhr" : {}}
[2020-01-16 09:30:18,758] ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#55)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#55)`

That `invalid client` maybe some lost/misconfigured header?

**Comment by tmkasun** [comment]
Hi @grego9,

```javascript
{
  "data": "{\"error_description\":\"Client Authentication failed.\",\"error\":\"invalid_client\"}",
  "xhr": {}
}

```

In the error logs, It says `Invalid_client`, This could happen if you revoke or re-create the `admin_apim_publisher` service provider via carbon console

![image](https://user-images.githubusercontent.com/3313885/72587086-fb38f100-3919-11ea-931c-1095725f4d42.png)

Have you done any changes to `admin_apim_publisher` SP via carbon console (Other than changing the callback URL ) ?

**Comment by grego9** [comment]
Hi @tmkasun,

Yes, I did . When a I ran out of ideas before posting here, I regenerated the secret for the OAuth Client Key. This is a new installation, so I don't mind if I have to reinstall, but, if the is a way to solve this, that would be awesome.

Thanks

**Comment by tmkasun** [comment]
Hi @grego9 ,

That's the reason, You should not have changed the secret or key in any case, This SP is a system generated one and we have cached some of its properties in web apps to improve the performance.

**Comment by grego9** [comment]
Hi @tmkasun 

Oh, that makes sense. Guess I'll reinstall and make sure to not change the secret.

Thank you for your time

**Comment by kshaa** [comment]
@tmkasun I had a deployment succesfully running for more than 4 months I'd say. Then out of nowhere (or because of some obscure bug) `/devportal/` login page started showing `invalid_client: Cannot find an application associated with the given consumer key : XXX`.

I checked out the Service Provider OAuth2 `client_id` and `client_secret` values and unfortunately `client_secret` was empty. Any ideas how such a thing could happen? Possibly #7400 is related.

**Comment by kshaa** [comment]
And more importantly - is there a way to recover from such a situation?

**Comment by nikhilsg-git** [comment]
Hi @tmkasun 
Is there a way to resolve this , without re-installing the application?
