### ISSUE TITLE
Gateway Environment: 'Production and Sandbox' is set as default environment to sample application 'PizzaShakeAPI'.

### ISSUE THREAD

**Issue by Meruja** [wso2/product-apim#7255]
API gateway environment can be defined with any name. Earlier we have hard-code this value to be 'Production and Sandbox'. But now users can use any name, and it should applies to sample as well. But currently, when we renamed the apim.gateway.environment's name getting the following exception.
<img width="1360" alt="default name" src="https://user-images.githubusercontent.com/28688743/72496855-e04e7a00-3850-11ea-8429-525297f17519.png">

Steps to reproduce the issue:
1. Open <API-M>/repository/conf/deployment.toml file.
2. Edit the name of 'apim.gateway.environment'.
3. Now deploy API-M-3.0.0 and open dev portal and publisher.
4. In publisher, deploy an existing API and publish it.
5.  Go to dev portal and click 'Key Generation Wizard' fill the values and generate the keys. 

Now check the terminal.

**Comment by hungtv-86** [comment]
![image](https://user-images.githubusercontent.com/54196319/72662640-fd837400-3a1b-11ea-94fc-773b365fd5a6.png)
Currently, i config multi gateway but it show error

**Comment by Krishanx92** [comment]
This is not reproducing in the latest pack, hence closing the issue.
