### ISSUE TITLE
[APIM 2.2.0] Charset is not Removing in Tenant API

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#7263]
### Description

The below mediation sequence is used to remove the `charset` from requests

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="sample-sequence">
   <property name="setCharacterEncoding" value="false" scope="axis2"/>
</sequence>
```

The sequence is working as expected for Carbon Super tenant but not for Tenant specific APIs.

#### Reproducing Steps

* Start a WSO2 APIM 2.2.0 Pack
* Create a Tenant and publish an API
* Add the above-mentioned sequence as `in-sequence`
* Enable the Wire logs and invoke the API (POST) and analyze the Headers

**Comment by vithu30** [comment]
Fixed by https://github.com/wso2/carbon-kernel/pull/3195
