### ISSUE TITLE
[APIM-3.1.0] Oracle table UM_UUID_DOMAIN_MAPPER not created

### ISSUE THREAD

**Issue by jkirch57** [wso2/product-apim#7300]
### Description:
When creating SHAREDDB on Oracle using script from 3.1.0-Alpha, this table couldn't be created :  

``
CREATE TABLE UM_UUID_DOMAIN_MAPPER (
            UM_ID INTEGER,  
            UM_USER_ID VARCHAR(255),  
            UM_DOMAIN_ID INTEGER NOT NULL,  
            UM_TENANT_ID INTEGER DEFAULT 0,  
            PRIMARY KEY (UM_ID),  
            UNIQUE (UM_USER_ID),  
            FOREIGN KEY (UM_DOMAIN_ID) REFERENCES UM_DOMAIN(UM_DOMAIN_ID)  
)
``  

Because the foreign key is trying to use a reference to UM_DOMAIN where the primary key is composed by both columns (UM_DOMAIN_ID, UM_TENANT_ID),

### Steps to reproduce:
Try to import dbscripts/oracle.sql

### Affected Product Version:
3.1.0 - alpha

**Comment by tharikaGitHub** [comment]
Hi @jkirch57, Thank you for reporting the issue. This issue is fixed with the following PR and will be available in the next release of APIM 3.1.0. 

https://github.com/wso2/carbon-kernel/pull/2536
