### ISSUE TITLE
[APIM-3.1.0-m5] Publish through Multiple API Gateways

### ISSUE THREAD

**Issue by hungtv-86** [wso2/product-apim#7302]
Hello, 
i deployed publish through multiple api gateways but when i view api from publisher page to devportal page, it always show error below
![image](https://user-images.githubusercontent.com/54196319/72865194-7f6be980-3d09-11ea-856a-6ed1e52bbc45.png)
![image](https://user-images.githubusercontent.com/54196319/72865224-914d8c80-3d09-11ea-8134-227409b457d4.png)

And i deploy with document: https://apim.docs.wso2.com/en/next/Learn/DesignAPI/PublishAPI/publish-through-multiple-api-gateways/

**Comment by Krishanx92** [comment]
This is not reproducing the latest pack, hence closing the issue.
