### ISSUE TITLE
Authentication type "none" Resources gets null for API_NAME

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-apim#7304]
### Description:
When setting the Authentication type "none" to API resource, API_NAME not setting to the messageContext.

### Steps to reproduce:
1. Get a 2.6.0 WUM latest pack (2020-01-22)
2. Create simple API (test) and create 2 API Definitions
   2.1. /sample1
   2.2 /sample2
3. Change the **/sample1** authentication type to "none" in the **manage** tab and keep the **/sample2** as it is.
4. Create an application and generate an access token. Subscribe **test** API.
5. Add a following log to the API XML file (resided in wso2am-2.6.0/repository/deployment/server/synapse-configs/default/api) as below. Need to add to them both **/sample1** and **/sample2** resources
`<log level="custom">  `
      `              <property name="API- /sample1 ---->" expression="$ctx:API_NAME"/> ` 
`</log>`
6. Invoke to 2 APIs, and check the logs.

Will get a sample log as below
`API- /sample1 ----> null`
`API- /sample2 ----> test`

### Affected Product Version:
2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by SupunTharakaSandaruwan** [comment]
**Description**
The same issue also identified for APIM 2.0.0 by following the above steps.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/product-apim/issues/7304
