### ISSUE TITLE
[APIM-3.1.0] Oracle table creation error for APIMGTDB (seems mysql copy/paste)

### ISSUE THREAD

**Issue by jkirch57** [wso2/product-apim#7308]
### Describe your problem(s)
Table IDN_OAUTH2_DEVICE_FLOW and IDN_OAUTH2_DEVICE_FLOW_SCOPES are not created because the option "IF NOT EXISTS" doesn't exist on Oracle.  
BIGINT doesn't exist for POLL_TIME which I replaced by NUMBER(19), AUTO_INCREMENT doesn't exists not so I replaced by a ORACLE sequence and we can't create a foreign key on a non primary from another table but for this one I don't know how to change it ? (I tried to replace by DEVICE_CODE)

```
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_DEVICE_FLOW (
            CODE_ID VARCHAR2(255),
            DEVICE_CODE VARCHAR2(255),
            USER_CODE VARCHAR2(25),
            CONSUMER_KEY_ID INTEGER,
            LAST_POLL_TIME TIMESTAMP NOT NULL,
            EXPIRY_TIME TIMESTAMP NOT NULL,
            TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            POLL_TIME BIGINT,
            STATUS VARCHAR2 (25) DEFAULT 'PENDING',
            AUTHZ_USER VARCHAR2 (100),
            TENANT_ID INTEGER,
            USER_DOMAIN VARCHAR2(50),
            IDP_ID INTEGER,
            PRIMARY KEY (DEVICE_CODE),
            UNIQUE (CODE_ID, USER_CODE, DEVICE_CODE),
            FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_DEVICE_FLOW_SCOPES (
            ID INTEGER NOT NULL AUTO_INCREMENT,
            SCOPE_ID VARCHAR2(255),
            SCOPE VARCHAR2(255),
            PRIMARY KEY (ID),
            FOREIGN KEY (SCOPE_ID) REFERENCES IDN_OAUTH2_DEVICE_FLOW(CODE_ID) ON DELETE CASCADE)
/
```

### Describe your solution
```
CREATE TABLE IDN_OAUTH2_DEVICE_FLOW (
            CODE_ID VARCHAR2(255),
            DEVICE_CODE VARCHAR2(255),
            USER_CODE VARCHAR2(25),
            CONSUMER_KEY_ID INTEGER,
            LAST_POLL_TIME TIMESTAMP NOT NULL,
            EXPIRY_TIME TIMESTAMP NOT NULL,
            TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            POLL_TIME NUMBER(19),
            STATUS VARCHAR2 (25) DEFAULT 'PENDING',
            AUTHZ_USER VARCHAR2 (100),
            TENANT_ID INTEGER,
            USER_DOMAIN VARCHAR2(50),
            IDP_ID INTEGER,
            PRIMARY KEY (DEVICE_CODE),
            UNIQUE (CODE_ID, USER_CODE, DEVICE_CODE),
            FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE);

CREATE TABLE IDN_OAUTH2_DEVICE_FLOW_SCOPES (
            ID INTEGER NOT NULL,
            SCOPE_ID VARCHAR2(255),
            SCOPE VARCHAR2(255),
            PRIMARY KEY (ID),
            FOREIGN KEY (SCOPE_ID) REFERENCES IDN_OAUTH2_DEVICE_FLOW(DEVICE_CODE) ON DELETE CASCADE);
            
CREATE SEQUENCE IDN_OAUTH2_DEVICE_FLOW_SCOPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER IDN_OAUTH2_DEVICE_FLOW_SCOPES_TRIG
            BEFORE INSERT
            ON IDN_OAUTH2_DEVICE_FLOW_SCOPES
            REFERENCING NEW AS NEW
            FOR EACH ROW
               BEGIN
                   SELECT IDN_OAUTH2_DEVICE_FLOW_SCOPES_SEQ.nextval INTO :NEW.ID FROM dual;
               END;
```

**Comment by tharikaGitHub** [comment]
Hi @jkirch57, Thank you for reporting the issue. 

We have fixed this error with the following PR [1] and will be available in the next release of APIM 3.1.0.

The fix for the oracle script can be found in [2].

[1] https://github.com/wso2/carbon-apimgt/pull/8094
[2] https://github.com/wso2/carbon-apimgt/pull/8094/files#diff-735b717f6e309ed8cae52be4f0046018R166

**Comment by jkirch57** [comment]
Hello @tharikaGitHub, as I can see in the in the oracle scripts from the link [2], it looks like there is some other Oracle issue which aren't corrected like for example the "AUTO_INCREMENT", "NOT NULL" (which should be before the DEFAULT options), the "FOREIGN KEY" which has reference to a non PRIMARY KEY.... If you do a diff from my the describe problems code and the solution you'll see the differences.

Is there another PR for this ??

Regards,
Jérôme.

**Comment by tharikaGitHub** [comment]
Hi Jérôme,

Yes you are right. All those places need to be fixed. Thank you for bringing it to notice. We will fix them and let you know.

**Comment by tharikaGitHub** [comment]
Hi Jérôme,

We have corrected these errors with the following PRs [1] and [2]. These changes will be incorporated to API Manager in the next release.

[1] https://github.com/wso2/carbon-identity-framework/pull/2682
[2] https://github.com/wso2/carbon-identity-framework/pull/2688

**Comment by jkirch57** [comment]
Hi @tharikaGitHub ,

After a check on the master from the previous PR you gave me, I've one more question, why use number for poll_time instead of number(19) ? After a check on all oracle script and a corelation with mysql one, it looks like for this kind of columns you were using number(19) as a replacement of bigint in Oracle.

Last thing, what about the AUTO_INCREMENT replacement ? I can see that it was removed from the oracle script but without any SEQUENCE and TRIGGER replacement, is that normal ?

Regards,
Jerome.

**Comment by Abilashini** [comment]
Hi Jerome,

Thanks for reporting the issues in the oracle DB script. We have fixed the above issues with [1]

[1] https://github.com/wso2/carbon-identity-framework/pull/2704
