### ISSUE TITLE
Admin portal URL is not displayed when starting the APIM server

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-apim#7310]
When you start from the APIM server from the command prompt it will display management console, dev portal, and publisher URLs in the command prompt at the end. But it will be good if we can show the admin portal URL as well. 

<img width="1263" alt="Screen Shot 2020-01-22 at 4 30 37 PM" src="https://user-images.githubusercontent.com/10182430/72888922-8f4cf300-3d34-11ea-878b-8a9241dbc4c6.png">

**Comment by tharindu1st** [comment]
This is a limitation from carbon-kernel
