### ISSUE TITLE
Separate endpoint security for sandbox and production endpoints

### ISSUE THREAD

**Issue by chathurace** [wso2/product-apim#7313]
Currently same endpoint security configuration (e.g. basic auth) is applied for both sandbox and production endpoints. However, it is useful to have separate security configurations for these endpoints as they may use different credentials, certificates, etc. Therefore, ideally, these security configs have to be configured per endpoint along with timeouts, suspension state, etc.

**Comment by dushaniw** [comment]
This will be tracked with https://github.com/wso2/product-apim/issues/1547
