### ISSUE TITLE
APIM by default does not include **Access-Control-Expose-Headers: Content-Disposition** for restful apis

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#7317]
### Description:
For the cross origin requests for restful apis, APIM by default does not include **Access-Control-Expose-Headers: Content-Disposition** in the response.

### Steps to reproduce:

- Adding a new document to a published API using [1]
- Upload a file to the document using [2]
- Try to download the file using [3]

Since they are cross origin request, APIM by default does not include **Access-Control-Expose-Headers: Content-Disposition** in the response. Hence, unable to access the Content-Disposition header programmatically.

1. https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/publisher-v1/#/API%20Documents/post_apis_apiId_documents
2. https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/publisher-v1/#/API%20Documents/post_apis_apiIddocumentsdocumentId_content
3. https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/publisher-v1/#/API%20Documents/get_apis__apiId__documents__documentId__content

**Workaround**

Browse to <API-M_HOME>/repository/deployment/server/webapps/api#am#store#v1.0/WEB-INF/beans.xml.
Modify the beans.xml file by adding a new value to the list belonging to the property "allowHeaders" under "<bean id="cors-filter" class="org.apache.cxf.rs.security.cors.CrossOriginResourceSharingFilter">" section as below.

    <bean id="cors-filter" class="org.apache.cxf.rs.security.cors.CrossOriginResourceSharingFilter">
         <property name="allowHeaders">
             <list>
                 <value>Authorization</value>
                 <value>X-WSO2-Tenant</value>
                 <value>Content-Type</value>
             </list>
         </property>
         <property name="allowCredentials" value="true"/>
    </bean>

Restart the server and try out the scenario.

### Affected Product Version:
APIM 300

**Comment by isharac** [comment]
Correction: we need to add Content-Disposition header in exposeHeaders as below.

        <property name="exposeHeaders">
            <list>
                <value>Content-Disposition</value>
            </list>
        </property>
