### ISSUE TITLE
/publisher stuck at You will be redirected to /publisher/services/auth/login with blank loading page

### ISSUE THREAD

**Issue by manuel-di-iorio** [wso2/product-apim#7321]
### Description:
On a server (so not in localhost), after a fresh installation of the API Manager, I changed in the `deployment.toml` configuration file the hostname to the machine IP address.
While /carbon works well, the /publisher and /devportal are not responding and remain in pending state, until the server closes the connection with a timeout.

The affected APIs seem to be services/auth/login and /devportal/services/configs (so all /services routes)

Example config:
[server]
hostname = "ip etc.." (changed from the default localhost)

Screen:
![Screen](https://i.snipboard.io/CeT0fc.jpg)

If this is a configuration problem, what else need to be changed ?

### Affected Product Version:
3.0.0

### Environment details (with versions):
- OS: Ubuntu 18.04
- Client:
- Env (Docker/K8s):

**Comment by manuel-di-iorio** [comment]
Solved. The port 9443 was closed for external requests directly to the server IP. Hope this can help someone else.

**Comment by amritaramnauth** [comment]
How was this solved? I'm having same issue and not sure how to continue...

**Comment by amritaramnauth** [comment]
Can you provide more details on the solution? @manuel-di-iorio I'm having a similar issue when fronting with nginx proxy.

**Comment by manuel-di-iorio** [comment]
@amritaramnauth Sure. I needed to allow requests (azure firewall in my case) from the server IP on the port 9443. Pratically WSO2 must be able to call itself on that port

**Comment by samseiitra** [comment]
Hello, I have the same problem with nginx fronting.
9443 is open between Nginx and WSO APIM Server
The problem still ....... 
publisher and /devportal are not responding and remain in pending state, until the server closes the connection with a timeout.

Could you help me please ? 

Thanks

**Comment by amritaramnauth** [comment]
@SamWso2 check your server if port 9443 is opened for external requests.

**Comment by SamWso2** [comment]
The port 9443 is open between nginx and my server Wso2

**Comment by SamWso2** [comment]
I have devoprtal site from external
When I sign in it's not responding

**Comment by eric-sf** [comment]
If you changed admin password, you need to change it in config file as well.

**Comment by SamWso2** [comment]
It's not a problem of changed password. By internal it's work fine
It's not repondinf (/devportal and /publisher after I log in.
Thanks
