### ISSUE TITLE
Thumbnail image flickers when loading APIs

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7324]
### Description:
When a custom API thumbnail image is added, There is a slight delay in loading the image

### Steps to reproduce:
- Create an API
- Upload a custom image
- Use network throttling and goto APIs listing page

![Jan-26-2020 00-11-04](https://user-images.githubusercontent.com/3313885/73125767-9ee86800-3fd0-11ea-9746-fa23998f9706.gif)

### Affected Product Version:

- APIM 3.1.0-Alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chanaka3d** [comment]
This issue is fixed with the following PR.

https://github.com/wso2/carbon-apimgt/pull/8119
