### ISSUE TITLE
Provisioning jar is not packed with APIM 3.0.0

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#7328]
### Description:
org.wso2.carbon.identity.provisioning_5.14.97.jar should be packed in /dropins directory for identity provisioning to work in APIM 3.0.0

**Comment by tharindu1st** [comment]
fixed in https://github.com/wso2/product-apim/blame/master/modules/p2-profile/product/pom.xml#L455-L457

**Comment by isharac** [comment]
Fixed in APIM 3.2.0
