### ISSUE TITLE
Interactive tutorial is missing in version 3.0

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-apim#7330]
In APIM 2.6.0, there was an APIM walkthrough interactive tutorial, which helped new users to catch up APIM usage easily. But that feature is missing in 3.0.

**Comment by tmkasun** [comment]
Thanks for reporting this feature request,
We have discussed this feature in here https://github.com/wso2/product-apim/issues/1832 hence closing this issue

**Comment by tmkasun** [comment]
Will keep this issue open until this feature gets implemented.
