### ISSUE TITLE
Scope validation is not happening for Implicit Grant flow.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-apim#7331]
### Description:
In the authorization code grant flow, we have proper scope validation happening based on roles. But when the implicit flow is executed scope validation is not happening and all the requested scopes are attached to the token.

### Steps to reproduce:
Use this command to generate an access token using the implicit grant.
https://localhost:8243/authorize?response_type=token&client_id=y4m0YV1kbSfdKxh4jh16NCf0Awka&redirect_uri=http://example.com&nonce=abc&scope=<invalidScope>

Introspect with,
curl -k -u admin:admin -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 'token=a805f69f-057a-352f-a580-da2bd59f00c5' https://localhost:9443/oauth2/introspect
Gives the invalid scope attached to the token.

### Affected Product Version:
2.5.0

### Environment details (with versions):
- OS: Linux
- Client:
- Env (Docker/K8s):

### Further troubleshooting details:
It seems like in the implicit flow when it goes through the TokenResponseTypeGrantHandler scope validation happens through https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/util/APIManagerOAuthCallbackHandler.java#L63-L72 which sets all the requested scopes as approved.

But for authorization code grant it goes through the grant handler which has ScopeIssuer to perform scope validation. If this same logic can be used in the response type handler for the implicit grant, we will be able to handle the concern.

**Comment by dushaniw** [comment]
Need to fix in WUM 2.2.0 as well.
