### ISSUE TITLE
Allow to enable or disable default application in developer portal

### ISSUE THREAD

**Issue by harsha89** [wso2/product-apim#7333]
### Describe your problem(s)
When subscriber or the application developer login to the portal, API manager creates a default application. It's required to provide a way to enable or disable on creating this application as some users doesn't want this.

**Comment by tharindu1st** [comment]
We can disable DefaultApplication Creation on user sign into the dev portal by add following configuration into the tenant-config.json
"DisableDefaultApplicationCreation" : true

**Comment by menakaj** [comment]
Fixed hence resolving.
