### ISSUE TITLE
Passing enduser attributes via JWT doesn't work following the guide.

### ISSUE THREAD

**Issue by Pelellone** [wso2/product-apim#7335]
### Description:
I have Api Manager 3.0.0 configured and working on default ports. 
Just this product, no IS as additional service. I'm managing users with carbon's suite on apim.
Following this guide: https://apim.docs.wso2.com/en/latest/Learn/APIGateway/PassingEndUserAttributesToTheBackend/passing-enduser-attributes-to-the-backend-using-jwt/#configuring-jwt
I'm trying to pass the user informations via JWT Token. 

Here's my configuration block about JWT:
[apim.jwt]
enable = true
encoding = "base64" # base64,base64url
generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
claim_dialect = "http://wso2.org/claims"
header = "X-JWT-Assertion"
signing_algorithm = "SHA256withRSA"
enable_user_claims = true
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

When I receive the JWT Token and decode it, I got: 
`{
  "sub": "Daniele@carbon.super",
  "backendJwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlpqUm1ZVE13TlRKak9XVTVNbUl6TWpnek5ESTNZMkl5TW1JeVkyRXpNamRoWmpWaU1qYzBaZz09In0=.eyJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9vcmdhbml6YXRpb24iOiJQd0MgSXRhbHkiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC91c2VybmFtZSI6IkRhbmllbGUiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9yb2xlIjpbIkludGVybmFsXC9zdWJzY3JpYmVyIiwiQXBwbGljYXRpb25cL0RhbmllbGVfLkRBTklFTEUuIEpXVCBEZW1vX1BST0RVQ1RJT04iLCJJbnRlcm5hbFwvZXZlcnlvbmUiLCJBcHBsaWNhdGlvblwvRGFuaWVsZV8uREFOSUVMRS4gRGVtbyBhcHBsaWNhdGlvbl9QUk9EVUNUSU9OIl0sImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2V4dGVybmFsaWQiOiI3ODY0NjEiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hcHBsaWNhdGlvbnRpZXIiOiJVbmxpbWl0ZWQiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9rZXl0eXBlIjoiUFJPRFVDVElPTiIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL21vYmlsZSI6IjM2NjQ2NTAxMzgiLCJpc3MiOiJ3c28yLm9yZ1wvcHJvZHVjdHNcL2FtIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb25uYW1lIjoiLkRBTklFTEUuIEpXVCBEZW1vIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZW5kdXNlciI6IkRhbmllbGVAY2FyYm9uLnN1cGVyIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZW5kdXNlclRlbmFudElkIjoiLTEyMzQiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9naXZlbm5hbWUiOiJEYW5pZWxlIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb25VVUlkIjoiZjFlZTQyYmEtY2NmZS00MGU2LTg1ODUtY2NiMGE1N2I0ZjQ3IiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvdGVsZXBob25lIjoiMzY2NDY1MDEzOCIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2ltIjoiaW1jaGUiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9jb3VudHJ5IjoiSXRhbHkiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9zdWJzY3JpYmVyIjoiRGFuaWVsZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2VtYWlsYWRkcmVzcyI6ImRhbmllbGUucm9zc2luaUBwd2MuaXQiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9sYXN0bmFtZSI6IlJvc3NpbmkiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC91cmwiOiJ3d3cuZ29vZ2xlLml0IiwiZXhwIjoxNTgwMTM1MTAwLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hcHBsaWNhdGlvbmlkIjoiNyJ9.fOPCcbcbaQbfYbUcyIk4tIjYs9lnez5S1NWtBgVdHNpLmQix6ZsREs0_JsKffUT5BpB1exFRlFytl2xh2QRXFun6e6d6TkwBhkLr5ciIUwBd56PlTpS-lMK3MvqO5zSVh_jRpdL90jjV4fj9Z9Qui_SU3lKyUp20tXTs2ip8P_fgAyIjdQWKXnHIxV9r3r0xNQzIHaz0sbnqnIsPaDr_1LwckhLcB1yqoSw4xFNxKdg6X8-HUqVQyYUauoYizOiX3ZfL1L_jILLjplKXDl5lSLyAL4PfN-oWbL-9fKVQQ796vH4sdOJQGoVz5VRUebs4_srfe22Cv7rU0H8lx59hyQ==",
  "iss": "https://10.245.104.108:9443/oauth2/token",
  "tierInfo": {
    "Unlimited": {
      "stopOnQuotaReach": true,
      "spikeArrestLimit": 0,
      "spikeArrestUnit": null
    }
  },
  "keytype": "PRODUCTION",
  "subscribedAPIs": [
    {
      "subscriberTenantDomain": "carbon.super",
      "name": "DemoAPI",
      "context": "/demo/1",
      "publisher": "admin",
      "version": "1",
      "subscriptionTier": "Unlimited"
    }
  ],
  "aud": "http://org.wso2.apimgt/gateway",
  "application": {
    "owner": "Daniele",
    "tier": "Unlimited",
    "name": ".DANIELE. JWT Demo",
    "id": 7,
    "uuid": null
  },
  "scope": "am_application_scope default",
  "consumerKey": "mxD5tziO2egtw11i8Yla0iRJeS0a",
  "exp": 1580137800,
  "iat": 1580134200,
  "jti": "9658c184-e6a6-48ba-b8ea-7e6aa473e9af"
}`

and no informations about the user. 

### Affected Product Version:
wso2am 3.0.0

**Comment by tharindu1st** [comment]
Hi @Pelellone ,
By looking at the decoded payload we could see **backendJwt** element available in JWT which contains the base64 encoded backend JWT token. 

Didn't you able to get the backend JWT token into your backend as expected ?

**Comment by isharac** [comment]
Closing as the backendJwt contains user claims.
You may reopen if need any further assistance.
