### ISSUE TITLE
CURL not updating properly in POST

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#7336]
In the swagger console, when using POST, the "Payload" and "string" is fixed and does not update with the proper values within the curl as shown in the screenshot below. The curl should be updated properly with the user entered values. This is the scenario when using GraphQL.

![WSO2 APIM Developer Portal](https://user-images.githubusercontent.com/30475839/71084895-472e3400-21bc-11ea-8ba8-f0af1fc91519.png)

**Comment by tharikaGitHub** [comment]
This issue is reproducible in APIM 3.1.0-Beta for a normally created API.

![image](https://user-images.githubusercontent.com/8557410/75218060-0efc3080-57bf-11ea-982b-b10c82084314.png)
