### ISSUE TITLE
Ability to define mandatory properties for APIs

### ISSUE THREAD

**Issue by chathurace** [wso2/product-apim#7341]
If an organization need to associate addition information with APIs, current approach is to use properties. However, these properties are optional, so that API publishers can ignore associating relevant information, which may affect organization's API governance. Therefore, it is useful to have ability define mandatory properties for APIs, so that API publishers are enforced to fill those before publishing.

Admins should be able to define mandatory API properties in the admin portal. API Publisher displays these mandatory properties in the properties areas and does not allow the API to be published until those are filled.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/12072
