### ISSUE TITLE
[AM-3.0] Only 25 APIs are listed under the Subscription Management in API Dev portal

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#7342]
**Steps to reproduce:**
1. Create more than 25 APIs in the Publisher portal 
2. Go to the dev-portal and click on one of the applications.
3. Navigate to the "Subscriptions".
4. Under the "Subscription Management" tab, you can see only 25 APIs are listed to subscribe.

![image](https://user-images.githubusercontent.com/28176167/73242491-226da900-41cb-11ea-9a7d-d9dc2ff975fd.png)

**Product version:**
APIM 3.0

**Comment by chanaka3d** [comment]
Fixed for 3.1.0 with the following PR in the UI level.

https://github.com/wso2/carbon-apimgt/pull/8158

It's better if we can fix this from the Rest API level.

**Comment by Krishanx92** [comment]
Reduce the priority since this is fixed in UI level.

**Comment by Arshardh** [comment]
Closing this as this fix have been shipped in wum and added to master
