### ISSUE TITLE
[3.1.0 Migration] Add TENANT_DOMAIN VARCHAR(255) column to AM_SYSTEM_APPS table

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7348]
### Describe your problem(s)
Required by https://github.com/wso2/carbon-apimgt/pull/8110/files

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim/issues/7347

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/product-apim/pull/7766
