### ISSUE TITLE
The API files get undeployed, when the NFS server goes down.

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#7353]
### Description:
When the /server directory is mounted with NFS, all the APIs are undeployed from the gateway once the NFS Server goes down. This is due to the hot undeployment feature where missing files will be undeployed by running a scheduler task. The two scenarios where a single file gets deleted and the whole directory goes down due NFS failures should be distinguished and we should stop hot undeployment when the whole directory dissappears.

### Steps to reproduce:

- Mount the /server directory with NFS 

- Create an API and invoke.

- Stop the NFS server and try to invoke the API.

### Affected Product Version:
APIM 2.1

**Comment by isharac** [comment]
Fix in 1.6.1.wso2v41 https://github.com/wso2-support/wso2-axis2/pull/194
