### ISSUE TITLE
API Availability Statistics are not displayed in Tenants

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#7357]
### Description:
In a multitenanted environment, tenant api availability statistics cannot be viewed.

### Steps to reproduce:
1. Enable analytics in apim 2.6.0
2. Create a tenant, login to publisher through a tenant user and create an API.
3. Invoke the API for several times.
4. Go to Analytics -> API Availability in admin portal.
5. No data is available.

### Affected Product Version:
APIM 2.6.0

### Environment details (with versions):
- OS: ubuntu 16.04
- Client:
- Env (Docker/K8s):

---
#### Related Issues:
Be mindful not to break functionality fixed in https://github.com/wso2/product-apim/issues/5917 when fixing this issue.

**Comment by AnuGayan** [comment]
Fixed in latest version
