### ISSUE TITLE
Cannot set whether a parameter is required

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#7363]
### Describe your problem(s)
When creating an API, If a parameter is created for the resource, There is no option to make it mandatory or not. Instead it will always set it as required NO.

<img width="1396" alt="Screenshot 2020-01-31 at 09 59 17" src="https://user-images.githubusercontent.com/11259401/73512631-5f76ad00-4410-11ea-8a8c-15a75cca4543.png">

### Describe your solution
Can add a button to make it required or not.

**Comment by Sarangan0219** [comment]
In 3.1.0 this issue no longer exists.Thus we can close this issue.

![Screenshot from 2020-03-03 13-52-58](https://user-images.githubusercontent.com/60866295/75756288-6ae22e80-5d56-11ea-8ec4-e1f892bd2069.png)
