### ISSUE TITLE
Error updating credentials for user admin : org.wso2.carbon.user.core.UserStoreException: Error occurred while updating string values to database.

### ISSUE THREAD

**Issue by loeb-ift** [wso2/product-apim#7365]
### Description:

Changing User Passwords in the Carbon H2 Database fail 
1.Edit  /opt/wso2am-3.1/repository/conf/deployment.toml change password form {admin/admin} to {admin/$NEWPASSWORD}

2.Start the service and login web carbon-portal  to change password on web 
carbon/user/change-passwd.jsp
Change New Password For User: admin
 {change password value in mysql (shared_db. UM_USER . UM_USER_PASSWORD}

3.Change the Local H2 carbondb password with script as 
`bash chpasswd.sh --db-url jdbc:h2:/opt/wso2am-3.1/repository/database/WSO2CARBON_DB.mv.db  --db-username "wso2carbon" --db-password "wso2carbon" --username "admin" --new-password "{$NEWPASSWORD}"`

`
setup:
    [mkdir] Created dir: /opt/wso2am-3.1/repository/lib
     [copy] Copying 66 files to /opt/wso2am-3.1/repository/lib
    [mkdir] Created dir: /opt/wso2am-3.1/tmp/setup
    [unzip] Expanding: /opt/wso2am-3.1/repository/components/plugins/org.wso2.carbon.security.mgt.stub_5.16.24.jar into /opt/wso2am-3.1/tmp/setup
    [unzip] Expanding: /opt/wso2am-3.1/repository/components/plugins/org.wso2.carbon.security.mgt.ui_5.16.24.jar into /opt/wso2am-3.1/tmp/setup
    [unzip] Expanding: /opt/wso2am-3.1/repository/components/plugins/org.wso2.carbon.security.mgt_5.16.24.jar into /opt/wso2am-3.1/tmp/setup
   [delete] Deleting directory /opt/wso2am-3.1/tmp/setup
    [unzip] Expanding: /opt/wso2am-3.1/repository/components/plugins/h2_1.4.199.wso2v1.jar into /opt/wso2am-3.1/repository/lib
    [unzip] Expanding: /opt/wso2am-3.1/repository/components/plugins/org.wso2.carbon.utils_4.6.0.alpha3.jar into /opt/wso2am-3.1/repository/lib
     [copy] Copying 4 files to /opt/wso2am-3.1/repository/lib
     [move] Moving 30 files to /opt/wso2am-3.1/repository/lib
   [delete] Deleting directory /opt/wso2am-3.1/repository/lib/META-INF
   [delete] Deleting directory /opt/wso2am-3.1/repository/lib/org

BUILD SUCCESSFUL
Total time: 2 seconds

Error updating credentials for user admin : org.wso2.carbon.user.core.UserStoreException: Error occurred while updating string values to database.

`
### Affected Product Version:
WSO2 APIM 3.1 alpha

### Environment details (with versions):
- OS: Linux wso2am-314 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
- Env :single server

---
#### Suggested Labels:
Passwords,Security

**Comment by tharikaGitHub** [comment]
@loeb-ift You can change the password of the super admin user by following the documentation [1]. Please try that and see if you can change the passwords successfully.

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/LoginsAndPasswords/maintaining-logins-and-passwords/#changing-the-super-admin-credentials

**Comment by tharikaGitHub** [comment]
@loeb-ift did you manage to fix this issue by following the documentation?

**Comment by loeb-ift** [comment]
Yes I did fix the issue by following the doc.
It looks like had nothing with the carbondb!?
Is chpasswd.sh not necessary at 3.1!?
