### ISSUE TITLE
Create J2 template for n-http.properties file

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-apim#7368]
### Describe your problem(s)
Currently, there is no J2 Template for conf/n-http.properties file. 
Needs to introduce this so that only doployment.yaml file contains the custom configuration in n-http.properties file as well.

### Describe your solution
Introduce new J2 template.
Add default values to default.json

### How will you implement it

---

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7228
