### ISSUE TITLE
Parameter column is not visible when the API created by importing swagger file - 

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#7373]
### Description:
 If creating an API by using the swagger definition and tried to add the parameter for the created resources. Then the required parameter section was not available.
![NoParameterSection](https://user-images.githubusercontent.com/15210142/73536790-c6b25280-444c-11ea-9b65-dab2e755c6f5.png)

### Steps to reproduce:
1. Create an API using an existing swagger file (the swagger version is 2.0.0)
2. Edit and try to add parameters to API resources 
3. Will not see the parameter section to add parameters
 
### Affected Product Version:
APIM 3.0.0

**Comment by tmkasun** [comment]
We need to support Swagger 2.0 definitions in Publisher Resources page
