### ISSUE TITLE
WSO2 store not working after selecting API

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7381]
### Description:
When I login to wso2 store and click on recently added API, it should open api page which allow me to browse "overview", "API console", "documentation" and "SDKs". Instead my store web page is crashing with the error, such thing happen very first time.

### Steps to reproduce:
Login to WSO2 store https://xxx.xxx.xxx/store

Click on recently added API 

### Affected Product Version:

2.2.0
### Environment details (with versions):
- OS: RHEL 7.0
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
Closing Since the issue has been stale for a long time.
