### ISSUE TITLE
Improve information tags in Publisher

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7386]
### Describe your problem(s)

1. The following (per resource security enable/disable option) is confusing what happens when disabled. It removes all application level securities I believe.

<img width="515" alt="Screenshot 2020-02-05 at 10 09 24" src="https://user-images.githubusercontent.com/17607322/73811763-56b31c00-4800-11ea-8c2a-7724869d5cd6.png">

2. The following(Application level security in Runtime configurations) mentions about a mutual SSL. Which is a transport level security. 
<img width="654" alt="Screenshot 2020-02-05 at 10 09 44" src="https://user-images.githubusercontent.com/17607322/73811560-c4ab1380-47ff-11ea-9bd2-6b89edeccfef.png">

### How will you implement it

---
#### Suggested Labels:

3.1.0 publisher

**Comment by erangatl** [comment]
> ### Describe your problem(s)
> 1. The following (per resource security enable/disable option) is confusing what happens when disabled. It removes all application level securities I believe.
> 
> <img alt="Screenshot 2020-02-05 at 10 09 24" width="515" src="https://user-images.githubusercontent.com/17607322/73811763-56b31c00-4800-11ea-8c2a-7724869d5cd6.png">
> 

@AmaliMatharaarachchi it disables security, isn't it intuitive? 
@tmkasun WDYT?

**Comment by AmaliMatharaarachchi** [comment]
@erangatl  I believe we need to mention that disabling removes all transport/application security for the resource. Enabling means whatever the security types(transport/application) defined at the API level would be there. It doesn't necessarily mean it needs an oauth2 token. It can be just mutual SSL. AFAIK. See, this info tag is confusing.

**Comment by erangatl** [comment]
+1 yes we need to revise the help text.
