### ISSUE TITLE
Mandate HTTPS transport if mutual SSL is in use

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7398]
### Description:

In publisher portal, mandate the HTTPS transport type if a user wants to use Mutual SSL security type for their API

![image](https://user-images.githubusercontent.com/3313885/73855695-7119e380-485a-11ea-849f-ae45031218dc.png)

**Comment by tmkasun** [comment]
@ isuruh15 FYI  😃

**Comment by isuruh15** [comment]
REST API validation should be added to this. 
If a user chose an invalid combination of options and save, the response is saying successfully updated and default options have been selected.
