### ISSUE TITLE
Remove webpack externals imports in portal data layer

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7399]
### Describe your problem(s)

Remove webpack externalized imports in `data` layer implementations, supporting them to import from external projects without any issue.

i:e [AuthManager](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx#L22)

usage is: These data handler implementations can be used in external React base projects like external API portals to avoid duplicating code.
 
### Describe your solution/ suggestion

- Move externalized imports to React container components and pass them down to data layer via function args

**Comment by hasuniea** [comment]
This affect while sharing the store components with the publisher through lerna.

ERROR in /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx
Module not found: Error: Can't resolve 'Settings' in '/Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data'
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Utils.jsx 21:0-32 230:108-116 234:85-93 239:112-120 243:114-122
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/api.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/index.js
 @ ./source/src/app/components/Apis/Details/TestConsole/TestConsole.jsx
 @ ./source/src/app/components/Apis/Details/index.jsx
 @ ./source/src/app/components/Apis/Apis.jsx
 @ ./source/src/app/ProtectedApp.jsx
 @ ./source/src/Publisher.jsx
 @ ./source/index.jsx

ERROR in /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx
Module not found: Error: Can't resolve 'Settings' in '/Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data'
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/AuthManager.jsx 20:0-32 91:37-45 127:35-43 244:60-68 271:54-62 290:16-24 331:60-68
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Resource.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/index.js
 @ ./source/src/app/components/Apis/Details/TestConsole/TestConsole.jsx
 @ ./source/src/app/components/Apis/Details/index.jsx
 @ ./source/src/app/components/Apis/Apis.jsx
 @ ./source/src/app/ProtectedApp.jsx
 @ ./source/src/Publisher.jsx
 @ ./source/index.jsx

ERROR in /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClient.jsx
Module not found: Error: Can't resolve 'Settings' in '/Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data'
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClient.jsx 20:0-32 153:32-40 157:30-38
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/APIClientFactory.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/data/Application.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/app/components/Apis/Details/ApiConsole/TryOutController.jsx
 @ /Users/hasunie/RD/UI/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/devportal/source/src/index.js
 @ ./source/src/app/components/Apis/Details/TestConsole/TestConsole.jsx
 @ ./source/src/app/components/Apis/Details/index.jsx
 @ ./source/src/app/components/Apis/Apis.jsx
 @ ./source/src/app/ProtectedApp.jsx
 @ ./source/src/Publisher.jsx
 @ ./source/index.jsx
