### ISSUE TITLE
Support saving markdown documents as HTML

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#7401]
### Describe your problem(s)
When a Markdown document is added(for both sourceType inline and markdown), the content is saved as a text string. As an improvement, we could support converting the Markdown content to HTML and saving the document as HTML.

**Comment by tmkasun** [comment]
Why do we need to convert it and save? 
How it will be different from rendering HTML when presenting the MD

**Comment by tmkasun** [comment]
Hi

I have a few concerns regarding your requirements,

1.  Is this intended to add API documents in Markdown ( MD ) format to APIs via a REST API ?
2.  Do we want to show those documents in MD format in the API Manager Developer portal (earlier called as Store) ?

If Yes to both,

We can use API Manager 3.x new REST API (it's V1), Add Document API and Update document content API to add a markdown type document and update its content.

You can find the REST API documentation in [here](http://wso2.github.io/carbon-apimgt/apidocs/publisher/v1/#!/operations#APIDocuments#apisApiIdDocumentsPost)

**Comment by tmkasun** [comment]
Here is a sample request to add markdown type document and its content

Add document
```
curl 'https://localhost:9443/api/am/publisher/v1/apis/febbd9f2-1a55-46ab-9c5b-b78fb0f8250a/documents' -H 'authorization: Bearer XXXXXXXX -H 'Content-Type: application/json'  --data-binary '{"name":"sample_doc","type":"HOWTO","summary":"This is a sample Markdown Document","sourceType":"MARKDOWN","visibility":"API_LEVEL","sourceUrl":"","otherTypeName":null,"inlineContent":""}'
```


Add document content

```
curl 'https://localhost:9443/api/am/publisher/v1/apis/febbd9f2-1a55-46ab-9c5b-b78fb0f8250a/documents/48fc7d70-ed66-4595-99f0-4222fb440ffe/content' -H 'authorization: Bearer XXXXXXXX' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVB39jwIVOflzaB3x' --data-binary $'------WebKitFormBoundaryVB39jwIVOflzaB3x\r\nContent-Disposition: form-data; name="inlineContent"\r\n\r\n# Enter your markdown content\n\nThis is a sample document content\r\n------WebKitFormBoundaryVB39jwIVOflzaB3x--\r\n' 
```
