### ISSUE TITLE
HostNameVerifier allowed parameter in deployment.toml not reflected in axis2.xml -WSO2apim 3.0.0

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7402]
Host name verifier parameter in deployment.toml file is not reflected in axis2.xml file.
Steps to reproduce.
Gateway component  -

1.Add the 
[transport.passthru_https.sender.parameters]
HostnameVerifier = "AllowAll"  in deployment.toml file.
2. Check the axis2.xml file.
3.It is not reflecting the changes.

**Comment by menakaj** [comment]
https://github.com/wso2/product-apim/issues/6731
