### ISSUE TITLE
Unclassified Error for Application with JWT token type in store -APIM 3.0.0

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7405]
Getting an error as "Unclassified error" for an application having default token type JWT.
steps to reproduce.

1. Create an application with default JWT token type in devportal.
2. Register API  to the application.
3. try to consume the API with default JWT token in devportal.
4. Getting error as "Unclassified error".

**Comment by afshinsharafi** [comment]
I Have The Same Problem!!!!!

**Comment by tharindu1st** [comment]
This is no longer applicable since all applications are JWT applications
