### ISSUE TITLE
When generating a REST API from a SOAP backend it does not generate all the required parameters for the SOAP operations 

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-apim#7408]
### Description:
When generating a REST API from a SOAP backend it does not generate all the required parameters for the SOAP operations.

If you try to generate a REST API for the WSDL provided then for the "doLogin" SOAP operation which takes in 2 parameters (Login and Password) only one parameter will be generated.

wsdl: https://soap.proofhq.com/soap?wsdl

### Steps to reproduce:

1. Generate a REST API from the WSDL given above from the API Publisher
2. Check the parameters in the "doLogin" SOAP operation from the swagger definition, you can observe that only one parameter has been generated. (whereas it should have 2)

### Affected Product Version:
3.0.0 and 3.1.0 Alpha

### Environment details (with versions):
- OS: Ubuntu 19.04

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7130
