### ISSUE TITLE
When generating a REST API from a SOAP backend the XML payload generated contains an extra XML tag for all the SOAP operations

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-apim#7409]
### Description:
When generating a REST API from a SOAP backend the XML payload generated contains an extra XML tag for all the SOAP operations. The extra XML tag is the request object.

wsdl: https://soap.proofhq.com/soap?wsdl

Request payloads for the "doLogin" operation is as follows:

_Correct payload_ 
<payloadFactory description="transform" media-type="xml">
         
  <format>
               
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="https://soap.proofhq.com/">
                     
      <soapenv:Header />
                     
      <soapenv:Body>
                           
        <soap:doLogin>
                                 
          <Login>??</Login>
                                 
          <Password>??</Password>
                             
        </soap:doLogin>
                       
      </soapenv:Body>
                 
    </soapenv:Envelope>
           
  </format>
     
</payloadFactory>

_Generated payload_
                       
    <soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:web="https://soap.proofhq.com/">
                             
      <soapenv:Header />
                             
      <soapenv:Body>
                                   
        <web:doLogin>
                                         
          <web:doLoginRequest>
                                               
            <web:Password>$1</web:Password>
                                           
          </web:doLoginRequest>
                                     
        </web:doLogin>
                               
      </soapenv:Body>
                         
    </soapenv:Envelope>
             

### Steps to reproduce:
1. Generate a REST API from the WSDL given above from the API Publisher
2. Go to resources in the API and expand the "doLogin" resource
3. Check the mediation given for the inflow. You can see that it has an extra XML tag enclosing the parameters

### Affected Product Version:
3.0.0 and 3.1.0 Alpha

### Environment details (with versions):
- OS : Ubuntu 19.04

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7130
