### ISSUE TITLE
Multiple Version of API is not working woth toml file changes WSO2 APIM 3.0.0

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7415]
Multiple Version of API is not working with deployment.toml file changes WSO2 APIM 3.0.0.
Steps
1.Added below configuration in Devportal to display mutiple versions of API.
2.Getting an error while starting the server.

[apim.devportal]
display_multiple_versions = true

**Comment by AmaliMatharaarachchi** [comment]
Did you try this in a WUM updated pack? I believe we fixed this with https://github.com/wso2/product-apim/issues/6710

**Comment by Krishanx92** [comment]
Fix: https://github.com/wso2/carbon-apimgt/pull/7828/files
