### ISSUE TITLE
Cannot add a new handler to the registry.xml through toml

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-apim#7420]
### Description:
The requirement to add a new handler to regsitry.xml is not through the toml templates. Hence users are not able to add more handlers to the file. #7228 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
tagging: https://github.com/wso2/product-apim/issues/7228

**Comment by tharindu1st** [comment]
This was not needed since we removed org.wso2.carbon.registry.extensions.handlers.WSDLMediaTypeHandler at 2.5.0 version
