### ISSUE TITLE
[Publisher] Add link to report in 42Crunch platform

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-apim#7424]
### Describe your problem(s)

![image](https://user-images.githubusercontent.com/32578617/74131694-f0b50300-4c0a-11ea-8733-75aef91d5336.png)

It would be useful if a link to the report in 42Crunch platform was shown in the UI for the API Security Audit feature

### Describe your solution

Adding a link in the UI under the Audit Score and Summary Section

### How will you implement it

---
#### Suggested Labels:

3.1.0
Type/New Feature

#### Suggested Assignees:

@sanjulamadurapperuma

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8165
