### ISSUE TITLE
Swagger generation is incomplete when simple content has 

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7432]
### Description:
Some model definitions are missed when simple content has "." in its name.
For example:
```
<xsd:complexType name="test">
        <xsd:simpleContent>
          <xsd:extension base="test.Content">
            <xsd:attribute name="code" type="code"/>
          </xsd:extension>
        </xsd:simpleContent>
</xsd:complexType>
```
### Affected Product Version:
2.6.0, 3.1.0

**Comment by ruks** [comment]
Have a "." character in an element name is not a best practice. But it is better to improve this to generate API even though "." is defined.

**Comment by vithu30** [comment]
This issue is only reproducible when the simple content extension name contains ".". For other complex types it is working fine.
