### ISSUE TITLE
Active-Active deployment documentation improvement

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#7434]
### Description:
In the API-M 2.6.0 Active-Active deployment docs, step 6: configuring throttling, the example provided has the loopback adapter(127.0.0.1) as the host and the ports have offsets. It will be more clear and comprehensive for the example to have the node IP as host(ex: node-1-ip-address) and the default ports as the port, because we refer to the nodes as node 1 and node 2 throughout the doc.

### Content Positioning in Documentation:
- Link:
https://docs.wso2.com/display/AM260/Configuring+an+Active-Active+Deployment#ConfiguringanActive-ActiveDeployment-Step6-ConfigureThrottling

**Comment by sanethmaduranga** [comment]
Hi Team,

The sample configuration mentioned under the '**Step 6 - Configure Throttling**' is also needed to be corrected as below. 

```
    <ThrottlingConfigurations>
        <EnableAdvanceThrottling>true</EnableAdvanceThrottling>
        <TrafficManager>
            <Type>Binary</Type>
            <ReceiverUrlGroup>{tcp://<node1-hostname>:<node1-port>},{tcp://<node2-hostname>:<node2-port>}</ReceiverUrlGroup>
            <AuthUrlGroup>{ssl://<node1-hostname>:<node1-port>},{ssl://<node2-hostname>:<node2-port>}</AuthUrlGroup>
            <Username>${admin.username}</Username>
            <Password>${admin.password}</Password>
        </TrafficManager>
        <DataPublisher>
            <Enabled>true</Enabled>
             .......
```
