### ISSUE TITLE
API documents not visible when API is made public from the restricted by roles.

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#7448]
### Description:
API documents not visible when API is made public from the restricted by roles.

### Steps to reproduce:
- Created an API.
- Set(Restrict) visibility on the store only for a set of roles and updated the API.
- Then added documentation via publisher console.
- After adding the documentation, updated the API by setting the visibility on the store as public.
- But still, the particular document that we added previously, is not available publicly.

### Affected Product Version:
APIM-2.1.0 & APIM-2.6.0

**Comment by vithu30** [comment]
This issue is reproducible for API Products.

**Comment by tharindu1st** [comment]
fixed
