### ISSUE TITLE
Improvement to make the Scope Issuer extendable

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#7450]
### Describe your problem(s)
The scope issuer is currently not extendable, which make it difficult to add any custom logic to the Scope Issuer.

### Describe your solution
Making the Scope Issuer extendable through a config in a backward compatible way.

### How will you implement it
Making the Scope Issuer extendable through a configuration in api-manager.xml, when the config is not available it will pick the default scope issuer and will work in the default way.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8248
