### ISSUE TITLE
[Try-it] Cannot invoke APIs with enum field types

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7451]
### Description:
Swagger UI doesn't seem to allow selecting a value for the parameters with a list of enum values.

### Steps to reproduce:
1. Create an API using http://petstore.swagger.io/v2/swagger.json
2. Try to invoke `GET ​/pet​/findByStatus` resource

We are not allowed to select the value for the status field from the list of items on the box. 
![image](https://user-images.githubusercontent.com/1591316/74306734-63e48380-4d89-11ea-8340-4b61c8d6ed80.png)

**Comment by dushansilva** [comment]
this seems to be fixed in public branch therefore closing issue
