### ISSUE TITLE
Mutual SSL Transport security for API

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7453]
### Description:

UI allows Mutual ssl enabled https disabled.

### Steps to reproduce:
<img width="724" alt="Screenshot 2020-02-13 at 13 26 28" src="https://user-images.githubusercontent.com/17607322/74412946-797aab80-4e64-11ea-9e58-c2a33afe0723.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Duplicate of https://github.com/wso2/product-apim/issues/7398 hence closing the issue
