### ISSUE TITLE
Improve JWT Validation from multiple JWT Token issuers

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#7467]
### Describe your problem(s)
When JWT retrieved from Multiple Identity providers Gateway should able to validate the JWT and map the Relevant Claims
### Describe your solution
1. Retrieve the Issuer from Given JWT.
2. Retrieve the JWKS from the URL given from Identity Provider.
3. Validate the JWT signature against that.
4. Transform the JWT from Map Claims.
5. Validate JWT claims from JWT Validator against required fields

**Comment by bhathiya** [comment]
How does step 5 work?

**Comment by tharindu1st** [comment]
required fields in the sense subscription consumer key scopes
