### ISSUE TITLE
Product download page shows only latest version

### ISSUE THREAD

**Issue by ankit-agrawal07** [wso2/product-apim#7474]
### Description:
The download page does not have link to download earlier versions on APIM.
https://wso2.com/api-management/#

It will be nice to have other versions on download page. A drop-down to choose product version would be nice.

### Content Positioning in Documentation:

- Link: https://wso2.com/api-management/#

- Heading (& Step):

- Any other reference:

---

**Comment by pubudu538** [comment]
Hi,

When you click download and scroll down, you can find a section called other resources. There you can find the previous releases section. Otherwise, use [https://wso2.com/api-management/previous-releases/](https://wso2.com/api-management/previous-releases/)

Thank you!
Pubudu.
