### ISSUE TITLE
Required scopes are missing in DevPortal API Try-It

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#7479]
### Description:

Attached the below scope from publisher.

![image](https://user-images.githubusercontent.com/1591316/74654939-6c85f100-51b1-11ea-9fe1-a651b807f277.png)

It is not visible in the dev portal try-it tool.
![image](https://user-images.githubusercontent.com/1591316/74654964-7c9dd080-51b1-11ea-8143-7b9f8511ed0e.png)

**Comment by HiranyaKavishani** [comment]
Ref: https://github.com/swagger-api/swagger-ui/issues/5892
