### ISSUE TITLE
UI issue when listing tenant names in Dev Portal

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7481]
### Description:
Following UI issue occurred (Half part of the page is rendered and remaining part is black) when there are tenants and click on `GO TO PUBLIC DEV PORTAL` from top menu:

![image](https://user-images.githubusercontent.com/19728269/74511227-8c0be800-4f2b-11ea-92eb-8bb8d7920068.png)

### Affected Product Version:
3.1.0

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8232
