### ISSUE TITLE
[Throttling] PropertyMap is not allowed in Custom policy Key template.

### ISSUE THREAD

**Issue by RaveenAthapaththu** [wso2/product-apim#7484]
When adding a custom policy for throttling, the key template only allows the following stream parameters.
"apiContext, apiVersion, resourceKey, userId, appId, apiTenant, appTenant, clientIp".

Because of this, the flexibility of the custom throttling policy is limited. Even though the default blocking request stream contains a 'propertyMap' parameter, because of the above-limited stream parameters we cannot use a custom value, (e.g: path parameter such as an account-id) using the property map as it is not supported in the current implementation.

**Comment by menakaj** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/1853

**Comment by malinthaprasan** [comment]
We need to fix this in master branch. The code is missing.
