### ISSUE TITLE
Older version of API is not removed from devportal when new version is created

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#7488]
### Description:
Older version of API published in the devportal is not removed when a new version is published using a older version of the API from publisher. This happens specifically when the the newest version is in a different page from the older version in the publisher.

### Steps to reproduce:
1. Create an API and publish it.
2. Create versions of it until the newest version is displayed in a different page.
3. Create and publish a new version of the API using an older version of the API which is in a different page other than the page (in publisher) containing the newest version.

![test3-older version](https://user-images.githubusercontent.com/25485783/74721012-ba0b6800-525c-11ea-8317-d49c33fce366.jpg)

![test3-new version](https://user-images.githubusercontent.com/25485783/74721026-c099df80-525c-11ea-88c0-856319229b49.jpg)

**Comment by Sarangan0219** [comment]
This issue is not reproducible in the latest pack.
