### ISSUE TITLE
API Categories and Groups can lead to confusion 

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#7490]
### Description:

When both API Categories and Groups are available users can get confused

![image](https://user-images.githubusercontent.com/20179540/74725957-aa901d00-5264-11ea-9e25-cc011198f5e7.png)

### Affected Product Version:

3.1.0 beta

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by erangatl** [comment]
> For APIM 3.1.0 release we decided to let api-categories and tag wise groups to co-exist but we will be deprecating and removing tag wise groups feature altogether in future releases. 3.1.0 Users are advised to use api-categories instead of older tag-wise grouping feature to group APIs. It is advised to migrate old tag wise groups into categories and avoid co-existence of categories and groups to avoid confusions.

Then we better update these information in docs https://github.com/wso2/docs-apim/issues/724

**Comment by msm1992** [comment]
@Mariangela can you please review and add this doc to 3.1.0 doc space ? 
[1]. https://github.com/wso2/docs-apim/pull/652/files

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/778
