### ISSUE TITLE
[Intermitten] The registry.xml file is not copied for newly added tenants

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#7500]
### Description:
The **registry.xml** file is not copied for newly added tenants intermittently.
The reason for this behaviour is that the _TenantServiceCreator_ class of the gateway executes before the  _TenantServiceBusInitializer_ class of carbon-mediation. When this happens the _TenantServiceCreator_ creates the synapse-configs directory, and the _createTenantSynapseConfigHierarchy_ method of _TenantServiceBusInitializer_ which is responsible for copying the **registry.xml** is not executed because the synapse-configs directory has already been created.

### Steps to reproduce:
Create a tenant in a WUM update 2.6.0 pack and check whether the  repository/tenants/<tenant-id>/synapse-configs/default/registry.xml file is available. 
If the behaviour is not reproduced, restart the server and try again a few times.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-mediation/commit/691e9d3760a933d1fb1c3759a8757f9c6f633189
