### ISSUE TITLE
wso2 api manager 3.0.0 - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by kharsha64** [wso2/product-apim#7504]
Am getting the below-mentioned error and need some help in resolving it.

Have referred to - https://github.com/wso2/product-apim/issues/7276.

But need clarification. The response in the post says - "You need to import the public certificate that you have used in deployment.toml server hostname configuration".

Am following the quick starter guide to use the api manager. But there is no such step mentioned about modifying deployment.toml.

Am a newbie playing with the certificates. Can someone please explain?

Thanks.

```
ERROR - TargetHandler I/O error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at 
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by menakaj** [comment]
Do you get this error when invoking the api?

**Comment by kharsha64** [comment]
Thanks for clarifying.
