### ISSUE TITLE
/publisher stuck at You will be redirected to /publisher/services/auth/login with error 901401: No partial token found

### ISSUE THREAD

**Issue by amritaramnauth** [wso2/product-apim#7506]
### Description:
On a server (not localhost), after installing and configuring IS as KM for API Manager, I made changes to deployment.toml configuration for hostname. Products use nginx as a proxy. While /carbon works well, the /publisher gets stuck and /devportal sign up doesn't respond. Eventually, the server closes connection with a timeout.

I made the adjustments to IS for admin_store and admin_publisher callbacks as follow
```
regexp=(https://[hostname]/devportal/services/auth/callback/login|https://[hostname]/devportal/services/auth/callback/logout)
```
and
```
regexp=(https://[hostname]/publisher/services/auth/callback/login|https://[hostname]/publisher/services/auth/callback/logout)
```

I also made the change to /services route 
```
[apim.key_manager]
service_url = "https://[is_hostname]/services/"
```

However, the console returns an error for both publisher and devportal

Publisher:
```
Error: 901401: No partial token found!,redirecting to login page.
```
Screen:
![Screenshot from 2020-02-19 07-48-46](https://user-images.githubusercontent.com/11462412/74832281-53825a80-52ed-11ea-92d9-73b00de427df.png)

Devportal:

```
User not found. Token refreshing failed. 
Error: Error: No partial token found,redirecting to Anonymous View
```
Screen:
![Screenshot from 2020-02-19 07-50-11](https://user-images.githubusercontent.com/11462412/74832308-6301a380-52ed-11ea-96ac-b8c534bfa1ed.png)

The affected APIs seem to be  all /services routes.

Is this a configuration problem, what else needs to be changed?

### Affected Product Version:
3.0.0
5.9.0 (for IS as KM)

### Environment details (with versions):
- OS: CentOS7
- Client:
- Env (Docker/K8s): Docker

---
#### Related Issues:
https://github.com/wso2/product-apim/issues/7321

**Comment by amritaramnauth** [comment]
Solved just as similar issue. Port 9443 was closed for external requests.

**Comment by TohidMakari** [comment]
How to open 9443 port for external request?

**Comment by MPincay** [comment]
configure port  rule enable to level SO with the command :

firewall-cmd --zone=public --add-port=9443/tcp --permanent
firewall-cmd --reload

It's resolved your problem?

**Comment by TohidMakari** [comment]
@MPincay my problrm was else where and solved
