### ISSUE TITLE
Updating burst control in subscription throttling policies are not working at runtime

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#7507]
**Description**

Burst Control configurations of the subscription throttling policies are not applying in the runtime.

**Cause**

The initial request comes and constructs the throttling policy as below.

`throttle.addThrottleContext(subscriptionLevelThrottleKey, subscriptionLevelSpikeThrottle);`

The subscriptionLevelThrottleKey contain the following variables which are initialized at the first request. 

`String subscriptionLevelThrottleKey = authContext.getApplicationId() + ":" + apiContext + ":" + apiVersion`

It checks the spike arrest from the following logic.

```
public boolean isSubscriptionLevelSpike(MessageContext synCtx, String throttleKey) {
    ThrottleContext subscriptionLevelSpikeArrestThrottleContext = throttle.getThrottleContext(throttleKey);
    try {
```

According to the above implementation, the throttling policy isn't getting cleared even if we update the policy at the runtime.

**Steps To Reproduce**

- Create a throttling tier with a burst rate of 15 req/min
- Invoke an API. It throttled out in 16 requests.
- Change the burst rate of 30 req/min and invoke. It still throttled out at 16 requests.
- Re-generated the key and checked the behavior, the same results were experienced.

**Comment by Krishanx92** [comment]
@dileepagayan Can you mention which product affecting this?

**Comment by athiththan11** [comment]
The same behavior is observed in APIM 2.0.0 as well
