### ISSUE TITLE
API-M v3.1.0 does not load on Internet Explorer 11

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#7509]
### Description:
APIM does not load on IE11. The landing page keeps on loading and a syntax error is shown on browser's console.

### Steps to reproduce:
- Run the server
- Navigate to https://localhost:9443/publisher/

### Affected Product Version:
API-M v3.1.0

### Environment details (with versions):
- OS: Windows 10
- Client: Internet Explorer 11

---
#### Related Issues:
https://github.com/wso2/product-apim/issues/7435

#### Screenshot of the issue:
![IE11](https://user-images.githubusercontent.com/25485273/74901894-53a45800-53ca-11ea-8e39-916b70882fcf.png)

**Comment by tmkasun** [comment]
Yes , IE 11 is not supported, You should have edge 16+ to work with APIM portals

https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/babel.config.js#L38-L43
