### ISSUE TITLE
No way to download WSDL file from Dev Portal

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7513]
### Describe your problem(s)
In 2.6.0, WSDL can be downloaded from Store for the REST APIs generated from SOAP back-end. Refer the following screenshot:
![image](https://user-images.githubusercontent.com/19728269/74910997-bead5900-53e1-11ea-83ea-49eb58040d37.png)

In 3.1.0 Dev Portal, no UI option to download WSDL file.

**Comment by malinthaprasan** [comment]
Is this for SOAP APIs or SOAP to REST APIs?

**Comment by vithu30** [comment]
It is for SOAP to REST APIs.

**Comment by vithu30** [comment]
Closing the issue as it is not required to expose the WSDL in Dev Portal for SOAP to REST APIs
