### ISSUE TITLE
[Monetization] Required code removed from the product

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-apim#7523]
### Description:
Some of the required code for monetization to work is missing in the product. The stripe extension for monetization makes use of a method which was in usage client(carbon-apimgt) to pull data from analytics. The above module is removed from the repo and that should be added back in a new location and the above new location should be called from the extension. 

### Steps to reproduce:
Configure monetization.
Try to create a subscription policy.

### Affected Product Version:
3.1.0

**Comment by AnuGayan** [comment]
This is fixed in the latest version
