### ISSUE TITLE
[Publisher] Selected mediation policy is not preserved properly in Runtime Configurations.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/product-apim#7524]
![Screenshot from 2019-11-26 16-39-06](https://user-images.githubusercontent.com/31464477/75006431-c29bb280-5497-11ea-8407-c163f259f761.png)
![Screenshot from 2019-11-26 16-39-26](https://user-images.githubusercontent.com/31464477/75006437-ca5b5700-5497-11ea-8a7c-ca4c6a92fc00.png)
![Screenshot from 2019-11-26 16-39-30](https://user-images.githubusercontent.com/31464477/75006446-d2b39200-5497-11ea-86e7-40f1d485835e.png)

Issue
When we edit Message Mediation in Runtime Configurations if we select one mediation policy from global mediation and after clicking the select button, if we switched from custom mediation to global mediation or none to global mediation, selected mediation policy is not preserved properly.if we choose None or Common polices option and click the select button and go back again to edit mediation policy, selected policy not preserved properly.

**Comment by Krishanx92** [comment]
This is not reproduce in latest version hence closing
