### ISSUE TITLE
Inconsistent behavior on case sensitive API context

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#7528]
### Description:
The case-sensitivity factor of the API context in WSO2 APIM has inconsistent behaviors in some of the APIM versions.

A case sensitive API context can not be created when trying to create APIs via Publisher UI (when the version is also the same).
However, it is allowed to create case sensitive API contexts via the RESTful APIs.
#### Suggested Labels:
APIM 3.0

**Comment by Meruja** [comment]
This issue is reproducible in 3.1.0 as well.
