### ISSUE TITLE
ORA-00933: SQL command not properly ended error when generating token for application.

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#7531]
### Description:ORA-00933: SQL command not properly ended error when generating token for application in Oracle.

APIM 2.6.0 latest wum updated pack as at 21/02/2020
Due to the fix introduced in https://github.com/wso2-support/carbon-identity-framework/pull/983

**Comment by isharac** [comment]
Fixed with https://github.com/wso2-support/carbon-identity-framework/pull/997

**Comment by kavishkafernando** [comment]
@isharac has this been fixed in latest WUM?
