### ISSUE TITLE
Account lock and unlock notification emails are not sent

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#7536]
### Description:
When a user account is locked or unlocked, the notification mails are not sent to the user. This happens for both tenant and super tenant.

### Steps to reproduce:
Follow the steps in documentation [1] for enabling account locking for a user.

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/identity-management-for-the-api-dev-portal/#account-locking

### Affected Product Version:
WSO2 API Manager 3.1.0-Beta

### Environment details (with versions):
- OS: Ubuntu
- Browser: Chrome

**Comment by Meruja** [comment]
The issue could not be reproducible. Able to receive lock and unlock notification emails.

**Comment by Meruja** [comment]
When a user account is locked or unlocked, the notification emails are not sent to the tenant user only.
