### ISSUE TITLE
[Publisher] View in Dev portal link in menu bar redirects to localhost

### ISSUE THREAD

**Issue by teodora-mitrovic** [wso2/product-apim#7540]
### Description:

In publisher component of API Manager, when I go to service overview, and want to open view in dev portal, it redirects me to localhost, instead to domain_name.

I saw that this same issue was closed, so I am opening a new one, because changing **[apim.devportal]** **url** in deployment.toml file didn't fix the issue for me.

### Affected Product Version:
WSO2 API Manager 3.0.0

### Environment details (with versions):
- OS: Centos 7
- Client: Chrome 79

---
#### Related Issues:
[https://github.com/wso2/product-apim/issues/7067]

#### Suggested Assignees:
@kavishkafernando

**Comment by kavishkafernando** [comment]
Hi @teodora-mitrovic 

Adding the following configuration to the deployment.toml file should work.
**[apim.devportal]
url = "https://<<**HOST**>>/devportal**

How many nodes do you have?

Could you please share the deployment.toml file of the publisher node.

**Comment by teodora-mitrovic** [comment]
Hi @kavishkafernando 

I am confused now, should I change apim.devportal url in general deployment.toml file or in deployment.toml file of the publisher node?

**Comment by teodora-mitrovic** [comment]
So I forgot to also comment out [apim.devportal] line beside the actual url, when I restarted the server everything was working okay :)
