### ISSUE TITLE
HTTP Headers should be processed in case-insensitive manner

### ISSUE THREAD

**Issue by madhawa-gunasekara** [wso2/product-apim#7575]
### Description:
Generic HTTP Headers don't process properly with APIM, for example, if the backend sends a response with lowercase header names, API Manager process headers in a case-sensitive manner, so It adds additional headers to the response. like Content-Type 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

### Steps to reproduce:
use a backend service which sends all the response headers in lower case.

### Affected Product Version:
2.0.0 , 2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
@tharindu1st @tmkasun isn't this fixed in later versions?

**Comment by gspadotto** [comment]
Hi, any news about this issue? I am seeing duplicate "Content-Type/content-type" headers in the responses when using an APIM instance running in a Container with an Istio Proxy.

**Comment by shammijayasinghe** [comment]
This can be reproduced when the backend was sending a lower case content-type header while having a content-aware mediator in the flow. 
eg: "content-type: application/json[\r][\n]"

In oder to avoid the problem, We can use following in the API manager 3.2.0 environment.
[passthru_http]
"http.response.headers.preserve"="content-type"
