### ISSUE TITLE
Add Basic and MutualSSL Options in Try Out page

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7580]
### Description:
Need to Add basic and Mutual Options in Try Out page in the Developer Portal.

<img width="1433" alt="Screen Shot 2020-02-26 at 11 48 57 AM" src="https://user-images.githubusercontent.com/19324135/75317559-54d3fa00-588e-11ea-80f5-1e57a28e7937.png">

**Comment by tmkasun** [comment]
As discussed with @harsha89 , Since this is a very valuable feature, We need to prioritize this &  fix in APIM 3.1.0 , hence removing 3.x.x
