### ISSUE TITLE
Need to rearrange try-out overview section

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7581]
### Description:
Need to re-arrange try-out overview section as follows.

<img width="1433" alt="Screen Shot 2020-02-26 at 11 48 57 AM" src="https://user-images.githubusercontent.com/19324135/75318105-84cfcd00-588f-11ea-8abb-2e6f8276668c.png">

The following changes need to be done,

1. Hide default application and Key type when API Key is selected
2.  The UI needs to be arranged as follows

**Select Authentication**
i) Access Token selection radio buttons
ii) Access token text box
iii) Applications and key type

**Select Endpoint**
i) Environment

**Comment by kavishkafernando** [comment]
@chanaka3d @erangatl @tmkasun please provide your suggestions.

**Comment by erangatl** [comment]
Prototype:
https://xd.adobe.com/view/4566d6eb-af2f-49bf-522d-4bc7a3e9a541-3357/?fullscreen

![image](https://user-images.githubusercontent.com/20179540/76828681-8285e080-6847-11ea-885f-eec5671d43f2.png)

**Comment by tmkasun** [comment]
Hi @erangatl 

Shall we separate the Gateway environment selection bit apart from the Security type and Keytype selection menus

And also the Endpoint selection menu should available  across all the security mechanisms

**Comment by erangatl** [comment]
> Hi @erangatl
> 
> Shall we separate the Gateway environment selection bit apart from the Security type and Keytype selection menus
> 
> And also the Endpoint selection menu should available across all the security mechanisms

+1 will do the changes

**Comment by erangatl** [comment]
Prototype:
https://xd.adobe.com/view/4566d6eb-af2f-49bf-522d-4bc7a3e9a541-3357/?fullscreen

![image](https://user-images.githubusercontent.com/20179540/76926433-5bd8b000-6902-11ea-8f22-2cf3b325eeab.png)

Need a descriptive text for Mutual SSL.

**Comment by kavishkafernando** [comment]
@tmkasun we will need to add a text box to provide the validity period for the Generation of test Key right?

**Comment by erangatl** [comment]
> @tmkasun we will need to add a text box to provide the validity period for the Generation of test Key right?

Is the "validity period" set of pre-defined values or user-defined?

If it is pre-defined we can show a select with default value selected, when the Generate Test Key button clicked. If it is user-defined we can show a text box with the default value.

**Comment by kavishkafernando** [comment]
Validity period will be user-defined. Can we update wireframe with the positioning of the validity period text box as well?

**Comment by erangatl** [comment]
> Validity period will be user-defined. Can we update wireframe with the positioning of the validity period text box as well?

Sure will do

**Comment by erangatl** [comment]
Prototype:
https://xd.adobe.com/view/4566d6eb-af2f-49bf-522d-4bc7a3e9a541-3357/?fullscreen

Wireframe:
![image](https://user-images.githubusercontent.com/20179540/76945185-32cb1600-6928-11ea-8e1b-75389e6e4aed.png)
