### ISSUE TITLE
Add security type to API Overview

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#7583]
### Description:
Currently a user who visits the Developer Portal has no idea about the security related to an API.

We need to Add security type to API Overview so that a user can get a clear idea.

<img width="1234" alt="Screen Shot 2020-02-26 at 12 29 56 PM" src="https://user-images.githubusercontent.com/19324135/75320037-d67a5680-5893-11ea-98ad-02d481258a3c.png">

**Comment by chanaka3d** [comment]
<img width="537" alt="Screen Shot 2020-10-02 at 2 09 15 PM" src="https://user-images.githubusercontent.com/3424539/94904430-f1abe500-04b8-11eb-9b2e-2153a2fca575.png">
