### ISSUE TITLE
Parameterise WSO2_CARBON_DB database in to toml structure.

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-apim#7585]
### Description:
Due to fresh pack deployment issues the h2 path is moved out of the running pack sometimes. Hence the path for WSO2_CARBON_DB should be configurable via toml. 

tagging https://github.com/wso2/product-apim/issues/7228

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
@Krishanx92 Shall we do this to 3.1.0 release?

**Comment by pubudu538** [comment]
@tharindu1st Thoughts?
