### ISSUE TITLE
Dev Portal Create Account - Invalid redirection when cancelled

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#7587]
### Description:
User gets redirected to "/carbon/admin/login.jsp" when "Cancel" button is clicked in Signup page.

### Steps to reproduce:

1. Navigate to dev-portal
2. Click Sign-in button
3. Click "Create Account"
4. Click Cancel button

![Screenshot from 2020-02-26 17-26-59](https://user-images.githubusercontent.com/32265029/75342886-4c46e800-58bd-11ea-8af9-badf83872ae9.png)

### Expected Result:
Should navigate back to "Sign-In" page

### Affected Product Version:
API-M v3.1.0 

### Environment details (with versions):
- OS: Ubuntu
- Browser : Chrome

**Comment by tmkasun** [comment]
@tharindu1st I think a fix should come from IS side
