### ISSUE TITLE
localhost is hardcoded when I click the Sign-in button of the dev-portal

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#7597]
### Description:

When I try to log in to the dev portal in the  **wso2am-3.1.0-beta** and **wso2am-3.1.0-alpha**, my host IP address is getting replaced with the **localhost**

https://**MYIPADDRESS**:9443/devportal/apis is getting changed as follow when I click the **SIGN_IN** button (In the following link we can see that there are two localhosts addresses)
https://localhost:9443/authenticationendpoint/login.do?client_id=ye3yosSUFusswE2J9BzASjYc2NQa&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fdevportal%2Fservices%2Fauth%2Fcallback%2Flogin&response_type=code&scope=apim%3Aapi_key+apim%3Aapp_manage+apim%3Astore_settings+apim%3Asub_alert_manage+apim%3Asub_manage+apim%3Asubscribe+openid&state=%2Fapis&tenantDomain=carbon.super&sessionDataKey=99a465ab-8c3b-44e3-8b75-86855642148b&relyingParty=ye3yosSUFusswE2J9BzASjYc2NQa&type=oidc&sp=admin_apim_devportal&isSaaSApp=true&authenticators=BasicAuthenticator%3ALOCAL

Also, I checked the same scenario by starting the servers in the remote instance and I met 
the same output.
### Steps to reproduce:
1. Go to the https://**MYorREMOTEIPADDRESS**:9443/devportal/apis link
2. Click the **SIGN_IN** button 

### Affected Product Version:
 **wso2am-3.1.0-beta** and **wso2am-3.1.0-alpha**,

### Environment details (with versions):
- OS: MAC
- Client: Google Chrome browser

**Comment by menakaj** [comment]
Could you please try changing the hostname in deployment.toml and check?
