### ISSUE TITLE
Mutual SSL authentication not working in APIM wso2am-3.1.0-beta

### ISSUE THREAD

**Issue by ashishpilania18** [wso2/product-apim#7598]
### Description:
Mutual SSL authentication not working in APIM 

### Steps to reproduce:
1. Host a Rest API
2. In Publisher , In Runtime Configuration got to transport layer security select Mutual SSL and Select Mode Mandatory ,Upload Public cert file in certificates.
3. Save the configuration and Publish on Dev Portal.
4. Wait for 10 minutes to load the setting.

### Affected Product Version:

wso2am-3.1.0-beta

### Environment details (with versions):
- OS: Window 10

### Error Encountered:
 After Waiting for 10 minutes Error Encountered in Log
![image](https://user-images.githubusercontent.com/46710223/75512967-32bab300-5a19-11ea-922d-e32af0f85e67.png)

### CURL Command to Acccess API Using Certificate and Key
![image](https://user-images.githubusercontent.com/46710223/75516691-086df300-5a23-11ea-96e8-0a15fde49d45.png)

Please help in this regard
-

**Comment by tmkasun** [comment]
@isuruh15 did we face this issue when trying out the mutual SSL flow ?

**Comment by Krishanx92** [comment]
@tmkasun This is happens only in windows environment.

**Comment by isuruh15** [comment]
@tmkasun We haven't encountered such a scenario.

**Comment by ashishpilania18** [comment]
@isuruh15 
Please confirm in Which OS  with which version u had tried in which error was not encountered. Please share the screenshot too if possible. Thanks in advance

**Comment by ashishpilania18** [comment]
@isuruh15 @Krishanx92 @tmkasun 

Same test has been done in Ubuntu Platform . But still the error is same . Please help in this regards. IF any document for aforesaid process please share too.

**Comment by tharindu1st** [comment]
Hi @ashishpilania18,

Since you invoke the HTTP URL SSL client termination does not happen at the Gateway end due to that gateway didn't know on the certificate which exchanged from Client.
Could you please try the https port in order to test

**Comment by ashishpilania18** [comment]
@tharindu1st 
Thanks for the support. Its working now in Ubuntu Environment. In Window , Https Multilistener address already bind error still there
