### ISSUE TITLE
SOAP to REST feature mediating the out sequence

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#7602]
### Describe your problem(s)
The SOAP to REST conversion feature adds mediation to the in-sequence (using the payload factory) and in the out-sequence, it only includes the ContentType property in order to set the response type to JSON. However, there are cases in the WSDL definition which defines the response path of the API invocation as well. 

For example, an XSD such as the following would indicate array elements in the response message. 
```
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="arrayElement" nillable="true" type="tns:test"/></xs:sequence> 
```
If the WSDL has the above attribute set as "unbounded" against a given element, the expectation is that the element should always be formatted as an array (and placed within [] square brackets in JSON), whether it has one or many instances. 

This works fine without an issue if there are multiple items included in the SOAP response for the above element. But the case matters if there's only one item available for the above element because unless a workaround such as using an XSLT mediator is used, the JSON response will not include this as an array. 

### Describe your solution
As a solution including mediation to the out sequence can also be looked into while creating the API from the WSDL definition. 

---
### Optional Fields
Observed in API-Manager-2.6.0

**Comment by lkokila** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise
