### ISSUE TITLE
Mediation policy download not working

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7618]
### Description:

Cannot download mediation policies

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:

3.0.0

**Comment by Meruja** [comment]
Mediation policy can be download in wso2am-3.1.0-beta pack.

**Comment by dushaniw** [comment]
Similar issue https://github.com/wso2/product-apim/issues/6845
