### ISSUE TITLE
Property naming

### ISSUE THREAD

**Issue by aukhatov** [wso2/product-apim#7623]
Hi!
I found a strange a property name in 
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.util/src/main/java/org/wso2/carbon/apimgt/rest/api/util/RestApiConstants.java#L103

What does it mean? 

```java
String SERVER_PASSWORD = "/applications";
```

**Comment by malinthaprasan** [comment]
It seems like an unused one. I will send a PR with removing those. Thanks for the pointer.
