### ISSUE TITLE
[AM-2.1] Endpoind load balance behaviour is not working as expect.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#7635]
**Steps to reproduce:**
1. Create an API with two delayed endpoints (50s) by enabling load balance.
![image](https://user-images.githubusercontent.com/28176167/73044986-1b286180-3e92-11ea-809a-94f42c2a42a4.png)
2. Set the endpoint suspension and timeout parameters. Then Save and publish the API.
![image](https://user-images.githubusercontent.com/28176167/73045014-3004f500-3e92-11ea-9f88-0b6a54d78dba.png)
3. Go to the store and subscribe to the API.
4. Then, when you are invoking that API, client will not receive any error message saying that the endpoint timeout or suspension. Also, the load balancer will try continuously between two endpoints like a never-ending loop. This can be seen through the wso2carbon logs.

**Comment by tharindu1st** [comment]
This is no longer applicable due to UI change.
