### ISSUE TITLE
publisher and carbon not working through gateway

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7639]
### Description:

I have very basic setup where apim 2.2.0 is hosted on linux machine. I can access store usnig

https://ipaddress:port/store
https://mygateway/store

Now I am trying to access 

https://ipaddress:port/publisher and https://ipaddress:port/carbon 

It is working fine. But when I try

https://mygateway/publisher or https://mygateway/carbon is not working and throwing 404 error.

### Environment details (with versions):
- OS: RHEL7
- Client: 
- Env (Docker/K8s): Linux

---

**Comment by dushaniw** [comment]
@raj-rajaratnam Have you followed https://docs.wso2.com/display/AM220/Changing+the+Hostname documentation?

Can you attach the error log (wso2carbon.log) ?

**Comment by rajputvishwas** [comment]
[4MAR20_log.txt](https://github.com/wso2/product-apim/files/4290997/4MAR20_log.txt)

carbon.xml
========
<HostName>mygateway</HostName>
<MgtHostName>mygateway</MgtHostName>

api-manager.xml

<APIStore>
         
        <URL>https://localhost:[mgt-transport-https-port]/store</URL>
      
</APIStore>

<APIPublisher>
         
        <URL>https://localhost:[mgt-transport-https-port]/publisher</URL>
      
</APIPublisher>

**Comment by Arshardh** [comment]
Closing since this is identified as stale
