### ISSUE TITLE
Alert is not generating in WSO2 V3.0

### ISSUE THREAD

**Issue by deepak21singh** [wso2/product-apim#7642]
I am trying to generate alert in WSO2 V3.0. All the required settings has been configured as per the WSO2 documents but still alerts are not generating. I have made delay of 5 mins in the API response at the backend to test and generate the alerts.

I have followed the WSO2 official documentation to generate alert but there are no alerts... there is not error logs.

https://apim.docs.wso2.com/en/latest/learn/analytics/managing-alerts-with-real-time-analytics/configuring-alerts/#configuring-alerts

WSO2 V3.0 on Windows 7 and integrated with mysql
![Capture](https://user-images.githubusercontent.com/57327730/75851816-9fb2bc00-5e10-11ea-99ed-187f8fdb1e34.PNG)

![image](https://user-images.githubusercontent.com/57327730/75851845-b1945f00-5e10-11ea-846c-dd233b813a3a.png)

**Comment by ruks** [comment]
Closing the issue since SP analytics is deprecated.
