### ISSUE TITLE
Support x-wso2 Swagger extensions that are already supported by Micro Gateway

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#7648]
### Describe your problem(s)
WSO2 Micro gateway currently supports processing several x-wso2 vendor extensions defined at swagger level which contain all the information required to create APIs. Processing these needs to be supported at APIM level in order to allow the same swagger definition to be used to create a complete API on APIM as well as importing a complete API definition as a swagger

**Comment by Rajith90** [comment]
Here are the list of extensions[1] supported by microgateway. Its better if we can capture those extensions from swagger when creating the API

[1] - https://github.com/wso2/product-microgateway#microgateway-supported-open-api-extensions

**Comment by Rajith90** [comment]
Please find the list of extensions we need to support from APIM side as well

1. x-wso2-basePath
2. x-wso2-production-endpoints
3. x-wso2-sandbox-endpoints
4. x-wso2-endpoints
5. x-wso2-throttling-tier
6. x-wso2-cors
7. x-wso2-disable-security
8. x-wso2-transports
9. x-wso2-application-security
10. x-wso2-mutual-ssl
11. x-wso2-auth-header
12. x-wso2-response-cache
