### ISSUE TITLE
Cannot import API definition from a file

### ISSUE THREAD

**Issue by tharmini** [wso2/product-apim#7652]
### Description:
When importing the swagger definition from a file it popup error. 

### Steps to reproduce:
1. deploy a sample API
2. Import the API definition from the file

### Affected Product Version:
APIM 3.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
APIM 3.0.0

#### Suggested Assignees:

<img width="1680" alt="Screen Shot 2020-03-05 at 1 16 43 PM" src="https://user-images.githubusercontent.com/29250881/75959626-9c890000-5ee4-11ea-8391-a7cb4ebe9544.png">

**Comment by tmkasun** [comment]
Is this reproducible in APIM 3.1.0 latest pack as well ?

**Comment by SaranganJ** [comment]
> Is this reproducible in APIM 3.1.0 latest pack as well ?

Nope! It is working fine in the latest pack.

**Comment by Sarangan0219** [comment]
> Is this reproducible in APIM 3.1.0 latest pack as well ?

Nope .It is working fine in the latest pack of APIM.
