### ISSUE TITLE
Publisher console isn't showing the existing api's when Rows per Page modified

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#7661]
### Description:
APIs are not visible when the Rows per page changed in the next page. Seems the appended offset is wrong in the Rest API call. 

### Steps to reproduce:

1) Create 15 APIs in the publisher console.
2) Upon creating 15 APIs, navigate to the next page to view the remaining 5 APIs.
3) Change the 'rows per page' from 10 to 100 from the UI.

![image](https://user-images.githubusercontent.com/29249776/76053835-889cd700-5f94-11ea-8cf5-60469610c816.png)

Request URL: https://localhost:9443/api/am/publisher/v1.0/apis?limit=100&offset=100

### Affected Product Version:

APIM-3.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Fixed in latest pack
