### ISSUE TITLE
enable forum in APIM 3.0.0

### ISSUE THREAD

**Issue by amir-dh** [wso2/product-apim#7669]
### Description:
I want to use the forum of APIM v2.5 in v3.0.
I read the documents but not find a document for the enable forum in API manager v 3.0.0.

### Affected Product Version:
APIM 3.0.0

### Environment details (with versions):
- OS: ubuntu 16.04
- Client: ubuntu 18.04
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Hi @amir-dh 

API forum feature is not available in APIM 3.x.x series yet, Observing the product usage, we have noticed that forum usage is less common in the developer portal (AKA Store portal) , Hence we haven't included it in 3.x so far. despite that, we have, Improved the interaction between API consumers and API developers/Publishers through the commenting feature and planing to improve it to support multilevel commenting (Reddit like).

@nuwand , @sanjeewa-malalgoda @chanaka3d  WDYT , How often people use forums to interact with peer developers and API Publishers, Should we add this(forums) to our 3.x road map ?

@amir-dh Thanks for bringing this up.

**Comment by amir-dh** [comment]
Hi @tmkasun 
Is there a way for using the forum v2.5 on v3.0.0. Using the old codes and APIs or any other ways.

**Comment by tmkasun** [comment]
Hi @amir-dh ,

No , it's not possible. API Manager 2.x portals have built using [JaggeryJS](http://jaggeryjs.org/documentation.jag) and API Manager 3.x portals have built using ReactJS library. JaggeryJS is a server-side rendering(SSR) framework while we use ReactJS with client-side rendering.

**Comment by amir-dh** [comment]
Hi @tmkasun 
Thanks for your help.
