### ISSUE TITLE
apim not able to connect backend endpoint

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7671]
### Description:

I am creating an API as per the guidelines given in the URL 

https://docs.wso2.com/display/AM220/Create+and+Publish+an+API

In the **implementation step** while configuring **Endpoint**

I am trying to connect backend 

http://ws.cdyne.com/phoneverify/phoneverify.asmx

which is working fine in my browser. But it throws error **Error connecting backend.**

![image](https://user-images.githubusercontent.com/15668995/76205868-1260d480-6221-11ea-99b7-dd3b897719a2.png)

While tracing in developer console it shows 
![image](https://user-images.githubusercontent.com/15668995/76206401-f3af0d80-6221-11ea-948f-3c9e7696423c.png)

[WS9mar20.txt](https://github.com/wso2/product-apim/files/4306169/WS9mar20.txt)
### Affected Product Version:

wso2 apim 2.2.0
### Environment details (with versions):
- OS: windows 64

- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Not reproducing with the latest APIM-4.4.0 product, hence closing
