### ISSUE TITLE
X-JWT-Assertion not working as expected to send backend endpoint

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7673]
WSO2 apim 3.0.0-
Steps to re-produce-

enabled the JWT in deployment toml file.
Call the API and check the JWT is sending in header to backend or not.

JWT is not sending to backend endpoint.

**Comment by vithu30** [comment]
This is not reproducible in 3.1.0 latest built pack.

**Comment by vithu30** [comment]
Hi @arun-1983,

I tried the same scenario and able to see the JWT assertion being sent to backend. You need to add following configurations in deployment.toml to send JWT to backend:
```
[apim.jwt]
enable = true
encoding = "base64" # base64,base64url
generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
claim_dialect = "http://wso2.org/claims"
header = "X-JWT-Assertion"
signing_algorithm = "SHA256withRSA"
enable_user_claims = true
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"
```
More information can be found in [1]. Can you verify whether these configurations are added properly?

[1] https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/#configuring-jwt
