### ISSUE TITLE
WSDL download option is not available in Dev Portal for SOAP APIs

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7675]
### Description:
It would be better to have download WSDL option in Dev Portal for SOAP APIs. Currently there is an option to download swagger.json but it does not contain any useful information.

![image](https://user-images.githubusercontent.com/19728269/76074035-abdd7b80-5fc0-11ea-8c73-15bd3c86f133.png)

### Affected Product Version:
Latest built 3.1.0 pack

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise.
