### ISSUE TITLE
[Improvement] Starting server profiles when installed as a Windows service.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-apim#7679]
### Description:
Running the apim product using profiles in Windows as a service. Instructions already present to pass this parameter and enabling the profile when starting with .bat script. But I failed to locate the same when using wrapper.conf file.

Below instructions work and better to keep this added in the docs as this might not be obvious to many users.
Add the below parameter to wrapper conf. Replace x with the next digit.
wrapper.java.additional.x = -Dprofile=gateway-worker
--

**Comment by HiranyaKavishani** [comment]
Closing the issue as now it is not reproducing
