### ISSUE TITLE
API Product Life cycle management  from API publisher

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#7687]
Currently, there is no option to republish the API product (bundled set of resources from multiple APIs) from the API publisher portal and there is no option to manage the API product lifecycle either.

Observed in APIM 3.0.0

**Comment by HiranyaKavishani** [comment]
@SiluniPathirana API Product design is a bit different from API design as an API Product is getting published during its creation. The life cycle management feature is not implemented for API Products. Therefore, the republish option is not supported for API Products.

**Comment by Krishanx92** [comment]
This is Fix in latest version
