### ISSUE TITLE
Improvements to the API monetization document

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-apim#7691]
### Description
The following needs to be incorporated into the documentation

1) When configuring API monetization with API Manager 3.0 by following [1] we configure the APIM_DB to MySQL. In such a case, if a user needs to view API Manager Analytics then we need to also update the configuration of the APIM_DB in both the Worker and Dashboard components in WSO2 API Manager Analytics to point to the same database. This step is not mentioned.

2) In step 4 when sending usage data to the billing engine first we need to obtain the consumer key and secret key pair by calling the dynamic client registration endpoint. In the curl request that is provided, we need to send a JSON payload but the content of the payload is not provided in [1]. We need to add a sample payload as in [2] which mentions the content to be included

[1] https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/
[2] https://docs.wso2.com/display/AM260/apidocs/publisher/index.html#guide

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
