### ISSUE TITLE
[APIM 3.0.0] Subscription policy description is misleading when monetization is enabled

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#7692]
### Description:
When monetization enabled, there is an inconsistency in subscription policy description which can be misleading.

### Steps to reproduce:
1. Create a commercial policy with dynamic usage, attach it to an API and publish the API.
2. When going subscribe to the API in the dev portal, the description is shown as "**10 AUD per week**" which is incorrect since a dynamic plan is created. The description should be "**10 AUD Per Request**".

### Affected Product Version:
3.0.0

**Comment by AmaliMatharaarachchi** [comment]
Related to https://github.com/wso2/product-apim/issues/7615. Fixed in https://github.com/wso2/carbon-apimgt/pull/8308
