### ISSUE TITLE
Subscription level throttling doesn't work with JWT tokens

### ISSUE THREAD

**Issue by ChamithKodikara** [wso2/product-apim#7693]
### Description:
when using JWT token for authentications subscription level throttling doesn't work. No matter how low is the request count allowed, I can keep calling API with the JWT token without being blocked. I tried both postman and curl. When I used the Oauth Its works properly.

### Steps to reproduce:
1.Create Subscription level throttling with a minimum number of request per min
2.Subscribe to that subscription with an APP with token type as JWT
3.Generate the token and try the API call with bearer token with either postman or curl throttling doesn't work
4. change the token type to Oauth and throttling strting to work.
### Environment details (with versions):
- OS: Ubuntu 
- Client: Postman/curl
- Env (Docker/K8s):

---
#### Suggested Labels:

Priority/High

**Comment by tharindu1st** [comment]
Hi @ChamithKodikara,
This was working in the 3.0.0 and 3.1.0 versions.
does this have any configuration changes?

**Comment by ChamithKodikara** [comment]
This happened during the training program at WSO2, and the version vs 3.0.0 there weren't any specific configs, I was following the lab kit given by WSO2 training program
