### ISSUE TITLE
Publisher portal login issue after upgrade from wso2 apim 210 to Wso2 apim 300 

### ISSUE THREAD

**Issue by chkishorebabu** [wso2/product-apim#7698]
I get the following error when trying to access publisher portal using URL https:///publisher

TID: [-1234] [client-registration/v0.15] [2020-03-11 11:45:16,329] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/client-registration/v0.15].[CXFServlet]} - Servlet.service() for servlet [CXFServlet] in context with path [/client-registration/v0.15] threw exception java.util.MissingFormatArgumentException: Format specifier '%s' at java.util.Formatter.format(Formatter.java:2519) at java.util.Formatter.format(Formatter.java:2455) at java.lang.String.format(String.java:2940) at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationTemplateDAOImpl.getApplicationTemplate(ApplicationTemplateDAOImpl.java:110) at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getSpTemplateFromDB(ApplicationManagementServiceImpl.java:1619) at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.doGetApplicationTemplate(ApplicationManagementServiceImpl.java:1468) at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationTemplate(ApplicationManagementServiceImpl.java:1359) at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplicationWithTemplate(ApplicationManagementServiceImpl.java:169) at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:154) at org.wso2.carbon.apimgt.rest.api.dcr.web.impl.RegistrationServiceImpl.createApplication(RegistrationServiceImpl.java:347) at org.wso2.carbon.apimgt.rest.api.dcr.web.impl.RegistrationServiceImpl.register(RegistrationServiceImpl.java:170) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 

TID: [-1234] [publisher] [2020-03-11 11:45:16,336] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} - org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<>/META-INF/scripts/http.js#17) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<>/META-INF/scripts/http.js#17) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289) at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

Caused by: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<>/META-INF/scripts/http.js#17) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665) at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:112) at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:88) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)

TID: [-1] [] [2020-03-11 11:58:19,226] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} - [ Sequence: 2722 ] Exception occurred while processing inbound events. java.lang.NullPointerException at org.wso2.andes.kernel.router.MessageRouterFactory.createMessageRouter(MessageRouterFactory.java:70) at org.wso2.andes.store.rdbms.RDBMSAndesContextStoreImpl.getAllMessageRoutersStored(RDBMSAndesContextStoreImpl.java:777) at org.wso2.andes.store.FailureObservingAndesContextStore.getAllMessageRoutersStored(FailureObservingAndesContextStore.java:312) at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadMessageRoutersFromDB(InboundDBSyncRequestEvent.java:111) at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:73)

Any kind of help would be appreciated.

**Comment by prasa7** [comment]
Can you send wso2am-2.6.0/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json file for us to check

**Comment by tharindu1st** [comment]
Invalid due to ui revamp
