### ISSUE TITLE
Intermittant test failures in product-scenario tests

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#7699]
### Description:
Below two product-scenario tests fail intermittantly for apim 2.6.0
1)
` 2-collaborative-api-development::PublishAPIByValidRolePermissionCategoryTestCase#testPublishAlreadyPublishedAPIByValidPermissionAssignedUser: Error message received {"error" : true, "message" : " Failed to change the life cycle status : Unable to put resource Resource update failed. User User8 is not authorized to update the resource /_system/governance/apimgt/applicationdata/provider/User_8/API_8/1.0.0/api."} expected:<false> but was:<true>`

2)
` 7-managing-api-traffic-based-on-various-conditions::SubscribeToAssignedTiersTestCase#testRepublishWithDifferentTier: New changes for :Republish_Diff_Tier_API was not visible in store at the end of wait time. expected:<true> but was:<false>`
This failure should be due to wait time exceeding (waiting until API update is reflected in Store).

**Comment by Krishanx92** [comment]
Not related to latest product, hence closing this
