### ISSUE TITLE
Remove Deploy Sample API Product option to users with Publish permission

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7703]
### Description:
Currently `Deploy Sample API Product` is visible for users only with publish permission. Refer the screenshot below:

![image](https://user-images.githubusercontent.com/19728269/76489459-68668f80-644e-11ea-9fe8-28e096a57ef8.png)

When trying to deploy the sample product, error thrown as:
```
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```
It would be better to hide this option to users only with Publish permission. (Deploy sample API is hidden for same users)

**Comment by chanaka3d** [comment]
Fixed with PR https://github.com/wso2/carbon-apimgt/pull/8343
