### ISSUE TITLE
Unable to update the API when documents are added.

### ISSUE THREAD

**Issue by Meruja** [wso2/product-apim#7719]
### Description:
There is an NPE when updating the API. There will not be an issue if we add 'File' type documentations only.

### Steps to reproduce:
1. Create an API
2. Add different types of documentation.
3. Go to 'Design Configuration' and save API.
4. Check the backend.
### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
3.1.0
Priority/High

#### Suggested Assignees:
Meruja

**Comment by menakaj** [comment]
Duplicate https://github.com/wso2/product-apim/issues/7735
