### ISSUE TITLE
Control API visibility in the Developer Portal not working as expected

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#7723]
### Description:
1. Create tenant wso2.com
2. login to publisher from tenant admin.
3. Create an API (TestAPI) and enable Developer Portal Visibility - Restricted by Roles.
4. Add internal/publisher role to the list of roles.
5. Login to carbon console as tenant admin.
6. Create a user ( chanaka ) and add all available roles except admin and internal/publisher.
7. Login to devportal as chanaka@wso2.com.
8. Go to wso2.com tenant store.
9. The TestAPI is visible to chanaka@wso2.com.
10. The TestAPI tags are visible to chanaka@wso2.com in the tag cloud.

Expected: TestAPI should be invisible to the user chanaka@wso2.com. And TestAPI tags should not be visible to chanaka@wso2.com

**Comment by malinthaprasan** [comment]
Does the user have admin role assigned? For admin users, this restriction doesn't apply

**Comment by Krishanx92** [comment]
This issue occur if a particular user has an internal/creator role assign. This restriction should not apply to the internal/creator.

**Comment by chanaka3d** [comment]
No. Admin role was not applied. The following are the roles applied.
<img width="721" alt="Screen Shot 2020-03-13 at 10 14 24 PM" src="https://user-images.githubusercontent.com/3424539/76642712-bfb54e80-6579-11ea-9a13-b7cc4950740c.png">

Once internal/creator role removed from the user the APIs were hidden as expected.

**Comment by Krishanx92** [comment]
I Tested this further and this behavior shows because of internal/creator and internal/publisher roles.
If a user has one of these roles a user can view API in the Publisher portal. So we don't block access in dev-portal as well. If API has publisher access control then this will not be shown in dev portal.

So this should be the default behavior.
@malinthaprasan please confirm.

**Comment by malinthaprasan** [comment]
Yes, this is the correct behaviour.
