### ISSUE TITLE
how can i enable ssoConfiguration in site.json

### ISSUE THREAD

**Issue by amir-dh** [wso2/product-apim#7724]
### Description:
I want to Setup the API Manager 3.0.0 store login with google and I use [1] document. in step 12 I should edit site.json in API Publisher, but in the new version, this configuration has been changed!.
How can complete this guide?

1- https://wso2.com/library/articles/2016/02/article-how-to-setup-a-wso2-api-manager-store-login-with-google/

### Affected Product Version:
API Manager

### Environment details (with versions):
- OS: 
- Client:
- Env (Docker/K8s):

---

**Comment by menakaj** [comment]
In 3.0.0, the dev portal UI already uses a Service Provider. You will be able to check that in the service providers. (admin_admin_store)

Therefore, when configuring SSO with a federated IDP, it would be sufficient to create an identity provider and configure the existing service provider to use that IDP. 

No site.json config is not necessary.

**Comment by tmkasun** [comment]
Closing the issue since an answer is given. Feel free to reopen the issue if you need further clarification.
