### ISSUE TITLE
Error when changing the SDK generation configuration

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#7738]
### Description:

Error when changing the SDK generation configuration.

![image](https://user-images.githubusercontent.com/20179540/76740736-5c533880-6794-11ea-805a-8faffe952649.png)

### Steps to reproduce:

1. Open <API-M_HOME>/repository/conf/deployment.toml file.

1. Add following configuration.
[apim.sdk]
supported_languages = "android, java, scala, csharp, dart, flash, groovy, javascript"

1. Restart the server.

https://apim.docs.wso2.com/en/latest/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal/#generate-sdks-in-developer-portal

### Affected Product Version:
API-M 3.0 RC1

### Environment details (with versions):
MAC

**Comment by kavishkafernando** [comment]
Hi @eranga

Can you try the following configuration?
[apim.sdk]
supported_languages = ["android", "java", "scala", "csharp", "dart", "flash", "groovy", "javascript"]

**Comment by kavishkafernando** [comment]
<img width="1245" alt="Screen Shot 2020-03-16 at 5 03 36 PM" src="https://user-images.githubusercontent.com/19324135/76754854-d8f01200-67a8-11ea-9203-f78915d7ca08.png">

**Comment by erangatl** [comment]
> Hi @eranga
> 
> Can you try the following configuration?
> [apim.sdk]
> supported_languages = ["android", "java", "scala", "csharp", "dart", "flash", "groovy", "javascript"]

Yeah it works, need to update docs

**Comment by kavishkafernando** [comment]
Created a doc issue https://github.com/wso2/docs-apim/issues/849

Hence closing this issue.
