### ISSUE TITLE
wso2 apim starts with error

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7749]
### Description:

wso2 apim 2.2.0 starts with error while connected to internet, but works fine in offline mode

### Steps to reproduce:
Start wso2 using wso2server.bat ensure you are connected to internet, wso2 server starts with some error you can find the same in 16032020.txt log file. 
[16032020.txt](https://github.com/wso2/product-apim/files/4338331/16032020.txt)

Turn off the internet..[Offline]
Start wso2 using wso2server.bat, wso2 server starts without any kind of error you can find the sam in the 16032020l2.txt log file

[16032020_l2.txt](https://github.com/wso2/product-apim/files/4338333/16032020_l2.txt)

### Affected Product Version:

wso2 apim 2.2.0

### Environment details (with versions):
- OS: windows 10 x 64 10.0.17134
- Client:
- Env (Docker/K8s):

---

**Comment by prasa7** [comment]
Hi I checked the logs. As for it you IP address is assigned to 192.168.43.12 when you are connected to the internet. WSO2 server is trying to resolve it and it could not. 

Can you add a host mapping to this file (C:\Windows\System32\Drivers\etc\hosts.) as below and get back to us.

192.168.43.12 localhost

**Comment by rajputvishwas** [comment]
It worked without any error thanks
