### ISSUE TITLE
Unable to create SP in  a tenant in APIM 3.0.0 ,WSO2IS-KM-5.9.0

### ISSUE THREAD

**Issue by nalakas** [wso2/product-apim#7752]
This is not reproducible in a 3.0.0 fresh pack. Only reproducible in WUM updated pack.

steps:
1.create tenant.
2.create SP. It will fail to create SP and only give UI error as below screenshot.
database: h2 and MySQL

<img width="966" alt="Screenshot 2020-03-16 at 21 04 02" src="https://user-images.githubusercontent.com/40158948/76774372-d520b780-67c9-11ea-88cc-29c68ca9fbb3.png">

**Comment by Krishanx92** [comment]
This is not reproduce in latest pack, hence closing
