### ISSUE TITLE
Throttling is not working in WSO2 APIM 3.0.0 distributed setup with profiling

### ISSUE THREAD

**Issue by arun-1983** [wso2/product-apim#7757]
Throttling is not working in WSO2 APIM 3.0.0 distributed setup with profiling

Steps to reproduce-

Distributed setup of WSO2 APIM 3.0.0
Run the product with profiling.
Create subscription level throttling policy.
Test the throttling and it is not working.

**Comment by Krishanx92** [comment]
This is working in latest APIM-4.4.0 with distributed setup, hence closing. please re-open if you still face this with latest.
