### ISSUE TITLE
apiname is passing as null to Analytic Worker Node after some time  with aPIM 2.6

### ISSUE THREAD

**Issue by ashishpilania18** [wso2/product-apim#7773]
### Description:

Analytics Worker Node is throwing below error due to which it is not table to insert records wherever API_NAME column is there.
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "apiname" violates not-null constraint. 

When we restart the server it starts functioning properly but again after sometime like 2-3 hours, same problem arises.

Can you please suggest how to resolve this issue?

### Affected Product Version:

Wso2 Analytics Version: 2.6.0
Wso2 APIM Version: 2.6.0

### Environment details (with versions):
- OS:Linux

---

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
