### ISSUE TITLE
Minor issues in TagWise mode and Tag cloud

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#7785]
### Description:
When both the tag cloud and tagWise mode are active but there are no APIs tagged as foo-group following happens.
<img width="387" alt="Screen Shot 2020-03-19 at 11 05 17 AM" src="https://user-images.githubusercontent.com/3424539/77035065-9b220200-69d1-11ea-8a84-fb1504a601d2.png">

When tagWise.mode = 'page' and tagCloud is disabled following happens.

<img width="488" alt="Screen Shot 2020-03-19 at 11 04 39 AM" src="https://user-images.githubusercontent.com/3424539/77035067-9e1cf280-69d1-11ea-9a72-a593674b4782.png">

**Comment by Krishanx92** [comment]
Fixed in master hence closing
