### ISSUE TITLE
[Doc] Improve Jaggery API doc warning message

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-apim#7786]
### Description:
The Jaggery API doc warning message states as "The following Store APIs are deprecated and will be unsupported in a future release." [1]

However, as there are other Jaggery APIs which are not included in the documentation, we need to make the warning message to a more generic one like "Jaggery APIs are deprecated in the AM-2.x.x releases and will be unsupported in future releases"

[1] https://docs.wso2.com/display/AM260/Store+APIs

#### Suggested Labels:
AM-2.x.x

**Comment by kavithasub** [comment]
Note that I've fixed the above in doc(https://docs.wso2.com/display/AM260/Store+APIs) as I need to share the same with customer urgently where they looked for jaggery apis.
