### ISSUE TITLE
carbon.xml entries move to backup

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim#7806]
### Description:

I am using wso2 api 3.0, what I observe that is entries to cabon.xml are being restored  to default when I start the apim and changed entries moved to backup folder

### Steps to reproduce:
Go to wso2 home/repository/conf/carbon.xml

<HostName>host123</HostName>
<MgtHostName>host123</MgtHostName>

### Affected Product Version:

wso2 3.0
### Environment details (with versions):
- OS: windows 10 x 64
- Client:
- Env (Docker/K8s):

---

**Comment by kavishkafernando** [comment]
Hi @rajputvishwas,

With APIM-3.0 we have introduced a new configuration model. The changes to configuration files must now be done in repository/conf/deployment.toml.

You can follow the configuration catalog document [1] for more information about the configurations.
[1] - [https://apim.docs.wso2.com/en/latest/reference/config-catalog/](https://apim.docs.wso2.com/en/latest/reference/config-catalog/)

**Comment by rajputvishwas** [comment]
Thanks
