### ISSUE TITLE
Custom grant is not visible in API manager store UI

### ISSUE THREAD

**Issue by ankit-agrawal07** [wso2/product-apim#7818]
### Description:

Custom grant is not visible in API manager store UI

### Steps to reproduce:
Follow the steps as mentioned in the documentation below to create and add a custom grant in API manager:
https://docs.wso2.com/display/IS560/Writing+a+Custom+OAuth+2.0+Grant+Type

Please note that APIM docs points to IS docs for creating custom grants:
https://docs.wso2.com/display/AM260/Writing+Custom+Grant+Types

Restart the sever and visit the store page to check if the custom grant was added. In the UI you can see that the grant check box is available but the grant name is missing. It is only visible when mouse is hovered over the checkbox.
![custom_grant_visibility_issue](https://user-images.githubusercontent.com/59166722/77420634-6c03fa00-6df0-11ea-940b-50021dc74fe2.PNG)

### Affected Product Version:

Tested with WSO2 APIM 2.6.0

### Environment details (with versions):
- OS: Windows 10
- Client:
- Env (Docker/K8s): Standalone using product binary

---

**Comment by Krishanx92** [comment]
UI change to react and this is not reproducible, hence closing.
