### ISSUE TITLE
Error while creating an API through Publisher without a context

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#7828]
### Description:
With the publisher RestFul API, was Able to create an API without a context in windows.

### Steps to reproduce:
Make API creation request with “context”: “”

**Expected output:**
Should get 500 error code.
API Shouldn't be created.

**Actual output:**
500 error code
API is created in publisher.
Unable to access publisher

### Affected Product Version:
v3.1.0

### Environment details (with versions):
- OS: Windows

**Comment by TheRasanjana** [comment]
Affected Product Version:
v3.2.0

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version APIM 4.4.0
