### ISSUE TITLE
issue in profile optimization script 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7836]
### Steps to reproduce:
get a all in one pack. 
Start the any profile using below command
sh <PRODUCT_HOME>/bin/wso2server.sh --optimize -Dprofile=<preferred-profile>

<img width="1136" alt="Screenshot 2020-03-26 at 17 27 58" src="https://user-images.githubusercontent.com/17607322/77723594-edd56c80-7016-11ea-8947-af933e526c73.png">

### Affected Product Version:

2.5.0

### Environment details (with versions):
- OS: mac os catalina
- Client:
- Env (Docker/K8s):

---

**Comment by rmsamitha** [comment]
Same issue reported in https://github.com/wso2/product-apim/issues/4148
