### ISSUE TITLE
Issues when generating additional SDKs in the Developer Portal.

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#7838]
### Description:
There is a flickering issue in the UI and not allowed to download any of the SDKs except for the first one. 

### Steps to reproduce:

1. Configure the supported languages for SDK generation in the deployment.toml file: 
`[apim.sdk]
supported_languages ="android, java, php, csharp, python, ruby, groovy, javascript"`
2. Restart the server and log into the Developer Portal.
3. Click on the API and click SDKs.
4. There is a flickering issue in the UI and not allowed to download the SDKs giving an error in the terminal.

### Affected Product Version:
APIM-3.0.0

**Comment by Prasadi-R** [comment]
Related PR for the fix: https://github.com/wso2/carbon-apimgt/pull/8068

**Comment by Prasadi-R** [comment]
Related issue: https://github.com/wso2/product-apim/issues/6895

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest vesion
