### ISSUE TITLE
Missing Content-Type Header in the response path

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7853]
### Description:
Content-Type header is missing in the response received from the gateway.

### Steps to reproduce:
N/A

### Affected Product Version:

APIM-1.7.0 (After applying :  patch2235)

### Environment details (with versions):
- OS: 
- Client:
- Env (Docker/K8s):
- JAVA - 1.7_80
---
#### Suggested Labels:
Affected/1.7.0

**Comment by Arshardh** [comment]
Closing since this is identified as stale.
