### ISSUE TITLE
UX not consistent when login out from Publisher Vs Devportal

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7858]
### Describe your problem(s)

When a user has logged into both publisher and dev portal, After a successful logout from dev portal redirects the user to different pages depends on the logout triggered a portal

If single logout was initiated from Devportal , It finally redirects the user back to the anonymous view of the dev portal

![devlg](https://user-images.githubusercontent.com/3313885/78062177-e530bd80-73ab-11ea-9d1e-b2b02e1ba976.gif)

If single  logout was initiated from Publisher, Devportal logout ends in a user login prompt which is not the expected behavior in Developer portal logout action

![pl](https://user-images.githubusercontent.com/3313885/78062148-dea24600-73ab-11ea-8b58-8b8ad60305e1.gif)

### How will you implement it

---

**Comment by HiranyaKavishani** [comment]
This issue is not reproducible in the latest pack, Fixed with https://github.com/wso2/carbon-apimgt/commit/b463509bf0f79004a4d4f69298e4e14053e60cfc
