### ISSUE TITLE
Please help me to Configuring External IDP through Identity Server for SSO in WSO2 Analytics 3.0

### ISSUE THREAD

**Issue by akurathimohan** [wso2/product-apim#7864]
### Description:
Hi Team,

Please help me to Configuring External IDP through Identity Server for SSO in WSO2 Analytics 3.0
I could't able to find any documentation related to this in Analytics 3.0 document.
https://apim.docs.wso2.com/en/latest/learn/analytics/overview-of-api-analytics/

Regards,
Mohan Akurathi.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
