### ISSUE TITLE
Improve API create page endpoint test UI

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7868]
### Describe your problem(s)

This test button doesn't look like a button and also it doesn't imply a test action in the icon as well 

![image](https://user-images.githubusercontent.com/3313885/78262633-7d4eb400-751e-11ea-9380-ed8ffa83b76d.png)

@rmsamitha @chanaka3d @erangatl Shall we improve this UX ? WDYT ?

### How will you implement it

---

**Comment by rmsamitha** [comment]
In that case, we will have to replace the icon with a text (i.e. "Test") I guess. Will it be nice?
