### ISSUE TITLE
Publisher gets signed in with previous session

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#7876]
### Steps to reproduce:
1) Create user A with publish/create permissons
2) Log in to the publisher with user A credentials
3) click to view API details
4)click view in dev portal
5) The message appears allows to log out. Click log out.
6) Notice that the publisher portal also logs out the current user
7) log in with admin credentials to the publisher
8) notice that the previous user is signed in.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by CrowleyRajapakse** [comment]
Fixed and not reproducing in the latest pack
