### ISSUE TITLE
When adding a blacklist policy based on context, it is not working unless version is appended

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7883]
### Description:
When creating a blacklist policy based on context, it is mandatory to append the version to it. If we have just defined the context alone, the following error pops.
ERROR - condition-edit:jag Error occurred while adding conditions:  Couldn't Save Block Condition Due to Invalid API Context /pizzashack

### Steps to reproduce:
Deploy the pizzashack API and try to create a black list policy as mentioned above

### Affected Product Version:

3.0.0

### Environment details (with versions):
- OS: MacOS Mojave
- Client: 
- Env (Docker/K8s):

---
#### Suggested Labels:
Affected/3.0.0

**Comment by isharac** [comment]
Admin portal has moved from jaggery to react since APIM 3.2.0. Please reopen if this issue still appears in the latest version.
