### ISSUE TITLE
Improve tags input UX across portals

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#7887]
### Describe your problem(s)

We have a UX issue with tag type inputs in 3.x. Where to add a tag value it is required to press `**Enter**` button , but most of the users doesn't recognize that action and find difficulties in adding tags

This issue is there in Store visibility control role addition input and other tags input interfaces

### Describe your solution

![image](https://user-images.githubusercontent.com/3313885/78627945-63abc480-78b0-11ea-8778-51d1f8fad89d.png)

Like in 2.x tags input , We could warn the user, if we detect raw string in tags input and focus out from the input field

#### Suggested Assignees:

@chanaka3d , @erangatl  WDYT ?

@hasuniea recently experienced this issue , and I too have experienced this some time back

**Comment by erangatl** [comment]
Related #6920
