### ISSUE TITLE
Devportal Custom CSS loading fails when a customurl is enabled

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-apim#7892]
### Description:
When a custom URL is set for the API Devportal the overriding of CSS by adding a new custom CSS file fails. With the above conditions met the JS request for a wrong path for the css file. 

Without custom URL the request goes to https://site/public/tenant_themes/<tenant_domain>/apim/css/custom.css 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by prasa7** [comment]
@chanaka3d
