### ISSUE TITLE
Path parameters can be removed. But the resource remains.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7895]
### Description:
When a resource is added with a path parameter, that path parameter segment can be deleted. But the resource remains. And when I save it, the following error pops in User Interface.
[900754]: Error while parsing OpenAPI definition
attribute paths.'/pet/{id}'. Declared path parameter id needs to be defined as a path parameter in path or operation level

the following log can be seen in the carbon log.
[2020-04-08 21:37:44,753] ERROR - ApisApiServiceImpl Error while parsing OpenAPI definition:attribute paths.'/pet/{id}'. Declared path parameter id needs to be defined as a path parameter in path or operation level

IMO, It is better not to allow path param to be changed if the resource name is changed accordingly.

### Steps to reproduce:
Create an API and add resource /pet/{id}.
Remove the path parameter listed under the resource details.
And save the API.

### Affected Product Version:
3.0.0 wum timestamp 1586343950785

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
In addition to above following behavior can also be seen,

1. When editing such path parameter and click on save, a new duplicate entry is added.
2. If we remove the duplicate entry, both entries get deleted.
