### ISSUE TITLE
Mediation Sequences cannot be downloaded.

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7897]
### Description:
Mediation sequences cannot be downloaded from the User Interface.

### Steps to reproduce:
Try downloading the existing sequences.
Add a sequence file and then try downloading it.

### Affected Product Version:
3.0.0 wum timestamp 1586217330513

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This is changed with latest APIM, hence closing
