### ISSUE TITLE
WSO2-APIM Migration Guide from 3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by ghost** [wso2/product-apim#7900]
### Description:
Hello.
I'm having some troubles with upgrade WSO2-APIM from 3.0.0 to 3.1.0
I'm successfuly done it on my test environment using this guide from google web cache - https://apim.docs.wso2.com/en/next/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310/
But now this page was deleted from cache. Could I have a copy?

**Comment by rvieiracosta** [comment]
I also need a copy.

**Comment by pubudu538** [comment]
Hopefully, the migration guide from 3.0.0 to 3.1.0 will be available around 15th May.

**Comment by nandika** [comment]
Pls get migration docs via support team
