### ISSUE TITLE
Wrong port in the curl cmd and Request URL

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#7916]
### Description:

I was testing WSO2 APIM 3.0.0 and found a strange UI Bug;  In DevPortal -> Tryout section of the API, there is an option to choose a scheme. When HTTP has chosen the expectation is to have 8280 as the port number in the curl and Request URL.
However, it is reflecting as **8243**.  This needs to fix as soon as possible. As a first time users or evaluators, most of the devs start on a tryout.

### Steps to reproduce:
![Screen Shot 2020-04-15 at 3 02 02 PM](https://user-images.githubusercontent.com/3397321/79393988-4a97b900-7f2b-11ea-95c3-97d164940be8.png)

![Screen Shot 2020-04-15 at 2 57 02 PM](https://user-images.githubusercontent.com/3397321/79393994-4c617c80-7f2b-11ea-92a8-08e06dd18fa8.png)

### Affected Product Version:
APIM 3.0.0 

### Environment details (with versions):
- OS: MacOS

**Comment by vanjikumaran** [comment]
This still exists in the APIM 3.0 and 3.1

**Comment by isharac** [comment]
@vanjikumaran 
We have fixed simillar issue for OAS 3.0 
We cannot fix this for swagger 2.0 due to it's limitation as stated in [1].

Did you get the issue for swagger 2.0?

**Comment by Krishanx92** [comment]
Stale issue, closing with above comment
