### ISSUE TITLE
bot detection email issue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#7918]
### Description:
I am following below URL
https://apim.docs.wso2.com/en/latest/learn/api-security/threat-protection/bot-detection/

the document says to configure email.
  -     
      extension:
            name: email
            namespace: sink
            properties:
              username: kalevivek11@gmail.com
              address: kalevivek11@gmail.com
              password: ******

but getting error:
![image](https://user-images.githubusercontent.com/10954248/79439265-3a96dc80-7ff2-11ea-9083-be7aee466024.png)

**Comment by Krishanx92** [comment]
@kalevivek11  It seems the issue happens due to bad credentials, could you please check if it's correct?

**Comment by kalevivek11** [comment]
@Krishanx92 credentials are perfectly fine

**Comment by hisanhunais** [comment]
@kalevivek11,
Could you please check by turning "**ON**", the  "**Allow less secure apps**" option of the gmail account?

**Comment by kalevivek11** [comment]
yes i have checked
