### ISSUE TITLE
The inline script in Prototype Implementation cannot be moved down.

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/product-apim#7921]
### Description:

When trying to edit the generated inline script in Prototype implementation by pressing "Enter" at the first and last lines they cannot be moved down, it is unresponsive. 

![Screenshot from 2020-04-16 21-23-24](https://user-images.githubusercontent.com/39290953/79478222-bdd32500-8028-11ea-9c9e-558c17d02c17.png)

**Comment by vithu30** [comment]
This issue needs to be fixed in 3.1.0 as well
