### ISSUE TITLE
SelfSign in DevPortal issue ver 3.0

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-apim#7946]
### Description:
After finishing the self-sign process I got error message:

> 'Message: Invalid callback URL found in the request.'

Note: User was created and I was able to login.

### Steps to reproduce:
Start APIM. No offset. The hostname is localhost.
On dev portal went over self-sign process. After click on the save button, I got error message.

### Affected Product Version:

V3.0
### Environment details (with versions):
- OS: Mac

**Comment by lpastor74** [comment]
Any progress?

**Comment by tharikaGitHub** [comment]
This issue is fixed now in APIM 3.0.0.
