### ISSUE TITLE
Admin Portal Conversion to React + REST improvements

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#7954]
# Description:
This is to keep track of the issues and new features/improvements regarding the Admin Portal revamping to REST+React app.
Let's add a comment to this issue with the details of the changes/improvements to be done.

**Comment by chathuranga95** [comment]
## Add an API to validate a given user has a particular role.

Scenario: When transferring ownership of an application to a user, that user should hold the role `Internal/subscriber`. ([Reference](https://apim.docs.wso2.com/en/3.1.0/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/))

A new API is needed for this type of scenario validation.

**Comment by fazlan-nazeem** [comment]
##  Modify subscription policies DTO to support GraphQL Query Analysis

A subscription policy will have two optional fields as following to support GraphQL query analysis.
1. MaxDepth
2. MaxComplexity

**Comment by chathuranga95** [comment]
### Need to have `IsEnableAnalytics` property on the admin settings API.

**Comment by tmkasun** [comment]
@tgtshanika @kavishkafernando  Shall we unpin this issue now?

**Comment by kavishkafernando** [comment]
+1 seems like majority of issues are fixed.

**Comment by Krishanx92** [comment]
Closing the issue since Admin Portal revamping to REST+React app is done
