### ISSUE TITLE
 last persistence state is not loading during the server startup.

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/product-apim#7955]
### Description:
State persistence is not loading the last snapshot during server startup

### Steps to reproduce:
1. Configure the event-processor.xml to enable state persistence in a single-mode setup. (here we are using FileSystemPersistenceStore but it is valid for DBPersistenceStore as well)

    <mode name="Single" enable="true">
        <persistence enable="true">
            <persistenceIntervalInMinutes>1</persistenceIntervalInMinutes>
            <persisterSchedulerPoolSize>10</persisterSchedulerPoolSize>
            <persister class="org.wso2.carbon.event.processor.core.internal.persistence.FileSystemPersistenceStore">
                <property key="persistenceLocation">cep_persistence</property>
            </persister>
        </persistence>
    </mode>

2. Create an advanced throttling policy in APIM as 5 requests per 1 hour and apply it as a resource level throttling policy of an API.

3. Invoke the API 5 times within an hour then restart the server after 1 minute (since persistenceIntervalInMinutes is set to 1 minute in event-processor.xml),
      **Expected behavior**:  after restarting the server API should be throttled out since there is no remaining quota available.
      **Actual behavior**: It was possible to invoke the API 5 times.
4. Invoke the API 3 time within an hour and then restart the server after 1 minute,
     **Expected behavior**: API should be able to invoke 2 times and then it should be throttled out
     **Actual behavior**: It was possible to call the API 5 times.

### Affected Product Version:
3.1.0, 2.6.0, 2.5.0

**Comment by nalakas** [comment]
fix for 3.1.0 https://github.com/wso2-support/carbon-event-processing/commit/3d8b2d9f7c7eab0d5f6782baad976ff390e071f7
