### ISSUE TITLE
Systemd support for WSO2

### ISSUE THREAD

**Issue by liepinshw** [wso2/product-apim#7966]
### Describe your problem(s)
Mainly for a enterprise or high valued systems are built on Red Hat or Centos. F.e. In RHEL 5 and 6,  automatic startup feature of RHEL through /etc/rc.d/init.d to run any script at system boot was used. Starting with RHEL 7 init is replaced by systemd and the prior method is now deprecated.
Some services are not so related to other components. f.e. apim analytics and can be automatically started up after system boot.
At the moment systemd script is not available in wso2 documentation.

### Describe your solution
WSO2 can be properly added to RHEL startup.

### How will you implement it
[Unit]

Description=WSO2 API Manager Server service
After=network.target

[Service]
Type=forking
PIDFile=<API-M_HOME>/wso2carbon.pid
#Environment=JAVA_HOME=/JAVAPATH (this or add to below execs)
ExecStart=/bin/bash -c 'JAVA_HOME=/JAVAPATH sh <API-M_HOME>/bin/wso2server.sh start
ExecReload=/bin/bash -c 'JAVA_HOME=/JAVAPATH sh <API-M_HOME>/bin/wso2server.sh restart
ExecStop=/bin/bash -c 'JAVA_HOME=/JAVAPATH sh <API-M_HOME>/bin/wso2server.sh stop
[Install]
WantedBy=multi-user.target

---

**Comment by tharindu1st** [comment]
@liepinshw  Thank you on the contribution on content. We will move this content into wso2 relevant documentations.

Thanks

**Comment by scara** [comment]
Hi @tharindu1st,
any update?
In late 2017 there was already something even here: https://github.com/wso2/puppet-base/pull/41.

Being WSO2 API Manager 4.0 released, any ETA to have an official _unit_ file?

TIA,
Matteo

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
