### ISSUE TITLE
Look and feel improvements to the add subscription full screen dialog

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#7968]
### Describe your problem(s)
1. Improve the look and feel of the Application -> subscriptions -> add subscriptions dialog box.
2. Don't make the above dialog full screen.

<img width="1680" alt="Screen Shot 2020-04-28 at 15 25 46" src="https://user-images.githubusercontent.com/3424539/80477737-18924800-896a-11ea-965d-8abbfc0b74e0.png">

**Comment by pubudu538** [comment]
Shall we add the version as well to the API?

**Comment by tmkasun** [comment]
And also , I think the title should be changed as 
`Subscribed API(s)` or an appropriate one

![image](https://user-images.githubusercontent.com/3313885/84101816-7c5d6580-aa2c-11ea-9365-1571cd532cd6.png)

**Comment by Krishanx92** [comment]
Fix https://github.com/wso2/carbon-apimgt/pull/8892
