### ISSUE TITLE
API level throttling for websockets cannot be provided from the UI

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-apim#7978]
### Description:
The option to set API level throttling for the websocket APIs, is not provided from the UI.

### Steps to reproduce:
N/A

### Affected Product Version:
Affected/3.1.0

### Environment details (with versions):
- OS: MacOS Mojave
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise.
