### ISSUE TITLE
Resetting the added values after change the thumbnail

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-apim#7979]
### Description:
When the user is trying to change the thumbnail in publisher after filling the rest of the design configurations and try to update the thumbnail, it's resetting the added values.

<img width="1200" alt="Design-config" src="https://user-images.githubusercontent.com/40847371/80859064-7a5cf580-8c7b-11ea-93c6-c171991c8495.png">
 

### Steps to reproduce:

1. Create an API and Publish
2. Click Design Configurations
3. Add the required details
4. Try to change the thumbnail and save the thumbnail

### Affected Product Version:
API 3.1.0

**Comment by chanaka3d** [comment]
This issue is fixed in the latest snapshot build.
