### ISSUE TITLE
Reduce dependency on Database while validating subscriptions.

### ISSUE THREAD

**Issue by jaadds** [wso2/product-apim#7981]
At the moment while validating tokens Gateway needs to call to KM component to get the subscriptions validated. KeyManager subsequently calls the underlying Databases, which makes it reliant on the Database. In case of an intermittent connectivity issue, or a Database failure, the Gateway traffic will fail.

Through the new feature, data needed to validate subscriptions will be kept in memory, while loading happens through a background task. Since validations are checked against memory, even in the case Database goes down, Gateway traffic wouldn't fail.

This will be done by 
- Introducing a new KeyValidationHandler which would load entries and validate against those.
- Abstracting out the method to load URITemplate so that those will be fetched from the memory instead from the DB

**Comment by kavishkafernando** [comment]
This has been fixed with #https://github.com/wso2/product-apim/issues/8224

**Comment by kavishkafernando** [comment]
Related PR : #https://github.com/wso2/carbon-apimgt/pull/8563
