### ISSUE TITLE
Per Token Quota are not getting displayed without APIs in store for tenants

### ISSUE THREAD

**Issue by TheNiron** [wso2/product-apim#7987]
### Description:
With a tenant user when you try to create an application without publishing any APIs, **Per Token Quota** drop down is displayed empty. (Only seen this behaviour with IS as Key manager setup)

### Steps to reproduce:
Setup IS as KM
Create a tenant.
Login with tenant to store
Create an application

![image](https://user-images.githubusercontent.com/32265029/80943237-5aa50900-8e04-11ea-8258-45ac5963d5e4.png)

### Affected Product Version:
v2.6.0

### Environment details (with versions):
- OS: MacOS
- Client: IS as Key manager
- Env (Database): Oracle for UserDB, RegistryDB, AMDB

**Comment by Krishanx92** [comment]
This is not reproduce in latest pack.
