### ISSUE TITLE
Accessibility issue in form labels

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#7988]
### Describe your problem(s)
When you go to the Create an API page, the first input field label is not clearly visible.

It's a UX best practice to autofocus the first input element so that the user can type in directly without any interaction. Since we use floating-label pattern inputs and the input field is already focused user has not seen the label and it's difficult to view the floated label. This can create an accessibility issue.

![image](https://user-images.githubusercontent.com/20179540/80942256-f6814580-8e01-11ea-907b-474bdc61ea27.png)

### Describe your solution

We can override Material style and make the floated label equal prominence as input. Also it will improve the general usability of the form as the input labels are clearly visible even after filling the fields.

![image](https://user-images.githubusercontent.com/20179540/80943526-0b130d00-8e05-11ea-825e-5d6651e99390.png)

### How will you implement it

---

**Comment by prasa7** [comment]
Fixed
