### ISSUE TITLE
Unable to upload xml/xsd document in API publisher

### ISSUE THREAD

**Issue by 321pranay** [wso2/product-apim#7993]
### Description:
In the API Publisher, I am unable to upload documents with extension xml, xsd

### Steps to reproduce:
Open API Publisher > Select Documents > Add new document > Select File > Upload xml or xsd file

### Affected Product Version:
3.0.0
3..0.1

### Environment details (with versions):
- OS: Linux and Windows
- Client: APIM

### Error in logs
DocumentIndexer No document associated to API

---

**Comment by 321pranay** [comment]
DocumentIndexer No document associated to API

**Comment by Sarangan0219** [comment]
You can only add documents with the extension of  `pdf , .html , .doc ,  .txt` .
As it is a documentation we are not expecting to provide .xml or .xsd files.

https://apim.docs.wso2.com/en/latest/learn/design-api/api-documentation/add-api-documentation/#add-documentation-using-a-file
