### ISSUE TITLE
tomcat/carbon/WEB-INF/web.xml can not be configured via deployment.toml

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#7996]
### Description:
Currently can't configure tomcat/carbon/WEB-INF/web.xml file using deployment.toml since this has not been templated.

### Steps to reproduce:
tomcat/carbon/WEB-INF/web.xml.j2 file has no placeholders to configure.

### Affected Product Version:
APIM3.0.0

### Environment details (with versions):
N/A

---
#### Related Issues:
N/A

#### Suggested Labels:
APIM3.0.0

**Comment by vithu30** [comment]
This config files needs to be templated in 3.2.0 as well
