### ISSUE TITLE
wso2 3.0.0 documentation issue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#8000]
go to link

https://apim.docs.wso2.com/en/3.0.0/learn/design-api/create-api/create-a-rest-api/

Point no 8
![image](https://user-images.githubusercontent.com/10954248/81070674-37ac4f00-8f01-11ea-88de-38ed3f508483.png)

here it is showing the option to add parameters but in the actual tool(publisher), it is not there

![image](https://user-images.githubusercontent.com/10954248/81070832-6fb39200-8f01-11ea-8b6a-89fded579b0a.png)

**Comment by HiranyaKavishani** [comment]
Issue is already fixed
