### ISSUE TITLE
Publisher theming capability to APIM 3.1.0

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#8010]
### Description:
Publisher Tenant theming is not there in the APIM 3.1.0 but it is available in the APIM 2.6.0. As per this documentation[1] tenant theme capability is available for the devportal.

[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/#tenant-theming

### Affected Product Version:
APIM 3.1.0

#### Suggested Labels:
APIM 3.1.0

**Comment by Krishanx92** [comment]
Fix in latest https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/overriding-the-publisher-portal-theme/
