### ISSUE TITLE
Websocket Sample for wscat

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#8011]
### Description:
wscat sample given with the query param model is not working as expected.

### Steps to reproduce:
Follow the steps in https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-websocket-api/#step-1-design-a-websocket-api

Try to execute the 
wscat -c ws://localhost:9099/echowebsocket/1.0.0?access_token=[accesstoken] 
and it will return "zsh: no matches found: " Error

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Arshardh** [comment]
Adding double quotes to the url with the query param sorts this issue. I will create an issue in docs-apim for this
