### ISSUE TITLE
Use webpack file hashing for browser cache eviction

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#8019]
### Describe your problem(s)

Currently, we have static bundle naming in the webpack output, Which could potentially cause a caching issue in the browser.
For example, If we update the bundles in background , Browser could load the cached resource from disk unaware of resource update in the server. 

### Describe your solution

This cache eviction could fine-tune with etags and `if-not-modified` headers. 
In another way, We can improve the cache invalidation by changing the bundle name with random hash code appending to the file name.

```javascript
module.exports = {
  //...
  output: {
    filename: '[name].[hash].bundle.js'
  }
};
```
Related webpack configs,

https://webpack.js.org/configuration/output/
https://webpack.js.org/guides/caching/

**Comment by chanaka3d** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/commit/1e0b9bf30befc23492e5a0cd8ec9174945a72ef1
