### ISSUE TITLE
Contents are truncated in deployment.toml  by running secure vault

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#8021]
### Description:
Deployment.toml configurations - all after [secret] section are loosing by running secure vault.

### Steps to reproduce:
1. Configure secret aliases in a middle position of the toml file. (Ex:- next to the keystore configs)
2. Run ciphertool.sh -Dconfigure
3. This will remove all the contents after secret alias section which we newly configured in the toml file.

### Affected Product Version:
3.0.0 , wum - 1586442818040

### Environment details (with versions):
- OS: MacOS

---

**Comment by msm1992** [comment]
This issue is already reported against cipher-tool at https://github.com/wso2/cipher-tool/issues/60.
As a workaround for the moment, we can add the [secret] config at the bottom of the deployment.toml

**Comment by nadeepoornima** [comment]
This issue is available in APIM 3.1.0 too.
