### ISSUE TITLE
Multiple scopes per resource does not work with basic and oauth authentication with JWT tokens.

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#8025]
### Description:
From, 3.2.0 onwards, we will be supporting multiple scopes per resource as an OOTB feature with this https://github.com/wso2/carbon-apimgt/pull/8476. However, multiple scopes per resources are not yet honored during basic authentication for both GraphQL and REST APIs. Need to change the logic in [here](https://github.com/wso2/carbon-apimgt/blob/40d22a843b3f0f0ff4b2a65f549dff6d3d2644be/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/utils/OpenAPIUtils.java#L86) to read multiple scopes from an operation. The same flow in OASParserUtils is used for JWT token scope validation as well. 

In addition, for GraphQL APIs when publishing, we need to add multiple scopes for the ScopeOperationMapping_ type in GraphQL SD local entry in [here](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/definitions/GraphQLSchemaDefinition.java#L169)

### Steps to reproduce:

Using Publisher REST api, create GraphQL or REST API with a resource/operation with multiple scopes.
Obtain a JWT token with each scope (Or using basic authentication) and try invoking, Invocation will be a success only for the first scope in scopes array of the operation.

## Affected Product Versions:

Latest master build with https://github.com/wso2/carbon-apimgt/pull/8476

**Comment by Arshardh** [comment]
Fixed with above PR
