### ISSUE TITLE
Fix the Active-Active deployment documentation with the correct throttling configurations - AM-3.1.0

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#8040]
### Description:

Add the missing steps for setting up throttling configuration HA All-in-one nodes. 

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/single-node/configuring-an-active-active-deployment/#step-7-configure-throttling

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

AM-3.1.0

---

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1354 | master
-- | --
https://github.com/wso2/docs-apim/pull/1352 | 3.1.0

**Comment by Mariangela** [comment]
@NipuniC , please create documentation related Git issues in https://github.com/wso2/docs-apim in the future.
