### ISSUE TITLE
Add option to enable Home Page only for logged in users.

### ISSUE THREAD

**Issue by kasun-bandara** [wso2/product-apim#8059]
### Describe your problem(s)
Assume a customer who doesn't have any public APIs enabled the Home page from store theming. So their public homepage will be displayed only the API description but without any APIs listed under them. Please find the below image for your reference. So for this scenario, API listing will not be visible on the homepage. 
![api-group](https://user-images.githubusercontent.com/30401379/81899074-a1022100-95d7-11ea-8668-4509e13d615d.png)

### Describe your solution
So shall we introduce an option in the defaultTheme configuration under landingPage section, to enable Home Page only for the logged in users? Then whole content in the Home Page will be visible to logged in users. 

---
#### Suggested Labels:
3.1.0

**Comment by chanaka3d** [comment]
The requested feature is provided by adding activeForAnonymous to landingPage attributes. The default is true. Set it false to hide the landing page to anonymous users.

landingPage: {
            activeForAnonymous: true,
}

Introduced following custom param to disable the public tenant store and redirect to a given url.

publicTenantStore: {
            active: true,
            redirectToIfInactive: 'https://wso2.com/api-management/cloud/',
        }
