### ISSUE TITLE
API store login failed intermittently - 401 Error: Unauthorized

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#8075]
### Description:

When the cacheHttpClient is enabled in the axis2_client.xml as follows in an all-in-one environment, the second Authentication call is failing with a 401 Unauthorized.

`<parameter name="cacheHttpClient">true</parameter>`

### Steps to reproduce:

1. Get a WSO2 API Manager 2.6 pack (WUM updated)
2. Add the following configurations in axis2_client.xml

```
<transportSender name="http" class="org.apache.axis2.transport.http.CommonsHTTPTransportSender">
    ...
    <parameter name="cacheHttpClient">true</parameter>
    <parameter name="defaultMaxConnectionsPerHost">500</parameter>
    <parameter name="maxTotalConnections">15000</parameter>
</transportSender>
<transportSender name="https" class="org.apache.axis2.transport.http.CommonsHTTPTransportSender">
    ...
    <parameter name="cacheHttpClient">true</parameter>
    <parameter name="defaultMaxConnectionsPerHost">500</parameter>
    <parameter name="maxTotalConnections">15000</parameter>
</transportSender>
```
3. Start the server and log-in to the Publisher and then sign-in to the Store (or vice-versa)
4. The second Authentication will result in 401 Unauthorized

### Affected Product Version:
AM-2.6.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
Not reproducible in 3.x series. Fix for 260 is pushed via wum
