### ISSUE TITLE
Devportal - Application Name becomes invisible for wider screens (Over 720p resolution)

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#8085]
### Description:
The application name become invisible in the application details page of the APIM 3.0.0 dev portal.

![unnamed](https://user-images.githubusercontent.com/11259401/82173647-9d2e1180-98eb-11ea-9b28-1c9f0fd9363b.png)

### Steps to reproduce:
- Go to the application details page.
- From the browser developer console, Change the resolution to 1080p.

**Comment by praminda** [comment]
Closing as this is already fixed in the master
