### ISSUE TITLE
Display Custom Properties in Developer Portal

### ISSUE THREAD

**Issue by gspadotto** [wso2/product-apim#8091]
### Describe your problem(s)
Custom properties can be assigned to APIs within the Publisher. This is handy in Dev Portal to search for APIs using the "propertyName:propertyValue" syntax in the "search" input field.
The only problem is that, unless the API developer notifies all possible API subscribers about the custom property names and values, an API Subscriber has no way of seeing examples of assigned properties and values from within the Developer Portal.

### Describe your solution
Add a section in which the names and values of (optional) Custom Properties are displayed in the detail page of a given API in DevPortal.

### How will you implement it

---
#### Suggested Labels:
DevPortal, ui

**Comment by harsha89** [comment]
Please make sure we keep the existing behavior as we don't show them in the UI for the existing properties. This is because users use these properties to add new handlers and etc based on the value. We may go with prefix based approached to only display the values if the prefix is present.
