### ISSUE TITLE
Self Signup Improvements

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#8092]
### Description:

1. Self-signup feature is now enabled by default for any tenant, security wise this is not idealas anyone would be able to signup for those devportals without the consent of owners. Therefore self signup should be disabled for new tenants.
2. When trying to do self signup for a tenant, tenant domain is always passed in as "carbon.super", instead the correct tenant domain should be passed.

### Affected Product Version:

3.1.0
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise
