### ISSUE TITLE
Document default thumbnail icon is not visible in unified search result listing

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#8097]
### Description:
Please not the $subject.

### Steps to reproduce:
- Deploy sample API
- Create an inline document for that API
- Search for that document in the search bar and press `Enter`

![image](https://user-images.githubusercontent.com/3313885/82277271-10e02500-99a5-11ea-9038-ac40afe02aed.png)

### Affected Product Version:
- Latest
- 3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chanaka3d** [comment]
<img width="929" alt="Screen Shot 2020-10-02 at 9 23 32 PM" src="https://user-images.githubusercontent.com/3424539/94943618-9e0bbc80-04f5-11eb-9860-9e7907906ff4.png">'
Fixed the styling issues also with the following commit.
