### ISSUE TITLE
APIs for Alerts

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#8108]
### Description:
Need the following APIs for Alerts when Analytics is enabled.
- GET /alert-types
- GET /alert-subscriptions
- PUT /alert-subscriptions
- DELETE /alert-subscriptions
- GET /alerts/{alertType}/configurations
- PUT /alerts/{alertType}/configurations/{configurationId}
- DELETE /alerts/{alertType}/configurations

Related : https://github.com/wso2/product-apim/issues/7954

**Comment by tharikaGitHub** [comment]
Closing as this issue is already fixed in master branch.
