### ISSUE TITLE
react component sharing across various projects.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#8128]
### Describe your problem(s)
When we want to reuse some store component in the publisher, we have to copy-paste the same UI component on the publisher side. But if we could have a way to reuse the same component from the store, we can keep the reusable component in one package and reuse it in different locations. Moreover, it enhances the maintainability and easy to use pre-defined component.

### Describe your solution
Lerna will resolve this issue and it facilitates the ability to share front end component with other packages. 

### How will you implement it

---

**Comment by hasuniea** [comment]
Doc - https://docs.google.com/document/d/15eVUGG4JG8iKqePAvmsUFVXO8N1Fydp1CCZl_J8h8EQ/edit?usp=sharing

PR - https://github.com/wso2/carbon-apimgt/pull/8561

**Comment by tmkasun** [comment]
At the moment (As per https://github.com/wso2/carbon-apimgt/pull/8561 ) we are exposing the source component in the npm module.

```
"main": "source/src/index.js",
```

To avoid some adverse effects in exposing the original source, We can use the bundled output as the main entry.
for example in [here](https://github.com/swagger-api/swagger-js/blob/master/package.json#L5) , swagger-api package.json pointing to `dist/index.js` as the main file.
We might need to create a separate entry and output parameters for this library file bundling.

Here are some articles on Library Authoring (using webpack)
- [How to publish a npm package?](https://www.robinwieruch.de/publish-npm-package-node)
- [Authoring Libraries](https://webpack.js.org/guides/author-libraries/)

**Comment by pahans** [comment]
@tmkasun  
+1 for providing a bundled output. IMO webpack using for this is an overkill just a babel transpile is enough like we did for [analytics repo](https://github.com/wso2/analytics-apim/tree/master/components/org.wso2.analytics.apim.widgets/CommonLib).

**Comment by tmkasun** [comment]
shall we keep this issue open, because i think we have some work left to do in this sharing improvements ?

**Comment by hasuniea** [comment]
@pahans 
Can you give a brief description of the babel transpile which you have done in analytics repo?

**Comment by pahans** [comment]
In analytics, we have moved common code to a package named `common-lib`. common lib don't need a webpack bundle since we don't use it independently anywhere. you can check the analytics implementation here. https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/CommonLib/package.json#L11

**Comment by prasa7** [comment]
Duplicate issue https://github.com/wso2/product-apim/issues/8321
