### ISSUE TITLE
Buttons, Links, Form elements should have accessible names

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8132]
### Describe your problem(s)

Buttons, Links, Form elements should have accessible names

### Describe your solution
[G211](https://www.w3.org/WAI/WCAG21/Techniques/general/G211.html) - Labels for inputs should have for attribute

Helper text for inputs should be linked through aria-describedby attribute

@@ If an icon has no accompanying text, consider using its hover text as its accessible name

**Comment by Krishanx92** [comment]
Currently on-hold. we consider this once theres any requirement.
