### ISSUE TITLE
Edit button disappears in Scope Mappings page in admin portal 

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-apim#8141]
### Description:
When we provide a considerably long list for the roles in the Scope Mapping in Admin portal, the Edit button disappears and no horizontal scroller found to scroll and locate the button.

See the attached screenshot.

<img width="1277" alt="scope_mapping" src="https://user-images.githubusercontent.com/3957104/82776984-56e82d80-9e6a-11ea-893a-7c95ba98a58a.png">

### Steps to reproduce:

1. Login into the admin portal
2. Go to Settings --> Scope Mappings from left navigation
3. Add a long list of roles by clicking the Edit button and then Save

Edit button then disappears and no longer able to edit again.

**Comment by Krishanx92** [comment]
This is revamped in the latest release hence resolve.
