### ISSUE TITLE
Rows with null in the admin panel

### ISSUE THREAD

**Issue by Krelion** [wso2/product-apim#8142]
### Description:
Rows with null in the admin panel

### Steps to reproduce:
Log in to admin console

### Affected Product Version:
wso2am-3.1.0 with latest updates 

### Environment details (with versions):
- OS: Windows 10
- Client: Google Chrome 81.0.4044.138

![image](https://user-images.githubusercontent.com/25265029/82782902-940ee880-9e87-11ea-8318-1e9267174b60.png)

**Comment by Krishanx92** [comment]
We have change the admin portal to react based app, hence this issue is no longer there.
