### ISSUE TITLE
Verify admin REST API scope descriptions

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#8146]
### Description
- The admin REST API has the following scopes with the corresponding descriptions shown in the table below.

| Scope | Description |
| :--------| :---------------|
| openid | Authorize access to user details |
| apim:tier_view | View tiers |
| apim:tier_manage | Update and delete tiers |
| apim:bl_view | View blocking conditions |
| apim:bl_manage | Update and delete blocking conditions |
| apim:mediation_policy_view | View mediation policies |
| apim:mediation_policy_create | Create mediation policies |
| apim:app_owner_change | Retrieve and manage applications |
| apim:app_import_export | Import and export applications |
| apim:api_import_export | Import and export APIs |
| apim:label_manage | Manage labels |
| apim:label_read | Retrieve labels |
| apim:monetization_usage_publish | Retrieve and publish Monetization related usage records |
| apim:api_workflow | Manage workflows |
| apim:bot_data | Retrieve bot detection data | 
| apim:tenantInfo | Retrieve tenant related information |
| apim:admin_operations | Manage API categories |
| apim:admin_settings | Retrieve admin settings |

- The above scope descriptions has to be verified.

**Comment by malinthaprasan** [comment]
| Scope | Description |
| :--------| :---------------|
| openid | Authorize access to user details |
| apim:tier_view | **View Throttling Policies** |
| apim:tier_manage | **Update and Delete Throttling Policies** |
| apim:bl_view | View Deny Policies|
| apim:bl_manage | Update and Delete Deny Policies |
| apim:mediation_policy_view | View Mediation Policies |
| apim:mediation_policy_create | Create Mediation Policies |
| apim:app_owner_change | Retrieve and Manage Applications |
| apim:app_import_export | Import and Export Applications |
| apim:api_import_export | Import and Export APIs |
| apim:label_manage | **Manage Microgateway Labels** |
| apim:label_read | **Retrieve Microgateway Labels** |
| apim:monetization_usage_publish | Retrieve and Publish Monetization related usage records |
| apim:api_workflow | Manage Workflows |
| apim:bot_data | Retrieve Bot-Detection data | 
| apim:tenantInfo | Retrieve Tenant related information |
| apim:admin_operations | Manage API Categories |
| apim:admin_settings | Retrieve Admin Settings |
