### ISSUE TITLE
Blank application names in Subscriptions page

### ISSUE THREAD

**Issue by tuholainen** [wso2/product-apim#8154]
### Description:
On the wso2am 3.1.0 and 3.0.0 devportal API subscribe section... in Subscriptions ( Applications Subscribed to this Api ) table some application names appear to be blank??

![image](https://user-images.githubusercontent.com/2714662/82840260-977f8f80-9eda-11ea-9104-2c1dbea6d458.png)

### Steps to reproduce:
Create more than 25 applications and subscribe one single API to all of them... 26th application shows the problem. 

### Affected Product Version:

wso2am 3.0.0 and 3.1.0 (/devportal)

### Environment details (with versions):
- OS: ALL
- Client: ALL
- Env (Docker/K8s): Linux server

---

**Comment by erangatl** [comment]
@tuholainen Thanks for reporting this issue, we'll look into this.

**Comment by msm1992** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/8883. hence closing,

**Comment by dumindurox777** [comment]
Observed similar issue on APIM 3.1.0. Therefore shall we fix that.
