### ISSUE TITLE
[Admin] Sort Icon doesn't display

### ISSUE THREAD

**Issue by jhatzenb** [wso2/product-apim#8167]
### Description:
All table with sort icon doesn't display well.

### Steps to reproduce:

- Download WSO2 APIM 3.1.0
- Start server
- Go to admin
- Login
- Go to :
  - Settings > Applications
![image](https://user-images.githubusercontent.com/42028146/82992623-af9cff00-9fff-11ea-90c0-5258aaf9135f.png)
  - Throttling Policiese >Black listed items
![image](https://user-images.githubusercontent.com/42028146/82992574-a01db600-9fff-11ea-939b-4c450959c707.png)
  - Analytics > API Availability
![image](https://user-images.githubusercontent.com/42028146/82992658-bcb9ee00-9fff-11ea-8407-b3ca998d4f7b.png)

### Affected Product Version:
WSO2 APIM 3.1.0

### Environment details (with versions):
- OS: RedHat
- Client: Firefox  76.0.1
- Env (Docker/K8s):

**Comment by AnuGayan** [comment]
Fixed in the latest version
