### ISSUE TITLE
[Admin] Custom Policies two No button in confirmation pop-up

### ISSUE THREAD

**Issue by jhatzenb** [wso2/product-apim#8168]
### Description:
When deleting a Custom Policies the confirmation pop-up contains two No buttons if cancelled one time

### Steps to reproduce:
- Download WSO2 APIM 3.1.0
- Start server
- Go to admin
- Go to Throttling Policies > Custom Throttling Policies
- Create a policy
- Click on delete button
- On confirmation pop-up clic No
- Click on delete button
- The confirmation pop-up contains two No buttons
![image](https://user-images.githubusercontent.com/42028146/82994017-c93f4600-a001-11ea-8244-82428ef330d5.png)

### Affected Product Version:
WSO2 APIM 3.1.0

### Environment details (with versions):
- OS: Red Hat
- Client: Firefox 76.0.1
- Env (Docker/K8s):

**Comment by Krishanx92** [comment]
Fixed with latest APIM-4.4.0
