### ISSUE TITLE
[APIM 3.1] No certificates/ Cipher suits set for port 9711 when primary user store  is configured LDAPS 

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#8169]
No certificates/ Cipher suits set for port 9711 when the primary user store is configured LDAPS connection. As a result, the following errors can be seen

When starting the product you will see the following exception

> TID: [-1] [] [2020-05-25 06:02:56,057]  WARN {org.wso2.carbon.databridge.agent.endpoint.DataEndpointGroup} - No receiver is reachable at reconnection, will try to reconnect every 30 sec
> TID: [-1] [] [2020-05-25 06:02:56,061] ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} - Error while trying to connect to the endpoint. Cannot borrow client for ssl://10.43.239.199:9711. org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://10.43.239.199:9711.
> 	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:145)
> 	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to data receiver :/10.43.239.199:9711
> 	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:50)
> 	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139)
> 	... 6 more
> Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
> 	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2041)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1145)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
> 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:765)
> 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
> 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
> 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
> 	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.sendBinaryLoginMessage(BinaryEventSender.java:47)
> 	at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:43)
> 	... 7 more
> 
> TID: [-1] [] [2020-05-25 06:02:56,061] ERROR {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Error while reading from the socket. javax.net.ssl.SSLHandshakeException: no cipher suites in common
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:321)
> 	at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1199)
> 	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:853)
> 	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:222)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
> 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:946)
> 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
> 	at org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver$BinaryTransportReceiver.run(BinaryDataReceiver.java:212)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

If you do the following command on port 9711
`openssl s_client -connect localhost:9711`

You will get the following result 
> CONNECTED(00000005)
> 4656350656:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1544:SSL alert number 40
> ---
> no peer certificate available
> ---
> No client certificate CA names sent
> ---
> SSL handshake has read 7 bytes and written 293 bytes
> Verification: OK
> ---
> New, (NONE), Cipher is (NONE)
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> Early data was not sent
> Verify return code: 0 (ok)

Affected version
APIM 3.1

**Comment by gusto2** [comment]
This exception is as well manifested in the version wso2am-2.6.0+1591023536458 (maybe even older, not tested)
