### ISSUE TITLE
Incorrect screenshot in the document for ResourceUsageperApplication API Statistics.

### ISSUE THREAD

**Issue by Madhu-NEC** [wso2/product-apim#8177]
As per the document **[1]** , the analytics data in WSO2AM 2.6.0 will be displayed in 5 columns i.e. **Application Name, API Name, API Version, Resource Usage, Resource Hit Count**.

But as per my investigation, the column support for **Resource Hit Count** was released in **wso/carbon-apimgt version 6.4.60** **[2]** and support for **API Version** was released in **wso2/carbon-apimgt version 6.4.230** **[3]** . WSO2AM 2.6.0 uses carbon-apimgt version 6.4.50. Hence the column support of API Version and Resource Hit Count should not be in WSO2AM 2.6.0. 

If my understanding is correct, then document **[1]** needs an update for correct screenshot.
**[1]** https://docs.wso2.com/display/AM260/Viewing+API+Statistics#ViewingAPIStatistics-ResourceUsageperApplication 
**[2]** https://github.com/wso2/carbon-apimgt/blob/v6.4.60/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js 
**[3]** https://github.com/wso2/carbon-apimgt/blob/v6.4.230/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/stats/apiCallType/js/stats.js

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
