### ISSUE TITLE
APIM [3.1.0] Introduce configurable property to restrict the token type selection 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#8187]
Currently, In the store portal  when creating an application 
 "Reference (opaque)" option and "Self-contained (JWT)" option both listed.

It will be great if we can introduce a configurable property with in the product itself to restrict the token type.

**Comment by Krishanx92** [comment]
Fix: https://github.com/wso2/carbon-apimgt/pull/8738
