### ISSUE TITLE
MG 3.1.0 analytics doc has <<TO-DO>> sections on 'Architecture' and 'How real-time publishing works'

### ISSUE THREAD

**Issue by wx-yz** [wso2/product-apim#8221]
### Description:
Microgateway 3.1.0 analytics doc, has <<TO-DO>> sections for 'Architecture' and 'How real-time publishing works' - https://docs.wso2.com/display/MG310/Analytics+for+Microgateway

![image](https://user-images.githubusercontent.com/57770159/83564371-7407a680-a4d1-11ea-9f7b-71a7619126cc.png)

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time, and the document has been obsolete
