### ISSUE TITLE
[3.1] SOAP to REST API operations have security disabled by default

### ISSUE THREAD

**Issue by himasha** [wso2/product-apim#8228]
### Steps to reproduce:
Try deploying a SOAP WSDL as a REST service as [1].
 Check the operations under resources section and security is set to disable, and you can invoke it without a token.
### Affected Product Version:
APIM 3.1 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Arshardh** [comment]
This was not reproduced in the latest pack.
