### ISSUE TITLE
Admin REST API swagger definition has to be updated with resource x-examples

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#8231]
The deprecated vendor extensions:x-wso2-request, x-wso2-response has to be removed and x-example has to be introduced with example requests. 
https://github.com/wso2/carbon-apimgt/wiki/Adding-Examples-for-REST-APIs 

Related to https://github.com/wso2/product-apim/issues/7954

**Comment by Arshardh** [comment]
x-wso2-request, x-wso2-response is removed but we still need to add x-examples

**Comment by vithu30** [comment]
For redocly changes, `x-code-samples` has been added to the latest REST APIs.
