### ISSUE TITLE
Frequent Coordination changes when multiple store queries are used to retrieve data in an Analytics HA environment

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#8236]
### Description:

I have a APIM-Analytics 2.6.0 setup where Analytics is a HA cluster. 

This issue comes when the dataset is high and trying to retrieve from publisher statistics (multiple store queries should sent frequently).

In this case, the active worker node will be unresponsive and passive will start working as active. But after some time unresponsive node will start working as active and throw some primary key violations issues, Hikari issues and remote client close issues.

JVM heap remains as same here during the incident and load average was high.

### Affected Product Version:
APIM Analytics 2.6.0

### Environment details (with versions):
- OS: RHEL 7 HA Analytics Cluster

---
#### Suggested Labels:
APIM-Analytics, 2.6.0

**Comment by dilini-muthumala** [comment]
Colsing the issue as the fixes are already available in the master branches:
https://github.com/siddhi-io/siddhi/commit/d74fb595ee423c2c274a5a55fb21abbaf6d6001a
https://github.com/siddhi-io/siddhi/commit/adfacc7e0fbb9316900871a68af43092e471d733
https://github.com/siddhi-io/siddhi/commit/68d0982b53c336b090f15524ff6d59c6c086820d
https://github.com/siddhi-io/siddhi/commit/521282202a6f7a5c912bfa6cb80ca9ecdff0ada3
https://github.com/siddhi-io/siddhi/commit/3321adfe2cc3fcdf931d457bfd1a3064b092bee2
https://github.com/siddhi-io/siddhi/commit/43b2db411c6aa597e6cb2e7d67ac10cc83cf78ec
https://github.com/wso2-support/siddhi-store-rdbms/pull/16/commits/22901d0eaf384748bcf218fc98849de128b931cf
