### ISSUE TITLE
API Key restriction for IP and Referrer

### ISSUE THREAD

**Issue by ChamodDamitha** [wso2/product-apim#8241]
### Describe your problem(s)
After issuing an API key for an application, it can be used by anyone to invoke an API 
subscribed to the application. Therefore, there should be a way to restrict who can use the token to avoid unnecessary invocations.

### Describe your solution

- IP restriction

Only the clients with specific IP addresses can use the token.
- HTTP Referer Restriction

Only the specific HTTP referrers can use the token.

### How will you implement it
When generating the API key, users are allowed to specify the allowed IP addresses or HTTP referrers. The specified IPs or referrers will be embedded in the token body as new claims (**permittedIP**, **permittedReferer**).

**Comment by ChamodDamitha** [comment]
Closed with https://github.com/wso2/carbon-apimgt/pull/8427/

**Comment by feyzollahi** [comment]
Hello!
I'm Mahdi.
please give a good example for this.
I don't understand it!!
I tested my localhost for IP and it give me forbidden!
please help me!
