### ISSUE TITLE
GrapthQL LInk not working

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#8243]
https://apim.docs.wso2.com/en/latest/learn/design-api/create-api/create-a-graphql-api/ 
under point no 3
under note "The file name can be any name, which is based on your preference."
is associated with link but that is not working

@dunithd @knightbeat @

**Comment by kalevivek11** [comment]
please accept this as bug

**Comment by HiranyaKavishani** [comment]
Closing the issue as this is not reproducing
