### ISSUE TITLE
[APIM 2.6.0] Unnecessary SOAP Action element in generated sequence template for SOAP 1.1

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#8245]
### Description:

Invalid xml element `<web:operationID>` is added as the root element of the generated sequence template when creating an API using SOAP 1.1
### Steps to reproduce:
1. Create and publish a SOAP API using either a file or a url.
2. Enable wirelogs and invoke the API.
3. Invalid sequence template will be shown in the gateway logs.
### Affected Product Version:

APIM-2.6.0

---

**Comment by binodmx** [comment]
Issue cannot be reproduced in the pack built using master branch. 
Fixed by https://github.com/wso2/carbon-apimgt/pull/9271.
