### ISSUE TITLE
Modify existing Human tasks to work with EI humantask-explorer webapp

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#8253]
### Describe your problem(s)
Current APIM default WS workflows cannot be approved or rejected using humantask-explorer webapp. APPROVE/REJECT buttons are not visible in the UI

![image](https://user-images.githubusercontent.com/4861150/83753542-1d909880-a688-11ea-89b6-eb43c09d2e84.png)
 
### Describe your solution
To get this working, we need to modify the .ht files and include <htd:renderings> elements

**Comment by chamilaadhi** [comment]
Please refer to https://docs.wso2.com/display/EI650/Claims+Approval+Task+Sample as a sample

**Comment by SahanHerath** [comment]
API Manager's admin dashboard can not be used to approve or reject workflow pending requests of WS workflow Executor. So we are approving or rejecting workflow requests from human task explorer. Application creation, Subscription creation, User sign up, Application key generation requests can be approved or rejected like this. API state change requests are approved/ rejected through bpmn-explorer like the past.
![Screenshot from 2020-06-26 03-42-09](https://user-images.githubusercontent.com/45681406/85801596-d5cdd000-b760-11ea-90f9-973db4efd86f.png)

#https://github.com/wso2/product-apim/pull/8395

**Comment by chamilaadhi** [comment]
Fixed in https://github.com/wso2/product-apim/pull/8473
