### ISSUE TITLE
Inconsistent Tenant files/folders in WSO2 APIM 3.1.0 

### ISSUE THREAD

**Issue by Kalpanayella** [wso2/product-apim#8257]
### Description:
The newly created tenants are missing registry.xml, synapse.xml, and a couple of directories under <APIM-HOME>/repository/tenants/{id}/synapse-configs/default/. Hence throwing warning message from google analytics handler -"_WARN - APIMgtGoogleAnalyticsTrackingHanlder Unable to load Google Analytics configuration using key: gov/apimgt/statistics/ga-config.xml_" when published API is invoked.  Though the registry entry is not missing. We can see it in the carbon console.
Also unable to implement API custom handlers as synapse.xml / registry.xml are not present in certain tenants.

The behavior is very inconsistent. As some time folders are created correctly but not other times. 
Please see the steps below to reproduce with APIM v3.1.0
 (note these are exact steps that are working fine in APIM v2.6.0)

### Steps to reproduce:
1. Start Wso2.
2. Go to carbon console, create a tenant, and then log in to the publisher with credentials of this tenant. At this point, I see that <APIM-HOME>/repository/tenants/1/synapse-configs/default contains multiple directories and two XML files: registry.xml and synapse.xml.-Not 100% consistence.
3. Now stop WSO2 and start it again.
4. Create another tenant in carbon console, and log in to the publisher with the credentials of this second tenant. This time <APIM-HOME>/repository/tenants/2/synapse-configs/default contains only sequence directory, all the other directories and XML files are missing.
Again, this is not 100% consistent, sometimes tenant 2 is created correctly, and only after a while trying to create another tenant you see that it has missing files.

### Affected Product Version:
APIM 3.1.0

### Environment details (with versions):
OS: Windows/CentOS

---
#### Suggested Labels:
Priority/Highest/Urgent

**Comment by AnuGayan** [comment]
Fixed in the latest version
