### ISSUE TITLE
APIM Publisher Usability Issue in Slow Networks

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/product-apim#8259]
### Description:
While creating an API depending on the network situation, resources under the 'Manage' section take time to appear under resources without any indication of resource loading. If the user publishes the API before resources appear, swagger definitions are not saved/published. All the swagger changes will also be lost if published at this point. 

### Steps to reproduce:
1. Add network throttling policy in the browser. (Slow 3G in chrome)
2. Create a new API using the publisher.
3. Under the 'Design' section import a swagger that contains a considerable amount of resources to create resources.
4. Under 'implement' section backend URL endpoint can be added as any random endpoint.
5. When the network is really slow, resources under the 'Manage' section take time to appear under resources.
6. Publishes the API before resources appear.

### Affected Product Version:
APIM 2.2.0

#### Suggested Labels:
APIM 2.2.0

**Comment by Krishanx92** [comment]
Not applicable for latest since resolve.
