### ISSUE TITLE
APIM 3.1.0 installation guide link on Analytics page return 404 not found

### ISSUE THREAD

**Issue by wx-yz** [wso2/product-apim#8261]
### Description:
Installation Guide in this page is a 404 - https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/

### Steps to reproduce:

1. Go to docs.wso2.com, and click on APIM 3.1.0 docs
2. Click on Analytics in bottom right hand corner
3. Click on 'Setup and Configuration' under Analytics
4. Click on 'Configure APIM Analytics'
5. Click on 'Installation Guide' (1st step) under Quick Setup

Gives page not found error

**Comment by AnuGayan** [comment]
This documentation has been revamped and fixed the issue for the latest APIM releases

**Comment by wx-yz** [comment]
@AnuGayan This issue is still not fixed. I just tried the repro steps and it's still giving me a 404. I'm specifically talking about APIM 3.1.0 here. Not the latest version.

**Comment by AnuGayan** [comment]
Hi @wx-yz We have fixed this from the above PR,
Please check on an incognito browser window.
