### ISSUE TITLE
Field name not preserved when we use multipart/form-data file upload.

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim#8270]
### Description:
APIM 2.6.0 is not sending the name when there is a content-aware mediator is present in the mediation sequence.

### Steps to reproduce:
Create an API with the resource that has the following resource.
```
Parameter Name : docpdf
Parameter Type : formData
DataType : file
```

Then use a content-aware mediator, for example, a log full mediator as below.
```
<log level="full">
<property name="IN_MESSAGE" value="IN_MESSAGE"/>
</log>
```
Enable the wirelog and in the wirelog name is not preserved in the log that is sent from APIM to the backend. We have observed the following.
`TID: [-1] [] [2020-06-08 09:52:36,818] DEBUG {org.apache.synapse.transport.http.wire} -  HTTP-Sender I/O dispatcher-2 << "Content-Disposition: form-data; name="file"; filename="Migration_Steps.pdf"[\r][\n]" {org.apache.synapse.transport.http.wire}`

### Affected Product Version:
APIM 2.6.0

A similar issue can be found here[1]

[1] https://github.com/wso2/product-ei/issues/5109

**Comment by npamudika** [comment]
Public fix https://github.com/wso2/wso2-axis2/commit/a2d3999a57649155e7369432d2cef2c65b0e06ea

**Comment by dushaniw** [comment]
Can be reproduced in API-M 2.5.0 latest wum/u2 updated distribution
