### ISSUE TITLE
Internal server error when importing an API Project due to validateKeyManagers function

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#8294]
### Description:
When importing an API Project that was created using "apictl init" command, an error occurs from APIM as below.
![keymanagererror](https://user-images.githubusercontent.com/25246848/84283273-6e0c6800-ab58-11ea-96ba-172d111a9bc4.png)

### Steps to reproduce:
1. Create an API Project using APICTL using the command below. 
```
apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json
```

2. Try to import it to an environment using the command below.
```
apictl import-api -f <path-to-api-project>/Petstore -e <env-name>
```

3. Then you will receive an internal server error.

![apictlerror](https://user-images.githubusercontent.com/25246848/84284150-73b67d80-ab59-11ea-9f49-3bfcb30eda9b.png)

### Affected Product Version:
API Manager 3.2.0-m1 (Tested with APICTL 3.1.2)

### Environment details (with versions):
- OS: Ubuntu 18.04.4 LTS

**Comment by malinthaprasan** [comment]
"keyManagers" : ["all"],
