### ISSUE TITLE
Documenting the available REST api to upload usage data from the MGM

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/product-apim#8302]
### Description:
A REST API is available to manual upload API usage information to the API analytics server without enabling the upload file task in the MGW.  This is an important capability available in the product to allow MGW's running in a locked down environment to sync their usage data with the API Analytics server. This capability needs to be updated in the below document.
https://docs.wso2.com/display/MG310/Analytics+for+Microgateway

### Content Positioning in Documentation:
https://docs.wso2.com/display/MG310/Analytics+for+Microgateway
- Link:

- Heading (& Step):

- Any other reference:

---
#### Related Issues:
Mail Thread - subject:[API Manager analytics] Working with MGW API usage data in a lockdown environment

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
