### ISSUE TITLE
Performance and Capacity Planning documentation for WSO2 APIM v3.1.0

### ISSUE THREAD

**Issue by Kalpanayella** [wso2/product-apim#8313]
### Description:
 I can see there is a Performance and Capacity Planning documentation for the previous version (APIM v2.6.0) : [link](https://docs.wso2.com/display/AM260/WSO2+API-M+Performance+and+Capacity+Planning) . But, I could not find Performance and Capacity Planning documentation for WSO2 API v3.1.0. Can you please share the documentation link for the same? We would need this for planning/evaluating the product for our use cases.

### Content Positioning in Documentation:
Currently, it is available for APIM 2.6.0 here: https://docs.wso2.com/display/AM260/WSO2+API-M+Performance+and+Capacity+Planning

#### Suggested Labels:
Priority/highest/urgent

**Comment by samgnaniah** [comment]
This is fixed.

https://apim.docs.wso2.com/en/3.1.0/install-and-setup/setup/deployment-best-practices/performance-test-results/
