### ISSUE TITLE
[DevPortal] Create new application UX issue

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#8336]
### Description:
Deleting all the applications of a particular user gives a UX issue in the Create Application button.

![image](https://user-images.githubusercontent.com/1591316/84587975-4d3a6000-ae41-11ea-9afa-25ecb8b42a73.png)

### Steps to reproduce:
1. Login to the DevPortal
2. Delete all the applications of the user

**Comment by kavishkafernando** [comment]
Cannot reproduce in latest pack. 
<img width="1678" alt="Screen Shot 2020-07-17 at 12 36 13 PM" src="https://user-images.githubusercontent.com/19324135/87758487-2a2d1280-c82a-11ea-8842-a88bbf72de8b.png">
