### ISSUE TITLE
API rating should show in text in the list view

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8342]
### Describe your problem(s)

Should display the rating in text - **4 of 5**

![image](https://user-images.githubusercontent.com/20179540/84626172-4aec0a80-af02-11ea-95b7-3230bd0fd0ff.png)

[ARIA10 - Using aria-labelledby to provide a text alternative for non-text content](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA10.html)

### Describe your solution

Should display in text too like in overview

![image](https://user-images.githubusercontent.com/20179540/84626519-d82f5f00-af02-11ea-8308-8b341a5d3eb7.png)

![image](https://user-images.githubusercontent.com/20179540/84626587-fb5a0e80-af02-11ea-8dd7-4f2a8899b627.png)

### How will you implement it

---

**Comment by chanaka3d** [comment]
Fixed as the following commit
<img width="551" alt="Screen Shot 2020-10-03 at 6 54 10 AM" src="https://user-images.githubusercontent.com/3424539/94980225-4ac15a80-0545-11eb-966f-3417e60aaa4c.png">
