### ISSUE TITLE
[APIM 3.1.0] Issue when connecting to analytics after running profile optimization

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#8353]
### Description:
The profile optimization scripts are still containing the outdated configs related to analytics. After executing the profile optimization for components, Gateway, Publisher and Dev Portal, the existing configuration under **[apim.analytics]** gets replaced with the available configuration in the optimization scripts. The config **[[apim.analytics.url_group]]** gets replaced with the **[[apim.analytics.analytics_node]]**. 

Need to fix this in the profile optimization scripts, gateway-worker.toml, api-publisher.toml and api-devportal.toml resides in the <API-M_HOME>/repository/resources/conf/deployment-templates/ accordingly.

### Affected Product Versions:
wso2am-3.0.0, wso2am-3.1.0

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
