### ISSUE TITLE
Re-indexing Existing Data -Wso2am v2.6.0 onwards

### ISSUE THREAD

**Issue by Kalpanayella** [wso2/product-apim#8371]
### Description:
I see reindexing the existing data that are already stored in databases configured for WSO2 API-M Analytics documentation/steps to follow in Wso2am v2.5.0. I could not find documentation or steps for the same from  Wso2am v2.6.0 onwards. Could you please share or provide information on how to achieve reindexing of the existing data to reduce the growing size of databases.

### Content Positioning in Documentation:

https://docs.wso2.com/display/AM260/Re-indexing+Existing+Data

#### Suggested Labels:
Priority/Normal

**Comment by AnuGayan** [comment]
Analytics data reindexing is not available in APIM 2.6.0 onwords
