### ISSUE TITLE
Dev Portal left menu panel expand button not visible.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#8375]
### Describe your problem(s)
The left menu panel is collapsed and the expand button is at the bottom of the page. It is required to scroll the page to find the button. 
This could affect the ux.

![Screenshot - 2020-06-17T120758 335](https://user-images.githubusercontent.com/10165411/84864585-83235280-b094-11ea-9460-6ba8b7534d19.png)

### How will you implement it

---

**Comment by tmkasun** [comment]
This is fixed in the latest master branch code hence closing the issue

![image](https://user-images.githubusercontent.com/3313885/94302015-2aaffb00-ff89-11ea-8e98-a698be2d193c.png)
