### ISSUE TITLE
Application level security shows that the API is OAuth2 protected even though all the resources are unsecured

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#8382]
### Description:
Even if we remove security from all the resources, Still in the Runtime configurations, OAuth2 option is selected indicating that the API is OAuth2 protected.

### Steps to reproduce:
1. Create an API
2. Remove security for all the resources
3. Check the Runtime Configurations tab 

### Affected Product Version:
3.0.0

**Comment by chamilaadhi** [comment]
fixed in 3.2.0 https://github.com/wso2-support/carbon-apimgt/pull/2155
