### ISSUE TITLE
MS SQL - Devportal API v1 /applications GET limit parameter is not working 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#8387]
### Description:
When APIM 3.1.0 setup with MS SQL as database and invoke the GET API api/am/store/v1/applications with limit parameter, getting all the applications in the response without respecting the limit parameter. Also in the UI when there are applications more than 9 pagination is not coming.

### Steps to reproduce:

- Setup APIM with MS SQL database.
- Invoke api/am/store/v1/applications API with setting limit parameter 

### Affected Product Version:
APIM 3.1.0

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2148

**Comment by chamilaadhi** [comment]
Fixed in the public branch with https://github.com/wso2/carbon-apimgt/pull/8854
