### ISSUE TITLE
[Publisher] Resources page become slow for APIs created using FHIR swaggers

### ISSUE THREAD

**Issue by isuruh15** [wso2/product-apim#8388]
### Description:
For the APIs created using swagger files which defines an FHIR resource, the Resources page of that particular API takes a long time to completely loaded. 
(FHIR swaggers have reference definitions that are 7,8 levels of depth.)
Sometimes the UI become unresponsive. 
![image](https://user-images.githubusercontent.com/25496974/85015865-5c454900-b186-11ea-91ec-9d90f67263e1.png)

### Steps to reproduce:
Create an API using a swagger file which defines a FHIR API.
Try to go to Resources page. 

### Affected Product Version:
Affected/3.2.0

### Environment details (with versions):
- OS: Linux, MacOS

#### Suggested Labels:
React/UI

**Comment by isuruh15** [comment]
sample fhir swagger is attached
[ExplanationOfBenefit-swagger.txt](https://github.com/wso2/product-apim/files/4838330/ExplanationOfBenefit-swagger.txt)

**Comment by wh0am111** [comment]
have

> ### Description:
> For the APIs created using swagger files which defines an FHIR resource, the Resources page of that particular API takes a long time to completely loaded. (FHIR swaggers have reference definitions that are 7,8 levels of depth.) Sometimes the UI become unresponsive. ![image](https://user-images.githubusercontent.com/25496974/85015865-5c454900-b186-11ea-91ec-9d90f67263e1.png)
> 
> ### Steps to reproduce:
> Create an API using a swagger file which defines a FHIR API. Try to go to Resources page.
> 
> ### Affected Product Version:
> Affected/3.2.0
> 
> ### Environment details (with versions):
> * OS: Linux, MacOS
> 
> #### Suggested Labels:
> React/UI

have you reslove this question?

**Comment by isuruh15** [comment]
This is not reproducing in APIM-4.2.0

**Comment by Krishanx92** [comment]
Closing with above comment
