### ISSUE TITLE
Show API attributes with a special prefixes in Developer portal

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#8389]
### Describe your problem(s)

API Publisher wants to communicate some information to the App developer which couldn't do by the existing API propertied.

### Describe your solution

Define a new prefix...like `display` that will work as a flag to show those properties (with that prefix) to appear in the API overview page of the Devportal
```
ex: display_region=US
```

### How will you implement it

---

**Comment by tmkasun** [comment]
Related issue : https://github.com/wso2/product-apim/issues/8091

**Comment by chanaka3d** [comment]
The attribute to display need to add with __display suffix as follows.

<img width="1215" alt="Screen Shot 2020-09-29 at 8 48 38 PM" src="https://user-images.githubusercontent.com/3424539/94578540-7d452c00-0295-11eb-9ca6-7282e53d9744.png">


From devportal API overview page, it will be displayed as follows.

<img width="499" alt="Screen Shot 2020-09-29 at 8 49 08 PM" src="https://user-images.githubusercontent.com/3424539/94578654-9cdc5480-0295-11eb-800d-4dec5341bfc9.png">

**Comment by gspadotto** [comment]
How do I declare additional properties that should be visible on the dev portal **_using apictl import_**?

I have tried adding: 
```yaml
additionalProperties:
   mypropertyone__display: valueone
   mypropertytwo__display: valuetwo
```
to **api_template.yaml**, but I do not see them in the Publisher and - of course - they are not shown in the DevPortal. 

My goal is to publish an API with additional properties shown in the DevPortal within a CI/CD pipeline (thus using apictl)

APIM 3.2.0 - Update Level 137
apictl Version: 3.1.4 Build Date: 2020-07-31 04:23:40 UTC
