### ISSUE TITLE
Subscriptions are getting updated when saving without selecting any tiers for APIs in CREATED state.

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#8394]
### Description:
Allows to save without selecting any subscription plan for APIs in CREATED state. But it automatically sets the previously selected one. 

### Steps to reproduce:
1. Create a API
2. In Subscription uncheck all the selected ones.
3. Save

### Affected Product Version:
3.0.0
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8247
