### ISSUE TITLE
Add Custom Endpoint header support

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#8399]
### Describe your problem(s)
Add Custom Endpoint header support.

### Describe your solution

- Add a new section in endpoints page where an API creator can add Custom headers.
- They will be key value pairs - header name and header value
- If the value needs to be encoded, the API creator will have to provide the value as 'secret:$value' . This secret will be encrypted when storing.

**Comment by Krishanx92** [comment]
Currently on-hold this if we consider this once theres any requirement.
