### ISSUE TITLE
Template the qpid-config.xml to provide the ability to configure heartbeat values

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-apim#8434]
### Describe your problem(s)
qpid-config.xml file is not templated in 3.1.0  ( no .j2 file exists ) and hence below heart beat values cannot be configured.
```
<heartbeat>    
    <delay>60</delay>
    <timeoutFactor>2.0</timeoutFactor>
</heartbeat>
```

**Comment by tharindu1st** [comment]
templated with 
[qpid.heartbeat]
delay = 60
timeout_factor = 2.0
