### ISSUE TITLE
Sign APIKey JWT using a different keystore other than default

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#8448]
### Describe your problem(s)
In APIKey feature,  JWT is always signed using the default Keystore in devportal. There could be usecase, where apikey needs to be signed using a different keystore for different reasons.

## Describe your solution
Provide a config to give the private key alias in api-manager.xml to sign the APIKey.

**Comment by dushaniw** [comment]
@Ketharan Have we added this improvement to laster master?

**Comment by malinthaprasan** [comment]
Fixed from PR https://github.com/wso2/carbon-apimgt/pull/9485.

**Comment by wasuradananjith** [comment]
> Fixed from PR [wso2/carbon-apimgt#9485](https://github.com/wso2/carbon-apimgt/pull/9485).

A small correction. This is fixed via https://github.com/wso2/carbon-apimgt/pull/9256 in master, not with https://github.com/wso2/carbon-apimgt/pull/9485.
