### ISSUE TITLE
Error when trying to edit Shared Scope while logged in as a non admin user

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#8456]
### Description:
Getting following error when updating a shared scope as a non-admin user.
```
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

![auth_error](https://user-images.githubusercontent.com/28379317/85660164-ea638700-b6d2-11ea-8498-9d261c4bd2d5.png)

I think Shared scope editing should be disabled for non-admin users.

### Steps to reproduce:
1. Create user 'publisher' with Internal publisher role.
2. Try to update a shared scope

### Affected Product Version:
apimgt 6.7.31-SNAPSHOT

### Environment details (with versions):
- OS: Ubuntu 16.04
- Client:
- Env (Docker/K8s):

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8843
