### ISSUE TITLE
Error when trying to add Shared scope with empty display name

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#8460]
### Description:
![error](https://user-images.githubusercontent.com/28379317/85679991-87c8b600-b6e7-11ea-8a14-038b580d5097.png)

Seems there is a backend validation to check whether the display name field is empty [1]. But we are missing a UI validation here. 

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ScopesApiServiceImpl.java#L102-L105

### Steps to reproduce:
1. Go to scopes UI in publisher portal.
2. Try to add a scope with empty display name

### Affected Product Version:
apimgt 6.7.31-SNAPSHOT

### Environment details (with versions):
- OS: Ubuntu 16.04
- Client:
- Env (Docker/K8s):

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8843
