### ISSUE TITLE
Open API 3 (Swagger 3) definitions not working as expected

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#8466]
### Description:
When uploading openapi-3.0.0 API definition in wso2am-2.2.0 in the latest wum pack(wso2am-2.2.0+1592499585729) the resource response payload got displayed in publisher's swagger UI but didn't get displayed in the store swagger UI. But this issue did not occur in the wso2am-2.2.0 vanilla pack

### Steps to reproduce:
1. Create a new API with swagger 3 definitions.
2. Import attached swagger 3 definitions in newly created API.
3. Confirm it has a request payload from swagger editor under "Design->Edit Source".
4. Publish the API with a dummy endpoint.
5. View API console in the API store.
6. Request Body is not visible in TryIt view.
![image](https://user-images.githubusercontent.com/20519000/85728288-667ebe80-b715-11ea-8d33-87c23ca44e29.png)

### Affected Product Version:
wso2am-2.2.0+1592499585729

**Comment by shilmyhasan** [comment]
Fixed in https://github.com/wso2-support/carbon-apimgt/pull/2158/
