### ISSUE TITLE
Publisher fails to load on windows 

### ISSUE THREAD

**Issue by pahans** [wso2/product-apim#8469]
### Description:
$subject 
this is for latest master(75a08c19d4d9fd31cd5b4116e42c27e52d351fb6) branch. please refer the below screenshot.

![image](https://user-images.githubusercontent.com/1552869/85768994-38aa7180-b737-11ea-8379-e734c3fc6a99.png)

### Environment details (with versions):
- OS: WIndows
- Client:MS EDGE
- Env (Docker/K8s):

---

**Comment by pahans** [comment]
tested this on windows/chrome. seems its a MS edge specific issue

**Comment by RakhithaRR** [comment]
I tested the same on Windows 10 but didn't come across any issues in publisher or devportal.

**Comment by pahans** [comment]
closing based on above comment
