### ISSUE TITLE
Customizing JWT generation not working in WSO2 APIM 3.1.0

### ISSUE THREAD

**Issue by dsmohan** [wso2/product-apim#8476]
I tried to implement the steps given in WSO2 3.1.0 documentation (https://apim.docs.wso2.com/en/3.0.0/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/) for customizing JWT.

As given in the documentation, I created the custom JWT generator java class, generated the jar and placed it under WSO2 Home/repository/components/lib folder. Did the necessary configurations in deployment.toml for enabling JWT and restarted the server.

When i hit an API with the bearer token, i am getting the X-JWT-Assertion header in the carbon logs but when i decode it, it doesn't contain the custom claims that i added in the custom JWT generator java class.

It contains the standard claims as seen in the below image and not the custom claims that were added (current_timestamp, message).

Need suggestions on this as i have followed the steps given in the documentation.

![image](https://user-images.githubusercontent.com/66669898/85862282-2edc4900-b7df-11ea-9f7a-64b321fc5c4a.png)

**Comment by pttse** [comment]
@dsmohan  Did you find an alternative solution for this issue? It seems we've got a similar problem here. 
Many thanks in advance!

**Comment by dsmohan** [comment]
@pttse No, I didn't find any solution for this yet. I was able to follow the steps (https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/) and successfully customized the JWT token when token type is Opaque in APIM 3.1.0, but I wasn't able to execute the steps given for customizing when token type is JWT.
Have raised the issue here: https://github.com/wso2/product-apim/issues/8601
