### ISSUE TITLE
IMAGE_URL is missing on IDP and SP_APP tables after migration

### ISSUE THREAD

**Issue by warunap** [wso2/product-apim#8488]
### Description:
The document needs to be updated with db migration script to add the mentioned column  to required tables

### Content Positioning in Documentation:

- Link: https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310/

- Heading (& Step):

- Any other reference:

---

**Comment by HiranyaKavishani** [comment]
Closing the issue as this has been included in the identity migration script
