### ISSUE TITLE
Invalidate gateway cache when blocking subscriptions while using Opaque tokens

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#8491]
### Describe your problem(s)
When Opaque tokens are used to invoke APIs, they are cached in the Gateway. Therefore if a subscription is blocked from the Publisher portal, the blocking doesn't take effect immediately until the cache is expired.

### Describe your solution
When JWT tokens are used and a subscription is blocked from the Publisher portal, the blocking takes effect immediately. It is suggested to implement this behavior for the Opaque tokens as well in away that gateway cache is invalidated when a subscription is blocked. 

#### Suggested Labels:
3.0.0
3.1.0

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise.
