### ISSUE TITLE
Provisioning Out-of-Band OAuth2 Clients with existing client credentials

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#8499]
### Describe your problem(s)
While provisioning an OAuth2 Client which already has it's client-id/client-secret values, the API-Manager doesn't provide the capability to register clients with defined credentials. When external IDPs are used this becomes a limitation. 

### Describe your solution
Using the existing Admin services to provide the capability of providing client credentials while provisioning Out-of-Band OAuth2 Clients.

**Comment by uvindra** [comment]
@lkokila can you elaborate a bit more on this by explaining the use case?

**Comment by lkokila** [comment]
@uvindra, the use case is regarding OAuth2 Clients which are managed by external Identity Providers (IDP). When they are provisioned into the API-Manager, the facility needs to be there to register them with the client-id/client-secret values generated by the external IDP. This relates to the details available in the following document [1] on Provisioning Out-of-Band OAuth2 Clients. When it comes to validating JWTs generated by the external IDPs [2], the OAuth2 Client having the existing client-id/client-secret values will be important. 

[1]. https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/provisioning-out-of-band-oauth-clients/#provisioning-out-of-band-oauth2-clients

[2]. https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/access-token-types/jwt-tokens/#secure-apis-using-jwt-self-contained-access-tokens
