### ISSUE TITLE
Test console page is not working for API product

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#8504]
### Description:
When click on the test console left pane, test initialize page is not working

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
In the current master code, `Test console` menu is not visible for API products , But I think we need to provide the test console for API products as well , hence will keep this issue open

![Uploading image.png…]()

**Comment by tmkasun** [comment]
I think we can't change lifecycle state of an API product (change to prototyped) hence providing testing capability is not straightforward. @uvindra Is it worth giving a test console for API products?

**Comment by Krishanx92** [comment]
Fixed with latest product, hence closing.
