### ISSUE TITLE
Test console support for grapghql APIs.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#8508]
### Describe your problem(s)
At the moment, the publisher test console doesn't support graphql APIs. Test APIs(testconsole) should be in prototype state. But currently, we implemented a way like engaged graphql handlers only for the published APIs. 

### How will you implement it

---

**Comment by malinthaprasan** [comment]
https://www.npmjs.com/package/graphiql was added in APIM 3.2.0
