### ISSUE TITLE
 [APIM 2.6.0] Default API not work with Mutual SSL enable

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#8513]
The default API does not work with Mutual SSL enabled in APIM 2.6.0 version
we have fixed this behaviour for APIM 3.1.0 version. Please refer issue [1] for more information
need to backport the same for APIM 2.6.0 version

[1] https://github.com/wso2/product-apim/issues/7418

**Comment by dushaniw** [comment]
Will be fixed with https://github.com/wso2/product-apim/issues/7418

**Comment by dushaniw** [comment]
same issue https://github.com/wso2/product-apim/issues/7418
