### ISSUE TITLE
[APIM-3.2.0] - Unable to create scopes

### ISSUE THREAD

**Issue by Meruja** [wso2/product-apim#8531]
### Steps to reproduce:
In a distributed setup, cannot able to create scope. Getting "Scope name already used by another API" error for all random names.
<img width="433" alt="Screen Shot 1399-04-11 at 4 21 39 PM" src="https://user-images.githubusercontent.com/28688743/86314676-df19d980-bc45-11ea-890e-5a4ce98a60ae.png">
<img width="395" alt="Screen Shot 1399-04-11 at 4 21 19 PM" src="https://user-images.githubusercontent.com/28688743/86314684-e345f700-bc45-11ea-9bac-e8911c2a202b.png">
<img width="436" alt="Screen Shot 1399-04-11 at 4 20 59 PM" src="https://user-images.githubusercontent.com/28688743/86314691-e5a85100-bc45-11ea-9d45-b0357cbd35a4.png">

### Affected Product Version:
3.2.0 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
Bug
Priority/Normal

**Comment by Arshardh** [comment]
Similar issue: https://github.com/wso2/product-apim/issues/8536

**Comment by Arshardh** [comment]
Fixed with https://github.com/wso2/product-apim/pull/8577

**Comment by Sirdara** [comment]
Because there is somewhere that has that scope. I experienced this too, it existed in Api Definition.

`security:
        - default:
            - testScrope`
