### ISSUE TITLE
Documentation validation always produces 404 in the Publisher v1 REST API 

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#8532]
### Describe your problem(s)
When you invoke Publisher v1 POST /apis/{apiId}/documents/validate it always issues 404.

### Steps to reproduce
1. Try to validate a document name for a particular API using the below cURL request.
   ```
   curl -L -X POST 'https://localhost:9443/api/am/publisher/v1/apis/e1e8572e-db28-425c-9a57-af5094cad2bd/documents/validate?name=mydoc' -H 'Authorization: Bearer e2bd2064-c24b-3c86-92d5-690db6e5eb7b' -k -I 
   ```
2. You will receive 404 error code.
   ```
   HTTP/1.1 404 
   Date: Thu, 02 Jul 2020 03:47:25 GMT
   Content-Length: 0
   Server: WSO2 Carbon Server
   ```
3. Check the same thing in the UI, when creating a document. Similar behaviour with 404 is visible.
![image](https://user-images.githubusercontent.com/25246848/86314434-4a16e080-bc45-11ea-994f-c8c199d2c093.png)

**Comment by Sarangan0219** [comment]
This issue is not reproducible in the latest pack. We are getting 200 for existing documents.
