### ISSUE TITLE
Enabling out-of-band oauth client provisioning in devportal causes App keys veiw rendering error

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#8535]
### Description:
Enabling out-of-band oauth client provisioning in devportal[1], leads to errors when rendering keys of Applications that are created subsequently.

![image](https://user-images.githubusercontent.com/6614042/86319769-e4315580-bc52-11ea-95c8-988d1845f7d7.png)

[1]https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/provisioning-out-of-band-oauth-clients/#provisioning-out-of-band-oauth2-clients

### Steps to reproduce:

1. Edit the deployment.toml to enable provisioning out-of-band oauth clients as follows
```
 [apim.devportal]
 enable_key_provisioning=true
```

2. Start API Manager and login to devportal.

3. Create a new Application and click on either production or sandbox keys to view the Apps credentials.

4. Page does not render and following error is seen in browser console.

```
react_devtools_backend.js:6 TypeError: Cannot read property 'keyType' of undefined
    at TokenManager.jsx:630
    at Array.map (<anonymous>)
    at be.render (TokenManager.jsx:533)
    at qa (react-dom.production.min.js:182)
    at za (react-dom.production.min.js:181)
    at ws (react-dom.production.min.js:263)
    at Eu (react-dom.production.min.js:246)
    at xu (react-dom.production.min.js:246)
    at pu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
r @ react_devtools_backend.js:6
os @ index.bundle.js:39
n.callback @ index.bundle.js:39
mo @ index.bundle.js:39
ls @ index.bundle.js:39
Tu @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Cu @ index.bundle.js:39
pu @ index.bundle.js:39
(anonymous) @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Ki @ index.bundle.js:39
Xi @ index.bundle.js:39
su @ index.bundle.js:39
enqueueSetState @ index.bundle.js:39
x.setState @ index.bundle.js:47
(anonymous) @ ApplicationDetails.bundle.js:1
Promise.then (async)
(anonymous) @ ApplicationDetails.bundle.js:1
componentDidMount @ ApplicationDetails.bundle.js:1
ls @ index.bundle.js:39
Tu @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Cu @ index.bundle.js:39
pu @ index.bundle.js:39
(anonymous) @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Ki @ index.bundle.js:39
Xi @ index.bundle.js:39
R @ index.bundle.js:39
Xe @ index.bundle.js:39
53ProtectedApp.jsx:177 Uncaught TypeError: Cannot read property 'contentWindow' of null
    at ProtectedApp.jsx:177
(anonymous) @ ProtectedApp.bundle.js:1
setInterval (async)
checkSession @ ProtectedApp.bundle.js:1
componentDidMount @ ProtectedApp.bundle.js:1
ls @ index.bundle.js:39
Tu @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Cu @ index.bundle.js:39
pu @ index.bundle.js:39
(anonymous) @ index.bundle.js:39
e.unstable_runWithPriority @ index.bundle.js:55
$i @ index.bundle.js:39
Ki @ index.bundle.js:39
L @ index.bundle.js:55
A.port1.onmessage @ index.bundle.js:55
```

### Environment details (with versions):
- OS: Ubuntu 18.04
- Client: Chromium Version 83.0.4103.116 
- Env (Docker/K8s):

**Comment by uvindra** [comment]
A similar issue occurs now after keys have been provisioned and attempting to view those keys again.

![image](https://user-images.githubusercontent.com/6614042/86768483-49c67d00-c06b-11ea-91ac-4f1f19071f06.png)


### Steps to reproduce:
1. Follow the steps outlined in https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/provisioning-out-of-band-oauth-clients/#provisioning-out-of-band-oauth2-clients

2. Subscribe to an API using the App that was just provisioned with out of band credentials.

3. Go back to the Applications detailed view and click on either production or sandbox keys to view the Apps credentials.

4. Page does not render and following error is seen in browser console.

```
react-dom.production.min.js:209 TypeError: Cannot read property 'includes' of null
    at ne.render (ApplicationDetails.bundle.js:1)
    at qa (react-dom.production.min.js:182)
    at za (react-dom.production.min.js:181)
    at ws (react-dom.production.min.js:263)
    at Eu (react-dom.production.min.js:246)
    at xu (react-dom.production.min.js:246)
    at pu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at e.unstable_runWithPriority (scheduler.production.min.js:19)
    at $i (react-dom.production.min.js:122)
os	@	index.bundle.js:39
Uncaught TypeError: Cannot read property 'contentWindow' of null
    at ProtectedApp.jsx:177

```

**Comment by dushansilva** [comment]
This can be related to [1], as mentioned in [1] the supported grant types array isn't being sent from the backend, therefore, this includes check can fail, @tharindu1st pls note

[1] - https://github.com/wso2/product-apim/issues/8579

**Comment by uvindra** [comment]
This issue is no longer reproducible in 4.0.0
