### ISSUE TITLE
Cannot create a scope for an API

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim#8536]
### Description:
When tried to create a new scope (which is not created earlier) for an API, it gives the following error saying the scope is already existing.

![Selection_109](https://user-images.githubusercontent.com/8363838/86320749-252a6980-bc55-11ea-8bed-cf55ed3c29fd.png)

### Affected Product Version:
APIM 3.2.0 - Alpha - Distributed Setup

**Comment by Arshardh** [comment]
Fixed with https://github.com/wso2/product-apim/pull/8577
