### ISSUE TITLE
Subscription Creation, application creation, application registration, API State change workflow admin portal Approval UI Information  

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#8541]
### Description:
When above workflows are enabled, when admin view the approval in the admin portal there seem to be some broken/missing information showing as follows.

![image](https://user-images.githubusercontent.com/18071381/86333499-9b38cb80-bc69-11ea-85e0-887730ddec89.png)

![image](https://user-images.githubusercontent.com/18071381/86335827-a17c7700-bc6c-11ea-91ca-c0f4b01d283f.png)

![image](https://user-images.githubusercontent.com/18071381/86335997-dc7eaa80-bc6c-11ea-8e03-b064fe78280c.png)

![image](https://user-images.githubusercontent.com/18071381/86338236-b4dd1180-bc6f-11ea-8609-b48658797c14.png)

**Comment by kavishkafernando** [comment]
@dushansilva I am unable to reproduce this.
**Application creation**
<img width="1290" alt="Screen Shot 2020-07-17 at 2 58 57 PM" src="https://user-images.githubusercontent.com/19324135/87771561-24d9c300-c83e-11ea-9745-7f93a18eaa2a.png">
**User creation**
<img width="1423" alt="Screen Shot 2020-07-17 at 3 00 04 PM" src="https://user-images.githubusercontent.com/19324135/87771604-3ae78380-c83e-11ea-849e-953316c379af.png">
**Subscription creation**
<img width="1415" alt="Screen Shot 2020-07-17 at 3 01 38 PM" src="https://user-images.githubusercontent.com/19324135/87771814-7c782e80-c83e-11ea-8711-e78d59ecaeea.png">
**Application Reagistration**
<img width="1410" alt="Screen Shot 2020-07-17 at 3 02 20 PM" src="https://user-images.githubusercontent.com/19324135/87771886-974aa300-c83e-11ea-86dc-360dc9cd9d5b.png">
**API state change**
<img width="1411" alt="Screen Shot 2020-07-17 at 3 04 05 PM" src="https://user-images.githubusercontent.com/19324135/87772031-cc56f580-c83e-11ea-979a-7c33a207ef73.png">

**Comment by dushansilva** [comment]
this was tested the older method using EI, hence the reason for this, therefore closing issue

**Comment by chamilaadhi** [comment]
I think we should provide a config to prevent loading pending tasks if an external workflow engine is defined
