### ISSUE TITLE
When re-publishing APIs in privateJet mode, kubernetes deployment is not created

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#8542]
### Description:
When change the API's lifecycle block to re-publish with privateJet mode, only the apis, configmaps and the secrets are created. Deployment is not created. 

### Steps to reproduce:
1. Create an API from the publisher
2. Select the environment from the environment tab
3. Publish the API from lifecycle tab
4. Then change the lifecycle state to block
5. Then again change the lifecycle state to re-publish
6. Check the deployment and the pods from "kubectl"

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS: 
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Not required to latest product, hence closing
