### ISSUE TITLE
Deploy an API in privateJet mode when the APIM running in the same kubernetes cluster

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#8543]
### Description:
It should be able to deploy an API in privateJet mode in the same kubernetes cluster where the APIM is running. In this scenario should analyse the configurations required to deploy the API in the same cluster and support it. 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Not require to latest product, hence closing
