### ISSUE TITLE
Invalid Credentials error when invoking a Prototype API

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#8544]
### Description:
When trying to invoke a Prototype API with a prototype endpoint, it gives an "Invalid Credentials" error.

![prototypeerror1](https://user-images.githubusercontent.com/30455603/86343591-ca096e80-bc76-11ea-8e0b-189e523911d1.png)

### Steps to reproduce:
1. Follow the steps in https://apim.docs.wso2.com/en/latest/learn/design-api/mock-api/deploy-and-test-mock-apis/
2. In Step 10 under Deploy a created API as a Prototype, when invoking the API, it gives the "Invalid Credentials" error.

### Affected Product Version:
- APIM 3.2.0-Pre Beta

### Environment details (with versions):
- OS: Ubuntu 18.04.4 LTS

**Comment by Chamindu36** [comment]
This cannot be reproduced in the latest pack. This is already fixed as it seems.
