### ISSUE TITLE
Publisher portal font style gets changed when on the Test console

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#8551]
### Describe your problem
On the publisher portal, entering the Test Console - Initialize test makes the whole publisher portal's font larger and bold.

#### Normal Screen
![normal screen](https://user-images.githubusercontent.com/25490163/86359797-1c568980-bc8f-11ea-8aff-cbc6c88de686.png)

#### Test console Screen
![bold screen](https://user-images.githubusercontent.com/25490163/86359969-5889ea00-bc8f-11ea-9f91-5fb77414c0ef.png)

**Comment by hasuniea** [comment]
the issue is fixed from https://github.com/wso2/carbon-apimgt/pull/9056

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88380197-b9559f80-cdc1-11ea-998e-969d77952f3c.png)
