### ISSUE TITLE
Getting JS errors on console when clicking SUBSCRIPTION & KEY GENERATION WIZARD button

### ISSUE THREAD

**Issue by deelaka96** [wso2/product-apim#8556]
### Description:

The SUBSCRIPTION & KEY GENERATION WIZARD UI does not work. 

### Steps to reproduce:

1. Log in to devportal
2. Open an API
3. Click on the Subscriptions tab
4. Click SUBSCRIPTION & KEY GENERATION WIZARD button

### Affected Product Version:
API manager 3.1.0

**Comment by dushaniw** [comment]
Fixed in the latest WUM 3.1.0
