### ISSUE TITLE
Password recovery info message is not stated the username validation

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-apim#8557]
### Description:

As $subject when we are going to recover our password in APIM portals, we want to input our username to get a recovery email Here if we input even a non-existing username the popup messages say the recover email send to the email which was linked to the particular username. But when considering the user friendliness, the info message should state that the "**username is invalid**". 

### Steps to reproduce:

1. First, you need to link an email to a particular user.

2. Set up an email server as below.
![image](https://user-images.githubusercontent.com/21282060/86376372-875e8b00-bca4-11ea-9acc-5161c555858c.png)

3.  After the mail server is configured, the user can click on the Forgot Password link on the Sign In page of the API Developer Portal and request a password change.

4. Enter an invalid username and click Submit. 
![sc2](https://user-images.githubusercontent.com/21282060/86376720-0fdd2b80-bca5-11ea-8c81-45789fe25cac.png)

**Then you can see an incorrect message like below.**

![sc3](https://user-images.githubusercontent.com/21282060/86376798-2b483680-bca5-11ea-8751-fe648340f3c5.png)

### Affected Product Version:

3.2.0 - Pre Beta
### Environment details (with versions):
- OS: Linux
- Client:
- Env (Docker/K8s):

---

**Comment by Sarangan0219** [comment]
According to [this issue](https://github.com/wso2/product-is/issues/4166#issuecomment-445686596) , this behavior is implemented intentionally to avoid username enumeration vulnerability. Thus we can Close this issue.
