### ISSUE TITLE
Applications listed in the developer portal are not sorted correctly

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#8560]
### Description:
When applications are created in the developer portal, they are not sorted correctly according do the selected criteria (eg: by Name)

### Steps to reproduce:
1. Create 10 new applications with varying names (With the default application total is 11)
2. Make sure the 9th application's name starts with a letter greater than the 10th application (eg: 9th App-->Zapp, 10th App->Xapp)
3. When listed in the developer portal Zapp is displayed on the first page and Xapp is displayed on the second page

### Affected Product Version:
APIM 3.1.0

**Comment by malinthaprasan** [comment]
Tested in the latest pack with:

1. pagination (apps created more than 10)
2. sorting asc and dsc for name, owner and throttle policy with apps created from multiple users and shared
3. above in tenant mode
