### ISSUE TITLE
Improvement to mutual SSL feature when Gateway is fronted with LB

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#8564]
### Describe your problem(s)
Feature to validate certificate sent in header is added to 3.1.0 in [1], it needs to be back-ported to 2.6.0 to validate certificate received from LB.

[1] https://github.com/wso2/carbon-apimgt/pull/8145

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/8145/files
