### ISSUE TITLE
WSO2 API Manager 3.1 - Issue on updating inline implementation Prototype API

### ISSUE THREAD

**Issue by Thiyanwso2** [wso2/product-apim#8567]
### Description:
Let assume we have created a prototype of API using swagger.yaml file which includes the inline implementation for a resource. If we add an inline implementation for another resource using APIM UI, then the previous resource implementation got removed/disappear (value of "x-mediation-script" in the API definition is becoming blank).

### Steps to reproduce:
- Create a prototype of API using a swagger.yaml file which includes the inline implementation for a resource. 
- You can see the inline implementation of that resource in API definition. (in x-mediation-script)
- Create another resource in that API.
- Go to Endpoints --> Prototype Implementation
- Add an inline implementation for the newly created resource.
- Then go to the API definition, you can see that inline implementation of the previous resource got removed. Value of "x-mediation-script" will empty. (But the implementation of newly created resource will remain same)

### Affected Product Version:
3.1.0
Note - I have tried the same thing in version 2.6.0, and it's working fine.

**Comment by mushthaq33** [comment]
Fixed via update
