### ISSUE TITLE
Rate Limiting does not work properly for GraphQL APIs

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#8578]
### Description:
Application rate limiting, Subscription rate limiting, Custom policies does not work properly for GraphQL APIs. If the request count is specified as 5 per minute, the request gets throttled out after 3 requests. This number changes intermittently.

### Steps to reproduce:
1. Create an Application rate limiting policy or a Subscription rate limiting policy or a Custom policy from the Admin portal.
2. Create a graphQL API as given in [1]. 
3. Associate the new rate limiting policy to the API or the Application accordingly.
4. Invoke the graphQL API and observe the throttling out requests.

[1] https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-a-graphql-api/

**Comment by chamilaadhi** [comment]
Seems like there are two events sent to the traffic manager for a single request

**Comment by chamilaadhi** [comment]
I think the confusion here comes from the sample in the doc. It invokes two operations. Throttling is happening for each operation
