### ISSUE TITLE
Cannot generate access token with out of band provisioned applications

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#8579]
### Description:
Cannot generate access token with out of band provisioned applications. The following error is printed 
```[2020-07-03 18:36:46,643] ERROR - ApplicationsApiServiceImpl Requested application consumer key with Id '{keyMappingId}' not found```

Also, we can see that the keymappingid and supported grant types values not set
![image](https://user-images.githubusercontent.com/18071381/86473574-cb15cb00-bd5e-11ea-9217-0963304962c0.png)

**Comment by uvindra** [comment]
Seems that this is working now, please refer to the screenshot of the browser network tab after clicking on the generate access token for an out of band OAuth2 client

![image](https://user-images.githubusercontent.com/6614042/114136317-2301e380-9928-11eb-9a51-30536cfdf5d4.png)

Note that the keyMappingId  and supportedGarentTypes are being sent now. An access token gets generated successfully.
