### ISSUE TITLE
[Devportal] UX issue when editing an application

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#8583]
### Description:

![appdevporta](https://user-images.githubusercontent.com/3313885/86484465-e5a66f00-bd73-11ea-8cd4-ee1a80dc632d.gif)

I think this is happening because we have used same edit page for application create, application edit from app listing page and edit from individual application details UI

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Arshardh** [comment]
This isn't reproducible in the latest pack. The edit screen returns to the application overview page

**Comment by Arshardh** [comment]
The issue is when cancelling the edit view. The UI returns to the listing page instead of the overview page.
