### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by TomasTokaMrazek** [wso2/product-apim#8590]
APIM 3.1.0 uses old Tomcat 7.0.59, where TLS 1.3 is not supported. This feature was implemented in version 7.0.92. I'm not aware of hardcoded dependency on old Tomcat (apart from deployment.toml config), so in order to implement this security standard, switching libraries and some minor work should be enough.

**Comment by scara** [comment]
Hello Everyone,
any update here?

TLS 1.3 should be supported: APIM 4.0.0 has been already released.

TIA,
Matteo

**Comment by pubudu538** [comment]
APIM v4 has the TLS 1.3 support.
