### ISSUE TITLE
"Loading" animation is needed whenever some action is being done 

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#8610]
### Describe your problem(s)
Loading animation is needed whenever some action is being done so that the user is aware that an action is in progress.
Some suggested places are
1. When we click on an API category in Dev portal
2. When we click on a Tag in Dev portal
3. Change the pagination page size from 10 to 100,
4. When we update swagger of an API, after clicking on "Update Content" button

---
#### Related Issues:
https://github.com/wso2/product-apim/issues/8417

**Comment by dushaniw** [comment]
Yet to be fixed in wum 3.1 and 3.0
