### ISSUE TITLE
Documentation about changing the default DB

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-apim#8615]
### Description:
Hi team. I'm following the documentation about changing the default H2 for DB2 for all in one APIM. The following is related to any DB because the explanation is the same.

According to the documentation I have 3 DB's: AM_DB, WSO2_SHARED_DB, and Carbon_DB.
1.  AM_DB script is on <API-M_HOME>/dbscripts/apimgt/db2.sql
2. WSO2_SHARED_DB is on <API-M_HOME>/dbscripts/db2.sql
but I have a hard time understanding where is the script for WSO2CARBON_DB? or should I run the same dbscripts/apimgt/db2.sql ? Documentation is confusing 

We need to explain that For carbon_db, you can keep the data in h2 so you don't need to execute any database script against h2 (but we don't recommend  for production)
Lots of prospects contact me about this. Also in toml file we mentioned only configuration for APIM and SharedDB 

### Content Positioning in Documentation:
https://apim.docs.wso2.com/en/3.0.0/install-and-setup/setting-up-databases/overview/

**Comment by HiranyaKavishani** [comment]
` This database has the internal data related to the product. This data is stored in the embedded H2 database.`  The date is there in the documention . Hence closing the issue
