### ISSUE TITLE
Documentation required on how to generate token to access publisher APIs

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-apim#8616]
### Description:
Currently, There is no documentation found on how to generate the OAuth2 token for accessing publisher REST APIs in 3.0.0 documentation

https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/restful-apis/

This is a major fact as there is no way a user can use these APIs without knowing how to generate the token. Please fix this ASAP such as we have in https://docs.wso2.com/display/AM260/apidocs/publisher/#guide 
or

https://apim.docs.wso2.com/en/latest/develop/product-apis/publisher-apis/publisher-v0.16/guide/

**Comment by Mariangela** [comment]
Reset the labels to the original

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1507
