### ISSUE TITLE
Role based scope issuer doesn't support for the federated users

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#8618]
### Description:

When using the 3rd party IDP, the user is not provisioned in the APIM side and the RBAC(Role-Based Access Control) feature doesn't work due to a limitation in the scope issuer ([RoleBasedScopesIssuer.java#L147](https://github.com/wso2-support/carbon-apimgt/blob/fb64da553ac1243afb7b2e371394d28a1e621ad8/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/issuers/RoleBasedScopesIssuer.java#L147))

Since It will extract the 'tenantDomain' and the 'username' details by considering the 'Federated-User'. But for the user-roles, it will search inside the available user-stores only (not in the user attributes of the authenticated user )
Due to that, although the user roles are available for the authenticated user as 'userAttributes', those will be skipped during the scope issuing flow.

### Affected Product Version:
APIM 3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2179
