### ISSUE TITLE
Role based scope issuer doesn't support for the dynamic user roles.

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#8619]
### Describe your problem(s)
Dynamic claims(such as roles, permissions) is a common requirement of a security platform when it comes to user authorization.
Since the APIM already supports the user authorization for a resource by validating the OAuth scopes(RBAC), it will be more valuable if we support the dynamic claims for the RBAC feature.
This will enhance our integration capabilities with existing security platforms.

### How will you implement it

---

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2179
