### ISSUE TITLE
Mgt Console URL : too many redirects

### ISSUE THREAD

**Issue by damoebius** [wso2/product-apim#8624]
### Description:
My WSO2 APIM run behind a reverse proxy. It's configured to use the proxyPort 443. It's works fine for devportal and publisher but not for carbon.

calling https://mydomain/carbon redirect me to https://mydomain**:443**/carbon and my browser fall into an infinite redirection loop.

What's wrong ?

Thanks for your help

### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS: Redhat 8
- Client: Chrome
- Env (Docker/K8s): Docker

---

**Comment by damoebius** [comment]
I fix it by adding this in catalina-server.xml

```
                <Valve
                    className="org.apache.catalina.valves.RemoteIpValve"
                    internalProxies="172\.\d{1,3}\.0\.\d{1,3}"
                    remoteIpHeader="x-real-ip"
                    proxiesHeader="x-forwarded-server"
                    protocolHeader="x-forwarded-proto"
                />
```

**Comment by swagy-tarun** [comment]
Hi damoebius,

Where are you terminating ssl? I tried this change but not working for me. My access pattern is AWS LB -> Nginx Ingress -> WSO2 Carbon

Thanks,
Tarun

**Comment by eniayomi** [comment]
Any update on this yet? @swagy-tarun  where you able to fix?
