### ISSUE TITLE
Admin Portal UI Issues

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#8627]
This issue includes UI issues related to Admin Portal UI

**Comment by kavishkafernando** [comment]
**Advanced Policies**
- Capitalize MUI data table headings
- Capitalize first letter of 'policyName'
- Change search text to 'Search by Advanced Policy name'
<img width="1425" alt="Screen Shot 2020-07-09 at 10 20 58 AM" src="https://user-images.githubusercontent.com/19324135/86998882-f0775e80-c1ce-11ea-932f-f10e8d71af0f.png">

- Align Default options a little towards the right
- Save button cannot be seen
<img width="1653" alt="Screen Shot 2020-07-09 at 10 31 00 AM" src="https://user-images.githubusercontent.com/19324135/86999353-033e6300-c1d0-11ea-8bff-b977d583f8af.png">

- Move description box abit towards the right to align with Request count Unit time boxes
<img width="957" alt="Screen Shot 2020-07-09 at 10 34 56 AM" src="https://user-images.githubusercontent.com/19324135/86999498-5b756500-c1d0-11ea-964f-33936ef80811.png">

- IP condition type helper text should move below the options
<img width="452" alt="Screen Shot 2020-07-09 at 10 42 40 AM" src="https://user-images.githubusercontent.com/19324135/86999802-23baed00-c1d1-11ea-8abe-e91f890270fe.png">

**Comment by erangatl** [comment]
> * Capitalize first letter of 'policyName'

Let's have space as well

`Policy Name`

**Comment by erangatl** [comment]
![image](https://user-images.githubusercontent.com/20179540/87001570-6b437800-c1d5-11ea-9389-6a6189b1d9bf.png)

Shouldn't the title be  ` Advanced  Rate Limiting Policies `?

**Comment by kavishkafernando** [comment]
**Application Policy**

- In add Application policy there's a typo in the error message.
- Need to bold MUI data table headings as well

<img width="517" alt="Screen Shot 2020-07-09 at 12 18 06 PM" src="https://user-images.githubusercontent.com/19324135/87006666-b6ae5400-c1de-11ea-8af7-2b85ea12ae92.png">

**Comment by kavishkafernando** [comment]
**Subscription Policies**

- Need to bold MUI data table headings
- 'Request Count' and 'Request Bandwith' should move abit to the left to align with the text boxes
- Stop on Quota Reach should move to the left
- Allow/ Deny radio buttons also need to be moved to the left

<img width="952" alt="Screen Shot 2020-07-09 at 12 24 37 PM" src="https://user-images.githubusercontent.com/19324135/87007168-726f8380-c1df-11ea-935f-3820812f0516.png">

<img width="949" alt="Screen Shot 2020-07-09 at 12 28 32 PM" src="https://user-images.githubusercontent.com/19324135/87007389-d42fed80-c1df-11ea-81ce-ae22ffb71fbc.png">

- Need to link the policy names with the 'Edit' page of the policy (like in Advanced policies)

<img width="994" alt="Screen Shot 2020-07-09 at 12 31 40 PM" src="https://user-images.githubusercontent.com/19324135/87007786-6c2dd700-c1e0-11ea-89d3-51a7e7d1ad54.png">

**Comment by kavishkafernando** [comment]
**Custom Policies**

- Need to bold MUI data table headings
- Need to link the policy names with the 'Edit' page of the policy (like in Advanced policies)
- Helper text should be 'Name of the throttle policy' and 'Description of the throttle policy' to be consistent with other pages
<img width="1049" alt="Screen Shot 2020-07-09 at 12 39 05 PM" src="https://user-images.githubusercontent.com/19324135/87008439-5a98ff00-c1e1-11ea-9945-bfeab7f2a891.png">

**Comment by kavishkafernando** [comment]
**Microgateway Label**

- Helper text should be changed to 'Name of the Microgateway Label' and 'Description of the Microgateway label' and 'Name of the Host' for consistency purposes.

<img width="610" alt="Screen Shot 2020-07-09 at 12 46 08 PM" src="https://user-images.githubusercontent.com/19324135/87009064-4b668100-c1e2-11ea-91be-9ecdbf172e6c.png">

**Comment by kavishkafernando** [comment]
**API Categories**
Helper text should be changed to 'Name of the API Category' and 'Description of the API Category'  for consistency purposes.
<img width="512" alt="Screen Shot 2020-07-09 at 12 51 11 PM" src="https://user-images.githubusercontent.com/19324135/87009625-0bec6480-c1e3-11ea-94c1-52ca3a801321.png">

**Comment by tmkasun** [comment]
Need to put a space in menu name

![image](https://user-images.githubusercontent.com/3313885/87010487-3f7bbe80-c1e4-11ea-896a-41b845d00315.png)

**Comment by tmkasun** [comment]
Z-index issue in the footer

![image](https://user-images.githubusercontent.com/3313885/87011952-37248300-c1e6-11ea-94aa-5cc90964b5bd.png)

**Comment by kavishkafernando** [comment]
**Application creation**
**Subscription creation**
**Application registration**
**Subscription update**
**API state change**

- Need to change the search text to 'Search by Application, Throttling Policy or Creator'
- Created time 'a few seconds ago' text needs to be abit smaller

<img width="1300" alt="Screen Shot 2020-07-09 at 4 26 53 PM" src="https://user-images.githubusercontent.com/19324135/87031810-3c42fb80-c201-11ea-9aae-902b18d70594.png">

**User creation**

- Need to change the search text to 'Search by Application, Throttling Policy or Creator'
- Created time 'a few seconds ago' need to be in the same font
<img width="1242" alt="Screen Shot 2020-07-09 at 4 33 36 PM" src="https://user-images.githubusercontent.com/19324135/87032257-f5a1d100-c201-11ea-8450-93b7e950cfd5.png">

**Comment by kavishkafernando** [comment]
**Applications**
Too much gap between first column and 2nd column
<img width="1102" alt="Screen Shot 2020-07-09 at 4 40 26 PM" src="https://user-images.githubusercontent.com/19324135/87033070-30583900-c203-11ea-82d9-1687cc74bff3.png">

**Comment by kavishkafernando** [comment]
**Key Manager**

- Need to add helper text for Display name

<img width="998" alt="Screen Shot 2020-07-09 at 4 45 06 PM" src="https://user-images.githubusercontent.com/19324135/87033412-cee49a00-c203-11ea-98da-af08e718c48b.png">

**Comment by chathuranga95** [comment]
#### Dashboard
The rate limiting card is missing links. (Only Advanced policies link is working)
The PR: https://github.com/wso2/carbon-apimgt/pull/8887 fixes this.

**Comment by chathuranga95** [comment]
#### Dashboard

The bottom dashboard card is cropped when in a smaller screen or when zoomed in. (Scroll down doesn't scroll all the way down)

![cropped dashboard](https://user-images.githubusercontent.com/25490163/87034065-e2dccb80-c204-11ea-999b-e4ea97f13a9d.png)

**Comment by chathuranga95** [comment]
#### Bot Detection -- Configure Emails

The email configuring for bot detection alerts is not working since REST APIs resources are changed recently.
The PR: https://github.com/wso2/carbon-apimgt/pull/8938 fixes this

**Comment by tmkasun** [comment]
![image](https://user-images.githubusercontent.com/3313885/87132858-19255400-c2b4-11ea-82b0-bf63ff670160.png)

In bot detection menu, We have used `Android` icon , change it to different appropriate icon

**Comment by chanaka3d** [comment]
Since all the issues have been addressed we can close this issue.
