### ISSUE TITLE
Signed up users on Devportal through the Approval workflow extension have missing roles

### ISSUE THREAD

**Issue by shirolk** [wso2/product-apim#8628]
When using the Approval workflow executor for user signup the newly created users do not have the required roles assigned. 
This results in an error when logging in after sign up. 

When the internal/subscriber and Application/apim_devportal are assigned via the management console the new user can login successfully.

**Comment by tmkasun** [comment]
Hi @shirolk 

What is the APIM version you have used ?

**Comment by shirolk** [comment]
3.2 beta

**Comment by shirolk** [comment]
Mistake - this works okay
