### ISSUE TITLE
Error occur callback URL empty when Application update

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#8635]
### Description:

- Create Application

- Generate keys

- Add callback URL

![Screenshot from 2020-07-09 16-32-09](https://user-images.githubusercontent.com/8374895/87032299-05b9b080-c202-11ea-8792-771e0d22649a.png)

- Then again remove callback URL

- Click Save.

![Screenshot from 2020-07-09 16-32-30](https://user-images.githubusercontent.com/8374895/87032335-12d69f80-c202-11ea-851d-1d072d092a5a.png)

[2020-07-09 16:32:28,504] ERROR - ApplicationsApiServiceImpl The callback url must have at least one URI value when using Authorization code or implicit grant types.

Since this effect migration makes as the highest priority level.

**Comment by rmsamitha** [comment]
@Krishanx92 Please do not use the deprecated labels (3.2.0)

**Comment by Arshardh** [comment]
Not reproducing in the latest pack
