### ISSUE TITLE
[APIM 3.2.0] Avoid extra configurations outside of the deployment.toml for Throttling

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/product-apim#8638]
### Describe your problem(s)
It was identified that currently throttling configurations in an active-active deployment of WSO2 API Manager have [configurations outside of the primary configuration file `<AM_HOME>/repository/conf/deployment.toml`](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/single-node/configuring-an-active-active-deployment/#step-8-configure-throttling).

This tarnishes the usability since, users' familiarity with the primary configuration file and will be cumbersome when it comes to introducing these configuration changes in an installation platform.

### Describe your solution
This is an improvement request to provide support for these additional configurations within the primary configuration file and avoid the need to perform extra configuring steps outside of this configuration file.

#### Suggested Labels:
Type/Improvement

#### Suggested Assignees:
@tharindu1st @pubudu538

**Comment by tharindu1st** [comment]
This can be achieved by configuring following configuration

[apim.throttling]
event_duplicate_url = ["tcp:traffic-manager-2:5672"]
@Mariangela @shaniR  please replace the above mentioned step by defining this config
