### ISSUE TITLE
When disabling the advanced throttling, web socket API is not working and giving errors.

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#8639]
### Description:
When disabling the advanced throttling, web socket API is not working as below.
```
wscat -c ws://localhost:9099/echowebsocket/1.0 -H "Authorization: Bearer 334bb639-cb05-3a6e-9fd3-72b27b98279c"
Connected (press CTRL+C to quit)
> aaa
Disconnected (code: 1006, reason: "")

```

### Steps to reproduce:
1. Disable the advanced throttling as below in the api-manager.xml file.
`  <EnableAdvanceThrottling>false</EnableAdvanceThrottling>
`
2. Create the Web socket API with the following endpoint.
`ws://echo.websocket.org:80`
3. Invoke the API as below and then you will get connected.
`wscat -c ws://localhost:9099/echowebsocket/1.0 -H "Authorization: Bearer 334bb639-cb05-3a6e-9fd3-72b27b98279c"`
4. Please input value as below and you will get the error.
```
Connected (press CTRL+C to quit)
> aaa
Disconnected (code: 1006, reason: "")
```

### Affected Product Version:
APIM 2.6.0

**Comment by wasuradananjith** [comment]
This feature is not there in public branch (APIM 3.2.0). Hence we can close this issue.
