### ISSUE TITLE
WSO2 APIM-3.1.0: APIs are not lined properly when the UI is minimized

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#8640]
### Description:
The APIs were not properly aligned and there were some alignment issues in the API thumbnail as well when the publisher UI is minimized. I was able to reproduce this issue using wso2am-3.1.0 pack and we tested this in chrome version 83.0.4103.116. 

### Steps to reproduce:
1. Create at least 5 APIs in the publisher portal
2. Go to API list view
3. Minimize the UI
![image](https://user-images.githubusercontent.com/20519000/87112360-3abd1600-c289-11ea-8373-2ae33ecbb7c8.png)

### Affected Product Version:
wso2am-3.1.0

**Comment by chanaka3d** [comment]
This issue is fixed in the latest build.
