### ISSUE TITLE
WSO2 APIM-3.1.0: "Character length exceeds the allowable limit" in API name and context 

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#8641]
### Describe your problem(s)
While creating an API in the publisher portal, if the API name or context is too long an error message saying "Character length exceeds the allowable limit" is displayed in both error notification in UI as well as in the wso2carbon logs. If the maximum character limit can be displayed in the error message it would be more meaningful and will guide the user with the naming/context policies.

### Describe your solution
1. Create an API using any method(new REST API, openapi definition) in the publisher portal
2. Enter a very large value for name/context. E.g: **testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest**
3. Click on Create/ Create and Publish button
4. You will end up with the following message in the UI error box and in wso2carbon.log
```
[2020-07-08 04:16:29,084] ERROR - ApisApiServiceImpl Error while adding new API : null-testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest-test - Character length exceeds the allowable limit
org.wso2.carbon.apimgt.api.APIManagementException: Character length exceeds the allowable limit
```

![image](https://user-images.githubusercontent.com/20519000/87112738-3b09e100-c28a-11ea-8c37-d66688a94c3c.png)

### How will you implement it
Modify the error message with maximum character length.
E.g: Character length(provided value's length) exceeds the allowable limit(max character length)

**Comment by rmsamitha** [comment]
@saranki  It is not required to mention the affected product version in the issue title. The affected version will be anyway recorded via a label, the information will be duplicated. The users not having write access to repo can add the "affected version" as a suggested label in the issue description.
