### ISSUE TITLE
APIM 2.1.0 Tuning Performance guide has long typo

### ISSUE THREAD

**Issue by lahirus** [wso2/product-apim#8642]
### Steps to reproduce:
Access https://docs.wso2.com/display/AM210/Tuning+Performance
### Content Positioning in Documentation:
Start of the page "the actual API timeout, it triggers the timeout before the actual configured API timeout." at https://docs.wso2.com/display/AM210/Tuning+Performance

**Comment by Mariangela** [comment]
Thanks for reporting!
Fixed in -
https://docs.wso2.com/display/AM210/Tuning+Performance
https://docs.wso2.com/display/AM220/Tuning+Performance
Checked in 2.5.0, 2.6.0, 3.0.0, 3.1.0, but this issue was not there in those versions.
