### ISSUE TITLE
incorrect formation of toml file in publisher for analytics component

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#8646]
**Description:**
while doing the distributed setup, when we run profile optimizer on apim distribution for the publisher
analytics component in toml file is added with

[[apim.analytics.analytics_node]]
analytics_url="tcp://localhost:7612"
analytics_auth_url="ssl://localhost:7712"

But,
it should be 

[[apim.analytics.url_group]]
analytics_url =["tcp://das.wso2-dev:7612"]
analytics_auth_url =["ssl://das.wso2-dev:7712"]
type = "loadbalance"

please fix this issue in profile optimizer script

**Comment by ruks** [comment]
Moving to APIM since configurations are from the APIM Product.
