### ISSUE TITLE
[Devportal] - Application search inconsistent behavior

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#8656]
### Description:
Sign-in to the Devportal and go to the Application section
Search for an application which is not existing (for example Foo)
This will result in the "No Matching Applications" UI
Empty the search bar by pressing the backspace in the keyboard (not using the Clear button)
Directs to the "Create New Application" page

**Comment by athiththan11** [comment]
This behavior is observed on API Manager `3.1.0` as well
