### ISSUE TITLE
Cannot update carbon.properties file with new configuration model 

### ISSUE THREAD

**Issue by deelaka96** [wso2/product-apim#8663]
### Description:
The system properties defined in the deployment.toml file is not loaded into the server on the first start.

### Steps to reproduce:
1.Add following configuration to deployment.toml file
[system.parameter]
'org.wso2.CipherTransformation'="AES"
2. Start the server. Still the original value will be picked up.
3. Restart the server. Now the new value in the deployment.toml will be picked.

### Affected Product Version:

APIM 3.1.0

---
#### Related Issues:
https://github.com/wso2/product-is/issues/7991

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/2754
