### ISSUE TITLE
Application view action is not visible and intuitive

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8676]
### Description:

To view Application details you need to click on the application name, but it's not visible and intuitive

![image](https://user-images.githubusercontent.com/20179540/87417063-41cb8780-c5ed-11ea-91d1-823d2ac783d4.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chanaka3d** [comment]
<img width="467" alt="Screen Shot 2020-10-05 at 5 49 19 PM" src="https://user-images.githubusercontent.com/3424539/95078660-1e6b3100-0733-11eb-86db-89d9d46eb082.png">
