### ISSUE TITLE
API list make the card clickable

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8679]
### Description:

Currently, only Image and API name is clickable

![image](https://user-images.githubusercontent.com/20179540/87505792-62e0b680-c687-11ea-94ac-10fc91038f89.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chanaka3d** [comment]
This issue is fixed in carbon-apimgt 6.8.49-SNAPSHOT
