### ISSUE TITLE
Cannot generate Keys for Okta Key Manager configured from Devportal

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#8698]
### Description:
After configuring Okta as a Key Manager from Admin portal, cannot generate keys from the Devportal. The following error is thrown.

```
ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Missing required properties to create/update oauth application
```

### Steps to reproduce:
1. Configure an Okta Key Manager instance from the Admin portal.
2. Create an application from the Devportal.
3. Click on Generate Keys button under Okta key Manager tab.

### Affected Product Version:
APIM 3.2.0 latest pack

**Comment by CrowleyRajapakse** [comment]
Fixed and not reproducing in latest
