### ISSUE TITLE
Username in analytics data is always published as admin@carbon.super

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#8716]
### Description:
When analytics data is published, the username is always published as admin@carbon.super instead of the logged in user. This behaviour is reproducible for both JWT and opaque tokens.

Find the request logs below(please note that the user used for following invocations is 'alex')
 
_opaque:_
INFO {io.siddhi.core.stream.output.sink.LogSink} - REQUEST : Event{timestamp=1594964677494, data=[{"correlationID":"e433a346-ff67-4b0f-8130-ae69f4920523","keyType":"PRODUCTION"}, jJMYYJ4mP_kxd2tuNU_0ZBMnCbIa, opaque, 29, alex, /pizzashack/1.0.0, PizzaShackAPI, 1.0.0, /order, /order, POST, alex, carbon.super, Unlimited, localhost, admin@carbon.super, carbon.super, 127.0.0.1, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36, 1594964677453, false, 41, 8, 33, false, 0, https-8243, 201, https://localhost:9443/am/sample/pizzashack/v1/api/, 7, 0, 0, 0, 34, 0, SYNAPSE, Synapse], isExpired=false}
[2020-07-17 11:14:37,511]  INFO {io.siddhi.core.stream.output.sink.LogSink} - USERNAME : Event{timestamp=1594964677494, data=[admin@carbon.super, carbon.super], isExpired=false}

_JWT:_
INFO {io.siddhi.core.stream.output.sink.LogSink} - REQUEST : Event{timestamp=1594964708503, data=[{"correlationID":"30236e17-926a-45cd-867c-34597b34c67a","keyType":"PRODUCTION"}, Xsuo6LULuFrfUeWHswzcfbouDkIa, jwt, 30, alex, /pizzashack/1.0.0, PizzaShackAPI, 1.0.0, /order, /order, POST, alex, carbon.super, Unlimited, localhost, admin@carbon.super, carbon.super, 127.0.0.1, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36, 1594964708468, false, 35, 2, 33, false, 0, https-8243, 201, https://localhost:9443/am/sample/pizzashack/v1/api/, 1, 0, 0, 0, 33, 0, SYNAPSE, Synapse], isExpired=false}
[2020-07-17 11:15:08,506]  INFO {io.siddhi.core.stream.output.sink.LogSink} - USERNAME : Event{timestamp=1594964708503, data=[admin@carbon.super, carbon.super], isExpired=false}

**Comment by fazlan-nazeem** [comment]
This has been fixed by https://github.com/wso2/product-apim/pull/8684/files
