### ISSUE TITLE
Oracle migration script issue with Callback URL value as NULL

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#8726]
### Description:
In oracle empty strings '' are considered same as null. Therefore, when executing following query,
`UPDATE IDN_OAUTH_CONSUMER_APPS SET CALLBACK_URL='' WHERE CALLBACK_URL IS NULL
/`
It doesn't change anything, the value remains null. Therefore, users can't update the keys in application keys page since callback value is "null"  still in migrated apps.

ref: https://stackoverflow.com/questions/49678159/insert-empty-string-in-oracle

**Comment by HiranyaKavishani** [comment]
@shilmyhasan Could you please close the issue if this is solved ?

**Comment by shilmyhasan** [comment]
@HiranyaKavishani This particular query is available only when migrating from 3.1.0. I will check on this during 3.1.0 to 4.1.0 migration.

**Comment by shilmyhasan** [comment]
Hi Team,

The issue is resolved.

Thanks
