### ISSUE TITLE
Oauth Apps created via the devportal is always owned by admin

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#8727]
### Description:
When keys are generated for an application via the devportal and then once we generate a token, the sub claim in the jwt token is set to admin irrespective of the user.

This directly affects analytics and may affect other features.

**Comment by fazlan-nazeem** [comment]
closing as this has been fixed in https://github.com/wso2-extensions/apim-km-wso2is/pull/10/files

**Comment by tommasofavaron1** [comment]
I still have this problem, how did you solve this?
