### ISSUE TITLE
Deletion of the Service-Providers related to the 'Publisher', 'Devportal' and 'Analytics-Dashboard' manually has residual data in database

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#8729]
### Describe your problem

- In APIM-3.1.0, we can observe that there are set of Service-Providers(SPs) created inside the APIM for the default applications such as Publisher, Devportal, and Dashboard.
- During the initiating process of those applications, we could identify that the client credentials (client Id and client secret) retrieved from the DCR request are stored in the 'AM_SYSTEM_APPS' table located in the 'WSO2AM_DB'.
- After that, the login requests are initiated using the credentials stored in the aforementioned 'AM_SYSTEM_APPS' table.
- However, the deletion of the Service-Providers manually from the APIM management-console UI does not affect to the aforementioned 'AM_SYSTEM_APPS' table.

### Describe your solution
The deletion of the SPs related to the default applications needs to remove the data in the 'AM_SYSTEM_APPS' table as well.

#### Suggested Labels:
APIM-3.1.0

**Comment by uvindra** [comment]
As discussed, there is no real use case to delete these SPs that are created by the product itself. We do not recommend deleting these SPs and therefore we will not be proceeding with providing any specific guidelines of how to do so.
