### ISSUE TITLE
Analytics events getting dropped when User-Agent is null

### ISSUE THREAD

**Issue by grego9** [wso2/product-apim#8732]
### Description:
TID: [-1234] [] [2020-07-17 17:21:45,909] ERROR {org.wso2.carbon.apimgt.usage.publisher.APIMgtUsageDataBridgeDataPublisher} - **RequestResponse event dropped due to unavailability of mandatory data: [User agent]** in event: Application consumer key: *************************1Ua, Application name: ENGAGE, Application ID: 7, Application owner: RFA, API name: FirstData, API version: v2, API context: /firstdata/v2, Username: rfa@carbon.super, API resource path: /, API resource template: /*, API method: POST, API creator: admin, API creator tenant domain: carbon.super, API tier: Unlimited, Username: rfa@carbon.super, User tenant domain: carbon.super, Host name: apimserver, User IP: xxx.xx.xx.xxx, User Agent :null, Is throttled: false, Request timestamp: 1595017304995, Response time: 913, Service time: 0, Backend time: 913, Is response cache hit: false, Response size: 711, Protocol: http-8280, Response code: 200, Destination: https://apimserver:8246/services/FirstData, Security latency: 0, Throttling latency: 0, Mediation latency: 0, Response mediation latency: 0, Backend latency: 913, Other latency: 0, Gateway type: SYNAPSE, Label: Synapse

### Steps to reproduce:

    * Create and publish an API.
    * Invoke the API without User-Agent header. Refer to below example curl command.

`curl -k -X GET "https://192.168.8.100:8243/test/v1.0.0/foo" -H "accept: application/json" -H "Authorization: Bearer 5cd2c989-86ce-3467-a844-f10154016fae" -H 'User-Agent:'`

### Affected Product Version:
APIM 3.1.0
APIM-Analytics 3.1.0

### Suggested Labels:
APIM 3.1.0, APIM-Analytics

### Environment details (with versions):
- OS: Centos 7
- Java: openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

---

#### Related Issues:
https://github.com/wso2/product-apim/issues/4668

**Comment by dushansilva** [comment]
@ruwiniwj @RAVEENSR @fazlan-nazeem did we fix this? as I recall we fixed something similar

**Comment by ruwiniwj** [comment]
As per https://github.com/wso2/product-apim/issues/4668 this has been fixed only for APIM 2.6.0. I checked the code and this hasn't been fixed in master.

**Comment by grego9** [comment]
This needs to be fixed on APIM or APIM Analytics? If it's only in APIM Analytics, may it be already fixed on the latests v3.2.0-m1 release?

**Comment by ruwiniwj** [comment]
This needs to be fixed in APIM side. The event is dropped due to a validation which happens at the gateway prior to publishing data to analytics.

**Comment by grego9** [comment]
Thank you. Can you hand me the commit that fixed this in 2.6.0? Would you recommend some kind of workaround for this in the meanwhile?

**Comment by ruwiniwj** [comment]
The 2.6.0 fix is in a private repo so we are unable to share the commit. The fix is to remove the null check in [1].  A work around is to invoke the API with the User-Agent header. 

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.publisher/src/main/java/org/wso2/carbon/apimgt/usage/publisher/dto/DataBridgeRequestResponseStreamPublisherDTO.java#L134-L136
