### ISSUE TITLE
Change the path of access.log file- APIM 3.1.0

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#8740]
### Describe your problem(s)
Need to change the http_access log file path to a custom location.

### Describe your solution
Through deployment.toml we can change the http_access log name as follows.
```
[http_access_log]
prefix="http_access_test"
```
Something similar can be achieved to change the file path as well.

**Comment by kavishkafernando** [comment]
For APIM 3.1.0 you can do the following configuration to change the directory path,
```
[http_access_log]
prefix="../../hello/Kavishka"
suffix=".log"
pattern=""
```
<img width="594" alt="Screen Shot 2020-07-27 at 12 47 04 PM" src="https://user-images.githubusercontent.com/19324135/88515253-0a0b0980-d009-11ea-9f29-0d69f46eb846.png">

**Comment by Krishanx92** [comment]
Close with above comment.
