### ISSUE TITLE
Keyboard navigation for search is not working for API Products

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8764]
### Description:

Keyboard navigation for search is not working for API Products
The mouse click is working

![image](https://user-images.githubusercontent.com/20179540/88076809-24bc2900-cb98-11ea-99da-eb674171b3c0.png)

### Steps to reproduce:

1. Search for a product 
2. select it using the keyboard arrows
3. when pressing enter it directs to a not found page

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Cannot reproduce in latest version hence closing
