### ISSUE TITLE
Search does not work as expected

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8765]
### Description:

When you are inside an API, Search does not work.
When searched from Listing and Applications page it works.

![image](https://user-images.githubusercontent.com/20179540/88078431-1a029380-cb9a-11ea-93ed-15c621278106.png)

### Steps to reproduce:

1. Select an API
2. Search for another API
3. IT does not work

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Arshardh** [comment]
When searched in the api info view, the searched api is shown in the dropdown, but clicking it does not enter the overview page of the new api. Demoting the issue severity.
