### ISSUE TITLE
When application keygeneration workflow is enabled, after the key generation UI does not update to

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#8775]
When application keygeneration workflow is enabled, after the key generation UI should update to pending state, but when only refresh it updates.

after key generation, the success message should also be change as pending for approval
![image](https://user-images.githubusercontent.com/18071381/88151428-5082f180-cc20-11ea-9f58-32d5abe149f8.png)

when refreshed
![image](https://user-images.githubusercontent.com/18071381/88151510-6f818380-cc20-11ea-90be-f643fa4e6c67.png)

**Comment by Krishanx92** [comment]
This is fixed with latest pack.
