### ISSUE TITLE
Cannot generate token for APIs when trying to subscribe using an application from a different tenant.

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#8779]
### Description:
When performing cross tenant subscription and invocation for APIs the tenant which is not the owner of the API cannot generate keys for API invoke even though API is in the public visibility state.
It freezes from here in the dev portal when creating a new application with keys. The next button in the window does not work.

![Screenshot from 2020-07-22 14-59-28](https://user-images.githubusercontent.com/42435576/88160217-fd16a080-cc2b-11ea-9c65-5ca8e6d1e2f3.png)

When trying with production keys under subscriptions of an API it gives` "Error occurred when generating application keys" error ` from UI

### Steps to reproduce:

1. Create a Tenant using the carbon console.
2. Then log in as super admin and create an API and Publish it.
3. Logout and login as the tenant admin which you created before.
4. In dev portal navigate to public dev portal and select carbon.super APIs 
5. Then try to subscribe and generate a token

### Affected Product Version:
3.2.0 Latest Pack (6.7.125-SNAPSHOT)

**Comment by chamilaadhi** [comment]
Not reproducible after https://github.com/wso2/carbon-apimgt/pull/10067
