### ISSUE TITLE
Deprecating Cross Tenant Subscription

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#8801]
### Description:
We will go to deprecate the cross tenant subscription feature which allows us to subscribe and invoke APIs in a different tenant.

After this change, if the user needs to enable this feature. User needs to enable explicitly from below configuration.

[apim.devportal]
enable_cross_tenant_subscriptions = true

**Comment by HiranyaKavishani** [comment]
Closing the issue as its already fixed
