### ISSUE TITLE
Unable to disable the input fields and buttons after importing keys from external apps

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#8804]
### Description:
Unable to disable all the input fields and update button in the UI after importing keys from an external app since the Keys and Key manager payloads do not provide a flag for this purpose.

**Comment by msm1992** [comment]
This issue is fixed in carbon-apimgt master branch with PR https://github.com/wso2/carbon-apimgt/commit/2c8d038e37a51b1e82bf7a8985c51b6f56391271
