### ISSUE TITLE
Publisher test console: Issue in testing the API with incorrect token or missing the 'test-key'

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#8810]
### Description:
If API developer tries to test the API(invoke) without giving the token(test-key), returns an empty response.

### Steps to reproduce:
1. Create API.
2. Navigate to the test console.
3. Click on initialize test button.
4. click on try out and get the curl.
test-key is automatically generated. If we remove the test-key from the request, it gives the empty result.
If we give wrong test-key, it also gives an empty response.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88380107-8f03e200-cdc1-11ea-8747-b541a63ebf07.png)

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88380848-ee162680-cdc2-11ea-8752-b1f60911dc5f.png)

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88380994-2c134a80-cdc3-11ea-97aa-289297089ba0.png)

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88381061-4cdba000-cdc3-11ea-97f6-808b38a894f9.png)

**Comment by hasuniea** [comment]
![image](https://user-images.githubusercontent.com/12996810/88381106-5fee7000-cdc3-11ea-9766-2cb356231f95.png)

**Comment by hasuniea** [comment]
fixed from https://github.com/wso2/carbon-apimgt/pull/9056

**Comment by tmkasun** [comment]
closing this issue as it's fixed in above PR
