### ISSUE TITLE
GET https://127.0.0.1:9443/api/am/publisher/v1/subscriptions is not working as expected

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#8825]
### Description:
APIM 310
Retrieving all subscriptions for the user's APIs return a Bad request.
GET https://127.0.0.1:9443/api/am/publisher/v1/subscriptions

Response:
**{"code":400,"message":"Bad Request","description":"Validation Error","moreInfo":"","error":[{"code":"400_subscriptionsGet.arg0","message":"subscriptionsGet.arg0: may not be null","description":null}]}**

### Steps to reproduce:
- Create an API and subscribe it to an app
- Use below curl command to retrieve all subscriptions

**curl -X GET "https://localhost:9443/api/am/publisher/v1/subscriptions" -H  "accept: application/json" -u admin:admin -k**
or
**curl -X GET "https://localhost:9443/api/am/publisher/v1/subscriptions" -H  "accept: application/json" -H "Authorization: Bearer 1e99cbc4-cd8e-3fa3-ae6a-cb273ce48672" -k** (token bound with apim:subscription_view) 

- Observe above mentioned response

**Comment by Arshardh** [comment]
This resource requires the apiId to be sent as a query param right?
`curl -X GET "https://localhost:9443/api/am/publisher/v1/subscriptions?apiId=bab78d5b-93d1-40f0-a220-1a68b429d406" -H "accept: application/json" -u admin:admin -k`
