### ISSUE TITLE
The charset is forcefully set to the Content-Type header 

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#8839]
### Description:
The charset is forcefully set to the Content-Type header. 

https://github.com/wso2/product-ei/issues/4082

### Affected Product Version:

AM-2.5.0
### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/wso2-synapse/commit/fabb6fb18b0c90636ae9abcebc1ee260c37c8c6f
