### ISSUE TITLE
Role with all the permission not allowed to access the Admin Portal

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#8842]
### Description:
Role with all the permission not allowed to access the Admin Portal

### Steps to reproduce:

1. Create a new role called "Manager"
2. Assigned all the permission to it.
3. Create a new user.
4. Assign a Manager role to new users.
5. Try to log in into the Admin Portal
6. Admin Portal mention 403
![Screen Shot 2020-07-29 at 12 38 58 PM](https://user-images.githubusercontent.com/3397321/88845108-88e27c80-d198-11ea-81e0-9e21c4a01cf8.png)

### Affected Product Version:
APIM 3.2.0 Beta

### Environment details (with versions):
- OS:  MacOs 10.15
- JDK: 11

#### Suggested Labels:
Bug

**Comment by chamilaadhi** [comment]
Hi Vanji,
We have done a fix (https://github.com/wso2/carbon-apimgt/pull/9088) for this and it will be available in the RC pack. With the fix, you will have to set a role to **apim:admin** scope in the **tenant-conf.json** file in the registry and then use that role to a user. 
Thanks for reporting this issue.

**Comment by vanjikumaran** [comment]
@chamilaadhi Does that mean, permission tree still not play a roll here?

**Comment by chamilaadhi** [comment]
@vanjikumaran yes that is correct. Admin portal is written on top of the admin rest apis. These apis are protected by scopes and roles are mapped to these scopes. So users who have the role related to this scope are authorised. 

As an additional information, we have provided a UI in the admin portal to configure this role to scope mapping. so you no longer need to manually edit the tenant-conf.json file in the registry
