### ISSUE TITLE
Error when trying to attach a shared scope to an API that has other scope schemes already defined

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#8843]
### Description:
Getting an error when trying to attach a shared scope to an API that has other scope schemes already defined
```
ERROR - ApisApiServiceImpl Resource Scope 'sharedScope' not found.
```

### Steps to reproduce:
1. Create an API using a swagger that already has other scope schemes (ex: petstore with petstore_auth oauth scheme)
2. Create a shared scope
3. Try to attach the shared scope to a resource.

### Affected Product Version:
APIM 3.2.0 latest (6.7.157-SNAPSHOT)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9090
