### ISSUE TITLE
NTLMGrantClientWithHandshake directory is not available

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#8881]
### Description:
`<APIM_HOME>/samples/NTLMGrantClientWithHandshake` is not available in the APIM pack (RC1).

### Content Positioning in Documentation:
Step 2 on this documentation: https://apim.docs.wso2.com/en/next/learn/api-security/oauth2/grant-types/ntlm-grant/#invoking-the-token-api-to-generate-tokens

**Comment by Krishanx92** [comment]
Its now there in the doc: https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/ntlm-grant/
