### ISSUE TITLE
[3.2.0] CORS issue in Publisher Test Console

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8883]
### Description:

As out-of-the-box, when trying out the `Test Console` feature in the Publisher portal, it is throwing a CORS error for the `testkey` value in the browser.

Furthermore, the documentation for the new `Test Console` feature is missing.

### Steps to reproduce:

1. Login to the Publisher portal
2. Deploy the sample `PizzaShack` API
3. Go to Test Console > Initialize Test
4. Invoke the API and check the Console Tab

### Affected Product Version:

- APIM v3.2.0 - RC1

**Comment by Arshardh** [comment]
Duplicate : https://github.com/wso2/product-apim/issues/8867

**Comment by Arshardh** [comment]
Documentation: https://apim.docs.wso2.com/en/next/learn/design-api/create-api/test-a-rest-api/#test-a-rest-api

**Comment by Arshardh** [comment]
This issue. was fixed with https://github.com/wso2/product-apim/pull/8869
