### ISSUE TITLE
[3.2.0] Admin Portal UI Inconsistency

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8888]
### Description:

In the new Admin portal, the `Advanced Policies` and `Subscription Policies` table views contain hyperlinks applied to the name of the policies. But the `Application Policies` are missing it. Please find the attached Gif where the `Advanced Policies` and `Subscription Policies` names are hyperlinked and not the `Application Policies`

![admin-ui-inconsistency](https://user-images.githubusercontent.com/29927177/89148733-49d97000-d578-11ea-915c-57c5a22c153c.gif)

Is these UI changes were made intentionally or this can be fixed to have consistent behavior across the Policy views. 

Thanks in advance.

### Steps to reproduce:

1. Log in to the Admin portal
2. Click on `Advanced Policies` or `Subscription Policies` (the name of the policies are hyperlinked)
3. Click on `Application Policies` (the name of the policy is not hyperlinked)

### Affected Product Version:

- API Manager v3.2.0 - RC1

**Comment by kavishkafernando** [comment]
Hi @athiththan11 

We did this intentionally. The policies that are linked have an individual create/edit page instead of a pop up.
In policy types with pop ups we haven't linked the policy name.

Are we going to change this behaviour @tmkasun @chanaka3d @erangatl ?

**Comment by chanaka3d** [comment]
Yes. This is the behavior we agreed upon. If we make the name a link and it triggers a popup, it looks odd IMO.

**Comment by athiththan11** [comment]
Hi @chanaka3d and @kavishkafernando 

Thank you for your insights and update.

@chanaka3d, I raised this question, since all the table views are having the `Edit` icon as well at the end of each row element, and both the `Advanced` and `Subscription` policy table views are hyperlinked with the name as well. Therefore, thought this seems to be an inconsistent behavior among the views.

Thank you

**Comment by chanaka3d** [comment]
Yes. There is a difference between the behavior of the two pages. But we can't route the user to a new page when they click the link since there is no such full page view. This difference with the links is intended to provide the different behaviors of the UIs. So we are keeping it as it is since it's intentionally done.
