### ISSUE TITLE
[3.2.0] Role Permission table view is not responsive

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8889]
### Description:

The `Role Permission` view in the Admin Portal is not responsive to the pagination selections. When changing the items per page count in the table view, it creates an empty white space after the existing rows. Please find the attached Gif for the reference

![role-permission-view](https://user-images.githubusercontent.com/29927177/89149181-7b067000-d579-11ea-8edb-788eaef0e19f.gif)

Moreover, the values listed for the items per page are different from other views (for example, all the other table views contain the number of 10, 15, and 100, and this view contains 5, 10, 40).

### Steps to reproduce:

1. Log in to the Admin portal
2. Go to Role Permission view
3. Change the items per page from 5 to 10 or 40 (extra white space is can be observed in the table view)

### Affected Product Version:

- API Manager v3.2.0 - RC1

**Comment by Arshardh** [comment]
Duplicate issue for https://github.com/wso2/product-apim/issues/8859
