### ISSUE TITLE
OpenAPI documentation issues: publisher-api.yaml file

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#8895]
### Description:
Parsing error is shown when loaded to the swagger.io

<img width="685" alt="Screenshot 2020-08-03 at 19 21 12" src="https://user-images.githubusercontent.com/4861150/89190052-86c85580-d5be-11ea-826b-9cacd632912b.png">

**Comment by chamilaadhi** [comment]
API creation sample payload needs to be changed

**Comment by chamilaadhi** [comment]
Same issue is there in store-api.yaml as well

**Comment by mushthaq33** [comment]
Closing as it is fixed
