### ISSUE TITLE
Read Me is not updated to 3.2.0, Still have information of 2.6.0 , 2.5.0

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-apim#8902]
### Describe your problem(s)
Read me file located in the Home directory of the release still has information related to 2.6.0.

### Affected Product Version:
3.2.0-RC1 

Installation & Running
==================================

1. Extract the wso2am-2.6.0.zip and go to the 'bin' directory
2. Run the wso2server.sh or wso2server.bat script based on you operating system.
=====
Documentation
==============

On-line product documentation is available at:
        https://docs.wso2.com/display/AM250/WSO2+API+Manager+Documentation

=====
Known Issues of WSO2 API Manager
==================================

All known issues of WSO2 API Manager are filed at:

* https://wso2.org/jira/issues/?filter=14454 
* https://github.com/wso2/product-apim/issues?q=is%3Aopen+is%3Aissue+label%3A2.6.0

=====
I think we have to updated the copy right year as well.

**Comment by Arshardh** [comment]
Fixed
