### ISSUE TITLE
Unwanted field in the document

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-apim#8906]
### Description:
As in the attached image, Though it is pointing as **token type**, There is no such field to configure. It makes the user confusing. So, Please edit the image in the document https://apim.docs.wso2.com/en/next/getting-started/quick-start-guide/

![JWT](https://user-images.githubusercontent.com/7627481/89231935-35f33580-d59b-11ea-8b17-4245f9da5eb1.png)

**Comment by Arshardh** [comment]
Trackid with https://github.com/wso2/docs-apim/issues/1601

**Comment by Arshardh** [comment]
Fixed
