### ISSUE TITLE
Generating opaque tokens - Not matching to the document

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-apim#8907]
### Description:
As per the documentation [1] when we try to change the token type expecting bellow UI,
![Expectted](https://user-images.githubusercontent.com/7627481/89237504-33e3a380-d5a8-11ea-954b-a69eabfe1540.png)

But what i find in 3.2.0 - RC 1
is as follows.

![3 2 0](https://user-images.githubusercontent.com/7627481/89237532-48c03700-d5a8-11ea-816b-35331ef1929e.png)

Why is this difference

[1] https://apim.docs.wso2.com/en/next/learn/api-security/oauth2/access-token-types/opaque-tokens/#secure-apis-using-oauth2-opaquereference-access-tokens

### Affected Product Version:
3.2.0-RC1

**Comment by Arshardh** [comment]
We have removed the token type selection in 3.2.0. We are tracking the documentation issue via https://github.com/wso2/docs-apim/issues/1601

**Comment by Arshardh** [comment]
This was fixed
https://github.com/wso2/docs-apim/issues/1601
