### ISSUE TITLE
CPU Keep 100% with the JDK 11 (After Oracle JDK 8  miner version 261 it is getting reproduced) 

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#8908]
### Description:
CPU Getting spiked suddenly even with a very low load and keep halted at 100% even after the load reduced.

### Steps to reproduce:

- Create an API responding with the status code 503
- Do several API invocations

### Affected Product Version:
- Any Version

### Environment details (with versions):
- Oracle JDK 8 and the miner version 261 Or
- Any JDK 11 (Oracle or Open JDK)

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/wso2-httpcore-nio/pull/38

**Comment by TanyaM** [comment]
Need to release httpcore-nio version and use newer version in synapse and that synapse version needs to be used in apim.
@Arshardh please note.

**Comment by slarti-b** [comment]
We had what appears to be the same problem with OpenJDK 1.8.0_312.  Seems that OpenJDK 1.8.0_302 is OK, but 312 is not.  This was on CentOS 7 with APIM 2.6.0.  

The issue refers to 261 not 312 but it's talking oracle JDK and this was with OpenJDK so I'm assuming it's the same issue as the symptoms (eats all the CPU you give it without significant load) seem the same so mentioning it.
