### ISSUE TITLE
API Product Restrict by role(s) does not work

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8916]
### Description:
API Product - Design Configurations - Developer Portal Visibility - Restrict by role(s) does not work. Even when Developer Portal Visibility is set back to Public it's not visible in Developer Portal.

### Affected Product Version:

3.2.0 RC1

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Cannot reproduce in Latest pack
