### ISSUE TITLE
Improvement to Application override feature.

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#8918]
### Describe your problem(s)
Files in source directory would need to be reconfigured to reference the AppComponents and AppData directories by default. 

### Affected verison

APIM-3.1.0

**Comment by vithu30** [comment]
If there are new files introduced for UI customization are imported in the format ```import NewFile from 'AppOverride/src/app/components/Apis/Listing/NewFile';```, when building Devportal component with npm run build:prod, following error is thrown:

```
ERROR in ./source/src/app/components/Apis/Apis.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\~\repository\deployment\server\jaggeryapps\devportal\source\src\app\components\Apis\Apis.jsx: Octal literal in strict mode (26:38)
...
import NewFile from 'C:\~\repository\deployment\server\jaggeryapps\devportal/override//src/app/components/Apis/Listing/NewFile';
```
This is caused due to the issue in file path separator.

**Comment by rmsamitha** [comment]
The original issue is already fixed via https://github.com/wso2/product-apim/issues/9341
