### ISSUE TITLE
[3.2.0][UI] 'GET TEST KEY' button in the try out window of dev portal is not working.

### ISSUE THREAD

**Issue by Ketharan** [wso2/product-apim#8920]
### Description:
'GET TEST KEY' button in the try out window of dev portal is not working.

Following log found in browser console :
```
TryOutController.jsx:249 TypeError: Cannot read property 'keyMappingId' of undefined
    at Application.jsx:117
```

### Steps to reproduce:
create an API
create an app
subscribe the API with that app
Create consumer key and secret for the app
go to the try out window and click the 'GET TEST KEY' Button

### Affected Product Version:
3.2.0-rc1

### Environment details (with versions):
Browser : Chrome 81.0.4044.138

#### Suggested Labels:
Type/Bug, Priority/Normal

**Comment by CrowleyRajapakse** [comment]
This is fixed and not reproducible in the latest
