### ISSUE TITLE
Option to mark mandatory fields when adding Key Manager

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#8924]
### Describe your problem(s)
As per the current implementation, certain fields are marked as mandatory when creating a Key Manager instance via admin portal. For instance, Client registration endpoint, introspection endpoint, token endpoint, revoke endpoint etc.

Some of these configurations may not be available for all vendors. For instance, revocation endpoint has been introduced in the latest versions of KeyCloak. (Refer [1] and [2])

Hence it would be better to make the mandatory fields configurable via a configuration. 

[1] https://issues.redhat.com/browse/KEYCLOAK-5325
[2] https://issues.redhat.com/browse/KEYCLOAK-14289

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise.
