### ISSUE TITLE
[3.2.0][Doc] Missing docs to configure third-party Key Manager from Admin Portal

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8926]
### Description:

Missing documentation to configure third-party key managers (for both `Okta` and `Keycloak`) from the Admin portal in API Manager 3.2.0. The [doc](https://apim.docs.wso2.com/en/next/install-and-setup/setup/distributed-deployment/configure-a-third-party-key-manager/#configure-a-third-party-key-manager) refers to an external [GitHub reference]() to configure Okta as third-party Key manager which is missing a couple of information related to Admin portal configurations and steps.

### Content Positioning in Documentation:

- API Manager Docs: [https://apim.docs.wso2.com/en/next/install-and-setup/setup/distributed-deployment/configure-a-third-party-key-manager/#configure-a-third-party-key-manager](https://apim.docs.wso2.com/en/next/install-and-setup/setup/distributed-deployment/configure-a-third-party-key-manager/#configure-a-third-party-key-manager)
- GitHub reference: [https://github.com/wso2-extensions/apim-km-okta/blob/OKTA-OAuth-Client-2.0.0/docs/config.md](https://github.com/wso2-extensions/apim-km-okta/blob/OKTA-OAuth-Client-2.0.0/docs/config.md)

**Comment by isharac** [comment]
Docs are available.
please refer https://apim.docs.wso2.com/en/next/administer/key-managers/overview/
