### ISSUE TITLE
[3.2.0] Cannot find application error when loading Devportal

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#8933]
### Description:

The following error-trace is observed when loading the Devportal page once after a server start/restart (from second start onwards). This is not observed for the Publisher portal.

```log
[2020-08-05 13:12:39,958] ERROR - OIDCSessionIFrameServlet Error while retrieving OAuth application information for the provided client id : null, Cannot find an application associated with the given consumer key : null
```

![cannot-find-application](https://user-images.githubusercontent.com/29927177/89386564-e0479600-d71e-11ea-8769-fe1f631ecb80.gif)

### Steps to reproduce:

1. Start the API Manager and login to the Devportal
2. Restart the server (close all active tabs and browsers) and open a browser and go to Devportal
3. The above-reported error-trace can be observed in the wso2carbon logs

### Affected Product Version:

- API Manager v3.2.0 - RC1

**Comment by tmkasun** [comment]
Did you change the server hostname in deployment toml ?

**Comment by athiththan11** [comment]
@tmkasun 
No changes were done to the `deployment.toml`. 
The API Manager was running with the default shipped configurations.

**Comment by ruks** [comment]
This is due to the token information persisted in the browser in an old APIM setup. Open in a private window this issue will not occur. Normally this can be reproduced when you redeploy new fresh pack or clean up DBs.

**Comment by HiranyaKavishani** [comment]
Same issue [1] has been closed

[1] https://github.com/wso2/product-apim/issues/7874
