### ISSUE TITLE
Cannot assign apim_analytics related scopes to a role

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#8941]
### Description:
In admin portal it is not possible to assign apim_analytics related scopes and apim:app_update scope to a role, via role permissions page.

### Steps to reproduce:
1. Login to admin portal
2. Go to settings > Role permissions > Select "Permissions" link on any role > 
3. In the permission trees listed "apim_analytics:*" scopes are are listed, so they can't be assigned.

### Affected Product Version:
APIM-3.2.0-RC1

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time and is not valid for the latest APIM versions (4.x)
