### ISSUE TITLE
UI Issue in GraphQL API listing view

### ISSUE THREAD

**Issue by chaamini** [wso2/product-apim#8943]
Hi there,

I took the lastest WUM updated APIM 3.1.0 pack. When I created a GraphQL API the API tile in the UI has an alignment issue where the delete button does not seem to have a proper padding offset set. Could you look into the issue? 
Browser used - Chrome

<img width="242" alt="Screenshot 2020-08-05 at 19 45 17" src="https://user-images.githubusercontent.com/4281345/89423797-937eb200-d754-11ea-99a2-c7eb5b435fab.png">

**Comment by Krishanx92** [comment]
This is fixed in latest pack, hence closing
