### ISSUE TITLE
API Product Runtime Configurations - error on changing any control

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8949]
### Description:

API Product Runtime Configurations - error on changing any control

![image](https://user-images.githubusercontent.com/20179540/89501164-80b1bf00-d7e0-11ea-92f4-c0dba13e8080.png)

### Affected Product Version:

RC2

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/9143
