### ISSUE TITLE
Wrong Content when accessing Product URL for admin v0.17

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#8950]
### Description:
When you access this URL in APIM RC1 content says v0.16 instead of v0.17

https://localhost:9443/api/am/admin/v0.17/swagger.json

<img width="1680" alt="Screenshot 2020-08-06 at 12 40 53" src="https://user-images.githubusercontent.com/5195851/89502444-a4760480-d7e2-11ea-9778-4effd6d17ae6.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
Closing since we are removing admin REST APIs 0.17 from 4.0 release
