### ISSUE TITLE
Add documentation button is not visible for API creators

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#8978]
**Steps to reproduce**
1. Login to API Publisher as a creator
2. Create an API
3. Navigate to the Documents tab
4. Add a new doc and navigate to doc list page

**Behavior**
The Add documentation button is not visible for creators, hence more docs cannot be added

**Comment by Sarangan0219** [comment]
This issue is not reproducible in the latest version of the APIM pack.

![Screenshot from 2020-11-25 12-44-28](https://user-images.githubusercontent.com/60866295/100194660-156d3380-2f1c-11eb-8d03-5ad23187d3a3.png)
