### ISSUE TITLE
Tokens cannot be generated with shared scopes

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#8986]
### Description:
In 2.0 to 3.2 migrated setup tokens cannot be generated from shared scopes.

### Steps to reproduce:
1. Migrate to 3.2 from 2.0
2. Create and Attach a shared scope to an API
3. Subscribe to the API and generate an access token for the shared scope
4. The generated token contains only default scopes

### Affected Product Version:
APIM 2.0 to 3.2 Migration

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by dushaniw** [comment]
This is not reproducible. hence closing.
