### ISSUE TITLE
Publisher test-console UI shows apikey,basic radio buttons

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#8987]
### Description:
If a user adds application-layer security(basic auth or api-key), apikey and basic radio buttons are visible in the publisher test console.
![image](https://user-images.githubusercontent.com/12996810/89707572-f5c1f780-d98c-11ea-8a24-c1110d3aab37.png)

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by hasuniea** [comment]
Fix for the issue[1].
[1].https://github.com/wso2/carbon-apimgt/pull/9152

**Comment by tmkasun** [comment]
Closing the issue as it's fixed in above PR
