### ISSUE TITLE
[APIM 3.1.0] Error when starting API Publisher product profile

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-apim#8989]
### Description:
An error occurs when trying to start APIM 3.1.0 pack in a api-publisher product profile.

![image](https://user-images.githubusercontent.com/25485783/89711653-30398d80-d9a9-11ea-9d2e-dc1cf31c20f7.png)

### Steps to reproduce:
1. Run `sh profileSetup.sh -Dprofile=api-publisher` to setup api-publisher product profile
2. Run `sh wso2server.sh -Dprofile=api-publisher` to start the server 

### Affected Product Version:
APIM 3.1.0

### Environment details (with versions):
- OS: Ubuntu 20.04

**Comment by npamudika** [comment]
This has been fixed now in the WUM updated APIM 3.1.0 pack with the timestamp 1597713792746.
