### ISSUE TITLE
Errors thrown when deploying API when we have special characters in the admin password even with CDATA

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-apim#8998]
### Description:
Unable to deploy sample API when having special characters in super admin password. As per the document [1], We can not include @ or % without URL encoding. So, assumption is all others should be possible. 

### Steps to reproduce:

Use following super admin password : 

```
[super_admin]
username = "foo_admin"
password = "<![CDATA[~^&*#`43d:3;]]>"
```

Login and try to deploy the sample API

[1]: https://apim.docs.wso2.com/en/next/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#change-the-super-admin-credentials

### Affected Product Version:
APIM 3.2.0 - RC2

[TenantDeployAPIError.txt](https://github.com/wso2/product-apim/files/5048086/TenantDeployAPIError.txt)

**Comment by rmsamitha** [comment]
@shammijayasinghe 
And the approach you have to follow to change super admin credentials has been changed by the fix. We will update the docs [1] soon. [2]
If there is any special character (including all others than @ and % too) in the password, you have to specify it at 2 location in the deployment.toml

Your example: 
password: ~^&*#`43d:3;
url encoded password: "~%5E%26*%23%6043d%3A3%3B"

Put the CDATA wrapped password and url enncoded password accordingly as below under the [super_admin] and  [apim.throttling.jms]  sections in deployment.toml

```
[super_admin]
username = "foo_admin"
password = "<![CDATA[~^&*#`43d:3;]]>"
create_admin_account = true

[apim.throttling.jms]
username = "foo_admin"
password = "~%5E%26*%23%6043d%3A3%3B"
```

[1] https://apim.docs.wso2.com/en/next/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#change-the-super-admin-credentials
[2] Doc issue : https://github.com/wso2/docs-apim/issues/1662
