### ISSUE TITLE
Login issues with tenants in 2.x - 3.2 migrated APIM

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9000]
### Description:
When trying to log in to publisher portal through a tenant user(even tenant admin) the following error is logged and the UI loading langs.
```
ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
```

At this time even the dev portal login fails.

However if we restart the server, and try to login to the dev portal first through an admin user, the login is successful and then the issue with publisher login is also resolved.

### Steps to reproduce:
1. Migrate from 2.x to 3.2
2. Try to login to publisher portal with tenant admin
    - here the scope validation error occurs
3. Try to login to dev portal
    - UI hangs
4. Restart the serever
5. Try to login to dev portal through tenant admin
    - this is successful
6. Then try to login to publisher through tenant user/admin
    - this is also successful

### Affected Product Version:
2.x to 3.2 Migrated latest APIM

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by msm1992** [comment]
Tenant login issue gets resolved after restarting the server, hence not a blocker for migration

**Comment by tharikaGitHub** [comment]
Tried this in 2.5.0 to 3.2.0 migration, but this issue was not observed.

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/46. Hence resolving.
