### ISSUE TITLE
Error is not thrown when creating Documents with special Characters from UI

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#9008]
### Describe your problem(s)

Add a document with a name including some special characters. Error is not getting thrown from the UI. When we click create document UI responds with nothing. 

![Screenshot from 2020-08-10 18-04-12](https://user-images.githubusercontent.com/60866295/89783109-0496de80-db34-11ea-8ce1-f84750db9832.png)

### Describe your solution

We need to notify from the UI that the Document name should not contain any special characters.

![Screenshot from 2020-08-10 18-02-26](https://user-images.githubusercontent.com/60866295/89783076-f6e15900-db33-11ea-998c-afe3194c065f.png)

### Affected Versions
APIM 3.2 RC2

**Comment by hisanhunais** [comment]
Similar Issue reported in https://github.com/wso2/product-apim/issues/9682

**Comment by Sarangan0219** [comment]
This issue is fixed in the latest master via https://github.com/wso2/carbon-apimgt/pull/9651.

![Screenshot from 2022-01-19 16-43-02](https://user-images.githubusercontent.com/60866295/150119233-9b841f92-4e13-4f89-9f57-c6fdc40bef95.png)
