### ISSUE TITLE
[Admin Portal] Validation issues in Advanced throttling policy

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#9012]
### Description:
It allows saving new advanced throttling policy with special characters for the attributes, (-) values for the request count even it shows the server errors

![Screen Shot 2020-08-10 at 8 55 08 PM](https://user-images.githubusercontent.com/29066805/89800331-46cc1a00-db4c-11ea-9d4a-2b96c98967ae.jpg)

![Screen Shot 2020-08-10 at 8 55 36 PM](https://user-images.githubusercontent.com/29066805/89800199-108e9a80-db4c-11ea-8d6a-21c5717856b9.jpg)

### Steps to reproduce:
1. Login to the admin portal
2. Add new Advanced Throttling policy including special characters and (-) values for requests count

### Affected Product Version:
3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Sarangan0219** [comment]
We can't create throttling policies with special characters. Validations are already handled for this flow.

![Screenshot from 2020-11-25 15-49-36](https://user-images.githubusercontent.com/60866295/100216865-ce416b80-2f38-11eb-8399-4211233cef76.png)

**Comment by HiranyaKavishani** [comment]
We are closing this as this bug is no longer reproduced .
