### ISSUE TITLE
UI validation issues in adding properties to APIs and Application Creation

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#9036]
### Description:

1) When adding API Properties, the property name with special characters is getting saved successfully. But It should not.

![Screenshot from 2020-08-11 11-57-29](https://user-images.githubusercontent.com/60866295/89864630-e24fa000-dbc9-11ea-8ea3-ff8264818e7d.png)

2) When adding a property name with spaces or special characters UI is not validating responsively.

![Screenshot from 2020-08-11 11-59-06](https://user-images.githubusercontent.com/60866295/89864733-15922f00-dbca-11ea-974e-abd5b717b6a4.png)

We should show that the `name cannot contain whitespaces or special characters`  error stack in the UI.

3)  When creating applications UI should responsively validate for the inputs. (If there are special characters it should show the error that special characters are not allowed)
![Screenshot from 2020-08-11 12-04-29](https://user-images.githubusercontent.com/60866295/89865213-ed570000-dbca-11ea-86de-2020526c0846.png)

### Solution
3)
![Screenshot from 2020-08-11 12-06-55](https://user-images.githubusercontent.com/60866295/89865372-35762280-dbcb-11ea-8952-82b020bf0d24.png)

### Affected Product Version:
APIM 3.2 RC2

**Comment by Krishanx92** [comment]
Not reproduce in the APIM-4.4.0 latest pack
