### ISSUE TITLE
Deleting a user doesn't revoke the already generated tokens

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9039]
### Description:
Once a user is deleted, tokens generated on behalf of him must be revoked. 
But, still the APIs are invocable with the same token after the user is deleted.

### Steps to reproduce:
1. Create a user "user1" with Internal/subscriber role.
2. Login to dev portal using "user1"
3. Create an application - App1
4. Subscribe App1 to API1
5. Generate a token for App1 using password grant.
6. Invoke the API - invocation is successful.
7. Now login to the carbon console using "admin" and delete the user "user1"
8. Invoke the API again - 

Still invocation success.

It seems the token is usable till its expiry. 
Even after restarting the server, token can be used.

**Comment by tharindu1st** [comment]
This was fixed from 3.2.0 onwards
