### ISSUE TITLE
[3.2] generate access token button not working when third party km connected 

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#9042]
Curl to generate access token button is not working when third party km is connected

![errorgif](https://user-images.githubusercontent.com/18071381/89895374-505f8b80-dbf9-11ea-9495-4a1daa33b71d.gif)

**Comment by CrowleyRajapakse** [comment]
Seems fixed now, will check with IS as 3rd party key manager also.
<img width="1644" alt="Screenshot 2020-09-25 at 17 07 33" src="https://user-images.githubusercontent.com/23296184/94264246-fe2dbc00-ff53-11ea-8a21-fd1654f003ca.png">

**Comment by CrowleyRajapakse** [comment]
This issue isn't preset in the APIM 3.2, hence closing the ticket.
<img width="1634" alt="Screenshot 2020-09-28 at 10 05 42" src="https://user-images.githubusercontent.com/23296184/94391189-812c5d80-0172-11eb-8931-5220433347db.png">
