### ISSUE TITLE
"Role-Based Access Control using XACML" doc needs to update

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9046]
### Description:
https://apim.docs.wso2.com/en/next/learn/api-security/authorization/role-based-access-control-using-xacml/#enabling-role-based-access-control-using-xacml

Few issues:

1. Publisher portal screenshot is outdated.
![image](https://user-images.githubusercontent.com/1591316/89929383-cd552a00-dc26-11ea-83f9-00ff7a92cb79.png)

New:
![image](https://user-images.githubusercontent.com/1591316/89929769-53717080-dc27-11ea-9e85-2c0c47fd8df9.png)

![image](https://user-images.githubusercontent.com/1591316/89929759-50768000-dc27-11ea-934e-42ff04086151.png)

2. Outdated configuration example.

![image](https://user-images.githubusercontent.com/1591316/89929514-ea89f880-dc26-11ea-83a0-bcf5dd3d91cb.png)

New:

> By default, in API Manager `UniqueIDJDBCUserStoreManager` is enabled. When you are moving to the `UniqueIDReadWriteLDAPUserStoreManager`, make sure you have commented the configuration of default `[user_store]` and keep only one user store configuration `<API-M_HOME>/repository/conf/deployment.toml` in both nodes. You can use the same `[user_store]` configuration defined in `<IS_HOME>/repository/conf/deployment.toml` to define the `[user_store]` in API Manager. Make sure to update `connection_url` to correctly point to the Identity Server.

**Comment by HiranyaKavishani** [comment]
Its already updated. Hence closing the issue

[1] https://apim.docs.wso2.com/en/latest/design/api-security/authorization/role-based-access-control-using-xacml/#enabling-role-based-access-control
