### ISSUE TITLE
Missing templated entries for identity.xml

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#9050]
### Description:
The following entries are not templated. Hence cannot apply via deployment.toml
```
<OpenIDConnect> 
... 
<RedirectToOAuth2ErrorPage>true</RedirectToOAuth2ErrorPage>
...
</OpenIDConnect>
```
```
<OAuth> 
... 
<AllowAdditionalParamsFromErrorUrl>true</AllowAdditionalParamsFromErrorUrl>
...
</OAuth>
```
### Affected Product Version:
3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by AmaliMatharaarachchi** [comment]
Related https://github.com/wso2/carbon-identity-framework/pull/2940 and https://github.com/wso2/product-is/issues/6569
