### ISSUE TITLE
[2.x to 3.x Migration] Subscriptions are not visible for a user with Internal/publisher role after the migration

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#9056]
### Description:
After migrating from APIM 2.x (Tested with APIM 2.2.0) to APIM 3.x (Tested with APIM 3.2.0), a user with the Internal/publisher role cannot view the subscriptions of a particular API. Refer **Steps to reproduce** for further information.

This is happening because in **tenant-conf.json**, the **apim:subscription_view** is not available for **Internal/publisher** after the migration. (But if you check a non-migrated APIM 3.2.0 setup, the Internal/publisher also has this scope)

This should be fixed from the migration client. Also, this needs to be fixed for other scopes as well, if there are any missing user roles. (Need a common fix to all)

### Steps to reproduce:
1. After migrating from APIM 2.2.0 to APIM 3.3.0, login to Publisher Portal as a user with Internal/publisher role.
2. Click on an API and navigate to the **Subscriptions** tab.
3. The UI will keep loading as shown below.
    ![image](https://user-images.githubusercontent.com/25246848/89996956-151c9580-dca9-11ea-90c7-533f8147a4bb.png)
4. Check the server now. You will see the below log.
    ```
    [2020-08-12 14:34:45,954] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
    ```

### Affected Product Version:
- APIM 2.2.0 to APIM 3.x migration
- APIM 2.1.0 to APIM 3.x migration
- APIM 2.6.0 to APIM 3.x migration

### Environment details (with versions):
- OS: Ubuntu 20.04 LTS
- DB: PostgreSQL 12.3

**Comment by msm1992** [comment]
We have fixed this in 2.x to 3.2 migrations with https://github.com/wso2-extensions/apim-migration-resources/pull/47

**Comment by Krishanx92** [comment]
Close with above comment
