### ISSUE TITLE
Unable to edit an application in the devportal

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9058]
### Description:
Unable to edit the application in the devportal. When the edit button is clicked the page goes blank.

### Steps to reproduce:
1. Go to devportal
2. Click on an existing application or create a new app and click on that app
3. Click on the edit button
4. The UI goes blank as follows
![image](https://user-images.githubusercontent.com/20519000/90013794-9719b800-dcc3-11ea-89c7-07ec576ca30b.png)

### Affected Product Version:
WSO2 API Manager 3.2.0-RC3

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/9167
