### ISSUE TITLE
API Search not cleared after closing the popup.

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#9070]
### Description:
Create multiple APIs a publish them.
Create a new application and navigate to its subscription listing page.
Click the "SUBSCRIBE APIS" button next to "Subscription Management" title.
Search for an API.
Without clearing the search close the window.
Now again open the window without refreshing the page.
The previous filtered APIs are displayed, but the search text is not visible in the text box.
After clicking the search button full API list can be viewed.

<img width="667" alt="Screen Shot 2020-08-13 at 3 22 55 PM" src="https://user-images.githubusercontent.com/3424539/90120904-ed94fe00-dd78-11ea-80bc-aca205c5d636.png">

**Expected behavior**

When opening the popup for the second time, we need to show the text inside the search textbox.

**Comment by chathuranga95** [comment]
The text clear button `(X)` button inside the search text box doesn't clear the text in the search text box.
search is cleared and `Displaying all APIs` helper text is displayed under the search text box.
