### ISSUE TITLE
When test console is initialized for an API in created state, the API is still visible in dev portal 'search'

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9072]
### Description:
When test console is initialized for an API in created state, the API is still visible during dev portal 'search'.
expected : API should not be accessible through dev portal

### Steps to reproduce:
1. Create an API. (API is in created state)
2. Initialize test console. (This will update the lc state to prototyped, but set the enableStore api rxt field to false, so this API will not be retrievable when calling /apis GET endpoint as we have added the enableStore=(true or null) to the query)
3. However if I type the API name on the search bar, then this API will be accessible from dev portal.
When this happens the call goes to /search GET endpoint in store REST API and the enableStore=(true or null) is not added to the store query, making the API retrievable through this store endpoint. [1]

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1/impl/SearchApiServiceImpl.java#L53 

### Affected Product Version:

3.2.0 latest

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by hasuniea** [comment]
fixed from https://github.com/wso2/carbon-apimgt/pull/9232
