### ISSUE TITLE
[3.2.0][Admin Portal] Mandatory Fields are not marked in Key Manager UI

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9085]
### Description:

As per the documentation, it is mentioned that both the `Consumer Key Claim URI` and `Scope Claim URI` are **mandatory** fields. Please find the attached screenshot extracted from the [doc](https://apim.docs.wso2.com/en/next/administer/key-managers/configure-okta-connector/#configure-okta-as-a-key-manager).

<img width="705" alt="Screenshot 2020-08-16 at 18 10 10" src="https://user-images.githubusercontent.com/29927177/90334506-bf6b2480-dfeb-11ea-85a8-9cf8755726dd.png">

But, the respective fields in Key Manager interfaces are not marked as required/mandatory fields and it is also possible to save the KM configurations without those values filled. Please find the attached screenshot of the KM UI in the Admin portal

<img width="975" alt="Screenshot 2020-08-16 at 18 12 01" src="https://user-images.githubusercontent.com/29927177/90334546-00633900-dfec-11ea-84e0-fece7092f22a.png">

### Steps to reproduce:

- Verify the [documentation](https://apim.docs.wso2.com/en/next/administer/key-managers/configure-okta-connector/#configure-okta-as-a-key-manager) along with the UI represented in the Admin portal

### Affected Product Version:

- API Manager v3.2.0 - RC5

---

### Improvement Suggestion

> The improvement suggestion is not (completely) related to the above-mentioned scenario. This suggestion is to make the UX improved.

Moreover, displaying example values under each input field (as help text) would be much helpful when configuring the KM from the Admin portal without reaching to the docs each and every time. 

For example, the `Consumer Key Claim URI` and `Scope Claim URI` of the Okta are `cid` and `scp` as default. Since the Admin portal provides a drop-down to select the KM type from either WSO2/Okta/Keycloak, based on the selection altering the existing Help texts of those fields will be an added improvement to the experience.

- Current UI and the Help text of `Consumer Key Claim URI`

<img width="975" alt="Screenshot 2020-08-16 at 18 12 01" src="https://user-images.githubusercontent.com/29927177/90334700-276e3a80-dfed-11ea-9315-fde9ee4ecffd.png">

- Improved UI with an additional example value

<img width="945" alt="Screenshot 2020-08-16 at 18 22 55" src="https://user-images.githubusercontent.com/29927177/90334797-bbd89d00-dfed-11ea-9f25-726a14e2a419.png">

**Comment by wasuradananjith** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/9217. Hence can close the issue.
