### ISSUE TITLE
Changes are not reflected in advanced endpoint configuration in SOAP endpoint

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#9092]
### Description:
When we change the message content optimize type in the advanced endpoint configuration via the publisher portal, we could not see the changes reflected in advanced endpoint configuration in SOAP endpoint.

### Steps to reproduce:

1. Login to the publisher portal and create a SOAP API. 
2. Then change the advanced endpoint configuration as shown below screenshot.

![image](https://user-images.githubusercontent.com/28176167/90361987-2553bc80-e07d-11ea-8029-9b8e61df603a.png)

3. Click on save.
4. Check again advanced configuration and you will see the changes are not there. It has the default type as shown below screenshot.
![image](https://user-images.githubusercontent.com/28176167/90362144-88ddea00-e07d-11ea-9bc4-b056c5b1b99b.png)

### Affected Product Version:
APIM 2.6.0 -t 1594834553877

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by CrowleyRajapakse** [comment]
This is not an issue. This is working as expected.

**Comment by kunalspatil** [comment]
> This is not an issue. This is working as expected.
@CrowleyRajapakse, This is more like a UI issue. The API will work after this change but on UI part it still shows optimize as "SWA"

**Comment by CrowleyRajapakse** [comment]
Hi @kunalspatil ,
The implementation here is as follows,
We have only two optimisation mechanisms SWA and MTOM, and by default it's selected as SWA.
The third option here is "Leave As-Is", when you select that option it will reset and set the default value which is "SWA".
You can verify this by changing the value from SWA to MTOM and save. Then reload the page you can see the new value is correctly set as MTOM. Then select "Leave As-Is" and save and reload the page. Now the value will be set to default value which is "SWA".
<img width="853" alt="Screenshot 2020-09-24 at 12 10 05" src="https://user-images.githubusercontent.com/23296184/94110314-102e3280-fe60-11ea-84fa-3904c1fbd7fb.png">
If you can see the following image also we do have an "Leave As-Is" option in the format dropdown as well. It's functionality is also same as above mentioned. It will reset the value to default "SOAP 1.1".
<img width="917" alt="Screenshot 2020-09-24 at 12 10 35" src="https://user-images.githubusercontent.com/23296184/94110480-508db080-fe60-11ea-9ebb-6f1aa71ccb2e.png">

**Comment by CrowleyRajapakse** [comment]
please reopen if needed
