### ISSUE TITLE
Validation error message given for a long subscription policy name can be improved.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#9105]
### Description:
When a long subscription policy name is given, the error message given from the UI is not accurate.It gives "Name contains one or more illegal characters". This can be improved saying that the name is too long.
<img width="1440" alt="Screenshot 2020-08-18 at 15 14 32" src="https://user-images.githubusercontent.com/19996612/90502673-d9337580-e16b-11ea-87fe-f1ee708ea67d.png">

### Steps to reproduce:
Provide a long name to Subscription policy name and try to save.

### Affected Product Version:
APIM 3.2.0-RC5

### Environment details (with versions):
- OS: Mac OS Catalina 10.15.6
- Client: Postgres 12.3

**Comment by Meruja** [comment]
Closing the issue since it's fixed in wso2/carbon-apimgt#9206
