### ISSUE TITLE
Permissions in the Subscription Rate Limiting Policy is not getting persisted and not validated. Need to say how to add multiple permissions as well.

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#9108]
### Description:
Permissions in the Subscription Rate Limiting Policy is not getting persisted. When you give something like `Internal/admin` and save it and again go to edit of that policy, the given `Internal/admin` is replaced by the default `Internal/everyone`. Also when you provide something like `abcd` it is not validated from the UI. 

Also need to say how to add multiple permissions in here as well.
Also the input filed is a multi line one. That should be corrected as well.

<img width="1440" alt="Screenshot 2020-08-18 at 16 13 45" src="https://user-images.githubusercontent.com/19996612/90504184-5233cc80-e16e-11ea-975f-5da9165a9906.png">

### Steps to reproduce:
Mentioned above.

### Affected Product Version:
APIM 3.2.0-RC5

### Environment details (with versions):
- OS: Mac OS Cataline 10.15.6
- Client: PostgreSQL 12.3

**Comment by malinthaprasan** [comment]
Fixed with above PR https://github.com/wso2/carbon-apimgt/pull/9804 by @hisanhunais
