### ISSUE TITLE
Getting page not found issue for the API category help link

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#9112]
### Description:
It seems like there is an issue in the help Doc links.

### Steps to reproduce:
1. Log into the admin portal.
2. Click on the API categories.
3. Add API category.
4. You can see **help** in top right corner. Click on it. You will get a page not found issue for the doc link.
![image](https://user-images.githubusercontent.com/12996810/90507041-db4d0280-e172-11ea-9fba-1546589cb1ed.png)

### Environment details (with versions):
- OS: MAC OS
- Client: Oracle
- Env (Docker/K8s):

---

**Comment by erangatl** [comment]
These links will work when the 3.2.0 doc space is released, it will be release with product
