### ISSUE TITLE
Application Rate Limitation Policy Adding dialog box can be improved

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#9113]
### Describe your problem(s)
When trying to create an Application Rate Limiting policy with a long name (more than 30 characters), the UI provides a wrong error message: `Name contains one or more illegal characters `. This can be improved as `Name is too long`.

Application Rate Limiting policy adding dialog is not always displaying the validation errors under the input field. Observe the error (in the second screenshot) is not showing anymore when another input field is changed.

![throttling 2](https://user-images.githubusercontent.com/25490163/90506624-38948400-e172-11ea-90b6-159e3d017a09.png)
![application throttling UI error](https://user-images.githubusercontent.com/25490163/90506631-3a5e4780-e172-11ea-9ac1-904df59585a6.png)

#### Suggested Labels:
React/UI

**Comment by chathuranga95** [comment]
related: Similar behavior is reported in: https://github.com/wso2/product-apim/issues/9105

**Comment by Meruja** [comment]
Closing the issue since it's fixed in wso2/carbon-apimgt#9208
