### ISSUE TITLE
Can not add a Advanced Rate Limiting policy without description - Database DB2

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#9143]
### Description:
Can not add a Advanced Rate Limiting policy without description with database IBM DB2
No error logs in carbon console

<img width="1680" alt="Screenshot 2020-08-19 at 22 20 00" src="https://user-images.githubusercontent.com/23183042/90665991-6826b780-e26a-11ea-9973-71cc5d19f99d.png">

### Steps to reproduce:
Add Advanced Rate Limiting policy without description

### Affected Product Version:
APIM 3.2.0-RC5

### Environment details (with versions):
OS: Mac OS Catalina 10.15.6
DB: IBM DB2 11.5.4.0

**Comment by Sarangan0219** [comment]
Similar to this issue https://github.com/wso2/product-apim/issues/9007

**Comment by renuka-fernando** [comment]
This has fixed with above PR
Tested in APIM Snapshot 6.7.206 and IBM DB2 version 11.5.4 as the DB
