### ISSUE TITLE
Custom roles created from the carbon console are not listed in the Admin portal unless those are mapped or aliased

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#9148]
### Describe your problem(s)
1. Assume I have created some custom roles from the carbon console as below.
    ![image](https://user-images.githubusercontent.com/25246848/90770153-f81e3d00-e30e-11ea-9251-f23ad4acd5e8.png)
2. When I logged in to Admin portal and navigated to **Settings/Role Permissions**, the custom roles are not listed.
    ![image](https://user-images.githubusercontent.com/25246848/90770313-34ea3400-e30f-11ea-8614-283577d44fb0.png)
    ![image](https://user-images.githubusercontent.com/25246848/90770335-3e739c00-e30f-11ea-8e19-59057382bd73.png)

### Describe your solution
Currently, we only list mapped or aliased roles. But as an improvement, we can list all the roles to avoid the confusions that may arise.

**Comment by Krishanx92** [comment]
This role permission in not there in latest product.
