### ISSUE TITLE
Token refresh always fail in Publisher App

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9150]
### Description:
After expiring the current login session, there's underline code to refresh the token and it always seems to fail.

It redirects to the login page. After login, it gives a 400 and page goes blank.

![image](https://user-images.githubusercontent.com/1591316/90779336-52bd9600-e31b-11ea-9978-9d0fa61a38f0.png)

### Steps to reproduce:

![token_refresh_fail](https://user-images.githubusercontent.com/1591316/90779169-230e8e00-e31b-11ea-94ec-75dcd4947d31.gif)

**Comment by CrowleyRajapakse** [comment]
Fixed by https://github.com/wso2-support/carbon-apimgt/commit/ff6ee5b83b5832defe4e6994540e1301eb5cf307
