### ISSUE TITLE
Admin portal Dashboard is not displayed correctly when there are long API category names and descriptions

### ISSUE THREAD

**Issue by chathuranga95** [wso2/product-apim#9157]
### Description:
Attached a screenshot of the scenario.

![api categories card broken](https://user-images.githubusercontent.com/25490163/90854459-9b686400-e39a-11ea-8b93-2284ebd33c01.png)

### Steps to reproduce:
Login to admin portal.
Create one or more API categories with long names and/or long descriptions and go to the dashboard.

### Affected Product Version:
APIM 3.2.0 RC5

#### Suggested Labels:
React/UI

#### Suggested Assignees:
@chathuranga95

**Comment by tmkasun** [comment]
This is a common issue in lots of places, We need to make these boxes/grid items responsive and use `ellipsis` [doc](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp) inappropriate places (where text could get long text) to render an ellipsis ("...") to represent the clipped text.

@erangatl WDY ?

**Comment by tmkasun** [comment]
Another related issue in scope addition page

<img width="1677" alt="Screen Shot 2020-08-23 at 1 40 48 AM" src="https://user-images.githubusercontent.com/3313885/91001616-d7ddcf00-e5e9-11ea-8f9c-f563b74bec4c.png">
