### ISSUE TITLE
Product profiles doc 2.2.0

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#9158]
### Description:

Need to review steps mentions in product profiles doc. 
In order to get profiles to work, I had to follow this document [1] as well. 

[1] https://docs.wso2.com/display/AM220/Deploying+WSO2+API-M+in+a+Distributed+Setup#DeployingWSO2API-MinaDistributedSetup-Step6.5-ConfigureandstarttheTrafficManager

### Content Positioning in Documentation:

- Link: https://docs.wso2.com/display/AM220/Product+Profiles

- Heading (& Step):

- Any other reference:

---

**Comment by samgnaniah** [comment]
This is based on a much older version of API-M so will close this as not planned.
