### ISSUE TITLE
[Publisher] UI for configuring Analytics email configuration have unintended behaviour

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9162]
### Description:
When providing email addresses for analytics notifications in Publisher -> Settings UI page, It shows the following unintended behaviors

- When there is only one email added And tries to add 2nd email, the first and only one get replaced by the second address
- When I delete an existing email address and add it back, same email address gets added twice

![image](https://user-images.githubusercontent.com/3313885/90870650-83eba400-e3b7-11ea-910d-3894d7c0f2fa.png)

### Steps to reproduce:

- Enable APIM analytics, and goto settings page
- Enable analytics notifications and add multiple email addresses
- Save the changes and refresh the page
- Then try to add a new email address

### Affected Product Version:
- APIM 3.2.0 RC5

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Fixed in 3.2.0 version. Since this is not related to APIM-4.0.0 shall we close this issue?

**Comment by mushthaq33** [comment]
We need to fix this in 3.1.0 as well

**Comment by chanaka3d** [comment]
This issue is fixed in the 3.1.0 latest update level. We can close this issue.
