### ISSUE TITLE
csrftoken validation fail.

### ISSUE THREAD

**Issue by s4n7h0** [wso2/product-apim#917]
the csrftoken parameters is not validation at the server side for null values. For Instance, If the user sends request with csrftoken completely removed is successfully processed by the server. Apparently. X-CSRFToken header is not used within the admin console. This void the usage of csrftoken throughout the application. 

Can you please release a patch for this ?

**Comment by harsha89** [comment]
Please check the latest veersion and get back if the issue is persist.
