### ISSUE TITLE
Create policies in admin app and name includes / \ cause policy deployment error

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#9172]
### Describe your problem(s)
When we create policies in admin app and name includes / \ or something like them then policy deployment gives error

Error in BE
[2020-08-23 01:50:12,618] ERROR - ThrottlePolicyDeploymentManager Error while deploying policy to global policy server.Error while saving 
[2020-08-23 01:50:13,375] ERROR - NativeWorkerPool Uncaught exception
java.lang.IllegalArgumentException: Illegal character in query at index 79: https://localhost:9443/internal/data/v1/api-policies?policyName=akdsaklsjd/ssas\sdd
	at java.net.URI.create(URI.java:883) ~[?:?]

user wont notice anything

### Describe your solution
Input validation and API level validation would solve this issue.

### How will you implement it

---

**Comment by sanjeewa-malalgoda** [comment]
![image](https://user-images.githubusercontent.com/7975153/91011124-5d20ae00-e601-11ea-9f85-dfec664829b6.png)

**Comment by Meruja** [comment]
Closing the issue since it's fixed in wso2/carbon-apimgt#9269
