### ISSUE TITLE
Lengthy Scope names or descriptions cause UI rendering issue

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/product-apim#9173]
### Describe your problem(s)
If we add scope name or description with lengthy string then we wont be able to see rest of the columns. Due to that cannot delete scope or view all columns

### Describe your solution
Having UI field validation would solve this issue along with API level data validation
![image](https://user-images.githubusercontent.com/7975153/91011460-f3ed6a80-e601-11ea-8b7c-62268f4c8c23.png)

### How will you implement it

---

**Comment by Meruja** [comment]
Closing the issue since it's fixed in wso2/carbon-apimgt#9269
