### ISSUE TITLE
API M doesnt allow APIs that are subscribed after opaque token generation to be accessed

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/product-apim#9179]
### Description:
API M 3.1 doesnt allow APIs that are subscribed after the token is generated to be accessed via the token, it responds with 
  <ams:code>900901</ams:code>
  <ams:message>Invalid Credentials</ams:message>
error

### Steps to reproduce:
Create 2 APIs,
Create an application and generate a opaque token
Subscribe to one API and access the API (should work fine)
Subscribe to the second API and access (this will fail with the above error)

### Affected Product Version:
3.1.0 WUM -wso2am - 3.1.0 1597713792746

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tharindu1st** [comment]
This was due to the CacheInvalidator available in product this was removed in 3.2.0
