### ISSUE TITLE
APIM running out of memory/endpoint not destroy issue in admin services

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/product-apim#9180]
### Description:
ScheduledFuture objects are created by the EndpointView instance and there is a destroy method in EnpointView class that should be triggered before deleting an endpoint. This destroys the method cancels the ScheduleFuture task and allows EndpointView class to let the garbage collected. When we are trying to remove an endpoint(Or an API from APIM) through the management console, we have noticed that the EndpointView destroy method does not get hit and it keeps on the heap. In admin service implementation we have noticed that endpoint removal does not call destroy events and due to that reason, these objects do not remove and keep on increasing.

### Steps to reproduce:
1. Start the APIM server.
2. Create, publish, and delete an API for like 30min.
3. Take a heap dump and check the growth of the ScheduledFuture objects.

### Affected Product Version:
APIM 2.6
---
#### Related Issues:
Fix - https://github.com/wso2/carbon-mediation/pull/1463

#### Suggested Labels:
APIM, EI

**Comment by mushthaq33** [comment]
Fixed in master https://github.com/wso2/carbon-mediation/pull/1463
