### ISSUE TITLE
[APIM][3.1.0][API-Product]-Unable to update API Product when the source API scope role is renamed/deleted

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9183]
### Description:
Unable to update API Product when it has a resource belongs to its source API and the source API scope role is renamed/deleted in the carbon management console.

### Steps to reproduce:
1. Create a user role in carbon management console as "aRole"
2. Create an API in the publisher
3. Create a scope with the created role in the publisher
4. Add the created scope to any API resource
5. Create an API Product with the API resources including the resource with the scope
6. Save the changes
7. Navigate back to the carbon management console and rename the role "aRole" as "aRoleNew" and save the changes
8. Go to the publisher --> API Products --> Select the API Product and edit resources
9. Try to remove the relevant resource with the scope and save the changes
10. You will get the below error in the publisher
![image](https://user-images.githubusercontent.com/20519000/91210742-4d04ed80-e72b-11ea-9d43-a62b32e3b5f7.png)

### Affected Product Version:
wso2am-3.1.0

### Workaround
This can be solved by modifying the API definite of the API product in the carbon management console. Please follow the below steps.
1. Navigate to carbon management console
2. Go to Main --> Resources --> Browser and search /_system/governance/apimgt/applicationdata/provider/<provider>/<API_Product>/<version>
3. Select the swagger.json file and click on Edit as text
4. Under securityDefinitions in the swagger/openapi definition make the following changes.

**Case 1: Scope role renamed**
```
scopes:      
  <scope_name>: <scope_description>   
x-scopes-bindings:      
  <scope_name>: <new_role_name>
```

**Case 2: Scope role deleted**
```
scopes: {} 
x-scopes-bindings: {}
```
5. Save the changes and test the flow again. You will be able to make the changes to the API Product now.

**Comment by rmsamitha** [comment]
**The fix suggested**

**Scenario 1:** : Role name is changed but the related API is not updated with the changed role name in scope-role binding.
**Expected result**: When try to update API product (even any other field too) it should be allowed (role validations should not happen)

**Scenario 2** : Role name is changed and API is updated with the changed role name in scope-role binding.
**Expected result**:  When try to update API product (even any other field too) it should be allowed (role validations should not happen). Correct (updated) scope-role bindings should be updated in the swagger file too.

**Comment by RakhithaRR** [comment]
This issue can be closed since the fix is done.
