### ISSUE TITLE
custom messageBuilder is getting selected as messageFormatter under the <messageBuilders> in axis2.xml

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-apim#9190]
### Description:

When a custom messageBuilder is defined under the deployment.toml, that messageBuilder will be taken as a messageFormatter when it parsing to the axis2.xml file through the axis2.xml.j2.

### Steps to reproduce:
1. Add a custom messageBuilder as follows in deployment.toml file
```
[[custom_message_builders]]
content_type = "application/custom+json"
class= "org.apache.synapse.commons.json.JsonStreamBuilder"
```
2. Start the server
3. Open the <APIM_Home>/repository/conf/axis2/axis2.xml file and check for the messageBuilders section.
```
<messageBuilders>
        <messageBuilder contentType="application/octet-stream"
                        class="org.wso2.carbon.relay.BinaryRelayBuilder"/>
        <messageFormatter contentType="application/custom+json"
                          class="org.apache.synapse.commons.json.JsonStreamBuilder"/>
    </messageBuilders>
```
#### Reason for the issue
1. Open the <APIM_HOME>/repository/resources/conf/templates/repository/conf/axis2/axis2.xml.j2
2. Under the <messageBuilders> messageBuilder has been replaced with messageFormatter
```
      <messageBuilders>
        {% for message_builder in custom_message_builders %}
        <messageFormatter contentType="{{message_builder.content_type}}"
                          class="{{message_builder.class}}"/>
        {% endfor %}
    </messageBuilders>
```
### Affected Product Version:
APIM 3.0.0

**Comment by AmaliMatharaarachchi** [comment]
This is fixed in WUM
