### ISSUE TITLE
[3.2.0] [GA] Unable to Access the WebSocket API as per Example

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/product-apim#9195]
### Description:
$subject was experienced when trying out the standalone API Manager deployment, locally.

The official [documentation](https://apim.docs.wso2.com/en/next/learn/tutorials/create-and-publish-websocket-api/) was used as a guide for this pupose.

The error experienced on the client-side is as follows:
```
(node:24310) Warning: N-API is an experimental feature and could change at any time.
error: socket hang up
```

The error experienced on the server side is as follows:

For a WSS based request
```
[2020-08-27 13:47:50,059] ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 8099 tenant domain : null
```

For a WS based request
```
[2020-08-27 12:56:50,614] ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 9099 tenant domain : null
```

The original purpose was to [review configurations and test WebSocket endpoints in Kubernetes](https://github.com/wso2/kubernetes-apim/issues/422) based deployments of API Manager production grade deployment patterns (using Helm).

### Steps to reproduce:

1. Followed steps defined in the official documentation to [design](https://apim.docs.wso2.com/en/next/learn/tutorials/create-and-publish-websocket-api/#step-1-design-a-websocket-api) and [publish](https://apim.docs.wso2.com/en/next/learn/tutorials/create-and-publish-websocket-api/#step-2-publish-the-websocket-api) the WebSocket API, successfully.

![Screenshot from 2020-08-27 12-48-24](https://user-images.githubusercontent.com/9444555/91418245-85154900-e86f-11ea-8557-6db26ee900dd.png)

2. Experiencing the issue when following step 4(b) in the section defining [how to invoke an API](https://apim.docs.wso2.com/en/next/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api).

In this step, both `wscat` versions `2.2.1` and `4.0.1` were used to try accessing the API as per the documentation.

```
wscat -n -c "wss://localhost:8099/echowebsocket/1.0.0" -H "Authorization: Bearer <access-token>"
```

### Affected Product Version:
WSO2 API Manager version `3.2.0` GA

### Environment details (with versions):
- OS: Ubuntu `18.04 LTS`
- Client: `wscat`

---
#### Related Issues:
https://github.com/wso2/kubernetes-apim/issues/422

#### Suggested Labels:
Type/Bug

#### Suggested Assignees:
@pubudu538 @tharindu1st @Arshardh

**Comment by CrowleyRajapakse** [comment]
Hi @chirangaalwis ,
I could reproduce this issue when following the exact documentation. But the issue is due to documentation error as it seems. In the doc the API created has the 1.0 as API version and the curl command provided to invoke the API has 1.0.0 as version. Once you change the curl command such as follows it resolves this issue.

`wscat -n -c "wss://localhost:8099/echowebsocket/1.0?access_token=XXXX`

We will change the documentation accordingly.

**Comment by CrowleyRajapakse** [comment]
Docs Updated: https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-websocket-api/#create-and-publish-a-websocket-api
