### ISSUE TITLE
[APIM][3.1.0][UI-Bug]-Devportal UI goes blank when the token hashing is enabled

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9203]
### Description:
Devportal UI goes blank as soon after clicking on an application or after generating the keys. This is due to the following configuration in the **<APIM-Home>/repository/conf/deployment.toml** file.
```
[apim.oauth_config]
enable_token_hashing = true
```
### Steps to reproduce:
1. In the <APIM-Home>/repository/conf/deployment.toml file add the following config.
```
[apim.oauth_config]
enable_token_hashing = true
```
2. Start the APIM server and navigate to devportal
3. Create an application and generate the keys
4. The UI will go blank after the key generation
5. List the apps and click on any application
6. Again the UI goes blank

### Affected Product Version:
wso2am-3.1.0

**Comment by dushaniw** [comment]
@Krishanx92 Have we fixed this in the latest master build? If so, can we close the issue?

**Comment by msm1992** [comment]
This is fixed with changes in https://github.com/wso2/carbon-apimgt/pull/8691/files. Tested in the latest APIM build (6.8.130-SNAPSHOT) and the issue was not reproducible, hence closing the issue.
