### ISSUE TITLE
[APIM][3.1.0] A null pointer is thrown when getting a user access token

### ISSUE THREAD

**Issue by imesh94** [wso2/product-apim#9205]
### Description:

After the fix #2179, when a federated claim with no local claim mapping is present as user attributes, a null pointer is thrown when generating a user access token. 
This happens because the `org.wso2.carbon.apimgt.keymgt.issuers.RoleBasedScopesIssuer#getRolesFromUserAttribute
` method is trying to get the claimUri from the local claim, even when the local claim is null.

<img width="1208" alt="Screenshot 2020-08-15 at 19 25 06" src="https://user-images.githubusercontent.com/25720507/91679197-36b0c480-eb65-11ea-8aba-8ae5d1bb9961.png">

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by isharac** [comment]
Fixed with https://github.com/wso2-extensions/apim-km-wso2is/pull/32
