### ISSUE TITLE
Bring back log level updating feature

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#9206]
### Describe your problem(s)

We need to provide the feature to update log levels through the management console. We removed this feature while migrating from log4j 1.x to log4j 2.x.
We need to provide this feature to update log4j2 loggers from the management console.

### How will you implement it

---

**Comment by dushaniw** [comment]
@dinusha92 Have we added this feature to the latest build?

**Comment by tharindu1st** [comment]
Fixes From #https://github.com/wso2/carbon-commons/pull/421
