### ISSUE TITLE
Per API logging in API Manager

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim#9207]
### Describe your problem(s)

Enabling logs per API at the run time to analyze the headers and body of the API request coming to gateway and leaving the gateway. This would help to debug and analyze the issues in requests and transformation(mediation) at the run time for a given API.

### How will you implement it

---

**Comment by dushaniw** [comment]
@dinusha92 Have we added the implementation for this in the master branch?

**Comment by daz96050** [comment]
This was added as of September 19 2020 for 3.1.0 - per WUM on 09-01-2020
https://apim.docs.wso2.com/en/3.1.0/administer/logging-and-monitoring/logging/setting-up-logging-per-api/
