### ISSUE TITLE
[APIM 3.2.0] J2 template mapping does not exists for configuring new valve.

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-apim#9212]
Currently, there is no template mapping in ./repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2 to configure a new valve in APIM 3.x.x versions

WSO2 IS we have the following template mapping in ./repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2 to configure new valve.

```
 {% for valve in catalina.valves %}
                <Valve
                    {% for property,value in valve.properties.items() %}
                      {{property}}="{{value}}"
                    {% endfor %}
                 />
                {% endfor %}
```
Shall we add template mapping ./repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2   and fix this in the product level

**Comment by CrowleyRajapakse** [comment]
Fixed by https://github.com/wso2/product-apim/pull/9254
https://github.com/wso2-support/product-apim/pull/592
