### ISSUE TITLE
APIs are not sorted correctly in the Developer portal

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/product-apim#9217]
### Description:
APIs displayed in the developer portal appear without a particular order. In the publisher portal APIs are sorted alphabetically and grouped by the provider.

### Steps to reproduce:
1. Create few APIs (eg: test, beta, pizza, cal .etc) from publisher portal and publish them
2. View the APIs in the developer portal

### Affected Product Version:
APIM 3.1.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per the above commits
