### ISSUE TITLE
Web socket API is not throwing the proper detailed  error response with wrong or expired token.

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#9220]
### Description:

When we are having a WS endpoint in the API and when we invoke the API, we are getting the following errors printed in the carbon logs.
```
[2020-08-31 16:15:27,120] ERROR - AMDefaultKeyManagerImpl Invalid OAuth Token : Access token expired
[2020-08-31 16:15:27,122] ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 9099 tenant domain : null
```
Also, we got following to the client-side.
```
wscat -c ws://localhost:9099/echowebsocket/1.0 -H "Authorization: Bearer 8680375b-d0d1-311c-bfad-c25b4bc77563"
error: socket hang up
>
```
When trying to invoke a Websocket API with the WS endpoint in the API through the Nginx web server and we are executing WSS endpoint from the client. When the client is using an expired access token, who is getting the same error message in the carbon logs.
And getting following to the client-side.

```
wscat -c "wss://NginxServerHost/1.0.0" -H "Authorization: Bearer 8680375b-d0d1-311c-bfad-c25b4bc77563" -n
error: Unexpected server response: 502
```
It is not possible to understand that the error is related to an invalid, wrong, or expired token since there is no proper error code and message as we have referenced in our error handling documentation[1].

[1] https://docs.wso2.com/display/AM260/Error+Handling

### Steps to reproduce:
1. Create and publish and web socket API with WS endpoint in the APIM publisher.
2. Execute the web socket API with the expired or invalid or wrong token.

### Affected Product Version:
APIM 2.6.0

**Comment by lkokila** [comment]
After portOffsetting the Gateway node (APIM-3.2.0), when exceptional requests (i.e: TCP requests or requests without valid tokens) are sent, the following error is logged with misleading port information (disregarding the offset).

```
{org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler} - Endpoint not found for port : 8099 tenant domain : null
{org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler} - Endpoint not found for port : 9099 tenant domain : null
```
Steps to reproduce: 
1. PortOffset the API-Manager Gateway (i.e: offset = 6, websocket ports = 8105 and 9105)
2. Start the API-Manager Gateway.
3. Telnet to 9105 port (i.e: telnet localhost 9105).
4. The above error will be logged for the 9099 port. 

It seems like there's a redundant port setting [1] by removing the portOffset in the InboundWebsocketSourceHandler. This seems to be included from [2] to support WebSocket ports with offset. 

[1]. https://github.com/wso2/carbon-mediation/blob/master/components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java#L128
[2]. https://github.com/wso2/carbon-mediation/pull/777/commits/c92db1a1687dd6b82d6c9e3078d610299bda6f77

**Comment by lkokila** [comment]
Related issue - https://github.com/wso2/product-apim/issues/10220
