### ISSUE TITLE
/settings/gateway-environments returns 'magic!' as response

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9228]
### Description:
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SettingsApiServiceImpl.java#L41

Need to either implement this resource or remove it.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment]
Fixed in latest product, hence closing
