### ISSUE TITLE
[APIM 2.6.0] Add ability to override properties in the default security definition in the API swagger definition

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#9230]
### Description:
Currently there is no way to override the values of the default security definiton for the API while creating an API or editing an already created API. If we provide a custom values in the default definition for an API by editing the swagger file(from portal by clicking the Edit Source), still it is overridden by the default hard-coded security definition.  

### Steps to reproduce:
1. Create an API from publisher and by clicking **Edit Source** and provide a custom security definition as below:
```
swagger: "2.0"
paths:
  /getResource:
    get:
      responses:
        "200":
          description: ""
info:
  title: TestAPI2
  version: v1.0.0
securityDefinitions:
  default:
    type: oauth2
    tokenUrl: https://192.168.1.15:8243/authorize
    flow: password
```
2. Save and publish the API.
3. Log in to the Store and select the API and click on the **API Console** tab.
4. Get the swagger from there.
5. You will see that the provided custom security definition is overridden by the default security definition.
`{"swagger":"2.0","paths":{"/getResource":{"get":{"responses":{"200":{"description":""}},"x-auth-type":"Application & Application User","x-throttling-tier":"Unlimited"}}},"info":{"title":"TestAPI1","version":"v1.0.0"},"securityDefinitions":{"default1":{"type":"oauth2","tokenUrl":"https://192.168.1.15:8243/authorize","flow":"password"},"default":{"type":"oauth2","authorizationUrl":"https://192.168.1.15:8243/authorize","flow":"implicit","scopes":{}}},"host":"192.168.1.15:8243","basePath":"/te/v1.0.0","schemes":["https","http"]}`

### Affected Product Version:
APIM 2.6

### Suggested solution:
If a default security definition with custom values is provided from the publisher swagger console, then that provided definition should be honoured.

**Comment by dushaniw** [comment]
@RAVEENSR Is this reproducible in lastet master build as well? If not, can we close this issue?

**Comment by emiliobristech** [comment]
> @RAVEENSR @CrowleyRajapakse Is this reproducible in lastet master build as well? If not, can we close this issue?

Yes, it happens in v3.2.0 download version. You just can't edit security definitions because it will be overriden!
