### ISSUE TITLE
wso2 3.0.0 admin password causing issue in throttling 

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#9240]
We are using wso2 3.0.0 API manager distributed setup
in toml files has password admin for admin user but if we change the password to any other password with special characters for eg if you have "@"  in the password we get an error in the traffic manger

it is easily reproducible but do distributed setup

**Comment by isharac** [comment]
It is not possible to use **@** in the username or passwords.

Please refer documentation[1].

{1] https://apim.docs.wso2.com/en/3.0.0/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords/#maintaining-logins-and-passwords
