### ISSUE TITLE
Svg images cannot be uploaded to API thumbnail

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#9245]
### Description:
It is unable to upload SVG images to the Thumbnail of a created API

### Steps to reproduce:
1. Create an API
2. Upload SVG image to the Thumbnail section displayed at the design configuration of the API

### Affected Product Version:
3.2.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit

**Comment by malinthaprasan** [comment]
Have to send this fix and resolve https://github.com/wso2/carbon-apimgt/pull/9274/commits/57a4f9f441ef2abc53a4f7f8cb4ff68ece0ab9b8
