### ISSUE TITLE
wso2 3.0.0 analytics alerts issue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#9247]
Hi
I was trying to configure alters on emails into wso2 analytics by following this link https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-alerts/
I had configured email id with "less secure apps enabled" but still getting below error, although credentials are correct

ERROR {io.siddhi.core.stream.output.sink.Sink} - Error on 'APIM_ALERT_EMAIL_NOTIFICATION'. Error is encountered while connecting to the the smtp server.Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at_535 5.7.8  https://support.google.com/mail/?p=BadCredentials l79sm816443pfd.210 - gsmtp_, error while connecting at Sink 'email' at 'EmailNotificationStream'. java.lang.RuntimeException: Error is encountered while connecting to the the smtp server.Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials l79sm816443pfd.210 - gsmtp

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
