### ISSUE TITLE
wso2 3.0.0 alters not getting in admin portal for non admin users

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#9252]
I have done configuration like analytics worker - allINone wso2 3.0.0 and analytics dashboard 
1.enabled alerts in analytics worker 
2. through publisher setup alerts for response time and backend response time 
3. logged in as admin user on devportal and tested API 
4. logged in through the admin portal() and I can see alters for response time threshold 
5. logged in to devportal as another user(non-admin)(but has all the roles) tested the API 6. logged in through the admin portal() and I cant see alters for response time threshold

response time threshold I have set as 1 milisec

Error in worker Node
[2020-09-11 11:22:59,710] ERROR {org.wso2.transport.http.netty.contractimpl.listener.SslHandshakeCompletionHandlerForServer} - Error while SSL handshake: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
