### ISSUE TITLE
Add user roles to JWT in Password Grant [Question]

### ISSUE THREAD

**Issue by emiliobristech** [wso2/product-apim#9255]
Hello, is there a way to add user roles to JWT generated through [Password Grant](https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/password-grant/)?

I mean, I know I need to pass username, password, consumer-key and consumey-secret. Is it possible to add account's roles to generated JWT?

Thanks

**Comment by CrowleyRajapakse** [comment]
Hi @emiliobristech ,
Can you specify which API Manager version you wish to cater this requirement?

**Comment by emiliobristech** [comment]
Hello, got the answer in StackOverflow! In summary, Just need to configure Claims in Service Provider and request token passing parameter "scope=openid". More details is in [this answer](https://stackoverflow.com/questions/63792575/wso2-apim-add-user-roles-in-jwt-payload/63932466#63932466). Thank you!
