### ISSUE TITLE
InboundWebsocketSourceHandler Endpoint not found for port : 8099 tenant domain : null

### ISSUE THREAD

**Issue by rajamadhu** [wso2/product-apim#9256]
### Description:
i am using api manager 3.1.0 , i have configured web socket in api publisher and configured tenant=carbon.super i am trying to access wss with domain name., i have updated host name with deployment.toml file,the problem is unable to access wss secure socket-.wss://test.com:8099/Notification/v1?access_token=xxx123 .i am getting error in connection, please guide me, how to resolve this

[2020-09-11 14:06:17,276] ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 8099 tenant domain : null

### WSO2 APIM 3.1.0:
- OS:windows
- Client:
- Env (Docker/K8s):

---

**Comment by CrowleyRajapakse** [comment]
Duplicate issue but different version https://github.com/wso2/product-apim/issues/9195

**Comment by CrowleyRajapakse** [comment]
Hi @rajamadhu ,
Please check and verify whether the API Context and Version is as same as the Created API.
API Context= /Notification
Version= v1
Check for Capital and Simple letter differences.

**Comment by CrowleyRajapakse** [comment]
please reopen if you need further assistance on this.
