### ISSUE TITLE
Require a gRPC data receiver for the throttling in APIM Traffic Manager

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-apim#9259]
### Describe your problem(s)

Currently, the Trafic manager can receive data through thrift and binary protocols. But to be compatible with Envoy Microgateway, need to implement a gRPC data receiver.

### How will you implement it

Currently in Traffic Manager, it uses siddhi 3.2.3 version. But existing siddhi gRPC extension ( https://github.com/siddhi-io/siddhi-io-grpc ) supports only 4.x.x version onwards.
 
Considering the above reasons there are two options to implement the gRPC data receiver for the Traffic manager.

1. Migrating Traffic Manager siddhi version to the newest version and use the existing siddhi gRPC extension.
2. Implement a gRPC support for the 3.x.x version.
---

**Comment by Krishanx92** [comment]
Is this requirement still valid? We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
