### ISSUE TITLE
not able to login analytics business rules in wso2 3.0.0

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#9260]
not able to login to https://localhost:9643/business-rules/login?referrer=%2Fbusiness-rules%2Flogin%2F

i have setup analytics worker + allinone + dashboard
username and password is admin admin

**Comment by christianrhoades** [comment]
Did you ever find a fix for this issue?

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time, and this was fixed in APIM 3.2.1 analytics
