### ISSUE TITLE
API Manager allows request to go thru even with a JWT that has missing values and invalid signature

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/product-apim#9269]
### Description:
API Manager allows request to go thru even with a JWT that has missing values and invalid signature, looks like the API M caches the first request and allow all requests from the same token to go thru. 

### Steps to reproduce:
Publish the Pizzashack API.
Subscribe to the API.
Generate a JWT.
Invoke the API.
Change any part of the token with some random text.
Invoke the API and the request still goes thru.
Invoke a different resource of the same API and it still works.

### Affected Product Version:
API Manager 3.2.0

### Environment details (with versions):
- OS: Mac OS
- Client:
- Env (Docker/K8s):

---

**Comment by ChamodDamitha** [comment]
Already fixed in 3.2.0
