### ISSUE TITLE
Markdown editor support for API description 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#9272]
### Description:
API description should have to support the Markdown editor. Currently, description looks like as follows
![Screen Shot 2020-09-16 at 12 22 54 PM](https://user-images.githubusercontent.com/29066805/93302985-696ee400-f818-11ea-9e5e-7ba8904450c7.jpg)

### Steps to reproduce:
Import API with an apictl where contains Markdown description

### Affected Product Version:
3.x.x

**Comment by tmkasun** [comment]
If we are going to make the description content as markdown by default, I think we should provide a markdown editor to add/edit the description in the publisher portal + we should place the description in a way to accommodate lengthy description document/content.

**Comment by HiranyaKavishani** [comment]
As per the discussion, We have to support the markdown support for API description in publisher instead of plain/text

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/9362 hence closing the issue
