### ISSUE TITLE
API creation rest API is allowed to create API when the version contains special characters

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#9275]
### Description:
API creation rest API is allowed to create API when the version contains special characters. Therefore, the generated endpoint.xml file has been included special characters in the name property and so that deploying that kind of synapse files are failed.
![Screen Shot 2020-09-16 at 1 15 42 PM](https://user-images.githubusercontent.com/29066805/93308784-552ee500-f820-11ea-9619-c62027c3d286.jpg)

Ex:- 
**ApiDapp--v2019-02-14T16_47_01Z_APIsandboxEndpoint.xml** file can be found as follows. name property in the synapse file has been included special characters. 

```
<?xml version="1.0" encoding="UTF-8"?><endpoint xmlns="http://ws.apache.org/ns/synapse" name="ApiDapp--v2019-02-14T16:47:01Z_APIsandboxEndpoint">
    <http uri-template="http://localhost:8081">
        <timeout>
            <responseAction>fault</responseAction>
        </timeout>
    </http>
    <property name="ENDPOINT_ADDRESS" value="http://localhost:8081"/>
</endpoint>

```

### Steps to reproduce:
Import API Project where contains special characters in the version

### Affected Product Version:
3.x.x

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9349
