### ISSUE TITLE
 Gateway error when using response caching

### ISSUE THREAD

**Issue by allmind75** [wso2/product-apim#9281]
### Description:

Can I using Endpoint API **Content-Type:application/hal+json**?

### Steps to reproduce:
API Manager Publisher > Runtime Configurations > Response Caching Activation

Endpoints API Content-Type : application/hal+json

API TEST -> 500 Internal Server Error

Response
```
<am:fault xmlns:am="http://wso2.org/apimanager">
    <am:code>601000</am:code>
    <am:type>Status report</am:type>
    <am:message>Runtime Error</am:message>
    <am:description>Error while building message. Error while building Passthrough stream</am:description>
</am:fault>
```

Gateway Log
```
...
Error while building Passthrough stream org.apache.axiom.om.OMException: com.ctcwstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
...
```
### Affected Product Version:

3.1.0

### Environment details (with versions):
- OS: Ubuntu 18.04 LTS

**Comment by CrowleyRajapakse** [comment]
Hi @allmind75 ,
Yes, you can use Content-Type:application/hal+json. You should be able to resolve this issue by defining following message builder and formatter in the deployment.toml file.

[[custom_message_builders]]
content_type = "application/hal+json"
class="org.apache.synapse.commons.json.JsonStreamBuilder"

[[custom_message_formatters]]
content_type = "application/hal+json"
class="org.apache.synapse.commons.json.JsonStreamFormatter"

You can follow the following documentation for more information on regarding the default message builders and formatters and about defining custom builders and formatters.

https://apim.docs.wso2.com/en/3.1.0/learn/api-gateway/message-mediation/configuring-message-builders-formatters/#configuring-message-builders-and-formatters

**Comment by allmind75** [comment]
Hi @CrowleyRajapakse 
I solved the problem with your help.
Thank you :)
