### ISSUE TITLE
API icon keeps defaulting back to original after a save

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-apim#9291]
### Description:

API Icon reverts back to its default icon when a new API icon is selected and saved from the available Material Icons in the publisher portal.
### Steps to reproduce:

- Log in to the Publisher Portal 
- Click on Design Configuration. -> Click on the API Icon
- Select an Icon that is offered in the portal.
- Click on Save.
- Then redirected to the Design Configurations UI and clicked on Save.
- After that, will observe that API icaon has been changed to the previous one.
### Affected Product Version:

latest APIM 3.1.0 
APIM 3.2.0

**Comment by CrowleyRajapakse** [comment]
duplicate issue https://github.com/wso2/product-apim/issues/9223

**Comment by tmkasun** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/9278 hence closing the issue
