### ISSUE TITLE
Endpoint details are mandatory in swagger definition

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-apim#9292]
### Description:
While trying to create a new API using an existing swagger definition(which does not include endpoint details), it failed in the APIM-3.2.0.

### Steps to reproduce:
- Create sample PizzaShackAPI in the APIM-3.2.0.
- Download the swagger definition.
- Edit the swagger definition by removing the endpoint details.
- After that, try to create a new API using the updated swagger definition.
[swagger1.json.zip](https://github.com/wso2/product-apim/files/5262745/swagger1.json.zip)
- It ends up with the below error.
![image](https://user-images.githubusercontent.com/38488254/93909103-0d76f480-fd1d-11ea-8d8d-cd8ef90bad24.png)

### Affected Product Version:
APIM-3.2.0

**Comment by CrowleyRajapakse** [comment]
Similar issue https://github.com/wso2/product-apim/issues/9244
