### ISSUE TITLE
Blacklist not working as expected

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-apim#9293]
### Description:
When we create a blacklist policy and click on the button ' Blacklist ' it works as expected , but if we press 'enter' on keyboard, we have the following error :

![image-2020-09-22-17-19-36-210](https://user-images.githubusercontent.com/19996612/93966735-0c78ae00-fd83-11ea-893b-9cef4716ea75.png)

### Solution
Handle the enter key press event when adding a Blacklist Policy.

**Comment by mushthaq33** [comment]
Fixed via WUM
