### ISSUE TITLE
Support for 'decimal' data type in SOAP to REST feature

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#9301]
### Description:
Currently, when WSDL contains an element of `decimal` type, swagger generation is incomplete. It generates the model definition as `RefProperty`.

#### Example:
> <xsd:element name="sequenceNumber" type="xsd:decimal" minOccurs="0"/>

The API definition will be generated as,
> 
      sequenceNumber:
        $ref: '#/definitions/decimal'

Need to improve the implementation to support the `decimal` data type as well.

### Affected Product Version:
APIM-3.2.0

**Comment by lkokila** [comment]
Tagging #7130
