### ISSUE TITLE
Support for 'complexContent' XSD element type in SOAP to REST feature

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-apim#9302]
### Description:
Currently, the support for some scenarios in the `complexContent` XSD element type is not available in SOAP to REST conversion feature.

Hence, some of the attributes of the elements belong to `complexContent` XSD type are not included when generating REST APIs using SOAP endpoints.
Need to improve the implementation to support these scenarios as well.

### Affected Product Version:
APIM-3.2.0

**Comment by lkokila** [comment]
Tagging #7130

**Comment by Krishanx92** [comment]
This is currently on hold and will be reconsidered if any requirements arise
