### ISSUE TITLE
Wso2 APIM DevPortal Try_out“TypeError: Failed to fetch” for the same, Getting response when trying with postman.

### ISSUE THREAD

**Issue by murtaza0726** [wso2/product-apim#9314]
While Trying to test the api in swagger, i am getting “TypeError: Failed to fetch”
but when i am trying the same request with postman is works fine

I have crossed checked all the configurations related to CORS and all looks fine but
don't know why this is happening.

I am using the latest version of API Manager-3.2.0 and had tried in 3.1.0 as well but no luck

And for testing purpose i am mocking my endpoint which i am expecting in the response.

I have also tried to used Curl command in my cmd prompt and it also respond with the
correct response.

![apim](https://user-images.githubusercontent.com/69367683/94562609-2898b580-0283-11eb-9005-5cce478e30ba.PNG)
![apim postman](https://user-images.githubusercontent.com/69367683/94562621-2cc4d300-0283-11eb-9c51-ca7918378816.PNG)

**Comment by CrowleyRajapakse** [comment]
Hi @murtaza0726 ,
This error can happen if the user selects an HTTPS scheme and on their local development environment has a self signed SSL certificate. In this case, when you are using curl command you might be adding -K to the curl command and in the postman you might be using request without SSL verification hence this error is not happening on those instances. So can you import that SSL certificate to the browser and check whether this issue is resolved?

**Comment by murtaza0726** [comment]
Hi @CrowleyRajapakse ,

Thanks you for the quick response

But I am using Signed SSL certificate not even self assigned and it happens in both 3.0.1 and 3.0.2 version when testing with try_out option..

**Comment by CrowleyRajapakse** [comment]
Hi @murtaza0726 ,
Can you provide the wso2carbon.log entries related to the scenario when invoking above API using Devportal try out console. Also if there are any log errors in the Browser's developer console or network tab in related to API invocation please provide them as well so that we can check for possible issues.

**Comment by tmkasun** [comment]
Adding to @CrowleyRajapakse's comment, Can you also attach a screenshot of the browser console when this error occurs and better if you can provide an HTTP archive file (HAR)

**Comment by murtaza0726** [comment]
Hi @CrowleyRajapakse 

Please find the attached carbon logs which we are getting while invoking the api and browser console logs.

TID: [-1] [] [2020-10-05 05:52:54,236] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "OPTIONS /profileManagement/v2/2.12.0/manageableAssets HTTP/1.1[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,236] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "OPTIONS /profileManagement/v2/2.12.0/manageableAssets HTTP/1.1[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,237] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Host: 54.220.161.180:8243[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,237] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Host: 54.220.161.180:8243[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,237] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Connection: keep-alive[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,237] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Connection: keep-alive[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept: */*[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept: */*[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Access-Control-Request-Method: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Access-Control-Request-Method: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Access-Control-Request-Headers: authorization,x-request-id,x-request-session-id,x-request-tracking-id[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Access-Control-Request-Headers: authorization,x-request-id,x-request-session-id,x-request-tracking-id[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Origin: https://54.220.161.180:9443[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,238] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Origin: https://54.220.161.180:9443[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Mode: cors[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Mode: cors[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Site: same-site[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Site: same-site[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Dest: empty[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,239] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Sec-Fetch-Dest: empty[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Referer: https://54.220.161.180:9443/[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Referer: https://54.220.161.180:9443/[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept-Encoding: gzip, deflate, br[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept-Encoding: gzip, deflate, br[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kn;q=0.6,mt;q=0.5[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,240] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kn;q=0.6,mt;q=0.5[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,241] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,241] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 >> "[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:54,247]  WARN {org.apache.synapse.transport.http.access.AccessConfiguration} - Error loading properties from file: access-log.properties
TID: [-1] [] [2020-10-05 05:52:54,251]  WARN {org.apache.synapse.commons.util.MiscellaneousUtil} - Error loading properties from a file at from the System defined location: access-log.properties
TID: [-1] [] [2020-10-05 05:52:54,254]  WARN {org.apache.synapse.commons.util.MiscellaneousUtil} - Error loading properties from a file at from the System defined location: access-log.properties
TID: [-1234] [] [2020-10-05 05:52:54,302]  INFO {org.wso2.carbon.analytics.message.tracer.handler.util.HandlerUtils} - Massage Info: Transaction id=242271129095794883632  Message direction=IN  Server name=54.220.161.180  Timestamp=1601877174302  Service name=__SynapseService  Operation Name=mediate
TID: [-1234] [] [2020-10-05 05:52:55,000]  INFO {org.wso2.carbon.analytics.message.tracer.handler.util.HandlerUtils} - Massage Info: Transaction id=242271129095794883632  Message direction=OUT  Server name=54.220.161.180  Timestamp=1601877175000  Service name=__SynapseService  Operation Name=mediate
TID: [-1] [] [2020-10-05 05:52:55,015] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "HTTP/1.1 200 OK[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,015] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "HTTP/1.1 200 OK[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,016] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Origin: https://54.220.161.180:9443[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,016] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Origin: https://54.220.161.180:9443[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,016] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept: */*[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,016] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept: */*[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Origin: *[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Origin: *[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Methods: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Methods: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Referer: https://54.220.161.180:9443/[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,017] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Referer: https://54.220.161.180:9443/[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Dest: empty[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Dest: empty[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Site: same-site[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Site: same-site[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Host: 54.220.161.180:8243[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Host: 54.220.161.180:8243[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept-Encoding: gzip, deflate, br[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,018] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept-Encoding: gzip, deflate, br[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,019] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,Authorization[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,019] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,Authorization[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,019] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Mode: cors[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,019] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Sec-Fetch-Mode: cors[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "activityID: 242271129095794883632[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "activityID: 242271129095794883632[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Expose-Headers: [\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Expose-Headers: [\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Request-Method: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Request-Method: GET[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Request-Headers: authorization,x-request-id,x-request-session-id,x-request-tracking-id[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,021] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Access-Control-Request-Headers: authorization,x-request-id,x-request-session-id,x-request-tracking-id[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kn;q=0.6,mt;q=0.5[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kn;q=0.6,mt;q=0.5[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Date: Mon, 05 Oct 2020 05:52:55 GMT[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Date: Mon, 05 Oct 2020 05:52:55 GMT[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Connection: keep-alive[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,022] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "Connection: keep-alive[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "0[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "0[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "[\r][\n]"
TID: [-1] [] [2020-10-05 05:52:55,023] DEBUG {org.apache.synapse.transport.http.wire} - HTTPS-Listener I/O dispatcher-1 << "[\r][\n]"

![image](https://user-images.githubusercontent.com/69367683/95045171-ffeb4280-06fe-11eb-9ee0-66494d9200ce.png)

**Comment by tmkasun** [comment]
Hi @murtaza0726 

Error in the browser console explains the issue, 

```
has been blocked by CORS policy: Request header field x-request-tracking-id is not allowed by Access-Control-Allow-Headers in preflight response.
```

you have to put `x-request-tracking-id` header In `Access Control Allow Headers` list from the publisher portal.

follow these steps to configure it

- Login to the publisher
- Goto the above API details page
- Click runtime configurations
- Enable CORS configuration
- Put `x-request-tracking-id`  header in `Access Control Allow Headers` list (press enter after putting your new header value)
- Save and try again in dev portal

![image](https://user-images.githubusercontent.com/3313885/95155270-64ff7080-07b1-11eb-9ad5-a7fe245fb977.png)

**Comment by murtaza0726** [comment]
Hi @tmkasun,

Thank you for guidance, Issue is resolved by making the above changes thereby closing the ticket.

**Comment by hitechie17** [comment]
I have a similar issue, APIM 4.2.  backend service is deployed on Kiali via Istio, rest of the services are accessible, however my service when Trying out from publisher portal gives the following error - 

Access to fetch at 'https://host:8243/test/book/v1/api/v1/book/category' from origin 'https://host:9443' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The same API we are able to hit via postman and works on swagger api

Also CORS is disabled at Publisher portal for all other working services, so kept it disabled for this one as well. Even if I enable the CORS configuration, the error is same. Any help would be appreciated @tmkasun Thanks!

**Comment by tmkasun** [comment]
I'm not sure what's the issue, May be @malinthaprasan or @pubudu538 could help

**Comment by wh0am111** [comment]
> I have a similar issue, APIM 4.2. backend service is deployed on Kiali via Istio, rest of the services are accessible, however my service when Trying out from publisher portal gives the following error -
> 
> Access to fetch at 'https://host:8243/test/book/v1/api/v1/book/category' from origin 'https://host:9443' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> The same API we are able to hit via postman and works on swagger api
> 
> Also CORS is disabled at Publisher portal for all other working services, so kept it disabled for this one as well. Even if I enable the CORS configuration, the error is same. Any help would be appreciated @tmkasun Thanks!

I have the same issue，do you solve it？
