### ISSUE TITLE
[Analytics] Need to improve our rest API output by including respective parameters along with the values

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#9322]
### Describe your problem(s)

With our rest API [1] to retrive the data from analytics side, we can formulate a query such as below

`curl -X POST -H "content-type: application/json" -u "admin:admin" -d '{"appName" : "APIM_ACCESS_SUMMARY", "query" : "from ApiUserPerAppAgg on apiName==\"PizzaShackAPI\" within 1537333194000L, 1539752394000L per \"days\" select username, apiCreator, sum(totalRequestCount) as net_total_requests group by username, apiCreator order by net_total_requests DESC" }' "https://localhost:7444/stores/query" -k
`
Here, we can specify parameters within the body such as '**net_total_requests**' in above query.

But in the result output we couldn't see this parameter mapping with the values

`{"records":[["admin@carbon.super","admin",45]]}`

### Describe your solution

The suggestion is to add this to the output or provide a new rest API with the change as below.

`{
  "records": [
     { 
        "username": "admin@carbon.super",
        "apiCreator": "admin",
        "net_total_requests": 45
     }
   ]
}`

#### Suggested Labels:
[Type/Improvement], [Affected/3.1.0]

[1] https://apim.docs.wso2.com/en/3.1.0/develop/analytics-rest-api/

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
