### ISSUE TITLE
Add support for 3.0.x OpenAPI definitions in API publisher.

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9323]
### Description:
Currently in 2.2.0 publisher we only support version 3.0.0 OpenAPI definitions. However we should add improved support for 3.0x versions because they can only contain minor fixes and not major changes in the spec.

### Steps to reproduce:
Import an OpenAPI 3.0.1 API definition. UI will show an error saying the OpenAPI version is not supported.

### Affected Product Version:
APIM 2.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by wasuradananjith** [comment]
Already fixed via https://github.com/wso2/carbon-apimgt/pull/5837. Hence, can close the issue.
