### ISSUE TITLE
Remove Local (API) Scopes from API-M 4.x onwards

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#9331]
### Description:
With the introduction of Shared Scopes from API-M 3.2, local scopes are deprecated because of the following major reasons.

- API Versioning story does not align with local scopes.
- Number of KeyManager calls during API update is high.

Removing local scopes from API-M 4.x onwards includes

- Remove API Scopes UI
- Remove the local scope check during API update, creation and deletion
- Migrate all local scopes to shared scopes

**Comment by floj** [comment]
Hi, I see that this issue is about removing local scopes in API-M 4.x. Was this completed? I still see that WSO2 API-M v4.0.0 has local scopes enabled. Is there a specific configuration one need to set do disable local scopes?
