### ISSUE TITLE
[MGW 3.2.0] subscriptions validation process

### ISSUE THREAD

**Issue by dushansachinda** [wso2/product-apim#9335]
### Description:
A combination of the following config at the micro-gw.conf will allow the mgw for subscription validation. Better if we could improve the documentation to explaining the end to user scenario.  As of now how to config have scattered across multiple documentation 

[[jwtTokenConfig]]
  issuer = "https://localhost:9443/oauth2/token
  certificateAlias = "wso2apim310"
  validateSubscription = true
  consumerKeyClaim = "aud"

and

[apim.eventHub]
  enable = true
  serviceUrl = "https://localhost:9443"
  internalDataContext="/internal/data/v1/"
  username="admin"
  password="admin"
  eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"

### Steps to reproduce:
Configure micro gateway default mode, then allow mgw to validate subscription flow, cross-check information available in the wso2 migro gateway documenation

**Comment by Chamindu36** [comment]
This issue is fixed already with the following PR [1]. Hence we can close this issue.

[1]. https://github.com/wso2/docs-mg/pull/67

**Comment by Chamindu36** [comment]
This issue is fixed already with the following PR [1]. Hense we can close this issue.

[1]. https://github.com/wso2/docs-mg/pull/67
