### ISSUE TITLE
There are a bunch of Source files included with the Publisher that are completely unused

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim#9340]
### Describe your problem(s)
There are a bunch of Source files included with the Publisher that are completely unused.

The following are some of them.
source/src/app/components/Apis/Details/Comments/
source/src/app/components/Apis/Listing/CardView/CardView.jsx
source/src/app/components/Apis/Listing/TableView/APITableHeader.jsx
source/src/app/components/Apis/Listing/TableView/APITableToolBar.jsx
source/src/app/components/Apis/APIsNavigation.jsx
source/src/app/components/Apis/Details/Overview/
source/src/app/components/Apis/Details/components/APIDetailsNavBar.jsx
source/src/app/components/Apis/Details/components/APIDetailsRoutes.jsx

**Comment by chanaka3d** [comment]
Following files are identified as Unused files are identified and will be removed.

source/src/app/components/Apis/APIsNavigation.jsx
source/src/app/components/Apis/Create/Components/APICreateTopMenu.jsx
source/src/app/components/Apis/Create/Components/APIProductCreateTopMenu.jsx
source/src/app/components/Apis/Create/Default/APICreateWrapper.jsx
source/src/app/components/Apis/Create/GraphQL/Steps/ProvideGraphQL.old.jsx
source/src/app/components/Apis/Create/WSDL/BindingInfo.jsx
source/src/app/components/Apis/Details/APIDetails.jsx
source/src/app/components/Apis/Details/APIProductDetails.jsx
source/src/app/components/Apis/Details/components/APIDetailsNavBar.jsx
source/src/app/components/Apis/Details/components/APIDetailsRoutes.jsx
source/src/app/components/Apis/Details/Endpoints/Prototype/PrototypeEndpoints.jsx
source/src/app/components/Apis/Details/EndpointsNew/Endpoints.jsx
source/src/app/components/Apis/Details/LifeCycle/Policies.jsx
source/src/app/components/Apis/Details/MediationPolicies/Diagram.jsx
source/src/app/components/Apis/Details/MediationPolicies/Flow.jsx
source/src/app/components/Apis/Details/MediationPolicies/Overview.jsx
source/src/app/components/Apis/Details/NewOverview/AdditionalProperties.jsx
source/src/app/components/Apis/Details/NewOverview/Documents.jsx
source/src/app/components/Apis/Details/NewOverview/Lifecycle.jsx
source/src/app/components/Apis/Details/NewOverview/MediationPolicies.jsx
source/src/app/components/Apis/Details/NewOverview/Scopes.jsx
source/src/app/components/Apis/Details/Overview/AdditionalProperty.jsx
source/src/app/components/Apis/Details/Overview/APIPropertyField.jsx
source/src/app/components/Apis/Details/Overview/BusinessPlans.jsx
source/src/app/components/Apis/Details/Overview/Overview.jsx
source/src/app/components/Apis/Details/Scopes/Scope.jsx
source/src/app/components/Apis/Details/Subscriptions/SubscriptionsBlock.jsx
source/src/app/components/Apis/Listing/CardView/CardView.jsx
source/src/app/components/Apis/Listing/components/ApiProgress.jsx
source/src/app/components/Apis/Listing/SampleAPI/SampleAPIProductWizard.jsx
source/src/app/components/Apis/Listing/TableView/APITableHeader.jsx
source/src/app/components/Apis/Listing/TableView/APITableToolBar.jsx
source/src/app/components/Base/container/index.jsx
source/src/app/components/Base/container/navigation/NavItem.jsx
source/src/app/components/Base/container/navigation/PageNav.jsx
source/src/app/components/Base/Errors/APINotfound.jsx
source/src/app/data/ApiPermissionValidation.jsx
source/src/app/components/Apis/Details/LifeCycle/TransitionStateButton.js
source/src/app/components/Apis/Listing/SampleAPI/apiProduct.js
source/src/app/components/Apis/Listing/SampleAPI/calculator.js
source/src/app/components/Apis/Listing/SampleAPI/math.js
source/src/app/components/index.js
source/src/app/components/Shared/CustomTheme.js
source/src/app/data/ConfigManager.js
source/src/app/data/Endpoint.js
source/src/app/data/Scopes.js
