### ISSUE TITLE
JWT claim_dialect config is not properly read

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9344]
### Description:
https://github.com/wso2-support/carbon-apimgt/blob/support-6.7.206/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/AbstractAPIMgtGatewayJWTGenerator.java#L55 this line should be corrected to 
```
dialectURI = ServiceReferenceHolder.getInstance().getAPIManagerConfigurationService().getAPIManagerConfiguration().getJwtConfigurationDto().getConsumerDialectUri(); 
```
to get the calim_dialect properly

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chamilaadhi** [comment]
fix https://github.com/wso2/carbon-apimgt/pull/9303
