### ISSUE TITLE
Enable APIKEY signing with primary keystore. 

### ISSUE THREAD

**Issue by akila95fernando** [wso2/product-apim#9350]
### Description:
1) In a scenario where **api_key_keystore**  is not configured and having a separate internal keystore, the APIKEY will be signed using the internal keystore. We need to give the priority to primary keystore istead of internal. 
refer the code [1]

2) When following property is used to point primary keystore for signing APIKEY and the passwords are encrypted with the Ciphertool we were able to notice that the retrieval of the Private key is failing.

_[apim.devportal]
api_key_keystore = "KeyStore"_

[1] https://github.com/wso2-support/carbon-apimgt/blob/07d078afea5d0d78275ac72e7d5ad7ac6823a5ce/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/utils/APIUtil.java#L9951
### Affected Product Version:
APIM-3.1.0

**Comment by rmsamitha** [comment]
@Chamindu36 If this is fixed in master, shall we close this issue?

**Comment by Chamindu36** [comment]
> @Chamindu36 If this is fixed in master, shall we close this issue?

This fix is added to the master. Hence this issue will be closed.

**Comment by hasuniea** [comment]
https://github.com/wso2-support/carbon-apimgt/pull/3612
