### ISSUE TITLE
Existing subscriptions of the old version are copied to the new version of the API.

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/product-apim#9353]
### Description:
Subscriptions of the older version of an API will be copied to the new version of that API even without checking the “Requires Re-Subscription” checkbox. 

### Steps to reproduce:
1. Create an API. 
2. Subscribe to that API using the API store portal.
3. Create a new version of that API.
4. Edit and publish the new version. => Edit API>Manage> Save & publish.

### Affected Product Version:
APIM 2.6.0, APIM 2.1.0

#### Suggested Labels:
APIM 2.6.0, APIM 2.1.0

**Comment by isharac** [comment]
Since APIM 3.0.0 jaggery based applications were deprecated and react based web applications are used.
