### ISSUE TITLE
"Go to public dev portal" icon text is not appropriate 

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#9355]
### Description:
Text in "Go to public dev portal" icon in dev portal is not appropriate. When user clicks on this button, he is directed to a page where he can select any other dev portal. (not to a public dev portal)

![image](https://user-images.githubusercontent.com/2484781/95834831-132f8b00-0d5b-11eb-8ef7-9426ccd7a812.png)

This is something like a public hub where user can select and go to another tenant's dev portal.

![image](https://user-images.githubusercontent.com/2484781/95834879-27738800-0d5b-11eb-9d51-d695ca6d6add.png)

So the text "Go to public dev portal" is not appropriate.
The suggested text is **"Switch Dev Portal"**

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by isharac** [comment]
Fixed.
