### ISSUE TITLE
Devportal Imports result in large webpack

### ISSUE THREAD

**Issue by daz96050** [wso2/product-apim#9361]
### Description:

An improper import of an Mui Icon is unnecessarily increasing the size of the vendors\~Apis\~Landing bundle (17 MiB vs 97KiB)
![image](https://user-images.githubusercontent.com/16062219/95937858-4fd0a600-0d9e-11eb-9863-3ddbcd139458.png)

source/src/app/components/Apis/Listing/StarRatingBar.jsx
source/src/app/components/Apis/Details/StarRatingSummary.jsx

import is:
```
import { StarRating } from '@material-ui/icons';
```
instead of using:
```
import StarRating from '@material-ui/icons/StarRating';
```

### Steps to reproduce:
1. install with `npm ci`
2. Run the dev webpack utility using `npm run dev`
3. observe webpack size for Api Landing bundle
4. Change the imports in the mentioned files above to use 2nd-level import.
5. Observe much smaller webpack size for the bundle

### Affected Product Version:
Affected/3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment]
Related issue https://github.com/wso2/product-apim/issues/9365
