### ISSUE TITLE
Remove hardcoded "/" in the JWT claim key

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#9368]
### Description:
Remove hardcoded '/' values from the claim url.
https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/generator/APIMgtGatewayJWTGeneratorImpl.java#L43-L78

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by HiranyaKavishani** [comment]
Close the issue as per the above commit
