### ISSUE TITLE
Registry Abstraction and Implementation

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#9370]
### Describe your problem(s)
Current Registry implementation of API Manager needs to be replaced with a different approach considering multiple reasons. So in order to eliminate/mitigate those issues, the existing WSO2 Registry implementation will be made selective and new implementation will be introduced so that this registry related persistence/retrieval/search requirements will be replaced with a new implementation. This new implementation approach will be done with MogoDB.

All the persistence related operations need to be defined in a new abstraction layer. Existing Registry or MongoDB implementations will implement the defined abstract interface methods for required persistence operations.

**Comment by rmsamitha** [comment]
- [ ] REgistry implementation of interface method org.wso2.carbon.apimgt.api.APIPersistence#getDocumentation(String apiId, String docId, Organization requestedOrg) doesn't need apiId to be passed. But mongoDb impl will require it.

**Comment by rmsamitha** [comment]
Registry implementation of interface method org.wso2.carbon.apimgt.api.APIPersistence#getDocumentation(String apiId, String docId, Organization requestedOrg) doesn't need apiId to be passed. But mongoDb impl will require it.

**Comment by dushansilva** [comment]
- [ ] when updating swagger we can return the updated swagger

**Comment by dushansilva** [comment]
we need to pass api uuid when calling org.wso2.carbon.apimgt.impl.AbstractAPIManager#getOpenAPIDefinition method
