### ISSUE TITLE
Migrated opaque tokens with unlimited validity period not working

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#9372]
### Description:
When an APIM 2.6 DB with an unlimited validity period is migrated to 3.2, it can be used only once. When trying to use it again, a token expired error occurs.

### Affected Product Version:
3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chamilaadhi** [comment]
Fixes for this issue
https://github.com/wso2-support/carbon-apimgt/pull/2539/
https://github.com/wso2-support/carbon-apimgt/pull/2560
https://github.com/wso2-support/identity-inbound-auth-oauth/pull/761

**Comment by chamilaadhi** [comment]
Public fix 
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1478
https://github.com/wso2/carbon-apimgt/pull/9331
