### ISSUE TITLE
 File content get encoded when using multipart/form-data

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/product-apim#9375]
### Problem
File content gets encoded when sending to the backend.

Reproducing steps

- Creating a slow backend that can upload files. Please refer to the document [1] for a sample Spring application. Add Thread.sleep(200000) in the controller to make a slow backend

- Create a load-balanced API in APIM 2.6 WUM 1597939817141 configure the above backend URL as a child endpoint and set endpoint suspension as follows.
initialDuration =0
progressionFactor = 1.0
maximumDuration =0

- Add the following property in [APIM_HOM]/repository/conf/synapse.properties
build.message.on.failover.enable=true

- Invoke the API to upload a file. A Sample curl command would be as follows.
curl -X PUT https://192.168.1.102:8243/t/abc.com/testAPI/1.0.0/ -H "Authorization: Bearer 23413e44-6b13-3235-93e0-6bde1b99c3b8" -H "Content-Type: multipart/form-data" -F file=@result2.csv -k -v

[1] http://www.vitharana.org/2015/07/invoke-file-upload-spring-service-using.html

**Comment by 1akshitha** [comment]
Duplicate Issue: https://github.com/wso2/product-ei/issues/1525
The fix is working only for the super tenant. In order to work in the tenant environment, we have to add the DECODE_MULTIPART_DATA_PARAM  constant in the  MultitenantConstants.java as well.
