### ISSUE TITLE
Enables masking sensitive data by default

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-apim#9377]
### Describe your problem(s)
APIM need to support masking sensitive data by default the same way as [1].

[1] - https://is.docs.wso2.com/en/latest/setup/masking-sensitive-information-in-logs/#the-masking-pattern-file

Currently we need to do the following changes to get it to work.

- Replace appender.CARBON_CONSOLE.layout.pattern = [%d{DEFAULT}] %5p - %c{1} %m%n with
`appender.CARBON_CONSOLE.layout.pattern = [%d{DEFAULT}] %5p - %c{1} %mm%n`

- Replace appender.CARBON_LOGFILE.layout.pattern = TID: [%tenantId] [%appName] [%d] %5p {%c} - %m%ex%n with
`appender.CARBON_LOGFILE.layout.pattern = TID: [%tenantId] [%appName] [%d] %5p {%c} - %mm%ex%n`

- Replace appender.AUDIT_LOGFILE.layout.pattern = TID: [%tenantId] [%d] %5p {%c} - %m%ex%n
`appender.AUDIT_LOGFILE.layout.pattern = TID: [%tenantId] [%d] %5p {%c} - %mm%ex%n`

The masking feature takes place by adding an additional m after the %m. Therefore you can add an additional m to the log files in which you want the values to be masked.

**Comment by RakhithaRR** [comment]
Masking will not be enabled by default in APIM. The docs have been updated with the necessary steps to enable masking.
