### ISSUE TITLE
Non Expired Opaque Token or Reference Token

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-apim#9382]
### Description:

 The opaque token once generated at step 1 cannot be reused for step 3 similar to the previous version of APIM. 
### Steps to reproduce:

1. User A subscribes to API A using Application A. User A generates the access token using Opaque or Reference Token and set validity to -1 (Non expired).
2. User A is able to make API call for API A.
3. User A subscribes to API B using Application A and reuse the access token generated at step 1.
4. User A is not able to make API call for API B. Error 401 unauthorized.
5. User A updates the access token again for Application A.
6. User A is able to make API call for API B.
7. User A is not able to make API call for API A using access token generated at step 1 and need to use access token generated at step 5.

### Affected Product Version:
APIM 3.1.0

**Comment by dushaniw** [comment]
@Arshardh @dinusha92 Is this reproducing in latest build as well? If not, can we close this issue?
