### ISSUE TITLE
Scope validation fails when using OAUTH token type and Default API version

### ISSUE THREAD

**Issue by girespro** [wso2/product-apim#9386]
### Description:
When using OAUTH as token type and calling and API in the default version (no version in the uri), the scope validation fails. If the same API is called with the version in the uri, the scope validation passes and the request is successful.

### Steps to reproduce:
* Create and API and mark it as default version (I used the Publisher Rest API)
* Add a path to the API protected by a scope
* Create an Application with tokenType `OAUTH`
* Get a token with the expected scope
* Call the API as default version : The call will fail
* Call the API using the published version : It works

### Affected Product Version:
WSO2 API Manager 3.2.0

### Environment details (with versions):
- OS: Linux -> docker.wso2.com/wso2am:3.2.0
- Client:
- Env (Docker/K8s): Docker

---
#### Related Issues:
-

#### Suggested Labels:
-

#### Suggested Assignees:
-

**Comment by HiranyaKavishani** [comment]
@girespro, What is the difference between the above two request flows. Could you please mention the sample requests that you have tried?

**Comment by girespro** [comment]
Well, the first call goes to `<$gatewayUurl>/<$apiContext>/path` while the second goes to <$gatewayurl>/<$apiContext>/<$apiVersion>/path.

During Debugging I was able to see that the failure happens in the `DefaultKeyValidationHandler`. Retriving the API by context and version returns null when the version is `default***`

**Comment by HiranyaKavishani** [comment]
@girespro Thank you for reporting the issue and found the root cause. We will try to reproduce it on our end and fix it.

**Comment by YasasRangika** [comment]
@girespro  This is regarding your issue. Could you recheck the APIM version that error has occurred? because, from 3.2.0 onwards, we only support APPs with JWT token type. If I understood your issue correctly that has happened with an opaque token issued from APP of OAuth type.

**Comment by girespro** [comment]
I was upgrading from APIM 3.0.0 with IS-KM 5.9.0 to APIM 3.2.0 with IS-KM 5.10.0. My Applications from the old version all had the token type 'OAUTH'.

Also, the use of OAUTH token type is not really completely removed from the product. During my upgrade process, I was able to create new Applications with token type OAUTH by using the `api#am#store#v1.0.war` and copying it in the webapps directory of the new version.
