### ISSUE TITLE
[Urgent][Migration][APIM] Synapse artifact Migration issue on tenant domain with Windows OS

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#9391]
### Description:

If someone wants to **, migrate 2.x to 3.x** series, and if **have multi-tenants** and server **run on Windows OS**, they have to use two separate power shell scripts to migrate their synapse artefacts.   
1. **Super Tenants Script**: apim200_to_apim310_gateway_artifact_migrator.ps1
2. **Tenants**: apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1

More details here[1].
[1]. https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310/#step-2-upgrade-api-manager-to-310

In this tenant synapse artefact migration script(apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1) has missed the below handler change. 

```Foreach-Object { $_ -replace "org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler", "org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler" } ```

Therefore it keeps the old deprecated "org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler", and when accessing them throw the below errors. Because the expected handler is "org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler"

> WARN {org.apache.synapse.config.xml.SynapseXMLConfigurationFactory} - API configuration cannot be built - Continue in fail-safe mode org.apache.synapse.SynapseException: Error loading class : org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler - Class not found
at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:105)
:
by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler cannot be found by synapse-core_2.1.7.wso2v147  

Solution: Need to introduce, the below change to that tenant synapse artefact migration script("apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1").
 
```Foreach-Object { $_ -replace "org.wso2.carbon.apimgt.usage.publisher.APIMgtResponseHandler", "org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler" } ```

### Steps to reproduce:
Do a migration on windows environment with multi-tenants from APIM 2.0.0 to APIM 3.1.0 by following this doc[1].  

### Affected Product Version:

APIM 3.x.x with multi tenants

### Environment details (with versions):
- OS: Windows
- Client:
- Env (Docker/K8s): on-prem

---
#### Suggested Labels:

Urgent

**Comment by AnuGayan** [comment]
This was fixed in the APIM 3.2.0 onwards
