### ISSUE TITLE
 Same expiry time for the JWT access token and the Backend JWT token

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#9400]
### Describe your problem(s)
According to the current implementation of apim 3.0.0, there is no way to set the same validity period for both the JWT access token and the backend JWT token when we pass the validity period using the token request. 

Since the JWT token itself contains the backendJWT, both tokens need to have at least equal or greater than value for the backend JWT (since JWT generation does not happen at the token validation stage).

Due to the above-mentioned limitation, for some cases, we cannot fulfill this valid requirement.

**Comment by prasa7** [comment]
Fixed with https://github.com/wso2-support/carbon-apimgt/pull/2615

**Comment by prasa7** [comment]
Added to 3.0.0 branch and this is not valid for master branch
