### ISSUE TITLE
Full Thumbnail Image Not Visible in API Listing and Overview Pages in Publisher and DevPortal

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#9402]
### Description:
When importing APIs to the API Manager, it was observed that the thumbnail image of some APIs were not fully visible in the API Listing and Overview Pages in the Publisher and DevPortal.

**API Listing Page**

![card_view_image](https://user-images.githubusercontent.com/30455603/97136238-98ae3480-1778-11eb-9992-f778b59cd2c1.png)

**API Overview Page**

![overview_page_image](https://user-images.githubusercontent.com/30455603/97136260-a6fc5080-1778-11eb-8257-c085b2496b83.png)

### Steps to reproduce:
1. Import [1].
2. Go to the API Listing page and observe the thumbnail image. It is not fully visible.
3. Click the API and go to the Overview page and observe the image at the top of the Overview page. It is not fully visible.

### Affected Product Version:
- APIM Latest

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS (64-bit)

#### Suggested Labels:
- Import-third-party-APIs

[1] https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/googleapis.com/abusiveexperiencereport/v1/openapi.yaml

**Comment by Sarangan0219** [comment]
This issue is addressed through this one with a different approach https://github.com/wso2/product-apim/issues/10755
