### ISSUE TITLE
Some API Context Values are not Displayed Properly in DevPortal Listing Page

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#9403]
### Description:
When importing APIs to the API Manager, it was observed that the context values of some APIs were not displayed properly in the API Listing Page in DevPortal. Only a part of the context value was visible and it does not have the "..." which indicates the there is some more text to this value.

![context_issue_devportal](https://user-images.githubusercontent.com/30455603/97137828-be3d3d00-177c-11eb-87e8-3f5edb3dff4e.png)

But the context value is displayed properly in the Publisher.

![context_issue_publisher](https://user-images.githubusercontent.com/30455603/97137848-cf864980-177c-11eb-96df-c46bbb08caed.png)

### Steps to reproduce:
1. Import [1]
2. Publish the API.
3. Go to the DevPortal API Listing Page and observe the context value. It is not displayed properly.

### Affected Product Version:
- APIM Latest

### Environment details (with versions):
- OS: Ubuntu 20.04.1 LTS (64-bit)

#### Suggested Labels:
- Import-third-party-APIs

[1] https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/azure.com/managementpartner-ManagementPartner/2018-02-01/swagger.yaml

**Comment by Sarangan0219** [comment]
This issue is not reproducible in the latest version. 
![Screenshot from 2022-01-21 16-31-44](https://user-images.githubusercontent.com/60866295/150516131-423083b3-1e56-4dcd-a36b-f6b0f3af669a.png)
