### ISSUE TITLE
Load balanced endpoints retries infinite number of times.

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#9405]
### Steps to reproduce:

- Create a backend that takes around 200000 ms to send a reply.
- Create a load-balanced endpoint in APIM and configured the above backend as a child endpoint.
- Configure the endpoint suspension as  initialDuration = 0, progressionFactor = 1.0 and maximumDuration =0
- When we invoke the API even though the endpoint gets timeout it re-tries for an infinite no of times.

### Affected Product Version:
APIM 2.6.0 / 3.10

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1660
