### ISSUE TITLE
API Revisioning

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#9406]
API revisioning allows API developers to maintain multiple revisions for a given API. In an environment where API changes are done rapidly, the changes can be deployed as revisions, track the changes applied, and rever back to a stable revision in a case where the API is broken.

Subtasks

- [x] List revisions
- [x] View all information of a revision (including docs, swagger, all)
- [x] Deploy Revision
- [x] Restore Revision

**Comment by malinthaprasan** [comment]
Closing since the feature is completed.
