### ISSUE TITLE
API UUID migration from Registry to APIM Database

### ISSUE THREAD

**Issue by tgtshanika** [wso2/product-apim#9407]
Currently, the UUID of a given API is maintained with the API registry artifact. This particular task is to move the existing API IDs from the registry to AM_API table.

- [x] Implement UUID read/write from AM_DB
- [x]  [Migrating existing UUIDs from Reg DB](https://github.com/wso2/product-apim/issues/9408)

**Comment by CrowleyRajapakse** [comment]
Migration PR: https://github.com/wso2-extensions/apim-migration-resources/pull/60
