### ISSUE TITLE
Update Kernel Version to 4.6.1

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-apim#9410]
### Description:
Update Kernel Version to 4.6.1

**Comment by mushthaq33** [comment]
Done with https://github.com/wso2/carbon-apimgt/pull/9388/commits/e2b3601f8e2f518ce30caa1f63d87da690d994a5 and  https://github.com/wso2/product-apim/pull/9521/commits/5fa694a029c77511bb767ff1263b09faf1e1ecfa
