### ISSUE TITLE
Throttling Policies for Streaming APIs

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-apim#9432]
Streaming APIs are predominantly based on server-initiated communication. Therefore, the throttling policies used for client-initiated request-response based communication might not be directly applicable.

First, we need to research this to define 'what throttling policies mean in a streaming API'. And implement the required polices

**Comment by malinthaprasan** [comment]
@chanikag could you please check and close if this is completed

**Comment by chanikag** [comment]
Added by https://github.com/wso2/product-apim/pull/10010
