### ISSUE TITLE
Prototyping APIs doesn't work as expected for JS based mocks

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#9442]
### Description:
According to the document [1] when I import an OpenAPI which has a sample response when creating a prototype API which has a JS implementation, it is supposed to auto generate some JS code that mocks the API response. That doesn't seem to happen as expected on version 3.2.0 of the product. See screenshot below.

![image](https://user-images.githubusercontent.com/6469654/97376975-d4660d00-18e4-11eb-96dc-1877fa6c3479.png)

[1] - https://apim.docs.wso2.com/en/latest/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script/

### Steps to reproduce:
Follow the pointed doc and notice the behavior is different then mentioned.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9326
