### ISSUE TITLE
Cannot create an API using swagger json file if is bigger than 15Kb.

### ISSUE THREAD

**Issue by giosdas** [wso2/product-apim#9460]
### Description:
Cannot create an API using swagger json file if is bigger than 15Kb.
For example if I upload swagger petstore it work ( 14Kb) but with pretty printed version of the same swagger I receive this error
![immagine](https://user-images.githubusercontent.com/16049206/97580457-a15e6f00-19f3-11eb-9d30-5b59339bbfb5.png)

In attachment logs and swagger used.
Notes: I'm using HTTPS

### Steps to reproduce:
1. Login as admin and open publisher
2. Click CREATE API  "I Have an existing rest api"
3. Upload attached "petstore_swagger_prettyprinted.json" 
![immagine](https://user-images.githubusercontent.com/16049206/97580457-a15e6f00-19f3-11eb-9d30-5b59339bbfb5.png)

If I create api using an url with petstore_swagger_prettyprinted.json it work, but I cannot modify the json/yaml from apim webapp beacuse I receive the same error

### Affected Product Version:
wso2 apim 3.1.0

### Environment details (with versions):
- OS: Ubuntu 18
- Client: Firefox/Chrome
- Env: Virtual server

### Attachments
[apim.log](https://github.com/wso2/product-apim/files/5458688/apim.log)
[petstore_swagger_prettyprinted.json.gz](https://github.com/wso2/product-apim/files/5458697/petstore_swagger_prettyprinted.json.gz)
[petstore_swagger.json.gz](https://github.com/wso2/product-apim/files/5458698/petstore_swagger.json.gz)

**Comment by tmkasun** [comment]
Hi @giosdas 

Is this a vanilla wso2 apim 3.1.0 pack ?

**Comment by giosdas** [comment]
Hi @tmkasun 

It's a wso2 apim configured with a wso2 IS 5.10.0 as key manager
