### ISSUE TITLE
Unable to delete apis after even after removing the subscriptions

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#9476]
### Description:
Create an API and publish
Go to devportal and subscribe to the API
Now go to the subscriptions page from the publisher and press the "Block production only" button.
Now go back to devportal and unsubscribe.
From publisher try to delete the API.
It's not possible to do so.

Only after deleting the Application from devportal it allows to delete the API.

Effected version: 3.2.0

**Comment by NethmiRanasinghe** [comment]
This issue is not reproducing in the latest version APIM 4.4.0
