### ISSUE TITLE
Suggested to add tenantDomain PAX plugin (similar to tenantId)

### ISSUE THREAD

**Issue by Grr1967** [wso2/product-apim#9498]
### Describe your problem(s)
Currently there is a tenant ID PAX plugin for the logging mechanism. I suggest to add also similar one for tenant domain.

### Describe your solution
Same as TenantIdConverter.java, just display the domain instead of the ID

### How will you implement it
public class TenantDomainConverter extends LogEventPatternConverter {
    private static final TenantDomainConverter INSTANCE = new TenantDomainConverter();

    /**
     * Constructs an instance of TenantDomainConverter.
     */
    private TenantDomainConverter() {
        super("tenantDomain", "tenantDomain");
    }

    /**
     * Obtains an instance of TenantDomainConverter.
     *
     * @param options ignored since it cannot be configured in log4j2.properties
     * @return instance of TenantDomainConverter
     */
    public static TenantDomainConverter newInstance(String[] options) {
        return INSTANCE;
    }

    @Override public void format(LogEvent event, StringBuilder toAppendTo) {
        if (getTenantDomain() != null) {
            toAppendTo.append(getTenantDomain());
        }
    }

    /**
     * Obtains the tenantDomain from CarbonContext.
     *
     * @return tenantDomain tenantDomain of ThreadLocalCarbonContext
     */
    public String getTenantDomain() {
        String tenantDomain = String.valueOf(AccessController.doPrivileged(new PrivilegedAction<String>() {
            public String run() {
                return CarbonContext.getThreadLocalCarbonContext().getTenantDomain();
            }
        }));

        return tenantDomain;
}

**Comment by 1akshitha** [comment]
Closing the issue as the wum update is released for APIM 3.2.0
