### ISSUE TITLE
WSO2 APIM 3.2.0 not working behind reverse proxy

### ISSUE THREAD

**Issue by nkhan95** [wso2/product-apim#9506]
### Description:
I am trying to configure WSO2 APIM behind reverse proxy but it is not working. I followed up [this](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer/#step-3-configure-the-reverse-proxy-settings-in-the-product) article and [this](https://ishara-cooray.blogspot.com/2019/11/how-to-change-default-hostname-of-wso2.html) blog as well. I can access the /carbon without any issue but when accessing /publisher or /devportal, it is redirecting to my machine IP for OAUTH.

### Steps to reproduce:
1. Install and configure APIM to work on single server.
2. Install and configure nginx reverse proxy on another server and follow the article mentioned in description.

### Affected Product Version:
APIM 3.2.0

### Environment details (with versions):
- OS: CentOS 8
- Client: Windows 10

---

**Comment by isharac** [comment]
@nkhan95 
The blog you have followed applies for APIM 3.0.0 and in 3.2.0 configuration is slightly different.
So for 3.2.0 following the documentation would be sufficient.
If you have set the customurl.enabled to true it will read the host from the X-Forwarded-For header to construct the server URL for accessing OAuth

If there is no need to have portal URLs per each tenant you can keep this config false given that you have configured the reverse proxy host as the hostname in the deployment.toml.
But if you need portal URLs per each tenant or original hostname in the deploymnet.toml you can change the customUrl. forwardedHeader to a header that gives you the reverse proxy host name.(ex: X-Forwarded-Host)

**Comment by nkhan95** [comment]
@isharac 
Thank you for your reply. I commented out 'X-Forwarded-For' and it worked like a charm.
