### ISSUE TITLE
user registration is successful messagebox UX issue

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#9513]
### Describe your problem(s) 
In self-registration in the devportal, the message box that appears when user registration is successful ha a red color close button. Please refer the attached image.
Having a red color button gives a negative first impression that the operation is not successful.

### Describe your solution

Changing the color to the primary color will improve UX.

### How will you implement it

---
#### Suggested Assignees:

<img width="468" alt="Screen Shot 2020-11-11 at 3 24 34 PM" src="https://user-images.githubusercontent.com/8057793/98800706-c234b480-2436-11eb-8d50-a43dd947c9db.png">

**Comment by Krishanx92** [comment]
This color coming from Auth app color theme which is orange, hence issue closing.
