### ISSUE TITLE
[3.2.0] Signup UI input field UI validation is not available.

### ISSUE THREAD

**Issue by isharac** [wso2/product-apim#9516]
### Describe your problem(s)

Need to validate the input fields of the Self SignuP UI.

password
email

**Comment by tmkasun** [comment]
I hope you are referring to this self signup page for devportal
![image](https://user-images.githubusercontent.com/3313885/100042618-d662b380-2e31-11eb-9712-7c3ac1bcf710.png)

when I tried to register with an invalid email and  a password which not complies with the password policy I got error messages as above and below

![image](https://user-images.githubusercontent.com/3313885/100042681-fa25f980-2e31-11eb-8554-5643028b80d1.png)

**Comment by tmkasun** [comment]
Can you please confirm the behavior ?

**Comment by Krishanx92** [comment]
Stale issue. hence closing
