### ISSUE TITLE
Provisioning clients for Keycloak client_secret_jwt gives error

### ISSUE THREAD

**Issue by Arshardh** [wso2/product-apim#9520]
### Description:
The error thrown is as follows:
`ERROR - GlobalThrowableMapper org.wso2.carbon.apimgt.api.APIManagementException: Consumer credentials are blank `

**Comment by HiranyaKavishani** [comment]
Close the issue as per the above commit

**Comment by HiranyaKavishani** [comment]
Close the issue as per the above commit
