### ISSUE TITLE
Stop reverse proxying the OAuth2 and other Identity related Endpoints through the API Gateway

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim#9523]
### Problem
Currently the OAuth2 /token, /authorize and a few other endpoints have been reverse proxied through the API Gateway. This causes issues with redirect protocols and cookies.

### Solution
Directly expose the relevant endpoints for client access. Organizations who don't want to expose these ports can consciously reverse proxy these endpoints either through the gateway or a load balancer. 

### Note
This will impact client applications which are being migrated from older versions. This change therefore needs to be backwards compatible. A possible solution could be to leave the gateway endpoints as is (for the sake of old clients) and fix the documentation to reflect the direct security endpoints instead of the gateway reverse-proxy endpoints.

**Comment by malinthaprasan** [comment]
@tharindu1st

**Comment by tharindu1st** [comment]
fixed in https://github.com/wso2/product-apim/pull/9878
