### ISSUE TITLE
Values of the "resourcePath" and "httpVerb" attributes are interchanged in the response of the "apis/{apiId}/resource-paths" endpoint

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#9525]
### Description:
In the response of the "apis/{apiId}/resource-paths" endpoint, the value of the "resourcePath" comes with the "httpVerb" attribute. And the value of the "httpVerb" comes with the "resourcePath" attributes as follows. 

            "resourcePath": "POST",
            "httpVerb": "/order/{orderId}"

### Steps to reproduce:
1. Publish an API in the publisher.
2. Add resources to the API.
3. Invoke the "apis/{apiId}/resource-paths" endpoint.

### Affected Product Version:

APIM-3.1.0

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9412
