### ISSUE TITLE
Different appearance for the token endpoint and revoke endpoint in the devportal UI

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#9528]
### Description:
There is a different appearance for the token endpoint and revoke endpoint in the devportal UI.

Subscription & Key Generation Wizard has /oauth2/token and /oauth2/revoke.
![image](https://user-images.githubusercontent.com/44961438/99254544-86d02680-2838-11eb-943b-5d1aa519cf30.png)

Key Configuration has /token and /revoke
![image](https://user-images.githubusercontent.com/44961438/99254571-90598e80-2838-11eb-86b0-d12b2e1c02de.png)

### Affected Product Version:
3.2.0

**Comment by tmkasun** [comment]
Closing the issue since this is fixed in https://github.com/wso2/carbon-apimgt/pull/9395 PR
