### ISSUE TITLE
Option to hide the carbon.super tenant from the tenant list of the devportal UI

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#9529]
### Describe your problem(s)
Can we have a UI improvement to hide the carbon.super tenant from the tenant list?
![image](https://user-images.githubusercontent.com/44961438/99254900-1d044c80-2839-11eb-9e55-42df6db78aed.png)

#### Suggested Labels:
APIM 3.2.0

**Comment by tmkasun** [comment]
closing the issue since it's fixed in https://github.com/wso2/carbon-apimgt/pull/9395
