### ISSUE TITLE
Avoid having to declare FORCE_POST_PUT_NOBODY explicitly in APIM

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/product-apim#9543]
### Description:
When a request comes with an empty body for POST/PUT resources and if the message is build in the mediation flow, this request will be failed.

We can put the below property to the in sequence and avoid this failure. 
<property name="FORCE_POST_PUT_NOBODY" value="true" scope="axis2" type="BOOLEAN"/>

But this should be fixed since, it is necessary to change these sequences for APIs and it difficult when there are a high number of APIs

### Affected Product Version:
wso2am-2.1.0

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1664 in the next APIM release.

**Comment by npamudika** [comment]
Refer https://github.com/wso2/product-ei/issues/4376
