### ISSUE TITLE
GraphQL Validation Failure when the Query attribute of the request is not at the first place

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#9545]
### Description:
GraphQL Validation Failing when we use below request payload

**{"operationName":null,"variables":{},"query":"{\n  patientRequestInfo(organizationId: 151977, programId: 250) {\n    firstName\n    lastName\n  }\n}\n"}**

But the same payload is successful with a different order (Query as the first element) as follows.

**{"query":"{\n  patientRequestInfo(organizationId: 151977, programId: 250) {\n    firstName\n    lastName\n  }\n}\n", "operationName":null,"variables":{}}**

### Steps to reproduce:

- Create a GrphQl API
- Invoke the API with a similar request pattern as below

**{"operationName":null,"variables":{},"query":"{\n  patientRequestInfo(organizationId: 151977, programId: 250) {\n    firstName\n    lastName\n  }\n}\n"}**

### Product Version:
APIM 3.2.0

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9430
