### ISSUE TITLE
[APIM-3.1.0]-Descriptive error response is not displayed in any client with JSON schema validation

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9552]
### Description:
In the latest wum pack(wso2am-3.1.0+1605883070720), when JSON schema validation is tested, upon an unsuccessful call the error response is not displayed in devportal or in Postman.

### Steps to reproduce:
1. Create an API in the publisher
2. Enable JSON schema validation
3. Publish the API
4. Log in to devportal
5. Test the API call with the wrong payload values
6. You will get the following response in devportal and in the carbon management console.

![image](https://user-images.githubusercontent.com/20519000/100071799-771c9780-2e61-11eb-99d3-793be290079e.png)

![image](https://user-images.githubusercontent.com/20519000/100071813-797ef180-2e61-11eb-89da-acdbe5d7becb.png)

But in the previous wum levels(wso2am-3.1.0+1600099491681), we were able to get a descriptive error response as follows.
![image](https://user-images.githubusercontent.com/20519000/100071909-97e4ed00-2e61-11eb-9107-151928947bd5.png)

### Affected Product Version:
wso2am-3.1.0

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9438
