### ISSUE TITLE
Avoid appending trailing backslash at the end of resources in WebSocket APIs when using socket.io based endpoints

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim#9554]
When sending requests from the client-side to a WebSocket API which is created to connect from the [socket.io](https://socket.io/), a trailing backslash is added at the end of the resource by the client (socket.io).

> **Ex: ws://localhost:9099/test/v1/?access_token=<access_token>**

This cause an authentication failure inside the WebsocketInboundHandler since the apiContextUri is having an additional trailing backslash appended at the end of resource which is not supported by APIM.

Hence, need to omit appending non-required characters (i.e. trailing backslash) at the end of the URL path.

#### Suggested Labels:
wso2am-3.0.0

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9450
