### ISSUE TITLE
[APIM-3.2.0]-SP is not created in the carbon management console for non-admin users

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#9561]
### Description:
When a non-admin user creates an application and generates the application keys via devportal or REST API calls the keys are generated successfully. The role is created and assigned to the correct user but the relevant SP for the application is not created in the carbon management console. This was tested in the latest wum pack of wso2am-3.2.0 and the deployment was an all-in-one pack.

### Steps to reproduce:
1. Create a user named "demo" in the carbon management console and assign Internal/everyone and Internal/subscriber roles.
2. Create an application in the devportal via devportla UI or through the REST API call.
3. Generate application keys and access tokens for the application via devportal or REST API call.
4. Navigate to carbon management console --> Main --> Service Providers --> List
5. There won't be an SP created for the application with a non-admin user.

### Affected Product Version:
wso2am-3.2.0

**Comment by isharac** [comment]
This is the expected behavior.
