### ISSUE TITLE
About page of Management console of APIM 3.2.0 product is showing APIM 2.6.0 details

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#9563]
### Description:
When clicking the "About" page of Management console of APIM 3.2.0, it will show APIM 2.6.0 details as in the screenshot.
![screenshot_1](https://user-images.githubusercontent.com/15210142/100320045-a6104600-2fe6-11eb-901b-2efe2541bd36.png)
![screenshot_2](https://user-images.githubusercontent.com/15210142/100320055-a9a3cd00-2fe6-11eb-9f89-070c83db79e5.png)

I hope this is reproducing other APIM 3.x products. 
### Steps to reproduce:
Start APIM 3.2.0 pack and log to the management console of APIM. Click "About" page.

### Affected Product Version:

APIM 3.2.0 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by isharac** [comment]
https://github.com/wso2/product-apim/pull/9575
