### ISSUE TITLE
[APIM 3.2.0] Admin Portal Theming

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9573]
### Description:

The Logo of the Admin portal is hardcoded in the React Component [Navigator.jsx](https://github.com/wso2/carbon-apimgt/blob/v6.7.206/features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/Base/Navigator.jsx). Hence, changing the logo URL in the `defaultTheme.js` of the Admin portal is not reflected.

Furthermore, the `appBar` customizations made in the Admin portal are not reflected due to the Styles being configured in the React components without any reference to the `defaultTheme.js` artifact.

### Steps to reproduce:

- Change the Logo URL of the Admin portal in `<apim>/repository/deployment/server/jaggeryapps/admin/site/public/conf/defaultTheme.js`

### Affected Product Version:

- APIM 3.2.0

**Comment by Krishanx92** [comment]
This issue fixed in latest pack, hence closing
