### ISSUE TITLE
Enable Mutual SSL behind Proxy/LB

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/product-apim#9576]
### Describe your problem(s)
There are some use cases where the Proxy/LB send the client certificate unencoded as a header. But Mutual SSL is failing in this use case since, it is always try to decode the certificate present in the header by the source code.

### Describe your solution
We can ignore the decoding part by the source code for this particular occasion using a system property or configuration.

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9257
