### ISSUE TITLE
Having new elements inside the JWT payload

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#9579]
### Description:
There are new elements in the JWT payload in the latest APIM 2.6 version (ex: aud). It would be better if we can have a configuration to add or remove these claims.
![image](https://user-images.githubusercontent.com/44961438/100714392-b2781280-33db-11eb-9c1b-495b8033e6f9.png)

### Affected Product Version:
APIM 2.6.0

**Comment by menakaj** [comment]
This can be configured by setting the parameter apim.disableAudClaim.
To remove the claim from the token, start the server with

`-Dapim.disableAudClaim=true`
