### ISSUE TITLE
API Key Referer restriction is not working when "Referer" header is not added to the request

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#9581]
### Description:
When invoking an API which is secured with API Key with referer restriction is enabled (allowed referer: www.example.com/path) following behavior can be observed.

1. Invoked the API with the -H "Referer: www.example.com/path" added to the request. (Successfully received the response as expected)
2. Invoked the API with the -H "Referer: www.google.com" added to the request. (Got the forbidden error as expected)
3. Invoked the API without adding the Referer header to the request. (Successfully received the response)

1st and 2nd behaviors are expected but 3rd scenario should be addressed without depending on the Referer header as it is only an optional attribute. As per the source code, the referer is extracting from the transport headers of the incoming request. Hence, need to address the situations like the 3rd one which Referer doesn't comes in the transport headers.

### Steps to reproduce:

1. Publish an API with application level security set only to API key.
2. Create an Application.
3. Subscribe to the API.
4. Add a permitted referer and generate an API Key.
5. Invoke the API as mentioned in the description.

### Affected Product Version:
APIM-3.2.0

**Comment by isharac** [comment]
Fixed.
