### ISSUE TITLE
Default API invocation fail with the Opaque token

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#9594]
Deployment migrated from 2.6 -> 3.2. So there are applications that generate opaque tokens.

APIs with the version in the URL can invoke without any issue using opaque token but once version removed from URL (default API) it failed with below error message.

The same behavior can reproduce after extracting jti from the JWT token as well.

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9403
