### ISSUE TITLE
500 Internal server error from revoke endpoint when regenerating tokens from the Store

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/product-apim#9602]
### Description:

This issue occurs when the Store UI has the last generated access token which is already revoked from Revoke API. Since it is already revoked, while regenerating a token from Store UI it fails to revoke the token and generate a new one.

### Steps to reproduce:

1. Generate access token from the store UI.
2. Revoke the generated access token using the revoke endpoint.
3. Try to regenerate access tokens from the UI

### Affected Product Version:

APIM 2.2 (1602171620869)

**Comment by vithu30** [comment]
This is not reproducible in latest built pack (APIM 4.0.0)
