### ISSUE TITLE
[2.1.0] Disable chunking is not working with large payloads

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#9614]
### Description:
Payloads are sent to back-end in chunks with large payloads, even though the following sequence is added as in-sequence to disable chunking:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="disableChunking">
   <property name="DISABLE_CHUNKING" value="true" scope="axis2"/>
</sequence>
```

### Steps to reproduce:

1. Create an API with POST resource
2. Add the above sequence as in-sequnce to disable chunking
3. Invoke the API with large payload

### Affected Product Version:
2.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by vithu30** [comment]
Fixed in master with https://github.com/wso2/wso2-synapse/commit/45327928d88ec228bef3319b6c61d5484f231a2b and https://github.com/wso2/wso2-synapse/commit/720a8ca01a51dd44d27e18fe2fd1164704a54c62

**Comment by vithu30** [comment]
Issue reported in API Manager 2.2.0

**Comment by ruks** [comment]
Closing since this is already fixed in public branch
