### ISSUE TITLE
High heap utilization in Analytics node when listing the API Subscriptions in the Publisher UI

### ISSUE THREAD

**Issue by Methma** [wso2/product-apim#9628]
### Description:
Noticed a high heap utilization and a 'GC overhead limit exceeded' error in the Analytics nodes when there is a large data set in the ApiUserPerAppAgg table. When analyzing the carbon logs during that time the below store query is observed, which is having a time range from **0L**.

> Error while querying for siddhiApp: APIM_ACCESS_SUMMARY, with query: from ApiUserPerAppAgg on(apiCreatorTenantDomain=='carbon.super' AND apiName=='xxxx') within 0L, 1605888971800L per 'months' select apiContext, username, totalRequestCount, apiVersion; Error: Error executing 'store_select_query_ApiUserPerAppAgg', GC overhead limit exceeded org.wso2.siddhi.core.exception.StoreQueryCreationException: Error executing 'store_select_query_ApiUserPerAppAgg', GC overhead limit exceeded

To overcome this, we can add a time range in this section instead of the 0L timestamp for "from" time. (eg: Month, Week, etc)

The respective query is created in [1] and a store query call is executed only when Analytics is enabled.

In analytics disabled APIM deployments it is showing the "No data available" label in all 2.x.x APIM distributions.
For this, it's better to have a meaningful label.

[1]. https://github.com/wso2/carbon-apimgt/blob/a3f91941622aed9bed0bc06884deaad009ce6926/components/apimgt/org.wso2.carbon.apimgt.usage/org.wso2.carbon.apimgt.usage.client/src/main/java/org/wso2/carbon/apimgt/usage/client/impl/APIUsageStatisticsRestClientImpl.java#L1915

### Steps to reproduce:
1. Deploy an API in Publisher.
2. Subscribe and Invoke that API.
3. Go to the Publisher -> APIS -> Subscriptions
4. The above API Call will be triggered and with a large database, this can lead to GC overhead limit issues.

### Affected Product Version:
2.x.x

**Comment by vithu30** [comment]
Fixed in master with https://github.com/wso2/carbon-apimgt/commit/f737f2e58da96f3b81206f64f88ea1e8ddb75c37
