### ISSUE TITLE
Revamping WS API support to be inline with Streaming APIs

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-apim#9633]
The current WebSocket APIs designed need to be revamped to be inline with the overall design for Streaming APIs.

**Comment by malinthaprasan** [comment]
Shall we add relavant PRs and close this

**Comment by Krishanx92** [comment]
<img width="215" alt="Screenshot 2024-12-09 at 15 18 03" src="https://github.com/user-attachments/assets/4dd75321-9a6c-42c6-aba3-462891242970">
