### ISSUE TITLE
Can invoke APIs with revoked API keys

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#9641]
### Description:
Can invoke APIs by using previously revoked API keys via revoke endpoint.

### Steps to reproduce:
Create and publish an API with API key authorization.
Generate an API Key.
Invoke the revoke endpoint and revoke the generated API key.
Invoke the published API by using revoked API key.

### Affected Product Version:
3.2.0

**Comment by RakhithaRR** [comment]
A customer has further reported that they can use the revoked APIKEY token to invoke an API after a server restart. We need to handle that scenario as well.
