### ISSUE TITLE
UI inconsistency in Devportal grant types selection

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#9651]
### Description:
When deselecting client credentials grant type and adding Code grant type in the application key generation process, generate key button is getting disabled.

### Steps to reproduce:
Deselect the client credential grant types from grant types list, the generate key button is getting disabled.
After adding the callback URL, the generate key button is getting enabled again.
If callback URL added first, selects the Code grant type and Deselects the Client Credentials grant type, still the generate key button will be disabled.
### Affected Product Version:
APIM v3.1.0

**Comment by chashikajw** [comment]
This issue is not there in the public branch
