### ISSUE TITLE
Custom interface to modify/validate API request

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#9656]
### Describe your problem(s)
In the current APIM solution, we are validating and modifying API requests (according to various API specs/regulations) by plugging in synapse handlers, in between existing APIM default synapse handlers. 
The correct way to handle this is by the product APIM providing a custom extension point and a defined interface ( to request in and respond back) to handle all these business logic related validations and modifications. 

According to the discussion we had, the below parameters were suggested as the input parameters for this interface. 

- Request Payload
- Transport Headers
- HTTP Method
- Elected Resource
- API Context
- Transport Certificate
- API Name
- API Version
- Unique Key to the request

Output parameters

- Success/ Error Payload
- Error code
- Added headers
- Validation Status ( Success/ Failure)

**Comment by dushaniw** [comment]
Fixed with https://github.com/wso2/product-apim/issues/9904
