### ISSUE TITLE
Schema validation extension point

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#9657]
### Describe your problem(s)
In the current API Manager implementation, swagger is published as a local entry and then it is read and OpenAPI model is created for schema validation purposes. If someone need to do a custom validation against the swagger, it is costly to build the OpenAPI object again in a different place. So the better approach to solve this problem is by having an extension point in the schema validator

Suggested Input parameters for the extension point

- Transport headers
- Scopes 
- Context properties
    -  Open API Object
    - HTTP Method
    - API Version
    - API Context
    - Elected resource

Suggested output parameters

- Error Payload
- Error Code
- Added Headers

**Comment by Krishanx92** [comment]
Is this requirement still valid? We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
