### ISSUE TITLE
[Feature Request] Custom labels for Web-socket APIs

### ISSUE THREAD

**Issue by NomadXD** [wso2/product-apim#9659]
### Describe your problem(s)
We want to enable support for adding custom labels to web-socket APIs. For the project envoy based micro-gateway, there's a feature to deploy APIs to a selected set of gateways based on their labels. 

### Describe your solution
Adding gateway labels to web-socket APIs from the publisher portal.   

### How will you implement it
Add a separate section to add gateway labels. Currently only the name, context, version, endpoint and business plans fields are there as shown in the below image. 
[publisher portal web-socket design view](https://drive.google.com/file/d/1CiSIfJIMdjVwl-cB4_wAXgFwnEsHljJ4/view?usp=sharing)

#### Suggested Labels:
Type/New Feature

cc @Rajith90

**Comment by Krishanx92** [comment]
Is this requirement still valid? We are closing the issue due to a long period of inactivity. Please re-open it if you need this again.
