### ISSUE TITLE
wso2 apim 3.2.0 disbale data chunking does not work.

### ISSUE THREAD

**Issue by ashailly** [wso2/product-apim#9671]
Running WSO2 apim 3.2.0 as docker container using https://github.com/wso2/product-apim/releases/download/v3.2.0/wso2am.zip. Tried disabling data chunking on message mediation policy section as per - https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-mediation/disabling-message-chunking/, it does not work! 
Did anyone else see this issue ? Need immediate help. TIA.

**Comment by isharac** [comment]
Can you please go to the Lifecycle tab and try re-deploying the API.
You can verify whether the chunking is enabled by enabling the wire log

**Comment by ashailly** [comment]
Re-deploying and trying the published API worked. I was trying to test it using Publisher >Test-Console and that never worked! Thanks much!

**Comment by isharac** [comment]
Glad to hear that it worked!
I am afraid mediation sequences do not work in the 3.2.0 publisher test console.
But we have fixed it in the upcoming release APIM 4.0.0
