### ISSUE TITLE
X-JWT-Assertion header is not removing from the client response

### ISSUE THREAD

**Issue by chashikajw** [wso2/product-apim#9673]
### Description:

As $subject X-JWT-Assertion header is not removing from the client response.

### Steps to reproduce:

1. Started the APIM server with enabling backend JWT
2. Deployed a sample API.
3. Added a custom IN mediation sequence. (json_validator.xml).
4. Invoked the API with an invalid JSON payload.
5. Could observe that the X-JWT-Assertion header is received by the client.

### Affected Product Version:

APIM 2.2.0 and all the other versions

### Environment details (with versions):
- OS: Ubunutu 20.04
- Client:
- Env (Docker/K8s):

**Comment by Jayanie** [comment]
Fixes https://github.com/wso2/product-apim/issues/9673

**Comment by Jayanie** [comment]
Fixed in https://github.com/wso2/product-apim/pull/9683
