### ISSUE TITLE
[3.2.0] High CPU when a single request hits the Gateway on Kubernetes

### ISSUE THREAD

**Issue by okhuz** [wso2/product-apim#9685]
### Description:
High CPU when a single request hits the Gateway. 

Followed [troubleshooting](https://apim.docs.wso2.com/en/latest/troubleshooting/admin-troubleshooting-in-production-environments/) documentation and findings are like this:

- usage result:
%CPU CPU  NI S     TIME   PID   TID
...
78.1   -   0 R 00:17:27   167   356
77.9   -   0 R 00:17:25   167   357
...

- dump result according to thread ids: 
```
"HTTPS-Listener I/O dispatcher-1" #190 prio=5 os_prio=0 cpu=1043696.51ms elapsed=1336.89s tid=0x00007fdc54094000 nid=0x164 runnable  [0x00007fdc1b606000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@11.0.8/Native Method)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.8/EPollSelectorImpl.java:120)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.8/SelectorImpl.java:124)
        - locked <0x00000000eafef8d8> (a sun.nio.ch.Util$2)
        - locked <0x00000000eafef778> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@11.0.8/SelectorImpl.java:136)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:256)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)

"HTTPS-Listener I/O dispatcher-2" #191 prio=5 os_prio=0 cpu=1041420.55ms elapsed=1336.89s tid=0x00007fdc5409d000 nid=0x165 runnable  [0x00007fdc1b505000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@11.0.8/Native Method)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.8/EPollSelectorImpl.java:120)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.8/SelectorImpl.java:124)
        - locked <0x00000000eaff0950> (a sun.nio.ch.Util$2)
        - locked <0x00000000eaff08f8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@11.0.8/SelectorImpl.java:136)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:256)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)
```
This two threads consuming a lot of resources and I couldn't find a specific reason. 

### Steps to reproduce:

Deploy helm chart on AWS m5a.large worker nodes.

### Affected Product Version:
API-M version 3.2.0

### Environment details (with versions):
- OS: AWS Linux
- Env (Docker/K8s): K8s 1.18

---

**Comment by dinusha92** [comment]
Hi @okhuz , can you please let me know if you have done any resources changes in the heml charts. I believe you are using WSO2 helm charts. Further, can you tell me the deployment pattern you are using and how many nodes are there the cluster(m5a.large). According to the WSO2 helm charts, a pod requires minimum 2000m CPUs(2 CPUs). Since m5a.large node has 2 vCPUs, I'm guessing it can be that(just a possibility). Also can you tell me any specific scenario that you are trying out when you observe this high CPU usage? As in higher throughput, mediation logics included etc.

**Comment by okhuz** [comment]
Hi @dinusha92, we have auto-scaling nodes on AWS EKS, between 3 and 6 and in [chart](https://github.com/wso2/kubernetes-apim/blob/master/advanced/am-pattern-2/values.yaml#L70) the limit is 2000m, I have assumed that it would work just as it is. I have increased the request CPU but it did not had any impact. Do we need bigger instance?

**Comment by dinusha92** [comment]
Can you check the resource usage of the node and the pod using `kubectl top node <node name>` and `kubectl top pod <pod name>`. (Pod related command should be executed with the namespace)

**Comment by pubudu538** [comment]
Shall we apply this https://github.com/wso2/product-apim/issues/8908?

**Comment by okhuz** [comment]
Gateway consuming all the resources in a single node. We are currently upgrading our instances in size to test this issue.

**Comment by okhuz** [comment]
```
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
xxxxxxx    65m             1%        742Mi                  10%       
xxxxxxx    240m           6%        3065Mi                44%       
xxxxxxx    259m           6%        3145Mi                45%       
xxxxxxx    2198m         56%      3660Mi                53%       
xxxxxxx    190m           4%        2762Mi                40% 
```
------
```
NAME                                                                                                       CPU(cores)   MEMORY(bytes) 
wso2am-pattern-2-am-gateway-deployment-7c5dc7dc67-d68tr           1956m         958Mi           
wso2am-pattern-2-am-gateway-deployment-7c5dc7dc67-jczjb            519m           958Mi  
```

Still no success. It should be very small CPU consumption on idle, am I right?

**Comment by okhuz** [comment]
> Also can you tell me any specific scenario that you are trying out when you observe this high CPU usage?

We have a couple of APIs in API manager but this happens directly after Gateway receives any request. Like if I enter gateway.xxx.com or gateway.xxx.com/services/Version, right after that CPU spins to limit.

**Comment by dinusha92** [comment]
As @pubudu538  mentioned, we have fixed a performance issue. If you have WSO2 subscription you can use WUM in order to get the bug fix. If not you will have to include the fix manually and patch it.

**Comment by navaneethVG** [comment]
Hi @dinusha92 ,

we do not have a subscription for wso2, can someone let us know how to apply this fix manually ?
We are facing the same issue.

Thanks,
Navaneeth

**Comment by nachii** [comment]
Hello everybody,
same problem here.

> Shall we apply this #8908?

Is this fix suggested in this issue also valid for the APIM 4.0.0?

Thanks in advance
