### ISSUE TITLE
Error in importing API definition

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#9689]
### Description:
Import API definition from API Definition of an API as below, and getting a 415 status code error.

Importing API definition works if we import from the menu "I have an existing REST API".

### Steps to reproduce:

![image](https://user-images.githubusercontent.com/12208083/103857223-1200c680-50dc-11eb-8bf0-21429b3ac358.png)

API-M 4.0.0 M2

**Comment by mushthaq33** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/9559
