### ISSUE TITLE
Latest improvements to the APIM 3.2.0 under update 2.0

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#9692]
This ticket is created to track the latest improvements to APIM 3.2.0 under update 2.0. Following issues are tracked here.

https://github.com/wso2/product-apim/issues/9324
https://github.com/wso2/product-apim/issues/9345
https://github.com/wso2/product-apim/issues/9329
https://github.com/wso2/product-apim/issues/9328"
https://github.com/wso2/product-apim/issues/9368
https://github.com/wso2/product-apim/issues/9372 
https://github.com/wso2-extensions/apim-km-keycloak/issues/23
https://github.com/wso2/product-apim/issues/9442
https://github.com/wso2/product-apim/issues/9451
https://github.com/wso2/product-apim/issues/9461
https://github.com/wso2/product-apim/issues/9341
https://github.com/wso2/product-apim/issues/9365
https://github.com/wso2/product-apim/issues/9340
https://github.com/wso2/product-apim/issues/9339
https://github.com/wso2/product-apim/issues/9325
https://github.com/wso2/product-apim/issues/9385
https://github.com/wso2/product-apim/issues/9301
https://github.com/wso2/product-apim/issues/9387
https://github.com/wso2/product-apim/issues/9288
https://github.com/wso2/product-apim/issues/9463
https://github.com/wso2/product-apim/issues/8079 
"https://github.com/wso2/product-apim/issues/9528
https://github.com/wso2/product-apim/issues/9529
https://github.com/wso2/product-apim/issues/9520
https://github.com/wso2/product-apim/issues/9491
https://github.com/wso2/product-apim/issues/9328
https://github.com/wso2/product-apim/issues/9329
https://github.com/wso2/carbon-apimgt/issues/9375
https://github.com/wso2/product-apim/issues/9545
https://github.com/wso2/product-apim/issues/9541
https://github.com/wso2/product-is/issues/10016"
https://github.com/wso2/product-apim/issues/8389
https://github.com/wso2/product-apim/issues/9573
https://github.com/wso2/product-apim/issues/9554
https://github.com/wso2/product-apim/issues/9536
https://github.com/wso2/product-apim/issues/7885
https://github.com/wso2/product-apim/issues/9479

**Comment by Hervinho** [comment]
#9324 the issue still persists. I tried to override with the following and t did not reflect

`
palette: { background: { appBar: '#f2f2f2', appBarSelected: '#85c441', leftMenu: '#f2f2f2', leftMenuActive: '#f2f2f2', drawer: '#1a1f2f', activeMenuItem: '#008ea9', }, }
`

**Comment by 1akshitha** [comment]
Closing the issue as the updates are released
