### ISSUE TITLE
Subscription does not get removed in publisher

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-apim#9707]
### Description:
Subscription of APIs and API Product does not get removed after subscription blocking.

### Steps to reproduce:
- Follow steps in https://github.com/wso2/product-apim/issues/9706
- Remove the subscription from Dev Portal
- Check the Publisher Subscription tab

### Affected Product Version:
M2 Pack

**Comment by malinthaprasan** [comment]
Not reproducible in the latest pack.

**Comment by rmsamitha** [comment]
@malinthaprasan Can we close this if this was not reproducible in the latest pack?

**Comment by malinthaprasan** [comment]
@YasasRangika to double check and close this

**Comment by YasasRangika** [comment]
This issue is not reproducing in latest APIM pack(9.0.89 components). Hence we can close this issue.
