### ISSUE TITLE
Advanced Endpoint Configuration changes not getting saved in UI

### ISSUE THREAD

**Issue by sajinidesilva** [wso2/product-apim#9725]
### Description:
In the UI when endpoint type is set to HTTP/SOAP and click on advanced configuration, then change the message content format. After saving the changes the change is not getting persisted.  

### Steps to reproduce:

- Create an API
- Go to endpoint configuration
- Select HTTP/SOAP as endpoint type
- Click on advanced configuration.
- select "Representational State Transer (REST)" as the message content format.

### Affected Product Version:
2.5.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s): Standalone

---

**Comment by Jayanie** [comment]
This is fixed in the latest
