### ISSUE TITLE
WSDL URL get vanished in import WSDL form

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9735]
### Description:

When importing a WSDL to APIM and create an API , the WSDL URL get disappeared after validation

![image](https://user-images.githubusercontent.com/3313885/104838877-9ecd3080-58e3-11eb-99be-4a6db9b2ef4c.png)

Sample WSDL : https://svn.apache.org/repos/asf/airavata/sandbox/xbaya-web/test/Calculator.wsdl

**Comment by malinthaprasan** [comment]
Not reproducible to me in the latest pack.

![createWSDL](https://user-images.githubusercontent.com/1591316/111210502-54baaf80-85f3-11eb-805a-7e03d101bdb9.gif)
