### ISSUE TITLE
Rename Gateway URL in devportal as API Endpoint URL

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9749]
### Describe your problem(s)

Needs to refactor the API overview in dev portal, Which includes the renaming of gateway URLs as API Endpoint(s)

Following is the design (need to get the XD separately), and there has to be some refactoring to the API Endpoint URL placement 
![image](https://user-images.githubusercontent.com/3313885/105028853-93ab0980-5a77-11eb-8fee-0b5fb5367f86.png)

**Comment by tmkasun** [comment]
@erangatl   Shall we update the design as per the offline chat and attach a screenshot ?

**Comment by erangatl** [comment]
![DevPortal Overview – 5](https://user-images.githubusercontent.com/20179540/105047205-07591080-5a90-11eb-8729-755fc1e7ea10.png)
