### ISSUE TITLE
Inform reason openapi spec is not valid on upload.

### ISSUE THREAD

**Issue by emiliobristech** [wso2/product-apim#9759]
### Describe your problem(s)

I'm trying to create a new API based on generated openapi definition. When I upload it, I get an useless error information:

`OpenAPI content validation failed!`

It would be very useful to get more info about the reason that openapi spec is not valid since it doesn't seems to be invalid based on test I did in https://apitools.dev/swagger-parser/online/.

### Describe your solution

Show detailed information about the reason openapi spec is not valid.

### How will you implement it

Just show more info.

---

**Comment by tmkasun** [comment]
Hi @emiliobristech 

Thanks for bringing this up, The error information is right there in the REST API response

![image](https://user-images.githubusercontent.com/3313885/105819827-b8a2fd80-5fde-11eb-891f-903a802e8e91.png)

But we haven't pass/show that information to the portal users.

We could improve the current error message to include the available error details

I:e :
 
This is how it shows in Swagger Editor
![image](https://user-images.githubusercontent.com/3313885/105819888-cfe1eb00-5fde-11eb-976b-2883c1a32369.png)

**Comment by emiliobristech** [comment]
Hello, thank you for your response and suggestion! It would be great if any additional information comes with error message. In my particular case, what was happening is that I have generated openApi in Windows PowerShell, for an unknown reason, it was adding invisible characters to generated openapi spec file. In this case, a message such as "Invalid file format" or "Cannot read file" would be welcome. I had to create a new file copy and paste small parts of content to understant where the error was. In the end, the error was in file itself and solved creating new file with same content but I've lost couple of hours finding out what was wrong.

**Comment by emiliobristech** [comment]
Guys, I did some tests in v4.1.0 now, there is no message when open api spec is invalid. It deploys successfuly but API always returns 404. When I check logs, there are messages that indicates open apispec is invalid. As I use API Product, there is no additional information about which API is invalid.

This lack of feedback is really bad for usability since we don't know what is happening.

**Comment by tmkasun** [comment]
Hi @emiliobristech ,

In 4.1.0 we now have the following `Show errors` button which lists down all the OAS spec errors

![image](https://user-images.githubusercontent.com/3313885/174708397-3a46ea0a-08fd-4479-8fc0-80df40c89f36.png)

![image](https://user-images.githubusercontent.com/3313885/174708457-df43f7a3-3976-4c5d-86c7-01da1548ba23.png)

**Comment by Krishanx92** [comment]
With the latest release we include linter capability.
https://apim.docs.wso2.com/en/latest/design/advanced-topics/validate-api-definitions-with-linters/
