### ISSUE TITLE
Nested commenting feature

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9764]
### How will you implement it

---

**Comment by thisaltennakoon** [comment]
[Integration tests](https://github.com/wso2/product-apim/pull/10106)

**Comment by thisaltennakoon** [comment]
[Pagination for Nested Commenting & DBMS bug fixes](https://github.com/wso2/carbon-apimgt/pull/9975)

**Comment by thisaltennakoon** [comment]
#10106

**Comment by thisaltennakoon** [comment]
[Nested comment new tmkasun backup](https://github.com/wso2/carbon-apimgt/pull/9904)

**Comment by tmkasun** [comment]
[Documentation for nested commenting](https://github.com/wso2/docs-apim/pull/3267)

**Comment by thisaltennakoon** [comment]
#10261 https://github.com/wso2/product-apim/issues/10261

**Comment by thisaltennakoon** [comment]
https://github.com/wso2/product-apim/pull/10259

**Comment by thisaltennakoon** [comment]
[Integration Tests - Nested Commenting Feature](https://github.com/wso2/product-apim/pull/10259)

**Comment by thisaltennakoon** [comment]
[Changes requested by @malinthaprasan](https://github.com/wso2/carbon-apimgt/pull/10021)

**Comment by thisaltennakoon** [comment]
[Nested commenting feature - Migrations](https://github.com/wso2-extensions/apim-migration-resources/pull/92)

**Comment by thisaltennakoon** [comment]
[Integration testing for Pagination](https://github.com/wso2/product-apim/pull/10370)
