### ISSUE TITLE
Redundant API calls to get revisions

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9801]
We are making 2 API calls to get revisions, one in `APIDetailsTopMenue` and one in `Environments` component

![image](https://user-images.githubusercontent.com/3313885/105882311-82d83600-602b-11eb-84c9-8ebdc2f25125.png)

This is both redundant and error-prone and that's why we can't update the dropdown
![image](https://user-images.githubusercontent.com/3313885/105882435-a602e580-602b-11eb-93f4-e8194a9d9dcf.png)

when a new revision is created,
Shall we reduce this to 1 call ?

_Originally posted by @tmkasun in https://github.com/wso2/carbon-apimgt/pull/9614#r564703724_

**Comment by Krishanx92** [comment]
This will fixed with issue https://github.com/wso2/product-apim/issues/10436.
