### ISSUE TITLE
Improve error handling in create API from scratch form with revisions support

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9802]
In case of an error shouldn't we stop proceeding forward ?

![image](https://user-images.githubusercontent.com/3313885/105876059-93d17900-6024-11eb-93b4-b6b6e788f6cb.png)

I got the above error when I blocked the 

```
https://localhost:9443/api/am/publisher/v2/apis/*/revisions
``` 
and also got below error 

![image](https://user-images.githubusercontent.com/3313885/105876635-2a059f00-6025-11eb-96c5-0983e0ae04a9.png)

when I blocked the 

```
https://localhost:9443/api/am/publisher/v2/apis/*/deploy-revision
```

_Originally posted by @tmkasun in https://github.com/wso2/carbon-apimgt/pull/9614#r564667420_

**Comment by malinthaprasan** [comment]
This issue is most probably fixed with https://github.com/wso2/carbon-apimgt/pull/9961
Need to check and close.

**Comment by tmkasun** [comment]
Yes this is fixed now , Hence closing the issue.
