### ISSUE TITLE
[3.2.0] Revoked API Keys are Usable After Server Restart

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9811]
### Description:

Revoked API Keys are being valid after the Server restart. 
Please find the steps to reproduce the behavior below.

### Steps to reproduce:

1. Start the APIM 3.2.0 and log-in to the Publisher portal and publish an API with API Key enabled
2. Navigate to Devportal and subscribe to the API
3. Generate an API Key with long life
4. Invoke the API using the API Key
5. Revoke the API Key using the Devportal APIs
6. Restart the server
7. After a successful restart (soon after restart) invoke the API again using the same API Key (will give 401)
8. Wait for a few minutes for the Revoked Token clean up process and then invoke the API again (will be successful)

### Affected Product Version:

- APIM 3.2.0

**Comment by YasasRangika** [comment]
Closing as per the public fix has been added via: https://github.com/wso2/carbon-apimgt/pull/10104
