### ISSUE TITLE
User interaface issue in WSO2 API Manager 3.0 Devportal.

### ISSUE THREAD

**Issue by akurathimohan** [wso2/product-apim#9828]
### Description:
Applications are not showing in Application dropdown box on Developer Portal, when number of applications count greater than 24.
Please refer attached screenshot

![application](https://user-images.githubusercontent.com/10825796/106554554-a4608280-6541-11eb-8627-7a57ac182737.PNG)
 for same.

### Affected Product Version:
API Manager 3.0

**Comment by tharikaGitHub** [comment]
Hi @akurathimohan thank you for bringing this up. This issue is fixed in the latest versions of API Manager. We will be fixing this in 3.0.0 as well.

**Comment by tharikaGitHub** [comment]
Hi @akurathimohan this issue is fixed in the latest WUM updated pack in WSO2 API Manager 3.0.0. You can try this out taking the latest pack.

**Comment by tharikaGitHub** [comment]
Hi @akurathimohan I will close this issue as this is fixed now.
