### ISSUE TITLE
Spelling mistake in analytics 3.0.0 dashboard

### ISSUE THREAD

**Issue by kalevivek11** [wso2/product-apim#9829]
![AnalyticsBugSpellingIssue](https://user-images.githubusercontent.com/10954248/106555239-2e5d1b00-6543-11eb-9944-b9d9e8045d72.JPG)

**Comment by kalevivek11** [comment]
"Statstics" should be "statistics"

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
