### ISSUE TITLE
UI improvements in Store/Publisher portal

### ISSUE THREAD

**Issue by rizmir22** [wso2/product-apim#9831]
### Describe your solution

**Publisher**
1. No pagination button is generated in the Last Access time widget.
2. Not clear about the data points in the x-axis of the following widgets 
   * Created APIs Over Time
   * Applications Created Over time
   * Subscriptions Created Over Time.
   
**Store**
 No explanation of what statistics will be loaded by default when loading the API Usage per Application. It seems this widget is showing the data for the last 24 hours in the default view even though it's not mentioned in the document or the UI.

### How will you implement it

---
#### Suggested Labels:
APIM-Analytics

**Comment by HeshanSudarshana** [comment]
Closing the issue since it is fixed
