### ISSUE TITLE
Service Catalog API Issues

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9836]
### Description:
This is to keep track of service catalog REST API related issues.

**Comment by malinthaprasan** [comment]
Service Catalog - Delete service by UUID is not working.

What has been implemented is delete by serviceKey. This needs to support UUID.

**Comment by malinthaprasan** [comment]
Service Catalog - serviceKey parameter is not exposed

serviceKey parameter needs to be exposed in ServiceEntry DTO

{"id":"ad3e1603-4976-4bdf-b4c3-059be6be9359","name":"Swagger Petstore 1","displayName":"Petstore-Endpoint-1","description":"This is a sample server Petstore server","version":"1.0.0","serviceUrl":"https://127.0.0.1:9443/api/am/service/catalog/services","definitionType":"OAS3","securityType":"BASIC","mutualSSLEnabled":false,"usage":null,"createdTime":"2021-02-02 20:16:00.809","lastUpdatedTime":"2021-02-02 20:16:00.809","md5":"e2a249160f86a87decf1525cf9c67996d754f66047ebd8c2eb6863a0d6e83fed","definitionUrl":null}

**Comment by malinthaprasan** [comment]
Service Catalog - expose swagger.yaml from the REST API

swagger.yaml needs to be exposed in https://127.0.0.1:9443/api/am/service-catalog/{version}/swagger.yaml

Fix included in https://github.com/wso2/carbon-apimgt/pull/9683 without supporting anonymous mode.

**Comment by malinthaprasan** [comment]
Service Catalog - include version v0 in the resource path

Rename the service catalog rest api to api#am#service-catalog#v0.war and deploy so that it will accept  https://127.0.0.1:9443/api/am/service-catalog/v0/..

**Comment by malinthaprasan** [comment]
Service Catalog - support /services instead of /service-entries

/service-entries was used instead of /services due to the issue comes with CXF where it tries to do a service listing. Try to fix it by [disabling it](http://trabajosdesisifo.blogspot.com/2016/11/apache-cxf-hide-service-list.html).

**Comment by tmkasun** [comment]
In the list of services returned in `/service-entries` GET, Create time, display name, service URL, etc are missing (null), even though the data is visible/available in the service catalog database table

**Comment by malinthaprasan** [comment]
Service Catalog - DB column names inconsistency

ENTRY_NAME, ENTRY_VERSION, SERVICE_KEY column names are not consistent. Need to use consistent naming.

**Comment by vithu30** [comment]
Need to validate the service definition before adding the services.

**Comment by malinthaprasan** [comment]
**Handle API Import Export** 

When an API created using service is exported and imported, service references needs to be preserved. 
1. When API imported Service-Key entry needs to be added to the mapping table.
2. It might be a stale entry while Service is added
3. UX buttons needs to be disabled until service is available.

**Comment by Krishanx92** [comment]
https://github.com/wso2/product-apim/issues/10016

**Comment by malinthaprasan** [comment]
Closing since the feature is implemented. We can track individual issues using the label `Feature/ServiceCatalog`.
