### ISSUE TITLE
Service Catalog - Create time, display name, service URL, etc are missing (null) in listing, even though the data is available in DB

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9842]
In the list of services returned in `/service-entries` GET, Create time, display name, service URL, etc are missing (null), even though the data is visible/available in the service catalog database table

_Originally posted by @tmkasun in https://github.com/wso2/product-apim/issues/9836#issuecomment-771774759_

**Comment by vithu30** [comment]
This behavior is currently the default value for shrink is set as true - [1]. Shall we change the default value to `false`. That would resolve this issue.
