### ISSUE TITLE
Holder of Key Validation support for JWT access tokens

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#9853]
### Describe your problem(s)
Client A and Client B have two applications in APIM. Client A obtains a token T from APIM. Client B sends a request to access an API using the token T. This will not be failed with MTLS ( Since B also a valid client to APIM, his transport certificate is in APIM trust-store). 

HOK Mechanism suggests binding the transport certificate to the token. ( Introspection should return the hash value of transport cert). Then per each API call, we should validate the received transport cert against the transport cert bound to the token. 

When JWT access tokens are used with WSO2 API Manager, we can do this validation easily if the certificate hash is included in the JWT token itself. 

### Describe your solution
The specification regarding this feature is  [1]. According to  [1] Mutual TLS token binding has been used as the HoK mechanism. Once the token is bounded with the Mutual TLS cert, the hash of the certificate will be present in the following locations

 

Introspection Response (for opaque tokens) [2] 

 { "active": true,"iss": "https://server.example.com", "sub": "ty.webb@example.com", "exp": 1493726400, "nbf": 1493722800, "cnf":{ "x5t#S256": "bwcK0esc3ACC3DB2Y5_lESsXE8o9ltc05O89jdN-dg2" } } 
 

As a JWT claim (for JWT tokens)  [3] 

{ "iss": "https://server.example.com", "sub": "ty.webb@example.com", "exp": 1493726400, "nbf": 1493722800, "cnf":{ "x5t#S256": "bwcK0esc3ACC3DB2Y5_lESsXE8o9ltc05O89jdN-dg2" } }
 

 [1] https://tools.ietf.org/html/rfc8705

 [2] https://tools.ietf.org/html/rfc8705#section-3.2

[3]  https://tools.ietf.org/html/rfc8705#section-3.1

**Comment by isharac** [comment]
Duplicate with https://github.com/wso2/product-apim/issues/9821
