### ISSUE TITLE
[APIM-3.2.0] Authentication/Account recovery endpoints using external fonts

### ISSUE THREAD

**Issue by lkokila** [wso2/product-apim#9861]
### Describe your problem(s)
The following files contain the below import statement to extract fonts from fonts.googleapis.com.

`@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);`

'<HOME>/repository/deployment/server/jaggeryapps/admin/site/public/fonts/iconfont/README.md
'<HOME>/repository/deployment/server/jaggeryapps/devportal/site/public/fonts/iconfont/README.md
'<HOME>/repository/deployment/server/jaggeryapps/publisher/site/public/fonts/iconfont/README.md
'<HOME>/repository/deployment/server/webapps/accountrecoveryendpoint/libs/theme/wso2-default.css
'<HOME>/repository/deployment/server/webapps/accountrecoveryendpoint/libs/theme/wso2-default.min.css
'<HOME>/repository/deployment/server/webapps/authenticationendpoint/libs/theme/wso2-default.css
'<HOME>/repository/deployment/server/webapps/authenticationendpoint/libs/theme/wso2-default.min.css

The fonts are not extracted from the above API when the API-Manager is used in a private network. 

### Describe your solution
Embedding the fonts within the API-Manager server itself.

**Comment by Chamindu36** [comment]
This issue is fixed with https://github.com/wso2-support/identity-apps/pull/38. Hence, we can close this issue.
