### ISSUE TITLE
Sign backend JWT via Tenant Key Store Certificate 

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#9871]
### Describe your problem
With the new KM implementations in APIM v3.2.0, backend JWT is signed by only using default gateway certificate. No configuration to select tenant keystore certificates for JWT signing. 

### Describe your solution
Implement a configuration to enable the backend JWT is signed by the per tenant keystore certificate.

**Comment by dushaniw** [comment]
Needs to be frontported to master - in progress
