### ISSUE TITLE
[2.6.0] API Gateway Token Cache Clearance are not working for JWT Tokens

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9875]
### Description:

API GW Token Cache clearance is not working as expected when using JWT Tokens in APIM 2.6 with IS KM 5.7.0. The APIM supports the token cache clearance mechanism with the new Token Revocation notification in which the Opaque access tokens are working as expected and not the JWT tokens. 

Please find the reproducing steps below.

### Steps to reproduce:

1. Configure APIM 2.6 (latest WUM) with IS KM 5.7.0 and configure the servers with Token Revocation notification
2. Create and publish an API and subscribe to an Application
3. Configure the SP to generate JWT Tokens
4. Generate a JWT Access Token and invoke the API
5. Revoke the JWT Token using the IS KM Revoke endpoint (/oauth2/revoke)
6. Invoke the API again with the same JWT Token (gets a successful response)

### Affected Product Version:

- APIM 2.6

**Comment by RakhithaRR** [comment]
Closing this since ISKM use cases are not valid for newer versions.
