### ISSUE TITLE
Unable to change the application owner from Admin portal in APIM

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#9880]
### Description:
  Cannot change the owner of the application via admin console. (Update has not applied) But this is working in GA Pack.

### Affected Product Version:
3.2.0

**Comment by msm1992** [comment]
Fixed in master with https://github.com/wso2/carbon-apimgt/commit/43b4d04782ba1a835d165976dc627e4671d749da. Hence closing.
