### ISSUE TITLE
WSO2 apictl import-app fails "Error Importing Application"

### ISSUE THREAD

**Issue by akilamunasinghe** [wso2/product-apim#9883]
### Steps to reproduce:

- Env_1 and Env_2 have to have different users as user_1 and user2.
- apictl should be logged in with user_1 and user_2 respectively.
- Env_1 has API_1 and API_2
- Env_1 has APP_1 subscribed to both API_1 and API_2
- Env_2 has APP_1 created (same name as APP_1 in Env_1)
- Env_2 has no APIs
- Export API_1 from Env_1
- Import API_1 into Env_2
- Export APP_1 from Env_1
- Import APP_1 into Env_2
- Export API_2 from Env_1
- Import API_2 into Env_2
- Export APP_1 from Env_1
- Import APP_1 into Env_2  (Issue arises at this point, saying API_1 is already subscribed to APP_1 of Env_2)
- Ideally, the expectation is to update the subscriptions of APP_1 in Env_2

### Affected Product Version:
APIM 3.2

**Comment by YasasRangika** [comment]
Closing this issue because the scenario is not occurring in the way the latest code is handling the importing and exporting of APIs and applications. Therefore, closing this issue.
