### ISSUE TITLE
Enable or Disable API Detail Tabs in Developer Portal doesn't work in WSO2 APIM 3.2.0

### ISSUE THREAD

**Issue by dsmohan** [wso2/product-apim#9892]
Hi Team,

I tried to customize the API Detail Tabs in APIM Developer Portal 3.2.0 by following the documentation at "https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs/".

I edited the defaultTheme.js at "<API-M_HOME>/repository/deployment/server/jaggeryapps/devportal/site/public/theme/defaultTheme.js" as given in the document.
But on refreshing the page the changes are not visible. For e.g. I changed "showComments" and "showTryout" to "false" but the tabs are still visible on refreshing the page. I even restarted the APIM server and checked but the tabs are visible.

**Comment by dsmohan** [comment]
Its working on opening in new tab.

**Comment by tmkasun** [comment]
This type of `Theme not getting applied` can occur, due to network cache or simply if you do not reload the page
