### ISSUE TITLE
Don't Allow to create the API in the publisher portal through the user who had user name with 32 character or more in the APIM 3.2.0  

### ISSUE THREAD

**Issue by dumindurox777** [wso2/product-apim#9898]
In the APIM 3.2.0, when creating an API by using the Publisher UI user who has name with 33 characters(lalama.hlouatawara@bbhjesglencvfj.com), If exceed that  31characters  it shows a UI error as "Error while adding new API : null-sdfar-1.0.0 - Error while performing registry transaction operation" 
<img width="1243" alt="Screen Shot 2021-02-09 at 6 37 55 PM" src="https://user-images.githubusercontent.com/29389251/107368023-0868e500-6b06-11eb-8896-4decc632df86.png">

```
TID: [-1234] [api/am/publisher] [2021-02-08 09:30:01,564] ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO} - Failed to add resource to path /_system/governance/apimgt/applicationdata/provider/papama.hlouatawara@bbhjesglencvfj.com. String or binary data would be truncated in table 'DEV_APIM_SHARED_DB.dbo.REG_RESOURCE', column 'REG_CREATOR'. Truncated value: 'alexander.zaytsev@holmesglen.ed'. com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'DEV_APIM_SHARED_DB.dbo.REG_RESOURCE', column 'REG_CREATOR'. Truncated value: 'alexander.zaytsev@holmesglen.ed'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPre

```
The REG_CREATOR column in the REG_RESOURCE table has the following varchar length 31 defined and The REG_USER_ID column in the REG_LOG table has the following varchar length 31 defined.

increase that value length in the REG_CREATOR column in the REG_RESOURCE table and REG_USER_ID column in the REG_LOG table.

**Steps to reproduce:**
Up an APIM 3.2.0 pack
Create User wit length username which has more than 30 characters.(papama.hlouatawara@bbhjesglencvfj.com) 
Logging to the publisher UI and create the api
Affected Product Version:
APIM **3.2.0**

**Comment by HeshanSudarshana** [comment]
Closing the issue since it is fixed
