### ISSUE TITLE
Getting invalid expiry time in access tokens  

### ISSUE THREAD

**Issue by chaliya96** [wso2/product-apim#9909]
### Description:
When an access token is generated from HA-APIM setup through the different nodes, an invalid expiry time is getting in the access token if the other node has generated an access token for the same token request before. 
The issue behaviour is observed when the first time token request is sending through the other node and returning the expiry time as the original expiry time which should be reduced. But when the same request sends again the expiry time is returning correctly. 
### Steps to reproduce:

- Setup the APIM with HA by sharing the same DB between two nodes. 
- Generate Token via Node A 
- After 15s send the same token request via Node B -  The same token is received but the expiry time is not reduced and returned the original validity period
- After another 10s send the same token request via Node B - The same token requested is received with the correct expiry time.

### Affected Product Version:
v2.2.0

**Comment by msm1992** [comment]
Fixed in public branch with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1546. Hence closing.
