### ISSUE TITLE
Need to remove identity IDN_CORS_ORIGIN table unique index

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/product-apim#9914]
### Description:
When performing APIM 4.0- SNAPSHOT migration to IS 5.11 components IDN_CORS_ORIGIN table query doesn't get executed properly due to following issue https://github.com/wso2/product-is/issues/11159.

Once this is resolved, need to do the same fix to apim_db tables.

### Env:

mysql 8.x

**Comment by isharac** [comment]
Need to fix in the apim-is-migration-client repo

**Comment by HiranyaKavishani** [comment]
This is completed.
