### ISSUE TITLE
Need to support OTHER Key Manager Type

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#9923]
### Describe your problem(s)
Currently, APIM does not have a way to add another Key Manager (such as Azure) from the **Admin Portal**. This may lead to several problems. For example, when **Provisioning Out-of-Band OAuth2 Clients** [1] there isn't a proper way to do it when using any other Key Manager except the Key Managers listed in [2].

### Describe your solution
Introduce another type as OTHER for **Key Manager Type** to the section shown below, so that the users can use it to add another type such as Azure etc.
![image](https://user-images.githubusercontent.com/25246848/107647397-20c13700-6ca1-11eb-94f9-5e0c3eb6902a.png)

[1] https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/provisioning-out-of-band-oauth-clients/#step-2-provision-the-out-of-band-oauth2-client
[2] https://apim.docs.wso2.com/en/latest/administer/key-managers/overview/

**Comment by Krishanx92** [comment]
This is fixed with latest pack.
