### ISSUE TITLE
Add UNIQUE index in AM_API -> UUID column

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9930]
### Description:
We are using getAPIIdentifierFromUUID(String uuid) in APIUtil in many places. This uses
```
SELECT API_PROVIDER, API_NAME, API_VERSION FROM AM_API WHERE API_UUID = ?
```
This might get a performance impact as this has to scan through the whole AM_API table otherwise.

**Comment by malinthaprasan** [comment]
@isharac FYI

After completing the migration, let's add the constraint.

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/product-apim/issues/10552, hence closing.
