### ISSUE TITLE
Error When Trying to Add a New Role Permission

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim#9939]
### Description:
The Add new role permissions wizard produces the following error in UI when a role name is entered and "Next" button is clicked

![admin-scope-role-mapping-error](https://user-images.githubusercontent.com/30455603/107916146-d1725380-6f8b-11eb-9a0f-351388b13800.png)

### Steps to reproduce:
1. Login to Admin Portal and Go to "Role Permissions tab"
2. Click "Add role permission". The Add new role permissions wizard opens.
3. Enter a role name and click "Next". 

#### Suggested Labels:
APIM 4.0.0

**Comment by Krishanx92** [comment]
This cannot reproduce in latest pack.
