### ISSUE TITLE
Carbon-db oracle_rac script syntax error

### ISSUE THREAD

**Issue by harshanL** [wso2/product-apim#9951]
### Description:
The oracle_rac.sql script to create Shared_DB doesn't work due to a syntax issue (closing bracket at wrong place) in line 37. It should be corrected as below.
CREATE TABLE REG_PATH(
 REG_PATH_ID INTEGER NULL,
 REG_PATH_VALUE VARCHAR2(2000) NOT NULL,
 REG_PATH_PARENT_ID INTEGER,
 REG_TENANT_ID INTEGER DEFAULT 0,
 CONSTRAINT PK_PATH PRIMARY KEY(REG_PATH_ID, REG_TENANT_ID),
 CONSTRAINT UNIQUE_REG_PATH_TENANT_ID UNIQUE (REG_PATH_VALUE,REG_TENANT_ID))

### Affected Product Version:
apim-3.1.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
bug

**Comment by rmsamitha** [comment]
The related fix is added also in https://github.com/wso2/carbon-kernel/pull/2766/files#diff-2bc1c407a78bdc024533110391ab072108aa5e28b17d50601c350d32955a3309L37-R38

**Comment by malinthaprasan** [comment]
Reduced the priority due to issues with the setting up process. We'll take this up after beta..
