### ISSUE TITLE
Cannot add role-permission mapping from Dev portal ui

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-apim#9965]
### Description:
Adding a role permission in dev portal throws an error

<img width="1023" alt="err" src="https://user-images.githubusercontent.com/4861150/108190389-e4298b80-7137-11eb-89fb-0bc0730950d7.png">

### Steps to reproduce:
1. Go to Admin Portal and try to add a Role permission

### Affected Product Version:
APIM 4.0.0 M7

**Comment by wasuradananjith** [comment]
This is not reproducible anymore. Hence, closing this.
