### ISSUE TITLE
Service catalog REST API Improvements

### ISSUE THREAD

**Issue by Krishanx92** [wso2/product-apim#9988]
### Describe your problem(s)

-  Need settings API for service catalog.
-  Download service definition.
-  Need REST API for get usage of the services.
-  Need to get list of available service definitions versions.
-  Once re-import service definition API should updated.

**Comment by tharikaGitHub** [comment]
- Need functionality to deploy sample service for the Onboarding page

**Comment by vithu30** [comment]
> ### Describe your problem(s)
> 
>     * Need settings API for service catalog.
> 
>     * Download service definition.
> 
>     * Need REST API for get usage of the services.
> 
>     * Need to get list of available service definitions versions.
> 
>     * Once re-import service definition API should updated.

These are fixed by https://github.com/wso2/carbon-apimgt/pull/9877 and https://github.com/wso2/carbon-apimgt/pull/9884

**Comment by vithu30** [comment]
Related issue https://github.com/wso2/product-apim/issues/9836
