### ISSUE TITLE
Service Catalog - Handle API Import Export

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9998]
**Handle API Import Export** 

When an API created using service is exported and imported, service references needs to be preserved. 
1. When API imported Service-Key entry needs to be added to the mapping table.
2. It might be a stale entry while Service is added
3. UX buttons needs to be disabled until service is available.

_Originally posted by @malinthaprasan in https://github.com/wso2/product-apim/issues/9836#issuecomment-783860516_

**Comment by rmsamitha** [comment]
### Through the fix done:

- When API is imported while the service there already, the related mapping entry in the mapping table will be added with the corresponding MD5 value of the linked service.
The other-way round scenario (Service import after API import), is not resolved and will be tracked and fixed via #10714 .
- It was not required to disable and UX elements for this issue.
