### ISSUE TITLE
Endpoint synapse configurations are not getting update when saving the API Products

### ISSUE THREAD

**Issue by shagihan** [wso2/product-apim#9999]
### Description:
When API's are in created state and if an API product is being created and published using those api's. The changes made to the endpoints in those API's are not getting reflected in endpoint synapse config file.

### Steps to reproduce:
- Create several API's and keep remain in **created** state
- Create an API product using those API's.
- Publish the API Product.
- Make a change to an endpoint in one of the parent API and save it.
- Then save the API. Expected to update the endpoint synapse config.
- But Synapse file not getting update.

### Affected Product Version:
- 3.1.0
- 3.2.0

**Comment by tharikaGitHub** [comment]
Fixed in Public branch with https://github.com/wso2/carbon-apimgt/pull/9917
